### ISSUE TITLE
UNB upload failures on plinux

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10009]
Seen this twice today. The builds last night were fine.

https://ci.eclipse.org/openj9/job/Build_JDKnext_ppc64le_linux_Personal/43 - cent7-ppcle-5
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_Personal/941 - cent7-ppcle-5
```
15:41:52  [consumer_0] Deploying artifact: http://ub18p8art.casa.cs.unb.ca/artifactory/ci-eclipse-openj9/Build_JDK11_ppc64le_linux_Personal/941/OpenJ9-JDK11-ppc64le_linux-20200624-185154.tar.gz
15:41:52  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
15:41:53  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Build_JDK11_ppc64le_linux_Personal/941/OpenJ9-JDK11-ppc64le_linux-20200624-185154.tar.gz;build.parentNumber=2171;build.parentName=Pipeline_Build_Test_JDK11_ppc64le_linux;build.buildIdentifier=ibmruntimes/openj9-openjdk-jdk11%23320;build.timestamp=1593024707245;build.name=Build_JDK11_ppc64le_linux_Personal;build.number=941 HTTP/1.1: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
15:41:53  [consumer_0] An exception occurred during execution:
15:41:53  java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:41:53  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
15:41:53  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
15:41:53  	at java.lang.Thread.run(Thread.java:748)
15:41:53  Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:41:53  	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
15:41:53  	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
15:41:53  	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
15:41:53  	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
15:41:53  	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
15:41:53  	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
15:41:53  	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
15:41:53  	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
15:41:53  	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
15:41:53  	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
15:41:53  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
15:41:53  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
15:41:53  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
15:41:53  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
15:41:53  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
15:41:53  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
15:41:53  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
15:41:53  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
15:41:53  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
15:41:53  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
15:41:53  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
15:41:53  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
15:41:53  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
15:41:53  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
15:41:53  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:89)
15:41:53  	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:253)
15:41:53  	at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:249)
15:41:53  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:692)
15:41:53  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:379)
15:41:53  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:367)
15:41:53  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
15:41:53  	... 2 more
15:41:53  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:41:53  	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
15:41:53  	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
15:41:53  	at sun.security.validator.Validator.validate(Validator.java:262)
15:41:53  	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
15:41:53  	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
15:41:53  	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
15:41:53  	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
15:41:53  	... 28 more
15:41:53  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:41:53  	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
15:41:53  	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
15:41:53  	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
15:41:53  	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
15:41:53  	... 34 more
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
Looks like that machine hasn't accepted the cert for the server. I will follow up.

**Comment by pshipton** [comment]
It's not just cent7-ppcle-5. All the plinux OMR builds failed https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1999/

**Comment by pshipton** [comment]
Re-enabled cent7-ppcle-5

**Comment by AdamBrousseau** [comment]
Looks like the UNB Art cert isn't in the java keystore. Adding to machines now. From what I can tell, packages were last updated on
`Sun 08 Mar 2020 10:50:27 PM ADT`. If I look at the bash history (on cent7-1) I see that I originally imported it to java8-242. Today, default java on the machine is 252. We should probably make OpenJ9 jdk8 default and keep it static.

**Comment by AdamBrousseau** [comment]
I was looking at the update log wrong, but it still shows sdk 252 was added April 30 so I'm stumped why we're just hitting this now.
The nightly build passed
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64le_linux_Nightly/432/

I will open a follow up issue to change the default jdk to be OpenJ9 (which will also change the bootjdk8).

**Comment by AdamBrousseau** [comment]
Node 1 failed again. Joe had re-upgraded ca-certs after I had accepted the cert for 252. This upgrade must be clearing the keystore, at least for our custom entry because I had to re-add it again.

**Comment by pshipton** [comment]
Was resolved.
