### ISSUE TITLE
OpenJ9 JDK8 builds fail to run Apache Spark due to missing JAAS libraries

### ISSUE THREAD

**Issue by ymanton** [eclipse/openj9#1000]
Attempting to run Spark 2.2.1 results in the following exception on a Linux machine:

```
Exception in thread "main" java.io.IOException: failure to login
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:824)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2424)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2424)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2424)
        at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:220)
        at org.apache.spark.deploy.master.Master$.startRpcEnvAndEndpoint(Master.scala:1048)
        at org.apache.spark.deploy.master.Master$.main(Master.scala:1033)
        at org.apache.spark.deploy.master.Master.main(Master.scala)
Caused by: javax.security.auth.login.LoginException: java.lang.UnsatisfiedLinkError: jaas_unix (Not found in com.ibm.oti.vm.bootstrap.library.path)
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1435)
        at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1400)
        at java.lang.System.loadLibrary(System.java:567)
        at com.sun.security.auth.module.UnixSystem.<init>(UnixSystem.java:48)
        at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:125)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(AccessController.java:730)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:799)
        at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:761)
        at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:634)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2424)
        at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2424)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2424)
        at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:220)
        at org.apache.spark.deploy.master.Master$.startRpcEnvAndEndpoint(Master.scala:1048)
        at org.apache.spark.deploy.master.Master$.main(Master.scala:1033)
        at org.apache.spark.deploy.master.Master.main(Master.scala)
```

This is caused by a missing `libjaas_unix.so` that is not actually built as part of OpenJ9 JDK8.

**Comment by ymanton** [comment]
Seems like the lines that enable this library to be built in the OpenJ9-JDK8 makefiles were commented out (see ibmruntimes/openj9-openjdk-jdk8#29). Is there a specific reason why we're not building this library or is it just an oversight?

**Comment by pshipton** [comment]
I notice other libraries are also commented out: LIBJ2PCSC, LIBJ2GSS, LIBJ2PKCS11

**Comment by pshipton** [comment]
Added a blocker label to indicate this Issue is a blocker for the Eclipse OpenJ9 0.8 release.
