### ISSUE TITLE
aarch64 openjdk java/util/jar/JarFile/mrjar/MultiReleaseJarAPI.java cannot verify signature block file META-INF/SIGNER

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10033]
0.21.0 m2 build https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl_Personal/2
java/util/jar/JarFile/mrjar/MultiReleaseJarAPI.java
```
16:07:53  test MultiReleaseJarAPI.testAliasing(8, 8): failure
16:07:53  java.lang.SecurityException: cannot verify signature block file META-INF/SIGNER
16:07:53  	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:296)
16:07:53  	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:269)
16:07:53  	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
16:07:53  	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
16:07:53  	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:759)
16:07:53  	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:840)
16:07:53  	at MultiReleaseJarAPI.readAndCompare(MultiReleaseJarAPI.java:222)
16:07:53  	at MultiReleaseJarAPI.testAliasing(MultiReleaseJarAPI.java:213)
16:07:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:07:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:07:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:07:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:07:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
16:07:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
16:07:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
16:07:53  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
16:07:53  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
16:07:53  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
16:07:53  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
16:07:53  	at org.testng.TestRunner.run(TestRunner.java:623)
16:07:53  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
16:07:53  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
16:07:53  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
16:07:53  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
16:07:53  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:07:53  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
16:07:53  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
16:07:53  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
16:07:53  	at org.testng.TestNG.run(TestNG.java:1018)
16:07:53  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
16:07:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:07:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:07:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:07:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:07:53  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:07:53  	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
I have never seen this failure before.

**Comment by knn-k** [comment]
I wonder if this could be another case around hash value or not.
#9048 is a known intermittent failure with wrong hash value in jlink.
