### ISSUE TITLE
JTReg java/util/concurrent/Executors/AutoShutdown.java timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10048]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/104/
java/util/concurrent/Executors/AutoShutdown.java
Core file in job artifacts (until they are purged)
```
Timeout information:
Running jcmd on process 15237
Dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_15934865945599/jdk_util_j9_0/work/scratch/0/core.20200629.233816.15237.0001.dmp
Running jstack on process 15237
2020-06-29T23:38:23.177
Virtual machine: 15237 JVM information:
JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200629_431 (JIT enabled, AOT enabled)
OpenJ9   - 2914e1fa50f
OMR      - cb2a33376f1
JCL      - a3e59588fb9 based on jdk8u262-b08

"main" Id=1 WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:218)
	at java.lang.Thread.join(Thread.java:703)
	- locked java.lang.Thread@280ba081
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"JIT Compilation Thread-000" Id=2 RUNNABLE

"JIT Compilation Thread-001 Suspended" Id=3 RUNNABLE

"JIT Compilation Thread-002 Suspended" Id=4 RUNNABLE

"JIT Compilation Thread-003 Suspended" Id=5 RUNNABLE

"JIT Compilation Thread-004 Suspended" Id=6 RUNNABLE

"JIT Compilation Thread-005 Suspended" Id=7 RUNNABLE

"JIT Compilation Thread-006 Suspended" Id=8 RUNNABLE

"JIT Diagnostic Compilation Thread-007 Suspended" Id=9 RUNNABLE

"JIT-SamplerThread" Id=10 TIMED_WAITING

"IProfiler" Id=11 RUNNABLE

"Concurrent Mark Helper" Id=12 RUNNABLE

"GC Slave" Id=13 RUNNABLE

"GC Slave" Id=14 RUNNABLE

"GC Slave" Id=15 RUNNABLE

"Attach API wait loop" Id=18 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:953)
	at openj9.internal.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:140)
	at openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
	at openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)

"MainThread" Id=20 WAITING
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at AutoShutdown.tryWaitForFinalizersToRun(AutoShutdown.java:49)
	at AutoShutdown.realMain(AutoShutdown.java:69)
	at AutoShutdown.main(AutoShutdown.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)

"Finalizer thread" Id=23 RUNNABLE

"file lock watchdog" Id=25 TIMED_WAITING
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:218)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked java.util.TaskQueue@c1d169a8
	at java.util.TimerThread.run(Timer.java:505)

"Attachment 46286" Id=26 RUNNABLE
	at openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
	at openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:233)
	at openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$4/0000000000000000.apply(Unknown Source)
	at openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:169)
	at openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:239)
	at openj9.internal.tools.attach.target.Attachment.run(Attachment.java:150)


--- Timeout information end.
elapsed time (seconds): 969.452
```

**Comment by pshipton** [comment]
Given `AutoShutdown.tryWaitForFinalizersToRun`, looks like another finalization problem, possibly the same issue as https://github.com/eclipse/openj9/issues/9651
@andrewcraik fyi

**Comment by pshipton** [comment]
I'll close this as a dup of https://github.com/eclipse/openj9/issues/11899
