### ISSUE TITLE
jdk11: MathLoadTest_bigdecimal_0 : NPE VMAccess.addPackageToList()

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10063]
Testcase: MathLoadTest_bigdecimal_0
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_aarch64_linux/187/consoleFull
```
03:32:13  MLT java.lang.NullPointerException
03:32:13  MLT 	at java.base/java.lang.VMAccess.addPackageToList(VMAccess.java:183)
03:32:13  MLT 	at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1512)
03:32:13  MLT 	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
03:32:13  MLT 	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
03:32:13  MLT 	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
03:32:13  MLT 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
03:32:13  MLT 	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
03:32:13  MLT 	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
03:32:13  MLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
03:32:13  MLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:32:13  MLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:32:13  MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
03:32:13  MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
03:32:13  MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
03:32:13  MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
03:32:13  MLT 	at junit.framework.TestResult.run(TestResult.java:125)
03:32:13  MLT 	at junit.framework.TestCase.run(TestCase.java:129)
03:32:13  MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
03:32:13  MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
03:32:13  MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
03:32:13  MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
03:32:13  MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
03:32:13  MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
03:32:13  MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
03:32:13  MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
03:32:13  MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
03:32:13  MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
03:32:13  MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
03:32:13  MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
03:32:13  MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
03:32:13  MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
03:32:13  MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
03:32:13  MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
03:32:13  MLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
03:32:13  MLT 	at java.base/java.lang.Thread.run(Thread.java:836)
```

java -version
```
02:04:52  openjdk version "11.0.8" 2020-07-14
02:04:52  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+8-202007010020)
02:04:52  Eclipse OpenJ9 VM AdoptOpenJDK (build master-a955735ae, JRE 11 Linux aarch64-64-Bit Compressed References 20200701_401 (JIT enabled, AOT enabled)
02:04:52  OpenJ9   - a955735ae
02:04:52  OMR      - cb2a33376
02:04:52  JCL      - 933345df6a based on jdk-11.0.8+8)
```

Re-run succeeded.
So maybe intermittent.

**Comment by knn-k** [comment]
I don't think I have seen this failure before.

**Comment by knn-k** [comment]
I ran the test 20 times in my local environment, and got no failures.

**Comment by pshipton** [comment]
We can close this as a dup of https://github.com/eclipse/openj9/issues/8189
