### ISSUE TITLE
JDK16 HCRLateAttachWorkload_previewEnabled_0_FAILED : IllegalArgumentException: Unsupported class file major version 60

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10066]
Failure link
------------

From an internal build `Test_openjdkNext_j9_extended.system_ppc64_aix_Nightly/192`:
```
04:59:28  openjdk version "16-internal" 2021-03-16
04:59:28  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
04:59:28  Eclipse OpenJ9 VM (build master-a955735ae33, JRE 16 AIX ppc64-64-Bit Compressed References 20200630_266 (JIT enabled, AOT enabled)
04:59:28  OpenJ9   - a955735ae33
04:59:28  OMR      - 9e9c666540b
04:59:28  JCL      - 8ccead0563a based on jdk-16+3)
```

Optional info
-------------

- intermittent failure (no): 

Failure output (captured from console output)
---------------------------------------------

```
LT  Exception seen while transforming String.
LT  stderr Exception in thread "Attachment 53425" java.lang.reflect.InvocationTargetException
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
LT  stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 60
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 60
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
LT  stderr Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:70)
LT  stderr 	... 6 more
LT  stderr Agent failed to start!
LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
STF 05:28:34.270 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)

HCRLateAttachWorkload_previewEnabled_0_FAILED
```

07:31:08  For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
07:31:08  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=ppc64_aix&TARGET=HCRLateAttachWorkload_previewEnabled_0

**Comment by pshipton** [comment]
@JasonFengJ9 I think this has been resolved? I see extended system testing is passing.

**Comment by JasonFengJ9** [comment]
yup, it passes now.

closing.
