### ISSUE TITLE
JVM crash when combining JNI/Native + Thread

### ISSUE THREAD

**Issue by kakawait** [eclipse/openj9#10128]
Java -version output
--------------------

```
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10) 
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux amd64-64-Bit Compressed References 20200416_574 (JIT enabled, AOT enabled) 
OpenJ9 - 05fa2d361 
OMR - d4365f371 
JCL - 838028fc9d based on jdk-11.0.7+10) 
```

Summary of problem
------------------

I've TomEE java (AdoptOpenJDK + OpenJ9) app that crashing periodically (around 1 per day but it should be related to activity and maybe other triggers that I'm yet able to reproduce and isolate).
But crash seems to be related to _winning_ combo: `JNI (for calling native client)` + `Thread (for async)`.

There is no special error on application logs (`catalina.out`)

```
JVMDUMP039I Processing dump event "abort", detail "" at 2020/07/08 18:13:09 - please wait.
JVMDUMP032I JVM requested System dump using '/FILTERED_USER_DIR/core.20200708.181309.9433.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 3363 was not found. Expected to find core file with name "/mnt/core.bin.3363"
JVMDUMP032I JVM requested Java dump using '/FILTERED_USER_DIR/javacore.20200708.181309.9433.0002.txt' in response to an event
08-Jul-2020 18:13:15.380 WARNING [main] jdk.internal.reflect.NativeMethodAccessorImpl.invoke The socket listening for the shutdown command experienced an unexpected timeout [310,763,727] milliseconds after the call to accept(). Is this an instance of bug 56684?
java.net.SocketTimeoutException: Accept timed out
	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
	at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:609)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:721)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:667)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
JVMDUMP010I Java dump written to /FILTERED_USER_DIR/javacore.20200708.181309.9433.0002.txt
JVMDUMP032I JVM requested Snap dump using '/FILTERED_USER_DIR/Snap.20200708.181309.9433.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /FILTERED_USER_DIR/Snap.20200708.181309.9433.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/FILTERED_USER_DIR/jitdump.20200708.181309.9433.0004.dmp'
JVMDUMP010I JIT dump written to /FILTERED_USER_DIR/jitdump.20200708.181309.9433.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
```

I've checked that I've no thread leak (stable around ~200), nor `OutOfMemory`. Every metrics are stable and enougth free spaces for running (memory or disk space). And `open_file` seems to be ok too (but need more investigation for this metrics).

As you can see on log, `core.*.dump` is not available.

Diagnostic files
----------------

For privacy reason (but if committer is ok to help me, I can share more information outside github) I can't put `javacore`, `Snap`, nor `jitdump` inside issue.

I attached filtered version, I don't know if there is enough information

[javacore.filtered.txt](https://github.com/eclipse/openj9/files/4896356/javacore.filtered.txt)

**Comment by JasonFengJ9** [comment]
```
JVMDUMP032I JVM requested System dump using '/FILTERED_USER_DIR/core.20200708.181309.9433.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 3363 was not found. Expected to find core file with name "/mnt/core.bin.3363"
```
system core dump is most helpful in this kind of crash, could you check the settings such as `ulimit` if enough space is available?

**Comment by kakawait** [comment]
@JasonFengJ9 here our ulimit

```
NULL           type                            soft limit           hard limit
2CIUSERLIMIT   RLIMIT_AS                        unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CORE                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CPU                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_DATA                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_FSIZE                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_LOCKS                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_MEMLOCK                       65536                65536
2CIUSERLIMIT   RLIMIT_NOFILE                        65000                65000
2CIUSERLIMIT   RLIMIT_NPROC                          4096                63346
2CIUSERLIMIT   RLIMIT_RSS                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_STACK                       8388608            unlimited
2CIUSERLIMIT   RLIMIT_MSGQUEUE                     819200               819200
2CIUSERLIMIT   RLIMIT_NICE                              0                    0
2CIUSERLIMIT   RLIMIT_RTPRIO                            0                    0
2CIUSERLIMIT   RLIMIT_SIGPENDING                    63346                63346
```

And I didn't notice strange on our metrics. 

But btw if `abort` still `core.*.dump` is proceed?

**Comment by kakawait** [comment]
I've dump, I'll analyze and share information asap.

But we've made some other change to reduce scope of problem.

1. I removed thread/async usage, so even without additional thread (I mean only on current thread) I have the crash
2. Never reproduced on previous build `build openj9-0.18.0` (but was not the same code, is our previous release so I can't claim that is this new build `0.20.0` the problem)

**Comment by pshipton** [comment]
It might be worth trying the 0.21 milestone 2 build, in case the problem has been resolved. The 0.21.0 release should finalize next week.
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.8+8_openj9-0.21.0-m2

**Comment by kakawait** [comment]
@pshipton right after getting `core.dump` I contacted owner of native lib and seems to be a bug on their side.

So nothing related to OpenJ9

I'm currently re-testing with patched native code and I'm confident. Otherwise I'll try with `0.18.0` and `0.21.0`

Sorry for disturbing
