### ISSUE TITLE
JDK 15 : RecordReflectionTest.java IllegalArgumentException: Can not set final int field

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10148]
Failure link
------------

From an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/8`:
```
22:31:31  openjdk version "15-internal" 2020-09-15
22:31:31  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64lelinuxNightly)
22:31:31  Eclipse OpenJ9 VM (build master-d8cd2a6fb35, JRE 15 Linux ppc64le-64-Bit Compressed References 20200707_19 (JIT enabled, AOT enabled)
22:31:31  OpenJ9   - d8cd2a6fb35
22:31:31  OMR      - 281f29d31a6
22:31:31  JCL      - 8e963ae8ecc based on jdk-15+30)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:44:13  TEST: java/lang/reflect/records/RecordReflectionTest.java
22:44:13  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image

22:44:13  rerun:
22:44:13  cd /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/scratch/1 && \
22:44:13  DISPLAY=:1 \
22:44:13  HOME=/home/jenkins \
22:44:13  LANG=en_US.UTF-8 \
22:44:13  PATH=/bin:/usr/bin:/usr/sbin \
22:44:13      /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/javac \
22:44:13          -J-ea \
22:44:13          -J-esa \
22:44:13          -J-Xmx512m \
22:44:13          -J-Xdump:system:none \
22:44:13          -J-Xdump:heap:none \
22:44:13          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
22:44:13          -J-XX:-JITServerTechPreviewMessage \
22:44:13          -J-Djava.library.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
22:44:13          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage' \
22:44:13          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage' \
22:44:13          -J-Dtest.compiler.opts= \
22:44:13          -J-Dtest.java.opts= \
22:44:13          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
22:44:13          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
22:44:13          -J-Dtest.timeout.factor=8.0 \
22:44:13          -J-Dtest.nativepath=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
22:44:13          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
22:44:13          -J-Dtest.name=java/lang/reflect/records/RecordReflectionTest.java \
22:44:13          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records/RecordReflectionTest.java \
22:44:13          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records \
22:44:13          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records \
22:44:13          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/1/java/lang/reflect/records/RecordReflectionTest.d \
22:44:13          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/1/java/lang/reflect/records/RecordReflectionTest.d \
22:44:13          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/1/java/lang/reflect/records/RecordReflectionTest.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records \
22:44:13          -d /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/1/java/lang/reflect/records/RecordReflectionTest.d \
22:44:13          -sourcepath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records \
22:44:13          -classpath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/1/java/lang/reflect/records/RecordReflectionTest.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar \
22:44:13          --enable-preview \
22:44:13          -source 15 /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records/RecordReflectionTest.java
22:44:13  direct:
22:44:13  Note: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/records/RecordReflectionTest.java uses preview language features.
22:44:13  Note: Recompile with -Xlint:preview for details.

22:44:13  java.lang.IllegalArgumentException: Can not set final int field RecordReflectionTest$R2.i to null value
22:44:13  	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
22:44:13  	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
22:44:13  	at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.set(UnsafeQualifiedIntegerFieldAccessorImpl.java:82)
22:44:13  	at java.base/java.lang.reflect.Field.set(Field.java:793)
22:44:13  	at RecordReflectionTest.testReadOnlyFieldInRecord(RecordReflectionTest.java:199)
22:44:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:44:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:44:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:44:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:44:13  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:44:13  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:44:13  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:44:13  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
22:44:13  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
22:44:13  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
22:44:13  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
22:44:13  	at org.testng.TestRunner.run(TestRunner.java:623)
22:44:13  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
22:44:13  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
22:44:13  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
22:44:13  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
22:44:13  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
22:44:13  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
22:44:13  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
22:44:13  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
22:44:13  	at org.testng.TestNG.run(TestNG.java:1018)
22:44:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:44:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:44:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:44:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:44:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:44:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:44:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:44:13  	at java.base/java.lang.Thread.run(Thread.java:851)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:07:59  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_lang_j9_0

**Comment by pshipton** [comment]
Looks resolved now.
