### ISSUE TITLE
JDK 15 : TEST: java/lang/reflect/Field/Set.java `main' threw exception: java.lang.Throwable: Test for Field.set FAILED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10146]
Failure link
------------

From an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/8`:
```
22:31:31  openjdk version "15-internal" 2020-09-15
22:31:31  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64lelinuxNightly)
22:31:31  Eclipse OpenJ9 VM (build master-d8cd2a6fb35, JRE 15 Linux ppc64le-64-Bit Compressed References 20200707_19 (JIT enabled, AOT enabled)
22:31:31  OpenJ9   - d8cd2a6fb35
22:31:31  OMR      - 281f29d31a6
22:31:31  JCL      - 8e963ae8ecc based on jdk-15+30)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:41:00  --------------------------------------------------
22:44:09  TEST: java/lang/reflect/Field/Set.java
22:44:09  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image
22:44:09  
22:44:09  ACTION: build -- Passed. Build successful
22:44:09  REASON: Named class compiled on demand
22:44:09  TIME:   0.031 seconds
22:44:09  messages:
22:44:09  command: build Set
22:44:09  reason: Named class compiled on demand
22:44:09  Test directory:
22:44:09    compile: Set
22:44:09  elapsed time (seconds): 0.031
22:44:09  
22:44:09  ACTION: compile -- Passed. Compilation successful
22:44:09  REASON: .class file out of date or does not exist
22:44:09  TIME:   0.03 seconds
22:44:09  messages:
22:44:09  command: compile /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field/Set.java
22:44:09  reason: .class file out of date or does not exist
22:44:09  Mode: agentvm
22:44:09  Agent id: 4
22:44:09  elapsed time (seconds): 0.03
22:44:09  configuration:
22:44:09  Boot Layer (javac runtime environment)
22:44:09    class path: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar 
22:44:09                /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar 
22:44:09    patch:      java.base /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/patches/java.base
22:44:09  
22:44:09  javac compilation environment
22:44:09    source path: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field
22:44:09    class path:  /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field
22:44:09                 /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d
22:44:09  
22:44:09  rerun:
22:44:09  cd /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/scratch/0 && \
22:44:09  DISPLAY=:1 \
22:44:09  HOME=/home/jenkins \
22:44:09  LANG=en_US.UTF-8 \
22:44:09  PATH=/bin:/usr/bin:/usr/sbin \
22:44:09      /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/javac \
22:44:09          -J-ea \
22:44:09          -J-esa \
22:44:09          -J-Xmx512m \
22:44:09          -J-Xdump:system:none \
22:44:09          -J-Xdump:heap:none \
22:44:09          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
22:44:09          -J-XX:-JITServerTechPreviewMessage \
22:44:09          -J-Djava.library.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
22:44:09          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage' \
22:44:09          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage' \
22:44:09          -J-Dtest.compiler.opts= \
22:44:09          -J-Dtest.java.opts= \
22:44:09          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
22:44:09          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
22:44:09          -J-Dtest.timeout.factor=8.0 \
22:44:09          -J-Dtest.nativepath=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
22:44:09          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
22:44:09          -J-Dtest.name=java/lang/reflect/Field/Set.java \
22:44:09          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field/Set.java \
22:44:09          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field \
22:44:09          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field \
22:44:09          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d \
22:44:09          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d \
22:44:09          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field \
22:44:09          -d /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d \
22:44:09          -sourcepath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field \
22:44:09          -classpath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_lang_j9_0/work/classes/0/java/lang/reflect/Field/Set.d /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/reflect/Field/Set.java
22:44:09  
22:44:09  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Throwable: Test for Field.set FAILED

22:44:09  STDOUT:
22:44:09  setInt() did not work for static
22:44:09  FAILED: testAccessibleStaticPrimitive()
22:44:09  FAILED: testAccessibleStaticObject()
22:44:09  STDERR:
22:44:09  java.lang.Throwable: Test for Field.set FAILED
22:44:09  	at Set.main(Set.java:74)
22:44:09  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:44:09  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:44:09  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:44:09  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:44:09  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
22:44:09  	at java.base/java.lang.Thread.run(Thread.java:851)
22:44:09  
22:44:09  JavaTest Message: Test threw exception: java.lang.Throwable
22:44:09  JavaTest Message: shutting down test
22:44:09  
22:44:09  
22:44:09  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Throwable: Test for Field.set FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:07:59  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_lang_j9_0

**Comment by pshipton** [comment]
Looks resolved.
