### ISSUE TITLE
AArch64: Test failure with Cipher/AEAD/GCMLargeDataKAT

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#10141]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/154/consoleText

Optional info
-------------

- intermittent failure: yes
- regression or new test: regression
- if regression, what are the last passing public SHAs: OpenJ9 - 5daf4597c / OMR - 2e7b141e2 / JCL - 4983461e55 based on jdk-11.0.8+8)

Failure output (captured from console output)
---------------------------------------------

```
[2020-07-10T02:31:37.973Z] TEST: com/sun/crypto/provider/Cipher/AEAD/GCMLargeDataKAT.java

[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 65537 	Result: Fail
[2020-07-10T02:31:37.974Z] 	Expected: e7dfca4a71495c65d20982c3c9b9813f
[2020-07-10T02:31:37.974Z] 	Returned: 6de64eb761e46290d1572d6c16d6596b
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 67585 	Result: Fail
[2020-07-10T02:31:37.974Z] 	Expected: 1d21b42d80ea179810744fc23dc228b6
[2020-07-10T02:31:37.974Z] 	Returned: 32cd8f8ab5b8aa17176bfe1d9994672b
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102401 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102401 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 65536 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 65536 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 67584 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 67584 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102400 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102400 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102403 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102403 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102402 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102402 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102405 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102405 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102404 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102404 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102407 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102407 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102406 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102406 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102409 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102409 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102408 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102408 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102411 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102411 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102410 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102410 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102413 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102413 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102412 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102412 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102415 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102415 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102414 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102414 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 102416 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 102416 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 65534 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 65534 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 67583 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 67583 	Result: Pass
[2020-07-10T02:31:37.974Z] ---------------------------------------------
[2020-07-10T02:31:37.974Z] Encrypt data size 65535 	Result: Pass
[2020-07-10T02:31:37.974Z] Decrypt data size 65535 	Result: Pass
[2020-07-10T02:31:37.974Z] STDERR:
[2020-07-10T02:31:37.974Z] java.lang.Exception: Tests failed
[2020-07-10T02:31:37.974Z] 	at GCMLargeDataKAT.test(GCMLargeDataKAT.java:189)
[2020-07-10T02:31:37.974Z] 	at GCMLargeDataKAT.main(GCMLargeDataKAT.java:210)
[2020-07-10T02:31:37.974Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-07-10T02:31:37.974Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-07-10T02:31:37.974Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-07-10T02:31:37.974Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-07-10T02:31:37.974Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2020-07-10T02:31:37.974Z] 	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by knn-k** [comment]
This test compares the hash value from `MessageDigest.getInstance("MD5").digest(data)`.

**Comment by knn-k** [comment]
These failures were caused by https://github.com/eclipse/omr/pull/5366.
I opened https://github.com/eclipse/omr/pull/5428 to fix it.

**Comment by knn-k** [comment]
I posted a comment in this Issue by mistake minutes ago, which should have been posted to #10254.

**Comment by knn-k** [comment]
Closing this as a dup of #11901.
