### ISSUE TITLE
AIX JDK15 NoClassDefFoundError: sun.java2d.Disposer (initialization failure) due to UnsatisfiedLinkError: j2sdk-image/lib/libawt_xawt.so (	0509-022 Cannot load module j2sdk-image/lib/liba.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10173]
Failure link
------------

From an internal build `Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/8`:
```
02:03:55  openjdk version "15-internal" 2020-09-15
02:03:55  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64aixNightly)
02:03:55  Eclipse OpenJ9 VM (build master-123825b18b3, JRE 15 AIX ppc64-64-Bit Compressed References 20200713_19 (JIT enabled, AOT enabled)
02:03:55  OpenJ9   - 123825b18b3
02:03:55  OMR      - 19153e91d16
02:03:55  JCL      - ede7a69a235 based on jdk-15+30)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
    [echo] Running the DDR Extension Test
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: sun.java2d.Disposer (initialization failure)
     [java] 	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:136)
     [java] 	at java.desktop/javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
     [java] 	at java.desktop/javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
     [java] 	at com.ibm.j9ddr.corereaders.CoreReader.getFileHeader(CoreReader.java:193)
     [java] 	at com.ibm.j9ddr.corereaders.elf.ELFDumpReaderFactory.testDump(ELFDumpReaderFactory.java:57)
     [java] 	at com.ibm.j9ddr.corereaders.CoreReader.readCoreFile(CoreReader.java:105)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.locateRuntimes(DDRInteractive.java:366)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.<init>(DDRInteractive.java:273)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.<init>(DDRInteractive.java:258)
     [java] 	at j9vm.test.ddrext.SetupConfig.initDDRInteractive(SetupConfig.java:72)
     [java] 	at j9vm.test.ddrext.SetupConfig.init(SetupConfig.java:112)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:216)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] Caused by: java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/lib/libawt_xawt.so (	0509-022 Cannot load module /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/lib/liba.
     [java] 	0509-150   Dependent module /opt/freeware/lib/libXrender.a(shr_64.o) could not be loaded.
     [java] 	0509-152   Member shr_64.o is not found in archive 
     [java] 	0509-022 Cannot load module /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/lib/liba.
     [java] 	0509-150   Dependent module /home/jenkins/workspace/Te)
     [java] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1745)
     [java] 	at java.base/java.lang.System.load(System.java:578)
     [java] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(Native Method)
     [java] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1719)
     [java] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1692)
     [java] 	at java.base/java.lang.System.loadLibrary(System.java:591)
     [java] 	at java.desktop/sun.java2d.Disposer$1.run(Disposer.java:67)
     [java] 	at java.desktop/sun.java2d.Disposer$1.run(Disposer.java:65)
     [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
     [java] 	at java.desktop/sun.java2d.Disposer.<clinit>(Disposer.java:64)
     [java] 	at java.desktop/javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
     [java] 	at java.desktop/javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:73)
     [java] 	at com.ibm.j9ddr.corereaders.CoreReader.getFileHeader(CoreReader.java:193)
     [java] 	at com.ibm.j9ddr.corereaders.minidump.MiniDumpReader.testDump(MiniDumpReader.java:165)
     [java] 	... 8 more
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
03:15:56  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=testDDRExt_General_openj9_0

**Comment by pshipton** [comment]
Looks like a machine problem.
