### ISSUE TITLE
openjdk java/util/Arrays/Correct failed!

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10170]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl_Release/8
java/util/Arrays/Correct.java
```
00:54:13  java.lang.RuntimeException: failed!
00:54:13  	at Correct.main(Correct.java:49)
00:54:13  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:54:13  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:54:13  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:54:13  	at java.lang.reflect.Method.invoke(Method.java:498)
00:54:13  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:54:13  	at java.lang.Thread.run(Thread.java:823)
00:54:13  
00:54:13  JavaTest Message: Test threw exception: java.lang.RuntimeException
00:54:13  JavaTest Message: shutting down test
00:54:13  
00:54:13  
00:54:13  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: failed!
00:54:13  --------------------------------------------------
00:59:40  Test results: passed: 646; failed: 1
```

**Comment by pshipton** [comment]
20x grinder https://ci.eclipse.org/openj9/job/Grinder/972/

**Comment by pshipton** [comment]
@fjeremic fyi

**Comment by fjeremic** [comment]
0/160 repro rate. We will keep an eye if it starts occurring more often.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/184
```
22:57:26  STDERR:
22:57:26  java.lang.RuntimeException: failed!
22:57:26  	at Correct.main(Correct.java:50)
22:57:26  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:57:26  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:57:26  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:57:26  	at java.lang.reflect.Method.invoke(Method.java:498)
22:57:26  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
22:57:26  	at java.lang.Thread.run(Thread.java:823)
```
```
            Arrays.sort(array1, array1.length/3, array1.length/2);
            stupidSort(array2, array2.length/3, array2.length/2);
            if(!Arrays.equals(array1, array2))
                throw new RuntimeException("failed!");
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Release_testList_1/10/
jdk_util_0
java/util/Arrays/Correct.java
```
20:53:41  java.lang.RuntimeException: failed!
20:53:41  	at Correct.main(Correct.java:50)
```
