### ISSUE TITLE
JDK8 Windows MauveMultiThreadLoadTest_special_17 - Uncaught exception:  java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10179]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Release_mauveLoadTest/6/tapResults/
```
23:43:04  openjdk version "1.8.0_262-internal"
23:43:04  OpenJDK Runtime Environment (build 1.8.0_262-internal-****_2020_07_14_21_30-b00)
23:43:04  Eclipse OpenJ9 VM (build v0.21.0-release-34cf4c07578, JRE 1.8.0 Windows Server 2012 R2 amd64-64-Bit Compressed References 20200714_41 (JIT enabled, AOT enabled)
23:43:04  OpenJ9   - 34cf4c07578
23:43:04  OMR      - 113e5421922
23:43:04  JCL      - 257cb216141 based on jdk8u262-b10)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:56:50  LT  22:56:50.031 - Starting thread. Suite=0 thread=6
23:57:04  LT  03:57:02.737 - First failure detected by thread: load-5. Not creating dumps as no dump generation is requested for this load test
23:57:33  LT  03:57:04.103 - Uncaught exception: 
23:57:33  LT  java.lang.StackOverflowError: null
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:509) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTraceHelper(Throwable.java:338) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:307) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:250) ~[?:1.8.0_262-internal]
23:57:33  LT  	at net.adoptopenjdk.loadTest.reporting.OutputFilter.write(OutputFilter.java:60) ~[bin/:?]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.BufferedWriter.write(BufferedWriter.java:230) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.Writer.write(Writer.java:157) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.write(PrintStream.java:525) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.append(PrintStream.java:1065) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.append(PrintStream.java:57) ~[?:1.8.0_262-internal]
23:57:33  LT  	at com.ibm.oti.util.Util.appendTo(Util.java:225) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:545) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTraceHelper(Throwable.java:338) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:307) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:250) ~[?:1.8.0_262-internal]
23:57:33  LT  	at net.adoptopenjdk.loadTest.reporting.OutputFilter.write(OutputFilter.java:60) ~[bin/:?]
...
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:545) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTraceHelper(Throwable.java:338) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:307) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:250) ~[?:1.8.0_262-internal]
23:57:33  LT  	at net.adoptopenjdk.loadTest.reporting.OutputFilter.write(OutputFilter.java:60) ~[bin/:?]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.write(PrintStream.java:526) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.append(PrintStream.java:1065) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.append(PrintStream.java:57) ~[?:1.8.0_262-internal]
23:57:33  LT  	at com.ibm.oti.util.Util.appendTo(Util.java:225) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:545) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTraceHelper(Throwable.java:338) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:307) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Throwable.printStackTrace(Throwable.java:250) ~[?:1.8.0_262-internal]
23:57:33  LT  	at net.adoptopenjdk.loadTest.reporting.OutputFilter.write(OutputFilter.java:60) ~[bin/:?]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282) ~[?:1.8.0_262-internal]
23:57:33  LT  	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.write(PrintStream.java:526) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.print(PrintStream.java:669) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.io.PrintStream.println(PrintStream.java:806) ~[?:1.8.0_262-internal]
23:57:33  LT  	at net.adoptopenjdk.loadTest.reporting.ExecutionTracker.recordTestFailure(ExecutionTracker.java:161) ~[bin/:?]
23:57:33  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:232) ~[bin/:?]
23:57:33  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_262-internal]
23:57:33  LT  	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_262-internal]
23:57:33  LT  22:57:31.691 - Completed 0.1%. Number of tests started=519
```
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
00:27:38  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/mauveLoadTest&PLATFORM=x86-64_windows&TARGET=MauveMultiThreadLoadTest_special_17

**Comment by pshipton** [comment]
This is likely a dup of https://github.com/eclipse/openj9/issues/8204. The StackOverflow has already been addressed via https://github.com/AdoptOpenJDK/stf/pull/84. The build pre-dates the fix.
