### ISSUE TITLE
TestJstack_0 test.property missing expected

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10198]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_xl_Nightly_testList_1/47
TestJstack_0
```
FAILED: testProperties
java.lang.AssertionError: test.property missing expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJstack.testProperties(TestJstack.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by Mesbah-Alam** [comment]
This failure is seen on IBM Semeru Open January 2022 - AIX P10 manual testing too, while running `extended.functional` :   https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/20619: 

```
[2022-02-02T18:42:16.740Z] ===============================================
[2022-02-02T18:42:16.740Z] Running test TestJstack_SE80_0 ...
[2022-02-02T18:42:16.740Z] ===============================================
[2022-02-02T18:42:16.740Z] TestJstack_SE80_0 Start Time: Wed Feb  2 13:42:16 2022 Epoch Time (ms): 1643827336417
[2022-02-02T18:42:16.740Z] "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2022-02-02T18:42:16.740Z] JVMSHRC005I No shared class caches available
[2022-02-02T18:42:16.740Z] JVMSHRC005I No shared class caches available
[2022-02-02T18:42:16.740Z] cache cleanup done
[2022-02-02T18:42:16.740Z] variation: NoOptions
[2022-02-02T18:42:16.740Z] JVM_OPTIONS:  
[2022-02-02T18:42:16.740Z] { itercnt=1; \
[2022-02-02T18:42:16.740Z] mkdir -p "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_16438241052375/TestJstack_SE80_0"; \
[2022-02-02T18:42:16.740Z] cd "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_16438241052375/TestJstack_SE80_0"; \
[2022-02-02T18:42:16.740Z] "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"   \
[2022-02-02T18:42:16.740Z] -cp "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
[2022-02-02T18:42:16.740Z] -Dcom.ibm.tools.attach.enable=yes \
[2022-02-02T18:42:16.740Z] -Djdk.attach.allowAttachSelf=true \
[2022-02-02T18:42:16.740Z] -Dcom.ibm.tools.attach.timeout=15000 \
[2022-02-02T18:42:16.740Z] org.testng.TestNG -d "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_16438241052375/TestJstack_SE80_0" "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestJstack \
[2022-02-02T18:42:16.740Z] -groups level.extended \
[2022-02-02T18:42:16.740Z] -excludegroups d.*.aix_ppc-64,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all; \
[2022-02-02T18:42:16.740Z] if [ $? -eq 0 ] ; then echo ""; echo "TestJstack_SE80_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_16438241052375/TestJstack_SE80_0"; else echo ""; echo "TestJstack_SE80_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_16438241052375/TestTargetResult";
[2022-02-02T18:42:17.492Z] [IncludeExcludeTestAnnotationTransformer] [INFO] EXCLUDE_FILE environment variable: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
[2022-02-02T18:42:17.492Z] [IncludeExcludeTestAnnotationTransformer] [INFO] Processing exclude file: /home/jenkins/workspace/Grinder/aqa-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
[2022-02-02T18:42:17.492Z] ...
[2022-02-02T18:42:17.492Z] ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
[2022-02-02T18:42:17.492Z] ...
[2022-02-02T18:42:17.492Z] 
[2022-02-02T18:42:18.764Z] FAILED: testProperties
[2022-02-02T18:42:18.764Z] java.lang.AssertionError: test.property missing expected [true] but found [false]
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.fail(Assert.java:96)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.assertTrue(Assert.java:44)
[2022-02-02T18:42:18.764Z] 	at org.openj9.test.attachAPI.TestJstack.testProperties(TestJstack.java:103)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-02-02T18:42:18.764Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] FAILED: testRemote
[2022-02-02T18:42:18.764Z] java.lang.AssertionError: Method name missing expected [true] but found [false]
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.fail(Assert.java:96)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.assertTrue(Assert.java:44)
[2022-02-02T18:42:18.764Z] 	at org.openj9.test.attachAPI.TestJstack.testRemote(TestJstack.java:65)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-02-02T18:42:18.764Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] FAILED: testSynchronizers
[2022-02-02T18:42:18.764Z] java.lang.AssertionError: Method name missing expected [true] but found [false]
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.fail(Assert.java:96)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2022-02-02T18:42:18.764Z] 	at org.testng.Assert.assertTrue(Assert.java:44)
[2022-02-02T18:42:18.764Z] 	at org.openj9.test.attachAPI.TestJstack.testSynchronizers(TestJstack.java:82)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-02-02T18:42:18.764Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-02-02T18:42:18.764Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2022-02-02T18:42:18.764Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2022-02-02T18:42:18.764Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2022-02-02T18:42:18.764Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] ===============================================
[2022-02-02T18:42:18.764Z]     TestJstack
[2022-02-02T18:42:18.764Z]     Tests run: 3, Failures: 3, Skips: 0
[2022-02-02T18:42:18.764Z] ===============================================
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] ===============================================
[2022-02-02T18:42:18.764Z] GeneralTest suite
[2022-02-02T18:42:18.764Z] Total tests run: 3, Failures: 3, Skips: 0
[2022-02-02T18:42:18.764Z] ===============================================
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] 
[2022-02-02T18:42:18.764Z] TestJstack_SE80_0_FAILED
```

**SDK version:** 

```
[2022-02-02T17:42:22.340Z] openjdk version "1.8.0_322-internal"
[2022-02-02T17:42:22.340Z] OpenJDK Runtime Environment (build 1.8.0_322-internal-jenkins_2022_01_22_23_55-b00)
[2022-02-02T17:42:22.340Z] Eclipse OpenJ9 VM (build openj9-0.30.0-rc1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20220122_25 (JIT enabled, AOT enabled)
[2022-02-02T17:42:22.340Z] OpenJ9   - f441547b87f
[2022-02-02T17:42:22.340Z] OMR      - dac962a283a
[2022-02-02T17:42:22.340Z] JCL      - 3273d1d5e1e based on jdk8u322-b06)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_aarch64_mac_Nightly_testList_1/187
TestJstack_0
```
FAILED: testProperties
java.lang.AssertionError: test.property missing expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJstack.testProperties(TestJstack.java:103)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/1043
