### ISSUE TITLE
OpenJ9 cannot build android project (again)

### ISSUE THREAD

**Issue by Unpublished** [eclipse/openj9#10223]
Java -version output
--------------------

```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200715_715 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 4fe4692246 based on jdk8u262-b10)
```

Summary of problem
------------------

Building a fresh android project fails.

Steps to reproduce:
1. Download https://github.com/Unpublished/OpenJ9_android_example
2. Execute `./gradlew assembleRelease`

Output with OpenJ9:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > wrong number of arguments
   > KotlinJvmAndroidCompilation with name 'debugAndroidTest' not found.
```

Output with Hotspot:
```
BUILD SUCCESSFUL in 1m 18s
24 actionable tasks: 24 executed
```

A demo repo including `./gradlew assembleRelease --stacktrace` output can be found here:
https://github.com/Unpublished/OpenJ9_android_example/actions/runs/178702350

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by JasonFengJ9** [comment]
The example produces following exception stacktrace:
```
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
        at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler.getJavaTask(Android25ProjectHandler.kt:108)
        at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler.preprocessVariant(KotlinPlugin.kt:920)
        at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler.access$preprocessVariant(KotlinPlugin.kt:711)
        at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$configureTarget$3.invoke(KotlinPlugin.kt:799)
        at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$configureTarget$3.invoke(KotlinPlugin.kt:711)
        at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandlerKt$sam$org_gradle_api_Action$0.execute(Android25ProjectHandler.kt)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
        at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:225)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:253)
        at com.android.build.gradle.internal.ApiObjectFactory.create(ApiObjectFactory.java:96)
        at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.java:681)
        at com.android.build.gradle.internal.plugins.BasePlugin$$Lambda$279/0000000000000000.call(Unknown Source)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:82)
        at com.android.build.gradle.internal.plugins.BasePlugin.lambda$createTasks$4(BasePlugin.java:582)
        at com.android.build.gradle.internal.plugins.BasePlugin$$Lambda$262/0000000000000000.accept(Unknown Source)
        at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
        at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:152)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$$Lambda$278/0000000000000000.run(Unknown Source)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:92)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 124 more
```

This appears a mismatch of the `kotlin-gradle-plugin` and `gradle`.
`org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler.getJavaTask(Android25ProjectHandler.kt:108)` [1] expects `org.gradle.api.internal.provider.AbstractMinimalProvider.get(org.gradle.internal.DisplayName)` [2] which exists in just a few versions between [3] and [4], the earlier and later versions don't require the parameter `org.gradle.internal.DisplayName`.

An earlier plugin with `classpath "com.android.tools.build:gradle:3.5.0"` works with the same `OpenJ9 JDK8` (no newer `gradle` plugin available including `AbstractMinimalProvider.get()` yet).

In addition, it seems `hotspot VM` goes different code path without hitting `Android25ProjectHandler.getJavaTask()` hence no `java.lang.IllegalArgumentException` thrown.

[1] https://github.com/JetBrains/kotlin/blob/6d6a228057576470682dfb74161ad642cd882bbb/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/android/Android25ProjectHandler.kt#L99-L107
[2] https://github.com/gradle/gradle/blob/e2334a037a77faa8b28f3425322f9a632c5b1fb6/subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractMinimalProvider.java#L51-L53
[3] https://github.com/gradle/gradle/commit/e2334a037a77faa8b28f3425322f9a632c5b1fb6#diff-43bb3970dbe66d70b22157d9808b7b16
[4] https://github.com/gradle/gradle/blob/f386cf5bd39dbcc3ca737e51c424ecc41f320b4f/subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractMinimalProvider.java

**Comment by Unpublished** [comment]
Thanks for your in-depth analysis @JasonFengJ9.

Updating gradle to at least [6.2](https://github.com/gradle/gradle/releases/tag/v6.2.0)  also fixes the build.

Should the difference in code execution path still be tracked?

**Comment by DanHeidinga** [comment]
Moving this out to the Oct quarterly release as it's not java 15 specific and there's a work around - use a newer gradle

**Comment by JasonFengJ9** [comment]
> In addition, it seems hotspot VM goes different code path without hitting Android25ProjectHandler.getJavaTask() hence no java.lang.IllegalArgumentException thrown.

Sorry for lack of progress here, due to other workitem I wasn't able to figure out why `HotSpot` took different code path yet. The initial failure has been determined that it was a mismatching of `kotlin-gradle-plugin` and `gradle`, upgrading `gradle` (as per https://github.com/eclipse/openj9/issues/10223#issuecomment-672703561) fixed the error. The remaining question is to better understand the interaction between `JVM` and `gradle`/`plugin`.

There is no VM change required for this issue, I think it can be assigned to `backlog` instead.
