### ISSUE TITLE
jdk16 test_loadIllegalSubclassOfSealedClass Class file is a preview version but has the wrong major version or preview is not enabled

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10241]
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/278/
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK_testList_0/
Jep360Tests_0
```
FAILED: test_loadIllegalSubclassOfSealedClass
org.testng.TestException: 
Expected exception of type class java.lang.IncompatibleClassChangeError but got java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=TestIllegalSealedClass, offset=6
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=TestIllegalSealedClass, offset=6
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:479)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:440)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:392)
	at org.openj9.test.utilities.CustomClassLoader.getClass(CustomClassLoader.java:27)
	at org.openj9.test.sealedclasses.SealedClassesTests.test_loadIllegalSubclassOfSealedClass(SealedClassesTests.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	... 18 more
```

**Comment by pshipton** [comment]
@theresa-m please take a look. This is "blocking" the jdknext (Java 16) acceptance build, I could promote it manually, but it's extra work every day to confirm this is the only failure on all the platforms.

**Comment by theresa-m** [comment]
Okay. Working on a fix.

**Comment by theresa-m** [comment]
Opened a pr to disable these tests for now since I'm not sure if sealed classes will continue to java 16 yet. I'll open an issue to decide about re-enabling once the Java 16 JEP list has been decided.
