### ISSUE TITLE
Failures with Cipher tests on AArch64 

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#10254]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/209/

- com/sun/crypto/provider/Cipher/DES/TestCipherDES.java.TestCipherDES
- com/sun/crypto/provider/Cipher/DES/TestCipherDESede.java.TestCipherDESede
- com/sun/crypto/provider/Cipher/KeyWrap/TestCipherKeyWrapperTest.java.TestCipherKeyWrapperTest
- com/sun/crypto/provider/Cipher/KeyWrap/XMLEncKAT.java.XMLEncKAT
- com/sun/crypto/provider/Cipher/PBE/PBESameBuffer/PBESameBuffer.java.PBESameBuffer
- com/sun/crypto/provider/Cipher/PBE/PBESealedObject.java.PBESealedObject
- com/sun/crypto/provider/Cipher/PBE/PKCS12Cipher.java.PKCS12Cipher
- com/sun/crypto/provider/Cipher/PBE/PKCS12CipherKAT.java.PKCS12CipherKAT
- com/sun/crypto/provider/Cipher/PBE/TestCipherKeyWrapperPBEKey.java.TestCipherKeyWrapperPBEKey
- com/sun/crypto/provider/Cipher/PBE/TestCipherPBE.java.TestCipherPBE

Optional info
-------------

- intermittent failure: no
- regression or new test: regression

This test was run on test-aws-rhel76-armv8-3.

Other passing builds were run on the following servers:
- #205 test-aws-rhel76-armv8-6
- #206 test-aws-ubuntu1804-armv8-1
- #207 test-aws-rhel76-armv8-5
- #208 test-aws-ubuntu1804-armv8-1

Failure output (captured from console output)
---------------------------------------------

TestCipherDES
```
[2020-07-23T01:53:20.801Z] Testing: DES/CTR/PKCS5Padding
[2020-07-23T01:53:20.801Z] Recovered and plain text are same
[2020-07-23T01:53:20.801Z] Recovered and plain text are same with same buffer
[2020-07-23T01:53:20.801Z] Test Passed.
[2020-07-23T01:53:20.801Z] Testing: DES/CTS/NoPaDDing
[2020-07-23T01:53:20.801Z] STDERR:
[2020-07-23T01:53:20.801Z] java.lang.RuntimeException: Recovered text not same as plain text
[2020-07-23T01:53:20.801Z] 	at TestCipher.runTest(TestCipher.java:188)
[2020-07-23T01:53:20.801Z] 	at TestCipher.runAll(TestCipher.java:118)
[2020-07-23T01:53:20.801Z] 	at TestCipherDES.main(TestCipherDES.java:46)
[2020-07-23T01:53:20.801Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-07-23T01:53:20.801Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-07-23T01:53:20.801Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-07-23T01:53:20.801Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-07-23T01:53:20.801Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2020-07-23T01:53:20.801Z] 	at java.base/java.lang.Thread.run(Thread.java:836)
```

TestCipherDESede
```
[2020-07-23T01:53:20.802Z] STDOUT:
[2020-07-23T01:53:20.802Z] Testing: DESede/CBC/NoPaDDing
[2020-07-23T01:53:20.802Z] STDERR:
[2020-07-23T01:53:20.802Z] java.lang.RuntimeException: Recovered text not same as plain text
[2020-07-23T01:53:20.802Z] 	at TestCipher.runTest(TestCipher.java:188)
[2020-07-23T01:53:20.802Z] 	at TestCipher.runAll(TestCipher.java:118)
[2020-07-23T01:53:20.802Z] 	at TestCipherDESede.main(TestCipherDESede.java:46)
[2020-07-23T01:53:20.802Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-07-23T01:53:20.802Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-07-23T01:53:20.802Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-07-23T01:53:20.802Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-07-23T01:53:20.802Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2020-07-23T01:53:20.802Z] 	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by knn-k** [comment]
XL build on the same day (https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/163/ run on build-packet-ubuntu1804-armv8l-1) has the following failures in Cipher:

- com/sun/crypto/provider/Cipher/DES/TestCipherDES.java.TestCipherDES
- com/sun/crypto/provider/Cipher/DES/TestCipherDESede.java.TestCipherDESede
- com/sun/crypto/provider/Cipher/PBE/PBESameBuffer/PBESameBuffer.java.PBESameBuffer
- com/sun/crypto/provider/Cipher/PBE/PKCS12CipherKAT.java.PKCS12CipherKAT

**Comment by knn-k** [comment]
I can reproduce the failures locally using the build OpenJDK11U-jdk_aarch64_linux_openj9_2020-07-22-23-32.tar.gz.

```
Running test with pbeWithMD5ANDdes:
java.security.InvalidKeyException: The wrapped key is not padded correctly
        at java.base/com.sun.crypto.provider.PBES1Core.unwrap(PBES1Core.java:544)
        at java.base/com.sun.crypto.provider.PBEWithMD5AndDESCipher.engineUnwrap(PBEWithMD5AndDESCipher.java:426)
        at java.base/javax.crypto.Cipher.unwrap(Cipher.java:2587)
        at TestCipherKeyWrapperPBEKey.runTest(TestCipherKeyWrapperPBEKey.java:149)
        at TestCipherKeyWrapperPBEKey.runAll(TestCipherKeyWrapperPBEKey.java:95)
        at TestCipherKeyWrapperPBEKey.main(TestCipherKeyWrapperPBEKey.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
        at java.base/java.lang.Thread.run(Thread.java:836)
STATUS:Failed
```

**Comment by knn-k** [comment]
These failures were caused by eclipse/omr#5366.
I opened eclipse/omr#5428 to fix it.

**Comment by knn-k** [comment]
The result of `bloadi` (n13n) is stored in `GPR_0085` below, and this node is referenced later.  But the `bu2i` node changes the value of `GPR_0085`, and that causes the failures.

```
 n14n     (  0)                                bu2i (in GPR_0085) (X>=0 )                             [    0xffff97003d70] bci=[-1,5,701] rc=0 vc=454 vn=- li=2 udi=26000 nc=1 flg=0x100
 n13n     (  1)                                  bloadi  <array-shadow>[#186  Shadow] [flags 0x80000601 0x0 ] (in GPR_0085) (cannotOverflow )  [    0xffff97003d20] bci=[-1,5,701] rc=1 vc=454 vn=- li=2 udi=26000 nc=1 flg=0x1000
```

**Comment by knn-k** [comment]
eclipse/omr#5428 has been merged.  I am waiting for the next round of sanity.openjdk test.

**Comment by knn-k** [comment]
All the tests passed in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/210/.
Closing.
