### ISSUE TITLE
openjdk BigDecimal/StringConstructor.java NumberFormatException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10268]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl_Nightly/109
java/math/BigDecimal/StringConstructor.java
ub18-390-2
```
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:599)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:809)
	at StringConstructor.nonAsciiZeroTest(StringConstructor.java:110)
	at StringConstructor.main(StringConstructor.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
50x grinder ub16-390-1 https://ci.eclipse.org/openj9/job/Grinder/1009 - passed
50x grinder ub18-390-2 https://ci.eclipse.org/openj9/job/Grinder/1010 - passed

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/447
jdk_math_1 
java/math/BigDecimal/StringConstructor.java
```
23:24:51  java.lang.NumberFormatException
23:24:51  	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:628)
23:24:51  	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:405)
23:24:51  	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:838)
23:24:51  	at StringConstructor.nonAsciiZeroTest(StringConstructor.java:112)
23:24:51  	at StringConstructor.main(StringConstructor.java:72)
23:24:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:24:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:24:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:24:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:24:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
23:24:51  	at java.base/java.lang.Thread.run(Thread.java:839)
23:24:51  Caused by: java.lang.ArrayIndexOutOfBoundsException
23:24:51  	at java.base/java.lang.CharacterDataLatin1.digit(CharacterDataLatin1.java:210)
23:24:51  	at java.base/java.lang.Character.digit(Character.java:9981)
23:24:51  	at java.base/java.lang.Character.digit(Character.java:9929)
23:24:51  	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:500)
23:24:51  	... 10 more
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Release/61/ - [ub20-390-2](https://openj9-jenkins.osuosl.org/computer/ub20-390-2)
java/math/BigDecimal/StringConstructor.java
```
20:13:29  java.lang.NumberFormatException
20:13:29  	at java.math.BigDecimal.<init>(BigDecimal.java:603)
20:13:29  	at java.math.BigDecimal.<init>(BigDecimal.java:387)
20:13:29  	at java.math.BigDecimal.<init>(BigDecimal.java:813)
20:13:29  	at StringConstructor.nonAsciiZeroTest(StringConstructor.java:111)
20:13:29  	at StringConstructor.main(StringConstructor.java:71)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OpenJDK8_testList_2/10
jdk_math_0
java/math/BigDecimal/StringConstructor.java
```
20:48:46  java.lang.NumberFormatException
20:48:46  	at java.math.BigDecimal.<init>(BigDecimal.java:603)
20:48:46  	at java.math.BigDecimal.<init>(BigDecimal.java:387)
20:48:46  	at java.math.BigDecimal.<init>(BigDecimal.java:813)
20:48:46  	at StringConstructor.nonAsciiZeroTest(StringConstructor.java:111)
20:48:46  	at StringConstructor.main(StringConstructor.java:71)
```
