### ISSUE TITLE
jitserver Processing dump event "abort"

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10269]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/58
testJITServer_0
ub16x64j92
```
////////////////////////////////////////////////////////////////////////
//// JITServer is currently a technology preview. Its use is not yet supported.
//// JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServerUnreachableForAWhile.server.jitverboselog.out
//// 
//// JITServer is ready to accept incoming requests
//// #0: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x8b16d5) [0x7f27d69e56d5]
//// #1: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x8bc110) [0x7f27d69f0110]
//// #2: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x174b7e) [0x7f27d62a8b7e]
//// #3: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so(+0x2946a) [0x7f27d832c46a]
//// #4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f27d9e1d390]
//// #5: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x74d72b) [0x7f27d688172b]
//// #6: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x74dd9b) [0x7f27d6881d9b]
//// #7: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x548d27) [0x7f27d667cd27]
//// #8: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x52da5c) [0x7f27d6661a5c]
//// #9: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x1875b4) [0x7f27d62bb5b4]
//// #10: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x188511) [0x7f27d62bc511]
//// #11: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so(+0x29fa3) [0x7f27d832cfa3]
//// #12: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x18a2d5) [0x7f27d62be2d5]
//// #13: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x1e7f61) [0x7f27d631bf61]
//// #14: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x1861bb) [0x7f27d62ba1bb]
//// #15: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x186682) [0x7f27d62ba682]
//// #16: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x18672a) [0x7f27d62ba72a]
//// #17: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so(+0x29fa3) [0x7f27d832cfa3]
//// #18: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x186b84) [0x7f27d62bab84]
//// #19: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9thr29.so(+0xe3c6) [0x7f27d80f63c6]
//// #20: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f27d9e136ba]
//// #21: function clone+0x6d [0x7f27d9b4941d]
//// JVMDUMP039I Processing dump event "abort", detail "" at 2020/07/28 01:08:47 - please wait.
//// JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/core.20200728.010847.31082.0001.dmp' in response to an event
//// JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.31242.
//// 
//// JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/core.20200728.010847.31082.0001.dmp
//// JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/javacore.20200728.010847.31082.0002.txt' in response to an event
//// JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/javacore.20200728.010847.31082.0002.txt
//// JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/Snap.20200728.010847.31082.0003.trc' in response to an event
//// JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/Snap.20200728.010847.31082.0003.trc
//// JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/jitdump.20200728.010847.31082.0004.dmp' in response to an event
//// JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly_testList_0/openjdk-tests/TKG/test_output_1595906907231/testJITServer_0/jitdump.20200728.010847.31082.0004.dmp
//// JVMDUMP013I Processed dump event "abort", detail "".
////////////////////////////////////////////////////////////////////////
PASSED: testServer
PASSED: testServerComesUpAfterClient
PASSED: testServerComesUpAfterClientAndGoesDownAgain
PASSED: testServerGoesDown
PASSED: testServerGoesDownAnotherComesUp
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Expected an exit value of 0 or 143, got 1 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:144)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@mpirvu

**Comment by dmitry-ten** [comment]
I think it's the same failure as #10215 and thus can be closed as well @mpirvu.

**Comment by mpirvu** [comment]
Closing based on the above comment
