### ISSUE TITLE
testSCCacheManagement_0 TestSharedCacheJvmtiAPI failing on z/OS

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10275]
I don't think this is intermittent, but the assert at OSCachesysv.cpp:1213 doesn't always occur. I think the assert is a separate issue.

11.0.8 stream
job/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/17
testSCCacheManagement_0
fyrec520
```
--------- PROGRAM RUN COMMANDLINE INFO ---------
java_exe =	/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java  
cmd.runProgramSimpleApp =	null
.Running  :testSharedCacheJvmtiAPI  (Test suite : TestOptionsDefault)
Command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
vvv STDOUT vvv

^^^ STDOUT ^^^
vvv STDERR vvv
JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
/home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00

^^^ STDERR ^^^
vvv STACK TRACE vvv
java.lang.Throwable
	at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
	at tests.sharedclasses.TestUtils.checkFileExistsForNonPersistentCache(TestUtils.java:889)
	at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:92)
	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at junit.textui.TestRunner.start(TestRunner.java:180)
	at junit.textui.TestRunner.main(TestRunner.java:138)
^^^ STACK TRACE ^^^
2nd last command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
vvv 2ND LAST STDOUT vvv

^^^ 2ND LAST STDOUT ^^^
vvv 2ND LAST STDERR vvv
JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
/home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00

^^^ 2ND LAST STDERR ^^^
No file found at '/home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00'
	Last command: /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent
05:20:13.309 0x1d9cb600   j9shr.1009   *   ** ASSERTION FAILED ** at ./OSCachesysv.cpp:1213: ((0 ))
05:20:13.309 0x1d9c6c00   j9shr.1009   *   ** ASSERTION FAILED ** at ./OSCachesysv.cpp:1213: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/07/28 05:20:13 - please wait.
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/07/28 05:20:13 - please wait.
JVMDUMP032I JVM requested System dump using 'JENKINS.JVM.JENKINS3.D200728.T052013.X&DS' in response to an event
IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
IEATDUMP success for DSN='JENKINS.JVM.JENKINS3.D200728.T052013.X&DS'
JVMDUMP040I System dump written to dataset(s) using name template JENKINS.JVM.JENKINS3.D200728.T052013.X&DS
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/test_output_15959133211694/testSCCacheManagement_0/javacore.20200728.052013.16777396.0003.txt' in response to an event
JVMDUMP032I JVM requested System dump using 'JENKINS.JVM.JENKINS3.D200728.T052013.X&DS' in response to an event
IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/test_output_15959133211694/testSCCacheManagement_0/javacore.20200728.052013.16777396.0003.txt
IEATDUMP failure for DSN='JENKINS.JVM.JENKINS3.D200728.T052013.X&DS' RC=0x00000008 RSN=0x00000026
JVMPORT024E IEATDUMP failed because we couldn't allocate the dump dataset (check disk space and field permissions).
JVMDUMP012E Error in System dump: JENKINS.JVM.JENKINS3.D200728.T052013.X&DS
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/test_output_15959133211694/testSCCacheManagement_0/javacore.20200728.052013.16777396.0005.txt' in response to an event
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/test_output_15959133211694/testSCCacheManagement_0/Snap.20200728.052013.16777396.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/test_output_15959133211694/testSCCacheManagement_0/Snap.20200728.052013.16777396.0004.trc
JVMDUMP013I Processed dump event "traceassert", detail "".

testSCCacheManagement_0_FAILED
```

head stream:
job/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/18/
fyrec520
```
[2020-07-28T06:36:25.893Z] .Running  :testSharedCacheJvmtiAPI  (Test suite : TestOptionsDefault)
[2020-07-28T06:36:36.336Z] Command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
[2020-07-28T06:36:36.336Z] vvv STDOUT vvv
[2020-07-28T06:36:36.336Z]
[2020-07-28T06:36:36.336Z] ^^^ STDOUT ^^^
[2020-07-28T06:36:36.336Z] vvv STDERR vvv
[2020-07-28T06:36:36.336Z] JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
[2020-07-28T06:36:36.336Z] /home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00
[2020-07-28T06:36:36.336Z]
[2020-07-28T06:36:36.336Z] ^^^ STDERR ^^^
[2020-07-28T06:36:36.336Z] vvv STACK TRACE vvv
[2020-07-28T06:36:36.336Z] java.lang.Throwable
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.TestUtils.checkFileExistsForNonPersistentCache(TestUtils.java:889)
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:92)
[2020-07-28T06:36:36.336Z]      at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
[2020-07-28T06:36:36.336Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-07-28T06:36:36.336Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-07-28T06:36:36.336Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-07-28T06:36:36.336Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestCase.runTest(TestCase.java:168)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestCase.runBare(TestCase.java:134)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestResult$1.protect(TestResult.java:110)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestResult.runProtected(TestResult.java:128)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestResult.run(TestResult.java:113)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestCase.run(TestCase.java:124)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestSuite.runTest(TestSuite.java:243)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestSuite.run(TestSuite.java:238)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestSuite.runTest(TestSuite.java:243)
[2020-07-28T06:36:36.336Z]      at junit.framework.TestSuite.run(TestSuite.java:238)
[2020-07-28T06:36:36.336Z]      at junit.textui.TestRunner.doRun(TestRunner.java:116)
[2020-07-28T06:36:36.336Z]      at junit.textui.TestRunner.start(TestRunner.java:180)
[2020-07-28T06:36:36.336Z]      at junit.textui.TestRunner.main(TestRunner.java:138)
[2020-07-28T06:36:36.336Z] ^^^ STACK TRACE ^^^
[2020-07-28T06:36:36.336Z] 2nd last command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
[2020-07-28T06:36:36.336Z] vvv 2ND LAST STDOUT vvv
[2020-07-28T06:36:36.336Z]
[2020-07-28T06:36:36.336Z] ^^^ 2ND LAST STDOUT ^^^
[2020-07-28T06:36:36.336Z] vvv 2ND LAST STDERR vvv
[2020-07-28T06:36:36.336Z] JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
[2020-07-28T06:36:36.336Z] /home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00
[2020-07-28T06:36:36.336Z]
[2020-07-28T06:36:36.336Z] ^^^ 2ND LAST STDERR ^^^
2020-07-28T06:36:36.336Z] No file found at '/home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00'
[2020-07-28T06:36:36.336Z]      Last command: /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent
[2020-07-28T06:36:40.199Z] E.Running  :testSharedCacheJavaAPI  (Test suite : TestOptionsDefault)
[2020-07-28T06:36:51.437Z] Command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
[2020-07-28T06:36:51.437Z] vvv STDOUT vvv
[2020-07-28T06:36:51.437Z]
[2020-07-28T06:36:51.437Z] ^^^ STDOUT ^^^
[2020-07-28T06:36:51.437Z] vvv STDERR vvv
[2020-07-28T06:36:51.437Z] JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
[2020-07-28T06:36:51.437Z] /home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00
[2020-07-28T06:36:51.437Z]
[2020-07-28T06:36:51.437Z] ^^^ STDERR ^^^
[2020-07-28T06:36:51.437Z] vvv STACK TRACE vvv
[2020-07-28T06:36:51.437Z] java.lang.Throwable
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.TestUtils.checkFileExistsForNonPersistentCache(TestUtils.java:889)
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.options.TestSharedCacheJavaAPI.main(TestSharedCacheJavaAPI.java:171)
[2020-07-28T06:36:51.437Z]      at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJavaAPI(TestOptionsBase.java:120)
[2020-07-28T06:36:51.437Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-07-28T06:36:51.437Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-07-28T06:36:51.437Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-07-28T06:36:51.437Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestCase.runTest(TestCase.java:168)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestCase.runBare(TestCase.java:134)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestResult$1.protect(TestResult.java:110)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestResult.runProtected(TestResult.java:128)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestResult.run(TestResult.java:113)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestCase.run(TestCase.java:124)
[2020-07-28T06:36:51.437Z]      at junit.framework.TestSuite.runTest(TestSuite.java:243)
[2020-07-28T06:36:51.438Z]      at junit.framework.TestSuite.run(TestSuite.java:238)
[2020-07-28T06:36:51.438Z]      at junit.framework.TestSuite.runTest(TestSuite.java:243)
[2020-07-28T06:36:51.438Z]      at junit.framework.TestSuite.run(TestSuite.java:238)
[2020-07-28T06:36:51.438Z]      at junit.textui.TestRunner.doRun(TestRunner.java:116)
[2020-07-28T06:36:51.438Z]      at junit.textui.TestRunner.start(TestRunner.java:180)
[2020-07-28T06:36:51.438Z]      at junit.textui.TestRunner.main(TestRunner.java:138)
[2020-07-28T06:36:51.438Z] ^^^ STACK TRACE ^^^
[2020-07-28T06:36:51.438Z] 2nd last command executed: '/home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent'
[2020-07-28T06:36:51.438Z] vvv 2ND LAST STDOUT vvv
[2020-07-28T06:36:51.438Z]
[2020-07-28T06:36:51.438Z] ^^^ 2ND LAST STDOUT ^^^
[2020-07-28T06:36:51.438Z] vvv 2ND LAST STDERR vvv
[2020-07-28T06:36:51.438Z] JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
[2020-07-28T06:36:51.438Z] /home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00
[2020-07-28T06:36:51.438Z]
[2020-07-28T06:36:51.438Z] ^^^ 2ND LAST STDERR ^^^
[2020-07-28T06:36:51.438Z] No file found at '/home/jenkins/javasharedresources/C290M11F1A64_memory_cache2_groupaccess_G41L00'
[2020-07-28T06:36:51.438Z]      Last command: /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=cache2_groupaccess,nonpersistent
[2020-07-28T06:36:56.438Z] E.Running  :testDestroyCache  (Test suite : TestOptionsDefault)

**Comment by pshipton** [comment]
@hangshao0 I think the test needs to be updated for Java 11 to handle the location difference between regular and groupAccess.

**Comment by hangshao0** [comment]
I have an impression @LongyuZhang has fixed something similar (cache location issue) on z/OS recently.  (I guess it was on Java 8 ? I cannot recall the details).

**Comment by LongyuZhang** [comment]
Discussed with @hangshao0  about this failure. Previous fix passed OpenJ9 11, for this issue about IBM 11, will add extra condition for the cache location. 
Related to Runtimes/backlog/issue/306

**Comment by hangshao0** [comment]
The build been tested in `job/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/` are built from
`job/Build_JDK11_s390x_zos_Nightly`

Looking at the latest build: `job/Build_JDK11_s390x_zos_Nightly/488/consoleFull`, I see ` -DOPENJ9_BUILD` is incorrectly set:

`04:47:43  cxx -DOPENJ9_BUILD -Wc,debug -Wc,"langlvl(extended)" -Wc,lp64 -+ -DIPv6_FUNCTION_SUPPORT -DJ9ZOS390 -DLONGLONG -DJ9VM_TIERED_CODE_CACHE -D_ALL_SOURCE -D_XOPEN_SOURCE_EXTENDED -DIBM_ATOE -D_POSIX_SOURCE -D_ISOC99_SOURCE -D__STDC_LIMIT_MACROS -I../omr/util/a2e/headers -O3 -Wc,"ARCH(10)" -Wc,"TUNE(10)" -Wl,compat=ZOSV2R3 -Wc,"convlit(ISO8859-1),xplink,rostring,FLOAT(IEEE,FOLD,AFP),enum(4)" -Wa,goff -Wc,NOANSIALIAS -Wc,"inline(auto,noreport,600,5000)" -Wc,"SERVICE(j20200810)" -Wc,"TARGET(zOSV2R3)" -Wc,list,offset -DJ9ZOS39064 -Wc,lp64 -Wa,"SYSPARM(BIT64)" -I. -I../include -I../oti -I../shared_util -I../verbose -I../shared_common/include -I../shared -I../nls -I../omr/include_core    -DTR_HOST_S390 -c shrinit.cpp > shrinit.asmlist`

The` -DOPENJ9_BUILD` should not be set for an IBM build. The default cache location is affected by `-DOPENJ9_BUILD`.

**Comment by LongyuZhang** [comment]
> The build been tested in `job/Test_openjdk11_ibm_extended.functional_s390x_zos_Personal_testList_0/` are built from
> `job/Build_JDK11_s390x_zos_Nightly`
> 
> Looking at the latest build: `job/Build_JDK11_s390x_zos_Nightly/488/consoleFull`, I see ` -DOPENJ9_BUILD` is incorrectly set:
> 
> `04:47:43 cxx -DOPENJ9_BUILD -Wc,debug -Wc,"langlvl(extended)" -Wc,lp64 -+ -DIPv6_FUNCTION_SUPPORT -DJ9ZOS390 -DLONGLONG -DJ9VM_TIERED_CODE_CACHE -D_ALL_SOURCE -D_XOPEN_SOURCE_EXTENDED -DIBM_ATOE -D_POSIX_SOURCE -D_ISOC99_SOURCE -D__STDC_LIMIT_MACROS -I../omr/util/a2e/headers -O3 -Wc,"ARCH(10)" -Wc,"TUNE(10)" -Wl,compat=ZOSV2R3 -Wc,"convlit(ISO8859-1),xplink,rostring,FLOAT(IEEE,FOLD,AFP),enum(4)" -Wa,goff -Wc,NOANSIALIAS -Wc,"inline(auto,noreport,600,5000)" -Wc,"SERVICE(j20200810)" -Wc,"TARGET(zOSV2R3)" -Wc,list,offset -DJ9ZOS39064 -Wc,lp64 -Wa,"SYSPARM(BIT64)" -I. -I../include -I../oti -I../shared_util -I../verbose -I../shared_common/include -I../shared -I../nls -I../omr/include_core -DTR_HOST_S390 -c shrinit.cpp > shrinit.asmlist`
> 
> The` -DOPENJ9_BUILD` should not be set for an IBM build. The default cache location is affected by `-DOPENJ9_BUILD`.

Opened Issue of above mentioned ```-DOPENJ9_BUILD``` setting on Internal GitHub runtimes/openj9-openjdk-jdk11-zos/issues/360. Thanks.

**Comment by pshipton** [comment]
@hangshao0 @LongyuZhang `-DOPENJ9_BUILD` needs to be set for all Java 11+ builds, even IBM variants. We need to find another way to fix the test. Something like `isOpen() && isZos()` should work.

**Comment by hangshao0** [comment]
@LongyuZhang, you may want to modify your change https://github.com/eclipse/openj9/pull/10368 according to the comment above.

**Comment by LongyuZhang** [comment]
> @hangshao0 @LongyuZhang `-DOPENJ9_BUILD` needs to be set for all Java 11+ builds, even IBM variants. We need to find another way to fix the test. Something like `isOpen() && isZos()` should work.

Hi @pshipton, if all Java 11+ all use `-DOPENJ9_BUILD`, does it mean ibm 11+ use this setting on all platforms, not only on zos? So far Hang and I tried to change `is openj9` check to `is not ibm 8` check, and it passed ibm zos 11. Thanks.

**Comment by hangshao0** [comment]
> if all Java 11+ all use -DOPENJ9_BUILD, does it mean ibm 11+ use this setting on all platforms

I think the answer is yes.

**Comment by pshipton** [comment]
Correct, -DOPENJ9_BUILD should be set for all builds which aren't IBM Java 8. It's enabled via the extensions repos, and only IBM Java 8 doesn't use the OpenJDK extensions.
