### ISSUE TITLE
JDK15 java/util/StringJoiner/MergeTest.java OutOfMemoryError: UTF16 String size is 2147483639, should be less than 1073741823

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10316]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_mac_Nightly/7/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
00:27:30  test MergeTest.OOM(): failure
00:27:30  java.lang.OutOfMemoryError: UTF16 String size is 2147483639, should be less than 1073741823
00:27:30  	at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
00:27:30  	at java.base/java.lang.String.repeat(String.java:3967)
00:27:30  	at MergeTest.OOM(MergeTest.java:175)
00:27:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:27:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:27:30  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:27:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:27:30  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:27:30  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:27:30  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:27:30  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:27:30  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:27:30  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:27:30  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:27:30  	at org.testng.TestRunner.run(TestRunner.java:623)
00:27:30  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:27:30  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:27:30  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:27:30  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:27:30  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:27:30  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:27:30  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:27:30  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:27:30  	at org.testng.TestNG.run(TestNG.java:1018)
00:27:30  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:27:30  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:27:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:27:30  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:27:30  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:27:30  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:27:30  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:27:30  	at java.base/java.lang.Thread.run(Thread.java:851)
00:27:30  test MergeTest.testCascadeEmpty(): success
00:27:30  test MergeTest.testDelimiter(): success
00:27:30  test MergeTest.testEmptyBoth(): success
00:27:30  test MergeTest.testEmptyOther(): success
00:27:30  test MergeTest.testEmptyThis(): success
00:27:30  test MergeTest.testMergeSelf(): success
00:27:30  test MergeTest.testNull(): success
00:27:30  test MergeTest.testSimple(): success
00:27:30  
00:27:30  ===============================================
00:27:30  java/util/StringJoiner/MergeTest.java
00:27:30  Total tests run: 9, Failures: 1, Skips: 0
00:27:30  ===============================================
```

For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
00:30:20  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_util_j9_0

**Comment by adamfarley** [comment]
Could this be a duplicate of https://github.com/eclipse/openj9/issues/10149 ?

**Comment by JasonFengJ9** [comment]
Yup, you are right, @adamfarley
