### ISSUE TITLE
JTReg Timeout: java/util/concurrent/BlockingQueue/SingleProducerMultipleConsumerLoops.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#10336]
Failure link
------------

Public link to the failing test => https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/test/java/util/concurrent/BlockingQueue/SingleProducerMultipleConsumerLoops.java

and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, openjdk 
- test target name, jdk_util_j9_0
- OS/architecture, x86-64_linux
```
18:49:52  openjdk version "1.8.0_265"
18:49:52  OpenJDK Runtime Environment (build 1.8.0_265-202008041719-b01)
18:49:52  Eclipse OpenJ9 VM (build master-2020312e3, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200804_734 (JIT enabled, AOT enabled)
18:49:52  OpenJ9   - 2020312e3
18:49:52  OMR      - 7b76a160b
18:49:52  JCL      - bf6e4d1c based on jdk8u265-b01)
```

Optional info
-------------

- intermittent failure: Unknown. Investigating via Grinder => https://ci.adoptopenjdk.net/job/Grinder/3689/console
- new test

Failure output (captured from console output)
---------------------------------------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/279/console
```
20:17:53  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 3 timed out with a timeout of 4800 seconds; check console log for any additional details
20:17:53  REASON: User specified action: run main/timeout=600 SingleProducerMultipleConsumerLoops 
20:17:53  TIME:   4805.091 seconds
20:17:53  messages:
20:17:53  command: main SingleProducerMultipleConsumerLoops
20:17:53  reason: User specified action: run main/timeout=600 SingleProducerMultipleConsumerLoops 
20:17:53  Mode: agentvm
20:17:53  Agent id: 3
20:17:53  Timeout refired 4800 times
20:17:53  Timeout information:
20:17:53  Running jcmd on process 30036
20:17:53  Dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_15965634482580/jdk_util_j9_0/work/scratch/0/core.20200804.121736.30036.0001.dmp
20:17:53  Running jstack on process 30036
20:17:53  2020-08-04T12:17:38.053
20:17:53  Virtual machine: 30036 JVM information:
20:17:53  JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200804_734 (JIT enabled, AOT enabled)
20:17:53  OpenJ9   - 2020312e3
20:17:53  OMR      - 7b76a160b
20:17:53  JCL      - bf6e4d1c based on jdk8u265-b01
```
Core dump that is mentioned in the log => https://ibm.box.com/shared/static/o9dt0wzy2rpcyw4jh3bwhtiumt1thjwh.zip

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly_testList_1/522/ - [ub20-390-1](https://openj9-jenkins.osuosl.org/computer/ub20-390-1)
jdk_util_0 
java/util/concurrent/BlockingQueue/SingleProducerMultipleConsumerLoops.java
```
00:31:18  "pool-1-thread-1" Id=21 TIMED_WAITING
00:31:18  	at sun.misc.Unsafe.park(Native Method)
00:31:18  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
00:31:18  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
00:31:18  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
00:31:18  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
00:31:18  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
00:31:18  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
00:31:18  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:31:18  	at java.lang.Thread.run(Thread.java:822)
00:31:18  
00:31:18  "ClassByNameCache Reaper" Id=37 WAITING
00:31:18  	at java.lang.Object.waitImpl(Native Method)
00:31:18  	at java.lang.Object.wait(Object.java:248)
00:31:18  	at java.lang.Object.wait(Object.java:216)
00:31:18  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
00:31:18  	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
00:31:18  	at java.io.ClassByNameCache$Reaper.run(ClassByNameCache.java:233)
00:31:18  	at java.lang.Thread.run(Thread.java:822)
00:31:18  
00:31:18  "AgentVMThread" Id=237 WAITING
00:31:18  	at sun.misc.Unsafe.park(Native Method)
00:31:18  	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
00:31:18  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
00:31:18  	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:234)
00:31:18  	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362)
00:31:18  	at SingleProducerMultipleConsumerLoops.oneRun(SingleProducerMultipleConsumerLoops.java:163)
00:31:18  	at SingleProducerMultipleConsumerLoops.oneTest(SingleProducerMultipleConsumerLoops.java:85)
00:31:18  	at SingleProducerMultipleConsumerLoops.main(SingleProducerMultipleConsumerLoops.java:59)
00:31:18  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:18  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:31:18  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:18  	at java.lang.reflect.Method.invoke(Method.java:503)
00:31:18  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:31:18  	at java.lang.Thread.run(Thread.java:822)
00:31:18  
00:31:18  "pool-4-thread-1" Id=238 RUNNABLE
00:31:18  	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(SynchronousQueue.java:677)
00:31:18  	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:877)
00:31:18  	at SingleProducerMultipleConsumerLoops$Producer.run(SingleProducerMultipleConsumerLoops.java:110)
00:31:18  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:31:18  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:31:18  	at java.lang.Thread.run(Thread.java:822)
```
