### ISSUE TITLE
JDK11 : BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10343]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/111/consoleFull

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
01:12:22  --------------------------------------------------
01:12:22  TEST: java/lang/String/Supplementary.java
01:12:22  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image
01:12:22  
01:12:22  rerun:
01:12:22  cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15966886939296/jdk_lang_j9_0/work/scratch/1 && \
01:12:22  DISPLAY=:0 \
01:12:22  HOME=/home/jenkins \
01:12:22  LANG=en_US.UTF-8 \
01:12:22  PATH=/bin:/usr/bin:/usr/sbin \
01:12:22      /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image/bin/java \
01:12:22          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage' \
01:12:22          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage' \
01:12:22          -Dtest.compiler.opts= \
01:12:22          -Dtest.java.opts= \
01:12:22          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image \
01:12:22          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image \
01:12:22          -Dtest.timeout.factor=8.0 \
01:12:22          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
01:12:22          -Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
01:12:22          -Dtest.name=java/lang/String/Supplementary.java \
01:12:22          -Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/String/Supplementary.java \
01:12:22          -Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/String \
01:12:22          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/String \
01:12:22          -Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15966886939296/jdk_lang_j9_0/work/classes/1/java/lang/String/Supplementary.d \
01:12:22          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15966886939296/jdk_lang_j9_0/work/classes/1/java/lang/String/Supplementary.d \
01:12:22          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15966886939296/jdk_lang_j9_0/work/classes/1/java/lang/String/Supplementary.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/String \
01:12:22          -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15966886939296/jdk_lang_j9_0/work/classes/1/java/lang/String/Supplementary.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/String:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
01:12:22          Supplementary
01:12:22  STDERR:
01:12:22  java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
01:12:22  	at Supplementary.test10(Supplementary.java:498)
01:12:22  	at Supplementary.main(Supplementary.java:43)
01:12:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:12:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:12:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:12:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:12:22  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
01:12:22  	at java.base/java.lang.Thread.run(Thread.java:836)
01:12:22  Caused by: java.lang.invoke.StringConcatException: Generator failed
01:12:22  	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
01:12:22  	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
01:12:22  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
01:12:22  	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
01:12:22  	at java.base/java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
01:12:22  	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
01:12:22  	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
01:12:22  	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
01:12:22  	... 8 more
01:12:22  Caused by: java.lang.NullPointerException
01:12:22  	at java.base/java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286)
01:12:22  	at java.base/java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2915)
01:12:22  	at java.base/java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2932)
01:12:22  	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1536)
01:12:22  	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
01:12:22  	... 15 more
01:12:22  
01:12:22  JavaTest Message: Test threw exception: java.lang.BootstrapMethodError
01:12:22  JavaTest Message: shutting down test
01:12:22  
01:12:22  
01:12:22  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
```

For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
02:18:35  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_linux_xl&TARGET=jdk_lang_j9_0

**Comment by pshipton** [comment]
Dup of https://github.com/eclipse/openj9/issues/8972
