### ISSUE TITLE
PR build reports false pass result

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10384]
Failure link
------------

PR : https://github.com/eclipse/openj9/pull/10364
PR build (showing **pass** status) : https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/10/ 
in which the actual build **failed** at https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/10/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
16:51:06  FAILED: test_fillInStackTrace_getStackTrace
16:51:06  java.lang.AssertionError: unexpected method1: fillInStackTrace
16:51:06  	at java.base/java.lang.Throwable.fillInStackTrace(Native Method) from jrt:/java.base
16:51:06  	at java.base/java.lang.Throwable.<init>(Throwable.java:90) from jrt:/java.base
16:51:06  	at java.base/java.lang.Throwable.<init>(Throwable.java:101) from jrt:/java.base
16:51:06  	at java.base/java.lang.Error.<init>(Error.java:71) from jrt:/java.base
16:51:06  	at java.base/java.lang.AssertionError.<init>(AssertionError.java:59) from jrt:/java.base
16:51:06  	at java.base/java.lang.AssertionError.<init>(AssertionError.java:75) from jrt:/java.base

16:51:06  ===============================================
16:51:06      JCL_TEST_Java-Lang
16:51:06      Tests run: 364, Failures: 1, Skips: 0
16:51:06  ===============================================
```

By the way, I discovered a similar failure in a nightly build and was wondering why the PR build passed.
A fix will be submitted for the `test_fillInStackTrace_getStackTrace` failure shortly.

fyi @gacholio @DanHeidinga

**Comment by AdamBrousseau** [comment]
cc @llxia 
I see the parent knows that a child was unstable, but the parent does not set itself UNSTABLE. This _was_ working so I'm not sure if there was a change made recently to this part of the pipeline.
```
Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1 #10 completed with status SUCCESS
[Pipeline] step
Copied 1 artifact from "Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1" build number 10
[Pipeline] echo
Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0 #10 completed with status UNSTABLE
[Pipeline] step
Copied 1 artifact from "Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0" build number 10
[Pipeline] step
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/TestTargetResult.tap
Saving reports...
Processing '/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/10/openjdk-tests/TKG/test_output_15972618664159/TestTargetResult.tap'
Parsing TAP test result [/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/10/openjdk-tests/TKG/test_output_15972618664159/TestTargetResult.tap].
Processing '/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/9/openjdk-tests/TKG/test_output_15972617951004/TestTargetResult.tap'
Parsing TAP test result [/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/9/openjdk-tests/TKG/test_output_15972617951004/TestTargetResult.tap].
Processing '/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1/10/openjdk-tests/TKG/test_output_15972618376605/TestTargetResult.tap'
Parsing TAP test result [/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1/10/openjdk-tests/TKG/test_output_15972618376605/TestTargetResult.tap].
Processing '/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1/9/openjdk-tests/TKG/test_output_15972618298351/TestTargetResult.tap'
Parsing TAP test result [/var/jenkins/jobs/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal/builds/10/tap-master-files/Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_1/9/openjdk-tests/TKG/test_output_15972618298351/TestTargetResult.tap].
TAP Reports Processing: FINISH
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by llxia** [comment]
This issue is related to the recent PR [copy TAP for UNSTABLE builds](https://github.com/AdoptOpenJDK/openjdk-tests/commit/6ba13885541dae835c0d960b6c08d1d01ca786f4#diff-9da4c7b7710fb521a3c011d52316f1f9). On top of the above issue, the parent build seems getting other TAP files that are unrelated to its child builds (i.e., `Test_openjdk15_j9_sanity.functional_x86-64_windows_Personal_testList_0/9/openjdk-tests/TKG/test_output_15972617951004/TestTargetResult.tap`)

I will revert the change for now.
@OscarQQ  could you take a look? Thanks.

**Comment by llxia** [comment]
PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1990 should fix this.

Close this issue for now. Please reopen if this issue still exists.
