### ISSUE TITLE
JDK16 Valhalla ValueTypeTests FAILED: testGCFlattenedValueArrayWithLongAlignment

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10454]
Failure link
------------

From an internal build `Test_openjdkValhalla_j9_sanity.functional_x86-64_linux_valhalla_Nightly_testList_1/62`:
```
22:47:14  openjdk version "16-internal" 2021-03-16
22:47:14  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
22:47:14  Eclipse OpenJ9 VM (build master-04a8b9eb903, JRE 16 Linux amd64-64-Bit Compressed References 20200824_129 (JIT enabled, AOT enabled)
22:47:14  OpenJ9   - 04a8b9eb903
22:47:14  OMR      - 97452b48be2
22:47:14  JCL      - d286fa99214 based on jdk-16+11)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
FAILED: testGCFlattenedValueArrayWithLongAlignment
java.lang.AssertionError: expected [-1412571974] but found [739584]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:442)
	at org.openj9.test.lworld.ValueTypeTests.checkEqualPoint2D(ValueTypeTests.java:2677)
	at org.openj9.test.lworld.ValueTypeTests.checkEqualFlattenedLine2D(ValueTypeTests.java:2682)
	at org.openj9.test.lworld.ValueTypeTests.checkEqualTriangle2D(ValueTypeTests.java:2688)
	at org.openj9.test.lworld.ValueTypeTests.checkFieldAccessMHOfAssortedType(ValueTypeTests.java:2533)
	at org.openj9.test.lworld.ValueTypeTests.testGCFlattenedValueArrayWithLongAlignment(ValueTypeTests.java:337)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    ValueTypeTests
    Tests run: 99, Failures: 1, Skips: 0
===============================================


===============================================
Valhalla suite
Total tests run: 99, Failures: 1, Skips: 0
===============================================


ValueTypeTests_2_FAILED
```

22:47:44  For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
22:47:44  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=Valhalla&JDK_IMPL=openj9&BUILD_LIST=functional/Valhalla,functional/cmdline_options_tester,functional/cmdLineTests/valuetypeddrtests&PLATFORM=x86-64_linux&TARGET=ValueTypeTests_2

**Comment by tajila** [comment]
i believe this is fixed
