### ISSUE TITLE
Intermittent java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException in ValueTypeTestsJIT_0

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#10564]
Intermittent `java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException `in `ValueTypeTestsJIT_0`

```
PASSED: testACMPTestOnAssortedValues
FAILED: testCheckCastRefClassOnNull
java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
	at org.openj9.test.lworld.ValueTypeGenerator.makeRefDefaultValue(ValueTypeGenerator.java:383)
	at org.openj9.test.lworld.ValueTypeGenerator.generateClass(ValueTypeGenerator.java:98)
	at org.openj9.test.lworld.ValueTypeGenerator.generateRefClass(ValueTypeGenerator.java:933)
	at org.openj9.test.lworld.ValueTypeTests.testCheckCastRefClassOnNull(ValueTypeTests.java:2156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.invoke.StringConcatException: Generator failed
	at <unknown class>.<unknown method>(Unknown Source)
	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:300)
	at java.base/java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
	... 28 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1003)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1579)
	at <unknown class>.<unknown method>(Unknown Source)
	... 35 more

FAILED: testMonitorEnterAndExitWithRefType
java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
	at java.base/java.lang.invoke.ConstructorHandle.invokeExact_thunkArchetype_L(ConstructorHandle.java:90)
	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:123)
	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at org.openj9.test.lworld.ValueTypeGenerator.makeRefDefaultValue(ValueTypeGenerator.java:383)
	at org.openj9.test.lworld.ValueTypeGenerator.generateClass(ValueTypeGenerator.java:98)
	at org.openj9.test.lworld.ValueTypeGenerator.generateRefClass(ValueTypeGenerator.java:933)
	at org.openj9.test.lworld.ValueTypeTests.testMonitorEnterAndExitWithRefType(ValueTypeTests.java:1233)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.invoke.StringConcatException: Generator failed
	at <unknown class>.<unknown method>(Unknown Source)
	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:300)
	at java.base/java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
	at org.openj9.test.lworld.ValueTypeGenerator.makeRefDefaultValue(ValueTypeGenerator.java:383)
	at org.openj9.test.lworld.ValueTypeGenerator.generateClass(ValueTypeGenerator.java:98)
	at org.openj9.test.lworld.ValueTypeGenerator.generateRefClass(ValueTypeGenerator.java:933)
	at org.openj9.test.lworld.ValueTypeTests.testCheckCastRefClassOnNull(ValueTypeTests.java:2156)
	... 24 more
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1003)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1579)
	at <unknown class>.<unknown method>(Unknown Source)
	... 35 more

...
...

FAILED: testAssortedRefWithSingleAlignment
java.lang.NullPointerException
	at org.openj9.test.lworld.ValueTypeTests.createAssorted(ValueTypeTests.java:2462)
	at org.openj9.test.lworld.ValueTypeTests.createAssorted(ValueTypeTests.java:2421)
	at org.openj9.test.lworld.ValueTypeTests.testAssortedRefWithSingleAlignment(ValueTypeTests.java:1641)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    ValueTypeTestsJIT
    Tests run: 99, Failures: 24, Skips: 0
===============================================


===============================================
Valhalla suite
Total tests run: 99, Failures: 24, Skips: 0
===============================================


ValueTypeTestsJIT_0_FAILED

```
Full console log is attached below:
[log_console_ ValueTypeTestsJIT_0_0910_01.txt](https://github.com/eclipse/openj9/files/5203494/log_console_.ValueTypeTestsJIT_0_0910_01.txt)

**Comment by a7ehuo** [comment]
Ran 50x `ValueTypeTestsJIT_1` which has `JVM_OPTIONS:  -Xjit:count=1,disableAsyncCompilation`, the same config as the old `ValueTypeTestsJIT_0`. All passed.

```
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.root.openj9-openjdk-jdk16)
Eclipse OpenJ9 VM (build master-3dcfa9804, JRE 16 Linux amd64-64-Bit Compressed References 20210225_000000 (JIT enabled, AOT enabled)
OpenJ9   - 3dcfa9804
OMR      - 116004c6a
JCL      - 96da0b31991 based on jdk-16+36)
make[2]: Entering directory '/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test'
make[3]: Entering directory '/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/functional'
make[4]: Entering directory '/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/functional/Valhalla'
```
