### ISSUE TITLE
Intermittent failure in ValueTypeTestsJIT_0: *** Invalid JIT return address 00000000FFFFFB98 in 0000000000019D10

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#10565]
Found a very intermittent failure in `ValueTypeTestsJIT_0`. The invalid JIT return address looks to be related to method `org/testng/internal/annotations/JDK15AnnotationFinder.findAnnotation(Ljava/lang/Class;Ljava/lang/annotation/Annotation;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/reflect/Constructor;Ljava/lang/reflect/Method;Lorg/testng/internal/collections/Pair;)Lorg/testng/annotations/IAnnotation; `

```
*** Invalid JIT return address 00000000FFFFFB98 in 0000000000019D10

15:11:53.599 0x19a00    j9vm.249    *   ** ASSERTION FAILED ** at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/swalk.c:1565: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/09/10 08:11:53 - please wait.
```

```
(gdb) bt
#0  0x00007fe7473392d1 in pthread_kill () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fe74571c29d in omrdump_create (portLibrary=0x7fe74690f320 <j9portLibrary>, 
    filename=0x7fe7471116b0 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/TKG/test_output_15997506937165/ValueTypeTestsJIT_0/", dumpType=<optimized out>, userData=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/omr/port/unix/omrosdump.c:188
#2  0x00007fe744fd3002 in doSystemDump (agent=0x7fe740026f80, 
    label=0x7fe7471116b0 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/TKG/test_output_15997506937165/ValueTypeTestsJIT_0/", context=0x7fe747111b70) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpagent.c:751
#3  0x00007fe744fcee35 in protectedDumpFunction (portLibrary=portLibrary@entry=0x7fe74690f320 <j9portLibrary>, 
    userData=userData@entry=0x7fe747111610)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpagent.c:2904
#4  0x00007fe74571dd43 in omrsig_protect (portLibrary=0x7fe74690f320 <j9portLibrary>, 
    fn=0x7fe744fcee20 <protectedDumpFunction>, fn_arg=0x7fe747111610, handler=0x7fe744fcee40 <signalHandler>, 
    handler_arg=0x0, flags=505, result=0x7fe747111608)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/omr/port/unix/omrsignal.c:425
#5  0x00007fe744fd246b in runDumpFunction (agent=<optimized out>, 
    label=0x7fe7471116b0 "/root/home/ahuo/src/openj9-openjdk-jdk8/openj9/test/TKG/test_output_15997506937165/ValueTypeTestsJIT_0/", context=<optimized out>) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpagent.c:2878
#6  0x00007fe744fd25ff in runDumpAgent (vm=vm@entry=0x7fe7400100c0, agent=agent@entry=0x7fe740026f80, 
    context=context@entry=0x7fe747111b70, state=state@entry=0x7fe747111b68, detail=detail@entry=0x7fe747111bf0 "", 
    timeNow=timeNow@entry=1599750713599) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rasdump/dmpagent.c:2804
#7  0x00007fe744fe9dab in triggerDumpAgents (vm=0x7fe7400100c0, self=0x19a00, eventFlags=524288, eventData=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rasdump/trigger.c:1045
#8  0x00007fe744db50dd in triggerHit (thr=thr@entry=0x1a388, compName=0x7fe74628f2d5 "j9vm", traceId=traceId@entry=249, 
    phase=phase@entry=AFTER_TRACEPOINT)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trctrigger.c:1333
#9  0x00007fe744da8977 in fireTriggerHit (thread=0x1a3f0, phase=AFTER_TRACEPOINT, traceId=249, compName=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trclog.c:2568
#10 raiseAssertion (traceId=4258051, modInfo=0x7fe7464c6340 <j9vm_UtModuleInfo>, thread=0x1a3f0)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trclog.c:2556
#11 logTracePoint (varArgs=0x7fe747111f88, spec=<optimized out>, traceId=<optimized out>, modInfo=<optimized out>, 
    thr=<optimized out>) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trclog.c:2131
#12 doTracePoint (thr=<optimized out>, modInfo=<optimized out>, traceId=<optimized out>, spec=<optimized out>, 
    varArgs=varArgs@entry=0x7fe747112088) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trclog.c:2207
#13 0x00007fe744da07bf in javaTrace (env=<optimized out>, modInfo=<optimized out>, traceId=<optimized out>, 
    spec=<optimized out>) at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/rastrace/trcengine.c:1311
#14 0x00007fe746193219 in invalidJITReturnAddress (walkState=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/swalk.c:1565
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007fe73fb41866 in jitWalkStackFrames (walkState=0x19d10)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/codert_vm/jswalk.c:283
#16 0x00007fe74619240e in walkStackFrames (currentThread=0x19a00, walkState=0x19d10)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/swalk.c:335
#17 0x00007fe7461b223e in VM_BytecodeInterpreterCompressed::inlThrowableFillInStackTrace (_pc=<optimized out>, 
    _sp=<optimized out>, this=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/BytecodeInterpreter.hpp:3001
#18 VM_BytecodeInterpreterCompressed::run (this=0x2124, this@entry=0x7fe747112630, vmThread=0x0)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/BytecodeInterpreter.hpp:9342
#19 0x00007fe7461a49d0 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/BytecodeInterpreter.inc:110
#20 0x00007fe7462081c2 in c_cInterpreter ()
    at /root/home/ahuo/src/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/vm/runtime/vm/xcinterp.s:160
#21 0x00007fe74613d46a in internalSendExceptionConstructor (currentThread=0x11, currentThread@entry=0x19a00, 
    exceptionClass=0x7fe747112838, exceptionClass@entry=0x6a300, exception=0xffe5e928, detailMessage=<optimized out>, 
    detailMessage@entry=0x0, constructorIndex=<optimized out>, constructorIndex@entry=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/callin.cpp:602
#22 0x00007fe7461543c1 in internalSetCurrentExceptionWithCause (cause=<optimized out>, utfMessage=<optimized out>, 
    detailMessage=0x0, exceptionNumber=<optimized out>, currentThread=0x19a00)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/exceptionsupport.c:725
#23 setCurrentExceptionWithUtfCause (currentThread=0x19a00, exceptionNumber=<optimized out>, detailMessage=<optimized out>, 
    utfMessage=<optimized out>, cause=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/vm/exceptionsupport.c:807
#24 0x00007fe73fb31c53 in setCurrentExceptionFromJIT (detailMessage=0x0, exceptionNumber=6, currentThread=0x19a00)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/codert_vm/cnathelp.cpp:391
#25 old_slow_jitHandleNullPointerExceptionTrap (currentThread=0x19a00)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/codert_vm/cnathelp.cpp:1376
#26 0x00007fe73fb47440 in jitHandleNullPointerExceptionTrap ()
    at /root/home/ahuo/src/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/vm/runtime/codert_vm/xnathelp.s:3929
#27 0x0000000000019a00 in ?? ()
#28 0x00007fe747112a80 in ?? ()
#29 0x00000000fffb5aa0 in ?? ()
#30 0x00000000ffe05d38 in ?? ()
#31 0x00000000ffe05d00 in ?? ()
#32 0x0000000500000000 in ?? ()
#33 0x00000000ffe5e908 in ?? ()
#34 0x00000000ffe05d38 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#35 0x0000000000019a00 in ?? ()
#36 0x00007fe74690f320 in ?? ()
   from /root/home/ahuo/src/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libjvm.so
#37 0x0000000000000001 in ?? ()
#38 0x000000008374e448 in ?? ()
#39 0x00000000ffe5e908 in ?? ()
#40 0xffffffffffffffff in ?? ()
#41 0x00000000ffe05d10 in ?? ()
#42 0x0000000100000000 in ?? ()
#43 0x0000000100000010 in ?? ()
#44 0x00000000ffe05d00 in ?? ()
#45 0x0000000000319920 in ?? ()
#46 0x00000000ffe06420 in ?? ()
#47 0x00007fe7471128f0 in ?? ()
#48 0xbfdfb26604773c69 in ?? ()
#49 0xbfb1973c5a611ccc in ?? ()
#50 0x000000003da83c90 in ?? ()
#51 0x000000003f800000 in ?? ()
#52 0x000000004741f800 in ?? ()
#53 0x007600610077002e in ?? ()
#54 0x0000000000000000 in ?? ()
(gdb) 

(gdb) fr 15
#15 0x00007fe73fb41866 in jitWalkStackFrames (walkState=0x19d10)
    at /root/home/ahuo/src/openj9-openjdk-jdk11/openj9/runtime/codert_vm/jswalk.c:283
283					walkState->walkThread->javaVM->internalVMFunctions->invalidJITReturnAddress(walkState);
(gdb) list -
278			 */
279			if (walkState->errorMode != J9_STACKWALK_ERROR_MODE_IGNORE) {
280				/* Avoid recursive error situations */
281				if (0 == (walkState->walkThread->privateFlags & J9_PRIVATE_FLAGS_STACK_CORRUPT)) {
282					walkState->walkThread->privateFlags |= J9_PRIVATE_FLAGS_STACK_CORRUPT;
283					walkState->walkThread->javaVM->internalVMFunctions->invalidJITReturnAddress(walkState);
284				}
285			}
286	i2jTransition: ;
287		}

(gdb) print *walkState
$2 = {previous = 0x0, walkThread = 0x19a00, flags = 336331008, bp = 0x10f1f0, unwindSP = 0x10f1f8, 
  pc = 0xfffffb98 "\244]\340\377", nextPC = 0x7fe724a0bdd7 ":", sp = 0x10f198, arg0EA = 0x10f230, literals = 0x10, 
  walkSP = 0x10f160, argCount = 8, constantPool = 0x1f2690, method = 0x1f3100, jitInfo = 0x0, frameFlags = 0, 
  resolveFrameFlags = 0, skipCount = 0, maxFrames = 1, userData1 = 0x0, userData2 = 0x8377e650, userData3 = 0x0, 
  userData4 = 0x0, framesWalked = 1, 
  frameWalkFunction = 0x7fe746181930 <cInterpGetStackClassJEP176Iterator(J9VMThread*, J9StackWalkState*)>, 
  objectSlotWalkFunction = 0x0, returnAddressWalkFunction = 0x0, cache = 0x108410, restartPoint = 0xfffffffffffffffb, 
  restartException = 0xffe5e928, inlinerMap = 0x0, inlineDepth = 0, cacheCursor = 0x108418, decompilationRecord = 0x0, 
  registerEAs = {jit_rax = 0x0, jit_rbx = 0x10f520, jit_rcx = 0x0, jit_rdx = 0x0, jit_rdi = 0x0, jit_rsi = 0x0, 
    jit_rbp = 0x0, jit_rsp = 0x0, jit_r8 = 0x0, jit_r9 = 0x10f558, jit_r10 = 0x10f550, jit_r11 = 0x10f548, 
    jit_r12 = 0x10f540, jit_r13 = 0x10f538, jit_r14 = 0x10f530, jit_r15 = 0x10f528}, 
  walkedEntryLocalStorage = 0x7fe747112aa0, i2jState = 0x7fe747112ab0, decompilationStack = 0x0, pcAddress = 0x10f1f0, 
  outgoingArgCount = 0, objectSlotBitVector = 0x0, elsBitVector = 0, savedObjectSlotWalkFunction = 0x0, 
  bytecodePCOffset = -1, dropToCurrentFrame = 0x7fe73fb40b00 <jitDropToCurrentFrame>, j2iFrame = 0x0, 
  previousFrameFlags = 524288, slotIndex = 0, slotType = 0, currentThread = 0x19a00, linearSlotWalker = 0x0, errorMode = 0, 
  inlinedCallSite = 0x0, stackMap = 0x0, inlineMap = 0x0}
(gdb) print walkState->method
$3 = (struct J9Method *) 0x1f3100
```

```
> !j9method 0x1f3100
J9Method at 0x1f3100 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00007FE74024EC48
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x00000000001F2690 (flags = 0x0)
	0x10: void* methodRunAddress = !j9x 0x0000000000000018
	0x18: void* extra = !j9x 0x00007FE724A0BB48
}
Signature: org/testng/internal/annotations/JDK15AnnotationFinder.findAnnotation(Ljava/lang/Class;Ljava/lang/annotation/Annotation;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/reflect/Constructor;Ljava/lang/reflect/Method;Lorg/testng/internal/collections/Pair;)Lorg/testng/annotations/IAnnotation; !bytecodes 0x00000000001F3100
ROM Method: !j9rommethod 0x00007FE74024EC34
Next Method: !j9method 0x00000000001F3120

>  !j9rommethod 0x00007FE74024EC34
J9ROMMethod at 0x7fe74024ec34 {
  Fields for J9ROMMethod:
	0x0: struct J9ROMNameAndSignature nameAndSignature = !j9romnameandsignature 0x00007FE74024EC34
	0x8: U32 modifiers = 0x13040002 (319029250)
	0xc: U16 maxStack = 0x0006 (6)
	0xe: U16 bytecodeSizeLow = 0x004A (74)
	0x10: U8 bytecodeSizeHigh = 0x00 (0)
	0x11: U8 argCount = 0x08 (8)
	0x12: U16 tempCount = 0x0001 (1)
}
Signature: findAnnotation(Ljava/lang/Class;Ljava/lang/annotation/Annotation;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/reflect/Constructor;Ljava/lang/reflect/Method;Lorg/testng/internal/collections/Pair;)Lorg/testng/annotations/IAnnotation;
Next ROM Method: !j9rommethod 0x7fe74024ecc0
> 

(kca) j9method 0x1f3100
Method   {ClassPath/Name.MethodName}: {org/testng/internal/annotations/JDK15AnnotationFinder.findAnnotation}
                           Signature: (Ljava/lang/Class;Ljava/lang/annotation/Annotation;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/reflect/Constructor;Ljava/lang/reflect/Method;Lorg/testng/internal/collections/Pair;)Lorg/testng/annotations/IAnnotation;
                              Access: Private 
                    J9Class/J9Method: 0x00000000001f2e00 / 0x00000000001f3100
               Compiled Method Start: 0x00007fe724a0bb48 (953 bytes)
                      ByteCode Start: 0x00007fe74024ec48 (74 bytes)
                   ROM Constant Pool: 0x00007fe74024e208 (107 entries)
                       Constant Pool: 0x00000000001f2690 (0 entries)
(kca) 
```

**Comment by a7ehuo** [comment]
I have not been able to reproduce this issue with the latest code in value types. closing it.
