### ISSUE TITLE
JDK16 TEST: java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10581]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Nightly/288`:
```
22:25:25  openjdk version "16-internal" 2021-03-16
22:25:25  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64lelinuxNightly)
22:25:25  Eclipse OpenJ9 VM (build master-5ef8df8f481, JRE 16 Linux ppc64le-64-Bit Compressed References 20200910_326 (JIT enabled, AOT enabled)
22:25:25  OpenJ9   - 5ef8df8f481
22:25:25  OMR      - 58b0c18383a
22:25:25  JCL      - 15ca9bbabd5 based on jdk-16+14)
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:03:39  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:36:18  --------------------------------------------------
22:39:13  TEST: java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java

22:39:13  test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@3eab360): failure
22:39:13  java.lang.AssertionError: expected [true] but found [false]
22:39:13  	at org.testng.Assert.fail(Assert.java:94)
22:39:13  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:39:13  	at org.testng.Assert.assertTrue(Assert.java:42)
22:39:13  	at org.testng.Assert.assertTrue(Assert.java:52)
22:39:13  	at SealedClassesReflectionTest.testSealedClasses(SealedClassesReflectionTest.java:87)
22:39:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:39:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:39:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:39:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:39:13  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:39:13  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:39:13  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:39:13  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
22:39:13  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
22:39:13  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
22:39:13  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
22:39:13  	at org.testng.TestRunner.run(TestRunner.java:623)
22:39:13  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
22:39:13  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
22:39:13  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
22:39:13  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
22:39:13  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
22:39:13  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
22:39:13  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
22:39:13  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
22:39:13  	at org.testng.TestNG.run(TestNG.java:1018)
22:39:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:39:13  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:39:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:39:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:39:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:39:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:39:13  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:39:13  	at java.base/java.lang.Thread.run(Thread.java:845)
22:39:13  ===============================================
22:39:13  java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java
22:39:13  Total tests run: 58, Failures: 20, Skips: 0
22:39:13  ===============================================
```

**Comment by ChengJin01** [comment]
It seems the test failed at
```
   @Test(dataProvider = "sealedClasses")
    public void testSealedClasses(Class<?> cls) {
        assertTrue(cls.isSealed());   <---------------------------------
        assertTrue(!Modifier.isFinal(cls.getModifiers()));
        assertTrue(cls.permittedSubclasses() != null);
        assertTrue(cls.permittedSubclasses().length > 0);
    }
```

I suspect the reason for this is that these flags were disabled in Java 15 temporarily (in the preview status).

@JasonFengJ9,  please help verify the failing test here to see whether https://github.com/eclipse/openj9/pull/11203 (just merged) works to fix the issue.  I will take a look if it still fails with the PR.

**Comment by JasonFengJ9** [comment]
From last night build `Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Nightly/345`, `openjdk-tests/TKG/test_output_16055832441665/jdk_lang_j9_0/work/java/lang/reflect/sealed_classes/SealedClassesReflectionTest.jtr ` has content as following:

```
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@20b9cf94): failure
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at SealedClassesReflectionTest.testSealedClasses(SealedClassesReflectionTest.java:87)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:773)
        at org.testng.TestRunner.run(TestRunner.java:623)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
        at org.testng.SuiteRunner.run(SuiteRunner.java:259)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1018)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:844)

```

test SealedClassesReflectionTest.testnon_sealedClasses(java.lang.Class@159594c6): failure
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at SealedClassesReflectionTest.testnon_sealedClasses(SealedClassesReflectionTest.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:773)
        at org.testng.TestRunner.run(TestRunner.java:623)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
        at org.testng.SuiteRunner.run(SuiteRunner.java:259)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1018)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:844)
```
===============================================
java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java
Total tests run: 58, Failures: 20, Skips: 0
===============================================

**Comment by ChengJin01** [comment]
I compile a JDK16 build (https://github.com/ibmruntimes/openj9-openjdk-jdk) with the latest update on OpenJ9 & OMR on a `ppc64le_Linux` machine and tried to reproduce the issue locally by manually running over 10 times but all test cases in `SealedClassesReflectionTest.java` passed without any exception.
[SealedClassesReflectionTest.jtr.txt](https://github.com/eclipse/openj9/files/5562846/SealedClassesReflectionTest.jtr.txt)

```
#section:script_messages
----------messages:(7/393)----------
JDK under test: /root/docker_openj9_2/jdk16_internal_openj9_v0
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc..openj9-openjdk-jdk16)
Eclipse OpenJ9 VM (build master-c40cf2f, JRE 16 Linux ppc64le-64-Bit Compressed References 20201118_000000 (JIT enabled, AOT enabled)
OpenJ9   - c40cf2f
OMR      - 70484c4
JCL      - 1587e2b based on jdk-16+23)
...
[TestNG] Running:
  java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java

test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Object): success
test SealedClassesReflectionTest.testNotSealedClasses(void): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Void): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Void;): success
test SealedClassesReflectionTest.testNotSealedClasses(byte): success
test SealedClassesReflectionTest.testNotSealedClasses(class [B): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Byte): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Byte;): success
test SealedClassesReflectionTest.testNotSealedClasses(short): success
test SealedClassesReflectionTest.testNotSealedClasses(class [S): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Short): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Short;): success
test SealedClassesReflectionTest.testNotSealedClasses(char): success
test SealedClassesReflectionTest.testNotSealedClasses(class [C): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Character): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Character;): success
test SealedClassesReflectionTest.testNotSealedClasses(int): success
test SealedClassesReflectionTest.testNotSealedClasses(class [I): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Integer): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Integer;): success
test SealedClassesReflectionTest.testNotSealedClasses(long): success
test SealedClassesReflectionTest.testNotSealedClasses(class [J): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Long): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Long;): success
test SealedClassesReflectionTest.testNotSealedClasses(float): success
test SealedClassesReflectionTest.testNotSealedClasses(class [F): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Float): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Float;): success
test SealedClassesReflectionTest.testNotSealedClasses(double): success
test SealedClassesReflectionTest.testNotSealedClasses(class [D): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Double): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Double;): success
test SealedClassesReflectionTest.testNotSealedClasses(boolean): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Z): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.Boolean): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.Boolean;): success
test SealedClassesReflectionTest.testNotSealedClasses(class java.lang.String): success
test SealedClassesReflectionTest.testNotSealedClasses(class [Ljava.lang.String;): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@c4682f57): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@67ff8898): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@2c1c8186): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@b7bed823): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@6f647a26): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@da611fef): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@966fbaed): success
test SealedClassesReflectionTest.testSealedClasses(java.lang.Class@e5f1e397): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@c4682f57, 2, [Ljava.lang.String;@12306f14, [Ljava.lang.Class;@6945c39d, [LSealedClassesReflectionTest$SealedStatus;@1b7eacc1): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@67ff8898, 2, [Ljava.lang.String;@ecd0adcb, [Ljava.lang.Class;@c977ddf4, [LSealedClassesReflectionTest$SealedStatus;@b288d5f2): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@2c1c8186, 2, [Ljava.lang.String;@93ec8d4b, [Ljava.lang.Class;@3e422b69, [LSealedClassesReflectionTest$SealedStatus;@cbc35353): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@b7bed823, 1, [Ljava.lang.String;@4ac975e2, [Ljava.lang.Class;@6b90b190, [LSealedClassesReflectionTest$SealedStatus;@57185dd1): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@6f647a26, 2, [Ljava.lang.String;@ee2bb160, [Ljava.lang.Class;@5f45728a, [LSealedClassesReflectionTest$SealedStatus;@3f3688ec): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@da611fef, 2, [Ljava.lang.String;@9a060ac4, [Ljava.lang.Class;@d3e2dffa, [LSealedClassesReflectionTest$SealedStatus;@4eeb40f3): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@966fbaed, 3, [Ljava.lang.String;@2cb18e56, [Ljava.lang.Class;@9fcb022f, [LSealedClassesReflectionTest$SealedStatus;@3aab6446): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@e5f1e397, 1, [Ljava.lang.String;@91067e9c, [Ljava.lang.Class;@6120a367, [LSealedClassesReflectionTest$SealedStatus;@21ad7721): success
test SealedClassesReflectionTest.testSealedReflection(java.lang.Class@22bd15c0, 1, [Ljava.lang.String;@830ca160, [Ljava.lang.Class;@f0614792, [LSealedClassesReflectionTest$SealedStatus;@ffb875b3): success
test SealedClassesReflectionTest.testnon_sealedClasses(java.lang.Class@1314656e): success
test SealedClassesReflectionTest.testnon_sealedClasses(java.lang.Class@e79f14): success
test SealedClassesReflectionTest.testnon_sealedClasses(java.lang.Class@5f7af935): success

===============================================
java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java
Total tests run: 58, Failures: 0, Skips: 0
```

So I suspect the nightly build above didn't pick up the latest changes in OpenJ9.

@JasonFengJ9,  please double-check again to see how it goes.

**Comment by JasonFengJ9** [comment]
Latest nightly build passed `SealedClassesReflectionTest` at `Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Nightly/98`.

```
openjdk-tests/TKG/test_output_16057595878409/jdk_lang_j9_0/work/java/lang/reflect/sealed_classes/SealedClassesReflectionTest.jtr

===============================================
java/lang/reflect/sealed_classes/SealedClassesReflectionTest.java
Total tests run: 58, Failures: 0, Skips: 0
===============================================
```
