### ISSUE TITLE
JDK16 TEST: java/lang/StringBuilder/HugeCapacity.java failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10582]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Nightly/288`:
```
22:25:25  openjdk version "16-internal" 2021-03-16
22:25:25  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64lelinuxNightly)
22:25:25  Eclipse OpenJ9 VM (build master-5ef8df8f481, JRE 16 Linux ppc64le-64-Bit Compressed References 20200910_326 (JIT enabled, AOT enabled)
22:25:25  OpenJ9   - 5ef8df8f481
22:25:25  OMR      - 58b0c18383a
22:25:25  JCL      - 15ca9bbabd5 based on jdk-16+14)
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:03:39  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:39:30  --------------------------------------------------
22:39:41  TEST: java/lang/StringBuilder/HugeCapacity.java

22:39:41  STDERR:
22:39:41  java.lang.OutOfMemoryError: Required length exceeds implementation limit
22:39:41  	at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:259)
22:39:41  	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:229)
22:39:41  	at java.base/java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:213)
22:39:41  	at java.base/java.lang.StringBuilder.ensureCapacity(StringBuilder.java:87)
22:39:41  	at HugeCapacity.testLatin1(HugeCapacity.java:49)
22:39:41  	at HugeCapacity.main(HugeCapacity.java:37)
22:39:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:39:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:39:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:39:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:39:41  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:39:41  	at java.base/java.lang.Thread.run(Thread.java:845)
22:39:41  java.lang.RuntimeException: 1 tests failed
22:39:41  	at HugeCapacity.main(HugeCapacity.java:42)
22:39:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:39:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:39:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:39:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:39:41  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:39:41  	at java.base/java.lang.Thread.run(Thread.java:845)
22:39:41 
```

**Comment by pshipton** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-tests/pull/2141 to perm exclude the test.
