### ISSUE TITLE
jdk-15+36: TestJlmRemote/TestIBMJlmRemote fail JVM exits

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10592]
Failure link
------------
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.system_aarch64_linux_xl/22/consoleFull
Tests:
15:16:26 TestJlmRemoteClassAuth_0
15:16:26 TestJlmRemoteMemoryAuth_0
15:16:26 TestJlmRemoteNotifierProxyAuth_0
15:16:26 TestIBMJlmRemoteClassAuth_0
15:16:26 TestIBMJlmRemoteMemoryAuth_0

Failure output (captured from console output)
---------------------------------------------
```
13:49:15  CL1 ..j> 2020/09/11 12:49:12.407 Exiting as JVM we are connected to has finished
13:49:15  CL1 stderr Exception in thread "main" java.lang.AssertionError: Exiting as JVM we are connected to has finished
13:49:15  CL1 stderr 	at org.junit.Assert.fail(Assert.java:88)
13:49:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:179)
13:49:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
13:49:15  STF 12:49:12.747 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
13:49:15  STF 12:49:12.748 - Monitoring Report Summary:
13:49:15  STF 12:49:12.748 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
13:49:15  STF 12:49:12.748 -   o Process LT1 is still running as expected
13:49:15  STF 12:49:12.749 - Killing processes: CL1 LT1
13:49:25  STF 12:49:23.752 -   o Process LT1 killed
13:49:25  STF 12:49:23.752 -   o Process CL1 is not running
13:49:25  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk15_j9_sanity.system_aarch64_linux_xl/openjdk-tests/TKG/../TKG/test_output_15998283008076/TestJlmRemoteClassAuth_0/20200911-124824-TestJlmRemoteClassAuth/execute.pl line 174.
13:49:25  STF 12:49:24.090 - **FAILED** execute script failed. Expected return value=0 Actual=1

```

**Comment by lumpfish** [comment]
This is fixed by https://github.com/eclipse/openj9-systemtest/pull/118

**Comment by pshipton** [comment]
These system failures didn't occur again in the jdk15 release testing last night.
https://ci.eclipse.org/openj9/job/Pipeline-Release-0.22.0-Build15/4/
The nightly builds for jdk8 and jdk11 also look good, closing as resolved.
