### ISSUE TITLE
openjdk jdk15 defineHiddenClass/BasicTest defineHiddenClass/TypeDescriptorTest failures

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10611]
https://ci.eclipse.org/openj9/job/Pipeline-Release-0.22.0-Build15/4/
java/lang/invoke/defineHiddenClass/BasicTest.java
```
00:25:22  java.lang.AssertionError: expected [true] but found [false]
00:25:22  	at org.testng.Assert.fail(Assert.java:94)
00:25:22  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:22  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:22  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:22  	at BasicTest.hiddenClass(BasicTest.java:124)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:22  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:22  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:22  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:22  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:22  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:22  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:22  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:22  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:22  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:22  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:22  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:22  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:22  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:22  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:22  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:22  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:22  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:22  	at java.base/java.lang.Thread.run(Thread.java:851)
```
java/lang/invoke/defineHiddenClass/TypeDescriptorTest.java
```
00:25:28  test test.TypeDescriptorTest.testToMethodDescriptorString(()HiddenClass/00000000102EC890, "\(\)Ltest/HiddenClass.0x[0-9a-f]+;"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testToMethodDescriptorString(TypeDescriptorTest.java:161)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testToMethodDescriptorString(java.lang.invoke.MethodType@6b631cb4, "\(\[\[Ltest/HiddenClass.0x[0-9a-f]+;\)V"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testToMethodDescriptorString(TypeDescriptorTest.java:161)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testToMethodDescriptorString(java.lang.invoke.MethodType@e5821347, "\(ILtest/HiddenClass.0x[0-9a-f]+;\)V"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testToMethodDescriptorString(TypeDescriptorTest.java:161)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testTypeDescriptor(java.lang.Class@6dec4464, "Ltest/HiddenClass.0x[0-9a-f]+;"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testTypeDescriptor(TypeDescriptorTest.java:130)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testTypeDescriptor(java.lang.Class@9a04b8a6, "\[\[Ltest/HiddenClass.0x[0-9a-f]+;"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testTypeDescriptor(TypeDescriptorTest.java:130)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testTypeDescriptor(()HiddenClass/00000000102EC890, "\(\)Ltest/HiddenClass.0x[0-9a-f]+;"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testTypeDescriptor(TypeDescriptorTest.java:130)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testTypeDescriptor(java.lang.invoke.MethodType@abc7eb7f, "\(Ltest/HiddenClass.0x[0-9a-f]+;\)V"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testTypeDescriptor(TypeDescriptorTest.java:130)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:28  test test.TypeDescriptorTest.testTypeDescriptor(java.lang.invoke.MethodType@a9517d2b, "\(Ltest/HiddenClass.0x[0-9a-f]+;ILjava/lang/Object;\)V"): failure
00:25:28  java.lang.AssertionError: expected [true] but found [false]
00:25:28  	at org.testng.Assert.fail(Assert.java:94)
00:25:28  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:28  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:28  	at test.TypeDescriptorTest.testTypeDescriptor(TypeDescriptorTest.java:130)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:28  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:28  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:28  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:28  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:28  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:28  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:28  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:28  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:28  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:28  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:28  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:28  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:28  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:28  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:28  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:28  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:28  	at java.base/java.lang.Thread.run(Thread.java:851)
```

**Comment by pshipton** [comment]
Tests were re-included by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1960
@tajila are the failures in the jdk15 release stream expected, or did we miss delivering a change to this stream?

**Comment by DanHeidinga** [comment]
The failures are expected.  Given how close to the release we were, I opted not to ask for a port of this change

**Comment by pshipton** [comment]
Closing as a known issue in the jdk15 0.22 release.
