### ISSUE TITLE
JDK15 release build : test BasicTest.hiddenClass(): failure - java.lang.AssertionError: expected [true] but found [false]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10632]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Release/4/consoleFull
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
01:41:11  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
00:25:22  --------------------------------------------------
00:25:22  TEST: java/lang/invoke/defineHiddenClass/BasicTest.java
00:25:22  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Release/openjdkbinary/j2sdk-image
00:25:22  
00:25:22  test BasicTest.hiddenClass(): failure
00:25:22  java.lang.AssertionError: expected [true] but found [false]
00:25:22  	at org.testng.Assert.fail(Assert.java:94)
00:25:22  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:25:22  	at org.testng.Assert.assertTrue(Assert.java:42)
00:25:22  	at org.testng.Assert.assertTrue(Assert.java:52)
00:25:22  	at BasicTest.hiddenClass(BasicTest.java:124)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:22  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:25:22  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:25:22  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:25:22  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:25:22  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:25:22  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:25:22  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:25:22  	at org.testng.TestRunner.run(TestRunner.java:623)
00:25:22  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:25:22  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:25:22  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:25:22  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:25:22  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:25:22  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:25:22  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:25:22  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:25:22  	at org.testng.TestNG.run(TestNG.java:1018)
00:25:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:25:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:25:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:25:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:25:22  	at java.base/java.lang.Thread.run(Thread.java:851)
00:25:22  test BasicTest.lessPrivilegedLookup(): success
00:25:22  test BasicTest.primitiveClass(): success
00:25:22  test BasicTest.testHiddenNestHost(): success
00:25:22  test BasicTest.testLambda(): success
00:25:22  
00:25:22  ===============================================
00:25:22  java/lang/invoke/defineHiddenClass/BasicTest.java
00:25:22  Total tests run: 34, Failures: 1, Skips: 0
00:25:22  ===============================================
```

Occurred at zLinux platform as well https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_s390x_linux_xl_Release/4/.

**Comment by hangshao0** [comment]
See https://github.com/eclipse/openj9/issues/10633#issuecomment-694305495

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse/openj9/issues/10611
