### ISSUE TITLE
JDK16 java/lang/String/CompactString/CompareToIgnoreCase.java : test CompareToIgnoreCase.testCompareToIgnoreCase("???A", "???a", 0): failure

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10649]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_s390x_linux_xl_Nightly/167`:
```
22:24:00  openjdk version "16-internal" 2021-03-16
22:24:00  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxxlNightly)
22:24:00  Eclipse OpenJ9 VM (build master-149dd6186ef, JRE 16 Linux s390x-64-Bit 20200917_189 (JIT enabled, AOT enabled)
22:24:00  OpenJ9   - 149dd6186ef
22:24:00  OMR      - 25e93bed006
22:24:00  JCL      - 2e50335fca8 based on jdk-16+15)
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:19:03  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=s390x_linux_xl&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
22:42:10  test CompareToIgnoreCase.testCompareToIgnoreCase("A?", "a?", -1): success
22:42:10  test CompareToIgnoreCase.testCompareToIgnoreCase("???A", "???a", 0): failure
22:42:10  java.lang.AssertionError: testing String(\ud801\udc00\ud801\udc01\uff21A).compareToIgnoreCase(\ud801\udc28\ud801\udc29\uff41a), source : source from byte array with charset,  expected [0] but found [-40]
22:42:10  	at org.testng.Assert.fail(Assert.java:94)
22:42:10  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:42:10  	at org.testng.Assert.assertEquals(Assert.java:125)
22:42:10  	at org.testng.Assert.assertEquals(Assert.java:372)
22:42:10  	at CompareToIgnoreCase.lambda$testCompareToIgnoreCase$0(CompareToIgnoreCase.java:81)
22:42:10  	at CompareToIgnoreCase$$Lambda$12/0x00000000b5d3df20.accept(Unknown Source)
22:42:10  	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
22:42:10  	at CompareToIgnoreCase.testCompareToIgnoreCase(CompareToIgnoreCase.java:79)
22:42:10  	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
22:42:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:42:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:42:10  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:42:10  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:42:10  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:42:10  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
22:42:10  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
22:42:10  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
22:42:10  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
22:42:10  	at org.testng.TestRunner.run(TestRunner.java:623)
22:42:10  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
22:42:10  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
22:42:10  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
22:42:10  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
22:42:10  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
22:42:10  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
22:42:10  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
22:42:10  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
22:42:10  	at org.testng.TestNG.run(TestNG.java:1018)
22:42:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:42:10  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:42:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:42:10  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
22:42:10  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:42:10  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
22:42:10  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:42:10  	at java.base/java.lang.Thread.run(Thread.java:845)

22:42:10  ===============================================
22:42:10  java/lang/String/CompactString/CompareToIgnoreCase.java
22:42:10  Total tests run: 28, Failures: 2, Skips: 0
22:42:10  ===============================================
```

Similar failures:
```
22:42:16  test EqualsIgnoreCase.testEqualsIgnoreCase("???A", "???a", true): failure
22:42:16  java.lang.AssertionError: testing String(\ud801\udc00\ud801\udc01\uff21A).equalsIgnoreCase(\ud801\udc28\ud801\udc29\uff41a), source : source from byte array with charset,  expected [true] but found [false]
22:42:16  	at org.testng.Assert.fail(Assert.java:94)
22:42:16  	at org.testng.Assert.failNotEquals(Assert.java:496)

22:42:29  test RegionMatches.testRegionMatches("???A", true, 0, "??", 0, 4, true): failure
22:42:29  java.lang.AssertionError: testing String(\ud801\udc00\ud801\udc01\uff21A).regionMatches(true, 0, \ud801\udc28\ud801\udc29, 0, 4), source : source from byte array with charset,  expected [true] but found [false]
22:42:29  	at org.testng.Assert.fail(Assert.java:94)
22:42:29  	at org.testng.Assert.failNotEquals(Assert.java:496)
```

**Comment by pshipton** [comment]
Test is passing now, I expect this was resolved by https://github.com/eclipse/openj9/pull/11061
