### ISSUE TITLE
java/lang/invoke/InvokeDynamicPrintArgs.java: IncompatibleClassChangeError

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10684]
Failure link
------------
jdk8u272-b08_openj9-0.23.0-m1
Platform: aarch64
test case: sanity.openjdk : java/lang/invoke/InvokeDynamicPrintArgs.java
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/51/console

```
00:20:42  An exception has occurred in the compiler (1.8.0_272). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
00:20:42  java.lang.IncompatibleClassChangeError
00:20:42  	at com.sun.tools.javac.comp.Infer$InferenceContext.notifyChange(Infer.java:2119)
00:20:42  	at com.sun.tools.javac.comp.Infer$InferenceContext.notifyChange(Infer.java:2113)
00:20:42  	at com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:210)
00:20:42  	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:567)
00:20:42  	at com.sun.tools.javac.comp.Resolve.checkMethod(Resolve.java:604)
00:20:42  	at com.sun.tools.javac.comp.Attr.checkMethod(Attr.java:3829)
00:20:42  	at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3616)
00:20:42  	at com.sun.tools.javac.comp.Attr.checkMethodIdInternal(Attr.java:3527)
00:20:42  	at com.sun.tools.javac.comp.Attr.checkMethodId(Attr.java:3502)
00:20:42  	at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3489)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3371)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1075)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
00:20:42  	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
00:20:42  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
00:20:42  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
00:20:42  	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
00:20:42  	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
00:20:42  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
00:20:42  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
00:20:42  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
00:20:42  	at com.sun.tools.javac.main.Main.compile(Main.java:381)
00:20:42  	at com.sun.tools.javac.main.Main.compile(Main.java:370)
00:20:42  	at com.sun.tools.javac.main.Main.compile(Main.java:361)
00:20:42  	at com.sun.tools.javac.Main.compile(Main.java:74)
00:20:42  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
00:20:42  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:20:42  	at java.lang.reflect.Method.invoke(Method.java:498)
00:20:42  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
00:20:42  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
00:20:42  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
00:20:42  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
00:20:42  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
00:20:42  
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
Possibly related to Issue #10413, which is also failing in the Java method `com.sun.tools.javac.comp.Infer$InferenceContext.notifyChange()` in Java 8.

**Comment by koppor** [comment]
I have a similar issue

```text
   java.lang.IncompatibleClassChangeError: class com/google/common/collect/AbstractMultimap$EntrySet has conflicting defaults for method stream()Ljava/util/stream/Stream;
      at org.jabref.logic.texparser.LatexParserTest.testTwoFilesDifferentDatabases(LatexParserTest.java:142)
```

OpenJDK 14.0.2 - OpenJ9; full build log: https://github.com/koppor/jabref/pull/481/checks?check_run_id=1745595249

Should I file a seperate bug report with a MWE?

**Comment by knn-k** [comment]
@koppor The `IncompatibleClassChangeError` in this issue is an intermittent JIT problem that is specific to AArch64 platform.  What is your target platform?  It that is not AArch64, please open a separate issue.
