### ISSUE TITLE
openjdk PlatformLoggerTest unexpected null

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10759]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/162
sun/util/logging/PlatformLoggerTest.java
cent7-ppcle-2
```
Oct 01, 2020 2:51:13 AM PlatformLoggerTest testLogMethods
INFO: Test info(String)
java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected WARNING
	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_mac_Nightly/153
```
01:20:33  Jan 08, 2021 1:20:28 AM PlatformLoggerTest testLogMethods
01:20:33  INFO: Test info(String)
01:20:33  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINER
01:20:33  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
01:20:33  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
01:20:33  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
01:20:33  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:20:33  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
01:20:33  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:20:33  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
01:20:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:20:33  	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_s390x_linux_Nightly/168
```
00:55:53  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINER
00:55:53  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
00:55:53  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/65
```
java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINEST
	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
```

**Comment by pshipton** [comment]
See also https://github.com/eclipse-openj9/openj9/issues/13616

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_OpenJDK11/27
```
04:54:26  May 26, 2022 4:54:21 AM PlatformLoggerTest testLogMethods
04:54:26  INFO: Test info(String)
04:54:26  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINER
04:54:26  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
04:54:26  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
04:54:26  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly/176
jdk_util_1 
sun/util/logging/PlatformLoggerTest.java
```
09:42:37  May 27, 2022 9:42:25 AM PlatformLoggerTest testLogMethods
09:42:37  INFO: Test info(String)
09:42:37  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected OFF
09:42:37  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
09:42:37  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
09:42:37  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Release/27
jdk_util_1
sun/util/logging/PlatformLoggerTest.java

```
05:52:38  INFO: Test info(String)
05:52:38  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected ALL
05:52:38  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
05:52:38  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
05:52:38  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
```

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_1/111/)
```
openjdk version "11.0.16" 2022-07-19
IBM Semeru Runtime Open Edition 11.0.16.0 (build 11.0.16+8)
Eclipse OpenJ9 VM 11.0.16.0 (build openj9-0.33.0, JRE 11 Linux aarch64-64-Bit Compressed References 20220804_463 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - ab74d97849 based on jdk-11.0.16+8)

[2022-08-04T19:52:41.044Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-08-04T19:52:41.044Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-08-04T20:08:55.597Z] TEST: sun/util/logging/PlatformLoggerTest.java

[2022-08-04T20:08:55.599Z] java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE
[2022-08-04T20:08:55.599Z] 	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
[2022-08-04T20:08:55.599Z] 	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
[2022-08-04T20:08:55.599Z] 	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
[2022-08-04T20:08:55.599Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-08-04T20:08:55.599Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-08-04T20:08:55.599Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-08-04T20:08:55.599Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-08-04T20:08:55.599Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-08-04T20:08:55.599Z] 	at java.base/java.lang.Thread.run(Thread.java:840)
[2022-08-04T20:08:55.599Z] 
[2022-08-04T20:08:55.599Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE

[2022-08-04T20:09:36.962Z] jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/289/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_Nightly/18

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_Nightly/340
jdk_util_1
sun/util/logging/PlatformLoggerTest.java
```
22:37:42  STDOUT:
22:37:42  Testing Java Level with: ALL
22:37:42  Effective Java Level used is: ALL
22:37:42  Testing Java Level with: CONFIG
22:37:42  Effective Java Level used is: 693
22:37:42  Testing Java Level with: FINE
22:37:42  Effective Java Level used is: 493
22:37:42  Testing Java Level with: FINER
22:37:42  Effective Java Level used is: 393
22:37:42  Testing Java Level with: FINEST
22:37:42  Effective Java Level used is: 293
22:37:42  Testing Java Level with: INFO
22:37:42  Effective Java Level used is: 793
22:37:42  Testing Java Level with: OFF
22:37:42  Effective Java Level used is: OFF
22:37:42  Testing Java Level with: SEVERE
22:37:42  Effective Java Level used is: 993
22:37:42  Testing Java Level with: WARNING
22:37:42  Effective Java Level used is: 893
STDERR:
...
22:37:42  Jan 10, 2023 3:37:38 AM PlatformLoggerTest testLogMethods
22:37:42  INFO: Test info(String)
22:37:42  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected WARNING
22:37:42  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
22:37:42  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
22:37:42  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release_testList_2/5/consoleFull
```
11:30:28  java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE
11:30:28  	at PlatformLoggerTest.checkJavaLoggerLevel(PlatformLoggerTest.java:237)
11:30:28  	at PlatformLoggerTest.checkPlatformLoggerLevels(PlatformLoggerTest.java:175)
11:30:28  	at PlatformLoggerTest.main(PlatformLoggerTest.java:84)
11:30:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:30:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:30:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:30:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:30:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:30:28  	at java.base/java.lang.Thread.run(Thread.java:839)
11:30:28  
11:30:28  JavaTest Message: Test threw exception: java.lang.RuntimeException: Retrieved backing PlatformLogger level null is not the expected FINE
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly_testList_2/59/
