### ISSUE TITLE
openjdk System/finalization/FinThreads hang in runFinalizationImpl

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10752]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_xl_Nightly/169
Note this run also had other issues #8972
java/lang/System/finalization/FinThreads.java
ub18-390-2
```
00:30:11  JavaTest Message: Problem cleaning up the following threads:
00:30:11  AgentVMThread
00:30:11    at java.base/java.lang.ref.Finalizer.runFinalizationImpl(Native Method)
00:30:11    at java.base/java.lang.ref.Finalizer.runFinalization(Finalizer.java:29)
00:30:11    at java.base/java.lang.ref.Reference$1.runFinalization(Reference.java:63)
00:30:11    at java.base/java.lang.Runtime.runFinalization(Runtime.java:681)
00:30:11    at java.base/java.lang.System.runFinalization(System.java:608)
00:30:11    at FinThreads.main(FinThreads.java:120)
00:30:11    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:30:11    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:30:11    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:30:11    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:30:11    at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:30:11    at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by dmitripivkine** [comment]
The source of the test: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/System/finalization/FinThreads.java

Finalizer thread is sleeping at (FinThreads.java:73):
```
00:30:11  "Finalizer thread" prio=5 Id=13 TIMED_WAITING
00:30:11  	at java.base@11.0.9-internal/java.lang.Thread.sleep(Native Method)
00:30:11  	at java.base@11.0.9-internal/java.lang.Thread.sleep(Thread.java:966)
00:30:11  	at app//FinThreads$Foo.finalize(FinThreads.java:73)
00:30:11  	at java.base@11.0.9-internal/java.lang.J9VMInternals.runFinalize(J9VMInternals.java:322)
```
There are two `FinThreads$Foo` alive objects around, each of them can be associated with `Foo.create(true);`:
```
> !j9object 0x3ff9803fd08
!J9Object 0x000003FF9803FD08 {
	struct J9Class* clazz = !j9class 0x3FEF4022800 // FinThreads$Foo
	Object flags = 0x00000000;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	Z catchFinalizer = 0x00000001 (offset = 16) (FinThreads$Foo)
	J finalizeLink = 0x0000000000000000 (offset = 8) (FinThreads$Foo) <hidden>
}
> !markmap ismarked 0x000003FF9803FD08
Object 0x000003FF9803FD08 is marked

> !rootpathfind 0x000003FF9803FD08

========================================
FinThreads$Foo@0x000003FF9803FD08
```
and `Foo.create(false);`:
```
> !j9object 0x3ff98029948
!J9Object 0x000003FF98029948 {
	struct J9Class* clazz = !j9class 0x3FEF4022800 // FinThreads$Foo
	Object flags = 0x00000000;
	J lockword = 0x0000000000000000 (offset = 0) (java/lang/Object) <hidden>
	Z catchFinalizer = 0x00000000 (offset = 16) (FinThreads$Foo)
	J finalizeLink = 0x0000000000000000 (offset = 8) (FinThreads$Foo) <hidden>
}
> !markmap ismarked 0x3ff98029948
Object 0x000003FF98029948 is marked
> !rootpathfind 0x3ff98029948

========================================
FinThreads$Foo@0x000003FF98029948

> !gccheck finalizable:all:scan | grep -i 3ff98029948
    <000003FF98029948 >
```
Last object is a member of `finalizable` list. GC must treat it as a strong root (and it does). This element should be handle by Finalized thread eventually.

Now "Main" test thread:
```00:30:11  "AgentVMThread" prio=5 Id=73 RUNNABLE
00:30:11  	at java.base@11.0.9-internal/java.lang.ref.Finalizer.runFinalizationImpl(Native Method)
00:30:11  	at java.base@11.0.9-internal/java.lang.ref.Finalizer.runFinalization(Finalizer.java:29)
00:30:11  	at java.base@11.0.9-internal/java.lang.ref.Reference$1.runFinalization(Reference.java:63)
00:30:11  	at java.base@11.0.9-internal/java.lang.Runtime.runFinalization(Runtime.java:681)
00:30:11  	at java.base@11.0.9-internal/java.lang.System.runFinalization(System.java:608)
00:30:11  	at app//FinThreads.main(FinThreads.java:120)
00:30:11  	at java.base@11.0.9-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:30:11  	at java.base@11.0.9-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:30:11  	at java.base@11.0.9-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:30:11  	at java.base@11.0.9-internal/java.lang.reflect.Method.invoke(Method.java:566)
00:30:11  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:30:11  	at java.base@11.0.9-internal/java.lang.Thread.run(Thread.java:836)

<3fefc0ad400> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x000003FEFC0AD400 ***
<3fefc0ad400> 	ITERATE_O_SLOTS
<3fefc0ad400> 	RECORD_BYTECODE_PC_OFFSET
<3fefc0ad400> Initial values: walkSP = 0x000003FEF4034180, PC = 0x0000000000000006, literals = 0x0000000000000000, A0 = 0x000003FEF40341A0, j2iFrame = 0x000003FEF4034388, ELS = 0x000003FFA597E2D0, decomp = 0x0000000000000000
<3fefc0ad400> JIT JNI call-out frame: bp = 0x000003FEF40341A0, sp = 0x000003FEF4034180, pc = 0x0000000000000006, cp = 0x000003FEFC0A2180, arg0EA = 0x000003FEF40341A0, flags = 0x0000000020000000
<3fefc0ad400> 	Method: java/lang/ref/Finalizer.runFinalizationImpl()V !j9method 0x000003FEF4028100
<3fefc0ad400> JIT inline frame: bp = 0x000003FEF4034218, pc = 0x000003FF687E7C24, unwindSP = 0x000003FEF40341A8, cp = 0x000003FEFC0A2180, arg0EA = 0x0000000000000000, jitInfo = 0x000003FF61F26038
<3fefc0ad400> 	Method: java/lang/ref/Finalizer.runFinalization()V !j9method 0x000003FEF40280E0
<3fefc0ad400> 	Bytecode index = 0, inlineDepth = 4, PC offset = 0x000003FF687E653B
<3fefc0ad400> JIT inline frame: bp = 0x000003FEF4034218, pc = 0x000003FF687E7C24, unwindSP = 0x000003FEF40341A8, cp = 0x000003FFA02F24E0, arg0EA = 0x0000000000000000, jitInfo = 0x000003FF61F26038
<3fefc0ad400> 	Method: java/lang/ref/Reference$1.runFinalization()V !j9method 0x000003FFA02F2598
<3fefc0ad400> 	Bytecode index = 0, inlineDepth = 3, PC offset = 0x000003FF687E74DB
<3fefc0ad400> JIT inline frame: bp = 0x000003FEF4034218, pc = 0x000003FF687E7C24, unwindSP = 0x000003FEF40341A8, cp = 0x000003FFA02F66C0, arg0EA = 0x0000000000000000, jitInfo = 0x000003FF61F26038
<3fefc0ad400> 	Method: java/lang/Runtime.runFinalization()V !j9method 0x000003FFA02F6DD0
<3fefc0ad400> 	Bytecode index = 5, inlineDepth = 2, PC offset = 0x000003FF687E74DB
<3fefc0ad400> JIT inline frame: bp = 0x000003FEF4034218, pc = 0x000003FF687E7C24, unwindSP = 0x000003FEF40341A8, cp = 0x000003FFA02AD4C0, arg0EA = 0x0000000000000000, jitInfo = 0x000003FF61F26038
<3fefc0ad400> 	Method: java/lang/System.runFinalization()V !j9method 0x000003FFA02AE500
<3fefc0ad400> 	Bytecode index = 3, inlineDepth = 1, PC offset = 0x000003FF687E74DB
<3fefc0ad400> JIT frame: bp = 0x000003FEF4034218, pc = 0x000003FF687E7C24, unwindSP = 0x000003FEF40341A8, cp = 0x000003FFA071BEC0, arg0EA = 0x000003FEF4034220, jitInfo = 0x000003FF61F26038
<3fefc0ad400> 	Method: FinThreads.main([Ljava/lang/String;)V !j9method 0x000003FFA071C098
<3fefc0ad400> 	Bytecode index = 3, inlineDepth = 0, PC offset = 0x0000000000000E2A
<3fefc0ad400> 	stackMap=0x000003FF61F26222, slots=I16(0x0001) parmBaseOffset=I16(0x0010), parmSlots=U16(0x0000), localBaseOffset=I16(0xFFE8)
<3fefc0ad400> 	Described JIT temps starting at 0x000003FEF4034200 for IDATA(0x0000000000000003) slots
<3fefc0ad400> 		O-Slot: : t2[0x000003FEF4034200] = 0x000003FF9803FB48
<3fefc0ad400> 		O-Slot: : t1[0x000003FEF4034208] = 0x0000000000000000
<3fefc0ad400> 		I-Slot: : t0[0x000003FEF4034210] = 0x000003FF9803FB48
<3fefc0ad400> 	JIT-RegisterMap = UDATA(0x0000000000000000)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341B8] = UDATA(0x000003FFA55DEE86) (jit_r6)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341C0] = UDATA(0x000003FFA0311DF0) (jit_r7)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341C8] = UDATA(0x000000000000000A) (jit_r8)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341D0] = UDATA(0x000003FFA5BBA960) (jit_r9)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341D8] = UDATA(0x000003FFA071C0B8) (jit_r10)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341E0] = UDATA(0x000003FFA071B500) (jit_r11)
<3fefc0ad400> 	JIT-Frame-RegisterMap[0x000003FEF40341E8] = UDATA(0x000003FFA68D7428) (jit_r12)
```

It is obviously free running inside `System.runFinalization();`
I did not try to look where this thread in native debugger on instruction level (I guess it just happen to run there and there is no infinite loop)

So everything looks correct except `finalize()` has not been called yet... after 10 minutes

@tajila @pshipton There is a case I need help from Java experts to interpret what I see in the core (it is downloaded, ask me where if you need to look to it). Any comments, suggestions?

**Comment by tajila** [comment]
Ill take a look

**Comment by tajila** [comment]
@dmitripivkine Is this easily reproduce-able?

**Comment by dmitripivkine** [comment]
> @dmitripivkine Is this easily reproduce-able?

I did not try but I guess it is very intermittent (based it has been observed once only). I do have files loaded for original hang.
