### ISSUE TITLE
openjdk String/Split timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10767]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/66/
java/lang/String/Split.java
win2012-x86-2
```
02:02:26  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 16 timed out with a timeout of 960 seconds; check console log for any additional details
02:02:26  REASON: Assumed action based on file name: run main Split 
02:02:26  TIME:   966.454 seconds
02:02:26  messages:
02:02:26  command: main Split
02:02:26  reason: Assumed action based on file name: run main Split 
02:02:26  Mode: agentvm
02:02:26  Agent id: 16
02:02:26  Timeout refired 960 times
02:02:26  Timeout information:
02:02:26  Running jcmd on process 7848
02:02:26  Dump written to F:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16016171366118\jdk_lang_j9_0\work\scratch\1_1\core.20201002.010219.7848.0001.dmp
02:02:26  Running jstack on process 7848
02:02:26  2020-10-02T01:02:21.744035400
02:02:26  Virtual machine: 7848 JVM information:
02:02:26  JRE 15 Windows Server 2012 R2 amd64-64-Bit Compressed References 20201001_66 (JIT enabled, AOT enabled)
02:02:26  OpenJ9   - d5c93e7946f
02:02:26  OMR      - b90f691fb65
02:02:26  JCL      - c52d2e0810e based on jdk-15+36
02:02:26  
02:02:26  "main" prio=5 Id=1 WAITING
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Native Method)
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Object.java:221)
02:02:26  	at java.base@15-internal/java.lang.Thread.join(Thread.java:725)
02:02:26  	- locked java.lang.Thread@9acd3365
02:02:26  	at app//com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
02:02:26  	at app//com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:301)
02:02:26  	at app//com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:232)
02:02:26  	at app//com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
02:02:26  
02:02:26  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
02:02:26  
02:02:26  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
02:02:26  
02:02:26  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
02:02:26  
02:02:26  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
02:02:26  
02:02:26  "IProfiler" prio=5 Id=12 RUNNABLE
02:02:26  
02:02:26  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Native Method)
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Object.java:221)
02:02:26  	at java.base@15-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
02:02:26  	- locked java.lang.ref.ReferenceQueue@34af90ff
02:02:26  	at java.base@15-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
02:02:26  	at java.base@15-internal/java.lang.Thread.run(Thread.java:845)
02:02:26  	at java.base@15-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
02:02:26  
02:02:26  "Finalizer thread" prio=5 Id=13 RUNNABLE
02:02:26  
02:02:26  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=15 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=16 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=17 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=18 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=19 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=20 RUNNABLE
02:02:26  
02:02:26  "GC Worker" prio=5 Id=21 RUNNABLE
02:02:26  
02:02:26  "Attach API wait loop" prio=10 Id=24 RUNNABLE
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:259)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
02:02:26  
02:02:26  "pool-1-thread-1" prio=5 Id=25 TIMED_WAITING
02:02:26  	at java.base@15-internal/jdk.internal.misc.Unsafe.park(Native Method)
02:02:26  	at java.base@15-internal/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
02:02:26  	at java.base@15-internal/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
02:02:26  	at java.base@15-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
02:02:26  	at java.base@15-internal/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
02:02:26  	at java.base@15-internal/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
02:02:26  	at java.base@15-internal/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
02:02:26  	at java.base@15-internal/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
02:02:26  	at java.base@15-internal/java.lang.Thread.run(Thread.java:845)
02:02:26  
02:02:26  "AgentVMThread" prio=5 Id=76 RUNNABLE
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.newCharProperty(Pattern.java:2950)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.atom(Pattern.java:2336)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.sequence(Pattern.java:2159)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.expr(Pattern.java:2069)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.compile(Pattern.java:1783)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.<init>(Pattern.java:1430)
02:02:26  	at java.base@15-internal/java.util.regex.Pattern.compile(Pattern.java:1069)
02:02:26  	at java.base@15-internal/java.lang.String.split(String.java:3283)
02:02:26  	at app//Split.main(Split.java:125)
02:02:26  	at java.base@15-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:02:26  	at java.base@15-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
02:02:26  	at java.base@15-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:02:26  	at java.base@15-internal/java.lang.reflect.Method.invoke(Method.java:564)
02:02:26  	at app//com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:02:26  	at java.base@15-internal/java.lang.Thread.run(Thread.java:845)
02:02:26  
02:02:26  "file lock watchdog" prio=10 Id=78 TIMED_WAITING
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Native Method)
02:02:26  	at java.base@15-internal/java.lang.Object.wait(Object.java:221)
02:02:26  	at java.base@15-internal/java.util.TimerThread.mainLoop(Timer.java:553)
02:02:26  	- locked java.util.TaskQueue@e74d5282
02:02:26  	at java.base@15-internal/java.util.TimerThread.run(Timer.java:506)
02:02:26  
02:02:26  "Attachment 54632" prio=10 Id=79 RUNNABLE
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:233)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$150/0x00000000c03a3e68.apply(Unknown Source)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:169)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
02:02:26  	at java.base@15-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
02:02:26  
02:02:26  
02:02:26  --- Timeout information end.
```

**Comment by pshipton** [comment]
10x grinder https://ci.eclipse.org/openj9/job/Grinder/1088/
