### ISSUE TITLE
openj9 jdk11 dumpAllThreads(boolean, boolean, int)  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#10796]
At jdk10 `dumpAllThreads(boolean, boolean, int)` was introduced: https://docs.oracle.com/en/java/javase/11/docs/api/java.management/java/lang/management/ThreadMXBean.html#dumpAllThreads(boolean,boolean,int), but if this is called in the openj9 jdk11 `java.lang.ArrayIndexOutOfBoundsException` is thrown.

The test case below demonstrates the issue - tested on
```
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Openj9 (build 11.0.9+10-202010042349)
Eclipse OpenJ9 VM Openj9 (build master-6f9989460, JRE 11 Linux amd64-64-Bit Compressed References 20201004_784 (JIT enabled, AOT enabled)
OpenJ9   - 6f9989460
OMR      - d405b96ec
JCL      - 6eb01bf3ab based on jdk-11.0.9+10)
```

Test case code:
```
import java.lang.management.*;

public class DumpAllThreadsTest {

        public static void main(String[] args) {

                ThreadMXBean threadMXBean = ManagementFactory.getThreadMXBean();

                ThreadInfo[] threads = threadMXBean.dumpAllThreads(true, true);
                System.out.println("Calling threadMXBean.dumpAllThreads(true, true)");
                for (ThreadInfo thInfo : threads) {
                        System.out.println("ThreadName: " + thInfo.getThreadName());
                        System.out.println("  ThreadId: " + thInfo.getThreadId());
                        System.out.println("  stackTrace.length: " + thInfo.getStackTrace().length);
                }

                System.out.println("");
                System.out.println("Calling threadMXBean.dumpAllThreads(true, true, 1)");
                threads = threadMXBean.dumpAllThreads(true, true, 1);
                for (ThreadInfo thInfo : threads) {
                        System.out.println("ThreadName: " + thInfo.getThreadName());
                        System.out.println("  ThreadId: " + thInfo.getThreadId());
                        System.out.println("  stackTrace.length: " + thInfo.getStackTrace().length);
                }
        }
}
```

Output running jdk11 openj9
```

java -cp . DumpAllThreadsTest
Calling threadMXBean.dumpAllThreads(true, true)
ThreadName: main
  ThreadId: 1
  stackTrace.length: 4
ThreadName: JIT Compilation Thread-000
  ThreadId: 3
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-001 Suspended
  ThreadId: 4
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-002 Suspended
  ThreadId: 5
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-003 Suspended
  ThreadId: 6
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-004 Suspended
  ThreadId: 7
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-005 Suspended
  ThreadId: 8
  stackTrace.length: 0
ThreadName: JIT Compilation Thread-006 Suspended
  ThreadId: 9
  stackTrace.length: 0
ThreadName: JIT Diagnostic Compilation Thread-007 Suspended
  ThreadId: 10
  stackTrace.length: 0
ThreadName: JIT-SamplerThread
  ThreadId: 11
  stackTrace.length: 0
ThreadName: IProfiler
  ThreadId: 12
  stackTrace.length: 0
ThreadName: Common-Cleaner
  ThreadId: 2
  stackTrace.length: 6
ThreadName: Concurrent Mark Helper
  ThreadId: 13
  stackTrace.length: 0
ThreadName: Attach API wait loop
  ThreadId: 16
  stackTrace.length: 4

Calling threadMXBean.dumpAllThreads(true, true, 1)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:676)
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:690)
	at DumpAllThreadsTest.main(DumpAllThreadsTest.java:19)
```

Output running jdk11 hotspot:
```
java -cp . DumpAllThreadsTest
Calling threadMXBean.dumpAllThreads(true, true)
ThreadName: main
  ThreadId: 1
  stackTrace.length: 4
ThreadName: Reference Handler
  ThreadId: 2
  stackTrace.length: 3
ThreadName: Finalizer
  ThreadId: 3
  stackTrace.length: 4
ThreadName: Signal Dispatcher
  ThreadId: 4
  stackTrace.length: 0
ThreadName: Common-Cleaner
  ThreadId: 9
  stackTrace.length: 5

Calling threadMXBean.dumpAllThreads(true, true, 1)
ThreadName: main
  ThreadId: 1
  stackTrace.length: 1
ThreadName: Reference Handler
  ThreadId: 2
  stackTrace.length: 1
ThreadName: Finalizer
  ThreadId: 3
  stackTrace.length: 1
ThreadName: Signal Dispatcher
  ThreadId: 4
  stackTrace.length: 0
ThreadName: Common-Cleaner
  ThreadId: 9
  stackTrace.length: 1
```

**Comment by tajila** [comment]
@mikezhang1234567890 can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into it.
