### ISSUE TITLE
Minecraft error on start

### ISSUE THREAD

**Issue by AndiLeni** [eclipse/openj9#10813]
Java -version output
--------------------
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

Summary of problem
------------------

I was using openj9 for minecraft because of better performance.  
Unfortunately, since the 1.16.2 version openj9 does not work anymore.  
Are there any tips on how this could be solved or is this in mojangs hands to solve this?

````
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:186)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
	at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
	at java.base/java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:935)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1084)
	at hk.<clinit>(SourceFile:50)
	at gm.<clinit>(SourceFile:237)
	at vm.a(SourceFile:42)
	at net.minecraft.client.main.Main.main(SourceFile:137)
	... 8 more
Caused by: java.lang.NullPointerException
	at hk.a(SourceFile:88)
	at kk.a(SourceFile:20)
	at kk.<clinit>(SourceFile:13)
	... 15 more
Exiting with -1
````

**Comment by AndiLeni** [comment]
I've see this has been reported already and should be solved in one of the latest builds.
Sorry for the inconvenience.

_https://github.com/eclipse/openj9/pull/10410
https://github.com/eclipse/openj9/issues/10356_
