### ISSUE TITLE
HCRLateAttachWorkload_0 NPE from ClassReader.accept

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10840]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_aarch64_linux/62 (0.23.0 M2 build)
HCRLateAttachWorkload_0
test-aws-rhel76-armv8-4
```
LT  The agent's agentmain method was called.
LT  To re-run this agent with these options, pass this option to the agent on the command line: "percentage=50,threads=10,threadsTimeout=60000,duration=240,seed=-5143177746756303179"
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
AG  stderr 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
LT  stderr Exception in thread "Attachment 40885" java.lang.reflect.InvocationTargetException
LT  stderr 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  stderr 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  stderr 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  stderr 	at java.lang.reflect.Method.invoke(Method.java:498)
LT  stderr 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
LT  stderr 	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:426)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:346)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:324)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:190)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.run(Attachment.java:150)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:443)
LT  stderr 	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
LT  stderr 	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:156)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
LT  stderr Caused by: java.lang.NullPointerException
LT  stderr 	at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3671)
LT  stderr 	at <unknown class>.<unknown method>(Unknown Source)
LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:717)
LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:76)
LT  stderr 	... 5 more
LT  stderr Agent failed to start!
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
Possibly related to #10812.

**Comment by lumpfish** [comment]
Seen being seen on AdoptOpenJDK nightly builds - e.g. https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_aarch64_linux_xl/303/consoleFull
```
01:27:44  openjdk version "11.0.10" 2021-01-19
01:27:44  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+8-202101032344)
01:27:44  Eclipse OpenJ9 VM AdoptOpenJDK (build master-a6994047e, JRE 11 Linux aarch64-64-Bit 20210103_490 (JIT enabled, AOT enabled)
01:27:44  OpenJ9   - a6994047e
01:27:44  OMR      - d19d2fff4
01:27:44  JCL      - 6319cd4ec9 based on jdk-11.0.10+8)
```
```
01:27:44  STF 01:27:43.673 - +------ Step 3 - Wait for Agent to complete, followed by the MiniMix test seconds later.
01:27:44  STF 01:27:43.673 - | Wait for processes to meet expectations
01:27:44  STF 01:27:43.673 - |   Processes: [LT, AG]
01:27:44  STF 01:27:43.673 - |
01:27:44  STF 01:27:43.673 - Monitoring processes: AG  LT 
01:27:44  AG  1:27:43 > Will attempt to attach to JVM with pid 38191
01:27:44  AG  1:27:44 > Attach will be done using agent jar file: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar
01:27:44  LT  The agent's agentmain method was called.
01:27:44  LT  To re-run this agent with these options, pass this option to the agent on the command line: "percentage=50,threads=10,threadsTimeout=60000,duration=240,seed=2010424693344955433"
01:27:46  LT  01:27:45.925 - Load test parameters
01:27:46  LT  01:27:46.125 -   Time limited         = true
01:27:46  LT  01:27:46.127 -   Time limit         = 5m
01:27:46  LT  01:27:46.128 -   abortIfOutOfMemory   = true
01:27:46  LT  01:27:46.129 -   reportFailureLimit   = 1
01:27:46  LT  01:27:46.130 -   abortAtFailureLimit  = 10
01:27:46  LT  01:27:46.131 -   maxTotalLogFileSpace = 209715200
01:27:46  LT  01:27:46.132 -   maxSingleLogSize     = 8388608
01:27:46  LT  01:27:46.133 - Parameters for suite 0
01:27:46  LT  01:27:46.134 -   Suite name     = mini-mix
01:27:46  LT  01:27:46.135 -   Number threads = 3
01:27:46  LT  01:27:46.136 -   Supplied seed  = -1
01:27:46  LT  01:27:46.137 -   Inventory file = /home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/results/1.LT.inventory/openjdk.test.load/config/inventories/util/util.xml
01:27:46  LT  01:27:46.139 -   Exclude file   = /home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/results/1.LT.inventory/openjdk.test.load/config/inventories/util/util_exclude.xml
01:27:46  LT  01:27:46.141 -   Number tests   = -1
01:27:46  LT  01:27:46.142 -   Repeat count   = 1
01:27:46  LT  01:27:46.143 -   Thinking time  = 0ms..0ms
01:27:46  LT  01:27:46.144 -   Selection mode = sequential
01:27:46  LT  01:27:46.228 - Parsing inventory file. Root=/home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/results/1.LT.inventory File=openjdk.test.load/config/inventories/util/util.xml
01:27:47  LT  01:27:46.300 - Reading exclusion file. File=openjdk.test.load/config/inventories/util/util_exclude.xml
01:27:47  LT  01:27:46.300 - Parsing inventory file. Root=/home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/results/1.LT.inventory File=openjdk.test.load/config/inventories/util/util_exclude.xml
01:27:47  LT  01:27:46.317 - Final test list:
01:27:47  LT  01:27:46.322 -   0 ArbitraryJava[net.adoptopenjdk.test.util.calendars.CalendarTest run]  Weighting=1 
01:27:47  LT  01:27:46.323 -   1 ArbitraryJava[net.adoptopenjdk.test.util.hashmap.Hog run]  Weighting=1 
01:27:47  LT  01:27:46.324 -   2 JUnit[net.adoptopenjdk.test.util.lilac.TestArrays]  Weighting=1 
01:27:47  LT  01:27:46.324 -   4 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapAPITest]  Weighting=1 
01:27:47  LT  01:27:46.324 -   5 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapTest]  Weighting=1 
01:27:47  LT  01:27:47.361 - Starting thread. Suite=0 thread=0
01:27:47  LT  01:27:47.366 - Starting thread. Suite=0 thread=1
01:27:47  LT  01:27:47.366 - Starting thread. Suite=0 thread=2
01:28:10  LT  01:28:07.537 - Completed 6.7%. Number of tests started=24
01:28:28  LT  01:28:27.411 - Completed 13.4%. Number of tests started=39 (+15)
01:28:50  LT  01:28:47.406 - Completed 20.1%. Number of tests started=54 (+15)
01:29:08  LT  01:29:07.339 - Completed 26.8%. Number of tests started=65 (+11)
01:29:30  LT  01:29:27.354 - Completed 33.5%. Number of tests started=79 (+14)
01:29:48  LT  01:29:47.780 - Completed 40.3%. Number of tests started=94 (+15)
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  Exception seen while transforming String.
01:29:56  LT  stderr Exception in thread "Attachment 34631" java.lang.reflect.InvocationTargetException
01:29:56  LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:29:56  LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:29:56  LT  stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:29:56  LT  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
01:29:56  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
01:29:56  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
01:29:56  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
01:29:56  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
01:29:56  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
01:29:56  LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.NullPointerException
01:29:56  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
01:29:56  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
01:29:56  LT  stderr 	... 11 more
01:29:56  LT  stderr Caused by: java.lang.Error: java.lang.NullPointerException
01:29:56  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
01:29:56  LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
01:29:56  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
01:29:56  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
01:29:56  LT  stderr Caused by: java.lang.NullPointerException
01:29:56  LT  stderr 	at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java)
01:29:56  LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:492)
01:29:56  LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
01:29:56  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:76)
01:29:56  LT  stderr 	... 6 more
01:29:56  LT  stderr Agent failed to start!
01:29:56  LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
01:29:56  AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
01:29:56  AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
01:29:56  AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
01:29:56  AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
01:29:56  STF 01:29:54.997 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
01:29:56  STF 01:29:54.998 - Monitoring Report Summary:
01:29:56  STF 01:29:54.998 -   o Process AG  ended with exit code (1) and not the expected exit code/s (0)
01:29:56  STF 01:29:54.998 -   o Process LT  is still running
01:29:56  STF 01:29:54.998 - Killing processes: AG  LT 
01:29:56  STF 01:29:54.998 -   o Process LT  pid 38191 stop()
01:30:06  STF 01:30:04.999 -   o Process LT  pid 38191 terminate()
01:30:06  STF 01:30:06.000 -   o Process LT  pid 38191 killed
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  LT  Exception seen while transforming String.
01:30:06  STF 01:30:06.001 -   o Process AG  pid 38192 is not running
01:30:06  **FAILED** at step 3 (Wait for Agent to complete, followed by the MiniMix test seconds later.). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/../TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/execute.pl line 151.
01:30:06  STF 01:30:06.119 - **FAILED** execute script failed. Expected return value=0 Actual=1
01:30:06  STF 01:30:06.119 - 
01:30:06  STF 01:30:06.120 - ====================   T E A R D O W N   ====================
01:30:06  STF 01:30:06.120 - Running teardown: perl /home/jenkins/workspace/Test_openjdk11_j9_extended.system_aarch64_linux_xl/openjdk-tests/TKG/../TKG/test_output_16097228994856/HCRLateAttachWorkload_previewEnabled_0/20210104-012739-HCRLateAttachWorkload/tearDown.pl
01:30:06  STF 01:30:06.202 - TEARDOWN stage completed
01:30:06  STF 01:30:06.209 - 
01:30:06  STF 01:30:06.209 - =====================   R E S U L T S   =====================
01:30:06  STF 01:30:06.209 - Stage results:
01:30:06  STF 01:30:06.209 -   setUp:     pass
01:30:06  STF 01:30:06.209 -   execute:  *fail*
01:30:06  STF 01:30:06.209 -   teardown:  pass
01:30:06  STF 01:30:06.209 - 
01:30:06  STF 01:30:06.209 - Overall result: **FAILED**
```
