### ISSUE TITLE
openjdk aarch64 jdk8 exception has occurred in the compiler

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10841]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/62
java/lang/invoke/PermuteArgsTest.java
java/lang/reflect/Generics/getAnnotationTest.java
```
18:52:24  direct:
18:52:24  An exception has occurred in the compiler (1.8.0_272). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
18:52:24  java.lang.IncompatibleClassChangeError
18:52:24  	at com.sun.tools.javac.comp.Infer$InferenceContext.notifyChange(Infer.java:2123)
18:52:24  	at com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:212)
18:52:24  	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:567)
18:52:24  	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1446)
18:52:24  	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1633)
18:52:24  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1704)
18:52:24  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1677)
18:52:24  	at com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2436)
18:52:24  	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3097)
18:52:24  	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3348)
18:52:24  	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2433)
18:52:24  	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2427)
18:52:24  	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3396)
18:52:24  	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3278)
18:52:24  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
18:52:24  	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
18:52:24  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:625)
18:52:24  	at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1593)
18:52:24  	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
18:52:24  	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
18:52:24  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
18:52:24  	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
18:52:24  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
18:52:24  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
18:52:24  	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
18:52:24  	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
18:52:24  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
18:52:24  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
18:52:24  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
18:52:24  	at com.sun.tools.javac.main.Main.compile(Main.java:381)
18:52:24  	at com.sun.tools.javac.main.Main.compile(Main.java:370)
18:52:24  	at com.sun.tools.javac.main.Main.compile(Main.java:361)
18:52:24  	at com.sun.tools.javac.Main.compile(Main.java:74)
18:52:24  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:52:24  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:52:24  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:52:24  	at java.lang.reflect.Method.invoke(Method.java:498)
18:52:24  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
18:52:24  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
18:52:24  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
18:52:24  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
18:52:24  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
18:52:24  
18:52:24  TEST RESULT: Error. compiler crashed (exit code 4)
```

**Comment by pshipton** [comment]
@knn-k
