### ISSUE TITLE
JDK11 testOpenJ9DiagnosticsMXBean_1_FAILED testRemote_setDumpOptions - Dump configuration cannot be changed while a dump is in progress

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10922]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/122`
```
23:13:31  openjdk version "11.0.9-internal" 2020-10-20
23:13:31  OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxxlNightly)
23:13:31  Eclipse OpenJ9 VM (build master-e5e0324a0f5, JRE 11 Linux amd64-64-Bit 20201017_547 (JIT enabled, AOT enabled)
23:13:31  OpenJ9   - e5e0324a0f5
23:13:31  OMR      - d2cc022b7d9
23:13:31  JCL      - 5e617ab0c87 based on jdk-11.0.9+10)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
01:26:34  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux_xl&TARGET=testOpenJ9DiagnosticsMXBean_1

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
FAILED: testRemote_setDumpOptions
openj9.lang.management.ConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.handleDumpConfigurationUnavailableException(OpenJ9DiagnosticsMXBeanImpl.java:295)
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeSetter(MBeanIntrospector.java:267)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.setAttribute(PerInterface.java:102)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.setAttribute(MBeanSupport.java:230)
	at java.management/javax.management.StandardMBean.setAttribute(StandardMBean.java:383)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.setAttribute(DefaultMBeanServerInterceptor.java:736)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.setAttribute(JmxMBeanServer.java:739)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1489)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:720)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$82/0x0000000000000000.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.ibm.jvm.DumpConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress.
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptions(Dump.java:624)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:104)
	... 42 more
Caused by: openj9.management.internal.DumpConfigurationUnavailableExceptionBase: Dump configuration cannot be changed while a dump is in progress.
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptionsImpl(Native Method)
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptions(Dump.java:619)
	... 47 more


===============================================
    testOpenJ9DiagnosticsMXBean
    Tests run: 10, Failures: 1, Skips: 0
===============================================


===============================================
JLM_Tests_Suite
Total tests run: 10, Failures: 1, Skips: 0
===============================================


testOpenJ9DiagnosticsMXBean_1_FAILED
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdknext_j9_extended.functional_aarch64_linux_Personal/3/tapResults/`(`ub18-aarch64-4`)
```
===============================================
Running test testOpenJ9DiagnosticsMXBean_0 ...
===============================================
testOpenJ9DiagnosticsMXBean_0 Start Time: Tue Jun  7 14:44:29 2022 Epoch Time (ms): 1654627469487
variation: NoOptions
JVM_OPTIONS:  

11:33:00  openjdk version "19-internal" 2022-09-20
11:33:00  OpenJDK Runtime Environment (build 19-internal-adhoc.jenkins.BuildJDKnextaarch64linuxPersonal)
11:33:00  Eclipse OpenJ9 VM (build exclude19-52f04efbff5, JRE 19 Linux aarch64-64-Bit Compressed References 20220607_35 (JIT enabled, AOT enabled)
11:33:00  OpenJ9   - 52f04efbff5
11:33:00  OMR      - c60867497c6
11:33:00  JCL      - 5ccf02de16a based on jdk-19+25)

FAILED: testRemote_resetDumpOptions
openj9.lang.management.ConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.handleDumpConfigurationUnavailableException(OpenJ9DiagnosticsMXBeanImpl.java:311)
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:97)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at java.management/com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeSetter(MBeanIntrospector.java:267)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.setAttribute(PerInterface.java:102)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.setAttribute(MBeanSupport.java:230)
	at java.management/javax.management.StandardMBean.setAttribute(StandardMBean.java:383)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.setAttribute(DefaultMBeanServerInterceptor.java:737)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.setAttribute(JmxMBeanServer.java:740)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1495)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:722)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1566)
Caused by: com.ibm.jvm.DumpConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress.
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptions(Dump.java:626)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at jdk.management/openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:118)
	... 35 more
Caused by: openj9.management.internal.DumpConfigurationUnavailableExceptionBase: Dump configuration cannot be changed while a dump is in progress.
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptionsImpl(Native Method)
	at openj9.jvm/com.ibm.jvm.Dump.setDumpOptions(Dump.java:621)
	... 38 more


===============================================
    testOpenJ9DiagnosticsMXBean
    Tests run: 10, Failures: 1, Skips: 0
===============================================


===============================================
JLM_Tests_Suite
Total tests run: 10, Failures: 1, Skips: 0
===============================================


testOpenJ9DiagnosticsMXBean_0_FAILED
```
50x grinder - `job/Grinder/24654/`

**Comment by pshipton** [comment]
@JasonFengJ9 the original report is on jdk11, and the grinder on jdk19 passed. I'm going to remove the jdk19 label, and remove from the milestone. I think this is just a highly intermittent test issue, sometimes we get unlucky with the timing.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly_testList_0/355
```
23:13:56  FAILED: testRemote_setDumpOptions
23:13:56  openj9.lang.management.ConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress
23:13:56  	at openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.handleDumpConfigurationUnavailableException(OpenJ9DiagnosticsMXBeanImpl.java:231)
23:13:56  	at openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:86)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:13:56  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:13:56  	at java.lang.reflect.Method.invoke(Method.java:498)
23:13:56  	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:13:56  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:13:56  	at java.lang.reflect.Method.invoke(Method.java:498)
23:13:56  	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:276)
23:13:56  	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
23:13:56  	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
23:13:56  	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
23:13:56  	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
23:13:56  	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeSetter(MBeanIntrospector.java:267)
23:13:56  	at com.sun.jmx.mbeanserver.PerInterface.setAttribute(PerInterface.java:102)
23:13:56  	at com.sun.jmx.mbeanserver.MBeanSupport.setAttribute(MBeanSupport.java:230)
23:13:56  	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.setAttribute(DefaultMBeanServerInterceptor.java:746)
23:13:56  	at com.sun.jmx.mbeanserver.JmxMBeanServer.setAttribute(JmxMBeanServer.java:739)
23:13:56  	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1491)
23:13:56  	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
23:13:56  	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
23:13:56  	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
23:13:56  	at javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:722)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:13:56  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:13:56  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:13:56  	at java.lang.reflect.Method.invoke(Method.java:498)
23:13:56  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
23:13:56  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
23:13:56  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
23:13:56  	at java.security.AccessController.doPrivileged(AccessController.java:783)
23:13:56  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
23:13:56  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
23:13:56  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
23:13:56  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
23:13:56  	at java.security.AccessController.doPrivileged(AccessController.java:717)
23:13:56  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
23:13:56  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:13:56  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:13:56  	at java.lang.Thread.run(Thread.java:826)
23:13:56  Caused by: com.ibm.jvm.DumpConfigurationUnavailableException: Dump configuration cannot be changed while a dump is in progress.
23:13:56  	at com.ibm.jvm.Dump.setDumpOptions(Dump.java:626)
23:13:56  	at openj9.lang.management.internal.OpenJ9DiagnosticsMXBeanImpl.setDumpOptions(OpenJ9DiagnosticsMXBeanImpl.java:83)
23:13:56  	... 41 more
23:13:56  Caused by: openj9.management.internal.DumpConfigurationUnavailableExceptionBase: Dump configuration cannot be changed while a dump is in progress.
23:13:56  	at com.ibm.jvm.Dump.setDumpOptionsImpl(Native Method)
23:13:56  	at com.ibm.jvm.Dump.setDumpOptions(Dump.java:621)
23:13:56  	... 42 more
```

**Comment by pshipton** [comment]
@JasonFengJ9 why is the exclude label added? The test doesn't seem to be excluded, I see it running on jdk19.

**Comment by JasonFengJ9** [comment]
This was to be excluded by https://github.com/eclipse-openj9/openj9/pull/15290 which wasn't merged, and probably need re-evaluation after recent development.
