### ISSUE TITLE
Network issues? Remote call on cent7-ppcle-2 failed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10965]
I've seen a number of builds pass the testing, but then fail afterwards. Reporting it just in case it's something real, otherwise I guess it's network related.

The latest one is https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Release/13
I can find earlier failures if anybody cares.

```
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[WS-CLEANUP] done
[Pipeline] sh
+ find /tmp -name '*core*' -print -exec rm -f '{}' ';'
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:218)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:288)
Caused: hudson.remoting.RemotingSystemException
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:301)
	at com.sun.proxy.$Proxy5.getResources2(Unknown Source)
	at hudson.remoting.RemoteClassLoader.findResources(RemoteClassLoader.java:483)
	at java.lang.ClassLoader.getResources(ClassLoader.java:683)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at javax.xml.datatype.FactoryFinder$1.run(FactoryFinder.java:296)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at javax.xml.datatype.FactoryFinder.findServiceProvider(FactoryFinder.java:292)
	at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:268)
	at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:145)
	at com.thoughtworks.xstream.converters.extended.DurationConverter$1.getFactory(DurationConverter.java:39)
	at com.thoughtworks.xstream.converters.extended.DurationConverter.<init>(DurationConverter.java:36)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:897)
Caused: com.thoughtworks.xstream.InitializationException: Could not instantiate converter : com.thoughtworks.xstream.converters.extended.DurationConverter : null
	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:904)
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:867)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
	at hudson.util.XStream2.<init>(XStream2.java:113)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5325)
	at hudson.model.Computer.<clinit>(Computer.java:1803)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to cent7-ppcle-2
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1083)
		at org.jenkinsci.plugins.xvfb.Xvfb.shutdownAndCleanup(Xvfb.java:327)
		at org.jenkinsci.plugins.xvfb.XvfbDisposer.tearDown(XvfbDisposer.java:52)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Callback.finished(CoreWrapperStep.java:152)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$Callback2.finished(CoreWrapperStep.java:122)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall.lambda$onSuccess$0(GeneralNonBlockingStepExecution.java:140)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall$$Lambda$363/000000008006BE00.run(Unknown Source)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$$Lambda$352/00000000800618F0.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
Caused: java.lang.NoClassDefFoundError: hudson.slaves.SlaveComputer (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:98)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1100)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1091)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)
Caused: java.io.IOException: Remote call on cent7-ppcle-2 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1083)
	at org.jenkinsci.plugins.xvfb.Xvfb.shutdownAndCleanup(Xvfb.java:327)
	at org.jenkinsci.plugins.xvfb.XvfbDisposer.tearDown(XvfbDisposer.java:52)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Callback.finished(CoreWrapperStep.java:152)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$Callback2.finished(CoreWrapperStep.java:122)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall.lambda$onSuccess$0(GeneralNonBlockingStepExecution.java:140)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall$$Lambda$363/000000008006BE00.run(Unknown Source)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$$Lambda$352/00000000800618F0.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64le_linux_Release/45

**Comment by pshipton** [comment]
This one didn't get started
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_extended.functional_x86-64_windows_Release_testList_0/10

**Comment by jdekonin** [comment]
Looks like a network issue with UNB based systems.  These system are all online atm.  I checked a few previous failed systems are either running jobs or have run jobs successfully since.

**Comment by pshipton** [comment]
All except one of the jobs ran yesterday and last night, just many of them failed to report status after running the tests (and passing). I can only hope it's fixed itself now, otherwise it's a lot more work to determine if there are any test failures. Didn't see much of this in the jdk15 run, and I haven't yet seen this re-occur today in the omr acceptance build.
