### ISSUE TITLE
PBEKeyCleanupTest timeout in FileOutputStream.writeBytes

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10990]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/190
com/sun/crypto/provider/Cipher/PBE/PBEKeyCleanupTest.java
jdk11_tier1_cipher_0
```
02:05:37  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 980329ms).
02:05:37  REASON: User specified action: run main/othervm PBEKeyCleanupTest 
02:05:37  TIME:   980.368 seconds
02:05:37  messages:
02:05:37  command: main PBEKeyCleanupTest
02:05:37  reason: User specified action: run main/othervm PBEKeyCleanupTest 
02:05:37  Mode: othervm [/othervm specified]
02:05:37  Additional options from @modules: --add-modules java.base --add-exports java.base/com.sun.crypto.provider=ALL-UNNAMED --add-opens java.base/com.sun.crypto.provider=ALL-UNNAMED
02:05:37  Timeout information:
02:05:37  Running jstack on process 14221552
02:05:37  2020-10-25T02:05:01.793573
02:05:37  Virtual machine: 14221552 JVM information:
02:05:37  JRE 11 AIX ppc64-64-Bit Compressed References 20201024_545 (JIT enabled, AOT enabled)
02:05:37  OpenJ9   - 75a73048046
02:05:37  OMR      - e2fac34fcb3
02:05:37  JCL      - fd18c0317c3 based on jdk-11.0.9+11
02:05:37  
02:05:37  "main" prio=5 Id=1 WAITING
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Native Method)
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Object.java:221)
02:05:37  	at java.base@11.0.9-internal/java.lang.Thread.join(Thread.java:715)
02:05:37  	- locked java.lang.Thread@bbfcdfd0
02:05:37  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
02:05:37  
02:05:37  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
02:05:37  
02:05:37  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
02:05:37  
02:05:37  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
02:05:37  
02:05:37  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
02:05:37  
02:05:37  "IProfiler" prio=5 Id=12 RUNNABLE
02:05:37  
02:05:37  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Native Method)
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Object.java:221)
02:05:37  	at java.base@11.0.9-internal/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
02:05:37  	- locked java.lang.ref.ReferenceQueue@b82814a0
02:05:37  	at java.base@11.0.9-internal/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
02:05:37  	at java.base@11.0.9-internal/java.lang.Thread.run(Thread.java:835)
02:05:37  	at java.base@11.0.9-internal/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
02:05:37  
02:05:37  "Finalizer thread" prio=5 Id=13 RUNNABLE
02:05:37  	at java.base@11.0.9-internal/java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:175)
02:05:37  	at java.base@11.0.9-internal/java.lang.ref.Reference.enqueueImpl(Reference.java:161)
02:05:37  	- locked java.lang.Class$ReflectRef@e7a06295
02:05:37  
02:05:37  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=15 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=16 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=17 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=18 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=19 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=20 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=21 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=22 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=23 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=24 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=25 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=26 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=27 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=28 RUNNABLE
02:05:37  
02:05:37  "GC Worker" prio=5 Id=29 RUNNABLE
02:05:37  
02:05:37  "Attach API wait loop" prio=10 Id=32 RUNNABLE
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:259)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
02:05:37  
02:05:37  "MainThread" prio=5 Id=34 RUNNABLE
02:05:37  	at java.base@11.0.9-internal/java.io.FileOutputStream.writeBytes(Native Method)
02:05:37  	at java.base@11.0.9-internal/java.io.FileOutputStream.write(FileOutputStream.java:354)
02:05:37  	at java.base@11.0.9-internal/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
02:05:37  	at java.base@11.0.9-internal/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
02:05:37  	- locked java.io.BufferedOutputStream@e6cc58e
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.write(PrintStream.java:561)
02:05:37  	- locked java.io.PrintStream@c4a1f2f1
02:05:37  	at java.base@11.0.9-internal/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
02:05:37  	at java.base@11.0.9-internal/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
02:05:37  	at java.base@11.0.9-internal/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
02:05:37  	- locked java.io.OutputStreamWriter@c9874204
02:05:37  	at java.base@11.0.9-internal/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.write(PrintStream.java:606)
02:05:37  	- locked java.io.PrintStream@c4a1f2f1
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.print(PrintStream.java:745)
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.append(PrintStream.java:1147)
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.append(PrintStream.java:1188)
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.append(PrintStream.java:63)
02:05:37  	at java.base@11.0.9-internal/java.util.Formatter$FixedString.print(Formatter.java:2754)
02:05:37  	at java.base@11.0.9-internal/java.util.Formatter.format(Formatter.java:2661)
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.format(PrintStream.java:1053)
02:05:37  	- locked java.io.PrintStream@c4a1f2f1
02:05:37  	at java.base@11.0.9-internal/java.io.PrintStream.printf(PrintStream.java:949)
02:05:37  	at app//PBEKeyCleanupTest.testCleanupSecret(PBEKeyCleanupTest.java:91)
02:05:37  	at app//PBEKeyCleanupTest.testPBKSecret(PBEKeyCleanupTest.java:77)
02:05:37  	at app//PBEKeyCleanupTest.main(PBEKeyCleanupTest.java:56)
02:05:37  	at java.base@11.0.9-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:05:37  	at java.base@11.0.9-internal/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:05:37  	at java.base@11.0.9-internal/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:05:37  	at java.base@11.0.9-internal/java.lang.reflect.Method.invoke(Method.java:566)
02:05:37  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:05:37  	at java.base@11.0.9-internal/java.lang.Thread.run(Thread.java:835)
02:05:37  
02:05:37  "file lock watchdog" prio=10 Id=36 TIMED_WAITING
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Native Method)
02:05:37  	at java.base@11.0.9-internal/java.lang.Object.wait(Object.java:221)
02:05:37  	at java.base@11.0.9-internal/java.util.TimerThread.mainLoop(Timer.java:553)
02:05:37  	- locked java.util.TaskQueue@813b5a04
02:05:37  	at java.base@11.0.9-internal/java.util.TimerThread.run(Timer.java:506)
02:05:37  
02:05:37  "Attachment 62366" prio=10 Id=37 RUNNABLE
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$19/0x0000000000000000.apply(Unknown Source)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
02:05:37  	at java.base@11.0.9-internal/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
02:05:37  
02:05:37  
02:05:37  --- Timeout information end.
```

**Comment by lumpfish** [comment]
Occurred on the AIX jdk-16+36_openj9-0.25.0-m2 build: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/31/consoleFull
```
11:59:23  openjdk version "16" 2021-03-16
11:59:23  OpenJDK Runtime Environment AdoptOpenJDK (build 16+36-202103011038)
11:59:23  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.25.0-m2, JRE 16 AIX ppc64-64-Bit Compressed References 20210301_61 (JIT enabled, AOT enabled)
11:59:23  OpenJ9   - 212eb1038
11:59:23  OMR      - 09514431e
11:59:23  JCL      - 27a256c845f based on jdk-16+36)
```
```
15:46:18  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 971729ms).
15:46:18  REASON: User specified action: run main/othervm PBEKeyCleanupTest 
15:46:18  TIME:   971.773 seconds
15:46:18  messages:
15:46:18  command: main PBEKeyCleanupTest
15:46:18  reason: User specified action: run main/othervm PBEKeyCleanupTest 
15:46:18  Mode: othervm [/othervm specified]
15:46:18  Additional options from @modules: --add-modules java.base --add-exports java.base/com.sun.crypto.provider=ALL-UNNAMED --add-opens java.base/com.sun.crypto.provider=ALL-UNNAMED
15:46:18  Timeout information:
15:46:18  Running jstack on process 28115284
15:46:18  2021-03-01T09:45:52.595711
15:46:18  Virtual machine: 28115284 JVM information:
15:46:18  JRE 16 AIX ppc64-64-Bit Compressed References 20210301_61 (JIT enabled, AOT enabled)
15:46:18  OpenJ9   - 212eb1038
15:46:18  OMR      - 09514431e
15:46:18  JCL      - 27a256c845f based on jdk-16+36
15:46:18  
15:46:18  "main" prio=5 Id=1 WAITING
15:46:18  	at java.base@16/java.lang.Object.wait(Native Method)
15:46:18  	at java.base@16/java.lang.Object.wait(Object.java:221)
15:46:18  	at java.base@16/java.lang.Thread.join(Thread.java:733)
15:46:18  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
15:46:18  
15:46:18  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
15:46:18  
15:46:18  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
15:46:18  
15:46:18  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
15:46:18  
15:46:18  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
15:46:18  
15:46:18  "IProfiler" prio=5 Id=12 RUNNABLE
15:46:18  
15:46:18  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
15:46:18  	at java.base@16/java.lang.Object.wait(Native Method)
15:46:18  	at java.base@16/java.lang.Object.wait(Object.java:221)
15:46:18  	at java.base@16/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
15:46:18  	at java.base@16/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
15:46:18  	at java.base@16/java.lang.Thread.run(Thread.java:853)
15:46:18  	at java.base@16/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
15:46:18  
15:46:18  "Finalizer thread" prio=5 Id=13 RUNNABLE
15:46:18  
15:46:18  "Concurrent Mark Helper" prio=1 Id=14 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=15 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=16 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=17 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=18 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=19 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=20 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=21 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=22 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=23 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=24 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=25 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=26 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=27 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=28 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=29 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=30 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=31 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=32 RUNNABLE
15:46:18  
15:46:18  "GC Worker" prio=5 Id=33 RUNNABLE
15:46:18  
15:46:18  "MainThread" prio=5 Id=37 RUNNABLE
15:46:18  	at java.base@16/java.io.FileOutputStream.writeBytes(Native Method)
15:46:18  	at java.base@16/java.io.FileOutputStream.write(FileOutputStream.java:347)
15:46:18  	at java.base@16/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
15:46:18  	at java.base@16/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
15:46:18  	- locked java.io.BufferedOutputStream@827f0cc7
15:46:18  	at java.base@16/java.io.PrintStream.write(PrintStream.java:570)
15:46:18  	- locked java.io.PrintStream@b8e2835e
15:46:18  	at java.base@16/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
15:46:18  	at java.base@16/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
15:46:18  	at java.base@16/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:110)
15:46:18  	- locked java.io.OutputStreamWriter@1e788a44
15:46:18  	at java.base@16/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
15:46:18  	at java.base@16/java.io.PrintStream.write(PrintStream.java:699)
15:46:18  	- locked java.io.PrintStream@b8e2835e
15:46:18  	at java.base@16/java.io.PrintStream.print(PrintStream.java:863)
15:46:18  	at java.base@16/java.io.PrintStream.append(PrintStream.java:1303)
15:46:18  	at java.base@16/java.io.PrintStream.append(PrintStream.java:63)
15:46:18  	at java.base@16/java.util.Formatter$FormatSpecifier.appendJustified(Formatter.java:3087)
15:46:18  	at java.base@16/java.util.Formatter$FormatSpecifier.print(Formatter.java:3077)
15:46:18  	at java.base@16/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3050)
15:46:18  	at java.base@16/java.util.Formatter$FormatSpecifier.print(Formatter.java:2927)
15:46:18  	at java.base@16/java.util.Formatter.format(Formatter.java:2689)
15:46:18  	at java.base@16/java.io.PrintStream.format(PrintStream.java:1209)
15:46:18  	- locked java.io.PrintStream@b8e2835e
15:46:18  	at java.base@16/java.io.PrintStream.printf(PrintStream.java:1105)
15:46:18  	at app//PBEKeyCleanupTest.testCleanupSecret(PBEKeyCleanupTest.java:91)
15:46:18  	at app//PBEKeyCleanupTest.testPBKSecret(PBEKeyCleanupTest.java:77)
15:46:18  	at app//PBEKeyCleanupTest.main(PBEKeyCleanupTest.java:56)
15:46:18  	at java.base@16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:46:18  	at java.base@16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
15:46:18  	at java.base@16/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:46:18  	at java.base@16/java.lang.reflect.Method.invoke(Method.java:567)
15:46:18  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:46:18  	at java.base@16/java.lang.Thread.run(Thread.java:853)
15:46:18  
15:46:18  "Attach API wait loop" prio=10 Id=38 RUNNABLE
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:259)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
15:46:18  
15:46:18  "file lock watchdog" prio=10 Id=40 TIMED_WAITING
15:46:18  	at java.base@16/java.lang.Object.wait(Native Method)
15:46:18  	at java.base@16/java.lang.Object.wait(Object.java:221)
15:46:18  	at java.base@16/java.util.TimerThread.mainLoop(Timer.java:553)
15:46:18  	at java.base@16/java.util.TimerThread.run(Timer.java:506)
15:46:18  
15:46:18  "Attachment 59187" prio=10 Id=42 RUNNABLE
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:245)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$19/0x0000000000000000.apply(Unknown Source)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:181)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
15:46:18  	at java.base@16/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
15:46:18  
15:46:18  
15:46:18  --- Timeout information end.
```
