### ISSUE TITLE
OpenJ9 produces incorrect results when java/lang/Math.abs is used successively

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#11032]
Opening up an issue on behalf of @travisfw from an original bug report [[1]](https://discuss.kotlinlang.org/t/i-think-the-adopt-openjdk-j9-jvm-jit-messes-with-kotlin-somehow/19596/10) on the Kotlin Discussion boards. Running the following program intermittently results in the exception being thrown:

```
package com.travisfw.voxelsphere.lwjgl3

import kotlin.math.abs

data class Vector3(val x: Float, val y: Float, val z: Float) {
    operator fun minus(v2: Vector3): Vector3 =Vector3(x-v2.x, y-v2.y, z-v2.z)
    fun taxiDistance(): Float = abs(x) + abs(y) + abs(z)
}

fun main(args: Array<String>) {
    val gridCenter = Vector3(32.0f, 32.0f, 32.0f)
    for (x in 0..320)
      for (y in 0..320)
        for (z in 0..320) {
           val cornerPosition = Vector3(x.toFloat(), y.toFloat(), z.toFloat())
           val centeredPos = cornerPosition - gridCenter
           val taxiFromCenter = centeredPos.taxiDistance()
           val centeredPos2 = Vector3(centeredPos.x, centeredPos.y, centeredPos.z)
           val taxiFromCenter2 = centeredPos2.taxiDistance()
           if (taxiFromCenter != taxiFromCenter2) {
               val recomputed = centeredPos2.taxiDistance()
               throw Exception("taxiFromcenter are not equal $taxiFromCenter ($centeredPos) $taxiFromCenter2 ($centeredPos2) - recomputed = $recomputed")
           }
       }
      println("If you reached here, it worked (and you are likely using a non-J9 openjdk)")
}
```

Save as `test.kt` and compile with `kotlinc test.kt -include-runtime -d test.jar`.

[1] https://discuss.kotlinlang.org/t/i-think-the-adopt-openjdk-j9-jvm-jit-messes-with-kotlin-somehow/19596/10

**Comment by fjeremic** [comment]
The issue appears to be a JIT problem with the recognized call transformer. Looking at the trees before the optimization we see the following:

```
n1n       BBStart <block_2>                                                                   [  0x33ab3580] bci=[-1,0,7] rc=0 vc=0 vn=- li=- udi=- nc=0
n5n       fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab36c0] bci=[-1,4,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n4n         floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.x F[#367  final Shadow +8] [flags 0xa0605 0x0 ]  [  0x33ab3670] bci=[-1,1,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n3n           aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab3620] bci=[-1,0,7] rc=1 vc=0 vn=
n7n       istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab3760] bci=[-1,6,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n6n         iconst 0                                                                          [  0x33ab3710] bci=[-1,5,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n10n      treetop                                                                             [  0x33ab3850] bci=[-1,8,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n9n         fcall  java/lang/Math.abs(F)F[#371  final static Method] [flags 0x20500 0x0 ]     [  0x33ab3800] bci=[-1,8,7] rc=2 vc=0 vn=- li=- udi=- nc=1
n8n           fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                               [  0x33ab37b0] bci=[-1,7,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n13n      fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab3940] bci=[-1,15,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n12n        floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.y F[#372  final Shadow +12] [flags 0xa0605 0x0 ]  [  0x33ab38f0] bci=[-1,12,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n11n          aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab38a0] bci=[-1,11,7] rc=1 vc=0 vn
n15n      istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab39e0] bci=[-1,17,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n14n        iconst 0                                                                          [  0x33ab3990] bci=[-1,16,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n18n      treetop                                                                             [  0x33ab3ad0] bci=[-1,19,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n17n        fcall  java/lang/Math.abs(F)F[#371  final static Method] [flags 0x20500 0x0 ]     [  0x33ab3a80] bci=[-1,19,7] rc=2 vc=0 vn=- li=- udi=- nc=1
n16n          fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                               [  0x33ab3a30] bci=[-1,18,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n23n      treetop                                                                             [  0x33ab3c60] bci=[-1,27,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n19n        fadd                                                                              [  0x33ab3b20] bci=[-1,22,7] rc=2 vc=0 vn=- li=- udi=- nc=2
n9n           ==>fcall
n17n          ==>fcall
n22n      fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab3c10] bci=[-1,27,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n21n        floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.z F[#373  final Shadow +16] [flags 0xa0605 0x0 ]  [  0x33ab3bc0] bci=[-1,24,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n20n          aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab3b70] bci=[-1,23,7] rc=1 vc=0 vn
n25n      istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab3d00] bci=[-1,29,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n24n        iconst 0                                                                          [  0x33ab3cb0] bci=[-1,28,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n28n      treetop                                                                             [  0x33ab3df0] bci=[-1,31,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n27n        fcall  java/lang/Math.abs(F)F[#371  final static Method] [flags 0x20500 0x0 ]     [  0x33ab3da0] bci=[-1,31,7] rc=2 vc=0 vn=- li=- udi=- nc=1
n26n          fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                               [  0x33ab3d50] bci=[-1,30,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n30n      freturn                                                                             [  0x33ab3e90] bci=[-1,35,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n29n        fadd                                                                              [  0x33ab3e40] bci=[-1,34,7] rc=1 vc=0 vn=- li=- udi=- nc=2
n19n          ==>fadd
n27n          ==>fcall
n2n       BBEnd </block_2>                                                                    [  0x33ab35d0] bci=[-1,35,7] rc=0 vc=0 vn=- li=- udi=- nc=0
```

Whereas after the optimization:

```
<optimization id=5 name=recognizedCallTransformer method=com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F>
Performing 5: recognizedCallTransformer
[     1]   5.1    O^O RECOGNIZED CALL TRANSFORMER: Transforming recognized call node [0000000033AB3800]
```

We see this:

```
n1n       BBStart <block_2>                                                                   [  0x33ab3580] bci=[-1,0,7] rc=0 vc=0 vn=- li=- udi=- nc=0
n5n       fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab36c0] bci=[-1,4,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n4n         floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.x F[#367  final Shadow +8] [flags 0xa0605 0x0 ]  [  0x33ab3670] bci=[-1,1,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n3n           aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab3620] bci=[-1,0,7] rc=1 vc=0 vn=
n7n       istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab3760] bci=[-1,6,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n6n         iconst 0                                                                          [  0x33ab3710] bci=[-1,5,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n13n      fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab3940] bci=[-1,15,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n12n        floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.y F[#372  final Shadow +12] [flags 0xa0605 0x0 ]  [  0x33ab38f0] bci=[-1,12,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n11n          aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab38a0] bci=[-1,11,7] rc=1 vc=0 vn
n15n      istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab39e0] bci=[-1,17,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n14n        iconst 0                                                                          [  0x33ab3990] bci=[-1,16,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n18n      treetop                                                                             [  0x33ab3ad0] bci=[-1,19,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n17n        fcall  java/lang/Math.abs(F)F[#371  final static Method] [flags 0x20500 0x0 ]     [  0x33ab3a80] bci=[-1,19,7] rc=2 vc=0 vn=- li=- udi=- nc=1
n16n          fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                               [  0x33ab3a30] bci=[-1,18,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n23n      treetop                                                                             [  0x33ab3c60] bci=[-1,27,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n19n        fadd                                                                              [  0x33ab3b20] bci=[-1,22,7] rc=2 vc=0 vn=- li=- udi=- nc=2
n9n           fabs                                                                            [  0x33ab3800] bci=[-1,8,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n8n             fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                             [  0x33ab37b0] bci=[-1,7,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n17n          ==>fcall
n22n      fstore  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                                  [  0x33ab3c10] bci=[-1,27,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n21n        floadi  com/travisfw/voxelsphere/lwjgl3/Vector3.z F[#373  final Shadow +16] [flags 0xa0605 0x0 ]  [  0x33ab3bc0] bci=[-1,24,7] rc=1 vc=0 vn=- li=- udi=- nc=1
n20n          aload  this<'this' parm Lcom/travisfw/voxelsphere/lwjgl3/Vector3;>[#366  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [  0x33ab3b70] bci=[-1,23,7] rc=1 vc=0 vn
n25n      istore  <auto slot 2>[#369  Auto] [flags 0x3 0x0 ]                                  [  0x33ab3d00] bci=[-1,29,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n24n        iconst 0                                                                          [  0x33ab3cb0] bci=[-1,28,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n28n      treetop                                                                             [  0x33ab3df0] bci=[-1,31,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n27n        fcall  java/lang/Math.abs(F)F[#371  final static Method] [flags 0x20500 0x0 ]     [  0x33ab3da0] bci=[-1,31,7] rc=2 vc=0 vn=- li=- udi=- nc=1
n26n          fload  <auto slot 1>[#368  Auto] [flags 0x5 0x0 ]                               [  0x33ab3d50] bci=[-1,30,7] rc=1 vc=0 vn=- li=- udi=- nc=0
n30n      freturn                                                                             [  0x33ab3e90] bci=[-1,35,7] rc=0 vc=0 vn=- li=- udi=- nc=1
n29n        fadd                                                                              [  0x33ab3e40] bci=[-1,34,7] rc=1 vc=0 vn=- li=- udi=- nc=2
n19n          ==>fadd
n27n          ==>fcall
n2n       BBEnd </block_2>                                                                    [  0x33ab35d0] bci=[-1,35,7] rc=0 vc=0 vn=- li=- udi=- nc=0
```

The problem here is that the reoduction of `fcall java/lang/Math.abs(F)F` to `fabs` removed the original tree top, that is node `n10n`. This forces the `fabs` node to swing down to it's only use. The issue with this is that the descendants of the `fabs` node may have had side effects, and in this case they do. There is a load from slot 1 underneath the `fabs`. This stack slot 1 is re-used for other computations, and by removing the treetop we have altered the semantics of the program because the load has now swung down.

All in all the effect of this transformation makes us compute:
```
abs(y) + abs(y) + abs(z)
```

instead of:
```
abs(x) + abs(y) + abs(z)
```

The fix is simple. Don't remove the treetop during recognized call transformer optimization! Going to take an hour or so to come up with a unit test with Java and check this in so we don't get bit by this in the future.

**Comment by fjeremic** [comment]
For completeness here is a few raw runs of the program:

```
fjeremic@Filips-MacBook-Pro kotlin-bug % ../x86-pre-write-barrier/jdk-11.0.9+11/Contents/Home/bin/java -Xjit:'limit={com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F}(count=0,lastOptIndex=5,lastOptSubIndex=1,traceFull,log=log.trace),disableAsynccompilation,enablefastscorchingrecompilation' -Xnoaot -Xmx4G -Xms4G -jar test.jar
Exception in thread "main" java.lang.Exception: taxiFromcenter are not equal 306.0 (Vector3(x=-32.0, y=-9.0, z=265.0)) 283.0 (Vector3(x=-32.0, y=-9.0, z=265.0)) - recomputed = 283.0
	at com.travisfw.voxelsphere.lwjgl3.TestKt.main(test.kt:22)

fjeremic@Filips-MacBook-Pro kotlin-bug % ../x86-pre-write-barrier/jdk-11.0.9+11/Contents/Home/bin/java -Xjit:'limit={com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F}(count=0,lastOptIndex=5,lastOptSubIndex=1,traceFull,log=log.trace),disableAsynccompilation,enablefastscorchingrecompilation' -Xnoaot -Xmx4G -Xms4G -jar test.jar
Exception in thread "main" java.lang.Exception: taxiFromcenter are not equal 132.0 (Vector3(x=-32.0, y=-8.0, z=92.0)) 108.0 (Vector3(x=-32.0, y=-8.0, z=92.0)) - recomputed = 108.0
	at com.travisfw.voxelsphere.lwjgl3.TestKt.main(test.kt:22)

fjeremic@Filips-MacBook-Pro kotlin-bug % ../x86-pre-write-barrier/jdk-11.0.9+11/Contents/Home/bin/java -Xjit:'limit={com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F}(count=0,lastOptIndex=5,lastOptSubIndex=1,traceFull,log=log.trace),disableAsynccompilation,enablefastscorchingrecompilation' -Xnoaot -Xmx4G -Xms4G -jar test.jar
^C%                                                              
                                                                                                                   fjeremic@Filips-MacBook-Pro kotlin-bug % ../x86-pre-write-barrier/jdk-11.0.9+11/Contents/Home/bin/java -Xjit:'limit={com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F}(count=0,lastOptIndex=5,lastOptSubIndex=1,traceFull,log=log.trace),disableAsynccompilation,enablefastscorchingrecompilation' -Xnoaot -Xmx4G -Xms4G -jar test.jar
Exception in thread "main" java.lang.Exception: taxiFromcenter are not equal 218.0 (Vector3(x=-32.0, y=30.0, z=156.0)) 216.0 (Vector3(x=-32.0, y=30.0, z=156.0)) - recomputed = 216.0
	at com.travisfw.voxelsphere.lwjgl3.TestKt.main(test.kt:22)

fjeremic@Filips-MacBook-Pro kotlin-bug % ../x86-pre-write-barrier/jdk-11.0.9+11/Contents/Home/bin/java -Xjit:'limit={com/travisfw/voxelsphere/lwjgl3/Vector3.taxiDistance()F}(count=0,lastOptIndex=5,lastOptSubIndex=1,traceFull,log=log.trace),disableAsynccompilation,enablefastscorchingrecompilation' -Xnoaot -Xmx4G -Xms4G -jar test.jar
Exception in thread "main" java.lang.Exception: taxiFromcenter are not equal 121.0 (Vector3(x=-32.0, y=31.0, z=58.0)) 120.0 (Vector3(x=-32.0, y=31.0, z=58.0)) - recomputed = 120.0
	at com.travisfw.voxelsphere.lwjgl3.TestKt.main(test.kt:22)
```

Not that we are always computing `2*abs(y) + abs(z)` in the failing cases.
