### ISSUE TITLE
JDK15 java/foreign/TestMemoryAccess.java AssertionError: expected [2.91E-43] but found [0.0]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11075]
Failure link
------------

From an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Nightly/85`:
```
22:27:32  openjdk version "15.0.1-internal" 2020-10-20
22:27:32  OpenJDK Runtime Environment (build 15.0.1-internal+0-adhoc.jenkins.BuildJDK15ppc64aixNightly)
22:27:32  Eclipse OpenJ9 VM (build master-40f5a961545, JRE 15 AIX ppc64-64-Bit Compressed References 20201101_121 (JIT enabled, AOT enabled)
22:27:32  OpenJ9   - 40f5a961545
22:27:32  OMR      - 4ede03ca616
22:27:32  JCL      - 425fa83a6d0 based on jdk-15.0.1+9)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
00:51:22  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_foreign_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
TestMemoryAccess$MatrixChecker$$Lambda$74/0x0000000022898568@f7f909c1): failure
00:36:52  java.lang.AssertionError: expected [2.91E-43] but found [0.0]
00:36:52  	at org.testng.Assert.fail(Assert.java:94)
00:36:52  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:36:52  	at org.testng.Assert.assertEquals(Assert.java:125)
00:36:52  	at org.testng.Assert.assertEquals(Assert.java:167)
00:36:52  	at TestMemoryAccess$MatrixChecker.lambda$static$5(TestMemoryAccess.java:447)
00:36:52  	at TestMemoryAccess$MatrixChecker$$Lambda$74/0x0000000022898568.check(Unknown Source)
00:36:52  	at TestMemoryAccess.testMatrixAccessInternal(TestMemoryAccess.java:193)
00:36:52  	at TestMemoryAccess.testMatrixAccess(TestMemoryAccess.java:154)
00:36:52  	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
00:36:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:36:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:36:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:36:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:36:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:36:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:36:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:36:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:36:52  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:36:52  	at org.testng.TestRunner.run(TestRunner.java:623)
00:36:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:36:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:36:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:36:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:36:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:36:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:36:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:36:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:36:52  	at org.testng.TestNG.run(TestNG.java:1018)
00:36:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:36:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:36:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:36:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:36:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:36:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:36:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:36:52  	at java.base/java.lang.Thread.run(Thread.java:844)

TestMemoryAccess$Checker$$Lambda$36/0x000000002288cb38@4e6ecac3): failure
00:36:52  java.lang.AssertionError: expected [2.91E-43] but found [42.0]
00:36:52  	at org.testng.Assert.fail(Assert.java:94)
00:36:52  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:36:52  	at org.testng.Assert.assertEquals(Assert.java:125)
00:36:52  	at org.testng.Assert.assertEquals(Assert.java:167)
00:36:52  	at TestMemoryAccess$Checker.lambda$static$5(TestMemoryAccess.java:293)
00:36:52  	at TestMemoryAccess$Checker$$Lambda$36/0x000000002288cb38.check(Unknown Source)
00:36:52  	at TestMemoryAccess.testAccessInternal(TestMemoryAccess.java:90)
00:36:52  	at TestMemoryAccess.testPaddedAccessByIndexSeq(TestMemoryAccess.java:63)
00:36:52  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
00:36:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:36:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:36:52  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:36:52  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:36:52  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:36:52  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:36:52  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
00:36:52  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:36:52  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:36:52  	at org.testng.TestRunner.run(TestRunner.java:623)
00:36:52  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:36:52  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:36:52  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:36:52  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:36:52  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:36:52  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:36:52  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:36:52  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:36:52  	at org.testng.TestNG.run(TestNG.java:1018)
00:36:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:36:52  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
00:36:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:36:52  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
00:36:52  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:36:52  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:36:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:36:52  	at java.base/java.lang.Thread.run(Thread.java:844)

00:36:52  
00:36:52  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 8
00:36:52  --------------------------------------------------
```

**Comment by fjeremic** [comment]
A combination of the following PRs have addressed this issue:
https://github.com/eclipse/omr/pull/5645
https://github.com/eclipse/omr/pull/5646
https://github.com/eclipse/omr/pull/5653
https://github.com/eclipse/openj9/pull/11079
https://github.com/eclipse/openj9/pull/11096
