### ISSUE TITLE
JDK8 Win32 DaaLoadTest_daa2_0_FAILED JUnit[net.openj9.test.binaryData.TestBinaryConverters] 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11077]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/490`:
```
23:16:34  openjdk version "1.8.0_272-internal"
23:16:34  OpenJDK Runtime Environment (build 1.8.0_272-internal-jenkins_2020_11_01_18_29-b00)
23:16:34  Eclipse OpenJ9 VM (build master-40f5a961545, JRE 1.8.0 Windows Server 2016 x86-32-Bit 20201101_568 (JIT enabled, AOT enabled)
23:16:34  OpenJ9   - 40f5a961545
23:16:34  OMR      - 4ede03ca616
23:16:34  JCL      - 8425b0a2dcf based on jdk8u272-b10)
```
to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
00:20:10  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-32_windows&TARGET=DaaLoadTest_daa2_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
=============================================== 
Running test DaaLoadTest_daa2_0 ... 
===============================================

DLT 20:18:22.991 -   27 JUnit[net.openj9.test.PD2Primitive.TestPD2I]  Weighting=1 
DLT 20:18:23.070 - Starting thread. Suite=0 thread=0
DLT 20:18:23.085 - Starting thread. Suite=0 thread=1
DLT 20:18:23.085 - Starting thread. Suite=0 thread=2
DLT 20:18:23.085 - Starting thread. Suite=0 thread=3
DLT 20:18:23.085 - Starting thread. Suite=0 thread=4
DLT 20:18:23.085 - Starting thread. Suite=0 thread=5
DLT 20:18:24.866 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
DLT 20:18:24.882 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/daa/daa2.xml
DLT 20:18:24.882 - suite.isCreateDump() : false
DLT 20:18:24.882 - Test failed
DLT   Failure num.  = 1
DLT   Test number   = 4
DLT   Test details  = 'JUnit[net.openj9.test.binaryData.TestBinaryConverters]'
DLT   Suite number  = 0
DLT   Thread number = 0
DLT >>> Captured test output >>>

DLT Reason expected(as double):<9.0> result(as double):<4.332E-320>  expected:<4621256167635550208> but was:<8768>
DLT 	at org.junit.Assert.fail(Assert.java:88)
DLT 	at org.junit.Assert.failNotEquals(Assert.java:834)
DLT 	at org.junit.Assert.assertEquals(Assert.java:645)
DLT 	at net.openj9.test.binaryData.TestBinaryConverters.assertEqualsDouble(TestBinaryConverters.java:3992)
DLT 	at net.openj9.test.binaryData.TestBinaryConverters.testDoubleNormals(TestBinaryConverters.java:3513)
DLT 	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
DLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DLT 	at java.lang.reflect.Method.invoke(Method.java:498)
DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
DLT 	at java.lang.Thread.run(Thread.java:822)

DLT JUnit Test Results for: net.openj9.test.binaryData.TestBinaryConverters
DLT   Ran    : 10
DLT   Passed : 8
DLT   Failed : 2
DLT   Ignored: 0
DLT   Result : FAILED
DLT <<<

DaaLoadTest_daa2_0_FAILED
```

**Comment by fjeremic** [comment]
A combination of the following PRs have addressed this issue:
https://github.com/eclipse/omr/pull/5645
https://github.com/eclipse/omr/pull/5646
https://github.com/eclipse/omr/pull/5653
https://github.com/eclipse/openj9/pull/11079
https://github.com/eclipse/openj9/pull/11096
