### ISSUE TITLE
JDK11 AIX java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java AssertionError: weakCompareAndSet float expected [true] but found [false]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11074]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/483`:
```
22:15:47  openjdk version "11.0.9-internal" 2020-10-20
22:15:47  OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
22:15:47  Eclipse OpenJ9 VM (build master-40f5a961545, JRE 11 AIX ppc64-64-Bit Compressed References 20201101_615 (JIT enabled, AOT enabled)
22:15:47  OpenJ9   - 40f5a961545
22:15:47  OMR      - 4ede03ca616
22:15:47  JCL      - 39a80556b52 based on jdk-11.0.9+11)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
00:09:26  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:38:59  [TestNG] Running:
22:38:59    java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java
22:38:59  java.lang.AssertionError: weakCompareAndSet float expected [true] but found [false]
22:38:59  	at org.testng.Assert.fail(Assert.java:94)
22:38:59  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:38:59  	at org.testng.Assert.assertEquals(Assert.java:125)
22:38:59  	at org.testng.Assert.assertEquals(Assert.java:288)
22:38:59  	at VarHandleTestByteArrayAsFloat.testArrayReadWrite(VarHandleTestByteArrayAsFloat.java:1084)
22:38:59  	at VarHandleTestByteArrayAsFloat.lambda$accessTestCaseProvider$0(VarHandleTestByteArrayAsFloat.java:139)
22:38:59  	at VarHandleTestByteArrayAsFloat$$Lambda$7/0x0000000000000000.action(Unknown Source)
22:38:59  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
22:38:59  	at VarHandleTestByteArrayAsFloat.testAccess(VarHandleTestByteArrayAsFloat.java:196)
22:38:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:38:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:38:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:38:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:38:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:38:59  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:38:59  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:38:59  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
22:38:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
22:38:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
22:38:59  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
22:38:59  	at org.testng.TestRunner.run(TestRunner.java:623)
22:38:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
22:38:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
22:38:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
22:38:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
22:38:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
22:38:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
22:38:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
22:38:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
22:38:59  	at org.testng.TestNG.run(TestNG.java:1018)
22:38:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
22:38:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
22:38:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:38:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:38:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:38:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22:38:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:38:59  	at java.base/java.lang.Thread.run(Thread.java:835)

22:38:59  ===============================================
22:38:59  java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java
22:38:59  Total tests run: 138, Failures: 1, Skips: 0
22:38:59  ===============================================
```

**Comment by fjeremic** [comment]
A combination of the following PRs have addressed this issue:
https://github.com/eclipse/omr/pull/5645
https://github.com/eclipse/omr/pull/5646
https://github.com/eclipse/omr/pull/5653
https://github.com/eclipse/openj9/pull/11079
https://github.com/eclipse/openj9/pull/11096
