### ISSUE TITLE
jtreg ThreadMXBeanProxy Number of locked monitors = 2 not matched. Expected: 1

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11113]
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1156
test/jdk/java/lang/management/ManagementFactory/ThreadMXBeanProxy.java

I ran it on zlinux using the last nightly build, but it's not platform specific. This test isn't run as part of sanity.openjdk.

https://ci.eclipse.org/openj9/job/Grinder/parambuild/?TARGET=jdk_custom&CUSTOM_TARGET=test%2Fjdk%2Fjava%2Flang%2Fmanagement%2FManagementFactory%2FThreadMXBeanProxy.java&SDK_RESOURCE=customized&DEBUG_IMAGES_REQUIRED=false&JDK_BRANCH=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&TEST_IMAGES_REQUIRED=false&DOCKER_REQUIRED=false&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&LABEL_ADDITION=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&ARTIFACTORY_REPO=ci-eclipse-openj9&ARTIFACTORY_ROOT_DIR=Test&PLATFORM=s390x_linux&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&UPSTREAM_TEST_JOB_NUMBER=&JDK_IMPL=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2F140-211-168-230-openstack.osuosl.org%2Fartifactory%2Fci-eclipse-openj9%2FBuild_JDK11_s390x_linux_Nightly%2F558%2FOpenJ9-JDK11-s390x_linux-20201105-003349.tar.gz&AUTO_DETECT=true&ADOPTOPENJDK_BRANCH=master&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=AdoptOpenJDK%3Amaster&ARTIFACTORY_SERVER=ci-eclipse-openj9&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=1&KEEP_WORKSPACE=false&BUILD_LIST=openjdk&JDK_VERSION=&UPSTREAM_JOB_NUMBER=&ITERATIONS=1&STF_OWNER_BRANCH=AdoptOpenJDK%3Amaster&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&JVM_OPTIONS=&PARALLEL=None

```
10:48:32  java.lang.RuntimeException: Number of locked monitors = 2 not matched. Expected: 1
10:48:32  	at ThreadMXBeanProxy$MyThread.checkThreadInfo(ThreadMXBeanProxy.java:139)
10:48:32  	at ThreadMXBeanProxy.main(ThreadMXBeanProxy.java:86)
10:48:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:48:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:48:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:48:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:48:32  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
10:48:32  	at java.base/java.lang.Thread.run(Thread.java:835)
```

The test counts the ThreadInfo.getLockedMonitors(). It seems OpenJ9 is returning `waiter` as a locked monitor, although it's in state `waiter.wait()`.

I created a smaller, standalone test case.
[test4.zip](https://github.com/eclipse/openj9/files/5495703/test4.zip)
```
Test4$MyThread.run(Test4.java:59)
Test4$MyThread.run(Test4.java:59)
Exception in thread "main" java.lang.RuntimeException: Number of locked monitors = 2 not matched. Expected: 1
	at Test4$MyThread.checkThreadInfo(Test4.java:80)
	at Test4.main(Test4.java:45)
```

@tajila fyi

**Comment by tajila** [comment]
@JasonFengJ9 can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure, will look into this.

**Comment by gacholio** [comment]
Stack being queried:
```
<703b00> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x0000000000703B00 ***
<703b00> 	ITERATE_O_SLOTS
<703b00> 	RECORD_BYTECODE_PC_OFFSET
<703b00> Initial values: walkSP = 0x000000000071F5E0, PC = 0x0000000000000003, literals = 0x0000000000000000, A0 = 0x000000000071F620, j2iFrame = 0x0000000000000000, ELS = 0x00007FFFEEB7BB50, decomp = 0x0000000000000000
<703b00> INL native method frame: bp = 0x000000000071F600, sp = 0x000000000071F5E0, pc = 0x0000000000000003, cp = 0x0000000000000000, arg0EA = 0x000000000071F620, flags = 0x0000000000000000
<703b00> 	Method: java/lang/Object.wait(JI)V !j9method 0x000000000062A620
<703b00> 	Using signature mapper
<703b00> 	Arguments starting at 0x000000000071F620 for UDATA(0x0000000000000004) slots
<703b00> 		O-Slot: a0[0x000000000071F620] = 0x00000000FFFBA540
<703b00> 		I-Slot: a1[0x000000000071F618] = 0x000000000062A580
<703b00> 		I-Slot: a2[0x000000000071F610] = 0x0000000000000000
<703b00> 		I-Slot: a3[0x000000000071F608] = 0x0000000000000000
<703b00> Bytecode frame: bp = 0x000000000071F638, sp = 0x000000000071F628, pc = 0x00007FFFEF78034F, cp = 0x000000000062A660, arg0EA = 0x000000000071F640, flags = 0x0000000000000000
<703b00> 	Method: java/lang/Object.wait()V !j9method 0x000000000062A5E0
<703b00> 	Bytecode index = 3
<703b00> 	Using local mapper
<703b00> 	Locals starting at 0x000000000071F640 for 0x0000000000000001 slots
<703b00> 		I-Slot: a0[0x000000000071F640] = 0x00000000FFFBA540
<703b00> Bytecode frame: bp = 0x000000000071F658, sp = 0x000000000071F648, pc = 0x00007FFFF040BE7D, cp = 0x00000000007441C0, arg0EA = 0x000000000071F678, flags = 0x0000000000000000
<703b00> 	Method: Test4$MyThread.run()V !j9method 0x0000000000743E60
<703b00> 	Bytecode index = 21
<703b00> 	Using local mapper
<703b00> 	Locals starting at 0x000000000071F678 for 0x0000000000000004 slots
<703b00> 		I-Slot: a0[0x000000000071F678] = 0x00000000FFFBBA30
<703b00> 		O-Slot: t1[0x000000000071F670] = 0x00000000FFFBA530
<703b00> 		O-Slot: t2[0x000000000071F668] = 0x00000000FFFBA540
<703b00> 		I-Slot: t3[0x000000000071F660] = 0x0000000000000000
<703b00> JNI call-in frame: bp = 0x000000000071F6A0, sp = 0x000000000071F680, pc = 0x00007FFFF68F193D, cp = 0x0000000000000000, arg0EA = 0x000000000071F6A0, flags = 0x0000000000000000
<703b00> 	New ELS = 0x0000000000000000
<703b00> JNI native method frame: bp = 0x000000000071F6C8, sp = 0x000000000071F6A8, pc = 0x0000000000000007, cp = 0x0000000000000000, arg0EA = 0x000000000071F6C8, flags = 0x0000000000000000
<703b00> <end of stack>
<703b00> *** END STACK WALK (rc = NONE) ***
```

**Comment by gacholio** [comment]
Monitor enter records:
```
(gdb) p targetThread->monitorEnterRecords 
$1 = (struct J9MonitorEnterRecord *) 0x7ffff042c108
(gdb) p *targetThread->monitorEnterRecords
$2 = {object = 0xfffba540, arg0EA = 0x58, dropEnterCount = 1, next = 0x7ffff042c0e0}
(gdb) p *(struct J9MonitorEnterRecord *) 0x7ffff042c0e0
$3 = {object = 0xfffba530, arg0EA = 0x58, dropEnterCount = 1, next = 0x0}
```

**Comment by JasonFengJ9** [comment]
Just a quick note, this issue is not recent regression, it is reproducible with a 2015 Java 8 build.

**Comment by gacholio** [comment]
Both enter records are for the `run` frame, which makes sense given the bytecodes:
```
    0 getstatic 10 Test4.lock Ljava/lang/Object;
    3 dup 
    4 astore1 
    5 monitorenter 
    6 getstatic 12 Test4.waiter Ljava/lang/Object;
    9 dup 
   10 astore2 
   11 monitorenter 
   12 getstatic 12 Test4.waiter Ljava/lang/Object;
   15 invokespecial 13 java/lang/Object.notify()V
   18 getstatic 12 Test4.waiter Ljava/lang/Object;
   21 invokespecial 15 java/lang/Object.wait()V
```

**Comment by gacholio** [comment]
Two monitors have been entered - maybe the test is expecting the one being waited on not to be counted.

**Comment by pshipton** [comment]
> maybe the test is expecting the one being waited on not to be counted.

That was the impression I got.
