### ISSUE TITLE
MathLoadTest_autosimd_special_22 didn't exit

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11191]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64_aix_Nightly_mathLoadTest/186/
MathLoadTest_autosimd_special_22
variation: Mode614
JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:counts=- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000,gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xmn512k -Xcheck:gc:vmthreads:all:quiet
aix71-p8-10
```
MLT 03:41:46.353 - Load test completed
MLT 03:41:46.353 -   Ran     : 160000
MLT 03:41:46.353 -   Passed  : 160000
MLT 03:41:46.353 -   Failed  : 0
MLT 03:41:46.353 -   Result  : PASSED
STF 03:46:08.157 - Heartbeat: Process MLT is still running
STF 03:46:09.161 - **FAILED** Process MLT has timed out
STF 03:46:09.161 - Collecting dumps for: MLT
```

For diagnostics there are 5 javacore files, a core file, others
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_special.system_ppc64_aix_Nightly_mathLoadTest/186/system_mathLoadTest_test_output.tar.gz
I see JIT-SamplerThread, 2 Anonymous native thread, GC Worker threads, Finalizer thread, IProfiler, Concurrent Mark Helper, JIT Compilation Thread-005
```
3XMTHREADINFO      "main" J9VMThread:0x000000003000E700, omrthread_t:0x0000010010052D80, java/lang/Thread:0x00000000800131A8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x4160283, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000081)
3XMCPUTIME               CPU usage total: 0.958857000 secs, user: 0.910571000 secs, system: 0.048286000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4592 (0x11F0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Shutdown.halt0(Native Method)
4XESTACKTRACE                at java/lang/Shutdown.halt(Shutdown.java:142)
5XESTACKTRACE                   (entered lock: java/lang/Shutdown$Lock@0x0000000080038AF0, entry count: 1)
4XESTACKTRACE                at java/lang/Shutdown.exit(Shutdown.java:217)
5XESTACKTRACE                   (entered lock: java/lang/Shutdown@0x0000000080050998, entry count: 1)
4XESTACKTRACE                at java/lang/Runtime.exit(Runtime.java:109)
4XESTACKTRACE                at java/lang/System.exit(System.java:345)
4XESTACKTRACE                at net/adoptopenjdk/loadTest/LoadTest.main(LoadTest.java:130)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               _event_wait+0x344 (0x09000000005843C8 [libpthreads.a+0x173c8])
4XENATIVESTACK               _cond_wait_local+0x4dc (0x0900000000592920 [libpthreads.a+0x25920])
4XENATIVESTACK               _cond_wait+0xc8 (0x0900000000592F0C [libpthreads.a+0x25f0c])
4XENATIVESTACK               pthread_cond_wait+0x19c (0x0900000000593B60 [libpthreads.a+0x26b60])
4XENATIVESTACK               IPRA.$monitor_wait_original+0x9b0 (0x09000000128ACD34 [libj9thr29.so+0x9d34])
4XENATIVESTACK               omrthread_monitor_wait+0x40 (0x09000000128AC104 [libj9thr29.so+0x9104])
4XENATIVESTACK               (0x0900000012C3D094 [libj9jit29.so+0x1e7094])
4XENATIVESTACK               (0x090000001338CABC [libj9jit29.so+0x936abc])
4XENATIVESTACK               (0x090000001338BC20 [libj9jit29.so+0x935c20])
4XENATIVESTACK               exitJavaVM+0x330 (0x090000001261F4F4 [libj9vm29.so+0x84f4])
4XENATIVESTACK               JVM_Halt_Impl+0xbc (0x09000000145E8C20 [libjclse29.so+0x92c20])
4XENATIVESTACK               JVM_Halt+0x44 (0x09000000125C3BE8 [libjvm.so+0xfbe8])
4XENATIVESTACK               JVM_Halt+0xc4 (0x09000000125823C8 [libjvm.so+0x63c8])
4XENATIVESTACK               Java_java_lang_Shutdown_halt0+0x10 (0x090000001462D3F4 [libjava.so+0x143f4])
4XENATIVESTACK               (0x09000000127EA63C [libj9vm29.so+0x1d363c])
4XENATIVESTACK               ffi_call+0x98 (0x09000000127E991C [libj9vm29.so+0x1d291c])
4XENATIVESTACK               (0x09000000127EEFE4 [libj9vm29.so+0x1d7fe4])
4XENATIVESTACK               (0x090000001268717C [libj9vm29.so+0x7017c])
4XENATIVESTACK               runCallInMethod+0x264 (0x0900000012683C48 [libj9vm29.so+0x6cc48])
4XENATIVESTACK               gpProtectedRunCallInMethod__FPv+0x48 (0x090000001267434C [libj9vm29.so+0x5d34c])
4XENATIVESTACK               signalProtectAndRunGlue+0x28 (0x090000001266DFAC [libj9vm29.so+0x56fac])
4XENATIVESTACK               omrsig_protect+0x488 (0x09000000129205CC [libj9prt29.so+0x595cc])
4XENATIVESTACK               gpProtectAndRun+0xf8 (0x090000001266E0FC [libj9vm29.so+0x570fc])
4XENATIVESTACK               gpCheckCallin+0x114 (0x09000000126742B8 [libj9vm29.so+0x5d2b8])
4XENATIVESTACK               callStaticVoidMethod+0x48 (0x09000000126CE20C [libj9vm29.so+0xb720c])
4XENATIVESTACK               (0x0000010000004838 [java+0x4838])
4XENATIVESTACK               _pthread_body+0xf0 (0x0900000000570E14 [libpthreads.a+0x3e14])
```

**Comment by pshipton** [comment]
@gita-omr someone should take a look at this hang on exit.

**Comment by gita-omr** [comment]
Yes.

**Comment by pshipton** [comment]
Try some grinders https://ci.eclipse.org/openj9/job/Grinder/1175/

**Comment by pshipton** [comment]
Not easily recreatable, but worth looking at the existing core file.

**Comment by pshipton** [comment]
Trying to open the core file in jdmpview gives "No JRE".
