### ISSUE TITLE
CMake windows test failure in VarHandleTestMethodHandleAccessX

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#11222]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/213/ (win2012-x86-3)

Optional info
-------------

- intermittent failure (yes|no): appears to be intermittent, investigating further
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) : Appears to be related to switch to cmake default (jdk extensions repo).

Failure output (captured from console output)
---------------------------------------------
```
 --------------------------------------------------
[2020-11-18T04:35:45.270Z] TEST: java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java
[2020-11-18T04:35:45.270Z] TEST JDK: F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image
[2020-11-18T04:35:45.270Z] 
[2020-11-18T04:35:45.270Z] ACTION: build -- Passed. Build successful
[2020-11-18T04:35:45.270Z] REASON: Named class compiled on demand
[2020-11-18T04:35:45.270Z] TIME:   0.797 seconds
[2020-11-18T04:35:45.270Z] messages:
[2020-11-18T04:35:45.270Z] command: build VarHandleTestMethodHandleAccessLong
[2020-11-18T04:35:45.270Z] reason: Named class compiled on demand
[2020-11-18T04:35:45.270Z] Test directory:
[2020-11-18T04:35:45.270Z]   compile: VarHandleTestMethodHandleAccessLong
[2020-11-18T04:35:45.270Z] elapsed time (seconds): 0.797
[2020-11-18T04:35:45.270Z] 
[2020-11-18T04:35:45.270Z] ACTION: compile -- Passed. Compilation successful
[2020-11-18T04:35:45.270Z] REASON: .class file out of date or does not exist
[2020-11-18T04:35:45.270Z] TIME:   0.797 seconds
[2020-11-18T04:35:45.270Z] messages:
[2020-11-18T04:35:45.270Z] command: compile F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.java
[2020-11-18T04:35:45.270Z] reason: .class file out of date or does not exist
[2020-11-18T04:35:45.270Z] Mode: agentvm
[2020-11-18T04:35:45.270Z] Agent id: 4
[2020-11-18T04:35:45.270Z] elapsed time (seconds): 0.797
[2020-11-18T04:35:45.270Z] configuration:
[2020-11-18T04:35:45.270Z] Boot Layer (javac runtime environment)
[2020-11-18T04:35:45.270Z]   class path: F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\javatest.jar 
[2020-11-18T04:35:45.270Z]               F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jtreg.jar 
[2020-11-18T04:35:45.270Z]   patch:      java.base F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\patches\java.base
[2020-11-18T04:35:45.270Z] 
[2020-11-18T04:35:45.270Z] javac compilation environment
[2020-11-18T04:35:45.270Z]   source path: F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles
[2020-11-18T04:35:45.270Z]   class path:  F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles
[2020-11-18T04:35:45.270Z]                F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d
[2020-11-18T04:35:45.270Z]                F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\testng.jar
[2020-11-18T04:35:45.270Z]                F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jcommander.jar
[2020-11-18T04:35:45.270Z] 
[2020-11-18T04:35:45.270Z] rerun:
[2020-11-18T04:35:45.271Z] cd 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\scratch\3' && \
[2020-11-18T04:35:45.271Z] PATH='C:\cygwin64\bin;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files\Java\jdk8u202-b08\bin;C:\Strawberry\perl\bin;C:\Program Files\Microsoft Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\OpenSSL-1.1.1-x86_32\bin;C:\OpenSSL-1.1.1-x86_64\bin;C:\Program Files (x86)\IncrediBuild;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0' \
[2020-11-18T04:35:45.271Z] SystemDrive=C: \
[2020-11-18T04:35:45.271Z] SystemRoot='C:\Windows' \
[2020-11-18T04:35:45.271Z] TEMP='C:\temp' \
[2020-11-18T04:35:45.271Z] windir='C:\Windows' \
[2020-11-18T04:35:45.271Z]     'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\javac' \
[2020-11-18T04:35:45.271Z]         -J-ea \
[2020-11-18T04:35:45.271Z]         -J-esa \
[2020-11-18T04:35:45.271Z]         -J-Xmx512m \
[2020-11-18T04:35:45.271Z]         -J-Xdump:system:none \
[2020-11-18T04:35:45.271Z]         -J-Xdump:heap:none \
[2020-11-18T04:35:45.271Z]         -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
[2020-11-18T04:35:45.271Z]         -J-XX:-JITServerTechPreviewMessage \
[2020-11-18T04:35:45.271Z]         -J-Xdump:system+java:events=throw,filter=java/lang/NullPointerException#*java/lang/invoke/BruteArgumentMoverHandle.permuteArguments* \
[2020-11-18T04:35:45.271Z]         -J'-Djava.library.path=F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xdump:system+java:events=throw,filter=java/lang/NullPointerException#*java/lang/invoke/BruteArgumentMoverHandle.permuteArguments*' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage -J-Xdump:system+java:events=throw,filter=java/lang/NullPointerException#*java/lang/invoke/BruteArgumentMoverHandle.permuteArguments*' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.compiler.opts= \
[2020-11-18T04:35:45.271Z]         -J-Dtest.java.opts= \
[2020-11-18T04:35:45.271Z]         -J-Dtest.jdk='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
[2020-11-18T04:35:45.271Z]         -J-Dcompile.jdk='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.timeout.factor=8.0 \
[2020-11-18T04:35:45.271Z]         -J-Dtest.nativepath='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.root='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.name=java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java \
[2020-11-18T04:35:45.271Z]         -J-Dtest.file='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.java' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.src='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.src.path='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.classes='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.class.path='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d' \
[2020-11-18T04:35:45.271Z]         -J-Dtest.class.path.prefix='F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles' \
[2020-11-18T04:35:45.271Z]         -d 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d' \
[2020-11-18T04:35:45.271Z]         -sourcepath 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles' \
[2020-11-18T04:35:45.271Z]         -classpath 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16056738866824\jdk_lang_j9_0\work\classes\1\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.d;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\testng.jar;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\jvmtest\openjdk\jtreg\lib\jcommander.jar' 'F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\invoke\VarHandles\VarHandleTestMethodHandleAccessLong.java'
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.BootstrapMethodError: java.lang.NullPointerException
[2020-11-18T04:35:45.271Z] REASON: User specified action: run testng/othervm -Diters=20000 VarHandleTestMethodHandleAccessLong 
[2020-11-18T04:35:45.271Z] TIME:   16.11 seconds
[2020-11-18T04:35:45.271Z] messages:
[2020-11-18T04:35:45.271Z] command: testng -Diters=20000 VarHandleTestMethodHandleAccessLong
[2020-11-18T04:35:45.271Z] reason: User specified action: run testng/othervm -Diters=20000 VarHandleTestMethodHandleAccessLong 
[2020-11-18T04:35:45.271Z] Mode: othervm [/othervm specified]
[2020-11-18T04:35:45.271Z] elapsed time (seconds): 16.11
[2020-11-18T04:35:45.271Z] configuration:
[2020-11-18T04:35:45.271Z] STDOUT:
[2020-11-18T04:35:45.271Z] [TestNG] Running:
[2020-11-18T04:35:45.271Z]   java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] config VarHandleTestMethodHandleAccessLong.setup(): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Instance field", VarHandleBaseTest$MethodHandleAccessTestCase@7d91337a): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Instance field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@feba4123): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Static field", VarHandleBaseTest$MethodHandleAccessTestCase@44cf9d13): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Static field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@cb1b987a): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Array", VarHandleBaseTest$MethodHandleAccessTestCase@7dfc81a9): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Array unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@f567fc08): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> VarHandle.toMethodHandle -> Array index out of bounds", VarHandleBaseTest$MethodHandleAccessTestCase@6d8bc8d3): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Instance field", VarHandleBaseTest$MethodHandleAccessTestCase@e7ead7c3): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Instance field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@ae5bc540): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Static field", VarHandleBaseTest$MethodHandleAccessTestCase@defa2543): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Static field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@e4c0d860): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Array", VarHandleBaseTest$MethodHandleAccessTestCase@7e570b7a): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Array unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@ad4ddf9f): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> Lookup.findVirtual -> Array index out of bounds", VarHandleBaseTest$MethodHandleAccessTestCase@50b60d51): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Instance field", VarHandleBaseTest$MethodHandleAccessTestCase@5adcd1bd): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Instance field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@9f7c3375): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Static field", VarHandleBaseTest$MethodHandleAccessTestCase@162860ab): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Static field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@101f0ae): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Array", VarHandleBaseTest$MethodHandleAccessTestCase@334ed0d2): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Array unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@36f9a1c4): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Array index out of bounds", VarHandleBaseTest$MethodHandleAccessTestCase@2519acc): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Instance field", VarHandleBaseTest$MethodHandleAccessTestCase@b21e871c): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Instance field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@357cc43c): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Static field", VarHandleBaseTest$MethodHandleAccessTestCase@3d8973c): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Static field unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@94d2106d): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Array", VarHandleBaseTest$MethodHandleAccessTestCase@f7928d5b): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Array unsupported", VarHandleBaseTest$MethodHandleAccessTestCase@a36904c8): success
[2020-11-18T04:35:45.271Z] test VarHandleTestMethodHandleAccessLong.testAccess("VarHandle -> MethodHandles.varHandleExactInvoker -> Array index out of bounds", VarHandleBaseTest$MethodHandleAccessTestCase@a7e6fa0b): success
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] ===============================================
[2020-11-18T04:35:45.271Z] java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java
[2020-11-18T04:35:45.271Z] Total tests run: 28, Failures: 0, Skips: 0
[2020-11-18T04:35:45.271Z] ===============================================
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] STDERR:
[2020-11-18T04:35:45.271Z] java.lang.BootstrapMethodError: java.lang.NullPointerException
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.newResourceBundle(ResourceBundle.java:3572)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.ResourceBundle$1.newResourceBundle(ResourceBundle.java:416)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.Bundles.findBundleOf(Bundles.java:209)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.Bundles.of(Bundles.java:106)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:185)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:182)
[2020-11-18T04:35:45.271Z] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.resources.LocaleData.getCalendarData(LocaleData.java:90)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.LocaleResources.getCalendarData(LocaleResources.java:138)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.cldr.CLDRCalendarDataProviderImpl.findValue(CLDRCalendarDataProviderImpl.java:91)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.cldr.CLDRCalendarDataProviderImpl.getFirstDayOfWeek(CLDRCalendarDataProviderImpl.java:59)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:248)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:233)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:262)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.CalendarDataUtility.retrieveFirstDayOfWeek(CalendarDataUtility.java:75)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.Calendar.setWeekCountData(Calendar.java:3414)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.Calendar.<init>(Calendar.java:1611)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.GregorianCalendar.<init>(GregorianCalendar.java:738)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.Calendar$Builder.build(Calendar.java:1493)
[2020-11-18T04:35:45.271Z] 	at java.base/sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:87)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.Calendar.createCalendar(Calendar.java:1696)
[2020-11-18T04:35:45.271Z] 	at java.base/java.util.Calendar.getInstance(Calendar.java:1660)
[2020-11-18T04:35:45.271Z] 	at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
[2020-11-18T04:35:45.271Z] 	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
[2020-11-18T04:35:45.271Z] 	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:599)
[2020-11-18T04:35:45.271Z] 	at org.testng.reporters.XMLReporter.addDurationAttributes(XMLReporter.java:180)
[2020-11-18T04:35:45.271Z] 	at org.testng.reporters.XMLReporter.getSuiteAttributes(XMLReporter.java:171)
[2020-11-18T04:35:45.271Z] 	at org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:114)
[2020-11-18T04:35:45.271Z] 	at org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:86)
[2020-11-18T04:35:45.271Z] 	at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:63)
[2020-11-18T04:35:45.271Z] 	at org.testng.TestNG.generateReports(TestNG.java:1076)
[2020-11-18T04:35:45.271Z] 	at org.testng.TestNG.run(TestNG.java:1035)
[2020-11-18T04:35:45.271Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2020-11-18T04:35:45.271Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2020-11-18T04:35:45.271Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-11-18T04:35:45.271Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-11-18T04:35:45.271Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-11-18T04:35:45.271Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.Thread.run(Thread.java:835)
[2020-11-18T04:35:45.271Z] Caused by: java.lang.NullPointerException
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:182)
[2020-11-18T04:35:45.271Z] 	at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
[2020-11-18T04:35:45.271Z] 	... 43 more
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] JavaTest Message: Test threw exception: java.lang.BootstrapMethodError: java.lang.NullPointerException
[2020-11-18T04:35:45.271Z] JavaTest Message: shutting down test
[2020-11-18T04:35:45.271Z] 
[2020-11-18T04:35:45.271Z] STATUS:Failed.`main' threw exception: java.lang.BootstrapMethodError: java.lang.NullPointerException
```

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse/openj9/issues/10929

**Comment by pshipton** [comment]
@dnakamura maybe there is a problem, since this failure is happening more frequently now.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/214

**Comment by pshipton** [comment]
We can run some non-cmake testing, in case there was something else delivered which is causing this.

**Comment by pshipton** [comment]
Didn't recreate with an uma build, trying 4 more runs across different machines.
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1196/

**Comment by pshipton** [comment]
All the grinders failed some native test (I assume a setup issue) which is unrelated, but the NPE in `java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccess<type>` didn't recreate. Given the NPE has occurred in the last two nightlies, it seems related to cmake. I started a 4x grinder on the cmake build for comparison.

https://ci.eclipse.org/openj9/view/Test/job/Grinder/1197/

**Comment by pshipton** [comment]
Only 1/4 occurrence of the NPE in `VarHandleTestMethodHandleAccess<type>`  in the cmake runs. https://ci.eclipse.org/openj9/job/Grinder_iteration_3/11/testReport/ (win2012-x86-1)

A timezone test failed, but I believe that's because jdk-11.0.10+3 promoted with newer test material over the cmake JVM I'm using.

0/4, 1/4 isn't conclusive, I'll run more grinders. 

12x with uma https://ci.eclipse.org/openj9/view/Test/job/Grinder/1198
12x with cmake https://ci.eclipse.org/openj9/view/Test/job/Grinder/1199

**Comment by pshipton** [comment]
All passed, perhaps just running jdk_lang_j9_0 isn't good enough.

**Comment by pshipton** [comment]
running all sanity.openjdk again.

12x with uma https://ci.eclipse.org/openj9/view/Test/job/Grinder/1200
12x with cmake https://ci.eclipse.org/openj9/view/Test/job/Grinder/1201

**Comment by pshipton** [comment]
Nothing in the build last night.

**Comment by pshipton** [comment]
I didn't find there is an obvious problem that can be attributed to cmake, closing this again.
