### ISSUE TITLE
OOM Java heap space JLM_Tests_interface_1 TestNG.generateReports

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11282]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_ppc64le_linux_xl_OpenJDK_testList_1/88/
JLM_Tests_interface_1
"java/lang/OutOfMemoryError" "Java heap space"
Diagnostics https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdknext_j9_sanity.functional_ppc64le_linux_xl_OpenJDK_testList_1/88/functional_test_output.tar.gz
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at org/testng/reporters/SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:51)
4XESTACKTRACE                at org/testng/TestNG.generateReports(TestNG.java:1097)
4XESTACKTRACE                at org/testng/TestNG.run(TestNG.java:1022)
4XESTACKTRACE                at org/testng/TestNG.privateMain(TestNG.java:1354)
4XESTACKTRACE                at org/testng/TestNG.main(TestNG.java:1323)
```
```
NULL           id                 start              end                size               space/region
1STHEAPSPACE   0x00003FFFA00AA650         --                 --                 --         Generational
1STHEAPREGION  0x00003FFFA00AB2C0 0x00003FFF21960000 0x00003FFF21F60000 0x0000000000600000 Generational/Tenured Region
1STHEAPREGION  0x00003FFFA00AACF0 0x00003FFF98F20000 0x00003FFF99170000 0x0000000000250000 Generational/Nursery Region
1STHEAPREGION  0x00003FFFA00AA720 0x00003FFF99170000 0x00003FFF99200000 0x0000000000090000 Generational/Nursery Region
NULL
1STHEAPTOTAL   Total memory:                     9306112 (0x00000000008E0000)
1STHEAPTARGET  Target memory:                    8389632 (0x0000000000800400)
1STHEAPINUSE   Total memory in use:              6972136 (0x00000000006A62E8)
1STHEAPFREE    Total memory free:                2333976 (0x0000000000239D18)
```
```
1STGCHTYPE     GC History
3STHSTTYPE     08:48:12:207092938 GMT j9mm.100 -   J9AllocateObject() returning NULL! 24 bytes requested for object of class 00003FFFA014B600 from memory space 'Generational' id=00003FFFA00AA650
3STHSTTYPE     08:48:12:207042939 GMT j9mm.134 -   Allocation failure end: newspace=2407704/3014656 oldspace=0/6291456 loa=0/0
3STHSTTYPE     08:48:12:207038939 GMT j9mm.470 -   Allocation failure cycle end: newspace=2407704/3014656 oldspace=0/6291456 loa=0/0
3STHSTTYPE     08:48:12:207012939 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=2407704/9306112
3STHSTTYPE     08:48:12:206991940 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     08:48:12:206964940 GMT j9mm.137 -   Compact end: bytesmoved=0
3STHSTTYPE     08:48:12:198536058 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     08:48:12:198534058 GMT j9mm.57 -   Sweep end
3STHSTTYPE     08:48:12:198159063 GMT j9mm.56 -   Sweep start
3STHSTTYPE     08:48:12:198157063 GMT j9mm.94 -   Class unloading end: classloadersunloaded=0 classesunloaded=0
3STHSTTYPE     08:48:12:198152063 GMT j9mm.60 -   Class unloading start
3STHSTTYPE     08:48:12:198151063 GMT j9mm.55 -   Mark end
3STHSTTYPE     08:48:12:193571128 GMT j9mm.54 -   Mark start
3STHSTTYPE     08:48:12:193536128 GMT j9mm.474 -   GlobalGC start: globalcount=20
3STHSTTYPE     08:48:12:193482129 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=2407704/9306112
3STHSTTYPE     08:48:12:193458129 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     08:48:12:193430129 GMT j9mm.137 -   Compact end: bytesmoved=5200
3STHSTTYPE     08:48:12:184033261 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     08:48:12:184031261 GMT j9mm.57 -   Sweep end
3STHSTTYPE     08:48:12:183634267 GMT j9mm.56 -   Sweep start
3STHSTTYPE     08:48:12:183630267 GMT j9mm.55 -   Mark end
3STHSTTYPE     08:48:12:177901347 GMT j9mm.54 -   Mark start
3STHSTTYPE     08:48:12:177825348 GMT j9mm.474 -   GlobalGC start: globalcount=19
3STHSTTYPE     08:48:12:177788348 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.061 meanexclusiveaccessms=0.061 threads=0 lastthreadtid=0x00003FFFA00D6588 beatenbyotherthread=0
3STHSTTYPE     08:48:12:177787348 GMT j9mm.469 -   Allocation failure cycle start: newspace=1792680/3014656 oldspace=0/6291456 loa=0/0 requestedbytes=24
3STHSTTYPE     08:48:12:177785349 GMT j9mm.133 -   Allocation failure start: newspace=1792680/3014656 oldspace=0/6291456 loa=0/0 requestedbytes=24
3STHSTTYPE     08:48:12:161891571 GMT j9mm.75 -   Concurrent collection end: newspace=2364128/3014656 oldspace=0/6291456 loa=0/0
3STHSTTYPE     08:48:12:161854572 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=2364128/9306112
3STHSTTYPE     08:48:12:161818572 GMT j9mm.90 -   GlobalGC collect complete
3STHSTTYPE     08:48:12:161776573 GMT j9mm.137 -   Compact end: bytesmoved=60024
3STHSTTYPE     08:48:12:151452717 GMT j9mm.136 -   Compact start: reason=compact to meet allocation
3STHSTTYPE     08:48:12:151449717 GMT j9mm.57 -   Sweep end
3STHSTTYPE     08:48:12:150986724 GMT j9mm.56 -   Sweep start
3STHSTTYPE     08:48:12:150984724 GMT j9mm.55 -   Mark end
3STHSTTYPE     08:48:12:149575743 GMT j9mm.54 -   Mark start
3STHSTTYPE     08:48:12:149547744 GMT j9mm.73 -   Concurrent collection card cleaning end
3STHSTTYPE     08:48:12:149387746 GMT j9mm.72 -   Concurrent collection card cleaning start, workstackoverflowcount=0
3STHSTTYPE     08:48:12:149386746 GMT j9mm.79 -   Concurrent remembered set scan end, rememberedsetobjectsfound=214 scantracecount=21304 overflowcount=0
3STHSTTYPE     08:48:12:149144749 GMT j9mm.78 -   Concurrent remembered set scan start, overflowcount=0
3STHSTTYPE     08:48:12:149116750 GMT j9mm.474 -   GlobalGC start: globalcount=18
3STHSTTYPE     08:48:12:149108750 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.047 meanexclusiveaccessms=0.047 threads=0 lastthreadtid=0x00003FFFA00D6588 beatenbyotherthread=0
3STHSTTYPE     08:48:12:149106750 GMT j9mm.132 -   Concurrent collection start: newspace=2241656/3014656 oldspace=0/6291456 loa=0/0 tracesizetarget=4314535 totaltraced=4666072 mutatorstraced=653320 conhelpertraced=4012752 concurrentcleanedcards=11 cardcleaningthreshold=233738 overflowoccurred=false overflowcount=0
3STHSTTYPE     08:48:12:148975752 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:148971752 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:148968752 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:148938752 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:148907753 GMT j9mm.134 -   Allocation failure end: newspace=2315384/3014656 oldspace=0/6291456 loa=0/0
3STHSTTYPE     08:48:12:148747755 GMT j9mm.470 -   Allocation failure cycle end: newspace=2315504/3014656 oldspace=0/6291456 loa=0/0
3STHSTTYPE     08:48:12:148732755 GMT j9mm.468 -   Cycle End: type 2 approximateFreeMemorySize 2315504
3STHSTTYPE     08:48:12:148704756 GMT j9mm.560 -   LocalGC end: rememberedsetoverflow=0 causedrememberedsetoverflow=0 scancacheoverflow=0 failedflipcount=0 failedflipbytes=0 failedtenurecount=117 failedtenurebytes=10288 flipcount=337 flipbytes=60792 newspace=2315504/3014656 oldspace=0/6291456 loa=0/0 tenureage=0
3STHSTTYPE     08:48:12:148620757 GMT j9mm.140 -   Tilt ratio: 78
3STHSTTYPE     08:48:12:147892767 GMT j9mm.64 -   LocalGC start: globalcount=18 scavengecount=33 weakrefs=0 soft=0 phantom=0 finalizers=0
3STHSTTYPE     08:48:12:147873767 GMT j9mm.467 -   Cycle Start: type 2 approximateFreeMemorySize 0
3STHSTTYPE     08:48:12:147821768 GMT j9mm.135 -   Exclusive access: exclusiveaccessms=0.053 meanexclusiveaccessms=0.053 threads=0 lastthreadtid=0x00003FFFA00D6588 beatenbyotherthread=0
3STHSTTYPE     08:48:12:147819768 GMT j9mm.469 -   Allocation failure cycle start: newspace=0/3014656 oldspace=0/6291456 loa=0/0 requestedbytes=120
3STHSTTYPE     08:48:12:147817768 GMT j9mm.133 -   Allocation failure start: newspace=0/3014656 oldspace=0/6291456 loa=0/0 requestedbytes=120
3STHSTTYPE     08:48:12:140498871 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:140496871 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:140343873 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:140335873 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:135246944 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:135244944 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:132918977 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:123565108 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:118680176 GMT j9mm.77 -   Concurrent background thread finished
3STHSTTYPE     08:48:12:106390348 GMT j9mm.76 -   Concurrent background thread activated
3STHSTTYPE     08:48:12:100463431 GMT j9mm.69 -   Concurrent kickoff, tracesizetarget=4314535 kickoffthreshold=593338 remainingfree=520520
3STHSTTYPE     08:48:12:047462173 GMT j9mm.75 -   Concurrent collection end: newspace=2174040/3014656 oldspace=0/6291456 loa=0/0
```

**Comment by pshipton** [comment]
@dmitripivkine I don't understand why this OOM occurred.

**Comment by dmitripivkine** [comment]
> @dmitripivkine I don't understand why this OOM occurred.

`-Xsoftmx` is set at ~8M:
```
0x5af0: U64 softMx = 0x0000000000800400 (8389632)

+----------------+----------------+----------------+----------------+--------+----------------+----------------------
|    region      |     start      |      end       |    subspace    | flags  |      size      |      region type
+----------------+----------------+----------------+----------------+--------+----------------+----------------------
 00003fffa00ab2c0 00003fff21960000 00003fff21f60000 00003fffa0098890 00000009           600000 ADDRESS_ORDERED
 00003fffa00aacf0 00003fff98f20000 00003fff99170000 00003fffa00a4930 0000000a           250000 ADDRESS_ORDERED
 00003fffa00aa720 00003fff99170000 00003fff99200000 00003fffa009ee70 0000000a            90000 ADDRESS_ORDERED
+----------------+----------------+----------------+----------------+--------+----------------+----------------------
```
So even reserved heap size is ~2G heap can not be expanded:
```
08:48:12.206588045  0x3FFFA00D5B00 j9mm.12              Exit       <MM_MemorySubSpace_calculateExpandSize Exit1 Desired free bytes = 1950720, current free bytes = 0, returning expand size of 0 bytes
```

**Comment by dmitripivkine** [comment]
The OOM is thrown at the very end of `JLM_Tests_interface_1` testing while summary report is preparing. My guess one of the tests in the bundle set `-Xsoftmx` but never recover after

**Comment by pshipton** [comment]
Ok. I've never seen this one before. Will monitor to see if it occurs again. Unless it's related to some recent change, it may just be some highly intermittent problem with the test.

**Comment by dmitripivkine** [comment]
There are not so many tests in this `JLM_Tests_interface_1` bundle. This tests can be inspected. I think if one of tests left bogus -Xsoftmx value it should be fixed by restoring maximum heap size at the exit

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/pull/11294
