### ISSUE TITLE
JIT assertion in SR6_FP11

### ISSUE THREAD

**Issue by dusanboskovic** [eclipse/openj9#11327]
Assertion is raised when trying to create a test patch for an older build - SR6_FP11

Assertion first noticed in the "Build git tests Java8" job when running javac. This was the message:
```
    [javac] Assertion failed at /tmp/bld_460907/bld_linux_x86-64_cmprssptrs/compiler/../omr/compiler/x/codegen/OutlinedInstructions.cpp:395: _hasEnded
    [javac] VMState: 0x0005ff04
    [javac] 	TR_OutlinedInstructionsGenerator object has gone out of scope before call to endOutlinedInstructionSequence().
```
Snaptrace was empty, assuming that this crash occurs before the VM is able to startup

Native stack:
```
#9  <signal handler called>
#10 0x00007f48c958f387 in raise () from /lib64/libc.so.6
#11 0x00007f48c9590a78 in abort () from /lib64/libc.so.6
#12 0x00007f48c22c7d26 in TR::trap() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#13 0x00007f48c22c7de2 in TR::fatal_assertion(char const*, int, char const*, char const*, ...) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#14 0x00007f48c2680234 in TR_OutlinedInstructionsGenerator::~TR_OutlinedInstructionsGenerator() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#15 0x00007f48c20f2acc in J9::X86::AMD64::JNILinkage::releaseVMAccessAtomicFree(TR::Node*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#16 0x00007f48c20f394b in J9::X86::AMD64::JNILinkage::buildDirectJNIDispatch(TR::Node*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#17 0x00007f48c266a7eb in OMR::X86::TreeEvaluator::performCall(TR::Node*, bool, bool, TR::CodeGenerator*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#18 0x00007f48c266a9e2 in OMR::X86::TreeEvaluator::directCallEvaluator(TR::Node*, TR::CodeGenerator*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#19 0x00007f48c20d6cd3 in J9::X86::TreeEvaluator::directCallEvaluator(TR::Node*, TR::CodeGenerator*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#20 0x00007f48c224815b in OMR::CodeGenerator::evaluate(TR::Node*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#21 0x00007f48c266af9c in OMR::X86::TreeEvaluator::treetopEvaluator(TR::Node*, TR::CodeGenerator*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#22 0x00007f48c224815b in OMR::CodeGenerator::evaluate(TR::Node*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#23 0x00007f48c1f53e7e in J9::CodeGenerator::doInstructionSelection() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#24 0x00007f48c2255f86 in OMR::CodeGenPhase::performInstructionSelectionPhase(TR::CodeGenerator*, TR::CodeGenPhase*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#25 0x00007f48c2254882 in OMR::CodeGenPhase::performAll() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#26 0x00007f48c2251ec3 in OMR::CodeGenerator::generateCode() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#27 0x00007f48c2267721 in OMR::Compilation::compile() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#28 0x00007f48c1f8c458 in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR::Compilation*, TR_ResolvedMethod*, TR_J9VMBase&, TR_OptimizationPlan*, TR::SegmentAllocator const&) ()
   from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#29 0x00007f48c1f8d1a6 in TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#30 0x00007f48c35fd903 in omrsig_protect () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9prt29.so
#31 0x00007f48c1f8ec85 in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR_MethodToBeCompiled*, J9::J9SegmentProvider&) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#32 0x00007f48c1f8f23f in TR::CompilationInfoPerThread::processEntry(TR_MethodToBeCompiled&, J9::J9SegmentProvider&) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#33 0x00007f48c1f8b18b in TR::CompilationInfoPerThread::processEntries() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#34 0x00007f48c1f8b4aa in TR::CompilationInfoPerThread::run() () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#35 0x00007f48c1f8b56a in protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#36 0x00007f48c35fd903 in omrsig_protect () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9prt29.so
#37 0x00007f48c1f8b9c4 in compilationThreadProc(void*) () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9jit29.so
#38 0x00007f48c3a6c326 in thread_wrapper () from /bluebird/builds/bld_460907/sdk/xa6480/jre/lib/amd64/compressedrefs/libj9thr29.so
#39 0x00007f48c9d54ea5 in start_thread () from /lib64/libpthread.so.0
#40 0x00007f48c965796d in clone () from /lib64/libc.so.6
``` 

Data located on the internal build system: `/bluebird/builds/bld_460907/sdk`

**Comment by dusanboskovic** [comment]
@0xdaryl 
Opened issue as you suggested. Is this the right place?
