### ISSUE TITLE
Cannot deploy artifacts from xlinux, the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11332]
Some examples

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/560
```
01:20:49  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/560/SHA.txt
01:20:49  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/560/SHA.txt;build.parentNumber=2519;build.parentName=Pipeline_Build_Test_JDK8_x86-64_linux;build.timestamp=1606880521268;build.name=Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly;build.number=560 HTTP/1.1: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
01:20:49  [consumer_0] An exception occurred during execution:
01:20:49  java.lang.RuntimeException: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
01:20:49  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
01:20:49  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
01:20:49  	at java.lang.Thread.run(Thread.java:748)
01:20:49  Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_OMR/789
```
05:53:12  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_OMR/789/OpenJ9-JDK11-x86-64_linux_xl-20201202-051138.tar.gz
05:53:12  [consumer_0] An exception occurred during execution:
05:53:12  java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
```

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_OMR/778
```
05:55:27  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_OMR/778/OpenJ9-JDK11-x86-64_linux-20201202-051317.tar.gz
05:55:27  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
05:55:27  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_OMR/778/OpenJ9-JDK11-x86-64_linux-20201202-051317.tar.gz;build.parentNumber=2618;build.parentName=Pipeline_Build_Test_JDK11_x86-64_linux;build.buildIdentifier=OMR-Acceptance;build.timestamp=1606903837113;build.name=Build_JDK11_x86-64_linux_OMR;build.number=778 HTTP/1.1: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
05:55:27  [consumer_0] An exception occurred during execution:
05:55:27  java.lang.RuntimeException: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
05:55:27  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
05:55:27  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
05:55:27  	at java.lang.Thread.run(Thread.java:748)
05:55:27  Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

All xlinux builds in OMR acceptance
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/2160/

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau this is blocking OMR acceptance, and I expect any future builds on xlinux, unless it's some temporary problem.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/559
```
01:03:57  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/559/SHA.txt
01:04:03  [consumer_0] An exception occurred during execution:
01:04:03  java.lang.InternalError: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-0.el6_10.x86_64/jre/lib/jce.jar
```

**Comment by AdamBrousseau** [comment]
Related #10009
I assume the xlinux deault java8 got updated again. I thought we had forced this to be a static version of openj9. I will look into it.

**Comment by AdamBrousseau** [comment]
cent6-x64-3]#  /var/log/yum.log
```
Dec 02 01:04:17 Updated: 1:java-1.8.0-openjdk-headless-1.8.0.275.b01-0.el6_10.x86_64
Dec 02 01:04:18 Updated: 1:java-1.8.0-openjdk-1.8.0.275.b01-0.el6_10.x86_64
Dec 02 01:04:22 Updated: 1:java-1.8.0-openjdk-devel-1.8.0.275.b01-0.el6_10.x86_64
```
I will look into setting OpenJ9 as default so we don't get bit again.

**Comment by AdamBrousseau** [comment]
Install OpenJ9 0.23 as default java/javac
```
cd /tmp
wget https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01_openj9-0.23.0/OpenJDK8U-jdk_x64_linux_openj9_8u275b01_openj9-0.23.0.tar.gz
tar zxf OpenJDK8U-jdk_x64_linux_openj9_8u275b01_openj9-0.23.0.tar.gz
rm -f OpenJDK8U-jdk_x64_linux_openj9_8u275b01_openj9-0.23.0.tar.gz
mv jdk8u275-b01 /usr/lib/jvm/
update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk8u275-b01/bin/java 4
update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk8u275-b01/bin/javac 4
update-alternatives --config java
update-alternatives --config javac
```

Add cert to keystore. Adjust instructions from readme for new sdk
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/ARTIFACTORY.md#configure-unb-nodes-to-accept-self-signed-certificate-upload-only
```
openssl s_client -connect 192.168.10.216:443 -servername ub18p8art.casa.cs.unb.ca:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > public.crt
/usr/lib/jvm/jdk8u275-b01/bin/keytool -import -alias ub18p8art.casa.cs.unb.ca -keystore /usr/lib/jvm/jdk8u275-b01/jre/lib/security/cacerts -file public.crt
```

Completed on cent6 1-7. This should now be resolved.
