### ISSUE TITLE
--show-module-resolution: Unable to extend shared class path to index 0

### ISSUE THREAD

**Issue by Thihup** [eclipse/openj9#11342]
Java -version output
--------------------
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

Summary of problem
------------------
Using the flag `--show-module-resolution` starting Tomcat 9.0.40 it throws ISE and the JVM ends.

Steps to reproduce:
--------------
1. Download Tomcat: https://downloads.apache.org/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.zip
2. Extract it
3. `cd apache-tomcat-9.0.40/bin`
4. `JDK_JAVA_OPTIONS="--show-module-resolution -Xshareclasses" ./catalina.sh run`
```
Error: A JNI error has occurred, please check your installation and try again
Exceção no encadeamento "main"java.lang.IllegalStateException: Unable to extend shared class path to index 0
        at java.base/jdk.internal.loader.URLClassPath.updateClasspathWithSharedClassesHelper(URLClassPath.java:267)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:422)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:921)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:832)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:790)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1108)
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:419)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)
```

Aditional information
-----
I've detected that the problem may be related to internationalization. By default, my environment variable LANG is set to "pt_BR.UTF-8." Setting it to "c" or "en" the exception doesn't happen. However, it happens with it set to "C" or "en_US.UTF-8"
Running without the "-Xshareclasses" the exception doesn't happen too.

**Comment by Thihup** [comment]
Looks like my shared classes cache is almost full. It may influence the --show-module-resolution.
```
Current statistics for cache "sharedcc_thiago": 

Cache created with:
        -Xnolinenumbers                      = false
        BCI Enabled                          = true
        Restrict Classpaths                  = false
        Feature                              = cr
        Processor Features                   = fpu cx8 cmov mmx sse
                                               sse2 ssse3 fma sse4_1
                                               popcnt aesni osxsave
                                               avx

Cache contains only classes with line numbers

base address                         = 0x00007FE511459000
end address                          = 0x00007FE524000000
allocation pointer                   = 0x00007FE514487140

cache layer                          = 0
cache size                           = 314572192
softmx bytes                         = 67108864
free bytes                           = 1552
Reserved space for AOT bytes         = -1
Maximum space for AOT bytes          = -1
Reserved space for JIT data bytes    = -1
Maximum space for JIT data bytes     = -1
Metadata bytes                       = 2522172
Metadata % used                      = 3%
Class debug area size                = 25133056
Class debug area used bytes          = 8414316
Class debug area % used              = 33%

ROMClass bytes                       = 50520384
AOT bytes                            = 5241504
JIT data bytes                       = 43312
Zip cache bytes                      = 0
Startup hint bytes                   = 1080
Data bytes                           = 363936

# ROMClasses                         = 19853
# AOT Methods                        = 2553
# Classpaths                         = 18
# URLs                               = 2053
# Tokens                             = 0
# Zip caches                         = 0
# Startup hints                      = 9
# Stale classes                      = 0
% Stale classes                      = 0%


Cache is 99% soft full

Cache is accessible to current user = true
```

**Comment by Thihup** [comment]
It happens with Open Liberty too.

`$ JDK_JAVA_OPTIONS="--show-module-resolution" ./server run`
```
Exceção no encadeamento "main"java.lang.IllegalStateException: Unable to extend shared class path to index 2
        at java.base/jdk.internal.loader.URLClassPath.updateClasspathWithSharedClassesHelper(URLClassPath.java:267)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:422)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:473)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:921)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:832)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:790)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1108)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

Fatal error: processing of -javaagent failed, processJavaStart failed
```

**Comment by hangshao0** [comment]
So the issue goes away if you remove `--show-module-resolution` ?

**Comment by Thihup** [comment]
Yes, without the --show-module-resolution it works

**Comment by hangshao0** [comment]
I have re-produced this issue. It happens on Java 11 as well.

**Comment by hangshao0** [comment]
What happens here is that `loaderURLs` is not updated because the `usingSharedClasses()` returns false here:

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L572to#L575

`usingSharedClasses()` should return `true`. However, when reaching the above code, it is too early that the SCC support for `builtinClassLoaders` are not initialized yet.

**Comment by hangshao0** [comment]
Pull Request: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/369
