### ISSUE TITLE
JDK16 : SecurityTests StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11361]
Failure link
------------

From an internal build `Test_openjdkNext_j9_extended.functional_s390x_linux_Nightly/323`:
```
21:52:21  openjdk version "16-internal" 2021-03-16
21:52:21  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:52:21  Eclipse OpenJ9 VM (build master-9f11871a18a, JRE 16 Linux s390x-64-Bit Compressed References 20201202_402 (JIT enabled, AOT enabled)
21:52:21  OpenJ9   - 9f11871a18a
21:52:21  OMR      - a58cd2f5687
21:52:21  JCL      - f7021059fd3 based on jdk-16+26)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
00:16:31  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux&TARGET=SecurityTests_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
FAILED: testTls13
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.String.substring(String.java:2722)
	at net.adoptopenjdk.test.Tls13FunctionalTest.isSupportedPlatform(Tls13FunctionalTest.java:133)
	at net.adoptopenjdk.test.Tls13FunctionalTest.testTls13(Tls13FunctionalTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    SecurityTests
    Tests run: 2, Failures: 1, Skips: 0
===============================================

SecurityTests_0_FAILED
```

Occurred at `Test_openjdkNext_j9_extended.functional_x86-64_linux_Nightly/362` as well.

**Comment by pshipton** [comment]
Looks like a test problem parsing the java.version `16-internal`. I assume it fails across all platforms? I'll fix the parsing code.
