### ISSUE TITLE
JDK16 GCMBufferTest Exception: Wrong update return len (BYTE):  rlen=0, expected output len=16

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11391]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly/325`:
```
21:55:49  openjdk version "16-internal" 2021-03-16
21:55:49  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:55:49  Eclipse OpenJ9 VM (build master-c757b511544, JRE 16 Linux s390x-64-Bit Compressed References 20201206_405 (JIT enabled, AOT enabled)
21:55:49  OpenJ9   - c757b511544
21:55:49  OMR      - c3c479f9d59
21:55:49  JCL      - ac04db2e394 based on jdk-16+27)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
22:52:08  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=s390x_linux&TARGET=jdk11_tier1_cipher_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:50:19  --------------------------------------------------
22:50:22  TEST: com/sun/crypto/provider/Cipher/AEAD/GCMBufferTest.java

22:50:22  STDERR:
22:50:22  java.lang.Exception: Wrong update return len (BYTE):  rlen=0, expected output len=16
22:50:22  	at GCMBufferTest.crypto(GCMBufferTest.java:423)
22:50:22  	at GCMBufferTest.encrypt(GCMBufferTest.java:303)
22:50:22  	at GCMBufferTest.test(GCMBufferTest.java:281)
22:50:22  	at GCMBufferTest.main(GCMBufferTest.java:631)
22:50:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:50:22  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
22:50:22  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:50:22  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
22:50:22  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
22:50:22  	at java.base/java.lang.Thread.run(Thread.java:853)
22:50:22  
22:50:22  JavaTest Message: Test threw exception: java.lang.Exception
22:50:22  JavaTest Message: shutting down test
22:50:22  
22:50:22  
22:50:22  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Wrong update return len (BYTE): rlen=0, expected output len=16
```

**Comment by pshipton** [comment]
@JasonFengJ9
- is this an intermittent failure?
- does/did it fail only on zlinux or across platforms?

**Comment by JasonFengJ9** [comment]
>does/did it fail only on zlinux or across platforms?

This is also seen across platforms: `AIX`, `x86-64 Linux`, `mac` & `Windows`.

> is this an intermittent failure?

The failure occurred in last two nightly builds, it doesn't seem intermittent. 

It appears a regression between following two builds:
Good build:
```
21:51:12  openjdk version "16-internal" 2021-03-16
21:51:12  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:51:12  Eclipse OpenJ9 VM (build master-9f11871a18a, JRE 16 Linux s390x-64-Bit Compressed References 20201202_402 (JIT enabled, AOT enabled)
21:51:12  OpenJ9   - 9f11871a18a
21:51:12  OMR      - a58cd2f5687
21:51:12  JCL      - f7021059fd3 based on jdk-16+26)
```

Bad build:
```
21:54:32  openjdk version "16-internal" 2021-03-16
21:54:32  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:54:32  Eclipse OpenJ9 VM (build master-c757b511544, JRE 16 Linux s390x-64-Bit Compressed References 20201205_404 (JIT enabled, AOT enabled)
21:54:32  OpenJ9   - c757b511544
21:54:32  OMR      - c3c479f9d59
21:54:32  JCL      - a40d4ba969a based on jdk-16+27)
```

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/11390#issuecomment-740330784

**Comment by pshipton** [comment]
Closing this as a dup of https://github.com/eclipse/openj9/issues/11390, this is being resolved via https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/266, which will have to be backported to jdk16 once the review completes.
