### ISSUE TITLE
PlatformLoggerTest.java Logger test.platformlogger.goo does not exist

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11401]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_xl_Nightly/1
jdk_util_j9_0
sun/util/logging/PlatformLoggerTest.java
```
23:25:20  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Logger test.platformlogger.goo does not exist
23:25:20  REASON: User specified action: run main/othervm PlatformLoggerTest 
23:25:20  TIME:   0.957 seconds
23:25:20  messages:
23:25:20  command: main PlatformLoggerTest
23:25:20  reason: User specified action: run main/othervm PlatformLoggerTest 
23:25:20  Mode: othervm [/othervm specified]
23:25:20  elapsed time (seconds): 0.957
23:25:20  configuration:
23:25:20  STDOUT:
23:25:20  STDERR:
23:25:20  Dec 07, 2020 11:25:08 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) 1 string
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) {x=0, y=0}
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  WARNING: Test warning(String, Throwable)
23:25:20  java.lang.Throwable: Testing
23:25:20  	at PlatformLoggerTest.testLogMethods(PlatformLoggerTest.java:135)
23:25:20  	at PlatformLoggerTest.main(PlatformLoggerTest.java:51)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:20  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:20  	at java.lang.reflect.Method.invoke(Method.java:498)
23:25:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:25:20  	at java.lang.Thread.run(Thread.java:823)
23:25:20  
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  INFO: Test info(String)
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest checkPlatformLogger
23:25:20  INFO: OK: Testing log message
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest checkPlatformLogger
23:25:20  INFO: OK: Testing log message
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) 1 string
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) {x=0, y=0}
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  WARNING: Test warning(String, Throwable)
23:25:20  java.lang.Throwable: Testing
23:25:20  	at PlatformLoggerTest.testLogMethods(PlatformLoggerTest.java:135)
23:25:20  	at PlatformLoggerTest.main(PlatformLoggerTest.java:66)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:20  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:20  	at java.lang.reflect.Method.invoke(Method.java:498)
23:25:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:25:20  	at java.lang.Thread.run(Thread.java:823)
23:25:20  
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  INFO: Test info(String)
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) 1 string
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  SEVERE: Test severe(String, Object...) {x=0, y=0}
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  WARNING: Test warning(String, Throwable)
23:25:20  java.lang.Throwable: Testing
23:25:20  	at PlatformLoggerTest.testLogMethods(PlatformLoggerTest.java:135)
23:25:20  	at PlatformLoggerTest.main(PlatformLoggerTest.java:67)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:20  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:20  	at java.lang.reflect.Method.invoke(Method.java:498)
23:25:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:25:20  	at java.lang.Thread.run(Thread.java:823)
23:25:20  
23:25:20  Dec 07, 2020 11:25:09 PM PlatformLoggerTest testLogMethods
23:25:20  INFO: Test info(String)
23:25:20  java.lang.RuntimeException: Logger test.platformlogger.goo does not exist
23:25:20  	at PlatformLoggerTest.checkLogger(PlatformLoggerTest.java:121)
23:25:20  	at PlatformLoggerTest.main(PlatformLoggerTest.java:72)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:20  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:20  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:20  	at java.lang.reflect.Method.invoke(Method.java:498)
23:25:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:25:20  	at java.lang.Thread.run(Thread.java:823)
23:25:20  
23:25:20  JavaTest Message: Test threw exception: java.lang.RuntimeException: Logger test.platformlogger.goo does not exist
23:25:20  JavaTest Message: shutting down test
23:25:20  
23:25:20  STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Logger test.platformlogger.goo does not exist
```

**Comment by pshipton** [comment]
Try 5x x 4 grinder https://ci.eclipse.org/openj9/job/Grinder/1263/

**Comment by pshipton** [comment]
Also fails with -Xint https://ci.eclipse.org/openj9/job/Grinder/1270

**Comment by pshipton** [comment]
The test doesn't keep a strong reference to the loggers. The test is excluded on win, linux, mac, but not AIX, I guess because by fluke it doesn't fail on AIX compressed refs (failure is dependent on when the GC runs and collects the loggers). Opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/2106 to exclude the test on AIX as well since AIX XL builds are running, and the test fails intermittently in this build.
