### ISSUE TITLE
jdk16 jdmpview doesn't work with JEP 396 (--illegal-access=deny)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11445]
See https://github.com/eclipse/openj9/issues/11419#issuecomment-742937439
jdmpview doesn't start with the new jdk16 default `--illegal-access=deny`
```
21:23:15   [ERR] Exception in thread "main" java.lang.IllegalAccessError: com/ibm/dtfj/utils/ManagedImage is not visible
21:23:15   [ERR] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:491)
21:23:15   [ERR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:452)
21:23:15   [ERR] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
21:23:15   [ERR] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:650)
21:23:15   [ERR] 	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1047)
21:23:15   [ERR] 	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1032)
21:23:15   [ERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
21:23:15   [ERR] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:565)
21:23:15   [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1210)
21:23:15   [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1125)
21:23:15   [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1108)
21:23:15   [ERR] 	at com.ibm.j9ddr.view.dtfj.image.J9DDRImageFactory.getImage(J9DDRImageFactory.java:132)
21:23:15   [ERR] 	at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.foundImage(ImageFactory.java:403)
21:23:15   [ERR] 	at openj9.dtfj/com.ibm.dtfj.image.j9.ImageFactory.getImage(ImageFactory.java:233)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.commands.OpenCommand.imagesFromCommandLine(OpenCommand.java:115)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.commands.OpenCommand.run(OpenCommand.java:83)
21:23:15   [ERR] 	at openj9.dtfj/com.ibm.java.diagnostics.utils.Context.tryCommand(Context.java:141)
21:23:15   [ERR] 	at openj9.dtfj/com.ibm.java.diagnostics.utils.Context.execute(Context.java:97)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:173)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:157)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.imageFromCommandLine(Session.java:610)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.sessionInit(Session.java:226)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.<init>(Session.java:175)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.getInstance(Session.java:171)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:51)
21:23:15   [ERR] 	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
```

**Comment by pshipton** [comment]
I'll test https://github.com/pshipton/openj9/commit/d90d3ded tomorrow, and see if it's sufficient to fix the problem.

**Comment by pshipton** [comment]
It doesn't work to export `com.ibm.dtfj.utils` to openj9.dtfjview. The following is on the stack and comes from lib/ddr/j9ddr.jar,  which is loaded as part of the unnamed module.
`com.ibm.j9ddr.view.dtfj.image.J9DDRImageFactory.getImage(J9DDRImageFactory.java:132)`
Exporting `com.ibm.dtfj.utils` publicly works. Not the best solution, but a quick solution for this problem until we can create a better one. The better solution is to make j9ddr.jar a modularized jar and load it as a module.

**Comment by pshipton** [comment]
Actually, exporting `com.ibm.dtfj.utils` doesn't work in the build, as it results in the following error. I'll try a different approach and add the export to `jdmpview` at runtime.
```
11:58:43  /home/jenkins/workspace/Build_JDK15_s390x_linux_Personal/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImage.java:362: error: getImageSource() in J9DDRImage cannot implement getImageSource() in ManagedImage
11:58:43  	public ManagedImageSource getImageSource() {
11:58:43  	                          ^
11:58:43    return type com.ibm.dtfj.utils.file.ManagedImageSource is not compatible with com.ibm.dtfj.utils.file.ManagedImageSource
```

**Comment by pshipton** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/257 as a temporary (or permanent) workaround.

**Comment by pshipton** [comment]
No longer a blocker since https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/257 works around the problem.

**Comment by pshipton** [comment]
Actually to avoid confusion I've created a new issue https://github.com/eclipse/openj9/issues/11464 and closing this one.
