### ISSUE TITLE
git, mv: cannot move XX to YY : Directory not empty

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11453]
Cleaning problem?

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR/336
```
06:24:47  git clone --depth 1 -b master https://github.com/eclipse/openj9.git
06:25:43  update to openj9 sha: 88959036c015a9140edbf7cc1142b63023c24ac2
06:25:43  git fetch -q --unshallow
06:28:10  Note: checking out '88959036c015a9140edbf7cc1142b63023c24ac2'.
06:28:10  
06:28:10  You are in 'detached HEAD' state. You can look around, make experimental
06:28:10  changes and commit them, and you can discard any commits you make in this
06:28:10  state without impacting any branches by performing another checkout.
06:28:10  
06:28:10  If you want to create a new branch to retain commits you create, you may
06:28:10  do so (now or later) by using -b with the checkout command again. Example:
06:28:10  
06:28:10    git checkout -b <new-branch-name>
06:28:10  
06:28:10  HEAD is now at 88959036c Merge pull request #11436 from babsingh/remove_deadcode
06:28:10  mv: cannot move 'openj9/test/functional/CacheManagement' to 'functional/CacheManagement': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/cmdline_options_tester' to 'functional/cmdline_options_tester': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/cmdline_options_testresources' to 'functional/cmdline_options_testresources': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/cmdLineTests' to 'functional/cmdLineTests': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/DDR_Test' to 'functional/DDR_Test': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/IllegalAccessError_for_protected_method' to 'functional/IllegalAccessError_for_protected_method': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/InstrumentationAgent' to 'functional/InstrumentationAgent': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/J9 Exclude File Support' to 'functional/J9 Exclude File Support': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java10andUp' to 'functional/Java10andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java11andUp' to 'functional/Java11andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java12andUp' to 'functional/Java12andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java14andUp' to 'functional/Java14andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java15andUp' to 'functional/Java15andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java8andUp' to 'functional/Java8andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Java9andUp' to 'functional/Java9andUp': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/JavaAgentTest' to 'functional/JavaAgentTest': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/JIT_Test' to 'functional/JIT_Test': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/JLM_Tests' to 'functional/JLM_Tests': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Jsr292' to 'functional/Jsr292': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Jsr335' to 'functional/Jsr335': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Jsr335_interfaceStaticMethod' to 'functional/Jsr335_interfaceStaticMethod': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/NativeTest' to 'functional/NativeTest': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/OpenJ9_Jsr_292_API' to 'functional/OpenJ9_Jsr_292_API': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Panama' to 'functional/Panama': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/SharedCPEntryInvokerTests' to 'functional/SharedCPEntryInvokerTests': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/TestExample' to 'functional/TestExample': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/TestUtilities' to 'functional/TestUtilities': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/UnsafeTest' to 'functional/UnsafeTest': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/Valhalla' to 'functional/Valhalla': Directory not empty
06:28:10  mv: cannot move 'openj9/test/functional/VM_Test' to 'functional/VM_Test': Directory not empty
```

**Comment by AdamBrousseau** [comment]
Looks like the [previous build](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR/335/console) failed because the machine went offline. This probably left the workspace in a bad state. I wonder if we should add a cleanWs at the start of the test build (cc @llxia).

335 failure
```
00:06:05.572  Processing DSL script openjdk-tests/buildenv/jenkins/testJobTemplate
00:06:05.644  Processing DSL script openjdk-tests/buildenv/jenkins/testJobTemplate
00:38:22.384  LEVELS: [sanity]
00:38:22.384  JDK_VERSIONS: [8]
00:38:22.384  GROUPS: [functional]
00:38:22.384  ARCH_OS_LIST: [ppc64le_linux_xl]
00:38:22.386  LEVELS: [sanity]
00:38:22.387  JDK_VERSIONS: [8]
00:38:22.387  GROUPS: [functional]
00:38:22.387  ARCH_OS_LIST: [ppc64le_linux_xl]
00:38:22.406  Warning: (testJobTemplate, line 240) triggers is deprecated
00:38:22.408  Warning: (testJobTemplate, line 240) triggers is deprecated
00:38:22.727  Existing items:
00:38:22.727      GeneratedJob{name='Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR_testList_1'}
00:38:22.727  Unreferenced items:
00:38:22.727      GeneratedJob{name='Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR_testList_0'}
00:38:22.747  Existing items:
00:38:22.748      GeneratedJob{name='Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR_testList_0'}
00:38:22.748      GeneratedJob{name='Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OMR_testList_1'}
[Pipeline] }
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
ub18-ppcle-2 was marked offline: Connection was broken: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)

[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Also:   hudson.remoting.ProxyException: hudson.model.Computer$TerminationRequest: Termination requested at Thu Dec 10 18:03:16 EST 2020 by Thread[Ping thread for channel hudson.remoting.Channel@5c60f98c:ub18-ppcle-2,5,main] [id=915]
		at hudson.model.Computer.recordTermination(Computer.java:227)
		at hudson.model.Computer.disconnect(Computer.java:491)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:753)
		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:198)
		at hudson.remoting.PingThread.ping(PingThread.java:133)
		at hudson.remoting.PingThread.run(PingThread.java:89)
hudson.remoting.ProxyException: java.io.IOException: Unable to create live FilePath for ub18-ppcle-2
	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:64)
	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:47)
	at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:94)
	at org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:139)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariable(CpsThread.java:135)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:297)
	at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:75)
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:264)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:296)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Unable to create live FilePath for ub18-ppcle-2
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.replay(CpsStepContext.java:496)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:350)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeDescribable(DSL.java:498)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: hudson.remoting.ProxyException: java.lang.IllegalArgumentException: Failed to prepare cleanWs step
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeDescribable(DSL.java:500)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor564.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at Script1.testBuild(Script1.groovy:688)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor555.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```
