### ISSUE TITLE
OpenJDK 15 only, display java.lang.ClassNotFoundException: com.sun.glass.ui.Pixels

### ISSUE THREAD

**Issue by tretonis** [eclipse/openj9#11490]
Why OpenJ9 is showing this error, when I put the JVM Hotspot runs normal.
Details : Jdk 14 OpenJ9  work's and Jdk 15 HotSpot work normal and this error only display in Jdk 15 Open-J9.

Java Version :
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

Platform
 Ubuntu 20.04 LTS  
 kernel = 5.4.0-58-generic
 Linux amd64-64-Bit

Exception :
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com.sun.glass.ui.Pixels
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com.sun.glass.ui.Pixels
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1787)
	at java.base/java.lang.System.load(System.java:581)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:386)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:128)
	at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:187)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication$$Lambda$106/0x000000002c30c448.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.Pixels
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)

**Comment by pshipton** [comment]
I'm wondering if this is related to NativeLibraries.load(). Some problems with this have already been fixed since the 0.23.0 release. On Slack I suggested trying the Milestone 1 build for the next OpenJ9 release (0.24), where the problems are resolved.
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15.0.1+9_openj9-0.24.0-m1

**Comment by tretonis** [comment]
Yes, Open-J9 (0.24) this correct.
Thank's
