### ISSUE TITLE
OpenJDK java/util/Collections/EmptyCollectionSerialization.java .ClassNotFoundException: java.util.Collections$EmptyList

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11516]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/241/
java/util/Collections/EmptyCollectionSerialization.java
win2012-x86-4
```
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptySet()", EmptyCollectionSerialization$$Lambda$110/0x0000000000000000@ed122d6b): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_SET", EmptyCollectionSerialization$$Lambda$107/0x0000000000000000@3869e311): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_LIST", EmptyCollectionSerialization$$Lambda$105/0x0000000000000000@3dd86df0): failure
23:25:25  java.lang.AssertionError: Collections.EMPTY_LIST: Unexpected Exception
23:25:25  	at org.testng.Assert.fail(Assert.java:83)
23:25:25  	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:74)
23:25:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:25  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:25:25  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
23:25:25  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
23:25:25  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
23:25:25  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
23:25:25  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
23:25:25  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:25:25  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
23:25:25  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23:25:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
23:25:25  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
23:25:25  	at java.base/java.lang.Thread.run(Thread.java:836)
23:25:25  Caused by: java.lang.ClassNotFoundException: java.util.Collections$EmptyList
23:25:25  	at java.base/java.lang.Class.forNameImpl(Native Method)
23:25:25  	at java.base/java.lang.Class.forName(Class.java:426)
23:25:25  	at java.base/java.io.ClassCache$FutureValue.get(ClassCache.java:190)
23:25:25  	at java.base/java.io.ClassCache.get(ClassCache.java:161)
23:25:25  	at java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:877)
23:25:25  	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2117)
23:25:25  	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1984)
23:25:25  	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2291)
23:25:25  	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1801)
23:25:25  	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:577)
23:25:25  	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:487)
23:25:25  	at EmptyCollectionSerialization.patheticDeepCopy(EmptyCollectionSerialization.java:60)
23:25:25  	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:68)
23:25:25  	... 15 more
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_MAP", EmptyCollectionSerialization$$Lambda$106/0x0000000000000000@f40e47e6): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptyMap()", EmptyCollectionSerialization$$Lambda$109/0x0000000000000000@8730e7f0): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptySortedMap()", EmptyCollectionSerialization$$Lambda$112/0x0000000000000000@eaef5689): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptyNavigableMap()", EmptyCollectionSerialization$$Lambda$114/0x0000000000000000@797fdeec): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptySortedSet()", EmptyCollectionSerialization$$Lambda$111/0x0000000000000000@37bf3d43): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptyList()", EmptyCollectionSerialization$$Lambda$108/0x0000000000000000@e756a01e): success
23:25:25  test EmptyCollectionSerialization.serializableSingletons("Collections.emptyNavigableSet()", EmptyCollectionSerialization$$Lambda$113/0x0000000000000000@1b642aca): success
23:25:25  
23:25:25  ===============================================
23:25:25  java/util/Collections/EmptyCollectionSerialization.java
23:25:25  Total tests run: 10, Failures: 1, Skips: 0
23:25:25  ===============================================
23:25:25  
23:25:25  STDERR:
23:25:25  java.lang.Exception: failures: 1
23:25:25  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
23:25:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:25:25  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:25:25  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:25:25  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23:25:25  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
23:25:25  	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by JasonFengJ9** [comment]
Observed a similar failure at an internal build `job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_0/115/`(`win16x64rt2-4`)
```
java version "11.0.16" 2022-07-19
IBM Semeru Runtime Certified Edition 11.0.16+7 (build 11.0.16+7)
Eclipse OpenJ9 VM 11.0.16+7 (build master-10ef9ca2c, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20220618_311 (JIT enabled, AOT enabled)
OpenJ9   - 10ef9ca2c
OMR      - 81e9c1cf4
JCL      - 8f469da1d6 based on jdk-11.0.16+7)

[2022-06-18T03:45:03.711Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-06-18T03:45:04.101Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-06-18T03:48:47.531Z] TEST: java/util/Collections/EmptyCollectionSerialization.java

[2022-06-18T03:48:47.532Z] [TestNG] Running:
[2022-06-18T03:48:47.532Z]   java/util/Collections/EmptyCollectionSerialization.java
[2022-06-18T03:48:47.532Z] 
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_SET", EmptyCollectionSerialization$$Lambda$125/0x0000000000000000@a9787102): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptySet()", EmptyCollectionSerialization$$Lambda$128/0x0000000000000000@da9557fe): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_MAP", EmptyCollectionSerialization$$Lambda$124/0x0000000000000000@e42a7959): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptyList()", EmptyCollectionSerialization$$Lambda$126/0x0000000000000000@2af81013): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptyMap()", EmptyCollectionSerialization$$Lambda$127/0x0000000000000000@c110a239): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_LIST", EmptyCollectionSerialization$$Lambda$123/0x0000000000000000@a37a5527): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptySortedMap()", EmptyCollectionSerialization$$Lambda$130/0x0000000000000000@8eabc236): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptyNavigableMap()", EmptyCollectionSerialization$$Lambda$132/0x0000000000000000@e4b3ff80): success
[2022-06-18T03:48:47.532Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptyNavigableSet()", EmptyCollectionSerialization$$Lambda$131/0x0000000000000000@db8a01aa): failure
[2022-06-18T03:48:47.532Z] java.lang.AssertionError: Collections.emptyNavigableSet(): Unexpected Exception
[2022-06-18T03:48:47.532Z] 	at org.testng.Assert.fail(Assert.java:83)
[2022-06-18T03:48:47.532Z] 	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:74)
[2022-06-18T03:48:47.532Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-06-18T03:48:47.532Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-06-18T03:48:47.532Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-06-18T03:48:47.532Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-06-18T03:48:47.539Z] 	at java.base/java.lang.Thread.run(Thread.java:844)
[2022-06-18T03:48:47.539Z] Caused by: java.io.InvalidClassException: java.util.TreeMap; local class incompatible: stream classdesc serialVersionUID = 1820017752578914078, local class serialVersionUID = 919286545866124006
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:560)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2306)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1792)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:572)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
[2022-06-18T03:48:47.539Z] 	at EmptyCollectionSerialization.patheticDeepCopy(EmptyCollectionSerialization.java:60)
[2022-06-18T03:48:47.539Z] 	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:68)
[2022-06-18T03:48:47.539Z] 	... 15 more
[2022-06-18T03:48:47.539Z] test EmptyCollectionSerialization.serializableSingletons("Collections.emptySortedSet()", EmptyCollectionSerialization$$Lambda$129/0x0000000000000000@6779af3b): failure
[2022-06-18T03:48:47.539Z] java.lang.AssertionError: Collections.emptySortedSet(): Unexpected Exception
[2022-06-18T03:48:47.539Z] 	at org.testng.Assert.fail(Assert.java:83)
[2022-06-18T03:48:47.539Z] 	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:74)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-06-18T03:48:47.539Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
[2022-06-18T03:48:47.539Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-06-18T03:48:47.539Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-06-18T03:48:47.539Z] 	at java.base/java.lang.Thread.run(Thread.java:844)
[2022-06-18T03:48:47.539Z] Caused by: java.io.InvalidClassException: java.util.TreeMap; local class incompatible: stream classdesc serialVersionUID = 1820017752578914078, local class serialVersionUID = 919286545866124006
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:560)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2125)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1975)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2306)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1792)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:572)
[2022-06-18T03:48:47.539Z] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:482)
[2022-06-18T03:48:47.539Z] 	at EmptyCollectionSerialization.patheticDeepCopy(EmptyCollectionSerialization.java:60)
[2022-06-18T03:48:47.539Z] 	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:68)
[2022-06-18T03:48:47.539Z] 	... 15 more
[2022-06-18T03:48:47.539Z] 
[2022-06-18T03:48:47.539Z] ===============================================
[2022-06-18T03:48:47.539Z] java/util/Collections/EmptyCollectionSerialization.java
[2022-06-18T03:48:47.539Z] Total tests run: 10, Failures: 2, Skips: 0
[2022-06-18T03:48:47.539Z] ===============================================
[2022-06-18T03:48:47.539Z] 
[2022-06-18T03:48:47.539Z] STDERR:
[2022-06-18T03:48:47.539Z] java.lang.Exception: failures: 2
[2022-06-18T03:48:47.539Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-06-18T03:48:47.539Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-06-18T03:48:47.539Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-06-18T03:48:47.539Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-06-18T03:48:47.539Z] 	at java.base/java.lang.Thread.run(Thread.java:844)
[2022-06-18T03:48:47.539Z] 
[2022-06-18T03:48:47.539Z] JavaTest Message: Test threw exception: java.lang.Exception
[2022-06-18T03:48:47.539Z] JavaTest Message: shutting down test
[2022-06-18T03:48:47.539Z] 
[2022-06-18T03:48:47.539Z] 
[2022-06-18T03:48:47.539Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
[2022-06-18T03:48:47.539Z] --------------------------------------------------
[2022-06-18T04:20:37.311Z] Test results: passed: 843; failed: 1
[2022-06-18T04:20:51.598Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_0\jvmtest\openjdk\report\html\report.html
[2022-06-18T04:20:51.598Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_16555218368669\jdk_util_1\work
[2022-06-18T04:20:51.598Z] Error: Some tests failed or other problems occurred.
[2022-06-18T04:20:51.598Z] 
[2022-06-18T04:20:51.598Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_OMR_testList_1/42
jdk_util_0
java/util/Collections/EmptyCollectionSerialization.java
```
20:18:46  test EmptyCollectionSerialization.serializableSingletons("Collections.EMPTY_LIST", EmptyCollectionSerialization$$Lambda$11/0x0000000000000000@36f781dc): failure
20:18:46  java.lang.NoClassDefFoundError: java.lang.Class
20:18:46  	at EmptyCollectionSerialization.serializableSingletons(EmptyCollectionSerialization.java:62)
20:18:46  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:18:46  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:18:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:18:46  	at java.lang.reflect.Method.invoke(Method.java:498)
20:18:46  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:18:46  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:18:46  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:18:46  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
20:18:46  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
20:18:46  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:18:46  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:18:46  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:18:46  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:18:46  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:18:46  	at java.lang.Thread.run(Thread.java:826)
```
