### ISSUE TITLE
--illegal-access=debug doesn't show the correct Stacktrace

### ISSUE THREAD

**Issue by Thihup** [eclipse/openj9#11522]
Java -version output
--------------------
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

Summary of problem
------------------
Example code:
```java
public class Example {

    public static void main(String[] args) throws Exception {
        new Example().foo();
    }

    void foo() throws Exception {
        ClassLoader.class.getDeclaredMethod("defineClass", 
        String.class, 
        byte[].class,
        Integer.TYPE, 
        Integer.TYPE).setAccessible(true);
    }
}
```

Hotspot:
```
$ /jdk-15/bin/java --illegal-access=debug Example.java
WARNING: Illegal reflective access by Example (file:/Example.java) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
        at Example.foo(Example.java:12)
        at Example.main(Example.java:4)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:415)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```

OpenJ9:
```
$ /jdk-15-openj9/bin/java --illegal-access=debug Example.java
WARNING: Illegal reflective access by Example (file:/Example.java) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
        at java.lang.StackWalker$StackFrameImpl@768ae0dd
        at java.lang.StackWalker$StackFrameImpl@e154ba68
        at java.lang.StackWalker$StackFrameImpl@90a3b7ac
        at java.lang.StackWalker$StackFrameImpl@382eeb69
        at java.lang.StackWalker$StackFrameImpl@be59a290
```

**Comment by ChengJin01** [comment]
As discussed with @JasonFengJ9 as to how this happens to the JCL code, it turns out we might never deal with `warn` or `debug` option given the `deny` option is treated as an illegal access exception captured by the VM. So the question is whether OpenJ9 need to check `warn` or `debug` in which case some value should be sent out to the OpenJDK to trigger the warn message, which is the next step to figure out.

**Comment by ChengJin01** [comment]
Hi @Thihup,  the issue with the stack trace in this test case should be fixed once the PR at https://github.com/eclipse/openj9/pull/11631 is merged:

```
 $ ../jdk15_openj9_v26/bin/java  --illegal-access=debug   Example.java
WARNING: Illegal reflective access by Example (file:Example.java) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
	at Example.foo(Example.java:16)
	at Example.main(Example.java:6)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:415)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```

FYI  @pshipton
