### ISSUE TITLE
MiniMix_5min_0 HttpURLConnection.requestPropertiesTest AccessControlException: access denied

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11534]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64_aix_xl_Nightly/15
MiniMix_5min_0
```
LT  00:27:28.856 - First failure detected by thread: load-10. Not creating dumps as no dump generation is requested for this load test
LT  00:27:28.860 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3628
LT    Test details  = 'Mauve[gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest]'
LT    Suite number  = 0
LT    Thread number = 10
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest: Default properties (number 0)
LT  Test failed:
LT  java.lang.ExceptionInInitializerError
LT  	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
LT  	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
LT  	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
LT  	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
LT  	at java.net.URL.openConnection(URL.java:1002)
LT  	at gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest.test_Properties(requestPropertiesTest.java:63)
LT  	at gnu.testlet.java.net.HttpURLConnection.requestPropertiesTest.test(requestPropertiesTest.java:44)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:823)
LT  Caused by: java.security.AccessControlException: access denied: ("java.util.logging.LoggingPermission" "control")
LT  	at gnu.testlet.java.util.logging.Logger.TestSecurityManager.checkPermission(TestSecurityManager.java:48)
LT  	at java.util.logging.LogManager.checkPermission(LogManager.java:1586)
LT  	at java.util.logging.Logger.setParent(Logger.java:2035)
LT  	at java.util.logging.LogManager$7.run(LogManager.java:1205)
LT  	at java.security.AccessController.doPrivileged(AccessController.java:678)
LT  	at java.util.logging.LogManager.doSetParent(LogManager.java:1202)
LT  	at java.util.logging.LogManager.access$1200(LogManager.java:145)
LT  	at java.util.logging.LogManager$LoggerContext.addLocalLogger(LogManager.java:830)
LT  	at java.util.logging.LogManager$LoggerContext.addLocalLogger(LogManager.java:758)
LT  	at java.util.logging.LogManager.addLogger(LogManager.java:1162)
LT  	at java.util.logging.LogManager.demandSystemLogger(LogManager.java:592)
LT  	at java.util.logging.Logger.getPlatformLogger(Logger.java:576)
LT  	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
LT  	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
LT  	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
LT  	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
LT  	at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
LT  	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
LT  	at sun.net.www.protocol.http.HttpURLConnection.<clinit>(HttpURLConnection.java:432)
LT  	... 14 more
```

**Comment by pshipton** [comment]
@Mesbah-Alam is the MiniMix test running sub-tests which were excluded in other loads? I thought we'd already excluded sub-tests that set a SecurityManager.
If the same sub-tests aren't excluded, I wonder if this is also the cause of https://github.com/eclipse/openj9/issues/11532

**Comment by Mesbah-Alam** [comment]
MiniMix runs [mauve_all.xml ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mix/mix-more.xml#L8) using more than 1 threads. However, a load that runs mauve_all.xml would only take into account the excludes in [mauve_all_exclude.xml](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml) file. 

This should be causing the problem above. Since all the exclusions for SecurityManager related failures were added in [mauve_multiThread_exclude.xml ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml) - since SecurityManager related timing issues take place only when mauve load is run using more than 1 thread, e.g., mauve loads that run [mauve_multiThread.xml](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml). 

I will have a PR to fix the test load so that we use the right mauve inventory file suitable for multi-threaded load run in MiniMix.
