### ISSUE TITLE
jlink output cannot load openjfx apps due to java.lang.UnsatisfiedLinkError: Can't load glassgtk3

### ISSUE THREAD

**Issue by bmarwell** [eclipse/openj9#11547]
Java -version output
--------------------
```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
```

Summary of problem
------------------

If I create a jlink distribution using OpenJ9, an app using OpenJFX will not start:

```
(bmarwell@aeon)[~/git/MemeforceHunt]$ mvn  clean verify -Prun-its,jlink,docs
[…]
maven-jlink-plugin
[…]
(bmarwell@aeon)[~/git/MemeforceHunt]$ ./app/target/maven-jlink/classifiers/linux/bin/memeforcehunt
Loading library glassgtk3 from resource failed: java.lang.NoClassDefFoundError: com.sun.glass.ui.Pixels
java.lang.NoClassDefFoundError: com.sun.glass.ui.Pixels
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1787)
        at java.base/java.lang.System.load(System.java:581)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:187)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication$$Lambda$77/0x000000005c072d20.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl$$Lambda$24/0x00000000f86d19a0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:845)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.Pixels
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1104)
        ... 24 more
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't load glassgtk3
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl$$Lambda$24/0x00000000f86d19a0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:845)
Caused by: java.lang.UnsatisfiedLinkError: Can't load glassgtk3
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1819)
        at java.base/java.lang.System.loadLibrary(System.java:602)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:163)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:187)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication$$Lambda$77/0x000000005c072d20.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at javafx.graphics/com.sun.glass.ui.Application.run(Application.java:144)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        ... 7 more
```

However, using the same hotspot version, the app starts as expected.

The sample output from above is a simple tool which I created for the speedrun gaming community:
https://github.com/alttpj/MemeforceHunt

// Edit: Better use this tag: https://github.com/alttpj/MemeforceHunt/tree/v2.2.0-M1

Diagnostic files
----------------

None

**Comment by JasonFengJ9** [comment]
I will have a look this.

**Comment by JasonFengJ9** [comment]
Not able to reproduce this at `Mac OSX` platform, and got following error at `Linux x86`:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Memeforce Hunt :: parent ........................... FAILURE [  5.097 s]
[INFO] Memeforce Hunt ..................................... SKIPPED
[INFO] Memeforce Hunt :: common ........................... SKIPPED
[INFO] Memeforce Hunt :: common :: value .................. SKIPPED
[INFO] Memeforce Hunt :: common :: sprites ................ SKIPPED
[INFO] Memeforce Hunt :: lib .............................. SKIPPED
[INFO] Memeforce Hunt :: app .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.379 s
[INFO] Finished at: 2021-01-04T10:35:32-08:00
[INFO] Final Memory: 16M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) on project memeforcehunt-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) on project memeforcehunt-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:260)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

@bmarwell any hints to reproduce the issue?
In addition, there were some known issue at `v0.23` release, would you try a `v0.24` early release build [1] instead?

[1] https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk15u-2020-12-28-10-18

**Comment by bmarwell** [comment]
Hi, you cut out the error message preceding the info messages. I think you need to use a more recent version.

As I use Linux, I bet this happens only on Linux.

Haven't been able to download the recent jdk due to the ongoing Telefon+AWS peering problem.

Please try maven 3.6.3.

**Comment by pshipton** [comment]
Milestone 2 builds are available now.
https://openj9.slack.com/archives/C01C8PL6319/p1609854328008100

**Comment by JasonFengJ9** [comment]
Reproduced the issue reported with `v0.23` release build.

The issue is not observed with `v0.24` milestone 2 build [1]. Assuming it has been fixed.

[1] https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9_openj9-0.24.0-m2/OpenJDK15U-jdk_x64_linux_openj9_15.0.1_9_openj9-0.24.0-m2.tar.gz
