### ISSUE TITLE
Eclipse IDE can't launch with Java 15 OpenJ9

### ISSUE THREAD

**Issue by Filip62** [eclipse/openj9#11586]
It **can't launch** with:
- AdoptOpenJDK 15 OpenJ9

It **can launch** with:
- AdoptOpenJDK 11 OpenJ9
- AdoptOpenJDK 14 OpenJ9
- AdoptOpenJDK 15 Hotspot

Eclipse IDE reports:
`An error has occurred. See the log file...`

```
!SESSION 2021-01-06 20:08:24.107 -----------------------------------------------
eclipse.buildId=4.18.0.I20201202-1800
java.fullversion=15.0.1+9
JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 4 0 2021-01-06 20:08:26.058
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	Can't load swt-pi4-gtk-4940r23
	Can't load swt-pi4-gtk
	Can't load /home/filip/.swt/lib/linux/x86_64/libswt-pi4-gtk-4940r23.so
	Can't load /home/filip/.swt/lib/linux/x86_64/libswt-pi4-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:338)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:96)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:163)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:726)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:168)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

```

Output of `tree ~/.swt`:
```
/home/filip/.swt
├── lib
│  └── linux
│     └── x86_64
│        └── libswt-pi3-gtk-4940r23.so
└── trims.prefs
```

**Comment by JasonFengJ9** [comment]
This might be due to some known issue within JDK15 v0.23 release.

Would you try a v0.24 milestone build [1]?

[1] https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15.0.1+9_openj9-0.24.0-m2

**Comment by Filip62** [comment]
I tried and it didn't work.

The same error.

I have no idea why, but to me it seems like for some reason the Java 15 OpenJ9 JVM wants to find
libswt-_**pi4**_-gtk-4940r23.so - which doesn't exist anywhere in any package on the internet, as far as I can tell.

I do not know the meaning of the piX part of the library file, but it just feels like it is looking for the wrong one, it
should be looking for libswt-_**pi3**_-gtk-4940r23.so

Am I wrong?

**Comment by JasonFengJ9** [comment]
Thanks trying @Filip62 
I will have a look.

**Comment by keithc-ca** [comment]
This is due to #11076. Taking the same SHAs as the latest nightly build from adoptopenjdk.net and making the one-line change in #11591 fixes this.

**Comment by JasonFengJ9** [comment]
So this is a Linux platform specific problem. I didn't reproduce it at Mac OS. (it took me a while to setup a Linux desktop environment).
