### ISSUE TITLE
jdk16 MiniMix_5min_0 InaccessibleObjectException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11607]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.system_s390x_linux_Nightly/1
MiniMix_5min_0
```
LT  10:14:20.283 - Test failed
LT    Failure num.  = 1
LT    Test number   = 2443
LT    Test details  = 'Mauve[gnu.testlet.java.lang.reflect.AccessibleObject.accessible]'
LT    Suite number  = 0
LT    Thread number = 5
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.lang.reflect.AccessibleObject.accessible (number 0)
LT  java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.ClassLoader() accessible: module java.base does not "opens java.lang" to unnamed module @835191a6
LT  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
LT  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
LT  	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
LT  	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
LT  	at gnu.testlet.java.lang.reflect.AccessibleObject.accessible.test(accessible.java:43)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
LT  	at java.base/java.lang.Thread.run(Thread.java:853)
LT  FAIL: gnu.testlet.java.lang.reflect.AccessibleObject.accessible: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.ClassLoader() accessible: module java.base does not "opens java.lang" to unnamed module @835191a6 (number 0)
```

**Comment by pshipton** [comment]
@Mesbah-Alam I expect this is related to https://github.com/eclipse/openj9/issues/11240

The test needs to run with Java option `--add-opens java.base/java.lang=ALL-UNNAMED` to fix this failure. Using this option for jdk11+ isn't harmful, although it's only needed from jdk16.

**Comment by Mesbah-Alam** [comment]
I'll prepare a PR to add `--add-opens java.base/java.lang=ALL-UNNAME` for 11+ for this target.
