### ISSUE TITLE
JDK16: IAE in ConstantDynamic resolution

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11605]
Failures:
java/lang/invoke/lambda/LambdaReceiver.java.LambdaReceiver
java/lang/invoke/lambda/LambdaReceiverBridge.java.LambdaReceiverBridge
java/lang/invoke/lambda/superProtectedMethod/InheritedProtectedMethod.java.InheritedProtectedMethod

```
/jdk_lang_j9_0/work/classes/0/java/lang/invoke/lambda/LambdaReceiver.d:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_s390x_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/invoke/lambda:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
09:48:05          LambdaReceiver
09:48:05  STDERR:
09:48:05  java.lang.IllegalAccessError: Class LambdaReceiver$$Lambda$701/0x000000001077a750 illegally accessing "package private" member of class java/lang/invoke/MethodHandles
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.resolveConstantDynamic(MethodHandleResolver.java:106)
09:48:05  	at LambdaReceiver$$Lambda$701/0x000000001077a750.m(Unknown Source)
09:48:05  	at LambdaReceiver.main(LambdaReceiver.java:64)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:48:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:48:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:48:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
09:48:05  	at java.base/java.lang.Thread.run(Thread.java:853)


/Test_openjdk16_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
09:48:05          LambdaReceiverBridge
09:48:05  STDERR:
09:48:05  java.lang.IllegalAccessError: Class LambdaReceiverBridge$$Lambda$702/0x000000001077b7a0 illegally accessing "package private" member of class java/lang/invoke/MethodHandles
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.resolveConstantDynamic(MethodHandleResolver.java:106)
09:48:05  	at LambdaReceiverBridge$$Lambda$702/0x000000001077b7a0.m(Unknown Source)
09:48:05  	at LambdaReceiverBridge.main(LambdaReceiverBridge.java:65)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:48:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:48:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:48:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
09:48:05  	at java.base/java.lang.Thread.run(Thread.java:853)

09:48:05    java/lang/invoke/lambda/superProtectedMethod/InheritedProtectedMethod.java
09:48:05  
09:48:05  config InheritedProtectedMethod.setup(): success
09:48:05  test InheritedProtectedMethod.run(): failure
09:48:05  java.lang.reflect.InvocationTargetException
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:48:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:48:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:48:05  	at InheritedProtectedMethod.run(InheritedProtectedMethod.java:73)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:48:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:48:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:48:05  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
09:48:05  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
09:48:05  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
09:48:05  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
09:48:05  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
09:48:05  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
09:48:05  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
09:48:05  	at org.testng.TestRunner.run(TestRunner.java:623)
09:48:05  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
09:48:05  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
09:48:05  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
09:48:05  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
09:48:05  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
09:48:05  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
09:48:05  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
09:48:05  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
09:48:05  	at org.testng.TestNG.run(TestNG.java:1018)
09:48:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
09:48:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:48:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
09:48:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:48:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
09:48:05  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:48:05  	at java.base/java.lang.Thread.run(Thread.java:853)
09:48:05  Caused by: java.lang.IllegalAccessError: Class MethodInvoker$$Lambda$210/0x0000000018059b68 illegally accessing "package private" member of class java/lang/invoke/MethodHandles
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
09:48:05  	at java.base/java.lang.invoke.MethodHandleResolver.resolveConstantDynamic(MethodHandleResolver.java:106)
09:48:05  	at MethodInvoker$$Lambda$210/0x0000000018059b68.invokeMethodReference(Unknown Source)
09:48:05  	at MethodInvoker.invoke(MethodInvoker.java:29)
09:48:05  	... 34 more
```

**Comment by tajila** [comment]
This is related to https://github.com/eclipse/openj9/issues/11366
