### ISSUE TITLE
jdk17: IllegalAccessError: jdk/internal/org/objectweb/asm/Opcodes is not visible

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11613]
Adopt jdk-17 build break:
```
08:04:39  Writing generated classes to /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/build/linux-x86_64-server-release/support/ddr/gensrc/com/ibm/j9ddr/vm29/pointer/generated
08:04:40  Unhandled structure type: big_int_unionPointer->i128 __int128
08:04:40  Unhandled structure type: _IO_FILEPointer->_lock _IO_lock_t*
08:04:41  Exception in thread "main" java.lang.IllegalAccessError: jdk/internal/org/objectweb/asm/Opcodes is not visible
08:04:41  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
08:04:41  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:450)
08:04:41  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1167)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:954)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:862)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:820)
08:04:41  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
08:04:41  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1106)
08:04:41  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
08:04:41  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
08:04:41  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:450)
08:04:41  	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1167)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:954)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:862)
08:04:41  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:820)
08:04:41  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
08:04:41  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1106)
08:04:41  	at com.ibm.j9ddr.BytecodeGenerator.getStructureClassBytes(BytecodeGenerator.java:113)
08:04:41  	at com.ibm.j9ddr.StructureReader.getStructureClassBytes(StructureReader.java:860)
08:04:41  	at com.ibm.j9ddr.tools.ClassGenerator.writeTo(ClassGenerator.java:186)
08:04:41  	at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:147)
08:04:41  	at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:53)
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-openj9/223/console

**Comment by pshipton** [comment]
[2021-01-11T07:59:47.040Z]   Source version info:
[2021-01-11T07:59:47.040Z]     openjdk - 1cfc6bfe87
[2021-01-11T07:59:47.040Z]     openj9  - 4be12d366
[2021-01-11T07:59:47.040Z]     omr     - bded46caf

Not sure what caused this, but the latest build is working so it seems to be resolved.
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/426/

**Comment by pshipton** [comment]
Maybe a timing problem? This build is a match for the SHAs, but it succeeded.
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/424/
OpenJ9: 4be12d3
OMR: bded46c
OpenJDKnext: 1cfc6bf - openj9-openjdk-jdk

@keithc-ca fyi

**Comment by andrew-m-leonard** [comment]
Still failing: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-openj9/224/console

**Comment by keithc-ca** [comment]
The difference may be that adopt is using Java 16 for the boot-jdk while openj9 is using Java 15.

**Comment by keithc-ca** [comment]
The same problem occurs building Java 16 using Java 16 as the boot jdk.

**Comment by keithc-ca** [comment]
Addressed by these pull requests:
* https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/5
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/265
