### ISSUE TITLE
TEST: java/util/Locale/LocaleCategory.java failed with jdk_util_j9: ubuntu, openj9, 11 |15 

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#11620]
https://github.com/AdoptOpenJDK/run-aqa/issues/59#issuecomment-758067623

TEST: java/util/Locale/LocaleCategory.java failed with jdk_util_j9: ubuntu, openj9, 11 |15

```
STDERR:
java.util.IllformedLocaleException: Ill-formed language: c.u [at index 0]
	at java.base/java.util.Locale$Builder.setLanguage(Locale.java:2585)
	at LocaleCategory.main(LocaleCategory.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:836)

JavaTest Message: Test threw exception: java.util.IllformedLocaleException: Ill-formed language: c.u [at index 0]
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.util.IllformedLocaleException: Ill-formed language: c.u [at index 0]
rerun:
cd /home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/scratch && \
HOME=/home/runner \
LANG=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/util/Locale/LocaleCategory.d:/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/Locale:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/text/testlib:/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/text/testlib:/home/runner/work/run-aqa/run-aqa/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/runner/work/run-aqa/run-aqa/jvmtest/openjdk/jtreg/lib/jtreg.jar \
    /opt/hostedtoolcache/jdk-11-openj9/1.0.0/x64/bin/java \
        -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache' \
        -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/hostedtoolcache/jdk-11-openj9/1.0.0/x64 \
        -Dcompile.jdk=/opt/hostedtoolcache/jdk-11-openj9/1.0.0/x64 \
        -Dtest.timeout.factor=8.0 \
        -Dtest.root=/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
        -Dtest.name=java/util/Locale/LocaleCategory.java \
        -Dtest.file=/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/Locale/LocaleCategory.java \
        -Dtest.src=/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/Locale \
        -Dtest.src.path=/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/Locale:/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/text/testlib \
        -Dtest.classes=/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/util/Locale/LocaleCategory.d \
        -Dtest.class.path=/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/util/Locale/LocaleCategory.d:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/text/testlib \
        -Dtest.class.path.prefix=/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/util/Locale/LocaleCategory.d:/home/runner/work/run-aqa/run-aqa/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/Locale:/home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/classes/java/text/testlib \
        -ea \
        -esa \
        -Xmx512m \
        -Xdump:system:none \
        -Xdump:heap:none \
        -Xdump:system:events=gpf+abort+traceassert+corruptcache \
        -Duser.language.display=ja \
        -Duser.language.format=zh \
        com.sun.javatest.regtest.agent.MainWrapper /home/runner/work/run-aqa/run-aqa/openjdk-tests/TKG/test_output_16080649133171/jdk_util_j9_0/work/java/util/Locale/LocaleCategory.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.util.IllformedLocaleException: Ill-formed language: c.u [at index 0]

```

https://github.com/AdoptOpenJDK/run-aqa/runs/1664999703?check_suite_focus=true

**Comment by pshipton** [comment]
Created https://github.com/eclipse/omr/pull/5744 which fixes the issue.

**Comment by pshipton** [comment]
The OMR change has promoted, should be fixed in the next build.
