### ISSUE TITLE
testDDRExtJunit_FindExtThread_0 NPE TestThread.getStackSlotsValues(TestThread.java:234)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11640]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1/220/
testDDRExtJunit_FindExtThread_0
```
     [java] [AutoRun] [INFO] Starting testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] [AutoRun] [INFO] Finished testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] ================Test Result for F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1\openjdk-tests\TKG\test_output_16105113056287\testDDRExtJunit_FindExtThread_0\DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   1 out of 13 test cases.
     [java] [AutoRun] [INFO] Failures: 0 out of 13 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] java.lang.NullPointerException
     [java] 	at j9vm.test.ddrext.junit.TestThread.getStackSlotsValues(TestThread.java:234)
     [java] 	at j9vm.test.ddrext.junit.TestThread.testLocalmap(TestThread.java:196)
```

**Comment by pshipton** [comment]
3 x 5x grinder https://ci.eclipse.org/openj9/job/Grinder/1376/

**Comment by JasonFengJ9** [comment]
A similar `testDDRExtJunit_FindExtThread_0_FAILED` is observed at JDK11 0.27 release build https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Release_testList_1/5/consoleFull
