### ISSUE TITLE
Some zlinux machines offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11651]
https://ci.eclipse.org/openj9/computer/ub16-390-1/
https://ci.eclipse.org/openj9/computer/ub18-390-1/
https://ci.eclipse.org/openj9/computer/ub18-390-2/
```
Connection was broken

java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Machines all appear to be taking jobs now.  Must've been a temporary network problem.
