### ISSUE TITLE
J9 (1.8.0_275) and J9 (11.0.9) failed to threw AssertionError.

### ISSUE THREAD

**Issue by fuzzy000** [eclipse/openj9#11721]
JVM Versions
------------------
We used the following versions of J9:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201110_845 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```
```
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+12)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 9 Linux amd64-64-Bit Compressed References 20180814_248 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - feec4d2ae based on jdk-9.0.4+12)
```
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
```

The used OpenJDK versions:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```
```
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
```
Summary of the Problem
------------------

We made some changes to a class file in the JUnit project, and let several JVMs execute the corresponding JUnit test. We found that in a run, J9 (1.8.0_275) and J9 (11.0.9) just passed the two test cases, while OpenJDK (8u275, 9.0.4, 11.0.9) and J9 (9.0.4) threw java.lang.AssertionError for both test cases.

Diagnostic files
----------------
[assertionIssue.zip](https://github.com/eclipse/openj9/files/5849328/assertionIssue.zip)

1. extract the assertionIssue.zip
2. In directory `assertionIssue`, run command `java -cp sootOutput/junit-junit/:hamcrest-all-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore org.junit.rules.TestWatchmanTest`

Execution environment
---------------------------------
- OS and version: Ubuntu 16.04.6 LTS
- CPU model: Intel(R) Xeon(R) CPU E5-4610 v4 @ 1.80GHz
- Number of CPU cores: 4CPUs, each has 10 cores
- Size of physical memory: 16384 MB * 20

**Comment by pshipton** [comment]
```
There were 2 failures:
1) neitherLogSuccessNorFailedForViolatedAssumption(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.neitherLogSuccessNorFailedForViolatedAssumption(TestWatchmanTest.java:35)
2) logFailingTest(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting failed finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.logFailingTest(TestWatchmanTest.java:59)
```

**Comment by fuzzy000** [comment]
The output of J9 (1.8.0_275) and J9 (11.0.9) is like:
```
JUnit version 4.13
...
Time: 0.021
OK (2 tests)
```
The output of other JVMs is like:
```
JUnit version 4.13
.E.E
Time: 0.037
There were 2 failures:
1) neitherLogSuccessNorFailedForViolatedAssumption(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError:
Expected: is "starting finished "
     but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.junit.rules.TestWatchmanTest.neitherLogSuccessNorFailedForViolatedAssumption(TestWatchmanTest.java:35)
2) logFailingTest(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError:
Expected: is "starting failed finished "
     but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.junit.rules.TestWatchmanTest.logFailingTest(TestWatchmanTest.java:59)

FAILURES!!!
Tests run: 2,  Failures: 2
```

**Comment by pshipton** [comment]
@tajila this could use an owner.

**Comment by tajila** [comment]
Apologies @pshipton, I missed this message.

**Comment by tajila** [comment]
Not going to get to this soon, moving to next release.

**Comment by tajila** [comment]
@JasonFengJ9 can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure, will look into it.

**Comment by JasonFengJ9** [comment]
Latest OpenJ9 JDK8/11 throw expected AssertionErrors.
```
jdk8u282-b08/Contents/Home/bin/java -showversion -cp sootOutput/junit-junit/:hamcrest-all-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore org.junit.rules.TestWatchmanTest
openjdk version "1.8.0_282-internal"
OpenJDK Runtime Environment (build 1.8.0_282-internal-202101271831-b08)
Eclipse OpenJ9 VM (build master-091d2c311, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210127_845 (JIT enabled, AOT enabled)
OpenJ9   - 091d2c311
OMR      - 5ad82738f
JCL      - 12291000 based on jdk8u282-b08)

JUnit version 4.13
.E.E
Time: 0.017
There were 2 failures:
1) neitherLogSuccessNorFailedForViolatedAssumption(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.neitherLogSuccessNorFailedForViolatedAssumption(TestWatchmanTest.java:35)
2) logFailingTest(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting failed finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.logFailingTest(TestWatchmanTest.java:59)

FAILURES!!!
Tests run: 2,  Failures: 2
```
```
jdk-11.0.11+1/Contents/Home/bin/java -showversion -cp sootOutput/junit-junit/:hamcrest-all-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore org.junit.rules.TestWatchmanTest
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+1-202102091841)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-8e6e103bb, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210209_909 (JIT enabled, AOT enabled)
OpenJ9   - 8e6e103bb
OMR      - 4c449812b
JCL      - 27e7f25b77 based on jdk-11.0.11+1)
JUnit version 4.13
.E.E
Time: 0.019
There were 2 failures:
1) neitherLogSuccessNorFailedForViolatedAssumption(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.neitherLogSuccessNorFailedForViolatedAssumption(TestWatchmanTest.java:35)
2) logFailingTest(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting failed finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.logFailingTest(TestWatchmanTest.java:59)

FAILURES!!!
Tests run: 2,  Failures: 2
```

@fuzzy000 can you check if this problem still presents against latest OpenJ9 JVM?

**Comment by pshipton** [comment]
Does this also run on Java 16? If so we can check against a 0.25 build and close this against the 0.25 milestone.
Latest builds are here https://ci.eclipse.org/openj9/job/Pipeline-Release-0.25.0-Build16/3/

**Comment by JasonFengJ9** [comment]
> Does this also run on Java 16? If so we can check against a 0.25 build and close this against the 0.25 milestone.

JDK16 0.25 milestone build [1] throws expected AssertionError as well.
```
jdk/bin/java -showversion -cp sootOutput/junit-junit/:hamcrest-all-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore org.junit.rules.TestWatchmanTest
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDK16x86-64macRelease)
Eclipse OpenJ9 VM (build v0.25.0-release-1911986f731, JRE 16 Mac OS X amd64-64-Bit Compressed References 20210213_1 (JIT enabled, AOT enabled)
OpenJ9   - 1911986f731
OMR      - 6ca2fd841e1
JCL      - 63b6db22be7 based on jdk-16+36)
JUnit version 4.13
.E.E
Time: 0.034
There were 2 failures:
1) neitherLogSuccessNorFailedForViolatedAssumption(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.neitherLogSuccessNorFailedForViolatedAssumption(TestWatchmanTest.java:35)
2) logFailingTest(org.junit.rules.TestWatchmanTest)
java.lang.AssertionError: 
Expected: is "starting failed finished "
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.junit.rules.TestWatchmanTest.logFailingTest(TestWatchmanTest.java:59)

FAILURES!!!
Tests run: 2,  Failures: 2
```

[1] http://ub18p8art.casa.cs.unb.ca/artifactory/ci-eclipse-openj9/Build_JDK16_x86-64_mac_Release/1/OpenJ9-JDK16-x86-64_mac-20210213-100148.tar.gz
