### ISSUE TITLE
JDK8 Windows : testDDRExtJunit_FindExtThread_0_FAILED - Structure validation failed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11727]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.functional_x86-64_windows/1`
```
21:52:46  openjdk version "1.8.0_282-internal"
21:52:46  OpenJDK Runtime Environment (build 1.8.0_282-internal-202101200210-b07)
21:52:46  Eclipse OpenJ9 VM (build master-b90f8218d, JRE 1.8.0 Windows Server 2012 R2 amd64-64-Bit Compressed References 20210120_31 (JIT enabled, AOT enabled)
21:52:46  OpenJ9   - b90f8218d
21:52:46  OMR      - 83828b8d7
21:52:46  JCL      - 56a6fa896b based on jdk8u282-b07)
```
to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
01:43:08  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_windows&TARGET=testDDRExtJunit_FindExtThread_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test testDDRExtJunit_FindExtThread_0 ...
===============================================
testDDRExtJunit_FindExtThread_0 Start Time: Tue Jan 19 21:25:36 2021 Epoch Time (ms): 1611120336593
variation: NoOptions
JVM_OPTIONS:  
 [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [ERROR] Structure validation failed
     [java] [DDRExtTesterBase] [ERROR] Unrecognised command: !portlibptbuffers_ 0x0000000000000000[DDRExtTesterBase] [INFO] Runing structure test with : !j9object 0x0000000000000000
     [java] 
     [java] 
     [java] [DDRExtTesterBase] [INFO] Can not validate: '!j9object  0x0000000000000000' output is not a structure
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9threadmonitor 0x000001A713A68F38
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9javastack 0x000000000014D578
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9stackelement 0x0000000000000000
     [java] [DDRExtTesterBase] [WARN] '!j9stackelement  0x0000000000000000' output contains <FAULT> references
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9stackwalkstate 0x0000000000150908
     [java] -10[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9vmentrylocalstorage 0x00000098F6BFF650
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9vmgcsublistfragment 0x0000000000150870
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !mm_gcrememberedsetfragment 0x00000000001508A0
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9pool 0x000001A713AFCD20
     [java] 8162147483650[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9monitorenterrecord 0x0000000000000000
     [java] [DDRExtTesterBase] [WARN] '!j9monitorenterrecord  0x0000000000000000' output contains <FAULT> references
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9jitdecompilationinfo 0x0000000000000000
     [java] [DDRExtTesterBase] [WARN] '!j9jitdecompilationinfo  0x0000000000000000' output contains <FAULT> references
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9modronthreadlocalheap 0x0000000000150B40
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !portlibptbuffers_ 0x0000000000000000
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9dltinformationblock 0x0000000000150C38
     [java] 30[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9vmgcsegregatedallocationcacheentry 0x0000000000000000
     [java] [DDRExtTesterBase] [WARN] '!j9vmgcsegregatedallocationcacheentry  0x0000000000000000' output contains <FAULT> references
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9osrbuffer 0x0000000000000000
     [java] [DDRExtTesterBase] [WARN] '!j9osrbuffer  0x0000000000000000' output contains <FAULT> references
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !omr_vmthread 0x0000000000150F80
     [java] 01[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9gsparameters 0x0000000000150F48
     [java] 0[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!j9vmthread  0x00150600'
     [java] [AutoRun] [INFO] Finished testJ9VMThread(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] Starting testJ9Thread(j9vm.test.ddrext.junit.TestThread)
     [java] 2562560-1[DDRExtTesterBase] [INFO] Validation started for : '!j9thread  0x1a727551130'
     [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!j9thread  0x1a727551130'
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9threadlibrary 0x00007FFC3A272160
     [java] 130[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9threadtracing 0x000001A7137A62B8
     [java] [DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !_rtl_critical_section 0x000001A7275515A8
     [java] -10[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!j9thread  0x1a727551130'
     [java] [AutoRun] [INFO] Finished testJ9Thread(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] Starting testThreadOptions(j9vm.test.ddrext.junit.TestThread)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  help'
     [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!threads  help'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  help'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  stack'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  stack'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  stackslots'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  stackslots'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  flags'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  flags'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  debugEventData'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  debugEventData'
     [java] java.lang.NullPointerException
     [java] 	at j9vm.test.ddrext.junit.TestThread.getStackSlotsValues(TestThread.java:234)
     [java] 	at j9vm.test.ddrext.junit.TestThread.testLocalmap(TestThread.java:196)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  monitors'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  monitors'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  trace'
     [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!threads  trace'
     [java] [DDRExtTesterBase] [INFO] Runing structure test with : !utthreaddata 0x1a7132ec200
     [java] 2000[DDRExtTesterBase] [INFO] Structure validation passed
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  trace'
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!threads  search 0x854'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!threads  search 0x854'
     [java] [AutoRun] [INFO] Finished testThreadOptions(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] Starting testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] [AutoRun] [INFO] Finished testLocalmap(j9vm.test.ddrext.junit.TestThread)
     [java] 
     [java] [AutoRun] [INFO] ================Test Result for C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.functional_x86-64_windows\openjdk-tests\TKG\test_output_16111122696037\testDDRExtJunit_FindExtThread_0\DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   1 out of 13 test cases.
     [java] [AutoRun] [INFO] Failures: 0 out of 13 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1

BUILD FAILED
C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.functional_x86-64_windows\jvmtest\functional\DDR_Test\tck_ddrext.xml:115: Java returned: -2

Total time: 38 seconds

testDDRExtJunit_FindExtThread_0_FAILED
```

**Comment by pshipton** [comment]
Seems a dup of https://github.com/eclipse/openj9/issues/11640
