### ISSUE TITLE
jdk-15.0.2+7_openj9-0.24.0: java/lang/ProcessBuilder/Basic.java#id0 failure

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11738]
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/174/console
```
09:08:51  This appears to be a Unix system.
09:08:51  Testing ASCII environment values
09:08:51  Testing Latin1 environment values
09:08:51  Testing directory .
09:08:51  Testing directory ..
09:08:51  Testing directory /
09:08:51  Testing directory /bin
09:08:51  cmdp
09:08:51  cmdp 0: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java
09:08:51  cmdp 1: -XX:+DisplayVMOutputToStderr
09:08:51  cmdp 2: -classpath
09:08:51  cmdp 3: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/test_output_16113064611379/jdk_custom_0/work/classes/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jtreg.jar
09:08:51  cmdp 4: Basic$JavaChild
09:08:51  cmdp 5: System.getenv()
09:08:51  envp
09:08:51  envp 0: LC_ALL=C
09:08:51  envp 1: FO=BR
09:08:51   waitFor process: delta: 113283
09:08:51  
09:08:51  Passed = 9127, failed = 4
09:08:51  
09:08:51  STDERR:
09:08:51  java.lang.Throwable
09:08:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
09:08:51  	at Basic.fail(Basic.java:2744)
09:08:51  	at Basic.check(Basic.java:2747)
09:08:51  	at Basic.realMain(Basic.java:1794)
09:08:51  	at Basic.main(Basic.java:2754)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
09:08:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
09:08:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:08:51  	at java.base/java.lang.Thread.run(Thread.java:853)
09:08:51  java.lang.Throwable
09:08:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
09:08:51  	at Basic.fail(Basic.java:2744)
09:08:51  	at Basic.check(Basic.java:2747)
09:08:51  	at Basic.realMain(Basic.java:1795)
09:08:51  	at Basic.main(Basic.java:2754)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
09:08:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
09:08:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:08:51  	at java.base/java.lang.Thread.run(Thread.java:853)
09:08:51  java.lang.Throwable
09:08:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
09:08:51  	at Basic.fail(Basic.java:2744)
09:08:51  	at Basic.check(Basic.java:2747)
09:08:51  	at Basic.realMain(Basic.java:1796)
09:08:51  	at Basic.main(Basic.java:2754)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
09:08:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
09:08:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:08:51  	at java.base/java.lang.Thread.run(Thread.java:853)
09:08:51  >'0'< not equal to '1'
09:08:51  java.lang.Throwable
09:08:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
09:08:51  	at Basic.fail(Basic.java:2744)
09:08:51  	at Basic.fail(Basic.java:2745)
09:08:51  	at Basic.equal(Basic.java:2751)
09:08:51  	at Basic.realMain(Basic.java:1797)
09:08:51  	at Basic.main(Basic.java:2754)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
09:08:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
09:08:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:08:51  	at java.base/java.lang.Thread.run(Thread.java:853)
09:08:51  java.lang.AssertionError: Some tests failed
09:08:51  	at Basic.main(Basic.java:2756)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
09:08:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
09:08:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:08:51  	at java.base/java.lang.Thread.run(Thread.java:853)
09:08:51  
09:08:51  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
```

**Comment by pshipton** [comment]
I think this is a test/machine issue. The test fails because it's expecting an OutOfMemoryError but didn't get it. The code just allocates something really big as follows, which doesn't guarantee an OOM if the machine has enough memory.
```
                switch(new Random().nextInt(3)) {
                case 0: dummy = new Integer[Integer.MAX_VALUE]; break;
                case 1: dummy = new double[Integer.MAX_VALUE];  break;
                case 2: dummy = new byte[Integer.MAX_VALUE][];  break;
```
