### ISSUE TITLE
openjdk String/NonCharacterMapping.java SpecialCasingTest.java ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11799]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/279
aix71-p8-7
java/lang/String/NonCharacterMapping.java
```
01:00:09  java.lang.ArrayIndexOutOfBoundsException
01:00:09  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
01:00:09  	at java.base/java.lang.CharacterDataLatin1.toUpperCaseEx(CharacterDataLatin1.java:260)
01:00:09  	at java.base/java.lang.Character.toUpperCaseEx(Character.java:10573)
01:00:09  	at java.base/java.lang.StringUTF16.toUpperCase(StringUTF16.java:780)
01:00:09  	at java.base/java.lang.String.toUpperCase(String.java:2840)
01:00:09  	at NonCharacterMapping.main(NonCharacterMapping.java:74)
```
java/lang/String/SpecialCasingTest.java
```
01:00:09  java.lang.ArrayIndexOutOfBoundsException
01:00:09  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
01:00:09  	at java.base/java.lang.CharacterDataLatin1.toUpperCaseEx(CharacterDataLatin1.java:260)
01:00:09  	at java.base/java.lang.Character.toUpperCaseEx(Character.java:10573)
01:00:09  	at java.base/java.lang.StringUTF16.toUpperCase(StringUTF16.java:780)
01:00:09  	at java.base/java.lang.String.toUpperCase(String.java:2840)
01:00:09  	at SpecialCasingTest.testUpperCase(SpecialCasingTest.java:320)
01:00:09  	at SpecialCasingTest.test(SpecialCasingTest.java:298)
01:00:09  	at SpecialCasingTest.test(SpecialCasingTest.java:147)
01:00:09  	at SpecialCasingTest.main(SpecialCasingTest.java:118)
```

It only failed on AIX jdk11, didn't fail in the AIX_XL build, passed the previous night.

Changes from the previous build:
https://github.com/eclipse/openj9/compare/d132a6b...cafb94c
https://github.com/eclipse/openj9-omr/compare/b38b0b7...5ad8273
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/b608a89...f7475ea

Grinders
https://ci.eclipse.org/openj9/job/Grinder/1472 - aix71-p8-3
https://ci.eclipse.org/openj9/job/Grinder/1473 - aix71-p8-7

**Comment by pshipton** [comment]
Trying all jdk_lang_0
https://ci.eclipse.org/openj9/job/Grinder/1475
https://ci.eclipse.org/openj9/job/Grinder/1476
https://ci.eclipse.org/openj9/job/Grinder/1477
https://ci.eclipse.org/openj9/job/Grinder/1478

**Comment by pshipton** [comment]
@gita-omr fyi

**Comment by pshipton** [comment]
@zl-wang fyi

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Release_testList_0/31 - [win2019x64-openj9-2a](https://openj9-jenkins.osuosl.org/computer/win2019x64-openj9-2a)
jdk_lang_0
java/lang/Character/CheckProp.java
```
19:18:25  java.lang.ArrayIndexOutOfBoundsException
19:18:25  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
19:18:25  	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
19:18:25  	at java.lang.Character.getType(Character.java:6978)
19:18:25  	at java.lang.Character.isUpperCase(Character.java:5554)
19:18:25  	at CheckProp.main(CheckProp.java:90)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_OMR_testList_0/271
jdk_lang_0
java/lang/Character/CheckProp.java
```
05:31:59  java.lang.ArrayIndexOutOfBoundsException
05:31:59  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
05:31:59  	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
05:31:59  	at java.lang.Character.getType(Character.java:6978)
05:31:59  	at java.lang.Character.isLowerCase(Character.java:5488)
05:31:59  	at CheckProp.main(CheckProp.java:83)
```

java/lang/Character/TestIsJavaIdentifierMethods.java
```
05:31:59  java.lang.ArrayIndexOutOfBoundsException
05:31:59  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
05:31:59  	at java.lang.CharacterDataLatin1.getType(CharacterDataLatin1.java:103)
05:31:59  	at java.lang.Character.getType(Character.java:6978)
05:31:59  	at TestIsJavaIdentifierMethods.testIsJavaIdentifierPart_int(TestIsJavaIdentifierMethods.java:89)
05:31:59  	at TestIsJavaIdentifierMethods.main(TestIsJavaIdentifierMethods.java:50)
```

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_testList_2/390/)
```
[2026-04-08T07:49:26.862Z] Running test jdk_lang_j9_0 ...
[2026-04-08T07:49:28.963Z] ===============================================
[2026-04-08T07:49:28.963Z] jdk_lang_j9_0 Start Time: Wed Apr  8 00:49:27 2026 Epoch Time (ms): 1775634567692
[2026-04-08T07:49:28.963Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
[2026-04-08T07:49:28.963Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -

[2026-04-08T07:55:40.757Z] TEST: java/lang/Character/TestIsJavaIdentifierMethods.java

[2026-04-08T07:55:40.758Z] java.lang.ArrayIndexOutOfBoundsException
[2026-04-08T07:55:40.758Z] 	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
[2026-04-08T07:55:40.758Z] 	at java.lang.CharacterDataLatin1.isJavaIdentifierPart(CharacterDataLatin1.java:113)
[2026-04-08T07:55:40.758Z] 	at java.lang.Character.isJavaIdentifierPart(Character.java:6150)
[2026-04-08T07:55:40.758Z] 	at TestIsJavaIdentifierMethods.testIsJavaIdentifierPart_int(TestIsJavaIdentifierMethods.java:100)
[2026-04-08T07:55:40.758Z] 	at TestIsJavaIdentifierMethods.main(TestIsJavaIdentifierMethods.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly_testList_1/489
jdk_lang_1 
ava/lang/Character/TestIsJavaIdentifierMethods.java
```
22:11:41  java.lang.ArrayIndexOutOfBoundsException
22:11:41  	at java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:72)
22:11:41  	at java.lang.CharacterDataLatin1.isJavaIdentifierPart(CharacterDataLatin1.java:113)
22:11:41  	at java.lang.Character.isJavaIdentifierPart(Character.java:6150)
22:11:41  	at TestIsJavaIdentifierMethods.testIsJavaIdentifierPart_int(TestIsJavaIdentifierMethods.java:100)
22:11:41  	at TestIsJavaIdentifierMethods.main(TestIsJavaIdentifierMethods.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly_testList_0/508
jdk_lang_0 
java/lang/String/NonCharacterMapping.java
```
03:17:07  java.lang.ArrayIndexOutOfBoundsException
03:17:07  	at java.base/java.lang.CharacterDataLatin1.getProperties(CharacterDataLatin1.java:74)
03:17:07  	at java.base/java.lang.CharacterDataLatin1.toUpperCase(CharacterDataLatin1.java:165)
03:17:07  	at java.base/java.lang.Character.toUpperCase(Character.java:9820)
03:17:07  	at java.base/java.lang.Character.toUpperCase(Character.java:9791)
03:17:07  	at NonCharacterMapping.main(NonCharacterMapping.java:41)
```
