### ISSUE TITLE
extended.functional MXBean tests hanging on zlinux Ubuntu18 machines

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11798]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/241
```
22:51:04  [JvmCpuMonitorMXBeanTest] [INFO]  ------------------------------------------
22:51:04  [JvmCpuMonitorMXBeanTest] [INFO]  Starting JvmCpuMonitorMXBean API tests....
22:51:04  [JvmCpuMonitorMXBeanTest] [INFO]  ------------------------------------------
22:51:04  [JvmCpuMonitorMXBeanTest] [INFO] Starting Remote Server to Monitor!
22:51:04  [JvmCpuMonitorMXBeanTest] [INFO] /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar  -Xint -Xgcpolicy:optthruput -Xnocompressedrefs  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.lock.file=/tmp/tmp3321318257212696386.lock org.openj9.test.management.RemoteMonitor 
00:08:33  Cannot contact ub18-390-1: java.lang.InterruptedException
Cancelling nested steps due to timeout
08:16:15  Sending interrupt signal to process
```
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/241
```
22:53:14  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
22:53:14  [TestOperatingSystemMXBean] [INFO]  Starting the OperatingSystemMXBean usage API tests........
22:53:14  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
22:53:14  [TestOperatingSystemMXBean] [INFO] Starting Remote Server!
22:53:14  [TestOperatingSystemMXBean] [INFO] /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false org.openj9.test.management.RemoteServer 
22:53:15  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:15  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:15  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719595204 ms.  Retry 1 after 1000 ms.
22:53:16  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:16  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:16  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719596205 ms.  Retry 2 after 1000 ms.
22:53:17  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:17  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:17  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719597206 ms.  Retry 3 after 1000 ms.
22:53:18  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:18  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:18  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719598208 ms.  Retry 4 after 1000 ms.
22:53:19  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:19  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:19  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719599209 ms.  Retry 5 after 1000 ms.
22:53:20  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:20  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:20  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719600211 ms.  Retry 6 after 1000 ms.
22:53:21  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:21  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:21  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719601212 ms.  Retry 7 after 1000 ms.
22:53:22  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:22  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:22  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719602213 ms.  Retry 8 after 1000 ms.
22:53:23  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:23  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:23  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719603215 ms.  Retry 9 after 1000 ms.
22:53:24  [TestOperatingSystemMXBean] [WARN] Connection request failed: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
22:53:24  	java.net.ConnectException: Connection refused (Connection refused)]
22:53:24  [TestOperatingSystemMXBean] [WARN] Connection failed at: 1611719604216 ms.  Retry 10 after 1000 ms.
22:53:25  FAILED: runTestOSMXBean
22:53:25  java.lang.AssertionError: !!!Test(s) couldn't be started in remote mode: Connection setup failed !!! expected [true] but found [false]
22:53:25  	at org.testng.Assert.fail(Assert.java:96)
22:53:25  	at org.testng.Assert.failNotEquals(Assert.java:776)
22:53:25  	at org.testng.Assert.assertTrue(Assert.java:44)
22:53:25  	at org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean(TestOperatingSystemMXBean.java:155)
22:53:25  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:53:25  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:53:25  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:53:25  	at java.lang.reflect.Method.invoke(Method.java:498)
22:53:25  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
22:53:25  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
22:53:25  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
22:53:25  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
22:53:25  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
22:53:25  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
22:53:25  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
22:53:25  	at org.testng.TestRunner.run(TestRunner.java:505)
22:53:25  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
22:53:25  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
22:53:25  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
22:53:25  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
22:53:25  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
22:53:25  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
22:53:25  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
22:53:25  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
22:53:25  	at org.testng.TestNG.runSuites(TestNG.java:1049)
22:53:25  	at org.testng.TestNG.run(TestNG.java:1017)
22:53:25  	at org.testng.TestNG.privateMain(TestNG.java:1354)
22:53:25  	at org.testng.TestNG.main(TestNG.java:1323)
...
22:53:36  [JvmCpuMonitorMXBeanTest] [INFO]  ------------------------------------------
22:53:36  [JvmCpuMonitorMXBeanTest] [INFO]  Starting JvmCpuMonitorMXBean API tests....
22:53:36  [JvmCpuMonitorMXBeanTest] [INFO]  ------------------------------------------
22:53:36  [JvmCpuMonitorMXBeanTest] [INFO] Starting Remote Server to Monitor!
22:53:36  [JvmCpuMonitorMXBeanTest] [INFO] /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar  -Xjit -Xgcpolicy:optthruput -Xnocompressedrefs  -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.lock.file=/tmp/tmp8798617851963710187.lock org.openj9.test.management.RemoteMonitor 
00:08:22  Cannot contact ub18-390-2: java.lang.InterruptedException
Cancelling nested steps due to timeout
08:14:39  Sending interrupt signal to process
```

**Comment by pshipton** [comment]
@jdekonin this seems network related, is it related to the machine configuration as done for https://github.com/eclipse/openj9/issues/11781#issuecomment-767564788?

We're also having this problem https://github.com/eclipse/openj9/issues/11795 which I thought was code (although no changes made sense to break this). I'll re-check my conclusions.

**Comment by pshipton** [comment]
Disabling the machines until this can be resolved.

**Comment by pshipton** [comment]
Another one https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Nightly_testList_1/244
Jenkins was restarted and the machines were re-enabled. Disabled them again.

**Comment by jdekonin** [comment]
Machine issues apparently resolved.  I've rebooted them as suggested and enabled for use.

I also launched a grinder on ub18-390-1 to verify.
https://ci.eclipse.org/openj9/job/Grinder/1486/console

**Comment by jdekonin** [comment]
Grinder passes, so looking good again.
