### ISSUE TITLE
JDK17 Windows : testRASAPI_0_FAILED due to The (dump) file exists.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11800]
Failure link
------------

From an internal build `Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly/377`:
```
23:37:40  openjdk version "17-internal" 2021-09-14
23:37:40  OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.buildjdknextx86-64windowsnightly)
23:37:40  Eclipse OpenJ9 VM (build master-d132a6b28b5, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20210125_449 (JIT enabled, AOT enabled)
23:37:40  OpenJ9   - d132a6b28b5
23:37:40  OMR      - b38b0b77c99
23:37:40  JCL      - fba167cf63c based on jdk-17+5)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test testRASAPI_0 ...
===============================================
testRASAPI_0 Start Time: Tue Jan 26 01:29:59 2021 Epoch Time (ms): 1611642599888
variation: NoOptions
JVM_OPTIONS:  
Buildfile: C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\test.xml

[test]     [junit] JVMDUMP010I Java dump written to /STDOUT/
     [test]     [junit] JVMDUMP034I User requested Java dump using 'C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\javacore.testJavaDumpWithSameFile.1611642614599.txt' through com.ibm.jvm.Dump.javaDumpToFile
     [test]     [junit] JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\javacore.testJavaDumpWithSameFile.1611642614599.txt
     [test]     [junit] JVMDUMP030W Cannot write dump to file C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\javacore.testJavaDumpWithSameFile.1611642614599.txt: (80) The file exists.
     [test]     [junit] JVMDUMP034I User requested Java dump using 'C:\Temp\javacore.testJavaDumpWithSameFile.1611642614599.txt' through com.ibm.jvm.Dump.javaDumpToFile
     [test]     [junit] JVMDUMP010I Java dump written to C:\Temp\javacore.testJavaDumpWithSameFile.1611642614599.txt
     [test]     [junit] com.ibm.jvm.InvalidDumpOptionException: Error in dump options.
     [test]     [junit] reach here
     [test]     [junit] JVMDUMP030W Cannot write dump to file C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\javacore.testJavaDumpWithSameFile.1611642614599.txt: (80) The file exists.

BUILD FAILED
C:\Users\jenkins\workspace\Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly_testList_1\jvmtest\functional\RasapiTest\test.xml:52: Timeout: killed the sub-process

Total time: 15 minutes 1 second

testRASAPI_0_FAILED
```

Need determine if the test removes existing dump files before starting the run, or the cleanup failed due to machine issue.

**Comment by JasonFengJ9** [comment]
It appears in JDK8 ibuild across platforms
```
[test]     [junit] NULL           ---------------------- END OF DUMP -------------------------------------
     [test]     [junit] JVMDUMP010I Java dump written to /bluebird/builds/bld_464579/jvmtest/test/SE80/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1611811334200.txt
     [test]     [junit] JVMDUMP030W Cannot write dump to file /bluebird/builds/bld_464579/jvmtest/test/SE80/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1611811334200.txt: Do not specify an existing file.
     [test]     [junit] JVMDUMP034I User requested Java dump using '/tmp/javacore.testJavaDumpWithSameFile.1611811334200.txt' through com.ibm.jvm.Dump.javaDumpToFile
     [test]     [junit] JVMDUMP010I Java dump written to /tmp/javacore.testJavaDumpWithSameFile.1611811334200.txt
     [test]     [junit] JVMDUMP030W Cannot write dump to file /bluebird/builds/bld_464579/jvmtest/test/SE80/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1611811334200.txt: Do not specify an existing file.
     [test]     [junit] com.ibm.jvm.InvalidDumpOptionException: Error in dump options.
```

**Comment by pshipton** [comment]
@llxia seems this test isn't working.

**Comment by llxia** [comment]
The test passed in Test_openjdkNext_j9_extended.functional_x86-64_windows_Nightly/376 and it worked in my Grinder: Grinder/13571/

**Comment by llxia** [comment]
@OscarQQ is vmfarm failure a known issue? If so, could you exclude the test on vmfarm? Thanks

**Comment by pshipton** [comment]
Another different failure (hang) of testRASAPI_0 in OpenJ9 jdk16 testing https://github.com/eclipse/openj9/issues/11821

**Comment by llxia** [comment]
@OscarQQ Could you exclude the test on JDK16 and JDK17? The problem seems intermittent.

**Comment by JasonFengJ9** [comment]
A slightly different failure at an internal ibuild `466720` (`job_output.php?id=671244631`) which might be due to the existing dump files.
```
     [test]     [junit] 	FAILED
     [test]     [junit] Failed to find expected number of files in /bluebird/builds/bld_466720/jvmtest/test/SE80/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, test.xml, junit4.jar, autoGen.mk, junitvmwatcher1791756860094546621.properties, junit7825584026004656005.properties, heap.testTriggerDumpClassicHeapToFile.1614744756746.txt, junitvmwatcher7209927740504311610.properties, junit3118576621082231881.properties, core.20210302.231153.11927554.0023.dmp] expected:<7> but was:<10>
     [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /bluebird/builds/bld_466720/jvmtest/test/SE80/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, test.xml, junit4.jar, autoGen.mk, junitvmwatcher1791756860094546621.properties, junit7825584026004656005.properties, heap.testTriggerDumpClassicHeapToFile.1614744756746.txt, junitvmwatcher7209927740504311610.properties, junit3118576621082231881.properties, core.20210302.231153.11927554.0023.dmp] expected:<7> but was:<10>
     [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpX(DumpAPITriggerTests.java:309)
     [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpClassicHeapToFile(DumpAPITriggerTests.java:150)
     [test]     [junit] 
     [test] 
     [test] BUILD FAILED
     [test] /bluebird/builds/bld_466720/jvmtest/test/SE80/functional/RasapiTest/test.xml:77: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
```

**Comment by pshipton** [comment]
The test was excluded so it shouldn't run starting in the next build.

**Comment by OscarQQ** [comment]
related: runtimes/tooling/pull/867 this pr is to disable testRASAPI on vmfarm, still needs one pending approval

**Comment by pshipton** [comment]
Ah sorry, confused it with testOSGiTCK https://github.com/eclipse/openj9/issues/12072.

I poked @llxia in the tooling issue.

**Comment by llxia** [comment]
I merged the excludes in the tooling repo.

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_extended.functional_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/975/)
```
[2025-06-02T17:24:00.793Z] variation: NoOptions
[2025-06-02T17:24:00.793Z] JVM_OPTIONS:  

[2025-06-02T17:24:06.299Z]      [test]     [junit] JVMDUMP030W Cannot write dump to file /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/jvmtest/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1748885043743.txt: File exists
[2025-06-02T17:24:06.299Z]      [test]     [junit] JVMDUMP034I User requested Java dump using '/tmp/javacore.testJavaDumpWithSameFile.1748885043743.txt' through com.ibm.jvm.Dump.javaDumpToFile

[2025-06-02T17:24:10.715Z]      [test]     [junit] JVMDUMP030W Cannot write dump to file /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/jvmtest/functional/RasapiTest/Snap.testSnapDumpWithSameFile.1748885043748.trc: File exists
[2025-06-02T17:24:10.715Z]      [test]     [junit] JVMDUMP034I User requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_testList_0/jvmtest/functional/RasapiTest/core.20250602.102410.28399.0023.dmp' through com.ibm.jvm.Dump.SystemDump
[2025-06-02T17:24:18.294Z]      [test]     [junit] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.28432.  Review the manual for the external program to find where the core dump is written and ensure the program does not truncate it.

[2025-06-02T17:24:22.194Z] testRASAPI_0_FAILED
```

[5x internal grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/51312/)

**Comment by JasonFengJ9** [comment]
[openjdk11_j9_extended.functional_s390x_linux_openjceplus](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/2/)
```
[2025-06-20T20:24:06.740Z] variation: NoOptions
[2025-06-20T20:24:06.740Z] JVM_OPTIONS:   -Djava.security.properties=/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/aqa-tests/config/openjceplus/jdk/java.security

[2025-06-20T20:24:12.700Z]      [test]     [junit] JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1750450947046.txt
[2025-06-20T20:24:12.700Z]      [test]     [junit] JVMDUMP030W Cannot write dump to file /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest/javacore.testJavaDumpWithSameFile.1750450947046.txt: File exists

```

**Comment by llxia** [comment]
The above 5x Grinder link is expired. Rerun 5x Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/52216/

Update: pass rate 3/5. DumpAPITriggerTests failed - `Failed to find expected number of files in /home/jenkins/workspace/Grinder_iteration_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher8765012842711470689.properties, junit6018803838343712984.properties] expected:<6> but was:<5>`

```
00:10:00.576       [test]     [junit] 	FAILED
00:10:00.576       [test]     [junit] Failed to find expected number of files in /home/jenkins/workspace/Grinder_iteration_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher8765012842711470689.properties, junit6018803838343712984.properties] expected:<6> but was:<5>
00:10:00.576       [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Grinder_iteration_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher8765012842711470689.properties, junit6018803838343712984.properties] expected:<6> but was:<5>
00:10:00.576       [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerBadDumpX(DumpAPITriggerTests.java:371)
00:10:00.576       [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpBadAgentNoOpts(DumpAPITriggerTests.java:125)
00:10:00.576       [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:10:00.576       [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:10:00.576       [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:10:00.576       [test]     [junit] 
00:10:00.576       [test] 
00:10:00.576       [test] BUILD FAILED
00:10:00.576       [test] /home/jenkins/workspace/Grinder_iteration_1/jvmtest/functional/RasapiTest/test.xml:78: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
```

**Comment by llxia** [comment]
The real failure is due to `Test com.ibm.jvm.ras.tests.DumpAPITriggerTests` - `expected:<6> but was:<5>`, not `Cannot write dump to file ... File exists`. `Cannot write dump to file ... File exists` message can be found in the passed job as well (in both the passed [openjceplus test build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/1/consoleText) and [regular test build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_testList_1/907/consoleText)).

[failed openjceplus test build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/2/consoleText)
```
[2025-06-20T20:24:34.454Z]      [test]     [junit] 	FAILED
[2025-06-20T20:24:34.454Z]      [test]     [junit] Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher16981527957121656873.properties, junit15420372418077558963.properties] expected:<6> but was:<5>
[2025-06-20T20:24:34.454Z]      [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher16981527957121656873.properties, junit15420372418077558963.properties] expected:<6> but was:<5>
[2025-06-20T20:24:34.454Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpX(DumpAPITriggerTests.java:306)
[2025-06-20T20:24:34.454Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.doTestTriggerDumpNoOpts(DumpAPITriggerTests.java:249)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITriggerTests.testTriggerDumpConsoleNoOpts(DumpAPITriggerTests.java:111)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 
[2025-06-20T20:24:34.455Z]      [test]     [junit] -------- Console dump --------
[2025-06-20T20:24:34.455Z]      [test]     [junit] Thread=main (000003FF8C01E100) Status=Running
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/Dump.triggerDumpsImpl(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; (Native Method)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/Dump.triggerDump(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; (Dump.java:575)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/Dump.triggerDump(Ljava/lang/String;)Ljava/lang/String; (Dump.java:567)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/ras/tests/DumpAPITriggerTests.doTestTriggerDumpX(Ljava/lang/String;Lcom/ibm/jvm/ras/tests/DumpAPISuite$DumpType;)V (DumpAPITriggerTests.java:280)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/ras/tests/DumpAPITriggerTests.doTestTriggerDumpNoOpts(Ljava/lang/String;Lcom/ibm/jvm/ras/tests/DumpAPISuite$DumpType;)V (DumpAPITriggerTests.java:249)
[2025-06-20T20:24:34.455Z]      [test]     [junit] 	at com/ibm/jvm/ras/tests/DumpAPITriggerTests.testTriggerDumpConsoleNoOpts()V (DumpAPITriggerTests.java:111)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Native Method)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at jdk/internal/reflect/NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (NativeMethodAccessorImpl.java:62)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (DelegatingMethodAccessorImpl.java:43)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (Method.java:572)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestCase.runTest()V (TestCase.java:168)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestCase.runBare()V (TestCase.java:134) (Compiled Code)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestResult$1.protect()V (TestResult.java:110)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestResult.runProtected(Ljunit/framework/Test;Ljunit/framework/Protectable;)V (TestResult.java:128)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestResult.run(Ljunit/framework/TestCase;)V (TestResult.java:113)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestCase.run(Ljunit/framework/TestResult;)V (TestCase.java:124)
[2025-06-20T20:24:34.456Z]      [test]     [junit] 	at junit/framework/TestSuite.runTest(Ljunit/framework/Test;Ljunit/framework/TestResult;)V (TestSuite.java:243)
[2025-06-20T20:24:34.457Z]      [test]     [junit] 	at junit/framework/TestSuite.run(Ljunit/framework/TestResult;)V (TestSuite.java:238)
[2025-06-20T20:24:34.457Z]      [test]     [junit] 	at org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunner.run()V (JUnitTestRunner.java:535)
[2025-06-20T20:24:34.457Z]      [test]     [junit] 	at org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunner.launch(Lorg/apache/tools/ant/taskdefs/optional/junit/JUnitTest;[Ljava/lang/String;ZZZZZZ)I (JUnitTestRunner.java:1197)
[2025-06-20T20:24:34.457Z]      [test]     [junit] 	at org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunner.main([Ljava/lang/String;)V (JUnitTestRunner.java:1042)
[2025-06-20T20:24:34.457Z]      [test]     [junit] 
...
[2025-06-20T20:24:34.461Z]      [test] BUILD FAILED
[2025-06-20T20:24:34.461Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest/test.xml:78: Test com.ibm.jvm.ras.tests.DumpAPITriggerTests failed
[2025-06-20T20:24:34.461Z]      [test] 
[2025-06-20T20:24:34.461Z]      [test] Total time: 24 seconds
[2025-06-20T20:24:34.461Z] 
[2025-06-20T20:24:34.461Z] BUILD FAILED
[2025-06-20T20:24:34.461Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_s390x_linux_openjceplus_testList_1/jvmtest/functional/RasapiTest/test.xml:50: Java returned: 1
[2025-06-20T20:24:34.461Z] 
[2025-06-20T20:24:34.461Z] Total time: 26 seconds
[2025-06-20T20:24:34.461Z] -----------------------------------
[2025-06-20T20:24:34.461Z] testRASAPI_0_FAILED
[2025-06-20T20:24:34.461Z] -----------------------------------
```

Test code: https://github.com/eclipse-openj9/openj9/blob/f5ad9f21f1b9d372e5c793f02e90e25b69ba39b2/test/functional/RasapiTest/src/com/ibm/jvm/ras/tests/DumpAPITriggerTests.java#L304-L310

**Comment by llxia** [comment]
I [printed the files before](https://github.com/llxia/openj9/commit/9602c1c3dd6e4efd4fe146d5d08b0d50a7489306).

20x Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/52248/

failed child iteration: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_15/154/consoleFull

- Before
```
00:04:29.800       [test]     [junit] found beforeFileNames:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher1835571377149227355.properties, junit17702131132141183594.properties]
````

- After
```
00:04:29.802       [test]     [junit] junit.framework.AssertionFailedError: Failed to find expected number of files in /home/jenkins/workspace/Grinder_iteration_15/jvmtest/functional/RasapiTest , found:[com.ibm.jvm.ras.tests.jar, junit4.jar, test.xml, junitvmwatcher1835571377149227355.properties, junit17702131132141183594.properties, javacore.testTriggerDumpJavaToFile.1751556669093.txt, omrvmem_002283662_wfvWeM] expected:<6> but was:<7>
```

We have 2 extra files `javacore.testTriggerDumpJavaToFile.1751556669093.txt, omrvmem_002283662_wfvWeM`. I think `javacore.testTriggerDumpJavaToFile.1751556669093.txt` is expected and `omrvmem_002283662_wfvWeM` is the extra that caused the failure.

**Comment by mpirvu** [comment]
@llxia The pattern used to find RAS files is `String dumpFilePattern = ".*\\.*";`
This matches even files without a `.` in their file name and thus the `omrvmem` file.
Maybe we should change the pattern to `".*\\..*"` or `".*\\.\\w+"`

**Comment by llxia** [comment]
@LongyuZhang could you try to update the test? Thanks
