### ISSUE TITLE
cmdLineTester_GCCheck test failure

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#11811]
Reported first in https://github.com/eclipse/openj9/issues/11801#issuecomment-769029469.
```
23:37:40  openjdk version "11.0.10-internal" 2021-01-19
23:37:40  OpenJDK Runtime Environment (build 11.0.10-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
23:37:40  Eclipse OpenJ9 VM (build master-00e156b6c95, JRE 11 AIX ppc64-64-Bit Compressed References 20210127_713 (JIT enabled, AOT enabled)
23:37:40  OpenJ9   - 00e156b6c95
23:37:40  OMR      - 94012c0f8a7
23:37:40  JCL      - f7475ea97ee based on jdk-11.0.10+9)

===============================================
Running test cmdLineTester_GCCheck_1 ...
===============================================
cmdLineTester_GCCheck_1 Start Time: Thu Jan 28 00:21:52 2021 Epoch Time (ms): 1611811312093
variation: Mode610
JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 
Parsing exclude list...
  add excludes for [all]
  add excludes for [aix_ppc-64_cr]
DONE in 0 ms.

Testing: Run gccheck
Test start time: 2021/01/28 00:22:23 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/openjdkbinary/j2sdk-image/lib/ddr/j9ddr.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/functional/IBM_Internal/cmdLineTests_IBM_Internal/gcCheck/caffeine.jar com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive j9core.dmp
Time spent starting: 24 milliseconds
Time spent executing: 9454 milliseconds
Test result: FAILED
Output from test:
 [ERR] Exception in thread "main" java.lang.IllegalAccessError: com/ibm/j9ddr/IVMData is not visible
 [ERR] 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:479)
 [ERR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:440)
 [ERR] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:392)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.J9DDRClassLoader.findClass(J9DDRClassLoader.java:137)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.J9DDRClassLoader.loadClass(J9DDRClassLoader.java:206)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.J9DDRClassLoader.loadClassRelativeToStream(J9DDRClassLoader.java:195)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.J9DDRClassLoader.getIVMData(J9DDRClassLoader.java:259)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.VMDataFactory.getVMData(VMDataFactory.java:213)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.VMDataFactory.getAllVMData(VMDataFactory.java:143)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.VMDataFactory.getVMData(VMDataFactory.java:106)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.locateRuntimes(DDRInteractive.java:387)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.locateRuntimes(DDRInteractive.java:371)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.<init>(DDRInteractive.java:273)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.<init>(DDRInteractive.java:258)
 [ERR] 	at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.main(DDRInteractive.java:282)
>> Success condition was not found: [Output match: Checking HEAP...done]
>> Failure condition was not found: [Output match: gc check]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was found: [Output match: Exception]

cmdLineTester_GCCheck_1_FAILED
```

**Comment by keithc-ca** [comment]
@JasonFengJ9 Can you please share a link for the build that yielded the failure in the description?
Looking at https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_ppc64_aix/2520/ (which is a build of the same SHAs), everything passed.

**Comment by keithc-ca** [comment]
It would seem to be https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/234 which concludes:
```
[2021-01-28T07:53:43.483Z] TOTAL: 156   EXECUTED: 90   PASSED: 90   FAILED: 0   DISABLED: 3   SKIPPED: 63
[2021-01-28T07:53:43.483Z] ALL TESTS PASSED
```

**Comment by pshipton** [comment]
job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly/593/ on the internal server.

**Comment by keithc-ca** [comment]
The internal build is running an obsolete copy of the tests.

**Comment by JasonFengJ9** [comment]
> The internal build is running an obsolete copy of the tests.

Are the tests/pipeline updated by any chance?
