### ISSUE TITLE
substring error exception could be more useful

### ISSUE THREAD

**Issue by pwagland** [eclipse/openj9#11833]
Java -version output
--------------------

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20201023_788 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)

Summary of problem
------------------

Using jshell:

```
jshell> "test".substring(0,1000);
|  Exception java.lang.StringIndexOutOfBoundsException: String index out of range: 0
|        at String.substring (String.java:2655)
|        at (#1:1)
```

The index `0` _isn't_ out of range. It should say:
```
jshell> "test".substring(0,1000);
|  Exception java.lang.StringIndexOutOfBoundsException: String index out of range: 1000
|        at String.substring (String.java:2655)
|        at (#1:1)
```

Or even better do the same as base Java:
```
jshell> "test".substring(0,1000)
|  Exception java.lang.StringIndexOutOfBoundsException: begin 0, end 1000, length 4
|        at String.checkBoundsBeginEnd (String.java:3319)
|        at String.substring (String.java:1874)
|        at (#1:1)
```

The issue is that for any out of bounds character https://github.com/eclipse/openj9/blob/0ad4ed91031ecc8d8daa16dac4d9a484c78747b2/jcl/src/java.base/share/classes/java/lang/String.java#L2770

the code just throws an exception and blames the begin https://github.com/eclipse/openj9/blob/0ad4ed91031ecc8d8daa16dac4d9a484c78747b2/jcl/src/java.base/share/classes/java/lang/String.java#L2779

**Comment by sharon-wang** [comment]
I can take a look at this.

**Comment by sharon-wang** [comment]
Ran a simple test program with the following String methods:
```
String s = "test";
char[] charData = new char[]{};
byte[] byteData = new byte[]{};

s.substring(0, 1000);
s.getChars(0, 1000, charData, 0);
s.getChars(0, 3, charData, 1000);
s.getBytes(0, 1000, byteData, 0);
s.getBytes(0, 3, byteData, 1000);
```

### OpenJ9 Output
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.String.substring(String.java:2663)
	at Main.main(Main.java:10)
java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.getChars(String.java:1863)
	at Main.main(Main.java:18)
java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.getChars(String.java:1863)
	at Main.main(Main.java:24)
java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.getBytes(String.java:1820)
	at Main.main(Main.java:32)
java.lang.StringIndexOutOfBoundsException
	at java.base/java.lang.String.getBytes(String.java:1820)
	at Main.main(Main.java:38)
```

### Hotspot Output
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 1000, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at Main.main(Main.java:10)
java.lang.StringIndexOutOfBoundsException: begin 0, end 1000, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.getChars(String.java:872)
	at Main.main(Main.java:18)
java.lang.StringIndexOutOfBoundsException: offset 1000, count 3, length 0
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3736)
	at java.base/java.lang.String.getChars(String.java:873)
	at Main.main(Main.java:24)
java.lang.StringIndexOutOfBoundsException: begin 0, end 1000, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.getBytes(String.java:926)
	at Main.main(Main.java:32)
java.lang.StringIndexOutOfBoundsException: offset 1000, count 3, length 0
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3736)
	at java.base/java.lang.String.getBytes(String.java:928)
	at Main.main(Main.java:38)
```

We actually have the [`checkBoundsOffCount()`](https://github.com/eclipse/openj9/blob/8e6e103bb9b626ec6f92755985c2944e92c3f6f5/jcl/src/java.base/share/classes/java/lang/String.java#L448-L454) and [`checkBoundsBeginEnd()`](https://github.com/eclipse/openj9/blob/8e6e103bb9b626ec6f92755985c2944e92c3f6f5/jcl/src/java.base/share/classes/java/lang/String.java#L3972-L3977) methods in OpenJ9, but we're not using them. Not sure if there's a particular reason why -- maybe something performance related?

**Comment by sharon-wang** [comment]
Aside from `String`, from some simple testing it also looks like we have some missing `StringIndexOutOfBoundsException()` message info for `StringBuilder` and `StringBuffer`, in comparison to the RI.

@fjeremic Maybe you have some insight into why we're not using `checkBoundsOffCount()` and `checkBoundsBeginEnd()` in our implementation?

**Comment by fjeremic** [comment]
> @fjeremic Maybe you have some insight into why we're not using `checkBoundsOffCount()` and `checkBoundsBeginEnd()` in our implementation?

Likely performance related. We can start using them and measure, or teach the JIT to always inline such methods.

**Comment by sharon-wang** [comment]
For the `String` class, there's a difference between the RI output for JDK 8 and JDK 11.

For example, if we have
```
"test".substring(0, 1000);
```

RI JDK 8
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1000
```

RI JDK 11
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 1000, length 4
```

@tajila Do we want to match the RI JDK 11 exception output in both JDK 8 and 11 (contains more useful info), or do we want to match our JDK 11 to the RI and match the RI's more minimal info in JDK 8 for our 8?

Additionally, the `StringBuffer` and `StringBuilder` classes are ifdeffed with `/*[INCLUDE-IF Sidecar16 & !Sidecar19-SE]*/`, which means we're using the OpenJDK versions of those classes, except for JDK 8. Some of our exception output for JDK 8 for `StringBuffer` and `StringBuilder` doesn't match the RI so I will be addressing those, but any fixes won't impact JDK 11+, which is already using OpenJDK.

**Comment by tajila** [comment]
> Do we want to match the RI JDK 11 exception output in both JDK 8 and 11 (contains more useful info), or do we want to match our JDK 11 to the RI and match the RI's more minimal info in JDK 8 for our 8?

@sharon-wang 
Making both JDK 11 and 8 similar is my preference. However, we first need to make sure there are no tests in JDK8 that depend on a certain error message format

**Comment by sharon-wang** [comment]
> Making both JDK 11 and 8 similar is my preference. However, we first need to make sure there are no tests in JDK8 that depend on a certain error message format

Sounds good. From a quick search through OpenJ9 tests, there's no specific format expected for the exception message -- we only care that the exception is thrown in some test cases. Running the String tests on my changes should confirm this.

**Comment by tajila** [comment]
@JasonFengJ9 will be investigating this
