### ISSUE TITLE
TestJlmRemoteThreadNoAuth_1 hang in socketRead on zlinux ub18 machine

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11875]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_mixed_Nightly_testList_0/8/
TestJlmRemoteThreadNoAuth_1
ub18-390-2
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_sanity.system_s390x_linux_mixed_Nightly_testList_0/8/system_test_output.tar.gz
```
STF 08:01:44.097 - Heartbeat: Process CL1 is still running
STF 08:01:45.099 - **FAILED** Process CL1 has timed out
STF 08:01:45.099 - Collecting dumps for: CL1
```
Seems to be hung in socketRead
```
3XMTHREADINFO      "main" J9VMThread:0x0000000000C6A700, omrthread_t:0x000003FFA801DA50, java/lang/Thread:0x000000000D4CB838, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x29EA, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000000)
3XMTHREADINFO2            (native stack address range from:0x000003FFAC480000, to:0x000003FFACC80000, size:0x800000)
3XMCPUTIME               CPU usage total: 1.651101691 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/net/SocketInputStream.socketRead0(Native Method)
4XESTACKTRACE                at java/net/SocketInputStream.socketRead(SocketInputStream.java:115)
4XESTACKTRACE                at java/net/SocketInputStream.read(SocketInputStream.java:168)
4XESTACKTRACE                at java/net/SocketInputStream.read(SocketInputStream.java:140)
4XESTACKTRACE                at java/io/BufferedInputStream.fill(BufferedInputStream.java:252)
4XESTACKTRACE                at java/io/BufferedInputStream.read(BufferedInputStream.java:271(Compiled Code))
5XESTACKTRACE                   (entered lock: java/io/BufferedInputStream@0x000000000D6491C0, entry count: 1)
4XESTACKTRACE                at java/io/DataInputStream.readByte(DataInputStream.java:270(Compiled Code))
4XESTACKTRACE                at sun/rmi/transport/StreamRemoteCall.executeCall(StreamRemoteCall.java:240(Compiled Code))
4XESTACKTRACE                at sun/rmi/server/UnicastRef.invoke(UnicastRef.java:164(Compiled Code))
4XESTACKTRACE                at jdk/jmx/remote/internal/rmi/PRef.invoke(Bytecode PC:11(Compiled Code))
4XESTACKTRACE                at javax/management/remote/rmi/RMIConnectionImpl_Stub.invoke(Bytecode PC:39(Compiled Code))
4XESTACKTRACE                at javax/management/remote/rmi/RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1021(Compiled Code))
4XESTACKTRACE                at com/sun/jmx/mbeanserver/MXBeanProxy$InvokeHandler.invoke(MXBeanProxy.java:150(Compiled Code))
4XESTACKTRACE                at com/sun/jmx/mbeanserver/MXBeanProxy.invoke(MXBeanProxy.java:167(Compiled Code))
4XESTACKTRACE                at javax/management/MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258(Compiled Code))
4XESTACKTRACE                at com/sun/proxy/$Proxy3.dumpAllThreads(Bytecode PC:28)
4XESTACKTRACE                at net/adoptopenjdk/test/jlm/resources/ThreadData.writeData(ThreadData.java:144)
4XESTACKTRACE                at net/adoptopenjdk/test/jlm/remote/ThreadProfiler.getStatsViaProxy(ThreadProfiler.java:135)
4XESTACKTRACE                at net/adoptopenjdk/test/jlm/remote/ThreadProfiler.main(ThreadProfiler.java:97)
```

**Comment by pshipton** [comment]
@jdekonin hopefully there aren't still network problems on the zlinux Ubuntu 18 machines.

**Comment by jdekonin** [comment]
Not that I am aware of.  I did grinders on the failing jobs in the previous issues and I am pretty certain they all passed.

**Comment by jdekonin** [comment]
system.special was aborted due to timeout but it didn't look healthy - #11835
functional.extended passes - #11798

**Comment by pshipton** [comment]
I'm hoping this was just some network blip, will see if it occurs again in subsequent builds.
