### ISSUE TITLE
OJDK MH: IllegalArgumentException not thrown

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11927]
### Error

```
FAILED: test_RevealDirect_TargetVarargsAdaptor
java.lang.AssertionError:
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@aa4ec875(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_1/openjdk-tests/TKG/lib/testng.jar)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@aa4ec875(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_1/openjdk-tests/TKG/lib/testng.jar)
        at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33) from jdk.internal.loader.ClassLoaders$AppClassLoader@aa4ec875(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_1/openjdk-tests/TKG/lib/testng.jar)
        at org.openj9.test.java.lang.invoke.Test_MethodHandleInfo.test_RevealDirect_TargetVarargsAdaptor(Test_MethodHandleInfo.java:667) from jdk.internal.loader.ClassLoaders$AppClassLoader@aa4ec875(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

`Test_MethodHandleInfo.test_RevealDirect_TargetVarargsAdaptor` expects an `IllegalArgumentException` to be thrown. With OJDK MHs enabled in OpenJ9, the `IllegalArgumentException` is not thrown.

### Failing Test Targets

1. `JCL_Test_*` (multiple variants with different JVM arguments) 
    - `test_RevealDirect_TargetVarargsAdaptor`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

**Comment by babsingh** [comment]
Needs to be investigated.

This should be tagged with the `project:MH` label.

**Comment by fengxue-IS** [comment]
I will look into this

**Comment by fengxue-IS** [comment]
Verified against RI behavior with following micro-test:
```

import java.lang.invoke.*;
import java.lang.invoke.MethodHandles.Lookup;
import static java.lang.invoke.MethodHandles.*;
import static java.lang.invoke.MethodType.*;

public class Test {
    public String publicNotVarargs(Object o) { return "publicVarargsMethod"; }

    public static void main(String[] args) throws Throwable {
        MethodHandle mh = lookup().findVirtual(Test.class, "publicNotVarargs", methodType(String.class, Object.class));
        mh = mh.asVarargsCollector(Object[].class);
        lookup().revealDirect(mh);
    }
}
```
OpenJ9 MH & OpenJDK Java11 both throw `java.lang.IllegalArgumentException: not a direct method handle`
OpenJDK 16 passed without any error

as this error is thrown by JCL code from `revealDirect()` call, I will test if OpenJ9 with OJDK MH Java 11 throws the same error as OpenJDK 11 to confirm this as JCL changes.
If so, we should investigate which result matches the spec

**Comment by tajila** [comment]
Ya I think short term, we should disable 16+. But we should try to update the test so it can detect between 11 and 16+ so we can properly test the required behaviour on both of those levels.

**Comment by JasonFengJ9** [comment]
`java.security.AccessControlException` not thrown at `Test_AccessController.test_doPrivilegedFrameStackWalking()` as per https://github.com/eclipse-openj9/openj9/pull/12604#issuecomment-840088458, the test in question is https://github.com/eclipse-openj9/openj9/blob/e80ab0f032fc4c2de3be817573f1fd4dda591a6f/test/functional/Java8andUp/src/org/openj9/test/java/security/Test_AccessController.java#L386-L395

Before https://github.com/eclipse-openj9/openj9/pull/12604, the test throws a different exception `AccessControlException: Access denied ("java.lang.RuntimePermission" "getProtectionDomain")` like https://github.com/eclipse-openj9/openj9/issues/12600, it doesn't throw an expected exception `AccessControlException: access denied ("java.util.PropertyPermission" "java.home" "read")`.

This is due to removal of `java.lang.invoke.SecurityFrame`
https://github.com/eclipse-openj9/openj9/blob/a6bf623d7dcbfcc727980536fb75c206e9dd287d/jcl/src/java.base/share/classes/java/lang/invoke/SecurityFrame.java#L25-L31

**Comment by fengxue-IS** [comment]
testcase disabled for OJDK MH builds, marking low prio
Todo: update testcase such that `asVarargsCollector` call will always generate a BoundMethodHandle
