### ISSUE TITLE
OJDK MH: InvocationTargetException not thrown

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11928]
### Errors

An `InvocationTargetException` is not thrown by the below tests when OJDK MHs are enabled in OpenJ9:
```
FAILED: test_MHInstanceFieldGetter2
java.lang.AssertionError: InvocationTargetException expected
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.security.Test_MHLoaderConstraints.test_MHInstanceFieldGetter2(Test_MHLoaderConstraints.java:73) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)

FAILED: test_MHInstanceFieldSetter2
java.lang.AssertionError: InvocationTargetException expected
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.security.Test_MHLoaderConstraints.test_MHInstanceFieldSetter2(Test_MHLoaderConstraints.java:113) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)

FAILED: test_MHStaticFieldGetter2
java.lang.AssertionError: InvocationTargetException expected
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.security.Test_MHLoaderConstraints.test_MHStaticFieldGetter2(Test_MHLoaderConstraints.java:153) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)

FAILED: test_MHStaticFieldSetter2
java.lang.AssertionError: InvocationTargetException expected
	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.java.security.Test_MHLoaderConstraints.test_MHStaticFieldSetter2(Test_MHLoaderConstraints.java:193) from jdk.internal.loader.ClassLoaders$AppClassLoader@df131ed8(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_0/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

### Expected Behaviour from `MethodHandleNatives.resolve`

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at mhtest.Test.test1(Test.java:25)
	at mhtest.Test.main(Test.java:19)
Caused by: java.lang.IllegalAccessException: no such field: mhtest.Parent.instanceField/mhtest.Dummy/getField
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:974)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3642)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3020)
	at mhtest.ChildMHLookupField.instanceFieldGetter2(ChildMHLookupField.java:32)
	... 6 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "instanceField" of type mhtest.Dummy, the class loader mhtest.ClassLoaderOne @251a69d7 of the current class, mhtest.ChildMHLookupField, and the class loader mhtest.ClassLoaderTwo @15db9742 for the field's defining class, mhtest.Parent, have different Class objects for type mhtest.Dummy (mhtest.ChildMHLookupField is in unnamed module of loader mhtest.ClassLoaderOne @251a69d7, parent loader 'app'; mhtest.Parent is in unnamed module of loader mhtest.ClassLoaderTwo @15db9742, parent loader 'app')
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1087)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1116)
	... 9 more
```

### OpenJ9's Current Behaviour

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at mhtest.Test.test1(Test.java:25)
	at mhtest.Test.main(Test.java:19)
Caused by: java.lang.IllegalAccessException: loading constraint violation: Lmhtest/Dummy; not visible from mhtest/ChildMHLookupField
	at java.base/java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:68)
	at java.base/java.lang.invoke.FieldHandle.<init>(FieldHandle.java:35)
	at java.base/java.lang.invoke.FieldGetterHandle.<init>(FieldGetterHandle.java:39)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:991)
	at mhtest.ChildMHLookupField.instanceFieldGetter2(ChildMHLookupField.java:32)
	... 6 more
Caused by: java.lang.LinkageError: loading constraint violation: Lmhtest/Dummy; not visible from mhtest/ChildMHLookupField
	at java.base/java.lang.invoke.PrimitiveHandle.lookupField(Native Method)
	at java.base/java.lang.invoke.FieldHandle.finishFieldInitialization(FieldHandle.java:64)
	... 10 more
```

### Failing Test Targets

1. `JCL_TEST_Java-Security_0` [sanity.functional] 
    - `test_MHInstanceFieldGetter2`
    - `test_MHInstanceFieldSetter2`
    - `test_MHStaticFieldGetter2`
    - `test_MHStaticFieldSetter2`

### Solution

Currently, OpenJ9 performs 
- `accessCheckMethodSignature` from `PrimitiveHandle.lookupMethod`; and
- `accessCheckFieldSignature` from `PrimitiveHandle.lookupField`.

The above checks throw a `LinkageError`, which gets translated to an `InvocationTargetException`.

These checks need to be performed from `MethodHandleNatives.resolve` under certain conditions. This should fix the above failures.

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
The `MethodHandleNatives.resolve` related solution is described above.

This should be tagged with the `project:MH` label.

fyi @fengxue-IS

**Comment by fengxue-IS** [comment]
I will look into this
