### ISSUE TITLE
OJDK MH: NoSuchMethodException: no such method: ...

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11925]
### Errors
Unexpected `NoSuchMethodException` thrown when OJDK MHs are enabled in OpenJ9.
```
FAILED: test_findVirtual_interface_ITest_private_static
java.lang.NoSuchMethodException: no such method: ITest.private_static_method()String/invokeInterface
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2687)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ReflectionAndMethodHandles.test_findVirtual_interface_ITest_private_static(Test_ReflectionAndMethodHandles.java:434)

FAILED: test_find_static_child_private_non_static
java.lang.NoSuchMethodException: no such method: ITestChild.child_private_non_static_method()String/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2595)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ReflectionAndMethodHandles.test_find_static_child_private_non_static(Test_ReflectionAndMethodHandles.java:328)

FAILED: test_find_static_child_public_non_static
java.lang.NoSuchMethodException: no such method: ITestChild.child_public_non_static_method()String/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2595)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ReflectionAndMethodHandles.test_find_static_child_public_non_static(Test_ReflectionAndMethodHandles.java:311)

FAILED: test_find_virtual_child_private_static
java.lang.NoSuchMethodException: no such method: ITestChild.child_private_static_method()String/invokeInterface
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2687)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ReflectionAndMethodHandles.test_find_virtual_child_private_static(Test_ReflectionAndMethodHandles.java:416)

FAILED: test_find_virtual_child_public_static
java.lang.NoSuchMethodException: no such method: ITestChild.child_public_static_method()String/invokeInterface
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1119)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3651)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2687)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ReflectionAndMethodHandles.test_find_virtual_child_public_static(Test_ReflectionAndMethodHandles.java:398)
```

### Failing Test Targets

1. `jsr335_interfacePrivateMethod_1` [sanity.functional] 
    - `test_findVirtual_interface_ITest_private_static`
    - `test_find_static_child_private_non_static`
    - `test_find_static_child_public_non_static`
    - `test_find_virtual_child_private_static`
    - `test_find_virtual_child_public_static`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
Fix is related to error handling within `MethodHandleNatives.resolve`.

This should be tagged with the `project:MH` label.

fyi @fengxue-IS

**Comment by fengxue-IS** [comment]
I will look into this
