### ISSUE TITLE
OJDK MH: Unexpected IllegalAccessException: caller class must be a subclass ...

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11935]
### Error

Unexpected `IllegalAccessException` thrown from `UnreflectTests.testLookupUnreflectSpecial`.

```
FAILED: testLookupUnreflectSpecial
java.lang.IllegalAccessException: caller class must be a subclass below the method: org.openj9.test.unnamed.UnnamedDummy.dummy(Dummy)void/invokeSpecial, from class org.openj9.test.modularity.tests.UnreflectTests (module org.openj9test.modularity.testUnreflect)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:957)
	at java.base/java.lang.invoke.MethodHandles$Lookup.restrictReceiver(MethodHandles.java:3918)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3993)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:3944)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:3402)
	at org.openj9test.modularity.testUnreflect/org.openj9.test.modularity.tests.UnreflectTests.testLookupUnreflectSpecial(UnreflectTests.java:64)
```

### Failing Test Targets

1. `UnreflectTests_0` [extended.functional]
    - `testLookupUnreflectSpecial`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

**Comment by babsingh** [comment]
Needs to be investigated.

**Comment by babsingh** [comment]
The reference implementation (RI) behaviour matches the above error which is thrown by OpenJ9 with OJDK MHs enabled. 

Java doc for `Lookup.unreflectSpecial`: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#unreflectSpecial(java.lang.reflect.Method,java.lang.Class)

### TODOs
1. Verify the correct behaviour using the above Javadoc.
2. If RI and OpenJ9 with OJDK MHs throw the correct error, then the test should be updated to check for the correct behaviour.
3. If RI and OpenJ9 with OJDK MHs show incorrect behaviour, then an OpenJDK bug report should be opened. 

### RI Output
```
openjdk version "16-ea" 2021-03-16
OpenJDK Runtime Environment (build 16-ea+33-2205)


java.lang.IllegalAccessException: caller class must be a subclass below the method: org.openj9.test.unnamed.UnnamedDummy.dummy(Dummy)void/invokeSpecial, from class org.openj9.test.modularity.tests.UnreflectTests (module org.openj9test.modularity.testUnreflect)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:957)
	at java.base/java.lang.invoke.MethodHandles$Lookup.restrictReceiver(MethodHandles.java:3918)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3993)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:3944)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:3402)
	at org.openj9test.modularity.testUnreflect/org.openj9.test.modularity.tests.UnreflectTests.testLookupUnreflectSpecial(UnreflectTests.java:64)
```

### Micro-test
**Run command:** `jdk16/bin/java -Xint UnreflectTest.java`
```
import static java.lang.invoke.MethodHandles.*;
import static java.lang.invoke.MethodType.*;
import java.lang.invoke.*;
import java.lang.reflect.*;

public class UnreflectTest {
        private final static MethodHandles.Lookup lookup = MethodHandles.lookup();

        public static void main (String[] args) throws Throwable {
                lookup.unreflectSpecial(UnnamedReflectObjects.getReflectMethod(), UnreflectTest.class);
        }

        static class UnnamedReflectObjects {
                private static Class<?> unnamedDummyClz;

                static {
                        try {
                                unnamedDummyClz = Class.forName("UnreflectTest$UnnamedDummy");
                        } catch (ClassNotFoundException e) {
                                System.out.println("FAIL: Cannot create tester class -- " + e);
                        }
                }

                public static Method getReflectMethod() throws Throwable {
                        return unnamedDummyClz.getMethod("dummy", Dummy.class);
                }
        }

        static class UnnamedDummy {
                public Dummy fieldModuleDummy = new Dummy();
                public UnnamedDummy(Dummy dummy) {
                }
                public void dummy(Dummy dummy) {
                }
        }

        static class Dummy {
        }

}
```

fyi @fengxue-IS

**Comment by babsingh** [comment]
@llxia We want to disable **specific tests** in a **test suite** for OpenJDK MethodHandles. E.g. `testLookupUnreflectSpecial` needs to be disabled in the `UnreflectTests_0 [extended.functional]` test suite. Currently, we are only allowed to disable the entire test suite through the XML file. How should we disable specific tests in a test suite? Can you point us to an existing example?

In OJ9, we have a JPP flag (`OPENJDK_METHODHANDLES`) to enable/disable Java level changes for OJDK MHs. Is it possible to extend the usage of this JPP flag to the test code?

We also plan to disable tests similarly for the following issues: https://github.com/eclipse-openj9/openj9/issues/11924 and https://github.com/eclipse-openj9/openj9/issues/11927.

**Comment by llxia** [comment]
It looks like we want to disable a specific test in a test suite when OpenJDK MethodHandles is enabled in Openj9. Currently, the test framework does not support disable based on a certain feature. Do we have OpenJDK MethodHandles build in Jenkins nightly? Or we are only running OpenJDK MethodHandles build in the personal build?

FYI @renfeiw

**Comment by smlambert** [comment]
@babsingh - can you specify what tests specifically you want to enable/disable?  It could be potentially possible that the targets in the openjdk/playlist can be broken down into smaller units that accomplish this, depending on the set of tests that you are talking about.

**Comment by pshipton** [comment]
This is extended.functional. I suggest setting some system property when OMH is enabled, and use that system property in the tests to control if they run or not.

**Comment by babsingh** [comment]
> Do we have OpenJDK MethodHandles build in Jenkins nightly? Or we are only running OpenJDK MethodHandles in the personal build?

OpenJDK MethodHandles have been enabled for JDK17 acceptance builds in 
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/308. Tests need to be disabled in order to promote the JDK17 acceptance build.

> can you specify what tests specifically you want to enable/disable?

In the below tests, test behaviour seen with OJ9 does not match the behaviour seen with the reference implementation (RI). These discrepancies were found when OJDK MHs were enabled in OJ9. These tests need to be updated to check for the correct RI behaviour. Due to scare resources, such tests will be disabled in the short term. This will allow the builds to promote when OJDK MHs are enabled in OJ9.
 
- test-case: `test335DefenderSupersendsAsmAsMethodHandles`; test-suite: `jsr335tests`; target: `sanity.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/11924
- test-case: `testConflictingDefinitionsInSuperInterface`; test-suite: `jsr335tests`; target: `sanity.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/11924
- test-case: `test_RevealDirect_TargetVarargsAdaptor`; test-suite: `JCL_Test`; target: `sanity.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/11927
- test-case: `testLookupUnreflectSpecial`; test-suite: `UnreflectTests`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/11935
- test-case: `testBindTo`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testAll`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testPermuteArguments`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testIfVirtualHandleTestIsJitted`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testIfConstructorHandleIsJitted`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testIfRecieverBoundHandleTestIsJitted`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testIfInterfaceHandleIsJitted`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571
- test-case: `testIfDirectHandleTestIsJitted`; test-suite: `jsr292Test`; target: `extended.functional`; issue: https://github.com/eclipse-openj9/openj9/issues/12571

> the targets in the openjdk/playlist can be broken down into smaller units that accomplish this,

The above test list can grow as we incrementally identify new test failures. **Requirements:**
- We need a process/feature to disable tests at a moment's notice. 
- Also, the tests should only be disabled if OJDK MHs are enabled in OJ9. 
- Existing OJ9 builds should have no impact.

**Comment by smlambert** [comment]
The point would be if all of those tests are related to a single feature (in this case MethodHandles), should they could get regrouped into their own target, a sub-target within functional.  Then it both makes it clearer that the tests are associated with the feature and excluding the entire set from the playlist.xml file is possible.  This may or may not be useful.

Since the specific list of tests are testNG tests, the exclusion of single test cases (and even single methods within a test case) can most certainly be done (with or without the above mentioned reorganizing of tests), using a Transformer to excludes annotated tests, IncludeExcludeTestAnnotationTransformer.java is one that is already in use.  

As mentioned in test doc, [How to Disable a test](https://github.com/eclipse-openj9/openj9/tree/master/test#3-how-to-disable-a-test) - adding the set of test classes to [TestConfig/resources/excludes/latest_exclude_17.txt](https://github.com/eclipse-openj9/openj9/blob/master/test/TestConfig/resources/excludes/latest_exclude_17.txt) would exclude them from the run.  

If it is needed that they are sometimes included but sometimes not, then creating a separate MethodHandlesExclude.txt that gets added to the list of exclude files to consider for a particular test run is likely also doable.  Include the MethodHandlesExclude.txt file as an input parameter when wanting to exclude the tests, and do not add it to the command line when not wanting to exclude them.

**Comment by babsingh** [comment]
Thanks @smlambert. `MethodHandles_exclude.txt` will allow us to quickly disable tests for OJDK MHs. I didn't find any references to `latest_exclude_17.txt` in the OpenJ9 repo. Where is the `list of exclude files` set or managed?

**Comment by llxia** [comment]
>Where is the list of exclude files set or managed?

https://github.com/adoptium/TKG/blob/07171520f8b0849d922125d35380d45193f9c5bf/settings.mk#L296
https://github.com/eclipse-openj9/openj9/blob/24b14b4743f82a648712bdca71a5b870828e65f9/test/Utils/src/org/openj9/test/util/IncludeExcludeTestAnnotationTransformer.java

As Peter mentioned in https://github.com/eclipse-openj9/openj9/issues/11935#issuecomment-839172060, we need some runtime check to determine if OMH is enabled if you want to use feature_exclude.txt.

To keep this simple, if JDK17 has OMH enabled by default, I think you can just update https://github.com/eclipse-openj9/openj9/blob/master/test/TestConfig/resources/excludes/latest_exclude_17.txt to exclude OMH failure.

**Comment by pshipton** [comment]
jdk17 doesn't have OMH enabled by default. There are two branches of the extensions. `openj9` doesn't have OMH enabled, while `openj9-staging` does.

**Comment by babsingh** [comment]
@llxia After reading `IncludeExcludeTestAnnotationTransformer.java`, I don't think it supports a `list of exclude files`. It only parses a `single exclude file`. So, `latest_ojdkmh_exclude_17.txt` will include everything from `latest_exclude_17.txt` + OJDK MH specific tests.

**Comment by llxia** [comment]
yes, it assumes a single exclude file.

**Comment by smlambert** [comment]
Since we wrote that transformer, would be a small matter of updating it to also read `feature_<featureName>_exclude` files.  

We should establish a simple naming convention, all files in excludes starting with feature_ and ending with _exclude.txt

**Comment by fengxue-IS** [comment]
test has been excluded, marking this as low prio.

Todo:  As OpenJ9 w/ OJDK MH matches RI behavior and the exception is generated from openjdk JCL, only need to review behavior against java doc to confirm if this is an error with testcase or JCL (then raise openjdk bug report)
