### ISSUE TITLE
Error cause not printed when JMX Agent fails to start

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#1196]
When appropriate command line options are set, a JMX Agent is started when the JVM launches. If the JMX Agent fails to start for any reason, the JVM also fails to start.

Here's an example command, where the JMX Agent fails because the specified class in the `javax.management.builder.initial` property does not exist:

`> java -Djavax.management.builder.initial=foo -Dcom.sun.management.jmxremote -version`

With Oracle/HotSpot the resulting error looks like this:

```
javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class foo: java.lang.ClassNotFoundException: foo
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:503)
        at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:539)
        at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:316)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:469)
        at sun.management.jmxremote.ConnectorBootstrap.startLocalConnectorServer(ConnectorBootstrap.java:533)
        at sun.management.Agent.startLocalManagementAgent(Agent.java:138)
        at sun.management.Agent.startAgent(Agent.java:260)
        at sun.management.Agent.startAgent(Agent.java:447)
Caused by: java.lang.ClassNotFoundException: foo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:446)
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:488)
        ... 9 more
Exception thrown by the agent : javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class foo: java.lang.ClassNotFoundException: foo
```
With OpenJ9 the same error looks like this:

```
Exception in thread "main" java/lang/InternalError: java.lang.reflect.InvocationTargetException
        at java/lang/System.completeInitialization (System.java:186)
        at java/lang/Thread.<init> (Thread.java:157)
```

As you can see, the root cause of the problem is swallowed in an InvocationTargetException, which is then wrapped in an InternalError. It's not even clear that the JMX Agent is involved.

The problem seems to be that OpenJ9 constructs the InternalError like this:
```
} catch (Exception e) {
	throw new InternalError(e.toString());
}
```
which means that the root cause of the InvocationTargetException (i.e. `e.getCause()`) is lost.

I tried changing the code to this:
```
} catch (Exception e) {
	throw new InternalError(e);
}
```
with the expectation that the JVM would print a chained stack trace with all the causes printed recursively (as described in the API doc for `Throwable.printStackTrace()`). But that isn't what happens - I still only see the single stack for the InternalError.

I also tried this testcase:

```
public class CauseTest {
	public static void main (String args[]) {
		try {
			throw new RuntimeException("Low level problem");
		} catch (Exception e) {
			throw new InternalError(e);
		}
	}
}
```
and it behaves as expected - i.e. I get a chained stack trace:

```
Exception in thread "main" java.lang.InternalError: java.lang.RuntimeException: Low level problem
        at CauseTest.main(CauseTest.java:6)
Caused by: java.lang.RuntimeException: Low level problem
        at CauseTest.main(CauseTest.java:4)
```
So there seems to be something different about how the InternalError is printed in the JMX Agent scenario.

**Comment by DanHeidinga** [comment]
@pdbain-ibm This is the jmx issue I mentioned this morning.  If you can take a look, would be appreciated.

**Comment by pdbain-ibm** [comment]
Dan
Will do.

@paulcheeseman 
I tried your command line with a JDK I recently built.  It seems to have the correct behaviour:

$ /team/pdbain/projects/openj9/openjdk/build/linux-x86_64-normal-server-release/jdk/bin/java -Djavax.management.builder.initial=foo -Dcom.sun.management.jmxremote -version
javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class foo: java.lang.ClassNotFoundException: foo
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(java.management/MBeanServerFactory.java:502)
	at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(java.management/MBeanServerFactory.java:535)
	at javax.management.MBeanServerFactory.newMBeanServer(java.management/MBeanServerFactory.java:316)
	at javax.management.MBeanServerFactory.createMBeanServer(java.management/MBeanServerFactory.java:231)
	at javax.management.MBeanServerFactory.createMBeanServer(java.management/MBeanServerFactory.java:192)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(java.management/ManagementFactory.java:477)
	at sun.management.jmxremote.ConnectorBootstrap.startLocalConnectorServer(jdk.management.agent/ConnectorBootstrap.java:534)
	at jdk.internal.agent.Agent.startLocalManagementAgent(jdk.management.agent/Agent.java:317)
	at jdk.internal.agent.Agent.startAgent(jdk.management.agent/Agent.java:453)
	at jdk.internal.agent.Agent.startAgent(jdk.management.agent/Agent.java:621)
	at java.lang.System.startSNMPAgent(java.base/Native Method)
	at java.lang.Thread.completeInitialization(java.base/Thread.java:168)
	at java.lang.J9VMInternals.completeInitialization(java.base/J9VMInternals.java:74)
Caused by: java.lang.ClassNotFoundException: foo
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base/BuiltinClassLoader.java:753)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base/ClassLoaders.java:185)
	at java.lang.ClassLoader.loadClass(java.base/ClassLoader.java:1026)
	at javax.management.MBeanServerFactory.loadBuilderClass(java.management/MBeanServerFactory.java:444)
	at javax.management.MBeanServerFactory.checkMBeanServerBuilder(java.management/MBeanServerFactory.java:487)
	... 12 more
Exception thrown by the agent : javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class foo: java.lang.ClassNotFoundException: foo
Exception in thread "main" java/lang/RuntimeException: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class foo: java.lang.ClassNotFoundException: foo
 

Could you give more details as to the OpenJ9 build you are using?

Thanks

**Comment by paulcheeseman** [comment]
Sorry again - it's actually 8.0.5.5 onwards. It was exposed by the fix for [APAR IV97963](https://www-01.ibm.com/support/docview.wss?uid=swg1IV97963) in the IBM class library.

**Comment by pdbain-ibm** [comment]
@paulcheeseman would you kindly verify the change?
Thank you.

**Comment by paulcheeseman** [comment]
@pdbain-ibm 
As discussed, I just tested with this build:

```
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-jenkins_2018_02_22_15_07-b00)
Eclipse OpenJ9 VM (build openj9-0.0M1, JRE 1.8.0 Linux amd64-64 Compressed References 20180222_85 (JIT enabled, AOT enabled)
OpenJ9   - 453326f7
OMR      - 1f7d88e0
JCL      - ce606dfd1f based on jdk8u162-b12)
```
but I see no error at all when running this command:

`> java -Djavax.management.builder.initial=foo -Dcom.sun.management.jmxremote -version`

**Comment by pshipton** [comment]
fyi that build predates the fix

**Comment by paulcheeseman** [comment]
@pshipton Is there an easy way to check whether a fix is in a particular build? I was going simply off the date, but that doesn't seem to be enough ([according to the commit](https://github.com/eclipse/openj9/commit/241ccb41f1821d22c392af154f121b5f7ca4ff26) the fix went in three days ago, and the binary was built yesterday).

**Comment by pdbain-ibm** [comment]
I tested with this build and it worked:
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-openj9_2018_02_23_09_07-b00)
Eclipse OpenJ9 VM (build ibm_sdk-73cfa4a, JRE 1.8.0 Linux amd64-64 Compressed References 20180223_379399 (JIT enabled, AOT enabled)
OpenJ9   - 73cfa4a
OMR      - 58194bc
JCL      - e2cb8c7 based on jdk8u162-b12)

**Comment by pshipton** [comment]
@paulcheeseman for a regular build "yesterday" would have been sufficient, but your build was created from a tag (openj9-0.0M1) which is a test tag we created in preparation for the 0.8 release in order to test the build process. The tagged level predates the fix.

You can check if a fix is in a build using the git SHAs, if you have the git sources.

**Comment by paulcheeseman** [comment]
I confirmed that a useful Error/Exception is printed with this build:
```
openjdk version "1.8.0"
OpenJDK Runtime Environment (build 1.8.0-jenkins_2018_03_02_16_02-b00)
Eclipse OpenJ9 VM (build openj9-0.8.0-rc2, JRE 1.8.0 Linux amd64-64 Compressed References 20180302_106 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ed7328e5 based on jdk8u162-b12)
```
By running this command:

`java -Djavax.management.builder.initial=foo -Dcom.sun.management.jmxremote -version`
