### ISSUE TITLE
Systemtest: Mauve load test fails with ClassNotFoundException

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#1198]
There is a Mauve test failure in **openjdk8 hotspot macos** JVM with the following error: 

```
LT  java.lang.ClassNotFoundException: gnu.testlet.java.awt.color.ColorSpace.getInstance
        LT  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        LT  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        LT  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        LT  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        LT  	at java.lang.Class.forName0(Native Method)
        LT  	at java.lang.Class.forName(Class.java:264)
        LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:50)
        LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
        LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        LT  	at java.lang.Thread.run(Thread.java:748)
        LT 
```

The same failure occurs in two different Mauve load tests : 
MauveSingleThreadLoadTest
MauveSingleInvocationLoadTest

**JVM Version info**
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_02_15_21_17-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

**Build link**
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_macos/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_1518732084195/TestTargetResult.tap/*view*/

**Comment by Mesbah-Alam** [comment]
This issue was opened under openj9 by mistake as Openj9 doesn't support macos.
