### ISSUE TITLE
TestUTF8 fails with assertion Unsafe_copySwapMemory0 is unimplemented

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1203]
openjdk-tests/openjdk_regression/openjdk-jdk/jdk/test/sun/nio/cs/TestUTF8.java

fails with an assertion:

```
#3  0xf6f169b2 in __assert_fail_base (fmt=0x1 <error: Cannot access memory at address 0x1>, 
    assertion=0xf54360ec "!\"Java_jdk_internal_misc_Unsafe_copySwapMemory0 is unimplemented\"", 
    assertion@entry=0x2 <error: Cannot access memory at address 0x2>, file=file@entry=0xd20de470 "\001", line=857, 
    line@entry=4143841408, 
    function=function@entry=0xf5435f28 <Java_jdk_internal_misc_Unsafe_copySwapMemory0::__PRETTY_FUNCTION__> "void Java_jdk_internal_misc_Unsafe_copySwapMemory0(JNIEnv*, jobject, jobject, jlong, jobject, jlong, jlong, jlong)") at assert.c:92
#4  0xf6f16a4a in __GI___assert_fail (assertion=0x2 <error: Cannot access memory at address 0x2>, 
    file=0xd20de470 "\001", line=4143841408, 
    function=0xf5435f28 <Java_jdk_internal_misc_Unsafe_copySwapMemory0::__PRETTY_FUNCTION__> "void Java_jdk_internal_misc_Unsafe_copySwapMemory0(JNIEnv*, jobject, jobject, jlong, jobject, jlong, jlong, jlong)") at assert.c:101
#5  0xf541a7b0 in Java_jdk_internal_misc_Unsafe_copySwapMemory0 ()
   from /home/jkingdon/sdks/jdk/lib/default/libjclse9_29.so
#6  0xf62d4768 in ffi_call_VFP () from /home/jkingdon/sdks/jdk/lib/default/libffi29.so
#7  0xf62d3490 in ffi_call () from /home/jkingdon/sdks/jdk/lib/default/libffi29.so
#8  0xf6397560 in bytecodeLoop () from /home/jkingdon/sdks/jdk/lib/default/libj9vm29.so
#9  0xf63e3d28 in cInterpreter () from /home/jkingdon/sdks/jdk/lib/default/libj9vm29.so
```
I saw this while running tests on arm, so it might be something platform specific, but I couldn't immediately see why that would be the case. The assertion comes from common code in openj9/runtime/jcl/common/sun_misc_Unsafe.cpp

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?  Running the test on x86 and seeing if it crashes would rule out the possibility of it being platform-specific and give an easier place to debug.

**Comment by theresa-m** [comment]
Yes. Looking at this.

**Comment by theresa-m** [comment]
This is not platform specific and has OpenJDK code calling the unsafe method:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/Unsafe.copySwapMemory0(Native Method)
4XESTACKTRACE                at jdk/internal/misc/Unsafe.copySwapMemory(Unsafe.java:894)
4XESTACKTRACE                at java/nio/DirectCharBufferS.put(DirectCharBufferS.java:395)
4XESTACKTRACE                at java/nio/CharBuffer.put(CharBuffer.java:899)
4XESTACKTRACE                at TestUTF8.encode(TestUTF8.java:107)
4XESTACKTRACE                at TestUTF8.checkRoundtrip(TestUTF8.java:175)
4XESTACKTRACE                at TestUTF8.main(TestUTF8.java:583)
```
I will write in the native as per discussion in the public slack channel.
