### ISSUE TITLE
renaissance-dec-tree_0_FAILED - Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12078]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.perf_ppc64le_linux/1`
```
04:08:39  openjdk version "17" 2021-09-14
04:08:39  OpenJDK Runtime Environment AdoptOpenJDK (build 17+11)
04:08:39  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f021812fb, JRE 17 Linux ppc64le-64-Bit Compressed References 20210227_13 (JIT enabled, AOT enabled)
04:08:39  OpenJ9   - f021812fb
04:08:39  OMR      - eb4f5a875
04:08:39  JCL      - 6031ea3dbe based on jdk-17+11)
```
rebuild the failed tests in one link:
05:28:29  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=perf&PLATFORM=ppc64le_linux_mixed&TARGET=testList%20TESTLIST=renaissance-als_0,renaissance-chi-square_0,renaissance-dec-tree_0,renaissance-gauss-mix_0,renaissance-log-regression_0,renaissance-movie-lens_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test renaissance-dec-tree_0 ...
===============================================
renaissance-dec-tree_0 Start Time: Sat Feb 27 05:12:46 2021 Epoch Time (ms): 1614420766918
variation: NoOptions
JVM_OPTIONS:  
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/02/27 05:12:50 INFO SparkContext: Running Spark version 2.0.0
21/02/27 05:12:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/02/27 05:12:50 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
21/02/27 05:12:50 INFO SecurityManager: Changing view acls to: jenkins
21/02/27 05:12:50 INFO SecurityManager: Changing modify acls to: jenkins
21/02/27 05:12:50 INFO SecurityManager: Changing view acls groups to: 
21/02/27 05:12:50 INFO SecurityManager: Changing modify acls groups to: 
21/02/27 05:12:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(jenkins); groups with view permissions: Set(); users  with modify permissions: Set(jenkins); groups with modify permissions: Set()
21/02/27 05:12:50 INFO PlatformDependent: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
21/02/27 05:12:51 INFO Utils: Successfully started service 'sparkDriver' on port 37963.
21/02/27 05:12:51 INFO SparkEnv: Registering MapOutputTracker
21/02/27 05:12:51 INFO SparkEnv: Registering BlockManagerMaster
21/02/27 05:12:51 INFO DiskBlockManager: Created local directory at /home/jenkins/workspace/Test_openjdk17_j9_extended.perf_ppc64le_linux/openjdk-tests/TKG/output_16144207471410/renaissance-dec-tree_0/dec_tree12822551946614936183/blockmgr-efbe0573-a320-4bf6-9c2f-7c648ed37728
21/02/27 05:12:51 INFO MemoryStore: MemoryStore started with capacity 9.4 GB
21/02/27 05:12:51 INFO SparkEnv: Registering OutputCommitCoordinator
21/02/27 05:12:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/02/27 05:12:51 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://9.37.235.127:4040
21/02/27 05:12:51 INFO Executor: Starting executor ID driver on host localhost
21/02/27 05:12:51 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34255.
21/02/27 05:12:51 INFO NettyBlockTransferService: Server created on 9.37.235.127:34255
21/02/27 05:12:51 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 9.37.235.127, 34255)
21/02/27 05:12:51 INFO BlockManagerMasterEndpoint: Registering block manager 9.37.235.127:34255 with 9.4 GB RAM, BlockManagerId(driver, 9.37.235.127, 34255)
21/02/27 05:12:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 9.37.235.127, 34255)
Exception occurred in org.renaissance.apache.spark.DecTree@7f3c9273: null
java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:184)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173)
	at org.apache.spark.sql.execution.datasources.PartitioningUtils$.<init>(PartitioningUtils.scala:415)
	at org.apache.spark.sql.execution.datasources.PartitioningUtils$.<clinit>(PartitioningUtils.scala)
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileCatalog.inferPartitioning(PartitioningAwareFileCatalog.scala:126)
	at org.apache.spark.sql.execution.datasources.ListingFileCatalog.partitionSpec(ListingFileCatalog.scala:60)
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileCatalog.allFiles(PartitioningAwareFileCatalog.scala:74)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:395)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:392)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:391)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
	at org.renaissance.apache.spark.DecTree.prepareAndLoadInput(DecTree.scala:84)
	at org.renaissance.apache.spark.DecTree.setUpBeforeAll(DecTree.scala:116)
	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite$$$Lambda$121/0x0000000044787990.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.Launcher.main(Launcher.java:18)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.String.substring(String.java:2752)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:48)
	... 27 more
The following benchmarks failed: dec-tree

renaissance-dec-tree_0_FAILED
```

**Comment by pshipton** [comment]
Is this test running/passing on versions prior to jdk17?

**Comment by JasonFengJ9** [comment]
> Is this test running/passing on versions prior to jdk17?

JDK16 failed in same way at `Test_openjdk16_j9_extended.perf_ppc64le_linux/1/`.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2255

Note there are several renaissance benchmarks that are failing in jdk16+ (that have no issue running against jdk8/jdk11 builds).

**Comment by pshipton** [comment]
It may just be incompatible with jdk16+. We should check if it works on Hotspot.

**Comment by smlambert** [comment]
It does not (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2255 shows it fails for both)

**Comment by smlambert** [comment]
So I am suggesting to @JasonFengJ9 to if renaissance jdk16+ failures are already reported in openjdk-tests repo, and they are failing for both j9 and hs, likely do not need an openj9 specific issue... I am thinking its a renaissance issue atm.

**Comment by JasonFengJ9** [comment]
closing to favour https://github.com/AdoptOpenJDK/openjdk-tests/issues/2255.
