### ISSUE TITLE
renaissance-als_0_FAILED - java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @da60dc9e

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12077]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.perf_ppc64le_linux/1`
```
04:08:39  openjdk version "17" 2021-09-14
04:08:39  OpenJDK Runtime Environment AdoptOpenJDK (build 17+11)
04:08:39  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f021812fb, JRE 17 Linux ppc64le-64-Bit Compressed References 20210227_13 (JIT enabled, AOT enabled)
04:08:39  OpenJ9   - f021812fb
04:08:39  OMR      - eb4f5a875
04:08:39  JCL      - 6031ea3dbe based on jdk-17+11)
```
rebuild the failed tests in one link:
05:28:29  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=perf&PLATFORM=ppc64le_linux_mixed&TARGET=testList%20TESTLIST=renaissance-als_0,renaissance-chi-square_0,renaissance-dec-tree_0,renaissance-gauss-mix_0,renaissance-log-regression_0,renaissance-movie-lens_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test renaissance-als_0 ...
===============================================
renaissance-als_0 Start Time: Sat Feb 27 05:12:27 2021 Epoch Time (ms): 1614420747559
variation: NoOptions
JVM_OPTIONS:  
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/02/27 05:12:30 INFO SparkContext: Running Spark version 2.0.0
21/02/27 05:12:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/02/27 05:12:31 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
21/02/27 05:12:31 INFO SecurityManager: Changing view acls to: jenkins
21/02/27 05:12:31 INFO SecurityManager: Changing modify acls to: jenkins
21/02/27 05:12:31 INFO SecurityManager: Changing view acls groups to: 
21/02/27 05:12:31 INFO SecurityManager: Changing modify acls groups to: 
21/02/27 05:12:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(jenkins); groups with view permissions: Set(); users  with modify permissions: Set(jenkins); groups with modify permissions: Set()
21/02/27 05:12:31 INFO PlatformDependent: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
21/02/27 05:12:31 INFO Utils: Successfully started service 'sparkDriver' on port 45403.
21/02/27 05:12:31 INFO SparkEnv: Registering MapOutputTracker
21/02/27 05:12:31 INFO SparkEnv: Registering BlockManagerMaster
21/02/27 05:12:31 INFO DiskBlockManager: Created local directory at /home/jenkins/workspace/Test_openjdk17_j9_extended.perf_ppc64le_linux/openjdk-tests/TKG/output_16144207471410/renaissance-als_0/als14130211358811306423/blockmgr-e7fcf200-b81a-4fa6-bb49-acc426ebdc09
21/02/27 05:12:31 INFO MemoryStore: MemoryStore started with capacity 9.4 GB
21/02/27 05:12:32 INFO SparkEnv: Registering OutputCommitCoordinator
21/02/27 05:12:32 INFO Utils: Successfully started service 'SparkUI' on port 4040.
21/02/27 05:12:32 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://9.37.235.127:4040
21/02/27 05:12:32 INFO Executor: Starting executor ID driver on host localhost
21/02/27 05:12:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42143.
21/02/27 05:12:32 INFO NettyBlockTransferService: Server created on 9.37.235.127:42143
21/02/27 05:12:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 9.37.235.127, 42143)
21/02/27 05:12:32 INFO BlockManagerMasterEndpoint: Registering block manager 9.37.235.127:42143 with 9.4 GB RAM, BlockManagerId(driver, 9.37.235.127, 42143)
21/02/27 05:12:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 9.37.235.127, 42143)
Error during tear-down: Cannot invoke "org.apache.spark.mllib.recommendation.MatrixFactorizationModel.userFeatures()" because the return value of "org.renaissance.apache.spark.Als.factModel()" is null
java.lang.NullPointerException: Cannot invoke "org.apache.spark.mllib.recommendation.MatrixFactorizationModel.userFeatures()" because the return value of "org.renaissance.apache.spark.Als.factModel()" is null
	at org.renaissance.apache.spark.Als.tearDownAfterAll(Als.scala:87)
	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:97)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite$$$Lambda$121/0x00000000c4789fc0.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.Launcher.main(Launcher.java:18)
Exception occurred in org.renaissance.apache.spark.Als@eed7b967: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @da60dc9e
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @da60dc9e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.apache.spark.util.SizeEstimator$$anonfun$getClassInfo$3.apply(SizeEstimator.scala:336)
	at org.apache.spark.util.SizeEstimator$$anonfun$getClassInfo$3.apply(SizeEstimator.scala:330)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.util.SizeEstimator$.getClassInfo(SizeEstimator.scala:330)
	at org.apache.spark.util.SizeEstimator$.visitSingleObject(SizeEstimator.scala:222)
	at org.apache.spark.util.SizeEstimator$.org$apache$spark$util$SizeEstimator$$estimate(SizeEstimator.scala:201)
	at org.apache.spark.util.SizeEstimator$.estimate(SizeEstimator.scala:69)
	at org.apache.spark.util.collection.SizeTracker$class.takeSample(SizeTracker.scala:78)
	at org.apache.spark.util.collection.SizeTracker$class.afterUpdate(SizeTracker.scala:70)
	at org.apache.spark.util.collection.SizeTrackingVector.$plus$eq(SizeTrackingVector.scala:31)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:214)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:919)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:866)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:910)
	at org.apache.spark.storage.BlockManager.putIterator(BlockManager.scala:700)
	at org.apache.spark.storage.BlockManager.putSingle(BlockManager.scala:1213)
	at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:103)
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:86)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:56)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1370)
	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1.apply(SparkContext.scala:984)
	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1.apply(SparkContext.scala:981)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:682)
	at org.apache.spark.SparkContext.hadoopFile(SparkContext.scala:981)
	at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:802)
	at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:800)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:682)
	at org.apache.spark.SparkContext.textFile(SparkContext.scala:800)
	at org.renaissance.apache.spark.Als.loadData(Als.scala:59)
	at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:82)
	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite$$$Lambda$121/0x00000000c4789fc0.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.Launcher.main(Launcher.java:18)
The following benchmarks failed: als

renaissance-als_0_FAILED
```

This appears the test requires `--add-opens` command line option.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
This is a known issue. We have the same failure in hotspot. 
Dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253
