### ISSUE TITLE
linux_x86-64_cmprssptrs] SE80_GIT testOSGiTCK_0 - NullPointerException at aQute.bnd.build.ProjectTester.getReports(ProjectTester.java:39)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12072]
Failure link
------------

From an internal ibuild `466386`
```
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20210122_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210225_466386 (JIT enabled, AOT enabled)
OpenJ9   - 5ccef80
OMR      - 8250f9d
IBM      - 358762e)
JCL - 20210108_01 based on Oracle jdk8u281-b09
```

Optional info
-------------

- intermittent failure (yes): 

Failure output (captured from console output)
---------------------------------------------
```
[exec] # test ran
     [exec] # queue []
     [exec] The java class is not found:  org.osgi.framework.ServiceListener
     [exec] java.lang.NullPointerException
     [exec] 	at aQute.bnd.build.ProjectTester.getReports(ProjectTester.java:39)
     [exec] 	at aQute.bnd.main.bnd.runtTest(bnd.java:1916)
     [exec] 	at aQute.bnd.main.bnd.runtests(bnd.java:1849)
     [exec] 	at aQute.bnd.main.bnd.doCommand(bnd.java:213)
     [exec] 	at aQute.bnd.main.bnd.run(bnd.java:112)
     [exec] 	at aQute.bnd.main.bnd.main(bnd.java:53)
     [exec] 4 errors
     [exec] 1 : Exception: null
     [exec] 2 : FAILURE IN RUNTESTS
     [exec] 3 : Exception: /bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/reports/summary.xml (No such file or directory)
     [exec] 4 : exception java.io.FileNotFoundException: /bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/reports/summary.xml (No such file or directory)
     [exec] 2 warnings
     [exec] 1 : osgi_test: Unknown code 1 from launcher: java -cp /bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/jar/org.eclipse.osgi_3.7.1.R37x_v20110808-1106.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/jar/com.springsource.junit-3.8.2.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/cnf/cache/biz.aQute.launcher/biz.aQute.launcher-latest.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/cnf/cache/biz.aQute.junit/biz.aQute.junit-latest.jar -Dlauncher.properties=/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/generated/launch7795144340790931943.properties aQute.launcher.Launcher
     [exec] 2 : osgi_test: Unknown code 1 from launcher: java -cp /bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/jar/org.eclipse.osgi_3.7.1.R37x_v20110808-1106.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/jar/com.springsource.junit-3.8.2.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/cnf/cache/biz.aQute.launcher/biz.aQute.launcher-latest.jar:/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/cnf/cache/biz.aQute.junit/biz.aQute.junit-latest.jar -Dlauncher.properties=/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/generated/launch105305328605508086.properties aQute.launcher.Launcher
     [exec] Result: 1

report-std:

BUILD FAILED
/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_tck.xml:35: The following error occurred while executing this line:
/bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_tck.xml:176: /bluebird/builds/bld_466386/jvmtest/test/SE80/functional/IBM_Internal/OSGi_TCK/osgi_test/reports not found.
```

**Comment by pshipton** [comment]
How intermittent?

**Comment by pshipton** [comment]
Pls provide at least a partial link.

**Comment by JasonFengJ9** [comment]
> Pls provide at least a partial link.

This is an ibuild job, no partial link like jenkines job, searching test name `[linux_x86-64_cmprssptrs] SE80_GIT testOSGiTCK_0` is sufficient.

> How intermittent?

This failure was marked by other problem tracker (PT), from the test history, the failure rate is ~50%.

**Comment by pshipton** [comment]
Link is job_output.php?id=670854043

**Comment by pshipton** [comment]
@llxia it seems this internal test wasn't running for some time and now it's intermittently failing. It needs some triage to determine if this is a problem with the test itself, or with OpenJ9.

**Comment by llxia** [comment]
@OscarQQ Could help to triage this issue? Thanks

**Comment by llxia** [comment]
The test works in [Jenkins](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_x86-64_linux_nightly/602/tapResults/), but not vmfarm. Exclude the test in vmfarm.

**Comment by OscarQQ** [comment]
Grinder/13997/

**Comment by OscarQQ** [comment]
runtimes/tooling/pull/870 is merged, could we close this issue?
