### ISSUE TITLE
JDK17 jdk_other_0_FAILED - AssertionError: Should have GCd a class loader by now

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12080]
Failure link
------------

From an internal build `Test_openjdk17_j9_extended.openjdk_x86-64_linux/1`
```
01:35:10  openjdk version "17" 2021-09-14
01:35:10  OpenJDK Runtime Environment AdoptOpenJDK (build 17+11)
01:35:10  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f021812fb, JRE 17 Linux amd64-64-Bit Compressed References 20210227_15 (JIT enabled, AOT enabled)
01:35:10  OpenJ9   - f021812fb
01:35:10  OMR      - eb4f5a875
01:35:10  JCL      - 6031ea3dbe based on jdk-17+11)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
02:41:21  --------------------------------------------------
02:41:21  TEST: jdk/dynalink/TypeConverterFactoryRetentionTests.java
02:41:21  TEST JDK: /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image
02:41:21  
02:41:21  ACTION: build -- Passed. Build successful
02:41:21  REASON: Named class compiled on demand
02:41:21  TIME:   0.068 seconds
02:41:21  messages:
02:41:21  command: build TypeConverterFactoryRetentionTests
02:41:21  reason: Named class compiled on demand
02:41:21  Test directory:
02:41:21    compile: TypeConverterFactoryRetentionTests
02:41:21  elapsed time (seconds): 0.068
02:41:21  
02:41:21  ACTION: compile -- Passed. Compilation successful
02:41:21  REASON: .class file out of date or does not exist
02:41:21  TIME:   0.068 seconds
02:41:21  messages:
02:41:21  command: compile /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink/TypeConverterFactoryRetentionTests.java
02:41:21  reason: .class file out of date or does not exist
02:41:21  Mode: agentvm
02:41:21  Agent id: 1
02:41:21  elapsed time (seconds): 0.068
02:41:21  configuration:
02:41:21  Boot Layer (javac runtime environment)
02:41:21    class path: /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar 
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar 
02:41:21    patch:      java.base /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/patches/java.base
02:41:21  
02:41:21  javac compilation environment
02:41:21    source path: /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink
02:41:21    class path:  /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink
02:41:21                 /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d
02:41:21  
02:41:21  rerun:
02:41:21  cd /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/scratch && \
02:41:21  DISPLAY=:0 \
02:41:21  HOME=/home/jenkins \
02:41:21  LANG=en_US.UTF-8 \
02:41:21  PATH=/bin:/usr/bin:/usr/sbin \
02:41:21      /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac \
02:41:21          -J-ea \
02:41:21          -J-esa \
02:41:21          -J-Xmx512m \
02:41:21          -J-XX:+UseCompressedOops \
02:41:21          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
02:41:21          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
02:41:21          -J-Dtest.compiler.opts= \
02:41:21          -J-Dtest.java.opts= \
02:41:21          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
02:41:21          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
02:41:21          -J-Dtest.timeout.factor=8.0 \
02:41:21          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
02:41:21          -J-Dtest.name=jdk/dynalink/TypeConverterFactoryRetentionTests.java \
02:41:21          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink/TypeConverterFactoryRetentionTests.java \
02:41:21          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d \
02:41:21          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d \
02:41:21          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -d /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d \
02:41:21          -sourcepath /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -classpath /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink/TypeConverterFactoryRetentionTests.java
02:41:21  
02:41:21  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Should have GCd a class loader by now
02:41:21  REASON: Assumed action based on file name: run main TypeConverterFactoryRetentionTests 
02:41:21  TIME:   15.062 seconds
02:41:21  messages:
02:41:21  command: main TypeConverterFactoryRetentionTests
02:41:21  reason: Assumed action based on file name: run main TypeConverterFactoryRetentionTests 
02:41:21  Mode: agentvm
02:41:21  Agent id: 4
02:41:21  elapsed time (seconds): 15.062
02:41:21  configuration:
02:41:21  Boot Layer
02:41:21    class path: /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar 
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar 
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/junit.jar 
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/testng.jar 
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jcommander.jar 
02:41:21    patch:      java.base /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/patches/java.base
02:41:21  
02:41:21  Test Layer
02:41:21    class path: /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d
02:41:21                /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink
02:41:21  
02:41:21  rerun:
02:41:21  cd /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/scratch && \
02:41:21  DISPLAY=:0 \
02:41:21  HOME=/home/jenkins \
02:41:21  LANG=en_US.UTF-8 \
02:41:21  PATH=/bin:/usr/bin:/usr/sbin \
02:41:21      /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java \
02:41:21          -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
02:41:21          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
02:41:21          -Dtest.compiler.opts= \
02:41:21          -Dtest.java.opts= \
02:41:21          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
02:41:21          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
02:41:21          -Dtest.timeout.factor=8.0 \
02:41:21          -Dtest.root=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
02:41:21          -Dtest.name=jdk/dynalink/TypeConverterFactoryRetentionTests.java \
02:41:21          -Dtest.file=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink/TypeConverterFactoryRetentionTests.java \
02:41:21          -Dtest.src=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -Dtest.classes=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d \
02:41:21          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d \
02:41:21          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink \
02:41:21          -classpath /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work/classes/jdk/dynalink/TypeConverterFactoryRetentionTests.d:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/jdk/dynalink:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar \
02:41:21          TypeConverterFactoryRetentionTests
02:41:21  STDERR:
02:41:21  java.lang.AssertionError: Should have GCd a class loader by now
02:41:21  	at TypeConverterFactoryRetentionTests.testFromOneClassToClassLoader(TypeConverterFactoryRetentionTests.java:151)
02:41:21  	at TypeConverterFactoryRetentionTests.testSystemLoaderToOtherLoader(TypeConverterFactoryRetentionTests.java:116)
02:41:21  	at TypeConverterFactoryRetentionTests.main(TypeConverterFactoryRetentionTests.java:98)
02:41:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:41:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02:41:21  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:41:21  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:41:21  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:41:21  	at java.base/java.lang.Thread.run(Thread.java:853)
02:41:21  
02:41:21  JavaTest Message: Test threw exception: java.lang.AssertionError
02:41:21  JavaTest Message: shutting down test
02:41:21  
02:41:21  
02:41:21  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Should have GCd a class loader by now
02:41:21  --------------------------------------------------
02:41:21  Test results: passed: 261; failed: 1
02:41:26  Report written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
02:41:26  Results written to /home/jenkins/workspace/Test_openjdk17_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16144108423372/jdk_other_0/work
02:41:26  Error: Some tests failed or other problems occurred.
02:41:26  
02:41:26  jdk_other_0_FAILED
```

**Comment by pshipton** [comment]
@dmitripivkine fyi

Is this test running/passing in earlier versions?

**Comment by JasonFengJ9** [comment]
> Is this test running/passing in earlier versions?

`jdk_other` containing the failing test in question wasn't seen in earlier version `openjdk` tests.

**Comment by dmitripivkine** [comment]
I guess we need to look to test source in order to understand what test expects from JVM. It might be specialized for Hotspot implementation

**Comment by dmitripivkine** [comment]
Seems OpenJDK has similar issue https://bugs.openjdk.java.net/browse/JDK-8261483?focusedCommentId=14401576&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

**Comment by dmitripivkine** [comment]
and seems they have a proposed fix https://github.com/openjdk/jdk/pull/2617/files

Looking what is fixed exactly... This test has bogus expectations about when GC/class unloading should occur.  For out case we might even need to run with `-Xalwaysclassgc`

**Comment by dmitripivkine** [comment]
> and seems they have a proposed fix https://github.com/openjdk/jdk/pull/2617/files
> 
> Looking what is fixed exactly... This test has bogus expectations about when GC/class unloading should occur. For OpenJ9 case we might even need to run with `-Xalwaysclassgc`

... or I guess this option might be not required as far as in the fix test calls SystemGC in the loop and every second SystemGC is going to be treated as Aggressive

**Comment by JasonFengJ9** [comment]
Closing since the fix is on the way.
Thanks investigation.
