### ISSUE TITLE
JDK8 javax/xml/jaxp/transform/8150704/TransformerTest.java - AssertionError: Output of transformation of Bug8150704-1.xml does not match reference expected 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12086]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.openjdk_ppc64_aix/1`
```
01:46:12  openjdk version "1.8.0_292"
01:46:12  OpenJDK Runtime Environment (build 1.8.0_292-b04)
01:46:12  Eclipse OpenJ9 VM (build master-f021812fb, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210226_67 (JIT enabled, AOT enabled)
01:46:12  OpenJ9   - f021812fb
01:46:12  OMR      - eb4f5a875
01:46:12  JCL      - d8816619 based on jdk8u292-b04)
```
rebuild the failed tests in one link:
06:11:58  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=openjdk&PLATFORM=ppc64_aix_mixed&TARGET=testList%20TESTLIST=jdk_other_0,jdk_other_1,jdk_security4_0,jdk_security4_1,jdk_imageio_0,jdk_imageio_1

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
03:01:39  --------------------------------------------------
03:07:22  TEST: javax/xml/jaxp/transform/8150704/TransformerTest.java
03:07:22  TEST JDK: /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image
03:07:22  
03:07:22  ACTION: build -- Passed. Build successful
03:07:22  REASON: Named class compiled on demand
03:07:22  TIME:   0.171 seconds
03:07:22  messages:
03:07:22  command: build TransformerTest
03:07:22  reason: Named class compiled on demand
03:07:22  Test directory:
03:07:22    compile: TransformerTest
03:07:22  elapsed time (seconds): 0.171
03:07:22  
03:07:22  ACTION: compile -- Passed. Compilation successful
03:07:22  REASON: .class file out of date or does not exist
03:07:22  TIME:   0.171 seconds
03:07:22  messages:
03:07:22  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704/TransformerTest.java
03:07:22  reason: .class file out of date or does not exist
03:07:22  Mode: agentvm
03:07:22  Agent id: 1
03:07:22  elapsed time (seconds): 0.171
03:07:22  configuration:
03:07:22  Boot Layer (javac runtime environment)
03:07:22    class path: /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar
03:07:22                /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/javatest.jar
03:07:22                /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jtreg.jar
03:07:22  
03:07:22  javac compilation environment
03:07:22    source path: /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704
03:07:22    class path:  /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704
03:07:22                 /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704
03:07:22                 /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/testng.jar
03:07:22                 /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jcommander.jar
03:07:22                 /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar
03:07:22  
03:07:22  rerun:
03:07:22  cd /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/scratch && \
03:07:22  DISPLAY=:0 \
03:07:22  HOME=/home/jenkins \
03:07:22  LANG=en_US \
03:07:22  PATH=/bin:/usr/bin:/usr/sbin \
03:07:22  TZ=America/Toronto \
03:07:22      /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/javac \
03:07:22          -J-ea \
03:07:22          -J-esa \
03:07:22          -J-Xmx512m \
03:07:22          -J-XX:+UseCompressedOops \
03:07:22          -J-Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
03:07:22          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
03:07:22          -J-Dtest.compiler.opts= \
03:07:22          -J-Dtest.java.opts= \
03:07:22          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
03:07:22          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
03:07:22          -J-Dtest.timeout.factor=8.0 \
03:07:22          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
03:07:22          -J-Dtest.name=javax/xml/jaxp/transform/8150704/TransformerTest.java \
03:07:22          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704/TransformerTest.java \
03:07:22          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704 \
03:07:22          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704 \
03:07:22          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -d /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704 \
03:07:22          -sourcepath /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar \
03:07:22          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704/TransformerTest.java
03:07:22  
03:07:22  ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
03:07:22  REASON: User specified action: run testng/othervm TransformerTest 
03:07:22  TIME:   2.909 seconds
03:07:22  messages:
03:07:22  command: testng TransformerTest
03:07:22  reason: User specified action: run testng/othervm TransformerTest 
03:07:22  Mode: othervm [/othervm specified]
03:07:22  elapsed time (seconds): 2.909
03:07:22  configuration:
03:07:22  STDOUT:
03:07:22  [TestNG] Running:
03:07:22    javax/xml/jaxp/transform/8150704/TransformerTest.java
03:07:22  
03:07:22  Testing transformation of Bug8150704-1.xml
03:07:22  test TransformerTest.testBug8150704("Bug8150704-1.xsl", "Bug8150704-1.xml", "Bug8150704-1.ref"): failure
03:07:22  java.lang.AssertionError: Output of transformation of Bug8150704-1.xml does not match reference expected 
03:07:22  ]
03:07:22  	at org.testng.Assert.fail(Assert.java:94)
03:07:22  	at org.testng.Assert.failNotEquals(Assert.java:496)
03:07:22  	at org.testng.Assert.assertEquals(Assert.java:125)
03:07:22  	at org.testng.Assert.assertEquals(Assert.java:178)
03:07:22  	at TransformerTest.testBug8150704(TransformerTest.java:54)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:07:22  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:07:22  	at java.lang.reflect.Method.invoke(Method.java:498)
03:07:22  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
03:07:22  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
03:07:22  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
03:07:22  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
03:07:22  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
03:07:22  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
03:07:22  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
03:07:22  	at org.testng.TestRunner.run(TestRunner.java:623)
03:07:22  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
03:07:22  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
03:07:22  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
03:07:22  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
03:07:22  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:07:22  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
03:07:22  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
03:07:22  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
03:07:22  	at org.testng.TestNG.run(TestNG.java:1018)
03:07:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
03:07:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:07:22  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:07:22  	at java.lang.reflect.Method.invoke(Method.java:498)
03:07:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:07:22  	at java.lang.Thread.run(Thread.java:823)
03:07:22  
03:07:22  ===============================================
03:07:22  javax/xml/jaxp/transform/8150704/TransformerTest.java
03:07:22  Total tests run: 2, Failures: 2, Skips: 0
03:07:22  ===============================================
03:07:22  
03:07:22  STDERR:
03:07:22  java.lang.Exception: failures: 2
03:07:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
03:07:22  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:07:22  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:07:22  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:07:22  	at java.lang.reflect.Method.invoke(Method.java:498)
03:07:22  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:07:22  	at java.lang.Thread.run(Thread.java:823)
03:07:22  
03:07:22  JavaTest Message: Test threw exception: java.lang.Exception: failures: 2
03:07:22  JavaTest Message: shutting down test
03:07:22  
03:07:22  STATUS:Failed.`main' threw exception: java.lang.Exception: failures: 2
03:07:22  rerun:
03:07:22  cd /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/scratch && \
03:07:22  DISPLAY=:0 \
03:07:22  HOME=/home/jenkins \
03:07:22  LANG=en_US \
03:07:22  PATH=/bin:/usr/bin:/usr/sbin \
03:07:22  TZ=America/Toronto \
03:07:22  CLASSPATH=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jtreg.jar \
03:07:22      /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java \
03:07:22          -Dtest.vm.opts='-ea -esa -Xmx512m -XX:+UseCompressedOops' \
03:07:22          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-XX:+UseCompressedOops' \
03:07:22          -Dtest.compiler.opts= \
03:07:22          -Dtest.java.opts= \
03:07:22          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
03:07:22          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image \
03:07:22          -Dtest.timeout.factor=8.0 \
03:07:22          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
03:07:22          -Dtest.name=javax/xml/jaxp/transform/8150704/TransformerTest.java \
03:07:22          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704/TransformerTest.java \
03:07:22          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704 \
03:07:22          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704 \
03:07:22          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/classes/javax/xml/jaxp/transform/8150704:/home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/xml/jaxp/transform/8150704 \
03:07:22          -ea \
03:07:22          -esa \
03:07:22          -Xmx512m \
03:07:22          -XX:+UseCompressedOops \
03:07:22          com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/TKG/output_16144120941027/jdk_other_0/work/javax/xml/jaxp/transform/8150704/TransformerTest.d/testng.0.jta javax/xml/jaxp/transform/8150704/TransformerTest.java false TransformerTest
03:07:22  
03:07:22  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 2
```

**Comment by pshipton** [comment]
This needs some triage.

**Comment by pshipton** [comment]
I assume this hasn't been seen again. Removing it from the milestone plan.
