### ISSUE TITLE
renaissance-fj-kmeans_0_FAILED - Harness failed with exception: scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12107]
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.perf_x86-64_windows/5`
```
22:17:35  openjdk version "17" 2021-09-14
22:17:35  OpenJDK Runtime Environment AdoptOpenJDK (build 17+11-202103020218)
22:17:35  Eclipse OpenJ9 VM AdoptOpenJDK (build master-5acdc8387, JRE 17 Windows Server 2016 amd64-64-Bit Compressed References 20210302_11 (JIT enabled, AOT enabled)
22:17:35  OpenJ9   - 5acdc8387
22:17:35  OMR      - eb4f5a875
22:17:35  JCL      - 6031ea3dbe based on jdk-17+11)
```
to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:09:50  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=perf&PLATFORM=x86-64_windows_mixed&TARGET=renaissance-fj-kmeans_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test renaissance-fj-kmeans_0 ...
===============================================
renaissance-fj-kmeans_0 Start Time: Mon Mar  1 20:02:03 2021 Epoch Time (ms): 1614657723798
variation: NoOptions
JVM_OPTIONS:  
====== fj-kmeans (jdk-concurrent) [default], iteration 0 started ======
GC before operation: completed in 993.687 ms, heap usage 70.432 MB -> 67.824 MB.
WARNING: This benchmark provides no result that can be validated.
         There is no way to check that no silent failure occurred.

====== fj-kmeans (jdk-concurrent) [default], iteration 29 completed (8574.552 ms) ======
Mar 01, 2021 8:06:23 PM org.renaissance.core.Launcher launchHarnessClass
SEVERE: Harness failed with exception: scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl@36bf869f (of class com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl)
	at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
	at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
	at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
	at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
	at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
	at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
	at org.renaissance.core.Launcher.main(Launcher.java:25)

Mar 01, 2021 8:06:23 PM org.renaissance.core.Launcher launchHarnessClass
SEVERE: Harness failed with exception: scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl@36bf869f (of class com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl)
	at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
	at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
	at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
	at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
	at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
	at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
	at org.renaissance.core.Launcher.main(Launcher.java:25)


renaissance-fj-kmeans_0_FAILED
```

**Comment by pshipton** [comment]
Close this as a dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1994#issuecomment-707304915
