### ISSUE TITLE
SC_Softmx_JitAot_0 Could not open file Invalid argument at stf/Commands.pm line 614

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12115]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/6/
SC_Softmx_JitAot_0
```
STF 01:54:38.145 - +------ Step 6 - Waiting for jvm1 and jvm2 to finish
STF 01:54:38.145 - | Wait for processes to meet expectations
STF 01:54:38.145 - |   Processes: [jvm1, jvm2]
STF 01:54:38.145 - |
STF 01:54:38.145 - Monitoring processes: jvm1 jvm2
Uncaught exception from user code:
	Could not open file 'F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests/\TKG\output_16147552716320\SC_Softmx_JitAot_0/20210303-015432-SharedClassesWorkloadTest_Softmx_Increase_JitAot/execute/execute.stdout' Invalid argument at F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 614.
	stf::Commands::process_logs("stf::Commands", stf::ProcessMgmt::Windows=HASH(0x17c27d8)) called at F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 387
	stf::Commands::monitor_processes("stf::Commands", stf::ProcessMgmt::Windows=HASH(0x17c27d8)) called at F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 830
	stf::Commands::run_process("stf::Commands", "mnemonic", "STF", "command", "perl F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.sy"..., "logName", "F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_"..., "uid", ...) called at F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests///..//jvmtest\system\sharedClasses/../\stf\stf.core\scripts\stf.pl line 584
	main::runScript("perl F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.sy"..., "F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_"..., "execute") called at F:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests///..//jvmtest\system\sharedClasses/../\stf\stf.core\scripts\stf.pl line 505
```

**Comment by pshipton** [comment]
@lumpfish @Mesbah-Alam fyi
There is another failing test in the build that produced core files, maybe a disk space issue.

**Comment by pshipton** [comment]
Found this in 4.jvm1.stdout
```
03:40:33.172 - Test failed
  Failure num.  = 1
  Test number   = 88
  Test details  = 'JUnit[net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest]'
  Suite number  = 0
  Thread number = 3
>>> Captured test output >>>
testStarted : testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:401)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
testFinished: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testStarted : testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to find intial provider 'memory0'
junit.framework.AssertionFailedError: Unable to find intial provider 'memory0'
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testFileSystemIsRegistered(FileSystemsTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
testFinished: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)

JUnit Test Results for: net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest
  Ran    : 2
  Passed : 0
  Failed : 2
  Ignored: 0
  Result : FAILED
<<<
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/21
```
STF 21:45:09.578 - +------ Step 6 - Waiting for jvm1 and jvm2 to finish
STF 21:45:09.578 - | Wait for processes to meet expectations
STF 21:45:09.578 - |   Processes: [jvm1, jvm2]
STF 21:45:09.578 - |
STF 21:45:09.578 - Monitoring processes: jvm1 jvm2
Uncaught exception from user code:
	Could not open file 'F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests/\TKG\output_16162915953150\SC_Softmx_JitAot_0/20210320-214503-SharedClassesWorkloadTest_Softmx_Increase_JitAot/execute/execute.stderr' Invalid argument at F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 614.
	stf::Commands::process_logs("stf::Commands", stf::ProcessMgmt::Windows=HASH(0x988980)) called at F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 387
	stf::Commands::monitor_processes("stf::Commands", stf::ProcessMgmt::Windows=HASH(0x988980)) called at F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/jvmtest/system/stf/stf.core/scripts/stf/Commands.pm line 830
	stf::Commands::run_process("stf::Commands", "mnemonic", "STF", "command", "perl F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.sy"..., "logName", "F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_"..., "uid", ...) called at F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests///..//jvmtest\system\sharedClasses/../\stf\stf.core\scripts\stf.pl line 584
	main::runScript("perl F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.sy"..., "F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_"..., "execute") called at F:/Users/jenkins/workspace/Test_openjdk16_j9_extended.system_x86-64_windows_Nightly_testList_2/openjdk-tests///..//jvmtest\system\sharedClasses/../\stf\stf.core\scripts\stf.pl line 505
```

**Comment by JasonFengJ9** [comment]
A similar `SC_Softmx_JitAot_0_FAILED` occurred at JDK11 0.27 release build at  https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_x86-64_windows_Release_testList_2/5/tapResults/
```
===============================================
Running test SC_Softmx_JitAot_0 ...
===============================================
SC_Softmx_JitAot_0 Start Time: Sat Jul 17 13:41:04 2021 Epoch Time (ms): 1626547264664
variation: Mode110
JVM_OPTIONS:  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 

STF 13:41:46.993 - =====================   R E S U L T S   =====================
STF 13:41:46.993 - Stage results:
STF 13:41:46.993 -   setUp:     pass
STF 13:41:46.993 -   execute:  *fail*
STF 13:41:46.993 -   teardown:  pass
STF 13:41:46.993 - 
STF 13:41:46.993 - Overall result: **FAILED**

SC_Softmx_JitAot_0_FAILED
```

From `SC_Softmx_JitAot_0/20210717-134105-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results/5.jvm2.executionlog.1.ltd`
```
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>^M
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>^M
        at junit.framework.Assert.fail(Assert.java:57)^M
        at junit.framework.Assert.failNotEquals(Assert.java:329)^M
        at junit.framework.Assert.assertEquals(Assert.java:78)^M
        at junit.framework.Assert.assertEquals(Assert.java:234)^M
        at junit.framework.TestCase.assertEquals(TestCase.java:401)^M
        at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)^M
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)^M
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)^M
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)^M
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)^M
        at junit.framework.TestCase.runTest(TestCase.java:176)^M
        at junit.framework.TestCase.runBare(TestCase.java:141)^M
        at junit.framework.TestResult$1.protect(TestResult.java:122)^M
        at junit.framework.TestResult.runProtected(TestResult.java:142)^M
        at junit.framework.TestResult.run(TestResult.java:125)^M
        at junit.framework.TestCase.run(TestCase.java:129)^M
        at junit.framework.TestSuite.runTest(TestSuite.java:252)^M
        at junit.framework.TestSuite.run(TestSuite.java:247)^M
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)^M
        at org.junit.runners.Suite.runChild(Suite.java:128)^M
        at org.junit.runners.Suite.runChild(Suite.java:27)^M
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)^M
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)^M
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)^M
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)^M
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)^M
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)^M
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)^M
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)^M
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)^M
        at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)^M
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)^M
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)^M
        at java.base/java.lang.Thread.run(Thread.java:866)^M
```
