### ISSUE TITLE
OpenJDK CalendarTest CalendarRegression Uncaught exception thrown in test method

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12127]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/28
java/util/Calendar/CalendarRegression.java
```
00:31:49  STDOUT:
00:31:49  CalendarRegression {
00:31:49    Test4031502 Passed
00:31:49    Test4035301 Passed
00:31:49    Test4040996 {
00:31:49      Uncaught exception thrown in test method Test4040996
00:31:49  STDERR:
00:31:49  java.lang.RuntimeException: Uncaught exception thrown in test method Test4040996
00:31:49  	at IntlTest.errImpl(IntlTest.java:198)
00:31:49  	at IntlTest.errln(IntlTest.java:185)
00:31:49  	at IntlTest.run(IntlTest.java:126)
00:31:49  	at CalendarRegression.main(CalendarRegression.java:59)
00:31:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
00:31:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
00:31:49  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:31:49  	at java.base/java.lang.Thread.run(Thread.java:853)
```

java/util/Calendar/CalendarTest.java
```
00:31:49  STDOUT:
00:31:49  CalendarTest {
00:31:49    TestGregorianChangeover Passed
00:31:49    TestMapping Passed
00:31:49    TestGenericAPI {
00:31:49      Uncaught exception thrown in test method TestGenericAPI
00:31:49  STDERR:
00:31:49  java.lang.RuntimeException: Uncaught exception thrown in test method TestGenericAPI
00:31:49  	at IntlTest.errImpl(IntlTest.java:198)
00:31:49  	at IntlTest.errln(IntlTest.java:185)
00:31:49  	at IntlTest.run(IntlTest.java:126)
00:31:49  	at CalendarTest.main(CalendarTest.java:57)
00:31:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
00:31:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
00:31:49  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:31:49  	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by pshipton** [comment]
Seems the IntlTest helper doesn't show the actual exception that occurs, and needs to be modified to show that. Created https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/35 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/292

**Comment by pshipton** [comment]
50x grinder to see if this can be recreated. https://ci.eclipse.org/openj9/view/Test/job/Grinder/1542/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Release/48
jdk_util_1
java/util/Calendar/CalendarTest.java
```
21:45:24  STDOUT:
21:45:24  CalendarTest {
21:45:24    TestGregorianChangeover Passed
21:45:24    TestMapping Passed
21:45:24    TestGenericAPI {
21:45:24      FAIL: equals/before/after failed
21:45:24      Uncaught exception thrown in test method TestGenericAPI
21:45:24  STDERR:
21:45:24  java.lang.RuntimeException: Uncaught exception thrown in test method TestGenericAPI
21:45:24  	at IntlTest.errImpl(IntlTest.java:190)
21:45:24  	at IntlTest.errln(IntlTest.java:177)
21:45:24  	at IntlTest.run(IntlTest.java:123)
21:45:24  	at CalendarTest.main(CalendarTest.java:41)
21:45:24  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:45:24  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:45:24  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:45:24  	at java.lang.reflect.Method.invoke(Method.java:498)
21:45:24  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
21:45:24  	at java.lang.Thread.run(Thread.java:826)
```
