### ISSUE TITLE
JDK16 Windows MBCS_Tests_file_cn_windows_0_FAILED NullPointerException: Cannot invoke "java.io.File.exists()" because "src" is null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12152]
Failure link
------------

From an internal build `Test_openjdk16_j9_special.functional_x86-64_windows/2`:
```
01:44:12  openjdk version "16" 2021-03-16
01:44:12  OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
01:44:12  Eclipse OpenJ9 VM AdoptOpenJDK (build master-b227feba2, JRE 16 Windows Server 2016 amd64-64-Bit Compressed References 20210306_47 (JIT enabled, AOT enabled)
01:44:12  OpenJ9   - b227feba2
01:44:12  OMR      - 4665e2f72
01:44:12  JCL      - 0599466a08 based on jdk-16+36)
```
to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
03:50:00  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=x86-64_windows_mixed&TARGET=MBCS_Tests_file_cn_windows_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MBCS_Tests_file_cn_windows_0 ...
===============================================
MBCS_Tests_file_cn_windows_0 Start Time: Sat Mar  6 03:26:30 2021 Epoch Time (ms): 1615019190503
variation: NoOptions
JVM_OPTIONS:  
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "src" is null
	at FileOperator.list(FileOperator.java:143)
	at FileOperatorWin.main(FileOperatorWin.java:58)
	at Main.main(Main.java:26)

MBCS_Tests_file_cn_windows_0_FAILED
```

**Comment by pshipton** [comment]
The test executes `functional\\MBCS_Tests\\file\\test2.bat Windows zh cn MS936`

test2.bat contains
```
if %3 == cn ( 
   SET SRC_DIR=file_%2-cn
...
%JAVA_BIN%\java Main %SRC_DIR% tmp\%SRC_DIR% "MODE" %2 %3 %4
```
This seems to compute `tmp\file_zh-cn` as the second parameter.

The code sets `File dst = new File(args[1]);` before doing
```
                fo.list(dst, 3);
                File newdir = fo.rename(dst);
                if (newdir != null) {
                    System.out.println("Renamed Directory :");
                    fo.list(newdir, 3);

                    System.out.println("Rename-back : ");
                    dst = fo.rename(newdir);

                    System.out.println("Renamed Directory :");
                    fo.list(dst, 3);               <-------- line 58
````

The rename can return null
```
  public static File rename(File src) {
    if (!src.exists())
      return null;
    if (src.isDirectory()) {
	String names[] = src.list();
	for (int i = 0; i < names.length; i++) {
	    rename(new File(src, names[i]));
	}
    }
    String name = src.getName();
    File dst = new File(src.getParent(), reverse(name));
//      System.out.println("renaming : " + src.getPath() + " to " + dst.getPath());
    src.renameTo(dst);
    return dst;
  }
```
The NPE occurs here.
```
  public static void list(File src, int indent) {
    if (!src.exists())
      return;
```

**Comment by pshipton** [comment]
Maybe some file system hiccup. If it occurs often we'll have to debug what is going on. There are some System.out.println() in the code, I'm not sure why they aren't seen in the output.
