### ISSUE TITLE
AIX jdk8_openj9-0.26.0-m1 : javax/rmi/ssl/SSLSocketParametersTest.sh.SSLSocketParametersTest : java.rmi.NoSuchObjectException

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12168]
javax/rmi/ssl/SSLSocketParametersTest.sh.SSLSocketParametersTest
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix/17/consoleFull
```
13:27:44  openjdk version "1.8.0_292"
13:27:44  OpenJDK Runtime Environment (build 1.8.0_292-202103091149-b05)
13:27:44  Eclipse OpenJ9 VM (build openj9-0.26.0-m1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210309_991 (JIT enabled, AOT enabled)
13:27:44  OpenJ9   - b227feba2
13:27:44  OMR      - 4665e2f72
13:27:44  JCL      - 1780cbc92b based on jdk8u292-b05)
```
```
14:00:34  -------------------------------------------------------------
14:00:34  Launching test for SSLSocketParametersTest
14:00:34  -------------------------------------------------------------
14:00:34  KeyStore = /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/keystore
14:00:34  TrustStore = /home/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/truststore
14:00:34  Running SSLSocketParametersTest [1]
14:00:34  ServerFactory::Calling createServerSocket(0)
14:00:34  Inside HelloImpl::runServer
14:00:34  Stub = Proxy[SSLSocketParametersTest$Hello,RemoteObjectInvocationHandler[UnicastRef2 [liveRef: [endpoint:[140.211.9.28:44417,SSLSocketParametersTest$ServerFactory@3f98c7f7,SSLSocketParametersTest$ClientFactory@bb7579f1](local),objID:[-1a3aaedf:1781749f858:-7fff, 8154199408189112208]]]]]
14:00:34  Inside HelloClient::runClient
14:00:34  ClientFactory::Calling createSocket(140.211.9.28,44417)
14:00:34  SSLSocketParametersTest [1] FAILED! Exception: java.rmi.NoSuchObjectException: no such object in table
14:00:34  java.rmi.NoSuchObjectException: no such object in table
14:00:34  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
14:00:34  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
14:00:34  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
14:00:34  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
14:00:34  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
14:00:34  	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
14:00:34  	at SSLSocketParametersTest$HelloClient.runClient(SSLSocketParametersTest.java:75)
14:00:34  	at SSLSocketParametersTest.runTest(SSLSocketParametersTest.java:137)
14:00:34  	at SSLSocketParametersTest.main(SSLSocketParametersTest.java:286)
```

**Comment by pshipton** [comment]
@andrew-m-leonard can you pls grind this and get a failure rate.

https://github.com/eclipse/openj9/issues/8515 looks related.

**Comment by andrew-m-leonard** [comment]
I did a Grinderx20 on AIX today and all passed!
The problem was also seen on Win32 and Win64, i'm waiting to try a Grinder on them as well

**Comment by andrew-m-leonard** [comment]
AIX grinder on same node as failed above: https://ci.adoptopenjdk.net/job/Grinder/7593/
Win64 grinder: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/16/console

**Comment by andrew-m-leonard** [comment]
AIX grinder showed intermittent 6 failures in 20 runs: https://ci.adoptopenjdk.net/job/Grinder/7593/
@pshipton fyi

**Comment by pshipton** [comment]
Pls try another grinder with `-Xint`

**Comment by andrew-m-leonard** [comment]
Grinder with -Xint: https://ci.adoptopenjdk.net/job/Grinder/7728/console

**Comment by andrew-m-leonard** [comment]
@pshipton https://ci.adoptopenjdk.net/job/Grinder/7728/console 2 out of 40 failed all with -Xint

**Comment by pshipton** [comment]
Is this problem also seen on Hotspot via grinder?

**Comment by andrew-m-leonard** [comment]
Hotspot grinder: https://ci.adoptopenjdk.net/job/Grinder/7829/

**Comment by JasonFengJ9** [comment]
Observed in an internal build `Test_openjdk8_j9_extended.openjdk_x86-64_windows/8/` (`win16x64rt3-3`)
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b01)
Eclipse OpenJ9 VM (build master-1e9235835, JRE 1.8.0 Windows Server 2016 amd64-64-Bit Compressed References 20210508_122 (JIT enabled, AOT enabled)
OpenJ9   - 1e9235835
OMR      - 7bff18ff5
JCL      - e0e56cb2 based on jdk8u302-b01)

[2021-05-08T07:11:10.752Z] SSLSocketParametersTest [2] FAILED! Exception: java.rmi.NoSuchObjectException: no such object in table
[2021-05-08T07:11:10.752Z] java.rmi.NoSuchObjectException: no such object in table
[2021-05-08T07:11:10.752Z] 	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
[2021-05-08T07:11:10.752Z] 	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
[2021-05-08T07:11:10.753Z] 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
[2021-05-08T07:11:10.753Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
[2021-05-08T07:11:10.753Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
[2021-05-08T07:11:10.753Z] 	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
[2021-05-08T07:11:10.753Z] 	at SSLSocketParametersTest$HelloClient.runClient(SSLSocketParametersTest.java:75)
[2021-05-08T07:11:10.753Z] 	at SSLSocketParametersTest.runTest(SSLSocketParametersTest.java:156)
[2021-05-08T07:11:10.753Z] 	at SSLSocketParametersTest.main(SSLSocketParametersTest.java:286)
```

**Comment by pshipton** [comment]
@JasonFengJ9 can you repeat it?

**Comment by pshipton** [comment]
Created a 10 x 4 grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1802/

**Comment by JasonFengJ9** [comment]
Another occurrence at an internal build JDK8 MacOS `Test_openjdk8_j9_extended.openjdk_x86-64_mac/7/` (`mac11x64rt02`):
```
[2021-05-29T04:05:01.867Z] SSLSocketParametersTest [2] FAILED! Exception: java.rmi.NoSuchObjectException: no such object in table
[2021-05-29T04:05:01.867Z] java.rmi.NoSuchObjectException: no such object in table
[2021-05-29T04:05:01.867Z] 	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
[2021-05-29T04:05:01.867Z] 	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
[2021-05-29T04:05:01.867Z] 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
[2021-05-29T04:05:01.867Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
[2021-05-29T04:05:01.867Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
[2021-05-29T04:05:01.867Z] 	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
[2021-05-29T04:05:01.867Z] 	at SSLSocketParametersTest$HelloClient.runClient(SSLSocketParametersTest.java:75)
[2021-05-29T04:05:01.867Z] 	at SSLSocketParametersTest.runTest(SSLSocketParametersTest.java:156)
[2021-05-29T04:05:01.867Z] 	at SSLSocketParametersTest.main(SSLSocketParametersTest.java:286)
```

**Comment by JasonFengJ9** [comment]
Observed at JDK8 MacOS `Test_openjdk8_j9_extended.openjdk_x86-64_mac/11/` (`osxrt8 `), so this is not AIX specific.
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b05)
Eclipse OpenJ9 VM (build master-0be9a6f3f, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210618_157 (JIT enabled, AOT enabled)
OpenJ9   - 0be9a6f3f
OMR      - b7eb96336
JCL      - be819230 based on jdk8u302-b05)
``` 
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_other_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_mac&amp;GENERATE_JOBS=true&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F157%2FOpenJDK8U-debugimage_x64_mac_openj9_2021-06-19-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F157%2FOpenJDK8U-jre_x64_mac_openj9_2021-06-19-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F157%2FOpenJDK8U-jdk_x64_mac_openj9_2021-06-19-02-30.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-mac-x64-openj9%2F157%2FOpenJDK8U-testimage_x64_mac_openj9_2021-06-19-02-30.tar.gz&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk8&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=20&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=)
```
[2021-06-19T03:01:25.250Z] Running test jdk_other_1 ...
[2021-06-19T03:01:25.250Z] ===============================================
[2021-06-19T03:01:25.250Z] jdk_other_1 Start Time: Fri Jun 18 23:01:17 2021 Epoch Time (ms): 1624071677896
[2021-06-19T03:01:25.250Z] "/Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-06-19T03:01:25.250Z] JVMSHRC005I No shared class caches available
[2021-06-19T03:01:25.250Z] JVMSHRC005I No shared class caches available
[2021-06-19T03:01:25.250Z] cache cleanup done
[2021-06-19T03:01:25.250Z] variation: Mode650
[2021-06-19T03:01:25.250Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-06-19T03:02:01.273Z] -------------------------------------------------------------
[2021-06-19T03:02:01.273Z] Launching test for SSLSocketParametersTest
[2021-06-19T03:02:01.273Z] -------------------------------------------------------------
[2021-06-19T03:02:01.273Z] KeyStore = /Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac/aqa-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/keystore
[2021-06-19T03:02:01.273Z] TrustStore = /Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac/aqa-tests/openjdk/openjdk-jdk/jdk/test/javax/rmi/ssl/truststore
[2021-06-19T03:02:01.273Z] Running SSLSocketParametersTest [1]
[2021-06-19T03:02:01.273Z] ServerFactory::Calling createServerSocket(0)
[2021-06-19T03:02:01.273Z] Inside HelloImpl::runServer
[2021-06-19T03:02:01.273Z] Stub = Proxy[SSLSocketParametersTest$Hello,RemoteObjectInvocationHandler[UnicastRef2 [liveRef: [endpoint:[9.42.99.239:53551,SSLSocketParametersTest$ServerFactory@d1988942,SSLSocketParametersTest$ClientFactory@a0b8aa41](local),objID:[-60f33884:17a2237cccb:-7fff, -2789099437545161867]]]]]
[2021-06-19T03:02:01.273Z] Inside HelloClient::runClient
[2021-06-19T03:02:01.273Z] ClientFactory::Calling createSocket(9.42.99.239,53551)
[2021-06-19T03:02:01.273Z] SSLSocketParametersTest [1] FAILED! Exception: java.rmi.NoSuchObjectException: no such object in table
[2021-06-19T03:02:01.273Z] java.rmi.NoSuchObjectException: no such object in table
[2021-06-19T03:02:01.273Z] 	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
[2021-06-19T03:02:01.273Z] 	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
[2021-06-19T03:02:01.273Z] 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
[2021-06-19T03:02:01.273Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
[2021-06-19T03:02:01.273Z] 	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
[2021-06-19T03:02:01.273Z] 	at com.sun.proxy.$Proxy0.sayHello(Unknown Source)
[2021-06-19T03:02:01.273Z] 	at SSLSocketParametersTest$HelloClient.runClient(SSLSocketParametersTest.java:75)
[2021-06-19T03:02:01.273Z] 	at SSLSocketParametersTest.runTest(SSLSocketParametersTest.java:137)
[2021-06-19T03:02:01.273Z] 	at SSLSocketParametersTest.main(SSLSocketParametersTest.java:286)
```

**Comment by pshipton** [comment]
10 x 4 grinder passed https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/103

**Comment by pshipton** [comment]
10 x 4 AIX grinder reproduced it on 3 of the 4 machines.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/105

**Comment by pshipton** [comment]
Can reproduce the failure on Windows by running jdk_other_1 instead of the individual test.
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/106/
10 x 4 which failed 33/40.

**Comment by pshipton** [comment]
This is a test problem. See https://stackoverflow.com/questions/645208/java-rmi-nosuchobjectexception-no-such-object-in-table

**Comment by JasonFengJ9** [comment]
This `java.rmi.NoSuchObjectException: no such object in table` occurred often in JDK21 runs, created
* https://github.com/adoptium/aqa-tests/pull/4721

[JDK21 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/13/consoleFull)
[JDK21 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_aarch64_linux_Personal/24/consoleFull)
[JDK21 x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_x86-64_linux_Personal/28/consoleFull)

**Comment by pshipton** [comment]
Excluded on jdk17
https://github.com/adoptium/aqa-tests/pull/5307
