### ISSUE TITLE
The Jdmpview from 8.0.6.26 does not work for system core files from older version.

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#12182]
Looks like some tags (for example J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE) are added in later releases

 $ <path>/pap6480sr6fp26-20210216_01-sdk/bin/java -version

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 8.0.6.26 - pap6480sr6fp26-20210216_01(SR6 FP26))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210216_465732 (JIT enabled, AOT enabled)
OpenJ9   - e5f4f96
OMR      - 999051a
IBM      - 358762e)
JCL - 20210108_01 based on Oracle jdk8u281-b09
 $ <path>/pap6480sr6fp26-20210216_01-sdk/bin/jdmpview -core core.20210219.173640.6055.0001.dmp

        *0 : PID: 9951 : JRE 1.8.0 Linux amd64-64 (build 8.0.6.0 - pxa6480sr6-20191107_01(SR6))

> !dumpromclasslinear 0x00007F51D04A8AE0
ROM Class 'com/fnf/agency/manageTrax/controllers/ManageTraxController' at 0x00007F51D04A8AE0
Error executing DDR command !dumpromclasslinear 0x00007F51D04A8AE0 : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
        at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
        at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
        at com.ibm.jvm.dtfjview.Session.run(Session.java:663)
        at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
        at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.RomClassWalker.allSlotsInOptionalInfoDo(RomClassWalker.java:695)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.RomClassWalker.allSlotsInObjectDo(RomClassWalker.java:155)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.LinearDumper.getAllRegions(LinearDumper.java:324)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.LinearDumper.gatherLayoutInfo(LinearDumper.java:449)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.DumpRomClassLinearCommand.run(DumpRomClassLinearCommand.java:63)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
        at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
        ... 16 more
>

**Comment by manqingl** [comment]
@keithc-ca : FYI

**Comment by pshipton** [comment]
@keithc-ca the changes are merged and delivered for the next set of releases, can this be closed?
