### ISSUE TITLE
renaissance-fj-kmeans_0_FAILED (Windows) : scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12186]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.perf_x86-32_windows/20`
```
01:06:55  openjdk version "1.8.0_292-internal"
01:06:55  OpenJDK Runtime Environment (build 1.8.0_292-internal-202103100304-b05)
01:06:55  Eclipse OpenJ9 VM (build master-c11f57cfb, JRE 1.8.0 Windows Server 2012 R2 x86-32-Bit 20210310_64 (JIT enabled, AOT enabled)
01:06:55  OpenJ9   - c11f57cfb
01:06:55  OMR      - 631fc1da2
01:06:55  JCL      - aa1907db based on jdk8u292-b05)
```
to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
02:25:43  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=perf&PLATFORM=x86-32_windows&TARGET=renaissance-fj-kmeans_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test renaissance-fj-kmeans_0 ...
===============================================
renaissance-fj-kmeans_0 Start Time: Tue Mar  9 23:17:09 2021 Epoch Time (ms): 1615360629832
variation: NoOptions
JVM_OPTIONS:  
====== fj-kmeans (jdk-concurrent) [default], iteration 0 started ======
GC before operation: completed in 212.492 ms, heap usage 68.694 MB -> 63.704 MB.
WARNING: This benchmark provides no result that can be validated.
         There is no way to check that no silent failure occurred.
====== fj-kmeans (jdk-concurrent) [default], iteration 0 completed (11907.861 ms) ======
Mar 09, 2021 11:22:00 PM org.renaissance.core.Launcher launchHarnessClass
SEVERE: Harness failed with exception: scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl@f421e481 (of class com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl)
	at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
	at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
	at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
	at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
	at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
	at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
	at org.renaissance.core.Launcher.main(Launcher.java:25)

Mar 09, 2021 11:22:00 PM org.renaissance.core.Launcher launchHarnessClass
SEVERE: Harness failed with exception: scala.MatchError: com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl@f421e481 (of class com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl)
	at org.renaissance.harness.JsonWriter.getOsInfo(ResultWriter.scala:168)
	at org.renaissance.harness.JsonWriter.getEnvironment(ResultWriter.scala:152)
	at org.renaissance.harness.JsonWriter.store(ResultWriter.scala:349)
	at org.renaissance.harness.ResultWriter.org$renaissance$harness$ResultWriter$$storeResults(ResultWriter.scala:60)
	at org.renaissance.harness.ResultWriter.beforeHarnessShutdown(ResultWriter.scala:64)
	at org.renaissance.harness.EventDispatcher.notifyBeforeHarnessShutdown(EventDispatcher.java:65)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:141)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:94)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.renaissance.core.Launcher.launchHarnessClass(Launcher.java:37)
	at org.renaissance.core.Launcher.main(Launcher.java:25)


renaissance-fj-kmeans_0_FAILED
```

**Comment by JasonFengJ9** [comment]
This appears a Windows specific failure.

**Comment by pshipton** [comment]
It's also worth checking if the test is working on Hotspot at Adopt. Some of these renaissance tests were not working.

**Comment by JasonFengJ9** [comment]
Being addressed by https://github.com/AdoptOpenJDK/openjdk-tests/issues/2471
