### ISSUE TITLE
JDK11 jdk_security_infra_0_FAILED : unexpected status of EE certificate

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12218]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.openjdk_ppc64_aix/3`
```
01:01:41  openjdk version "11.0.11" 2021-04-20
01:01:41  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+6)
01:01:41  Eclipse OpenJ9 VM AdoptOpenJDK (build master-67bdb5a35, JRE 11 AIX ppc64-64-Bit Compressed References 20210312_78 (JIT enabled, AOT enabled)
01:01:41  OpenJ9   - 67bdb5a35
01:01:41  OMR      - 2c0d1393c
01:01:41  JCL      - 8e3c671652 based on jdk-11.0.11+6)
```
rebuild the failed tests in one link:
08:36:08  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=openjdk&PLATFORM=ppc64_aix_mixed&TARGET=testList%20TESTLIST=jdk_security_infra_0,jdk_security_infra_1

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
08:32:43  ===============================================
08:32:43  Running test jdk_security_infra_0 ...
08:32:43  ===============================================
08:32:43  jdk_security_infra_0 Start Time: Sat Mar 13 07:40:13 2021 Epoch Time (ms): 1615642813840
08:32:43  "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
08:32:43  JVMSHRC005I No shared class caches available
08:32:43  JVMSHRC005I No shared class caches available
08:32:43  cache cleanup done
08:32:43  variation: Mode150
08:32:43  JVM_OPTIONS:  -XX:+UseCompressedOops 

08:33:05  --------------------------------------------------
08:33:05  TEST: security/infra/java/security/cert/CertPathValidator/certification/ComodoCA.java
08:33:05  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_ppc64_aix/openjdkbinary/j2sdk-image

08:33:05  certpath: Status of certificate (with serial number 213713858402224217355623573844556010821) is: REVOKED
08:33:05  certpath: OCSP response is signed by the target's Issuing CA
08:33:05  certpath: Constraints.permits(): Cert:       None
08:33:05  AlgParams:  None
08:33:05  NamedCurves: 
08:33:05  Variant:    generic
08:33:05  certpath: Verified signature of OCSP Response
08:33:05  certpath: OCSP response validity interval is from Fri Mar 12 04:00:50 GMT-06:00 2021 until Fri Mar 19 04:00:50 GMT-06:00 2021
08:33:05  certpath: Checking validity of OCSP response on Sat Mar 13 07:40:36 GMT-06:00 2021 with allowed interval between Sat Mar 13 07:25:36 GMT-06:00 2021 and Sat Mar 13 07:55:36 GMT-06:00 2021
08:33:05  certpath: X509CertSelector.match(SN: 3e8
08:33:05    Issuer: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK
08:33:05    Subject: CN=Hongkong Post Root CA 1, O=Hongkong Post, C=HK)
08:33:05  certpath: X509CertSelector.match: subject DNs don't match
08:33:05  java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
08:33:05  	at ValidatePathWithParams.validate(ValidatePathWithParams.java:193)
08:33:05  	at ComodoRSA.runTest(ComodoCA.java:222)
08:33:05  	at ComodoCA.main(ComodoCA.java:62)
08:33:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:33:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:33:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:33:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
08:33:05  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
08:33:05  	at java.base/java.lang.Thread.run(Thread.java:836)
08:33:05  
08:33:05  JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate

08:33:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: unexpected status of EE certificate
08:33:05  --------------------------------------------------
08:34:00  Test results: passed: 9; failed: 1
08:34:06  
08:34:06  jdk_security_infra_0_FAILED
```

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse/openj9/issues/12176, which is also closed since this isn't an OpenJ9 problem.
