### ISSUE TITLE
jtreg concurrent\ThreadPoolExecutor\ConfigChanges.java 22 not equal to 21

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12244]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_OpenJDK8/39
java\util\concurrent\ThreadPoolExecutor\ConfigChanges.java
```
07:44:33  STDOUT:
07:44:33  22 not equal to 21
07:44:33  
07:44:33  Passed = 33, failed = 1
07:44:33  
07:44:33  STDERR:
07:44:33  java.lang.Throwable
07:44:33  	at java.lang.Thread.dumpStack(Thread.java:498)
07:44:33  	at ConfigChanges.fail(ConfigChanges.java:233)
07:44:33  	at ConfigChanges.fail(ConfigChanges.java:234)
07:44:33  	at ConfigChanges.equal(ConfigChanges.java:239)
07:44:33  	at ConfigChanges.realMain(ConfigChanges.java:202)
07:44:33  	at ConfigChanges.main(ConfigChanges.java:241)
07:44:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:44:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:44:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:44:33  	at java.lang.reflect.Method.invoke(Method.java:498)
07:44:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
07:44:33  	at java.lang.Thread.run(Thread.java:823)
07:44:33  java.lang.AssertionError: Some tests failed
07:44:33  	at ConfigChanges.main(ConfigChanges.java:243)
07:44:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:44:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:44:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:44:33  	at java.lang.reflect.Method.invoke(Method.java:498)
07:44:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
07:44:33  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by hzongaro** [comment]
The symptoms for this failure appear to be quite similar to those that appear in the failure reported in issue #11899.  Might be a duplicate.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/78/ - osx1013-x86-3
jdk_util_0
```
00:23:44  STDOUT:
00:23:44  22 not equal to 21
00:23:44  
00:23:44  Passed = 32, failed = 1
00:23:44  
00:23:44  STDERR:
00:23:44  java.lang.Throwable
00:23:44  	at java.lang.Thread.dumpStack(Thread.java:499)
00:23:44  	at ConfigChanges.fail(ConfigChanges.java:233)
00:23:44  	at ConfigChanges.fail(ConfigChanges.java:234)
00:23:44  	at ConfigChanges.equal(ConfigChanges.java:239)
00:23:44  	at ConfigChanges.realMain(ConfigChanges.java:202)
00:23:44  	at ConfigChanges.main(ConfigChanges.java:241)
00:23:44  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:23:44  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:23:44  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:23:44  	at java.lang.reflect.Method.invoke(Method.java:498)
00:23:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:23:44  	at java.lang.Thread.run(Thread.java:826)
00:23:44  java.lang.AssertionError: Some tests failed
00:23:44  	at ConfigChanges.main(ConfigChanges.java:243)
00:23:44  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:23:44  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:23:44  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:23:44  	at java.lang.reflect.Method.invoke(Method.java:498)
00:23:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:23:44  	at java.lang.Thread.run(Thread.java:826)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_linux_OpenJDK19/6/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_OMR_testList_3/2
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_OMR_testList_3/5
