### ISSUE TITLE
[zos_390-64_cmprssptrs] SE80_GIT JCL_FVTest_SE80_Internal_0 AssertionError - JSE8535Tester

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12250]
Failure link
------------

From an internal ibuild `job_output.php?id=672561574`:
```
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pmz6480sr7-20210302_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20210317_467743 (JIT enabled, AOT enabled)
OpenJ9   - 7752868
OMR      - 2f626f4
IBM      - 8165371)
JCL - 20210225_01 based on Oracle jdk8u291-b05
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
PASSED: testMain
FAILED: testMain
java.lang.AssertionError: Test failed in java.lang.UNIXProcess@ab57fa4c
	at org.testng.Assert.fail(Assert.java:96)
	at tests.com.ibm.jtc.security.jse8535.JSE8535Tester.validate(JSE8535Tester.java:71)
	at tests.com.ibm.jtc.security.jse8535.JSE8535Tester.testMesg(JSE8535Tester.java:84)
	at tests.com.ibm.jtc.security.jse8535.JSE8535Tester.testMain(JSE8535Tester.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    JCL_FVTest
    Tests run: 688, Failures: 1, Skips: 0
===============================================
```
This failure was marked by other PT.

**Comment by JasonFengJ9** [comment]
I will have a look.

**Comment by JasonFengJ9** [comment]
This is a test issue. The test in question is `testMesg(r, "hwkeytool -list", "-storetype has defaulted to {0}.")`, it expects `hwkeytool -list"` output contains `-storetype has defaulted to {0}.` which is bogus, I suspect `{0}` was due to porting process.

This is an internal testcase, closing..
