### ISSUE TITLE
Jdmpview from 11.0.11+2-202102111813 does not work with system core file from older versions

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#12312]
$ ../pap/jdkxAix/bin/java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+2-202102111813)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-4fa9221e6, JRE 11 AIX ppc64-64-Bit Compressed References 20210211_908 (JIT enabled, AOT enabled)
OpenJ9   - 4fa9221e6
OMR      - a7e83c733
JCL      - 5778b50c73 based on jdk-11.0.11+2)

$ ../pap/jdkxAix/bin/jdmpview -core core.20200629.182920.25735.0001.dmp
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) :

Source : file:///.../core.20200629.182920.25735.0001.dmp
        *0 : PID: 25771 : JRE 11 Linux ppc64le-64 (build 11.0.6+10)
> context
Available contexts (* = currently selected context) :

Source : file:///.../core.20200629.182920.25735.0001.dmp
        *0 : PID: 25771 :
                JRE 11 Linux ppc64le-64 (build 11.0.6+10)

Eclipse OpenJ9 VM(JRE 11 Linux ppc64le-64-Bit Compressed References 20200122_428 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

> !dumpromclasslinear 0x00007FFF9C4CD150
ROM Class 'com/ibm/mq/MQQueueManager' at 0x00007FFF9C4CD150
Error executing DDR command !dumpromclasslinear 0x00007FFF9C4CD150 : null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:663)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoClassDefFoundError: com.ibm.j9ddr.vm29.pointer.generated.J9ROMRecordComponentShapePointer
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.DumpRomClassLinearCommand.run(DumpRomClassLinearCommand.java:62)
        at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
        at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
        at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
        at openj9.dtfj/com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
        at openj9.dtfj/com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: J9ROMRecordComponentShapePointer is not in core file.
        at openj9.dtfj/com.ibm.j9ddr.StructureReader.getPointerClassBytes(StructureReader.java:885)
        at openj9.dtfj/com.ibm.j9ddr.J9DDRClassLoader.getPointerClass(J9DDRClassLoader.java:227)

**Comment by manqingl** [comment]
@keithc-ca @pshipton : FYI

**Comment by keithc-ca** [comment]
As a workaround, you should be able to run
```
jdmpview -J-Dopenj9.dtfj.version-threshold=99 -core core.20200629.182920.25735.0001.dmp
```
which will use the DDR pointer classes from the new jdk instead of deriving them from the core file.

**Comment by manqingl** [comment]
The workaround seems working but I got a different issue.  Will dig into it.

```
> !dumpromclasslinear 0x00007FFF9C4CD150
ROM Class 'com/ibm/mq/MQQueueManager' at 0x00007FFF9C4CD150
Problem running command:
com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0x7FFFED9A40E4
```

**Comment by manqingl** [comment]
@keithc-ca I have confirmed the "-J-Dopenj9.dtfj.version-threshold=99" option works around the issue.  I also confirmed the memory fault afterwards is not related to the classloading.  It looks like it would take some time to figure out the memory fault reading issue, and I do not know when I will get the time.  For this specific issue, let's focus on the original issue.

**Comment by manqingl** [comment]
This is what I found for the following error:
`com.ibm.j9ddr.corereaders.memory.MemoryFault: Memory Fault reading 0x7FFFED9A40E4`

The above error was from the following block of code in RomClassWalker.java during the call to `recordAttributeDo`:
`
		if (romClass.optionalFlags().allBitsIn(J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE)) {
			classWalkerCallback.addSlot(clazz, SlotType.J9_SRP, cursor, "recordAttributeSRP");
			recordAttributeDo(U32Pointer.cast(cursor.get()));
			cursor = cursor.add(1);
		}`

At DDR runtime, `romClass.optionalFlags()=0x1` and `J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE=0`.

Therefore we have 2 questions here:

1. should `new UDATA(1).allBitsIn(0) == true` ?
2. Why  `J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE=0` in DDR runtime?  I guess it is supposed to be 0x800000.  Looks like the tag was defaulted to be 0 and not changed during the class file generation.  Or, the tag does not exist at all, but is defaulted to 0 at DDR runtime.

**Comment by keithc-ca** [comment]
I've reconsidered @pshipton's suggestion (https://github.com/eclipse/openj9/pull/12329#issuecomment-810604316) and agree that `allBitsIn(0)` should return `false`.

The compatibility mechanism is what yields `J9NonbuilderConstants.J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE = 0` when accessing a core file that was generated from a VM that predates the introduction of that constant. The new behavior will be that `allBitsIn(J9_ROMCLASS_OPTINFO_RECORD_ATTRIBUTE)` can only be true for a class that has the 'record' attribute (which implies the core file is from a VM that understands the 'record' concept).
