### ISSUE TITLE
TestJps testJpsPackageName Wrong package name

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12323]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.functional_x86-64_linux_Nightly/54
TestJps_0
```
FAILED: testJpsPackageName
java.lang.AssertionError: Wrong package name: 32588 org.testng.TestNG
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestJps.testJpsPackageName(TestJps.java:71)
```

**Comment by JasonFengJ9** [comment]
The failing Assertion is https://github.com/eclipse/openj9/blob/d277ed3d8a68d08d84f4f22ba79cde953babe5e2/test/functional/Java8andUp/src/org/openj9/test/attachAPI/TestJps.java#L71
