### ISSUE TITLE
Test_openjdk16_j9_extended.functional_aarch64_linux: AssertionError: Free Physical Memory size cannot be greater than total Physical Memory Size

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12353]
Build:
```
11:40:07  openjdk version "16" 2021-03-16
11:40:07  OpenJDK Runtime Environment AdoptOpenJDK-16+36-202104050826 (build 16+36)
11:40:07  Eclipse OpenJ9 VM AdoptOpenJDK-16+36-202104050826 (build openj9-0.26.0-m2, JRE 16 Linux aarch64-64-Bit Compressed References 20210405_13 (JIT enabled, AOT enabled)
11:40:07  OpenJ9   - 4ce9ec8a1
11:40:07  OMR      - b8996ac2c
11:40:07  JCL      - 8f1ec25575 based on jdk-16+36)
```
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_aarch64_linux/56/testReport/junit/org.openj9.test.management/TestOperatingSystemMXBean/runTestOSMXBean/
```
12:30:03  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
12:30:03  [TestOperatingSystemMXBean] [INFO]  Starting the OperatingSystemMXBean usage API tests........
12:30:03  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
12:30:03  [TestOperatingSystemMXBean] [INFO] Tests starting at: 1617622202921 ms.
12:30:03  [TestOperatingSystemMXBean] [INFO] Testing getTotalPhysicalMemory() & getFreePhysicalMemorySize() APIs
12:30:03  [TestOperatingSystemMXBean] [INFO] Tests finished at: 1617622202927 ms.
12:30:03  FAILED: runTestOSMXBean
12:30:03  java.lang.AssertionError: Free Physical Memory size cannot be greater than total Physical Memory Size. expected [false] but found [true]
12:30:03  	at org.testng.Assert.fail(Assert.java:96)
12:30:03  	at org.testng.Assert.failNotEquals(Assert.java:776)
12:30:03  	at org.testng.Assert.assertFalse(Assert.java:65)
12:30:03  	at org.openj9.test.management.TestOperatingSystemMXBean.test_PhysicalMemoryAPIs(TestOperatingSystemMXBean.java:263)
12:30:03  	at org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean(TestOperatingSystemMXBean.java:170)
12:30:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:30:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
12:30:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:30:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
```

**Comment by pshipton** [comment]
Seems a dup of https://github.com/eclipse/openj9/issues/12038
