### ISSUE TITLE
Jdmpview from Java 8.0.6.26 does not work with system core file from Java 8.0.5.37

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#12357]
$ <path>/sdks/pap6480sr6fp26-20210216_01-sdk/bin/jdmpview -core core.20210401.233037.3628.0001.dmp

> context
Available contexts (* = currently selected context) :

Source : file:///.../core.20210401.233037.3628.0001.dmp.zip_unpack/core.20210401.233037.3628.0001.dmp
        *0 : PID: 3628 :
                JRE 1.8.0 Windows Server 2012 R2 amd64-64

> !shrc name
!j9sharedclassconfig 0x000000000E5974B0

Error executing DDR command !shrc name : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:258)
        at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:169)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
        at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
        at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
        at com.ibm.jvm.dtfjview.Session.run(Session.java:663)
        at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
        at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/SH_CacheMap.__ccTailOffset_
        at com.ibm.j9ddr.vm29.pointer.generated.SH_CacheMapPointer._ccTail(SH_CacheMapPointer.java:321)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.dbgShrcReadConfig(ShrCCommand.java:1209)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.getSharedCacheMetadataStart(ShrCCommand.java:1311)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.run(ShrCCommand.java:105)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
        at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
        ... 16 more

**Comment by manqingl** [comment]
@keithc-ca @pshipton @hangshao0 FYI

**Comment by pshipton** [comment]
Caused by https://github.com/eclipse/openj9/pull/6883
FYI https://github.com/eclipse/openj9/pull/6984 which fixed a similar problem.

**Comment by pshipton** [comment]
@tajila fyi

**Comment by pshipton** [comment]
Note I've tagged this for the 0.26 release.

**Comment by hangshao0** [comment]
Should be able to fix in a similar way to #6984.

**Comment by pshipton** [comment]
@keithc-ca similar to https://github.com/eclipse/openj9/pull/12210, it is possible to add an automated check so access to new fields are flagged and need to be explicitly added to a compatibility table in order for the build to succeed? Adding to the compatibility table is an indication to the developer and reviewer that (a) there is a new field and (b) usage of the new field needs to be protected so that older cores continue to be supported.

**Comment by keithc-ca** [comment]
I think that's how it works now for constants. A constant that is used in DDR_VM code must appear in [superset-constants.dat](https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/data/superset-constants.dat) or [CompatibilityConstants29.dat](https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/CompatibilityConstants29.dat). It's not enough that it is defined in a native header file.

I'll think about it some more: maybe we can do something similar for fields. The problem I haven't solved is what the generated methods should do for fields that didn't always exist. To make it concrete, here is what is generated for `SH_CompositeCacheImpl * SH_CacheMap::_ccTail` now:
```
    // SH_CompositeCacheImpl* _ccTail
    @com.ibm.j9ddr.GeneratedFieldAccessor(offsetFieldName="__ccTailOffset_", declaredType="SH_CompositeCacheImpl*")
    public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException {
        return SH_CompositeCacheImplPointer.cast(getPointerAtOffset(SH_CacheMap.__ccTailOffset_));
    }

    // SH_CompositeCacheImpl* _ccTail
    public PointerPointer _ccTailEA() throws CorruptDataException {
        return PointerPointer.cast(nonNullFieldEA(SH_CacheMap.__ccTailOffset_));
    }
```
What should the implementation of those methods look like for a field that doesn't exist? You might suggest they return `SH_CompositeCacheImplPointer.NULL` and `PointerPointer.NULL`, respectively (or even just `null`). But, because we would have to check at all call sites, it's not really any better than the present situation.

**Comment by pshipton** [comment]
I don't think the implementation needs to change, getting a NoSuchFieldError is fine and better than getting `null`. I'm thinking that only fields which are "known" should get anything generated at all when building the VM. The only way you can have a method to get the field value in DDR and successfully compile the code is to add it to the "known" list. This is the trigger for the developer and reviewer to ensure that NoSuchFieldError / NoSuchMethodError is handled properly when using the new field.

**Comment by manqingl** [comment]
@pshipton will the simple catch of NoSuchFieldError give a representation which truly reflect the data structure in the memory?

**Comment by pshipton** [comment]
@manqingl it's not that simple, the developer needs to write the correct code. The problem is not writing the correct code, it's remembering to write it. If we have a known list of fields, it's easy to tell there is a new field, and have instructions that remind people they need to write the correct code when accessing a new field.

**Comment by pshipton** [comment]
It's not a perfect solution, but it's a step up from what we have now. If the developer doesn't think to write the compatibility code, and the reviewer doesn't realize there is a new field and call it out, it only gets found by service.

**Comment by keithc-ca** [comment]
To be sure I understand your comment, I think you're suggesting that we restrict the set of methods generated during a build so only those listed in 'base' or 'compatibility' files would be to DDR_VM code at build time, and the dynamically generated methods would behave like this (for absent fields mentioned in the compatibility file)?
```
    // SH_CompositeCacheImpl* _ccTail
    public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException {
        throw new NoSuchFieldError();
    }

    // SH_CompositeCacheImpl* _ccTail
    public PointerPointer _ccTailEA() throws CorruptDataException {
        throw new NoSuchFieldError();
    }
```
Unfortunately, this won't yield any reminder that code that calls `_ccTail()` needs to catch `NoSuchFieldError`.

**Comment by pshipton** [comment]
I'm suggesting not to generate these at all during the build, unless they are listed in `base` or `compatibility` files, so anything that calls `ccTail()` wouldn't compile.
```
    public SH_CompositeCacheImplPointer _ccTail() throws CorruptDataException {
        throw new NoSuchFieldError();
    }
```

**Comment by pshipton** [comment]
Note the methods would still be generated at runtime as they are now from the core file, so the runtime story doesn't change, only the OpenJ9 build story.

**Comment by keithc-ca** [comment]
What do you propose where a call to `_ccTail()` is needed? I hope you're not proposing reflection.

**Comment by pshipton** [comment]
The code would continue to call `_ccTail()` as it does now, but if `ccTail` isn't listed in the compatibility file then the method wouldn't be generated at build time and so the code would not compile.

**Comment by pshipton** [comment]
This discussion can continue in https://github.com/eclipse/openj9/issues/12370
