### ISSUE TITLE
Test_openjdk16_j9_extended.openjdk_aarch64_linux: DeleteOnExitTest.sh: RuntimeException: Test failed: cache was not used.

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12354]
Build:
```
10:13:59  openjdk version "16" 2021-03-16
10:13:59  OpenJDK Runtime Environment AdoptOpenJDK-16+36-202104050826 (build 16+36)
10:13:59  Eclipse OpenJ9 VM AdoptOpenJDK-16+36-202104050826 (build openj9-0.26.0-m2, JRE 16 Linux aarch64-64-Bit Compressed References 20210405_13 (JIT enabled, AOT enabled)
10:13:59  OpenJ9   - 4ce9ec8a1
10:13:59  OMR      - b8996ac2c
10:13:59  JCL      - 8f1ec25575 based on jdk-16+36)
```
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_aarch64_linux/19/consoleFull:
```
12:17:24  TEST: javax/imageio/stream/DeleteOnExitTest.sh
12:17:24  TEST JDK: /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image
12:17:24  
12:17:24  ACTION: shell -- Failed. Execution failed: exit code 1
12:17:24  REASON: User specified action: run shell DeleteOnExitTest.sh 
12:17:24  TIME:   3.619 seconds
12:17:24  messages:
12:17:24  command: shell DeleteOnExitTest.sh
12:17:24  reason: User specified action: run shell DeleteOnExitTest.sh 
12:17:24  elapsed time (seconds): 3.619
12:17:24  STDOUT:
12:17:24  TESTJAVA=/home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image
12:17:24  TESTSRC=/home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/javax/imageio/stream
12:17:24  TESTCLASSES=/home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdk-tests/TKG/output_16176141351257/jdk_imageio_0/work/classes/0/javax/imageio/stream/DeleteOnExitTest.d
12:17:24  tmp: /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdk-tests/TKG/output_16176141351257/jdk_imageio_0/work/classes/0/javax/imageio/stream/DeleteOnExitTest.d
12:17:24  tmpDir is /home/jenkins/workspace/Test_openjdk16_j9_extended.openjdk_aarch64_linux/openjdk-tests/TKG/output_16176141351257/jdk_imageio_0/work/classes/0/javax/imageio/stream/DeleteOnExitTest.d
12:17:24  Files before test: 1
12:17:24  iis = javax.imageio.stream.FileCacheImageInputStream@c2670bb7
12:17:24  ios = javax.imageio.stream.FileCacheImageOutputStream@e7127ede
12:17:24  Files after test: 1
12:17:24  Test fails: exception thrown!
12:17:24  STDERR:
12:17:24  Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
12:17:24  	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)
```

**Comment by pshipton** [comment]
@knn-k fyi

**Comment by pshipton** [comment]
@andrew-m-leonard does this test pass/fail on other platforms? What about Hotspot? Is the issue intermittent?

**Comment by JasonFengJ9** [comment]
Observed in an internal build `Test_openjdk11_j9_extended.openjdk_x86-64_linux/10/`
```
java version "11.0.11" 2021-04-20
Java(TM) SE Runtime Environment 11.0.10.0-IBM (build 11.0.11+9)
Eclipse OpenJ9 VM 11.0.10.0-IBM (build master-194f7f30f, JRE 11 Linux amd64-64-Bit Compressed References 20210501_69 (JIT enabled, AOT enabled)
OpenJ9   - 194f7f30f
OMR      - c4ef57d3f
JCL      - f7ecaa2df9 based on jdk-11.0.11+9)

[2021-05-01T07:37:29.035Z] Running test jdk_imageio_0 ...
[2021-05-01T07:37:29.035Z] ===============================================
[2021-05-01T07:37:29.035Z] jdk_imageio_0 Start Time: Sat May  1 03:37:25 2021 Epoch Time (ms): 1619854645632
[2021-05-01T07:37:29.035Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-05-01T07:37:29.035Z] JVMSHRC005I No shared class caches available
[2021-05-01T07:37:29.035Z] JVMSHRC005I No shared class caches available
[2021-05-01T07:37:29.035Z] cache cleanup done
[2021-05-01T07:37:29.035Z] variation: Mode150
[2021-05-01T07:37:29.035Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2021-05-01T07:46:28.119Z] --------------------------------------------------
[2021-05-01T07:46:28.119Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2021-05-01T07:46:28.120Z] STDERR:
[2021-05-01T07:46:28.120Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2021-05-01T07:46:28.120Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2021-05-01T07:46:28.120Z] --------------------------------------------------
[2021-05-01T07:48:13.983Z] Test results: passed: 189; failed: 1
[2021-05-01T07:48:35.416Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/jvmtest/openjdk/report/html/report.html
[2021-05-01T07:48:35.416Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_linux/openjdk-tests/TKG/output_16198341398570/jdk_imageio_0/work
[2021-05-01T07:48:35.416Z] Error: Some tests failed or other problems occurred.
[2021-05-01T07:48:35.416Z] 
[2021-05-01T07:48:35.416Z] jdk_imageio_0_FAILED
```

This is `JDK11` on `x86-64_linux`.

**Comment by pshipton** [comment]
@JasonFengJ9 is it easily repeatable?

**Comment by JasonFengJ9** [comment]
Launched 30x grinder on 5 different machines.
`cent6x64rt7` - 1/30 failed at `Grinder_iteration_0/334/consoleFull`
`cent6x64rt20` - 1/30 failed at `Grinder_iteration_4/278/consoleFull`
`cent6x64rt15` - 1/30 failed at `Grinder_iteration_2/299/consoleFull`
The other 2 machines passed all 30 runs.
It appears a highly intermittent failure.

**Comment by JasonFengJ9** [comment]
Observed at `job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/28/`
```
04:16:37  openjdk version "11.0.13" 2021-10-19
04:16:37  IBM Semeru Runtime Open Edition 11.0.13.0-m2a (build 11.0.13+7)
04:16:37  Eclipse OpenJ9 VM 11.0.13.0-m2a (build openj9-0.29.0-m2a, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20211006_201 (JIT enabled, AOT enabled)
04:16:37  OpenJ9   - b0023bd95
04:16:37  OMR      - aabfc12b9
04:16:37  JCL      - 136605aa8e based on jdk-11.0.13+7)

[2021-10-06T12:41:22.450Z] Running test jdk_imageio_1 ...
[2021-10-06T12:41:25.905Z] ===============================================
[2021-10-06T12:41:25.905Z] jdk_imageio_1 Start Time: Wed Oct  6 05:41:03 2021 Epoch Time (ms): 1633524063426
[2021-10-06T12:41:25.905Z] "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-10-06T12:41:25.905Z] JVMSHRC005I No shared class caches available
[2021-10-06T12:41:25.905Z] JVMSHRC005I No shared class caches available
[2021-10-06T12:41:25.905Z] cache cleanup done
[2021-10-06T12:41:25.905Z] variation: Mode650
[2021-10-06T12:41:25.905Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2021-10-06T12:48:32.772Z] --------------------------------------------------
[2021-10-06T12:48:32.772Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2021-10-06T12:48:32.772Z] STDERR:
[2021-10-06T12:48:32.772Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2021-10-06T12:48:32.772Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2021-10-06T12:50:43.163Z] jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
`job/Test_openjdk11_j9_extended.openjdk_ppc64le_linux/60/`(`sles15le-rt1-3`)
```
java version "11.0.14" 2022-01-18
IBM Semeru Runtime Certified Edition 11.0.14+9 (build 11.0.14+9)
Eclipse OpenJ9 VM 11.0.14+9 (build master-fb9389e0d, JRE 11 Linux ppc64le-64-Bit Compressed References 20220204_271 (JIT enabled, AOT enabled)
OpenJ9   - fb9389e0d
OMR      - 96a484d1b
JCL      - 0945fbe2bb based on jdk-11.0.14+9)

[2022-02-05T05:55:53.329Z] variation: Mode150
[2022-02-05T05:55:53.329Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-02-05T06:00:32.608Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2022-02-05T06:00:32.608Z] Test fails: exception thrown!
[2022-02-05T06:00:32.608Z] STDERR:
[2022-02-05T06:00:32.608Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2022-02-05T06:00:32.608Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2022-02-05T06:02:03.012Z] jdk_imageio_0_FAILED
```

**Comment by pshipton** [comment]
We've been moving this forward, but it doesn't occur often enough to get attention. Removing from milestone.

**Comment by JasonFengJ9** [comment]
Observed at JDK18 0.32 milestone 2 build - `job/Test_openjdk18_j9_extended.openjdk_s390x_linux/14/`
```
openjdk version "18" 2022-03-22
IBM Semeru Runtime Open Edition 18.0.1.0-m2 (build 18+37)
Eclipse OpenJ9 VM 18.0.1.0-m2 (build openj9-0.32.0-m2, JRE 18 Linux s390x-64-Bit Compressed References 20220406_58 (JIT enabled, AOT enabled)
OpenJ9   - 959fc5030
OMR      - ab24b6666
JCL      - ea5f594899a based on jdk-18+37)

[2022-04-07T04:56:14.101Z] variation: Mode150
[2022-04-07T04:56:14.101Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-04-07T04:59:20.629Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2022-04-07T04:59:20.629Z] STDERR:
[2022-04-07T04:59:20.629Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2022-04-07T04:59:20.629Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)
```

**Comment by JasonFengJ9** [comment]
[JDK11 0.35 rc1 internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/82/)(`win16x64rt2-8`)
```
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0-rc1 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0-rc1 (build openj9-0.35.0-rc1, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20221020_478 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)

[2022-10-20T09:14:45.289Z] variation: Mode650
[2022-10-20T09:14:45.289Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2022-10-20T09:22:52.148Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2022-10-20T09:22:52.148Z] STDERR:
[2022-10-20T09:22:52.148Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2022-10-20T09:22:52.148Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2022-10-20T09:22:52.148Z] TEST RESULT: Failed. Execution failed: exit code 1
[2022-10-20T09:22:52.148Z] --------------------------------------------------
[2022-10-20T09:24:56.483Z] Test results: passed: 195; failed: 1
[2022-10-20T09:25:14.279Z] Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16662370908054\jdk_imageio_1\report\html\report.html
[2022-10-20T09:25:14.279Z] Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.openjdk_x86-64_windows\aqa-tests\TKG\output_16662370908054\jdk_imageio_1\work
[2022-10-20T09:25:14.279Z] Error: Some tests failed or other problems occurred.
[2022-10-20T09:25:14.279Z] 
[2022-10-20T09:25:14.279Z] jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 0.36 milestone 1 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows/88/)(`win16x64rt3-4`)
```
openjdk version "11.0.18" 2023-01-17
IBM Semeru Runtime Open Edition 11.0.18.0-m1 (build 11.0.18+4)
Eclipse OpenJ9 VM 11.0.18.0-m1 (build v0.36.0-release-f98e55973, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20221201_507 (JIT enabled, AOT enabled)
OpenJ9   - f98e55973
OMR      - acdbafc4a
JCL      - acdae91f88 based on jdk-11.0.18+4)

[2022-12-01T11:51:43.207Z] variation: Mode150
[2022-12-01T11:51:43.588Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2022-12-01T11:59:45.649Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2022-12-01T11:59:45.649Z] STDERR:
[2022-12-01T11:59:45.649Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2022-12-01T11:59:45.649Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2022-12-01T12:02:01.074Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK21 ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/3/)(`p10sles021`)
```
[2023-09-22T22:08:10.778Z] variation: Mode650
[2023-09-22T22:08:10.778Z] JVM_OPTIONS:  -XX:-UseCompressedOops 

[2023-09-22T22:10:46.243Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2023-09-22T22:10:46.243Z] STDERR:
[2023-09-22T22:10:46.243Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2023-09-22T22:10:46.243Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2023-09-22T22:11:27.202Z] Test results: passed: 202; failed: 1
[2023-09-22T22:11:30.600Z] Report written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16954145511182/jdk_imageio_1/report/html/report.html
[2023-09-22T22:11:30.600Z] Results written to /home/jenkins/workspace/Test_openjdk21_j9_extended.openjdk_ppc64le_linux/aqa-tests/TKG/output_16954145511182/jdk_imageio_1/work
[2023-09-22T22:11:30.600Z] Error: Some tests failed or other problems occurred.
[2023-09-22T22:11:30.600Z] -----------------------------------
[2023-09-22T22:11:30.600Z] jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_0/8/)(`sles12s390x-svl-rt2-1`)
```
java version "11.0.23-beta" 2024-04-16
IBM Semeru Runtime Certified Edition 11.0.23+5-202403042324 (build 11.0.23-beta+5-202403042324)
Eclipse OpenJ9 VM 11.0.23+5-202403042324 (build master-3c621f26c, JRE 11 Linux s390x-64-Bit Compressed References 20240304_767 (JIT enabled, AOT enabled)
OpenJ9   - 3c621f26c
OMR      - 8bea58e95
JCL      - 7acd29681d based on jdk-11.0.23+5)

[2024-03-05T00:44:06.613Z] variation: Mode150
[2024-03-05T00:44:06.613Z] JVM_OPTIONS:  -XX:+UseCompressedOops -Xverbosegclog 

[2024-03-05T00:45:54.663Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2024-03-05T00:45:54.663Z] STDERR:
[2024-03-05T00:45:54.663Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2024-03-05T00:45:54.663Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2024-03-05T00:45:54.663Z] TEST RESULT: Failed. Execution failed: exit code 1
[2024-03-05T00:45:54.663Z] --------------------------------------------------
[2024-03-05T00:46:37.449Z] Test results: passed: 196; failed: 1
[2024-03-05T00:46:42.298Z] Report written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17095981241203/jdk_imageio_0/report/html/report.html
[2024-03-05T00:46:42.298Z] Results written to /home/jenkins/workspace/Test_openjdk11_j9_extended.openjdk_s390x_linux_testList_0/aqa-tests/TKG/output_17095981241203/jdk_imageio_0/work
[2024-03-05T00:46:42.298Z] Error: Some tests failed or other problems occurred.
[2024-03-05T00:46:42.298Z] -----------------------------------
[2024-03-05T00:46:42.298Z] jdk_imageio_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[JDK11 x86-64_windows](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.openjdk_x86-64_windows_testList_0/51/)(`win10x86-rtp-rt2-1`)
```
[2024-05-18T01:38:04.748Z] variation: Mode650
[2024-05-18T01:38:05.187Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2024-05-18T01:49:24.697Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2024-05-18T01:49:24.697Z] STDERR:
[2024-05-18T01:49:24.697Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2024-05-18T01:49:24.697Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

[2024-05-18T01:52:13.198Z] jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk24_j9_extended.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_extended.openjdk_ppc64_aix_Personal/12/consoleFull)
```
03:35:32  variation: Mode650
03:35:32  JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

03:43:54  TEST: javax/imageio/stream/DeleteOnExitTest.sh

03:43:54  STDERR:
03:43:54  Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
03:43:54  	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)

03:43:54  TEST RESULT: Failed. Execution failed: exit code 1
03:43:54  --------------------------------------------------
03:45:29  Test results: passed: 204; failed: 1

03:45:33  jdk_imageio_1_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk26_j9_extended.openjdk_ppc64le_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk26_j9_extended.openjdk_ppc64le_linux_testList_2/9/)
```
[2026-07-09T22:54:32.018Z] Running test jdk_imageio_1 ...
[2026-07-09T22:54:32.018Z] ===============================================
[2026-07-09T22:54:32.018Z] jdk_imageio_1 Start Time: Thu Jul  9 15:54:29 2026 Epoch Time (ms): 1783637669918
[2026-07-09T22:54:32.018Z] variation: Mode650
[2026-07-09T22:54:32.018Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2026-07-09T23:02:18.556Z] TEST: javax/imageio/stream/DeleteOnExitTest.sh

[2026-07-09T23:02:18.557Z] STDERR:
[2026-07-09T23:02:18.557Z] Exception in thread "main" java.lang.RuntimeException: Test failed: cache was not used.
[2026-07-09T23:02:18.557Z] 	at DeleteOnExitTest.main(DeleteOnExitTest.java:72)
```
