### ISSUE TITLE
JDK11 testRASAPI_0_FAILED - AssertionFailedError: The timestamp from the javacore was not between the timestamps taken before and after we took the dump

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12478]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.functional_ppc64_aix_testList_2/16/`
```
java version "11.0.11" 2021-04-20
Java(TM) SE Runtime Environment 11.0.11.0-IBM (build 11.0.11+8)
Eclipse OpenJ9 VM 11.0.11.0-IBM (build v0.26.0-release-b4cc246d9, JRE 11 AIX ppc64-64-Bit Compressed References 20210416_45 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 00af747b84 based on jdk-11.0.11+8)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=testRASAPI_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=functional&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=ppc64_aix&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F45%2Fibm-java-jdk_ppc64_aix_11.0.11.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F45%2Fibm-java-jre_ppc64_aix_11.0.11.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F45%2Fibm-java-testimage_ppc64_aix_11.0.11.0.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F45%2Fibm-java-debugimage_ppc64_aix_11.0.11.0.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=45&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-17T11:56:05.042Z] Running test testRASAPI_0 ...
[2021-04-17T11:56:05.042Z] ===============================================
[2021-04-17T11:56:05.042Z] testRASAPI_0 Start Time: Sat Apr 17 08:04:58 2021 Epoch Time (ms): 1618664698257
[2021-04-17T11:56:05.042Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_2/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-04-17T11:56:05.042Z] JVMSHRC005I No shared class caches available
[2021-04-17T11:56:05.042Z] JVMSHRC005I No shared class caches available
[2021-04-17T11:56:05.042Z] cache cleanup done
[2021-04-17T11:56:05.042Z] variation: NoOptions
[2021-04-17T11:56:05.042Z] JVM_OPTIONS:  

[2021-04-17T11:59:59.861Z]      [test]     [junit] Testcase: testJavaDumpWithDateAndTimeTokens took 1.118 sec
[2021-04-17T11:59:59.861Z]      [test]     [junit] 	FAILED
[2021-04-17T11:59:59.861Z]      [test]     [junit] The timestamp from the javacore was not between the timestamps taken before and after we took the dump.
[2021-04-17T11:59:59.861Z]      [test]     [junit] junit.framework.AssertionFailedError: The timestamp from the javacore was not between the timestamps taken before and after we took the dump.
[2021-04-17T11:59:59.861Z]      [test]     [junit] 	at com.ibm.jvm.ras.tests.DumpAPITokensTests.testJavaDumpWithDateAndTimeTokens(DumpAPITokensTests.java:166)
[2021-04-17T11:59:59.861Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-17T11:59:59.861Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-04-17T11:59:59.861Z]      [test]     [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-17T11:59:59.861Z]      [test]     [junit] 
[2021-04-17T11:59:59.861Z]      [test] 
[2021-04-17T11:59:59.861Z]      [test] BUILD FAILED
[2021-04-17T11:59:59.861Z]      [test] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_2/jvmtest/functional/RasapiTest/test.xml:97: Test com.ibm.jvm.ras.tests.DumpAPITokensTests failed
[2021-04-17T11:59:59.862Z]      [test] 
[2021-04-17T11:59:59.862Z]      [test] Total time: 3 minutes 53 seconds
[2021-04-17T12:00:00.692Z] 
[2021-04-17T12:00:00.692Z] BUILD FAILED
[2021-04-17T12:00:00.692Z] /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_2/jvmtest/functional/RasapiTest/test.xml:52: Java returned: 1
[2021-04-17T12:00:00.692Z] 
[2021-04-17T12:00:00.692Z] Total time: 3 minutes 54 seconds
[2021-04-17T12:00:00.692Z] 
[2021-04-17T12:00:00.692Z] testRASAPI_0_FAILED
```

**Comment by pshipton** [comment]
This is an internal machine issue, see runtimes/infrastructure/issues/5219. Also see runtimes/infrastructure/issues/5380 for the release trial triage.
