### ISSUE TITLE
AIX JVMJ9VM090I Slow response to network query

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12470]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly/380/

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_1/99
LambdaLoadTest_special_J9_5m_24
variation: Mode107-OSRG
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation 

```
GEN stderr JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN 06:35:50.913 - Found test. Project: 'openjdk.test.load' class: 'LambdaLoadTest.class' Dir: '/home/jenkins/workspace/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_1/jvmtest/system/openjdk-systemtest/openjdk.test.load/bin'
GEN 06:35:51.199 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.LambdaLoadTest'
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN stderr openjdk version "11.0.11-internal" 2021-04-20
GEN stderr OpenJDK Runtime Environment (build 11.0.11-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
GEN stderr Eclipse OpenJ9 VM (build master-22fc5113773, JRE 11 AIX ppc64-64-Bit Compressed References 20210418_687 (JIT enabled, AOT enabled)
GEN stderr OpenJ9   - 22fc5113773
GEN stderr OMR      - 0f967b721d2
GEN stderr JCL      - ba1caf576ee based on jdk-11.0.11+8)
GEN stderr 
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:497)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_2/99/
LambdaLoadTest_special_J9_5m_20
variation: Mode614
JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:counts=- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000,gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xmn512k -Xcheck:gc:vmthreads:all:quiet 
```
GEN stderr JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN 06:37:13.433 - Found test. Project: 'openjdk.test.load' class: 'LambdaLoadTest.class' Dir: '/home/jenkins/workspace/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_2/jvmtest/system/openjdk-systemtest/openjdk.test.load/bin'
GEN 06:37:13.496 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.LambdaLoadTest'
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN stderr openjdk version "11.0.11-internal" 2021-04-20
GEN stderr OpenJDK Runtime Environment (build 11.0.11-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
GEN stderr Eclipse OpenJ9 VM (build master-22fc5113773, JRE 11 AIX ppc64-64-Bit Compressed References 20210418_687 (JIT enabled, AOT enabled)
GEN stderr OpenJ9   - 22fc5113773
GEN stderr OMR      - 0f967b721d2
GEN stderr JCL      - ba1caf576ee based on jdk-11.0.11+8)
GEN stderr 
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:497)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_3/99/
MathLoadTest_all_special_5m_10
variation: Mode301
JVM_OPTIONS:  -Xgcpolicy:metronome -Xnocompressedrefs 
```
GEN stderr JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN 06:37:15.135 - Found test. Project: 'openjdk.test.load' class: 'MathLoadTest.class' Dir: '/home/jenkins/workspace/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_3/jvmtest/system/openjdk-systemtest/openjdk.test.load/bin'
GEN 06:37:15.197 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.MathLoadTest'
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN stderr openjdk version "11.0.11-internal" 2021-04-20
GEN stderr OpenJDK Runtime Environment (build 11.0.11-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
GEN stderr Eclipse OpenJ9 VM (build master-22fc5113773, JRE 11 AIX ppc64-64-Bit Compressed References 20210418_687 (JIT enabled, AOT enabled)
GEN stderr OpenJ9   - 22fc5113773
GEN stderr OMR      - 0f967b721d2
GEN stderr JCL      - ba1caf576ee based on jdk-11.0.11+8)
GEN stderr 
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:497)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_0/99/
ParallelStreamsLoadTest_special_J9_8
variation: Mode187
JVM_OPTIONS:  -Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs 
```
GEN stderr JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN 06:33:59.829 - Found test. Project: 'openjdk.test.load' class: 'ParallelStreamsLoadTest.class' Dir: '/home/jenkins/workspace/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_0/jvmtest/system/openjdk-systemtest/openjdk.test.load/bin'
GEN 06:33:59.883 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.ParallelStreamsLoadTest'
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN stderr openjdk version "11.0.11-internal" 2021-04-20
GEN stderr OpenJDK Runtime Environment (build 11.0.11-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
GEN stderr Eclipse OpenJ9 VM (build master-22fc5113773, JRE 11 AIX ppc64-64-Bit Compressed References 20210418_687 (JIT enabled, AOT enabled)
GEN stderr OpenJ9   - 22fc5113773
GEN stderr OMR      - 0f967b721d2
GEN stderr JCL      - ba1caf576ee based on jdk-11.0.11+8)
GEN stderr 
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:497)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_4/99/
DaaLoadTest_all_special_5m_9
variation: Mode187
JVM_OPTIONS:  -Xaggressive -Xgcpolicy:gencon -Xjit -Xnocompressedrefs 
```
GEN stderr JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN 06:34:14.491 - Found test. Project: 'openj9.test.load' class: 'DaaLoadTest.class' Dir: '/home/jenkins/workspace/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_4/jvmtest/system/openj9-systemtest/openj9.test.load/bin'
GEN 06:34:14.504 - Found test. Project: 'openj9.test.load' class: 'net.openj9.stf.DaaLoadTest'
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: 'Java -version' output does not start with 'java version'. Actual output was: JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration
GEN stderr openjdk version "11.0.11-internal" 2021-04-20
GEN stderr OpenJDK Runtime Environment (build 11.0.11-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
GEN stderr Eclipse OpenJ9 VM (build master-22fc5113773, JRE 11 AIX ppc64-64-Bit Compressed References 20210418_687 (JIT enabled, AOT enabled)
GEN stderr OpenJ9   - 22fc5113773
GEN stderr OMR      - 0f967b721d2
GEN stderr JCL      - ba1caf576ee based on jdk-11.0.11+8)
GEN stderr 
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:497)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

**Comment by pshipton** [comment]
@llxia fyi. A network problem, but STF could be coded to ignore the info message and continue on.

**Comment by llxia** [comment]
@Mesbah-Alam Please update STF for java version validation.

**Comment by pshipton** [comment]
I believe https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/46 is also caused by network. There are a number of occurrences of `JVMJ9VM090I Slow response to network query (160 secs), check your IP DNS configuration` in the output, including in 5.SCV.stderr, 14.SCC.stderr and 15.SCC.stderr. There is a core file, but no other diagnostics.
```
STF 06:22:21.118 - +------ Step 7 - Increasing cache size to 2mb via -Xshareclasses:adjustsoftmx option
STF 06:22:21.118 - | Run foreground process
STF 06:22:21.118 - |   Program:     /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdkbinary/j2sdk-image/bin/java
STF 06:22:21.118 - |   Mnemonic:    SL2
STF 06:22:21.118 - |   Echo:        ECHO_OFF
STF 06:22:21.118 - |   Expectation: NON_ZERO_EXIT [1] within 1m
STF 06:22:21.118 - |
STF 06:22:21.118 - Running command: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdk-tests/TKG/output_1618824330146/SC_Softmx_Increase_0/20210419-061627-SharedClassesWorkloadTest_Softmx_Increase/results/cache,adjustsoftmx=2m -Xjit -Xgcpolicy:gencon -Xnocompressedrefs
STF 06:22:21.118 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdk-tests/TKG/output_1618824330146/SC_Softmx_Increase_0/20210419-061627-SharedClassesWorkloadTest_Softmx_Increase/results/7.SL2.stderr
STF 06:22:21.118 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly_testList_2/openjdk-tests/TKG/output_1618824330146/SC_Softmx_Increase_0/20210419-061627-SharedClassesWorkloadTest_Softmx_Increase/results/7.SL2.stdout
STF 06:22:21.131 - Monitoring processes: SL2
STF 06:23:22.216 - **FAILED** Process SL2 has timed out
```

Also found the following in 4.Jvm1.stdout, but I don't think this caused the failure, as step 4 succeeded
```
STF 06:16:33.888 - Monitoring processes: Jvm1
STF 06:17:00.721 - Monitoring Report Summary:
STF 06:17:00.721 -   o Process Jvm1 ended with the expected exit code (1)
```
```
06:16:38.372 - First failure detected by thread: load-7. Not creating dumps as no dump generation is requested for this load test
06:16:38.419 - suite.getInventory().getInventoryFileRef(): openj9.test.load/config/inventories/mix/sharedclasses-mix.xml
06:16:38.420 - suite.isCreateDump() : false
06:16:38.420 - Test failed. Details recorded in execution log.
06:16:38.422 - Test failed
  Failure num.  = 1
  Test number   = 94
  Test details  = 'ArbitraryJava[net.adoptopenjdk.test.classloading.ClassMapHog run]'
  Suite number  = 0
  Thread number = 6
>>> Captured test output >>>
Test failed:
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:861)
<<<
```
