### ISSUE TITLE
JDK17 java/util/Random/RandomTestChiSquared.java - Failure of jdk.random.L64X1024MixRandom doubles(-59, -35)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12483]
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.openjdk_ppc64_aix/14/`
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment AdoptOpenJDK-17+18 (build 17+18)
Eclipse OpenJ9 VM AdoptOpenJDK-17+18 (build master-22fc51137, JRE 17 AIX ppc64-64-Bit Compressed References 20210417_36 (JIT enabled, AOT enabled)
OpenJ9   - 22fc51137
OMR      - 0f967b721
JCL      - 380dc812b6 based on jdk-17+18)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_util_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=ppc64_aix&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-aix-ppc64-openj9%2F36%2FOpenJDK-testimage_ppc64_aix_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-aix-ppc64-openj9%2F36%2FOpenJDK-jdk_ppc64_aix_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-aix-ppc64-openj9%2F36%2FOpenJDK-debugimage_ppc64_aix_openj9_2021-04-17-14-31.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk%2Fjdk-aix-ppc64-openj9%2F36%2FOpenJDK-jre_ppc64_aix_openj9_2021-04-17-14-31.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=17&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-17T20:09:34.702Z]   *** Failure of jdk.random.L64X1024MixRandom doubles(43, 67)
[2021-04-17T20:09:34.702Z]   chi-squared test failure for jdk.random.L64X1024MixRandom doubles(-59, -35): x=-9918.25 (should be in [3.03708,71.2211])
[2021-04-17T20:09:34.702Z]   testRngChiSquared glitch  chi-squared test failure for jdk.random.L64X1024MixRandom doubles(-59, -35): x=-9972.36 (should be in [3.03708,71.2211])
[2021-04-17T20:09:34.702Z]   *** Failure of jdk.random.L64X1024MixRandom doubles(-59, -35)
[2021-04-17T20:09:34.702Z] java.lang.RuntimeException: 3720 fails detected
[2021-04-17T20:09:34.702Z] 	at RandomTestChiSquared.exceptionOnFail(RandomTestChiSquared.java:60)
[2021-04-17T20:09:34.702Z] 	at RandomTestChiSquared.main(RandomTestChiSquared.java:237)
[2021-04-17T20:09:34.702Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-17T20:09:34.702Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-17T20:09:34.702Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-17T20:09:34.702Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-17T20:09:34.702Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-04-17T20:09:34.702Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
[2021-04-17T20:09:34.702Z] 
[2021-04-17T20:09:34.702Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2021-04-17T20:09:34.702Z] JavaTest Message: shutting down test
[2021-04-17T20:09:34.702Z] 
[2021-04-17T20:09:34.702Z] 
[2021-04-17T20:09:34.702Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 3720 fails detected
[2021-04-17T20:09:34.702Z] --------------------------------------------------
[2021-04-17T20:30:42.641Z] Test results: passed: 887; failed: 1
[2021-04-17T20:30:49.611Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/report/html/report.html
[2021-04-17T20:30:49.611Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_16186885972838/jdk_util_0/work
[2021-04-17T20:30:49.611Z] Error: Some tests failed or other problems occurred.
[2021-04-17T20:30:49.611Z] 
[2021-04-17T20:30:49.611Z] jdk_util_0_FAILED
```

No obvious VM code involved, need check RI behaviours.

**Comment by JasonFengJ9** [comment]
Similar `jdk.random.L64X1024MixRandom nextFloat` failure at `Test_openjdk17_j9_sanity.openjdk_s390x_linux/16/`
```
[2021-04-24T16:45:00.023Z]   poker test failure for jdk.random.L64X1024MixRandom nextFloat bit 31: x=-3668.67 (should be in [1.03,57.4])
[2021-04-24T16:45:00.023Z]   *** Failure of jdk.random.L64X1024MixRandom nextFloat
[2021-04-24T16:45:00.023Z] java.lang.RuntimeException: 10357 fails detected
[2021-04-24T16:45:00.023Z] 	at RandomTestBsi1999.exceptionOnFail(RandomTestBsi1999.java:108)
[2021-04-24T16:45:00.023Z] 	at RandomTestBsi1999.main(RandomTestBsi1999.java:453)
[2021-04-24T16:45:00.023Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-24T16:45:00.023Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[2021-04-24T16:45:00.023Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-24T16:45:00.023Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-04-24T16:45:00.023Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-04-24T16:45:00.023Z] 	at java.base/java.lang.Thread.run(Thread.java:878)
```

**Comment by pshipton** [comment]
If this hasn't re-occurred since April I think it should be closed.

**Comment by JasonFengJ9** [comment]
The failure (https://github.com/eclipse-openj9/openj9/issues/12483#issuecomment-827152563) is seen at https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/6/consoleFull

```
02:56:00  openjdk version "17-internal" 2021-09-14
02:56:00  OpenJDK Runtime Environment (build 17-internal+0-adhoc.****.BuildJDK17s390xlinuxOpenJDK17)
02:56:00  Eclipse OpenJ9 VM (build master-d3ef784535a, JRE 17 Linux s390x-64-Bit Compressed References 20210806_11 (JIT enabled, AOT enabled)
02:56:00  OpenJ9   - d3ef784535a
02:56:00  OMR      - 45440608cb0
02:56:00  JCL      - 8514182c964 based on jdk-17+34)
```
[Re-run in grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=OpenJDK17-Acceptance&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_s390x_linux_OpenJDK17%2F11%2FOpenJ9-JDK17-s390x_linux-20210806-013412.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK17_s390x_linux_OpenJDK17%2F11%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk17.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=d3ef784535a7c9cde53c6be0918432ed5f8b9ed5&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9-staging&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None)

```
03:46:20  ===============================================
03:46:20  Running test jdk_util_0 ...
03:46:20  ===============================================
03:46:20  jdk_util_0 Start Time: Fri Aug  6 03:46:09 2021 Epoch Time (ms): 1628235969786
03:46:20  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
03:46:20  JVMSHRC005I No shared class caches available
03:46:20  JVMSHRC005I No shared class caches available
03:46:20  cache cleanup done
03:46:20  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
03:46:20  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

03:58:35  --------------------------------------------------
03:58:35  TEST: java/util/Random/RandomTestBsi1999.java

03:58:35    poker test failure for jdk.random.L64X1024MixRandom nextFloat bit 31: x=-3668.67 (should be in [1.03,57.4])
03:58:35    *** Failure of jdk.random.L64X1024MixRandom nextFloat
03:58:35  java.lang.RuntimeException: 10427 fails detected
03:58:35  	at RandomTestBsi1999.exceptionOnFail(RandomTestBsi1999.java:108)
03:58:35  	at RandomTestBsi1999.main(RandomTestBsi1999.java:453)
03:58:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:58:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
03:58:35  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:58:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
03:58:35  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
03:58:35  	at java.base/java.lang.Thread.run(Thread.java:883)
03:58:35  
03:58:35  JavaTest Message: Test threw exception: java.lang.RuntimeException
03:58:35  JavaTest Message: shutting down test

03:58:35  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 10427 fails detected
03:58:35  --------------------------------------------------
03:59:50  Test results: passed: 886; failed: 1
03:59:50  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/jvmtest/openjdk/report/html/report.html
03:59:50  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/aqa-tests/TKG/output_16282330607169/jdk_util_0/work
03:59:50  Error: Some tests failed or other problems occurred.
03:59:50  
03:59:50  jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
@tajila this is one of the issues blocking jdk17 acceptance, so it needs to be resolved or excluded for the 0.28 release.

**Comment by tajila** [comment]
@pshipton This was excluded in https://github.com/adoptium/aqa-tests/pull/2741

**Comment by pshipton** [comment]
Maybe we need a separate issue. Jason added the similar java/util/Random/RandomTestBsi1999.java failure, which has the same test name jdk.random.L64X1024MixRandom, but as it's a different test it is not excluded.

**Comment by JasonFengJ9** [comment]
`java/util/Random/RandomTestBsi1999.java` failure is observed w/ a recent JDK17 (`openj9-staging`) build at `Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/3/consoleFull`
```
21:32:47  ===============================================
21:32:48  Running test jdk_util_1 ...
21:32:48  ===============================================
21:32:48  jdk_util_1 Start Time: Wed Aug 18 18:32:47 2021 Epoch Time (ms): 1629336767011
21:32:48  "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
21:32:48  JVMSHRC005I No shared class caches available
21:32:48  JVMSHRC005I No shared class caches available
21:32:48  cache cleanup done
21:32:48  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
21:32:48  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

21:58:00  --------------------------------------------------
21:58:00  TEST: java/util/Random/RandomTestBsi1999.java

21:58:00  STDERR:
21:58:00  L64X128StarStarRandom
21:58:00    poker test failure for jdk.random.L64X128StarStarRandom nextInt bit 14: x=-3749.38 (should be in [1.03,57.4])
...
21:58:00    poker test failure for jdk.random.L64X1024MixRandom nextFloat bit 31: x=-3668.67 (should be in [1.03,57.4])
21:58:00    *** Failure of jdk.random.L64X1024MixRandom nextFloat
21:58:00  java.lang.RuntimeException: 10352 fails detected
21:58:00  	at RandomTestBsi1999.exceptionOnFail(RandomTestBsi1999.java:108)
21:58:00  	at RandomTestBsi1999.main(RandomTestBsi1999.java:453)
21:58:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:58:00  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
21:58:00  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:58:00  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
21:58:00  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
21:58:00  	at java.base/java.lang.Thread.run(Thread.java:883)
21:58:00  
21:58:00  JavaTest Message: Test threw exception: java.lang.RuntimeException

21:58:00  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 10352 fails detected
21:58:00  --------------------------------------------------
22:10:48  Test results: passed: 882; failed: 1
22:11:00  Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/jvmtest/openjdk/report/html/report.html
22:11:00  Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_s390x_linux_Personal/aqa-tests/TKG/output_16293264859223/jdk_util_1/work
22:11:00  Error: Some tests failed or other problems occurred.
22:11:00  
22:11:00  jdk_util_1_FAILED
```

Created https://github.com/adoptium/aqa-tests/pull/2830 to exclude JDK17 `java/util/Random/RandomTestBsi1999.java`.
