### ISSUE TITLE
Multiple J9 implementations failed to throw NullPointerException

### ISSUE THREAD

**Issue by JavaTailor** [eclipse/openj9#12552]
### Summary
We found that multiple J9 implementations failed to handle NullPointerException correctly when declaring instance of java.lang.management.MemoryNotificationInfo and executed normally.

### How to reproduce?
We simplified the test case, and the bug can be summarized by a declaration statement, just put this declaration in an empty main function and execute it.
```
java.lang.management.MemoryNotificationInfo oo = new java.lang.management.MemoryNotificationInfo(null, null, 1);
```

The correct output should look like this, since if the parameter is NULL in the constructor of MemoryNotificationInfo, a NullPointerException will be thrown. However, the program executes normally without any exceptions in multiple implementations of J9.
```
Exception in thread "main" java.lang.NullPointerException: Null poolName
	at java.lang.management.MemoryNotificationInfo.<init>(MemoryNotificationInfo.java:152)
	at microbench.Test.main(Test.java:11)
```

```
MemoryNotificationInfo.java
public MemoryNotificationInfo(String poolName,
                              MemoryUsage usage,
                              long count) {
    if (poolName == null) {
        throw new NullPointerException("Null poolName");
    }
    if (usage == null) {
        throw new NullPointerException("Null usage");
    }

    this.poolName = poolName;
    this.usage = usage;
    this.count = count;
}
```

#### 1. Linux:
```
Ubuntu 18.04.2 LTS
CPU model: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPU cores: two octa-core CPUs
Memory: 96452 MB
```

#### Java -version output  under Linux
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
Eclipse OpenJ9 VM (build openj9-0.26.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210421_1000 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 2a5e268814 based on jdk8u292-b10)
```

```
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+12)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 9 Linux amd64-64-Bit Compressed References 20180814_248 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - feec4d2ae based on jdk-9.0.4+12)
```

```
openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13)
```

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)
```

#### 2. macOS:
```
macOS Big Sur
Version 11.2.3 (20D91)
Processor 2.3 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3
```

#### Java -version output under macOS
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201022_737 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20210120_897 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9)
```

**Comment by fjeremic** [comment]
Looks like we're missing the checks here:
https://github.com/eclipse/openj9/blob/b3b4b7e6f048a970052a4e2fff4f7eedce1a4285/jcl/src/java.management/share/classes/java/lang/management/MemoryNotificationInfo.java#L76-L98

However the API spec. doesn't say anything about having to throw NPEs if the arguments are `NULL`. This is just a difference in implementation of OpenJ9 vs. HotSpot. I suppose we can add them to be consistent.
