### ISSUE TITLE
Failures on osx1014-x86-3

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12564]
There are been some failures on osx1014-x86-3, https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_mac_OMR/875/console is the latest.
```
09:24:46  Uploading to 'osu'...
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] retry
[Pipeline] {
[Pipeline] artifactoryUpload
09:24:47  Failed sending usage report to Artifactory: java.io.IOException: Usage report is not supported on targeted Artifactory server.
[Pipeline] }
09:24:56  ERROR: Execution failed
09:24:56  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to osx1014-x86-3
09:24:56  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
09:24:56  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
09:24:56  		at hudson.remoting.Channel.call(Channel.java:1001)
09:24:56  		at hudson.FilePath.act(FilePath.java:1157)
09:24:56  		at hudson.FilePath.act(FilePath.java:1146)
09:24:56  		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
09:24:56  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:66)
09:24:56  		at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:53)
09:24:56  		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
09:24:56  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
09:24:56  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$616/0x0000000040060080.run(Unknown Source)
09:24:56  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
09:24:56  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:24:56  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:24:56  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:24:56  		at java.base/java.lang.Thread.run(Thread.java:836)
09:24:56  java.lang.NoClassDefFoundError: Could not initialize class org.jfrog.hudson.util.Credentials
09:24:56  	at java.io.ObjectStreamClass.hasStaticInitializer(Native Method)
09:24:56  	at java.io.ObjectStreamClass.computeDefaultSUID(ObjectStreamClass.java:1941)
09:24:56  	at java.io.ObjectStreamClass.access$100(ObjectStreamClass.java:79)
09:24:56  	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:275)
09:24:56  	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:273)
09:24:56  	at java.security.AccessController.doPrivileged(Native Method)
09:24:56  	at java.io.ObjectStreamClass.getSerialVersionUID(ObjectStreamClass.java:272)
09:24:56  	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:694)
09:24:56  	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
09:24:56  	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
09:24:56  	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
09:24:56  	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
09:24:56  	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
09:24:56  	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
09:24:56  	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
09:24:56  	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
09:24:56  	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
09:24:56  	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
09:24:56  	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
09:24:56  	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
09:24:56  	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
09:24:56  	at hudson.remoting.UserRequest.deserialize(UserRequest.java:290)
09:24:56  	at hudson.remoting.UserRequest.perform(UserRequest.java:189)
09:24:56  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
09:24:56  	at hudson.remoting.Request$2.run(Request.java:375)
09:24:56  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
09:24:56  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:24:56  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:24:56  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:24:56  	at java.lang.Thread.run(Thread.java:748)
09:24:56  Caused: java.io.IOException: Remote call on osx1014-x86-3 failed
09:24:56  	at hudson.remoting.Channel.call(Channel.java:1007)
09:24:56  	at hudson.FilePath.act(FilePath.java:1157)
09:24:56  	at hudson.FilePath.act(FilePath.java:1146)
09:24:56  	at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
09:24:56  	at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:66)
09:24:56  	at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:53)
09:24:56  	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
09:24:56  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
09:24:56  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$616/0x0000000040060080.run(Unknown Source)
09:24:56  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
09:24:56  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:24:56  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:24:56  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:24:56  	at java.base/java.lang.Thread.run(Thread.java:836)
```

@jdekonin fyi

See also
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_mac_OMR/874/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly_testList_1/297/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_Nightly_testList_0/282/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_mac_Nightly_testList_0/104/

**Comment by pshipton** [comment]
There are other machines having issues in the builds last night as well, or perhaps just network issues.

cent6-x64-4
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly_testList_2/111/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly_testList_0/284/

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_Nightly_testList_2/53/ - ub16x64j97
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_Nightly_testList_0/103/ - cent6-x64-7
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly_testList_0/291/ - cent6-x64-6

**Comment by pshipton** [comment]
Note I've disabled osx1014-x86-3

**Comment by jdekonin** [comment]
I've rebooted osx1014-x86-3, ub16x64j97, cent6-x64-6 and cent6-x64-7.  These systems are connected in jenkins once again.

cent6-x64-4 is currently running a job so I'll get to that when I notice its free.  Its marked offline.

**Comment by jdekonin** [comment]
cent6-x64-4 has been rebooted and is back online in jenkins.
