### ISSUE TITLE
JDK11 : TestJcmd - FAILED: testDumpsDefaultSettings

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12579]
Failure link
------------

From an internal build `Test_openjdk11_j9_extended.functional_ppc64_aix_testList_1/22/` (paix822)
```
java version "11.0.11" 2021-04-20
Java(TM) SE Runtime Environment 11.0.10.0-IBM (build 11.0.11+9-202104280109)
Eclipse OpenJ9 VM 11.0.10.0-IBM (build master-74f68cf40, JRE 11 AIX ppc64-64-Bit Compressed References 20210427_53 (JIT enabled, AOT enabled)
OpenJ9   - 74f68cf40
OMR      - 746acf8b5
JCL      - f7ecaa2df9 based on jdk-11.0.11+9)
```
[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=TestJcmd_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk11_j9_extended.functional_ppc64_aix&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=functional&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=ppc64_aix&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F53%2FOpenJDK11U-debugimage_ppc64_aix_openj9_IBM_2021-04-28-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F53%2FOpenJDK11U-testimage_ppc64_aix_openj9_IBM_2021-04-28-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F53%2FOpenJDK11U-jre_ppc64_aix_openj9_IBM_2021-04-28-01-00.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-openj9-IBM%2F53%2FOpenJDK11U-jdk_ppc64_aix_openj9_IBM_2021-04-28-01-00.tar.gz&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=git%40github.ibm.com%3Aruntimes%2Ftest.git&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk11&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=master&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=51&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=4e18ffe7-b1b1-4272-9979-99769b68bcc2&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
[2021-04-28T03:52:34.889Z] Running test TestJcmd_0 ...
[2021-04-28T03:52:34.889Z] ===============================================
[2021-04-28T03:52:34.889Z] TestJcmd_0 Start Time: Wed Apr 28 00:01:53 2021 Epoch Time (ms): 1619586113782
[2021-04-28T03:52:34.889Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_testList_1/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-04-28T03:52:34.889Z] JVMSHRC005I No shared class caches available
[2021-04-28T03:52:34.889Z] JVMSHRC005I No shared class caches available
[2021-04-28T03:52:34.889Z] cache cleanup done
[2021-04-28T03:52:34.889Z] variation: NoOptions
[2021-04-28T03:52:34.889Z] JVM_OPTIONS:  

[2021-04-28T03:53:53.420Z] FAILED: testDumpsDefaultSettings
[2021-04-28T03:53:53.420Z] java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND heapdump.20210427 expected [true] but found [false]
[2021-04-28T03:53:53.420Z] 	at org.testng.Assert.fail(Assert.java:96)
[2021-04-28T03:53:53.420Z] 	at org.testng.Assert.failNotEquals(Assert.java:776)
[2021-04-28T03:53:53.420Z] 	at org.testng.Assert.assertTrue(Assert.java:44)
[2021-04-28T03:53:53.420Z] 	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
[2021-04-28T03:53:53.420Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-04-28T03:53:53.420Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-04-28T03:53:53.420Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-28T03:53:53.420Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2021-04-28T03:53:53.420Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2021-04-28T03:53:53.420Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2021-04-28T03:53:53.420Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] ===============================================
[2021-04-28T03:53:53.420Z]     TestJcmd
[2021-04-28T03:53:53.420Z]     Tests run: 10, Failures: 1, Skips: 0
[2021-04-28T03:53:53.420Z] ===============================================
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] ===============================================
[2021-04-28T03:53:53.420Z] GeneralTest suite
[2021-04-28T03:53:53.420Z] Total tests run: 10, Failures: 1, Skips: 0
[2021-04-28T03:53:53.420Z] ===============================================
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] 
[2021-04-28T03:53:53.420Z] TestJcmd_0_FAILED
```

From the test history, this appears an intermittent failure.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly_testList_1/230
TestJcmd_0 `NoOptions`
```
FAILED: testDumpsDefaultSettings
java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20220316 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly_testList_1/258 - [cent7-ppcle-6](https://openj9-jenkins.osuosl.org/computer/cent7-ppcle-6)
TestJcmd_0
```
FAILED: testDumpsDefaultSettings
java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20220426 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_1/346 - [ub16x64j95](https://openj9-jenkins.osuosl.org/computer/ub16x64j95)
TestJcmd_0
```
FAILED: testDumpsDefaultSettings
java.lang.AssertionError: Expected string not found in jcmd output: Dump written to  AND core.20220913 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJcmd.testDumpsDefaultSettings(TestJcmd.java:338)
```
