### ISSUE TITLE
jtreg java/lang/ProcessBuilder/Basic.java IOException: Stream closed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12582]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/372
jdk_lang_0
JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -XX:+UseCompressedOops
java/lang/ProcessBuilder/Basic.java

```
22:05:47  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Some tests failed
22:05:47  REASON: User specified action: run main/othervm/timeout=300 -Djdk.lang.Process.launchMechanism=fork Basic 
22:05:47  TIME:   6.422 seconds
22:05:47  messages:
22:05:47  command: main -Djdk.lang.Process.launchMechanism=fork Basic
22:05:47  reason: User specified action: run main/othervm/timeout=300 -Djdk.lang.Process.launchMechanism=fork Basic 
22:05:47  Mode: othervm [/othervm specified]
22:05:47  elapsed time (seconds): 6.422
22:05:47  configuration:
22:05:47  STDOUT:
22:05:47  This appears to be a Unix system.
22:05:47  Testing ASCII environment values
22:05:47  Testing Latin1 environment values
22:05:47  Testing Unicode environment values
22:05:47  Testing directory .
22:05:47  Testing directory ..
22:05:47  Testing directory /
22:05:47  Testing directory /bin
22:05:47  cmdp
22:05:47  cmdp 0: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/jre/bin/java
22:05:47  cmdp 1: -XX:+DisplayVMOutputToStderr
22:05:47  cmdp 2: -classpath
22:05:47  cmdp 3: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdk-tests/TKG/output_16195754743272/jdk_lang_0/work/classes/0/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar
22:05:47  cmdp 4: Basic$JavaChild
22:05:47  cmdp 5: System.getenv()
22:05:47  envp
22:05:47  envp 0: LC_ALL=C
22:05:47  envp 1: FO=BR
22:05:47   waitFor process: delta: 25633
22:05:47  
22:05:47  Passed = 9000, failed = 1
22:05:47  
22:05:47  STDERR:
22:05:47  java.io.IOException: Stream closed
22:05:47  	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
22:05:47  	at java.io.BufferedInputStream.read(BufferedInputStream.java:269)
22:05:47  	at Basic$12.run(Basic.java:1995)
22:05:47  java.lang.AssertionError: Some tests failed
22:05:47  	at Basic.main(Basic.java:2600)
22:05:47  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:05:47  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:05:47  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:05:47  	at java.lang.reflect.Method.invoke(Method.java:498)
22:05:47  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
22:05:47  	at java.lang.Thread.run(Thread.java:821)
22:05:47  
22:05:47  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
22:05:47  JavaTest Message: shutting down test
```

**Comment by pshipton** [comment]
Try a 3 x 10x grinder https://ci.eclipse.org/openj9/job/Grinder/1786/

**Comment by keithc-ca** [comment]
Failed in https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/57.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/462
jdk_lang_1
java/lang/ProcessBuilder/Basic.java#id0

```
00:19:49  STDOUT:
00:19:49  This appears to be a Unix system.
00:19:49  Testing ASCII environment values
00:19:49  Testing Latin1 environment values
00:19:49  Testing Unicode environment values
00:19:49  Testing directory .
00:19:49  Testing directory ..
00:19:49  Testing directory /
00:19:49  Testing directory /bin
00:19:49  cmdp
00:19:49  cmdp 0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/openjdkbinary/j2sdk-image/bin/java
00:19:49  cmdp 1: -XX:+DisplayVMOutputToStderr
00:19:49  cmdp 2: -classpath
00:19:49  cmdp 3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16747093264778/jdk_lang_1/work/classes/0/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/TKG/output_16747093264778/jdk_lang_1/work/classes/0/test/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar
00:19:49  cmdp 4: Basic$JavaChild
00:19:49  cmdp 5: System.getenv()
00:19:49  envp
00:19:49  envp 0: LC_ALL=C
00:19:49  envp 1: FO=BR
00:19:49   waitFor process: delta: 49055
00:19:49  
00:19:49  Passed = 9060, failed = 1
00:19:49  
00:19:49  STDERR:
00:19:49  java.io.IOException: Stream closed
00:19:49  	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
00:19:49  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:275)
00:19:49  	at Basic$12.run(Basic.java:2197)
00:19:49  java.lang.AssertionError: Some tests failed
00:19:49  	at Basic.main(Basic.java:2829)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/66/
jdk_lang_0
java/lang/ProcessBuilder/Basic.java#id0
```
01:14:30  STDOUT:
01:14:30  This appears to be a Unix system.
01:14:30  Testing ASCII environment values
01:14:30  Testing Latin1 environment values
01:14:30  Testing Unicode environment values
01:14:30  Testing directory .
01:14:30  Testing directory ..
01:14:30  Testing directory /
01:14:30  Testing directory /bin
01:14:30  cmdp
01:14:30  cmdp 0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/openjdkbinary/j2sdk-image/bin/java
01:14:30  cmdp 1: -XX:+DisplayVMOutputToStderr
01:14:30  cmdp 2: -classpath
01:14:30  cmdp 3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16777368143959/jdk_lang_0/work/classes/0/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/TKG/output_16777368143959/jdk_lang_0/work/classes/0/test/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/aqa-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_s390x_linux_OpenJDK11/jvmtest/openjdk/jtreg/lib/jtreg.jar
01:14:30  cmdp 4: Basic$JavaChild
01:14:30  cmdp 5: System.getenv()
01:14:30  envp
01:14:30  envp 0: LC_ALL=C
01:14:30  envp 1: FO=BR
01:14:30   waitFor process: delta: 39713
01:14:30  
01:14:30  Passed = 9060, failed = 1
01:14:30  
01:14:30  STDERR:
01:14:30  java.io.IOException: Stream closed
01:14:30  	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
01:14:30  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:275)
01:14:30  	at Basic$12.run(Basic.java:2202)
01:14:30  java.lang.AssertionError: Some tests failed
01:14:30  	at Basic.main(Basic.java:2834)
```

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Release_testList_1/74/consoleFull
```
21:07:07  Running test jdk_lang_j9_0 ...
21:07:07  ===============================================
21:07:07  jdk_lang_j9_0 Start Time: Sat Jun 14 21:07:04 2025 Epoch Time (ms): 1749949624548
21:07:07  variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage Mode501
21:07:07  JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xverbosegclog 

21:08:09  TEST: java/lang/ProcessBuilder/Basic.java

21:08:09  STDERR:
21:08:09  java.io.IOException: Stream closed
21:08:09  	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
21:08:09  	at java.io.BufferedInputStream.fill(BufferedInputStream.java:214)
21:08:09  	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
21:08:09  	at Basic$13.run(Basic.java:2072)
21:08:09  java.lang.AssertionError: Some tests failed
21:08:09  	at Basic.main(Basic.java:2605)
21:08:09  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:08:09  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:08:09  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:08:09  	at java.lang.reflect.Method.invoke(Method.java:503)
21:08:09  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:08:09  	at java.lang.Thread.run(Thread.java:822)
```
