### ISSUE TITLE
Open source Apache Tomcat 8.5.24 builds but tests fail

### ISSUE THREAD

**Issue by chandrams** [eclipse/openj9#1353]
Executed Tomcat 8.5.24 tests, on both Openjdk8 and Openjdk9 builds below are the observations:

**With Openjdk8 and Openjdk9 ** - tests passed
**With Openjdk8-openj9 and Openjdk9-openj9 ** - 2 tests failed
```
test:
   [concat] Testsuites with skipped tests:
   [concat] TEST-org.apache.catalina.connector.TestMaxConnections.NIO2.txt
   [concat] TEST-org.apache.catalina.connector.TestRequest.NIO.txt
   [concat] TEST-org.apache.catalina.connector.TestRequest.NIO2.txt
   [concat] TEST-org.apache.catalina.core.TestDefaultInstanceManager.NIO.txt
   [concat] TEST-org.apache.catalina.core.TestDefaultInstanceManager.NIO2.txt
   [concat] TEST-org.apache.catalina.loader.TestWebappClassLoaderThreadLocalMemoryLeak.NIO.txt
   [concat] TEST-org.apache.catalina.loader.TestWebappClassLoaderThreadLocalMemoryLeak.NIO2.txt
   [concat] TEST-org.apache.coyote.http11.upgrade.TestUpgradeInternalHandler.NIO.txt
   [concat] TEST-org.apache.el.parser.TestELParser.NIO.txt
   [concat] TEST-org.apache.el.parser.TestELParser.NIO2.txt
   [concat] TEST-org.apache.tomcat.util.net.TestSsl.NIO.txt
   [concat] TEST-org.apache.tomcat.util.net.openssl.TestOpenSSLConf.NIO.txt
   [concat] TEST-org.apache.tomcat.util.net.openssl.TestOpenSSLConf.NIO2.txt
   [concat] TEST-org.apache.tomcat.util.net.openssl.ciphers.TestOpenSSLCipherConfigurationParser.NIO.txt
   [concat] TEST-org.apache.tomcat.util.net.openssl.ciphers.TestOpenSSLCipherConfigurationParser.NIO2.txt
   [concat] TEST-org.apache.tomcat.websocket.TestConnectionLimit.NIO.txt
   [concat] TEST-org.apache.tomcat.websocket.TestConnectionLimit.NIO2.txt
   [concat] TEST-org.apache.tomcat.websocket.TestWsWebSocketContainerWithProxy.NIO.txt
   [concat] TEST-org.apache.tomcat.websocket.TestWsWebSocketContainerWithProxy.NIO2.txt
   [concat] TEST-org.apache.tomcat.websocket.pojo.TestEncodingDecoding.NIO.txt
   [concat] TEST-org.apache.tomcat.websocket.pojo.TestEncodingDecoding.NIO2.txt
   [concat] TEST-org.apache.tomcat.websocket.server.TestWsRemoteEndpointImplServer.NIO.txt
   [concat] TEST-org.apache.tomcat.websocket.server.TestWsRemoteEndpointImplServer.NIO2.txt
   [concat] Testsuites with failed tests:
   [concat] TEST-org.apache.catalina.startup.TestWebappServiceLoader.NIO.txt
   [concat] TEST-org.apache.catalina.startup.TestWebappServiceLoader.NIO2.txt

BUILD FAILED

Failed to instantiate mock calling constructor: Exception in constructor
java.lang.RuntimeException: Failed to instantiate mock calling constructor: Exception in constructor
        at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:217)
        at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
        at org.easymock.internal.MockBuilder.createMock(MockBuilder.java:214)
        at org.easymock.internal.MockBuilder.createMock(MockBuilder.java:184)
        at org.apache.catalina.startup.TestWebappServiceLoader.init(TestWebappServiceLoader.java:56)
Caused by: java.lang.SecurityException: Uninitialized class loader
        at java.lang.ClassLoader.<init>(ClassLoader.java:254)
        at $java.lang.ClassLoader$$EnhancerByCGLIB$$a778596e.<init>(<generated>)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:207)
```

Steps to run the tomcat tests
-------------------------------
1) git clone -b tomcat git@github.com:chandrams/openjdk-tests.git
2) cd openjdk-tests/thirdparty_containers/tomcat
3) docker build -t adoptopenjdk-tomcat-test -f dockerfile/Dockerfile .
4) docker run --rm -v  java home dir of openjdk8 penj9 build:/java adoptopenjdk-tomcat-test:latest 
5) Failing test alone can be run by adding the below entry into /tomcat85/build.properties in the docker container and running "ant test"
test.entry=org.apache.catalina.startup.TestWebappServiceLoader

**Comment by JasonFengJ9** [comment]
Not able to reproduce the failure.
After step 1, step 2 command can't run. I have to `cd openjdk-tests/buildenv/docker` and run `docker build -t adoptopenjdk-tomcat-test -f Dockerfile .`. Afterwards, step 2 gives a prompt "Default Kerberos version 5 realm:", it just won't proceed regardless the input I provide.

@chandrams can you verify if the failure reproducing steps are correct?

**Comment by chandrams** [comment]
@JasonFengJ9 Sorry about that, I had used angular brackets and the text between that didn't seem to appear. I have edited the steps again in the description above, below is what I did on my machine:

_git clone -b tomcat git@github.com:chandrams/openjdk-tests.git
cd openjdk-tests/thirdparty_containers/tomcat
docker build -t adoptopenjdk-tomcat-test -f dockerfile/Dockerfile .
docker run --rm -v /home/chandrams/java_builds/openjdk8-openj9:/java adoptopenjdk-tomcat-test:latest_
