### ISSUE TITLE
JCL_FVTest_SE90 null pointer exception

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1403]
===============================================
Running test JCL_FVTest_SE90_Internal_0 ...
===============================================
test with NoOptions
{ "/testdir/sdk/xi3290/bin/java"   \
	--add-exports java.base/sun.nio.cs=ALL-UNNAMED \
	--add-exports java.base/sun.security.action=ALL-UNNAMED \
	--add-exports java.desktop/com.sun.beans.finder=ALL-UNNAMED \
	--add-exports java.base/sun.nio.ch=ALL-UNNAMED \
	--add-exports java.base/java.nio=ALL-UNNAMED \
	--add-exports java.desktop/sun.applet=ALL-UNNAMED \
	--add-exports java.desktop/sun.awt.image=ALL-UNNAMED \
	--add-exports java.desktop/sun.awt=ALL-UNNAMED \
	--add-exports java.desktop/sun.swing=ALL-UNNAMED \
	--add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
	--add-exports java.xml.bind/javax.xml.bind.annotation=ALL-UNNAMED \
	--add-exports java.xml.bind/javax.xml.bind=ALL-UNNAMED \
	--add-exports java.xml.bind/javax.xml.bind.annotation.adapters=ALL-UNNAMED \
	--add-modules java.se.ee,openj9.sharedclasses \
	-cp "/testdir/jvmtest/test/SE90/TestConfig/resources:/testdir/jvmtest/test/SE90/TestConfig/lib/testng.jar:/testdir/jvmtest/test/SE90/TestConfig/lib/jcommander.jar:/testdir/jvmtest/test/SE90/IBM_Internal/JCL_FVT/jcl_fvt.jar:/testdir/jvmtest/test/SE90/TestConfig/lib/junit4.jar" \
	org.testng.TestNG -d "/tmp/bld_380747/JCL_FVTest_SE90_Internal_0" "/testdir/jvmtest/test/SE90/IBM_Internal/JCL_FVT/testng.xml" \
	-testnames JCL_FVTest \
	-groups level.extended \
	-excludegroups d.*.linux_x86,d.*.arch.x86,d.*.os.linux,d.*.bits.32,d.*.generic-all
.....
PASSED: testMain
FAILED: testMain
java.lang.NullPointerException
	at tests.com.ibm.jtc.other.d274.d274.testMain(d274.java:39)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:90)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:65)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:558)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)

===============================================
    JCL_FVTest
    Tests run: 690, Failures: 1, Skips: 0
===============================================

**Comment by pdbain-ibm** [comment]
~10% failure rate. Fails with -Xint.
