### ISSUE TITLE
test pthreadDestructor failed on z/OS

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#1421]
console output:
```
Running make 4.1
set TEST_ROOT to /j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80
set JAVA_VERSION to SE80
set JAVA_IMPL to openj9
set JVM_VERSION to openjdk8-openj9
set JCL_VERSION to current
set JAVA_BIN to /j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin
set SPEC to zos_390-64
Running pthreadDestructor_0 ...
"/j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin/java" -version
JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pmz6480sr6-20180301_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64 Compressed References 20180309_380822 (JIT enabled, AOT enabled)
OpenJ9   - 0efec8a
OMR      - 5cbbadf
IBM      - 4453dac)
JCL - 20180209_01 based on Oracle jdk8u161-b12
make[2]: Entering directory '/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80'
make[3]: Entering directory '/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/Jsr335'
make[3]: Nothing to be done for 'pthreadDestructor_0'.
make[3]: Leaving directory '/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/Jsr335'
make[3]: Entering directory '/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/Java8andUp'

===============================================
Running test pthreadDestructor_0 ...
===============================================
test with NoOptions
{ export LIBPATH="/j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin/../lib/default:/j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin/../lib/s390x/default:/j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin/j9vm:.:/usr/lib"; "/j9vm/ebcdic/builds/bld_380822/sdk/mz6480/jre/bin/java"  -Xnocompressedrefs   \
-cp "/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/TestConfig/resources:/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/TestConfig/lib/testng.jar:/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/TestConfig/lib/jcommander.jar:/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/Java8andUp/GeneralTest.jar" \
org.testng.TestNG -d "/home/j9build/tmp/bld_380822/pthreadDestructor_0" "/j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/Java8andUp/testng.xml" \
-testnames pthreadDestructor \
-groups level.sanity \
-excludegroups d.*.zos_390-64,d.*.arch.390,d.*.os.zos,d.*.bits.64,d.*.generic-all; \
if [ $? -eq 0 ] ; then echo "pthreadDestructor_0""_PASSED"; else perl "-I/j9vm/ebcdic/builds/bld_380822/../../javatest/HEAD_379871/test/lib/perl" -mResultStore::Uploader -e "ResultStore::Uploader::upload('.',380822,533408178,'vmfarm.ottawa.ibm.com:31','results-533408178')"; echo; echo "pthreadDestructor_0""_FAILED"; fi; } 2>&1 | tee -a "/home/j9build/tmp/bld_380822/TestTargetResult"
JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /j9vm/ebcdic/builds/bld_380822/jvmtest/test/SE80/TestConfig/resources/excludes/current_exclude_SE80.txt
...
... TestNG 6.14.2 by C�dric Beust (cedric@beust.com)
...

thread attached
exitting pthread

*** failed to detach current thread rc = -2 ***
FAILED CONFIGURATION: @AfterMethod tearDown
java.lang.AssertionError: Thread successfully detached
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at j9vm.test.jni.PthreadTest.tearDown(PthreadTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

PASSED: test_destructor

===============================================
    pthreadDestructor
    Tests run: 1, Failures: 0, Skips: 0
    Configuration Failures: 1, Skips: 0
===============================================
```

The test code which trigger this error is:
```
worked = attachAndDetach();
AssertJUnit.assertTrue("Thread successfully detached", worked);
```

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by pdbain-ibm** [comment]
Will do.

**Comment by pdbain-ibm** [comment]
This is a newly ported test.  
The native code is in /runtime/tests/jni/jnitest.c
It calls pthread_key_create() with a destructor routine which calls DetachCurrentThread(vm);
The z/OS documentation https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxbd00/ptkycre.htm
says "The destructor routine **may** be called when the thread ends." (emphasis mine).

Historically, the test was excluded from Windows and z/OS, likely due to the fact that the OS
may (and apparently does) ignore the destructor.

@TianyuZuo @DanHeidinga @smlambert I suggest excluding this test from the Windows and z/OS platforms.

**Comment by DanHeidinga** [comment]
That makes sense @pdbain-ibm Can you put together the exclude?

**Comment by pdbain-ibm** [comment]
It's already there:
```
		<testCaseName>pthreadDestructor</testCaseName>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) $(JAVA_COMMAND) $(JVM_OPTIONS)  \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)GeneralTest.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) \
	-testnames pthreadDestructor \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<!-- OpenJ9 issue 1421, failed on zos -->
		<platformRequirements>^arch.arm,^os.zos</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
```
@TianyuZuo do you know why the test was running?

**Comment by DanHeidinga** [comment]
@pdbain-ibm That exclude points to this issue `<!-- OpenJ9 issue 1421, failed on zos -->`

Can you update the comment with some of the rationale on why its excluded?  Hopefully there's more context in the old internal repo where this was originally excluded.

Also, if it was excluded on windows, we should likely update this exclude to remove windows as well.

**Comment by pdbain-ibm** [comment]
Will do.
BTW, it's not clear why the test was excluded on Windows, since the test runs fine on Windows now.
