### ISSUE TITLE
IBM HealthCenter agent does not run on OpenJ9 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1538]
Tried it on Windows, installing the wa64-3.0.14.20171017 agent.

java -Xhealthcenter results in the following 
```
Mar 26, 2018 10:58:35 AM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean <init>
INFO: Agent version "3.0.14.20171017"
Mar 26, 2018 10:58:35 AM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
INFO: IIOP will be listening on the next available system assigned port. Use com.ibm.java.diagnostics.healthcenter.agent.iiop.port to specify a port
Mar 26, 2018 10:58:35 AM java.io.ObjectInputStream filterCheck
INFO: ObjectInputFilter REJECTED: class javax.rmi.CORBA.Stub, array length: -1, nRefs: 5, depth: 2, bytes: 157, ex: n/a
Mar 26, 2018 10:58:35 AM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
SEVERE: Health Center agent failed to start.
java.io.IOException: Cannot bind to URL [rmi://LAPTOP-5I5SNPG5:1972/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.ServerException: RemoteException occurred in server thread; nested exception is:
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.io.InvalidClassException: filter status: REJECTED]
        at javax.management.remote.rmi.RMIConnectorServer.newIOException(RMIConnectorServer.java:828)
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:433)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean.createJMXConnector(HCLaunchMBean.java:678)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean.startMBeanServer(HCLaunchMBean.java:462)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean$JmxStarterThread.run(HCLaunchMBean.java:267)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ServerException: RemoteException occurred in server thread; nested exception is:
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.io.InvalidClassException: filter status: REJECTED]
        at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:161)
        at com.sun.jndi.toolkit.url.GenericURLContext.bind(GenericURLContext.java:228)
        at javax.naming.InitialContext.bind(InitialContext.java:425)
        at javax.management.remote.rmi.RMIConnectorServer.bind(RMIConnectorServer.java:645)
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:428)
        ... 3 more
Caused by: java.rmi.ServerException: RemoteException occurred in server thread; nested exception is:
        java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.io.InvalidClassException: filter status: REJECTED
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:393)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(AccessController.java:732)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$7.00000000140AEBA0.run(Unknown Source)
        at java.security.AccessController.doPrivileged(AccessController.java:666)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:812)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:375)
        at sun.rmi.registry.RegistryImpl_Stub.bind(RegistryImpl_Stub.java:68)
        at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:155)
        ... 7 more
Caused by: java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is:
        java.io.InvalidClassException: filter status: REJECTED
        at sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:78)
        at sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:472)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:299)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(AccessController.java:732)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$7.00000000140AEBA0.run(Unknown Source)
        at java.security.AccessController.doPrivileged(AccessController.java:666)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:812)
Caused by: java.io.InvalidClassException: filter status: REJECTED
        at java.io.ObjectInputStream.filterCheck(ObjectInputStream.java:1355)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1975)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1982)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2139)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1673)
        at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:514)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:452)
        at sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:76)
        ... 15 more

Mar 26, 2018 10:58:35 AM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean startAgent
INFO: Health Center agent did not start correctly.
```

**Comment by pshipton** [comment]
Using the same version on IBM Java works
```
Mar 26, 2018 6:28:30 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean <init>
INFO: Agent version "3.0.14.20171017"
Mar 26, 2018 6:28:31 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
INFO: IIOP will be listening on the next available system assigned port. Use com.ibm.java.diagnostics.healthcenter.agent.iiop.port to specify a port
Mar 26, 2018 6:28:31 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean startAgent
INFO: Health Center agent started on port 1972.
```

**Comment by DanHeidinga** [comment]
The error looks very similar to:
https://www.ibm.com/developerworks/community/forums/html/topic?id=ac3e5db4-fba9-4348-a213-2a08feb6625d&ps=10

and https://xap-issues.atlassian.net/browse/XAP-13167 which offers a potential workaround which massaged a bit to the following might work:

```
-Dsun.rmi.registry.registryFilter=java.**;javax.**;com.ibm.**
```

**Comment by pshipton** [comment]
> `-Dsun.rmi.registry.registryFilter=java.**;javax.**;com.ibm.**`

works

```
 bin/java "-Dsun.rmi.registry.registryFilter=java.**;javax.**;com.ibm.**" -Xhealthcenter
Mar 26, 2018 11:27:18 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean <init>
INFO: Agent version "3.0.14.20171017"
Mar 26, 2018 11:27:18 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
INFO: IIOP will be listening on the next available system assigned port. Use com.ibm.java.diagnostics.healthcenter.agent.iiop.port to specify a port
Mar 26, 2018 11:27:18 PM com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean startAgent
INFO: Health Center agent started on port 1972.
```

**Comment by pshipton** [comment]
> works

I didn't notice earlier, but the OpenJ9 VM didn't exit when the healthcenter agent was started, but it should have.

**Comment by pshipton** [comment]
`-Dsun.rmi.registry.registryFilter=javax.**` is sufficient to avoid the stack trace initially reported.

**Comment by sxa555** [comment]
Tagging in @tobespc for awareness

**Comment by pshipton** [comment]
I'll just mention here that somebody noted there isn't currently any healthcenter agent for OSX.

**Comment by kgibm** [comment]
Note that in my tests at https://github.com/AdoptOpenJDK/openjdk-build/issues/692#issuecomment-476370646, `-Dsun.rmi.registry.registryFilter*` was not needed and the JVM does stop gracefully.

**Comment by Flandoll** [comment]
@kgibm I seem to need `-Dsun.rmi.registry.registryFilter=javax.**` when using jdk8 on win10 system, and the process will not stop automatically.
If I use jdk12 and add the system variable `CLASSPATH=F:\wa64\lib\ext\healthcenter.jar` then run `java -Xhealthcenter -version` will get an error
```
PS D:\AdoptOpenJDK\jdk-12+33\bin> ./java -Xhealthcenter -version
3月 27, 2019 12:04:48 上午 com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean <init>
信息: Agent version "3.0.11.20161017"
3月 27, 2019 12:04:48 上午 com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
信息: IIOP will be listening on the next available system assigned port. Use com.ibm.java.diagnostics.healthcenter.agent.iiop.port to specify a port
3月 27, 2019 12:04:48 上午 com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean createJMXConnector
严重: Health Center agent failed to start.
java.net.MalformedURLException: Unsupported protocol: iiop
        at java.management/javax.management.remote.JMXConnectorServerFactory.newJMXConnectorServer(JMXConnectorServerFactory.java:320)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean.createJMXConnector(HCLaunchMBean.java:673)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean.startMBeanServer(HCLaunchMBean.java:462)
        at com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean$JmxStarterThread.run(HCLaunchMBean.java:267)

3月 27, 2019 12:04:48 上午 com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean startAgent
信息: Health Center agent did not start correctly.
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.13.0, JRE 12 Windows 10 amd64-64-Bit Compressed References 20190320_32 (JIT enabled, AOT enabled)
OpenJ9   - caeb51f87
OMR      - 33a33ff2
JCL      - 419f571019 based on jdk-12+33)
```

**Comment by kgibm** [comment]
@Flandoll It's not beautiful, but you could try `-Xbootclasspath` instead of `CLASSPATH` as per my comment in the other issue.

**Comment by pshipton** [comment]
FWIW, this is what I did to get HealthCenter running on a Java 11 build. It would also work to get the latest agent for OpenJ9 Java 8, just copy the files to the same directories. On Java 8, changing from iiop isn't required, nor the `-Xbootclasspath/a:` option.

Download a recent IBM Java 8 build from https://developer.ibm.com/javasdk/downloads/sdk8/

Copy the following files from the Java 8 build to the Java 11 build.
jre/bin/healthcenter.dll to bin
jre/bin/hcapiplugin.dll to bin
jre/lib/healthcenter.properties to lib
jre/lib/ext/healthcenter.jar to lib

Edit the healthcenter.properties file and set
`com.ibm.java.diagnostics.healthcenter.agent.transport=jrmp` since iiop doesn't work for Java 11.

Enable it as follows 
`bin\java -Xhealthcenter -Xbootclasspath/a:lib/healthcenter.jar -Dsun.rmi.registry.registryFilter=javax.**`

**Comment by c-koell** [comment]
Hi.

I have tried it as described ...
I am using a following JDK
````
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200116_435 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 104cab2452 based on jdk-11.0.6+10)
````

I have copied the jars and dll's from following ibm jdk
````
java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 8.0.5.40 - pwa6480sr5fp40-20190807_01(SR5 FP40))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20190802_424001 (JIT enabled, AOT enabled)
OpenJ9   - 106f6ce
OMR      - fe07f6f
IBM      - af2a365)
JCL - 20190712_01 based on Oracle jdk8u221-b11
````

If i run java -Xhealthcenter -Xbootclasspath/a:lib/healthcenter.jar -version
i get follwing output
````
Ausnahmebedingung in Thread "main"# START NON-TRANSLATABLEjava.lang.NoClassDefFoundError: com.ibm.java.diagnostics.healthcenter.agent.mbean.HealthCenterOptionHandler
Caused by: java.lang.ClassNotFoundException: com.ibm.java.diagnostics.healthcenter.agent.mbean.HealthCenterOptionHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
Ausnahmebedingung in Thread "main"# START NON-TRANSLATABLEjava.lang.NoClassDefFoundError: com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean
Caused by: java.lang.ClassNotFoundException: com.ibm.java.diagnostics.healthcenter.agent.mbean.HCLaunchMBean
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200116_435 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 104cab2452 based on jdk-11.0.6+10)
````

Did I forget something?

**Comment by keithc-ca** [comment]
See https://github.com/eclipse/openj9/pull/12262 and related pull requests.

**Comment by kgibm** [comment]
> Copy the following files from the Java 8 build to the Java 11 build.
> jre/bin/healthcenter.dll to bin
> jre/bin/hcapiplugin.dll to bin
> jre/lib/healthcenter.properties to lib
> jre/lib/ext/healthcenter.jar to lib

Another user hit some issues trying [the workaround](https://github.com/eclipse-openj9/openj9/issues/1538#issuecomment-577894672) on Linux:

1. The first two copies should be to `bin` rather than `lib` on Linux, and
2. `-Xbootclasspath/a` must be an absolute path if `java` isn't started from `$JAVA_HOME`

Example with OpenLiberty and Semeru 11 on Linux:

```
$ podman run --rm -v /mnt/host:/mnt/host --user root -it icr.io/appcafe/open-liberty:full-java11-openj9-ubi bash
[...]
$ cp -r /mnt/host/work/ibmjava/linux/8.0.7.16/jre/ibm-java-x86_64-80/ /tmp/
$ cp /tmp/ibm-java-x86_64-80/jre/lib/amd64/libhealthcenter.so /opt/java/openjdk/lib/
$ cp /tmp/ibm-java-x86_64-80/jre/lib/amd64/libhcapiplugin.so /opt/java/openjdk/lib/
$ cp /tmp/ibm-java-x86_64-80/jre/lib/healthcenter.properties /opt/java/openjdk/lib/
$ cp /tmp/ibm-java-x86_64-80/jre/lib/ext/healthcenter.jar /opt/java/openjdk/lib/
$ printf -- "-Xhealthcenter:level=headless\n-Xbootclasspath/a:/opt/java/openjdk/lib/healthcenter.jar\n-Dsun.rmi.registry.registryFilter=javax.**\n" > /config/jvm.options
$ sed -i 's/transport=iiop/transport=jrmp/g' /opt/java/openjdk/lib/healthcenter.properties
$ /opt/ol/wlp/bin/server run

[Tue 18 Oct 2022 04:06:22 PM UTC] com.ibm.diagnostics.healthcenter.headless INFO: 4.0.1
```
