### ISSUE TITLE
JCL_Test_SE90+FAILED: test_getModifiers_classTypes 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1582]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/3/

```
FAILED: test_getModifiers_classTypes
java.lang.AssertionError: One or more tests failed:
Incorrect modifiers for org.openj9.test.java.lang.Test_Class$7. Expected <8>, Actual <0>.

	at org.testng.Assert.fail(Assert.java:96) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_Class.test_getModifiers_classTypes(Test_Class.java:1156) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10-internal/Native Method) from jrt:/java.base
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10-internal/NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10-internal/DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.lang.reflect.Method.invoke(java.base@10-internal/Method.java:564) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@ca632023(file:/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
```

**Comment by pshipton** [comment]
This has been an excluded test for Java 9 and has been excluded for 10 as well.

**Comment by mikezhang1234567890** [comment]
The error in test corresponds to this class: https://github.com/eclipse/openj9/blob/9329b7b997c923855d9f83ac54ae8cd3d1853fec/test/functional/Java8andUp/src_90/org/openj9/test/java/lang/Test_Class.java#L2798-L2799

Testing the `getModifers()` method on that class on a HotSpot build for Java 9 and 10 also results in an actual value of `0` for the class above, so I think we just need to update our test code.
