### ISSUE TITLE
java.lang.IllegalArgumentException: Constant pool index out of bounds, reading Annotations

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#1588]
Issue originally raised at AdoptOpenJDK, but seems like an openj9 issue, so raising it here (originally sser raised issue from Ingo60):

When there are a lot of custom annotations on a class, and later you want to read the annotations from the class file, the following happens (Open J9 JDK9, JDK10, linux x64):

java.lang.IllegalArgumentException: Constant pool index out of bounds
at sun.reflect.annotation.AnnotationParser.parseAnnotations(java.base@10-adoptopenjdk/AnnotationParser.java:77)
at java.lang.Class.getAnnotationCache(java.base@10-adoptopenjdk/Class.java:2646)
at java.lang.Class.getAnnotation(java.base@10-adoptopenjdk/Class.java:2294)

I'd provide an example if needed (this would be quite a bit of work though, since the annotations are compiler generated), however, I'm not even sure this is the right place to post this.

This used to work in Open j9 jdk8.

**Comment by Ingo60** [comment]
Original Poster here.

Clarification: the annotation parser is apparently wrong in all Open J9 versions I tested:

    OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0
    OpenJDK9-OPENJ9_x64_Linux_jdk-9.181
    OpenJDK10-OPENJ9_x64_Linux_20182903

It doesn't matter whether the class with the annotation was compiled with an Open J9 compiler or any other compiler. Whether the exception is raised depends solely on the JVM the annotation parsing is running under: if it's Open J9, it raises the exception, elsewise it works.

**Comment by Ingo60** [comment]
Here's code to try:

https://github.com/Frege/frege/blob/master/frege/runtime/Meta.java
https://github.com/Frege/frege/blob/master/tests/comp/Annotations.java

Here's a sample session (the `j9` is a link to the Open J9 java binary):

	ingo@freguntu:~/dev/test$ j9 -version
	openjdk version "1.8.0_162"
	OpenJDK Runtime Environment (build 1.8.0_162-b12)
	Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
	OpenJ9   - e24e8aa9
	OMR      - 3e8296b4
	JCL      - ee1e77df1d based on jdk8u162-b12)
       
	ingo@freguntu:~/dev/test$ javac -version
	javac 9-ea

	ingo@freguntu:~/dev/test$ javac -d build -source 1.8 -target 1.8 tests/comp/Annotations.java 
	warning: [options] bootstrap class path not set in conjunction with -source 1.8
	1 warning

	ingo@freguntu:~/dev/test$ java -version
	java version "9-ea"
	Java(TM) SE Runtime Environment (build 9-ea+99-jigsaw-nightly-h4279-20160114)
	Java HotSpot(TM) 64-Bit Server VM (build 9-ea+99-jigsaw-nightly-h4279-20160114, mixed mode)

	ingo@freguntu:~/dev/test$ java -cp build tests.comp.Annotations
	annotation present: true

	ingo@freguntu:~/dev/test$ j9 -cp build tests.comp.Annotations
	Exception in thread "main" java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Constant pool index out of bounds
		at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:77)
		at java.lang.Class.getAnnotationCache(Class.java:2447)
		at java.lang.Class.getAnnotation(Class.java:2095)
		at tests.comp.Annotations.main(Annotations.java:7295)
	Caused by: java.lang.IllegalArgumentException: Constant pool index out of bounds
		at sun.reflect.ConstantPool.getClassAt0(Native Method)
		at sun.reflect.ConstantPool.getClassAt(ConstantPool.java:37)
		at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:244)
		at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
		at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
		... 3 more

**Comment by fengxue-IS** [comment]
Looking into this
