### ISSUE TITLE
Windows _extended test failures on jdk8/9 

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#1608]
Failures on Windows64 extended testing in : 
cmdLineTester_verbosetest_0
cmdLineTester_verbosetest_3
cmdLineTester_verbosetest_6

```
[ERR] [TestNG] [ERROR] java.lang.IllegalArgumentException: InputStream cannot be null
[ERR] Exception in thread "main" java.lang.NullPointerException
[ERR] 	at org.testng.TestNG.getStatus(TestNG.java:211)
[ERR] 	at org.testng.TestNG.main(TestNG.java:1324)
```

This is using JDK8/9 variants using the latest from openj9, openj9-omr and openjdk extensions repos.  I haven't tested on jdk10.

**Comment by DanHeidinga** [comment]
Are you able to confirm whether these tests have ever passed on Windows?  

As we migrate the tests and platforms to OpenJ9, we've sometimes hit test failures where the test is excluded on a platform in the internal builds.

**Comment by jdekonin** [comment]
Currently I can only see this internally as eclipse/openj9 doesn't have windows machines available for testing.  But with access to internal build/test resources, I was able to track it back to March 15th for the last passing run.  Which then narrowed the shas to be between 39fd3df74842 and dbb333dde8fb.

A commit that obviously stands out is
https://github.com/eclipse/openj9/commit/b3b3e34f27b7
@TianyuZuo, can you please review?

**Comment by TianyuZuo** [comment]
investigating

**Comment by DanHeidinga** [comment]
This occurred in a build over the weekend: https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-win_x86-OpenJ9/8/consoleText

on many tests:
```
TestManagementAgent_SE80_0_FAILED
TestFileLocking_SE80_0_FAILED
gcNotificationTest_GenCon_0_FAILED
...
```
to name a few.

**Comment by DanHeidinga** [comment]
fyi @llxia

**Comment by llxia** [comment]
I think it is related to PR #1957. It seems that due to the path change, the test cannot find exclude file.
fyi @Ailloviee, could you rollback your change? Thanks.

**Comment by pshipton** [comment]
@llxia you can do this via the Revert button in #1957. Or are you looking for a partial reversion?
