### ISSUE TITLE
JDK10 JLM_Tests_interface FAILED

### ISSUE THREAD

**Issue by renfeiw** [eclipse/openj9#1626]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/8/tapResults/

```
FAILED: testGetMBeanInfo
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at org.openj9.test.java.lang.management.TestRuntimeMXBean.testGetMBeanInfo(TestRuntimeMXBean.java:625)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@10-internal/Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)



FAILED: testGetMBeanInfo
java.lang.AssertionError: expected:<14> but was:<16>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at org.openj9.test.java.lang.management.TestThreadMXBean.testGetMBeanInfo(TestThreadMXBean.java:1324)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@10-internal/Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by renfeiw** [comment]
java -version
```
17:26:48 [Test] "/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/build/linux-ppc64le-normal-server-release/images/jdk/bin/java" -version
17:26:48 [Test] openjdk version "10-internal" 2018-03-20
17:26:48 [Test] OpenJDK Runtime Environment (build 10-internal+0-adhoc.jenkins.PullRequest-Sanity-JDK10-linuxppc-64cmprssptrsle-OpenJ9)
17:26:48 [Test] Eclipse OpenJ9 VM (build HEAD-8c2ef91, JRE 10 Linux ppc64le-64 Compressed References 20180405_8 (JIT enabled, AOT enabled)
17:26:48 [Test] OpenJ9   - 8c2ef91
17:26:48 [Test] OMR      - 1c979db
17:26:48 [Test] JCL      - 7b778ff based on jdk-10+46)
```

**Comment by DanHeidinga** [comment]
@keithc-ca Can you take a look at this?  I know you've been involved with the MXBean impl and tests previously

**Comment by keithc-ca** [comment]
These results should be expected as the RuntimeMXBean and ThreadMXBean interfaces for Java 10 have changed relative to Java 9.

RuntimeMXBean adds a new method:
```
long getPid();
```
which is presumably supported by at least one additional attribute: hence the test failure.

ThreadMXBean has two new methods:
```
ThreadInfo[] dumpAllThreads(boolean lockedMonitors, boolean lockedSynchronizers, int maxDepth);
ThreadInfo[] getThreadInfo(long[] ids, boolean lockedMonitors, boolean lockedSynchronizers);
```
which accounts for the two operations not expected by the test.

**Comment by keithc-ca** [comment]
I expect #10010 to fix this.
