### ISSUE TITLE
Annotation testing failures

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#1765]
Running "_sanity" testing on Windows 2012 is now failing.  The sha tested against is a31cbae7, the last good sha was : 66fc23ae

Diff : https://github.com/eclipse/openj9/compare/66fc23ae...a31cbae7

01:20:36         =========================================== ...   (more...)
01:20:36         ===============================================
01:20:36         GeneralTest suite
01:20:36         Total tests run: 644, Failures: 27, Skips: 0
01:20:36         ===============================================

Tests :
org.openj9.test.annotation.Test_Annotation.*
org.openj9.test.annotationPackage.Test_PackageAnnotation.test_elementFormDefault
org.openj9.test.annotationPackage.Test_PackageAnnotation.test_elementFormDefault
org.openj9.test.annotationPackage.Test_PackageAnnotation2.test_isAnnotationPresent
org.openj9.test.annotationPackage.Test_PackageAnnotation2.test_isAnnotationPresent

**Comment by pshipton** [comment]
Is the failure on Java 8 or Java 9?

**Comment by pshipton** [comment]
Joe said Java 9. It happens on Jenkins builds but not Axxon.

**Comment by pshipton** [comment]
The failure appears intermittent.

**Comment by pshipton** [comment]
```
01:20:36         FAILED: test_package_Annotation_annotation
01:20:36         org.openj9.test.annotation.AnnotationNotFoundException: ValueAnnotation not found on package org.openj9.test.annotation
01:20:36         	at org.openj9.test.annotation.Test_Annotation.test_package_Annotation_annotation(Test_Annotation.java:253) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/functional/Java8andUp/GeneralTest.jar)
01:20:36         	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9.0.4-internal/Native Method) from jrt:/java.base
01:20:36         	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9.0.4-internal/NativeMethodAccessorImpl.java:62) from jrt:/java.base
01:20:36         	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9.0.4-internal/DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
01:20:36         	at java.lang.reflect.Method.invoke(java.base@9.0.4-internal/Method.java:564) from jrt:/java.base
01:20:36         	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
01:20:36         	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@a9fd01a2(file:/C:/Users/j9build/jenkins/workspace/Test-Sanity-JDK9-win_x86-64_cmprssptrs/openj9/jvmtest/TestConfig/lib/testng.jar)
```

**Comment by jdekonin** [comment]
Occurs on JDK8 builds as well.  Hit the same 2012 machine, win2012x64rt3.

**Comment by vsebe** [comment]
Test passes on a Windows 7(win7x64rt2) machine on JDK8.

**Comment by DanHeidinga** [comment]
Given the intermittent nature of this, we should look at how to modify the test to catch the failure and validate if this is a "real" failure or a machine (network? filesystem?) issue

**Comment by jdekonin** [comment]
I have this job failing on an internal win2008 and AIX7.1 systems.  And I can't find the job at the moment but I am 99% sure I've seen this fail on x86 CentOS6.9

ValueAnnotation.class can be found in generaltest.jar.  So far I haven't been able to catch a failing job and check the jar to see if its actually there.  I have also compiled and checked for the classes existence in a 20x loop with no apparent problems.

**Comment by jdekonin** [comment]
I have a grinder job like what is setup at [AdoptOpenJDK](https://ci.adoptopenjdk.net/view/all/job/Grinder/) and currently have a 10x on the same machine running.  Next I'll look at adding more debugging around the test itself.
