### ISSUE TITLE
Jenkins: Git clones fail intermittently with passwd file error

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1787]
Git clones failing intermittently. This one failed while trying to clone OpenJ9 ([this step](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le#L30)) on the master.

I'll have to look, but I don't think its always on the master that I've seen this.

Console:
```
 > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse/openj9.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: remote: Counting objects: 4657, done.        
remote: Compressing objects:   0% (1/161)       
...
...
Resolving deltas: 100% (3402/3402), completed with 1658 local objects.
fatal: unable to look up current user in the passwd file: Bad address
Unexpected end of command stream

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:860)
	... 13 more
```

One possible solution would be to wrap the clone in a `retry` block.

**Comment by AdamBrousseau** [comment]
On master
https://ci.eclipse.org/openj9/job/Build-JDK10-linux_x86-64_cmprssptrs/8/console
Master is running git 1.9 iirc. From what I read last week, older versions of git required the user to be looked up in the etc/passwd file for certain commands. They reduced the need for this in newer versions. Doesn't really explain why it's intermittent though. We could open a business bugzilla to see of eclipse will upgrade it for us.

**Comment by AdamBrousseau** [comment]
Opened a Bugzilla
https://bugs.eclipse.org/bugs/show_bug.cgi?id=534586

**Comment by AdamBrousseau** [comment]
We aren't getting much help from Eclipse on this. Possibly because they are [talking about](https://bugs.eclipse.org/bugs/show_bug.cgi?id=535057#c20) migrating off of HIPP5. We could change our Jenkins scripts to run on our `worker` machine and that should avoid this issue.

**Comment by AdamBrousseau** [comment]
They're planning to migrate us this week so we'll see what how Git performs on the new master.

**Comment by AdamBrousseau** [comment]
Eclipse has installed version 2.19.0 for us on the master at /usr/bin/git
Default git is still 1.9.0 located at /usr/local/sbin/git
Jenkins master has a global tool config where the default git is set to `git`. I tried changing this to /usr/bin/git but that has the side effect of trying to run that git on all the slaves. The Windows machines can't execute /usr/bin/git properly (even though that is the default git on the Windows machines). The solution was to edit the master node config and edit the path to be `PATH=/usr/lib/git:$PATH`. All the builds appear to be working now. We'll have to wait a bit to see if the passwd error is actually resolved since it is an intermittent issue.

**Comment by AdamBrousseau** [comment]
Haven't seen this issue reappear yet. Will close this issue. Can reopen if it resurfaces.

**Comment by DanHeidinga** [comment]
```
03:36:40 fatal: unable to look up current user in the passwd file: no such user
03:36:40 Unexpected end of command stream
```
Occurred again: https://ci.eclipse.org/openj9/job/Build-JDK8-linux_x86-64/333/console
