### ISSUE TITLE
fix test output, if the test passed, there would be better no exception throw

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#187]
```...
Calling getNotificationInfo on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getHardwareModel on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
	at j9vm.test.mxbeans.MXBeansGetterSanityTest.testMXBeanGetters(MXBeansGetterSanityTest.java:48)
	at j9vm.test.mxbeans.MXBeansGetterSanityTest.main(MXBeansGetterSanityTest.java:82)
Caused by: java.lang.UnsupportedOperationException
Calling getProcessCpuTime on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getProcessVirtualMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
	at com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl.getHardwareModelImpl(com.ibm.management@9-internal/Native Method)
	at com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl.getHardwareModel(com.ibm.management@9-internal/ExtendedOperatingSystemMXBeanImpl.java:193)
	... 6 more
Calling getVersion on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getSystemLoadAverage on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getTotalPhysicalMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getProcessPhysicalMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getFreePhysicalMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getProcessingCapacity on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getCommittedVirtualMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getProcessPrivateMemorySize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getArch on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getProcessCpuLoad on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getObjectName on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getOpenFileDescriptorCount on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getInstance on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getInstance on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getInstance on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getTotalSwapSpaceSize on com.ibm.lang.management.internal.UnixExtendedOperatingSystem
Calling getUptime on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getVMGeneratedCPULoad on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getClass on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getName on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getSpecVendor on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getVmName on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getClassPath on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getSpecVersion on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getSystemProperties on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getCPULoad on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getStartTime on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getInputArguments on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getManagementSpecVersion on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getVmVersion on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getBootClassPath on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
	at j9vm.test.mxbeans.MXBeansGetterSanityTest.testMXBeanGetters(MXB eansGetterSanityTest.java:48)
	at j9vm.test.mxbeans.MXBeansGetterSanityTest.main(MXBeansGetterSanityTest.java:83)
Caused by: java.lang.UnsupportedOperationException: VM does not support boot classpath.
	at com.ibm.java.lang.management.internal.RuntimeMXBeanImpl.getBootClassPath(java.management@9-internal/RuntimeMXBeanImpl.java:70)
	... 6 more
Calling getSpecName on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getObjectName on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getLibraryPath on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getProcessID on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getVmVendor on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getInstance on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getInstance on com.ibm.lang.management.internal.ExtendedRuntimeMXBeanImpl
Calling getClass on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getTotalStartedThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getCurrentThreadUserTime on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getDaemonThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getPeakThreadCount on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getAllThreadIds on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getCurrentThreadCpuTime on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getObjectName on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getInstance on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
Calling getInstance on com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl
--- Test PASSED ---

67 passed / 0 failed
ALL J9VM TESTS PASSED

J9vmTest_4_PASSED```



Test passed but there are exception thrown. It would be better not to show the exception if it is a real pass. Exception should be thrown to indicate a test failure.

**Comment by TianyuZuo** [comment]
Issue fixed
