### ISSUE TITLE
VmArgumentTests_0 java.lang.AssertionError Target process failed - non-compressed build

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1917]
https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_x86-64/2/
https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_x86-64/2/
https://ci.eclipse.org/openj9/job/Test-Extended-JDK10-linux_x86-64/2/

Adding Linux_x86-64 (nocompresed) builds to Jenkins.
Blocks #1884
```
testWAS80Cmdline
Exception java.lang.AssertionError
Message: Target process failed

Stacktrace:

at org.testng.Assert.fail(Assert.java:96)
at org.openj9.test.vmArguments.VmArgumentTests.runAndGetArgumentList(VmArgumentTests.java:1399)
at org.openj9.test.vmArguments.VmArgumentTests.testWAS80Cmdline(VmArgumentTests.java:1322)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by theresa-m** [comment]
Looking at this.

**Comment by theresa-m** [comment]
The failure in VmArgumentTests is due to -Xcompressedrefs being hard coded into the test testWAS80Cmdline. @smlambert can `testWAS80Cmdline` be excluded from openj9? or is there a way to tell in the java code whether we are using default or compressed refs?

still investigating the _testOpenJ9DiagnosticsMXBean_0 failure in the jdk9 run.

**Comment by smlambert** [comment]
Ah, the dreaded 'gotcha', that it is most possible to sneak in extra command line options in several places (not just in `<variation>` tags in the playlist.xml files, where we actually do check and skip the test if options that are defined there do not make sense for the SPEC being run against).

When it is set somewhere else, we currently do not check before we run the test... could put it on our backlog of items to try to do.  Wondering if we should just remove it from the commandline in the test itself and add -Xcompressedrefs to the variation being run.  

To answer your question:

To exclude this test method, you could add it to the [exclude files](https://github.com/eclipse/openj9/tree/master/test/TestConfig/resources/excludes) using this format: 
https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/excludes/latest_exclude_SE90.txt#L28

TestClass:TestMethod   IssueNumber   PlatformsToExcludeOn

**Comment by pshipton** [comment]
Removing the -Xcompressedrefs seems like the better approach, rather than excluding. Does the test pass if its removed?

**Comment by theresa-m** [comment]
looks like it works.

**Comment by pshipton** [comment]
+1 to just removing the -Xcompressedrefs
