### ISSUE TITLE
wins PR build always shows pass

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#1998]
It seems Jenkins wins builds have issue to copy *.tap file - AccessDeniedException
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/
```
14:35:20 Saving reports...
14:35:20 java.io.IOException: Failed to copy C:\Users\jenkins\workspace\PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9\openj9\test\TestConfig\test_output_15272708781957\TestTargetResult.tap to C:/Users/jenkins/workspace/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15272708781957/TestTargetResult.tap
14:35:20 	at hudson.FilePath.copyTo(FilePath.java:2043)
14:35:20 	at org.tap4j.plugin.TapPublisher.saveReports(TapPublisher.java:567)
14:35:20 	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:404)
14:35:20 	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:371)
14:35:20 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
14:35:20 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
14:35:20 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
14:35:20 	at hudson.security.ACL.impersonate(ACL.java:290)
14:35:20 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
14:35:20 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:35:20 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:35:20 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:35:20 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:35:20 	at java.lang.Thread.run(Thread.java:748)
14:35:20 Caused by: java.nio.file.AccessDeniedException: /C:
14:35:20 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
14:35:20 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
14:35:20 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
14:35:20 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
14:35:20 	at java.nio.file.Files.createDirectory(Files.java:674)
14:35:20 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
14:35:20 	at java.nio.file.Files.createDirectories(Files.java:767)
14:35:20 	at hudson.FilePath.mkdirs(FilePath.java:3001)
14:35:20 	at hudson.FilePath.write(FilePath.java:1927)
14:35:20 	at hudson.FilePath.copyTo(FilePath.java:2039)
14:35:20 	... 13 more
```

Without tap file, the build will show pass regardless the actual test result.
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-win_x86-64_cmprssptrs-OpenJ9/1/console

**Comment by llxia** [comment]
This is not limited to wins PR test builds. It seems all wins test builds have this issue.

The last working build is on May 18 11:45am.
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK9-win_x86-64_cmprssptrs/8/console

The first failure is seen on same day 7:44pm.
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK9-win_x86-64_cmprssptrs/9/console

fyi @jdekonin

**Comment by jdekonin** [comment]
@vsebe, please update with your findings.  Thanks.

**Comment by vsebe** [comment]
```
Failed to copy 
C:\Users\jenkins\workspace\PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9\openj9\test\TestConfig\test_output_15272708781957\TestTargetResult.tap 
to 
C:/Users/jenkins/workspace/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15272708781957/TestTargetResult.tap
```
The copy looks to overwrite the file- same path - and fails due to "/" vs "\".
Updated the Jenkins nodes path to root to use "\".

Latest [Test-Sanity-JDK8-win_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-win_x86-64_cmprssptrs/24/consoleFull) passed.

```
[Pipeline] step
02:18:24 TAP Reports Processing: START
02:18:24 Looking for TAP results report in workspace using pattern: **/*.tap
**02:18:25 Saving reports...**
02:18:26 Processing '/home/hudson/genie.openj9/.jenkins/jobs/Test-Sanity-JDK8-win_x86-64_cmprssptrs/builds/24/tap-master-files/openj9/test/TestConfig/test_output_15278308098341/TestTargetResult.tap'
02:18:26 Parsing TAP test result [/home/hudson/genie.openj9/.jenkins/jobs/Test-Sanity-JDK8-win_x86-64_cmprssptrs/builds/24/tap-master-files/openj9/test/TestConfig/test_output_15278308098341/TestTargetResult.tap].
```

**Comment by vsebe** [comment]
@llxia - this is fixed

**Comment by llxia** [comment]
Wins builds can get TAP file without problem.
