### ISSUE TITLE
Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le TestAttachErrorHandling OOM in attach API

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2019]
https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/171/tapResults/
```
===============================================
Running test TestAttachErrorHandling_SE80_0 ...
===============================================
TestAttachErrorHandling_SE80_0 Start Time: Wed May 30 07:19:57 2018 Epoch Time (ms): 1527664797425
test with NoOptions
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE80.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/5417 not removed because -1 still alive
[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/1234_5 not removed because -1 still alive
[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/foo not removed because -1 still alive
PASSED: testAttachWithCorruptAdvertisementFile
PASSED: testInitializationDeletesManyStaleDirectories
PASSED: testInitializationDeletesStaleDirectoryWithNumericId
PASSED: testInitializationDeletesStaleDirectoryWithPseudoNumericId
PASSED: testInitializationDeletesStaleDirectoryWithTextId
PASSED: testListVirtualMachinesWithCorruptAdvertisementFile
PASSED: testListVmsDeletesStaleDirectoriesWithNumericId
PASSED: testListVmsDeletesStaleDirectoryWithPseudoNumericId
PASSED: testListVmsDeletesStaleDirectoryWithTextId
PASSED: testPrematureSocketClose
PASSED: testTracepoint
PASSED: testVmShutdownWhileAttached
PASSED: test_startupShutdownRobustness
FAILED: testMemoryExhaustion
java.lang.AssertionError: OOM in attach API
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.testMemoryExhaustion(TestAttachErrorHandling.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    TestAttachErrorHandling
    Tests run: 14, Failures: 1, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
I don't see any re-occurrences of the failure. The test is still running nightly.
