### ISSUE TITLE
Intermittent NullPointerException in TestAttachErrorHandling.deleteIpcDirectories

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2047]
Low priority test issue.

```
FAILED: test_startupShutdownRobustness
java.lang.NullPointerException
	at java.io.File.<init>(File.java:371)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.deleteIpcDirectories(TestAttachErrorHandling.java:129)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:113)
```
```
	private void deleteIpcDirectories(File ipcDir,
			ArrayList<TargetManager> targets) {
		for (TargetManager victim: targets) {
			String tgtId = victim.getTargetPid();
>>>>>            File targetDir = new File(ipcDir, victim.targetId);
			if (targetDir.exists()) {
				logger.debug("delete "+tgtId);
				deleteRecursive(targetDir);
			}
		}
	}
```
getTargetPid() should not return null, and ipcDir is used on line 112.

**Comment by pdbain-ibm** [comment]
from https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK10-aix_ppc-64_cmprssptrs-OpenJ9/18/testReport/junit/org.openj9.test.attachAPI/TestAttachErrorHandling/test_startupShutdownRobustness/
```
java.io.IOException: Error deleting /tmp/test_startupShutdownRobustness/18153680
at org.openj9.test.util.FileUtilities.deleteRecursive(FileUtilities.java:51)
at org.openj9.test.attachAPI.TestAttachErrorHandling.deleteIpcDirectories(TestAttachErrorHandling.java:134)
at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:120)
```

**Comment by pdbain-ibm** [comment]
Excluding the test temporarily: https://github.com/eclipse/openj9/pull/2173
