### ISSUE TITLE
How can I user jstat, jinfo ... with openjdk8-openj9

### ISSUE THREAD

**Issue by eric-chao** [eclipse/openj9#2112]
Below is the errors:

[root@deploy-1 openj9]# java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

[root@deploy-1 ~]# jstat -gc 15907 3s
Exception in thread "main" java.lang.NullPointerException
	at sun.misc.Perf.attachImpl(Perf.java:285)
	at sun.misc.Perf.attach(Perf.java:200)
	at sun.jvmstat.perfdata.monitor.protocol.local.PerfDataBuffer.<init>(PerfDataBuffer.java:64)
	at sun.jvmstat.perfdata.monitor.protocol.local.LocalMonitoredVm.<init>(LocalMonitoredVm.java:68)
	at sun.jvmstat.perfdata.monitor.protocol.local.MonitoredHostProvider.getMonitoredVm(MonitoredHostProvider.java:77)
	at sun.tools.jstat.Jstat.logSamples(Jstat.java:116)
	at sun.tools.jstat.Jstat.main(Jstat.java:70)

[root@deploy-1 openj9]# jstatd
Could not create remote object
Access denied ("java.util.PropertyPermission" "java.rmi.server.ignoreSubClasses" "write")
java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "java.rmi.server.ignoreSubClasses" "write")
	at java.security.AccessController.throwACE(AccessController.java:176)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.security.AccessController.checkPermission(AccessController.java:373)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.System.setProperty(System.java:467)
	at sun.tools.jstatd.Jstatd.main(Jstatd.java:139)

**Comment by pshipton** [comment]
These tools are not supported by OpenJ9 at this time, i.e. #1621

**Comment by pshipton** [comment]
Also note you are using an older build, in the latest builds these tools are not present.

**Comment by DanHeidinga** [comment]
@eric-chao As Peter mentioned, the tools aren't currently supported but we'd like them to be.  Is this something you're interested in helping with add to OpenJ9?
