### ISSUE TITLE
Test-Extended-JDK8-aix_ppc-64_cmprssptrs startupShutdownRobustness IOException: Error deleting

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2141]
https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/90/

```
02:53:25 ===============================================
02:53:25 Running test TestAttachErrorHandling_SE80_0 ...
02:53:25 ===============================================
02:53:25 TestAttachErrorHandling_SE80_0 Start Time: Sun Jun 10 01:53:17 2018 Epoch Time (ms): 1528613597679
02:53:25 test with NoOptions
02:53:25 { "/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/j2sdk-image/jre/bin/java"  -Xcompressedrefs  \
02:53:25 -cp "/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/j2sdk-image/jre/bin/../../lib/tools.jar:/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
02:53:25 -Dcom.ibm.tools.attach.enable=yes \
02:53:25 -Dcom.ibm.tools.attach.timeout=15000 \
02:53:25 org.testng.TestNG -d "/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15286124245329/TestAttachErrorHandling_SE80_0" "/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestAttachErrorHandling \
02:53:25 -groups level.extended \
02:53:25 -excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all; \
02:53:25 if [ $? -eq 0 ] ; then echo ""; echo "TestAttachErrorHandling_SE80_0""_PASSED"; echo ""; else echo ""; echo "TestAttachErrorHandling_SE80_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15286124245329/TestTargetResult";
02:53:25 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/u0020236/workspace/Test-Extended-JDK8-aix_ppc-64_cmprssptrs/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE80.txt
02:53:25 ...
02:53:25 ... TestNG 6.14.2 by C�dric Beust (cedric@beust.com)
02:53:25 ...
02:53:25 
02:53:27 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/21495812 not removed because -1 still alive
02:53:27 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/1234_5 not removed because -1 still alive
02:53:27 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/foo not removed because -1 still alive
02:53:37 PASSED: testAttachWithCorruptAdvertisementFile
02:53:37 PASSED: testInitializationDeletesManyStaleDirectories
02:53:37 PASSED: testInitializationDeletesStaleDirectoryWithNumericId
02:53:37 PASSED: testInitializationDeletesStaleDirectoryWithPseudoNumericId
02:53:37 PASSED: testInitializationDeletesStaleDirectoryWithTextId
02:53:37 PASSED: testListVirtualMachinesWithCorruptAdvertisementFile
02:53:37 PASSED: testListVmsDeletesStaleDirectoriesWithNumericId
02:53:37 PASSED: testListVmsDeletesStaleDirectoryWithPseudoNumericId
02:53:37 PASSED: testListVmsDeletesStaleDirectoryWithTextId
02:53:37 PASSED: testMemoryExhaustion
02:53:37 PASSED: testPrematureSocketClose
02:53:37 PASSED: testTracepoint
02:53:37 PASSED: testVmShutdownWhileAttached
02:53:37 FAILED: test_startupShutdownRobustness
02:53:37 java.io.IOException: Error deleting /tmp/test_startupShutdownRobustness/6357000
02:53:37 	at org.openj9.test.util.FileUtilities.deleteRecursive(FileUtilities.java:51)
02:53:37 	at org.openj9.test.attachAPI.TestAttachErrorHandling.deleteIpcDirectories(TestAttachErrorHandling.java:134)
02:53:37 	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:120)
02:53:37 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:53:37 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:53:37 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:53:37 	at java.lang.reflect.Method.invoke(Method.java:498)
02:53:37 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
02:53:37 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
02:53:37 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
02:53:37 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
02:53:37 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:53:37 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:53:37 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:53:37 	at org.testng.TestRunner.run(TestRunner.java:505)
02:53:37 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:53:37 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
02:53:37 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
02:53:37 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
02:53:37 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:53:37 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
02:53:37 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
02:53:37 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
02:53:37 	at org.testng.TestNG.runSuites(TestNG.java:1049)
02:53:37 	at org.testng.TestNG.run(TestNG.java:1017)
02:53:37 	at org.testng.TestNG.privateMain(TestNG.java:1354)
02:53:37 	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pdbain-ibm** [comment]
This is a duplicate of issue #2047.

**Comment by pdbain-ibm** [comment]
@pshipton Would you kindly verify and close this issue?

**Comment by fjeremic** [comment]
> @pshipton Would you kindly verify and close this issue?

Actually I still see this happening in on of @mpirvu's builds from #2546:

https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/70/consoleFull

```
19:31:29 org.testng.TestNG -d "/home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15369644793807/TestAttachErrorHandling_SE80_0" "/home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestAttachErrorHandling \
19:31:29 -groups level.extended \
19:31:29 -excludegroups d.*.linux_390-64_cmprssptrs,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
19:31:29 if [ $? -eq 0 ] ; then echo ""; echo "TestAttachErrorHandling_SE80_0""_PASSED"; echo ""; else echo ""; echo "TestAttachErrorHandling_SE80_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15369644793807/TestTargetResult";
19:31:29 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE80.txt
19:31:29 ...
19:31:29 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
19:31:29 ...
19:31:29 
19:31:31 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/55007 not removed because -1 still alive
19:31:32 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/1234_5 not removed because -1 still alive
19:31:32 [AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/foo not removed because -1 still alive
19:31:35 
19:31:35 TestAttachErrorHandling_SE80_0_FAILED
19:31:35 
19:31:35 TestAttachErrorHandling_SE80_0 Finish Time: Fri Sep 14 19:31:35 2018 Epoch Time (ms): 1536967895360
```

**Comment by pdbain-ibm** [comment]
That's a recent regression in the socket code, cause unknown, unrelated to attach API: 
https://github.com/eclipse/openj9/issues/2871

**Comment by pdbain-ibm** [comment]
@pshipton would you kindly close this issue?

**Comment by pshipton** [comment]
I'll wait until tomorrow, after the overnight builds with #2965, when we can verify the test is running and passing.

**Comment by pshipton** [comment]
I see the test in TestAttachErrorHandling is running and passing now in extended testing
`PASSED: test_startupShutdownRobustness`
