### ISSUE TITLE
AssertionError in testModule

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2193]
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK10-linux_x86-64_cmprssptrs/33/consoleFull

```
02:45:10 Exception in thread "Thread-3" java.lang.AssertionError: Wrong module version expected [10.0.1-internal] but found [10.0.1-internal]
02:45:10 	at org.testng.Assert.fail(Assert.java:96)
02:45:10 	at org.testng.Assert.failNotEquals(Assert.java:776)
02:45:10 	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
02:45:10 	at org.testng.Assert.assertEquals(Assert.java:118)
02:45:10 	at org.openj9.test.stackWalker.StackWalkerTest.dumpModules(StackWalkerTest.java:268)
02:45:10 	at org.openj9.test.stackWalker.StackWalkerTest.lambda$testModule$14(StackWalkerTest.java:248)
02:45:10 	at org.openj9.test.stackWalker.StackWalkerTest$$Lambda$54.000000001C6E1F00.run(Unknown Source)
02:45:10 	at java.lang.Thread.run(java.base@10.0.1-internal/Thread.java:835)
02:45:10 PASSED: testClassLoaderName
02:45:10 PASSED: testForEach
02:45:10 PASSED: testGetCallerClass
02:45:10 PASSED: testGetCallerClassUsingReflection
02:45:10 PASSED: testGetInstance
02:45:10 PASSED: testGetInstanceSetStackWalkerOption
02:45:10 PASSED: testGetInstanceSetStackWalkerOptionint
02:45:10 PASSED: testGetInstanceStackWalkerOption
02:45:10 PASSED: testModule
02:45:10 PASSED: testOptions
02:45:10 PASSED: testRecursiveStackWalk
02:45:10 PASSED: testSanity
02:45:10 PASSED: testStackTop
02:45:10 PASSED: testThreads
02:45:10 
02:45:10 ===============================================
02:45:10     StackWalkerTest
02:45:10     Tests run: 14, Failures: 0, Skips: 0
02:45:10 ===============================================
02:45:10 
02:45:10 
02:45:10 ===============================================
02:45:10 Java9andUp suite
02:45:10 Total tests run: 14, Failures: 0, Skips: 0
02:45:10 ===============================================
02:45:10 
02:45:10 
02:45:10 StackWalkerTest_0_PASSED
```

There are two issues:
- AssertionError
```
assertEquals(modVersion.get(), e.getModuleVersion(), "Wrong module version");
```
One method returns `java.util.Optional` and the other returns String. Therefore, we have mismatch.
https://docs.oracle.com/javase/9/docs/api/java/lang/StackTraceElement.html#getModuleVersion--
https://docs.oracle.com/javase/9/docs/api/java/util/Optional.html#get--

- Test should fail when there is error.

**Comment by pdbain-ibm** [comment]
> Test should fail when there is error.

This looks like a testng issue, since the code is clearly indicating a failure:

`at org.testng.Assert.fail(Assert.java:96)`

**Comment by llxia** [comment]
yes, that is one of the issues. Another one is that we are comparing `Version` with `String` and expect they are equal. This is incorrect.

```
Optional<Version> modVersion = d.version();
if (modVersion.isPresent()) {
   assertEquals(modVersion.get(), e.getModuleVersion(), "Wrong module version");
}
```

**Comment by pdbain-ibm** [comment]
@llxia would you kindly verify that this is fixed?
Many thanks
    -P

**Comment by llxia** [comment]
yes, this is fixed. Thanks @pdbain-ibm 👍
