### ISSUE TITLE
Test-sanity.system-JDK8-linux_x86-64 LambdaLoadTest_0 TestStreamOperations OOM

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2209]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/5/tapResults/

```
===============================================
Running test LambdaLoadTest_0 ...
===============================================
LambdaLoadTest_0 Start Time: Sat Jun 16 12:07:54 2018 Epoch Time (ms): 1529150874796
test with NoOptions
STF 12:07:54.956 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqsRetrieving amount of free space on drive containing /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0
There is 11287 Mb free
STF 12:07:54.962 - ==================   G E N E R A T I O N   ==================
STF 12:07:54.963 - Checking JVM: /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../
STF 12:07:54.963 - Starting process to generate scripts: /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../..//bin/java  -Dlog4j.skipJansi=true -Djava.system.class.loader=net.adoptopenjdk.stf.runner.StfClassLoader -classpath /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/scripts/../bin net.adoptopenjdk.stf.runner.StfRunner -properties "/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/stf_parameters.properties, , /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/config/stf.properties" -testDir "/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest"
GEN 12:07:55.821 - Found test. Project: 'openjdk.test.load' class: 'LambdaLoadTest.class' Dir: '/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.load/bin'
GEN 12:07:55.832 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.LambdaLoadTest'
GEN Classpath directories used by project 'openjdk.test.load': 
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.load/bin
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/bin
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.load/bin
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar
GEN   /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar
GEN 12:07:56.097 - Using Mode NoOptions. Values = ''
GEN 12:07:56.131 - 
GEN 12:07:56.131 - Test command summary:
GEN 12:07:56.131 -   Step  Stage   Command           Description
GEN 12:07:56.131 -  -----+--------+-----------------+------------
GEN 12:07:56.131 -     1  execute  Run java          Run lambda and stream load test
STF 12:07:56.148 - 
STF 12:07:56.148 - Script generation completed
STF 12:07:56.148 - 
STF 12:07:56.148 - 
STF 12:07:56.148 - =======================   S E T U P   =======================
STF 12:07:56.148 - Running setup: perl /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/setUp.pl
STF 12:07:56.212 - SETUP stage completed
STF 12:07:56.216 - 
STF 12:07:56.216 - ====================   E X E C U T E -   ====================
STF 12:07:56.216 - Running execute: perl /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/execute.pl
STF 12:07:56.281 - 
STF 12:07:56.281 - Java version
STF 12:07:56.281 - Running: /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -version
openjdk version "1.8.0_172-internal"
OpenJDK Runtime Environment (build 1.8.0_172-internal-jenkins_2018_06_16_11_18-b00)
Eclipse OpenJ9 VM (build master-da56ab5, JRE 1.8.0 Linux amd64-64-Bit 20180616_104 (JIT enabled, AOT enabled)
OpenJ9   - da56ab5
OMR      - da0c7ee
JCL      - 34726b6 based on jdk8u172-b11)
STF 12:07:56.440 - 
STF 12:07:56.440 - +------ Step 1 - Run lambda and stream load test
STF 12:07:56.441 - | Run foreground process
STF 12:07:56.441 - |   Program:     /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java
STF 12:07:56.441 - |   Mnemonic:    LT
STF 12:07:56.441 - |   Echo:        ECHO_ON
STF 12:07:56.441 - |   Expectation: CLEAN_RUN within 30m
STF 12:07:56.441 - |
STF 12:07:56.441 - Running command: /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -Xnocompressedrefs -classpath /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.load/bin:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/bin:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.lambdasAndStreams/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results -resultsPrefix 1.LT. -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.lambda.threadCount 2 -suite.lambda.inventoryFile /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results/1.LT.inventory/openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml -suite.lambda.inventoryExcludeFile none -suite.lambda.totalNumberTests 200 -suite.lambda.selection random -suite.lambda.seed -1 -suite.lambda.repeatCount 1 -suite.lambda.thinkingTime 0ms..0ms
STF 12:07:56.441 - Redirecting stderr to /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results/1.LT.stderr
STF 12:07:56.441 - Redirecting stdout to /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results/1.LT.stdout
STF 12:07:56.451 - Monitoring processes: LT 
LT  12:07:57.342 - Load test parameters
LT  12:07:57.343 -   Time limited         = false
LT  12:07:57.343 -   abortIfOutOfMemory   = true
LT  12:07:57.344 -   reportFailureLimit   = 1
LT  12:07:57.344 -   abortAtFailureLimit  = 10
LT  12:07:57.344 -   maxTotalLogFileSpace = 209715200
LT  12:07:57.344 -   maxSingleLogSize     = 8388608
LT  12:07:57.344 - Parameters for suite 0
LT  12:07:57.344 -   Suite name     = lambda
LT  12:07:57.344 -   Number threads = 2
LT  12:07:57.344 -   Supplied seed  = -1
LT  12:07:57.344 -   Inventory file = /home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results/1.LT.inventory/openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  12:07:57.344 -   Exclude file   = none
LT  12:07:57.345 -   Number tests   = 200
LT  12:07:57.345 -   Repeat count   = 1
LT  12:07:57.345 -   Thinking time  = 0ms..0ms
LT  12:07:57.345 -   Selection mode = random
LT  12:07:57.345 -   Actual seed    = 1531226330622
LT  12:07:57.353 - Parsing inventory file. Root=/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15291505729410/LambdaLoadTest_0/20180616-120754-LambdaLoadTest/results/1.LT.inventory File=openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  12:07:57.361 - Final test list:
LT  12:07:57.361 -   0 JUnit[net.adoptopenjdk.test.lambda.ClassLibraryLambdaTests]  Weighting=1 
LT  12:07:57.361 -   1 JUnit[net.adoptopenjdk.test.lambda.TestLambdaCapture]  Weighting=1 
LT  12:07:57.361 -   2 JUnit[net.adoptopenjdk.test.lambda.TestLambdaContexts]  Weighting=1 
LT  12:07:57.361 -   3 JUnit[net.adoptopenjdk.test.lambda.TestLambdaDefaultsAndStatics]  Weighting=1 
LT  12:07:57.361 -   4 JUnit[net.adoptopenjdk.test.lambda.TestLambdaInferredTyping]  Weighting=1 
LT  12:07:57.361 -   5 JUnit[net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces]  Weighting=1 
LT  12:07:57.362 -   6 JUnit[net.adoptopenjdk.test.lambda.TestLambdaLexicalScoping]  Weighting=1 
LT  12:07:57.362 -   7 JUnit[net.adoptopenjdk.test.lambda.TestLambdaMethodReferences]  Weighting=1 
LT  12:07:57.362 -   8 JUnit[net.adoptopenjdk.test.lambda.TestLambdaMultithreaded]  Weighting=1 
LT  12:07:57.362 -   9 JUnit[net.adoptopenjdk.test.lambda.TestLambdaNested]  Weighting=1 
LT  12:07:57.362 -   10 JUnit[net.adoptopenjdk.test.lambda.TestLambdaRecursive]  Weighting=1 
LT  12:07:57.362 -   11 JUnit[net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface]  Weighting=1 
LT  12:07:57.362 -   12 JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]  Weighting=1 
LT  12:07:57.362 -   13 JUnit[net.adoptopenjdk.test.streams.TestStreamOperations]  Weighting=1 
LT  12:07:57.394 - Starting thread. Suite=0 thread=0
LT  12:07:57.396 - Starting thread. Suite=0 thread=1
LT  12:08:18.662 - Completed 3.5%. Number of tests started=7
LT  12:08:37.778 - Completed 3.5%. Number of tests started=7 (+0)
LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/06/16 12:08:56 - please wait.
```

**Comment by pshipton** [comment]
Restarted the test to see if it fails consistently

https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK8-linux_x86-64/

**Comment by pshipton** [comment]
Its not an intermittent problem.

**Comment by llxia** [comment]
@Mesbah-Alam , could you temporarily exclude this test? Thanks.

**Comment by Mesbah-Alam** [comment]
Hi Peter, 

The LambdaLoadTest falls into the category of "abbs" load tests. This test passed in the last openjdk8 openj9 x64 Linux systemtest build (3 days ago): https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_x86-64_linux/106/tapResults/

With the following sdk version: 

```
image/jre/bin/../../bin/java -version
10:29:04 openjdk version "1.8.0_172"
10:29:04 OpenJDK Runtime Environment (build 1.8.0_172-b11)
10:29:04 Eclipse OpenJ9 VM (build master-cafdf403, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180615_212 (JIT enabled, AOT enabled)
10:29:04 OpenJ9   - cafdf403
10:29:04 OMR      - 04dfe33b
10:29:04 JCL      - d587cde1 based on jdk8u172-b11)```

I have no problem excluding the test, but just want to make sure- is this really a test issue? Did anything change in the SDK since the last systemtest build was run, where the test had passed? @pshipton

**Comment by llxia** [comment]
@Mesbah-Alam, OpenJ9 and Adopt have different test build name. The test failed in OpenJ9 ran with `SPEC=linux_x86-64`. The test that you referenced in Adopt ran with `SPEC=linux_x86-64_cmprssptrs`. 

In OpenJ9, this test passed with `SPEC=linux_x86-64_cmprssptrs` as well. https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/6/tapResults/

**Comment by Mesbah-Alam** [comment]
@llxia , Thanks for pointing this out. So, the test only fails with `SPEC=linux_x86-64`; therefore that's the only spec on which it should be excluded.

**Comment by smlambert** [comment]
Yes, only exclude for that SPEC... and we should verify with a Grinder test at Adopt if we also fail it at Adopt (you can grab the largeHeap build from this job: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-64_linux_largeHeap/)

**Comment by pshipton** [comment]
Note once the exclude is working in the master branch we'll also want to open a PR against the v0.9.0-release branch.

**Comment by pshipton** [comment]
I should have looked at the existing PR, which is at AdoptOpenJDK/openjdk-tests, so I guess it applies across all OpenJ9 streams and branches.

**Comment by Mesbah-Alam** [comment]
The test has been excluded from OpenJDK 8/9/10 OpenJ9 sdk on Linux x64 non-compressedrefs platforms https://github.com/AdoptOpenJDK/openjdk-tests/pull/452

**Comment by pshipton** [comment]
Thanks Mesbah. Closing.

**Comment by pshipton** [comment]
Reopening to track the excluded test.

**Comment by smlambert** [comment]
The test is being excluded under this closed issue, which implies to me that I should be able to re-enable the test.  

Was there an actual resolution to this issue?  Or a test issue raised?  We need to update the `<disabled>` link in the [playlist file](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/lambdaLoadTest/playlist.xml#L4), if a different issue is being worked in order to reenable the test.

**Comment by pshipton** [comment]
Reading the earlier comments, I suspect I meant to re-open it but failed to do so.

**Comment by lumpfish** [comment]
See related issue: https://github.com/eclipse/openj9/issues/2209 with analysis of the test failure.

**Comment by pshipton** [comment]
@lumpfish I suspect you meant to refer to a different issue in the previous comment, it just refers back to this Issue.

**Comment by smlambert** [comment]
Could be referring to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/379 and/or https://github.com/AdoptOpenJDK/stf/issues/90.

**Comment by lumpfish** [comment]
Sorry, meant to reference https://github.com/eclipse/openj9/issues/10638

**Comment by lumpfish** [comment]
This OOM should no longer occur as a result of the changes made for https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/379.

**Comment by pshipton** [comment]
Test unexcluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/2229
LambdaLoadTest_special_J9_5m is running in the builds. https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_mixed_Nightly/5/tapResults/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/6
LambdaLoadTest_special_J9_5m_17
-Xcompressedrefs -Xgcpolicy:balanced -Xquickstart -Xjit

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/6/system_test_output.tar.gz
```
LT  07:01:31.480 -   12 JUnit[net.adoptopenjdk.test.streams.TestStreamOperations]  Weighting=1 
LT  stderr WARNING: A terminally deprecated method in java.lang.System has been called
LT  stderr WARNING: System::setSecurityManager has been called by net.adoptopenjdk.loadTest.LoadTest (file:/home/jenkins/workspace/Test_openjdk17_j9_special.system_s390x_linux_Release_testList_4/jvmtest/system/stf/stf.load/bin/)
LT  stderr WARNING: Please consider reporting this to the maintainers of net.adoptopenjdk.loadTest.LoadTest
LT  stderr WARNING: System::setSecurityManager will be removed in a future release
LT  07:01:31.519 - Starting thread. Suite=0 thread=0
LT  07:01:31.519 - Starting thread. Suite=0 thread=1
LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/09/26 07:01:34 - please wait.
```

@dmitripivkine fyi. probably nothing but just in case. This build is on the 0.28 branches.

**Comment by dmitripivkine** [comment]
FYI: there is another error as well:
```
07:02:26  LT  testFailure: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded): offset 471217168, count 14, length 235608587
07:02:26  LT  java.lang.StringIndexOutOfBoundsException: offset 471217168, count 14, length 235608587
07:02:26  LT  	at java.base/java.lang.String.checkBoundsOffCount(String.java:5346)
07:02:26  LT  	at java.base/java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1636)
07:02:26  LT  	at java.base/java.lang.StringUTF16.inflate(StringUTF16.java:1462)
07:02:26  LT  	at java.base/java.lang.StringLatin1.inflate(StringLatin1.java:788)
07:02:26  LT  	at java.base/java.lang.String.getBytes(String.java:5216)
07:02:26  LT  	at java.base/java.lang.StringConcatHelper.newArrayWithSuffix(StringConcatHelper.java:477)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
07:02:26  LT  	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.linkToTargetMethod(LambdaForm$MH)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.assertStack(TestLambdaMultithreaded.java:443)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.runAllOpcodes(TestLambdaMultithreaded.java:271)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:235)
07:02:26  LT  	at net.adoptopenjdk.test.lambda.TestLambdaMultithreaded$$Lambda$317/0x00000000000a11b0.run(Unknown Source)
07:02:26  LT  	at java.base/java.lang.Thread.run(Thread.java:884)
07:02:26  LT  testFinished: testLambdasWithMultipleThreads(net.adoptopenjdk.test.lambda.TestLambdaMultithreaded)
07:02:26  LT  
07:02:26  LT  JUnit Test Results for: net.adoptopenjdk.test.lambda.TestLambdaMultithreaded
07:02:26  LT    Ran    : 1
07:02:26  LT    Passed : 0
07:02:26  LT    Failed : 1
07:02:26  LT    Ignored: 0
07:02:26  LT    Result : FAILED
```

**Comment by pshipton** [comment]
Thanks. Opened https://github.com/eclipse-openj9/openj9/issues/13589 to track.
