### ISSUE TITLE
Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le ServiceLoadersTest_0 testServiceLoader AssertionError

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2225]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/3/tapResults/

```
===============================================
Running test ServiceLoadersTest_0 ...
===============================================
ServiceLoadersTest_0 Start Time: Mon Jun 18 20:47:27 2018 Epoch Time (ms): 1529354847110
test with NoOptions
STF 20:47:27.306 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqsRetrieving amount of free space on drive containing /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0
There is 62832 Mb free
STF 20:47:27.314 - ==================   G E N E R A T I O N   ==================
STF 20:47:27.315 - Checking JVM: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../
STF 20:47:27.315 - Starting process to generate scripts: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/..//bin/java  -Dlog4j.skipJansi=true -Djava.system.class.loader=net.adoptopenjdk.stf.runner.StfClassLoader -classpath /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/stf/stf.core/scripts/../bin net.adoptopenjdk.stf.runner.StfRunner -properties "/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/stf_parameters.properties, , /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/stf/stf.core/config/stf.properties" -testDir "/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest"
GEN 20:47:28.553 - Found test. Project: 'openjdk.test.modularity' class: 'ServiceLoadersTest.class' Dir: '/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin'
GEN 20:47:28.555 - Found test. Project: 'openjdk.test.modularity' class: 'net.adoptopenjdk.test.modularity.ServiceLoadersTest'
GEN Classpath directories used by project 'openjdk.test.modularity': 
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/displayService
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/com.helper
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/displayServiceImpl1
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/com.discreet
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/com.hello
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/com.hola
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/displayServiceImpl2
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/com.hi
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-override
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-override-new
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common/displayServiceImpl3
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common/displayServiceImpl4
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/stf/stf.core/bin
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar
GEN   /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar
GEN 20:47:28.841 - Using Mode NoOptions. Values = ''
GEN 20:47:28.931 - 
GEN 20:47:28.931 - Test command summary:
GEN 20:47:28.932 -   Step  Stage   Command           Description
GEN 20:47:28.932 -  -----+--------+-----------------+------------
GEN 20:47:28.932 -     1  execute  jar               Create modular jar displayServiceImpl1.jar
GEN 20:47:28.932 -     2  execute  jar               create project jar displayServiceImpl3.jar
GEN 20:47:28.932 -     3  execute  jar               create project jar displayServiceImpl4.jar
GEN 20:47:28.932 -     4  execute  Run java          Run service loader test by adding the use of display service in module-info.java
GEN 20:47:28.932 -     5  execute  Run java          Run serviceloader test2 with the test as an explicit module. It is same as test1, except that requires and uses are added through addReads() and addUses() through code instead of adding them into module-info.java
GEN 20:47:28.932 -     6  execute  jar               create project jar com.test.serviceloaders2.jar
GEN 20:47:28.932 -     7  execute  Run java          Run serviceloader test3 is same as test2 except that the TestServiceLoaders2 is in an automatic module
STF 20:47:28.949 - 
STF 20:47:28.949 - Script generation completed
STF 20:47:28.949 - 
STF 20:47:28.949 - 
STF 20:47:28.949 - =======================   S E T U P   =======================
STF 20:47:28.949 - Running setup: perl /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/setUp.pl
STF 20:47:29.012 - SETUP stage completed
STF 20:47:29.018 - 
STF 20:47:29.018 - ====================   E X E C U T E -   ====================
STF 20:47:29.018 - Running execute: perl /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/execute.pl
STF 20:47:29.080 - 
STF 20:47:29.080 - Java version
STF 20:47:29.080 - Running: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/java -version
openjdk version "10.0.1-internal" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-internal+0-adhoc.jenkins.Build-JDK10-linuxppc-64cmprssptrsle)
Eclipse OpenJ9 VM (build master-e27ef8e, JRE 10 Linux ppc64le-64-Bit Compressed References 20180618_201 (JIT enabled, AOT enabled)
OpenJ9   - e27ef8e
OMR      - 447fdf4
JCL      - 3e42389 based on jdk-10.0.1+10)
STF 20:47:29.229 - 
STF 20:47:29.229 - +------ Step 1 - Create modular jar displayServiceImpl1.jar
STF 20:47:29.229 - | Create modular jar
STF 20:47:29.229 - |   ModuleSpec:    openjdk.test.modularity/bin/common-mods/displayServiceImpl1
STF 20:47:29.230 - |   ModuleVersion: null
STF 20:47:29.230 - |   MainClass:     null
STF 20:47:29.230 - |   HashModules:   null
STF 20:47:29.230 - |
STF 20:47:29.230 - Running command: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/jar --create --file /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/modules/1.displayServiceImpl1.jar -C /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods/displayServiceImpl1 .
STF 20:47:29.230 - Redirecting stderr to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/1.CMJ.stderr
STF 20:47:29.230 - Redirecting stdout to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/1.CMJ.stdout
STF 20:47:29.240 - Monitoring processes: CMJ
STF 20:47:29.653 - Monitoring Report Summary:
STF 20:47:29.653 -   o Process CMJ ended with the expected exit code (0)
STF 20:47:29.653 - Created modular jar: 1.displayServiceImpl1.jar
STF 20:47:29.653 - 
STF 20:47:29.653 - +------ Step 2 - create project jar displayServiceImpl3.jar
STF 20:47:29.653 - | Create project jar
STF 20:47:29.653 - |   ProjectSpec: openjdk.test.modularity/bin/common/displayServiceImpl3
STF 20:47:29.653 - |   ArchiveSpec: 
STF 20:47:29.653 - |
STF 20:47:29.654 - Running command: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/jar --create --file /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl3.jar -C /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common/displayServiceImpl3 .
STF 20:47:29.654 - Redirecting stderr to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/2.JAR.stderr
STF 20:47:29.654 - Redirecting stdout to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/2.JAR.stdout
STF 20:47:29.655 - Monitoring processes: JAR
STF 20:47:30.012 - Monitoring Report Summary:
STF 20:47:30.012 -   o Process JAR ended with the expected exit code (0)
STF 20:47:30.012 - Created project jar: displayServiceImpl3.jar
STF 20:47:30.012 - 
STF 20:47:30.012 - +------ Step 3 - create project jar displayServiceImpl4.jar
STF 20:47:30.012 - | Create project jar
STF 20:47:30.012 - |   ProjectSpec: openjdk.test.modularity/bin/common/displayServiceImpl4
STF 20:47:30.012 - |   ArchiveSpec: 
STF 20:47:30.012 - |
STF 20:47:30.013 - Running command: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/jar --create --file /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl4.jar -C /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common/displayServiceImpl4 .
STF 20:47:30.013 - Redirecting stderr to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/3.JAR.stderr
STF 20:47:30.013 - Redirecting stdout to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/3.JAR.stdout
STF 20:47:30.014 - Monitoring processes: JAR
STF 20:47:30.386 - Monitoring Report Summary:
STF 20:47:30.386 -   o Process JAR ended with the expected exit code (0)
STF 20:47:30.386 - Created project jar: displayServiceImpl4.jar
STF 20:47:30.386 - 
STF 20:47:30.386 - +------ Step 4 - Run service loader test by adding the use of display service in module-info.java
STF 20:47:30.386 - | Run foreground process
STF 20:47:30.386 - |   Program:     /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/java
STF 20:47:30.386 - |   Mnemonic:    T1
STF 20:47:30.386 - |   Echo:        ECHO_ON
STF 20:47:30.386 - |   Expectation: CLEAN_RUN within 1m
STF 20:47:30.386 - |
STF 20:47:30.387 - Running command: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/java --add-reads com.test.serviceloaders=ALL-UNNAMED --module-path /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/modules/1.displayServiceImpl1.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl3.jar --add-modules=com.test.serviceloaders,displayService -Xcompressedrefs -classpath /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl4.jar org.junit.runner.JUnitCore adoptopenjdk.test.modularity.serviceloaders.TestServiceLoaders
STF 20:47:30.387 - Redirecting stderr to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/4.T1.stderr
STF 20:47:30.387 - Redirecting stdout to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/4.T1.stdout
STF 20:47:30.388 - Monitoring processes: T1 
T1  JUnit version 4.12
T1  .DisplayServiceImpl1
T1  DisplayServiceImpl2
T1  DisplayServiceImpl3
T1  DisplayServiceImpl4
T1  
T1  Time: 0.043
T1  
T1  OK (1 test)
T1  
STF 20:47:30.964 - Monitoring Report Summary:
STF 20:47:30.964 -   o Process T1  ended with the expected exit code (0)
STF 20:47:30.964 - 
STF 20:47:30.964 - +------ Step 5 - Run serviceloader test2 with the test as an explicit module. It is same as test1, except that requires and uses are added through addReads() and addUses() through code instead of adding them into module-info.java
STF 20:47:30.964 - | Run foreground process
STF 20:47:30.964 - |   Program:     /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/java
STF 20:47:30.964 - |   Mnemonic:    T2
STF 20:47:30.964 - |   Echo:        ECHO_ON
STF 20:47:30.965 - |   Expectation: CLEAN_RUN within 1m
STF 20:47:30.965 - |
STF 20:47:30.965 - Running command: /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/../bin/java --add-reads com.test.serviceloaders2=ALL-UNNAMED --module-path /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/modules/1.displayServiceImpl1.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-mods:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl3.jar --add-modules=com.test.serviceloaders2,displayService -Xcompressedrefs -classpath /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tmp/displayServiceImpl4.jar org.junit.runner.JUnitCore adoptopenjdk.test.modularity.serviceloaders2.TestServiceLoaders2
STF 20:47:30.965 - Redirecting stderr to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/5.T2.stderr
STF 20:47:30.965 - Redirecting stdout to /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/results/5.T2.stdout
STF 20:47:30.966 - Monitoring processes: T2 
T2  JUnit version 4.12
T2  .Added readability edge via addReads() API from com.test.serviceloaders2 to displayService
T2  Added uses edge via addUses() API from com.test.serviceloaders2 to displayService
T2  DisplayServiceImpl4
T2  E
T2  Time: 0.037
T2  There was 1 failure:
T2  1) testServiceLoader(adoptopenjdk.test.modularity.serviceloaders2.TestServiceLoaders2)
T2  java.lang.AssertionError
T2  	at org.junit.Assert.fail(Assert.java:86)
T2  	at org.junit.Assert.assertTrue(Assert.java:41)
T2  	at org.junit.Assert.assertTrue(Assert.java:52)
T2  	at adoptopenjdk.test.modularity.serviceloaders2.TestServiceLoaders2.testServiceLoader(com.test.serviceloaders2/TestServiceLoaders2.java:138)
T2  	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10.0.1-internal/Native Method)
T2  	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10.0.1-internal/NativeMethodAccessorImpl.java:62)
T2  	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10.0.1-internal/DelegatingMethodAccessorImpl.java:43)
T2  	at java.lang.reflect.Method.invoke(java.base@10.0.1-internal/Method.java:564)
T2  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
T2  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
T2  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
T2  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
T2  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
T2  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
T2  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
T2  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
T2  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
T2  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
T2  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
T2  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
T2  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
T2  	at org.junit.runners.Suite.runChild(Suite.java:128)
T2  	at org.junit.runners.Suite.runChild(Suite.java:27)
T2  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
T2  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
T2  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
T2  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
T2  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
T2  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
T2  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
T2  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
T2  	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
T2  	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
T2  
T2  FAILURES!!!
T2  Tests run: 1,  Failures: 1
T2  
STF 20:47:31.521 - **FAILED** Process T2  ended with exit code (1) and not the expected exit code/s (0)
STF 20:47:31.521 - Monitoring Report Summary:
STF 20:47:31.521 -   o Process T2  ended with exit code (1) and not the expected exit code/s (0)
STF 20:47:31.522 - Killing processes: T2 
STF 20:47:31.522 -   o Process T2  is not running
**FAILED** at step 5 (Run serviceloader test2 with the test as an explicit module. It is same as test1, except that requires and uses are added through addReads() and addUses() through code instead of adding them into module-info.java). Expected return value=0 Actual=1 at /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/execute.pl line 246.
STF 20:47:31.537 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 20:47:31.537 - 
STF 20:47:31.537 - ====================   T E A R D O W N   ====================
STF 20:47:31.537 - Running teardown: perl /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15293505442103/ServiceLoadersTest_0/20180618-204727-ServiceLoadersTest/tearDown.pl
STF 20:47:31.598 - TEARDOWN stage completed
STF 20:47:31.600 - 
STF 20:47:31.600 - =====================   R E S U L T S   =====================
STF 20:47:31.600 - Stage results:
STF 20:47:31.600 -   setUp:     pass
STF 20:47:31.600 -   execute:  *fail*
STF 20:47:31.600 -   teardown:  pass
STF 20:47:31.600 - 
STF 20:47:31.600 - Overall result: **FAILED**
```

**Comment by pshipton** [comment]
@Mesbah-Alam @smlambert fyi

**Comment by Mesbah-Alam** [comment]
This test was written on an much older version of modularity implementation. It fails consistently both on hotspot as well as openj9 which may indicate the test is no longer valid. I am investigating a bit more. If invalid, I'll take it out of the modularity test suite.

**Comment by Mesbah-Alam** [comment]
The failing ServiceLoaders tests have been excluded from running in the build: The failing tests have been excluded from running in the build : #138. I will add them back once Details: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/137 is resolved.

**Comment by pshipton** [comment]
I don't expect we need this issue open to track fixing the problem, closing it.
