### ISSUE TITLE
Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le Jlink directory count not be found

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2227]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/3/tapResults/

JlinkTest_RequiredMod_0
JlinkTest_AddModLimitMod_0
JlinkPluginOptionsTest_GeneralOptionsTest_0

```
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: Note: directory 'openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/linux_ppcle-64' could not be found in any of the supplied roots: '/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/stf','/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest'
GEN stderr 	at net.adoptopenjdk.stf.environment.DirectoryRef.findDirectory(DirectoryRef.java:274)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.findTestDirectory(StfEnvironmentCore.java:277)
GEN stderr 	at net.adoptopenjdk.stf.extensions.core.StfEnvironment.findTestDirectory(StfEnvironment.java:55)
GEN stderr 	at net.adoptopenjdk.test.modularity.JlinkTest.setUp(JlinkTest.java:98)
GEN stderr 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10.0.1-internal/Native Method)
GEN stderr 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10.0.1-internal/NativeMethodAccessorImpl.java:62)
GEN stderr 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10.0.1-internal/DelegatingMethodAccessorImpl.java:43)
GEN stderr 	at java.lang.reflect.Method.invoke(java.base@10.0.1-internal/Method.java:564)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.runStage(StfRunner.java:549)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:293)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

**Comment by pshipton** [comment]
@Mesbah-Alam @smlambert fyi

**Comment by pshipton** [comment]
No re-occurrences, assuming fixed.
