### ISSUE TITLE
java.lang.IllegalAccessError: Failed to unreflect constructor

### ISSUE THREAD

**Issue by dustContributor** [eclipse/openj9#2355]
Hi! I downloaded an OpenJ9 build to try it out. Adopt OpenJDK doesn't has a "release" for the OpenJDK 10 + OpenJ9 combination, so I downloaded the Linux x86_64 nightly of 28 June 2018 from here:

https://adoptopenjdk.net/nightly.html?variant=openjdk10-openj9

I have a hobby project that uses Nashorn in some places, but it was failing with an exception on OpenJ9. On the other hand, this code works fine on OpenJDK 10 10.0.1+10-4 from the Debian testing amd64 repositories.

Test case:

```java
System.setProperty( "nashorn.debug", "true" );
final String[] options = { "--language=es6", "-strict" };
var factory = new NashornScriptEngineFactory();
var engine = (NashornScriptEngine) factory.getScriptEngine( options );

try {
	engine.put( "javaList", Arrays.asList( new Object[] {1,2,3} ) );
	engine.eval( "javaList.forEach(function(i){print(i);})" );
} catch ( ScriptException e ) {
	throw new RuntimeException( e );
}
```
Exception thrown in this test case:

```
Exception in thread "main" java.lang.IllegalAccessError: Failed to unreflect constructor public jdk.nashorn.javaadapters.java_lang_Iterable(jdk.nashorn.internal.runtime.ScriptObject)
	at jdk.dynalink.linker.support.Lookup.unreflectConstructor(jdk.dynalink@10.0.1/Lookup.java:245)
	at jdk.dynalink.beans.CallerSensitiveDynamicMethod.unreflectConstructor(jdk.dynalink@10.0.1/CallerSensitiveDynamicMethod.java:185)
	at jdk.dynalink.beans.CallerSensitiveDynamicMethod.getTarget(jdk.dynalink@10.0.1/CallerSensitiveDynamicMethod.java:171)
	at jdk.dynalink.beans.OverloadedDynamicMethod.getInvocation(jdk.dynalink@10.0.1/OverloadedDynamicMethod.java:220)
	at jdk.dynalink.beans.StaticClassLinker$SingleClassStaticsLinker.getGuardedInvocation(jdk.dynalink@10.0.1/StaticClassLinker.java:157)
	at jdk.dynalink.beans.StaticClassLinker.getGuardedInvocation(jdk.dynalink@10.0.1/StaticClassLinker.java:207)
	at jdk.dynalink.beans.BeansLinker$NoSuchMemberHandlerBindingLinker.getGuardedInvocation(jdk.dynalink@10.0.1/BeansLinker.java:226)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(jdk.scripting.nashorn@10.0.1/NashornBeansLinker.java:169)
	at jdk.nashorn.internal.runtime.linker.NashornStaticClassLinker.delegate(jdk.scripting.nashorn@10.0.1/NashornStaticClassLinker.java:111)
	at jdk.nashorn.internal.runtime.linker.NashornStaticClassLinker.getGuardedInvocation(jdk.scripting.nashorn@10.0.1/NashornStaticClassLinker.java:104)
	at jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(jdk.dynalink@10.0.1/CompositeTypeBasedGuardingDynamicLinker.java:184)
	at jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(jdk.dynalink@10.0.1/CompositeGuardingDynamicLinker.java:132)
	at jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(jdk.dynalink@10.0.1/LinkerServicesImpl.java:160)
	at jdk.dynalink.LinkerServicesImpl$$Lambda$67.000000004849E550.get(Unknown Source)
	at jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(jdk.dynalink@10.0.1/LinkerServicesImpl.java:191)
	at jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(jdk.dynalink@10.0.1/LinkerServicesImpl.java:158)
	at jdk.nashorn.internal.runtime.linker.JavaAdapterFactory.getConstructor(jdk.scripting.nashorn@10.0.1/JavaAdapterFactory.java:194)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getSamTypeConverter(jdk.scripting.nashorn@10.0.1/NashornLinker.java:168)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.convertToType(jdk.scripting.nashorn@10.0.1/NashornLinker.java:118)
	at jdk.dynalink.TypeConverterFactory.createConverter(jdk.dynalink@10.0.1/TypeConverterFactory.java:405)
	at jdk.dynalink.TypeConverterFactory$1$1.computeValue(jdk.dynalink@10.0.1/TypeConverterFactory.java:126)
	at jdk.dynalink.TypeConverterFactory$1$1.computeValue(jdk.dynalink@10.0.1/TypeConverterFactory.java:122)
	at jdk.dynalink.ClassMap.get(jdk.dynalink@10.0.1/ClassMap.java:155)
	at jdk.dynalink.TypeConverterFactory.getCacheableTypeConverter(jdk.dynalink@10.0.1/TypeConverterFactory.java:360)
	at jdk.dynalink.TypeConverterFactory.getCacheableTypeConverterNull(jdk.dynalink@10.0.1/TypeConverterFactory.java:347)
	at jdk.dynalink.TypeConverterFactory.getTypeConverterNull(jdk.dynalink@10.0.1/TypeConverterFactory.java:353)
	at jdk.dynalink.TypeConverterFactory.asType(jdk.dynalink@10.0.1/TypeConverterFactory.java:250)
	at jdk.dynalink.LinkerServicesImpl.asType(jdk.dynalink@10.0.1/LinkerServicesImpl.java:131)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker$NashornBeansLinkerServices.asType(jdk.scripting.nashorn@10.0.1/NashornBeansLinker.java:259)
	at jdk.dynalink.beans.LinkerServicesWithMissingMemberHandlerFactory.asType(jdk.dynalink@10.0.1/LinkerServicesWithMissingMemberHandlerFactory.java:55)
	at jdk.dynalink.beans.LinkerServicesWithMissingMemberHandlerFactory.asType(jdk.dynalink@10.0.1/LinkerServicesWithMissingMemberHandlerFactory.java:55)
	at jdk.dynalink.linker.LinkerServices.asTypeLosslessReturn(jdk.dynalink@10.0.1/LinkerServices.java:145)
	at jdk.dynalink.beans.SingleDynamicMethod.createConvertingInvocation(jdk.dynalink@10.0.1/SingleDynamicMethod.java:295)
	at jdk.dynalink.beans.SingleDynamicMethod.getInvocation(jdk.dynalink@10.0.1/SingleDynamicMethod.java:195)
	at jdk.dynalink.beans.SingleDynamicMethod.lambda$getInvocation$0(jdk.dynalink@10.0.1/SingleDynamicMethod.java:131)
	at jdk.dynalink.beans.SingleDynamicMethod$$Lambda$91.000000004877A5B0.get(Unknown Source)
	at jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(jdk.dynalink@10.0.1/LinkerServicesImpl.java:191)
	at jdk.dynalink.LinkerServicesImpl.getWithLookup(jdk.dynalink@10.0.1/LinkerServicesImpl.java:179)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker$NashornBeansLinkerServices.getWithLookup(jdk.scripting.nashorn@10.0.1/NashornBeansLinker.java:298)
	at jdk.dynalink.beans.LinkerServicesWithMissingMemberHandlerFactory.getWithLookup(jdk.dynalink@10.0.1/LinkerServicesWithMissingMemberHandlerFactory.java:85)
	at jdk.dynalink.beans.LinkerServicesWithMissingMemberHandlerFactory.getWithLookup(jdk.dynalink@10.0.1/LinkerServicesWithMissingMemberHandlerFactory.java:85)
	at jdk.dynalink.beans.SingleDynamicMethod.getInvocation(jdk.dynalink@10.0.1/SingleDynamicMethod.java:131)
	at jdk.dynalink.beans.DynamicMethodLinker.getGuardedInvocation(jdk.dynalink@10.0.1/DynamicMethodLinker.java:124)
	at jdk.dynalink.beans.BeansLinker$NoSuchMemberHandlerBindingLinker.getGuardedInvocation(jdk.dynalink@10.0.1/BeansLinker.java:226)
	at jdk.dynalink.beans.BeansLinker.getGuardedInvocation(jdk.dynalink@10.0.1/BeansLinker.java:356)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(jdk.scripting.nashorn@10.0.1/NashornBeansLinker.java:169)
	at jdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(jdk.scripting.nashorn@10.0.1/NashornBeansLinker.java:156)
	at jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(jdk.dynalink@10.0.1/CompositeGuardingDynamicLinker.java:132)
	at jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(jdk.dynalink@10.0.1/LinkerServicesImpl.java:160)
	at jdk.dynalink.LinkerServicesImpl$$Lambda$67.000000004849E550.get(Unknown Source)
	at jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(jdk.dynalink@10.0.1/LinkerServicesImpl.java:191)
	at jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(jdk.dynalink@10.0.1/LinkerServicesImpl.java:158)
	at jdk.dynalink.DynamicLinker.relink(jdk.dynalink@10.0.1/DynamicLinker.java:265)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$\^eval\_.0000000048236380.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(jdk.scripting.nashorn@10.0.1/ScriptFunctionData.java:655)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(jdk.scripting.nashorn@10.0.1/ScriptFunction.java:513)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(jdk.scripting.nashorn@10.0.1/ScriptRuntime.java:527)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(jdk.scripting.nashorn@10.0.1/NashornScriptEngine.java:448)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(jdk.scripting.nashorn@10.0.1/NashornScriptEngine.java:405)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(jdk.scripting.nashorn@10.0.1/NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(jdk.scripting.nashorn@10.0.1/NashornScriptEngine.java:154)
	at javax.script.AbstractScriptEngine.eval(java.scripting@10.0.1/AbstractScriptEngine.java:264)
	at test.Testing.main(Testing.java:424)
Caused by: java.lang.IllegalAccessException: 'jdk.scripting.nashorn.scripts' no access to: 'jdk.nashorn.javaadapters'
	at java.lang.invoke.MethodHandles$Lookup.checkClassModuleVisibility(java.base@10.0.1/MethodHandles.java:660)
	at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(java.base@10.0.1/MethodHandles.java:448)
	at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@10.0.1/MethodHandles.java:358)
	at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@10.0.1/MethodHandles.java:314)
	at java.lang.invoke.MethodHandles$Lookup.unreflectConstructor(java.base@10.0.1/MethodHandles.java:1144)
	at jdk.dynalink.linker.support.Lookup.unreflectConstructor(jdk.dynalink@10.0.1/Lookup.java:243)
	... 62 more
```

**Comment by JasonFengJ9** [comment]
Will have a look this.

**Comment by dustContributor** [comment]
Cool, thanks! I'll try it again when AdoptOpenJDK has a recent build (most recent as of writing this is from two weeks ago).
