### ISSUE TITLE
systemtest failed to build Test-sanity.system-JDK8-linux_390-64_cmprssptrs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2363]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/34/console

```
01:00:23 BUILD FAILED
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/build_test.xml:71: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/build.xml:138: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openj9-systemtest/openj9.build/build.xml:64: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openj9-systemtest/openj9.build/build.xml:49: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/build.xml:41: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:66: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:498: The following error occurred while executing this line:
01:00:23 /home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.build/include/top.xml:512: java.lang.NullPointerException
01:00:23 	at java.lang.String.lastIndexOf(String.java:2256)
01:00:23 	at java.lang.String.lastIndexOf(String.java:2212)
01:00:23 	at org.apache.tools.ant.ProjectHelper.extractUriFromComponentName(ProjectHelper.java:515)
01:00:23 	at org.apache.tools.ant.ComponentHelper.checkNamespace(ComponentHelper.java:844)
01:00:23 	at org.apache.tools.ant.ComponentHelper.getDefinition(ComponentHelper.java:307)
01:00:23 	at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:284)
01:00:23 	at org.apache.tools.ant.IntrospectionHelper$Creator.create(IntrospectionHelper.java:1336)
01:00:23 	at org.apache.tools.ant.UnknownElement.handleChild(UnknownElement.java:575)
01:00:23 	at org.apache.tools.ant.UnknownElement.handleChildren(UnknownElement.java:359)
01:00:23 	at org.apache.tools.ant.UnknownElement.handleChild(UnknownElement.java:594)
01:00:23 	at org.apache.tools.ant.UnknownElement.handleChildren(UnknownElement.java:359)
01:00:23 	at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:205)
01:00:23 	at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:164)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:347)
01:00:23 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
01:00:23 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
01:00:23 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
01:00:23 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:00:23 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
01:00:23 	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
01:00:23 	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
01:00:23 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
01:00:23 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
01:00:23 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:23 	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:23 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
01:00:23 	at org.apache.tools.ant.Task.perform(Task.java:348)
01:00:23 	at org.apache.tools.ant.Target.execute(Target.java:435)
01:00:23 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
01:00:23 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
01:00:23 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
01:00:23 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
01:00:23 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
01:00:23 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
01:00:23 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
01:00:23 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
01:00:23 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

**Comment by pshipton** [comment]
@Mesbah-Alam fyi

**Comment by Mesbah-Alam** [comment]
The build fails with NPE at https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/3ffa0ff91162dea77c07d09200fa14d8424b4f21/openjdk.build/include/top.xml#L512 - where it tries to set the property containing a normalised platform string from the java os.name property.

The same script is passing on other platforms, including linux_390-64_cmprssptrs on SE10 : https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK10-linux_390-64_cmprssptrs/

Not sure if this is a malfunction in Ant rather than the systemtest scripts. 

@pshipton - could you please relaunch the build? (I don't have permission to do so).

**Comment by AdamBrousseau** [comment]
Based on the repeated failures in the history, I doubt restarting will change anything.
