### ISSUE TITLE
TestManagementAgent failed with com.sun.tools.attach.AttachOperationFailedException

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#241]
Link to Jenkins console output: https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/16/consoleFull

Output:
```
02:51:02 ===============================================
02:51:02 Running test TestManagementAgent_SE90_0 ...
02:51:02 ===============================================
02:51:02 test with NoOptions
02:51:02 { "/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/jdk/bin/java"  -Xcompressedrefs  \
02:51:02 --add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED \
02:51:02 -cp "/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/../../jvmtest/TestConfig/resources:/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/../../jvmtest/TestConfig/lib/testng.jar:/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/../../jvmtest/TestConfig/lib/jcommander.jar:/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/../../jvmtest/Java8andUp/GeneralTest.jar" \
02:51:02 -Dcom.ibm.tools.attach.enable=yes \
02:51:02 -Dcom.ibm.tools.attach.timeout=15000 \
02:51:02 -Djava.sidecar="--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED" \
02:51:02 org.testng.TestNG -d "/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/test_output_1507099002/TestManagementAgent_SE90_0" "/home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/test/TestConfig/../../jvmtest/Java8andUp/testng.xml" -testnames TestManagementAgent \
02:51:02 -groups level.extended \
02:51:02 -excludegroups d.*.linux_390-64_cmprssptrs,d.*.arch.390,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
02:51:02 if [ $? -eq 0 ] ; then echo "TestManagementAgent_SE90_0""_PASSED"; else echo "TestManagementAgent_SE90_0""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
02:51:10 [XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.
02:51:10 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/jvmtest/TestConfig/resources/excludes/default_exclude.txt
02:51:10 ...
02:51:10 ... TestNG 6.10 by Cédric Beust (cedric@beust.com)
02:51:10 ...
02:51:10 
02:51:10 [TestNG] Running:
02:51:10   /home/jenkins/jenkins-agent/workspace/Test-Extended-linux_390-64_cmprssptrs/jvmtest/Java8andUp/testng.xml
02:51:10 
02:51:14 com.sun.tools.attach.AttachOperationFailedException: AttachOperationFailedException from target: ATTACH_ERR AttachOperationFailedException in startLocalManagementAgent:  startLocalManagementAgent: com.sun.management.jmxremote.localConnectorAddress not defined
02:51:14 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(jdk.attach@9-internal/OpenJ9VirtualMachine.java:336)
02:51:14 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.startLocalManagementAgent(jdk.attach@9-internal/OpenJ9VirtualMachine.java:522)
02:51:14 	at org.openj9.test.attachAPI.TestManagementAgent.test_startLocalManagementAgent(TestManagementAgent.java:113)
02:51:14 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
02:51:14 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
02:51:14 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
02:51:14 	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
02:51:14 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
02:51:14 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
02:51:14 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
02:51:14 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
02:51:14 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
02:51:14 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
02:51:14 	at org.testng.TestRunner.privateRun(TestRunner.java:756)
02:51:14 	at org.testng.TestRunner.run(TestRunner.java:610)
02:51:14 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
02:51:14 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
02:51:14 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
02:51:14 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
02:51:14 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:51:14 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
02:51:14 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
02:51:14 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
02:51:14 	at org.testng.TestNG.runSuites(TestNG.java:1133)
02:51:14 	at org.testng.TestNG.run(TestNG.java:1104)
02:51:14 	at org.testng.TestNG.privateMain(TestNG.java:1434)
02:51:14 	at org.testng.TestNG.main(TestNG.java:1403)
```

**Comment by pdbain-ibm** [comment]
@llxia please assign this to me.  Thank you.
