### ISSUE TITLE
testCrNocr in VmArgumentTests failed - java.lang.AssertionError: Target process failed

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#244]
Link to Jenkins console output: https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/16/consoleFull

Output:
```
03:03:04 FAILED: testCrNocr
03:03:04 java.lang.AssertionError: Target process failed
03:03:04 	at org.testng.Assert.fail(Assert.java:94)
03:03:04 	at org.openj9.test.vmArguments.VmArgumentTests.runAndGetArgumentList(VmArgumentTests.java:1387)
03:03:04 	at org.openj9.test.vmArguments.VmArgumentTests.testCrNocr(VmArgumentTests.java:324)
03:03:04 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
03:03:04 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
03:03:04 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
03:03:04 	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
03:03:04 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
03:03:04 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
03:03:04 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
03:03:04 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
03:03:04 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
03:03:04 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
03:03:04 	at org.testng.TestRunner.privateRun(TestRunner.java:756)
03:03:04 	at org.testng.TestRunner.run(TestRunner.java:610)
03:03:04 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
03:03:04 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
03:03:04 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
03:03:04 	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
03:03:04 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:03:04 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
03:03:04 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
03:03:04 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
03:03:04 	at org.testng.TestNG.runSuites(TestNG.java:1133)
03:03:04 	at org.testng.TestNG.run(TestNG.java:1104)
03:03:04 	at org.testng.TestNG.privateMain(TestNG.java:1434)
03:03:04 	at org.testng.TestNG.main(TestNG.java:1403)
```

**Comment by pdbain-ibm** [comment]
@llxia please assign this to me.  Thank you.

**Comment by llxia** [comment]
@pdbain-ibm I think the UI only allows me to assign to committers.

**Comment by TianyuZuo** [comment]
The https://github.com/eclipse/openj9/pull/245 didn't work, the test src has to have `@Test` on the test functions to make the exclusion mechanism work. New PR updated the test src https://github.com/eclipse/openj9/pull/644

Hi @pdbain-ibm 

Are we going to have nocompressedref OpenJ9? I thought we are only supplying compressedref OpenJ9s. If this is our currently goal, I think we can disable this test from OpenJ9.

**Comment by pdbain-ibm** [comment]
According to issue #479, "not yet".  There is a proposal (issue #643) to make it a runtime check.

**Comment by TianyuZuo** [comment]
Thanks for the information, test is now successfully excluded from https://github.com/eclipse/openj9/pull/644#event-1353252595
