### ISSUE TITLE
Test-extended.functional-JDK10-linux_ppc-64_cmprssptrs_le threadMXBeanTestSuite1_7 testFindDeadlockTest fail

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2523]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_ppc-64_cmprssptrs_le/28

```
===============================================
Running test threadMXBeanTestSuite1_7 ...
===============================================
threadMXBeanTestSuite1_7 Start Time: Tue Jul 31 06:53:23 2018 Epoch Time (ms): 1533020003355
test with Mode610 -Xjit:noJitUntilMain,count=0,optlevel=warm
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-extended.functional-JDK10-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE100.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[FindDeadlockTest] [ERROR] Not deadlocks:
[FindDeadlockTest] [ERROR] Deadlocks not found:
tid: 43 (ds3)
blocker: java.util.concurrent.locks.ReentrantLock$NonfairSync@818b5ef0
owner: 44 (ds4)

PASSED: testAPITest
PASSED: testMonitorTraceTest
PASSED: testParkedThreadTest
FAILED: testFindDeadlockTest
java.lang.AssertionError: The following asserts failed:
	findDeadlocks failed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10.0.2-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10.0.2-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10.0.2-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@10.0.2-internal/Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    threadMXBeanTestSuite1
    Tests run: 4, Failures: 1, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
No re-occurrences, assuming fixed.

**Comment by pshipton** [comment]
Another one, different platform.
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/36
threadMXBeanTestSuite1_7
```
FAILED: testFindDeadlockTest
java.lang.AssertionError: The following asserts failed:
	findDeadlocks failed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/459
threadMXBeanTestSuite1_4
```
FAILED: testFindDeadlockTest
java.lang.AssertionError: The following asserts failed:
	findDeadlocks failed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/531
threadMXBeanTestSuite1_7
```
FAILED: testFindDeadlockTest
java.lang.AssertionError: The following asserts failed:
	findDeadlocks failed expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/474

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/595/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Release_testList_0/70

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/67/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly/605

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/94

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/745

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/752

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_1/693

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/218

**Comment by JasonFengJ9** [comment]
[JDK22 s390x_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk22_j9_extended.functional_s390x_linux_testList_0/50/)(`rhel9s390x-svl-rt6-1`)
```
[2024-05-18T20:22:57.046Z] variation: Mode610 -Xjit:noJitUntilMain,count=0,optlevel=warm
[2024-05-18T20:22:57.046Z] JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xjit:noJitUntilMain,count=0,optlevel=warm 

[2024-05-18T20:24:14.584Z] FAILED: testFindDeadlockTest
[2024-05-18T20:24:14.584Z] java.lang.AssertionError: The following asserts failed:
[2024-05-18T20:24:14.584Z] 	findDeadlocks failed expected [true] but found [false]
[2024-05-18T20:24:14.584Z] 	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
[2024-05-18T20:24:14.584Z] 	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)

[2024-05-18T20:24:14.584Z] ===============================================
[2024-05-18T20:24:14.584Z]     threadMXBeanTestSuite1
[2024-05-18T20:24:14.584Z]     Tests run: 4, Failures: 1, Skips: 0
[2024-05-18T20:24:14.584Z] ===============================================
[2024-05-18T20:24:14.584Z] 
[2024-05-18T20:24:14.584Z] 
[2024-05-18T20:24:14.584Z] ===============================================
[2024-05-18T20:24:14.584Z] GeneralTest suite
[2024-05-18T20:24:14.584Z] Total tests run: 4, Failures: 1, Skips: 0
[2024-05-18T20:24:14.584Z] ===============================================
[2024-05-18T20:24:14.584Z] 
[2024-05-18T20:24:15.062Z] -----------------------------------
[2024-05-18T20:24:15.062Z] threadMXBeanTestSuite1_7_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/910/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk23_j9_extended.functional_s390x_linux_Nightly_testList_1/130
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Release_testList_0/134 - 0.49
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/411
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/971
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_0/478/
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/496
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_Nightly_testList_0/1026
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_s390x_linux_Nightly_testList_1/598

**Comment by JasonFengJ9** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly_testList_1/1244/consoleFull
```
06:40:34  Running test threadMXBeanTestSuite1_11 ...
06:40:34  ===============================================
06:40:34  threadMXBeanTestSuite1_11 Start Time: Tue Mar  3 11:40:30 2026 Epoch Time (ms): 1772538030666
06:40:34  variation: Mode551 -Xjit:noJitUntilMain,count=0,optlevel=warm
06:40:34  JVM_OPTIONS:  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -Xjit:noJitUntilMain,count=0,optlevel=warm 

06:41:39  FAILED: testFindDeadlockTest
06:41:39  java.lang.AssertionError: The following asserts failed:
06:41:39  	findDeadlocks failed expected [true] but found [false]
06:41:39  	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
06:41:39  	at org.openj9.test.java.lang.management.ThreadMXBean.FindDeadlockTest.testFindDeadlockTest(FindDeadlockTest.java:66)
```
