### ISSUE TITLE
Neo4J Fails to build with openjdk8-openj9

### ISSUE THREAD

**Issue by AlenBadel** [eclipse/openj9#2555]
Using OpenJ9 Version: 

`openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_08_06_16_09-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)`

Steps to reproduce

1) git clone https://github.com/neo4j/neo4j.git

2) apt install debhelper devscripts dos2unix dpkg make xmlstarlet

3) Set JAVA_HOME & PATH

4) mvn clean install

The issue looks to be isolated in the licensing plugin in mavin 
https://www.mojohaus.org/license-maven-plugin/

Output

```
[ERROR] Failed to execute goal org.neo4j.build.plugins:licensing-maven-plugin:1.7.7:check (list-all-licenses) on project neo4j-common: Could not read licensing requirements file: licensing/licensing-requirements-base.xml: **Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor : Cannot construct** org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] ---- Debugging information ----
[ERROR] message             : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
[ERROR] cause-message       : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] class               : org.linuxstuff.mojo.licensing.model.CoalescedLicense
[ERROR] required-type       : org.linuxstuff.mojo.licensing.model.CoalescedLicense
[ERROR] converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] path                : /licensing-requirements/coalesced-licenses/license
[ERROR] line number         : 76
[ERROR] class[1]            : java.util.HashSet
[ERROR] converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
[ERROR] class[2]            : org.linuxstuff.mojo.licensing.model.LicensingRequirements
[ERROR] version             : null
[ERROR] -------------------------------
```

Verbose Log

```
[DEBUG] URLResourceLoader: Exception when looking for 'licensing/licensing-requirements-base.xml
java.net.MalformedURLException: no protocol: licensing/licensing-requirements-base.xml
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.codehaus.plexus.resource.loader.URLResourceLoader.getResource(URLResourceLoader.java:123)
	at org.codehaus.plexus.resource.DefaultResourceManager.getResource(DefaultResourceManager.java:159)
	at org.codehaus.plexus.resource.DefaultResourceManager.getResourceAsInputStream(DefaultResourceManager.java:67)
	at org.linuxstuff.mojo.licensing.AbstractLicensingMojo.readLicensingRequirements(AbstractLicensingMojo.java:219)
	at org.linuxstuff.mojo.licensing.CheckMojo.execute(CheckMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

> ---- Debugging information ----
> message             : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
> cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
> cause-message       : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
> class               : org.linuxstuff.mojo.licensing.model.CoalescedLicense
> required-type       : org.linuxstuff.mojo.licensing.model.CoalescedLicense
> converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
> path                : /licensing-requirements/coalesced-licenses/license
> line number         : 76
> class[1]            : java.util.HashSet
> converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
> class[2]            : org.linuxstuff.mojo.licensing.model.LicensingRequirements
> version             : null

-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:79)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:72)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:921)
	at org.linuxstuff.mojo.licensing.AbstractLicensingMojo.readLicensingRequirements(AbstractLicensingMojo.java:219)
	... 23 more
Caused by: com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:71)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:428)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:233)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 47 more
`
```

**Comment by DanHeidinga** [comment]
```
com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:71)
```

The message looks correct - the no-args constructor is missing from `CoalescedLicense` & the class isn't Serializable (both of which `PureJavaReflectionProvider`) checks.

Have you been able to build this successfully with other JDKs?  I'm trying to understand what would be different about OpenJ9 to cause the issue or if this needs to be fixed in `CoalescedLicense`

**Comment by DanHeidinga** [comment]
What version of the Maven license plugin is being used?  Is it up to date?

**Comment by AlenBadel** [comment]
@DanHeidinga 

Neo4J built perfectly with openjdk8-hotspot

Looks like 1.7.7 was used
```
          <groupId>org.neo4j.build.plugins</groupId>
          <artifactId>licensing-maven-plugin</artifactId>
          <version>1.7.7</version> 
```

**Comment by DanHeidinga** [comment]
Can you generate a java+system core when the exception is generated?  

The -Xdump option can do this.  Something like
`-Xdump:java+system:events=throw,filter=com/thoughtworks/xstream/converters/reflection/ObjectAccessException
`

It'll then be possible to look at the core in `jdmpview` and see the VM's state.  Hopefully that will allow us to figure what's going sideways.

**Comment by AlenBadel** [comment]
Building -Xdump you provided failed to produce a core file

> 
> [INFO] --- licensing-maven-plugin:1.7.7:check (list-all-licenses) @ neo4j-common ---
> JVMDUMP039I Processing dump event "throw", detail "com/thoughtworks/xstream/converters/reflection/ObjectAccessException" at 2018/08/16 10:11:13 - please wait.
> JVMDUMP032I JVM requested System dump using '/home/abadel/neo4j/build_openj9/neo4j/core.20180816.101113.41548.0001.dmp' in response to an event
> JVMDUMP012E Error in System dump: The core file created by child process with pid = 41777 was not found. Expected to find core file with name "/home/abadel/neo4j/build_openj9/neo4j/core"
> JVMDUMP032I JVM requested Java dump using '/home/abadel/neo4j/build_openj9/neo4j/javacore.20180816.101113.41548.0002.txt' in response to an event
> 
> JVMDUMP010I Java dump written to /home/abadel/neo4j/build_openj9/neo4j/javacore.20180816.101113.41548.0002.txt
> JVMDUMP013I Processed dump event "throw", detail "com/thoughtworks/xstream/converters/reflection/ObjectAccessException".

**Comment by DanHeidinga** [comment]
Can you attach the javacore that was created?  

Odd that the system core creation failed.  Can you tell me more about the environment? Do the `ulimits` allow cores to be created?  Which version of linux are you using?  Is this in a docker image?

**Comment by AlenBadel** [comment]
You were absolutely right, I was able to capture results after enabling core file generation via ulimit. 

Attached are the results. 

This was generated by using the follow jdk - on powerpc but was reproduced on X86. 

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
Eclipse OpenJ9 VM (build master-60bc16b9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20180806_226 (JIT enabled, AOT enabled)
OpenJ9   - 60bc16b9
OMR      - a796976b
JCL      - 1523b9c0 based on jdk8u181-b13)

**Comment by DanHeidinga** [comment]
> Attached are the results.

Sorry, might be slow today but I don't see a core file attached or linked from here.  Can you point me at the core?

**Comment by AlenBadel** [comment]
@DanHeidinga Please see https://ibm.box.com/s/6vxdi3kolbc7qfbcwu7faujm80p98q69

**Comment by ChengJin01** [comment]
I already checked the stacktraces in the core dump attached above.
[coredump_stacktraces.txt](https://github.com/eclipse/openj9/files/2606003/coredump_stacktraces.txt)

I didn't spot anything special in there given that the code related is already in the open source at https://github.com/jenkinsci/xstream

```> stackslots  0x00044500
<44500> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x0000000000044500 ***
<44500>         ITERATE_O_SLOTS
<44500>         RECORD_BYTECODE_PC_OFFSET
<44500> Initial values: walkSP = 0x00000000005E0350, PC = 0x0000000000000001, literals = 0x0000000000000000, A0 = 0x00000000005E0368, j2iFrame = 0x0000000000000000, ELS = 0x00003FFF8F46D990, decomp = 0x0000000000000000
<44500> Generic special frame: bp = 0x00000000005E0368, sp = 0x00000000005E0350, pc = 0x0000000000000001, cp = 0x0000000000000000, arg0EA = 0x00000000005E0368, flags = 0x0000000000000000
<44500> Bytecode frame: bp = 0x00000000005E0380, sp = 0x00000000005E0370, pc = 0x00003FFF89C0218B, cp = 0x0000000000979E80, arg0EA = 0x00000000005E03A8, flags = 0x0000000000000000
<44500>         Method: com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider.newInstance(Ljava/lang/Class;)Ljava/lang/Object; !j9method 0x000000000097A820
<44500>         Bytecode index = 107
<44500>         Using local mapper
<44500>         Locals starting at 0x00000000005E03A8 for 0x0000000000000005 slots
<44500>                 I-Slot: a0[0x00000000005E03A8] = 0x00000000FEB24E48
<44500>                 O-Slot: a1[0x00000000005E03A0] = 0x00000000E40BDE98
<44500>                 I-Slot: t2[0x00000000005E0398] = 0x00000000FF0F8A28
<44500>                 I-Slot: t3[0x00000000005E0390] = 0x0000000000000001
<44500>                 I-Slot: t4[0x00000000005E0388] = 0x00000000FF0F8A38
<44500> Bytecode frame: bp = 0x00000000005E03C0, sp = 0x00000000005E03B0, pc = 0x00003FFF89C0CF1B, cp = 0x000000000098C140, arg0EA = 0x00000000005E03F0, flags = 0x0000000000000000
<44500>         Method: com/thoughtworks/xstream/converters/reflection/AbstractReflectionConverter.instantiateNewInstance(Lcom/thoughtworks/xstream/io/HierarchicalStreamReader;Lcom/thoughtworks/xstream/converters/UnmarshallingContext;)Ljava/lang/Object; !j9method 0x000000000098CE20
<44500>         Bytecode index = 83
<44500>         Using local mapper
<44500>         Locals starting at 0x00000000005E03F0 for 0x0000000000000006 slots
```

Looking at the specific code at https://github.com/jenkinsci/xstream/blob/master/xstream/src/java/com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider.java
```
public Object newInstance(Class type) {
        try {
            Constructor[] constructors = type.getDeclaredConstructors();
            for (int i = 0; i < constructors.length; i++) {
                final Constructor constructor = constructors[i];
                if (constructor.getParameterTypes().length == 0) {
                    if (!constructor.isAccessible()) {
                        constructor.setAccessible(true);
                    }
                    return constructor.newInstance(new Object[0]); <--- return normally
                }
            }
            if (Serializable.class.isAssignableFrom(type)) {
                return instantiateUsingSerialization(type);  <--- return normally
            } else {
                throw new ObjectAccessException("Cannot construct " + type.getName()
               + " as it does not have a no-args constructor"); <---- this is where exception got thrown out
            }
        } catch (InstantiationException e) {
     ...
```

If this case, it is the code logic there that determines whether to throw out ObjectAccessException instead of the code itself.

That being said, the exception was thrown out simply because Serializable.class.isAssignableFrom(type) returned false (type is no assignable to Serializable.class)

**Comment by DanHeidinga** [comment]
```
<44500>                 O-Slot: a1[0x00000000005E03A0] = 0x00000000E40BDE98
```
@ChengJin01 this should be a java.lang.Class Object.  Can you validate it is a Class, and then dump the romclass?  That'll show the constructors and we can crawl the heirarchy to confirm it's not Serializable.

There has to be something diff between our implementation and the RI to explain the behaviour difference

**Comment by ChengJin01** [comment]
1) Looking at the thrown exception above against the source code:
```
com.thoughtworks.xstream.converters.reflection.ObjectAccessException: 
Cannot construct 
org.linuxstuff.mojo.licensing.model.CoalescedLicense  <---------- this is the passed-in argument: type
as it does not have a no-args constructor
```
public Object newInstance(Class type) {
        try {
            Constructor[] constructors = type.getDeclaredConstructors(); <------
```
throw new ObjectAccessException("Cannot construct " + type.getName() <--- "type" is CoalescedLicense
       + " as it does not have a no-args constructor"); 
}
```

2) Double-checked the bytecode of PureJavaReflectionProvider.newInstance against the source code:
```
```
[PureJavaReflectionProvider.newInstance_bytecode.txt](https://github.com/eclipse/openj9/files/2611416/PureJavaReflectionProvider.newInstance_bytecode.txt)
```
Signature: com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider.newInstance(Ljava/lang/Class;)Ljava/lang/Object; !bytecodes 0x000000000097A820
...
  Argument Count: 2
  Temp Count: 3

    0 aload1   <--------- argument "type" was stored at local variable at index 1
    1 invokevirtual 22 java/lang/Class.getDeclaredConstructors()[Ljava/lang/reflect/Constructor;
    4 astore2
```

Also checked the stacktrace in the core dump:
```
<44500>         Method: com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider.newInstance(Ljava/lang/Class;)Ljava/lang/Object; !j9method 0x000000000097A820
<44500>         Bytecode index = 107
<44500>         Using local mapper
<44500>         Locals starting at 0x00000000005E03A8 for 0x0000000000000005 slots
<44500>                 I-Slot: a0[0x00000000005E03A8] = 0x00000000FEB24E48 (PureJavaReflectionProvider)
<44500>                 O-Slot: a1[0x00000000005E03A0] = 0x00000000E40BDE98  <----- type was stored at local variable at index 1

> j9object  0x00000000FEB24E48
!J9Object 0x00000000FEB24E48 {
      struct J9Class* clazz = !j9class 0x97A600   // com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider
      Object flags = 0x00000000;
      I lockword = 0x00000000 (offset=0) (java/lang/Object) <hidden>
      Ljava/util/Map; serializedDataCache = !fj9object 0xfeb50650 (offset=4) (com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider)
      Lcom/thoughtworks/xstream/converters/reflection/FieldDictionary; fieldDictionary = !fj9object 0xfeb4d668 (offset=8) (com/thoughtworks/xstream/converters/reflection/PureJavaReflectionProvider)

> j9object  0x00000000E40BDE98
!J9Object 0x00000000E40BDE98 {
      struct J9Class* clazz = !j9class 0x62400   // java/lang/Class
      Object flags = 0x0000003A;
      I lockword = 0x00000000 (offset=0) (java/lang/Object) <hidden>
      J vmRef = 0x00000000009B1200 (offset=4) (java/lang/Class)
      Ljava/lang/ClassLoader; classLoader = !fj9object 0xfe60bb98 (offset=12) (java/lang/Class)
      Ljava/security/ProtectionDomain; protectionDomain = !fj9object 0xfe626768 (offset=16) (java/lang/Class)
      Ljava/lang/String; classNameString = !fj9object 0xe40bdee8 (offset=20) (java/lang/Class) <--------

>  fj9object 0xe40bdee8
J9VMJavaLangString at 0x00000000E40BDEE8 {

struct J9Class* clazz = !j9class 0x67A00   // java/lang/String
Object flags = 0x00000030;
[C value = !fj9object 0xe40bdef8 (offset=0) (java/lang/String)
I count = 0x00000034 (offset=4) (java/lang/String)
I hashCode = 0xBE64A1DC (offset=8) (java/lang/String)
"org.linuxstuff.mojo.licensing.model.CoalescedLicense"

```

3) Dumped the romclass of CoalescedLicense
[CoalescedLicense_dumpromclass.txt](https://github.com/eclipse/openj9/files/2611430/CoalescedLicense_dumpromclass.txt)
```
  Name: <init>
  Signature: (Ljava/lang/String;Ljava/util/Set;)V <----- only one constructor with two arguments
  Access Flags (2040001): public
  Max Stack: 2
  Argument Count: 3
  Temp Count: 0

    0 aload0
    1 invokespecial 1 java/lang/Object.<init>()V
    4 aload0
    5 aload1
    6 putfield 2 org/linuxstuff/mojo/licensing/model/CoalescedLicense.finalName Ljava/lang/String;
    9 aload0
   10 aload2
   11 putfield 3 org/linuxstuff/mojo/licensing/model/CoalescedLicense.otherNames Ljava/util/Set;
   14 returnFromConstructor
```
Which means the code won't return from `return constructor.newInstance(new Object[0]);` (the requested constructor has no argument) as CoalescedLicense.<init> has two arguments. So the logic goes to 
```
if (Serializable.class.isAssignableFrom(type)) {

   57 ldcw 28 (java.lang.Class) java/io/Serializable
   60 aload1
   61 invokevirtual 29 java/lang/Class.isAssignableFrom(Ljava/lang/Class;)Z <--------------
   64 ifeq 73
```

4) According to the dumped content, CoalescedLicense has no direct/indirect relation to Serializable,
```
>  dumpromclass  0x00003FFF89C49DB0
ROM Size: 0x5f8 (1528)
Class Name: org/linuxstuff/mojo/licensing/model/CoalescedLicense
Superclass Name: java/lang/Object  <-----------------
Source File Name: CoalescedLicense.java
Sun Access Flags (0x21): public super J9  Access Flags (0x8800000): (preverified)
Class file version: 52.0
Instance Shape: 0xe
Intermediate Class Data (1528 bytes): 3fff89c49db0
Maximum Branch Count: 7
```
which means Serializable is not a superclass or superinterface of CoalescedLicense.

**Comment by ChengJin01** [comment]
If so,  the code logic in isAssignableFrom() is correct in checking CoalescedLicense.

**Comment by prakaashkpk** [comment]
The issue seems to be similar to https://www.ibm.com/developerworks/community/forums/html/topic?id=c3a1feb4-aa3a-4702-9ca2-f3daeb47d504

**Comment by DanHeidinga** [comment]
Closing as this has gone stale (and the link to the similar problem indicates that issue has been fixed)
