### ISSUE TITLE
javacore captures environment variable ghprbPullLongDescription containing exception description

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2561]
`OpenJ9 javacore` captures environment variables however `ghprbPullLongDescription` set by PR builds might contain stacktrace and exception descriptions, hence fail tests which incorrectly assume the exception was generated by current test.

This is discovered from PR test https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/64/consoleFull
```
17:10:32  [OUT] 2CIENVVAR      ghprbPullLongDescription=FV tests for Skipping parameter access check for reflect objects #2402\r\n\r\nAdded the test within `Java9andUp`\r\nThe test has two named modules `org.openj9test.modularity.dummy` and `org.openj9test.modularity.testUnreflect`, and one unnamed module (classes in classpath).\r\nThe tests check if a named module `org.openj9test.modularity.testUnreflect` can `unreflectXXX` an incoming reflect object which contains a reference to a named module `org.openj9test.modularity.dummy` that doesn't export the package `org.openj9.test.modularity.dummy` unconditionally (specifically not export to current running module `org.openj9test.modularity.testUnreflect`).\r\n\r\nManually run the test `make UnreflectTests_0`\r\n```\r\nPASSED: testLookupUnreflect\r\nPASSED: testLookupUnreflectConstructor\r\nPASSED: testLookupUnreflectGetter\r\nPASSED: testLookupUnreflectSetter\r\nPASSED: testLookupUnreflectSpecial\r\nPASSED: testLookupUnreflectVarHandle\r\n\r\n===============================================\r\n    UnreflectTests\r\n    Tests run: 6, Failures: 0, Skips: 0\r\n===============================================\r\n```\r\n\r\n
Without PR #2402, it will fail with an error like following:\r\n```\r\n
FAILED: testLookupUnreflectConstructor\r\njava.lang.IllegalAccessError: 'org.openj9test.modularity.testUnreflect' no access to: 'org.openj9.test.modularity.dummy'\r\n	at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@10.0.1-internal/MethodHandles.java:383)\r\n	at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@10.0.1-internal/MethodHandles.java:314)\r\n	at java.lang.invoke.MethodHandles$Lookup.unreflectConstructor(java.base@10.0.1-internal/MethodHandles.java:1159)\r\n	at org.openj9.test.modularity.tests.UnreflectTests.testLookupUnreflectConstructor(org.openj9test.modularity.testUnreflect/UnreflectTests.java:53)\r\n	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10.0.1-internal/Native Method)\r\n	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10.0.1-internal/NativeMethodAccessorImpl.java:62)\r\n	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10.0.1-internal/DelegatingMethodAccessorImpl.java:43)\r\n	at java.lang.reflect.Method.invoke(java.base@10.0.1-internal/Method.java:564)\r\n	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)\r\n	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)\r\n	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)\r\n	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n	at org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n	at org.testng.TestRunner.run(TestRunner.java:505)\r\n	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n	at org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n	at org.testng.TestNG.runSuites(TestNG.java:1049)\r\n	at org.testng.TestNG.run(TestNG.java:1017)\r\n	at org.testng.TestNG.privateMain(TestNG.java:1354)\r\n	at org.testng.TestNG.main(TestNG.java:1323)\r\n
Caused by: java.lang.IllegalAccessException: 'org.openj9test.modularity.testUnreflect' no access to: 'org.openj9.test.modularity.dummy'\r\n	at java.lang.invoke.MethodHandles$Lookup.checkClassModuleVisibility(java.base@10.0.1-internal/MethodHandles.java:673)\r\n	at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@10.0.1-internal/MethodHandles.java:377)\r\n	... 27 more\r\n```\r\n\r\nReviewer: @DanHeidinga \r\n\r\nSigned-off-by: Jason Feng <fengj@ca.ibm.com>
```

The test failed because of `Exception` found in the `javacore.txt`.
```
17:10:26 Testing: Test 175: Ensure AOT/JIT sizes are correct in generated javacore
17:10:26 Test start time: 2018/08/07 21:10:26 Coordinated Universal Time
17:10:26 Running command: cat javacore.txt

17:10:32 >> Failure condition was found: [Output match: Exception:]
```

The test probably can be more robust to check specific `Exception` or avoid anything specific to environment variables.
On the another hand, `ghprbPullLongDescription` probably can remove the keywords such as `Error` or `Exception`, or is this variable necessary?

**Comment by JasonFengJ9** [comment]
This issue was reported earlier at https://github.com/eclipse/openj9/issues/1885
