### ISSUE TITLE
JDK12 module-info.java.extra GenModuleInfoSource compatibility error

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#2587]
JDK12 has updated the GenModuleInfoSource build tool, and it is more stringent on the format of the module-info.java.extra files, we now get this error:
```
Exception in thread "main" java.lang.Error: /home/admin/mydocker/ccm/jdkheadPublic/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/module-info.java.extra, line 22, cannot declare module in /home/admin/mydocker/ccm/jdkheadPublic/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/module-info.java.extra "module java.base {"
	at build.tools.module.GenModuleInfoSource$Parser.newError(GenModuleInfoSource.java:764)
	at build.tools.module.GenModuleInfoSource$ModuleInfo.process(GenModuleInfoSource.java:397)
	at build.tools.module.GenModuleInfoSource$ModuleInfo.parseExtra(GenModuleInfoSource.java:380)
	at build.tools.module.GenModuleInfoSource$ModuleInfo.access$100(GenModuleInfoSource.java:175)
	at build.tools.module.GenModuleInfoSource.<init>(GenModuleInfoSource.java:136)
	at build.tools.module.GenModuleInfoSource.main(GenModuleInfoSource.java:112)
```

**Comment by keithc-ca** [comment]
Fixed via #2586.
