### ISSUE TITLE
IOException deleting files in VmArgumentTests_0 on windows

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2642]
```
PASSED: testXprod
PASSED: testXserviceInOptionsFile
FAILED: testDumpDirectory
java.io.IOException: Error deleting w:\builds\bld_394700\jvmtest\test\SE80\functional\Java8andUp\dumps\javacore.20180816.225019.10172.0001.txt
	at org.openj9.test.util.FileUtilities.deleteRecursive(FileUtilities.java:63)
	at org.openj9.test.util.FileUtilities.deleteRecursive(FileUtilities.java:55)
	at org.openj9.test.util.FileUtilities.deleteRecursive(FileUtilities.java:38)
```

**Comment by pdbain-ibm** [comment]
This appears to have been a problem with internal builds. I will reopen it if it recurs in public builds.
@llxia FYI.
