### ISSUE TITLE
Test-extended.functional-JDK11-linux_x86-64_cmprssptrs TestAttachAPI failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2704]
`===============================================`
Running test TestAttachAPI_0 ...
`===============================================`
TestAttachAPI_0 Start Time: Thu Aug 23 16:22:17 2018 Epoch Time (ms): 1535041337228
test with NoOptions
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE110.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[AttachApiTest] [ERROR] com.sun.tools.attach.AgentLoadException: ATTACH_ERR AgentLoadException jvmtitest:
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(jdk.attach@11-internal/OpenJ9VirtualMachine.java:326)
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgentLibrary(jdk.attach@11-internal/OpenJ9VirtualMachine.java:244)
	at com.sun.tools.attach.VirtualMachine.loadAgentLibrary(jdk.attach@11-internal/VirtualMachine.java:377)
	at org.openj9.test.attachAPI.TestAttachAPI.test_agntld01(TestAttachAPI.java:132)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

[TargetManager] [ERROR] JVMJ9GC070E Failed to startup the Garbage Collector

[TargetManager] [ERROR] Error: Could not create the Java Virtual Machine.

[TargetManager] [ERROR] Error: A fatal exception has occurred. Program will exit.

[TargetManager] [ERROR] Error: A fatal exception has occurred. Program will exit.

FAILED: test_agntld01
java.lang.AssertionError: missing Agent_OnAttach string in starting

	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.attachAPI.TestAttachAPI.test_agntld01(TestAttachAPI.java:153)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: test_agntld02
java.lang.AssertionError: missing Agent_OnAttach string in starting

FAILED: test_agntld03
java.lang.AssertionError: missing Agent_OnAttach string

FAILED: test_attach01_02
java.lang.AssertionError: checkHashes ERROR: no target VMs found

FAILED: test_attach03
java.lang.AssertionError: checkHashes ERROR: no target VMs found

FAILED: test_vmlist01
java.lang.AssertionError: VirtualMachine.list contains test_vmlist012 my_test_vmlist012

`===============================================`
GeneralTest suite
Total tests run: 27, Failures: 6, Skips: 0
`===============================================`

TestAttachAPI_0_FAILED

FAILED: test_startupShutdownRobustness
java.lang.AssertionError: cannot find /tmp/test_startupShutdownRobustness_logs/_null.log

`===============================================`
GeneralTest suite
Total tests run: 14, Failures: 1, Skips: 0
`===============================================`

TestAttachErrorHandling_0_FAILED

FAILED: testAgentLoading
java.lang.AssertionError: missing Agent_OnAttach string

`===============================================`
GeneralTest suite
Total tests run: 3, Failures: 1, Skips: 0
`===============================================`

TestSunAttachClasses_0_FAILED

**Comment by pdbain-ibm** [comment]
Looks like a GC issue:
```
[TargetManager] [ERROR] JVMJ9GC070E Failed to startup the Garbage Collector

[TargetManager] [ERROR] Error: Could not create the Java Virtual Machine.

[TargetManager] [ERROR] Error: A fatal exception has occurred. Program will exit.

[TargetManager] [ERROR] Error: A fatal exception has occurred. Program will exit.
```
Is the failure reproducible?

**Comment by JasonFengJ9** [comment]
It still fails though the error is not identical.
```
===============================================
Running test TestAttachAPI_0 ...
===============================================
TestAttachAPI_0 Start Time: Wed Sep 12 04:59:16 2018 Epoch Time (ms): 1536728356254
test with NoOptions
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/j9build/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE110.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[AttachApiTest] [ERROR] com.sun.tools.attach.AgentLoadException: ATTACH_ERR AgentLoadException jvmtitest:
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(jdk.attach@11-internal/OpenJ9VirtualMachine.java:326)
	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgentLibrary(jdk.attach@11-internal/OpenJ9VirtualMachine.java:244)
	at com.sun.tools.attach.VirtualMachine.loadAgentLibrary(jdk.attach@11-internal/VirtualMachine.java:377)
	at org.openj9.test.attachAPI.TestAttachAPI.test_agntld01(TestAttachAPI.java:132)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pdbain-ibm** [comment]
This is a known issue: the test requires a native JVMTI agent which was missing in the builds.
The associated tests were previously excluded.
The native agent is likely either missing or in the wrong location.
Please re-exclude the tests.

**Comment by pshipton** [comment]
Note the JVMTI agent should be available in the Java 11 builds now. @llxia

**Comment by llxia** [comment]
I will look into this. Likely new location needed to be added into lib path.

**Comment by llxia** [comment]
yes, $(ADD_JVM_LIB_DIR_TO_LIBPATH) needs to be added. I will create a PR for this.
