### ISSUE TITLE
Test-extended.functional-JDK11-linux_x86-64_cmprssptrs JVMCFRE145 Nest host must be a constant class

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2708]
Exception in thread "main" java.lang.ClassFormatError: JVMCFRE145 Nest host must be a constant class; class=com/ibm/j9/jsr292/AdaptorTests$PackageExamplesCrossPackageSubClass, offset=521
	at java.lang.ClassLoader.defineClassImpl(java.base@11-internal/Native Method)
	at java.lang.ClassLoader.defineClass(java.base@11-internal/ClassLoader.java:459)
	at java.security.SecureClassLoader.defineClass(java.base@11-internal/SecureClassLoader.java:174)
	at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@11-internal/BuiltinClassLoader.java:1098)
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(java.base@11-internal/BuiltinClassLoader.java:886)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(java.base@11-internal/BuiltinClassLoader.java:793)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11-internal/BuiltinClassLoader.java:751)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11-internal/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11-internal/ClassLoader.java:1032)
	at java.lang.Class.getDeclaredClassesImpl(java.base@11-internal/Native Method)
	at java.lang.Class.getClasses(java.base@11-internal/Class.java:538)
	at org.testng.internal.ClassInfoMap.registerClass(ClassInfoMap.java:43)
	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:29)
	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:21)
	at org.testng.TestRunner.initMethods(TestRunner.java:369)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

jsr292Test_1_FAILED

**Comment by llxia** [comment]
`JCL_Test_OutOfMemoryError_1` and `JCL_Test_1` also failed with the same error `Exception in thread "main" java.lang.ClassFormatError: JVMCFRE145 Nest host must be a constant class;`

**Comment by pshipton** [comment]
@tajila this is still failing in sanity tests
i.e. https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/22/tapResults/

**Comment by DanHeidinga** [comment]
FYI @fengxue-IS - This is be a case that already covers https://github.com/eclipse/openj9/issues/2876 as it appears to be running with ` -XX:RecreateClassfileOnload`.

Can you take a look?  There may be cases that #2775 didn't handle

**Comment by fengxue-IS** [comment]
@DanHeidinga thanks for pointing at this, I ll look into the test failure and update #2876

**Comment by fengxue-IS** [comment]
This error is due to class writer linking the nest host attribute to wrong CP entry, (Class name UTF8 instead of Constant_Class_info)
