### ISSUE TITLE
Kafka tests fail with java.lang.AssertionError 

### ISSUE THREAD

**Issue by suman-mitra** [eclipse/openj9#2796]
We see Kafka tests failing with java.lang.AssertionError when ran with latest OpenJDK-OpenJ9 80 builds.

Build used 
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_09_04_11_02-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

 "<testcase name="classMethod" classname="kafka.api.SaslMultiMechanismConsumerTest" time="0.0">"
    "<failure message="java.lang.AssertionError: Found unexpected threads during @BeforeClass, allThreads=Set(Test worker, kafka-admin-client-thread | adminclient-58, metrics-meter-tick-thread-2, main, Signal Dispatcher, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 2, Reference Handler, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 3, Finalizer, metrics-meter-tick-thread-1), unexpected=Set(kafka-admin-client-thread | adminclient-58)" type="java.lang.AssertionError">java.lang.AssertionError: Found unexpected threads during @BeforeClass, allThreads=Set(Test worker, kafka-admin-client-thread | adminclient-58, metrics-meter-tick-thread-2, main, Signal Dispatcher, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 2, Reference Handler, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 3, Finalizer, metrics-meter-tick-thread-1), unexpected=Set(kafka-admin-client-thread | adminclient-58)"
        "at org.junit.Assert.fail(Assert.java:88)"
        "at org.junit.Assert.assertTrue(Assert.java:41)"
        "at kafka.zk.ZooKeeperTestHarness$.verifyNoUnexpectedThreads(ZooKeeperTestHarness.scala:129)"
        "at kafka.zk.ZooKeeperTestHarness$.setUpClass(ZooKeeperTestHarness.scala:106)"
        "at kafka.zk.ZooKeeperTestHarness.setUpClass(ZooKeeperTestHarness.scala)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)"
        "at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)"
        "at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)"
        "at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)"
        "at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)"
        "at org.junit.runners.ParentRunner.run(ParentRunner.java:363)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)"
        "at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)"
        "at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)"
        "at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)"
        "at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)"
        "at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)"
        "at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)"
        "at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)"
        "at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)"
        "at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)"
        "at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)"

**Comment by suman-mitra** [comment]
Steps to reproduce 
1. set the PATH for java and Gradle
2. set JAVA_HOME
3. git clone https://github.com/apache/kafka.git
4. cd kafka
5. gradle
6. ./gradlew jar
7. ./gradlew testAll

**Comment by suman-mitra** [comment]
We are running with OpenJDK Hotspot and Oracle JDK to verify if the same failures are seen with them

**Comment by suman-mitra** [comment]
<testcase name="classMethod" classname="kafka.api.SaslMultiMechanismConsumerTest" time="0.0">
    <failure message="java.lang.AssertionError: Found unexpected threads during @BeforeClass, allThreads=Set(Test worker, kafka-admin-client-thread | adminclient-58, metrics-meter-tick-thread-2, main, Signal Dispatcher, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 2, Reference Handler, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 3, Finalizer, metrics-meter-tick-thread-1), unexpected=Set(kafka-admin-client-thread | adminclient-58)" type="java.lang.AssertionError">java.lang.AssertionError: Found unexpected threads during @BeforeClass, allThreads=Set(Test worker, kafka-admin-client-thread | adminclient-58, metrics-meter-tick-thread-2, main, Signal Dispatcher, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 2, Reference Handler, /127.0.0.1:35416 to /127.0.0.1:34985 workers Thread 3, Finalizer, metrics-meter-tick-thread-1), unexpected=Set(kafka-admin-client-thread | adminclient-58)
      
       "at org.junit.Assert.fail(Assert.java:88)"
        "at org.junit.Assert.assertTrue(Assert.java:41)"
        "at kafka.zk.ZooKeeperTestHarness$.verifyNoUnexpectedThreads(ZooKeeperTestHarness.scala:129)"
        "at kafka.zk.ZooKeeperTestHarness$.setUpClass(ZooKeeperTestHarness.scala:106)"
        "at kafka.zk.ZooKeeperTestHarness.setUpClass(ZooKeeperTestHarness.scala)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)"
        "at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)"
        "at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)"
        "at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)"
        "at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)"
        "at org.junit.runners.ParentRunner.run(ParentRunner.java:363)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)"
        "at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)"
        "at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)"
        "at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)"
        "at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)"
        "at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)"
        "at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)"
        "at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
        "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
        "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
        "at java.lang.reflect.Method.invoke(Method.java:498)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)"
        "at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)"
        "at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)"
        "at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)"
        "at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)"
        "at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)"

**Comment by suman-mitra** [comment]
We found a link which has a similar issue 
https://lists.apache.org/thread.html/ad7bc9e3b7571dde49a2f7fb0d0b65209f933e9a290b9e3c2b8710f5@%3Cdev.kafka.apache.org%3E

**Comment by JasonFengJ9** [comment]
Note: there is a similar Kafka AssertionError reported #2797 which failed with RI as well.
