### ISSUE TITLE
Kafka SaslAuthenticatorTest failing with OPEN J9

### ISSUE THREAD

**Issue by sshamaia** [eclipse/openj9#2797]
Steps to follow:
---------------
git clone https://github.com/apache/kafka.git
cd kafka/
gradle
./gradlew jar

Now Run the unittests as 
./gradlew unitTest

There are 3 test cases that fails
testMultipleServerMechanisms, testMechanismPluggability and testAuthenticateCallbackHandlerMechanisms

```org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest > testMultipleServerMechanisms FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.apache.kafka.common.network.NetworkTestUtils.waitForChannelReady(NetworkTestUtils.java:79)
        at org.apache.kafka.common.network.NetworkTestUtils.checkClientConnection(NetworkTestUtils.java:52)
        at org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.testMultipleServerMechanisms(SaslAuthenticatorTest.java:281)




org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest > testMechanismPluggability FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.apache.kafka.common.network.NetworkTestUtils.waitForChannelReady(NetworkTestUtils.java:79)
        at org.apache.kafka.common.network.NetworkTestUtils.checkClientConnection(NetworkTestUtils.java:52)
        at org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.createAndCheckClientConnection(SaslAuthenticatorTest.java:1475)
        at org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.testMechanismPluggability(SaslAuthenticatorTest.java:257)




org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest > testAuthenticateCallbackHandlerMechanisms FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.apache.kafka.common.network.NetworkTestUtils.waitForChannelReady(NetworkTestUtils.java:79)
        at org.apache.kafka.common.network.NetworkTestUtils.checkClientConnection(NetworkTestUtils.java:52)
        at org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.createAndCheckClientConnection(SaslAuthenticatorTest.java:1475)
        at org.apache.kafka.common.security.authenticator.SaslAuthenticatorTest.testAuthenticateCallbackHandlerMechanisms(SaslAuthenticatorTest.java:776)
```

Open J9 level used 
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build master-712c2ee2, JRE 1.8.0 Linux amd64-64 Compressed References 20180322_127 (JIT enabled, AOT enabled)
OpenJ9   - 712c2ee2
OMR      - b623c98f
JCL      - 7580d499 based on jdk8u162-b12)

I would need to run the same tests with open JDK and confirm the behaviour .
There is similar issue reported in apache 
https://lists.apache.org/thread.html/bda87d268b08eb0b37bbb7d2b45b77a25b669d8c1f43bd39816b0aff@%3Cdev.kafka.apache.org%3E

**Comment by sshamaia** [comment]
Same tests fails with openJDK build too
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_10_17_16_02-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

**Comment by JasonFengJ9** [comment]
@sshamaia could you re-run the test with more recent `OpenJDK` and `OpenJ9`? (The OpenJDK version specified is almost one year old, OpenJ9 is a version 6 month ago).

**Comment by mdshadabin** [comment]
I have downloaded kafka 3.0 source code then build binaries ,  when i run unit test i see same issue. 


My env:
Gradle  7.1.1
scala 2.13 
Java 1.8 ( even with 11)
[testreport.zip](https://github.com/eclipse-openj9/openj9/files/7807444/testreport.zip)



Failed tests

    SaslAuthenticatorTest. testAuthenticateCallbackHandlerMechanisms()
    SaslAuthenticatorTest. testCannotReauthenticateWithDifferentMechanism()
    SaslAuthenticatorTest. testMechanismPluggability()
    SaslAuthenticatorTest. testMultipleServerMechanisms()
    LoggingSignalHandlerTest. testRegister()
    UtilsTest. testFileAsStringNamedPipe()

**Comment by JasonFengJ9** [comment]
Not able to reproduce the failure.

@mdshadabin is there any stacktrace or a standalone testcase available?

**Comment by mdshadabin** [comment]
Hi @JasonFengJ9 

 I have downloaded kafka 3.0 source code (from https://kafka.apache.org/downloads ) and build binaries (following https://github.com/apache/kafka) and run unit test.

I always get 99% success and 1% failure. 

Below is link to access : build log, unit test log and unit test report.
https://drive.google.com/drive/folders/1lMUgETBNUS6ncEkfD5SU4E3JbqR8wHD4?usp=sharing

Note: please download the unit test folder, inside that index.html file have a test report. Click on any failing unit test it will show you call stack.
