### ISSUE TITLE
NestAttributeTest_0 failed with FileNotFoundException in JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2800]
Java Version:

```
8:17:25 openjdk version "11-internal" 2018-09-25
08:17:25 OpenJDK Runtime Environment (build 11-internal+0-adhoc.j9build.Build-JDK11-linuxx86-64cmprssptrs)
08:17:25 Eclipse OpenJ9 VM (build fix_2562_dev-b20f4811, JRE 11 Linux amd64-64-Bit Compressed References 20180906_87 (JIT enabled, AOT enabled)
08:17:25 OpenJ9   - b20f4811
08:17:25 OMR      - ac8c19b2
08:17:25 JCL      - 79da47c4f2f based on jdk-11+28)
```

Output:
```
===============================================
Running test NestAttributeTest_0 ...
===============================================
NestAttributeTest_0 Start Time: Fri Sep  7 09:01:19 2018 Epoch Time (ms): 1536325279094
test with NoOptions
java.io.FileNotFoundException: /home/j9build/workspace/TestBuild_Sandbox/jvmtest/functional/Valhalla/testng.xml (No such file or directory)
	at java.io.FileInputStream.open0(java.base@11-internal/Native Method)
	at java.io.FileInputStream.open(java.base@11-internal/FileInputStream.java:219)
	at java.io.FileInputStream.<init>(java.base@11-internal/FileInputStream.java:157)
	at org.testng.xml.Parser.parse(Parser.java:148)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
[TestNG] [ERROR] No test suite found. Nothing to run
```

**Comment by llxia** [comment]
Above change will not disable Valhalla tests. In fact, it will include Valhalla tests as part of regular tests for JDK11, so we do not have test material cannot be found error when running functional tests.

In addition, I also proposed to remove the check for `JAVA_VERSION=Valhalla`. This was initially created to run Valhalla as a separate build. This is unnecessary imo, as Valhalla tests are part of regular tests.

**Comment by smlambert** [comment]
Thanks Lan, I think that will simplify and is a good approach forward.

**Comment by llxia** [comment]
Change delivered.
