### ISSUE TITLE
CloneWeakReferenceTest failed with CloneNotSupportedException on linux_x86-64_cmprssptrs in JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2801]
CloneWeakReferenceTest failed with CloneNotSupportedException on linux_x86-64_cmprssptrs in JDK11

Java Version:

```
8:17:25 openjdk version "11-internal" 2018-09-25
08:17:25 OpenJDK Runtime Environment (build 11-internal+0-adhoc.j9build.Build-JDK11-linuxx86-64cmprssptrs)
08:17:25 Eclipse OpenJ9 VM (build fix_2562_dev-b20f4811, JRE 11 Linux amd64-64-Bit Compressed References 20180906_87 (JIT enabled, AOT enabled)
08:17:25 OpenJ9   - b20f4811
08:17:25 OMR      - ac8c19b2
08:17:25 JCL      - 79da47c4f2f based on jdk-11+28)
```

Output:
```
+++ j9vm.test.clone.CloneWeakReferenceTest: +++
command: /home/j9build/workspace/TestBuild_Sandbox/openjdkbinary/j2sdk-image/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /home/j9build/workspace/TestBuild_Sandbox/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar:/home/j9build/workspace/TestBuild_Sandbox/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.clone.CloneWeakReferenceTest 

Exception in thread "main" java.lang.CloneNotSupportedException: Create a new Reference, since a Reference cannot be cloned.
	at java.lang.ref.Reference.clone(java.base@11-internal/Reference.java:221)
	at j9vm.test.clone.CloneWeakReferenceTest$SubWeakReference.clone(CloneWeakReferenceTest.java:85)
	at j9vm.test.clone.CloneWeakReferenceTest.main(CloneWeakReferenceTest.java:44)
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.clone.CloneWeakReferenceTest)
```

**Comment by pdbain-ibm** [comment]
From the Javadoc:
```
clone
protected Object clone() throws CloneNotSupportedException
Throws CloneNotSupportedException. A Reference cannot be meaningfully cloned. Construct a new Reference instead.
Overrides:
clone in class Object
Returns:
a clone of this instance.
Throws:
CloneNotSupportedException - always
Since:
11
```

**Comment by pdbain-ibm** [comment]
@llxia 
This test is not mentioned in any playlists.  How is it being run?
If and when it is added to a playlist it should be run only on Java 10 and earlier.

@DanHeidinga @dmitripivkine
Is this test still valuable?  If not, I propose to delete it.

**Comment by llxia** [comment]
[CloneWeakReferenceTest ](https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/test/functional/VM_Test/src/j9vm/test/clone/CloneWeakReferenceTest.java) is part of `J9vmTest` test.

**Comment by pdbain-ibm** [comment]
@DanHeidinga @dmitripivkine @llxia what's the plan for this test?

**Comment by DanHeidinga** [comment]
> If and when it is added to a playlist it should be run only on Java 10 and earlier.

The test should be updated to run on Java 10 and earlier as you suggested above.  We should also ensure that we have a test for the behaviour change in 11+.

Can you take a look at making this happen?

**Comment by pdbain-ibm** [comment]
Will do.

**Comment by pdbain-ibm** [comment]
I have made no progress on this and am focussed on issue #2871.  I would be obliged if someone on Shelley's team (who know the tools better) would resolve this.

**Comment by pshipton** [comment]
@llxia please help to resolve this.
