### ISSUE TITLE
test_bindTo_interfaceMethodImplementation_* tests failed in JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2811]
test_bindTo_interfaceMethodImplementation_* tests failed in JDK11.

Java Version:
```
00:08:10.103 "C:/Users/jenkins/workspace/TestBuild_Sandbox/openjdkbinary/j2sdk-image/bin\\java" -version
00:08:10.103 openjdk version "11-internal" 2018-09-25
00:08:10.103 OpenJDK Runtime Environment (build 11-internal+0-adhoc.j9build.Build-JDK11-winx86-64cmprssptrs)
00:08:10.103 Eclipse OpenJ9 VM (build nativetest-025d2d99, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20180908_21 (JIT enabled, AOT enabled)
00:08:10.103 OpenJ9   - 025d2d99
00:08:10.103 OMR      - 30a0046f
00:08:10.103 JCL      - 98f20388ae based on jdk-11+28)
```

```
01:26:08.670 FAILED: test_bindTo_interfaceMethodImplementation_package
01:26:08.672 java.lang.AbstractMethodError: A.f()V
01:26:08.675 	at java.lang.invoke.InterfaceHandle.invokeExact_thunkArchetype_V(java.base@11-internal/InterfaceHandle.java:93)
01:26:08.675 	at com.ibm.j9.jsr292.InterfaceHandleTest.test_bindTo_interfaceMethodImplementation_package(InterfaceHandleTest.java:99)
01:26:08.675 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
01:26:08.675 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
01:26:08.675 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
01:26:08.675 	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
01:26:08.675 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:26:08.675 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:26:08.676 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:26:08.676 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:26:08.676 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:26:08.676 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:26:08.676 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:26:08.676 	at org.testng.TestRunner.run(TestRunner.java:505)
01:26:08.676 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:26:08.676 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:26:08.676 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:26:08.676 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:26:08.676 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:26:08.676 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:26:08.676 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:26:08.676 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:26:08.676 	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:26:08.676 	at org.testng.TestNG.run(TestNG.java:1017)
01:26:08.676 	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:26:08.676 	at org.testng.TestNG.main(TestNG.java:1323)
01:26:08.676 
01:26:08.676 FAILED: test_bindTo_interfaceMethodImplementation_private
01:26:08.676 java.lang.AbstractMethodError: A.f()V
01:26:08.676 	at java.lang.invoke.InterfaceHandle.invokeExact_thunkArchetype_V(java.base@11-internal/InterfaceHandle.java:93)
01:26:08.676 	at com.ibm.j9.jsr292.InterfaceHandleTest.test_bindTo_interfaceMethodImplementation_private(InterfaceHandleTest.java:115)
01:26:08.676 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
01:26:08.676 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
01:26:08.676 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
01:26:08.676 	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
01:26:08.676 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:26:08.676 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:26:08.676 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:26:08.676 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:26:08.676 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:26:08.676 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:26:08.676 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:26:08.676 	at org.testng.TestRunner.run(TestRunner.java:505)
01:26:08.676 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:26:08.676 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:26:08.676 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:26:08.676 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:26:08.677 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:26:08.678 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:26:08.678 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:26:08.678 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:26:08.678 	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:26:08.678 	at org.testng.TestNG.run(TestNG.java:1017)
01:26:08.678 	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:26:08.678 	at org.testng.TestNG.main(TestNG.java:1323)
01:26:08.678 
01:26:08.678 FAILED: test_bindTo_interfaceMethodImplementation_protected
01:26:08.678 java.lang.AbstractMethodError: A.f()V
01:26:08.678 	at java.lang.invoke.InterfaceHandle.invokeExact_thunkArchetype_V(java.base@11-internal/InterfaceHandle.java:93)
01:26:08.678 	at com.ibm.j9.jsr292.InterfaceHandleTest.test_bindTo_interfaceMethodImplementation_protected(InterfaceHandleTest.java:83)
01:26:08.678 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
01:26:08.678 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
01:26:08.678 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
01:26:08.678 	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
01:26:08.678 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:26:08.678 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:26:08.678 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:26:08.678 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:26:08.678 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:26:08.678 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:26:08.678 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:26:08.678 	at org.testng.TestRunner.run(TestRunner.java:505)
01:26:08.678 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:26:08.678 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:26:08.679 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:26:08.679 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:26:08.679 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:26:08.679 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:26:08.679 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:26:08.679 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:26:08.679 	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:26:08.679 	at org.testng.TestNG.run(TestNG.java:1017)
01:26:08.679 	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:26:08.679 	at org.testng.TestNG.main(TestNG.java:1323)
01:26:08.679 
01:26:08.679 
01:26:08.679 ===============================================
01:26:08.679     jsr292Test_optional
01:26:08.679     Tests run: 12, Failures: 3, Skips: 0
01:26:08.679 ===============================================
01:26:08.679 
01:26:08.679 
01:26:08.679 ===============================================
01:26:08.679 jsr292_Suite_SE90
01:26:08.679 Total tests run: 475, Failures: 3, Skips: 0
01:26:08.679 ===============================================
01:26:08.679 
01:26:08.679 
01:26:08.679 jsr292Test_SE110_0_FAILED
```

Link to the build: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/495/

**Comment by DanHeidinga** [comment]
@gacholio Can you take a look a this as you've update a lot of the methodhandle code for nestmates / private invocation?

**Comment by gacholio** [comment]
Looks like a test issue - it's testing the JDK8 behaviour.

Likely broken by: #2770

**Comment by gacholio** [comment]
@llxia - do these tests pass on an OpenJDK build (JDK9+)? I personally only tested the new behaviour of private, not of default or protected.

**Comment by llxia** [comment]
yes, the these tests passed in jdk10: https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK10-linux_x86-64_cmprssptrs/63/consoleFull

```
05:07:13 PASSED: test_bindTo_interfaceMethodImplementation_package
05:07:13 PASSED: test_bindTo_interfaceMethodImplementation_private
05:07:13 PASSED: test_bindTo_interfaceMethodImplementation_protected
05:07:13 PASSED: test_bindTo_interfaceMethodImplementation_public
05:07:13 PASSED: testIfDirectHandleTestIsJitted
...
 ```

**Comment by gacholio** [comment]
I think you misunderstood - I'm asking about Oracle behaviour for the protected/default cases. Can this test run against OpenJDK?

**Comment by llxia** [comment]
ah, sorry. 
yes, these tests passed in OpenJDK10:

```
16:21:19 PASSED: test_bindTo_interfaceMethodImplementation_package
16:21:19 PASSED: test_bindTo_interfaceMethodImplementation_private
16:21:19 PASSED: test_bindTo_interfaceMethodImplementation_protected
16:21:19 PASSED: test_bindTo_interfaceMethodImplementation_public
```

Java Version:
```
16:21:05 "/home/j9build/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
16:21:05 openjdk version "10.0.2-adoptopenjdk" 2018-07-17
16:21:05 OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
16:21:05 OpenJDK 64-Bit Server VM (build 10.0.2-adoptopenjdk+13, mixed mode)
```

Do we expect all jsr292 tests passed in OpenJDK10? I noticed some other test failure.

**Comment by gacholio** [comment]
In JDK11, the test should be expecting AbstractMethodError for private implementation.

#2770 was a bit too aggressive - it threw AbstractMethodError for all illegal implementations, where it should only be doing so for private implementations.
