### ISSUE TITLE
JCL_Test failed with UncaughtException in JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2819]
Java Version:
```
14:57:14 openjdk version "11-internal" 2018-09-25
14:57:14 OpenJDK Runtime Environment (build 11-internal+0-adhoc.jenkins.LanPipeline-Build-Test-JDK8-linux390-64cmprssptrs)
14:57:14 Eclipse OpenJ9 VM (build nativetest-7b3fa7b, JRE 11 Linux ppc64le-64-Bit Compressed References 20180910_50 (JIT enabled, AOT enabled)
14:57:14 OpenJ9   - 7b3fa7b
14:57:14 OMR      - f29d158
14:57:14 JCL      - 98f2038 based on jdk-11+28)

```

Output:
```
org.openj9.test.java.lang.
Exception in thread "no-op thread" org.openj9.test.java.lang.Test_ThreadGroup$1UncaughtException
	at org.openj9.test.java.lang.Test_ThreadGroup$14.uncaughtException(Test_ThreadGroup.java:1204) from jdk.internal.loader.ClassLoaders$AppClassLoader@b8f8e91a(file:/home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.lang.Thread.uncaughtException(java.base@11-internal/Thread.java:1335) from jrt:/java.base
org.openj9.test.java.lang.Test_Throwable$TestException: test
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00003FFFB57DDAA0 Handler2=00003FFFB557B340
R0=00003FFF95E50C04 R1=00003FFFB61BD4F0 R2=00003FFFB5041E00 R3=00000000FFF17D78
R4=0000000000000000 R5=000000000000000C R6=0000000000000006 R7=0000000000000030
R8=0000000000000000 R9=00000000FFF3A720 R10=0000000000000000 R11=00003FFF95E50F04
R12=00000000004DA400 R13=00003FFFB61C6900 R14=00000000000F2020 R15=0000000000014F00
R16=00003FFF94140038 R17=00000000FFEE0010 R18=00000000807B7A38 R19=00000000FFEE0020
R20=0000000000000002 R21=0000000000000000 R22=0000000000000002 R23=0000000000000000
R24=00000000FFEE0000 R25=000000000008C475 R26=000000008078B730 R27=00000000FFB5CFE8
R28=0000000080E18478 R29=00000000FFF15670 R30=000000000010FFFE R31=00000000004DA400
NIP=0000000000000000 MSR=800000004280F033 ORIG_GPR3=00003FFFB47DED4C CTR=0000000000000000
LINK=00003FFF95E50C04 XER=0000000000000000 CCR=0000000048002224 SOFTE=0000000000000001
TRAP=0000000000000400 DAR=0000000000000000 dsisr=0000000040000000 RESULT=0000000000000000
FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR1 000000000000004e (f: 78.000000, d: 3.853712e-322)
FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
FPR3 bc45000000000000 (f: 0.000000, d: -2.276825e-18)
FPR4 402d1cb7eea86980 (f: 4004014592.000000, d: 1.455609e+01)
FPR5 3feb63be20000000 (f: 536870912.000000, d: 8.559256e-01)
FPR6 6574496b61657242 (f: 1634038400.000000, d: 5.261273e+180)
FPR7 61726574496b6165 (f: 1231774080.000000, d: 2.586356e+161)
FPR8 3878400c20000000 (f: 536870912.000000, d: 1.140238e-36)
FPR9 003103c200690020 (f: 6881312.000000, d: 9.464729e-308)
FPR10 380a800800000000 (f: 0.000000, d: 9.734607e-39)
FPR11 3ed7130a01c2b041 (f: 29536320.000000, d: 5.501359e-06)
FPR12 412fcae600000000 (f: 0.000000, d: 1.041779e+06)
FPR13 402ccd10d3497479 (f: 3544806400.000000, d: 1.440052e+01)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20180910_50 (Linux 4.4.0-134-generic)
CPU=ppc64le (4 logical CPUs) (0x1fe3a0000 RAM)
----------- Stack Backtrace -----------
(0x0000000000000000 [<unknown>+0x0])
(0x00003FFFB4E41724 [libj9jit29.so+0x8e1724])
(0x00003FFFB57C82AC [libj9vm29.so+0x882ac])
(0x00003FFFB57C9018 [libj9vm29.so+0x89018])
(0x00003FFFAFD8C0BC [libjclse11_29.so+0x6c0bc])
JVM_InvokeMethod+0x40 (0x00003FFFB5967290 [libjvm.so+0x27290])
JVM_InvokeMethod+0x34 (0x00003FFFB61C6854 [libjvm.so+0x6854])
Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00003FFF9406D384 [libjava.so+0xd384])
(0x00003FFF95B36224 [<unknown>+0x0])
(0x00003FFFB57C7C68 [libj9vm29.so+0x87c68])
(0x00003FFFB57E2200 [libj9vm29.so+0xa2200])
(0x00003FFFB58368E8 [libj9vm29.so+0xf68e8])
(0x00003FFFB557BD60 [libj9prt29.so+0x2bd60])
(0x00003FFFB58369BC [libj9vm29.so+0xf69bc])
(0x00003FFFB57E4BE0 [libj9vm29.so+0xa4be0])
(0x00003FFFB57E1810 [libj9vm29.so+0xa1810])
(0x00003FFFB6496664 [libjli.so+0x6664])
(0x00003FFFB6208070 [libpthread.so.0+0x8070])
clone+0x98 (0x00003FFFB63D3A70 [libc.so.6+0x123a70])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2018/09/10 19:47:20 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/core.20180910.194720.21220.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.21341.

JVMDUMP010I System dump written to /home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/core.20180910.194720.21220.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/javacore.20180910.194720.21220.0002.txt' in response to an event


*** Invalid JIT return address 0000000000000000 in 00003FFFB61B5D40

JVMDUMP010I Java dump written to /home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/javacore.20180910.194720.21220.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/Snap.20180910.194720.21220.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/Snap.20180910.194720.21220.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/jitdump.20180910.194720.21220.0004.dmp'
JVMDUMP010I JIT dump written to /home/jenkins/jenkins-agent/workspace/Lan_Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15366058329030/JCL_Test_0/jitdump.20180910.194720.21220.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".

JCL_Test_0_FAILED
```

**Comment by llxia** [comment]
JCL_Test_1 failed with `JVMCFRE145 Nest host must be a constant class`. The issue is tracked in https://github.com/eclipse/openj9/issues/2708

```
===============================================
Running test JCL_Test_1 ...
===============================================
JCL_Test_1 Start Time: Mon Sep 10 19:47:22 2018 Epoch Time (ms): 1536608842391
test with -XX:RecreateClassfileOnload
WARNING: package com.ibm.jit.crypto not in java.base
Exception in thread "main" java.lang.ClassFormatError: JVMCFRE145 Nest host must be a constant class; class=org/openj9/test/java/lang/management/ThreadMXBean/ThreadMXBeanTestCaseCommon$TimeoutNotifier, offset=357
	at java.lang.ClassLoader.defineClassImpl(java.base@11-internal/Native Method) from jrt:/java.base
```

**Comment by llxia** [comment]
There is no crash, but I still see `org.openj9.test.java.lang.Test_ThreadGroup$1UncaughtException`

```
===============================================
    JCL_TEST_Test-Annotation-Package
    Tests run: 2, Failures: 0, Skips: 0
===============================================

org.openj9.test.java.lang.
Exception in thread "no-op thread" org.openj9.test.java.lang.Test_ThreadGroup$1UncaughtException
	at org.openj9.test.java.lang.Test_ThreadGroup$14.uncaughtException(Test_ThreadGroup.java:1204) from jdk.internal.loader.ClassLoaders$AppClassLoader@1e49b3b9(file:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.lang.Thread.uncaughtException(java.base@11-internal/Thread.java:1335) from jrt:/java.base
org.openj9.test.java.lang.Test_Throwable$TestException: test
[Support_Exec] [INFO] ***11-internal+0-adhoc.jenkins.Build-JDK11-linuxppc-64cmprssptrsle
JRE 11 Linux ppc64le-64-Bit Compressed References 20180917_20 (JIT enabled, AOT enabled)
OpenJ9   - 298cfab
OMR      - beda1cb
JCL      - 2cff870 based on jdk-11+28***
org.openj9.test.java.lang.Test_System$TestSecurityManager
```

https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/18/tapResults/

**Comment by pshipton** [comment]
@JasonFengJ9 another failure for triage.

**Comment by pshipton** [comment]
Yes, seems printing a stack trace to the console is a side affect of causing an uncaughtException
