### ISSUE TITLE
Test-sanity.functional-JDK11-linux_390-64_cmprssptrs JCL_Test_0 test_toLowerCase_lithuanian

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2890]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/17
```
===============================================
Running test JCL_Test_0 ...
===============================================
JCL_Test_0 Start Time: Mon Sep 17 03:26:49 2018 Epoch Time (ms): 1537169209126
test with NoOptions
WARNING: package com.ibm.jit.crypto not in java.base
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE110.txt

...

FAILED: test_toLowerCase_lithuanian
java.lang.AssertionError: unexpected I conversion for: 8d4 : " 0x69 0x307 0x8d4"
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@aafff830(file:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@aafff830(file:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_String.test_toLowerCase_lithuanian(Test_String.java:1336) from jdk.internal.loader.ClassLoaders$AppClassLoader@aafff830(file:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method) from jrt:/java.base
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
...

===============================================
    JCL_TEST_Java-Lang
    Tests run: 358, Failures: 1, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
Appears to be a test issue related to #1875.

There are new combining characters in the Unicode 10 spec, since Unicode 8 (Java 9).
```
08D4;ARABIC SMALL HIGH WORD AR-RUB;Mn;230;NSM;;;;;N;;;;;
08D5;ARABIC SMALL HIGH SAD;Mn;230;NSM;;;;;N;;;;;
08D6;ARABIC SMALL HIGH AIN;Mn;230;NSM;;;;;N;;;;;
08D7;ARABIC SMALL HIGH QAF;Mn;230;NSM;;;;;N;;;;;
08D8;ARABIC SMALL HIGH NOON WITH KASRA;Mn;230;NSM;;;;;N;;;;;
08D9;ARABIC SMALL LOW NOON WITH KASRA;Mn;230;NSM;;;;;N;;;;;
08DA;ARABIC SMALL HIGH WORD ATH-THALATHA;Mn;230;NSM;;;;;N;;;;;
08DB;ARABIC SMALL HIGH WORD AS-SAJDA;Mn;230;NSM;;;;;N;;;;;
08DC;ARABIC SMALL HIGH WORD AN-NISF;Mn;230;NSM;;;;;N;;;;;
08DD;ARABIC SMALL HIGH WORD SAKTA;Mn;230;NSM;;;;;N;;;;;
08DE;ARABIC SMALL HIGH WORD QIF;Mn;230;NSM;;;;;N;;;;;
08DF;ARABIC SMALL HIGH WORD WAQFA;Mn;230;NSM;;;;;N;;;;;
08E0;ARABIC SMALL HIGH FOOTNOTE MARKER;Mn;230;NSM;;;;;N;;;;;
08E1;ARABIC SMALL HIGH SIGN SAFHA;Mn;230;NSM;;;;;N;;;;;
```
There may be more.

References
https://www.unicode.org/Public/8.0.0/ucd/UnicodeData.txt
https://www.unicode.org/Public/10.0.0/ucd/UnicodeData.txt

**Comment by pshipton** [comment]
@fjeremic

**Comment by fjeremic** [comment]
Taking a look at this now. This indeed does seem like a test issue, specifically related to the following code:

https://github.com/eclipse/openj9/blob/9c4322085b15f0227e188818cda4e289f46b2189/test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java#L1272-L1282

It looks like we need to update these strings for Java 11 with the proper mappings according to the Unicode 10 standard and the data found in [1].

[1] https://www.unicode.org/Public/10.0.0/ucd/extracted/DerivedCombiningClass.txt

**Comment by irinarada** [comment]
@fjeremic "we need to update" - will you be updating them?

**Comment by fjeremic** [comment]
> @fjeremic "we need to update" - will you be updating them?

Yes, working on this now.
