### ISSUE TITLE
Test-sanity.functional-JDK10-win_x86-64 Unable to delete JIT_Test

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2907]
Occurred in an OMR acceptance build
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/72

```
java.nio.file.FileSystemException: C:\Users\jenkins\workspace\Test-sanity.functional-JDK10-win_x86-64_cmprssptrs\openjdk-tests\functional\JIT_Test: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at hudson.Util.tryOnceDeleteFile(Util.java:316)
	at hudson.Util.deleteFile(Util.java:272)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to win2012r2-x86-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1036)
		at hudson.FilePath.act(FilePath.java:1025)
		at hudson.FilePath.deleteContents(FilePath.java:1245)
		at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1183)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Unable to delete 'C:\Users\jenkins\workspace\Test-sanity.functional-JDK10-win_x86-64_cmprssptrs\openjdk-tests\functional\JIT_Test'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteFile(Util.java:277)
	at hudson.FilePath.deleteRecursive(FilePath.java:1265)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1274)
	at hudson.FilePath.deleteRecursive(FilePath.java:1256)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1274)
	at hudson.FilePath.access$1300(FilePath.java:210)
	at hudson.FilePath$12.invoke(FilePath.java:1248)
	at hudson.FilePath$12.invoke(FilePath.java:1245)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2917)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:813)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@AdamBrousseau @llxia

**Comment by llxia** [comment]
I encountered the similar issue on windows where if a build is cancelled, it seems the process on the machine is still running. Hence, the next build cannot delete workspace.

**Comment by llxia** [comment]
Found this: https://issues.jenkins-ci.org/browse/JENKINS-48485

**Comment by pshipton** [comment]
Obsolete, closing.
