### ISSUE TITLE
IllegalAccessError setting final fields in <clinit> on JDK 11

### ISSUE THREAD

**Issue by aguibert** [eclipse/openj9#2911]
In the OpenLiberty project we use trace points injected at runtime (using the newest version of ASM).  This works fine with OpenJDK 11, but fails when using OpenJ9:

```
Stack Dump = java.lang.IllegalAccessError: Attempt to set static final field com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43DataSource.tc from method "<clinit>" that is not <clinit>
    at com.ibm.ws.rsadapter.jdbc.v43.WSJdbc43DataSource.<clinit>(WSJdbc43DataSource.java:30)
    at com.ibm.ws.jdbc.osgi.v43.JDBC43Runtime.newDataSource(JDBC43Runtime.java:71)
    at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.createConnectionFactory(WSManagedConnectionFactoryImpl.java:359)
    at com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.createConnectionFactory(WSManagedConnectionFactoryImpl.java:99)
    at com.ibm.ws.jca.cm.AbstractConnectionFactoryService.createResource(AbstractConnectionFactoryService.java:158)
    at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.createResourceWithFilterPrivileged(IndirectJndiLookupObjectFactory.java:383)
    at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.access$100(IndirectJndiLookupObjectFactory.java:57)
    at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory$3.run(IndirectJndiLookupObjectFactory.java:365)
    at java.security.AccessController.doPrivileged(java.base@11-adoptopenjdk/AccessController.java:696)
    at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.createResourceWithFilter(IndirectJndiLookupObjectFactory.java:362)
   ... more stack
```

**Comment by DanHeidinga** [comment]
@gacholio Can you take a look at this?

**Comment by aguibert** [comment]
The easiest way to reproduce this issue is to [build OpenLiberty](https://github.com/OpenLiberty/open-liberty/tree/master#contribute-to-open-liberty) and then run the com.ibm.ws.logging_fat test project with ./gradlew :com.ibm.ws.logging_fat:buildandrun

**Comment by gacholio** [comment]
So far unable to reproduce locally - hopefully we'll get some cores later today.

**Comment by aguibert** [comment]
Sent @gacholio a core earlier today (not uploading it here because it's >750MB).

I did determine that the class in question had an unused field which our trace injection was colliding with:

```java
public class WSJdbc43DataSource extends WSJdbcDataSource implements DataSource {
    
    // tc is an unused field, and trace instrumentation also tries to set it
    private static final TraceComponent tc = Tr.register(WSJdbc43DataSource.class, AdapterUtil.TRACE_GROUP, AdapterUtil.NLS_FILE);
```

For now, I'm going to try and work around this issue by removing the unused trace field, but I've sent Graham all of the info needed for him to reproduce the problem locally.

**Comment by gacholio** [comment]
This appears to be a problem with class redefinition (we're identity comparing classes which may no longer be identical if they get replaced).

**Comment by gacholio** [comment]
Looks like the class has been redefined before we get to the field resolve, so it either happened in the clinit, or before (in which case, why are we running the obsolete clinit?). There's a lot of HCR pitfalls in this code, so I'm not going to have a detailed look rather than banging out a quick fix.

**Comment by gacholio** [comment]
Class does not appear to be obsolete when clinit is invoked.

**Comment by gacholio** [comment]
I'll further instrument the VM to determine exactly when this class is replaced.

**Comment by gacholio** [comment]
The class (WSJdbc43DataSource) is being redefined during the Tr.register call (called from the clinit).

**Comment by gacholio** [comment]
The simple fix is the correct one for this case (use most current class when doing the final field check).

**Comment by aguibert** [comment]
Thanks for taking care of this @gacholio!
