### ISSUE TITLE
java.lang.NoClassDefFoundError: com.sun.xml.internal.txw2.IllegalAnnotationException on JDK 11

### ISSUE THREAD

**Issue by aguibert** [eclipse/openj9#2912]
In OpenLiberty we have an injection processing component which calls `Class.getDeclaredFields` to scan for annotations at runtime.  This works fine with HotSpot JDK 11 but fails on OpenJ9 JDK 11 with the following error:

```
java.lang.NoClassDefFoundError: com.sun.xml.internal.txw2.IllegalAnnotationException
	at java.lang.J9VMInternals.prepareClassImpl(java.base@11-adoptopenjdk/Native Method)
	at java.lang.J9VMInternals.prepare(java.base@11-adoptopenjdk/J9VMInternals.java:347)
	at java.lang.Class.getDeclaredFields(java.base@11-adoptopenjdk/Class.java:942)
	at com.ibm.ws.injectionengine.InjectionProcessorManager.getAllDeclaredFields(InjectionProcessorManager.java:374)
	at com.ibm.ws.injectionengine.InjectionProcessorManager.processAnnotations(InjectionProcessorManager.java:215)
	at com.ibm.ws.injectionengine.AbstractInjectionEngine.processInjectionMetaData(AbstractInjectionEngine.java:513)
	at com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl.processInjectionMetaData(OSGiInjectionEngineImpl.java:238)
	at com.ibm.ws.injectionengine.ReferenceContextImpl.processImpl(ReferenceContextImpl.java:594)
	at com.ibm.ws.injectionengine.ReferenceContextImpl.process(ReferenceContextImpl.java:289)
	at com.ibm.ws.injectionengine.osgi.internal.OSGiReferenceContextImpl.process(OSGiReferenceContextImpl.java:30)
	at com.ibm.ws.webcontainer.osgi.webapp.WebApp.commonInitializationStart(WebApp.java:253)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:978)
	at com.ibm.ws.webcontainer.webapp.WebApp.initialize(WebApp.java:6566)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApp(DynamicVirtualHost.java:467)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost.startWebApplication(DynamicVirtualHost.java:462)
	at com.ibm.ws.webcontainer.osgi.WebContainer.startWebApplication(WebContainer.java:1132)
	at com.ibm.ws.webcontainer.osgi.WebContainer.access$000(WebContainer.java:108)
	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:944)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11-adoptopenjdk/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11-adoptopenjdk/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11-adoptopenjdk/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11-adoptopenjdk/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11-adoptopenjdk/Thread.java:825)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.txw2.IllegalAnnotationException
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:504)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:276)
	at java.lang.ClassLoader.loadClassHelper(java.base@11-adoptopenjdk/ClassLoader.java:1134)
	at java.lang.ClassLoader.loadClass(java.base@11-adoptopenjdk/ClassLoader.java:1049)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:482)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:443)
	at java.lang.ClassLoader.loadClass(java.base@11-adoptopenjdk/ClassLoader.java:1032)
	... 23 more
```

**Comment by DanHeidinga** [comment]
@JasonFengJ9 FYI

**Comment by pshipton** [comment]
I expect this class is removed as part of http://openjdk.java.net/jeps/320. It exists in openjdk 8, 9, 10 but not 11 or the head stream.
@aguibert

**Comment by pshipton** [comment]
What hotspot build did you try?

**Comment by JasonFengJ9** [comment]
The issue description states "HotSpot JDK 11".

**Comment by aguibert** [comment]
hi @pshipton, yes I am painfully aware of JEP 320 =)

I am using the OpenJDK 11 release candidate build:
```
$ java --version
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by JasonFengJ9** [comment]
@aguibert any chance we can reproduce the failure?

**Comment by pshipton** [comment]
I have a build created from openjdk and it doesn't contain the class.
What does "bin/javap com.sun.xml.internal.txw2.IllegalAnnotationException" produce on your hotspot build?

**Comment by pshipton** [comment]
Could the problem be Liberty failing to detect the OpenJ9 build is Java 11?

**Comment by aguibert** [comment]
@JasonFengJ9 I am currently working on a way to reproduce this issue with a publicly available test.  I will post back when I have something.

@pshipton running the javap command results in a class not found error (which makes sense because this class isn't in my Hotspot build).  We do include the non-internal version of this class in OpenLiberty: `com.sun.xml.bind.v2.runtime.IllegalAnnotationException`.  This class comes from an OSGi bundle that the OpenLiberty runtime provides.  The OpenLiberty runtime conditionally provides the JEP 230 removed APIs if it detects Java 9+, including JAX-B API and impl.  

It's worth noting that the overall OpenLiberty test results w/ OpenJ9 JDK 11 is really good.
Overall we have 1590 tests failing out of 63.2k total, not too bad, compared to 455 tests failing with Hotspot. If OpenLiberty was failing to recognize the OpenJ9 build as Java 11, things would be all over the floor.

**Comment by pshipton** [comment]
Does -Xverify:none fix the problem?
