### ISSUE TITLE
Stack trace elements from JDK classes should include module name on JDK 9+

### ISSUE THREAD

**Issue by aguibert** [eclipse/openj9#2922]
We have a test in OpenLiberty that verifies stack traces in logs.  On Java 9+, stack trace elements should include what module they are from (if they are from a named module).  This works with Hotspot JDK 11 but not OpenJ9 JDK 11.

Example stack trace:
```
com.ibm.ws.logging.fat.broken.servlet.ExceptionPrintingServlet$SpecialPrintingException
	at com.ibm.ws.logging.fat.broken.servlet.ExceptionPrintingServlet$ExceptionGeneratingObject.hashCode(ExceptionPrintingServlet.java:72)
	at java.util.HashMap.hash(java.base@11-adoptopenjdk/HashMap.java:339)
	at java.util.HashMap.put(java.base@11-adoptopenjdk/HashMap.java:607)
	at java.util.HashSet.add(java.base@11-adoptopenjdk/HashSet.java:220)
	at com.ibm.ws.logging.fat.broken.servlet.ExceptionPrintingServlet.doGet(ExceptionPrintingServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4954)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:996)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1011)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:414)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:373)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:302)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11-adoptopenjdk/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11-adoptopenjdk/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11-adoptopenjdk/Thread.java:825)
```

Stack trace elements should look like this:
`	at java.base/java.util.HashMap.hash(java.base@11-adoptopenjdk/HashMap.java:339)`

The easiest way to reproduce this issue is to [build OpenLiberty](https://github.com/OpenLiberty/open-liberty/tree/master#contribute-to-open-liberty) and then run the com.ibm.ws.logging_fat test project with ./gradlew :com.ibm.ws.logging_fat:buildandrun

**Comment by pshipton** [comment]
@JasonFengJ9

**Comment by aguibert** [comment]
to add some additional info, it's not necessary to set up OpenLiberty just to reproduce the issue.  A simple JavaSE test case that dumps a stack trace should suffice.

According to the javadoc for `StackTraceElement.toString()` it seems that Hotspot has the correct interpretation:
https://docs.oracle.com/javase/10/docs/api/java/lang/StackTraceElement.html#toString()

**Comment by JasonFengJ9** [comment]
@aguibert does `OpenJ9` cause any specific test failure while `RI` makes them pass?

**Comment by JasonFengJ9** [comment]
Current direction is to match `RI JDK11 11-ea+24` output format.

**Comment by pshipton** [comment]
Note the current format is used by OpenJDK since Java 9 GA.

**Comment by aguibert** [comment]
Thanks for taking care of this @JasonFengJ9! The revised stack trace output looks much better
