### ISSUE TITLE
JDK11: TLS 1.3 test failure running jtreg_tests TESTDIRS=jdk/sun/security

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#2927]
make jtreg_tests TESTDIRS=jdk/sun/security failure caused by:
java: ../j9vm/java11vmi.c:1458: JVM_GetVmArguments: Assertion `!"JVM_GetVmArguments unimplemented"' failed.

https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_and_JTReg/24/console

**Comment by pshipton** [comment]
As called by jdk_internal_misc_VM_getRuntimeArguments() I'm guessing.
@andrew-m-leonard is the resulting javacore file available?

**Comment by pdbain-ibm** [comment]
I will investigate.

**Comment by andrew-m-leonard** [comment]
javacore sent to Peter

**Comment by pshipton** [comment]
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/misc/VM.getRuntimeArguments(Native Method)
4XESTACKTRACE                at Proc.start(Proc.java:267)
4XESTACKTRACE                at CompatImpact.main(CompatImpact.java:91)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
4XESTACKTRACE                at jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:566(Compiled Code))
4XESTACKTRACE                at com/sun/javatest/regtest/agent/MainActionHelper$SameVMRunnable.run(MainActionHelper.java:229)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:825)
```

**Comment by pshipton** [comment]
@theresa-m is implementing the missing native I believe.

**Comment by theresa-m** [comment]
I'm testing out my changes now. working on getting this out asap
