### ISSUE TITLE
Test-sanity.functional-JDK11-linux_x86-64 jsr335_interfacePrivateMethod_mode100_0 Should have thrown an IncompatibleClassChangeError

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2957]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/21/tapResults/

```
===============================================
Running test jsr335_interfacePrivateMethod_mode100_0 ...
===============================================
jsr335_interfacePrivateMethod_mode100_0 Start Time: Thu Sep 20 07:17:14 2018 Epoch Time (ms): 1537427834388
test with Mode100
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt

...

FAILED: testRunTest_private_non_static_method_with_InvokeVirtual
java.lang.AssertionError: Should have thrown an IncompatibleClassChangeError
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.jsr335.interfacePrivateMethod.Test_ITestRunner.testRunTest_private_non_static_method_with_InvokeVirtual(Test_ITestRunner.java:112)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    jsr335InterfacePrivateMethod
    Tests run: 66, Failures: 1, Skips: 0
===============================================


===============================================
GeneralTest suite
Total tests run: 66, Failures: 1, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
@fengxue-IS

**Comment by fengxue-IS** [comment]
looking into this
