### ISSUE TITLE
TAP results are truncated after test failure

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2960]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/18

The console shows the complete run, but the TAP results are truncated at the test failure

```
28 | - CondyPrimitive_1 |  
-- | -- | --
output
===============================================
Running test CondyPrimitive_1 ...
===============================================
CondyPrimitive_1 Start Time: Thu Sep 20 02:51:58 2018 Epoch Time (ms): 1537429918570
test with '-Xjit:count=1,disableA


Parse errors

No parse errors found
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
This is a known issue. When test output some special characters, TAP plugin cannot handle it. We checked TAP file that we generated, it looks fine.

@renfeiw

**Comment by llxia** [comment]
Please see attached TAP file
[TestTargetResult.txt](https://github.com/eclipse/openj9/files/2402334/TestTargetResult.txt)

**Comment by renfeiw** [comment]
We tried to reproduce this error by using the TAP plugin to parse this TAP file, but the result looks fine.  Not sure what caused the result to be truncated.

**Comment by llxia** [comment]
Similar case:
- TAP results are truncated at the test failure:
```
108	- TestAttachErrorHandling_0	
output	
===============================================
Running test TestAttachErrorHandling_0

Parse errors
No parse errors found
```
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/17/tapResults/

- console output shows a complete run
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/17/consoleFull

- failere test output from TestTargetResult.tap file:
```
04:40:41.711 not ok 108 - TestAttachErrorHandling_0
04:40:41.711   ---
04:40:41.711     output:
04:40:41.711       |
04:40:41.711         ===============================================
04:40:41.711         Running test TestAttachErrorHandling_0 ...
04:40:41.711         ===============================================
04:40:41.711         TestAttachErrorHandling_0 Start Time: Thu Dec 13 16:23:24 2018 Epoch Time (ms): 1544739804040
04:40:41.711         variation: NoOptions
04:40:41.711         JVM_OPTIONS: -Xcompressedrefs 
04:40:41.711         [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/u0020236/workspace/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
04:40:41.711         ...
04:40:41.711         ... TestNG 6.14.2 by C�dric Beust (cedric@beust.com)
04:40:41.711         ...
04:40:41.711         
04:40:41.711         [AttachApiTest] [ERROR] com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 19923104 on port 37017
04:40:41.711         	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:431)
04:40:41.711         	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:121)
04:40:41.711         	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9AttachProvider.attachVirtualMachine(OpenJ9AttachProvider.java:60)
04:40:41.711         	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
04:40:41.711         	at org.openj9.test.attachAPI.TestAttachErrorHandling.testVmShutdownWhileAttached(TestAttachErrorHandling.java:352)
04:40:41.711         	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:40:41.711         	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:40:41.711         	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:40:41.711         	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
04:40:41.711         	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
04:40:41.711         	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
04:40:41.711         	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
04:40:41.711         	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
04:40:41.711         	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
04:40:41.711         	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
04:40:41.711         	at org.testng.TestRunner.privateRun(TestRunner.java:648)
04:40:41.711         	at org.testng.TestRunner.run(TestRunner.java:505)
04:40:41.711         	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
04:40:41.711         	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
04:40:41.711         	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
04:40:41.711         	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
04:40:41.711         	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
04:40:41.711         	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
04:40:41.711         	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
04:40:41.711         	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
04:40:41.711         	at org.testng.TestNG.runSuites(TestNG.java:1049)
04:40:41.711         	at org.testng.TestNG.run(TestNG.java:1017)
04:40:41.711         	at org.testng.TestNG.privateMain(TestNG.java:1354)
04:40:41.711         	at org.testng.TestNG.main(TestNG.java:1323)
04:40:41.711         Caused by: java.net.SocketTimeoutException: Accept timed out
04:40:41.711         	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
04:40:41.711         	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:551)
04:40:41.711         	at java.base/java.net.ServerSocket.accept(ServerSocket.java:519)
04:40:41.711         	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:426)
04:40:41.711         	... 28 more
04:40:41.711         
04:40:41.711         PASSED: testAttachWithCorruptAdvertisementFile
04:40:41.711         PASSED: testInitializationDeletesManyStaleDirectories
04:40:41.711         PASSED: testInitializationDeletesStaleDirectoryWithNumericId
04:40:41.711         PASSED: testInitializationDeletesStaleDirectoryWithPseudoNumericId
04:40:41.711         PASSED: testInitializationDeletesStaleDirectoryWithTextId
04:40:41.711         PASSED: testListVirtualMachinesWithCorruptAdvertisementFile
04:40:41.711         PASSED: testListVmsDeletesStaleDirectoriesWithNumericId
04:40:41.711         PASSED: testListVmsDeletesStaleDirectoryWithPseudoNumericId
04:40:41.711         PASSED: testListVmsDeletesStaleDirectoryWithTextId
04:40:41.711         PASSED: testMemoryExhaustion
04:40:41.711         PASSED: testPrematureSocketClose
04:40:41.711         PASSED: testTracepoint
04:40:41.711         PASSED: test_startupShutdownRobustness
04:40:41.711         FAILED: testVmShutdownWhileAttached
04:40:41.711         java.lang.AssertionError: com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 19923104 on port 37017
04:40:41.711         	at org.testng.Assert.fail(Assert.java:96)
04:40:41.711         	at org.openj9.test.attachAPI.AttachApiTest.logExceptionInfoAndFail(AttachApiTest.java:46)
04:40:41.711         	at org.openj9.test.attachAPI.TestAttachErrorHandling.testVmShutdownWhileAttached(TestAttachErrorHandling.java:355)
04:40:41.711         	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:40:41.711         	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:40:41.711         	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:40:41.711         	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
04:40:41.711         	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
04:40:41.711         	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
04:40:41.711         	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
04:40:41.711         	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
04:40:41.711         	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
04:40:41.711         	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
04:40:41.711         	at org.testng.TestRunner.privateRun(TestRunner.java:648)
04:40:41.711         	at org.testng.TestRunner.run(TestRunner.java:505)
04:40:41.711         	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
04:40:41.711         	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
04:40:41.711         	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
04:40:41.711         	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
04:40:41.711         	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
04:40:41.711         	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
04:40:41.711         	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
04:40:41.711         	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
04:40:41.711         	at org.testng.TestNG.runSuites(TestNG.java:1049)
04:40:41.711         	at org.testng.TestNG.run(TestNG.java:1017)
04:40:41.711         	at org.testng.TestNG.privateMain(TestNG.java:1354)
04:40:41.711         	at org.testng.TestNG.main(TestNG.java:1323)
04:40:41.711         
04:40:41.711         
04:40:41.711         ===============================================
04:40:41.711             TestAttachErrorHandling
04:40:41.711             Tests run: 14, Failures: 1, Skips: 0
04:40:41.711         ===============================================
04:40:41.711         
04:40:41.711         
04:40:41.711         ===============================================
04:40:41.711         GeneralTest suite
04:40:41.711         Total tests run: 14, Failures: 1, Skips: 0
04:40:41.711         ===============================================
04:40:41.711         
04:40:41.711         
04:40:41.711         TestAttachErrorHandling_0_FAILED
04:40:41.711     duration_ms: 78927
04:40:41.711   ...
04:40:41.711 ok 109 - TestSunAttachClasses_0
```

**Comment by pshipton** [comment]
I assume whatever can be done, has been done. Closing.
