### ISSUE TITLE
security provider testing gets an unexpected AccessControlException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2978]
make jtreg_tests TESTDIRS=jdk/sun/security/provider

FAILED: sun/security/provider/PolicyFile/Modules.java
```
java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:191)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.findImageLocation(SystemModuleFinders.java:426)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.find(SystemModuleFinders.java:437)
	at java.base/jdk.internal.loader.BuiltinClassLoader$3.run(BuiltinClassLoader.java:617)
	at java.base/jdk.internal.loader.BuiltinClassLoader$3.run(BuiltinClassLoader.java:614)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:696)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:614)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:394)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:414)
	at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
	at java.base/java.lang.Module.getResourceAsStream(Module.java:1570)
	at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:189)
	at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:640)
	at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.security.ProtectionDomain.seeAllp(ProtectionDomain.java:471)
	at java.base/java.security.ProtectionDomain.toString(ProtectionDomain.java:424)
	at java.base/java.lang.String.valueOf(String.java:2949)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at java.base/java.security.AccessController.throwACE(AccessController.java:167)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
	at java.base/java.lang.System.getProperty(System.java:450)
	at java.base/java.lang.System.getProperty(System.java:419)
	at java.base/jdk.internal.jimage.ImageReaderFactory.<clinit>(ImageReaderFactory.java:49)
	at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1064)
	at java.base/sun.net.www.protocol.jrt.JavaRuntimeURLConnection.<clinit>(JavaRuntimeURLConnection.java:55)
	at java.base/sun.net.www.protocol.jrt.Handler.openConnection(Handler.java:42)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.checkPermissionToConnect(SystemModuleFinders.java:405)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.<init>(SystemModuleFinders.java:414)
	at java.base/jdk.internal.module.SystemModuleFinders$2.get(SystemModuleFinders.java:315)
	at java.base/jdk.internal.module.SystemModuleFinders$2.get(SystemModuleFinders.java:312)
	at java.base/jdk.internal.module.ModuleReferenceImpl.open(ModuleReferenceImpl.java:93)
	at java.base/jdk.internal.loader.BuiltinClassLoader$5.apply(BuiltinClassLoader.java:1291)
	at java.base/jdk.internal.loader.BuiltinClassLoader$5.apply(BuiltinClassLoader.java:1288)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at java.base/jdk.internal.loader.BuiltinClassLoader.moduleReaderFor(BuiltinClassLoader.java:1299)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:852)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:777)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:812)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:781)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:751)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
	at Modules.<clinit>(Modules.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/jdk.internal.jimage.ImageReaderFactory.get(ImageReaderFactory.java:59)
	at java.base/jdk.internal.jimage.ImageReaderFactory.getImageReader(ImageReaderFactory.java:85)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemImage.<clinit>(SystemModuleFinders.java:383)
	... 58 more
```

**Comment by pshipton** [comment]
It seems `ImageReaderFactory.<clinit>` is being run after the SecurityManager is installed, but it should be run before.

@JasonFengJ9

**Comment by JasonFengJ9** [comment]
Attempting to reproduce the failure.
