### ISSUE TITLE
JTReg test: sun/security/util/FilePermCompat/CompatImpact.java fails with OpenJ9

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#3008]
The `./jdk/sun/security/util/FilePermCompat/CompatImpact.java` test fails when running with the latest OpenJ9/OpenJDK 11 build. This same test passes when using Hotspot/OpenJDK11 build.

The issue seems to be related to the java option `-Djdk.security.filePermCompat=true`

The main error that is generated is:
```
java.security.AccessControlException: Access denied ("java.io.FilePermission" "f" "read")
```
The full JTReg output for the failure is:
```
command: main -Djdk.security.filePermCompat=true CompatImpact mine
reason: User specified action: run main/othervm -Djdk.security.filePermCompat=true CompatImpact mine 
Mode: othervm [/othervm specified]
Additional options from @modules: --add-modules java.base --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
elapsed time (seconds): 0.746
configuration:
Boot Layer
  add modules: java.base                   
  add exports: java.base/jdk.internal.misc ALL-UNNAMED

STDOUT:
PROC: PonA cmdline: [/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin/java, --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED, -cp, /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/classes/sun/security/util/FilePermCompat/CompatImpact.d:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/classes/java/security/testlibrary:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/jdk/sun/security/util/FilePermCompat:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/jdk/java/security/testlibrary, -Djdk.security.filePermCompat=true, -Djava.security.manager=, -Djava.security.policy=/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/PonA.policy, CompatImpact, test, mine, /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/f, f, /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/f]
/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin/java --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED -cp /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/classes/sun/security/util/FilePermCompat/CompatImpact.d:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/classes/java/security/testlibrary:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/jdk/sun/security/util/FilePermCompat:/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/jdk/java/security/testlibrary -Djdk.security.filePermCompat=true -Djava.security.manager= -Djava.security.policy=/home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/PonA.policy CompatImpact test mine /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/f f /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/f 
PROC: PonA readline: f
PROC: PonA readline: java.security.AccessControlException: Access denied ("java.io.FilePermission" "f" "read")
PROC: PonA readline: 	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
PROC: PonA readline: 	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
PROC: PonA readline: 	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
PROC: PonA readline: 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
PROC: PonA readline: 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
PROC: PonA readline: 	at java.base/java.io.File.exists(File.java:815)
PROC: PonA readline: 	at CompatImpact.main(CompatImpact.java:162)
PROC: PonA readline: /home/groeges/source/openj9jdk11/openj9-openjdk-jdk11/test/testoutput/manual/JTwork/scratch/f
PROC: PonA readline: <EOF>
STDERR:
java.nio.file.NoSuchFileException: stderr.PonA
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at java.base/java.nio.file.Files.copy(Files.java:3118)
	at CompatImpact.main(CompatImpact.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: Test threw exception: java.nio.file.NoSuchFileException: stderr.PonA
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.nio.file.NoSuchFileException: stderr.PonA
```

**Comment by groeges** [comment]
Peter stated: `-Djdk.security.filePermCompat` is related to the Limited doPrivileged method, I could believe OpenJ9 might have a bug related to that, hence me raising this issue. 

To recreate the issue you need to run the JTReg test:
```
$JT_HOME/bin/jtreg -jdk:$JAVA_HOME -r:./testoutput/manual/JTreport -w:./testoutput/manual/JTwork -verbose:fail ./jdk/sun/security/util/FilePermCompat/CompatImpact.java
```

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by groeges** [comment]
Reviewing the test output again I can see that the test that was initially failing now passes. Closing this issue.
