### ISSUE TITLE
OpenJ9 sanity tests fail on OpenJ9 build with OpenJDK10 (18.3)

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#303]
When running the Sanity tests against a build of OpenJ9 with  OpenJDK10 (18..3) the following test suites fail.
```
FAILED test targets:
	JCL_Test_SE90_0
	JCL_Test_SE90_1
```
These fail on these tests:
```
test_getProperties
test_getProperty
test_getProperty2
```
because the tests retrieve the system properties and check the java.version. 
The tests are looking for java.version starting with 9 where the java.version returned from this jdk is '10-internal'. 

Either the test frameworks needs to detect this new jdk version and run new tests or these tests need to be updated to work with both jdk9 and jdk10.

Exact test failure for one of the tests is:
```
test_getProperty2
java.lang.AssertionError: Failed to return correct property value: 10-internal
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_System.test_getProperty2(Test_System.java:220) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@10-internal/Native Method) from jrt:/java.base
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@10-internal/NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@10-internal/DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.lang.reflect.Method.invoke(java.base@10-internal/Method.java:564) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:756) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:610) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1133) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1104) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1434) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1403) from jdk.internal.loader.ClassLoaders$AppClassLoader@e62d135f(file:/root/openj9-openjdk-jdk9/openj9/jvmtest/TestConfig/lib/testng.jar)
```

**Comment by smlambert** [comment]
Based on #332 being closed, I believe this issue can also be closed.  @groeges please confirm.

**Comment by groeges** [comment]
@smlambert I am unsure why the PR was closed as the changes had not been merged. 
I don't have authority to merge them so will need someone to do this. once the pull request has been merged then we can close this issue.

**Comment by groeges** [comment]
@smlambert I remember now why the PR was closed as although the change I made did resolve the issue it was not a very clean solution. Keith made a suggestion which I was going to implement but never got around to it.  He suggested:
```
I was suggesting you use a test like that found at the beginning of test_getProperties() in test/Java8andUp/src_80/org/openj9/test/java/lang/Test_System.java to determine whether the test is running with a pre-java-9 JRE or not. Versions up to and including 8 java.version is "1.0" to "1.8". Version 9, 18.3, etc. will not start with "1.".

As I look at the two copies of Test_System.java, I think the methods test_getProperties(), test_getProperty() and test_getProperty2() should all be the same.
```
I have closed the PR again (as I had reopened it  - and then got lost of additional comments to the change!!) and will raise a new PR when I (or someone else) gets around to providing a more suitable fix. 

As such, this issue is still open.

**Comment by smlambert** [comment]
ok, thanks for the clarification @groeges

**Comment by mikezhang1234567890** [comment]
I'll take a look at this if no one else minds.
