### ISSUE TITLE
JTReg test: jdk/java/lang/Class/GenericStringTest.java fails against OpenJ9

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3041]
JTReg test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/Class/GenericStringTest.java is failing against OpenJ9.

The following output is generated ...
```
...
----------System.err:(18/1356)----------
Unexpected Class.toGenericString output; expected 'java.lang.String[]', got 'public abstract final class [Ljava.lang.String;'.
Unexpected Class.toGenericString output; expected 'java.lang.String[][]', got 'public abstract final class [[Ljava.lang.String;'.
Unexpected Class.toGenericString output; expected 'int[][]', got 'public abstract final class [[I'.
Unexpected Class.toGenericString output; expected 'java.util.Map<K,V>[]', got 'public abstract final class [Ljava.util.Map;'.
Unexpected Class.toGenericString output; expected 'java.util.Map<K,V>[][]', got 'public abstract final class [[Ljava.util.Map;'.
java.lang.RuntimeException
	at GenericStringTest.main(GenericStringTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException
...
```

From the JavaDoc on `<Class>.toGenericString()` (https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#toGenericString--) the strings are not correct.

OpenJ9 build run against ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201809241808)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f3a7b977, JRE 11 Linux amd64-64-Bit Compressed References 20180924_23 (JIT enabled, AOT enabled)
OpenJ9   - f3a7b977
OMR      - cb3dfab6
JCL      - afdb7423f7 based on jdk-11+28)
```

This test passes against Hotspot. Build used ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by pshipton** [comment]
The toGenericString spec changed, or at least was clarified, in Java 9. Need to double check the output on Java 8.

**Comment by pshipton** [comment]
Java 8 appears unchanged, this only affects Java 9 and later.

**Comment by pshipton** [comment]
Note that String.getName() remains unchanged.

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Can you take a look at this?

**Comment by mikezhang1234567890** [comment]
Taking a look.

**Comment by ben-walsh** [comment]
Confirmed test pass using ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810141809)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-fa48180f, JRE 11 Linux amd64-64-Bit Compressed References 20181014_61 (JIT enabled, AOT enabled)
OpenJ9   - fa48180f
OMR      - 6f35a3ce
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
