### ISSUE TITLE
JTReg test: jdk/java/lang/ClassLoader/EndorsedDirs.java fails against OpenJ9

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3055]
When executed against OpenJ9 build ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201809241808)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f3a7b977, JRE 11 Linux amd64-64-Bit Compressed References 20180924_23 (JIT enabled, AOT enabled)
OpenJ9   - f3a7b977
OMR      - cb3dfab6
JCL      - afdb7423f7 based on jdk-11+28)
```
... the JTReg test jdk/java/lang/ClassLoader/EndorsedDirs.java fails ...
```
#Test Results (version 2)
#Thu Sep 27 17:12:57 BST 2018
#-----testdescription-----
$file=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader/EndorsedDirs.java
$root=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk
keywords=bug8060206 bug8067366
library=/lib/testlibrary
run=ASSUMED_ACTION main EndorsedDirs\n
source=EndorsedDirs.java
title=Endorsed standards and override mechanism is removed

#-----environment-----

#-----testresult-----
description=file\:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader/EndorsedDirs.java
elapsed=3989 0\:00\:03.989
end=Thu Sep 27 17\:12\:57 BST 2018
environment=regtest
execStatus=Failed. Execution failed\: `main' threw exception\: java.lang.RuntimeException\: Expected to get exit value of [0]
harnessLoaderMode=Classpath Loader
harnessVariety=Full Bundle
hostname=bendev.hursley.ibm.com
javatestOS=Linux 4.4.0-64-generic (amd64)
javatestVersion=5.0
jtregVersion=jtreg 4.2 dev 398
script=com.sun.javatest.regtest.exec.RegressionScript
sections=script_messages build compile main
start=Thu Sep 27 17\:12\:53 BST 2018
test=java/lang/ClassLoader/EndorsedDirs.java
testJDK=/home/walshbp/openjdk11-openj9-binary/jdk-11+28
totalTime=3996
user.name=walshbp
work=/home/walshbp/jtreg_testing/JTwork/java/lang/ClassLoader

#section:script_messages
----------messages:(10/601)----------
JDK under test: /home/walshbp/openjdk11-openj9-binary/jdk-11+28
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201809241808)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f3a7b977, JRE 11 Linux amd64-64-Bit Compressed References 20180924_23 (JIT enabled, AOT enabled)
OpenJ9   - f3a7b977
OMR      - cb3dfab6
JCL      - afdb7423f7 based on jdk-11+28)
Library /lib/testlibrary; kind: packages
   source directory: /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary
   class directory: /home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary

#section:build
----------messages:(5/137)----------
command: build EndorsedDirs
reason: Named class compiled on demand
Test directory:
  compile: EndorsedDirs
elapsed time (seconds): 2.734
result: Passed. Build successful

#section:compile
----------messages:(4/207)----------
command: compile /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader/EndorsedDirs.java
reason: .class file out of date or does not exist
Mode: othervm
elapsed time (seconds): 2.731
----------configuration:(7/473)----------
javac compilation environment
  source path: /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader
               /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary
  class path:  /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader
               /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d
               /home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary

----------rerun:(23/1817)*----------
cd /home/walshbp/jtreg_testing/JTwork/scratch && \\
DISPLAY=:1 \\
GNOME_DESKTOP_SESSION_ID=this-is-deprecated \\
HOME=/home/walshbp \\
LANG=en_GB.UTF-8 \\
PATH=/bin:/usr/bin \\
XMODIFIERS=@im=ibus \\
    /home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/javac \\
        -J-XX:HeapDumpPath=/tmp \\
        -J-Dtest.src=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader \\
        -J-Dtest.src.path=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary \\
        -J-Dtest.classes=/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d \\
        -J-Dtest.class.path=/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d:/home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary \\
        -J-Dtest.vm.opts=-XX:HeapDumpPath=/tmp \\
        -J-Dtest.tool.vm.opts=-J-XX:HeapDumpPath=/tmp \\
        -J-Dtest.compiler.opts= \\
        -J-Dtest.java.opts= \\
        -J-Dtest.jdk=/home/walshbp/openjdk11-openj9-binary/jdk-11+28 \\
        -J-Dcompile.jdk=/home/walshbp/openjdk11-openj9-binary/jdk-11+28 \\
        -J-Dtest.timeout.factor=1.0 \\
        -d /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d \\
        -sourcepath /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary \\
        -classpath /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader:/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d:/home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary /home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader/EndorsedDirs.java
----------System.out:(0/0)----------
----------System.err:(6/421)----------
/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary/jdk/testlibrary/ProcessTools.java:344: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    public static OutputAnalyzer executeTestJvm(String... options) throws Exception {
                                 ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
result: Passed. Compilation successful

#section:main
----------messages:(4/137)----------
command: main EndorsedDirs
reason: Assumed action based on file name: run main EndorsedDirs 
Mode: othervm
elapsed time (seconds): 0.984
----------configuration:(0/0)----------
----------System.out:(5/879)----------
java.endorsed.dirs = 'null'
Command line: [/home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java -XX:HeapDumpPath=/tmp -Djava.endorsed.dirs=foo -cp /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d EndorsedDirs 0 ]
Command line: [/home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java -XX:HeapDumpPath=/tmp -cp /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d EndorsedDirs 0 ]
Command line: [/home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java -XX:HeapDumpPath=/tmp -Djava.endorsed.dirs= -cp /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d EndorsedDirs 1 ]
Command line: [/home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java -XX:HeapDumpPath=/tmp -Djava.endorsed.dirs="" -cp /home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d EndorsedDirs 2 ]
----------System.err:(24/1257)----------
 stdout: [];
 stderr: [JVMJ9VM148E java.endorsed.dirs="" is no longer supported. The endorsed-standards override mechanism is only supported via upgradable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:375)
	at EndorsedDirs.start(EndorsedDirs.java:79)
	at EndorsedDirs.main(EndorsedDirs.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
----------rerun:(22/1700)*----------
cd /home/walshbp/jtreg_testing/JTwork/scratch && \\
DISPLAY=:1 \\
GNOME_DESKTOP_SESSION_ID=this-is-deprecated \\
HOME=/home/walshbp \\
LANG=en_GB.UTF-8 \\
PATH=/bin:/usr/bin \\
XMODIFIERS=@im=ibus \\
CLASSPATH=/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader:/home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary:/home/walshbp/jtreg/lib/javatest.jar:/home/walshbp/jtreg/lib/jtreg.jar \\
    /home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java \\
        -Dtest.src=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader \\
        -Dtest.src.path=/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/java/lang/ClassLoader:/home/walshbp/jep_testing/openj9-openjdk-jdk11/test/jdk/lib/testlibrary \\
        -Dtest.classes=/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d \\
        -Dtest.class.path=/home/walshbp/jtreg_testing/JTwork/classes/java/lang/ClassLoader/EndorsedDirs.d:/home/walshbp/jtreg_testing/JTwork/classes/lib/testlibrary \\
        -Dtest.vm.opts=-XX:HeapDumpPath=/tmp \\
        -Dtest.tool.vm.opts=-J-XX:HeapDumpPath=/tmp \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/home/walshbp/openjdk11-openj9-binary/jdk-11+28 \\
        -Dcompile.jdk=/home/walshbp/openjdk11-openj9-binary/jdk-11+28 \\
        -Dtest.timeout.factor=1.0 \\
        -XX:HeapDumpPath=/tmp \\
        com.sun.javatest.regtest.agent.MainWrapper /home/walshbp/jtreg_testing/JTwork/java/lang/ClassLoader/EndorsedDirs.d/main.0.jta
result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]


test result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

This is confirmed outside of the JTReg test ... 

```
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -Djava.endorsed.dirs= Test
abc
walshbp@bendev:~/jtreg_testing$ echo $?
0
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -Djava.endorsed.dirs="" Test
abc
walshbp@bendev:~/jtreg_testing$ echo $?
0
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -Djava.endorsed.dirs=\"\" Test
JVMJ9VM148E java.endorsed.dirs="" is no longer supported. The endorsed-standards override mechanism is only supported via upgradable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
walshbp@bendev:~/jtreg_testing$ echo $?
1
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -Djava.endorsed.dirs=foo Test
JVMJ9VM148E java.endorsed.dirs=foo is no longer supported. The endorsed-standards override mechanism is only supported via upgradable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
walshbp@bendev:~/jtreg_testing$ echo $?
1
```

This test passes without issue when executed against Hotspot.

**Comment by ben-walsh** [comment]
That's correct. Okey dokey. I'll perm fail it and reference this issue. Thanks.

**Comment by ben-walsh** [comment]
Same problem with jdk/java/lang/ClassLoader/ExtDirs.java - perm failing also.

**Comment by pshipton** [comment]
As I don't think this is worth fixed, closing the issue.
