### ISSUE TITLE
DirectByteBufferLoadTest fails on Linux aarch64 JDK11 hotspot

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#3065]
**Test failure output**
```
NLT testFailure: testFutureSequentialReadWriteMultiple(net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest): Index -2147483648 out of bounds for length 17
NLT java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 17
NLT 	at net.adoptopenjdk.test.nio2.util.RandomByteArrays.getRandomByteArray(RandomByteArrays.java:95)
NLT 	at net.adoptopenjdk.test.nio2.util.SendingMessage.setRandomMessage(SendingMessage.java:65)
NLT 	at net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest.runFutureSequentialReadWriteMultiple(MultipleReadWriteFutureTest.java:200)
NLT 	at net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest.testFutureSequentialReadWriteMultiple(MultipleReadWriteFutureTest.java:94)
NLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
NLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
NLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
NLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
NLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
NLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
NLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
NLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
NLT 	at junit.framework.TestResult.run(TestResult.java:125)
NLT 	at junit.framework.TestCase.run(TestCase.java:129)
NLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
NLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
NLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
NLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
NLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
NLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
NLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
NLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
NLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
NLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
NLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
NLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
NLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
NLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
NLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
NLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
NLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
NLT 	at java.base/java.lang.Thread.run(Thread.java:834)
```
**Test source Link:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/27eedf98c37b5c950ef3d0810aa01076284318df/openjdk.test.nio/src/test.nio/net/adoptopenjdk/test/nio2/util/RandomByteArrays.java#L95

**Test repo:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest

**Build link**
https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

* Note, the same test passes on other platforms (e.g. Linux x64: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/16/tapResults/)

**Comment by Mesbah-Alam** [comment]
Note, `NioLoadTest_0` fails due to the same isue too, https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

**Comment by Mesbah-Alam** [comment]
Grinder link: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/200/console

**Comment by Mesbah-Alam** [comment]
Closing as it's not an OpenJ9 issue. Will re-open in appropriate repository.

**Comment by Mesbah-Alam** [comment]
Equivalent issues opened at https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/180
