### ISSUE TITLE
LockingLoadTest fails fails on Linux aarch64 JDK11 hotspot

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#3066]
**Test failure output**
```
 LLT testFailure: testCos(net.adoptopenjdk.test.math.MathAPITest): cos(double)[0] :: expected:<-0.9999876894265599> but was:<-0.99998768942656>
LLT junit.framework.AssertionFailedError: cos(double)[0] :: expected:<-0.9999876894265599> but was:<-0.99998768942656>
LLT 	at junit.framework.Assert.fail(Assert.java:57)
LLT 	at junit.framework.Assert.failNotEquals(Assert.java:329)
LLT 	at junit.framework.Assert.assertEquals(Assert.java:78)
LLT 	at junit.framework.TestCase.assertEquals(TestCase.java:244)
LLT 	at net.adoptopenjdk.test.math.MathAPITest.testCos(MathAPITest.java:366)
...
```

```
 testFailure: testLog(net.adoptopenjdk.test.math.MathAPITest): log(double)[2] :: expected:<-744.4400719213812> but was:<-710.989276736877>
LLT junit.framework.AssertionFailedError: log(double)[2] :: expected:<-744.4400719213812> but was:<-710.989276736877>
LLT 	at junit.framework.Assert.fail(Assert.java:57)
LLT 	at junit.framework.Assert.failNotEquals(Assert.java:329)
LLT 	at junit.framework.Assert.assertEquals(Assert.java:78)
LLT 	at junit.framework.TestCase.assertEquals(TestCase.java:244)
LLT 	at net.adoptopenjdk.test.math.MathAPITest.testLog(MathAPITest.java:813)
...
```

**Test repo:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest

**Build link**
https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

* Note, the same test passes on other platforms (e.g. Linux x64: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/16/tapResults/)

**Comment by Mesbah-Alam** [comment]
@DanHeidinga - the failure happens on the following jdk11 sdk: 

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201809271809)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28-201809271809, mixed mode)
```

Should I open this issue at https://github.com/AdoptOpenJDK/openjdk-jdk11 instead?

**Comment by DanHeidinga** [comment]
Given it's a Hotspot test failure, it doesn't apply here at the OpenJ9 project.  I can't speak to whether the particular Adopt repo is the right home or not.

**Comment by DanHeidinga** [comment]
Closing as this is not an OpenJ9 issue

**Comment by Mesbah-Alam** [comment]
Equivalent issue opened at https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/179
