### ISSUE TITLE
JDK11 win64 Jenkins jobs fail due to git fetch timeout

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#3097]
buildenv/jenkins/common/build:get_sources() times out after 30mins:
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Build/job/Build-JDK11-win_x86-64_cmprssptrs/76/

**Comment by pshipton** [comment]
@andrew-m-leonard the link you provided is internal, should this be an internal IBM issue?

**Comment by andrew-m-leonard** [comment]
yes... where do I raise that?, the code in error is possibly in this repo...?

**Comment by pshipton** [comment]
This is the error I see before the timeout. The sha specified doesn't seem to exist.
```
hudson.plugins.git.GitException: Command "git checkout -f d0b6ef5fac6e9c16b1c9fd5671c62cad1e3b78af" returned status code -1:
stdout: 
stderr: error: object directory <internal path>/j9build/jenkins/workspace/Build-JDK11-win_x86-64_cmprssptrs/.git/objects/C:/openjdk/openjdk_cache/objects does not exist; check .git/objects/info/alternates.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2301)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to <internal machine>
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor829.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy92.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1236)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused: hudson.plugins.git.GitException: Could not checkout d0b6ef5fac6e9c16b1c9fd5671c62cad1e3b78af
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2325)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
