### ISSUE TITLE
OpenJDK8 Sanity test failures in testcases JCL_Test_SE80_0/1:test_setSecurityManager2

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#314]
Running the Sanity test suite against OpenJ9 for extensions on OpenJDK8 fails in suites JCL_Test_SE80_0 & JCL_Test_SE80_1:

FAILED: test_setSecurityManager2
java.lang.AssertionError: Unexpected: java.lang.NullPointerException
        at org.testng.Assert.fail(Assert.java:94) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.openj9.test.java.lang.Test_System.test_setSecurityManager2(Test_System.java:400) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar
        at java.lang.reflect.Method.invoke(Method.java:498) from /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:645) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestRunner.privateRun(TestRunner.java:756) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestRunner.run(TestRunner.java:610) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:387) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1218) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.runSuites(TestNG.java:1133) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.run(TestNG.java:1104) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.privateMain(TestNG.java:1434) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
        at org.testng.TestNG.main(TestNG.java:1403) from sun.misc.Launcher$AppClassLoader@83e511ef(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)

**Comment by andrew-m-leonard** [comment]
Internal repo available to build and reproduce this here : https://github.ibm.com/runtimes/openjdk-jdk8

**Comment by pshipton** [comment]
Duplicate of #502, closing this one since there are more comments in #502.
