### ISSUE TITLE
JTReg test fail : java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3142]
Fails with following exception ...

```
test VarHandleTestByteArrayAsChar.testAccess(" VarHandle [ALIGNED, LITTLE_ENDIAN, READ_WRITE] -> byte[] [ALIGNED, LITTLE_ENDIAN, READ_WRITE] read write", VarHandleBaseByteArrayTest$VarHandleSourceAccessTestCase@b6c2da1d): failure
java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.lang.Character.valueOf(Character.java:7937)
	at org.testng.Assert.assertEquals(Assert.java:330)
	at VarHandleTestByteArrayAsChar.testArrayReadWrite(VarHandleTestByteArrayAsChar.java:788)
	at VarHandleTestByteArrayAsChar.lambda$accessTestCaseProvider$0(VarHandleTestByteArrayAsChar.java:139)
	at VarHandleTestByteArrayAsChar$$Lambda$9.00000000C805E640.action(Unknown Source)
	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
	at VarHandleTestByteArrayAsChar.testAccess(VarHandleTestByteArrayAsChar.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... from what's been discussed, I suspect this may well just be a further symptom of the problem identified in https://github.com/eclipse/openj9/issues/3137 and might aid in resolving it.

Full logs : [byteArrayAsCharProblem.tar.gz](https://github.com/eclipse/openj9/files/2446923/byteArrayAsCharProblem.tar.gz)

Passes against Hotspot.

**Comment by pshipton** [comment]
This doesn't need to be tracked against the 0.11.0 release as the release will not hold on this. Either the fix makes it in, or it doesn't and goes into the next release.

**Comment by liqunl** [comment]
Fixed by #3218

**Comment by pshipton** [comment]
@liqunl fyi https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ben-walsh** [comment]
Confirmed test pass using ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810141809)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-fa48180f, JRE 11 Linux amd64-64-Bit Compressed References 20181014_61 (JIT enabled, AOT enabled)
OpenJ9   - fa48180f
OMR      - 6f35a3ce
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
