### ISSUE TITLE
Jenkins java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3147]
Numerous examples in different PRs. Running sanity testing results in `java.lang.OutOfMemoryError: Java heap space` after `TEST AUTO GEN SUCCESSFUL`

https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_x86-64_cmprssptrs-OpenJDK8/3/console
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJDK8/7/console

```
15:11:47 Generated utils.mk
15:11:47 
15:11:47 Generated count.mk
15:11:47 
15:11:47 TEST AUTO GEN SUCCESSFUL
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Get Test Dependencies)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline
Setting status of 5bb0994736a6e4ba821d2dd37f6bbc3fda9c0540 to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJDK8/7/ and message: 'Build finished. '
Using context: Sanity - JDK8 - linux_390-64_cmprssptrs
java.lang.OutOfMemoryError: Java heap space
Caused: java.io.IOException: Unexpected reader termination
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to ub16-390-2
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.Request.call(Request.java:202)
		at hudson.remoting.Channel.call(Channel.java:954)
		at hudson.FilePath.act(FilePath.java:1071)
		at hudson.FilePath.act(FilePath.java:1060)
		at hudson.FilePath.touch(FilePath.java:1614)
		at hudson.plugins.copyartifact.CopyArtifact.copyOne(CopyArtifact.java:624)
		at hudson.plugins.copyartifact.CopyArtifact.copy(CopyArtifact.java:577)
		at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:537)
		at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:475)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
Caused: hudson.remoting.RequestAbortedException
	at hudson.remoting.Request.abort(Request.java:340)
	at hudson.remoting.Channel.terminate(Channel.java:1038)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:103)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau @smlambert

**Comment by AdamBrousseau** [comment]
Hopefully this
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539800

**Comment by AdamBrousseau** [comment]
>Also seen in the copyright check

And the omr mirror job

**Comment by pshipton** [comment]
Seems ok now after restarting Jenkins.
