### ISSUE TITLE
OpenJDK8 Sanity test failures in testcase JLM_Tests_class_SE80_0/1:testFrom_WithCDContainingNullStackFrame

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#316]
Running the Sanity test suite against OpenJ9 for extensions on OpenJDK8 fails in JLM_Tests_class_SE80_0 and JLM_Tests_class_SE80_1 :testFrom_WithCDContainingNullStackFrame:

FAILED: testFrom_WithCDContainingNullStackFrame
java.lang.AssertionError: expected:<Parameter stackDepth is 29 but stackFrame is null> but was:<K060F>
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
        at org.openj9.test.java.lang.management.TestMonitorInfo.testFrom_WithCDContainingNullStackFrame(TestMonitorInfo.java:188)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:756)
        at org.testng.TestRunner.run(TestRunner.java:610)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
        at org.testng.TestNG.runSuites(TestNG.java:1133)
        at org.testng.TestNG.run(TestNG.java:1104)
        at org.testng.TestNG.privateMain(TestNG.java:1434)
        at org.testng.TestNG.main(TestNG.java:1403)

**Comment by andrew-m-leonard** [comment]
I've done a "clean" openjdk8 build and re-compiled and re-run the Sanity tests, and this issue seems to have gone away :-)
