### ISSUE TITLE
JTReg test fail : java/lang/invoke/VarHandles/VarHandleMethodReferenceTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3180]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/VarHandles/VarHandleMethodReferenceTest.java#L58 fails with following due to NPE ...

```
test VarHandleMethodReferenceTest.testMethodReferences(): failure
java.lang.BootstrapMethodError: java.lang.NullPointerException
	at VarHandleMethodReferenceTest.testMethodReferences(VarHandleMethodReferenceTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.NullPointerException
	at java.base/jdk.internal.org.objectweb.asm.Item.set(Item.java:263)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.newMethodItem(ClassWriter.java:1527)
	at java.base/jdk.internal.org.objectweb.asm.MethodWriter.visitMethodInsn(MethodWriter.java:928)
	at java.base/jdk.internal.org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:514)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory$ForwardingMethodGenerator.generate(InnerClassLambdaMetafactory.java:464)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:283)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:188)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1098)
	... 30 more
```

Log archive : [VMMethRefProblem.tar.gz](https://github.com/eclipse/openj9/files/2459935/VMMethRefProblem.tar.gz)

Test passes on Hotspot.

**Comment by ben-walsh** [comment]
Test passes using ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810141809)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-fa48180f, JRE 11 Linux amd64-64-Bit Compressed References 20181014_61 (JIT enabled, AOT enabled)
OpenJ9   - fa48180f
OMR      - 6f35a3ce
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
... closing accordingly.

**Comment by pdbain-ibm** [comment]
I will investigate.

**Comment by pdbain-ibm** [comment]
Issue with invokeVirtual. Will need some help from @DanHeidinga or other JSR 335 expert.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/624

**Comment by pdbain-ibm** [comment]
Boiled it down to a simple test case:
```
public class VarHandleMethodReferenceTest {

  interface R {
      void apply();
  }

  public void testMethodReferences() {
      VarHandle vh = MethodHandles.arrayElementVarHandle(int[].class);

      R r;
      r = vh::get;
  }
	public static void main(String args[]) {
		VarHandleMethodReferenceTest vhTest = new VarHandleMethodReferenceTest();
		vhTest.testMethodReferences();
	}
}
```

**Comment by pdbain-ibm** [comment]
Simpler test case suggested by @DanHeidinga 
```
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandleInfo;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import java.lang.reflect.InvocationTargetException;
public class TestVarHandle  {
	Object foo = null;
	public static void main(String[] args) throws NoSuchFieldException, IllegalAccessException, NoSuchMethodException, SecurityException, IllegalArgumentException, InvocationTargetException {
		VarHandle vh = MethodHandles.lookup().findVarHandle(TestVarHandle.class, "foo", Object.class);
		VarHandle.AccessMode am = VarHandle.AccessMode.valueFromMethodName("get");
		MethodHandle mh = MethodHandles.varHandleExactInvoker(am,vh.accessModeType(am));
		System.out.println("mh class="+mh.getClass().getName());
		MethodHandleInfo result = MethodHandles.lookup().revealDirect(mh);
		System.out.println("result="+result);
	}
}
```
With Hotspot:
```
mh class=java.lang.invoke.MethodHandleImpl$WrappedMember
result=invokeVirtual java.lang.invoke.VarHandle.get:(TestVarHandle)Object
```
With OpenJ9:
```
mh class=java.lang.invoke.VarHandleInvokeExactHandle
result=invokeVirtual java.lang.invoke.VarHandle.null:(TestVarHandle)Object
```

**Comment by DanHeidinga** [comment]
Likely fixable by passing the name to the VarHandleInvoker constructor: https://github.com/eclipse/openj9/blob/fc206904ce524f8575628a8d9a217bf6c1548066/jcl/src/java.base/share/classes/java/lang/invoke/VarHandleInvokeHandle.java#L40

**Comment by pdbain-ibm** [comment]
This needs a test case: https://github.com/eclipse/openj9/issues/4459.
