### ISSUE TITLE
JTReg test fail : java/lang/invoke/condy/CondyBSMInvocation.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3182]
The following failure occurs at https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/condy/CondyBSMInvocation.java#L119 ...

```
test CondyBSMInvocation.testWrongShape(): failure
java.lang.AssertionError: BootstrapMethodError expected to be thrown for MethodHandle(Object[])Object
	at org.testng.Assert.fail(Assert.java:94)
	at CondyBSMInvocation.testWrongShape(CondyBSMInvocation.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Digging deeper, it seems the following shapes of BootstrapMethod trigger a BootstrapMethodError as expected ...
	
```
   public static Object shape_bsm() {
        return "0";
    }

    public static Object shape_bsm(Object a1) {
        return "0";
    }

    public static Object shape_bsm(Object a1, Object a2) {
        return "0";
    }
```

... while the following unexpectedly do not trigger a BootstrapMethodError ...
	
```
    public static Object shape_bsm(Object... args) {
        return "0";
    }

    public static Object shape_bsm(Object a1, Object... args) {
        return "0";
    }

    public static Object shape_bsm(Object a1, Object a2, Object a3) {
        return "0";
    }
```

Log archive : [CondyBSMInvProblem.tar.gz](https://github.com/eclipse/openj9/files/2460449/CondyBSMInvProblem.tar.gz)

Test passes on Hotspot.

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you take a look at this?

**Comment by fengxue-IS** [comment]
looking into this

**Comment by fengxue-IS** [comment]
This is testing the Constant_Dynamic parameter type passed to bsm, should be fixed once #3025 is merged

**Comment by ben-walsh** [comment]
Confirmed test pass using ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810141809)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-fa48180f, JRE 11 Linux amd64-64-Bit Compressed References 20181014_61 (JIT enabled, AOT enabled)
OpenJ9   - fa48180f
OMR      - 6f35a3ce
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
