### ISSUE TITLE
JTReg test fail : java/lang/invoke/condy/CondyWrongType.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3185]
Sub-test failure at https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/condy/CondyWrongType.java#L123 ...

```
test CondyWrongType.testPrimitives("B", "C", false): failure
java.lang.AssertionError: Throwable expected
	at org.testng.Assert.fail(Assert.java:94)
	at CondyWrongType.test(CondyWrongType.java:123)
	at CondyWrongType.testPrimitives(CondyWrongType.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```
Looks to be the only testPrimitive sub-test with an issue.

Digging deeper, I get ...
```
Exception in thread "main" java.lang.invoke.WrongMethodTypeException
	at java.base/java.lang.invoke.ConvertHandle$FilterHelpers.getPrimitiveReturnFilter(ConvertHandle.java:219)
	at java.base/java.lang.invoke.ConvertHandle$FilterHelpers.getReturnFilter(ConvertHandle.java:152)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:493)
	at Test.main(Test.java:10)
```
... executing ...
```
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;

public class Test {

   public static void main(String args[]) {

      MethodHandles.zero(byte.class).asType(MethodType.methodType(char.class));

   }

}
```
... which seems wrong to me.

Log archive : [CondyWrongTypProblem.tar.gz](https://github.com/eclipse/openj9/files/2460808/CondyWrongTypProblem.tar.gz)

Test passes on Hotspot.

**Comment by fengxue-IS** [comment]
problem is related to invocation casting, OpenJ9 allows converting from Boxed `Byte.class` to primitive `char.class`. As per **JLS 5.12 -5.14 & 5.3**, `MH.invoke(...)` argument casting should only allow boxing/unboxing/widening operation (Byte -> char is combination of widening and narrowing)

**Comment by smlambert** [comment]
Test excluded via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/625
