### ISSUE TITLE
JTReg test fail : java/util/Spliterator/SpliteratorCharacteristics.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3202]
Test failure at https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/util/Spliterator/SpliteratorCharacteristics.java#L93 ...

```
test SpliteratorCharacteristics.testSpliteratorFromCharSequence(): failure
java.lang.AssertionError: Spliterator characteristics expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at SpliteratorCharacteristics.assertCharacteristics(SpliteratorCharacteristics.java:392)
	at SpliteratorCharacteristics.testSpliteratorFromCharSequence(SpliteratorCharacteristics.java:93)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

This test passes against Hotspot.

Digging deeper, execution of this ...

```
import java.util.Spliterator;

public class Test {

   public static void main(String args[]) {

      CharSequence cs = "A";
      Spliterator.OfInt s = cs.chars().spliterator();
      System.out.println("IMMUTABLE : " + s.hasCharacteristics(Spliterator.IMMUTABLE));
      System.out.println("ORDERED : " + s.hasCharacteristics(Spliterator.ORDERED));
      System.out.println("SIZED : " + s.hasCharacteristics(Spliterator.SIZED));
      System.out.println("SUBSIZED : " + s.hasCharacteristics(Spliterator.SUBSIZED));

   }

}
```
... yields ...

```
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-hotspot-binary/jdk-11/bin/javac Test.java
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-hotspot-binary/jdk-11/bin/java Test
IMMUTABLE : true
ORDERED : true
SIZED : true
SUBSIZED : true
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/javac Test.java
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java Test
IMMUTABLE : false
ORDERED : true
SIZED : true
SUBSIZED : true
```

Is it intentional that a CharSequence is MUTABLE in OpenJ9 while it is IMMUTABLE in Hotspot ?

Log archive : [SplitCharProb.tar.gz](https://github.com/eclipse/openj9/files/2464242/SplitCharProb.tar.gz)

**Comment by pdbain-ibm** [comment]
String.chars() calls `CharSequence.super.chars();`.  The javadoc for Spliterator says 

> Structural interference of a source can be managed in the following ways (in approximate order of decreasing desirability):
>  
> The source cannot be structurally interfered with. 
> For example, an instance of CopyOnWriteArrayList is an immutable source. A Spliterator created from the source reports a characteristic of IMMUTABLE.
> ...

`spliterator​(int[] array, int fromIndex, int toIndex, int additionalCharacteristics)` looks like the ticket. `additionalCharacteristics` can set `IMMUTABLE`.

**Comment by pdbain-ibm** [comment]
I'll take a look at this.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/627
