### ISSUE TITLE
JTReg test fail : java/util/concurrent/tck/JSR166TestCase.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3213]
Multiple sub-test failures of https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/util/concurrent/tck/JSR166TestCase.java with similar exception stack ...

```
JavaTest Message: JUnit Failure: testRecursiveSubMaps(ConcurrentSkipListMapTest): java.util.GPUAssistHolder (initialization failure)
java.lang.NoClassDefFoundError: java.util.GPUAssistHolder (initialization failure)
	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:141)
	at java.base/java.util.Arrays.sort(Arrays.java:152)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1191)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1173)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1164)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1158)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1164)
	at ConcurrentSkipListMapTest.bashSubMap(ConcurrentSkipListMapTest.java:1158)
	at ConcurrentSkipListMapTest.testRecursiveSubMaps(ConcurrentSkipListMapTest.java:1052)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at JSR166TestCase.runTest(JSR166TestCase.java:361)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at JSR166TestCase.runBare(JSR166TestCase.java:352)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.util.ServiceConfigurationError: com.ibm.gpu.spi.GPUAssist$Provider: Unable to load com.ibm.gpu.internal.CudaGPUAssistProvider
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:862)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1076)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.util.GPUAssistHolder.gpuAssist(GPUAssistHolder.java:33)
	at java.base/java.util.GPUAssistHolder.<clinit>(GPUAssistHolder.java:28)
	at java.base/java.util.Arrays.sort(Arrays.java:226)
	at RecursiveActionTest$SortTask.sortSequentially(RecursiveActionTest.java:1234)
	at RecursiveActionTest$SortTask.compute(RecursiveActionTest.java:1223)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at RecursiveActionTest$SortTask.compute(RecursiveActionTest.java:1226)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at RecursiveActionTest$SortTask.compute(RecursiveActionTest.java:1226)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at RecursiveActionTest$SortTask.compute(RecursiveActionTest.java:1226)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:761)
	at RecursiveActionTest$SortTask.compute(RecursiveActionTest.java:1226)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.com.ibm.gpu.spi")
	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1238)
	at java.base/java.lang.J9VMInternals$2.run(J9VMInternals.java:313)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.base/java.lang.J9VMInternals.checkPackageAccess(J9VMInternals.java:308)
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:459)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1991)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1022)
	at java.base/jdk.internal.loader.BuiltinClassLoader.lambda$findClassInModuleOrNull$5(BuiltinClassLoader.java:866)
	at jdk.internal.loader.BuiltinClassLoader$$Lambda$42.0000000084312840.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:867)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:733)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1137)
	at java.base/java.lang.Class.forName(Class.java:482)
	at java.base/java.util.ServiceLoader.lambda$loadProvider$1(ServiceLoader.java:856)
	at java.util.ServiceLoader$$Lambda$39.0000000084311CA0.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:858)
	... 34 more
```

All the failures occur consistently.

I haven't been able to reproduce the any such failures with Arrays.sort(...) calls in non-concurrent environments. Are there any additional / different security permissions requried to perform the service loading in a concurrent threaded environment ?

Test passes against Hotspot.

Log archive : [JSR166Problem.tar.gz](https://github.com/eclipse/openj9/files/2465419/JSR166Problem.tar.gz)

**Comment by JasonFengJ9** [comment]
Looking at this.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/630

**Comment by JasonFengJ9** [comment]
Note: this test can't be enabled as per decision made as per https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/63.
