### ISSUE TITLE
aix jdk11 fails to build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3227]
https://ci.eclipse.org/openj9/job/Build-JDK11-aix_ppc-64_cmprssptrs/68/console

Likely caused by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/28

**Comment by pshipton** [comment]
@keithc-ca

**Comment by pshipton** [comment]
ibmruntimes/openj9-openjdk-jdk11#28 has been reverted until it can be fixed.

**Comment by pshipton** [comment]
Copied the console from the failure [aix-console.txt](https://github.com/eclipse/openj9/files/2468902/aix-console.txt)

**Comment by keithc-ca** [comment]
This is the problem:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized array: unsigned short int[]
    at com.ibm.j9ddr.PointerHelper.doArrayMethod(BytecodeGenerator.java:473)
    at com.ibm.j9ddr.PointerHelper.doAccessorMethods(BytecodeGenerator.java:344)
    at com.ibm.j9ddr.PointerHelper.generate(BytecodeGenerator.java:1540)
    at com.ibm.j9ddr.PointerHelper.getClassBytes(BytecodeGenerator.java:232)
    at com.ibm.j9ddr.BytecodeGenerator.getPointerClassBytes(BytecodeGenerator.java:52)
    at com.ibm.j9ddr.StructureReader.getPointerClassBytes(StructureReader.java:878)
    at com.ibm.j9ddr.tools.ClassGenerator.writeTo(ClassGenerator.java:188)
    at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:145)
    at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:53)
```

**Comment by keithc-ca** [comment]
This should be resolved by https://github.com/eclipse/omr/pull/3157: it should be safe to re-instate https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/28.

**Comment by keithc-ca** [comment]
This should be fixed by https://github.com/eclipse/omr/pull/3295 (and https://github.com/eclipse/omr/pull/2830).
