### ISSUE TITLE
Attach API agent loading tests fail on MacOS

### ISSUE THREAD

**Issue by pdbain** [eclipse/openj9#3266]
```
TestAttachAPI_0 Start Time: Sat Oct 13 18:43:08 2018 Epoch Time (ms): 1539470588364
test with NoOptions
{ mkdir -p "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15394705876345/TestAttachAPI_0"; \
	cd "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15394705876345/TestAttachAPI_0"; \
	export LD_LIBRARY_PATH=""/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/../../native-test-libs/:/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/../lib/compressedrefs:/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/j9vm":"; \
		"/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/java" -Xcompressedrefs  \
	--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED \
	-cp "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
	-Djava.sidecar="--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED" \
	-Dcom.ibm.tools.attach.enable=yes \
	-Dcom.ibm.tools.attach.timeout=15000 \
	org.testng.TestNG -d "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15394705876345/TestAttachAPI_0" "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestAttachAPI \
	-groups level.extended \
	-excludegroups d.*.osx_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all; \
	if [ $? -eq 0 ] ; then echo ""; echo "TestAttachAPI_0""_PASSED"; echo ""; cd /Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../..; rm -f -r "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15394705876345/TestAttachAPI_0"; else echo ""; echo "TestAttachAPI_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/pdbain/vm/test/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15394705876345/TestTargetResult";
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/pdbain/vm/test/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[AttachApiTest] [ERROR] com.sun.tools.attach.AgentLoadException: ATTACH_ERR AgentLoadException jvmtitest:
	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:326)
	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgentLibrary(OpenJ9VirtualMachine.java:244)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgentLibrary(VirtualMachine.java:377)
	at org.openj9.test.attachAPI.TestAttachAPI.test_agntld01(TestAttachAPI.java:132)
```

**Comment by pdbain** [comment]
```
1539470891553 test_agntld01: 16 [Attach API wait loop]: unlocking file /var/folders/w4/xf7tkpqr8xj1x500r6_kx6880000gn/T/.com_ibm_tools_attach/test_agntld01/attachNotificationSync
1539470891554 test_agntld01: 16 [Attach API wait loop]: closing /var/folders/w4/xf7tkpqr8xj1x500r6_kx6880000gn/T/.com_ibm_tools_attach/test_agntld01/attachNotificationSync
1539470891556 test_agntld01: 17 [Attachment 57622]: doCommand ATTACH_LOADAGENTLIBRARY(jvmtitest)
1539470891556 test_agntld01: 17 [Attachment 57622]: loadAgentLibrary jvmtitest: decorate=true
1539470891559 test_agntld01: 17 [Attachment 57622]: streamSend ATTACH_ERR AgentLoadException jvmtitest:
1539470891565 test_agntld01: 17 [Attachment 57622]: doCommand ATTACH_DETACH
1539470891565 test_agntld01: 17 [Attachment 57622]: streamSend ATTACH_DETACHED
1539470891570 test_agntld01: 14 [Attach API teardown]: shutting down attach API
```
There is no `libjvmtitst.so`:
```
: find  /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release -name libjvmti\*
/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/vm/lib/libjvmti_test_agent.a
/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/vm/lib/libjvmti_test_src.a
/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/vm/libjvmtitest.dylib
```

@DanHeidinga 
Do I need to decorate the library with `.dylib` instead of `.so`?

**Comment by DanHeidinga** [comment]
> Do I need to decorate the library with .dylib instead of .so?

Yes, mac uses .dylib for shared libraries.

**Comment by DanHeidinga** [comment]
For C code, you can use the `J9PORT_LIBRARY_SUFFIX` to get the right .so / .dylib suffix for the current platform

**Comment by pdbain-ibm** [comment]
AttachAPI is decorating the library name correctly.  I can do a `loadAgent` manually.

**Comment by pdbain-ibm** [comment]
Problems:

1. Build may be missing `libjvmtitest.dylib` (to be confirmed)
2. Need to fix this on MacOS:
```
public void test_agntld03() {
...
		String decoration = "lib";
		String suffix = ".so";
```

**Comment by pdbain** [comment]
In re comment 1 of 
https://github.com/eclipse/openj9/issues/3266#issuecomment-429977546, test agent
`libjvmtitest.dylib` is not being moved to the correct location.  The library search path is:

- /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/../../native-test-libs/
- /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/../lib/compressedrefs
- /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/j9vm

but the agent is in `/Users/pdbain/vm/openj9-openjdk-jdk11//build/macosx-x86_64-normal-server-release/vm/libjvmtitest.dylib`.

This looks like a build problem.

I will have a fix for issue 2 shortly.
