### ISSUE TITLE
JTreg test fail : java/lang/invoke/MethodHandles/TestCatchException.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3274]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/MethodHandles/TestCatchException.java has two failures ...

```
JavaTest Message: JUnit Failure: testVarargsCollectorNoThrow(test.java.lang.invoke.TestCatchException): arrays first differed at element [0]; expected:<str> but was:<[Ljava.lang.Object;@33cf9409>
arrays first differed at element [0]; expected:<str> but was:<[Ljava.lang.Object;@33cf9409>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.internalArrayEquals(Assert.java:416)
	at org.junit.Assert.assertArrayEquals(Assert.java:168)
	at org.junit.Assert.assertArrayEquals(Assert.java:185)
	at org.junit.Assert.assertEquals(Assert.java:709)
	at test.java.lang.invoke.TestCatchException.m1(TestCatchException.java:89)
	at java.base/java.lang.invoke.VarargsCollectorHandle.invokeWithArguments(VarargsCollectorHandle.java:128)
	at java.base/java.lang.invoke.MethodHandles$CatchHelper.helper(MethodHandles.java:4439)
	at test.java.lang.invoke.TestCatchException.testVarargsCollectorNoThrow(TestCatchException.java:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: JUnit Failure: testVarargsCollectorThrow(test.java.lang.invoke.TestCatchException): arrays first differed at element [0]; expected:<str> but was:<[Ljava.lang.Object;@33cf9409>
arrays first differed at element [0]; expected:<str> but was:<[Ljava.lang.Object;@33cf9409>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
	at org.junit.Assert.internalArrayEquals(Assert.java:416)
	at org.junit.Assert.assertArrayEquals(Assert.java:168)
	at org.junit.Assert.assertArrayEquals(Assert.java:185)
	at org.junit.Assert.assertEquals(Assert.java:709)
	at test.java.lang.invoke.TestCatchException.throwEx(TestCatchException.java:118)
	at java.base/java.lang.invoke.VarargsCollectorHandle.invokeWithArguments(VarargsCollectorHandle.java:128)
	at java.base/java.lang.invoke.MethodHandles$CatchHelper.helper(MethodHandles.java:4439)
	at test.java.lang.invoke.TestCatchException.testVarargsCollectorThrow(TestCatchException.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Test passes against HotSpot.

Log archive : [CatchExceptionProb.tar.gz](https://github.com/eclipse/openj9/files/2479464/CatchExceptionProb.tar.gz)

**Comment by pdbain-ibm** [comment]
MethodHandle. asVarargsCollector() javadoc says:

> Otherwise, if the caller and adapter arity are the same, and the trailing parameter type of the caller is a reference type identical to or assignable to the trailing parameter type of the adapter, the arguments and return values are converted pairwise, as if by asType on a fixed arity method handle.
> 
> Otherwise, the arities differ, or the adapter's trailing parameter type is not assignable from the corresponding caller type. In this case, the adapter replaces all trailing arguments from the original trailing argument position onward, by a new array of type arrayType, whose elements comprise (in order) the replaced arguments.

**Comment by DanHeidinga** [comment]
The implementation of CatchHandle is a little odd compared to the other handles as it has to be able to catch an exception:
https://github.com/eclipse/openj9/blob/4132ae378e5274c09cdc57fac2e52310e9a48d7c/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L2185-L2187

The JIT implementation uses a `thunkArchetype` method:
https://github.com/eclipse/openj9/blob/4132ae378e5274c09cdc57fac2e52310e9a48d7c/jcl/src/java.base/share/classes/java/lang/invoke/CatchHandle.java#L69-L84

But the interpreter implements this using a Collect-operate-spread pattern:
https://github.com/eclipse/openj9/blob/4132ae378e5274c09cdc57fac2e52310e9a48d7c/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L4712-L4723

The bug likely lies somewhere between the CatchHelper class and the `buildTransformHandle()` method that creates the CatchHelper: https://github.com/eclipse/openj9/blob/4132ae378e5274c09cdc57fac2e52310e9a48d7c/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L3208

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/643

**Comment by DanHeidinga** [comment]
Simple test cases work when run with `-Xjit:count=0` so this is going to be a bug in how the CatchHelper gets created
