### ISSUE TITLE
JTReg test fail : java/nio/file/Files/CallWithInterruptSet.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3325]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/nio/file/Files/CallWithInterruptSet.java has 3 similar failures of the form ...

```
test CallWithInterruptSet.testReadString(): failure
java.lang.AssertionError: expected [hello] but found [h\u0000e\u0000l\u0000l\u0000o\u0000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at CallWithInterruptSet.testReadString(CallWithInterruptSet.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Test passes against Hotspot.

Compiling & executing following "snippet" on OJ9 and HS ...
```
import java.nio.file.Files;
import java.nio.file.Path;

public class Test {

   public static void main(String args[]) throws Exception {

      String msg = "hello";
      Path file = Files.createTempFile(Path.of("."), "tmp", "tmp");
      Files.writeString(file, msg);
      String readString = Files.readString(file);

      System.out.println("readString length : " + readString.length());
      System.out.println("readString : " + readString);
      
      for (int i = 0; i < readString.length(); i++) {

            System.out.println("readstring["+i+"] : " + readString.charAt(i));

      }

      System.out.println("msg length : " + msg.length());
      System.out.println("msg : " + msg);

      for (int i = 0; i < msg.length(); i++) {

            System.out.println("msg["+i+"] : " + msg.charAt(i));

      }

      System.out.println("msg.equals(readString) : " + msg.equals(readString));

   }

}
```
... gives ...
```
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-openj9-binary/jdk-11+28/bin/java Test
readString length : 10
readString : hello
readstring[0] : h
readstring[1] : 
readstring[2] : e
readstring[3] : 
readstring[4] : l
readstring[5] : 
readstring[6] : l
readstring[7] : 
readstring[8] : o
readstring[9] : 
msg length : 5
msg : hello
msg[0] : h
msg[1] : e
msg[2] : l
msg[3] : l
msg[4] : o
msg.equals(readString) : false
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-hotspot-binary/jdk-11/bin/javac Test.java
walshbp@bendev:~/jtreg_testing$ /home/walshbp/openjdk11-hotspot-binary/jdk-11/bin/java Test
readString length : 5
readString : hello
readstring[0] : h
readstring[1] : e
readstring[2] : l
readstring[3] : l
readstring[4] : o
msg length : 5
msg : hello
msg[0] : h
msg[1] : e
msg[2] : l
msg[3] : l
msg[4] : o
msg.equals(readString) : true
```

Looks like what's written out to the file in OpenJ9 differs from what's written out to the file in Hotspot.

Log archive : [FilesWriteProb.tar.gz](https://github.com/eclipse/openj9/files/2488267/FilesWriteProb.tar.gz)

**Comment by pdbain-ibm** [comment]
Dumping the file on OpenJ9 gives:

> $ od -c tmp13975935562788960388tmp 
> 0000000    h  \0   e  \0   l  \0   l  \0   o  \0

on Hotspot:

> $ od -c tmp5839150921832204941tmp 
> 0000000    h   e   l   l   o

**Comment by pdbain-ibm** [comment]
OpenJ9's String.coder is 1 (UTF-16), while Hotspot's is 0 (LATIN-1).
OpenJ9 does not enable string compression (`-XX:[+-]CompactStrings`) by default, while Hotspot does enable it.
When run with compression _enabled_, OpenJ9 produces the correct result, and Hotspot run with compression _disabled_ produces the incorrect result.

This appears to be a bug in the OpenJDK string coding class.

**Comment by DanHeidinga** [comment]
FYI @andrew-m-leonard - Can you follow up with the OpenJDK community on this test?  Based on @pdbain-ibm's analysis, the test appears to be incorrect.

**Comment by pdbain-ibm** [comment]
> the test appears to be incorrect.

I beg to differ: I believe `writeString()` is not converting the `String` buffer to a `CharSequence` properly. `writeString()` is new in Java 11, so it may have some bugs.

**Comment by adamfarley** [comment]
My analysis isn't required anymore, because it appears the latest nightly build, as well as my local build, doesn't show this defect anymore. Test passes. 

Note that the last release build still shows this error, so it seems clear that the issue was resolved in one of the change sets since the last release.

Here's a test grinder to be sure:

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/735/

If this passes, I'll remove the affiliated tests from the exclude file. Working on that PR now.

**Comment by adamfarley** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/780

**Comment by ben-walsh** [comment]
Closing following de-exclusion of the test, following determination that the identified problem has been resolved by changes made subsequent to the last release build time.
