### ISSUE TITLE
Test-extended.functional-JDK10-aix_ppc-64_cmprssptrs TestAttachErrorHandling.testVmShutdownWhileAttached

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3341]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-aix_ppc-64_cmprssptrs/92/
aix71-p8-2

Error Message

com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 20316346 on port 50402

Stacktrace
```
      java.lang.AssertionError: com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 20316346 on port 50402
at org.testng.Assert.fail(Assert.java:96)
at org.openj9.test.attachAPI.AttachApiTest.logExceptionInfoAndFail(AttachApiTest.java:46)
at org.openj9.test.attachAPI.TestAttachErrorHandling.testVmShutdownWhileAttached(TestAttachErrorHandling.java:355)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@pdbain-ibm

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/217
`java.lang.AssertionError: com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 16056454 on port 55575`

**Comment by JasonFengJ9** [comment]
**JDK11** : https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/188
``
03:58:18  FAILED: testVmShutdownWhileAttached
03:58:18  java.lang.AssertionError: com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 11141206 on port 46059
03:58:18  	at org.testng.Assert.fail(Assert.java:96)
03:58:18  	at org.openj9.test.attachAPI.AttachApiTest.logExceptionInfoAndFail(AttachApiTest.java:54)
03:58:18  	at org.openj9.test.attachAPI.TestAttachErrorHandling.testVmShutdownWhileAttached(TestAttachErrorHandling.java:352)
``
