### ISSUE TITLE
can't run Eclipse itself using jdk11+28 on macOS

### ISSUE THREAD

**Issue by martinlippert** [eclipse/openj9#3371]
Tried to run Eclipse using OpenJDK 11 with J9 on macOS (jdk11+28), but it fails with a message: "Failed to create Java Virtual Machine"

Specified the J9 VM in the ini file using "-vm" option, as usual.

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by pdbain-ibm** [comment]
Will do.

**Comment by pdbain-ibm** [comment]
@babsingh: @charliegracie thinks you may have some insight into this.
I am building a non-compressedrefs JDK to test his hypothesis.

**Comment by pdbain-ibm** [comment]
Having trouble building non-compressedrefs: https://github.com/eclipse/openj9/issues/3382.

**Comment by babsingh** [comment]
> JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata; 200M requested

I saw the same error when building OpenJ9 compressedrefs; `javac` didn't run to build the JDK tools. Memory wasn't being allocated below 4GB. This issue was fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/35. `-pagezero_size 0x1000` was appended to `LDFLAGS_JDKEXE`. `-pagezero_size` is only applied when generating executables (`java`, `javac`, ...).

It may not be the same issue this time since `java -version`, `javac -version` and other Java tests run. Something else may be failing during GC initialization.

fyi @pdbain-ibm

**Comment by JasonFengJ9** [comment]
@martinlippert were you able to launch `Eclipse` with an `OpenJDK JDK11` by any chance?

**Comment by pdbain-ibm** [comment]
Successfully built OpenJ9 Java 11 (full 64 bit). I get a splash screen, then a message: `No Java runtime present, requesting install`.

**Comment by JasonFengJ9** [comment]
@babsingh the theory can be verified via a native application compiled and linked without `-pagezero_size 0x1000`, this app just launch an `OpenJ9 -version`. If the guess is right, `-version` won't succeed.

**Comment by babsingh** [comment]
Thanks, @JasonFengJ9. I am creating a native app (with and without `-pagezero_size 0x1000`). It will invoke/wrap a call to `java` compressedrefs to verify my hypothesis.

**Comment by babsingh** [comment]
Observations for `compressedrefs`:
1) Native applications which call `java` via the `system` function work fine.
2) Native applications which invoke the JVM using JNI after linking to the shared libraries such as `libjvm.dylib` need `-pagezero_size 0x1000`. Otherwise, `Initialization error for library j9gc29(2)` will be encountered.
3) Got further by launching Eclipse using the JAR file: `java -XstartOnFirstThread -jar /Applications/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar`. OpenJ9 JDK11 compressedrefs didn't encounter the `Initialization error for library j9gc29(2)`. But, hit the same error as before related to `org.eclipse.m2e.logback.configuration: Initializing logback`. As Peter mentioned above, using a full MacOS JVM may fix this issue. Not sure if there will be other issues related to directly using the JAR file.

To use the `./eclipse` executable with OpenJ9 compressedrefs on OSX, it will need to be rebuilt with `-pagezero_size 0x1000`.

**Comment by charliegracie** [comment]
Why does OpenJDK with hotspot, which defaults to compressed references, work with the same eclipse executable?

**Comment by pdbain-ibm** [comment]
Further to 
https://github.com/eclipse/openj9/issues/3371#issuecomment-432269446

> Start building full MacOS JREs.

Use `build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.0.1.jdk/Contents/Home/bin/java`

**Comment by pdbain-ibm** [comment]
About 
https://github.com/eclipse/openj9/issues/3371#issuecomment-432291933

> Native applications which invoke the JVM using JNI after linking to the shared libraries such as libjvm.dylib need -pagezero_size 0x1000.

This will be an issue with any custom Java launcher, right?

@babsingh could you try your native launcher (with the default `pagezero_size`) with Hotspot?

**Comment by pdbain-ibm** [comment]
@AdamBrousseau would it be possible to add MacOS Large Heap (alias non-compressedrefs) builds to AdoptOpenJDK so users can run Eclipse?

**Comment by AdamBrousseau** [comment]
>add MacOS Large Heap builds to Adopt

I assume it could be easily added. I would recommend opening an issue at [AdoptOpenJDK-Build](https://github.com/AdoptOpenJDK/openjdk-build). I think Stewart is trying to get 8 working atm.

**Comment by pdbain-ibm** [comment]
As a workaround for the present issue, I have requested large heap builds on AdoptOpenJDK: https://github.com/AdoptOpenJDK/openjdk-build/issues/686.

**Comment by babsingh** [comment]
> could you try your native launcher (with the default pagezero_size) with Hotspot?

@pdbain-ibm OpenJDK works regardless of `-pagezero_size,0x1000` being specified. OpenJ9 compressedrefs experiences `Initialization error for library j9gc29(2)` in the absence of `-pagezero_size,0x1000`.

**Compiling native app (using Java 8):**
```
OpenJ9:
gcc -o main -I ${JAVA_HOME}/include/ -I ${JAVA_HOME}/include/darwin/ -ldl main.c ${JAVA_HOME}/jre/lib/compressedrefs/libjvm.dylib -Wl,-rpath,${JAVA_HOME}/jre/lib/compressedrefs,-pagezero_size,0x1000

Hotspot:
gcc -o main -I ${JAVA_HOME}/include/ -I ${JAVA_HOME}/include/darwin/ -ldl main.c ${JAVA_HOME}/jre/lib/server/libjvm.dylib -Wl,-rpath,${JAVA_HOME}/jre/lib/server,-pagezero_size,0x1000
```

> Why does OpenJDK with hotspot, which defaults to compressed references, work with the same eclipse executable?

@charliegracie not sure why Hotspot works. Guess: it may have a fail safe if memory allocation below 4GB fails. In OMR context: if `allocate_memory32` fails, then use `malloc`.

On 64-bit, `pagezero` size is the lower 4GB by default; this is an unreadable segment created by the linker. I think the `pagezero` size can't be defined dynamically, and it can only be specified while building as a linker flag for executables.

**Comment by pdbain-ibm** [comment]
@babsingh would you kindly attach your `main.c`?

@charliegracie @dmitripivkine does the `compressed references metadata` need to be below the 32-bit bar?

**Comment by dmitripivkine** [comment]
> @babsingh would you kindly attach your `main.c`?
> 
> @charliegracie @dmitripivkine does the `compressed references metadata` need to be below the 32-bit bar?

Current implementation required some VM metadata (j9classes, j9vmthreads etc) to be allocated below 4G bar.

**Comment by babsingh** [comment]
@pdbain-ibm **main.c**:
```
#include <jni.h>

int main(int argc, char **argv)
{
    JavaVM         *vm;
    JNIEnv         *env;
    JavaVMInitArgs  vm_args;
    jint            res;
    jclass          cls;
    jmethodID       mid;
    jstring         jstr;
    jobjectArray    main_args;
    JavaVMOption    options;

    vm_args.version  = JNI_VERSION_1_8;
    vm_args.nOptions = 1;
    options.optionString = "-Xcompressedrefs";
    vm_args.options = &options;
    res = JNI_CreateJavaVM(&vm, (void **)&env, &vm_args);
    if (res != JNI_OK) {
        printf("Failed to create Java VM\n");
        return 1;
    } else {
        printf("Created Java VM successfully\n");
    }

    return 0;
}
```

**Comment by pdbain-ibm** [comment]
I modified the launcher to run an application, set the options to `-XX:+UseCompressedOops`, and compiled against Hotspot w/o `-pagezero_size`. I dumped the memory map from a running process:
```
==== regions for process 11640  (non-writable and writable regions are interleaved)
REGION TYPE                      START - END             [ VSIZE  RSDNT  DIRTY   SWAP] PRT/MAX SHRMOD PURGE    REGION DETAIL
__TEXT                 000000010579d000-000000010579e000 [    4K     4K     0K     0K] r-x/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
__DATA                 000000010579e000-000000010579f000 [    4K     4K     4K     0K] rw-/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
__LINKEDIT             000000010579f000-00000001057a0000 [    4K     4K     0K     0K] r--/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
Kernel Alloc Once      00000001057a0000-00000001057a2000 [    8K     4K     4K     0K] rw-/rwx SM=PRV    
MALLOC metadata        00000001057a2000-00000001057a3000 [    4K     4K     4K     0K] r--/rwx SM=ZER          DefaultMallocZone_0x1057a2000 zone structure
MALLOC metadata        00000001057a3000-00000001057a4000 [    4K     4K     4K     0K] rw-/rwx SM=ZER    
MALLOC metadata        00000001057a4000-00000001057a5000 [    4K     4K     4K     0K] r--/rwx SM=PRV    
shared memory          00000001057a5000-00000001057a6000 [    4K     4K     4K     0K] r--/rw- SM=SHM    
__TEXT                 00000001057a6000-0000000105f6e000 [ 7968K  7968K     0K     0K] r-x/rwx SM=COW          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/l...
```

Compiling with `-pagezero_size0x1000` gives a different map:
```
==== regions for process 11886  (non-writable and writable regions are interleaved)
REGION TYPE                      START - END             [ VSIZE  RSDNT  DIRTY   SWAP] PRT/MAX SHRMOD PURGE    REGION DETAIL
__TEXT                 000000000fae5000-000000000fae6000 [    4K     4K     0K     0K] r-x/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
__DATA                 000000000fae6000-000000000fae7000 [    4K     4K     4K     0K] rw-/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
__LINKEDIT             000000000fae7000-000000000fae8000 [    4K     4K     0K     0K] r--/rwx SM=COW          /Users/pdbain/macprojects/eclipse/launcher
__TEXT                 000000000fae8000-00000000102b0000 [ 7968K  7968K     0K     0K] r-x/rwx SM=COW          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/lib/server/libjvm.dylib
__DATA                 00000000102b0000-0000000010375000 [  788K   788K   788K     0K] rw-/rwx SM=COW          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/lib/server/libjvm.dylib
__DATA                 0000000010375000-00000000103a1000 [  176K   172K   172K     0K] rw-/rwx SM=PRV          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/lib/server/libjvm.dylib
__LINKEDIT             00000000103a1000-00000000105fe000 [ 2420K  2420K     0K     0K] r--/rwx SM=COW          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/lib/server/libjvm.dylib
Kernel Alloc Once      00000000105fe000-0000000010600000 [    8K     4K     4K     0K] rw-/rwx SM=PRV          
MALLOC metadata        0000000010600000-0000000010601000 [    4K     4K     4K     0K] r--/rwx SM=ZER          DefaultMallocZone_0x10600000 zone structure
MALLOC metadata        0000000010601000-0000000010602000 [    4K     4K     4K     0K] rw-/rwx SM=ZER          
MALLOC guard page      0000000010602000-0000000010603000 [    4K     0K     0K     0K] ---/rwx SM=ZER          
MALLOC metadata        0000000010603000-0000000010609000 [   24K    24K    24K     0K] rw-/rwx SM=ZER          
MALLOC guard page      0000000010609000-000000001060a000 [    4K     0K     0K     0K] ---/rwx SM=ZER          
MALLOC guard page      000000001060a000-000000001060b000 [    4K     0K     0K     0K] ---/rwx SM=NUL          
MALLOC metadata        000000001060b000-0000000010611000 [   24K    24K    24K     0K] rw-/rwx SM=PRV          
MALLOC guard page      0000000010611000-0000000010612000 [    4K     0K     0K     0K] ---/rwx SM=NUL          
MALLOC metadata        0000000010612000-0000000010613000 [    4K     4K     4K     0K] r--/rwx SM=PRV          
__TEXT                 0000000010613000-000000001061c000 [   36K    36K     0K     0K] r-x/rwx SM=COW          /Users/pdbain/vm/jdk8u181-b13/Contents/Home/jre/lib/libverify.dylib
```

**Comment by sxa555** [comment]
I will take a look at a prototype build of something suitable on the adoptopenjdk machines ...

**Comment by sxa555** [comment]
If anyone wants to pull a build from https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-build-macos-jdk11-LH/ and let me know if that solves anything (built with non compressed refs option) that would be appreciated

**Comment by pdbain-ibm** [comment]
That would be this build, right?
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201810251613)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-cca01361, JRE 11 Mac OS X amd64-64-Bit 20181025_1 (JIT enabled, AOT enabled)
OpenJ9   - cca01361
OMR      - 19d31aa4
JCL      - 88c0cee5e9 based on jdk-11.0.1+13)
```
If so, it is tested and working: Eclipse Version: 2018-09 (4.9.0) Build id: 20180917-1800 launches successfully and runs a simple program.  Many thanks @sxa555 !

**Comment by pdbain-ibm** [comment]
@martinlippert FYI ^^^

**Comment by martinlippert** [comment]
Yes, starts up now... :-)
THANKS!!!

Some strange error messages within my IDE coming up, but need to take a more detailed look at that, might be something completely unrelated.

**Comment by pdbain-ibm** [comment]
@martinlippert We are glad to help.  Please feel free to contact me directly on Slack at `openj9.slack.com`.

**Comment by martinlippert** [comment]
Looks like I need an invite for that slack workspace ?!? Can you send me one?

**Comment by AdamBrousseau** [comment]
https://join.slack.com/t/openj9/shared_invite/enQtNDU4MDI4Mjk0MTk2LWM2MjliMTQ4NWM5YjMwNTViOTgzMzM2ZDhlOWJmZTc1MjhmYmRjMDg2NDljNGM0YTAwOWRiZDE0YzI0NjgyOWI

(From the OpenJ9 Website)

**Comment by martinlippert** [comment]
btw, when running my Eclipse using this, I get a bunch of these exceptions:

`
java.io.FileNotFoundException
	at org.eclipse.jdt.internal.core.JavaModelManager.throwExceptionIfArchiveInvalid(JavaModelManager.java:2996)
	at org.eclipse.jdt.internal.core.JavaModelManager.getZipFile(JavaModelManager.java:2934)
	at org.eclipse.jdt.internal.core.JavaModelManager.getZipFile(JavaModelManager.java:2920)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.getJar(JarPackageFragmentRoot.java:264)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.computeChildren(JarPackageFragmentRoot.java:144)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.buildStructure(PackageFragmentRoot.java:163)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:268)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:267)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getModuleDescription(PackageFragmentRoot.java:888)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.getModuleDescription(JarPackageFragmentRoot.java:321)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.mapToClassPathLocation(JavaSearchNameEnvironment.java:188)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:134)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:78)
	at org.eclipse.jdt.internal.core.search.matching.IndexBasedJavaSearchEnvironment.create(IndexBasedJavaSearchEnvironment.java:334)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:169)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:94)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:552)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$1.execute(IndexManager.java:1063)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:401)
	at java.base/java.lang.Thread.run(Thread.java:825)
`

**Comment by martinlippert** [comment]
should I file a bug for JDT for that? or would you like to take this further (since it works when running with the Oracle JDK 11)

**Comment by martinlippert** [comment]
> https://join.slack.com/t/openj9/shared_invite/enQtNDU4MDI4Mjk0MTk2LWM2MjliMTQ4NWM5YjMwNTViOTgzMzM2ZDhlOWJmZTc1MjhmYmRjMDg2NDljNGM0YTAwOWRiZDE0YzI0NjgyOWI
> 
> (From the OpenJ9 Website)

Thanks for that, much appreciated !!!

**Comment by pdbain-ibm** [comment]
Further to 
https://github.com/eclipse/openj9/issues/3371#issuecomment-433416066
1. Which version of Eclipse are you using?
2. Under what conditions does the exception occur?

**Comment by pdbain-ibm** [comment]
@martinlippert Would you kindly close this issue and open another issue if you encounter further problems.  Thank you for bringing this to our attention.

**Comment by martinlippert** [comment]
I tried today again with the latest build from the nightlies and it doesn't work (starting up Eclipse). Is the solution to this in a special branch or a special build only? Or is there anything I need to do when using the latest from nightly?

**Comment by pdbain-ibm** [comment]
You will need to use a "large heap" version of the JDK, which I don't believe is available yet as a regular build.  @sxa555 I see https://github.com/AdoptOpenJDK/openjdk-build/issues/686 is closed, but I don't see any MacOS large heap builds.

**Comment by sxa555** [comment]
I think they're just being mislabelled - have opened https://github.com/AdoptOpenJDK/openjdk-build/issues/744 to resolve that.

**Comment by rubin55** [comment]
I just downloaded OpenJDK 8 OpenJ9 variant, release 202-b08 from here: https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9

$ java -version
```
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190130_136 (JIT enabled, AOT enabled)
OpenJ9   - 04890c300
OMR      - d2f4534b
JCL      - 6501440d7a based on jdk8u202-b08)
```

**Comment by JasonFengJ9** [comment]
@rubin55 could you try [MacOS x64 Large](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-30-04-38/OpenJDK11U-jdk_x64_mac_openj9_macosXL_2019-01-30-04-38.tar.gz)?

**Comment by rubin55** [comment]
I cannot run this particular instance of Eclipse with JDK 11; is there a JDK 8 version with large heap option?

**Comment by JasonFengJ9** [comment]
Not able to find **JDK 8** `MacOS x64 Large Heap` either.

@sxa555 any insights about availability of this particular build?

**Comment by JasonFengJ9** [comment]
Thanks quick actions at https://github.com/AdoptOpenJDK/openjdk-build/issues/892, [JDK 8 MacOS x64 Large Heap](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_mac_openj9_macosXL_8u202b08-openj9-0.12.1.tar.gz) is available now.

fyi @rubin55

**Comment by sxa555** [comment]
Yep all LH builds are now up - at the moment it needs a small about of manual tweaking to get it to show up properly after publishing.
