### ISSUE TITLE
MacOS: NPE in java.lang.Class.forNameImpl(Native Method) compiling non-compressedrefs

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#3382]
Following the standard recipe, but configuring for full 64-bit:
```
git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11
cd openj9-openjdk-jdk11/
bash ./get_source.sh 
bash ./configure --with-freemarker-jar=/Users/pdbain/lib/freemarker.jar --disable-ddr --with-noncompressedrefs --with-boot-jdk=/Users/pdbain/vm/jdk11/jdk
make all
```
Compiling 3053 files for java.base
Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:191)
    at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180)
    at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
    at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
    at java.desktop/java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
    at build.tools.icondata.awt.ToBin.main(ToBin.java:41)
Caused by: java.lang.NullPointerException
    at java.base/java.lang.Class.forNameImpl(Native Method)
    at java.base/java.lang.Class.forName(Class.java:340)
    at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
    at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
    ... 4 more 
```

**Comment by dmitripivkine** [comment]
Most likely corrupted heap. As we saw problem goes away with -Xint

**Comment by JasonFengJ9** [comment]
Running with `-Xint` avoids the GC crash though it stopped later with following:
```
java.lang.NoClassDefFoundError: javax.annotation.PreDestroy
        at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
        at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
        at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
        at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
        at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
        at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
        at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
        at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
        at org.eclipse.osgi.container.Module.doStop(Module.java:634)
        at org.eclipse.osgi.container.Module.stop(Module.java:498)
        at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
        at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
        ... 21 more
``` 
This is because `javax.annotation` doesn't present in `JDK11` default modules.

**Comment by JasonFengJ9** [comment]
`OpenJDK 11 b28` has same issue, i.e., can't launch either.

**Comment by JasonFengJ9** [comment]
`Eclipse` tested was:
```
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
```

**Comment by JasonFengJ9** [comment]
Probably need a newer Eclipse https://marketplace.eclipse.org/content/java-11-support-eclipse-2018-09-49.

**Comment by pdbain-ibm** [comment]
I switched to a newer build JDK: 
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)
```
and the compilation worked fine.
