### ISSUE TITLE
JTreg test fail : java/lang/invoke/modules/Driver.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3411]
Further to issue https://github.com/eclipse/openj9/issues/3301, test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/modules/Driver.java has these four failures where, this time, an IllegalAccessException is expected but not encountered ...

```
test p1.Main.testFromUnnamedToNamedModule(): failure
java.lang.AssertionError: expected [true] but found [false]
	at testng/org.testng.Assert.fail(Assert.java:94)
	at testng/org.testng.Assert.failNotEquals(Assert.java:496)
	at testng/org.testng.Assert.assertTrue(Assert.java:42)
	at testng/org.testng.Assert.assertTrue(Assert.java:52)
	at m1/p1.Main.findConstructorExpectingIAE(Main.java:350)
	at m1/p1.Main.testFromUnnamedToNamedModule(Main.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at testng/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at testng/org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at testng/org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at testng/org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at testng/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at testng/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at testng/org.testng.TestRunner.privateRun(TestRunner.java:773)
	at testng/org.testng.TestRunner.run(TestRunner.java:623)
	at testng/org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at testng/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at testng/org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at testng/org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at testng/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at testng/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at testng/org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at testng/org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at testng/org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

test p1.Main.testPublicLookupToAccessibleTypeInNamedModule(): failure
java.lang.AssertionError: expected [true] but found [false]
	at testng/org.testng.Assert.fail(Assert.java:94)
	at testng/org.testng.Assert.failNotEquals(Assert.java:496)
	at testng/org.testng.Assert.assertTrue(Assert.java:42)
	at testng/org.testng.Assert.assertTrue(Assert.java:52)
	at m1/p1.Main.findConstructorExpectingIAE(Main.java:350)
	at m1/p1.Main.testPublicLookupToAccessibleTypeInNamedModule(Main.java:275)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at testng/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at testng/org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at testng/org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at testng/org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at testng/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at testng/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at testng/org.testng.TestRunner.privateRun(TestRunner.java:773)
	at testng/org.testng.TestRunner.run(TestRunner.java:623)
	at testng/org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at testng/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at testng/org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at testng/org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at testng/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at testng/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at testng/org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at testng/org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at testng/org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

test p1.Main.testPublicLookupToBaseModule(): failure
java.lang.AssertionError: expected [true] but found [false]
	at testng/org.testng.Assert.fail(Assert.java:94)
	at testng/org.testng.Assert.failNotEquals(Assert.java:496)
	at testng/org.testng.Assert.assertTrue(Assert.java:42)
	at testng/org.testng.Assert.assertTrue(Assert.java:52)
	at m1/p1.Main.findConstructorExpectingIAE(Main.java:350)
	at m1/p1.Main.testPublicLookupToBaseModule(Main.java:257)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at testng/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at testng/org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at testng/org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at testng/org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at testng/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at testng/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at testng/org.testng.TestRunner.privateRun(TestRunner.java:773)
	at testng/org.testng.TestRunner.run(TestRunner.java:623)
	at testng/org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at testng/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at testng/org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at testng/org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at testng/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at testng/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at testng/org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at testng/org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at testng/org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

test p1.Main.testPublicLookupToUnnamedModule(): failure
java.lang.AssertionError: expected [true] but found [false]
	at testng/org.testng.Assert.fail(Assert.java:94)
	at testng/org.testng.Assert.failNotEquals(Assert.java:496)
	at testng/org.testng.Assert.assertTrue(Assert.java:42)
	at testng/org.testng.Assert.assertTrue(Assert.java:52)
	at m1/p1.Main.findConstructorExpectingIAE(Main.java:350)
	at m1/p1.Main.testPublicLookupToUnnamedModule(Main.java:333)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at testng/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at testng/org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at testng/org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at testng/org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at testng/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at testng/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at testng/org.testng.TestRunner.privateRun(TestRunner.java:773)
	at testng/org.testng.TestRunner.run(TestRunner.java:623)
	at testng/org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at testng/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at testng/org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at testng/org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at testng/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at testng/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at testng/org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at testng/org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at testng/org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Test passes against Hotspot.

Log archive : [DriverProb.tar.gz](https://github.com/eclipse/openj9/files/2505728/DriverProb.tar.gz)

**Comment by pdbain-ibm** [comment]
@tajila I will investigate.

**Comment by pdbain-ibm** [comment]
Testcase `testFromUnnamedToNamedModule()` creates a generic `Lookup` via `MethodHandles.lookup()`, then calls `privateLookupIn()` with the first `Lookup` and `p1.Type1` from the unnamed module, returning another `Lookup`.  It then invokes the `in()` method on the second `Lookup` with a class in the current (named) module to get a third `Lookup`. It then does a lookup using the final `Lookup` on `p2.Type2` in the same module, expecting an `IllegalAccessException` `not accessible: class p2.Type2, from p1.Type1/public (module m1)`.

**Comment by pdbain-ibm** [comment]
For the record, from `Lookup.in()` javadoc:
>However, the resulting Lookup object is guaranteed to have no more access capabilities than the original. In particular, access capabilities can be lost as follows:
- _If the old lookup class is in an unnamed module, and the new lookup class is a different module then MODULE access is lost._

**Comment by pdbain-ibm** [comment]
@DanHeidinga or @tajila could you clarify the effect of the `Lookup.MODULE` bit?  The `Lookup` javadoc says 

> In conjunction with the PUBLIC modifier bit, a Lookup with this lookup mode can access all public types in the module of the lookup class and public types in packages exported by other modules to the module of the lookup class.

If the `MODULE` bit is cleared, does that mean there is no access to _any_ methods in any named module, even that of the lookup class?

**Comment by pdbain-ibm** [comment]
I tested with the reference implementation:
```
Lookup lookup = MethodHandles.lookup().dropLookupMode(MODULE);
...
lookup.findConstructor(clazz, mt);
```
throws IAE on classes in the same module but different package; no exception on same module & package.

**Comment by DanHeidinga** [comment]
Good find @pdbain-ibm!  The use of the module bit is also missing in https://github.com/eclipse/openj9/issues/3047

**Comment by pdbain-ibm** [comment]
I am running a personal build now and will open a pull request.

**Comment by pdbain-ibm** [comment]
@ben-walsh FYI.

**Comment by smlambert** [comment]
Test was excluded via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/666 
If this issue has been fixed, it should get re-included.

FYI @ben-walsh
