### ISSUE TITLE
Multiple Crashes Running Eclipse

### ISSUE THREAD

**Issue by tsmaeder** [eclipse/openj9#3469]
I recently tried running Eclipse Photon on the latest jdk 8 build from AdoptOpenJDK. Within an hour, I crashed repeatedly with the attached core dumps. Version is: 

```./java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b12)
Eclipse OpenJ9 VM (build openj9-0.11.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181019_64 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - 51609250b5 based on jdk8u192-b12)```

**Comment by tsmaeder** [comment]
[javacore.20181024.141603.1841.0002.txt](https://github.com/eclipse/openj9/files/2526021/javacore.20181024.141603.1841.0002.txt)
[javacore.20181024.165654.2162.0002.txt](https://github.com/eclipse/openj9/files/2526022/javacore.20181024.165654.2162.0002.txt)
[javacore.20181024.170302.24920.0002.txt](https://github.com/eclipse/openj9/files/2526025/javacore.20181024.170302.24920.0002.txt)

**Comment by tsmaeder** [comment]
[jitdump.20181024.zip](https://github.com/eclipse/openj9/files/2526033/jitdump.20181024.zip)

**Comment by charliegracie** [comment]
I took a quick look at the javacore files.  All 3 of the crashes had similar stack traces:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at sun/misc/Unsafe.getByte(Native Method)
4XESTACKTRACE                at java/nio/DirectByteBuffer.get(DirectByteBuffer.java:252(Compiled Code))
4XESTACKTRACE                at java/nio/ByteBuffer.get(ByteBuffer.java:691)
4XESTACKTRACE                at java/nio/DirectByteBuffer.get(DirectByteBuffer.java:288(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/ByteBufferWindow.setInput(ByteBufferWindow.java:100(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/ByteWindow.setInput(ByteWindow.java:137(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/WindowCursor.inflate(WindowCursor.java:315(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/PackFile.decompress(PackFile.java:367(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/PackFile.load(PackFile.java:791(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/PackFile.get(PackFile.java:285(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/ObjectDirectory.openPackedObject(ObjectDirectory.java:486(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:444(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/ObjectDirectory.openObject(ObjectDirectory.java:435(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/internal/storage/file/WindowCursor.open(WindowCursor.java:165(Compiled Code))
4XESTACKTRACE                at org/eclipse/jgit/treewalk/CanonicalTreeParser.reset(CanonicalTreeParser.java:224(Compiled Code))
.....
```

**Comment by charliegracie** [comment]
Hi @tsmaeder as a quick check while I am trying to reproduce locally could you add the following command line options and see if it still fails? `-Xjit:exclude={java/nio/*},dontInline={java/nio/*}`

**Comment by fjeremic** [comment]
@liqunl FYI this is in your domain.

**Comment by liqunl** [comment]
@tsmaeder Other than the javacore, is there a system core dump? Another thing you can try is `-Xjit:{java/nio/*}(disableUnsafe)`

**Comment by tsmaeder** [comment]
@liqunl sorry, this is kinda low on my priority list :-( Will try...

**Comment by tsmaeder** [comment]
[javacore.20181108.141219.20950.0002.txt](https://github.com/eclipse/openj9/files/2561890/javacore.20181108.141219.20950.0002.txt)

**Comment by DanHeidinga** [comment]
Looking at the stacktrace, there are a number of `org/eclipse/jgit/internal/storage/file/*` classe like `ByteBufferWindow`.  Do these classes have a reference to the ByteBuffer?  Are any of them finalizable?

If you can share the system corefile, we can check some of these things using the `jdmpview` tool and may be able to help debug this faster.

**Comment by keithc-ca** [comment]
This happened to me twice this morning as I was trying to start eclipse. I have core files: how should I share them?

**Comment by keithc-ca** [comment]
I was using Java 11:
```
java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.keithc.jdk11)
Eclipse OpenJ9 VM (build master-1b94665, JRE 11 Linux amd64-64-Bit Compressed References 20181031_000000 (JIT enabled, AOT enabled)
OpenJ9   - 1b94665
OMR      - 47ec570
JCL      - 19de80e based on jdk-11.0.1+13)
```

**Comment by liqunl** [comment]
I got the core from @keithc-ca and am investigating the jitted code to see if anything's wrong from the jit side.

**Comment by liqunl** [comment]
I have looked at jitted code in the top 4 frames, didn't find anything wrong. I suspect it's a vm issue. Notice that `java/nio/ByteBuffer.get` is intepreted, so I didn't go any further.
```
 3946 4XESTACKTRACE                at jdk/internal/misc/Unsafe.getByte(Native Method)
 3947 4XESTACKTRACE                at jdk/internal/misc/Unsafe.getByte(Unsafe.java:1016(Compiled Code))
 3948 4XESTACKTRACE                at java/nio/DirectByteBuffer.get(DirectByteBuffer.java:267(Compiled Code))
 3949 4XESTACKTRACE                at java/nio/ByteBuffer.get(ByteBuffer.java:738)
```

**Comment by JamesKingdon** [comment]
If that's a gpf from memory that appears readable in the core, chances are the DBB has been unmapped. I've never seen this happen in the org.eclipse packages before though.

**Comment by pshipton** [comment]
fyi that @keithc-ca ran Eclipse with -Xint and reproduced the crash.

**Comment by charliegracie** [comment]
@keithc-ca would it be possible to reproduce with `-Xverbosegclog:<filename>` and provide the GC log?

**Comment by keithc-ca** [comment]
I'll give that a spin later today after I'm in the office.

**Comment by keithc-ca** [comment]
I ran with `-Xverbosegclog` all day today: no crashes yet.

**Comment by keithc-ca** [comment]
Still waiting for a crash with `-Xverbosegclog`...

**Comment by pshipton** [comment]
@keithc-ca  you could try again with -Xint and -Xverbosegclog

**Comment by charliegracie** [comment]
I will take a look at the logs tomorrow morning.  Would it also be possible to try with JNI check to make sure there isn’t some obvious JNI issue lurking?

**Comment by gacholio** [comment]
Thomas (hi!), please try adding this option to the command line:

`-Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo`

This will put the VM into debug mode which uses different liveness analysis, which may alleviate any errors in the DBB code.

**Comment by charliegracie** [comment]
To further on @gacholio 's comments if this resolves your issue we can prototype a change quickly that would likely resolve the issue without any extra command line options :)

**Comment by JamesKingdon** [comment]
I'm curious - we think the objects may be getting collected prematurely?

**Comment by gacholio** [comment]
The get() pattern is essentially:

```
public byte get() {
 return unsafe.getByte(something(this.address));
}
```

As soon as address is fetched, the receiver is unreachable and available for finalization. If the chain is not fully inlined (always true when running -Xint), there's a GC point at the beginning of `something`, which allows the DBB to be collected and finalized, which means the backing memory is freed.

**Comment by DanHeidinga** [comment]
I've opened https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/212 as a first pass to add the missing keepAlive calls.  I've matched them to the ones we had added to JDK11 and using the same pattern.

**Comment by JamesKingdon** [comment]
Many thanks for the explanation.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/212 is merged.

**Comment by DanHeidinga** [comment]
@tsmaeder Does the issue still occur with the latest AdoptOpenJDK OpenJ9 nightly builds?

**Comment by keithc-ca** [comment]
Note that the gc log I captured was from running Java 11:
```
$ /home/keithc/opt/openj9-11.0.1+13/bin/java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.keithc.jdk11)
Eclipse OpenJ9 VM (build master-1b94665, JRE 11 Linux amd64-64-Bit Compressed References 20181031_000000 (JIT enabled, AOT enabled)
OpenJ9   - 1b94665
OMR      - 47ec570
JCL      - 19de80e based on jdk-11.0.1+13)
```
so if we're on the right track, there are some missing uses of `Bits.keepAlive()` in newer versions too.

**Comment by DanHeidinga** [comment]
@keithc-ca Do you have the core files from the crashes still?

**Comment by DanHeidinga** [comment]
We've been using adhoc methods for sharing binaries so far.  Can you upload to Box and share a link (privately is fine)?

**Comment by keithc-ca** [comment]
cores-3469.tar.gz -> https://ibm.box.com/s/3chwbvqsrlxvt0gcaxech26anwt6bi7s

**Comment by dsouzai** [comment]
Has this been resolved or does it still need to remain open?

**Comment by NagarajuGunda** [comment]
> The get() pattern is essentially:
> 
> ```
> public byte get() {
>  return unsafe.getByte(something(this.address));
> }
> ```
> 
> As soon as address is fetched, the receiver is unreachable and available for finalization. If the chain is not fully inlined (always true when running -Xint), there's a GC point at the beginning of `something`, which allows the DBB to be collected and finalized, which means the backing memory is freed.

I am facing similar problem of GC prematurely collecting the objects while they are still referenced. Was this ever fixed into 8.x versions?
