### ISSUE TITLE
JTreg test fail : java/net/HttpURLConnection/SetAuthenticator/HTTPSetAuthenticatorTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3568]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/HttpURLConnection/SetAuthenticator/HTTPSetAuthenticatorTest.java is behaving inconsistently ...

Sometimes (3 out of 10 consecutive test runs) the following failure is encountered ...

```
java.lang.AssertionError: Authenticator #2 called twice expected it to be called once
	at HTTPSetAuthenticatorTest.run(HTTPSetAuthenticatorTest.java:148)
	at HTTPTest.test(HTTPTest.java:204)
	at HTTPTest.test(HTTPTest.java:178)
	at HTTPTest$$Lambda$49.000000007823EF40.accept(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at HTTPTest.execute(HTTPTest.java:171)
	at HTTPSetAuthenticatorTest.main(HTTPSetAuthenticatorTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Example log archive from such a failure run : [HTTPSetAuthenticatorTestFailure.tar.gz](https://github.com/eclipse/openj9/files/2553748/HTTPSetAuthenticatorTestFailure.tar.gz)

Example log archive from successful run : [HTTPSetAuthenticatorTestSuccess.tar.gz](https://github.com/eclipse/openj9/files/2553749/HTTPSetAuthenticatorTestSuccess.tar.gz)

This intermittent failure has not been encountered when running against Hotspot.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/672

**Comment by adam-thorpe** [comment]
Test now seems to be passing, so this is being un-excluded and this can be closed
