### ISSUE TITLE
jit_tr_0 failed with NullPointerException  in JITaaS JDK8 build

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3630]
**java -version**
```
00:15:57.546 "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/java" -version
00:15:57.546 java version "1.8.0"
00:15:57.546 Java(TM) SE Runtime Environment (build 1.8.0-foreman_2018_10_22_11_55-b00)
00:15:57.546 IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181103_401303 (JIT enabled, AOT enabled)
00:15:57.546 OpenJ9   - 29bd9e6
00:15:57.546 OMR      - 942d987
00:15:57.546 IBM      - 5c4a9f0)
```

**test results**
NullPointerException is thrown from TestNG at the end of each test group in `jit_tr_0`. TestNG output has both PASSED and FAILED for the same test.

```
PASSED: test012
PASSED: test013
PASSED: test014
PASSED: test015
FAILED: test015
java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeAfterGroupsConfigurations(Invoker.java:804)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    NewInstanceTest
    Tests run: 16, Failures: 1, Skips: 0
===============================================

PASSED: testAddressElim
PASSED: testOverflow
PASSED: testUseri2l
FAILED: testUseri2l
java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeAfterGroupsConfigurations(Invoker.java:804)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    signExtensionATest
    Tests run: 4, Failures: 1, Skips: 0
===============================================
...
```

fyi @mpirvu @harryyu1994

**Comment by harryyu1994** [comment]
@mpirvu verified that this one is fixed.

**Comment by mpirvu** [comment]
Thanks. Closing.
