### ISSUE TITLE
cmdLineTest: cmdLineTester_getCallerClassTests `java.lang.NoSuchMethodException: sun.reflect.Reflection.getCallerClass()`

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#364]
cmdLineTester_getCallerClassTests will get unexpected exception during execution `java.lang.NoSuchMethodException: sun.reflect.Reflection.getCallerClass()`

To re-enable this test, remove `getCallerClassTests` in `/test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl`

java -version:
```
root@1c569afa5e3e:/test/TestConfig# /java/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171011_366953 (JIT enabled, AOT enabled)
OpenJ9   - 26f4ca3
OMR      - 5d625a3
OpenJDK  - a4765a5 based on jdk-9+181)
```

Test error message output:
```
Testing: call APIs with/without @CallerSensitive annotation from the bootstrap classloader
Test start time: 2017/10/17 18:41:49 Coordinated Universal Time
Running command: "/java/bin/java"  -Xcompressedrefs  -Xdump --add-exports=java.base/com.ibm.oti.vm=ALL-UNNAMED --add-exports java.base/jdk.internal.reflect=ALL-UNNAMED -Xbootclasspath/a:/test/TestConfig/../../jvmtest/cmdline_options_testresources/cmdlinetestresources.jar com.ibm.j9.getcallerclass.TestGroup bootClassLoader
Time spent starting: 4 milliseconds
Time spent executing: 438 milliseconds
Test result: FAILED
Output from test:
 [OUT] test_getCallerClass_fromBootExtWithAnnotation: PASSED
 [OUT] test_ensureCalledFromBootstrapClass_fromBootWithAnnotation: PASSED
 [OUT] test_getCallerClass_Helper_Reflection_fromBootExtWithAnnotation: PASSED: return com.ibm.j9.getcallerclass.RefectionMHTests
 [OUT] test_getCallerClass_Direct_Reflection_fromBootExtClassLoader: FAILED 3
 [OUT] test_getCallerClass_Helper_MethodHandle_fromBootExtWithAnnotation: PASSED: return java.lang.invoke.SecurityFrame
 [OUT] test_getCallerClass_Direct_MethodHandle_fromBootExtClassLoader: FAILED 2
 [OUT] test_getCallerClass_MethodHandle_ArgumentHelper: PASSED: return java.lang.invoke.SecurityFrame
 [OUT] test_getCallerClass_fromBootExtWithoutAnnotation: PASSED
 [OUT] test_ensureCalledFromBootstrapClass_fromBootExtWithoutAnnotation: PASSED
 [ERR] java.lang.NoSuchMethodException: sun.reflect.Reflection.getCallerClass()
 [ERR] 	at java.lang.Class.newNoSuchMethodException(java.base@9-internal/Class.java:585)
 [ERR] 	at java.lang.Class.throwExceptionOrReturnNull(java.base@9-internal/Class.java:1270)
 [ERR] 	at java.lang.Class.getMethodHelper(java.base@9-internal/Class.java:1332)
 [ERR] 	at java.lang.Class.getDeclaredMethod(java.base@9-internal/Class.java:1027)
 [ERR] 	at com.ibm.j9.getcallerclass.RefectionMHTests.test_getCallerClass_Direct_Reflection_fromBootExtClassLoader(RefectionMHTests.java:74)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.fromBootClassLoader(TestGroup.java:80)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.classLoaderTest(TestGroup.java:47)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.main(TestGroup.java:36)
 [ERR] java.lang.NoSuchMethodException: sun/reflect/Reflection.getCallerClass()Ljava/lang/Class; (loaded from jrt:/jdk.unsupported by <Bootstrap Loader>) called from class java.lang.invoke.PrimitiveHandle (loaded from jrt:/java.base by <Bootstrap Loader>).
 [ERR] 	at java.lang.invoke.PrimitiveHandle.finishMethodInitialization(java.base@9-internal/PrimitiveHandle.java:202)
 [ERR] 	at java.lang.invoke.DirectHandle.<init>(java.base@9-internal/DirectHandle.java:51)
 [ERR] 	at java.lang.invoke.DirectHandle.<init>(java.base@9-internal/DirectHandle.java:43)
 [ERR] 	at java.lang.invoke.MethodHandles$Lookup.findStatic(java.base@9-internal/MethodHandles.java:538)
 [ERR] 	at com.ibm.j9.getcallerclass.RefectionMHTests.test_getCallerClass_Direct_MethodHandle_fromBootExtClassLoader(RefectionMHTests.java:142)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.fromBootClassLoader(TestGroup.java:82)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.classLoaderTest(TestGroup.java:47)
 [ERR] 	at com.ibm.j9.getcallerclass.TestGroup.main(TestGroup.java:36)
>> Success condition was not found: [Output match: All Tests Completed and Passed]
>> Failure condition was found: [Output match: FAILED]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: corrupt]
>> Failure condition was not found: [Output match: Processing dump event]
>> Failure condition was not found: [Output match: JVM requested Java dump]
>> Failure condition was not found: [Output match: JVM requested Snap dump]```

**Comment by DanHeidinga** [comment]
```
com.ibm.j9.getcallerclass.RefectionMHTests.test_getCallerClass_Direct_MethodHandle_fromBootExtClassLoader(RefectionMHTests.java:142)
```
@TianyuZuo On Java 9, that method should be looking up a different MH.  `sun.reflect.Reflection` was renamed to `jdk.internal.reflect.Reflection`

**Comment by TianyuZuo** [comment]
thanks for help, will update the test src
