### ISSUE TITLE
Remove workaround for Java 12 in java.lang.Access.defineClass()

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#3641]
https://github.com/eclipse/openj9/pull/3638 introduces a workaround that should be removed. Ideally the behavior of that method should be the same for all versions of Java.

**Comment by pshipton** [comment]
@keithc-ca what is the next step to remove the workaround?

**Comment by DanHeidinga** [comment]
@keithc-ca Can you point to examples of why the work around was required?  We're running out of time to have this sorted for 0.13.0

**Comment by keithc-ca** [comment]
Creating a `jmod` fails without the workaround because the validation done by `ClassLoader.defineClass` fails for class names containing `/`:
```
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedMethodAccessor1
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:470)
	at java.base/java.lang.Access.defineClass(Access.java:244)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:65)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.lang.Class.copyConstructors(Class.java:4155)
	at java.base/java.lang.Class.cacheConstructors(Class.java:4199)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:859)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory$1.run(InnerClassLambdaMetafactory.java:194)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory$1.run(InnerClassLambdaMetafactory.java:191)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:190)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1116)
	at java.base/java.util.stream.Collectors.toMap(Collectors.java:1459)
	at java.base/jdk.internal.jmod.JmodFile$Entry.<clinit>(JmodFile.java:161)
	at java.base/jdk.internal.jmod.JmodFile.lambda$stream$0(JmodFile.java:231)
	at jdk.internal.jmod.JmodFile$$Lambda$58.00000000544E6BE0.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:572)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at java.base/jdk.internal.module.ModulePath.jmodPackages(ModulePath.java:379)
	at java.base/jdk.internal.module.ModulePath.lambda$readJMod$1(ModulePath.java:393)
	at jdk.internal.module.ModulePath$$Lambda$54.00000000544E4E40.get(Unknown Source)
	at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:305)
	at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:131)
	at java.base/jdk.internal.module.ModulePath.readJMod(ModulePath.java:393)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:341)
	at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:282)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:230)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:188)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:164)
	at java.base/java.lang.module.ModuleFinder$2.lambda$findAll$2(ModuleFinder.java:368)
	at java.lang.module.ModuleFinder$2$$Lambda$51.00000000540E3F30.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.lang.module.ModuleFinder$2.findAll(ModuleFinder.java:369)
	at jdk.jlink/jdk.tools.jmod.JmodTask$Hasher.<init>(JmodTask.java:874)
	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.computeHashes(JmodTask.java:654)
	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.writeModuleInfo(JmodTask.java:585)
	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.write(JmodTask.java:481)
	at jdk.jlink/jdk.tools.jmod.JmodTask.create(JmodTask.java:438)
	at jdk.jlink/jdk.tools.jmod.JmodTask.run(JmodTask.java:208)
	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)
make[3]: *** [/home/keithc/space/openj9/jdk12/build/linux-x86_64-server-release/images/jmods/java.base.jmod] Error 1
```

**Comment by keithc-ca** [comment]
`java.lang.Access` must be less stringent than `ClassLoader`, but more so than `Unsafe`.

**Comment by keithc-ca** [comment]
It can be triggered more easily with `sun.reflect.inflationThreshold=0`:
```
$ ./jdk/bin/java -Dsun.reflect.inflationThreshold=0 -version
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/internal/reflect/GeneratedMethodAccessor1
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:470)
	at java.base/java.lang.Access.defineClass(Access.java:240)
	at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:65)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.lang.Class.cacheMethod(Class.java:3907)
	at java.base/java.lang.Class.getMethodHelper(Class.java:1470)
	at java.base/java.lang.Class.getMethod(Class.java:1341)
	at java.base/java.lang.Class$5.run(Class.java:2982)
	at java.base/java.lang.Class$5.run(Class.java:2979)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:2989)
	at java.base/java.lang.Access.getEnumConstantsShared(Access.java:91)
	at java.base/java.util.EnumSet.getUniverse(EnumSet.java:406)
	at java.base/java.util.EnumSet.noneOf(EnumSet.java:109)
	at java.base/java.util.EnumSet.of(EnumSet.java:283)
	at java.base/com.ibm.tools.attach.target.IPC.<clinit>(IPC.java:65)
	at java.base/com.ibm.tools.attach.target.AttachHandler.initializeAttachAPI(AttachHandler.java:131)
```

**Comment by keithc-ca** [comment]
I have what appears to be a workable solution to this. At a very high level, it involves making note (in RAM classes) whether they extend `MagicAccessorImpl` which says:

> All subclasses of this class are "magically" granted access by the VM to otherwise
> inaccessible fields and methods of other classes.

Classes defined via `Unsafe` API will continue to be exempt from access validation.
