### ISSUE TITLE
Test-sanity.system-JDK11-linux_390-64_cmprssptrs TestJlmRemoteXX failures due to Exiting as JVM we are connected to has finished

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#3651]
TestJlmRemoteClassNoAuth_0
```
STF 05:58:25.010 - **FAILED** Process LT1 has ended unexpectedly
STF 05:58:25.010 - Monitoring Report Summary:
STF 05:58:25.010 -   o Process CL1 is still running
STF 05:58:25.010 -   o Process LT1 has ended unexpectedly
STF 05:58:25.010 - Killing processes: CL1 LT1
STF 05:58:26.011 -   o Process CL1 killed
CL1 ............................j> 2018/11/13 05:58:25.049 Exiting as JVM we are connected to has finished
CL1 stderr Exception in thread "main" java.lang.AssertionError: Exiting as JVM we are connected to has finished
CL1 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:179)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
STF 05:58:26.011 -   o Process LT1 is not running
**FAILED** at step 3 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test-sanity.system-JDK11-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15420882026166/TestJlmRemoteClassNoAuth_0/20181113-055325-TestJlmRemoteClassNoAuth/execute.pl line 158.
STF 05:58:26.355 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

Similar failures at `TestJlmRemoteMemoryAuth_0` and `TestJlmRemoteMemoryNoAuth_0`.

**Comment by pshipton** [comment]
I  haven't seen this occur in the build, assuming fixed.
