### ISSUE TITLE
Test-sanity.functional-JDK11-win_x86-64_cmprssptrs gccheck failure: U64 contains value larger than Long.MAX_VALUE

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#3652]
```
Testing: Run gccheck
Test start time: 2018/11/13 07:15:45 Greenwich Mean Time
Running command: "C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\\java" -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  --add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED -cp C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\..\lib\ddr\j9ddr.jar;C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\functional\cmdline_options_testresources\cmdlinetestresources.jar;C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\functional\IBM_Internal\cmdLineTests_IBM_Internal\gcCheck\caffeine.jar com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive j9core.dmp
Time spent starting: 15 milliseconds
Time spent executing: 2822 milliseconds
Test result: FAILED
Output from test:
 [OUT] *0 : PID: 75688;  !j9javavm 0x239492a6d0
 [OUT] Run !j9help to see a list of commands
 [OUT] > Starting GC Check
 [OUT] Checking HEAP...Problem running command:
 [OUT] U64 contains value larger than Long.MAX_VALUE
 [OUT] > Quitting...
>> Success condition was not found: [Output match: Checking HEAP...done]
>> Failure condition was not found: [Output match: gc check]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: Exception]
```

**Comment by pshipton** [comment]
@JasonFengJ9 on what sha's did the problem occur?

@keithc-ca fyi

**Comment by keithc-ca** [comment]
Do we have the core file so this could be run manually (with additional details logged)?

**Comment by JasonFengJ9** [comment]
@pshipton the jvm in question is:
```
01:41:00  [ERR] Eclipse OpenJ9 VM (build ibm_sdk-1a697d7265, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20181113_257 (JIT enabled, AOT enabled)
01:41:00  [ERR] OpenJ9   - 1a697d7265
01:41:00  [ERR] OMR      - 220b9ed5
01:41:00  [ERR] JCL      - 358ac0fdee based on jdk-11.0.1+13)
```

**Comment by keithc-ca** [comment]
After enabling more logging detail:
```
> log j9ddr.interactive.context FINE
```
we see:
```
> !gccheck
Starting GC Check
Checking HEAP...Nov 13, 2018 2:19:30 PM com.ibm.j9ddr.tools.ddrinteractive.Context tryCommand
FINE: Problem running command:
com.ibm.j9ddr.InvalidDataTypeException: U64 contains value larger than Long.MAX_VALUE
    at com.ibm.j9ddr.vm29.types.U64.longValue(U64.java:115)
    at com.ibm.j9ddr.vm29.types.Scalar.eq(Scalar.java:106)
    at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorMarkMapIterator_V1.recacheMarkMapWord(GCObjectHeapIteratorMarkMapIterator_V1.java:146)
    at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorMarkMapIterator_V1.hasNext(GCObjectHeapIteratorMarkMapIterator_V1.java:168)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckObjectHeap.check(CheckObjectHeap.java:54)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:469)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:60)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:47)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:385)
    at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:360)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:819)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:773)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:747)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:671)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
    at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
```
