### ISSUE TITLE
Test-extended.system-JDK11-linux_x86-64 DaaLoadTest_all_ConcurrentScavenge_0 testConvertBigIntegerNormals NullPointerException 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3690]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/80
```
DLT testFailure: testConvertBigIntegerNormals(net.openj9.test.decimals.TestDecimalData): null
DLT java.lang.NullPointerException
DLT 	at org.junit.Assert.isEquals(Assert.java:131)
DLT 	at org.junit.Assert.equalsRegardingNull(Assert.java:127)
DLT 	at org.junit.Assert.assertEquals(Assert.java:111)
DLT 	at org.junit.Assert.assertEquals(Assert.java:144)
DLT 	at net.openj9.test.decimals.TestDecimalData.testConvertBigIntegerNormals(TestDecimalData.java:4953)
DLT 	at jdk.internal.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
DLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
DLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
DLT 	at java.base/java.lang.Thread.run(Thread.java:825)
```

**Comment by pshipton** [comment]
@dmitripivkine @0dvictor fyi

not sure if this is related to #3582

**Comment by dmitripivkine** [comment]
I looked to these failures. Most of them looks like https://github.com/eclipse/openj9/issues/3491
However there are failures looks different (but might still be the by same reason) - the problematic values referred from "temporary" slots of j9vmthread (returnValue2 and floatTemp1). These slots are not GC roots so it might refer to missed Read Barrier somewhere... or mean nothing. I am going to run grinder with -Xint in attempt to verify that GC changes is unrelated. If it is a case we need to wait until https://github.com/eclipse/openj9/issues/3491 is fixed

**Comment by pshipton** [comment]
This hasn't re-occurred, assuming fixed.
