### ISSUE TITLE
Error cloning remote repo 'origin' on AIX

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3729]
https://ci.eclipse.org/openj9/job/Build-JDK8-aix_ppc-64_cmprssptrs/742/console
https://ci.eclipse.org/openj9/job/Build-JDK8-aix_ppc-64_cmprssptrs/741/console

both occurred on aix71-p8-4

```
00:27:24 Cloning the remote Git repository
00:27:24 ERROR: Error cloning remote repo 'origin'
00:27:24 hudson.plugins.git.GitException: java.io.IOException: Remote call on aix71-p8-4 failed
00:27:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:169)
00:27:24 	at sun.reflect.GeneratedMethodAccessor932.invoke(Unknown Source)
00:27:24 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:27:24 	at java.lang.reflect.Method.invoke(Method.java:498)
00:27:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
00:27:24 	at com.sun.proxy.$Proxy93.execute(Unknown Source)
00:27:24 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
00:27:24 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
00:27:24 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
00:27:24 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
00:27:24 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
00:27:24 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
00:27:24 	at hudson.security.ACL.impersonate(ACL.java:290)
00:27:24 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
00:27:24 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:27:24 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:27:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:27:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:27:24 	at java.lang.Thread.run(Thread.java:748)
00:27:24 Caused by: java.io.IOException: Remote call on aix71-p8-4 failed
00:27:24 	at hudson.remoting.Channel.call(Channel.java:961)
00:27:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
00:27:24 	... 18 more
00:27:24 Caused by: java.lang.NoClassDefFoundError: jenkins.model.Jenkins (initialization failure)
00:27:24 	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96)
00:27:24 	at hudson.console.ConsoleNote.encodeToBytes(ConsoleNote.java:193)
00:27:24 	at hudson.console.ConsoleNote.encode(ConsoleNote.java:211)
00:27:24 	at hudson.plugins.timestamper.TimestampNotesOutputStream.eol(TimestampNotesOutputStream.java:70)
00:27:24 	at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
00:27:24 	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
00:27:24 	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:74)
00:27:24 	at java.io.PrintStream.write(PrintStream.java:480)
00:27:24 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
00:27:24 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
00:27:24 	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
00:27:24 	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
00:27:24 	at java.io.PrintStream.newLine(PrintStream.java:546)
00:27:24 	at java.io.PrintStream.println(PrintStream.java:807)
00:27:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:567)
00:27:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
00:27:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
00:27:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
00:27:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
00:27:24 	at hudson.remoting.Request$2.run(Request.java:369)
00:27:24 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
00:27:24 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:27:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:27:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:27:24 	at java.lang.Thread.run(Thread.java:813)
00:27:24 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to aix71-p8-4
00:27:24 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
00:27:24 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
00:27:24 		at hudson.remoting.Channel.call(Channel.java:955)
00:27:24 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
00:27:24 		at sun.reflect.GeneratedMethodAccessor932.invoke(Unknown Source)
00:27:24 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:27:24 		at java.lang.reflect.Method.invoke(Method.java:498)
00:27:24 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
00:27:24 		at com.sun.proxy.$Proxy93.execute(Unknown Source)
00:27:24 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
00:27:24 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
00:27:24 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
00:27:24 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
00:27:24 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
00:27:24 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
00:27:24 		at hudson.security.ACL.impersonate(ACL.java:290)
00:27:24 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
00:27:24 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:27:24 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:27:24 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:27:24 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:27:24 		at java.lang.Thread.run(Thread.java:748)
00:27:24 Caused by: com.thoughtworks.xstream.InitializationException: Could not instantiate converter : com.thoughtworks.xstream.converters.extended.DurationConverter : null
00:27:24 	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:904)
00:27:24 	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:867)
00:27:24 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
00:27:24 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
00:27:24 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
00:27:24 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
00:27:24 	at com.thoughtworks.xstream.XStream.<init>(XStream.java:378)
00:27:24 	at hudson.util.XStream2.<init>(XStream2.java:113)
00:27:24 	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5178)
00:27:24 	at hudson.model.Computer.<clinit>(Computer.java:1768)
00:27:24 	at hudson.util.ProcessTree.get(ProcessTree.java:399)
00:27:24 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1096)
00:27:24 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1087)
00:27:24 	... 8 more
00:27:24 Caused by: java.lang.reflect.InvocationTargetException
00:27:24 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:27:24 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:27:24 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:27:24 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
00:27:24 	at com.thoughtworks.xstream.XStream.registerConverterDynamically(XStream.java:897)
00:27:24 	... 20 more
00:27:24 Caused by: hudson.remoting.RemotingSystemException: java.lang.InterruptedException
00:27:24 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:299)
00:27:24 	at com.sun.proxy.$Proxy5.getResources2(Unknown Source)
00:27:24 	at hudson.remoting.RemoteClassLoader.findResources(RemoteClassLoader.java:481)
00:27:24 	at java.lang.ClassLoader.getResources(ClassLoader.java:664)
00:27:24 	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
00:27:24 	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
00:27:24 	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
00:27:24 	at javax.xml.datatype.FactoryFinder$1.run(FactoryFinder.java:296)
00:27:24 	at java.security.AccessController.doPrivileged(AccessController.java:640)
00:27:24 	at javax.xml.datatype.FactoryFinder.findServiceProvider(FactoryFinder.java:292)
00:27:24 	at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:268)
00:27:24 	at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:145)
00:27:24 	at com.thoughtworks.xstream.converters.extended.DurationConverter$1.getFactory(DurationConverter.java:39)
00:27:24 	at com.thoughtworks.xstream.converters.extended.DurationConverter.<init>(DurationConverter.java:36)
00:27:24 	... 25 more
00:27:24 Caused by: java.lang.InterruptedException
00:27:24 	at java.lang.Object.wait(Native Method)
00:27:24 	at java.lang.Object.wait(Object.java:218)
00:27:24 	at hudson.remoting.Request.call(Request.java:177)
00:27:24 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:286)
00:27:24 	... 38 more
```

**Comment by pshipton** [comment]
The restart seems to be running fine, at least it got past the clone, on aix71-p8-2

**Comment by jdekonin** [comment]
Machine cleaned up and reset.
