### ISSUE TITLE
ContendedFieldsTests failed on osx jdk11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3777]
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/6/tapResults/

```
00:21:58.573 + build/macosx-x86_64-normal-server-release/images/jdk/bin/java -version
00:21:58.574 openjdk version "11.0.1-internal" 2018-10-16
00:21:58.574 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.PullRequest-Extended-JDK11-osxx86-64cmprssptrs-OpenJ9)
00:21:58.574 Eclipse OpenJ9 VM (build HEAD-29f39b9d5, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181120_6 (JIT enabled, AOT enabled)
00:21:58.574 OpenJ9   - 29f39b9d5
00:21:58.574 OMR      - 1b8bfbae
00:21:58.574 JCL      - 2fbed1f42df based on jdk-11.0.1+13)
```

```
===============================================
Running test ContendedFieldsTests_90_1 ...
===============================================
ContendedFieldsTests_90_1 Start Time: Tue Nov 20 23:19:38 2018 Epoch Time (ms): 1542773978157
variation: -XX:-RestrictContended
JVM_OPTIONS: -Xcompressedrefs -XX:-RestrictContended 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

PASSED: testBigContendedClass
PASSED: testBigInteger
PASSED: testContentionGroups
PASSED: testCrypto
PASSED: testFinalizableMultipleField
PASSED: testFinalizableReferenceClasses
PASSED: testFinalizableSubclassOFinalizable
PASSED: testFinalizableSubclassOfFinalizable
PASSED: testFinalizableSubclassOfNonFinalizable
PASSED: testMultipleContField
PASSED: testMultipleField
PASSED: testNonFinalizableSubclassOFinalizable
PASSED: testPlainObject
PASSED: testReferenceClasses
PASSED: testString
PASSED: testSubclassOfBackfillableAndNonBackfillable
PASSED: testSubclassWithLockwordOfClassWithNoLockword
FAILED: testContentionGroupsAndClass
java.lang.AssertionError: org.openj9.test.contendedfields.TestClasses$ContGroupContClass calculated size 64 actual size 24 difference -40
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.contendedfields.FieldUtilities.checkObjectSize(FieldUtilities.java:67)
	at org.openj9.test.contendedfields.ContendedFieldsTests.testContentionGroupsAndClass(ContendedFieldsTests.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testFinalizableMultipleFieldContClass
java.lang.AssertionError: org.openj9.test.contendedfields.TestClasses$FinalizableMultipleFieldContClass calculated size 64 actual size 32 difference -32
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.contendedfields.FieldUtilities.checkObjectSize(FieldUtilities.java:67)
	at org.openj9.test.contendedfields.ContendedFieldsTests.testFinalizableMultipleFieldContClass(ContendedFieldsTests.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testMultipleContFieldContClass
java.lang.AssertionError: org.openj9.test.contendedfields.TestClasses$MultipleContFieldContClass calculated size 64 actual size 32 difference -32
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.contendedfields.FieldUtilities.checkObjectSize(FieldUtilities.java:67)
	at org.openj9.test.contendedfields.ContendedFieldsTests.testMultipleContFieldContClass(ContendedFieldsTests.java:172)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testMultipleFieldContClass
java.lang.AssertionError: org.openj9.test.contendedfields.TestClasses$MultipleFieldContClass calculated size 64 actual size 40 difference -24
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.openj9.test.contendedfields.FieldUtilities.checkObjectSize(FieldUtilities.java:67)
	at org.openj9.test.contendedfields.ContendedFieldsTests.testMultipleFieldContClass(ContendedFieldsTests.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    ContendedFieldsTests
    Tests run: 21, Failures: 4, Skips: 0
===============================================
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-osx_x86-64_cmprssptrs/1/

**Comment by pdbain-ibm** [comment]
I will investigate.

**Comment by pdbain-ibm** [comment]
The port library doesn't support `j9sysinfo_get_cache_info()` (yet), so the VM disables contended classes.
Working on adding that function to the port library.  @llxia we can disable this test on MacOS in the meantime if you wish.

**Comment by pdbain-ibm** [comment]
Testsed and working with https://github.com/eclipse/omr/pull/3273 and https://github.com/eclipse/openj9/pull/3906.

**Comment by llxia** [comment]
Test is still excluded. It needs to be re-enabled:
https://github.com/eclipse/openj9/blob/08634cd4cc2a8cde1ad7172bf1a153f1bdb1140c/test/functional/Java8andUp/playlist.xml#L694
https://github.com/eclipse/openj9/blob/08634cd4cc2a8cde1ad7172bf1a153f1bdb1140c/test/functional/Java8andUp/playlist.xml#L724

**Comment by pdbain-ibm** [comment]
@llxia Pull request https://github.com/eclipse/openj9/pull/4018 opened.
Would you kindly review and run an extended test suite on MacOS.

**Comment by llxia** [comment]
Thanks @pdbain-ibm.  #4018 is merged.
