### ISSUE TITLE
threadMXBeanTestSuite2_3 failed with AssertionError on osx jdk11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3778]
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/6/tapResults/

```
00:21:58.573 + build/macosx-x86_64-normal-server-release/images/jdk/bin/java -version
00:21:58.574 openjdk version "11.0.1-internal" 2018-10-16
00:21:58.574 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.PullRequest-Extended-JDK11-osxx86-64cmprssptrs-OpenJ9)
00:21:58.574 Eclipse OpenJ9 VM (build HEAD-29f39b9d5, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181120_6 (JIT enabled, AOT enabled)
00:21:58.574 OpenJ9   - 29f39b9d5
00:21:58.574 OMR      - 1b8bfbae
00:21:58.574 JCL      - 2fbed1f42df based on jdk-11.0.1+13)
```

```
===============================================
Running test threadMXBeanTestSuite2_3 ...
===============================================
threadMXBeanTestSuite2_3 Start Time: Tue Nov 20 23:24:35 2018 Epoch Time (ms): 1542774275890
variation: Mode610
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[APITest2] [ERROR] getThreadUserTime, enabled(true): unexpected -1 returned
[APITest2] [ERROR] failed
............................................................

 Sleeping for 10s 
..........
..............................
..............................
..........
........................................................................................................................
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
.PASSED: testManyInspectOne("60", "5")
PASSED: testBenchCurrentThreadCpuTime("1000000")
PASSED: testMaxMonitorsTest
PASSED: testBlockedThread("900", "100")
PASSED: testNewThread
PASSED: testCmvc106800
PASSED: testNoBlock("10")
PASSED: testCycle("30", "5")
PASSED: testRunnableThread("10")
PASSED: testDeadlocks
PASSED: testSleepingThread
PASSED: testDeadThread("100")
PASSED: testStackDepth
PASSED: testExitedThread("300")
PASSED: testThreadListMutex("10")
PASSED: testTimedWaitingThread("120")
PASSED: testWaitingThread("60")
FAILED: testAPITest2
java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at org.openj9.test.java.lang.management.ThreadMXBean.APITest2.runGetTimeTests(APITest2.java:297)
	at org.openj9.test.java.lang.management.ThreadMXBean.APITest2.testAPITest2(APITest2.java:267)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    threadMXBeanTestSuite2
    Tests run: 18, Failures: 1, Skips: 0
===============================================


===============================================
GeneralTest suite
Total tests run: 18, Failures: 1, Skips: 0
===============================================


threadMXBeanTestSuite2_3_FAILED
```

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by pshipton** [comment]
@JasonFengJ9 any update?

**Comment by JasonFengJ9** [comment]
@pshipton sorry, no progress due to other workload. Will give a update later of day.
