### ISSUE TITLE
hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on aix71-p8-X failed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3809]
Occurred in both OMR AIX sanity jobs after all testing passed, on aix71-p8-1 and aix71-p8-4.
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/323
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/182
```
21:58:34 TOTAL: 188   EXECUTED: 107   PASSED: 107   FAILED: 0   SKIPPED: 81
21:58:34 ALL TESTS PASSED
21:58:34 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
21:58:34 
21:58:34 _sanity.functional done
21:58:34 gmake: Leaving directory '/home/u0020236/workspace/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests'
[Pipeline] sh
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Command Close created at
	at hudson.remoting.Command.<init>(Command.java:68)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1265)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1263)
	at hudson.remoting.Channel.close(Channel.java:1436)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1270)
Caused: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1271)
	at hudson.remoting.Channel$1.handle(Channel.java:565)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:87)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on aix71-p8-4 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:948)
	at hudson.FilePath.act(FilePath.java:1071)
	at hudson.FilePath.act(FilePath.java:1060)
	at hudson.FilePath.mkdirs(FilePath.java:1245)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:79)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
I think this is a plugin bug
https://issues.jenkins-ci.org/browse/JENKINS-53468

If this is happening on a regular occurrence, we could roll back to a previous version.

**Comment by pshipton** [comment]
I haven't seen it since the original, so far.

**Comment by pshipton** [comment]
We might still have intermittent issues like this, but obviously we aren't using this Issue to discuss them.
