### ISSUE TITLE
testvmcheck_6 ASSERTION FAILED on osx JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3820]
```
00:42:07.830 "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
00:42:15.266 openjdk version "11.0.1-internal" 2018-10-16
00:42:15.266 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.Build-JDK11-osxx86-64cmprssptrs)
00:42:15.266 Eclipse OpenJ9 VM (build master-d8b22d802, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181120_9 (JIT enabled, AOT enabled)
00:42:15.266 OpenJ9   - d8b22d802
00:42:15.266 OMR      - 1b8bfbae
00:42:15.266 JCL      - 2fbed1f42df based on jdk-11.0.1+13)
```

```
01:40:18.915 ===============================================
01:40:18.915 Running test testvmcheck_6 ...
01:40:18.915 ===============================================
01:40:18.915 testvmcheck_6 Start Time: Fri Nov 23 11:17:15 2018 Epoch Time (ms): 1542989835108
01:40:18.915 variation: Mode551
01:40:18.915 JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced 
01:40:18.915 { mkdir -p "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15429863481456/testvmcheck_6"; \
01:40:18.915 	cd "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15429863481456/testvmcheck_6"; \
01:40:18.915 	"/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  \
01:40:18.915 	-cp "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
01:40:18.915 	org.testng.TestNG -d "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15429863481456/testvmcheck_6" "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" \
01:40:18.915 	-testnames testvmcheck \
01:40:18.915 	-groups level.extended \
01:40:18.915 	-excludegroups d.*.osx_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all; \
01:40:18.915 	if [ $? -eq 0 ] ; then echo ""; echo "testvmcheck_6""_PASSED"; echo ""; cd /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "testvmcheck_6""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15429863481456/TestTargetResult";
01:40:22.966 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
01:40:22.966 ...
01:40:22.966 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
01:40:22.966 ...
01:40:22.966 
01:40:22.966 [TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources are not end with .jar
01:42:15.296 16:19:00.446 0x16221600    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:2155: ((false && (copyCache->cacheAlloc <= copyCache->cacheTop)))
01:42:15.296 16:19:00.446 0x16216200    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:2163: ((false && (copyCache->cacheAlloc <= copyCache->cacheTop)))
01:42:15.296 16:19:00.446 0x1621da00    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:2155: ((false && (copyCache->cacheAlloc <= copyCache->cacheTop)))
01:42:15.296 16:19:00.446 0x16225100    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:2155: ((false && (copyCache->cacheAlloc <= copyCache->cacheTop)))
01:42:15.296 JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/23 11:19:00 - please wait.
01:42:15.296 JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/23 11:19:00 - please wait.
01:42:15.296 JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/23 11:19:00 - please wait.
01:42:15.296 JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/23 11:19:00 - please wait.
01:42:15.296 JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_15429863481456/testvmcheck_6/core.20181123.111900.23165.0001.dmp' in response to an event
01:42:15.296 JVMDUMP012E Error in System dump: The core file created by child process with pid = 23239 was not found. Expected to find core file with name "/cores/core.23239"
01:42:15.296 JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_15429863481456/testvmcheck_6/javacore.20181123.111900.23165.0005.txt' in response to an event
01:42:15.296 JVMDUMP012E Error in Java dump: /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_15429863481456/testvmcheck_6/javacore.20181123.111900.23165.0005.txt
01:42:15.296 JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_15429863481456/testvmcheck_6/Snap.20181123.111900.23165.0006.trc' in response to an event
01:42:15.296 JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Grinder/openjdk-tests/TestConfig/test_output_15429863481456/testvmcheck_6/Snap.20181123.111900.23165.0006.trc
01:42:15.296 JVMDUMP013I Processed dump event "traceassert", detail "".
01:42:15.296 
01:42:15.296 testvmcheck_6_FAILED
01:42:15.296 
01:42:15.296 testvmcheck_6 Finish Time: Fri Nov 23 11:19:10 2018 Epoch Time (ms): 1542989950883
```

**Comment by DanHeidinga** [comment]
fyi @dmitripivkine

**Comment by dmitripivkine** [comment]
This is a memory corruption most likely. Different threads are using different copyCache structures but all of them located close to each other (an array of them). The fact that all threads asserted here means that part of memory has been destroyed

**Comment by pshipton** [comment]
Also occurs on jdk8 as a hang
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/4

```
03:17:30 ===============================================
03:17:30 Running test testvmcheck_0 ...
03:17:30 ===============================================
03:17:30 testvmcheck_0 Start Time: Mon Dec 17 03:17:29 2018 Epoch Time (ms): 1545034649414
03:17:30 "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
03:17:30 JVMSHRC005I No shared class caches available
03:17:30 JVMSHRC005I No shared class caches available
03:17:30 cache cleanup done
03:17:30 variation: NoOptions
03:17:30 JVM_OPTIONS: -Xcompressedrefs 
03:17:30 { mkdir -p "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1545031637111/testvmcheck_0"; \
03:17:30 	cd "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1545031637111/testvmcheck_0"; \
03:17:30 	"/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/java" -Xcompressedrefs  \
03:17:30 	-cp "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
03:17:30 	org.testng.TestNG -d "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1545031637111/testvmcheck_0" "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" \
03:17:30 	-testnames testvmcheck \
03:17:30 	-groups level.extended \
03:17:30 	-excludegroups d.*.osx_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all; \
03:17:30 	if [ $? -eq 0 ] ; then echo ""; echo "testvmcheck_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "testvmcheck_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1545031637111/TestTargetResult";
03:17:30 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_8.txt
03:17:30 ...
03:17:30 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
03:17:30 ...
03:17:30 
03:17:30 [TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/compressedrefs/jclSC180/vm.jar does not exist
03:17:30 [TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/se-service.jar does not exist
```

**Comment by pshipton** [comment]
Attempting some 30x grinders
jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/172/
jkd8 - https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/173/

**Comment by pshipton** [comment]
jdk11 passed
jdk8 failed
```
23:21:59 ===============================================
23:21:59 Running test testvmcheck_0 ...
23:21:59 ===============================================
23:21:59 testvmcheck_0 Start Time: Sat Jan 12 23:21:58 2019 Epoch Time (ms): 1547353318941
23:21:59 "/Users/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
23:21:59 JVMSHRC005I No shared class caches available
23:21:59 JVMSHRC005I No shared class caches available
23:21:59 cache cleanup done
23:21:59 variation: NoOptions
23:21:59 JVM_OPTIONS:  -Xcompressedrefs 
23:21:59 { itercnt=1; \
23:21:59 	mkdir -p "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15473533181710/testvmcheck_0"; \
23:21:59 	cd "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15473533181710/testvmcheck_0"; \
23:21:59 	"/Users/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/jre/bin/java"  -Xcompressedrefs  \
23:21:59 	-cp "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
23:21:59 	org.testng.TestNG -d "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15473533181710/testvmcheck_0" "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" \
23:21:59 	-testnames testvmcheck \
23:21:59 	-groups level.extended \
23:21:59 	-excludegroups d.*.osx_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all; \
23:21:59 	if [ $? -eq 0 ] ; then echo ""; echo "testvmcheck_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "testvmcheck_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15473533181710/TestTargetResult";
23:21:59 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_8.txt
23:21:59 ...
23:21:59 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
23:21:59 ...
23:21:59 
23:21:59 [TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/jre/lib/compressedrefs/jclSC180/vm.jar does not exist
23:21:59 [TestLoadingClassesFromJarfile] [WARN] /Users/jenkins/workspace/Test-Grinder/openjdkbinary/j2sdk-image/jre/lib/se-service.jar does not exist
Cancelling nested steps due to timeout
09:16:12 Sending interrupt signal to process
09:16:18 FAILED: testLoadingClasses
09:16:18 java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<143>
09:16:18 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
09:16:18 	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
09:16:18 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
09:16:18 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
09:16:18 	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:184)
09:16:18 	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:109)
09:16:18 	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:78)
09:16:18 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:16:18 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:16:18 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:16:18 	at java.lang.reflect.Method.invoke(Method.java:498)
09:16:18 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
09:16:18 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
09:16:18 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
09:16:18 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
09:16:18 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
09:16:18 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
09:16:18 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
09:16:18 	at org.testng.TestRunner.run(TestRunner.java:505)
09:16:18 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
09:16:18 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
09:16:18 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
09:16:18 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
09:16:18 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
09:16:18 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
09:16:18 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
09:16:18 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
09:16:18 	at org.testng.TestNG.runSuites(TestNG.java:1049)
09:16:18 	at org.testng.TestNG.run(TestNG.java:1017)
09:16:18 	at org.testng.TestNG.privateMain(TestNG.java:1354)
09:16:18 	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
The jdk8 hang still occurs in the overnight builds, i.e. https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/31

**Comment by pshipton** [comment]
I've opened #4279 for the jdk8 issue and closing this one since the jdk11 doesn't occur.
