### ISSUE TITLE
cmdLineTester_jvmtitests_2 failed with NullPointerException on osx JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3839]
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/3/consoleFull

```
00:26:03.145 "/Users/jenkins/workspace/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java" -version
00:26:04.296 openjdk version "11.0.1-internal" 2018-10-16
00:26:04.296 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.Build-JDK11-osxx86-64cmprssptrs)
00:26:04.296 Eclipse OpenJ9 VM (build master-617897dfa, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181126_11 (JIT enabled, AOT enabled)
00:26:04.296 OpenJ9   - 617897dfa
00:26:04.296 OMR      - 8001cf22
00:26:04.296 JCL      - d42cd0d94f7 based on jdk-11.0.1+13)
```

```
00:44:21.056 Testing: gaste001_multiple
00:44:21.056 Test start time: 2018/11/26 01:31:54 Eastern Standard Time
00:44:21.056 Running command: "/Users/jenkins/workspace/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:cacheRetransformed,name=retransformenabled  -Xdump    -Xjit:count=0 -agentlib:jvmtitest=test:gaste001 -agentlib:jvmtitest=test:gaste001 -cp "/Users/jenkins/workspace/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
00:44:21.056 Time spent starting: 5 milliseconds
00:44:24.012 Time spent executing: 3032 milliseconds
00:44:24.017 Test result: FAILED
00:44:24.017 Output from test:
00:44:24.017  [ERR] java.lang.NullPointerException
00:44:24.017  [ERR] 	at java.base/java.util.Set.of(Set.java:693)
00:44:24.017  [ERR] 	at java.base/jdk.internal.module.Builder.requires(Builder.java:193)
00:44:24.017  [ERR] 	at java.base/jdk.internal.module.SystemModules$default.moduleDescriptors(Unknown Source)
00:44:24.017  [ERR] 	at java.base/jdk.internal.module.SystemModuleFinders.of(SystemModuleFinders.java:146)
00:44:24.017  [ERR] 	at java.base/jdk.internal.module.ModuleBootstrap.boot(ModuleBootstrap.java:193)
00:44:24.017  [ERR] 	at java.base/java.lang.ClassLoader.initializeClassLoaders(ClassLoader.java:217)
00:44:24.017  [ERR] 	at java.base/java.lang.Thread.initialize(Thread.java:422)
00:44:24.017  [ERR] 	at java.base/java.lang.Thread.<init>(Thread.java:153)
00:44:24.017 >> Success condition was not found: [Return code: 0]
```

**Comment by pdbain-ibm** [comment]
I will investigate.

**Comment by pshipton** [comment]
Not sure if this problem still occurs, but if it does then it is intermittent. i.e. it did not occur last night https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/21
```
01:18:08 Testing: gaste001_multiple
01:18:08 Test start time: 2018/12/16 22:18:07 Pacific Standard Time
01:18:08 Running command: "/Users/jenkins/workspace/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI  -Xdump    -Xjit:count=0 -agentlib:jvmtitest=test:gaste001 -agentlib:jvmtitest=test:gaste001 -cp "/Users/jenkins/workspace/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
01:18:08 Time spent starting: 17 milliseconds
01:18:12 Time spent executing: 4217 milliseconds
01:18:12 Test result: PASSED
```

**Comment by pshipton** [comment]
There was a similar failure here https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-osx_x86-64_cmprssptrs/16

**Comment by pshipton** [comment]
Attempting a 30x grinder https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/171/

**Comment by pshipton** [comment]
Seems test resources are missing in the grinder `JVMJ9TI001E Agent library jvmtitest could not be opened (dlopen(libjvmtitest.dylib, 1): image not found)`
@smlambert @llxia is there a way to fix this?

**Comment by smlambert** [comment]
You need to load the the native test libs in addition to the SDK under test.  You can do this by passing both URLs to CUSTOMIZED_SDK_URL parameter (I believe separated by a space, though if it doesn't work, then comma-separated).

**Comment by smlambert** [comment]
I'll try rerunning your Grinder with SDK/native-tests loaded via customized:
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/174/

**Comment by pshipton** [comment]
Thanks @smlambert !

Since the grinder passed I will assume this is fixed and close it.
