### ISSUE TITLE
testSoftMxDisclaimMemory_2 failed on osx JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3841]
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/9/tapResults/

```
00:21:33.637 + build/macosx-x86_64-normal-server-release/images/jdk/bin/java -version
00:21:34.925 openjdk version "11.0.1-internal" 2018-10-16
00:21:34.925 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.PullRequest-Extended-JDK11-osxx86-64cmprssptrs-OpenJ9)
00:21:34.925 Eclipse OpenJ9 VM (build HEAD-6c12d1731, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181126_9 (JIT enabled, AOT enabled)
00:21:34.925 OpenJ9   - 6c12d1731
00:21:34.925 OMR      - 8001cf22
00:21:34.925 JCL      - d42cd0d94f7 based on jdk-11.0.1+13)
```

```
===============================================
Running test testSoftMxDisclaimMemory_2 ...
===============================================
testSoftMxDisclaimMemory_2 Start Time: Mon Nov 26 10:09:30 2018 Epoch Time (ms): 1543244970624
variation: Mode601
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:optthruput 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[SoftmxAdvanceTest] [ERROR] 	FAIL: Memory didn't release back to OS! Post memory size 3918548992 is less than or equal to previous memory size 3918004224
[SoftmxAdvanceTest] [WARN] 	Generate Java core dump after forcing GC.
JVMJ9VM079W triggerOneOffDump(java) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(heap) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(system) requires j9dmp29
[SoftmxAdvanceTest] [ERROR] 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
[SoftmxAdvanceTest] [WARN] 	Generate Java core dump after forcing GC.
JVMJ9VM079W triggerOneOffDump(java) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(heap) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(system) requires j9dmp29
[SoftmxAdvanceTest] [ERROR] 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
[SoftmxAdvanceTest] [WARN] 	Generate Java core dump after forcing GC.
JVMJ9VM079W triggerOneOffDump(java) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(heap) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(system) requires j9dmp29
[SoftmxAdvanceTest] [ERROR] 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
[SoftmxAdvanceTest] [WARN] 	Generate Java core dump after forcing GC.
JVMJ9VM079W triggerOneOffDump(java) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(heap) requires j9dmp29
JVMJ9VM079W triggerOneOffDump(system) requires j9dmp29
[SoftmxAdvanceTest] [ERROR] 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
FAILED: testDisclaimMemoryEffects(5)
java.lang.AssertionError: Test has failed after 5 attempts
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects(SoftmxAdvanceTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    testSoftMxDisclaimMemory
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
JLM_Tests_Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================


testSoftMxDisclaimMemory_2_FAILED
```

**Comment by llxia** [comment]
Dup of #4090
