### ISSUE TITLE
TestSunAttachClasses_0 failed with missing Agent_OnAttach string on osx JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3842]
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/9/tapResults/

```
00:21:33.637 + build/macosx-x86_64-normal-server-release/images/jdk/bin/java -version
00:21:34.925 openjdk version "11.0.1-internal" 2018-10-16
00:21:34.925 OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.jenkins.PullRequest-Extended-JDK11-osxx86-64cmprssptrs-OpenJ9)
00:21:34.925 Eclipse OpenJ9 VM (build HEAD-6c12d1731, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181126_9 (JIT enabled, AOT enabled)
00:21:34.925 OpenJ9   - 6c12d1731
00:21:34.925 OMR      - 8001cf22
00:21:34.925 JCL      - d42cd0d94f7 based on jdk-11.0.1+13)
```

```
01:42:48.025 ===============================================
01:42:48.025 Running test TestSunAttachClasses_0 ...
01:42:48.025 ===============================================
01:42:48.025 TestSunAttachClasses_0 Start Time: Mon Nov 26 09:44:36 2018 Epoch Time (ms): 1543243476087
01:42:48.025 variation: NoOptions
01:42:48.025 JVM_OPTIONS: -Xcompressedrefs 
01:42:48.025 { mkdir -p "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15432393657299/TestSunAttachClasses_0"; \
01:42:48.025 	cd "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15432393657299/TestSunAttachClasses_0"; \
01:42:48.025 	export DYLD_LIBRARY_PATH="/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/test/openj9/:/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/jdk/bin/../lib/compressedrefs:/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/jdk/bin/../lib/j9vm":; \
01:42:48.025 		"/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/jdk/bin/java" -Xcompressedrefs  \
01:42:48.025 	--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED \
01:42:48.026 	-cp "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
01:42:48.026 	-Dcom.ibm.tools.attach.enable=yes \
01:42:48.026 	-Dcom.ibm.tools.attach.timeout=15000 \
01:42:48.026 	-Djdk.attach.allowAttachSelf=true \
01:42:48.026 	-Djava.sidecar="--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED" \
01:42:48.026 	org.testng.TestNG -d "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15432393657299/TestSunAttachClasses_0" "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestSunAttachClasses \
01:42:48.026 	-groups level.extended \
01:42:48.026 	-excludegroups d.*.osx_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all; \
01:42:48.026 	if [ $? -eq 0 ] ; then echo ""; echo "TestSunAttachClasses_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "TestSunAttachClasses_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15432393657299/TestTargetResult";
01:42:48.026 [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
01:42:48.026 ...
01:42:48.026 ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
01:42:48.026 ...
01:42:48.026 
01:42:48.026 PASSED: testAttachToOtherProcess
01:42:48.026 PASSED: testAttachToSelf
01:42:48.026 FAILED: testAgentLoading
01:42:48.026 java.lang.AssertionError: missing Agent_OnAttach string
01:42:48.026 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
01:42:48.026 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
01:42:48.026 	at org.openj9.test.attachAPI.TestSunAttachClasses.testAgentLoading(TestSunAttachClasses.java:135)
01:42:48.026 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:42:48.026 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:42:48.026 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:42:48.026 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:42:48.026 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:42:48.026 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:42:48.026 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:42:48.026 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:42:48.026 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:42:48.026 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:42:48.026 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:42:48.026 	at org.testng.TestRunner.run(TestRunner.java:505)
01:42:48.026 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:42:48.026 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:42:48.026 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:42:48.026 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:42:48.026 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:42:48.026 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:42:48.026 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:42:48.026 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:42:48.026 	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:42:48.026 	at org.testng.TestNG.run(TestNG.java:1017)
01:42:48.026 	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:42:48.026 	at org.testng.TestNG.main(TestNG.java:1323)
01:42:48.026 
01:42:48.026 
01:42:48.026 ===============================================
01:42:48.026     TestSunAttachClasses
01:42:48.026     Tests run: 3, Failures: 1, Skips: 0
01:42:48.026 ===============================================
01:42:48.026 
01:42:48.026 
01:42:48.026 ===============================================
01:42:48.026 GeneralTest suite
01:42:48.026 Total tests run: 3, Failures: 1, Skips: 0
01:42:48.026 ===============================================
01:42:48.026 
01:42:48.026 
01:42:48.026 TestSunAttachClasses_0_FAILED
```

**Comment by pdbain-ibm** [comment]
Using the wrong suffix for the agent library:
```
[AttachApiTest] [DEBUG] trying to load /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/lib/libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../../native-test-libs//libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../lib/compressedrefs/libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin//../lib/j9vm/libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /libjvmtitest.so
[AttachApiTest] [DEBUG] trying to load /usr/lib/libjvmtitest.so
```

**Comment by pdbain-ibm** [comment]
Testing the fix now.

**Comment by pdbain-ibm** [comment]
Pull request https://github.com/eclipse/openj9/pull/3890 opened.
