### ISSUE TITLE
IllegalAccessException when calling default methods on interfaces

### ISSUE THREAD

**Issue by mseele** [eclipse/openj9#3851]
There seem's to be an issue in openj9 when calling default methods on interfaces. 
Please see https://github.com/lviggiano/owner/issues/243

Here is a snippet to reproduce the error:

```
import org.aeonbits.owner.ConfigFactory;

import com.automation.remarks.video.SystemUtils;
import com.automation.remarks.video.recorder.VideoConfiguration;

public class Test {

	public static void main(String[] args) {
		ConfigFactory.setProperty("os.type", SystemUtils.getOsType()); //$NON-NLS-1$
		VideoConfiguration videoConfiguration = ConfigFactory.create(VideoConfiguration.class, System.getProperties());
		System.err.println(videoConfiguration.screenSize());
	}

}
```

...and here is the maven dependencies to run this code:

```
<dependencies>
	<dependency>
		<groupId>com.automation-remarks</groupId>
		<artifactId>video-recorder-core</artifactId>
		<version>1.8</version>
	</dependency>
	<dependency>
		<groupId>org.aeonbits.owner</groupId>
		<artifactId>owner</artifactId>
		<version>1.0.10</version>
	</dependency>
	<dependency>
		<groupId>org.aeonbits.owner</groupId>
		<artifactId>owner-java8</artifactId>
		<version>1.0.10</version>
	</dependency>
</dependencies>
```

It work's well with openjdk-11 hotspot (https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot) and java 8.

**Comment by DanHeidinga** [comment]
Copying the stack trace here:
```
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy7.screenSize(Unknown Source)
	at Test.main(Test.java:13)
Caused by: java.lang.IllegalAccessException: org.aeonbits.owner.util.Java8SupportImpl could not access com.automation.remarks.video.recorder.VideoConfiguration - private access required
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSpecialAccess(MethodHandles.java:493)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:517)
	at org.aeonbits.owner.util.Java8SupportImpl.invokeDefaultMethod(Java8SupportImpl.java:47)
	at org.aeonbits.owner.util.Reflection.invokeDefaultMethod(Reflection.java:68)
	at org.aeonbits.owner.PropertiesInvocationHandler.invoke(PropertiesInvocationHandler.java:61)
	... 2 more
```

**Comment by ChengJin01** [comment]
Will investigate to see what happened in there.

**Comment by ChengJin01** [comment]
The exception occurred at the following code at /jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
```
		private void checkSpecialAccess(Class<?> callerClass) throws IllegalAccessException {
			if (INTERNAL_PRIVILEGED == accessMode) {
				// Full access for use by MH implementation.
				return;
			}
			if (isWeakenedLookup() || accessClass != callerClass) { <----------
				/*[MSG "K0585", "{0} could not access {1} - private access required"]*/
				throw new IllegalAccessException(com.ibm.oti.util.Msg.getString("K0585", accessClass.getName(), callerClass.getName())); //$NON-NLS-1$
			}
		}
```

Looking at the access rules for findSpecial in the API Spec https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#findSpecial(java.lang.Class,java.lang.String,java.lang.invoke.MethodType,java.lang.Class)
```
Before method resolution, if the explicitly specified caller class is not identical with the lookup class, 
or if this lookup object does not have private access privileges, the access fails. 
```
According to the rules above,  it means org.aeonbits.owner.util.Java8SupportImpl != com.automation.remarks.video.recorder.VideoConfiguration.

So the thrown exception is correct as our code follows the access rules above.

Looking at the explanation of arguments **specialCaller** for findSpecial:
public MethodHandle findSpecial?(Class<?> refc, String name, MethodType type, Class<?> specialCaller)
```
specialCaller - the proposed calling class to perform the invokespecial
```
which means specialCaller should be Java8SupportImpl rather than VideoConfiguration in this case.

So the existing code in invokeDefaultMethod() needs to modify to make sure specialCaller is set to Java8SupportImpl 
```
return MethodHandles.lookup()
                    .findSpecial(declaringClass, method.getName(), rt, declaringClass <------
it is wrong to set the second argument declaringClass  to VideoConfiguration)
                    .bindTo(proxy)
.invokeWithArguments(args);
```

**Comment by DanHeidinga** [comment]
Nice work tracking that down @ChengJin01 but I think this is a case where the javadoc is incorrect. 

The intention of the MethodHandles.Lookup.find* calls is to emulate the behaviour of the equivalent bytecodes.  In the case of `findSpecial`, that would be emulating `invokespecial`, which DOES allow calling interface methods when the currentClass != resolvedClass:
https://github.com/eclipse/openj9/blob/7e0680444beb2c13865d966233cb73e03bd0141c/runtime/vm/resolvesupport.cpp#L1182-L1190

& in `isDirectSuperInterface`:
https://github.com/eclipse/openj9/blob/7e0680444beb2c13865d966233cb73e03bd0141c/runtime/util/resolvehelp.c#L104

Now it's a little hard to get the direct interfaces in Java so we can just check if the `resolvedClass` (aka `declaringClass`) is an interface and whether the `currentClass` (aka `specialCaller`) can be assigned to it.

**Comment by ChengJin01** [comment]
Already noticed the inconsistency of invokespecial in the VM Spec against findSpecial() in the API Spec.

@mseele , could you provide the detailed steps to reproduce the exception? So we verify once we fix the issue (probably we also need our own test cases for the fix).

**Comment by mseele** [comment]
@ChengJin01 of course, the steps to reproduce the issue are:

maven dependency:
```
<dependencies>
	<dependency>
		<groupId>com.automation-remarks</groupId>
		<artifactId>video-recorder-core</artifactId>
		<version>1.8</version>
	</dependency>
	<dependency>
		<groupId>org.aeonbits.owner</groupId>
		<artifactId>owner</artifactId>
		<version>1.0.10</version>
	</dependency>
	<dependency>
		<groupId>org.aeonbits.owner</groupId>
		<artifactId>owner-java8</artifactId>
		<version>1.0.10</version>
	</dependency>
</dependencies>
```

code:
```
import org.aeonbits.owner.ConfigFactory;

import com.automation.remarks.video.SystemUtils;
import com.automation.remarks.video.recorder.VideoConfiguration;

public class Test {

	public static void main(String[] args) {
		ConfigFactory.setProperty("os.type", SystemUtils.getOsType()); //$NON-NLS-1$
		VideoConfiguration videoConfiguration = ConfigFactory.create(VideoConfiguration.class, System.getProperties());
		System.err.println(videoConfiguration.screenSize());
	}

}
```

is that enough?

**Comment by ChengJin01** [comment]
I already reproduced the issue by creating a maven-based project with the test application above.
[myapp.zip](https://github.com/eclipse/openj9/files/2646555/myapp.zip)
```
$ java  -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20181115_19 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)

Administrator@JCHTORWIN101 /cygdrive/c/temp/243_access_findspec/myproject2/myapp
$ java -cp target/myapp-1.0-SNAPSHOT-jar-with-dependencies.jar verf.myproject.app.ownerTest
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy7.screenSize(Unknown Source)
        at verf.myproject.app.ownerTest.main(ownerTest.java:13)
Caused by: java.lang.IllegalAccessException: org.aeonbits.owner.util.Java8SupportImpl could not access com.automation.remarks.video.recorder.VideoConfiguration - private access required
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkSpecialAccess(MethodHandles.java:493)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:517)
        at org.aeonbits.owner.util.Java8SupportImpl.invokeDefaultMethod(Java8SupportImpl.java:47)
        at org.aeonbits.owner.util.Reflection.invokeDefaultMethod(Reflection.java:68)
        at org.aeonbits.owner.PropertiesInvocationHandler.invoke(PropertiesInvocationHandler.java:61)
        ... 2 more
```

With my fix,  it ended up with the same result as Oracle:
```
[Oracle/Hotspot]
jdk_11.0.1_13_hotspot/bin/java  -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

jdk_11.0.1_13_hotspot/bin/java -cp target/myapp-1.0-SNAPSHOT-jar-with-dependencies.jar verf.myproject.app.ownerTest
java.awt.Dimension[width=1536,height=864]

[OpenJ9]
build_jdk11_v2/windows-x86_64-normal-server-release/images/jdk/bin/java -version
openjdk version "11.0.1-internal" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1-internal+0-adhoc.Administrator.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-b04740cbc, JRE 11 Windows 10 amd64-64-Bit Compressed References 20181204_000000 (JIT enabled, AOT enabled)
OpenJ9   - b04740cbc
OMR      - 444ea2ca
JCL      - 176e4dd761 based on jdk-11.0.1+13)

build_jdk11_v2/windows-x86_64-normal-server-release/images/jdk/bin/java  -cp target/myapp-1.0-SNAPSHOT-jar-with-dependencies.jar verf.myproject.app.ownerTest
java.awt.Dimension[width=1536,height=864]
```

Need to check all existing JSR292/335 test cases related to findSpecial in our test buckets as some of tests there need to be updated accordingly to match the code changes.

**Comment by ChengJin01** [comment]
Just detected a couple of failing test cases with in JSR292 test bucket.
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.ibm.j9.jsr292.RestrictReceiverTest.callMethod(RestrictReceiverTest.java:35)
        at com.ibm.j9.jsr292.RestrictReceiverTest.testFindSpecialSameTokenAsCurrentClass(RestrictReceiverTest.java:122)

FAILED: test_FindSpecial_Public_CrossPackage_SubclassLookup
FAILED: testRestrictReceiver
java.lang.AssertionError: class com.ibm.j9.jsr292.Cdid not properly acces member of class A via findSpecial
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
```

Will investigate to figure out what happened in there with my changes.

**Comment by ChengJin01** [comment]
Already fixed the code issue in changes (all failing test cases passed). Will create test cases for the case of interface and verify all JSR292 test cases in personal build.
