### ISSUE TITLE
Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs LambdaLoadTest_OpenJ9_NonLinux_0 NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3903]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/156

```
===============================================
Running test LambdaLoadTest_OpenJ9_NonLinux_0 ...
===============================================
LambdaLoadTest_OpenJ9_NonLinux_0 Start Time: Sun Dec  2 02:03:05 2018 Epoch Time (ms): 1543737785331
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
STF 02:03:05.546 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqsRetrieving amount of free space on drive containing /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0
There is 44334 Mb free
STF 02:03:05.563 - ==================   G E N E R A T I O N   ==================
STF 02:03:05.566 - Checking JVM: /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../../
STF 02:03:05.566 - Starting process to generate scripts: /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../..//bin/java  -Dlog4j.skipJansi=true -Djava.system.class.loader=net.adoptopenjdk.stf.runner.StfClassLoader -classpath /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.core/scripts/../bin net.adoptopenjdk.stf.runner.StfRunner -properties "/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/stf_parameters.properties, , /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.core/config/stf.properties" -testDir "/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest"
GEN 02:03:06.691 - Found test. Project: 'openjdk.test.load' class: 'LambdaLoadTest.class' Dir: '/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.load/bin'
GEN 02:03:06.706 - Found test. Project: 'openjdk.test.load' class: 'net.adoptopenjdk.stf.LambdaLoadTest'
GEN Classpath directories used by project 'openjdk.test.load': 
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.load/bin
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.core/bin
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.load/bin
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar
GEN   /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar
GEN 02:03:06.969 - Using Mode NoOptions. Values = ''
GEN 02:03:07.006 - 
GEN 02:03:07.006 - Test command summary:
GEN 02:03:07.007 -   Step  Stage   Command           Description
GEN 02:03:07.007 -  -----+--------+-----------------+------------
GEN 02:03:07.007 -     1  execute  Run java          Run lambda and stream load test
STF 02:03:07.025 - 
STF 02:03:07.025 - Script generation completed
STF 02:03:07.025 - 
STF 02:03:07.026 - 
STF 02:03:07.026 - =======================   S E T U P   =======================
STF 02:03:07.026 - Running setup: perl /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/setUp.pl
STF 02:03:07.102 - SETUP stage completed
STF 02:03:07.110 - 
STF 02:03:07.110 - ====================   E X E C U T E -   ====================
STF 02:03:07.110 - Running execute: perl /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/execute.pl
STF 02:03:07.186 - 
STF 02:03:07.186 - Java version
STF 02:03:07.186 - Running: /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -version
openjdk version "1.8.0_192-internal"
OpenJDK Runtime Environment (build 1.8.0_192-internal-u0020236_2018_12_01_23_23-b00)
Eclipse OpenJ9 VM (build master-558931e05, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20181201_796 (JIT enabled, AOT enabled)
OpenJ9   - 558931e05
OMR      - 444ea2ca
JCL      - 88a4b74e775 based on jdk8u192-b12)
STF 02:03:07.324 - 
STF 02:03:07.324 - +------ Step 1 - Run lambda and stream load test
STF 02:03:07.324 - | Run foreground process
STF 02:03:07.324 - |   Program:     /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../../bin/java
STF 02:03:07.324 - |   Mnemonic:    LT
STF 02:03:07.324 - |   Echo:        ECHO_ON
STF 02:03:07.324 - |   Expectation: CLEAN_RUN within 30m
STF 02:03:07.324 - |
STF 02:03:07.325 - Running command: /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -Xcompressedrefs -classpath /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.load/bin:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/stf/stf.core/bin:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.lambdasAndStreams/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results -resultsPrefix 1.LT. -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.lambda.threadCount 6 -suite.lambda.inventoryFile /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/1.LT.inventory/openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml -suite.lambda.inventoryExcludeFile none -suite.lambda.totalNumberTests 200 -suite.lambda.selection random -suite.lambda.seed -1 -suite.lambda.repeatCount 1 -suite.lambda.thinkingTime 0ms..0ms
STF 02:03:07.325 - Redirecting stderr to /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/1.LT.stderr
STF 02:03:07.325 - Redirecting stdout to /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/1.LT.stdout
STF 02:03:07.342 - Monitoring processes: LT 
LT  02:03:08.252 - Load test parameters
LT  02:03:08.253 -   Time limited         = false
LT  02:03:08.253 -   abortIfOutOfMemory   = true
LT  02:03:08.253 -   reportFailureLimit   = 1
LT  02:03:08.253 -   abortAtFailureLimit  = 10
LT  02:03:08.254 -   maxTotalLogFileSpace = 209715200
LT  02:03:08.254 -   maxSingleLogSize     = 8388608
LT  02:03:08.254 - Parameters for suite 0
LT  02:03:08.254 -   Suite name     = lambda
LT  02:03:08.254 -   Number threads = 6
LT  02:03:08.254 -   Supplied seed  = -1
LT  02:03:08.254 -   Inventory file = /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/1.LT.inventory/openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  02:03:08.254 -   Exclude file   = none
LT  02:03:08.254 -   Number tests   = 200
LT  02:03:08.254 -   Repeat count   = 1
LT  02:03:08.254 -   Thinking time  = 0ms..0ms
LT  02:03:08.255 -   Selection mode = random
LT  02:03:08.255 -   Actual seed    = 1543765280062
LT  02:03:08.261 - Parsing inventory file. Root=/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/1.LT.inventory File=openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  02:03:08.272 - Final test list:
LT  02:03:08.272 -   0 JUnit[net.adoptopenjdk.test.lambda.ClassLibraryLambdaTests]  Weighting=1 
LT  02:03:08.272 -   1 JUnit[net.adoptopenjdk.test.lambda.TestLambdaCapture]  Weighting=1 
LT  02:03:08.273 -   2 JUnit[net.adoptopenjdk.test.lambda.TestLambdaContexts]  Weighting=1 
LT  02:03:08.273 -   3 JUnit[net.adoptopenjdk.test.lambda.TestLambdaDefaultsAndStatics]  Weighting=1 
LT  02:03:08.273 -   4 JUnit[net.adoptopenjdk.test.lambda.TestLambdaInferredTyping]  Weighting=1 
LT  02:03:08.273 -   5 JUnit[net.adoptopenjdk.test.lambda.TestLambdaJavaInterfaces]  Weighting=1 
LT  02:03:08.273 -   6 JUnit[net.adoptopenjdk.test.lambda.TestLambdaLexicalScoping]  Weighting=1 
LT  02:03:08.273 -   7 JUnit[net.adoptopenjdk.test.lambda.TestLambdaMethodReferences]  Weighting=1 
LT  02:03:08.273 -   8 JUnit[net.adoptopenjdk.test.lambda.TestLambdaMultithreaded]  Weighting=1 
LT  02:03:08.273 -   9 JUnit[net.adoptopenjdk.test.lambda.TestLambdaNested]  Weighting=1 
LT  02:03:08.273 -   10 JUnit[net.adoptopenjdk.test.lambda.TestLambdaRecursive]  Weighting=1 
LT  02:03:08.273 -   11 JUnit[net.adoptopenjdk.test.lambda.TestLambdasUserDefinedInterface]  Weighting=1 
LT  02:03:08.273 -   12 JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]  Weighting=1 
LT  02:03:08.273 -   13 JUnit[net.adoptopenjdk.test.streams.TestStreamOperations]  Weighting=1 
LT  02:03:08.306 - Starting thread. Suite=0 thread=0
LT  02:03:08.309 - Starting thread. Suite=0 thread=1
LT  02:03:08.310 - Starting thread. Suite=0 thread=2
LT  02:03:08.310 - Starting thread. Suite=0 thread=3
LT  02:03:08.310 - Starting thread. Suite=0 thread=4
LT  02:03:08.311 - Starting thread. Suite=0 thread=5
LT  02:03:08.464 - First failure detected by thread: load-1. Running test: JUnit[net.adoptopenjdk.test.lambda.TestLambdaInferredTyping]. Creating java dumps.
LT  stderr JVMDUMP034I User requested Heap dump using '/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.heapdump.20181202.020308.15597652.0001.phd' through com.ibm.jvm.Dump.heapDumpToFile
LT  stderr JVMDUMP010I Heap dump written to /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.heapdump.20181202.020308.15597652.0001.phd
LT  stderr JVMDUMP034I User requested Java dump using '/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.javacore.20181202.020308.15597652.0002.txt' through com.ibm.jvm.Dump.javaDumpToFile
LT  stderr JVMDUMP010I Java dump written to /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.javacore.20181202.020308.15597652.0002.txt
LT  stderr JVMDUMP034I User requested System dump using '/home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.core.20181202.020308.15597652.0003.dmp' through com.ibm.jvm.Dump.systemDumpToFile
LT  stderr JVMDUMP010I System dump written to /home/u0020236/workspace/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15437373069881/LambdaLoadTest_OpenJ9_NonLinux_0/20181202-020305-LambdaLoadTest/results/firstfailure.core.20181202.020308.15597652.0003.dmp
LT  02:03:12.546 - Test failed
LT    Failure num.  = 1
LT    Test number   = 4
LT    Test details  = 'JUnit[net.adoptopenjdk.test.lambda.TestLambdaInferredTyping]'
LT    Suite number  = 0
LT    Thread number = 1
LT  >>> Captured test output >>>
LT  testFailure: null: null
LT  java.lang.NullPointerException
LT  	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.startTest(JUnit38ClassRunner.java:37)
LT  	at junit.framework.TestResult.startTest(TestResult.java:168)
LT  	at junit.framework.TestResult.run(TestResult.java:119)
LT  	at junit.framework.TestCase.run(TestCase.java:129)
LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:813)
```

**Comment by pshipton** [comment]
@Mesbah-Alam is this a test issue?

**Comment by Mesbah-Alam** [comment]
It seems to be an intermittent issue, and not a failure caused by a bug in the test itself. 

The 5x grinder using openj9 sdk passed 100% : https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/980/

The test passes on hotspot too: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/982/console

**Comment by pshipton** [comment]
This hasn't re-occurred, assuming fixed.
