### ISSUE TITLE
JTreg test fail : java/lang/StackWalker/EmbeddedStackWalkTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3941]
The JTreg test https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/lang/StackWalker/EmbeddedStackWalkTest.java is failing inconsistently with the following ...

```
java.lang.RuntimeException: java.lang.AssertionError: expected [true] but found [false]
	at EmbeddedStackWalkTest$C2.run(EmbeddedStackWalkTest.java:118)
	at EmbeddedStackWalkTest$C2.lambda$walk$0(EmbeddedStackWalkTest.java:104)
	at EmbeddedStackWalkTest$C2$$Lambda$20.000000008804E400.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:104)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:106)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:106)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:106)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:106)
	at EmbeddedStackWalkTest$C2.walk(EmbeddedStackWalkTest.java:106)
	at EmbeddedStackWalkTest$C2.testEmbeddedWalker(EmbeddedStackWalkTest.java:98)
	at EmbeddedStackWalkTest$C1.lambda$call$2(EmbeddedStackWalkTest.java:83)
	at EmbeddedStackWalkTest$C1$$Lambda$18.000000008804D550.accept(Unknown Source)
	at java.base/java.util.stream.Stream$2.forEachRemaining(Stream.java:1314)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.lang.StackWalker.lambda$forEach$0(StackWalker.java:152)
	at java.lang.StackWalker$$Lambda$19.000000008804D810.apply(Unknown Source)
	at java.base/java.lang.StackWalker.walkImpl(StackWalker.java:206)
	at java.base/java.lang.StackWalker.walkWrapperImpl(Native Method)
	at java.base/java.lang.StackWalker.forEach(StackWalker.java:151)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:83)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
	at EmbeddedStackWalkTest.test(EmbeddedStackWalkTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at EmbeddedStackWalkTest$C2.lambda$verify$4(EmbeddedStackWalkTest.java:145)
	at EmbeddedStackWalkTest$C2$$Lambda$26.0000000088051B10.accept(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.stream.Stream$2.tryAdvance(Stream.java:1301)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:515)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at EmbeddedStackWalkTest$C2.lambda$verify$5(EmbeddedStackWalkTest.java:142)
	at EmbeddedStackWalkTest$C2$$Lambda$24.0000000088050AB0.apply(Unknown Source)
	at java.base/java.lang.StackWalker.walkImpl(StackWalker.java:206)
	at java.base/java.lang.StackWalker.walkWrapperImpl(Native Method)
	at java.base/java.lang.StackWalker.walk(StackWalker.java:221)
	at EmbeddedStackWalkTest$C2.verify(EmbeddedStackWalkTest.java:139)
	at EmbeddedStackWalkTest$C2.call(EmbeddedStackWalkTest.java:132)
	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_V(DirectHandle.java:177)
	at EmbeddedStackWalkTest$C2.run(EmbeddedStackWalkTest.java:116)
	... 81 more
```

For example, this failure occurred during this job run - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/161.
However, no such problem occurred with the test during this job run - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/162.

It seems the content of the stack is inconsistent, during some executions of this test, sufficient to fail the assertion at https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/lang/StackWalker/EmbeddedStackWalkTest.java#L145.

No such failure of this test is observed when running against Hotspot.

**Comment by pdbain-ibm** [comment]
Yup.  Will investigate.

**Comment by pdbain-ibm** [comment]
@ben-walsh my first few runs passed on MacOS but I am running a longer suite.  Could you indicate the failure rate?  Do you see the failure on platforms other than Linux X86?

**Comment by ben-walsh** [comment]
This job shows 10 failures from 100 iterations (ignore the "Test result" the 10 failures are recorded in the Console Output) - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/517.

I have kicked off two more rebuilds of that job to get additional data points ...
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/519
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/520

I haven't tried any platform other than Linux X86.

**Comment by ben-walsh** [comment]
@pdbain-ibm I also have a job running with a debug statement added to output the value of the line variable - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/518/consoleText ... thus far it looks like this being -1 is the problem.

**Comment by pdbain-ibm** [comment]
Thanks.  Reproduced on my Mac.  Investigating.
The line number is set to -1 if `getLineNumberForROMClassFromROMMethod(vm, romMethod, romClass, 0, classLoader, bytecodeOffset);` returns 0.

**Comment by pdbain-ibm** [comment]
I confirmed that the line number is indeed set to `-1`, which indicates unknown line number.

I get a reproduction rate of about 1%. I ran 800 times with `-Xint` without failure, so it looks like a JIT issue. Also, running with `-Xjit:count=0` causes a different failure:

> java.lang.AssertionError: expected [EmbeddedStackWalkTest] but found [org.testng.internal.MethodInvocationHelper]
> java.lang.AssertionError: expected [EmbeddedStackWalkTest] but found [java.lang.reflect.Method]
> java.lang.AssertionError: expected [EmbeddedStackWalkTest] but found [java.lang.reflect.Method]

> java.lang.Exception: failures: 3
> 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
> 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
> 	at java.base/java.lang.Thread.run(Thread.java:825)

@andrewcraik would you please assign this to someone on the JIT team?
Thank you.

**Comment by ben-walsh** [comment]
@pdbain-ibm Follow up with results on the failure rate from the additional job runs ...
```
JOB                                                             FAILURE RATE
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/517   10/100
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/519   13/100
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/520   12/100
```

**Comment by pdbain-ibm** [comment]
I instrumented the code (attached) 
[test.zip](https://github.com/eclipse/openj9/files/2657616/test.zip)
The line number for the bottom stack frame is getting corrupted.
Good run:

> PDB_DEBUG: EmbeddedStackWalkTest$C2.call@131
> PDB_DEBUG: EmbeddedStackWalkTest$C2.run@116
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@104
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@106
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@106
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@106
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@106
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@106
> PDB_DEBUG: EmbeddedStackWalkTest$C2.testEmbeddedWalker@98

Run with `-Xjit:count=0`:

> PDB_DEBUG: EmbeddedStackWalkTest$C1.call@75
> PDB_DEBUG: EmbeddedStackWalkTest$C1.call@85
> PDB_DEBUG: EmbeddedStackWalkTest$C1.call@85
> PDB_DEBUG: EmbeddedStackWalkTest$C1.call@85
> PDB_DEBUG: EmbeddedStackWalkTest$C1.call@85
> PDB_DEBUG: EmbeddedStackWalkTest$C2.call@123
> PDB_DEBUG: EmbeddedStackWalkTest$C2.run@114
> PDB_DEBUG: EmbeddedStackWalkTest$C2.walk@103
> PDB_DEBUG: EmbeddedStackWalkTest$C2.testEmbeddedWalker@-1
>

**Comment by pdbain-ibm** [comment]
There is another error (more common with `-Xjit:count=0`):

> Exception in thread "main" java.lang.AssertionError: expected [EmbeddedStackWalkTest$C1] but found [EmbeddedStackWalkTest]
> 	at org.testng.Assert.fail(Assert.java:94)
> 	at org.testng.Assert.failNotEquals(Assert.java:496)
> 	at org.testng.Assert.assertEquals(Assert.java:125)
> 	at org.testng.Assert.assertEquals(Assert.java:178)
> 	at org.testng.Assert.assertEquals(Assert.java:188)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:81)
> 	at EmbeddedStackWalkTest.test(EmbeddedStackWalkTest.java:65)
> 	at EmbeddedStackWalkTest.main(EmbeddedStackWalkTest.java:160)

I added the following on line 75 of the test program:
           if (loops == 0) {  **Thread.currentThread().dumpStack();**

With "-Xint" I get:

> java.lang.Throwable
> 	at java.base/java.lang.Thread.dumpStack(Thread.java:502)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:75)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:85)
> 	at EmbeddedStackWalkTest.test(EmbeddedStackWalkTest.java:65)
> 	at EmbeddedStackWalkTest.main(EmbeddedStackWalkTest.java:160)

With `-Xjit:count=0`, I get a much shorter stack trace:

> java.lang.Throwable
> 	at java.base/java.lang.Thread.dumpStack(Thread.java:502)
> 	at EmbeddedStackWalkTest$C1.call(EmbeddedStackWalkTest.java:75)
> 	at EmbeddedStackWalkTest.test(EmbeddedStackWalkTest.java:65)
> 	at EmbeddedStackWalkTest.main(EmbeddedStackWalkTest.java:160)

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/728
