### ISSUE TITLE
Test system Log4jContextFactory.getContext NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4005]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_x86-64/122
```
STF 10:29:33.884 - +------ Step 15 - Access cache using more workload processes
STF 10:29:33.884 - | Run multiple concurrent foreground processes
STF 10:29:33.884 - |   Program:     /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java
STF 10:29:33.884 - |   Mnemonic:    SCL
STF 10:29:33.884 - |   Instances:   2
STF 10:29:33.884 - |   Echo:        ECHO_OFF
STF 10:29:33.884 - |   Expectation: CLEAN_RUN within 20m
STF 10:29:33.884 - |
STF 10:29:33.884 - Running command: /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -Xshareclasses:name=workload_cache,cacheDir=/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/cache -Xnocompressedrefs -classpath /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.load/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.lang/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.util/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.math/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results -resultsPrefix 15.SCL1. -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mini-mix.inventoryFile /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL.inventory/openjdk.test.load/config/inventories/mix/mini-mix.xml -suite.mini-mix.inventoryExcludeFile /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.mini-mix.threadCount 3 -suite.mini-mix.totalNumberTests 600 -suite.mini-mix.selection sequential -suite.mini-mix.seed -1 -suite.mini-mix.repeatCount 1 -suite.mini-mix.thinkingTime 0ms..0ms
STF 10:29:33.884 - Redirecting stderr to /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL1.stderr
STF 10:29:33.884 - Redirecting stdout to /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL1.stdout
STF 10:29:33.886 - Running command: /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -Xshareclasses:name=workload_cache,cacheDir=/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/cache -Xnocompressedrefs -classpath /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.load/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/stf/stf.core/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.lang/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.util/bin:/home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/jvmtest/systemtest/openjdk-systemtest/openjdk.test.math/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results -resultsPrefix 15.SCL2. -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mini-mix.inventoryFile /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL.inventory/openjdk.test.load/config/inventories/mix/mini-mix.xml -suite.mini-mix.inventoryExcludeFile /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.mini-mix.threadCount 3 -suite.mini-mix.totalNumberTests 600 -suite.mini-mix.selection sequential -suite.mini-mix.seed -1 -suite.mini-mix.repeatCount 1 -suite.mini-mix.thinkingTime 0ms..0ms
STF 10:29:33.887 - Redirecting stderr to /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL2.stderr
STF 10:29:33.887 - Redirecting stdout to /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/results/15.SCL2.stdout
STF 10:29:33.888 - Monitoring processes: SCL1 SCL2
STF 10:29:34.340 - **FAILED** Process SCL1 ended with exit code (1) and not the expected exit code/s (0)
STF 10:29:34.340 - Monitoring Report Summary:
STF 10:29:34.340 -   o Process SCL1 ended with exit code (1) and not the expected exit code/s (0)
STF 10:29:34.340 -   o Process SCL2 is still running
STF 10:29:34.341 - Killing processes: SCL1 SCL2
STF 10:29:38.341 -   o Process SCL2 killed
STF 10:29:38.342 -   o Process SCL1 is not running
**FAILED** at step 15 (Access cache using more workload processes). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test-extended.system-JDK8-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15446095802443/SharedClassesWorkload_0/20181212-102859-SharedClassesWorkload/execute.pl line 727.
STF 10:29:38.626 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

15.SCL1.stderr shows
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/211
5.LT2.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_mac_Nightly/4
41.WL4.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/50/
5.LT2.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_mac_Nightly/54/
TestIBMJlmRemoteMemoryNoAuth_0
5.TL2.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_linux_Nightly/62/tapResults/
`PatchModuleImgTest_UnexportedType_0`

```
GEN stderr Error: A JNI error has occurred, please check your installation and try again
GEN stderr Exception in thread "main" java.lang.NullPointerException
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
GEN stderr 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
GEN stderr 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClassBytes(StfClassLoader.java:285)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.findClass(StfClassLoader.java:244)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClass(StfClassLoader.java:143)
GEN stderr 	at java.base/java.lang.Class.forNameImpl(Native Method)
GEN stderr 	at java.base/java.lang.Class.forName(Class.java:415)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
Generation failed

PatchModuleImgTest_UnexportedType_0_FAILED`
```

**Comment by pshipton** [comment]
I don't think anybody is looking at this intermittent failure yet. It's not a regression from the last release, moving out.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.system_x86-64_linux_Nightly/78
HCRLateAttachWorkload_0
```
GEN stderr Error: A JNI error has occurred, please check your installation and try again
GEN stderr Exception in thread "main" java.lang.NullPointerException
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
GEN stderr 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
GEN stderr 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClassBytes(StfClassLoader.java:285)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.findClass(StfClassLoader.java:244)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClass(StfClassLoader.java:143)
GEN stderr 	at java.base/java.lang.Class.forNameImpl(Native Method)
GEN stderr 	at java.base/java.lang.Class.forName(Class.java:415)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
Generation failed
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.system_x86-64_linux_Release/2/
SharedClassesAPI_0
8.WL4.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/83/
SharedClassesWorkload_0
7.SCL2.stderr
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
Caused by: java.lang.NullPointerException
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly/101
CpMpTest_MP_0
```
GEN stderr Exception in thread "main" java.lang.NullPointerException
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:199)
GEN stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
GEN stderr 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
GEN stderr 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClassBytes(StfClassLoader.java:285)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.findClass(StfClassLoader.java:244)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClass(StfClassLoader.java:143)
GEN stderr 	at java.base/java.lang.Class.forNameImpl(Native Method)
GEN stderr 	at java.base/java.lang.Class.forName(Class.java:410)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
GEN stderr 	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_ppc64le_linux_Nightly/4
SharedClasses.SCM23.MultiCL_0

**Comment by DanHeidinga** [comment]
@hangshao0  Can you take a look at this?

**Comment by pshipton** [comment]
Note I don't believe this failure is related to shared classes, it just happened that last few failures occurred in some shared classes testing. I expect any testing using Stf could see this problem.

**Comment by hangshao0** [comment]
The exception is from Apache logging-log4j2, and we do not own the code. I don't know what version of logging-log4j2 does system test framework use. Do you know the version ? @Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
@hangshao0 System test uses log4j-2.3 : https://github.com/AdoptOpenJDK/stf/blob/f4bb075895a7e23105c07bb2b6993c505b5f2d7b/stf.build/include/top.xml#L236

**Comment by hangshao0** [comment]
```
 public LoggerContext getContext(final String fqcn, final ClassLoader loader, final Object externalContext,
                                    final boolean currentContext, final URI configLocation, final String name) {
        final LoggerContext ctx = selector.getContext(fqcn, loader, currentContext, configLocation); 
        if (externalContext != null && ctx.getExternalContext() == null) {
            ctx.setExternalContext(externalContext);
        }
        if (ctx.getState() == LifeCycle.State.INITIALIZED) {         <-- NPE at this line Log4jContextFactory.java:199
...
```
Caller:
```
public static LoggerContext getContext(final boolean currentContext) {
        // TODO: would it be a terrible idea to try and find the caller ClassLoader here?
        return factory.getContext(FQCN, null, null, currentContext, null, null);
}
```

So selector.getContext(fqcn, loader, currentContext, configLocation) returns NULL (parameter loader is NULL and configLocation is NULL).

I don't see anything to do with OpenJ9 here.

**Comment by pshipton** [comment]
The NPE is intermittent, my theory is that it's a JIT problem. Possibly already fixed. Not sure how well the builds have been monitored in the past week+, I'll be keeping an eye out to see if this failure still occurs.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/132/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly/132
TestIBMJlmRemoteMemoryAuth_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_xl_Nightly/141/
TestJlmRemoteMemoryAuth_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_linux_xl_Nightly/45
DaaLoadTest_daa3_ConcurrentScavenge_0

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_ppc64le_linux_Nightly/48/tapResults/
`CpMpTest2_0`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64_aix_Nightly/148
PatchModuleTest_UnexportedType_0

**Comment by pshipton** [comment]
@andrewcraik this seems to occur fairly frequently, although in all sorts of different tests. Given it's an intermittent NPE, I'm thinking JIT problem. Can somebody take a look?

**Comment by DanHeidinga** [comment]
Moving out as this is not a regression in this release

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_windows_Release/7
SharedClassesWorkload_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_windows_Nightly/76
UpgradeModPathTest_ExpDir_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly/181
PatchModuleTest_AppMod_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly/187
LambdaLoadTest_OpenJ9_Linux_CompressedRefs_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_mac_Nightly/92
CpMpTest_MP_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_windows_Nightly/98
LambdaLoadTest_ConcurrentScavenge_0

**Comment by JasonFengJ9** [comment]
`DaaLoadTest_daa2_0`
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_windows_Nightly/118/tapResults/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/245
DaaLoadTest_daa2_special_21

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Nightly/15
SharedClassesWorkload_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_ppc64le_linux_Nightly/146
SC_Softmx_UpDown_0

**Comment by srogmann** [comment]
I saw such a NullPointerException in the Log4ContextFactory in a 64-bit-JVM (OSGi in CICS-JVMSERVER) of a z/OS-machine.

In what way does OpenJ9 deal with a WeakReference if the only reference is a local variable to be overwritten?

log4j-2.3, class org.apache.logging.log4j.core.selector.ClassLoaderContextSelector, method locateContext:

```
            LoggerContext ctx = new LoggerContext(name, null, configLocation);
            final AtomicReference<WeakReference<LoggerContext>> r =
                new AtomicReference<WeakReference<LoggerContext>>();
            r.set(new WeakReference<LoggerContext>(ctx));
            CONTEXT_MAP.putIfAbsent(name, r);
            ctx = CONTEXT_MAP.get(name).get().get();
            return ctx;
```

The corresponding bytecode (see local variable `#6`):

```
     116: new           #5                  // class org/apache/logging/log4j/core/LoggerContext
     119: dup
     120: aload         4
     122: aconst_null
     123: aload_2
     124: invokespecial #33                 // Method org/apache/logging/log4j/core/LoggerContext."<init>":(Ljava/lang/String;Ljava/lang/Object;Ljava/net/URI;)V
     127: astore        6
     129: new           #17                 // class java/util/concurrent/atomic/AtomicReference
     132: dup
     133: invokespecial #34                 // Method java/util/concurrent/atomic/AtomicReference."<init>":()V
     136: astore        7
     138: aload         7
     140: new           #19                 // class java/lang/ref/WeakReference
     143: dup
     144: aload         6
     146: invokespecial #35                 // Method java/lang/ref/WeakReference."<init>":(Ljava/lang/Object;)V
     149: invokevirtual #36                 // Method java/util/concurrent/atomic/AtomicReference.set:(Ljava/lang/Object;)V
     152: getstatic     #10                 // Field CONTEXT_MAP:Ljava/util/concurrent/ConcurrentMap;
     155: aload         4
     157: aload         7
     159: invokeinterface #37,  3           // InterfaceMethod java/util/concurrent/ConcurrentMap.putIfAbsent:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
     164: pop
     165: getstatic     #10                 // Field CONTEXT_MAP:Ljava/util/concurrent/ConcurrentMap;
     168: aload         4
     170: invokeinterface #31,  2           // InterfaceMethod java/util/concurrent/ConcurrentMap.get:(Ljava/lang/Object;)Ljava/lang/Object;
     175: checkcast     #17                 // class java/util/concurrent/atomic/AtomicReference
     178: invokevirtual #18                 // Method java/util/concurrent/atomic/AtomicReference.get:()Ljava/lang/Object;
     181: checkcast     #19                 // class java/lang/ref/WeakReference
     184: invokevirtual #20                 // Method java/lang/ref/WeakReference.get:()Ljava/lang/Object;
     187: checkcast     #5                  // class org/apache/logging/log4j/core/LoggerContext
     190: astore        6
     192: aload         6
     194: areturn
```

**Comment by pshipton** [comment]
I expect the LoggerContext instance is out of scope after `new WeakReference<LoggerContext>(ctx)` and is free to be collected. @DanHeidinga is that correct?

**Comment by DanHeidinga** [comment]
> I expect the LoggerContext instance is out of scope after `new WeakReference<LoggerContext>(ctx)` and is free to be collected

Yes, that's correct.  OpenJ9 can collect the object once there are no longer any more references to it in the method.  We aggressively mark locals as not-an-object so they can be collected as soon as possible.

If the local needs to be kept alive, check out the `reachAbilityFence` method - http://cr.openjdk.java.net/~iris/se/12/latestSpec/api/java.base/java/lang/ref/Reference.html#reachabilityFence(java.lang.Object)

**Comment by srogmann** [comment]
Regarding this problem I have filed https://issues.apache.org/jira/browse/LOG4J2-2756.

@pshipton Thanks for the list of failures!

**Comment by srogmann** [comment]
The `reachabilityFence` needs at least JRE 9.

@DanHeidinga Did you mean that _unused_ locals are aggressively marked as not-an-object? I would expect that the created WeakReference of `ctxJustCreated` in the following example isn't collected.

```
            final LoggerContext ctxJustCreated = createContext(name, configLocation);
            final AtomicReference<WeakReference<LoggerContext>> r = new AtomicReference<>();
            r.set(new WeakReference<>(ctxJustCreated));
            // Starting with JRE 8 computeIfAbsent could be used instead of putIfAbsent to simplify this code.
            CONTEXT_MAP.putIfAbsent(name, r);
            // To use only one LoggerContext in case of parallel threads read the one in CONTEXT_MAP.
            final LoggerContext ctxContextViaMap = CONTEXT_MAP.get(name).get().get();
            // LOG4J2-2756: Prevent the GC from collection of ctxJustCreated by reading it after the call of CONTEXT_MAP.get.
            if (ctxContextViaMap == null) {
                  // The call of ctxJustCreated.getClass() turns ctxJustCreated into a strong reference and prevents ctxContextMap == null.
                  throw new IllegalStateException(String.format("CONTEXT_MAP contains neither just created LoggerContext (%s) nor a parallel computed one.",
                              ctxJustCreated.getClass()));
            }
            return ctxContextViaMap;
```

**Comment by DanHeidinga** [comment]
In the original example, the `created WeakReference of ctxJustCreated` wasn't collected but the `ctxJustCreated` could be collected as the WeakReference was the only reference to it.

In the new code, the interpreter won't be able to collect `ctxJustCreated` as it is used further on in the program as an object - the `ctxJustCreated.getClass()` call.  I'd be surprised if the JIT reorderd the code enough to collect it early but I can't guarantee that it won't in the future

**Comment by srogmann** [comment]
There is a fix in Log4J 2.13.1.

* Prevent LoggerContext from being garbage collected while being created. Fixes LOG4J2-2756.
https://logging.apache.org/log4j/2.x/changes-report.html#a2.13.1

**Comment by pshipton** [comment]
@smlambert @Mesbah-Alam can we pick up the Log4J fix?

**Comment by smlambert** [comment]
Presume it is a matter of changing the prereqs, running all of the affected system tests across all of the platforms and versions to see that the change does not break something else before merging.

Also, need to confirm which log4j dependency that systemtest has, does this relate to the version of log4j used by stf (log4j-2.3) or the version of log4j used by jvmti tests (log4j-1.2.8) or both, based on https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md#installing-prereqs-manually.

**Comment by pshipton** [comment]
Looking at the stack trace, it's the stf one we see failing.

**Comment by pshipton** [comment]
Seems the update to log4j to 2.3 has occurred. I haven't seen this failure since, I think this is resolved.

**Comment by pshipton** [comment]
Another one https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_mac_uma_Nightly/2/

In the console output I see the following:
```
[2020-05-30T04:07:58.169Z] print-log4j-2.3-location:
[2020-05-30T04:07:58.169Z]      [echo] Using log4j-api-2.3 from /Users/****/workspace/Test_openjdk11_j9_sanity.system_x86-64_mac_uma_Nightly/openjdk-tests/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar and log4j-core-2.3 from /Users/****/workspace/Test_openjdk11_j9_sanity.system_x86-64_mac_uma_Nightly/openjdk-tests/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar
```

**Comment by pshipton** [comment]
> Seems the update to log4j to 2.3 has occurred

I misread the requirement, the fix is in Log4J 2.13.1

**Comment by DanHeidinga** [comment]
@Mesbah-Alam I think we need to have system test pick up a newer version of log4j.  Can you address this?

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_mac_Nightly/376
PatchModuleImgTest_PlatformMod_0

**Comment by Mesbah-Alam** [comment]
Log4J libraries have been [upgraded](https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/347) to the latest - 2.13.3. All system test builds will now use this for STF.

**Comment by pshipton** [comment]
Thanks @Mesbah-Alam. I'll go ahead and close this, will reopen if the problem is seen again.
