### ISSUE TITLE
!snapformat doesn't work in OpenJ9 jdmpview

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/openj9#4039]
> !snapformat Snap.trc.fmt.txt
Error executing DDR command !snapformat Snap.trc.fmt.txt : null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:819)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:773)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:747)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:671)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoClassDefFoundError: com.ibm.jvm.trace.format.api.TracePoint
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:339)
	at com.ibm.j9ddr.tools.ddrinteractive.commands.SnapFormatWrapperCommand.run(SnapFormatWrapperCommand.java:67)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:385)
	at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:360)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.ibm.jvm.trace.format.api.TracePoint
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:605)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
	... 24 more

tested JVM information:
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201812091910)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-842f12f84, JRE 11 Linux ppc64le-64-Bit Compressed References 20181209_47 (JIT enabled, AOT enabled)
OpenJ9   - 842f12f84
OMR      - 9b18ac96
JCL      - 14513b61ab based on jdk-11.0.1+13)

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2018-12-09-21-49/OpenJDK11U-jdk_ppc64le_linux_openj9_2018-12-09-21-49.tar.gz

**Comment by dmitripivkine** [comment]
@keithc-ca, @DanHeidinga  FYI

**Comment by pshipton** [comment]
@keithc-ca reminder about this, can you please take a look this week.

**Comment by keithc-ca** [comment]
I thought I had already assigned myself this one: I will look at it this week.
