### ISSUE TITLE
AIX disk space problem, cores generated by extended.system tests

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4088]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-aix_ppc-64_cmprssptrs/105
aix71-p8-3
```
There is 2918 Mb free

Test machine has only 2918 Mb free on drive containing /home/u0020236/workspace/Test-extended.system-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15451171118090/SharedClasses.SCM01.SingleCL_0.

There must be at least 3Gb (3072Mb) free to be sure of capturing diagnostics
files in the event of a test failure.
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by pshipton** [comment]
Should the cleanup run at night before the nightly builds?

**Comment by AdamBrousseau** [comment]
Current schedule is daily at 8:00am, 12 noon, 4:00pm, 11:00pm. Keep in mind, this is only a backup cleanup as all the jobs will cleanup after themselves unless there is a hard kill (machine goes offline, someone forcibly kills)

**Comment by pshipton** [comment]
Seems something isn't working, as this problem keep popping up every week or two. Closing this one, until next time.

**Comment by pshipton** [comment]
and yet it works for a week or two at a time. Should the machines just be restarted every weekend?

**Comment by AdamBrousseau** [comment]
Ideally no, but if there's space not getting reclaimed then perhaps some kind of check or auto-restart. How have the number of failures on AIX been lately? If they go up and down I could see the high times being more hungry for disk space?

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/issues/3081 fails occasionally. I don't think there are any other regular failures in the nightly builds. Not sure about omr acceptance.

**Comment by pshipton** [comment]
I downloaded the results file and it appears there were some failures in this test run which I hadn't seen, DAA and softmx. There are quite a few core files making the uncompressed result file ~40GB.

**Comment by pshipton** [comment]
@Mesbah-Alam I think you'd better take a look at this. In the test results there are core files in the directories for the following tests, however the tests did not fail.

DaaLoadTest_all_0
SharedClassesWorkloadTest_Softmx_Increase_0
SharedClassesWorkloadTest_Softmx_IncreaseDecrease_0
SharedClassesWorkloadTest_Softmx_Increase_JitAot_0

For the DaaLoadTest I'm not sure why the core file was generated. There is no javacore and the core hasn't been renamed by the VM.

For SharedClassesWorkloadTest_Softmx_Increase_0, I found the following in the Jvm2.stdout and requested dumps in the stderr. However overall the test passed.
```
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:401)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)

...

testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:401)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)

...

testFailure: testFileSystemIsRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to find intial provider 'memory0'
junit.framework.AssertionFailedError: Unable to find intial provider 'memory0'
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testFileSystemIsRegistered(FileSystemsTest.java:78)
```

**Comment by Mesbah-Alam** [comment]
I am investigating this.

**Comment by pshipton** [comment]
It would be interesting to discover if anybody actually uses the core files created in this way. They are not directly created as a result of the failure, but requested after the fact. I'm not sure if they are generally useful.

@DanHeidinga @andrewcraik @fjeremic

**Comment by Mesbah-Alam** [comment]
Ran a test with `-Xdump:none` provided in command line for the load test and found out that it does prevent stf load test framework to generate a dump: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_system/job/Grinder/1042/consoleFull 

Build above runs `SharedClassesWorkloadTest_Softmx_Increase_0 ` (where the same failure takes place in jvm2 (the mini-mix load test process) no dump is created: 

 ```
drwxrwxr-x 10 jenkins jenkins  4096 Dec 19 13:22 .
drwxrwxr-x 10 jenkins jenkins   233 Dec 19 12:51 ..
-rw-rw-r--  1 jenkins jenkins   527 Dec 19 12:52 10.SCV.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 10.SCV.stdout
-rw-rw-r--  1 jenkins jenkins  1622 Dec 19 12:52 11.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 11.SCC.stdout
-rw-rw-r--  1 jenkins jenkins   469 Dec 19 12:52 12.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 12.SCC.stdout
-rw-rw-r--  1 jenkins jenkins    45 Dec 19 12:52 13.SCV.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 13.SCV.stdout
-rw-rw-r--  1 jenkins jenkins   267 Dec 19 12:52 14.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 14.SCC.stdout
-rw-rw-r--  1 jenkins jenkins    45 Dec 19 12:52 15.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:52 15.SCC.stdout
-rw-rw-r--  1 jenkins jenkins   267 Dec 19 12:51 2.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:51 2.SCC.stdout
-rw-rw-r--  1 jenkins jenkins    45 Dec 19 12:51 3.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:51 3.SCC.stdout
-rw-rw-r--  1 jenkins jenkins 36446 Dec 19 12:51 4.Jvm1.executionlog.1.ltd
-rw-rw-r--  1 jenkins jenkins  8812 Dec 19 12:51 4.Jvm1.executionlog.ltm
drwxrwxr-x  4 jenkins jenkins    55 Dec 19 12:51 4.Jvm1.inventory
-rw-rw-r--  1 jenkins jenkins   331 Dec 19 12:51 4.Jvm1.stderr
-rw-rw-r--  1 jenkins jenkins 40124 Dec 19 12:51 4.Jvm1.stdout
-rw-rw-r--  1 jenkins jenkins   527 Dec 19 12:51 5.SCV.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:51 5.SCV.stdout
-rw-rw-r--  1 jenkins jenkins  1612 Dec 19 12:51 6.SCC.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:51 6.SCC.stdout
-rw-rw-r--  1 jenkins jenkins    48 Dec 19 12:51 7.SL2.stderr
-rw-rw-r--  1 jenkins jenkins     0 Dec 19 12:51 7.SL2.stdout
-rw-rw-r--  1 jenkins jenkins 36446 Dec 19 12:52 9.Jvm2.executionlog.1.ltd
-rw-rw-r--  1 jenkins jenkins  8812 Dec 19 12:51 9.Jvm2.executionlog.ltm
drwxrwxr-x  4 jenkins jenkins    55 Dec 19 12:51 9.Jvm2.inventory
-rw-rw-r--  1 jenkins jenkins   331 Dec 19 12:51 9.Jvm2.stderr
-rw-rw-r--  1 jenkins jenkins 40125 Dec 19 12:52 9.Jvm2.stdout
drwxrwxrwx  2 jenkins jenkins     6 Dec 19 12:52 cache
drwxrwxr-x  2 jenkins jenkins   176 Dec 19 12:51 directory_stream_files
-rw-rw-r--  1 jenkins jenkins   634 Dec 19 12:52 DirectoryTools.log
-rw-rw-r--  1 jenkins jenkins 11982 Dec 19 12:52 EchoServer.log
drwxrwxr-x  2 jenkins jenkins    88 Dec 19 12:51 mapped_file
drwxrwxr-x  2 jenkins jenkins     6 Dec 19 12:52 temporary
drwxrwxr-x  2 jenkins jenkins     6 Dec 19 12:51 walkfiletree_empty_files
drwxrwxr-x  2 jenkins jenkins   176 Dec 19 12:51 walkfiletree_files
[jenkins@rhel75x64rt3-1 results]$ vi 9.Jvm2.stdout
[jenkins@rhel75x64rt3-1 results]$ 
```

In jvm2.out file, we have an exception reported that indicates attempt to generate core dump failed:

```
12:51:49.272 - Failed to create a heapDump
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at net.adoptopenjdk.loadTest.FirstFailureDumper.createDump(FirstFailureDumper.java:134) [bin/:?]
        at net.adoptopenjdk.loadTest.FirstFailureDumper.createDumpIfFirstFailure(FirstFailureDumper.java:118) [bin/:?]
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.testFailure(JUnitAdaptor.java:84) [bin/:?]
        at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:63) [junit-4.12.jar:4.12]
        at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:142) [junit-4.12.jar:4.12]
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72) [junit-4.12.jar:4.12]
        at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:138) [junit-4.12.jar:4.12]
        at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:132) [junit-4.12.jar:4.12]
        at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.addError(JUnit38ClassRunner.java:43) [junit-4.12.jar:4.12]
        at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.addFailure(JUnit38ClassRunner.java:67) [junit-4.12.jar:4.12]
        at junit.framework.TestResult.addFailure(TestResult.java:50) [junit-4.12.jar:4.12]
        at junit.framework.TestResult.runProtected(TestResult.java:144) [junit-4.12.jar:4.12]
        at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
        at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
        at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
        at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
        at org.junit.runners.Suite.runChild(Suite.java:128) [junit-4.12.jar:4.12]
        at org.junit.runners.Suite.runChild(Suite.java:27) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115) [junit-4.12.jar:4.12]
        at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129) [bin/:?]
        at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177) [bin/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: com.ibm.jvm.InvalidDumpOptionException: Error in dump options.
        at com.ibm.jvm.Dump.triggerDumpsImpl(Native Method) ~[?:1.8.0_192]
        at com.ibm.jvm.Dump.triggerDump(Dump.java:566) ~[?:1.8.0_192]
        at com.ibm.jvm.Dump.heapDumpToFile(Dump.java:307) ~[?:1.8.0_192]
        ... 36 more
``` 

@pshipton  - should we go ahead with simply providing `-Xdump:none` - in the test so that the load tests do not generate core dumps unnecessarily? 

This is as simple fix, but not as graceful as adding a switch in stf (which will take longer to implement).

**Comment by pshipton** [comment]
If a load test crashed, would the test fail? We won't want -Xdump:none to stop core files from actual crashes. I think either adding the stf switch, or generally stop generating core files after the fact for test failures (depending on what Dan, Andrew, Filip think) are the better solutions.

**Comment by Mesbah-Alam** [comment]
I am adding the switch in stf. It will be a useful thing to have regardless of what the final decision ends up being.

**Comment by Mesbah-Alam** [comment]
We use the "load tests" in two scenarios - 
1) Where the load tests are run in form of "stress" tests (e.g. Mauve load tests)
2) Where the load tests are run in form of "workloads" (e.g. the softmx test above)

Core dumps may be useful for case (1). It is generally not required for case (2). 

We may want to have the behaviour of the framework to be as follows -  "do not generate dump unless switch is turned on". In that case we can have the switch turned on for case (1) only. 

Please comment.

**Comment by pshipton** [comment]
This is fine with me for now. I'd still like to determine if these cores are useful at all for case 1.

**Comment by fjeremic** [comment]
> It would be interesting to discover if anybody actually uses the core files created in this way. They are not directly created as a result of the failure, but requested after the fact. I'm not sure if they are generally useful.
> 
> @DanHeidinga @andrewcraik @fjeremic

@pshipton they are useful because often time we need to take a look at which method in the backtrace of the failure is actually compiled. i.e. we typically start from a reasonable point in the backtrace and check the method inlining table in the core file to figure out which method is the one that was JIT compiled and being executed at the time of the failure. We then proceed with the investigation via an `-Xdump:java+system:event=throw` targeting that specific method.

**Comment by DanHeidinga** [comment]
> hey are not directly created as a result of the failure, but requested after the fact. I'm not sure if they are generally useful.

I've rarely found these cores to be useful as they're created too far after the actual failure point.  If we're going to generate cores, I would rather see them be generated on uncaught exception using the -Xdump options.

**Comment by pshipton** [comment]
Believe the problem was resolved by turning off core file generation.
