### ISSUE TITLE
Test-sanity.functional linux_390-64_cmprssptrs J9vmTest J9vmTest_4 UnsafeArrayGetTest

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4089]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/526
```
+++ j9vm.test.unsafe.UnsafeArrayGetTest: +++
command: /home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/java -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m   -Xbootclasspath:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/s390x/compressedrefs/jclSC180/vm.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/se-service.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/rt.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/resources.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/jsse.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/charsets.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/jce.jar -classpath /home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK8-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.unsafe.UnsafeArrayGetTest 

Initializing data for class j9vm.test.unsafe.UnsafeArrayGetTest
Testing getLong() for byte[16]
Testing getLong() for short[8]
Testing getLong() for int[4]
Testing getLong() for long[2]
Testing getLong() for byte[1048576]
Testing getLong() for short[524288]
Testing getLong() for int[262144]
Testing getLong() for long[131072]
Testing getInt() for byte[16]
Testing getInt() for short[8]
Testing getInt() for int[4]
Testing getInt() for long[2]
Testing getInt() for byte[1048576]
Testing getInt() for short[524288]
Testing getInt() for int[262144]
Exception in thread "main" java.lang.Error: getInt() != manual read for offset=116969; expecting -1442430376; got -1442418049
	at j9vm.test.unsafe.UnsafeArrayGetTest.testGetInt(UnsafeArrayGetTest.java:313)
	at j9vm.test.unsafe.UnsafeArrayGetTest.main(UnsafeArrayGetTest.java:355)
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.unsafe.UnsafeArrayGetTest)
```

**Comment by pshipton** [comment]
Caused by https://github.com/eclipse/omr/pull/3337 I believe

**Comment by pshipton** [comment]
Fix is https://github.com/eclipse/omr/pull/3370

**Comment by fjeremic** [comment]
Both statements by Peter above are correct. I've verified the fix is working as intended.
