### ISSUE TITLE
OpenJ9 does not work with IntellijIDEA OSS from jetbrains

### ISSUE THREAD

**Issue by markehammons** [eclipse/openj9#41]
When I try to launch IntellijIDEA with the OpenJ9 JRE, I get the following error:

```
Internal error. Please report to http://jb.gg/ide/critical-startup-errors

io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)
    at org.jetbrains.io.BuiltInServer.bind(BuiltInServer.java:149)
    at org.jetbrains.io.BuiltInServer.start(BuiltInServer.java:118)
    at org.jetbrains.io.BuiltInServer.startNioOrOio(BuiltInServer.java:105)
    at com.intellij.idea.SocketLock.lambda$lock$2(SocketLock.java:153)
    at com.intellij.idea.SocketLock$$Lambda$189.000000007C182CE0.call(Unknown Source)
    at com.intellij.idea.SocketLock.underLocks(SocketLock.java:181)
    at com.intellij.idea.SocketLock.lock(SocketLock.java:128)
    at com.intellij.idea.StartupUtil.lockSystemFolders(StartupUtil.java:286)
    at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:122)
    at com.intellij.idea.MainImpl.start(MainImpl.java:34)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
    at com.intellij.ide.plugins.PluginManager.lambda$start$0(PluginManager.java:95)
    at com.intellij.ide.plugins.PluginManager$$Lambda$179.0000000024E69BD0.run(Unknown Source)
    at java.lang.Thread.run(java.base@9-internal/Thread.java:835)
Caused by: java.lang.NoClassDefFoundError: io.netty.buffer.ByteBufAllocator (initialization failure)
    at java.lang.J9VMInternals.initializationAlreadyFailed(java.base@9-internal/J9VMInternals.java:141)
    at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:56)
    at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:69)
    at io.netty.channel.socket.DefaultServerSocketChannelConfig.<init>(DefaultServerSocketChannelConfig.java:48)
    at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.<init>(NioServerSocketChannel.java:195)
    at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.<init>(NioServerSocketChannel.java:193)
    at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:87)
    at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72)
    at java.lang.J9VMInternals.newInstanceImpl(java.base@9-internal/Native Method)
    at java.lang.Class.newInstance(java.base@9-internal/Class.java:1954)
    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
    ... 21 more
Caused by: java.lang.UnsupportedOperationException: The method has not yet been implemented for now
    at java.lang.invoke.MethodHandles.privateLookupIn(java.base@9-internal/MethodHandles.java:1538)
    at java.util.concurrent.atomic.Striped64$1.run(java.base@9-internal/Striped64.java:390)
    at java.util.concurrent.atomic.Striped64$1.run(java.base@9-internal/Striped64.java:387)
    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
    at java.util.concurrent.atomic.Striped64.<clinit>(java.base@9-internal/Striped64.java:386)
    at io.netty.util.internal.PlatformDependent.newLongCounter(PlatformDependent.java:318)
    at io.netty.buffer.PoolArena.<init>(PoolArena.java:67)
    at io.netty.buffer.PoolArena$HeapArena.<init>(PoolArena.java:671)
    at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:236)
    at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:187)
    at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:176)
    at io.netty.buffer.PooledByteBufAllocator.<init>(PooledByteBufAllocator.java:162)
    at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:143)
    at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:79)
    at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24)
    ... 31 more
```

IntellijIDEA can be downloaded from [here](https://www.jetbrains.com/idea/download/index.html#section=linux). I am using the community edition. My OpenJ9 --version is
```
openjdk 9-internal
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170915_6 (JIT enabled, AOT enabled)
J9VM - cea1ed7
JIT  - cea1ed7
OMR  - 617de12
OpenJDK  - 83f5cd0 based on )
```

**Comment by steveniemitz** [comment]
Also seeing the same root cause using finagle stats:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(java.base@9-internal/J9VMInternals.java:191)
	at java.lang.J9VMInternals.recordInitializationFailure(java.base@9-internal/J9VMInternals.java:180)
	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:64)
	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:55)
	at java.lang.J9VMInternals.newInstanceImpl(java.base@9-internal/Native Method)
<snip>
Caused by: java.lang.UnsupportedOperationException: The method has not yet been implemented for now
	at java.lang.invoke.MethodHandles.privateLookupIn(java.base@9-internal/MethodHandles.java:1538)
	at java.util.concurrent.atomic.Striped64$1.run(java.base@9-internal/Striped64.java:390)
	at java.util.concurrent.atomic.Striped64$1.run(java.base@9-internal/Striped64.java:387)
	at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
	at java.util.concurrent.atomic.Striped64.<clinit>(java.base@9-internal/Striped64.java:386)
	... 53 more
```

**Comment by steveniemitz** [comment]
I patched `privateLookupIn` with the implementation from OpenJDK (plus a tiny tweak) and things seem good now!  I'm impressed even netty+tcnative worked on the first try!

**Comment by ben-walsh** [comment]
As another "data point", observed also with ElasticSearch (5.6.0) ...

```
cloudusr@benwalshopenj9testing:~/elasticsearch-5.6.0$ bin/elasticsearch
[2017-09-18T09:12:55,434][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-18T09:12:55,545][INFO ][o.e.e.NodeEnvironment    ] [O6Epyd0] using [1] data paths, mounts [[/ (/dev/vda1)]], net usable_space [65.8gb], net total_space [78.6gb], spins? [possibly], types [ext4]
[2017-09-18T09:12:55,546][INFO ][o.e.e.NodeEnvironment    ] [O6Epyd0] heap size [2gb], compressed ordinary object pointers [unknown]
[2017-09-18T09:12:55,577][INFO ][o.e.n.Node               ] node name [O6Epyd0] derived from node ID [O6Epyd0TSOiL0nRlaDDrzg]; set [node.name] to override
[2017-09-18T09:12:55,577][INFO ][o.e.n.Node               ] version[5.6.0], pid[29909], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.4.0-87-generic/amd64], JVM[Eclipse OpenJ9/Eclipse OpenJ9 VM/9-internal/2.9]
[2017-09-18T09:12:55,577][INFO ][o.e.n.Node               ] JVM arguments [-Xoptionsfile=/home/cloudusr/jdk-9+181/lib/options.default, -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple, -Xjcl:jclse9_29, -Dcom.ibm.oti.vm.bootstrap.library.path=/home/cloudusr/jdk-9+181/lib/compressedrefs:/home/cloudusr/jdk-9+181/lib, -Dsun.boot.library.path=/home/cloudusr/jdk-9+181/lib/compressedrefs:/home/cloudusr/jdk-9+181/lib, -Djava.library.path=/home/cloudusr/jdk-9+181/lib/compressedrefs:/home/cloudusr/jdk-9+181/lib:/usr/lib64:/usr/lib, -Djava.home=/home/cloudusr/jdk-9+181, -Duser.dir=/home/cloudusr/elasticsearch-5.6.0, -Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -server, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/home/cloudusr/elasticsearch-5.6.0, -Djava.class.path=/home/cloudusr/elasticsearch-5.6.0/lib/jna-4.4.0-1.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-core-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-sandbox-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-suggest-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/securesm-1.1.jar:/home/cloudusr/elasticsearch-5.6.0/lib/plugin-cli-5.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/log4j-api-2.9.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/snakeyaml-1.15.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-spatial-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-queryparser-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-misc-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-queries-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/spatial4j-0.6.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-memory-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/joda-time-2.9.5.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jts-1.13.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jackson-core-2.8.6.jar:/home/cloudusr/elasticsearch-5.6.0/lib/log4j-1.2-api-2.9.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/log4j-core-2.9.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-backward-codecs-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/t-digest-3.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jackson-dataformat-yaml-2.8.6.jar:/home/cloudusr/elasticsearch-5.6.0/lib/hppc-0.7.1.jar:/home/cloudusr/elasticsearch-5.6.0/lib/HdrHistogram-2.1.9.jar:/home/cloudusr/elasticsearch-5.6.0/lib/elasticsearch-5.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-join-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-spatial3d-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-highlighter-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-analyzers-common-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jopt-simple-5.0.2.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jackson-dataformat-cbor-2.8.6.jar:/home/cloudusr/elasticsearch-5.6.0/lib/java-version-checker-5.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/jackson-dataformat-smile-2.8.6.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-grouping-6.6.0.jar:/home/cloudusr/elasticsearch-5.6.0/lib/lucene-spatial-extras-6.6.0.jar, -Dsun.java.command=org.elasticsearch.bootstrap.Elasticsearch, -Dsun.java.launcher=SUN_STANDARD, -Dsun.java.launcher.pid=29909]
[2017-09-18T09:12:57,470][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [aggs-matrix-stats]
[2017-09-18T09:12:57,470][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [ingest-common]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [lang-expression]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [lang-groovy]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [lang-mustache]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [lang-painless]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [parent-join]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [percolator]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [reindex]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [transport-netty3]
[2017-09-18T09:12:57,471][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded module [transport-netty4]
[2017-09-18T09:12:57,472][INFO ][o.e.p.PluginsService     ] [O6Epyd0] loaded plugin [x-pack]
[2017-09-18T09:12:57,513][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:191) ~[?:?]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180) ~[?:?]
	at org.elasticsearch.common.metrics.CounterMetric.<init>(CounterMetric.java:28) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.<init>(EsAbortPolicy.java:30) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.common.util.concurrent.EsExecutors.newFixed(EsExecutors.java:78) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.threadpool.FixedExecutorBuilder.build(FixedExecutorBuilder.java:106) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.threadpool.FixedExecutorBuilder.build(FixedExecutorBuilder.java:39) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:199) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.node.Node.<init>(Node.java:325) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.0.jar:5.6.0]
Caused by: java.lang.UnsupportedOperationException: The method has not yet been implemented for now
	at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:1538) ~[?:?]
	at java.util.concurrent.atomic.Striped64$1.run(Striped64.java:390) ~[?:?]
	at java.util.concurrent.atomic.Striped64$1.run(Striped64.java:387) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:638) ~[?:?]
	at java.util.concurrent.atomic.Striped64.<clinit>(Striped64.java:386) ~[?:?]
	... 18 more
cloudusr@benwalshopenj9testing:~/elasticsearch-5.6.0$ echo $JAVA_HOME
/home/cloudusr/jdk-9+181
cloudusr@benwalshopenj9testing:~/elasticsearch-5.6.0$ /home/cloudusr/jdk-9+181/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170914_3 (JIT enabled, AOT enabled)
J9VM - 35f2a07
JIT  - 35f2a07
OMR  - 617de12
OpenJDK  - f35a4ea based on )
```

**Comment by gireeshpunathil** [comment]
Smallest test that recreates the issue:
```java
import java.util.concurrent.atomic.LongAdder;
public class Foo {
  public static void main(String args[]) {
   LongAdder str = new LongAdder();
 }
}
```
```ruby
bash$ java -Djava.security.policy=all.policy Foo
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(java.base/J9VMInternals.java:191)
	at java.lang.J9VMInternals.recordInitializationFailure(java.base/J9VMInternals.java:180)
	at Foo.main(Foo.java:4)
Caused by: java.lang.UnsupportedOperationException: The method has not yet been implemented for now
	at java.lang.invoke.MethodHandles.privateLookupIn(java.base/MethodHandles.java:1538)
	at java.util.concurrent.atomic.Striped64$1.run(java.base/Striped64.java:390)
	at java.util.concurrent.atomic.Striped64$1.run(java.base/Striped64.java:387)
	at java.security.AccessController.doPrivileged(java.base/AccessController.java:638)
	at java.util.concurrent.atomic.Striped64.<clinit>(java.base/Striped64.java:386)
	... 1 more
```
/cc @DanHeidinga @pshipton

**Comment by DanHeidinga** [comment]
Thanks for reporting this issue.  OpenJ9's Java 9 support is still a work in progress and there are a couple of MethodHandle apis that aren't complete.

@ChengJin01 has been working on these methods and will opening a PR to provide the implementation soon.

**Comment by steveniemitz** [comment]
Cool, good to hear!  Is there a way to build for java 8, or is this exclusively for java 9 right now?

**Comment by pshipton** [comment]
Exclusively for Java 9 atm, but we are looking at getting the Java 8 build working for OpenJ9.
