### ISSUE TITLE
Test-sanity.functional-JDK11-linux_x86-64 NullPointerException running javac

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4138]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/317
cmdLineTester_SCURLHelperTests_90_0
URLStaleClassPathEntryTest 2 and 3
```
Testing: URLStaleClassPathEntryTest 2
Test start time: 2018/12/20 05:32:27 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/java"  -Xnocompressedrefs -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=URLHelperTests --add-modules openj9.sharedclasses --add-exports java.base/Utilities=ALL-UNNAMED --add-reads java.base=openj9.sharedclasses --patch-module java.base=./Utils:.; StaleClassPathEntryTests.URLStaleClassPathEntryTest -testfile ./StaleClassPathEntryTests/props_unix/Test2.props -javacdir /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/../bin
Time spent starting: 2 milliseconds
Time spent executing: 5366 milliseconds
Test result: FAILED
 [OUT] 
 [OUT] ** urlsString: ./Alphabet;
 [OUT] classToLoad = A
 [OUT] classToLoad = B
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest2.sh /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] An exception has occurred in the compiler (11.0.1-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
 [OUT] java.lang.NullPointerException
 [OUT] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:282)
 [OUT] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:343)
 [OUT] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:58)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.file.RelativePath.resolveAgainst(RelativePath.java:60)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$DirectoryContainer.getFileObject(JavacFileManager.java:489)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:794)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:768)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:282)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:360)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1416)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:462)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1045)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:939)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
 [OUT] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
 [OUT] testResult = "true"
 [OUT] urlIndex = "0"
 [OUT] classToFind = "A"
 [OUT] 
 [OUT] Failure finding class: A on path: ./Alphabet; which is index: 0 result: true expecting: false
 [OUT] 
 [OUT] TEST FAILED
```

**Comment by pshipton** [comment]
Accidentally created. The failure is in the omr acceptance build

**Comment by pshipton** [comment]
A similar failure is seen in an OpenJ9 PR build.
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/14
cmdLineTester_SCURLClassLoaderTests_1
```
Testing: SignedSealed.BuildInitial1
Test start time: 2018/12/27 19:55:04 Coordinated Universal Time
Running command: sh ./SignedSealed/buildInitial1.sh /home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/build/linux-x86_64-normal-server-release/images/jdk/bin/../bin
Time spent starting: 1 milliseconds
Time spent executing: 2134 milliseconds
Test result: FAILED
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/A_Data.class(in = 446) (out= 288)(deflated 35%)
 [OUT] adding: jnurlcldr/shared/signedsealed/A_Main.class(in = 1218) (out= 649)(deflated 46%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 421) (out= 265)(deflated 37%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Dummy.class(in = 448) (out= 284)(deflated 36%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Data.class(in = 415) (out= 269)(deflated 35%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Dummy.class(in = 439) (out= 282)(deflated 35%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 421) (out= 265)(deflated 37%)
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Dummy.class(in = 448) (out= 284)(deflated 36%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Data.class(in = 415) (out= 269)(deflated 35%)
 [OUT] adding: jnurlcldr/shared/notsealed/C_Dummy.class(in = 439) (out= 282)(deflated 35%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/signedsealed/B_Data.class(in = 421) (out= 265)(deflated 37%)
 [OUT] AB.jar
 [OUT] B1.jar
 [OUT] B2.jar
 [ERR] rm: cannot remove '*.jar': No such file or directory
 [ERR] Fatal Error: Unable to find package java.lang in classpath or bootclasspath
 [ERR] An exception has occurred in the compiler (11.0.1-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
 [ERR] java.lang.NullPointerException
 [ERR] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:282)
 [ERR] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:343)
 [ERR] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:58)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.file.RelativePath.resolveAgainst(RelativePath.java:60)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$DirectoryContainer.getFileObject(JavacFileManager.java:489)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:794)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:768)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:282)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:360)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1416)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:462)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1045)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:939)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
 [ERR] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
>> Success condition was found: [Output match: AB.jar]
>> Failure condition was not found: [Output match: Usage:]
>> Failure condition was not found: [Output match: no such]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was found: [Output match: Error:]
```

**Comment by pshipton** [comment]
I expect this is JIT related. @andrewcraik

**Comment by pdbain-ibm** [comment]
FYI, there was a javac bug a while ago involving soft (or maybe weak) references. It went something like:
```
myRef = new SoftReference(new SomeClass());
myObject = myRef.get();
myObject.someMethod();
```
Occasionally, `myRef` would get cleared between the `new` and the `get`.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/132

**Comment by pshipton** [comment]
```
    @Override
    public final JrtPath resolve(Path other) {
        final JrtPath o = checkPath(other);
        if (this.path.length() == 0 || o.isAbsolute()) {
            return o;
        }
        if (o.path.length() == 0) {
            return this;
        }
        StringBuilder sb = new StringBuilder(path.length() + o.path.length() + 1);
        sb.append(path);
        if (path.charAt(path.length() - 1) != '/')
            sb.append('/');
        sb.append(o.path);
        return new JrtPath(jrtfs, sb.toString(), true);   <- line 282
    }
```

**Comment by andrewcraik** [comment]
@yanluo7 could you take a look?

**Comment by pshipton** [comment]
I've set this a high priority as it seems to fail fairly often, sometimes blocking omr acceptance.

**Comment by yanluo7** [comment]
Based on the `JrtPath resolve(Path other)` code Peter provided:
```
       StringBuilder sb = new StringBuilder(path.length() + o.path.length() + 1);
        sb.append(path);
        if (path.charAt(path.length() - 1) != '/')
            sb.append('/');
        sb.append(o.path);
        return new JrtPath(jrtfs, sb.toString(), true);   <- NPE thrown line 282
```
It thinks `sb` is somehow null, where has just been allocated and does not escape this method. Possible sb gets stack allocated and somewhere there was a bug in EA?

**Comment by pshipton** [comment]
I wonder if this is related to AOT and shared classes being enabled by default. Shared classes by default was disabled yesterday, and the builds last night ran clean. I'm going to run some functional sanity testing and see if this problem still occurs.
I ran this
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/16/
also trying a grinder
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/161/

**Comment by pshipton** [comment]
The problem didn't re-create in my builds.

**Comment by pshipton** [comment]
I'll keep an eye out to see if the problem occurs again now that shared classes by default has been disabled. It was occurring fairly frequently in omr acceptance builds.

**Comment by pshipton** [comment]
To state the obvious, even if disabling shared classes by default made it go away, this is not a fix. The problem still needs to be identified and fixed, as
a) it could affect something else using -Xshareclasses
b) we will re-enable shared classes by default in the future

**Comment by pshipton** [comment]
@yanluo7 I've got a simple reproducible case. Although it may be tricky to reproduce on another machine. The following should work to reproduce the problem, although I haven't tried it on another machine. On my machine the NPE occurs every time.

- You need to use the shared cache [cache.zip](https://github.com/eclipse/openj9/files/2753982/cache.zip). Change the "pete" part of the cache name to the username  you are using and put it in the /home/<username>/javasharedresources directory. 
- You need to use the following JVM, using any other JVM will automatically destroy the shared cache and create a new one. If this link expires I have a copy.
https://ci.eclipse.org/openj9/job/Build-JDK11-linux_x86-64/453/artifact/OpenJ9-JDK11-linux_x86-64-20190110-151412.tar.gz
- To cause the NPE, run javac on a simple .java file, the content doesn't matter. I used Hello.java `public class Hello { }`

**Comment by pshipton** [comment]
btw, there is AOT in the cache for
```
1: 0x00007F23466BFE80 AOT: resolve Signature: (Ljava/nio/file/Path;)Ljdk/internal/jrtfs/JrtPath; Address: 0x00007F23356C7E98
        for ROMClass jdk/internal/jrtfs/JrtPath at 0x00007F23356C6D20.
```

**Comment by yanluo7** [comment]
Using the cache,zip and the jdk from Peter I wasn't able to reproduce the NPE. So I tried to build and run the test locally, I am now running it on poisonivy in a loop. So far the reproducibility seems really low, I've only seem 1 failure in over 50 runs.

**Comment by pshipton** [comment]
Reproducibility may be related to timing and the machine being used. It occurred more than 1/50 on the machine I was using. However once the "bad" AOT gets into the shared cache, the NPE occurs every time.

**Comment by yanluo7** [comment]
Narrowed down to this AOT method: `jdk/internal/jrtfs/JrtPath.resolve(Ljava/lang/String;)Ljdk/internal/jrtfs/JrtPath;`

```
0x7f5b480b9c70 {jdk/internal/jrtfs/JrtPath.resolve} +1264  18:108  48b800f37c405b7f0000 mov       rax, 0x7f5b407cf300 J9Class - {jdk/internal/jrtfs/JrtPath}
0x7f5b480b9c7a {jdk/internal/jrtfs/JrtPath.resolve} +1274          4c8d240500000000     lea       r12, qword ptr [rax]
0x7f5b480b9c82 {jdk/internal/jrtfs/JrtPath.resolve} +1282          488b4560             mov       rax, qword ptr [rbp+0x60] J9VMThread.heapAlloc // TLH Alloc
0x7f5b480b9c86 {jdk/internal/jrtfs/JrtPath.resolve} +1286          4c8d7030             lea       r14, qword ptr [rax+0x30]
0x7f5b480b9c8a {jdk/internal/jrtfs/JrtPath.resolve} +1290          4c3b7568             cmp       r14, qword ptr [rbp+0x68] J9VMThread.heapTop
0x7f5b480b9c8e {jdk/internal/jrtfs/JrtPath.resolve} +1294          0f87c2110000         ja        0x7f5b480bae56 C>> +5846 
0x7f5b480b9c94 {jdk/internal/jrtfs/JrtPath.resolve} +1300          4c897560             mov       qword ptr [rbp+0x60], r14 J9VMThread.heapAlloc
0x7f5b480b9c98 {jdk/internal/jrtfs/JrtPath.resolve} +1304          c5                   UNKNOWN OPCODE
0x7f5b480b9c99 {jdk/internal/jrtfs/JrtPath.resolve} +1305          f9                   stc
0x7f5b480b9c9a {jdk/internal/jrtfs/JrtPath.resolve} +1306          ef                   out       dx, eax
0x7f5b480b9c9b {jdk/internal/jrtfs/JrtPath.resolve} +1307          c0c5fa               rol       ch, 250
0x7f5b480b9c9e {jdk/internal/jrtfs/JrtPath.resolve} +1310          7f40                 jg        0x7f5b480b9ce0 C>> +1376 
0x7f5b480b9ca0 {jdk/internal/jrtfs/JrtPath.resolve} +1312          08c5                 or        ch, al
0x7f5b480b9ca2 {jdk/internal/jrtfs/JrtPath.resolve} +1314          fa                   cli
0x7f5b480b9ca3 {jdk/internal/jrtfs/JrtPath.resolve} +1315          7f40                 jg        0x7f5b480b9ce5 C>> +1381 
0x7f5b480b9ca5 {jdk/internal/jrtfs/JrtPath.resolve} +1317          18c5                 sbb       ch, al
0x7f5b480b9ca7 {jdk/internal/jrtfs/JrtPath.resolve} +1319          f9                   stc
0x7f5b480b9ca8 {jdk/internal/jrtfs/JrtPath.resolve} +1320          d6                   UNKNOWN OPCODE
0x7f5b480b9ca9 {jdk/internal/jrtfs/JrtPath.resolve} +1321          40284c8920           sub       byte ptr [rcx+rcx*4+0x20], cl
0x7f5b480b9cae {jdk/internal/jrtfs/JrtPath.resolve} +1326          4c8be8               mov       r13, rax <<< ^+5875
0x7f5b480b9cb1 {jdk/internal/jrtfs/JrtPath.resolve} +1329          488b8c2488000000     mov       rcx, qword ptr [rsp+0x88]
0x7f5b480b9cb9 {jdk/internal/jrtfs/JrtPath.resolve} +1337          4c8b7110             mov       r14, qword ptr [rcx+0x10]
0x7f5b480b9cbd {jdk/internal/jrtfs/JrtPath.resolve} +1341          0f1f440000           nop       eax, dword ptr [rax+rax]
0x7f5b480b9cc2 {jdk/internal/jrtfs/JrtPath.resolve} +1346          0f1f440000           nop       eax, dword ptr [rax+rax]
0x7f5b480b9cc7 {jdk/internal/jrtfs/JrtPath.resolve} +1351          48b9484913405b7f0000 mov       rcx, 0x7f5b40134948 Ptr 
0x7f5b480b9cd1 {jdk/internal/jrtfs/JrtPath.resolve} +1361          833c0d0000000000     cmp       dword ptr [rcx], 0
0x7f5b480b9cd9 {jdk/internal/jrtfs/JrtPath.resolve} +1369          0f84c8020000         je        0x7f5b480b9fa7 C>> +2087 
0x7f5b480b9cdf {jdk/internal/jrtfs/JrtPath.resolve} +1375          4183791800           cmp       dword ptr [r9+0x18], 0
0x7f5b480b9ce4 {jdk/internal/jrtfs/JrtPath.resolve} +1380          400f94c7             sete      dil
0x7f5b480b9ce8 {jdk/internal/jrtfs/JrtPath.resolve} +1384          400fb6ff             movzx     edi, dil
0x7f5b480b9cec {jdk/internal/jrtfs/JrtPath.resolve} +1388          85ff                 test      edi, edi <<< ^+2089 ^+4458
0x7f5b480b9cee {jdk/internal/jrtfs/JrtPath.resolve} +1390          0f8519070000         jne       0x7f5b480ba40d C>> +3213 
0x7f5b480b9cf4 {jdk/internal/jrtfs/JrtPath.resolve} +1396          498b5910             mov       rbx, qword ptr [r9+0x10]
0x7f5b480b9cf8 {jdk/internal/jrtfs/JrtPath.resolve} +1400          458b411c             mov       r8d, dword ptr [r9+0x1c]
0x7f5b480b9cfc {jdk/internal/jrtfs/JrtPath.resolve} +1404          0f1f440000           nop       eax, dword ptr [rax+rax]
0x7f5b480b9d01 {jdk/internal/jrtfs/JrtPath.resolve} +1409          49b95820142ca87f0000 mov       r9, 0x7fa82c142058 
0x7f5b480b9d0b {jdk/internal/jrtfs/JrtPath.resolve} +1419          42833c0d0000000000   cmp       dword ptr [r9], 0       <--- NPE 
0x7f5b480b9d14 {jdk/internal/jrtfs/JrtPath.resolve} +1428          7438                 je        0x7f5b480b9d4e C>> +1486 
0x7f5b480b9d16 {jdk/internal/jrtfs/JrtPath.resolve} +1430          4d8bc8               mov       r9, r8
0x7f5b480b9d19 {jdk/internal/jrtfs/JrtPath.resolve} +1433          4c896c2468           mov       qword ptr [rsp+0x68], r13
0x7f5b480b9d1e {jdk/internal/jrtfs/JrtPath.resolve} +1438          4c89742460           mov       qword ptr [rsp+0x60], r14
0x7f5b480b9d23 {jdk/internal/jrtfs/JrtPath.resolve} +1443          488bc3               mov       rax, rbx
0x7f5b480b9d26 {jdk/internal/jrtfs/JrtPath.resolve} +1446          33f6                 xor       esi, esi
0x7f5b480b9d28 {jdk/internal/jrtfs/JrtPath.resolve} +1448          418bd1               mov       edx, r9d
0x7f5b480b9d2b {jdk/internal/jrtfs/JrtPath.resolve} +1451          0f1f440000           nop       eax, dword ptr [rax+rax]
0x7f5b480b9d30 {jdk/internal/jrtfs/JrtPath.resolve} +1456  43:9    e8321e0000           call      0x7f5b480bbb67 U>> +9191 Snippet-> 
0x7f5b480b9d35 {jdk/internal/jrtfs/JrtPath.resolve} +1461          4c8b742460           mov       r14, qword ptr [rsp+0x60]
0x7f5b480b9d3a {jdk/internal/jrtfs/JrtPath.resolve} +1466          4c8b6c2468           mov       r13, qword ptr [rsp+0x68]
0x7f5b480b9d3f {jdk/internal/jrtfs/JrtPath.resolve} +1471          4d8bc1               mov       r8, r9
0x7f5b480b9d42 {jdk/internal/jrtfs/JrtPath.resolve} +1474          488bf8               mov       rdi, rax
0x7f5b480b9d45 {jdk/internal/jrtfs/JrtPath.resolve} +1477          4885ff               test      rdi, rdi
0x7f5b480b9d48 {jdk/internal/jrtfs/JrtPath.resolve} +1480          0f8560020000         jne       0x7f5b480b9fae C>> +2094 
0x7f5b480b9d4e {jdk/internal/jrtfs/JrtPath.resolve} +1486          498bf8               mov       rdi, r8 <<< +1428
0x7f5b480b9d51 {jdk/internal/jrtfs/JrtPath.resolve} +1489          0f1f8000000000       nop       eax, dword ptr [rax]
0x7f5b480b9d58 {jdk/internal/jrtfs/JrtPath.resolve} +1496  43:31   e8f71d0000           call      0x7f5b480bbb54 U>> +9172 Snippet-> 
0x7f5b480b9d5d {jdk/internal/jrtfs/JrtPath.resolve} +1501          00            (Data)
0x7f5b480b9d5e {jdk/internal/jrtfs/JrtPath.resolve} +1502          0000                 add       byte ptr [rax], al
0x7f5b480b9d60 {jdk/internal/jrtfs/JrtPath.resolve} +1504          0000                 add       byte ptr [rax], al
```
The NPE is thrown from : 
```
0x7f5b480b9d01 {jdk/internal/jrtfs/JrtPath.resolve} +1409          49b95820142ca87f0000 mov       r9, 0x7fa82c142058
0x7f5b480b9d0b {jdk/internal/jrtfs/JrtPath.resolve} +1419          42833c0d0000000000   cmp       dword ptr [r9], 0       <--- NPE 
```
The value `0x7fa82c142058 ` is likely not relocated. These look like some kind of inline guard, but we can't completely sure. I've been trying to get a jit log with the failing method but once I start logging the method, I wasn't able to reproduce it in over 1000 runs.

**Comment by yanluo7** [comment]
So we are still trying to reproduce the problem while getting a trace log of the `JrtPath.resolve` method, in order to understand how the problematic instructions were generated. Logging a method while running the test seems to change the timing such that the NPE becomes even more intermittent. In addition to my local setup, Peter is also running in a loop on his machine to try to get a reproduction.

**Comment by pshipton** [comment]
Removing the prio:high label since this problem occurred regularly when shared classes was enabled by default, but shared classes by default has been disabled.

**Comment by yanluo7** [comment]
So I asked Devin to take a look at the failing `cmp` instruction, we discovered that the cmp instruction and the mov immediately before it seem to be loading a static from String -- java/lang/String.COMPACT_STRINGS. But so far we haven't found what could have caused the missed relocation -- hard to imagine it could happen to a common static load.

**Comment by yanluo7** [comment]
I have been trying a number of different options to try and coax a trace log from the run. What makes it difficult is the testcase tries to run javac on a number of very small Java source file, so the javac finishes very quickly, and the chance of generating the bad method before the javac finishes is really low. So far a few different options have been tried.
 `-Xaot:forceAOT,initialOptLevel=warm,verbose={compilePerformance},vlog=./vlog,dontInline={jdk/internal/jrtfs/JrtPath.resolve(Ljava/lang/String;*},{jdk/internal/jrtfs/JrtPath.resolve(Ljava/lang/String;*}(traceFull,traceCG,log=JrtPath.resolve)`
`rtResolve`
`disableAsyncCompilation`

**Comment by yanluo7** [comment]
With the following option I was able to get a trace log of the failing method. 
```"-Xaot:disableAsyncCompilation,forceAOT,initialOptLevel=warm,verbose={compilePerformance},vlog=./vlog,tryToInline={java/lang/StringUTF16.newString*},dontInline={jdk/internal/jrtfs/JrtPath.resolve(Ljava/lang/String;)Ljdk/internal/jrtfs/JrtPath;},{jdk/internal/jrtfs/JrtPath.resolve(Ljava/lang/String;)Ljdk/internal/jrtfs/JrtPath;}(count=15,traceFull,traceCG,log=JrtPath.resolve)"```
Unfortunately the inlining stops just before the problematic inlined method : `{java/lang/StringUTF16.newString}`, one more level of inlining it would have included it. I'm trying `tryToInline` option to hopefully force it to get inlined.

**Comment by pshipton** [comment]
There is no fix yet, but this is not a blocker for the 0.12 release. Moving to the next milestone.

**Comment by yanluo7** [comment]
Adding `tryToInline` did not make the inlining of `java/lang/StringUTF16.newString` happen, so I added some inliner trace options to find out why. However, after I added `traceInlining,debugInliner`, the inlining gets even less - the top level method inlined even less methods. This is very peculiar and discouraging.

**Comment by yanluo7** [comment]
After some exhaustive investigation work with Irwin, we are pretty sure what the issue was. The instruction that caused the NPE was from loading the static String.COMPACT_STRINGS under AOT. We found the relocation record was generated for this static load, but there are a number of methods that were inlined that did not have a guard (`Unloaded Method!` below). Because there's no guard for these methods, the inline table entry for them is incomplete; during an AOT load, we just ignore relocation records associated with these methods. Moreover, due to symbol sharing, a relocation record could appear to belong to a different inline target, which complicates the issue further. 
```
Inlined Calls: J9Method, Index, Caller, ByteCode, {Class.Method} (49 inlined method(s))
   0x00007f5b407d0760    0      -1       2 (  2)    {jdk/internal/jrtfs/JrtPath.getFileSystem}
   0x00007f5b407ce6e0    1      -1      10 (  a)    {jdk/internal/jrtfs/JrtFileSystem.getPath}
   0x00007f5b407d05a0    2       1      11 (  b)    {jdk/internal/jrtfs/JrtPath.<init>}
   0x00007f5b40128aa0    3       2       1 (  1)    {java/lang/Object.<init>}
   0x00007f5b407d0920    4       2      11 (  b)    {jdk/internal/jrtfs/JrtPath.normalize}
   0x00007f5b40137590    5       4       1 (  1)    {java/lang/String.length}
   0x00007f5b401375b0    6       5       1 (  1)    {java/lang/String.lengthInternal}
   0xffffffffffffffff    7       1      19 ( 13)    Unloaded Method! // {java/lang/StringBuilder.<init>()V}
   0xffffffffffffffff    8       7       3 (  3)    Unloaded Method! // java/lang/AbstractStringBuilder.<init>(I)V
   0xffffffffffffffff    9       8       1 (  1)    Unloaded Method! // java/lang/Object.<init>()V
   0xffffffffffffffff   10       8      27 ( 1b)    Unloaded Method! // java/lang/StringUTF16.newBytesFor(I)[B
   0xffffffffffffffff   11       1      25 ( 19)    Unloaded Method! // java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   0xffffffffffffffff   12       1      56 ( 38)    Unloaded Method! // java/lang/String.length()I
   0xffffffffffffffff   13      12       1 (  1)    Unloaded Method!
   0xffffffffffffffff   14       1      63 ( 3f)    Unloaded Method! // java/lang/StringBuilder.length()I
   0xffffffffffffffff   15      14       1 (  1)    Unloaded Method!
   0xffffffffffffffff   16       1      72 ( 48)    Unloaded Method! // java/lang/StringBuilder.append(C)Ljava/lang/StringBuilder;
   0xffffffffffffffff   17       1      79 ( 4f)    Unloaded Method! // java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
   0x00007f5b407d07a0   18      -1      13 (  d)    {jdk/internal/jrtfs/JrtPath.resolve}
   0x00007f5b407d08c0   19      18       2 (  2)    {jdk/internal/jrtfs/JrtPath.checkPath}
```
Under new AOT on linux X64, this issue would not have manifested as the error handling there allows us to just fail to do the AOT load. In order to fix this properly, @dsouzai will create another issue documenting various problems and fixes in both old and new AOT.

**Comment by dsouzai** [comment]
This issue is an instance of the general problem described by https://github.com/eclipse/openj9/issues/4621 . Once https://github.com/eclipse/openj9/issues/3752 is completed and the SVM is enabled even during startup, this particular test failure will go away.
