### ISSUE TITLE
Test-sanity.functional-JDK11-linux_x86-64 shareclasses HelperCompatibilityTest failures due to ClassNotFoundException

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#4166]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/344/tapResults/

```
Testing: HelperCompatibilityTest 10
Test start time: 2019/01/02 16:42:17 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/java"  -Xnocompressedrefs -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=HelperCompatibilityTests -Xbootclasspath/a:./Utils:. URLHelperURLClassPathHelperCompatibilityTest -testfile "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/shareClassTests/SCHelperCompatibilityTests/props_unix/Test9.props"
Time spent starting: 2 milliseconds
Time spent executing: 505 milliseconds
Test result: FAILED
 [OUT] 
 [OUT] Failure finding class: A result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
 [ERR] java.lang.ClassNotFoundException: E
 [ERR] 	at CustomClassloaders.CustomURLLoader.findClass(CustomURLLoader.java:240)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
 [ERR] 	at CustomClassloaders.CustomURLLoader.loadClassFrom(CustomURLLoader.java:117)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.executeTest(URLHelperURLClassPathHelperCompatibilityTest.java:136)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.run(URLHelperURLClassPathHelperCompatibilityTest.java:110)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.main(URLHelperURLClassPathHelperCompatibilityTest.java:51)
 [ERR] java.lang.ClassNotFoundException: F
 [ERR] 	at CustomClassloaders.CustomURLLoader.findClass(CustomURLLoader.java:240)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
 [ERR] 	at CustomClassloaders.CustomURLLoader.loadClassFrom(CustomURLLoader.java:117)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.executeTest(URLHelperURLClassPathHelperCompatibilityTest.java:136)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.run(URLHelperURLClassPathHelperCompatibilityTest.java:110)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.main(URLHelperURLClassPathHelperCompatibilityTest.java:51)
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was found: [Output match: Exception:]
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/358

**Comment by fengxue-IS** [comment]
Looking into this

**Comment by pshipton** [comment]
If these tests run javac, I wonder if it is related to https://github.com/eclipse/openj9/issues/4138

**Comment by pshipton** [comment]
There are other tests which fail as well. i.e.
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/384
cmdLineTester_SCURLClassLoaderNPTests_1
```
esting: FindStore.BuildInitial
Test start time: 2019/01/10 16:53:57 Coordinated Universal Time
Running command: sh ./FindStore/buildInitial.sh /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/../bin ../FindStore/sharedClassesResults
Time spent starting: 2 milliseconds
Time spent executing: 3879 milliseconds
Test result: FAILED
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/A_Main$Data.class(in = 697) (out= 432)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/A_Main.class(in = 1171) (out= 630)(deflated 46%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/B_Dummy$Data.class(in = 701) (out= 429)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/B_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/C_Dummy$Data.class(in = 701) (out= 428)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/C_Dummy.class(in = 504) (out= 320)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/D_Dummy$Data.class(in = 676) (out= 415)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/D_Dummy.class(in = 504) (out= 320)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/E_Main$Data.class(in = 697) (out= 432)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/E_Main.class(in = 1171) (out= 630)(deflated 46%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/F_Dummy$Data.class(in = 701) (out= 430)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/F_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/G_Dummy$Data.class(in = 701) (out= 430)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/G_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/H_Dummy$Data.class(in = 676) (out= 414)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/H_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/I_Main$Data.class(in = 697) (out= 432)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/I_Main.class(in = 1171) (out= 630)(deflated 46%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/J_Dummy$Data.class(in = 701) (out= 429)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/J_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/K_Dummy$Data.class(in = 701) (out= 428)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/K_Dummy.class(in = 504) (out= 321)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: jnurlcldr/shared/findstore/L_Dummy$Data.class(in = 676) (out= 413)(deflated 38%)
 [OUT] adding: jnurlcldr/shared/findstore/L_Dummy.class(in = 504) (out= 320)(deflated 36%)
 [OUT] added manifest
 [OUT] adding: nothing.txt(in = 7) (out= 9)(deflated -28%)
 [OUT] A.jar
 [OUT] B.jar
 [OUT] C.jar
 [OUT] D.jar
 [OUT] E.jar
 [OUT] F.jar
 [OUT] G.jar
 [OUT] H.jar
 [OUT] Nothing.jar
 [ERR] Fatal Error: Unable to find package java.lang in classpath or bootclasspath
>> Success condition was found: [Output match: A.jar]
>> Failure condition was not found: [Output match: Usage:]
>> Failure condition was not found: [Output match: no such]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was found: [Output match: Error:]
```

https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/366
cmdLineTester_SCURLHelperTests_90_0 - explicit NullPointerException JrtPath.resolve #4138
cmdLineTester_SCHelperCompatibilityTests_unix_0 
```
Testing: HelperCompatibilityTest 10
Test start time: 2019/01/10 17:13:03 Coordinated Universal Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/java"  -Xnocompressedrefs -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=HelperCompatibilityTests -Xbootclasspath/a:./Utils:. URLHelperURLClassPathHelperCompatibilityTest -testfile "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/shareClassTests/SCHelperCompatibilityTests/props_unix/Test9.props"
Time spent starting: 1 milliseconds
Time spent executing: 497 milliseconds
Test result: FAILED
 [OUT] 
 [OUT] Failure finding class: A result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
 [ERR] java.lang.ClassNotFoundException: E
 [ERR] 	at CustomClassloaders.CustomURLLoader.findClass(CustomURLLoader.java:240)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
 [ERR] 	at CustomClassloaders.CustomURLLoader.loadClassFrom(CustomURLLoader.java:117)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.executeTest(URLHelperURLClassPathHelperCompatibilityTest.java:136)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.run(URLHelperURLClassPathHelperCompatibilityTest.java:110)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.main(URLHelperURLClassPathHelperCompatibilityTest.java:51)
 [ERR] java.lang.ClassNotFoundException: F
 [ERR] 	at CustomClassloaders.CustomURLLoader.findClass(CustomURLLoader.java:240)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
 [ERR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
 [ERR] 	at CustomClassloaders.CustomURLLoader.loadClassFrom(CustomURLLoader.java:117)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.executeTest(URLHelperURLClassPathHelperCompatibilityTest.java:136)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.run(URLHelperURLClassPathHelperCompatibilityTest.java:110)
 [ERR] 	at URLHelperURLClassPathHelperCompatibilityTest.main(URLHelperURLClassPathHelperCompatibilityTest.java:51)
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was found: [Output match: Exception:]
```

**Comment by fengxue-IS** [comment]
testing with current master branch, did not see any failure. 

Enabling sharedclasses to check if failure related to enabling sharedClasses by default

**Comment by pshipton** [comment]
Closing as a dup of #4138
