### ISSUE TITLE
Test-extended.system-JDK11-linux_x86-64 NullPointerException JrtPath.resolve

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4199]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/132
```
01:02:27 build-java:
01:02:27     [javac] Compiling 3 source files to /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64/openjdk-tests/systemtest/openj9-systemtest/openj9.stf.extensions/bin
01:02:27     [javac] An exception has occurred in the compiler (11.0.1-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
01:02:27     [javac] java.lang.NullPointerException
01:02:27     [javac] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:282)
01:02:27     [javac] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:343)
01:02:27     [javac] 	at java.base/jdk.internal.jrtfs.JrtPath.resolve(JrtPath.java:58)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.file.RelativePath.resolveAgainst(RelativePath.java:60)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$DirectoryContainer.getFileObject(JavacFileManager.java:489)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForInput(JavacFileManager.java:794)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getJavaFileForInput(JavacFileManager.java:768)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:282)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findModuleInfo(ModuleFinder.java:360)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findAllModules(ModuleFinder.java:191)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.getUnnamedModuleCompleter(Modules.java:1416)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:462)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1045)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:939)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
01:02:27     [javac] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by pshipton** [comment]
Dup of #4138
