### ISSUE TITLE
UnknownHostException: ub16x64j96 and Connection refused on ub16x64j93, ub16x64j94

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4200]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/188
```
LT  Test failed:
LT  java.net.UnknownHostException: ub16x64j96: ub16x64j96: Name or service not known
LT  	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
LT  	at gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2.<init>(DatagramPacketTest2.java:70)
LT  	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
LT  	at java.lang.Class.newInstance(Class.java:1847)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:52)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:813)
LT  Caused by: java.net.UnknownHostException: ub16x64j96: Name or service not known
LT  	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
LT  	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
LT  	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
LT  	... 8 more
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
@cwillhelm I think the hostname may be messed up on the 2-6 unb machines. Can you please have a look. I will disable them in the meantime. I'm not sure if these are 2 separate issues or 2 issues with the same root cause.

**Comment by AdamBrousseau** [comment]
rerunning those 2 test jobs now
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_x86-64_cmprssptrs/187/
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/190/

**Comment by AdamBrousseau** [comment]
Builds are green. Will re-enable 2-6.
