### ISSUE TITLE
JTReg test fails - java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java and java/lang/String/Chars.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4301]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java consistently fails with multiple failures like this ...

```
test SpliteratorTraversingAndSplittingTest.testIntForEach(""𐀀".codePoints().spliterator()", [65536], SpliteratorTraversingAndSplittingTest$SpliteratorOfIntCharDataBuilder$$Lambda$212/000000007C214660@7d9ec70c): failure
java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:267)
	at org.testng.Assert.assertEquals(Assert.java:277)
	at java.base/java.util.SpliteratorTestHelper.testForEach(SpliteratorTestHelper.java:267)
	at java.base/java.util.SpliteratorTestHelper.testForEach(SpliteratorTestHelper.java:174)
	at SpliteratorTraversingAndSplittingTest.testIntForEach(SpliteratorTraversingAndSplittingTest.java:875)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

See https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/812/consoleText.
The failures can be found by searching for ": failure".

The commonality of the failures is the use of <String> containing the character 𐀀.

Running the following on my Linux developer machine ...

```
walshbp@bendev:~$ cat CodePointTest.java
public class CodePointTest {

	public static void main(String[] args) {

		String testCharSeq = "𐀀";	
		System.out.println("testCharSeq : " + testCharSeq);	
		System.out.println("codePoints count : " + testCharSeq.codePoints().count());
		
		System.out.println("codePoints values ...");
		testCharSeq.codePoints().forEach(System.out::println);
	
	}
	
}
walshbp@bendev:~$ openjdk11-hotspot-binary/jdk-11.0.1+13/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901131929)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13-201901131929, mixed mode)
walshbp@bendev:~$ openjdk11-hotspot-binary/jdk-11.0.1+13/bin/javac CodePointTest.java
walshbp@bendev:~$ openjdk11-hotspot-binary/jdk-11.0.1+13/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 1
codePoints values ...
65536
walshbp@bendev:~$ openjdk11-openj9-binary/jdk-11.0.1+13/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901131910)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-827f2551a, JRE 11 Linux amd64-64-Bit Compressed References 20190113_92 (JIT enabled, AOT enabled)
OpenJ9   - 827f2551a
OMR      - 11cdf3e2
JCL      - 8fcb1a0231 based on jdk-11.0.1+13)
walshbp@bendev:~$ openjdk11-openj9-binary/jdk-11.0.1+13/bin/javac CodePointTest.java
walshbp@bendev:~$ openjdk11-openj9-binary/jdk-11.0.1+13/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 2
codePoints values ...
65536
56320
```

... shows the difference in values returned from the <CharSequence>.codePoints() impl.

This is leading to the observed failures.

**Comment by ben-walsh** [comment]
This is a regression since the latest release ...

```
walshbp@bendev:~$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux amd64-64-Bit Compressed References 20181115_18 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)
walshbp@bendev:~$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/bin/javac CodePointTest.java 
walshbp@bendev:~$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 1
codePoints values ...
65536
```

**Comment by ben-walsh** [comment]
Run against my local Mac laptop, demonstrating this is a cross platform issue ...

```
bens-mbp:~ ben_walsh@uk.ibm.com$ cat CodePointTest.java
public class CodePointTest {

	public static void main(String[] args) {

		String testCharSeq = "𐀀";
		System.out.println("testCharSeq : " + testCharSeq);
		System.out.println("codePoints count : " + testCharSeq.codePoints().count());
		
		System.out.println("codePoints values ...");
		testCharSeq.codePoints().forEach(System.out::println);

	
	}
	
}
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-hotspot-binary-releases/jdk-11.0.1+13/Contents/Home/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-hotspot-binary-releases/jdk-11.0.1+13/Contents/Home/bin/javac CodePointTest.java
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-hotspot-binary-releases/jdk-11.0.1+13/Contents/Home/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 1
codePoints values ...
65536
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901141930)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-d9b58020a, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190114_91 (JIT enabled, AOT enabled)
OpenJ9   - d9b58020a
OMR      - 11cdf3e2
JCL      - 8fcb1a0231 based on jdk-11.0.1+13)
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/javac CodePointTest.java
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 2
codePoints values ...
65536
56320
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/Contents/Home/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181115_16 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/Contents/Home/bin/javac CodePointTest.java
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-releases/jdk-11.0.1+13/Contents/Home/bin/java CodePointTest
testCharSeq : 𐀀
codePoints count : 1
codePoints values ...
65536
```

**Comment by andrewcraik** [comment]
@ben-walsh do these failures occur with -Xint?

**Comment by ben-walsh** [comment]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/String/Chars.java also appears to be failing as a result of this problem too ...

```
java.lang.RuntimeException: chars/codePoints() failed!
	at Chars.testCPs(Chars.java:86)
	at Chars.main(Chars.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)```

**Comment by ben-walsh** [comment]
@andrewcraik My basic test, yes ...
```
walshbp@bendev:~$ cat CodePointTest.java
public class CodePointTest {

	public static void main(String[] args) {

		String testCharSeq = "𐀀";
		//String testCharSeq = "𐀁";
		//String testCharSeq = "a";
		System.out.println("testCharSeq : " + testCharSeq);	
		System.out.println("codePoints count : " + testCharSeq.codePoints().count());
		
		System.out.println("codePoints values ...");
		testCharSeq.codePoints().forEach(System.out::println);
	
	}
	
}
walshbp@bendev:~$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901131910)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-827f2551a, JRE 11 Linux amd64-64-Bit Compressed References 20190113_92 (JIT enabled, AOT enabled)
OpenJ9   - 827f2551a
OMR      - 11cdf3e2
JCL      - 8fcb1a0231 based on jdk-11.0.1+13)
walshbp@bendev:~$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/bin/javac CodePointTest.java
walshbp@bendev:~$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/bin/java -Xint CodePointTest
testCharSeq : 𐀀
codePoints count : 2
codePoints values ...
65536
56320
walshbp@bendev:~$ uname -a
Linux bendev 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I'll kick off runs of both with -Xint on Jenkins to confirm those.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/806

**Comment by ben-walsh** [comment]
@andrewcraik 
FYI - looks like first time these tests failed like this for the scheduled nightly runs was - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/140. Hopefully that will narrow down what introduced the regression.

**Comment by ben-walsh** [comment]
@andrewcraik
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/840 : -Xint of java/util/Spliterator/SpliteratorTraversingAndSplittingTest.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/841 : -Xint of java/lang/String/Chars.java

**Comment by ben-walsh** [comment]
@andrewcraik My basic test with -Xint on Mac also still shows the regression ...
```
bens-mbp:~ ben_walsh@uk.ibm.com$ cat CodePointTest.java
public class CodePointTest {

	public static void main(String[] args) {

		String testCharSeq = "𐀀";
		System.out.println("testCharSeq : " + testCharSeq);
		System.out.println("codePoints count : " + testCharSeq.codePoints().count());
		
		System.out.println("codePoints values ...");
		testCharSeq.codePoints().forEach(System.out::println);

	
	}
	
}
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/javac CodePointTest.java
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/java -Xint CodePointTest
testCharSeq : 𐀀
codePoints count : 2
codePoints values ...
65536
56320
bens-mbp:~ ben_walsh@uk.ibm.com$ uname -a
Darwin bens-mbp.hursley.uk.ibm.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
bens-mbp:~ ben_walsh@uk.ibm.com$ openjdk11-openj9-binary-nightly/jdk-11.0.1+13/Contents/Home/bin/java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901141930)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-d9b58020a, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190114_91 (JIT enabled, AOT enabled)
OpenJ9   - d9b58020a
OMR      - 11cdf3e2
JCL      - 8fcb1a0231 based on jdk-11.0.1+13)
```

**Comment by ben-walsh** [comment]
@andrewcraik
Same results for both tests with -Xint ...
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/840
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/841

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by DanHeidinga** [comment]
Possibly related to https://github.com/eclipse/openj9/pull/3528

**Comment by pdbain-ibm** [comment]
Will investigate.

**Comment by keithc-ca** [comment]
> Possibly related to #3528

I expect that is it; and it will occur with `-Xint`.

**Comment by pdbain-ibm** [comment]
The code is not handling the surrogates.

**Comment by pshipton** [comment]
@pdbain-ibm fyi https://github.com/eclipse/openj9/pull/4321
