### ISSUE TITLE
jdk-11.0.2+7 failure: org.openj9.test.runlast.Test_JavaNetWithSideEffectsShouldRunLast

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#4313]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/19/

Message: should have created URL: java.lang.Error: java.lang.IllegalAccessException: Class org/openj9/test/runlast/Test_JavaNetWithSideEffectsShouldRunLast$1(unnamed module 0x000000008358BE00) can not access class sun/net/www/protocol/jrt/Handler(module java.base) because module module java.base does not export package sun/net/www/protocol/jrt to module unnamed module 0x000000008358BE00

Stacktrace:

at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.openj9.test.runlast.Test_JavaNetWithSideEffectsShouldRunLast.test_getResource(Test_JavaNetWithSideEffectsShouldRunLast.java:61) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/functional/Java8andUp/GeneralTest.jar)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from jrt:/java.base
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
at java.base/java.lang.reflect.Method.invoke(Method.java:566) from jrt:/java.base
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)
at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@b1dded40(file:/home/jenkins/workspace/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJDK11/openj9/jvmtest/TestConfig/lib/testng.jar)

**Comment by DanHeidinga** [comment]
@ChengJin01 @tajila Can you two take a look at this and see why we're throwing the exception here?

**Comment by ChengJin01** [comment]
It seems the test cases failed at:
/Java8andUp/src/org/openj9/test/runlast/Test_JavaNetWithSideEffectsShouldRunLast.java
```
	try {
		URL url = ClassLoader.getSystemClassLoader().getResource("java/lang/Object.class"); <------
		AssertJUnit.assertTrue("URL should not be null", url != null);
	} catch (Throwable e) {
		e.printStackTrace();
		AssertJUnit.fail("should have created URL: " + e);
	}
```
Given that the error message was generated from J9NLS_VM_ILLEGAL_ACCESS_MODULE_EXPORT (related to J9_VISIBILITY_MODULE_PACKAGE_EXPORT_ERROR),  need to check which function called checkModuleAccess() in the code.

**Comment by ChengJin01** [comment]
It is probably because we didn't export in sun.net.www.protocol.jrt in test case as follows:
`--add-exports java.base/sun.net.www.protocol.jrt=ALL-UNNAMED`
The test case passed by adding the requested package to /Java8andUp/playlist.xml

**Comment by tajila** [comment]
Tyoically sun.* classes are not exported so its likely that we need to update our test.

This test also fails on hotspot VM
```
openjdk version "11.0.2" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.2+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7, mixed mode)
```

**Comment by ChengJin01** [comment]
Already confirmed the test ended up with the same failure on Hotspot
[failed_Hotspot_java11.txt](https://github.com/eclipse/openj9/files/2766039/failed_Hotspot_java11.txt)

and the test passed with "--add-exports java.base/sun.net.www.protocol.jrt=ALL-UNNAMED" on both OpenJ9 and Hotspot

[ok_hotspot_java11_updated_playlist.txt](https://github.com/eclipse/openj9/files/2766042/ok_hotspot_java11_updated_playlist.txt)
[ok_openj9_java11_updated_playlist.txt](https://github.com/eclipse/openj9/files/2766043/ok_openj9_java11_updated_playlist.txt)

Will create a PR with the fix soon.
