### ISSUE TITLE
JTReg test fail - MacOS : java/nio/channels/SocketChannel/AdaptSocket.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4317]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/nio/channels/SocketChannel/AdaptSocket.java fails consistently on Mac OS with the following ...

```
java.lang.Exception: Should time out, but not, data: [102, 111, 111, 13, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at AdaptSocket.testRead(AdaptSocket.java:106)
	at AdaptSocket.testRead(AdaptSocket.java:143)
	at AdaptSocket.main(AdaptSocket.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Successful run against Linux x86_64 - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/240/testReport/java_nio_channels_SocketChannel_AdaptSocket/java/AdaptSocket

No such problem against HotSpot on MacOS - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_macos/98/testReport/java_nio_channels_SocketChannel_AdaptSocket/java/AdaptSocket

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/810

**Comment by ben-walsh** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/854/consoleText - 10x with timeout reduced from 10 to 1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/855/consoleText - 10x with timeout reduced from 10 to 1 and -Xint

Notable and suspicious difference in behaviour for the 4th repetition in both these runs (search for "timeout: 1" in the output) - there is a SocketTimeoutException as expected (https://github.com/ben-walsh/openj9-openjdk-jdk11/blob/invAdaptSocket/test/jdk/java/nio/channels/SocketChannel/AdaptSocket.java#L116) from the read attempt (https://github.com/ben-walsh/openj9-openjdk-jdk11/blob/invAdaptSocket/test/jdk/java/nio/channels/SocketChannel/AdaptSocket.java#L104) but then the first of the subsequent checks (https://github.com/ben-walsh/openj9-openjdk-jdk11/blob/invAdaptSocket/test/jdk/java/nio/channels/SocketChannel/AdaptSocket.java#L144) succeeds.

Running a 100x job to ascertain any pattern - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/856/consoleText.

**Comment by ben-walsh** [comment]
Interesting set of results from https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/856/consoleText ...

99 runs failed - search for "jdk_custom_0_FAILED"

Of those 5 runs where the correct exception is thrown, then read works, as reported in https://github.com/eclipse/openj9/issues/4317#issuecomment-455249735 - search for "Read timed out, as expected".

Remaining 94 failed runs as reported https://github.com/eclipse/openj9/issues/4317#issue-399884334

1 run passed - search for "jdk_custom_0_PASSED"

Rerunning for further evidence (and fixing to the same test machine as used in https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/856/consoleText) - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/869/consoleText

**Comment by ben-walsh** [comment]
Another set of interesting results from https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/869/consoleText ...

Again 99 runs failed - search for "jdk_custom_0_FAILED"

Of those 8 runs where the correct exception is thrown once, then read wrongly works - search for "loop: 0 STDERR:"

1 runs where the correct exception is thrown twice, then read wrongly works - search for "loop: 1 STDERR:"

1 runs where the correct exception is thrown thrice, then read wrongly works - search for "loop: 2 STDERR:"

2 runs where the correct exception is thrown four times, then read wrongly works - search for "loop: 3 STDERR:"

Rerunning 200x with -Xint - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/873/consoleText
