### ISSUE TITLE
Error parsing TAP Stream

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4323]
Although the testing seems passed, the final result is not green.

Internal testing job/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/331
```
13:46:12 TOTAL: 210   EXECUTED: 124   PASSED: 124   FAILED: 0   SKIPPED: 86
13:46:12 ALL TESTS PASSED
13:46:12 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
13:46:12 
13:46:12 _sanity.functional done
13:46:12 make: Leaving directory `/home/jenkins/workspace/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/openjdk-tests/functional'
[Pipeline] sh
13:46:14 ++ uname
13:46:14 + '[' Linux = AIX ']'
13:46:14 + MAKE=make
13:46:14 + make -f ./openjdk-tests/TestConfig/testEnv.mk testEnvTeardown
13:46:14 make: Nothing to be done for `testEnvTeardown'.
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
13:46:14 TAP Reports Processing: START
13:46:14 Looking for TAP results report in workspace using pattern: **/*.tap
13:46:15 Saving reports...
13:46:15 Processing '/var/jenkins_home/jobs/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/builds/331/tap-master-files/openjdk-tests/TestConfig/test_output_15476607614305/TestTargetResult.tap'
13:46:15 Parsing TAP test result [/var/jenkins_home/jobs/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/builds/331/tap-master-files/openjdk-tests/TestConfig/test_output_15476607614305/TestTargetResult.tap].
13:46:15 org.tap4j.parser.ParserException: Error parsing TAP Stream: Error parsing YAML [ok 2 - stringConcatOptTest_0
13:46:15   ---
13:46:15 ok 3 - jit_jitt_0
13:46:15   ---
13:46:15 ok 4 - jit_jitt_1
13:46:15   ---
13:46:15 ok 5 - jit_jitt_2
13:46:15   ---
13:46:15 ok 6 - jit_jitt_3
13:46:15   ---
13:46:15 ok 7 - jit_jitt_XCEEHDLR_0 # skip
13:46:15   ---
13:46:15 ok 8 - jit_jitt_XCEEHDLR_1 # skip
13:46:15   ---
13:46:15 ok 9 - jit_jitt_XCEEHDLR_2 # skip
13:46:15   ---
13:46:15 ok 10 - jit_jitt_XCEEHDLR_3 # skip
13:46:15   ---
13:46:15 ok 11 - jit_jar_0
13:46:15   ---
13:46:15 ok 12 - jit_tr_0
13:46:15   ---
13:46:15 ok 13 - StringPeepholeTest_0
13:46:15   ---
13:46:15 ok 14 - jit_ra_0
13:46:15   ---
13:46:15 ok 15 - jit_vich_0
13:46:15   ---
13:46:15 ok 16 - jsr335tests_SE80_0 # skip
13:46:15   ---
13:46:15 ok 17 - jsr335tests_SE80_1 # skip
13:46:15   ---
13:46:15 ok 18 - jsr335tests_SE80_2 # skip
13:46:15   ---
13:46:15 ok 19 - jsr335tests_SE80_3 # skip
13:46:15   ---
13:46:15 ok 20 - jsr335tests_SE80_4 # skip
13:46:15   ---
13:46:15 ok 21 - jsr335tests_defendersupersends_SE80_0 # skip
13:46:15   ---
13:46:15 ok 22 - TestFlushReflectionCache_SE80_0
13:46:15   ---
13:46:15 ok 23 - TestFlushReflectionCache_SE80_1 # skip
13:46:15   ---
13:46:15 ok 24 - TestFlushReflectionCache_SE80_2 # skip
13:46:15   ---
13:46:15 ok 25 - TestRefreshGCSpecialClassesCache_NOBCI_SE80_0
13:46:15   ---
13:46:15 ok 26 - TestRefreshGCSpecialClassesCache_NOBCI_SE80_1 # skip
13:46:15   ---
13:46:15 ok 27 - TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_SE80_0
13:46:15   ---
13:46:15 ok 28 - TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_SE80_1 # skip
13:46:15   ---
13:46:15 ok 29 - TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_SE80_0 # skip
13:46:15   ---
13:46:15 ok 30 - cmdLineTester_GCCheck_SE80_0 # skip
13:46:15   ---
13:46:15 ok 31 - cmdLineTester_GCCheck_SE80_1
13:46:15   ---
13:46:15 ok 32 - cmdLineTester_GCCheck_SE80_2 # skip
13:46:15   ---
13:46:15 ok 33 - cmdLineTester_GCCheck_SE80_3 # skip
13:46:15   ---
13:46:15 ok 34 - cmdLineTester_GCCheck_SE80_4
13:46:15   ---
13:46:15 ok 35 - TestHashTablePerformance_0 # skip
13:46:15   ---
13:46:15 ok 36 - TestHashTablePerformance_1
13:46:15   ---
13:46:15 ok 37 - TestHashTablePerformance_2
13:46:15   ---
13:46:15 ok 38 - TestHashTableCorrectness_0 # skip
13:46:15   ---
13:46:15 ok 39 - TestHashTableCorrectness_1
13:46:15   ---
13:46:15 ok 40 - TestHashTableCorrectness_2
13:46:15   ---
13:46:15 ok 41 - jit_jitt_IBM_Internal_0
13:46:15   ---
13:46:15 ok 42 - jit_jitt_IBM_Internal_1
13:46:15   ---
13:46:15 ok 43 - jit_jitt_IBM_Internal_2
13:46:15   ---
13:46:15 ok 44 - jit_jitt_IBM_Internal_3
13:46:15   ---
13:46:15 ok 45 - jit_jitt_XCEEHDLR_IBM_Internal_0 # skip
13:46:15   ---
13:46:15 ok 46 - jit_jitt_XCEEHDLR_IBM_Internal_1 # skip
13:46:15   ---
13:46:15 ok 47 - jit_jitt_XCEEHDLR_IBM_Internal_2 # skip
13:46:15   ---
13:46:15 ok 48 - jit_jitt_XCEEHDLR_IBM_Internal_3 # skip
13:46:15   ---
13:46:15 ok 49 - cmdLineTester_J9securityTests_0
13:46:15   ---
13:46:15 ok 50 - cmdLineTest_J9test_SE80_0
13:46:15   ---
13:46:15 ok 51 - cmdLineTest_sigxfszHandlingTest_0
13:46:15   ---
13:46:15 ok 52 - cmdLineTester_DataHelperTests_0 # skip
13:46:15   ---
13:46:15 ok 53 - cmdLineTester_DataHelperTests_1
13:46:15   ---
13:46:15 ok 54 - cmdLineTester_SCCommandLineOptionTests_0 # skip
13:46:15   ---
13:46:15 ok 55 - cmdLineTester_SCCommandLineOptionTests_1
13:46:15   ---
13:46:15 ok 56 - cmdLineTester_ShareClassesSimpleSanity_0 # skip
13:46:15   ---
13:46:15 ok 57 - cmdLineTester_ShareClassesSimpleSanity_1
13:46:15   ---
13:46:15 ok 58 - testSCCMLListALLCaches_0 # skip
13:46:15   ---
13:46:15 ok 59 - testSCCMLListALLCaches_1
13:46:15   ---
13:46:15 ok 60 - testSCCMLExpireAndListALLCaches_0 # skip
13:46:15   ---
13:46:15 ok 61 - cmdLineTester_StoreFilterTests_win_0 # skip
13:46:15   ---
13:46:15 ok 62 - cmdLineTester_StoreFilterTests_unix_0 # skip
13:46:15   ---
13:46:15 ok 63 - testSCCMLTests1_openj9_0 # skip
13:46:15   ---
13:46:15 ok 64 - testSCCMLTests1_openj9_1
13:46:15   ---
13:46:15 ok 65 - cmdLineTester_SCHelperCompatibilityTests_win_0 # skip
13:46:15   ---
13:46:15 ok 66 - cmdLineTester_SCHelperCompatibilityTests_win_1 # skip
13:46:15   ---
13:46:15 ok 67 - cmdLineTester_SCHelperCompatibilityTests_unix_0 # skip
13:46:15   ---
13:46:15 ok 68 - cmdLineTester_SCHelperCompatibilityTests_unix_1
13:46:15   ---
13:46:15 ok 69 - cmdLineTester_SCURLHelperTests_80_0 # skip
13:46:15   ---
13:46:15 ok 70 - cmdLineTester_SCURLHelperTests_80_1
13:46:15   ---
13:46:15 ok 71 - cmdLineTester_loopReduction_0
13:46:15   ---
13:46:15 ok 72 - cmdLineTester_GCRegressionTests_0 # skip
13:46:15   ---
13:46:15 ok 73 - cmdLineTester_GCRegressionTests_1 # skip
13:46:15   ---
13:46:15 ok 74 - cmdLineTester_GCRegressionTests_2
13:46:15   ---
13:46:15 ok 75 - cmdLineTester_GCRegressionTests_3
13:46:15   ---
13:46:15 ok 76 - cmdLineTester_GCRegressionTests_Mode301_0 # skip
13:46:15   ---
13:46:15 ok 77 - cmdLineTest_gpTest_0
13:46:15   ---
13:46:15 ok 78 - cmdLineTester_jrvTest_0
13:46:15   ---
13:46:15 ok 79 - cmdLineTester_XcheckJNI_0
13:46:15   ---
13:46:15 ok 80 - cmdLineTester_gcsuballoctests_0
13:46:15   ---
13:46:15 ok 81 - testXXArgumentTesting_0
13:46:15   ---
13:46:15 ok 82 - cmdLineTester_ignoreunrecognizedvmoptions_0
13:46:15   ---
13:46:15 ok 83 - cmdLineTester_jvmtitests_0 # skip
13:46:15   ---
13:46:15 ok 84 - cmdLineTester_jvmtitests_1
13:46:15   ---
13:46:15 ok 85 - cmdLineTester_jvmtitests_2
13:46:15   ---
13:46:15 ok 86 - cmdLineTester_jvmtitests_3 # skip
13:46:15   ---
13:46:15 ok 87 - cmdLineTester_jvmtitests_4 # skip
13:46:15   ---
13:46:15 ok 88 - cmdLineTester_jvmtitests_5
13:46:15   ---
13:46:15 ok 89 - cmdLineTester_jvmtitests_6 # skip
13:46:15   ---
13:46:15 ok 90 - cmdLineTester_jvmtitests_7
13:46:15   ---
13:46:15 ok 91 - cmdLineTester_jvmtitests_8
13:46:15   ---
13:46:15 ok 92 - cmdLineTester_jvmtitests_hcr_SE80_0 # skip
13:46:15   ---
13:46:15 ok 93 - cmdLineTester_jvmtitests_hcr_SE80_1 # skip
13:46:15   ---
13:46:15 ok 94 - cmdLineTester_jvmtitests_hcr_SE80_2 # skip
13:46:15   ---
13:46:15 ok 95 - cmdLineTester_jvmtitests_hcr_SE80_3 # skip
13:46:15   ---
13:46:15 ok 96 - cmdLineTester_jvmtitests_hcr_SE80_4
13:46:15   ---
13:46:15 ok 97 - cmdLineTester_jvmtitests_hcr_SE80_5 # skip
13:46:15   ---
13:46:15 ok 98 - cmdLineTester_jvmtitests_hcr_SE80_6 # skip
13:46:15   ---
13:46:15 ok 99 - cmdLineTester_jvmtitests_hcr_SE80_7
13:46:15   ---
13:46:15 ok 100 - cmdLineTester_jvmtitests_hcr_SE80_8
13:46:15   ---
13:46:15 ok 101 - cmdLineTester_jvmtitests_hcr_SE80_9 # skip
13:46:15   ---
13:46:15 ok 102 - cmdLineTester_jvmtitests_hcr_SE80_10
13:46:15   ---
13:46:15 ok 103 - cmdLineTester_jvmtitests_debug_0 # skip
13:46:15   ---
13:46:15 ok 104 - cmdLineTester_jvmtitests_debug_1 # skip
13:46:15   ---
13:46:15 ok 105 - cmdLineTester_jvmtitests_debug_2 # skip
13:46:15   ---
13:46:15 ok 106 - cmdLineTester_jvmtitests_debug_3
13:46:15   ---
13:46:15 ok 107 - cmdLineTester_jvmtitests_debug_4 # skip
13:46:15   ---
13:46:15 ok 108 - cmdLineTester_jvmtitests_debug_5
13:46:15   ---
13:46:15 ok 109 - cmdLineTester_jvmtitests_debug_6 # skip
13:46:15   ---
13:46:15 ok 110 - cmdLineTester_jvmtitests_debug_7
13:46:15   ---
13:46:15 ok 111 - cmdLineTester_jvmtitests_debug_8
13:46:15   ---
13:46:15 ok 112 - cmdLineTester_jvmtitests_debug_9
13:46:15   ---
13:46:15 ok 113 - cmdLineTester_jvmtitests_debug_10 # skip
13:46:15   ---
13:46:15 ok 114 - cmdLineTester_jvmtitests_debug_11
13:46:15   ---
13:46:15 ok 115 - cmdLineTester_decompilationTests_0 # skip
13:46:15   ---
13:46:15 ok 116 - cmdLineTester_decompilationTests_1
13:46:15   ---
13:46:15 ok 117 - decompileAtMethodResolve_0
13:46:15   ---
13:46:15 ok 118 - cmdLineTester_test_0
13:46:15   ---
13:46:15 ok 119 - cmdLineTester_libpathTestRtf_0
13:46:15   ---
13:46:15 ok 120 - cmdLineTester_libpathTestRtfChild_0
13:46:15   ---
13:46:15 ok 121 - cmdLineTester_SCURLClassLoaderTests_SE80_0 # skip
13:46:15   ---
13:46:15 ok 122 - cmdLineTester_SCURLClassLoaderTests_SE80_1
13:46:15   ---
13:46:15 ok 123 - cmdLineTester_SCURLClassLoaderNPTests_SE80_0 # skip
13:46:15   ---
13:46:15 ok 124 - cmdLineTester_SCURLClassLoaderNPTests_SE80_1
13:46:15   ---
13:46:15 ok 125 - cmdLineTester_pltest_0
13:46:15   ---
13:46:15 ok 126 - cmdLineTester_pltest_aix_0 # skip
13:46:15   ---
13:46:15 ok 127 - cmdLineTester_pltest_CEEHDLR_0 # skip
13:46:15   ---
13:46:15 ok 128 - cmdLineTester_pltest_numcpus_bound_linux_0
13:46:15   ---
13:46:15 ok 129 - cmdLineTester_pltest_numcpus_bound_aix_0 # skip
13:46:15   ---
13:46:15 ok 130 - cmdLineTester_pltest_hyp_HV_vmware_0 # skip
13:46:15   ---
13:46:15 ok 131 - cmdLineTester_pltest_hyp_HV_kvm_0 # skip
13:46:15   ---
13:46:15 ok 132 - cmdLineTester_callsitedbgddrext_openj9_0
13:46:15   ---
13:46:15 ok 133 - cmdLineTester_loadLibraryTests_0 # skip
13:46:15   ---
13:46:15 ok 134 - jsr335_interfaceStaticMethod_0 # skip
13:46:15   ---
13:46:15 ok 135 - JLM_Tests_interface_SE80_0
13:46:15   ---
13:46:15 ok 136 - JLM_Tests_interface_SE80_1
13:46:15   ---
13:46:15 ok 137 - JLM_Tests_class_SE80_0
13:46:15   ---
13:46:15 ok 138 - JLM_Tests_class_SE80_1
13:46:15   ---
13:46:15 ok 139 - JLM_Tests_IBMinternal_SE80_0
13:46:15   ---
13:46:15 ok 140 - JLM_Tests_IBMinternal_SE80_1
13:46:15   ---
13:46:15 ok 141 - J9vmTest_0 # skip
13:46:15   ---
13:46:15 ok 142 - J9vmTest_1 # skip
13:46:15   ---
13:46:15 ok 143 - J9vmTest_2
13:46:15   ---
13:46:15 ok 144 - J9vmTest_3 # skip
13:46:15   ---
13:46:15 ok 145 - J9vmTest_4
13:46:15   ---
13:46:15 ok 146 - J9vmTest_5
13:46:15   ---
13:46:15 ok 147 - jvmnativestest_0
13:46:15   ---
13:46:15 ok 148 - SharedClassesSysVTesting_0
13:46:15   ---
13:46:15 ok 149 - SharedCPEntryInvokerTests_0
13:46:15   ---
13:46:15 ok 150 - SharedCPEntryInvokerTests_1
13:46:15   ---
13:46:15 ok 151 - testDDRExt_General_win_0 # skip
13:46:15   ---
13:46:15 ok 152 - testDDRExt_Callsites_win_0 # skip
13:46:15   ---
13:46:15 ok 153 - UnsafeTests_SE80_0
13:46:15   ---
13:46:15 ok 154 - UnsafeTests_SE80_1
13:46:15   ---
13:46:15 ok 155 - generalSanityTest_0
13:46:15   ---
13:46:15 ok 156 - truncatedReturnTest_0
13:46:15   ---
13:46:15 ok 157 - regressionFastresolve_mode110_0 # skip
13:46:15   ---
13:46:15 ok 158 - regressionFastresolve_mode150_0
13:46:15   ---
13:46:15 ok 159 - jsr335_interfacePrivateMethod_mode100_0 # skip
13:46:15   ---
13:46:15 ok 160 - AttachAPISanity_SE80_0
13:46:15   ---
13:46:15 ok 161 - CtorBCVTests_0
13:46:15   ---
13:46:15 ok 162 - OpenSSL_0
13:46:15   ---
13:46:15 ok 163 - JCL_Test_SE80_0
13:46:15   ---
13:46:15 ok 164 - JCL_Test_SE80_1
13:46:15   ---
13:46:15 ok 165 - JCL_Test_OutOfMemoryError_SE80_0
13:46:15   ---
13:46:15 ok 166 - JCL_Test_OutOfMemoryError_SE80_1
13:46:15   ---
13:46:15 ok 167 - J9VMInternals_Test_SE80_0
13:46:15   ---
13:46:15 ok 168 - J9VMInternals_Test_SE80_1
13:46:15   ---
13:46:15 ok 169 - JCL_TEST_Java-Security_SE80_0
13:46:15   ---
13:46:15 ok 170 - JCL_Test_JITHelpers_SE80_0
13:46:15   ---
13:46:15 ok 171 - JCL_TEST_MathMethods_0
13:46:15   ---
13:46:15 ok 172 - TestArrayCopy_0 # skip
13:46:15   ---
13:46:15 ok 173 - TestArrayCopy_1 # skip
13:46:15   ---
13:46:15 ok 174 - TestArrayCopy_2
13:46:15   ---
13:46:15 ok 175 - TestArrayCopy_3
13:46:15   ---
13:46:15 ok 176 - pthreadDestructor_0
13:46:15   ---
13:46:15 ok 177 - testReflectInvoke_0
13:46:15   ---
13:46:15 ok 178 - testInvokeSpecialInsideInterface_0
13:46:15   ---
13:46:15 ok 179 - reflect_0
13:46:15   ---
13:46:15 ok 180 - NoSuchMethodTests_0
13:46:15   ---
13:46:15 ok 181 - reattachAfterExit_0
13:46:15   ---
13:46:15 ok 182 - JCL_Test_Package_0
13:46:15   ---
13:46:15 ok 183 - hanoiTest_0
13:46:15   ---
13:46:15 ok 184 - hanoiTestTM_NATIVE_0 # skip
13:46:15   ---
13:46:15 ok 185 - hanoiTestTM_MEDIUM_0 # skip
13:46:15   ---
13:46:15 ok 186 - hanoiTestTM_HEAVY_0 # skip
13:46:15   ---
13:46:15 ok 187 - hanoiTestTM_SHOULDFAIL_0 # skip
13:46:15   ---
13:46:15 ok 188 - memleaksTest_0
13:46:15   ---
13:46:15 ok 189 - fibTest_0
13:46:15   ---
13:46:15 ok 190 - testStringInterning_0 # skip
13:46:15   ---
13:46:15 ok 191 - testStringInterning_1
13:46:15   ---
13:46:15 ok 192 - testStringIndexOfString_0
13:46:15   ---
13:46:15 ok 193 - testStringIndexOfString_1
13:46:15   ---
13:46:15 ok 194 - testStringStreams_0
13:46:15   ---
13:46:15 ok 195 - floatSanityTests_0
13:46:15   ---
13:46:15 ok 196 - floatSanityTests_1 # skip
13:46:15   ---
13:46:15 ok 197 - floatSanityTests_2
13:46:15   ---
13:46:15 ok 198 - FileSystem-isAccessUserOnlyTests_SE80_0
13:46:15   ---
13:46:15 ok 199 - algotest2_0
13:46:15   ---
13:46:15 ok 200 - ctest_0
13:46:15   ---
13:46:15 ok 201 - jniargtests_0
13:46:15   ---
13:46:15 ok 202 - vmtest_0
13:46:15   ---
13:46:15 ok 203 - jsigjnitest_0
13:46:15   ---
13:46:15 ok 204 - gc_rwlocktest_0
13:46:15   ---
13:46:15 ok 205 - gc_rwlocktest_win_0 # skip
13:46:15   ---
13:46:15 ok 206 - shrtest_linux_SE80_0
13:46:15   ---
13:46:15 ok 207 - shrtest_zos_SE80_0 # skip
13:46:15   ---
13:46:15 ok 208 - shrtest_aix_SE80_0 # skip
13:46:15   ---
13:46:15 ok 209 - shrtest_win_SE80_0 # skip
13:46:15   ---
13:46:15 ok 210 - thrstatetest_0
13:46:15   ---
13:46:15 ]: expected '<document start>', but found Scalar
13:46:15  in 'string', line 12, column 3:
13:46:15       ---
13:46:15       ^
13:46:15 
13:46:15 	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:230)
13:46:15 	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:193)
13:46:15 	at org.tap4j.plugin.TapParser.parse(TapParser.java:167)
13:46:15 	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:540)
13:46:15 	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:412)
13:46:15 	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:371)
13:46:15 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
13:46:15 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
13:46:15 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:46:15 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:46:15 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:46:15 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:46:15 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:46:15 	at java.lang.Thread.run(Thread.java:748)
13:46:15 Caused by: org.tap4j.parser.ParserException: Error parsing YAML [ok 2 - stringConcatOptTest_0
```

**Comment by pshipton** [comment]
@smlambert @llxia

**Comment by smlambert** [comment]
Yes it indicates that some test is producing output characters that are causing Tap parser to choke.

**Comment by pshipton** [comment]
I expect it needs to be resolved asap. It occurs with the jdk8 u202-b08 build we need for the release. Possibly upgrading to this jdk level will cause all sanity.functional testing to not show as green.

**Comment by smlambert** [comment]
In my opinion, you do not need the Jenkins TAP plugin in to work and subsequently a prettified Jenkins display to show as green, in order to know the tests pass (as you can look in console output and see that they did).  The step to produce the .tap file fails.  Agree that it needs to be fixed, but feel its not a blocker.

Also, this is likely not to be looked at this week, as we have people both out sick and out on vacation this week.

**Comment by smlambert** [comment]
Also, do we know this is reproducible on the same point in the test build, choking on stringConcatOptTest_0.  We should look if that test material change recently.

**Comment by pshipton** [comment]
I didn't say it was a blocker, but will take more effort to check if there are real failures.

Thanks.

**Comment by smlambert** [comment]
I have not been able to reproduce it yet, either running the specific stringConcatOptTest test 100's of times or running the whole sanity suite 10's of times.  So on the up-side, its not a very frequent failure.

**Comment by pshipton** [comment]
Great, let's hope it was a one-off and we don't see it again once jdk8u202-b08 is merged.

**Comment by pshipton** [comment]
This didn't re-occur in jdk8u202-b08 sanity.functional testing across platforms. Removing from the 0.12 milestone.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/437
```
16:24:21 ]: special characters are not allowed
16:24:21 	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:435)
16:24:21 	at org.tap4j.parser.Tap13Parser.parseLine(Tap13Parser.java:262)
16:24:21 	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:224)
16:24:21 	... 15 more
16:24:21 Caused by: unacceptable character '?' (0xD852) special characters are not allowed
16:24:21 in "'string'", position 916
16:24:21 	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
16:24:21 	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
16:24:21 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
16:24:21 	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:430)
16:24:21 	... 17 more
16:24:21 TAP parse errors found in the build. Marking build as UNSTABLE
```

**Comment by llxia** [comment]
The TAP plugin uses the default system java on the machine to parse. We tested using the same test on different xlinux. The TAP parsing passed on the xlinux machine with java 1.8.0_201-b09 installed and failed on the xlinux machine with java 1.8.0_191-b12 installed. 

The above issue may be related to this. We can not confirm as the job links are expired. If we have the similar failure again, we can check the machine settings.
