### ISSUE TITLE
Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le testSCCMLTests1_openj9_1 Character data ended prematurely

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4469]
Noticed this in the 0.12 release testing.

https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/450
```
21:51:50 Testing: At end destroy cache for cleanup
21:51:50 Test start time: 2019/01/27 02:51:50 Coordinated Universal Time
21:51:50 Running command: "/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,destroy
21:51:50 Time spent starting: 1 milliseconds
21:51:50 Time spent executing: 14 milliseconds
21:51:50 Test result: PASSED
21:51:50 
21:51:50 com.oti.j9.exclude.XMLException: null(1072):C1 : Character data ended prematurely
21:51:50 	at com.oti.j9.exclude.XMLParser.parseError(XMLParser.java:56)
21:51:50 	at com.oti.j9.exclude.XMLParser._scan_cdata_or_eof(XMLParser.java:242)
21:51:50 	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:444)
21:51:50 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:470)
21:51:50 	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
21:51:50 	at TestConfigParser.runTests(TestConfigParser.java:75)
21:51:50 	at MainTester.main(MainTester.java:106)
21:51:50 
21:51:50 ---TEST RESULTS---
21:51:50 Number of PASSED tests: 59 out of 59
21:51:50 Number of FAILED tests: 0 out of 59
21:51:50 
21:51:50 testSCCMLTests1_openj9_1_PASSED
```

**Comment by pshipton** [comment]
Haven't seen a re-occurance, assuming fixed.
