### ISSUE TITLE
osx1013-x86-4 Remote call on osx1013-x86-4 failed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4562]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/59
https://ci.eclipse.org/openj9/job/Build-JDK11-osx_x86-64_cmprssptrs/150
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/57

Something is wrong with this machine. There might be a few more of these if we look back further.

```
01:05:49 ALL TESTS PASSED
01:05:49 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
01:05:49 
01:05:49 _extended.functional done
[Pipeline] sh
01:05:53 ++ uname
01:05:53 + '[' Darwin = AIX ']'
01:05:53 + MAKE=make
01:05:53 + make -f ./openjdk-tests/TestConfig/testEnv.mk testEnvTeardown
01:05:53 make: Nothing to be done for `testEnvTeardown'.
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
01:05:54 TAP Reports Processing: START
01:05:54 Looking for TAP results report in workspace using pattern: **/*.tap
01:05:54 Saving reports...
01:05:54 Processing '/home/hudson/genie.openj9/.jenkins/jobs/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/builds/59/tap-master-files/openjdk-tests/TestConfig/test_output_15492565852456/TestTargetResult.tap'
01:05:54 Parsing TAP test result [/home/hudson/genie.openj9/.jenkins/jobs/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/builds/59/tap-master-files/openjdk-tests/TestConfig/test_output_15492565852456/TestTargetResult.tap].
01:05:54 TAP Reports Processing: FINISH
[Pipeline] junit
01:05:55 Recording test results
01:05:55 Remote call on osx1013-x86-4 failed
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to osx1013-x86-4
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
		at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:50)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:23)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
	at hudson.ExtensionList.lookup(ExtensionList.java:432)
	at hudson.tasks.junit.TestNameTransformer.all(TestNameTransformer.java:40)
	at hudson.tasks.junit.TestNameTransformer.getTransformedName(TestNameTransformer.java:33)
	at hudson.tasks.junit.CaseResult.getTransformedTestName(CaseResult.java:270)
	at hudson.tasks.junit.SuiteResult.casesByName(SuiteResult.java:134)
	at hudson.tasks.junit.SuiteResult.addCase(SuiteResult.java:297)
	at hudson.tasks.junit.SuiteResult.<init>(SuiteResult.java:270)
	at hudson.tasks.junit.SuiteResult.parseSuite(SuiteResult.java:209)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:181)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:348)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:281)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:206)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:178)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:143)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Caused: java.io.IOException: Remote call on osx1013-x86-4 failed
	at hudson.remoting.Channel.call(Channel.java:961)
	at hudson.FilePath.act(FilePath.java:1072)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:50)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:23)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
I believe this is a standard message from jenkins when it loses connection with the machine.
`Remote call on osx1013-x86-4 failed`. 

Regardless I rebooted the machine.

**Comment by pshipton** [comment]
If it happened once I would ignore it, but seems to be consistently happening since about Thursday or Friday.
