### ISSUE TITLE
JTReg test fail - Linux : java/net/Inet6Address/B6206527.java and java/net/ipv6tests/B6521014.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4564]
Intermittent failures ...

```
Stacktrace

Execution failed: `main' threw exception: java.net.BindException: Cannot assign requested address (Bind failed)    

Standard Output

trying LL addr: /fe80:0:0:0:3877:1fff:fe50:e5a7%veth4166a11
trying LL addr: /fe80:0:0:0:3877:1fff:fe50:e5a7
    

Standard Error

java.net.BindException: Cannot assign requested address (Bind failed)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:335)
	at B6206527.main(B6206527.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

```
Stacktrace

Execution failed: `main' threw exception: java.net.BindException: Cannot assign requested address (Bind failed)    

Standard Output

Using /fe80:0:0:0:3877:1fff:fe50:e5a7
timed out when connecting.
    

Standard Error

java.net.BindException: Cannot assign requested address (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.Socket.bind(Socket.java:646)
	at B6521014.test2(B6521014.java:90)
	at B6521014.main(B6521014.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed in tests https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/Inet6Address/B6206527.java and https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/ipv6tests/B6521014.java. 

Latest failures available here - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/268

Thus far, it looks like these failures are limited to Linux.

I have kicked off a 100x with -Xint of both java/net/Inet6Address/B6206527.java (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/954) and java/net/ipv6tests/B6521014.java (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/955).

**Comment by ben-walsh** [comment]
Latest failure observed on test machine test-scaleway-ubuntu1604-x64-1.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/954/consoleText has yet to show a success while running on test machine test-scaleway-ubuntu1604-x64-1.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/955/consoleText has yet to show a failure while running on test machine test-packet-ubuntu1604-x64-2.
Implication is that the IPV6 configuration of the scaleway machines is faulty.

**Comment by ben-walsh** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/960
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/961
