### ISSUE TITLE
JTReg test fail - MacOS : java/util/SplittableRandomTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4613]
Multiple intermittent failures of the form ...

```
1: java.lang.Error: STREAM_SPLITERATOR_FOREACH: java.lang.NullPointerException
java.lang.NullPointerException
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at org.openjdk.tests.java.util.SplittableRandomTest.lambda$randomAsserter$0(SplittableRandomTest.java:108)
	at org.openjdk.tests.java.util.SplittableRandomTest$$Lambda$49.00000000A28E7C20.assertResult(Unknown Source)
	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.lambda$exercise$2(OpTestCase.java:406)
	at java.util.stream.OpTestCase$ExerciseDataStreamBuilder$$Lambda$111.00000000A20A4A20.run(Unknown Source)
	at java.base/java.util.stream.LambdaTestHelpers.launderAssertion(LambdaTestHelpers.java:453)
	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:409)
	at org.openjdk.tests.java.util.SplittableRandomTest.testDoubles(SplittableRandomTest.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed on MacOS of test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/SplittableRandomTest.java.

See https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_macos/172/consoleText.

I have kicked off a 100x run to determine failure rate - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/990

Also, I have kicked off a 100x with -Xint, as this "smells" like a JIT problem - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/991

**Comment by ben-walsh** [comment]
Also observed on Linux s390 - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_s390x_linux/141/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_SplittableRandomTest/java/SplittableRandomTest
Title updated accordingly.

**Comment by JasonFengJ9** [comment]
Both grinder w/o Xint passed, maybe need larger grinders?

**Comment by ben-walsh** [comment]
@JasonFengJ9 
I've kicked off 200x rebuilds of both those (this time on Linux s390) ...
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1016
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1017

I'll also redo MacOS as 200x as well shortly.

**Comment by smlambert** [comment]
btw, if you are doing larger grinders, I would prefer you use internal Jenkins when possible.  For every grinder run on the test macs we have at Adopt (we only have 2), it takes those machines out of circulation for any regularly scheduled jobs.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/864

**Comment by ben-walsh** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1018
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1019

@smlambert Okey dokey. I'll keep in mind. Problem is I was chastised for linking to internal test results in public issues previously. Probably best for all if we get the additional machine resources (/budget) over to AdoptOJDK asap.

**Comment by smlambert** [comment]
Yes, for sure some more test machines are coming to Adopt which is going to help us (though unfortunately no macs on the way at the moment)...  and I recognize test macs are scarce everywhere :)

committers can also launch public Grinders at the openj9 Jenkins instance, which I am happy to do for folks (https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/)

**Comment by sophia-guo** [comment]
See the same failure with linux java8

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux/454/consoleFull

**Comment by sharon-wang** [comment]
Reproduced issue in 1/20 grinder iterations on platforms osx, linux, linux s390 with parameters:

- **BUILD_LIST:** `openjdk_regression`
- **TARGET:** `jdk_custom`
- **CUSTOM_TARGET:** `java/util/stream/test/org/openjdk/tests/java/util/SplittableRandomTest.java`

Occurring on both JDK 8 and 11 for each platform.

Errors revolve around testDoubles(), testLongs(), testInts(), seemingly related to creating new bounded SplittableRandom objects.
It looks like failures on osx and linux s390 only occur with int and long, and linux has failures only for double and long.

**Comment by adam-thorpe** [comment]
Any updates on this? Test seems to be consistent across all platforms as per above linked issue, which is being closed due to being a duplicate.

**Comment by M-Davies** [comment]
This is also failing on JDK11-openj9 nightly builds as well. Similar to the error @ben-walsh posted above
