### ISSUE TITLE
Java 12 functional sanity failure openj9_jsr292Test test_defineClass_ClassBytes_CorruptedArray

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4661]
I ran a Java 12 functional sanity test using the changes from #3980 and #4531.

https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK12-linux_390-64_cmprssptrs/3
openj9_jsr292Test_0
openj9_jsr292Test_JitCount0_0
```
FAILED: test_defineClass_ClassBytes_CorruptedArray
org.testng.TestException: 
Expected exception of type class java.lang.LinkageError but got java.lang.AssertionError: The test case failed to detect a corrupted class byte array
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1129)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
Caused by: java.lang.AssertionError: The test case failed to detect a corrupted class byte array
	at org.testng.Assert.fail(Assert.java:96)
	at com.ibm.j9.jsr292.api.MethodHandleAPI_defineClass.test_defineClass_ClassBytes_CorruptedArray(MethodHandleAPI_defineClass.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	... 18 more
```

**Comment by pshipton** [comment]
@theresa-m @DanHeidinga @JasonFengJ9

**Comment by pshipton** [comment]
@DanHeidinga this is the only jdk12 sanity failure not yet understood.

**Comment by DanHeidinga** [comment]
@fengxue-IS can you take a look at this?

**Comment by fengxue-IS** [comment]
I will look into this

**Comment by DanHeidinga** [comment]
@fengxue-IS This is targeted to the `0.13.0` release and needs to be delivered by Feb 25th to make the release.  Can you provide an update on where the investigation is at and whether there'll be a fix by then?

**Comment by fengxue-IS** [comment]
@DanHeidinga I've traced the test code and I believe this failure is caused by the use of `unsafe.defineClass()` introduced in #3638 (see #3641)

**Comment by JasonFengJ9** [comment]
Verified manually that #4919 makes this test pass.
