### ISSUE TITLE
Java 12 functional extended failure This feature requires ASM7

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4663]
I ran a Java 12 functional extended test using the changes from #3980 and #4531.

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-linux_390-64_cmprssptrs/1
TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_0
TestGCClassWithStaticRetransformInBalanced_0
```
===============================================
Running test TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_0 ...
===============================================
TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_0 Start Time: Thu Feb  7 19:20:51 2019 Epoch Time (ms): 1549585251763
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
[AgentMain] [INFO] AgentMain.premain() is initilized
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/jenkins-agent/workspace/Test-extended.functional-JDK12-linux_390-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_12.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

[RefreshGCCache_FastHCR_Test] [INFO] Starting RefreshGCCache_FastHCR_Test...
FAILED: test_FAST_HCR
java.lang.UnsupportedOperationException: This feature requires ASM7
	at java.base/jdk.internal.org.objectweb.asm.ClassVisitor.visitNestMember(ClassVisitor.java:267)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:682)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:422)
	at org.openj9.test.javaagenttest.util.Transformer.transform(Transformer.java:62)
	at org.openj9.test.javaagenttest.RefreshGCCache_FastHCR_Test.test_FAST_HCR(RefreshGCCache_FastHCR_Test.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@theresa-m @DanHeidinga @JasonFengJ9

**Comment by JasonFengJ9** [comment]
https://github.com/eclipse/openj9/blob/c35378a352036c09b9ca02d4185ed4259d46ea8d/test/functional/JavaAgentTest/src/org/openj9/test/javaagenttest/util/CustomClassVisitor.java#L33-L34

The test need to be updated to `ASM7`.

**Comment by pshipton** [comment]
@JasonFengJ9 can we exclude this test, at least temporarily, to get green test results for jdk12.

**Comment by pshipton** [comment]
Also failing

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-linux_x86-64/1
TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_0
TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_1
TestGCClassWithStaticRetransformInGencon_0
