### ISSUE TITLE
JTReg test failure - PPCLE JDK8: java/rmi/server/RMISocketFactory/useSocketFactory/activatable/UseCustomSocketFactory.java

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#4685]
Test java/rmi/server/RMISocketFactory/useSocketFactory/activatable/UseCustomSocketFactory.java intermittently failed with message 'Execution failed: `main' threw exception: TestFailedException: TEST FAILED: start rmid failed... giving up'

```
RMID: rmid still not started
TEST FAILED: start rmid failed... giving up
RMID: getting a reference to the activation system
RMID: could not contact registry while trying to shutdown activation system
TEST FAILED: reference to the activation system was null
RMID: caught exception trying to shutdown rmid
RMID: TEST FAILED: reference to the activation system was null
TestFailedException: TEST FAILED: reference to the activation system was null
	at TestLibrary.bomb(TestLibrary.java:121)
	at TestLibrary.bomb(TestLibrary.java:124)
	at RMID.shutdown(RMID.java:291)
	at RMID.destroy(RMID.java:313)
	at UseCustomSocketFactory.main(UseCustomSocketFactory.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)
RMID: testlibrary finished shutting down rmid
RMID: rmid exited on shutdown request
TestFailedException: TEST FAILED: start rmid failed... giving up
	at TestLibrary.bomb(TestLibrary.java:121)
	at RMID.start(RMID.java:258)
	at RMID.start(RMID.java:203)
	at UseCustomSocketFactory.main(UseCustomSocketFactory.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: start rmid failed... giving up
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: TestFailedException: TEST FAILED: start rmid failed... giving up
    
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_ppc64le_linux/316/testReport/junit/java_rmi_server_RMISocketFactory_useSocketFactory_activatable_UseCustomSocketFactory/java/UseCustomSocketFactory/

**Comment by JasonFengJ9** [comment]
Observed at an internal build `job/Test_openjdk8_j9_extended.openjdk_x86-32_windows/28/` (`win16x64rt2-2`)
```
[2021-11-27T06:28:49.553Z] variation: Mode1000
[2021-11-27T06:28:49.553Z] JVM_OPTIONS:  

[2021-11-27T06:31:33.368Z] --------------------------------------------------
[2021-11-27T06:31:33.368Z] TEST: java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java

[2021-11-27T06:31:33.369Z] STDERR:
[2021-11-27T06:31:33.369Z] 
[2021-11-27T06:31:33.369Z] Regression test for bug 6261402
[2021-11-27T06:31:33.369Z] 
[2021-11-27T06:31:33.369Z] export callback object and bind in registry
[2021-11-27T06:31:33.369Z] start rmid with inherited channel
[2021-11-27T06:31:33.369Z] RMID: Starting rmid on port 60003.
[2021-11-27T06:31:33.370Z] JAVAVM: command = [C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\openjdkbinary\j2sdk-image\jre\bin\java, -ea, -esa, -Xmx512m, -Djava.security.policy=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\activation\rmidViaInheritedChannel\rmid.security.policy, -Djava.nio.channels.spi.SelectorProvider=InheritedChannelNotServerSocket$SP, -Dsun.rmi.server.activation.debugExec=true, -Dtest.src=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\activation\rmidViaInheritedChannel, -Dtest.classes=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\TKG\output_1637990205140\jdk_rmi_2\work\classes\3\java\rmi\activation\rmidViaInheritedChannel, -Djava.rmi.server.logLevel=v, -Dsun.rmi.activation.execTimeout=60000, sun.rmi.server.Activation, -log, C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\TKG\output_1637990205140\jdk_rmi_2\work\java\rmi\activation\rmidViaInheritedChannel\InheritedChannelNotServerSocket\.\log, -port, 60003, -C-Dtest.src=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\openjdk\openjdk-jdk\jdk\test\java\rmi\activation\rmidViaInheritedChannel, -C-Dtest.classes=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\TKG\output_1637990205140\jdk_rmi_2\work\classes\3\java\rmi\activation\rmidViaInheritedChannel, -C-ea, -C-esa, -C-Xmx512m, -C-Djava.rmi.server.useCodebaseOnly=false]
[2021-11-27T06:31:33.370Z] SP.inheritedChannel
[2021-11-27T06:31:33.370Z] socket = Socket[unconnected]
[2021-11-27T06:31:33.370Z] notify test...
[2021-11-27T06:31:33.370Z] TEST FAILED: Failed to start rmid, giving up after 15907ms.
[2021-11-27T06:31:33.370Z] RMID: shutdown()
[2021-11-27T06:31:33.370Z] RMID: lookupSystem() returned null after 1022ms.
[2021-11-27T06:31:33.370Z] RMID: Destroying RMID process.
[2021-11-27T06:31:33.370Z] RMID: Destroy successful after 1022ms.
[2021-11-27T06:31:33.370Z] TestFailedException: TEST FAILED: Failed to start rmid, giving up after 15907ms.
[2021-11-27T06:31:33.370Z] 	at TestLibrary.bomb(TestLibrary.java:121)
[2021-11-27T06:31:33.370Z] 	at RMID.start(RMID.java:296)
[2021-11-27T06:31:33.370Z] 	at RMID.start(RMID.java:237)
[2021-11-27T06:31:33.370Z] 	at InheritedChannelNotServerSocket.main(InheritedChannelNotServerSocket.java:105)
[2021-11-27T06:31:33.370Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-27T06:31:33.370Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-27T06:31:33.370Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-27T06:31:33.370Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-11-27T06:31:33.370Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2021-11-27T06:31:33.370Z] 	at java.lang.Thread.run(Thread.java:826)
[2021-11-27T06:31:33.370Z] 
[2021-11-27T06:31:33.370Z] JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: Failed to start rmid, giving up after 15907ms.

[2021-11-27T06:31:33.370Z] TEST RESULT: Failed. Execution failed: `main' threw exception: TestFailedException: TEST FAILED: Failed to start rmid, giving up after 15907ms.
[2021-11-27T06:31:33.370Z] --------------------------------------------------
[2021-11-27T06:42:25.550Z] Test results: passed: 118; failed: 1
[2021-11-27T06:42:41.533Z] Report written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\jvmtest\openjdk\report\html\report.html
[2021-11-27T06:42:41.533Z] Results written to C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.openjdk_x86-32_windows\aqa-tests\TKG\output_1637990205140\jdk_rmi_2\work
[2021-11-27T06:42:41.533Z] Error: Some tests failed or other problems occurred.
[2021-11-27T06:42:41.533Z] 
[2021-11-27T06:42:41.533Z] jdk_rmi_2_FAILED
```
