### ISSUE TITLE
JTReg test fail - java/lang/invoke/ArrayLengthTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4704]
Intermittent failures ...

```
java.lang.ClassCastException: [Ljava.lang.Object; incompatible with [Ljava.lang.StringBuffer;
	at test.java.lang.invoke.ArrayLengthTest.testArrayLength(ArrayLengthTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/ArrayLengthTest.java.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2856752/consoleText.txt).

100x run - see [consoleText.txt](https://github.com/eclipse/openj9/files/2856762/consoleText.txt) - showing 1% failure rate.

100x with -Xint run - see [consoleText.txt](https://github.com/eclipse/openj9/files/2856776/consoleText.txt) - showing 0% failure rate. Given how low the failure rate with JIT appears to be, I have kicked off a 200x with -Xint run - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1046, to gain confidence this is a JIT problem.

**Comment by DanHeidinga** [comment]
Relevant code in OpenJ9 for creating the MH used in the test:
https://github.com/eclipse/openj9/blob/065a85358286844b8637b7177f09092860ef24ea/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L3422-L3427

Note, we create an MH of type `(Object[])I` and then convert the type to the required type - the `cloneWithNewType` call

**Comment by DanHeidinga** [comment]
Actually, the interesting line in the test case is:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/c24201865ace5db74af90d861686d6576cec33b9/test/jdk/java/lang/invoke/ArrayLengthTest.java#L61

which maps to 
https://github.com/eclipse/openj9/blob/065a85358286844b8637b7177f09092860ef24ea/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L3352-L3355
and the helper method:
https://github.com/eclipse/openj9/blob/065a85358286844b8637b7177f09092860ef24ea/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L3397-L3399

which will return an array of the wrong type - `[Ljava/lang/Object;` rather than the expected `[Ljava.lang.StringBuffer;`

**Comment by DanHeidinga** [comment]
We'll have to use https://github.com/eclipse/openj9/blob/87f128a0e7e924befcb2841eafbc8c951e915527/jcl/src/java.base/share/classes/java/lang/reflect/Array.java#L367 instead

**Comment by ben-walsh** [comment]
200x run on Linux shows 0.5% failure rate - see [consoleText.txt](https://github.com/eclipse/openj9/files/2861362/consoleText.txt). I'm adjusting the title and platform exclusion accordingly.

**Comment by DanHeidinga** [comment]
I'm not sure how this ever passes given the array created will always be the wrong type for any Object subclass.  It should fail 100%.

**Comment by ChengJin01** [comment]
I confirms the sub-test called testArrayLength() does fails every time only for `StringBuffer[].class`.  The reason for intermittent failure in JTReg test is because the input parameter was randomly picked up from **arrayClasses()**, which means `StringBuffer[].class` won't be chosen every time in test.

```
@DataProvider
    Object[][] arrayClasses() {
        return new Object[][] {
                {int[].class},
                {long[].class},
                {float[].class},
                {double[].class},
                {boolean[].class},
                {byte[].class},
                {short[].class},
                {char[].class},
                {Object[].class},
                {StringBuffer[].class}
        };
    }

    @Test(dataProvider = "arrayClasses") <--------------------
public void testArrayLength(Class<?> arrayClass) throws Throwable {
...
```
Actually our test cases at /test/functional/Jsr292/src/com/ibm/j9/jsr292/api/MethodHandleAPI_arrayConstructor.java already covered all kinds of 1-D arrays with primitive type (e.g char[], byte[], int[].class), 2D arrays as well as Object[].class but not something like StringBuffer[].class.

I will check to see what needs to be modified in arrayConstructor() to address the issue.
