### ISSUE TITLE
Windows IA32 NPE at java.util.Vector.size(Vector.java:329)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#4764]
From an internal test (job link is not accessible externally) 
Load_Level_2.abbs.5mins.Mode187
```
j> 16:20:14 20190215 16:20:13 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.testLambdasWithMultipleThreads|2311|Default Invocant> ERROR: Test testLambdasWithMultipleThreads(com.ibm.jtc.svt.lambda.TestLambdaMultithreaded) reported an error
j> 16:20:14 Throwable trace:
j> 16:20:14 java.lang.NullPointerException
j> 16:20:14 	at java.util.Vector.size(Vector.java:329)
j> 16:20:14 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.assertStack(TestLambdaMultithreaded.java:439)
j> 16:20:14 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.runNumberCounter(TestLambdaMultithreaded.java:400)
j> 16:20:14 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:231)
j> 16:20:14 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded$$Lambda$28.4BB15B80.run(Unknown Source)
j> 16:20:14 	at java.lang.Thread.run(Thread.java:812)
```

The code snippet [Vector.java](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4d2b0d68a3fbb3c0fc3d0ab5821e0908e2b077bd/jdk/src/share/classes/java/util/Vector.java#L329) in question:
```
    public synchronized boolean isEmpty() {
        return elementCount == 0;   --> NPE
    }
```

Could JIT team offer some insights?

The result is available at https://ibm.box.com/s/cbaa7kpoohi8nbf54homjn98361kou1x.

**Comment by pshipton** [comment]
Probably related
[linux_x86] SE80_GIT jsr335tests_SE80_2
```
FAILED: testAnonClassCodePaths
java.lang.NullPointerException
	at java.lang.Integer.valueOf(Integer.java:843)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:190)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by JasonFengJ9** [comment]
Occurred again at `[Linux Hammer Compressed Pointers] 80 Load_Level_2.abbs.5mins.Mode551.4`
``` 
j> 19:01:21 20190316 19:01:21 Plugin Loader INFO: Loading com.ibm.jtc.test.jltf.workunitadapters.JCKWorkUnitPlugin
j> 19:01:21 20190316 19:01:21 On First Failure Plugin INFO: Registering First Failure Handler
j> 19:01:21 20190316 19:01:21 Excessive Failure Plugin INFO: Registering Excessive Failure Handler
j> 19:01:22 main in static init
j> 19:01:22 20190316 19:01:22 Pooled Work Thread Factory INFO: Thread Pool Exhaustion Behaviour: Grow Pool
j> 19:01:22 20190316 19:01:22 ConfigurationReporter INFO: Change detected
j> 19:01:22 20190316 19:01:22 Execution Timer INFO: Execution Timer started
j> 19:01:22 20190316 19:01:22 Thread Control Engine INFO: Starting JobSet Primary
j> 19:01:29 20190316 19:01:28 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.testLambdasWithMultipleThreads|584|Default Invocant> ERROR: Test testLambdasWithMultipleThreads(com.ibm.jtc.svt.lambda.TestLambdaMultithreaded) reported an error
j> 19:01:29 Throwable trace:
j> 19:01:29 java.lang.NullPointerException
j> 19:01:29 	at java.util.Vector.size(Vector.java:329)
j> 19:01:29 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.assertStack(TestLambdaMultithreaded.java:439)
j> 19:01:29 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.runAllOpcodes(TestLambdaMultithreaded.java:266)
j> 19:01:29 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded.lambda$testLambdasWithMultipleThreads$14(TestLambdaMultithreaded.java:230)
j> 19:01:29 	at com.ibm.jtc.svt.lambda.TestLambdaMultithreaded$$Lambda$47.000000005800F080.run(Unknown Source)
j> 19:01:29 	at java.lang.Thread.run(Thread.java:812)
```

**Comment by andrewcraik** [comment]
@yanluo7 could you take a look please and see what might be up with this?

**Comment by yanluo7** [comment]
Did a 50-run Load_Level_2.abbs.5mins.Mode551 tests, all passed. Issue doesn't appear to be reproducible.

**Comment by yanluo7** [comment]
50-run win 32 abbs.5mins.Mode187 all passed.

**Comment by vij-singh** [comment]
@JasonFengJ9  Jason, are you able to reproduce this?

**Comment by JasonFengJ9** [comment]
@vij-singh it was reproduced in a grinder which has been purged now. Just started a 100x grinder to check if it still presents in current SDK.
