### ISSUE TITLE
JTReg Test Fail - Windows : java/rmi/activation/Activatable/checkRegisterInLog/CheckRegisterInLog.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4772]
Intermittent failures ...

```
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Unhandled exception
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Type=Segmentation error vmState=0x00000000
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFC0FA4261D ContextFlags=0010005f
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Handler1=00007FFC0FABD060 Handler2=00007FFC10A0ECF0 InaccessibleReadAddress=0000000099669976
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:RDI=000000E022ADEFC0 RSI=000000000030AE40 RAX=0000000099669966 RBX=000000000030AF00
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:RCX=000000E022ADEFD8 RDX=00000000002F06C0 R8=000000E021997B28 R9=0000000000060002
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:R10=000000E0219982AA R11=000000E022ADE910 R12=000000E022ADEFC8 R13=000000E022ADEFB8
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:R14=00000000002F06C8 R15=000000E022ADEFB0
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:RIP=00007FFC0FA4261D RSP=000000E022ADECA0 RBP=00000000002F0758 GS=002B
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:FS=0053 ES=002B DS=002B
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM0 000000e0219982aa (f: 563708608.000000, d: 4.756056e-312)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM1 99baaa25c397cdf0 (f: 3281505792.000000, d: -9.805243e-185)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM2 000e1781000e1781 (f: 923521.000000, d: 1.959708e-308)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM3 3fcffdb5481285d6 (f: 1209173504.000000, d: 2.499301e-01)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM4 3d10dc0acacac1ce (f: 3402285568.000000, d: 1.497428e-14)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM5 3f37012a8f28ee3e (f: 2401824256.000000, d: 3.510217e-04)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM6 00000000002f06c8 (f: 3081928.000000, d: 1.522675e-317)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM7 00000000002f06c8 (f: 3081928.000000, d: 1.522675e-317)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Module=C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\openjdkbinary\j2sdk-image\bin\compressedrefs\j9vm29.dll
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Module_base_address=00007FFC0FA40000 Offset_in_DLL=000000000000261d
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:Target=2_90_20190215_135 (Windows Server 2012 R2 6.3 build 9600)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:CPU=amd64 (4 logical CPUs) (0x1fff8d000 RAM)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:----------- Stack Backtrace -----------
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:(0x00007FFC0FA4261D [j9vm29+0x261d])
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:(0x0000000000000001)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:(0x000000000030B8E0)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:(0x0000000000000029)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:(0x000000E022ADEF01)
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:---------------------------------------
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:JVMDUMP039I Processing dump event "gpf", detail "" at 2019/02/18 15:40:53 - please wait.
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\core.20190218.154053.9764.0001.dmp' in response to an event
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:JVMDUMP010I System dump written to C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\core.20190218.154053.9764.0001.dmp
Mon Feb 18 15:40:53 UTC 2019:ExecGroup-0:err:JVMDUMP032I JVM requested Java dump using 'C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\javacore.20190218.154053.9764.0002.txt' in response to an event
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\javacore.20190218.154053.9764.0002.txt
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP032I JVM requested Snap dump using 'C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\Snap.20190218.154053.9764.0003.trc' in response to an event
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP010I Snap dump written to C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\Snap.20190218.154053.9764.0003.trc
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP007I JVM Requesting JIT dump using 'C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\jitdump.20190218.154053.9764.0004.dmp'
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP010I JIT dump written to C:\Users\jenkins\workspace\SXA-BenWalsh-Grinder\jvmtest\openjdk_regression\work\scratch\0\jitdump.20190218.154053.9764.0004.dmp
Mon Feb 18 15:40:54 UTC 2019:ExecGroup-0:err:JVMDUMP013I Processed dump event "gpf", detail "".
rmid: activation group inactive: java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at java.rmi/java.rmi.activation.ActivationGroup_Stub.newInstance(Unknown Source)
	at java.rmi/sun.rmi.server.Activation$ObjectEntry.activate(Activation.java:1523)
	at java.rmi/sun.rmi.server.Activation$GroupEntry.activate(Activation.java:1209)
	at java.rmi/sun.rmi.server.Activation$ActivatorImpl.activate(Activation.java:439)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:739)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$91.00000000D31FC8E0.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 25 more

failure: unexpected exception java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
	java.rmi.activation.ActivationException: object activation failed after 2 tries; nested exception is: 
	java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
	java.rmi.activation.ActivationException: object activation failed after 2 tries; nested exception is: 
	java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at java.rmi/sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:303)
	at java.rmi/sun.rmi.server.ActivatableRef.invoke(ActivatableRef.java:133)
	at CheckRegisterInLog_Stub.ping(CheckRegisterInLog_Stub.java:77)
	at CheckRegisterInLog.main(CheckRegisterInLog.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.rmi.activation.ActivationException: object activation failed after 2 tries; nested exception is: 
	java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at java.rmi/sun.rmi.server.Activation$GroupEntry.activate(Activation.java:1252)
	at java.rmi/sun.rmi.server.Activation$ActivatorImpl.activate(Activation.java:439)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:739)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$91.00000000D31FC8E0.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:209)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:161)
	at com.sun.proxy.$Proxy0.activate(Unknown Source)
	at java.rmi/java.rmi.activation.ActivationID.activate(ActivationID.java:132)
	at java.rmi/sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:276)
	... 9 more
Caused by: java.rmi.ConnectException: Connection refused to host: 10.0.0.5; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at java.rmi/java.rmi.activation.ActivationGroup_Stub.newInstance(Unknown Source)
	at java.rmi/sun.rmi.server.Activation$ObjectEntry.activate(Activation.java:1523)
	at java.rmi/sun.rmi.server.Activation$GroupEntry.activate(Activation.java:1209)
	at java.rmi/sun.rmi.server.Activation$ActivatorImpl.activate(Activation.java:439)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:739)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$91.00000000D31FC8E0.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 25 more
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/rmi/activation/Activatable/checkRegisterInLog/CheckRegisterInLog.java.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2876673/consoleText.txt).

Coredump files available here - https://ibm.box.com/s/m4o9qhg26sqfh4btlm9w4s3ki2mw4dp6

**Comment by DanHeidinga** [comment]
```
InaccessibleReadAddress=0000000099669976
```
This suggests that someone is treating a J9Class as a java.lang.Class and reading a small offset from the eyecatcher. 

FYI @andrewcraik as this is often a symptom of either a JIT or JNI native issues

**Comment by andrewcraik** [comment]
@DanHeidinga agreed - FYI @0dvictor though you are away for a couple of weeks. I'll see if we can get any additional help, but there are a few people away today with the Family Day holiday here in Ontario.

**Comment by JasonFengJ9** [comment]
Re-enabled the test at https://github.com/AdoptOpenJDK/openjdk-tests/pull/1126.
