### ISSUE TITLE
osx1011-x86-1 not connecting to Jenkins

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4811]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-osx_x86-64_cmprssptrs-OpenJ9/94
https://ci.eclipse.org/openj9/job/Build-JDK8-osx_x86-64_cmprssptrs/192/

```
17:02:46 Cloning the remote Git repository
17:02:47 ERROR: Error cloning remote repo 'origin'
17:02:47 hudson.plugins.git.GitException: java.io.IOException: Remote call on osx1011-x86-1 failed
17:02:47 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:169)
17:02:47 	at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
17:02:47 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:02:47 	at java.lang.reflect.Method.invoke(Method.java:498)
17:02:47 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
17:02:47 	at com.sun.proxy.$Proxy84.execute(Unknown Source)
17:02:47 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
17:02:47 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
17:02:47 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
17:02:47 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
17:02:47 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
17:02:47 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
17:02:47 	at hudson.security.ACL.impersonate(ACL.java:290)
17:02:47 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
17:02:47 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:02:47 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:02:47 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:02:47 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:02:47 	at java.lang.Thread.run(Thread.java:748)
17:02:47 Caused by: java.io.IOException: Remote call on osx1011-x86-1 failed
17:02:47 	at hudson.remoting.Channel.call(Channel.java:961)
17:02:47 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
17:02:47 	... 18 more
17:02:47 Caused by: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
17:02:47 	at hudson.console.ConsoleNote.encodeToBytes(ConsoleNote.java:193)
17:02:47 	at hudson.console.ConsoleNote.encode(ConsoleNote.java:211)
17:02:47 	at hudson.plugins.timestamper.TimestampNotesOutputStream.eol(TimestampNotesOutputStream.java:70)
17:02:47 	at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:60)
17:02:47 	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:56)
17:02:47 	at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:74)
17:02:47 	at java.io.PrintStream.write(PrintStream.java:480)
17:02:47 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
17:02:47 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
17:02:47 	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
17:02:47 	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
17:02:47 	at java.io.PrintStream.newLine(PrintStream.java:546)
17:02:47 	at java.io.PrintStream.println(PrintStream.java:807)
17:02:47 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:567)
17:02:47 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
17:02:47 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
17:02:47 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
17:02:47 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
17:02:47 	at hudson.remoting.Request$2.run(Request.java:369)
17:02:47 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
17:02:47 	... 4 more
17:02:47 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to osx1011-x86-1
17:02:47 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
17:02:47 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
17:02:47 		at hudson.remoting.Channel.call(Channel.java:955)
17:02:47 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
17:02:47 		at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
17:02:47 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:02:47 		at java.lang.reflect.Method.invoke(Method.java:498)
17:02:47 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
17:02:47 		at com.sun.proxy.$Proxy84.execute(Unknown Source)
17:02:47 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
17:02:47 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
17:02:47 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
17:02:47 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
17:02:47 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
17:02:47 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
17:02:47 		at hudson.security.ACL.impersonate(ACL.java:290)
17:02:47 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
17:02:47 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:02:47 		... 4 more
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
Disabled the machine for now.

**Comment by AdamBrousseau** [comment]
I disconnected and reconnected the machine. Please update if it happens again
