### ISSUE TITLE
Grinder results in FileNotFoundException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4817]
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/279/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/280/console
```
java.io.FileNotFoundException
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:167)
	at jenkins.plugins.git.GitSCMFile$3.invoke(GitSCMFile.java:159)
	at jenkins.plugins.git.GitSCMFileSystem$3.invoke(GitSCMFileSystem.java:193)
	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
	at jenkins.plugins.git.GitSCMFileSystem.invoke(GitSCMFileSystem.java:189)
	at jenkins.plugins.git.GitSCMFile.content(GitSCMFile.java:159)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:338)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:110)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:292)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@llxia @smlambert @AdamBrousseau @jdekonin

**Comment by smlambert** [comment]
Usage error, you need to select one of the files listed below the Jenkinsfile field, you have used a URL:

<img width="919" alt="screen shot 2019-02-21 at 9 15 10 am" src="https://user-images.githubusercontent.com/2836948/53175084-48e99400-35b9-11e9-822a-7506e2ae85a0.png">

**Comment by smlambert** [comment]
I've rebuilt your job here: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/281/
with openjdk_ppc64le_linux in that field.

**Comment by pshipton** [comment]
Thanks. Sorry about that.

**Comment by smlambert** [comment]
No worries, there are many different ways to launch testing (high flexibility means its difficult to keep it simple).  ;)
