### ISSUE TITLE
JTReg Test Failure : java/lang/invoke/MethodHandlesArityLimitsTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4937]
Consistent failure ...

```
[2019-02-27T15:44:47.755Z] STDERR:
[2019-02-27T15:44:47.755Z] JavaTest Message: JUnit Failure: testAsType(test.java.lang.invoke.MethodHandlesArityLimitsTest): Unexpected exception, expected<java.lang.invoke.WrongMethodTypeException> but was<java.lang.IllegalArgumentException>
[2019-02-27T15:44:47.755Z] java.lang.Exception: Unexpected exception, expected<java.lang.invoke.WrongMethodTypeException> but was<java.lang.IllegalArgumentException>
[2019-02-27T15:44:47.755Z] 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:31)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.Suite.runChild(Suite.java:128)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.Suite.runChild(Suite.java:24)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
[2019-02-27T15:44:47.755Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
[2019-02-27T15:44:47.755Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
[2019-02-27T15:44:47.755Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
[2019-02-27T15:44:47.755Z] 	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
[2019-02-27T15:44:47.755Z] Caused by: java.lang.IllegalArgumentException: MethodHandle would consume more than 255 argument slots ("256")
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.MethodHandle.throwIllegalArgumentExceptionForMTArgCount(MethodHandle.java:1439)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.MethodHandle.enforceArityLimit(MethodHandle.java:1433)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:243)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.CollectHandle.<init>(CollectHandle.java:45)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.MethodHandle.asCollectorCommon(MethodHandle.java:458)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.MethodHandle.asCollector(MethodHandle.java:424)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.invoke.VarargsCollectorHandle.asType(VarargsCollectorHandle.java:156)
[2019-02-27T15:44:47.755Z] 	at test.java.lang.invoke.MethodHandlesArityLimitsTest.testAsType(MethodHandlesArityLimitsTest.java:118)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
[2019-02-27T15:44:47.755Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
[2019-02-27T15:44:47.755Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
[2019-02-27T15:44:47.755Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
[2019-02-27T15:44:47.755Z] 	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22)
[2019-02-27T15:44:47.755Z] 	... 29 more
[2019-02-27T15:44:47.755Z] 
[2019-02-27T15:44:47.755Z] java.lang.Exception: JUnit test failure
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:92)
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:44:47.755Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:44:47.755Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-02-27T15:44:47.755Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/invoke/MethodHandlesArityLimitsTest.java against OpenJDK12+OpenJ9.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2918926/consoleText.txt) and [consoleText.txt](https://github.com/eclipse/openj9/files/2918932/consoleText.txt).

See https://github.com/ibmruntimes/openj9-openjdk-jdk12/commit/2534d8d98bea0c6c9546021f7e71223edd74bcba - I think we just need equivalent in the JCL version.

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by JasonFengJ9** [comment]
Might be related to https://github.com/eclipse/openj9/issues/4964
