### ISSUE TITLE
JTReg Test Failure : java/lang/Class/GenericStringTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4938]
Consistent failures ...

```
[2019-02-27T15:39:06.434Z] STDERR:
[2019-02-27T15:39:06.434Z] Unexpected Class.toGenericString output; expected 
[2019-02-27T15:39:06.434Z] 	'public class java.util.EnumMap<K extends java.lang.Enum<K>,V>',
[2019-02-27T15:39:06.434Z]  got 
[2019-02-27T15:39:06.434Z] 	'public class java.util.EnumMap<K,V>'.
[2019-02-27T15:39:06.434Z] Unexpected Class.toGenericString output; expected 
[2019-02-27T15:39:06.434Z] 	'public abstract class java.util.EventListenerProxy<T extends java.util.EventListener>',
[2019-02-27T15:39:06.434Z]  got 
[2019-02-27T15:39:06.434Z] 	'public abstract class java.util.EventListenerProxy<T>'.
[2019-02-27T15:39:06.434Z] Unexpected Class.toGenericString output; expected 
[2019-02-27T15:39:06.434Z] 	'public abstract class java.lang.Enum<E extends java.lang.Enum<E>>',
[2019-02-27T15:39:06.434Z]  got 
[2019-02-27T15:39:06.434Z] 	'public abstract class java.lang.Enum<E>'.
[2019-02-27T15:39:06.434Z] java.lang.RuntimeException
[2019-02-27T15:39:06.434Z] 	at GenericStringTest.main(GenericStringTest.java:78)
[2019-02-27T15:39:06.434Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:39:06.434Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:39:06.434Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:39:06.434Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:39:06.434Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2019-02-27T15:39:06.434Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/Class/GenericStringTest.java against OpenJDK12+OpenJ9 build.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2919012/consoleText.txt) and [consoleText.txt](https://github.com/eclipse/openj9/files/2919051/consoleText.txt).

See https://github.com/ibmruntimes/openj9-openjdk-jdk12/commit/d6b3d6b959d8381d0f240bc710ac6797e71dff44#diff-dcb8c538740ef99677c90b8e39b63199, suspect something is off with the JCL classes.

**Comment by pshipton** [comment]
@DanHeidinga @JasonFengJ9 @theresa-m

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by pshipton** [comment]
We're about out of time for the 0.13 release, moving this to 0.14
