### ISSUE TITLE
JTReg Test Failure : java/lang/constant/CondyDescTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4940]
Consistent failures ...

```
[2019-02-27T15:39:53.713Z] STDOUT:
[2019-02-27T15:39:53.713Z] [TestNG] Running:
[2019-02-27T15:39:53.713Z]   java/lang/constant/CondyDescTest.java
[2019-02-27T15:39:53.713Z] 
[2019-02-27T15:39:53.713Z] test CondyDescTest.testDynamicConstant(): success
[2019-02-27T15:39:53.713Z] test CondyDescTest.testEnumDesc(): success
[2019-02-27T15:39:53.713Z] test CondyDescTest.testLifting(): failure
[2019-02-27T15:39:53.713Z] java.lang.AssertionError: expected [DynamicConstantDesc[ConstantBootstraps::staticFieldVarHandle(sf/ClassDesc[CondyDescTest$MyClass],PrimitiveClassDesc[int])VarHandle]] but found [VarHandleDesc[static CondyDescTest$MyClass.sf:int]]
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.fail(Assert.java:94)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.assertEquals(Assert.java:125)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.assertEquals(Assert.java:167)
[2019-02-27T15:39:53.713Z] 	at CondyDescTest.assertLifted(CondyDescTest.java:212)
[2019-02-27T15:39:53.713Z] 	at CondyDescTest.testLifting(CondyDescTest.java:239)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2019-02-27T15:39:53.713Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:39:53.713Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
[2019-02-27T15:39:53.713Z] test CondyDescTest.testNested(): success
[2019-02-27T15:39:53.713Z] test CondyDescTest.testNullConstant(): success
[2019-02-27T15:39:53.713Z] test CondyDescTest.testVarHandles(): failure
[2019-02-27T15:39:53.713Z] java.lang.AssertionError: expected [VarHandleDesc[static CondyDescTest$MyClass.sf:int]] but found [DynamicConstantDesc[ConstantBootstraps::staticFieldVarHandle(sf/ClassDesc[CondyDescTest$MyClass],PrimitiveClassDesc[int])VarHandle]]
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.fail(Assert.java:94)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.assertEquals(Assert.java:125)
[2019-02-27T15:39:53.713Z] 	at org.testng.Assert.assertEquals(Assert.java:167)
[2019-02-27T15:39:53.713Z] 	at SymbolicDescTest.testSymbolicDesc(SymbolicDescTest.java:102)
[2019-02-27T15:39:53.713Z] 	at SymbolicDescTest.testSymbolicDesc(SymbolicDescTest.java:90)
[2019-02-27T15:39:53.713Z] 	at CondyDescTest.testVarHandleDesc(CondyDescTest.java:69)
[2019-02-27T15:39:53.713Z] 	at CondyDescTest.testVarHandles(CondyDescTest.java:178)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2019-02-27T15:39:53.713Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2019-02-27T15:39:53.713Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2019-02-27T15:39:53.713Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2019-02-27T15:39:53.713Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-02-27T15:39:53.713Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-02-27T15:39:53.713Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2019-02-27T15:39:53.713Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
[2019-02-27T15:39:53.713Z] 
[2019-02-27T15:39:53.713Z] ===============================================
[2019-02-27T15:39:53.713Z] java/lang/constant/CondyDescTest.java
[2019-02-27T15:39:53.713Z] Total tests run: 6, Failures: 2, Skips: 0
[2019-02-27T15:39:53.713Z] ===============================================
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/constant/CondyDescTest.java against OpenJDK12+OpenJ9 build.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2919294/consoleText.txt) and [consoleText.txt](https://github.com/eclipse/openj9/files/2919293/consoleText.txt).

**Comment by pshipton** [comment]
@DanHeidinga @theresa-m

**Comment by theresa-m** [comment]
I'll start looking at this one.

**Comment by theresa-m** [comment]
This is related to an error in https://github.com/eclipse/openj9/pull/4449

DynamicConstantDesc<VarHandle> -> VarHandle -> DynamicConstantDesc<VarHandle> is not working properly.
