### ISSUE TITLE
JTReg Test Failure : java/lang/ProcessBuilder/Basic.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4945]
Consistent failures ...

```
[2019-03-01T14:31:57.603Z] STDOUT:
[2019-03-01T14:31:57.603Z] This appears to be a Unix system.
[2019-03-01T14:31:57.603Z] Testing ASCII environment values
[2019-03-01T14:31:57.603Z] Testing Latin1 environment values
[2019-03-01T14:31:57.603Z] Testing Unicode environment values
[2019-03-01T14:31:57.603Z] Testing directory .
[2019-03-01T14:31:57.603Z] Testing directory ..
[2019-03-01T14:31:57.603Z] Testing directory /
[2019-03-01T14:31:57.603Z] Testing directory /bin
[2019-03-01T14:31:57.603Z] cmdp
[2019-03-01T14:31:57.603Z] cmdp 0: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java
[2019-03-01T14:31:57.603Z] cmdp 1: -XX:+DisplayVMOutputToStderr
[2019-03-01T14:31:57.603Z] cmdp 2: -classpath
[2019-03-01T14:31:57.603Z] cmdp 3: /home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/work/classes/0/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/jtreg/lib/javatest.jar:/home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/jtreg/lib/jtreg.jar
[2019-03-01T14:31:57.603Z] cmdp 4: Basic$JavaChild
[2019-03-01T14:31:57.603Z] cmdp 5: System.getenv()
[2019-03-01T14:31:57.603Z] envp
[2019-03-01T14:31:57.603Z] envp 0: LC_ALL=C��
[2019-03-01T14:31:57.603Z] envp 1: FO�=B�R
[2019-03-01T14:31:57.603Z]  waitFor process: delta: 139618
[2019-03-01T14:31:57.603Z] 
[2019-03-01T14:31:57.603Z] Passed = 9021, failed = 2
[2019-03-01T14:31:57.603Z] 
[2019-03-01T14:31:57.603Z] STDERR:
[2019-03-01T14:31:57.603Z] java.lang.Throwable
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.Thread.dumpStack(Thread.java:502)
[2019-03-01T14:31:57.603Z] 	at Basic.fail(Basic.java:2733)
[2019-03-01T14:31:57.603Z] 	at Basic.check(Basic.java:2736)
[2019-03-01T14:31:57.603Z] 	at Basic.realMain(Basic.java:1778)
[2019-03-01T14:31:57.603Z] 	at Basic.main(Basic.java:2743)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-03-01T14:31:57.603Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
[2019-03-01T14:31:57.603Z] java.lang.Throwable
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.Thread.dumpStack(Thread.java:502)
[2019-03-01T14:31:57.603Z] 	at Basic.fail(Basic.java:2733)
[2019-03-01T14:31:57.603Z] 	at Basic.check(Basic.java:2736)
[2019-03-01T14:31:57.603Z] 	at Basic.realMain(Basic.java:1779)
[2019-03-01T14:31:57.603Z] 	at Basic.main(Basic.java:2743)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-03-01T14:31:57.603Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
[2019-03-01T14:31:57.603Z] java.lang.AssertionError: Some tests failed
[2019-03-01T14:31:57.603Z] 	at Basic.main(Basic.java:2745)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-03-01T14:31:57.603Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[2019-03-01T14:31:57.603Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-03-01T14:31:57.603Z] 	at java.base/java.lang.Thread.run(Thread.java:825)
```

... observed with test https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/ProcessBuilder/Basic.java against OpenJDK12+OpenJ9 build.

See [consoleText.txt](https://github.com/eclipse/openj9/files/2919972/consoleText.txt) and [consoleText.txt](https://github.com/eclipse/openj9/files/2919861/consoleText.txt).

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by JasonFengJ9** [comment]
Sharon is looking at this.

**Comment by sharon-wang** [comment]
On lines 1778 and 1779 of:
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/bb38f8aaac36f1bb22dfc2461e47fc294c00c961/test/jdk/java/lang/ProcessBuilder/Basic.java#L1767-L1781

The test is failing since it is looking for `javaExe` and `System.getProperty("java.version")` in the `ProcessResults` error stream, however the error stream does not include that information. The out stream is empty. Only `java.lang.OutOfMemoryError:` is outputted to the error stream, so line 1777 of `Basic.java` passes. Here is a sample of the `ProcessResults` error stream:

```JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/03/14 18:56:29 - please wait.
JVMDUMP032I JVM requested System dump using '/root/jvmtest/openjdk_regression/work/scratch/0/core.20190314.185629.2631.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.2675.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 2675 was not found. Expected to find core file with name "/root/jvmtest/openjdk_regression/work/scratch/0/core"
JVMDUMP032I JVM requested Heap dump using '/root/jvmtest/openjdk_regression/work/scratch/0/heapdump.20190314.185629.2631.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /root/jvmtest/openjdk_regression/work/scratch/0/heapdump.20190314.185629.2631.0002.phd
JVMDUMP032I JVM requested Java dump using '/root/jvmtest/openjdk_regression/work/scratch/0/javacore.20190314.185629.2631.0003.txt' in response to an event
JVMDUMP010I Java dump written to /root/jvmtest/openjdk_regression/work/scratch/0/javacore.20190314.185629.2631.0003.txt
JVMDUMP032I JVM requested Snap dump using '/root/jvmtest/openjdk_regression/work/scratch/0/Snap.20190314.185629.2631.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /root/jvmtest/openjdk_regression/work/scratch/0/Snap.20190314.185629.2631.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at Basic$JavaChild.main(Basic.java:358)
```

Should we expect `javaExe` and `System.getProperty("java.version")` to be in the `ProcessResults` error stream, or should those checks be removed?

**Comment by JasonFengJ9** [comment]
@sharon-wang good findings! what's the result when running same test against `RI JDK 12/11` and `OpenJ9 JDK11`?

**Comment by sharon-wang** [comment]
@JasonFengJ9 here are the results for running the same test on other JDKs

-----

**OpenJ9 JDK11**
```openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+2-201903131911)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-e36bb64e5, JRE 11 Linux amd64-64-Bit Compressed References 20190313_167 (JIT enabled, AOT enabled)
OpenJ9   - e36bb64e5
OMR      - da32e2b9
JCL      - 2d7b48535f based on jdk-11.0.3+2)
```
**Result:** 
Same as OpenJ9 JDK12 in above comment

-----

**RI JDK11**
```java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
**Result:**
```STDERR:
java.lang.Error: posix_spawn is not a supported process launch mechanism on this platform.
	at java.base/java.lang.ProcessImpl$Platform.lambda$launchMechanism$0(ProcessImpl.java:148)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.lang.ProcessImpl$Platform.launchMechanism(ProcessImpl.java:131)
	at java.base/java.lang.ProcessImpl.<clinit>(ProcessImpl.java:171)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at Basic.run(Basic.java:986)
	at Basic.realMain(Basic.java:905)
	at Basic.main(Basic.java:1066)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at Basic.realMain(Basic.java:906)
	at Basic.main(Basic.java:1066)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:1068)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
- `java.lang.Error: posix_spawn is not a supported process launch mechanism on this platform.` due to https://github.com/sharon-wang/openj9-openjdk-jdk12/blob/54484f2d8247ff8db90c0d6be6bb0a261523daab/test/jdk/java/lang/ProcessBuilder/Basic.java#L905
- `java.lang.NullPointerException` due to https://github.com/sharon-wang/openj9-openjdk-jdk12/blob/54484f2d8247ff8db90c0d6be6bb0a261523daab/test/jdk/java/lang/ProcessBuilder/Basic.java#L906 - no `ProcessResults` `err()` output because of this

-----

**RI JDK12**
```java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+10, mixed mode, sharing)
```
**Result:** 
Test is passing

-----

So it looks like `javaExe` and `System.getProperty("java.version")` are in fact in the `ProcessResults` error stream, as seen in `RI JDK12`. Seems like that info is not being written to the error stream in OpenJ9 JDK 11 and 12. Will look into why that is missing!

**Comment by pshipton** [comment]
OpenJ9 doesn't support the `-XX:OnOutOfMemoryError` option. 

There is an equivalent `-Xdump:tool:events=systhrow,filter=java/lang/OutOfMemoryError,exec="<path>/java -version"`. You could add support for `-XX:OnOutOfMemoryError` to OpenJ9, and map it to the equivalent.

**Comment by JasonFengJ9** [comment]
>  The test is failing since it is looking for javaExe and System.getProperty("java.version") in the ProcessResults error stream, however the error stream does not include that information. The out stream is empty. Only java.lang.OutOfMemoryError: is outputted to the error stream, so line 1777 of Basic.java passes.

The [line 1777 of Basic.java](https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/bb38f8aaac36f1bb22dfc2461e47fc294c00c961/test/jdk/java/lang/ProcessBuilder/Basic.java#L1777) is:
```
check(r.err().contains("java.lang.OutOfMemoryError:"));
```
@sharon-wang could you check if `OpenJ9` actually throws `java.lang.OutOfMemoryError`?

**Comment by sharon-wang** [comment]
@JasonFengJ9 

Yes, OpenJ9 is throwing `java.lang.OutOfMemoryError`

-----

Ran: `java -Xdump:none -XX:OnOutOfMemoryError="java -version" Test` 
(`-Xdump:none` to suppress JVMDUMP messages)

Where `Test` is a simple Java program to generate the OutOfMemoryError:
```
public class Test {
	public static void main(String args[]){
		Object dummy = new double[Integer.MAX_VALUE];
	}
}
```

**OpenJ9 JDK 11 and 12 Output**
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at Test.main(Test.java:3)
```

**Comment by JasonFengJ9** [comment]
Thanks @sharon-wang, that makes senses now. `java -version` probably was expected to run after OOM which is not supported by `OpenJ9`.

**Comment by JasonFengJ9** [comment]
The [java/lang/ProcessBuilder/Basic.java](https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/ProcessBuilder/Basic.java) exercises `RI` specific command line options: `-XX:+DisplayVMOutputToStderr` and `-XX:OnOutOfMemoryError=%s`. Similarly there are also option like `-XX:+DisplayVMOutputToStdout`.
@pshipton are we going to support them all? In addition, I think this issue can be moved out from `Release 0.13.0 (Java 12)`.

**Comment by pshipton** [comment]
We may not be supporting `-XX:+DisplayVMOutputToStdout` any time soon, since there is no equivalent OpenJ9 option. Depends if there is any user demand to support it. I suggested to support `-XX:OnOutOfMemoryError` for compatibility since OpenJ9 already has support for this.

**Comment by pdbain-ibm** [comment]
@sharon-wang further to our chat: it seem the mapping code is parsing and replacing the first `=` in `-Xdump:tool:events=systhrow,filter=java/lang/OutOfMemoryError,exec="<path>/java -version"`.
One solution is to improve the mapper code to handle escape  characters, so you could say `events\=systhrow,filter\=java/lang/OutOfMemoryError,exec=` and the parser would ignore the escaped `=`s.

**Comment by pdbain-ibm** [comment]
> Would I be looking at escaping each : and = that should be ignored in both the new option and the existing j9 equivalent?

Yes.  If the mapper is treating the colons specially, I would add support for escaping them.
