### ISSUE TITLE
Missing jvmtest/TestConfig/resources/excludes/latest_exclude_13.txt

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4999]
Seems to be causing some tests to fail. Are there any plans to have a 11+ exclude list?

https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/330/tapResult
```
===============================================
Running test cmdLineTester_jvmtitests_hcr_4 ...
===============================================
cmdLineTester_jvmtitests_hcr_4 Start Time: Tue Mar  5 20:21:52 2019 Epoch Time (ms): 1551817312788
variation: Mode148
JVM_OPTIONS: -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI 
java.io.FileNotFoundException: /home/jenkins/jenkins-agent/workspace/Test-Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitests_excludes_13.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:71)
	at MainTester.main(MainTester.java:97)
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:468)
	at com.oti.j9.exclude.XMLInterface.parse(XMLInterface.java:138)
	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:83)
	at com.oti.j9.exclude.ExcludeList.readFrom(ExcludeList.java:75)
	at MainTester.main(MainTester.java:97)
Exiting...
Exception in thread "main" java.lang.NullPointerException
	at MainTester.main(MainTester.java:99)

cmdLineTester_jvmtitests_hcr_4_FAILED
```

**Comment by pshipton** [comment]
@llxia @smlambert

**Comment by llxia** [comment]
jvmtitests has its own exclude per JDK version `jvmtitests_excludes_$(JDK_VERSION).xml`:
https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/jvmtitests

We have a similar issue in global exclude file `TestConfig/resources/excludes/latest_exclude_13.txt`, but it will not cause test failure. See Test_Class_0 in the above console output. There was an exception for missing `latest_exclude_13.txt`, but `Test_Class_0` executed and passed at the end.

I will add version 13 for both cases for now. I think we need to find a better solution for this issue.
