### ISSUE TITLE
java.lang.UnsupportedOperationException in j9vm.test.mxbeans.MXBeansGetterSanityTest on windows

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#500]
J9vmTest_4 failure:
+++ j9vm.test.mxbeans.MXBeansGetterSanityTest: +++
command: C:/tmp/openj9-openjdk-jdk9_latest/build/windows-x86_64-normal-server-release/images/jdk/bin\java  -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m  --add-exports=java.management/com.ibm.java.lang.management.internal=ALL-UNNAMED --add-exports=com.ibm.management/com.ibm.lang.management.internal=ALL-UNNAMED    -classpath C:/tmp/openj9-openjdk-jdk9_latest/openj9/test///..//jvmtest\VM_Test\VM_Test.jar;C:/tmp/openj9-openjdk-jdk9_latest/openj9/test///..//jvmtest\TestConfig\lib\asm-all.jar  j9vm.test.mxbeans.MXBeansGetterSanityTest
...
Calling getHardwareModel on com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
        at j9vm.test.mxbeans.MXBeansGetterSanityTest.testMXBeanGetters(MXBeansGetterSanityTest.java:48)
        at j9vm.test.mxbeans.MXBeansGetterSanityTest.main(MXBeansGetterSanityTest.java:88)
Caused by: java.lang.UnsupportedOperationException
        at com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl.getHardwareModelImpl(com.ibm.management@9-internal/Native Method)
        at com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl.getHardwareModel(com.ibm.management@9-internal/ExtendedOperatingSystemMXBeanImpl.java:193)
        ... 6 more
Calling getProcessCpuTime on com.ibm.lang.management.internal.ExtendedOperatingSystemMXBeanImpl

Environment variables :
JAVA_BIN=C:/tmp/openj9-openjdk-jdk9_latest/build/windows-x86_64-normal-server-release/images/jdk/bin
SPEC=win_x86-64_cmprssptrs
JCL_VERSION=latest
OS: windows 10

**Comment by vsebe** [comment]
attn @llxia

**Comment by pshipton** [comment]
Note the UnsupportedOperationException for getHardwareModel() is expected on Windows.

Looks like the problem is in this code as Windows doesn't use UnixExtendedOperatingSystem but ExtendedOperatingSystemMXBeanImpl.
```
						} else if (mxBeanClass.getName().equals("com.ibm.lang.management.internal.UnixExtendedOperatingSystem")
								&& methodName.equals("getHardwareModel")) {
							/* above the methods of UnixExtendedOperatingSystem could be unsupported depends on the individual OS */
```

**Comment by pshipton** [comment]
@vsebe are all 4 failures related to getHardwareModel() or are there other issues as well?

Note I expect you could resolve this one yourself with the hint from the previous comment.

**Comment by vsebe** [comment]
@pshipton only 2 failures are related. 
Will fix, thank you!

**Comment by vsebe** [comment]
Invalid
