### ISSUE TITLE
StackTraceElement.toString() missing lock information

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#5012]
The reference implementation includes lock information in the stack trace (see below for test program):
```
$ java locker.java 

testMonitorsThread:
"testMonitorsThread" prio=5 Id=12 BLOCKED on java.lang.Object@2d1ef81a owned by "main" Id=1
	at locker.syncMethod(locker.java:39)
	-  blocked on java.lang.Object@2d1ef81a
	at locker$1.run(locker.java:16)
	at java.base@11/java.lang.Thread.run(Thread.java:834)

main:
"main" prio=5 Id=1 RUNNABLE
	at java.management@11/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@11/sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:466)
	at locker.printThreadInfo(locker.java:34)
	at locker.meth(locker.java:25)
	-  locked java.lang.Object@2d1ef81a
	at locker.main(locker.java:46)
	...
```

but not OpenJ9:
```

testMonitorsThread:
"testMonitorsThread" prio=5 Id=25 BLOCKED
	at locker.syncMethod(locker.java:39)
	at locker$1.run(locker.java:16)
	at java.base/java.lang.Thread.run(Thread.java:825)


main:
"main" prio=5 Id=1 RUNNABLE
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getMultiThreadInfoImpl(Native Method)
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfoCommon(ThreadMXBeanImpl.java:322)
	at java.management/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.getThreadInfo(ThreadMXBeanImpl.java:283)
	at locker.printThreadInfo(locker.java:34)
	at locker.meth(locker.java:25)
	at locker.main(locker.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

Note that this information is available in the javacore:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.sleep(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:955)
4XESTACKTRACE                at locker.meth(locker.java:26)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000007FFF9BA00, entry count: 1)
4XESTACKTRACE                at locker.main(locker.java:46)
...
3XMTHREADBLOCK     Blocked on: java/lang/Object@0x00000007FFF9BA00 Owned by: "main" (J9VMThread:0x000000001D774A00, java/lang/Thread:0x0000000700050F98)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at locker.syncMethod(locker.java:39)
4XESTACKTRACE                at locker$1.run(locker.java:16)
```
[locker.java.txt](https://github.com/eclipse/openj9/files/2938038/locker.java.txt)

**Comment by pdbain-ibm** [comment]
Disabling `org.openj9.test.attachAPI.TestJstack:testMonitors()`.  Re-enable when this is resolved.
