### ISSUE TITLE
JCL_Test_SE80_0:test_setSecurityManager2 fails on JDK8

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#502]
This fails for SE80, however I notice in SE90 version of Test_System.java this test is not present, should we remove it from SE80?

Java8andUp/src_80/org/openj9/test/java/lang/Test_System.java

FAILED: test_setSecurityManager2
java.lang.AssertionError: Unexpected: java.lang.NullPointerException
	at org.testng.Assert.fail(Assert.java:94) from sun.misc.Launcher$AppClassLoader@1bcb56f7(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_System.test_setSecurityManager2(Test_System.java:400) from sun.misc.Launcher$AppClassLoader@1bcb56f7(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)

**Comment by smlambert** [comment]
Is it useful for you to look at the equivalent test in the internal Java8 build and comparing the results of it to the build you are testing, then understanding why there is a difference in behaviour?  I see that test_setSecurityManager2 is passing in the internal build.  I am not aware that this test should be removed in Java8, as we are currently running it against it.

**Comment by andrew-m-leonard** [comment]
Where do I find an "internal Java8 build"?

**Comment by andrew-m-leonard** [comment]
Remember IBMJava8sr5 is a different beast to OpenJ9 for OpenJDK8

**Comment by smlambert** [comment]
Yes, so we need to determine if this is an expected difference (see Slack for link to referenced build).

**Comment by pshipton** [comment]
It would help if the test didn't catch the exception and then only print the exception message. If we had the entire stack for the NPE, instead of the assert, it might be obvious what is wrong.

**Comment by pshipton** [comment]
This is a dup of #314, I'll close #314 since there are more comments here.

**Comment by smlambert** [comment]
That test was likely written years ago.  When we migrated all of these tests into the open, we did not take the time to improve them as you suggest.  Feel free to change the test so that it doesn't swallow the useful information you need.

**Comment by andrew-m-leonard** [comment]
java.lang.NullPointerException
	at org.openj9.test.support.Support_Exec.getJavaCommand(Support_Exec.java:243) from sun.misc.Launcher$AppClassLoader@5e31dcce(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava2(Support_Exec.java:134) from sun.misc.Launcher$AppClassLoader@5e31dcce(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava2(Support_Exec.java:126) from sun.misc.Launcher$AppClassLoader@5e31dcce(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at org.openj9.test.support.Support_Exec.execJava(Support_Exec.java:46) from sun.misc.Launcher$AppClassLoader@5e31dcce(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at org.openj9.test.java.lang.Test_System.test_setSecurityManager2(Test_System.java:394) from sun.misc.Launcher$AppClassLoader@5e31dcce(file:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/Java8andUp/GeneralTest.jar)

**Comment by pshipton** [comment]
Looking at the test code, the problem is caused because java.vendor doesn't not contain "Sun" or "IBM". I expect if we modify the test code to also look for "OpenJ9" and use the same code as "IBM" then the test will work.

**Comment by pshipton** [comment]
Not sure if this will also fix the test for 90. We'll have to try it and see if there is another issue on 90.

**Comment by smlambert** [comment]
ah, the classic brittle string match in code...  makes me prickly... but yes, an update to match 'openj9' would at least see this test running again.

**Comment by andrew-m-leonard** [comment]
I've just tried the vendor check and it does fix the test :-)

**Comment by andrew-m-leonard** [comment]
I'll create a PR

**Comment by pshipton** [comment]
Fixed by #514.

@smlambert Likely test_setSecurityManager2() no longer needs to be removed from src_90 as it would work now. We can keep this Issue open until this is fixed.

**Comment by DanHeidinga** [comment]
Closing this based on the previous comment indicating it's fixed.  Please reopen if that isn't the case.

**Comment by pshipton** [comment]
Ok then, opened #790, which is clearer anyway.
