### ISSUE TITLE
Various tests in  cmdLineTester_XcheckJNI_0 suite fail as they cant find j9ben library

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#503]
When running the Sanlity tests on OpenJ9 with OpenJDK8 on AIX we see lots of errors on tests in the  cmdLineTester_XcheckJNI_0 suite. These all seem to fail because the test cannot find the lj9ben library. 
The errors seen are like this:
```
 Testing: illegalmode8.4
       Test start time: 2017/10/31 13:01:10 Greenwich Mean Time
       Running command: "/home/groeges/openj9jdk8/openjdk-jdk8/build/aix-ppc64-normal-server-release/images/j2sdk-image/jre/bin/java" -cp "/home/groeges/openj9jdk8/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/cmdline_options_testresources/cmdlinetestresources.jar" -Xcheck:jni -Xgcthreads1 j9vm.test.jnichk.ModifyArrayData float 100000 -1 -1 100
       Time spent starting: 11 milliseconds
       Time spent executing: 217 milliseconds
       Test result: FAILED
       Output from test:
        [ERR] JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
        [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: j9ben (Not found in java.library.path)
        [ERR]     at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1435)
        [ERR]     at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1405)
        [ERR]     at java.lang.System.loadLibrary(System.java:567)
        [ERR]     at j9vm.test.jnichk.Test.<clinit>(Test.java:40)
       >> Success condition was not found: [Output match: JVMJNCK054E]
```
The test framework does seem to configure the LIBPATH but this is not being utilised:
```
ADD_JVM_LIB_DIR_TO_LIBPATH is set to export LIBPATH="/home/groeges/openj9jdk8/openjdk-jdk8/build/aix-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../lib/ppc64/compressedrefs:/home/groeges/openj9jdk8/openjdk-jdk8/build/aix-ppc64-normal-server-release/images/j2sdk-image/jre/bin/j9vm:";
```
If this LIBPATH is setup manually and the test run manually then the test runs OK.

**Comment by groeges** [comment]
On a suggestion from Terry I did the following:
```
adding `$(ADD_JVM_LIB_DIR_TO_LIBPATH) ` in front of `$(JAVA_COMMAND)` in the file `/test/cmdLineTests/xcheckjni/playlist.xml`, and try to re-run the XcheckJNI test with following
```
```
make -f run_configure.mk
make compile
make cmdLineTester_XcheckJNI_0```
```
when I did this all the tests in that suite passed.

**Comment by DanHeidinga** [comment]
@groeges / @TianyuZuo The previous comment describes a possible fix which sounds like it works.  Have either of you opened a PR for this change?  We're trying to get the Java 8 tests sorted out so PR builds can be enabled.

**Comment by groeges** [comment]
@DanHeidinga It looks like this was fixed in pull request https://github.com/eclipse/openj9/pull/513

As such I will close this issue.
