### ISSUE TITLE
jdk13 sanity.functional JCL_Test failures test_Constructor test_Constructor4

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5032]
```
FAILED: test_Constructor4
java.lang.AssertionError: StringBuffer
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_StringBuffer.test_Constructor4(Test_StringBuffer.java:78) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)

FAILED: test_Constructor
java.lang.AssertionError: StringBuffer
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.openj9.test.java.lang.Test_StringBuilder.test_Constructor(Test_StringBuilder.java:151) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) from jrt:/java.base
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) from jrt:/java.base
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) from jrt:/java.base
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) from jrt:/java.base
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.privateRun(TestRunner.java:648) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestRunner.run(TestRunner.java:505) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.runSuites(TestNG.java:1049) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.run(TestNG.java:1017) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.privateMain(TestNG.java:1354) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
	at org.testng.TestNG.main(TestNG.java:1323) from jdk.internal.loader.ClassLoaders$AppClassLoader@2cbd1142(file:/home/jenkins/workspace/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/jvmtest/TestConfig/lib/testng.jar)
```

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by JasonFengJ9** [comment]
The test code failed at 
https://github.com/eclipse/openj9/blob/6556bf11fa607c2e11f5022fa623e8f22610cfe9/test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuffer.java#L77-L78

`OpenJ9` doesn't own `java.lang.StringBuffer` since `Java 9`. 
It appears https://github.com/ibmruntimes/openj9-openjdk-jdk `openj9` branch hasn't got the update from `master` yet.
Pausing the investigating for now.

fyi @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
@JasonFengJ9 Which "update" are you referring to? something from OpenJDK? openj9-openjdk-jdk has not been merged from OpenJDK for 2 weeks now due to auto-merge job unreliability.

**Comment by JasonFengJ9** [comment]
> openj9-openjdk-jdk has not been merged from OpenJDK for 2 weeks now due to auto-merge job unreliability.

Thanks, this explains (Pete also just mentioned it), I saw `java.lang.StringBuffer` in `OpenJ9` branch is different from that in `master` branch.
Hopefully this test will pass when the `OpenJ9` branch is merged with latest `master` contents.

**Comment by DanHeidinga** [comment]
> openj9-openjdk-jdk has not been merged from OpenJDK for 2 weeks now due to auto-merge job unreliability.

@andrew-m-leonard Is there an issue for making the auto-merge more reliable so we can track the progress?  And hopefully an ETA on when it'll be fixed?

**Comment by andrew-m-leonard** [comment]
@DanHeidinga I've kicked off a jdk"head" merge running on my local VM in the hope it will work (I think it should). We should look at moving jdk"head" to the new merge script soon I think...

**Comment by andrew-m-leonard** [comment]
@DanHeidinga My new merge job is now ready, however we will need to force push the master & openj9 branches...

**Comment by pshipton** [comment]
@andrew-m-leonard I think we need a separate dedicated issue to discuss this, containing some explanation of what is happening.

**Comment by andrew-m-leonard** [comment]
@pshipton that would be here: https://github.ibm.com/runtimes/openjdk-contribution/issues/758

**Comment by pshipton** [comment]
@JasonFengJ9 fyi
The latest jdk stream changes have been merged. StringBuffer is the same in the openj9 branch as master. The same failures still occur.
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDKnext-linux_ppc-64_cmprssptrs_le-OpenJ9/15

**Comment by pshipton** [comment]
`new StringBuffer((CharSequence)new StringBuffer("test2"))` produces a StringBuffer with toString() `tes`

**Comment by pshipton** [comment]
@JasonFengJ9 a hotspot build doesn't have the same behavior, so we need to look into why it occurs with OpenJ9. Using -Xint doesn't affect the output.

**Comment by JasonFengJ9** [comment]
Yeah, `RI` does work. `OpenJ9` patched with `StringBuffer.class` from `RI` still fails. It is an encoding problem and appears related to `toString()`.

**Comment by JasonFengJ9** [comment]
Here is how the failure occurred:
1. `new StringBuffer("test2")` constructed a `StringBuffer extends AbstractStringBuilder` object `SB1` with a `String` object `"test2"` which is encoded as `UTF16`, and the `coder` within this `StringBuffer` object is set to `UTF16` as well;
2. `new StringBuffer((CharSequence)new StringBuffer("test2"))` constructs second `StringBuffer` object `SB2` with first `StringBuffer` object `SB1` created in last step, however `StringBuffer(CharSequence seq)` assumes `String.LATIN1` encoding as per [super(String.LATIN1, seq.length(), 16);](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/52380253f7abd5346f11d842965a2862621eca1a/src/java.base/share/classes/java/lang/StringBuffer.java#L165)
3. Later on when comparing these two `StringBuffer` objects to determine if `inflate();` is required, `AbstractStringBuilder.getCoder()` returns same `coder` because it is implemented as [return COMPACT_STRINGS ? coder : UTF16;](https://github.com/JasonFengJ9/openj9-openjdk-jdk/blob/40bef5e626a5ea6ff8743f5917834d149445e7fe/src/java.base/share/classes/java/lang/AbstractStringBuilder.java#L1616-L1618) in which `COMPACT_STRINGS` is `java.lang.String.COMPACT_STRINGS` owned by `OpenJ9`. `COMPACT_STRINGS` hasn't been enabled in `OpenJ9` yet, hence `UTF16` is returned regardless the `coder` values for `SB1` and `SB2`. 
Mismatching of `coder` values within these two `StringBuffer` objects caused the failure.

Running the standalone testcase with `-XX:+CompactStrings` makes it pass.

Maybe it is the time to enable `COMPACT_STRINGS` for `Java 13+` by default?

fyi: @DanHeidinga @pshipton @fjeremic

**Comment by fjeremic** [comment]
2. looks incorrect. Why is the assumption that the coder is `String.LATIN1`? Presumably if you disable compact strings on HotSpot (`-XX:+CompactStrings`) you should see the same behaviour as OpenJ9, no?

**Comment by JasonFengJ9** [comment]
`RI` does go bad with `-XX:-CompactStrings`.

**Comment by pshipton** [comment]
@andrew-m-leonard please see the above, which describes a bug in the openjdk jdk13 code when running with `-XX:-CompactStrings`

**Comment by andrew-m-leonard** [comment]
OpenJDK bug raised: https://bugs.openjdk.java.net/browse/JDK-8221430
I have a fix in progress

**Comment by pshipton** [comment]
@JasonFengJ9 did we exclude any test for this? I don't see any record of this, just double checking. Otherwise the OpenJDK problem has been resolved, the tests are passing, and this can be closed.

**Comment by JasonFengJ9** [comment]
@pshipton there was no test excluded. No action required.
This can be closed.
