### ISSUE TITLE
JTReg test fail - Macos java8 : java/rmi/activation/Activatable/checkActivateRef/CheckActivateRef.java

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#5049]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/132/console

- JTReg rmi tests 
- Macos
- JDK8
- build level : 

```
07:11:07  openjdk version "1.8.0_202-internal"
07:11:07  OpenJDK Runtime Environment (build 1.8.0_202-internal-201903110454-b08)
07:11:07  Eclipse OpenJ9 VM (build master-f0820b5ca, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190311_181 (JIT enabled, AOT enabled)
07:11:07  OpenJ9   - f0820b5ca
07:11:07  OMR      - 5f74eb34
07:11:07  JCL      - 9dc1c4d81c based on )
```

Optional info
-------------

- intermittent failure : yes 
- regression or new test:  java/rmi/activation/Activatable/checkActivateRef/CheckActivateRef.java

Failure output
--------------

```
08:30:40  ACTIVATION_LIBRARY: Activation System available after 800 milliseconds
08:30:40  RMID: finished starting rmid.
08:30:40  Create activation group in this VM
08:30:40  TEST FAILED: 
08:30:40  Test failed with: null
08:30:40  java.lang.NullPointerException
08:30:40  	at CheckActivateRef.main(CheckActivateRef.java:140)
08:30:40  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:30:40  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:30:40  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:30:40  	at java.lang.reflect.Method.invoke(Method.java:498)
08:30:40  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
08:30:40  	at java.lang.Thread.run(Thread.java:813)
08:30:40  ACTIVATION_LIBRARY: Activation System available after 0 milliseconds
08:30:40  RMID: getting a reference to the activation system
08:30:40  RMID: obtained a reference to the activation system
08:30:40  TEST FAILED: reference to the activation system was null
08:30:40  RMID: caught exception trying to shutdown rmid
08:30:40  RMID: TEST FAILED: reference to the activation system was null
08:30:40  TestFailedException: TEST FAILED: reference to the activation system was null
08:30:40  	at TestLibrary.bomb(TestLibrary.java:121)
08:30:40  	at TestLibrary.bomb(TestLibrary.java:124)
08:30:40  	at RMID.shutdown(RMID.java:291)
08:30:40  	at RMID.destroy(RMID.java:313)
08:30:40  	at ActivationLibrary$DestroyThread.run(ActivationLibrary.java:220)
08:30:40  RMID: testlibrary finished shutting down rmid
```

**Comment by sophia-guo** [comment]
Same issue;
java/rmi/activation/Activatable/createPrivateActivable/CreatePrivateActivatable.java

Code:

```
            ActivationSystem system = ActivationGroup.getSystem();
            ActivationGroupID groupID = system.registerGroup(groupDesc);
```

**Comment by LongyuZhang** [comment]
This file also failed for JDK8 Windows jdk_rmi test on multiple machines:
 http://trss1.fyre.ibm.com/deepHistory?testId=60fc575555ecc3ddada3ae85
```
21:14:33  Activate object via method call
21:14:33  Fri Jul 23 18:14:28 PDT 2021:ExecGroup-0:err:ACTIVATION_LIBRARY: inactive successful
21:14:33  TEST FAILED: 
21:14:33  Test failed with: activation failed; nested exception is: 
21:14:33  	java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
21:14:33  	java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:304)
21:14:33  	at sun.rmi.server.ActivatableRef.invoke(ActivatableRef.java:220)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
21:14:33  	at $Proxy4.ping(Unknown Source)
21:14:33  	at CheckActivateRef.main(CheckActivateRef.java:172)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  Caused by: java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivationGroupImpl.newInstance(ActivationGroupImpl.java:313)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
21:14:33  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
21:14:33  	at java.rmi.activation.ActivationGroup_Stub.newInstance(Unknown Source)
21:14:33  	at sun.rmi.server.Activation$ObjectEntry.activate(Activation.java:1494)
21:14:33  	at sun.rmi.server.Activation$GroupEntry.activate(Activation.java:1180)
21:14:33  	at sun.rmi.server.Activation$ActivatorImpl.activate(Activation.java:409)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
21:14:33  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
21:14:33  	at com.sun.proxy.$Proxy3.activate(Unknown Source)
21:14:33  	at java.rmi.activation.ActivationID.activate(ActivationID.java:132)
21:14:33  	at sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:277)
21:14:33  	... 11 more
21:14:33  Caused by: sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivationGroupImpl.newInstance(ActivationGroupImpl.java:220)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	... 1 more
21:14:33  RMID: shutdown()
21:14:33  RMID: ActivationSystem.shutdown()
21:14:33  activation daemon shut down
21:14:33  RMID: Shutdown successful.
21:14:33  RMID: Removing rmid's old log file.
21:14:33  TestFailedException: TEST FAILED: ; nested exception is: 
21:14:33  	java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
21:14:33  	java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
21:14:33  	java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:304)
21:14:33  	at sun.rmi.server.ActivatableRef.invoke(ActivatableRef.java:220)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
21:14:33  	at $Proxy4.ping(Unknown Source)
21:14:33  	at CheckActivateRef.main(CheckActivateRef.java:172)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  Caused by: java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivationGroupImpl.newInstance(ActivationGroupImpl.java:313)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
21:14:33  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
21:14:33  	at java.rmi.activation.ActivationGroup_Stub.newInstance(Unknown Source)
21:14:33  	at sun.rmi.server.Activation$ObjectEntry.activate(Activation.java:1494)
21:14:33  	at sun.rmi.server.Activation$GroupEntry.activate(Activation.java:1180)
21:14:33  	at sun.rmi.server.Activation$ActivatorImpl.activate(Activation.java:409)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	at java.lang.Thread.run(Thread.java:826)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
21:14:33  	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
21:14:33  	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:235)
21:14:33  	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:180)
21:14:33  	at com.sun.proxy.$Proxy3.activate(Unknown Source)
21:14:33  	at java.rmi.activation.ActivationID.activate(ActivationID.java:132)
21:14:33  	at sun.rmi.server.ActivatableRef.activate(ActivatableRef.java:277)
21:14:33  	... 11 more
21:14:33  Caused by: sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  	at sun.rmi.server.ActivationGroupImpl.newInstance(ActivationGroupImpl.java:220)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:14:33  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:14:33  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:14:33  	at java.lang.reflect.Method.invoke(Method.java:498)
21:14:33  	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:200)
21:14:33  	at sun.rmi.transport.Transport$1.run(Transport.java:197)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:774)
21:14:33  	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$9/0x0000000000000000.run(Unknown Source)
21:14:33  	at java.security.AccessController.doPrivileged(AccessController.java:708)
21:14:33  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:14:33  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:14:33  	... 1 more
21:14:33  
21:14:33  JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: ; nested exception is: 
21:14:33  	java.rmi.activation.ActivateFailedException: activation failed; nested exception is: 
21:14:33  	java.rmi.activation.ActivationException: unable to activate object; nested exception is: 
21:14:33  	sun.rmi.server.InactiveGroupException: group is inactive
21:14:33  JavaTest Message: shutting down test
21:14:33  
21:14:33  STATUS:Failed.`main' threw exception: TestFailedException: TEST FAILED: ; nested exception is: java.rmi.activation.ActivateFailedException: activation failed; nested exception is: java.rmi.activation.ActivationException: unable to activate object; nested exception is: sun.rmi.server.InactiveGroupException: group is inactive
```

**Comment by JasonFengJ9** [comment]
[0.36 internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_extended.openjdk_x86-64_mac_testList_1/2/)(`mac12x64rt15`)
```
openjdk version "1.8.0_362"
IBM Semeru Runtime Open Edition (build 1.8.0_362-b09)
Eclipse OpenJ9 VM (build openj9-0.36.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20230207_620 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - eebde685ec based on jdk8u362-b09)
```

```
[2023-02-10T11:05:21.549Z] variation: Mode150
[2023-02-10T11:05:21.549Z] JVM_OPTIONS:  -XX:+UseCompressedOops 

[2023-02-10T11:05:42.248Z] TEST: java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java

[2023-02-10T11:05:42.251Z] STDERR:
[2023-02-10T11:05:42.251Z] 
[2023-02-10T11:05:42.251Z] Regression test for bug/rfe 4254808
[2023-02-10T11:05:42.251Z] 
[2023-02-10T11:05:42.251Z] Starting registry on default port
[2023-02-10T11:05:42.251Z] TEST FAILED: registry already running on test port
[2023-02-10T11:05:42.251Z] TestFailedException: TEST FAILED: registry already running on test port
[2023-02-10T11:05:42.251Z] 	at TestLibrary.bomb(TestLibrary.java:121)
[2023-02-10T11:05:42.251Z] 	at TestLibrary.bomb(TestLibrary.java:124)
[2023-02-10T11:05:42.251Z] 	at LegalRegistryNames.main(LegalRegistryNames.java:76)
[2023-02-10T11:05:42.251Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-02-10T11:05:42.251Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-02-10T11:05:42.251Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-02-10T11:05:42.251Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-02-10T11:05:42.251Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-02-10T11:05:42.251Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-02-10T11:05:42.251Z] 
[2023-02-10T11:05:42.251Z] JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: registry already running on test port

[2023-02-10T11:05:42.252Z] TEST RESULT: Failed. Execution failed: `main' threw exception: TestFailedException: TEST FAILED: registry already running on test port
[2023-02-10T11:05:42.252Z] --------------------------------------------------
[2023-02-10T11:07:36.535Z] Test results: passed: 115; failed: 1
[2023-02-10T11:07:39.939Z] Report written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac_testList_1/aqa-tests/TKG/output_16760257303768/jdk_rmi_0/report/html/report.html
[2023-02-10T11:07:39.939Z] Results written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.openjdk_x86-64_mac_testList_1/aqa-tests/TKG/output_16760257303768/jdk_rmi_0/work
[2023-02-10T11:07:39.939Z] Error: Some tests failed or other problems occurred.
[2023-02-10T11:07:39.939Z] -----------------------------------
[2023-02-10T11:07:39.939Z] jdk_rmi_0_FAILED
```
