### ISSUE TITLE
Remote AOT segfault

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#5077]
I'm frequently getting the following segfault when running AcmeAir on lara perf machine:
```
#0  0x00007f39854dd9b1 in pthread_kill () from /lib64/libpthread.so.0
#1  0x00007f3982f83eed in omrdump_create (portLibrary=0x7f3983dc9380 <j9portLibrary>, filename=0x7f398063f880 "/home/dmitry-ten/", dumpType=<optimized out>, userData=<optimized out>)
    at ../../omr/port/unix/omrosdump.c:188
#2  0x00007f39826e84e2 in doSystemDump (agent=0x7f397c025ad0, label=0x7f398063f880 "/home/dmitry-ten/", context=0x7f398063fd30) at dmpagent.c:718
#3  0x00007f39826e4365 in protectedDumpFunction (portLibrary=portLibrary@entry=0x7f3983dc9380 <j9portLibrary>, userData=userData@entry=0x7f398063f7e0) at dmpagent.c:2876
#4  0x00007f3982f56ec8 in omrsig_protect (portLibrary=0x7f3983dc9380 <j9portLibrary>, fn=0x7f39826e4350 <protectedDumpFunction>, fn_arg=0x7f398063f7e0, handler=0x7f39826e4370 <signalHandler>, handler_arg=0x0,
    flags=125, result=0x7f398063f7d8) at ../../omr/port/unix/omrsignal.c:384
#5  0x00007f39826e796b in runDumpFunction (agent=<optimized out>, label=0x7f398063f880 "/home/dmitry-ten/", context=<optimized out>) at dmpagent.c:2850
#6  0x00007f39826e7aec in runDumpAgent (vm=vm@entry=0x7f397c010310, agent=agent@entry=0x7f397c025ad0, context=context@entry=0x7f398063fd30, state=state@entry=0x7f398063fd28,
    detail=detail@entry=0x7f398063fdb0 "", timeNow=timeNow@entry=1552420882963) at dmpagent.c:2776
#7  0x00007f39826fe55b in triggerDumpAgents (vm=0x7f397c010310, self=0x22a3400, eventFlags=8192, eventData=<optimized out>) at trigger.c:1028
#8  0x00007f398366f6f2 in generateDiagnosticFiles (portLibrary=portLibrary@entry=0x7f3983dc9380 <j9portLibrary>, userData=userData@entry=0x7f3980640290) at gphandle.c:1170
#9  0x00007f3982f56ec8 in omrsig_protect (portLibrary=0x7f3983dc9380 <j9portLibrary>, fn=0x7f398366f610 <generateDiagnosticFiles>, fn_arg=0x7f3980640290, handler=0x7f398366ed10 <recursiveCrashHandler>,
    handler_arg=0x7f3980640260, flags=125, result=0x7f3980640258) at ../../omr/port/unix/omrsignal.c:384
#10 0x00007f398366f8e6 in vmSignalHandler (portLibrary=0x7f3983dc9380 <j9portLibrary>, gpType=4, gpInfo=0x7f3980641170, userData=<optimized out>) at gphandle.c:841
#11 0x00007f3982f5614f in masterSynchSignalHandler (signal=11, sigInfo=0x7f3980641330, contextInfo=0x7f3980641200) at ../../omr/port/unix/omrsignal.c:1001
#12 <signal handler called>
#13 0x00007f397445e760 in OMR::SymbolReference::getSymbol (this=0x0) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/il/OMRSymbolReference.hpp:192
#14 0x00007f3974a5e7da in OMR::Node::createLoad (originatingByteCodeNode=0x7f3972971960, symRef=0x0) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/il/OMRNode.cpp:1253
#15 0x00007f3974cdf086 in OMR::ValuePropagation::createReferenceArrayNodeWithoutFlags (this=0x7f39729d7020, tree=0x7f39729bf480, newTree=0x7f3972a77640, srcObjectRef=0x0, dstObjectRef=0x0,
    lenRef=0x7f3972a773e0, srcRef=0x0, dstRef=0x0, useFlagsOnOriginalArraycopy=true) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMRValuePropagation.cpp:6816
#16 0x00007f3974cdf2ef in OMR::ValuePropagation::transformReferenceArrayCopyWithoutCreatingStoreTrees (this=0x7f39729d7020, arrayTree=0x7f3972a5ad00, srcObjRef=0x0, dstObjRef=0x0, srcRef=0x0, dstRef=0x0,
    lenRef=0x7f3972a773e0) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMRValuePropagation.cpp:6860
#17 0x00007f3974cdf829 in OMR::ValuePropagation::transformReferenceArrayCopy (this=0x7f39729d7020, arrayTree=0x7f3972a5ad00)
    at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMRValuePropagation.cpp:6917
#18 0x00007f3974ce13b3 in OMR::ValuePropagation::doDelayedTransformations (this=0x7f39729d7020) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMRValuePropagation.cpp:7326
#19 0x00007f397491c473 in J9::ValuePropagation::doDelayedTransformations (this=0x7f39729d7020) at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/optimizer/J9ValuePropagation.cpp:930
#20 0x00007f3974cd329c in TR::GlobalValuePropagation::perform (this=0x7f39729d7020) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMRValuePropagation.cpp:3805
#21 0x00007f3974c64b45 in OMR::Optimizer::performOptimization (this=0x7f39729870d0, optimization=0x7f39754130a0 <cheapGlobalValuePropagationOpts+32>, firstOptIndex=0, lastOptIndex=2147483647, doTiming=0)
    at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMROptimizer.cpp:2049
#22 0x00007f3974c63020 in OMR::Optimizer::performOptimization (this=0x7f39729870d0, optimization=0x7f397536b398 <cheapWarmStrategyOpts+88>, firstOptIndex=0, lastOptIndex=2147483647, doTiming=0)
    at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMROptimizer.cpp:1595
#23 0x00007f3974c615f0 in OMR::Optimizer::optimize (this=0x7f39729870d0) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/optimizer/OMROptimizer.cpp:1130
#24 0x00007f39749efc6d in OMR::Compilation::performOptimizations (this=0x7f39728e7000) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/compile/OMRCompilation.cpp:1292
#25 0x00007f39749eebfe in OMR::Compilation::compile (this=0x7f39728e7000) at /root/openj9-openjdk-jdk8/openj9/runtime/omr/compiler/compile/OMRCompilation.cpp:1073
#26 0x00007f39744d9376 in TR::CompilationInfoPerThreadBase::compile (this=0x7f398065d4d0, vmThread=0x22a3400, compiler=0x7f39728e7000, compilee=0x7f39806475a8, vm=..., optimizationPlan=0x7f398073e510,
    scratchSegmentProvider=...) at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:8710
#27 0x00007f39744d7716 in TR::CompilationInfoPerThreadBase::wrappedCompile (portLib=0x7f3983dc9380 <j9portLibrary>, opaqueParameters=0x7f3980647320)
    at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:8241
#28 0x00007f3982f56ec8 in omrsig_protect (portLibrary=0x7f3983dc9380 <j9portLibrary>, fn=0x7f39744d504c <TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*)>, fn_arg=0x7f3980647320,
    handler=0x7f39744bf85a <jitSignalHandler(J9PortLibrary*, U_32, void*, void*)>, handler_arg=0x22a3400, flags=61, result=0x7f39806472f0) at ../../omr/port/unix/omrsignal.c:384
#29 0x00007f39744d4bd7 in TR::CompilationInfoPerThreadBase::compile (this=0x7f398065d4d0, vmThread=0x22a3400, entry=0x7f3854006ca0, scratchSegmentProvider=...)
    at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:7437
#30 0x00007f397472946f in TR::CompilationInfoPerThreadRemote::processEntry (this=0x7f398065d4d0, entry=..., scratchSegmentProvider=...)
    at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/JITaaSCompilationThread.cpp:3978
#31 0x00007f39744ca659 in TR::CompilationInfoPerThread::processEntries (this=0x7f398065d4d0) at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3777
#32 0x00007f39744c9efa in TR::CompilationInfoPerThread::run (this=0x7f398065d4d0) at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3648
#33 0x00007f39744c9cb5 in protectedCompilationThreadProc (compInfoPT=0x7f398065d4d0) at /root/openj9-openjdk-jdk8/openj9/runtime/compiler/control/CompilationThread.cpp:3591
....
```

A quick inspection tells me that a problem starts in frame 17, in `OMR::ValuePropagation::transformReferenceArrayCopy`.
This method calls `createStoresForArraycopyChildren`. to set pointers to args of the next frame,
but all of them remain NULL. 
```
void OMR::ValuePropagation::transformReferenceArrayCopy(TR_TreeTopWrtBarFlag *arrayTree)
   {
   TR::Node *node = arrayTree->_treetop->getNode();
   if (node->getOpCodeValue() != TR::arraycopy)
      node = node->getFirstChild();

   TR::SymbolReference *srcObjRef = NULL;
   TR::SymbolReference *dstObjRef = NULL;
   TR::SymbolReference *srcRef = NULL;
   TR::SymbolReference *dstRef = NULL;
   TR::SymbolReference *lenRef = NULL;

   createStoresForArraycopyChildren(comp(), arrayTree->_treetop, srcObjRef, dstObjRef, srcRef, dstRef, lenRef);

   transformReferenceArrayCopyWithoutCreatingStoreTrees(arrayTree, srcObjRef, dstObjRef, srcRef, dstRef, lenRef);
   }
```
And since this crash appears only in remote AOT mode, it has to be related to AOT somehow.
Investigating.

**Comment by mpirvu** [comment]
Fixed by #5099
