### ISSUE TITLE
java_lang_invoke_MethodHandlesProxiesTest failure on jdk12 

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#5087]
Failure link:
--------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_linux/18/testReport/

- test category: openjdk
- test suite name: jdk_lang
- OS/architecture: fails on all platforms

java -version
11:23:42  openjdk version "12" 2019-03-19
11:23:42  OpenJDK Runtime Environment AdoptOpenJDK (build 12+32-201903141003)
11:23:42  Eclipse OpenJ9 VM AdoptOpenJDK (build master-135f0b3f7, JRE 12 Linux amd64-64-Bit Compressed References 20190314_32 (JIT enabled, AOT enabled)
11:23:42  OpenJ9   - 135f0b3f7
11:23:42  OMR      - da32e2b9
11:23:42  JCL      - bb38f8aaac based on jdk-12+32)

Optional info
-------------
- intermittent failure: no
- regression:  yes, started failing on March 13

Failure output
--------------
```
11:32:35  [TestNG] Running:
11:32:35    java/lang/invoke/MethodHandlesProxiesTest.java
11:32:35  
11:32:35  test test.java.lang.invoke.MethodHandlesProxiesTest.testDefaultMethods(): failure
11:32:35  java.lang.InternalError: java.lang.IllegalAccessException: test/java/lang/invoke/MethodHandlesProxiesTest$A is not a direct superinterface of com/sun/proxy/jdk/proxy1/$Proxy3.
11:32:35  	at java.base/java.lang.invoke.MethodHandleProxies.lambda$callDefaultMethod$0(MethodHandleProxies.java:363)
11:32:35  	at java.lang.invoke.MethodHandleProxies$$Lambda$14.000000003C1960B0.apply(Unknown Source)
11:32:35  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
11:32:35  	at java.base/java.lang.invoke.MethodHandleProxies.callDefaultMethod(MethodHandleProxies.java:350)
11:32:35  	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:202)
11:32:35  	at jdk.proxy1/com.sun.proxy.jdk.proxy1.$Proxy3.a(Unknown Source)
11:32:35  	at test.java.lang.invoke.MethodHandlesProxiesTest.testDefaultMethods(MethodHandlesProxiesTest.java:87)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:32:35  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:32:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
11:32:35  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
11:32:35  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
11:32:35  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
11:32:35  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
11:32:35  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
11:32:35  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
11:32:35  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
11:32:35  	at org.testng.TestRunner.run(TestRunner.java:623)
11:32:35  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
11:32:35  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
11:32:35  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
11:32:35  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
11:32:35  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
11:32:35  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
11:32:35  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
11:32:35  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
11:32:35  	at org.testng.TestNG.run(TestNG.java:1018)
11:32:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
11:32:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:32:35  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:32:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
11:32:35  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:32:35  	at java.base/java.lang.Thread.run(Thread.java:825)
11:32:35  Caused by: java.lang.IllegalAccessException: test/java/lang/invoke/MethodHandlesProxiesTest$A is not a direct superinterface of com/sun/proxy/jdk/proxy1/$Proxy3.
11:32:35  	at java.base/java.lang.invoke.PrimitiveHandle.finishMethodInitialization(PrimitiveHandle.java:196)
11:32:35  	at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:51)
11:32:35  	at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:43)
11:32:35  	at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecialImpl(MethodHandles.java:576)
11:32:35  	at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:544)
11:32:35  	at java.base/java.lang.invoke.MethodHandleProxies.lambda$callDefaultMethod$0(MethodHandleProxies.java:354)
11:32:35  	... 35 more
11:32:35  test test.java.lang.invoke.MethodHandlesProxiesTest.testOverriddenDefaultMethods(): success
11:32:35  
11:32:35  ===============================================
11:32:35  java/lang/invoke/MethodHandlesProxiesTest.java
11:32:35  Total tests run: 2, Failures: 1, Skips: 0
11:32:35  ===============================================
11:32:35  
11:32:35  STDERR:
11:32:35  java.lang.Exception: failures: 1
11:32:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
11:32:35  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:32:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:32:35  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:32:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
11:32:35  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:32:35  	at java.base/java.lang.Thread.run(Thread.java:825)
11:32:35  
11:32:35  JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
11:32:35  JavaTest Message: shutting down test
```

**Comment by JasonFengJ9** [comment]
This appears a regression.

**Comment by JasonFengJ9** [comment]
fyi @keithc-ca https://github.com/eclipse/openj9/commit/58fccf2b499cb92f19c1d86cc071197a998a8a02

**Comment by smlambert** [comment]
Excluded via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/985
