### ISSUE TITLE
git Error fetching remote repo - fatal: index file smaller than expected

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5128]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/877
```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse/openj9.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: remote: Enumerating objects: 61, done.        
remote: Counting objects:   1% (1/61)           
remote: Counting objects:   3% (2/61)           
remote: Counting objects:   4% (3/61)           
remote: Counting objects:   6% (4/61)           
remote: Counting objects:   8% (5/61)           
remote: Counting objects:   9% (6/61)           
remote: Counting objects:  11% (7/61)           
remote: Counting objects:  13% (8/61)           
remote: Counting objects:  14% (9/61)           
remote: Counting objects:  16% (10/61)           
remote: Counting objects:  18% (11/61)           
remote: Counting objects:  19% (12/61)           
remote: Counting objects:  21% (13/61)           
remote: Counting objects:  22% (14/61)           
remote: Counting objects:  24% (15/61)           
remote: Counting objects:  26% (16/61)           
remote: Counting objects:  27% (17/61)           
remote: Counting objects:  29% (18/61)           
remote: Counting objects:  31% (19/61)           
remote: Counting objects:  32% (20/61)           
remote: Counting objects:  34% (21/61)           
remote: Counting objects:  36% (22/61)           
remote: Counting objects:  37% (23/61)           
remote: Counting objects:  39% (24/61)           
remote: Counting objects:  40% (25/61)           
remote: Counting objects:  42% (26/61)           
remote: Counting objects:  44% (27/61)           
remote: Counting objects:  45% (28/61)           
remote: Counting objects:  47% (29/61)           
remote: Counting objects:  49% (30/61)           
remote: Counting objects:  50% (31/61)           
remote: Counting objects:  52% (32/61)           
remote: Counting objects:  54% (33/61)           
remote: Counting objects:  55% (34/61)           
remote: Counting objects:  57% (35/61)           
remote: Counting objects:  59% (36/61)           
remote: Counting objects:  60% (37/61)           
remote: Counting objects:  62% (38/61)           
remote: Counting objects:  63% (39/61)           
remote: Counting objects:  65% (40/61)           
remote: Counting objects:  67% (41/61)           
remote: Counting objects:  68% (42/61)           
remote: Counting objects:  70% (43/61)           
remote: Counting objects:  72% (44/61)           
remote: Counting objects:  73% (45/61)           
remote: Counting objects:  75% (46/61)           
remote: Counting objects:  77% (47/61)           
remote: Counting objects:  78% (48/61)           
remote: Counting objects:  80% (49/61)           
remote: Counting objects:  81% (50/61)           
remote: Counting objects:  83% (51/61)           
remote: Counting objects:  85% (52/61)           
remote: Counting objects:  86% (53/61)           
remote: Counting objects:  88% (54/61)           
remote: Counting objects:  90% (55/61)           
remote: Counting objects:  91% (56/61)           
remote: Counting objects:  93% (57/61)           
remote: Counting objects:  95% (58/61)           
remote: Counting objects:  96% (59/61)           
remote: Counting objects:  98% (60/61)           
remote: Counting objects: 100% (61/61)           
remote: Counting objects: 100% (61/61), done.        
remote: Compressing objects:  14% (1/7)           
remote: Compressing objects:  28% (2/7)           
remote: Compressing objects:  42% (3/7)           
remote: Compressing objects:  57% (4/7)           
remote: Compressing objects:  71% (5/7)           
remote: Compressing objects:  85% (6/7)           
remote: Compressing objects: 100% (7/7)           
remote: Compressing objects: 100% (7/7), done.        
remote: Total 72 (delta 55), reused 55 (delta 54), pack-reused 11        
From https://github.com/eclipse/openj9
 + 3a8a4e3f9...066b669b5 refs/pull/1508/merge -> origin/pr/1508/merge  (forced update)
 + 639083aef...544fb717b refs/pull/5024/merge -> origin/pr/5024/merge  (forced update)
 + a3b6cf51a...6a5f32f3b refs/pull/5103/merge -> origin/pr/5103/merge  (forced update)
 + 8dda716dc...22c0391f9 refs/pull/5106/merge -> origin/pr/5106/merge  (forced update)
 + 9bafbe0da...33b2430de refs/pull/5112/merge -> origin/pr/5112/merge  (forced update)
 + 799c69f5f...862cf2806 refs/pull/5117/merge -> origin/pr/5117/merge  (forced update)
 + 8d51c3ff4...b8b239d9a refs/pull/5118/merge -> origin/pr/5118/merge  (forced update)
 + 4938cddff...a7ddc9864 refs/pull/5119/merge -> origin/pr/5119/merge  (forced update)
 * [new ref]             refs/pull/5125/head  -> origin/pr/5125/head
 * [new ref]             refs/pull/5125/merge -> origin/pr/5125/merge
 * [new ref]             refs/pull/5126/head  -> origin/pr/5126/head
 * [new ref]             refs/pull/5126/merge -> origin/pr/5126/merge
fatal: index file smaller than expected
```

**Comment by pshipton** [comment]
Other builds are working, such as https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/294/

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
Seems specific to plinux jdk8 testing

**Comment by pshipton** [comment]
Another failing example here https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/878/

**Comment by AdamBrousseau** [comment]
Cleaned up the workspaces on master. Seems to be working. Once the builds switch over (#2836) these won't run on master anymore and shouldn't leave anything behind from build to build.
