### ISSUE TITLE
Test-extended.functional-JDK11-win_x86-64_cmprssptrs hang creating core file

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5135]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/196
win2012r2-x86-6
```
01:38:00  Testing: Create core file
01:38:00  Test start time: 2019/03/18 00:38:05 Central Standard Time
01:38:00  Running command: "C:/Users/jenkins/workspace/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\\java" -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=shareddbgext -cp C:/Users/jenkins/workspace/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\functional\cmdLineTests\utils\utils.jar -Xdump:system:file=j9core1.dmp,events=vmstop org.openj9.test.ivj.Hanoi 2
01:38:00  Time spent starting: 15 milliseconds
01:48:03  ***[TEST INFO 2019/03/18 00:48:05] ProcessKiller detected a timeout after 600000 milliseconds!***
01:48:03  INFO: getUnixPID() has failed indicating this is not a UNIX System.'Debug on timeout' is currently only supported on Linux.
01:48:03  Output from test:
01:48:03   [OUT] Beginning puzzle.  Solving for 2 disks.
01:48:03   [OUT] Moved disk 0 to 1
01:48:03   [OUT] Moved disk 0 to 2
01:48:03   [OUT] Moved disk 1 to 2
01:48:03   [OUT] Puzzle solved!
01:48:03   [ERR] JVMDUMP039I Processing dump event "vmstop", detail "#0000000000000000" at 2019/03/18 00:38:06 - please wait.
01:48:03   [ERR] JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15528857591924\cmdLineTester_shrcdbgddrext_1\j9core1.dmp' in response to an event
Cancelling nested steps due to timeout
10:49:55  Sending interrupt signal to process
10:50:15  After 20s process did not stop
10:50:16  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to win2012r2-x86-6
10:50:16  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
10:50:16  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
10:50:16  		at hudson.remoting.Channel.call(Channel.java:955)
10:50:16  		at hudson.FilePath.act(FilePath.java:1072)
10:50:16  		at hudson.FilePath.act(FilePath.java:1061)
10:50:16  		at hudson.FilePath.deleteRecursive(FilePath.java:1268)
10:50:16  		at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.cleanup(FileMonitoringTask.java:349)
10:50:16  		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution$1.run(DurableTaskStep.java:409)
10:50:16  		at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
10:50:16  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:50:16  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:50:16  		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
10:50:16  		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
10:50:16  		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:50:16  		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:50:16  		at java.lang.Thread.run(Thread.java:748)
10:50:16  java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs@tmp\durable-f5d92687\jenkins-log.txt
10:50:16  	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
10:50:16  	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
10:50:16  	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
10:50:16  	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
10:50:16  	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
10:50:16  	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
10:50:16  	at java.nio.file.Files.readAttributes(Files.java:1737)
10:50:16  	at hudson.Util.isSymlink(Util.java:531)
10:50:16  	at hudson.FilePath.deleteRecursive(FilePath.java:1295)
10:50:16  	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
10:50:16  	at hudson.FilePath.deleteRecursive(FilePath.java:1304)
10:50:16  	at hudson.FilePath.access$1600(FilePath.java:213)
10:50:16  	at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1274)
10:50:16  	at hudson.FilePath$DeleteRecursive.invoke(FilePath.java:1270)
10:50:16  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
10:50:16  	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
10:50:16  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:50:16  	at hudson.remoting.Request$2.run(Request.java:369)
10:50:16  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
10:50:16  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:50:16  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:50:16  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:50:16  	at java.lang.Thread.run(Thread.java:813)
10:50:23  touch: cannot touch 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs@tmp\durable-f5d92687\jenkins-log.txt': Permission denied
10:50:26  touch: cannot touch 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs@tmp\durable-f5d92687\jenkins-log.txt': Permission denied
10:50:29  touch: cannot touch 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs@tmp\durable-f5d92687\jenkins-log.txt': Permission denied
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Looks like something hung in the sdk or test while generating a core file??  ~9 hours before the connection was terminated.

```
01:48:03   [ERR] JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15528857591924\cmdLineTester_shrcdbgddrext_1\j9core1.dmp' in response to an event
Cancelling nested steps due to timeout
10:49:55  Sending interrupt signal to process
```

Machine seems to be doing pull requests without issue atm.

**Comment by pshipton** [comment]
Happening again.
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/197/
win2012r2-x86-1
```
1:47:36  Testing: Create core file
01:47:36  Test start time: 2019/03/19 00:47:40 Central Standard Time
01:47:36  Running command: "C:/Users/jenkins/workspace/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\\java" -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=shareddbgext -cp C:/Users/jenkins/workspace/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/openjdk-tests///..//jvmtest\functional\cmdLineTests\utils\utils.jar -Xdump:system:file=j9core1.dmp,events=vmstop org.openj9.test.ivj.Hanoi 2
01:47:36  Time spent starting: 6 milliseconds
01:57:38  ***[TEST INFO 2019/03/19 00:57:40] ProcessKiller detected a timeout after 600000 milliseconds!***
01:57:38  INFO: getUnixPID() has failed indicating this is not a UNIX System.'Debug on timeout' is currently only supported on Linux.
01:57:38  Output from test:
01:57:38   [OUT] Beginning puzzle.  Solving for 2 disks.
01:57:38   [OUT] Moved disk 0 to 1
01:57:38   [OUT] Moved disk 0 to 2
01:57:38   [OUT] Moved disk 1 to 2
01:57:38   [OUT] Puzzle solved!
01:57:38   [ERR] JVMDUMP039I Processing dump event "vmstop", detail "#0000000000000000" at 2019/03/19 00:47:40 - please wait.
01:57:38   [ERR] JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test-extended.functional-JDK11-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\test_output_15529726932605\cmdLineTester_shrcdbgddrext_1\j9core1.dmp' in response to an event
```
test is hung there and will timeout eventually.
@jdekonin did anything change on the machine recently?

**Comment by pshipton** [comment]
There weren't any OpenJ9/OMR/JCL code changes between the last working and first failing build.

Last working build https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-win_x86-64_cmprssptrs/195
```
00:52:02  Eclipse OpenJ9 VM (build master-f2782748f, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20190316_662 (JIT enabled, AOT enabled)
00:52:02  OpenJ9   - f2782748f
00:52:02  OMR      - 9b73e2bd
00:52:02  JCL      - 3cd1a589af5 based on jdk-11.0.3+2)
```

First failing build
```
00:56:54  Eclipse OpenJ9 VM (build master-f2782748f, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20190317_663 (JIT enabled, AOT enabled)
00:56:54  OpenJ9   - f2782748f
00:56:54  OMR      - 9b73e2bd
00:56:54  JCL      - 3cd1a589af5 based on jdk-11.0.3+2)
```

**Comment by jdekonin** [comment]
Nothing that I am aware of.  I log on to the machine and cpu is currently 0%, completely idle.  I'll reboot and relaunch on this machine and see what happens.

**Comment by AdamBrousseau** [comment]
I wouldn't suspect a machine issue since it happened on 6 then 1. Unless something got applied to all the machines but I don't believe they've changed recently.

**Comment by pshipton** [comment]
@jdekonin note it has occurred on two different machines so far. First win2012r2-x86-6 and then win2012r2-x86-1 last night. Please reboot them both.

**Comment by jdekonin** [comment]
Both machines rebooted and back online taking jobs.

**Comment by pshipton** [comment]
I haven't seen this again.
