### ISSUE TITLE
SetChildEnv.java encounters NPE on OpenJ9 JDK8

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#5138]
Failure link
------------
https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_macos/137/console

Optional info
-------------

- intermittent failure (yes|no): Yes
- regression or new test:  regression
Grinder to determine repro rate: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/1817/

Failure output
--------------

06:40:12  java.lang.NullPointerException
06:40:12  	at SetChildEnv.runwith(SetChildEnv.java:126)
06:40:12  	at SetChildEnv.main(SetChildEnv.java:62)
06:40:12  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:40:12  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:40:12  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:40:12  	at java.lang.reflect.Method.invoke(Method.java:498)
06:40:12  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:40:12  	at java.lang.Thread.run(Thread.java:813)

**Comment by JasonFengJ9** [comment]
@sharon-wang will have a look at this.

**Comment by sharon-wang** [comment]
Unable to reproduce so far.

Ran several 20x grinder tests with parameters:
- **BUILDLIST:** `openjdk_regression`
- **TARGET:** `jdk_custom`
- **CUSTOM_TARGET:** `java/rmi/activation/CommandEnvironment/SetChildEnv.java`
- **JDK_VERSION:** `8`
- **JDK_IMPL:** `openj9`

Will continue looking into this.

**Comment by sharon-wang** [comment]
Still haven't reproduced on a 50x grinder, but here are some findings:

This test is failing on: 
**java/rmi/activation/CommandEnvironment/SetChildEnv.java** - line 126.
```
ActivationSystem actsys = ActivationGroup.getSystem();
ActivationGroupID gid = actsys.registerGroup(gdesc);           // NPE here
```

which is similar to issue https://github.com/eclipse/openj9/issues/5049:
**java/rmi/activation/Activatable/checkActivateRef/CheckActivateRef.java** - line 140.
```
ActivationSystem system = ActivationGroup.getSystem();
ActivationGroupID groupID = system.registerGroup(groupDesc);   // NPE here
```

Looking further into these lines.

**Comment by sharon-wang** [comment]
Not able to reproduce after 50x grinder with original SDK for three different custom targets that have previously failed on NPE.

Based on https://github.com/eclipse/openj9/issues/5049, built SDK artifact using:
```
OpenJ9   - f0820b5ca
OMR      - 5f74eb34
JCL      - 9dc1c4d81c
```

Custom Targets:
- java/rmi/activation/CommandEnvironment/SetChildEnv.java
- java/rmi/activation/Activatable/checkActivateRef/CheckActivateRef.java
- java/rmi/activation/Activatable/createPrivateActivable/CreatePrivateActivatable.java

Artifact: https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Build-JDK8-osx_x86-64_cmprssptrs/181/OpenJ9-JDK8-osx_x86-64_cmprssptrs-20190401-105201.tar.gz

**Comment by JasonFengJ9** [comment]
This probably is a dup of #5049 which is tagged as `comp:jit`.

**Comment by sharon-wang** [comment]
Reproduced NPE with `-Xint` option added to test command and above SDK build:
`java/rmi/activation/Activatable/createPrivateActivable/CreatePrivateActivatable.java`
```
19:02:07  ACTIVATION_LIBRARY: Activation System available after 600 milliseconds
19:02:07  RMID: finished starting rmid.
19:02:07  TEST FAILED: 
19:02:07  Test failed with: null
19:02:07  java.lang.NullPointerException
19:02:07  	at CreatePrivateActivatable.main(CreatePrivateActivatable.java:124)
19:02:07  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:02:07  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:02:07  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:02:07  	at java.lang.reflect.Method.invoke(Method.java:498)
19:02:07  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:02:07  	at java.lang.Thread.run(Thread.java:813)
19:02:07  ACTIVATION_LIBRARY: Activation System available after 0 milliseconds
19:02:07  RMID: getting a reference to the activation system
19:02:07  RMID: obtained a reference to the activation system
19:02:07  RMID: testlibrary finished shutting down rmid
19:02:07  activation daemon shut down
19:02:07  RMID: rmid exited on shutdown request
19:02:07  ACTIVATION_LIBRARY: finished destroying rmid
19:02:07  RMID: removing rmid's old log file...
19:02:07  TestFailedException: TEST FAILED: ; nested exception is: 
19:02:07  	java.lang.NullPointerException
19:02:07  java.lang.NullPointerException
19:02:07  	at CreatePrivateActivatable.main(CreatePrivateActivatable.java:124)
19:02:07  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:02:07  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:02:07  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:02:07  	at java.lang.reflect.Method.invoke(Method.java:498)
19:02:07  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:02:07  	at java.lang.Thread.run(Thread.java:813)
19:02:07  
19:02:07  JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: ; nested exception is: 
19:02:07  	java.lang.NullPointerException
19:02:07  JavaTest Message: shutting down test
```

Saw NPE in two separate 50x grinders.

**Comment by JasonFengJ9** [comment]
The `NULL ActivationSystem` seems from [java/rmi/activation/ActivationGroup.java](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/608e2d56745d1fd31e5e2898b3513bfa46435592/jdk/src/share/classes/java/rmi/activation/ActivationGroup.java#L444-L461)
```
    public static synchronized ActivationSystem getSystem()
        throws ActivationException
    {
        if (currSystem == null) {
            try {
                int port = AccessController.doPrivileged(
                    new GetIntegerAction("java.rmi.activation.port",
                                         ActivationSystem.SYSTEM_PORT));
                currSystem = (ActivationSystem)
                    Naming.lookup("//:" + port +
                         "/java.rmi.activation.ActivationSystem");  --> this probably returns NULL
            } catch (Exception e) {
                throw new ActivationException(
                    "unable to obtain ActivationSystem", e);
            }
        }
        return currSystem;
    }
```
