### ISSUE TITLE
Test-sanity.functional-JDK11-linux_x86-64 jsr335tests_2 testAnonClassCodePaths NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5203]
Occurred in omr acceptance
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/595
jsr335tests_2 
```
FAILED: testAnonClassCodePaths
java.lang.NullPointerException
	at java.base/java.lang.Integer.valueOf(Integer.java:1049)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:194)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

```
    public static Integer valueOf(int i) {
        if (i >= IntegerCache.low && i <= IntegerCache.high)
            return IntegerCache.cache[i + (-IntegerCache.low)]; <- 1049
        return new Integer(i);
    }
```

**Comment by harryyu1994** [comment]
Launching a grinder to determine failure rate

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK12-linux_x86-64/42
```
FAILED: testAnonClassCodePaths
java.lang.NullPointerException
	at java.base/java.lang.Integer.valueOf(Integer.java:1070)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:196)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-linux_x86-64/766
```
FAILED: testAnonClassCodePaths
java.lang.NullPointerException
	at java.lang.Integer.valueOf(Integer.java:831)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:190)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-linux_x86-64/780
```
java.lang.NullPointerException
	at java.lang.Integer.valueOf(Integer.java:831)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:190)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR/2
```
java.lang.NullPointerException
	at java.base/java.lang.Integer.valueOf(Integer.java:1049)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:190)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.functional_x86-64_linux_xl_Nightly/7

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR/59

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OpenJDK11/4

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.functional_x86-64_linux_xl_Nightly/35

**Comment by kobinau** [comment]
@jdekonin

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_xl_OpenJDK/16

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR/95

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR/103

**Comment by JasonFengJ9** [comment]
Happened in an internal test as well.

 [linux_x86-64] SE80_GIT jsr335tests_SE80_4
```
===============================================
Running test jsr335tests_SE80_4 ...
===============================================
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pxa6480sr6-20190531_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190611_419003 (JIT enabled, AOT enabled)
OpenJ9   - 6379367
OMR      - 50b2d23
IBM      - 7f7bec6)
JCL - 20190529_01 based on Oracle jdk8u221-b02
```
```
FAILED: testAnonClassCodePaths
java.lang.NullPointerException
	at java.lang.Integer.valueOf(Integer.java:843)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testIntField(TestUnsafeDefineAnonClass.java:140)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.runBasicClassTests(TestUnsafeDefineAnonClass.java:190)
	at org.openj9.test.jsr335.defineAnonClass.TestUnsafeDefineAnonClass.testAnonClassCodePaths(TestUnsafeDefineAnonClass.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR/128

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR/129

**Comment by kobinau** [comment]
Issue exists within the following line.

```+ (profiled very-hot) org/openj9/test/jsr335/defineAnonClass/TestUnsafeDefineAnonClass.testIntField(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Class;Z)V @ 00007F86B20F1BE8-00007F86B20FD314 OrdinaryMethod 20.20% T Q_SZ=2 Q_SZI=0 QW=230 j9m=00007F884C8EA4B8 bcsz=70 compThread=0 CpuLoad=230%(57%avg) JvmCpu=230%```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/84

**Comment by DanHeidinga** [comment]
Given how close the 0.15.0 release date is and we don't have a fix in hand, moving this to 0.16.0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.functional_x86-64_linux_Release/3

**Comment by DanHeidinga** [comment]
@andrewcraik Any update on this?  It's in the 0.16 milestone which we're trying to close out

**Comment by andrewcraik** [comment]
Have spoken to @kobinau who was looking at this. Seems the issue was occurring only on a subset of machines in the OpenJ9 Jenkins farm. He did investigate it with grinders (per above), but at some point the machine he was using ub16x64j97 died and had to be recreated. When he started running grinders and trying to setup on another machine, the newer nightly did not exhibit the problem. Given all the code changes related to 292 that have landed and the inability to reproduce on newer builds despite ready reproduction on older levels this has most likely been fixed in a newer level.

@pshipton and @DanHeidinga please feel free to re-open if there has been a recent reproduction we've missed.
