### ISSUE TITLE
Issue with creating launcher for agent ub16-ppcle-4

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5251]
The following pipeline in OMR acceptance failed. It wasn't reported to jenkins, and I'm not sure if I can restart it. There is a rerun option in the Blue Ocean view, but not sure if this will allow the build to promote.

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-win_x86-64_cmprssptrs/861
```
19:49:02  Running on ub16-ppcle-4 in /home/jenkins/jenkins-agent/workspace/Pipeline-Build-Test-JDK8-win_x86-64_cmprssptrs
[Pipeline] {
[Pipeline] checkout
19:49:02  No credentials specified
19:49:03  Cloning the remote Git repository
19:49:03  Cloning repository https://github.com/eclipse/openj9.git
19:49:03   > git init /home/jenkins/jenkins-agent/workspace/Pipeline-Build-Test-JDK8-win_x86-64_cmprssptrs # timeout=10
19:49:07  Fetching upstream changes from https://github.com/eclipse/openj9.git
19:49:07   > git --version # timeout=10
19:49:07   > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/heads/*:refs/remotes/origin/*
[Pipeline] cleanWs
19:55:53  ERROR: Issue with creating launcher for agent ub16-ppcle-4. The agent has not been fully initialized yet
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on ub16-ppcle-4 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:950)
	at hudson.FilePath.act(FilePath.java:1068)
	at hudson.FilePath.act(FilePath.java:1057)
	at hudson.FilePath.mkdirs(FilePath.java:1242)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:79)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
Another failure with no jenkins update.
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-JDK11-linux_x86-64_cmprssptrs/detail/Pipeline-Build-Test-JDK11-linux_x86-64_cmprssptrs/710/pipeline

**Comment by DanHeidinga** [comment]
Is this still occurring on Jenkins?  If not, let's close it
