### ISSUE TITLE
Test-sanity.system-JDK12-linux_ppc-64_cmprssptrs_le MauveMultiThreadLoadTest_OpenJ9_0 AccessControlException: access denied

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5288]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK12-linux_ppc-64_cmprssptrs_le/35
```
LT  00:24:29.316 - First failure detected by thread: load-12. Not creating dumps as no dump generation is requested for this load test
LT  00:24:29.316 - Test failed. Details recorded in execution log.
LT  00:24:29.319 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3547
LT    Test details  = 'Mauve[gnu.testlet.javax.imageio.spi.IIORegistry.getDefaultInstance]'
LT    Suite number  = 0
LT    Thread number = 12
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.lang.NoClassDefFoundError: sun.awt.AppContext (initialization failure)
LT  	at java.base/java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:143)
LT  	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:129)
LT  	at gnu.testlet.javax.imageio.spi.IIORegistry.getDefaultInstance.test(getDefaultInstance.java:38)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:825)
LT  Caused by: java.security.AccessControlException: access denied
LT  	at gnu.testlet.java.util.logging.Handler.TestSecurityManager.checkPermission(TestSecurityManager.java:48)
LT  	at java.logging/java.util.logging.LogManager$LoggingProviderAccess.demandLoggerFor(LogManager.java:2707)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.lambda$demandJULLoggerFor$0(LoggingProviderImpl.java:414)
LT  	at sun.util.logging.internal.LoggingProviderImpl$$Lambda$138.00000000C002B370.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:415)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
LT  	at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
LT  	at java.base/jdk.internal.logger.LazyLoggers.lambda$getLoggerFromFinder$0(LazyLoggers.java:392)
LT  	at jdk.internal.logger.LazyLoggers$$Lambda$129.00000000C0029A80.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:391)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
LT  	at java.base/sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:297)
LT  	at java.desktop/sun.awt.AppContext.<clinit>(AppContext.java:141)
LT  	... 11 more
```

**Comment by pshipton** [comment]
I expect this is a dup of https://github.com/eclipse/openj9/issues/4681
@Mesbah-Alam fyi https://github.com/eclipse/openj9/issues/4681#issuecomment-464175715
