### ISSUE TITLE
JTReg test fail - S390x java8 : java/lang/StringBuilder/Supplementary.java 'didn't throw java.lang.IllegalArgumentException'

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#5315]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_s390x_linux/257/testReport/junit/java_lang_StringBuilder_Supplementary/java/Supplementary/

- test category (jtreg jdk_lang): 
- test suite name: java/lang/StringBuilder/Supplementary.java
- OS/architecture (s390x): 
- OpenJDK version (i.e. 8u202-b08): 

```
13:42:56  openjdk version "1.8.0_212"
13:42:56  OpenJDK Runtime Environment (build 1.8.0_212-201904010901-b01)
13:42:56  Eclipse OpenJ9 VM (build master-76146edf6, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190401_274 (JIT enabled, AOT enabled)
13:42:56  OpenJ9   - 76146edf6
13:42:56  OMR      - 5ceecf19
13:42:56  JCL      - 608e2d5674 based on jdk8u212-b01)
```

Optional info
-------------

- intermittent failure (yes|no): yes
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output
--------------

```
Standard Error

java.lang.RuntimeException: Error: appendCodePoint(0xffffffff) didn't throw java.lang.IllegalArgumentException
	at Supplementary.check(Supplementary.java:388)
	at Supplementary.testAppendCodePoint(Supplementary.java:356)
	at Supplementary.test4(Supplementary.java:213)
	at Supplementary.main(Supplementary.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:813)

JavaTest Message: Test threw exception: java.lang.RuntimeException

```
Include the test name

**Comment by pshipton** [comment]
Given that it is intermittent, likely jit related.
@fjeremic

**Comment by fjeremic** [comment]
@r30shah can you help take a look at this one? Could possibly be related to #4640.

**Comment by liqunl** [comment]
#4640 should only apply to VarHandle, which mean java9+.

**Comment by r30shah** [comment]
Seeing 1/100 failure rate when ran grinder locally on this job. Going to continue investigation.

**Comment by fjeremic** [comment]
Just wondering if anyone's seen a reproduction of this. The above noted failure rate of 1/100 makes this lower priority from my perspective and can be migrated to the next milestone.

**Comment by pshipton** [comment]
Moved.

**Comment by pshipton** [comment]
@lumpfish fyi https://github.com/eclipse/openj9/issues/5315#issuecomment-506031521

**Comment by lumpfish** [comment]
The test currently looks to be excluded on s390x from the adoptopenjdk test runs pending the resolution of this issue, so no failures will be being seen at the moment.

In file https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk8-openj9.txt:
```
java/lang/StringBuilder/Supplementary.java https://github.com/eclipse/openj9/issues/5315 linux-s390x
```

**Comment by fjeremic** [comment]
@lumpfish do we need to tag it with `test excluded` label so we don't forget to re-include?

**Comment by lumpfish** [comment]
@fjeremic - yes,  @smlambert - thanks!

**Comment by pshipton** [comment]
Getting late to resolve this in 0.17 so moving forward again.

**Comment by DanHeidinga** [comment]
@fjeremic What's the current status on this?  I'm asking as it would be good to run clean on the `AQA` (AdoptOpenJDK Quality Assurance) tests for the `0.18.0` release

**Comment by fjeremic** [comment]
> +1 to running the grinder on the test to confirm it still occurs.

@r30shah could you please re-run the grinder on this test the same way you did in your previous https://github.com/eclipse/openj9/issues/5315#issuecomment-480326770? A 200-300 job grinder will suffice I would hope. I'm worried the 1/100 failure rate was a red herring as the failure rate could have easily been much lower and we just got lucky with the single failure.

**Comment by sophia-guo** [comment]
Without re-include the test this can be easily verified by running with a grinder with target = jdk_custom and Running a grinder with target jdk_custom and custom_target = jdk/test/java/lang/StringBuilder/Supplementary.java

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/853/console

**Comment by sophia-guo** [comment]
Seeing 1/200 failure rate 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/854/console

**Comment by fjeremic** [comment]
Reassigning this to @r30shah since he's been spearheading the JProfiling issues lately. I would imagine this issue is now fixed with the latest batch of fixes as we are no longer seeing any JProfiling related issues.

**Comment by fjeremic** [comment]
@r30shah can you kick off a grinder similar to above and see if we can reproduce given we have fixed all known JProfiling issues?

**Comment by r30shah** [comment]
@fjeremic  I launched grinder on internal infrastructure to run this job 300 times. I can not reproduce issue there. I will give another go tonight to see if still seen (Given it is highly intermittent)

**Comment by fjeremic** [comment]
400 job Grinder against the original failed job:
https://ci.eclipse.org/openj9/job/Grinder/576/

**Comment by fjeremic** [comment]
Another 600 job grinder for a total of 1000 jobs:
https://ci.eclipse.org/openj9/job/Grinder/577/

There is one failure here so the reproduction rate is 1/1000. It seems the problem is still present however it is quite unreproducible. I'm not sure this is wroth investing resources to fix given the reproduction rate. Will keep the issue open though if reproduction rate changes.

**Comment by pshipton** [comment]
Moving it out of the milestone plan as it seems it won't be fixed in 0.18.

**Comment by pshipton** [comment]
Note the failure is in test marked AQA, the Adopt Quality Assurance test suite, which OpenJ9 should be reliably passing.
