### ISSUE TITLE
Grinder doesn't report failure in TAP output

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5368]
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/367
The first iteration failed, however the TAP output shows 0 failures and only 99 iterations out of the 100 which occurred. `99 tests, 99 ok, 0 not ok, 0 skipped, 0 ToDo, 0 Bail Out!`
```
16:14:09  ===============================================
16:14:09      UnsafeTests
16:14:09      Tests run: 433, Failures: 3, Skips: 0
16:14:09  ===============================================
```

**Comment by pshipton** [comment]
@smlambert @llxia

**Comment by smlambert** [comment]
Appears that the 1 failed run out of the 100 encountered a parse error

<img width="917" alt="Screen Shot 2019-04-04 at 8 08 23 PM" src="https://user-images.githubusercontent.com/2836948/55596245-9b1fe800-5715-11e9-9f5e-753ae60d6600.png">

**Comment by llxia** [comment]
From console output:
```
00:59:52.418  Parsing TAP test result [/home/hudson/genie.openj9/.jenkins/jobs/Test-Grinder/builds/367/tap-master-files/openjdk-tests/TestConfig/test_output_15544088399362/TestTargetResult.tap].
00:59:52.419  org.tap4j.parser.ParserException: Error parsing TAP Stream: Missing TAP Plan.
00:59:52.419  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:230)
00:59:52.419  	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:193)
00:59:52.419  	at org.tap4j.plugin.TapParser.parse(TapParser.java:167)
00:59:52.419  	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:540)
00:59:52.419  	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:412)
00:59:52.419  	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:371)
00:59:52.419  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
00:59:52.419  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
00:59:52.419  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
00:59:52.419  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:59:52.419  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:59:52.419  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:59:52.419  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:59:52.419  	at java.lang.Thread.run(Thread.java:748)
00:59:52.419  Caused by: org.tap4j.parser.ParserException: Missing TAP Plan.
00:59:52.419  	at org.tap4j.parser.Tap13Parser.onFinish(Tap13Parser.java:399)
00:59:52.419  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:227)
00:59:52.419  	... 13 more
```

This is similar to the issue https://issues.jenkins-ci.org/browse/JENKINS-39509
Note: TAP Plugin version is 2.2.2 on OpenJ9 Jenkins

**Comment by smlambert** [comment]
Looking through comp:test issues, as there is no action we are going to take here, I suggest closing this issue.
