### ISSUE TITLE
Test-sanity.system linux_x86-64_cmprssptrs ClassLoadingTest_ConcurrentScavenge_0 NullPointerException or ASSERTION FAILED ** at StandardAccessBarrier.cpp:754

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5389]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/245
```
CLT Test failed:
CLT java.lang.NullPointerException
CLT 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:318)
CLT 	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:93)
CLT 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
CLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
CLT 	at java.base/java.lang.Thread.run(Thread.java:825)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/284
```
CLT 04:06:25.533 - Starting thread. Suite=0 thread=9
CLT 04:06:45.623 - Completed 16.5%. Number of tests started=1483
CLT stderr 07:06:47.237 0x1307600    j9mm.107    *   ** ASSERTION FAILED ** at StandardAccessBarrier.cpp:754: ((false && (_extensions->scavenger->isMutatorThreadInSyncWithCycle(env))))
```

**Comment by pshipton** [comment]
This build
OpenJ9: 946ef67
OMR: a595091
OpenJDK8: 2b68f66 - openj9-openjdk-jdk8
OpenJDK11: f30dc5f - openj9-openjdk-jdk11

Previous jdk8 build
OpenJ9: 2b707c2
OMR: 54908f0
OpenJDK8: ​2b68f66 ​- ​openj9-openjdk-jdk8

Previous jdk11 build
OpenJ9: 9ef06ee
OMR: 54908f0
OpenJDK11: ​61ed321 ​- ​openj9-openjdk-jdk11

https://github.com/eclipse/openj9/compare/

**Comment by pshipton** [comment]
@dmitripivkine @amicic

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/286/
Dump Event "abort" (00020000) received 
3XMTHREADINFO      "Dedicated GC Master" J9VMThread:0x0000000001748200, omrthread_t:0x00007FDCE43157A8, java/lang/Thread:0x00000000E0029C00, state:R, prio=5

**Comment by amicic** [comment]
This is related (based on the assert in the barrier code):  https://github.com/eclipse/openj9/pull/5322

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/290
```
CLT java.lang.NullPointerException
CLT 	at java.io.BufferedReader.readLine(BufferedReader.java:316)
CLT 	at java.io.BufferedReader.readLine(BufferedReader.java:389)
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:93)
CLT 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
CLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
CLT 	at java.lang.reflect.Method.invoke(Method.java:498)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
CLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
CLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
CLT 	at java.lang.Thread.run(Thread.java:813)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_linux_Nightly/2
```
CLT stderr 07:15:13.473 0x1b3e300    j9mm.107    *   ** ASSERTION FAILED ** at StandardAccessBarrier.cpp:857: ((false && (_extensions->scavenger->isMutatorThreadInSyncWithCycle(env))))
```

**Comment by amicic** [comment]
I'm looking into the problem. So far, it indeed seems to be related the mentioned changed, but still trying to understand the root cause (the change itself is probably ok, but it has some side effects).
