### ISSUE TITLE
LargeValueExceptions.java OpenJDK Regression test fails on ppcle with JDK8 on OpenJ9

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#5401]
Failure link
------------

https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_ppc64le_linux/366/console
https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_ppc64le_linux/367/console
https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_ppc64le_linux/368/console

Optional info
-------------

- intermittent failure : No
- regression or new test:  Regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
First Fail:
```
OpenJ9   - 69c95fe61
OMR      - a595091d
JCL      - 2b68f66d68
```

Last Pass
```
OpenJ9   - 2b707c264
OMR      - 54908f03
JCL      - 2b68f66d68
```

2b707c264...69c95fe61
https://github.com/eclipse/openj9-omr/compare/54908f03...a595091d

Failure output
--------------

```
06:08:20  ACTION: testng -- Failed. Unexpected exit from test [exit code: 137]
06:08:20  REASON: User specified action: run testng/othervm -Xmx4g LargeValueExceptions 
06:08:20  TIME:   159.504 seconds
06:08:20  messages:
06:08:20  command: testng -Xmx4g LargeValueExceptions
06:08:20  reason: User specified action: run testng/othervm -Xmx4g LargeValueExceptions 
06:08:20  Mode: othervm [/othervm specified]
06:08:20  elapsed time (seconds): 159.504
06:08:20  configuration:
06:08:20  STDOUT:
06:08:20  [TestNG] Running:
06:08:20    java/math/BigInteger/LargeValueExceptions.java
```

**Comment by adamfarley** [comment]
Fails 100% of the time on adopt's test machines, but does not fail when re-run as a unit test on a different ppcle ubuntu machine.

**Comment by adamfarley** [comment]
Requested access to said machine (test-osuosl-ppc64le-ubuntu-16-04-1) to try and find out why.

**Comment by pshipton** [comment]
@adamfarley there don't seem to be any openj9/omr code changes that would cause this.

**Comment by adamfarley** [comment]
The Hotspot JDK8 regression runs for the nightlies over the same time period run and pass.

Will consult the extensions repo.

**Comment by adamfarley** [comment]
Still unable to reproduce on another ppcle box.

I have noticed that the three failing jobs ran on the same Adopt machine, and that the job that passed last night ran on a different box.

I've run a pair of test runs (one on each machine) to see if this is a pattern.

**Comment by adamfarley** [comment]
Grinder failed. Machine has been re-enabled, and I'm trying new options

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1462/console

**Comment by adamfarley** [comment]
Defect still occurs on the latest build. 

Right now, it looks like a timeout. Running the unit test locally on the relevant machine sees a timeout, and since the error code in the grinder indicates the process was killed (137 - 128 = 9) this seems to line up with the idea of a killed process post-timeout.

Here's a thread trace from the timeout:

"MainThread" Id=20 RUNNABLE
        at java.math.BigInteger.multiplyToLen(BigInteger.java:1684)
        at java.math.BigInteger.multiply(BigInteger.java:1524)
        at java.math.BigInteger.multiply(BigInteger.java:1493)
        at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1725)
        at java.math.BigInteger.multiply(BigInteger.java:1530)
        at java.math.BigInteger.multiply(BigInteger.java:1493)
        at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1721)
        at java.math.BigInteger.multiply(BigInteger.java:1530)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1796)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1796)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1792)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1798)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1796)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1798)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiply(BigInteger.java:1493)
        at LargeValueExceptions.multiplyDefiniteOverflow(LargeValueExceptions.java:151)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:773)
        at org.testng.TestRunner.run(TestRunner.java:623)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
        at org.testng.SuiteRunner.run(SuiteRunner.java:259)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
        at org.testng.TestNG.run(TestNG.java:1018)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:813)
        CPU time: 118124614020 ns
        User time: 118124626544 ns

Also, I ran the test with a hotspot build as well. Same issue.

Upon review, here's a theory:

The test runs and fails on OpenJ9 because it runs *fractionally* slower than on Hotspot. The test is close to overrun in the Hotspot run anyway, it just falls fractionally short. Hotspot, running on the same machine, executes for 2mins and 18 seconds.

The reason the machine is running slow is because there's dozens of java jdi processes not being killed off. So, on balance, this is probably a testcase bug. Will copy it over and close this.

**Comment by adamfarley** [comment]
Addendum: The issue does not occur anymore. Reintroducing the test.
