### ISSUE TITLE
Test-sanity.system PatchModuleImageTest failing

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5462]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/47
aix71-p8-1
PatchModuleImageTest_AppModPatchModule_0
```
STF 11:57:39.074 - +------ Step 9 - Verify if we can patch an Application module using exploded directory
STF 11:57:39.074 - | Run foreground process
STF 11:57:39.074 - |   Program:     /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15549107323942/PatchModuleImageTest_AppModPatchModule_0/20190410-115728-PatchModuleImageTest/tmp/6.XpJVM/bin/java
STF 11:57:39.074 - |   Mnemonic:    OT21
STF 11:57:39.074 - |   Echo:        ECHO_ON
STF 11:57:39.074 - |   Expectation: CLEAN_RUN within 1m
STF 11:57:39.074 - |
STF 11:57:39.075 - Running command: /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15549107323942/PatchModuleImageTest_AppModPatchModule_0/20190410-115728-PatchModuleImageTest/tmp/6.XpJVM/bin/java --add-reads com.test=ALL-UNNAMED --patch-module com.hello=/home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-override/com.hello -Xcompressedrefs -classpath /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar org.junit.runner.JUnitCore net.adoptopenjdk.test.modularity.junit.TestOverrideUsingAppModule
STF 11:57:39.075 - Redirecting stderr to /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15549107323942/PatchModuleImageTest_AppModPatchModule_0/20190410-115728-PatchModuleImageTest/results/9.OT21.stderr
STF 11:57:39.075 - Redirecting stdout to /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15549107323942/PatchModuleImageTest_AppModPatchModule_0/20190410-115728-PatchModuleImageTest/results/9.OT21.stdout
STF 11:57:39.080 - Monitoring processes: OT21
OT21 JUnit version 4.12
OT21 stderr WARNING: module-info.class ignored in patch: /home/u0020236/workspace/Test-sanity.system-JDK12-aix_ppc-64_cmprssptrs/jvmtest/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/common-override/com.hello
OT21 .
OT21 Time: 0.036
OT21 
OT21 OK (1 test)
OT21 
STF 11:58:40.099 - **FAILED** Process OT21 has timed out
STF 11:58:40.099 - Collecting dumps for: OT21
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/1/
win2012r2-x86-6
PatchModuleImageTest_PlatformModPatchModule_0
```
STF 22:50:10.885 - Monitoring processes: OT11
STF 22:50:11.034 - **FAILED** Process OT11 ended with exit code (3221226505) and not the expected exit code/s (0)
STF 22:50:11.034 - Monitoring Report Summary:
STF 22:50:11.034 -   o Process OT11 ended with exit code (3221226505) and not the expected exit code/s (0)
STF 22:50:11.035 - Killing processes: OT11
```
3221226505 == C0000409
no more useful diagnostics

PatchModuleImageTest_UnexportedTypePatchModule_0
```
STF 23:02:44.917 - Monitoring processes: OT3
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549524336062\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-230233-PatchModuleImageTest\tmp\6.XpJVM\bin\j9vm29.dll) error: 7e
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549524336062\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-230233-PatchModuleImageTest\tmp\6.XpJVM\bin\j9hookable29.dll) error: 7e
OT3 stderr jvm.dll failed to load: j9vm29
STF 23:02:45.046 - **FAILED** Process OT3 ended with exit code (3221225477) and not the expected exit code/s (1)
```
3221225477 == C0000005 (access violation)

https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly/1/
win2012r2-x86-3
PatchModuleImageTest_PlatformModPatchModule_0
```
STF 23:02:17.089 - Monitoring processes: OT11
STF 23:02:17.905 - **FAILED** Process OT11 ended with exit code (3221226505) and not the expected exit code/s (0)
```

PatchModuleImageTest_UnexportedTypePatchModule_0
```
STF 23:02:44.917 - Monitoring processes: OT3
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549524336062\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-230233-PatchModuleImageTest\tmp\6.XpJVM\bin\j9vm29.dll) error: 7e
OT3 stderr jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549524336062\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-230233-PatchModuleImageTest\tmp\6.XpJVM\bin\j9hookable29.dll) error: 7e
OT3 stderr jvm.dll failed to load: j9vm29
STF 23:02:45.046 - **FAILED** Process OT3 ended with exit code (3221225477) and not the expected exit code/s (1)
```

First failing AIX build
04:39:03  Eclipse OpenJ9 VM (build master-e9670e438, JRE 12 AIX ppc64-64-Bit Compressed References 20190410_59 (JIT enabled, AOT enabled)
04:39:03  OpenJ9   - e9670e438
04:39:03  OMR      - 25d7b34a
04:39:03  JCL      - 29db1dc28e5 based on jdk-12+33)

Previous build
01:36:24  Eclipse OpenJ9 VM (build master-c32212c83, JRE 12 AIX ppc64-64-Bit Compressed References 20190408_58 (JIT enabled, AOT enabled)
01:36:24  OpenJ9   - c32212c83
01:36:24  OMR      - aeb23f7e
01:36:24  JCL      - 29db1dc28e5 based on jdk-12+33)

c32212c83...e9670e438

First failing Windows build. Previous build is the AIX build.
```
OpenJ9: 8aaaa8c
OMR: 2abc34c
OpenJDK8: cda1580 - openj9-openjdk-jdk8
OpenJDK11: e0bbee7 - openj9-openjdk-jdk11
OpenJDK12: 29db1dc - openj9-openjdk-jdk12
```

e9670e438...8aaaa8c

**Comment by pshipton** [comment]
Results file from the first AIX failure
[systemtest_test_output.tar-1.gz](https://github.com/eclipse/openj9/files/3070057/systemtest_test_output.tar-1.gz)

**Comment by pshipton** [comment]
javacores show it's stuck here
```
3XMTHREADINFO      "Attach API teardown" J9VMThread:0x00000000301C1300, omrthread_t:0x0000000121EA1ED0, java/lang/Thread:0x00000000FFF17EE0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x17, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x1F200BF, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x000000a1)
3XMCPUTIME               CPU usage total: 0.000192000 secs, user: 0.000110000 secs, system: 0.000082000 secs, current category="System-JVM"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4248 (0x1098)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/io/UnixFileSystem.delete0(Native Method)
4XESTACKTRACE                at java/io/UnixFileSystem.delete(UnixFileSystem.java:277)
4XESTACKTRACE                at java/io/File.delete(File.java:1053)
4XESTACKTRACE                at com/ibm/tools/attach/target/TargetDirectory.deleteMyFiles(TargetDirectory.java:135)
4XESTACKTRACE                at com/ibm/tools/attach/target/AttachHandler.terminate(AttachHandler.java:382)
4XESTACKTRACE                at com/ibm/tools/attach/target/AttachHandler$teardownHook.run(AttachHandler.java:516)
```

**Comment by pshipton** [comment]
The first Windows failures doesn't have any useful diagnostics.
The second has the following in OT3.stderr
```
jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549517134080\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-225026-PatchModuleImageTest\tmp\6.XpJVM\bin\j9vm29.dll) error: 7e
jvm.dll preloadLibrary: LoadLibrary(C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly\openjdk-tests\TestConfig\test_output_15549517134080\PatchModuleImageTest_UnexportedTypePatchModule_0\20190410-225026-PatchModuleImageTest\tmp\6.XpJVM\bin\j9hookable29.dll) error: 7e
jvm.dll failed to load: j9vm29
```

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by pshipton** [comment]
@Mesbah-Alam I wonder if the paths are too long on Windows. They got slightly longer when we added "_Nightly" to the end of the test job name.

**Comment by pshipton** [comment]
We has a similar problem with https://github.com/eclipse/openj9/issues/5448

**Comment by pshipton** [comment]
SharedClasses_Softmx_UpDown_0 is also failing on Windows, which I suspect is also path length related.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly/2
```
Can't open
	C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly/openjdk-tests/\TestConfig\test_output_15550436158275\SharedClasses_Softmx_UpDown_0/20190411-234600-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/generation/generation.stdout: No such file or directory (#1)
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/2

**Comment by Mesbah-Alam** [comment]
Did anything change to cause path names to suddenly become longer than what they used to ?

**Comment by smlambert** [comment]
Yes, the name of the Jenkins job is now longer (additional suffix _Nightly), therefore the full path name of the workspace directory in which everything is run is longer...

**Comment by Mesbah-Alam** [comment]
That explains it. I suspect all the Windows errors reported above are related to some paths exceeding max length on WIndows. https://github.com/AdoptOpenJDK/openjdk-tests/pull/1070 shortens the names of the tests in the playlist, which should fix this.

**Comment by Mesbah-Alam** [comment]
The failure in AIX is more interesting. 

Last change made to this test was 5 months ago-- so, nothing recent. The sub-process that "times out" is a custom runtime image on which some patch testing is done. 

The timeout set in these sub-processes is quite short however (may be not long enough for AIX?). I've increased them from `1m` to `5m` and ran a 4x grinder in internal Jenkins, and the tests are passing.

**Comment by pshipton** [comment]
We'll assume this is resolved and close it. Can reopen later or open a new issue if there is still a problem.

**Comment by pshipton** [comment]
Started a system test build on Windows to confirm. Since this is a "Personal" build instead of a "Nightly" build, the directory names will be even slightly longer.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/477/

**Comment by pshipton** [comment]
The build was terminated by a jenkins restart. We'll see how the nightly build behaves.

**Comment by pshipton** [comment]
@Mesbah-Alam the PatchModuleImageTests are still failing on Windows
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/3
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly/3/

**Comment by Mesbah-Alam** [comment]
PatchModuleImageTests failures are likely due to path being too long on windows as well. I'll have a PR for this.
