### ISSUE TITLE
Test_openjdk8_j9_extended.functional_x86-64_linux_xl testDDRExt_JITExt_openj9_0 CorruptDataException thrown walking stack NullPointerDereference

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5489]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/4/
```
     [java] [SetupConfig] [INFO] Created new DDR Interactive instance using core file : /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15551264766284/testDDRExt_JITExt_openj9_0/DDREXT.J9CORE.DMP
     [java] [AutoRun] [INFO] Running 1 tests for /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15551264766284/testDDRExt_JITExt_openj9_0/DDREXT.J9CORE.DMP
     [java] [AutoRun] [INFO] Starting testJITStack(j9vm.test.ddrext.junit.TestJITExt)
     [java] Apr 13, 2019 1:45:07 AM com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
     [java] WARNING: CorruptDataException thrown walking stack. walkThread = 0x00007F070C0A4C00
     [java] com.ibm.j9ddr.NullPointerDereference: Memory Fault reading 0x00000000 : 
     [java] 	at com.ibm.j9ddr.vm29.pointer.AbstractPointer.getPointerAtOffset(AbstractPointer.java:383)
     [java] 	at com.ibm.j9ddr.vm29.pointer.generated.J9ConstantPoolPointer.ramClass(J9ConstantPoolPointer.java:157)
     [java] 	at com.ibm.j9ddr.vm29.j9.ROMHelp$ROMHelp_29_V0.J9_CLASS_FROM_METHOD(ROMHelp.java:591)
     [java] 	at com.ibm.j9ddr.vm29.j9.ROMHelp$ROMHelp_29_V0.getOriginalROMMethod(ROMHelp.java:249)
     [java] 	at com.ibm.j9ddr.vm29.j9.ROMHelp.getOriginalROMMethod(ROMHelp.java:139)
     [java] 	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkBytecodeFrame(StackWalker.java:969)
     [java] 	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:449)
     [java] 	at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:103)
     [java] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.JitstackCommand.run(JitstackCommand.java:118)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:182)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:390)
     [java] 	at j9vm.test.ddrext.DDRExtTesterBase.exec(DDRExtTesterBase.java:101)
     [java] 	at j9vm.test.ddrext.junit.TestJITExt.testJITStack(TestJITExt.java:90)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
```

**Comment by pshipton** [comment]
Similar to https://github.com/eclipse/openj9/issues/5449
Not sure if it's the same issue.
@theresa-m

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/17

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/44

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/50

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/53
