### ISSUE TITLE
ub16x64j93 needs a poke

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5509]
https://ci.eclipse.org/openj9/computer/ub16x64j93/log
```
[04/16/19 06:52:59] Launching agent
$ ssh -C -i /opt/public/hipp/homes/genie.openj9/.ssh/id_rsa.openj9 jenkins@140.211.168.230 "ssh -i ~/.ssh/id_rsa.aix jenkins@192.168.10.155 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; java -jar slave.jar'"
ssh: connect to host 192.168.10.155 port 22: Connection timed out
Killed by signal 1.
ERROR: Unable to launch the agent for ub16x64j93
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:431)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
This machine no longer seems to exist.
