### ISSUE TITLE
java.lang.OutOfMemoryError: native memory exhausted

### ISSUE THREAD

**Issue by kthaya** [eclipse/openj9#5526]
I could run an application that includes derby database in hotspot without any issue, but it fails in openj9 with following error, we have -XX:MaxMetaspaceSize=1024m and -XX:MetaspaceSize=256m. Does these options support by openj9? 

_java.lang.OutOfMemoryError: native memory exhausted
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:379)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:638)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:613)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:574)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:492)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:465)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:862)_

Thanks in advance

**Comment by DanHeidinga** [comment]
> we have -XX:MaxMetaspaceSize=1024m and -XX:MetaspaceSize=256m. 

OpenJ9 doesn't have MetaSpace so those options are ignored.  

When the NativeOOM is triggered, a system core & javacore should be generated.  Are you able to share those files?  It'll help us to understand where the memory is being used.

**Comment by kthaya** [comment]
Thank you, .dmp and .phd file size is huge even after zip.

**Comment by pshipton** [comment]
I assume this is Java 8? The OpenJ9 heap size default for Java 8 is -Xmx512m, while for Hotspot it is based on your physical RAM. Try a bigger heap size value like `-Xmx1g` or base it on physical RAM like `-XX:MaxRAMPercentage=25`.

**Comment by kthaya** [comment]
yes, It is Java 8 (Adopt OpenJDK), I have explicitly set the values already (-Xms512m, -Xmx2048m). VM memory 4G. 
I wonder why is it failing when start derby? Is derby consume more native memory?

**Comment by kthaya** [comment]
forgot to mention, it fails in AIX (power 8) environment only. Windows and Mac looks good

**Comment by pshipton** [comment]
Ah, native memory, somehow I missed that. Try setting a bigger -Xmcrs such as `-Xmcrs400m`.

The NATIVEMEMINFO section of the javacore might be helpful, if you could attach that, or the entire javacore zipped.

**Comment by DanHeidinga** [comment]
@kthaya did @pshipton's suggestion to increase the `-Xmcrs` using the option `-Xmcrs400m` work?  Are you able to share the javacore from the OOM?

**Comment by DanHeidinga** [comment]
Closing as this has been dormant for a while
