### ISSUE TITLE
win2012r2-x86-1 Unable to create shared memory of size 314572800 bytes

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5535]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.system_x86-64_windows_Nightly/7/
```
SCC stderr JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested 
SCC stderr  	Adjusted to maximum shared memory permitted (67108864 bytes) 
SCC stderr  	(To increase available shared memory, modify system SHMMAX value) 
SCC stderr  	 If -Xscdmx is used, the debug attribute area is adjusted in proportion 
SCC stderr  	 according to its original ratio to the -Xscmx value.
SCC stderr JVMSHRC241E Error: unable to delete shared class cache file
SCC stderr JVMSHRC336E Port layer error code = -100
SCC stderr JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
SCC stderr JVMSHRC430I Failed to remove current generation of shared class cache "SCC_SysTest_Workload_Cache"
```

4.jvm1.stdout
5.jvm2.stdout
```
>>> Captured test output >>>
testStarted : testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
testFailure: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest): Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
junit.framework.AssertionFailedError: Unable to match all memory FileSystems in the list of available providers expected:<1000> but was:<0>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:401)
	at net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest.testAllFileSystemsAreRegistered(FileSystemsTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:825)
testFinished: testAllFileSystemsAreRegistered(net.adoptopenjdk.test.nio2.filesystem.FileSystemsTest)
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau seems like a machine issue

**Comment by jdekonin** [comment]
Being that the machine successfully completes job, both compile and test, it would be more accurate to say that something left the machine in a bad state.

Seems to be performing fine (for 5 days of jobs) after a reboot.
https://ci.eclipse.org/openj9/view/Infrastructure/job/Node-Build-History/2/console
