### ISSUE TITLE
Test_openjdk8_j9_extended.functional_x86-32_windows TestJps_SE80_0 testJpsIdOnly

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5569]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/9
```
01:44:10  FAILED: testJpsIdOnly
01:44:10  java.lang.AssertionError: Spurious output:  expected:<32> but was:<14732>
01:44:10  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
01:44:10  	at org.openj9.test.attachAPI.TestJps.testJpsIdOnly(TestJps.java:86)
01:44:10  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:44:10  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:44:10  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:44:10  	at java.lang.reflect.Method.invoke(Method.java:498)
01:44:10  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:44:10  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:44:10  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:44:10  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:44:10  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:44:10  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:44:10  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:44:10  	at org.testng.TestRunner.run(TestRunner.java:505)
01:44:10  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:44:10  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:44:10  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:44:10  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:44:10  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:44:10  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:44:10  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:44:10  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:44:10  	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:44:10  	at org.testng.TestNG.run(TestNG.java:1017)
01:44:10  	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:44:10  	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@pdbain-ibm

**Comment by pdbain-ibm** [comment]
Thanks.  Will investigate.

**Comment by pdbain-ibm** [comment]
Found the problem: `search()` does a substring search and matched `14732` which occurred earlier than the desired needle.  I will have a solution shortly.
