### ISSUE TITLE
Different result presented by Instrumentation.retransformClasses

### ISSUE THREAD

**Issue by NekoCaffeine** [eclipse/openj9#5571]
OpenJ9 does not support removing the native modifier.

got an exception:
`java.lang.UnsupportedOperationException: class redefinition failed: attempted to change method modifiers`

This works fine on OpenJDK.

**Comment by DanHeidinga** [comment]
@NekoCaffeine Do you have a minimal test case that you can share demonstrating the behaviour difference?

**Comment by gacholio** [comment]
The specification explicitly disallows this:

```The redefinition may change method bodies, the constant pool and attributes. The redefinition must not add, remove or rename fields or methods, change the signatures of methods, change modifiers, or change inheritance. ```

**Comment by gacholio** [comment]
Having said that, there's no technical reason OpenJ9 could not support this

**Comment by NekoCaffeine** [comment]
src/main/java/test/TestRemoveNative.java
```
package test;

import java.lang.instrument.ClassDefinition;
import java.lang.instrument.Instrumentation;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.MethodNode;

import static org.objectweb.asm.Opcodes.*;

public class TestRemoveNative {
    
    public static void premain(String agentArgs, Instrumentation instrumentation) throws Throwable {
        final ClassReader reader = new ClassReader(TestRemoveNative.class.getName());
        final ClassNode node = new ClassNode();
        reader.accept(node, 0);
        for (MethodNode methodNode : node.methods)
            if (methodNode.name.equals("foo")) {
                methodNode.access = ACC_STATIC;
                methodNode.instructions.add(new InsnNode(ICONST_3));
                methodNode.instructions.add(new InsnNode(IRETURN));
            }
        final ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        node.accept(writer);
        instrumentation.redefineClasses(new ClassDefinition(TestRemoveNative.class, writer.toByteArray()));
        System.out.println(foo()); // got 3
        System.exit(0);
    }
    
    static native int foo();
    
}
```
build.gradle
```
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '4.0.2'
}

group 'test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.ow2.asm:asm:7.1'
    compile 'org.ow2.asm:asm-tree:7.1'
    compile 'org.ow2.asm:asm-commons:7.1'
    compile 'org.ow2.asm:asm-util:7.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

jar {
    archivesBaseName = "test"

    manifest {
        attributes 'Premain-Class': 'test.TestRemoveNative'
        attributes 'Can-Redefine-Classes': 'true'
        attributes 'Can-Retransform-Classes': 'true'
    }
    finalizedBy shadowJar
}

shadowJar {
    classifier = "shadow"
}
```

**Comment by NekoCaffeine** [comment]
OpenJDK
```
"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -javaagent:test-1.0-SNAPSHOT-shadow.jar
Picked up JAVA_TOOL_OPTIONS: -Dsun.jnu.encoding=utf-8
3
```
OpenJ9
```
"D:\OpenJDK8U-jdk_x64_windows_openj9_8u212b03_openj9-0.14.0\jdk8u212-b03\bin\java.exe" -javaagent:test-1.0-SNAPSHOT-shadow.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:416)
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change method modifiers
        at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:182)
        at test.TestRemoveNative.premain(TestRemoveNative.java:28)
        ... 6 more

Fatal error: processing of -javaagent failed
```

**Comment by NekoCaffeine** [comment]
My framework encountered this problem when trying to roll back an unsupported native method.

**Comment by NekoCaffeine** [comment]
Ok, I can only give up OpenJ9 for the time being.

**Comment by pshipton** [comment]
We can keep it in the backlog.
