### ISSUE TITLE
Windows PR build failures: Unable to delete workspace

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#5600]
Some Windows PR builds have been failing lately (I've observed the past 1.5 weeks) with an error similar to:
```
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:86)
	at hudson.Util.deleteContentsRecursive(Util.java:260)
	at hudson.Util.deleteContentsRecursive(Util.java:249)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:596)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:813)
```
For example, here is a failure from a PR build today:   https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/652/console

**Comment by AdamBrousseau** [comment]
```
jenkins@oj9-win2012r2-2 /cygdrive/c/Users/jenkins/workspace
$ du -shc *
21M	Build_JDK8_x86-64_windows_Nightly
0	Build_JDK8_x86-64_windows_Nightly@tmp
64K	Build_JDK8_x86-64_windows_Nightly_ws-cleanup_1555554108088
64K	Build_JDK8_x86-64_windows_Nightly_ws-cleanup_1555640630282
56K	Build_JDK8_x86-64_windows_Nightly_ws-cleanup_1555899641175
64K	Build_JDK8_x86-64_windows_Nightly_ws-cleanup_1555986140601
64K	Build_JDK8_x86-64_windows_Nightly_ws-cleanup_1556072501912
8.0K	Build_JDKnext_x86-64_windows_Nightly
0	Build_JDKnext_x86-64_windows_Nightly@tmp
0	Cleanup-Nodes
0	Cleanup-Nodes@tmp
21M	PullRequest-Compile-JDK8-win_x86-64_cmprssptrs-OpenJ9
0	PullRequest-Compile-JDK8-win_x86-64_cmprssptrs-OpenJ9@tmp
56K	PullRequest-Compile-JDK8-win_x86-64_cmprssptrs-OpenJ9_ws-cleanup_1555442769976
56K	PullRequest-Compile-JDK8-win_x86-64_cmprssptrs-OpenJ9_ws-cleanup_1556055880525
64K	PullRequest-Compile-JDK8-win_x86-64_cmprssptrs-OpenJ9_ws-cleanup_1556129609170
64K	PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9
0	PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9@tmp
0	Sanitize-Nodes
0	Sanitize-Nodes@tmp
0	Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly@tmp
0	Test_openjdk11_j9_extended.functional_x86-64_windows_Release@tmp
0	Test_openjdk11_j9_extended.system_x86-64_windows_Nightly@tmp
0	Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly@tmp
0	Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly@tmp
0	Test_openjdk12_j9_extended.functional_x86-64_windows_Release@tmp
0	Test_openjdk12_j9_sanity.system_x86-64_windows_Nightly@tmp
84M	Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly
0	Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly@tmp
0	Test_openjdk8_j9_extended.functional_x86-32_windows_Release@tmp
0	Test_openjdk8_j9_extended.functional_x86-64_windows_Nightly@tmp
0	Test_openjdk8_j9_extended.system_x86-32_windows_Nightly@tmp
0	Test_openjdk8_j9_extended.system_x86-64_windows_Nightly@tmp
0	Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly@tmp
0	Test_openjdk8_j9_sanity.functional_x86-64_windows_OMR@tmp
0	Test_openjdk8_j9_sanity.system_x86-64_windows_Nightly@tmp
0	Test-Grinder@tmp
0	Test-Grinder_Sandbox@tmp
0	Update-Reference-Repos
0	Update-Reference-Repos@tmp
126M	total
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/12/console
```
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
ERROR: Cannot delete workspace :Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/647/console
```
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
Cannot delete workspace: null
Option not to fail the build is turned on, so let's continue
```
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/652/console
```
Running on win2012r2-x86-2 in C:\Users\jenkins\workspace\PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9
[Pipeline] {
[Pipeline] checkout
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/eclipse/openj9.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

Clearly there's an issue with windows cleanup. Should revisit the cleanWs on Win and look for open issues/solutions.
Also, the cleanup job should be catching these so obviously something wring there too (@vsebe cc @jdekonin )
https://ci.eclipse.org/openj9/job/Cleanup-Nodes/1211/
![image](https://user-images.githubusercontent.com/6430052/56687051-6ca58500-66a3-11e9-9120-9c6f9f9581ce.png)
