### ISSUE TITLE
Determine how to restore "Enhance the handling of indexOf in ValuePropagation #5444"

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#5727]
The original PR: 
> Enhance the handling of indexOf in ValuePropagation #5444

was reverted in this PR:
> Revert "Enhance the handling of indexOf in ValuePropagation" #5723

We need to determine if / how this should be restored.

**Comment by andrewcraik** [comment]
This does need to be restored at some point - it is a perf enhancement. I'm trying to figure out what went wrong because this went through a lot of testing (albeit on x86) before it went in. I did do builds on the other platforms, but given the intermittent nature of the failure perhaps it just didn't create for me. Current suspect is either a bug in the propagation logic or some kind of endian-ness issue.

**Comment by andrewcraik** [comment]
So looking at https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly/29/tapResults/ there is a failure of the form:
```LT  java.net.URISyntaxException: Illegal character in query at index 37: http://jones@example.com:98?name=Fred#1
LT  	at java.net.URI$Parser.fail(URI.java:2848)
LT  	at java.net.URI$Parser.checkChars(URI.java:3021)
LT  	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
LT  	at java.net.URI$Parser.parse(URI.java:3053)
LT  	at java.net.URI.<init>(URI.java:588)
LT  	at gnu.testlet.java.net.URI.ComparisonTest.test(ComparisonTest.java:48)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:813)
LT  FAIL: gnu.testlet.java.net.URI.ComparisonTest: Unexpected exception (number 0)
```

I took that test string and fed it into a BumbleBench. On x86 the BumbleBench runs fine - the string parses and we get good performance. I then tried the same string on zLinux and we get the exception shown above.

The change I made uses the `icmpeq` node which is not super common and it uses it under an `isub` as follows:
```
isub
  icmpeq
    <node>
    iconst #
  iconst #
```
This is not a common pattern. The expectation is that icmpeq will generate a 0 / 1 result and the sub will change it to -1 / 0. This works fine on x Linux so there maybe a codegen bug here. Still digging but one possible suspect tree evaluation:
```------------------------------
 n9133n   (  0)  iRegStore GPR6                                                                       [     0x3ff63521680] bci=[84,81,2053] rc=0 vc=6051 vn=- li=638 udi=- nc=1
 n10510n  (  1)    iadd (in GPR_1136) (X<=0 cannotOverflow )                                          [     0x3ff6373c4e0] bci=[84,81,2053] rc=1 vc=6051 vn=- li=638 udi=- nc=2 flg=0x1200
 n10508n  (  0)      icmpeq (in GPR_1136)                                                             [     0x3ff6373c440] bci=[84,81,2053] rc=0 vc=6051 vn=- li=638 udi=- nc=2
 n12718n  (  0)        ==>iRegLoad (in GPR_1125) (X>=0 cannotOverflow SeenRealReference )
 n10507n  (  0)        iconst 0 (X==0 X>=0 X<=0 )                                                     [     0x3ff6373c3f0] bci=[84,81,2053] rc=0 vc=6051 vn=- li=638 udi=- nc=0 flg=0x302
 n10509n  (  0)      iconst -1 (X!=0 X<=0 )                                                           [     0x3ff6373c490] bci=[84,81,2053] rc=0 vc=6051 vn=- li=638 udi=- nc=0 flg=0x204
------------------------------

 [     0x3ff898fc710]   LHI     GPR_1136,0x1
 [     0x3ff898fc920]   Label L0304:    # (Start of internal control flow)
 [     0x3ff898fc810]   CIJ     GPR_1125,Label L0305,0,BH(mask=0x8),
 [     0x3ff898fca20]   XR      GPR_1136,GPR_1136
 [     0x3ff898fd0e0]   ASSOCREGS
 [     0x3ff898fcb10]   Label L0305:    # (End of internal control flow)
 POST:
 {AssignAny:GPR_1125:R} {AssignAny:GPR_1136:R}
 [     0x3ff898fd1c0]   AHI     GPR_1136,0xffff```

**Comment by andrewcraik** [comment]
I'm told the above seems reasonable for z so I'm going to check the rest of the VP transforms to see if there is anything suspect there...

**Comment by fjeremic** [comment]
The above instruction sequence for the trees looks correct to me.
