### ISSUE TITLE
IntelliJ Idea java.lang.OutOfMemoryError at startup

### ISSUE THREAD

**Issue by fvasco** [eclipse/openj9#5739]
Java -version output
--------------------

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.1, JRE 12 Linux amd64-64-Bit Compressed References 20190418_66 (JIT enabled, AOT enabled)
OpenJ9   - 412258978
OMR      - 4a4278e6
JCL      - 9fad1c64af based on jdk-12.0.1+12)

Summary of problem
------------------

Installed AdoptOpenJDK 12-openj9, run IntelliJ Idea 2019.1.2 CE (without JBR).
OutOfMemoryError at startup

Diagnostic files
----------------

~~~
<?xml version="1.0" ?>

<verbosegc xmlns="http://www.ibm.com/j9/verbosegc" version="4a4278e6_CMPRSS">

<initialized id="1" timestamp="2019-05-11T19:16:10.394">
  <attribute name="gcPolicy" value="-Xgcpolicy:gencon" />
  <attribute name="maxHeapSize" value="0x2ee00000" />
  <attribute name="initialHeapSize" value="0x8000000" />
  <attribute name="compressedRefs" value="true" />
  <attribute name="compressedRefsDisplacement" value="0x0" />
  <attribute name="compressedRefsShift" value="0x0" />
  <attribute name="pageSize" value="0x1000" />
  <attribute name="pageType" value="not used" />
  <attribute name="requestedPageSize" value="0x1000" />
  <attribute name="requestedPageType" value="not used" />
  <attribute name="gcthreads" value="2" />
  <attribute name="gcthreads Concurrent Mark" value="1" />
  <attribute name="packetListSplit" value="2" />
  <attribute name="cacheListSplit" value="2" />
  <attribute name="splitFreeListSplitAmount" value="1" />
  <attribute name="numaNodes" value="0" />
  <system>
    <attribute name="physicalMemory" value="12059566080" />
    <attribute name="numCPUs" value="2" />
    <attribute name="architecture" value="amd64" />
    <attribute name="os" value="Linux" />
    <attribute name="osVersion" value="4.15.0-48-generic" />
  </system>
  <vmargs>
    <vmarg name="-Xoptionsfile=/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib/options.default" />
    <vmarg name="-Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword..." />
    <vmarg name="-Xjcl:jclse29" />
    <vmarg name="-Dcom.ibm.oti.vm.bootstrap.library.path=/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib/compressedrefs:/usr/lib/jvm/adoptopenjdk-12..." />
    <vmarg name="-Dsun.boot.library.path=/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib/compressedrefs:/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib" />
    <vmarg name="-Djava.library.path=/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib/compressedrefs:/usr/lib/jvm/adoptopenjdk-12-jdk-openj9/lib:/usr..." />
    <vmarg name="-Djava.home=/usr/lib/jvm/adoptopenjdk-12-jdk-openj9" />
    <vmarg name="-Duser.dir=/var/tmp/idea/bin" />
    <vmarg name="-Djava.class.path=/var/tmp/idea/lib/bootstrap.jar:/var/tmp/idea/lib/extensions.jar:/var/tmp/idea/lib/util.jar:/var/tmp/idea/lib..." />
    <vmarg name="-Xms128m" />
    <vmarg name="-Xmx750m" />
    <vmarg name="-XX:ReservedCodeCacheSize=240m" />
    <vmarg name="-XX:+UseConcMarkSweepGC" />
    <vmarg name="-XX:SoftRefLRUPolicyMSPerMB=50" />
    <vmarg name="-ea" />
    <vmarg name="-Dsun.io.useCanonCaches=false" />
    <vmarg name="-Djava.net.preferIPv4Stack=true" />
    <vmarg name="-Djdk.http.auth.tunneling.disabledSchemes=&quot;&quot;" />
    <vmarg name="-XX:+HeapDumpOnOutOfMemoryError" />
    <vmarg name="-XX:-OmitStackTraceInFastThrow" />
    <vmarg name="-Dawt.useSystemAAFontSettings=lcd" />
    <vmarg name="-Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine" />
    <vmarg name="-verbose:gc" />
    <vmarg name="-XX:ErrorFile=/home/francesco/java_error_in_IDEA_%p.log" />
    <vmarg name="-XX:HeapDumpPath=/home/francesco/java_error_in_IDEA.hprof" />
    <vmarg name="-Didea.paths.selector=IdeaIC2019.1" />
    <vmarg name="-Djb.vmOptionsFile=/var/tmp/idea/bin/idea64.vmoptions" />
    <vmarg name="-Didea.platform.prefix=Idea" />
    <vmarg name="-Didea.jre.check=true" />
    <vmarg name="-Dsun.java.command=com.intellij.idea.Main" />
    <vmarg name="-Dsun.java.launcher=SUN_STANDARD" />
    <vmarg name="-Dsun.java.launcher.pid=10443" />
  </vmargs>
</initialized>

<exclusive-start id="2" timestamp="2019-05-11T19:16:11.121" intervalms="727.350">
  <response-info timems="0.039" idlems="0.039" threads="0" lastid="0000000001283E00" lastname="main" />
</exclusive-start>
<af-start id="3" threadId="0000000001284788" totalBytesRequested="2147483656" timestamp="2019-05-11T19:16:11.121" intervalms="727.578" type="nursery" />
<cycle-start id="4" type="scavenge" contextid="0" timestamp="2019-05-11T19:16:11.122" intervalms="727.672" />
<gc-start id="5" type="scavenge" contextid="4" timestamp="2019-05-11T19:16:11.122">
  <mem-info id="6" free="111005952" total="134217728" percent="82">
    <mem type="nursery" free="10706232" total="33554432" percent="31">
      <mem type="allocate" free="10706232" total="16777216" percent="63" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="100299720" total="100663296" percent="99">
      <mem type="soa" free="95266760" total="95630336" percent="99" />
      <mem type="loa" free="5032960" total="5032960" percent="100" />
    </mem>
    <remembered-set count="4944" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="6430544" >
  <allocated-bytes non-tlh="1031936" tlh="5398608" />
  <largest-consumer threadName="main" threadId="0000000001283E00" bytes="6334840" />
</allocation-stats>
<gc-op id="7" type="scavenge" timems="4.350" contextid="4" timestamp="2019-05-11T19:16:11.126">
  <scavenger-info tenureage="2" tenuremask="fffc" tiltratio="50" />
  <memory-copied type="nursery" objects="20279" bytes="1315768" bytesdiscarded="185736" />
  <finalization candidates="80" enqueued="0" />
  <ownableSynchronizers candidates="2" cleared="0" />
  <references type="soft" candidates="289" cleared="0" enqueued="0" dynamicThreshold="32" maxThreshold="32" />
  <references type="weak" candidates="1633" cleared="806" enqueued="666" />
  <references type="phantom" candidates="27" cleared="1" enqueued="1" />
</gc-op>
<gc-end id="8" type="scavenge" contextid="4" durationms="4.868" usertimems="8.258" systemtimems="0.012" timestamp="2019-05-11T19:16:11.127" activeThreads="2">
  <mem-info id="9" free="115572552" total="134217728" percent="86">
    <mem type="nursery" free="15272832" total="33554432" percent="45">
      <mem type="allocate" free="15272832" total="16777216" percent="91" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="100299720" total="100663296" percent="99">
      <mem type="soa" free="95266760" total="95630336" percent="99" />
      <mem type="loa" free="5032960" total="5032960" percent="100" />
    </mem>
    <pending-finalizers system="0" default="0" reference="667" classloader="0" />
    <remembered-set count="4944" />
  </mem-info>
</gc-end>
<cycle-end id="10" type="scavenge" contextid="4" timestamp="2019-05-11T19:16:11.127" />
<cycle-start id="11" type="global" contextid="0" timestamp="2019-05-11T19:16:11.127" intervalms="733.410" />
<gc-start id="12" type="global" contextid="11" timestamp="2019-05-11T19:16:11.127">
  <mem-info id="13" free="115572552" total="134217728" percent="86">
    <mem type="nursery" free="15272832" total="33554432" percent="45">
      <mem type="allocate" free="15272832" total="16777216" percent="91" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="100299720" total="100663296" percent="99">
      <mem type="soa" free="95266760" total="95630336" percent="99" />
      <mem type="loa" free="5032960" total="5032960" percent="100" />
    </mem>
    <pending-finalizers system="0" default="0" reference="667" classloader="0" />
    <remembered-set count="4944" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="0" >
  <allocated-bytes non-tlh="0" tlh="0" />
</allocation-stats>
<heap-resize id="14" type="loa expand" space="tenure" amount="1006592" count="1" timems="0.000" reason="expand on failed allocate" timestamp="2019-05-11T19:16:11.128" />
<gc-op id="15" type="mark" timems="3.530" contextid="11" timestamp="2019-05-11T19:16:11.131">
  <trace-info objectcount="28110" scancount="23114" scanbytes="768008" />
  <finalization candidates="80" enqueued="0" />
  <ownableSynchronizers candidates="2" cleared="0" />
  <references type="soft" candidates="289" cleared="0" enqueued="0" dynamicThreshold="32" maxThreshold="32" />
  <references type="weak" candidates="827" cleared="52" enqueued="26" />
  <references type="phantom" candidates="26" cleared="0" enqueued="0" />
  <stringconstants candidates="3018" cleared="0"  />
</gc-op>
<gc-op id="16" type="classunload" timems="0.013" contextid="11" timestamp="2019-05-11T19:16:11.131">
  <classunload-info classloadercandidates="8" classloadersunloaded="0" classesunloaded="0" anonymousclassesunloaded="0" quiescems="0.000" setupms="0.011" scanms="0.001" postms="0.001" />
</gc-op>
<gc-op id="17" type="sweep" timems="0.547" contextid="11" timestamp="2019-05-11T19:16:11.132" />
<mem-info id="18" free="115758168" total="134217728" percent="86">
  <mem type="nursery" free="15458448" total="33554432" percent="46">
    <mem type="allocate" free="15458448" total="16777216" percent="92" />
    <mem type="survivor" free="0" total="16777216" percent="0" />
  </mem>
  <mem type="tenure" free="100299720" total="100663296" percent="99" micro-fragmented="2581" macro-fragmented="0">
    <mem type="soa" free="94260168" total="94623744" percent="99" />
    <mem type="loa" free="6039552" total="6039552" percent="100" />
  </mem>
  <pending-finalizers system="0" default="0" reference="693" classloader="0" />
  <remembered-set count="4897" />
</mem-info>
<gc-op id="19" type="compact" timems="22.209" contextid="11" timestamp="2019-05-11T19:16:11.155">
  <compact-info movecount="22710" movebytes="1453856" reason="compact to meet allocation" />
</gc-op>
<heap-resize id="20" type="expand" space="tenure" amount="652214272" count="1" timems="0.067" reason="satisfy allocation request" timestamp="2019-05-11T19:16:11.155" />
<gc-end id="21" type="global" contextid="11" durationms="27.446" usertimems="19.312" systemtimems="2.476" timestamp="2019-05-11T19:16:11.155" activeThreads="2">
  <mem-info id="22" free="767978984" total="786432000" percent="97">
    <mem type="nursery" free="15462592" total="33554432" percent="46">
      <mem type="allocate" free="15462592" total="16777216" percent="92" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="752516392" total="752877568" percent="99">
      <mem type="soa" free="707344680" total="707705856" percent="99" />
      <mem type="loa" free="45171712" total="45171712" percent="100" />
    </mem>
    <pending-finalizers system="0" default="0" reference="693" classloader="0" />
    <remembered-set count="4897" />
  </mem-info>
</gc-end>
<cycle-end id="23" type="global" contextid="11" timestamp="2019-05-11T19:16:11.155" />
<cycle-start id="24" type="global" contextid="0" timestamp="2019-05-11T19:16:11.159" intervalms="31.341" />
<gc-start id="25" type="global" contextid="24" timestamp="2019-05-11T19:16:11.159">
  <mem-info id="26" free="767978984" total="786432000" percent="97">
    <mem type="nursery" free="15462592" total="33554432" percent="46">
      <mem type="allocate" free="15462592" total="16777216" percent="92" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="752516392" total="752877568" percent="99">
      <mem type="soa" free="707344680" total="707705856" percent="99" />
      <mem type="loa" free="45171712" total="45171712" percent="100" />
    </mem>
    <pending-finalizers system="0" default="0" reference="693" classloader="0" />
    <remembered-set count="4897" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="0" >
  <allocated-bytes non-tlh="0" tlh="0" />
</allocation-stats>
<heap-resize id="27" type="loa contract" space="tenure" amount="37643264" count="1" timems="0.000" reason="contract on aggressive gc" timestamp="2019-05-11T19:16:11.159" />
<gc-op id="28" type="mark" timems="9.999" contextid="24" timestamp="2019-05-11T19:16:11.169">
  <trace-info objectcount="27331" scancount="22474" scanbytes="747100" />
  <finalization candidates="80" enqueued="0" />
  <ownableSynchronizers candidates="2" cleared="0" />
  <references type="soft" candidates="289" cleared="183" enqueued="174" dynamicThreshold="31" maxThreshold="32" />
  <references type="weak" candidates="775" cleared="0" enqueued="0" />
  <references type="phantom" candidates="26" cleared="0" enqueued="0" />
  <stringconstants candidates="3018" cleared="0"  />
</gc-op>
<gc-op id="29" type="classunload" timems="0.013" contextid="24" timestamp="2019-05-11T19:16:11.169">
  <classunload-info classloadercandidates="8" classloadersunloaded="0" classesunloaded="0" anonymousclassesunloaded="0" quiescems="0.000" setupms="0.012" scanms="0.001" postms="0.000" />
</gc-op>
<gc-op id="30" type="sweep" timems="1.764" contextid="24" timestamp="2019-05-11T19:16:11.171" />
<mem-info id="31" free="768158160" total="786432000" percent="97">
  <mem type="nursery" free="15641768" total="33554432" percent="46">
    <mem type="allocate" free="15641768" total="16777216" percent="93" />
    <mem type="survivor" free="0" total="16777216" percent="0" />
  </mem>
  <mem type="tenure" free="752516392" total="752877568" percent="99" micro-fragmented="0" macro-fragmented="0">
    <mem type="soa" free="744987944" total="745349120" percent="99" />
    <mem type="loa" free="7528448" total="7528448" percent="100" />
  </mem>
  <pending-finalizers system="0" default="0" reference="867" classloader="0" />
  <remembered-set count="4897" />
</mem-info>
<gc-op id="32" type="compact" timems="7.137" contextid="24" timestamp="2019-05-11T19:16:11.178">
  <compact-info movecount="13598" movebytes="911296" reason="compact to meet allocation" />
</gc-op>
<gc-end id="33" type="global" contextid="24" durationms="19.906" usertimems="27.816" systemtimems="0.000" timestamp="2019-05-11T19:16:11.179" activeThreads="2">
  <mem-info id="34" free="768173800" total="786432000" percent="97">
    <mem type="nursery" free="15657408" total="33554432" percent="46">
      <mem type="allocate" free="15657408" total="16777216" percent="93" />
      <mem type="survivor" free="0" total="16777216" percent="0" />
    </mem>
    <mem type="tenure" free="752516392" total="752877568" percent="99">
      <mem type="soa" free="744987944" total="745349120" percent="99" />
      <mem type="loa" free="7528448" total="7528448" percent="100" />
    </mem>
    <pending-finalizers system="0" default="0" reference="867" classloader="0" />
    <remembered-set count="4897" />
  </mem-info>
</gc-end>
<cycle-end id="35" type="global" contextid="24" timestamp="2019-05-11T19:16:11.179" />
<allocation-unsatisfied id="36" threadId="0000000001283E00" bytesRequested="2147483656" />
<af-end id="37" timestamp="2019-05-11T19:16:11.179" threadId="0000000001284788" success="false" />
<exclusive-end id="38" timestamp="2019-05-11T19:16:11.179" durationms="57.745" />

JVMDUMP039I Elaborazione dell'evento dump "systhrow", dettagli "java/lang/OutOfMemoryError" in 2019/05/11 19:16:11 - attendere.
JVMDUMP032I JVM ha richiesto il dump System utilizzando '/home/francesco/java_error_in_IDEA.hprof/core.20190511.191611.10443.0001.dmp' in risposta a un evento
JVMDUMP012E Errore nel dump System: The core file created by child process with pid = 10464 was not found. Expected to find core file with name "/home/francesco/java_error_in_IDEA.hprof/core"
JVMDUMP032I JVM ha richiesto il dump Heap utilizzando '/home/francesco/java_error_in_IDEA.hprof/heapdump.20190511.191611.10443.0002.phd' in risposta a un evento
JVMDUMP010I Dump Heap scritto in /home/francesco/java_error_in_IDEA.hprof/heapdump.20190511.191611.10443.0002.phd
JVMDUMP032I JVM ha richiesto il dump Java utilizzando '/home/francesco/java_error_in_IDEA.hprof/javacore.20190511.191611.10443.0003.txt' in risposta a un evento
JVMDUMP010I Dump Java scritto in /home/francesco/java_error_in_IDEA.hprof/javacore.20190511.191611.10443.0003.txt
JVMDUMP032I JVM ha richiesto il dump Snap utilizzando '/home/francesco/java_error_in_IDEA.hprof/Snap.20190511.191611.10443.0004.trc' in risposta a un evento
JVMDUMP010I Dump Snap scritto in /home/francesco/java_error_in_IDEA.hprof/Snap.20190511.191611.10443.0004.trc
JVMDUMP013I Evento dump elaborato "systhrow", dettaglio "java/lang/OutOfMemoryError".

Start Failed: Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.OutOfMemoryError: Spazio di heap Java
        at gnu.trove.TPrimitiveHash.setUp(TPrimitiveHash.java:123)
        at gnu.trove.TIntHash.setUp(TIntHash.java:126)
        at gnu.trove.TIntHash.insertionIndex(TIntHash.java:213)
        at gnu.trove.TIntHashSet.add(TIntHashSet.java:137)
        at com.intellij.util.lang.ClasspathCache$LoaderDataBuilder.addResourcePackageFromName(ClasspathCache.java:85)
        at com.intellij.util.lang.JarLoader.buildData(JarLoader.java:162)
        at com.intellij.util.lang.ClassPath.initLoader(ClassPath.java:241)
        at com.intellij.util.lang.ClassPath.initLoaders(ClassPath.java:202)
        at com.intellij.util.lang.ClassPath.getLoaderSlowPath(ClassPath.java:164)
        at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:144)
        at com.intellij.util.lang.ClassPath.access$700(ClassPath.java:32)
        at com.intellij.util.lang.ClassPath$MyEnumeration.next(ClassPath.java:318)
        at com.intellij.util.lang.ClassPath$MyEnumeration.hasMoreElements(ClassPath.java:334)
        at java.base/java.lang.ClassLoader.getResources(ClassLoader.java:807)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1196)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at java.base/java.util.GPUAssistHolder.gpuAssist(GPUAssistHolder.java:34)
        at java.util.GPUAssistHolder$$Lambda$55.0000000094568F00.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
        at java.base/java.util.GPUAssistHolder.<clinit>(GPUAssistHolder.java:29)
        at java.base/java.util.Arrays.sort(Arrays.java:153)
        at gnu.trove.PrimeFinder.<clinit>(PrimeFinder.java:138)
        at gnu.trove.THash.setUp(THash.java:246)
        at gnu.trove.TPrimitiveHash.setUp(TPrimitiveHash.java:122)
        at gnu.trove.TIntHash.setUp(TIntHash.java:126)
        at gnu.trove.TIntHash.insertionIndex(TIntHash.java:213)
        at gnu.trove.TIntHashSet.add(TIntHashSet.java:137)
        at com.intellij.util.lang.ClasspathCache$LoaderDataBuilder.addResourcePackageFromName(ClasspathCache.java:85)
        at com.intellij.util.lang.JarLoader.buildData(JarLoader.java:162)
        at com.intellij.util.lang.ClassPath.initLoader(ClassPath.java:241)
        at com.intellij.util.lang.ClassPath.initLoaders(ClassPath.java:202)
        at com.intellij.util.lang.ClassPath.getLoaderSlowPath(ClassPath.java:164)
        at com.intellij.util.lang.ClassPath.getLoader(ClassPath.java:144)
        at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:117)
        at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:265)
        at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:254)
        at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1157)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1072)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1055)
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:415)
        at com.intellij.ide.Bootstrap.main(Bootstrap.java:22)
        at com.intellij.idea.Main.main(Main.java:61)

</verbosegc>
~~~
[java_error_in_IDEA.hprof.zip](https://github.com/eclipse/openj9/files/3169301/java_error_in_IDEA.hprof.zip)

**Comment by charliegracie** [comment]
From the verbose:gc log: `<af-start id="3" threadId="0000000001284788" totalBytesRequested="2147483656" timestamp="2019-05-11T19:16:11.121" intervalms="727.578" type="nursery" />`.  Something is trying to allocate an object of size ~2GB and the heap is limited to 750MB. In the zip file there is a javacore where I found the -Xmx750M.

**Comment by charliegracie** [comment]
Would you be able to do another run with the following command line option added to the set used in the previous run?
`-Xdump:stack:events=allocation,filter=#750m`.

This will print the stack information for all allocations over 750m to stderr.

**Comment by fvasco** [comment]
That's all, however Idea CE is free.

[log.zip](https://github.com/eclipse/openj9/files/3169814/log.zip)

**Comment by fvasco** [comment]
Filed the issue https://intellij-support.jetbrains.com/hc/requests/2098185

**Comment by soumyabanerjee** [comment]
Issue also seen with AdoptOpenJDK 11.0.3
Interesting, does not happen with bundled JBR.

**Comment by soumyabanerjee** [comment]
So downgraded to 11.0.2 and issue still persist with IntelliJ 2019.1.2. Neither IntelliJ 2017/2018 have this issue with OpenJ9 11.0.2. So chances are the regression is from JetBrains team.

**Comment by fvasco** [comment]
Issue does happen with Adopt HotSpot

**Comment by fvasco** [comment]
JetBrains Support is not interested to investigate further.

**Comment by pshipton** [comment]
`-Xdump:stack:events=allocation,filter=#750m` just shows the same stacktrace in the description.
The problem still occurs with `-Xint` and with `-XX:+PositiveIdentityHash`

**Comment by karmakaze** [comment]
I've tried mixing jars between Idea Community 2018.3.6 and 2019.1.1 and found that the OutOfMemoryError occurs with the 2019.1.1 versions of the `extensions.jar` and `util.jar`. Mismatching versions of these two jars results in a different missing extension point error.

The command-line I tried was pieced together from the idea.bat on Windows10 (64-bit).

Working 2018.3.6 version (using trove4j.jar from 2019.1.1 libs):
```
"%IDEA_JDK%\bin\java" "-XX:ErrorFile=%USERPROFILE%\java_error_in_IDEA_%%p.log" "-XX:HeapDumpPath=%USERPROFILE%\java_error_in_IDEA.hprof" -Didea.paths.selector=IdeaIC2018.3 -cp "%IDE_HOME%\lib\bootstrap.jar;%IDE_HOME%\lib\extensions.jar;%IDE_HOME%\lib\util.jar;%IDE_HOME%\lib\jdom.jar;%IDE_HOME%\lib\log4j.jar;%IDE19_HOME%\lib\trove4j.jar;%IDE_HOME%\lib\jna.jar;%IDEA_JDK%\lib\tools.jar" com.intellij.idea.Main
```

OutOfMemoryError with 2018.3.6 mixed with 2019.1.1 extensions.jar and util.jar
```
"%IDEA_JDK%\bin\java" "-XX:ErrorFile=%USERPROFILE%\java_error_in_IDEA_%%p.log" "-XX:HeapDumpPath=%USERPROFILE%\java_error_in_IDEA.hprof" -Didea.paths.selector=IdeaIC2018.3 -cp "%IDE_HOME%\lib\bootstrap.jar;%IDE19_HOME%\lib\extensions.jar;%IDE19_HOME%\lib\util.jar;%IDE_HOME%\lib\jdom.jar;%IDE_HOME%\lib\log4j.jar;%IDE_HOME%\lib\trove4j.jar;%IDE_HOME%\lib\jna.jar;%IDEA_JDK%\lib\tools.jar" com.intellij.idea.Main
```
where:
* IDEA_JDK=C:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-openj9
* IDE_HOME=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
* IDE19_HOME=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1

There are quite a number of classes in the util.jar but my suspicion would be something to do with `com.intellij.util.lang.ClasspathCache$LoaderDataBuilder`.

**Comment by fjeremic** [comment]
@pshipton can we bump the priority to get this one investigated? Seems quite a few users are interested.

**Comment by pshipton** [comment]
The problem is here `at java.base/java.util.GPUAssistHolder.gpuAssist(GPUAssistHolder.java:34)`.

The GPUAssistHolder, which is a helper used by Array.sort() to optionally sort arrays on a gpu, is using the ServiceLoader framework. intellij has added it's own ClassLoader which is involved in finding the service providers. The intellij ClassLoader is using TIntHashSet(), which depends on having a sorted array of prime numbers. The GPUAssistHolder interferes with the array sorting, causing an incorrect value (Integer.MAX_VALUE) to be returned, which results in the OOM.

The code needs to be fixed. In the meantime, it can be worked around by using a java agent to pre-initialize Arrays.sort(), as follows.

Either
`java -javaagent:premain.zip ...`
or 
`export OPENJ9_JAVA_OPTIONS=-javaagent:premain.zip`

You probably need to specify the path to the premain.zip. 

The source is included in the zip.
[premain.zip](https://github.com/eclipse/openj9/files/3214370/premain.zip)

@keithc-ca

**Comment by fjeremic** [comment]
@fvasco the issue is fixed in the linked PR. Should be a day or two before the next Nightly build at AdoptOpenJDK picks up the commit and you can use that to verify.
