### ISSUE TITLE
extended.functional testDDRExt_SharedClasses_openj9_0 output does not contain success key : java/util/HashMap

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5741]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/29/tapResults/
```
     [java] [AutoRun] [INFO] Starting testShrcFindJITHext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [ERROR] '!shrc  jithstats' output does not contain success key : java/util/HashMap
     [java] [DDRExtTesterBase] [ERROR] '!shrc  jithstats' output :!j9sharedclassconfig 0x00007EFF480E3B30
     [java] 
     [java] Meta data region to be used: 0x00007EFF067E5F60..0x00007EFF06800FFC
     [java] !j9sharedcacheheader 0x00007EFEF54000F0
     [java] cache size       : 314544128
     [java] free bytes       : 63963064
     [java] softmx bytes     : 67108864
     [java] read write area  : 0x00007EFEF5400260 - 0x00007EFEF5400260 size 28432 used 0
     [java] segment area     : 0x00007EFEF5407000 - 0x00007EFEF56602E8 size 2462440
     [java] metadata area    : 0x00007EFF067E5F60 - 0x00007EFF06801000 size 110752
     [java] class debug area : 0x00007EFF06801000 - 0x00007EFF08000000 size 25161728 used 543936 (% used 2)
     [java] 1: 0x00007EFF067FE340 JITHINT data !j9x 0x00007EFF067FE358,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	getCharFromArrayByIndex(Ljava/lang/Object;I)C !j9rommethod 0x00007EFEF54252B8
     [java] 	com/ibm/jit/JITHelpers !j9romclass 0x00007EFEF5423E88
     [java] 1: 0x00007EFF067FC028 JITHINT data !j9x 0x00007EFF067FC040,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	putCharInArrayByIndex(Ljava/lang/Object;IC)V !j9rommethod 0x00007EFEF54251D8
     [java] 	com/ibm/jit/JITHelpers !j9romclass 0x00007EFEF5423E88
     [java] 1: 0x00007EFF067F7940 JITHINT data !j9x 0x00007EFF067F7958,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	floorMod(II)I !j9rommethod 0x00007EFEF5495198
     [java] 	java/lang/Math !j9romclass 0x00007EFEF54941C0
     [java] 2: 0x00007EFF067F1D90 JITHINT data !j9x 0x00007EFF067F1DA8,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	requireNonNull(Ljava/lang/Object;)Ljava/lang/Object; !j9rommethod 0x00007EFEF54362FC
     [java] 	java/util/Objects !j9romclass 0x00007EFEF5435F58
     [java] 2: 0x00007EFF067ECD90 JITHINT data !j9x 0x00007EFF067ECDA8,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	afterClinitInitialization()V !j9rommethod 0x00007EFEF5440188
     [java] 	java/lang/System !j9romclass 0x00007EFEF543F5F0
     [java] 2: 0x00007EFF067EB638 JITHINT data !j9x 0x00007EFF067EB650,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	getName()Ljava/lang/String; !j9rommethod 0x00007EFEF540F37C
     [java] 	java/lang/Class !j9romclass 0x00007EFEF540B7E8
     [java] 2: 0x00007EFF067EAC20 JITHINT data !j9x 0x00007EFF067EAC38,0x0000000000000004  type 2 updates 0 corrupt -1
     [java] 	append(Ljava/lang/String;)Ljava/lang/AbstractStringBuilder; !j9rommethod 0x00007EFEF54CE62C
     [java] 	java/lang/AbstractStringBuilder !j9romclass 0x00007EFEF54CD820
     [java] 
     [java] Cache contains 1463 classes, 6 orphans, 3 classpaths, 0 URLs, 0 tokens
     [java] 14 AOT, 26 SCOPES, 24 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
     [java] stale bytes 0
     [java] 120 JITPROFILE, 7 JITHINT
     [java] AOT data length 14680 code length 9280 metadata 336 total 23960
     [java] JITPROFILE data length 19376 metadata 3360 
     [java] JITHINT data length 28 metadata 196 
     [java] ROMClass data 2462440 metadata 58628
     [java] SCOPE data 506 metadata 312 total 818
     [java] BYTE data 1177 metadata 672 rwarea 0
     [java] UNINDEXEDBYTE data 0 metadata 0
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 248
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 0  STARTUPHINTS 0
     [java] 	JITHINT 192  AOTCLASSCHAIN 648 AOTTHUNK 89
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 205698
     [java] 	LocalVariableTable bytes : 338238
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcJITHStatsExt(TestSharedClassesExt.java:484)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] [DDRExtTesterBase] [ERROR] '!shrc  findjith <init>' output does not contain success key : <init>\(.*\)
     [java] [DDRExtTesterBase] [ERROR] '!shrc  findjith <init>' output :!j9sharedclassconfig 0x00007EFF480E3B30
     [java] 
     [java] Meta data region to be used: 0x00007EFF067E5F60..0x00007EFF06800FFC
     [java] Looking for JIT HINT method "<init>"
     [java] No entry found in the cache
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcFindJITHext(TestSharedClassesExt.java:496)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] [DDRExtTesterBase] [ERROR] '!shrc  findjithp <init>' output does not contain success key : <init>\(.*\)
     [java] [DDRExtTesterBase] [ERROR] '!shrc  findjithp <init>' output :!j9sharedclassconfig 0x00007EFF480E3B30
     [java] 
     [java] Meta data region to be used: 0x00007EFF067E5F60..0x00007EFF06800FFC
     [java] Looking for JIT HINT method prefix "<init>"
     [java] No entry found in the cache
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcFindJITHPext(TestSharedClassesExt.java:509)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] junit.framework.AssertionFailedError: No jit hint information found for the method :<init>. Can not proceed with test
     [java] 	at junit.framework.Assert.fail(Assert.java:50)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcJITHForExt(TestSharedClassesExt.java:522)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
```

**Comment by pshipton** [comment]
I expect this is a test problem, related to timing for adding AOT to the cache.
@hangshao0

**Comment by hangshao0** [comment]
Yes, this is a test issue.

**Comment by pshipton** [comment]
@llxia

**Comment by llxia** [comment]
We will investigate it.

**Comment by hangshao0** [comment]
```
TCK.initialize.cache:
     [echo] Initializing cache
     [echo] Running j9vm.test.corehelper.StackMapCoreGenerator to create a new cache
     [echo] Using JVM : ${sdk.executable}${sdk.executable.ext}
     [echo] classname = "j9vm.test.corehelper.StackMapCoreGenerator"
     [echo] Java VM Args:
     [echo] 	jvmarg = -Xshareclasses:name=ddrextjunitSCC,reset,modified=mod1
```

"addtestjithints" works on classes that can be found in the shared cache. I see in "TCK.initialize.cache", option "modified=mod1" is used. But in the second run that creates the core dump, option "modified=mod1" is not there. I believe removing "modified=mod1" should make this test case pass.

**Comment by llxia** [comment]
Thanks @hangshao0 

Ran the test 100x after removing `modified=mod1` and all passed.
