### ISSUE TITLE
NullPointerException running javac

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5833]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/43
```
02:58:34  compile:
02:58:34       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018
02:58:34       [echo] ============COMPILER SETTINGS============
02:58:34       [echo] ===fork:                         yes
02:58:34       [echo] ===executable:                   /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac
02:58:34       [echo] ===debug:                        on
02:58:34       [echo] ===destdir:                      /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/openjdk-tests/functional/cmdLineTests/jvmtitests/bin
02:58:34      [javac] Compiling 309 source files to /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/openjdk-tests/functional/cmdLineTests/jvmtitests/bin
02:58:37      [javac] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/openjdk-tests/functional/cmdLineTests/jvmtitests/src_80/com/ibm/jvmti/tests/util/DefineAnonClass.java:30: warning: Unsafe is internal proprietary API and may be removed in a future release
02:58:37      [javac] import sun.misc.Unsafe;
02:58:37      [javac]                ^
02:58:40      [javac] An exception has occurred in the compiler (1.8.0_202-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
02:58:40      [javac] java.lang.NullPointerException
02:58:40      [javac] 	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.debug(Resolve.java:3118)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3349)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3333)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Resolve.resolveMethod(Resolve.java:2400)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3166)
02:58:40      [javac] 	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
02:58:40      [javac] 	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:625)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1593)
02:58:40      [javac] 	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
02:58:40      [javac] 	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
02:58:40      [javac] 	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
02:58:40      [javac] 	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
02:58:40      [javac] 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
02:58:40      [javac] 	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
02:58:40      [javac] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
02:58:40      [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
02:58:40      [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:381)
02:58:40      [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:370)
02:58:40      [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:361)
02:58:40      [javac] 	at com.sun.tools.javac.Main.compile(Main.java:56)
02:58:40      [javac] 	at com.sun.tools.javac.Main.main(Main.java:42)
```

**Comment by pshipton** [comment]
I suspect this was resolved. Will reopen if seen again.
