### ISSUE TITLE
[IBM GPU] no CUDA-capable device is detected

### ISSUE THREAD

**Issue by jjfumero** [eclipse/openj9#5875]
## Java -version output

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
Eclipse OpenJ9 VM (build openj9-0.14.2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190521_315 (JIT enabled, AOT enabled)
OpenJ9   - 4b1df46fe
OMR      - b56045d2
JCL      - a8c217d402 based on jdk8u212-b04)

## Summary of problem

I am following of the simple examples explained [here](https://www.ibm.com/support/knowledgecenter/SSYKE2_7.1.0/com.ibm.java.lnx.71.doc/user/gpu_developing_sort.html) to use the GPU. 

Here the example:

```java
import com.ibm.gpu.GPUConfigurationException;
import com.ibm.gpu.GPUSortException;

import java.util.Arrays;

import com.ibm.gpu.CUDAManager;
import com.ibm.gpu.Maths;

/**
 * How to run: java -Dcom.ibm.gpu.verbose HelloGPUIBM
 */
public class HelloGPU {
    public static void main(String[] args) {
        int[] toSort = { 5, 17, 12, 32, 2, 6, 3, 20 };
		try {
			Maths.sortArray(toSort);
		} catch (GPUSortException e) {
			e.printStackTrace();
		} catch (GPUConfigurationException e) {
			e.printStackTrace();
        }
        System.out.println(Arrays.toString(toSort));
    }
}
```

I am using the jdk8u212-b04 build.  When I run I get the following stack-trace:

```bash
../compiler/jdk8u212-b04/bin/java -Dcom.ibm.gpu.verbose HelloGPU
[IBM GPU]: [time.ms=1558708407194]: Using device: 0 to sort int array; elements 0 to 8
[IBM GPU]: [time.ms=1558708407209]: no CUDA-capable device is detected
com.ibm.gpu.GPUConfigurationException: no CUDA-capable device is detected
	at com.ibm.gpu.SortNetwork$LoadResult.get(SortNetwork.java:167)
	at com.ibm.gpu.SortNetwork.load(SortNetwork.java:251)
	at com.ibm.gpu.SortNetwork.sortArray(SortNetwork.java:337)
	at com.ibm.gpu.Maths.sortArray(Maths.java:361)
	at HelloGPU.main(HelloGPU.java:16)
[5, 17, 12, 32, 2, 6, 3, 20]
```

I am using NVIDIA driver 430.14 with CUDA 10.0 on a CentOS 7.6 laptop. 

Any poiner about what is happening? Also, where can I get more documentation about the GPU backend? GPU options and examples? Any pointers will be approciated. 

I would like to see also the generated code if it is possible. 

Thanks

**Comment by pshipton** [comment]
The GPU support is not enabled in builds created by AdoptOpenJDK. I believe there is a licensing issue with the NVIDIA CUDA Toolkit. You can build it yourself and turn on the GPU support, although you'd need to install the NVIDIA CUDA Toolkit and agree to the license. 

Also note the OpenJDK extensions required to use GPU for array sort are not currently present in https://github.com/ibmruntimes/openj9-openjdk-jdk8. You'd need to build and use JDK11, which is enabled. 

@mstoodle @keithc-ca

**Comment by keithc-ca** [comment]
If you want to create a build with CUDA support, the relevant configure options to add are:
```
    --enable-cuda --with-cuda=/usr/local/cuda-10.0
```
(this assumes you have installed the CUDA 10 toolkit in the default location). You don't need the full toolkit for this, just the header files in /usr/local/cuda-10.0/include; you should already have the necessary shared libraries installed that will be needed at runtime.

You can see the generated PTX code for sorting 'int' with
```
    com.ibm.gpu.PtxKernelGenerator.writeTo(3, 'I', System.out);
```
That class is package-private so you'll either have to make it public in your build or add the code above to a new class in that package; alternatively you could copy `PtxKernelGenerator` to another package (it uses no internal API).

**Comment by jjfumero** [comment]
Thanks for your answers. I tried the installation on a Ubuntu 16.04  with CUDA 10.0 and it seems to work now. On CentOS, dependencies are too old. 

```
./bin/java -Dcom.ibm.gpu.verbose HelloGPU
[IBM GPU]: [time.ms=1559032626042]: Using device: 0 to sort int array; elements 0 to 8
[IBM GPU]: [time.ms=1559032626841]: Sorted ints on device 0 successfully
[2, 3, 5, 6, 12, 17, 20, 32]
```

I assume that the `time.ms` is a timestamp from the CUDA application? So that means that the generated CUDA kernel time takes 799ms. Is that right? 

Is it possible to obtain the time for data transfers as well? `H->D` and `D->H`

**Comment by keithc-ca** [comment]
Yes, 799ms elapsed within that call to `SortNetwork.sortArray()`.

The first use will include:
* loading a number of Java classes
* generating the PTX code
* compiling the PTX code to GPU native code
* transferring the native code the code to the GPU
* allocating memory on the GPU
* transferring the data to the GPU
* launching the appropriate set of kernels to sort the data
* transferring the data back to the CPU
* releasing the GPU memory

Subsequent calls to `SortNetwork.sortArray()` will not need to repeat the first four parts (for the same data type, e.g. `int`).

You can get more detail by adding `"-Xtrace:print=mt,methods=com/ibm/cuda.*"` to the VM command line. The transfers happen within `CudaBuffer.copyFromHostInt()` and `CudaBuffer.copyToHostInt()`.

**Comment by Byronze** [comment]
I have tried your way to build the jdk with Ubuntu 16.04, titan V ,nvidia-430 and cuda-9.1, the Math.sortArray is worked as you do, but the JIT GPU cannot work。
my example is gemm:
IntStream.range(0, N * N).parallel().forEach(idx -> {
                        int i = idx / N, j = idx % N;
                        int s = 0;
                        for (int k = 0; k < N; k++) {
                                s += b[i * N + k] * c[k * N + j];
                        }
                        a[idx] = s;
                });
and I tried :
java -Xjit:"enableGPU={default|verbose}" streamtest 1024
only got:
[IBM GPU JIT]:  Device Number  0: name=TITAN V, ComputeCapability=7.0
time:127510ms
It seems that no work is actually shifted to the GPU.

**Comment by pshipton** [comment]
@gita-omr

**Comment by gita-omr** [comment]
JIT-based GPU support is not enabled in openj9 yet. Interestingly, we are working on it right at this moment and hoping to open a PR very soon.

**Comment by Byronze** [comment]
emmmm...thanks

**Comment by gita-omr** [comment]
It’s actually there, we just need to provide instructions how to build it. Similar to arraySort support, AdoptOpenJDK does not build with GPU enabled. We will provide build instructions and documentation soon.

**Comment by gita-omr** [comment]
@Byronze You can also try IBM JDK from https://developer.ibm.com/javasdk/downloads/

All GPU support is enabled there.

**Comment by Byronze** [comment]
@gita-omr I think tornado's GPU support for users is better..I'd like to see your build instructions and documentation

**Comment by keithc-ca** [comment]
If accepted, AdoptOpenJDK/openjdk-build#1187 should enable CUDA for AdoptOpenJDK builds.

**Comment by gita-omr** [comment]
@ahayashi fyi

**Comment by gita-omr** [comment]
@Byronze ,re your IntStream test case above. After more careful investigation, it looks like JIT-GPU support is enabled in your build. [IBM GPU JIT] is an indication of that. Did you use **--enable-cuda --with-cuda** options?

In any case, GPU could  not happen because there is reduction statement s +=...  there. We currently do not support reductions on GPU. Please try some simple test case first, eg.:

import java.util.Random;
import java.util.stream.IntStream;

public class VecAdd {
    static float[] A;
    static float[] B;
    static float[] C;
    final static int T = 100;
    final static int ROWS = 4*1024*1024;

    public static void main (String[] args) {
        A = new float [ROWS];
        B = new float [ROWS];
        C = new float [ROWS];

        for (int i = 0; i < ROWS; i++) {
            A[i] = (float)i;
            B[i] = (float)i*2;
        }

        for (int iter  = 0; iter < T; iter++) {
            runGPULambda();
        }
        for (int i = 0; i < 10; i++) {
            System.out.println(C[i]);
        }
    }

    public static void runGPULambda() {
        IntStream.range(0, ROWS).parallel().forEach( i -> {
                C[i] = A[i] + B[i];
            } );        
    }
}

**Comment by gita-omr** [comment]
Here is also a script to run it:

#!/bin/bash -x

export LD_LIBRARY_PATH=/usr/local/cuda/nvvm/lib64:/usr/local/cuda/lib64

JAVAC="${JAVA_HOME}/bin/javac"
JFLAGS="-J-Xcompressedrefs -J-Xnojit -g"
J9_EXEC="${JAVA_HOME}/jre/bin/java"
JITFLAG="{*.runGPULambda*}(traceFull),enableGPU={details|verbose|enforce},disableAsyncCompilation,dontInline={*.runGPULambda*}"
J9_FLAGS="-Xcompressedrefs -XX:-EnableHCR -Xjit:${JITFLAG},log=test.trc"

CLASS=VecAdd
echo compiling ${CLASS}
${JAVAC} ${JFLAGS} ${CLASS}.java
echo running ${CLASS}
${J9_EXEC} ${J9_FLAGS} ${CLASS}

**Comment by xushijie** [comment]
> [@Byronze](https://github.com/Byronze) ,re your IntStream test case above. After more careful investigation, it looks like JIT-GPU support is enabled in your build. [IBM GPU JIT] is an indication of that. Did you use **--enable-cuda --with-cuda** options?
> 
> In any case, GPU could not happen because there is reduction statement s +=... there. We currently do not support reductions on GPU. Please try some simple test case first, eg.:
> 
> import java.util.Random; import java.util.stream.IntStream;
> 
> public class VecAdd { static float[] A; static float[] B; static float[] C; final static int T = 100; final static int ROWS = 4_1024_1024;
> 
> ```
> public static void main (String[] args) {
>     A = new float [ROWS];
>     B = new float [ROWS];
>     C = new float [ROWS];
> 
>     for (int i = 0; i < ROWS; i++) {
>         A[i] = (float)i;
>         B[i] = (float)i*2;
>     }
> 
>     for (int iter  = 0; iter < T; iter++) {
>         runGPULambda();
>     }
>     for (int i = 0; i < 10; i++) {
>         System.out.println(C[i]);
>     }
> }
> 
> public static void runGPULambda() {
>     IntStream.range(0, ROWS).parallel().forEach( i -> {
>             C[i] = A[i] + B[i];
>         } );        
> }
> ```
> 
> }

The streaming API with rangge is supported to use GPU, by generating PTX code using JIT compiler. 
Do you have idea where is the source code? Someone told me before but I can not find it now.

**Comment by keithc-ca** [comment]
I think you're looking for [CodeGenGPU.cpp](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/codegen/CodeGenGPU.cpp) and [GPUHelpers.cpp](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/runtime/GPUHelpers.cpp).
