### ISSUE TITLE
java.lang.NoSuchMethodError on test_indyn_invalid_bootstrap_method

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#600]
failure message:
```
===============================================
Running test jsr292_InDynTest_0 ...
===============================================
test with NoOptions
{ "/openj9/bin/java"  -Xcompressedrefs  \
-cp "/test/TestConfig/../../jvmtest/Jsr292/jsr292test.jar:/test/TestConfig/../../jvmtest/TestConfig/resources:/test/TestConfig/../../jvmtest/TestConfig/lib/testng.jar:/test/TestConfig/../../jvmtest/TestConfig/lib/jcommander.jar:/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" \
org.testng.TestNG -d "/test/TestConfig/test_output_1510778963/jsr292_InDynTest_0" "/test/TestConfig/../../jvmtest/Jsr292/testngSE90.xml" \
-testnames jsr292_InDynTest \
-groups level.extended \
-excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all; \
if [ $? -eq 0 ] ; then echo "jsr292_InDynTest_0""_PASSED"; else echo "jsr292_InDynTest_0""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /test/TestConfig/../TestConfig/resources/excludes/openj9_exclude.txt
...
... TestNG 6.10 by C?dric Beust (cedric@beust.com)
...

[TestNG] Running:
  /jvmtest/Jsr292/testngSE90.xml

PASSED: test_boostrap_return_constant_MethodType
PASSED: test_different_bsm_signatures
PASSED: test_indyn_asType_identity
PASSED: test_indyn_bind_mh_to_receiver
PASSED: test_indyn_call_Illegal_crosspackage_method
PASSED: test_indyn_call_invalid_method
PASSED: test_indyn_constant
PASSED: test_indyn_dropArguments
PASSED: test_indyn_filter_arguments_on_drop_arguments
PASSED: test_indyn_filter_return
PASSED: test_indyn_findGetter
PASSED: test_indyn_findSetter
PASSED: test_indyn_findSpecial
PASSED: test_indyn_findStatic
PASSED: test_indyn_findStaticGetter
PASSED: test_indyn_findStaticSetter
PASSED: test_indyn_findVirtual
PASSED: test_indyn_findVirtual_interface
PASSED: test_indyn_guard_with_test_constant_true
PASSED: test_indyn_guard_with_test_let_input_decide
PASSED: test_indyn_ldc_BootstrapMethod_type
PASSED: test_indyn_ldc_String_type
PASSED: test_indyn_ldc_invalidMethod
PASSED: test_indyn_ldc_invalid_CrossPackage_Access
PASSED: test_indyn_ldc_invalid_PrivateAccess
PASSED: test_indyn_ldc_invalid_type
PASSED: test_indyn_ldc_toLowerCase
PASSED: test_indyn_ldc_toString
PASSED: test_catchTest
PASSED: test_fibTest
PASSED: test_foldTest
PASSED: test_gwtTest_Integer
PASSED: test_gwtTest_Object
PASSED: test_gwtTest_String
PASSED: test_mcsTest
PASSED: test_permuteTest
PASSED: test_switchpointTest
FAILED: test_indyn_invalid_bootstrap_method
java.lang.NoSuchMethodError: com/ibm/j9/jsr292/indyn/BootstrapMethods.method_must_not_exist(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (loaded from file:/jvmtest/Jsr292/jsr292test.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@d391b822) called from class com.ibm.j9.jsr292.indyn.GenIndyn (loaded from file:/jvmtest/Jsr292/jsr292test.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@d391b822).
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(java.base@9-internal/Native Method)
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(java.base@9-internal/MethodHandle.java:812)
	at com.ibm.j9.jsr292.indyn.GenIndyn.invalid_bootstrap(Unknown Source)
	at com.ibm.j9.jsr292.indyn.IndyTest.test_indyn_invalid_bootstrap_method(IndyTest.java:218)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)


===============================================
    jsr292_InDynTest
    Tests run: 38, Failures: 1, Skips: 0
===============================================

root@3ca68caa24fd:/test/TestConfig# $JAVA_BIN/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171110_369845 (JIT enabled, AOT enabled)
OpenJ9   - 03c2335
OMR      - e1404d5
OpenJDK  - af9369e based on jdk-9+181)
root@3ca68caa24fd:/test/TestConfig# 

```

This test passed on SE80 but failed on SE90

**Comment by DanHeidinga** [comment]
```
java.lang.NoSuchMethodError: com/ibm/j9/jsr292/indyn/BootstrapMethods.method_must_not_exist
```
It appears that the exception is expected as the method is named `method_must_not_exist`.

There was a behaviour change between 8 & 9 where 8 expects every exception thrown by a BootstrapMethod to be wrapped in a BootStrapMethodError but 9 allows Error subclasses to be passed through.

This is likely a small fix to the test.

**Comment by DanHeidinga** [comment]
https://github.com/eclipse/openj9/blob/6858c8b89dc152d73fd9738869f2e6e8c133cbcd/test/Jsr292/src/com/ibm/j9/jsr292/indyn/IndyTest.java

```
} catch ( BootstrapMethodError e ) {
			bootstrapMethodError = true;
		}
```
Yup - Java 9 will need a different catch block... 

Something like:
```
boolean isJava9orNewer = ....

} catch ( BootstrapMethodError e ) {
       if (!isJava9orNewer) { 
 	     test_passed = true;
      }
} catch (NoSuchMethodError e) {
       if (isJava9orNewer) { 
 	     test_passed = true;
      }
}  
```

**Comment by TianyuZuo** [comment]
Great, thanks Dan, will update the test code to suit Java9
