### ISSUE TITLE
JTReg Test Failure - java/math/BigInteger/BigIntegerTest.java.BigIntegerTest fails

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#6139]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/305/testReport/junit/java_math_BigInteger_BigIntegerTest/java/BigIntegerTest/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/305/testReport/junit/java_math_BigInteger_BigIntegerTest/java/BigIntegerTest/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_windows/70/testReport/junit/java_math_BigInteger_BigIntegerTest/java/BigIntegerTest/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/213/testReport/junit/java_math_BigInteger_BigIntegerTest/java/BigIntegerTest/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux/562/testReport/junit/java_math_BigInteger_BigIntegerTest/java/BigIntegerTest/

Optional info
-------------

- intermittent failure (yes|no): yes

Failure output
--------------

```
Stacktrace

Execution failed: `main' threw exception: java.lang.ArrayIndexOutOfBoundsException    

Standard Output

Seed from RandomFactory = -548005041407499560L
    

Standard Error

Constructor: Passed
Prime: Passed
nextProbablePrime: Passed
Arithmetic I for 100 bits: Passed
Arithmetic II for 100 bits: Passed
Arithmetic I for 2760 bits: Passed
Arithmetic II for 2760 bits: Passed
Arithmetic I for 8000 bits: Passed
Arithmetic II for 8000 bits: Passed
divideAndRemainder for 100 bits: Passed
divideAndRemainder for 2760 bits: Passed
divideAndRemainder for 8000 bits: Passed
pow for 100 bits: Passed
pow for 2760 bits: Passed
pow for 8000 bits: Passed
square for 100 bits: Passed
square for 4200 bits: Passed
square for 7000 bits: Passed
squareRootSmall: Passed
squareRoot for 2^N and 2^N - 1, 1 <= N <= Double.MAX_EXPONENT: Passed
squareRoot for int: Passed
squareRoot for long: Passed
squareRoot for double: Passed
sqrtAndRemainder: Passed
Bit Count: Passed
BitLength: Passed
clearBit/testBit for 100 bits: Passed
flipBit/testBit for 100 bits: Passed
getLowestSetBit for 100 bits: Passed
Logic (^ | & ~) for 100 bits: Passed
Logic (&~ | ~) for 100 bits: Passed
baz shiftLeft for 100 bits: Passed
baz shiftRight for 100 bits: Passed
baz shiftLeft/Right for 100 bits: Passed
Array Conversion for 100 bits: Passed
Modular Inverse for 100 bits: Passed
Modular Inverse for 2760 bits: Passed
Modular Inverse for 8000 bits: Passed
Exponentiation I for 100 and 60 bits: Passed
Exponentiation II for 100 bits: Passed
String Conversion: Passed
Serialize: Passed
multiplyLarge Karatsuba: Passed
java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.math.BigInteger.add(BigInteger.java:1414)
	at java.base/java.math.BigInteger.add(BigInteger.java:1312)
	at java.base/java.math.BigInteger.multiplyToomCook3(BigInteger.java:1889)
	at java.base/java.math.BigInteger.multiply(BigInteger.java:1663)
	at java.base/java.math.BigInteger.multiply(BigInteger.java:1567)
	at BigIntegerTest.multiplyLarge(BigIntegerTest.java:494)
	at BigIntegerTest.main(BigIntegerTest.java:1273)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:831)

JavaTest Message: Test threw exception: java.lang.ArrayIndexOutOfBoundsException
JavaTest Message: shutting down test

```

Fails with
- 8,11,12 on windows
- 8, 11 on Mac
- 8 on linux,ppcle

Suspect non platform nor version specific.

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_ppc64_aix_Nightly/62/tapResults/

```
MLT testFailure: testItem_0731(net.adoptopenjdk.test.bigdecimal.TestSuite021): null
MLT java.lang.ArrayIndexOutOfBoundsException
MLT 	at java.math.BigInteger.add(BigInteger.java:1340)
MLT 	at java.math.BigInteger.add(BigInteger.java:1238)
MLT 	at java.math.BigInteger.squareKaratsuba(BigInteger.java:2119)
MLT 	at java.math.BigInteger.square(BigInteger.java:1985)
MLT 	at java.math.BigInteger.square(BigInteger.java:1964)
MLT 	at java.math.BigInteger.pow(BigInteger.java:2407)
MLT 	at java.math.BigDecimal.bigTenToThe(BigDecimal.java:3574)
MLT 	at java.math.BigDecimal.bigMultiplyPowerTen(BigDecimal.java:4548)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:4776)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:1761)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:1691)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite021.testItem_0731(TestSuite021.java:5196)
MLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
MLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
MLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
MLT 	at java.lang.reflect.Method.invoke(Method.java:498)
MLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
MLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
MLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
MLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
MLT 	at junit.framework.TestResult.run(TestResult.java:125)
MLT 	at junit.framework.TestCase.run(TestCase.java:129)
MLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
MLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
MLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
MLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
MLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
MLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
MLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
MLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
MLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
MLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
MLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
MLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
MLT 	at java.lang.Thread.run(Thread.java:819)
```

**Comment by pshipton** [comment]
I believe this has been fixed.
