### ISSUE TITLE
Validate that test_FindNestedClass_ProtectedAccess_DiffPackage passes on OJDK

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#636]
In the course of reviewing https://github.com/eclipse/openj9/pull/581 there is a check in `checkClassAccess` that uses `isProtected` to detect if a class is protected.  Removing this check causes one of our JSR292 tests to fail:
```
test_FindNestedClass_ProtectedAccess_DiffPackage as follows:
java.lang.IllegalAccessException: 'com.ibm.j9.jsr292.LookupAPITests_FindClass' no access to: 'com.ibm.j9.jsr292.helpers.Helper_LookupAPI_OtherPackage$ProtectedNestedClass'
at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(java.base@9-internal/MethodHandles.java:444)
at java.lang.invoke.MethodHandles$Lookup.checkAccess(java.base@9-internal/MethodHandles.java:334)
at java.lang.invoke.MethodHandles$Lookup.accessClass(java.base@9-internal/MethodHandles.java:1432)
at java.lang.invoke.MethodHandles$Lookup.findClass(java.base@9-internal/MethodHandles.java:1415)
at com.ibm.j9.jsr292.LookupAPITests_FindClass.test_FindNestedClass_ProtectedAccess_DiffPackage(LookupAPITests_FindClass.java:203)
```

We need to validate this behaviour on OpenJDK to confirm that results are consistent.

From the VM perspective, classes are only `public` or `package`.  From a Java Language perspective, inner classes can have a richer set of modifiers.

We need to validate which perspective is correct for this API.

**Comment by DanHeidinga** [comment]
@ChengJin01 FYI

**Comment by ChengJin01** [comment]
[OracleJDK_JSR292test.txt](https://github.com/eclipse/openj9/files/1492311/OracleJDK_JSR292test.txt)

**Comment by ChengJin01** [comment]
The all the tests related to access to the protected classes passed on OpenJDK including the failures on our build if removing the check of protected access.
...
PASSED: test_FindNestedClass_ProtectedAccess_DiffLookup_SamePackage
PASSED: test_FindNestedClass_ProtectedAccess_DiffPackage
PASSED: test_FindNestedClass_ProtectedAccess_PublicMode_DiffPackage
PASSED: test_AccessNestedClass_ProtectedAccess_DiffPackage
PASSED: test_AccessNestedClass_ProtectedAccess_SameNest_SamePackage
...

The only failures on OpenJDK are the access to protected classes from interface. It seems Oracle allows
such behavior to get through.

FAILED: test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage
java.lang.AssertionError: The class is not supposed to be found
        at org.testng.Assert.fail(Assert.java:94)
        at com.ibm.j9.jsr292.LookupAPITests_FindClass.test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage(LookupAPITests_FindClass.java:219)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
FAILED: test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage
java.lang.AssertionError: The protected class shouldn't be accessible to the lookup interface from a different package
        at org.testng.Assert.fail(Assert.java:94)
        at com.ibm.j9.jsr292.LookupAPITests_AccessClass.test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage(LookupAPITests_AccessClass.java:188)

**Comment by DanHeidinga** [comment]
Looking at https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/MethodHandles.Lookup.html it describes access checking occurring as though a bytecode was doing the method or field lookup.  The VM never checks for finer grained permissions on a class.  

If `checkClassAccess` was updated to only handle public & package for classes to match the VM behaviour, would minimal changes to the other access checks (field/method) provide consistent behaviour?

**Comment by ChengJin01** [comment]
I managed to change the existing code at https://github.com/ChengJin01/openj9/commit/dc52ac9ecdf0ef7f143b5385ebc35a886a036ea2 as we discussed previously to only check the protected access for members (method/field/member class).

Need to verify with the existing JSR 292 tests and JCK tests to ensure everything still works good with the changes before pulling request.
