### ISSUE TITLE
NullPointerException in com.ibm.oti.vm.BootstrapClassLoader.getPackages running tests under Gradle

### ISSUE THREAD

**Issue by bjhargrave** [eclipse/openj9#6522]
Java -version output
--------------------

```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1e based on jdk8u222-b10)
```

Summary of problem
------------------

Test execution under gradle fails with 

```
> Task :biz.aQute.bndlib.tests:test
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:59)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at java.lang.Package$1.run(Package.java:577)
	at java.lang.Package$1.run(Package.java:570)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at java.lang.Package.defineSystemPackage(Package.java:570)
	at java.lang.Package.getSystemPackages(Package.java:561)
	at java.lang.VMAccess.getSystemPackages(VMAccess.java:154)
	at com.ibm.oti.vm.BootstrapClassLoader.getPackages(BootstrapClassLoader.java:99)
	at java.lang.ClassLoader.getPackages(ClassLoader.java:1224)
	at java.lang.ClassLoader.getPackages(ClassLoader.java:1227)
	at worker.org.gradle.internal.classloader.FilteringClassLoader$RetrieveSystemPackagesClassLoader.getPackages(FilteringClassLoader.java:66)
	at worker.org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:50)
	... 2 more

> Task :biz.aQute.bndlib.tests:test FAILED
```

See the `Build` step of the`OpenJ9` job at https://dev.azure.com/bndtools/bnd/_build/results?buildId=1418&view=logs.

**Comment by tajila** [comment]
Hi @bjhargrave, I am trying to reproduce this issue on my machine. I have followed the commands used in the checkout stage of "https://dev.azure.com/bndtools/bnd/_build/results?buildId=1418&view=logs". However I fail at this command

```
git checkout --progress --force a905af91a02f901af9347c547bda52372b0b4249
fatal: reference is not a tree: a905af91a02f901af9347c547bda52372b0b4249
```
Do you know why this is happening? Is there an easier way to reproduce this issue?

**Comment by bjhargrave** [comment]
Sorry, that commit was disconnected from a branch when I abandoned that commit from a PR. I repushed it to https://github.com/bjhargrave/bnd as branch openj9-test. It is rebuilding now as https://dev.azure.com/bndtools/bnd/_build/results?buildId=1472.

**Comment by tajila** [comment]
@bjhargrave  All the test seem to pass on that run. Is it an intermittent issue? or were you seeing consistent failures before?

**Comment by bjhargrave** [comment]
Perhaps it is intermittent. It happened the first time I tried to add an OpenJ9 job to the CI build. I tried rebuilding several times today without an issue. I will note that the failing build occurred on Jul 18 which is the date of the release: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u222-b10_openj9-0.15.1. So perhaps there was some thing about the downloaded file that day which was wonky... ¯\_(ツ)_/¯

**Comment by DanHeidinga** [comment]
@bjhargrave Has this re-occurred for you?

**Comment by arxioly** [comment]
Hello! We have exactly the same error, on the same version of AdoptOpenJDK (build 1.8.0_222-b10), during integration tests execution on Jenkins. In our case, the error is floating, but occurs pretty often. One maybe not so much important note, that the application itself working on another environment with IBM Java (build 8.0.5.25).

**Comment by pshipton** [comment]
@arxioly can you please try a newer OpenJ9 release. The reported problem is with the 0.15 release, but the 0.17 release is available. There is also a 0.18 release coming next week, the Milestone 2 build for this release is https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b06_openj9-0.18.0-m2/OpenJDK8U-jdk_x64_linux_openj9_8u242b06_openj9-0.18.0-m2.tar.gz

IBM 8.0.5.25 roughly corresponds to OpenJ9 0.11

**Comment by arxioly** [comment]
@pshipton updating the version helped. Thanks a lot!

**Comment by sbradish** [comment]
@pshipton seeing the same stack trace with an IBM 8 JDK, wondering if it should be or is fixed in a later version?

```
[2020-07-07T11:24:46.980Z] OpenJ9   - 3088245
[2020-07-07T11:24:46.980Z] OMR      - eb95a4d
[2020-07-07T11:24:46.980Z] IBM      - 83517b6 -Djava.vm.name=IBM J9 VM
```

```
[2020-07-07T11:24:46.979Z] java.lang.ExceptionInInitializerError
[2020-07-07T11:24:46.979Z] 	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
[2020-07-07T11:24:46.979Z] 	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
[2020-07-07T11:24:46.979Z] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:57)
[2020-07-07T11:24:46.979Z] 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:67)
[2020-07-07T11:24:46.979Z] Caused by: java.lang.NullPointerException
[2020-07-07T11:24:46.979Z] 	at java.io.File.<init>(File.java:288)
[2020-07-07T11:24:46.979Z] 	at java.lang.Package$1.run(Package.java:578)
[2020-07-07T11:24:46.979Z] 	at java.lang.Package$1.run(Package.java:571)
[2020-07-07T11:24:46.979Z] 	at java.security.AccessController.doPrivileged(AccessController.java:678)
[2020-07-07T11:24:46.979Z] 	at java.lang.Package.defineSystemPackage(Package.java:571)
[2020-07-07T11:24:46.979Z] 	at java.lang.Package.getSystemPackages(Package.java:562)
[2020-07-07T11:24:46.979Z] 	at java.lang.VMAccess.getSystemPackages(VMAccess.java:154)
[2020-07-07T11:24:46.979Z] 	at com.ibm.oti.vm.BootstrapClassLoader.getPackages(BootstrapClassLoader.java:99)
[2020-07-07T11:24:46.979Z] 	at java.lang.ClassLoader.getPackages(ClassLoader.java:1224)
[2020-07-07T11:24:46.979Z] 	at java.lang.ClassLoader.getPackages(ClassLoader.java:1227)
[2020-07-07T11:24:46.979Z] 	at worker.org.gradle.internal.classloader.FilteringClassLoader$RetrieveSystemPackagesClassLoader.getPackages(FilteringClassLoader.java:66)
[2020-07-07T11:24:46.979Z] 	at worker.org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:50)
[2020-07-07T11:24:46.979Z] 	... 2 more
```

**Comment by pshipton** [comment]
@sbradish since we don't know what caused the problem, it's hard to say. Certainly there are newer IBM releases you can try. `OpenJ9   - 3088245` is 8.0.6.7, and the latest atm is 8.0.6.11.

**Comment by dusanboskovic** [comment]
Received a case with very similar symptoms as this issue. 
Resolution was #13033
