### ISSUE TITLE
Java 14 ant failing to compile test material 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6531]
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/52/
Example https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/20
```
19:30:44  BUILD FAILED
19:30:44  /home/jenkins/jenkins-agent/workspace/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/openjdk-tests/TestConfig/scripts/build_test.xml:74: The following error occurred while executing this line:
19:30:44  /home/jenkins/jenkins-agent/workspace/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/openjdk-tests/functional/build.xml:52: The following error occurred while executing this line:
19:30:44  /home/jenkins/jenkins-agent/workspace/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/openjdk-tests/functional/DDR_Test/build.xml:114: The following error occurred while executing this line:
19:30:44  /home/jenkins/jenkins-agent/workspace/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/openjdk-tests/functional/DDR_Test/build.xml:73: java.lang.NullPointerException
19:30:44  	at java.base/java.io.FilterOutputStream.<init>(FilterOutputStream.java:71)
19:30:44  	at org.apache.tools.zip.ZipOutputStream.<init>(ZipOutputStream.java:344)
19:30:44  	at org.apache.tools.ant.taskdefs.Zip.executeMain(Zip.java:678)
19:30:44  	at org.apache.tools.ant.taskdefs.Zip.execute(Zip.java:596)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.Target.execute(Target.java:435)
19:30:44  	at org.apache.tools.ant.Target.performTasks(Target.java:456)
19:30:44  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
19:30:44  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
19:30:44  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
19:30:44  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
19:30:44  	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
19:30:44  	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
19:30:44  	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.Target.execute(Target.java:435)
19:30:44  	at org.apache.tools.ant.Target.performTasks(Target.java:456)
19:30:44  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
19:30:44  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
19:30:44  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
19:30:44  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
19:30:44  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
19:30:44  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
19:30:44  	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:30:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.Target.execute(Target.java:435)
19:30:44  	at org.apache.tools.ant.Target.performTasks(Target.java:456)
19:30:44  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
19:30:44  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
19:30:44  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
19:30:44  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
19:30:44  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
19:30:44  	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
19:30:44  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
19:30:44  	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
19:30:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:30:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
19:30:44  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
19:30:44  	at org.apache.tools.ant.Task.perform(Task.java:348)
19:30:44  	at org.apache.tools.ant.Target.execute(Target.java:435)
19:30:44  	at org.apache.tools.ant.Target.performTasks(Target.java:456)
19:30:44  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
19:30:44  	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
19:30:44  	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
19:30:44  	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
19:30:44  	at org.apache.tools.ant.Main.runBuild(Main.java:853)
19:30:44  	at org.apache.tools.ant.Main.startAnt(Main.java:235)
19:30:44  	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
19:30:44  	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
19:30:44  
19:30:44  Total time: 5 seconds
19:30:45  makefile:82: recipe for target 'compile' failed
```

**Comment by pshipton** [comment]
@smlambert @llxia fyi
The build has been disabled since June 27 since the tests didn't pass. Obviously something has changed been then and now to cause this.

**Comment by llxia** [comment]
Ran a [grinder](https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/465/) using latest test material with JDK14 from https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDKnext_s390x_linux_OpenJDK/43/OpenJ9-JDKnext-s390x_linux-20190628-023808.tar.gz 

```
00:00:33.585  openjdk version "14-internal" 2020-03-17
00:00:33.585  OpenJDK Runtime Environment (build 14-internal+0-adhoc.****.BuildJDKnexts390xlinuxOpenJDK)
00:00:33.585  Eclipse OpenJ9 VM (build master-320fa41, JRE 14 Linux s390x-64-Bit Compressed References 20190627_43 (JIT enabled, AOT enabled)
00:00:33.585  OpenJ9   - 320fa41
00:00:33.585  OMR      - f284dd2
00:00:33.585  JCL      - 7ed78b6 based on jdk-14+3)
```

The test can be built successfully with this JDK14 (OpenJ9-JDKnext-s390x_linux-20190628-023808.tar.gz). Above issue does not seem to be a test problem.

**Comment by pshipton** [comment]
@llxia I know it used to work
i.e. https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK-Acceptance/50/
but it doesn't work with the latest Java 14 JVM. Now we need to figure out why.

**Comment by pshipton** [comment]
Might be related to http://hg.openjdk.java.net/jdk/jdk/rev/978350939943 - "Enforce null check for underlying I/O streams"

**Comment by pshipton** [comment]
There was at least one subsequent fix. Maybe it was just bad timing, I'll try another build.
http://hg.openjdk.java.net/jdk/jdk/rev/68deaa66130c - "Fix for JDK-8067801 breaks java/io/NegativeInitSize.java"

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK-Acceptance/53/

**Comment by pshipton** [comment]
It's working now, I think it was just bad timing.
