### ISSUE TITLE
ExceptionInInitializerError thrown when class specified in javax.management.builder.initial cannot be found

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#6623]
The following testcase simulates the situation where the class specified in the `javax.management.builder.initial` system property cannot be found:

```
public class PMBTest {
    public static void main(String[] args) {
        System.setProperty("javax.management.builder.initial", "NonExistentClass");
        System.out.println(java.lang.management.ManagementFactory.getPlatformMBeanServer());
    }
}
```

On Hotspot it throws a `JMRuntimeException`, which wraps a `ClassNotFoundException`:

```
Exception in thread "main" javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class NonExistentClass: java.lang.ClassNotFoundException: NonExistentClass
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:503)
        at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:539)
        at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:316)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:469)
        at PMBTest.main(PMBTest.java:4)
Caused by: java.lang.ClassNotFoundException: NonExistentClass
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:446)
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:488)
        ... 6 more
```

However, on OpenJ9 the `JMRuntimeException` is thrown from a static initializer so it gets wrapped in an `ExceptionInInitializerError` :

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:247)
        at PMBTest.main(PMBTest.java:4)
Caused by: javax.management.JMRuntimeException: Failed to load MBeanServerBuilder class NonExistentClass: java.lang.ClassNotFoundException: NonExistentClass
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:503)
        at javax.management.MBeanServerFactory.getNewMBeanServerBuilder(MBeanServerFactory.java:539)
        at javax.management.MBeanServerFactory.newMBeanServer(MBeanServerFactory.java:316)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:231)
        at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
        at java.lang.management.ManagementFactory$ServerHolder.<clinit>(ManagementFactory.java:466)
        ... 2 more
Caused by: java.lang.ClassNotFoundException: NonExistentClass
        at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
        at javax.management.MBeanServerFactory.loadBuilderClass(MBeanServerFactory.java:446)
        at javax.management.MBeanServerFactory.checkMBeanServerBuilder(MBeanServerFactory.java:488)
        ... 7 more
```

Applications can be expected to catch and handle the `JMRuntimeException`, but `Error` conditions are not expected to be caught. Obviously the real problem here is the fact that a missing class was specified, but the problem can be caught and handled gracefully on Hotspot, whereas on OpenJ9 the more severe failure mode can cause applications to fail (the application should not be expected to anticipate and catch the `Error`).

**Comment by keithc-ca** [comment]
The initialization of the server will need to be reworked to use `synchronized` instead of relying on the class loading lock.
