### ISSUE TITLE
JTReg Test failure: java/lang/StackTraceElement/PublicConstructor.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6659]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/StackTraceElement/PublicConstructor.java

Consistent test failure for JDK11-openj9 for x86_linux, windows and osx (test pass fine on hotspot for all platforms). Cause is due to an `assertEqual failure` when testing the constructor with a module attached.

Optional info
-------------
Investigation reveal the cause is the ``ToString()`` function in the ``StackTraceElement`` Class. The function doesn't take into account the class loader name and module version when converting the instance to a string. 

Digging deeper, the compiler generates its own version of the `StackTraceElement` class and produces the following `ToString`:
```
public String toString() {
	StringBuilder buf = new StringBuilder(80);
	Util.printStackTraceElement(this, source, buf, false);
	return buf.toString();
}
```
The first few lines of`Util.printStackTraceElement` looks like this:
```
public static void printStackTraceElement(StackTraceElement e, Object elementSource, Appendable buf, boolean extended) {
	final java.lang.String modName = e.getModuleName();
	if (null != modName) {
		appendTo(buf, modName);
		if (extended) {
			String mVer = e.getModuleVersion();
			if (null != mVer) {
				appendTo(buf, "@"); //$NON-NLS-1$
				appendTo(buf, mVer);
			}
		}
		appendTo(buf, "/"); //$NON-NLS-1$
	} else if (extended) {
		appendTo(buf, "app//"); //$NON-NLS-1$
	}
```
The `false` parameter in the caller function is potentially why it won't recognise the missing fields in the `ToString` but because it's within a compiler file, I can't edit it prior to runtime.

Failure output
--------------
```
PublicConstructor
15:46:02  STDERR:
15:46:02  java.lang.RuntimeException: Expected: app/jdk.module@9.0/com.acme.Widget.frobnicate(Widget.java:42) but found: jdk.module/com.acme.Widget.frobnicate(Widget.java:42)
15:46:02  	at PublicConstructor.assertEquals(PublicConstructor.java:92)
15:46:02  	at PublicConstructor.testConstructorWithModule(PublicConstructor.java:86)
15:46:02  	at PublicConstructor.main(PublicConstructor.java:36)
15:46:02  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:46:02  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:46:02  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:46:02  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:46:02  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
15:46:02  	at java.base/java.lang.Thread.run(Thread.java:831)
15:46:02  
15:46:02  JavaTest Message: Test threw exception: java.lang.RuntimeException
15:46:02  JavaTest Message: shutting down test
15:46:02  
15:46:02  
15:46:02  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected: app/jdk.module@9.0/com.acme.Widget.frobnicate(Widget.java:42) but found: jdk.module/com.acme.Widget.frobnicate(Widget.java:42)
```

**Comment by M-Davies** [comment]
Testing of `ToString` and `printStackTraceElement` with `extended` boolean's attached fails. This could be a building block for a potential fix however.

**Comment by M-Davies** [comment]
https://github.com/M-Davies/openj9-openjdk-jdk11/commit/09fe4255fbe9bfed4e043d71bad85f05efbd21d7
https://github.com/M-Davies/openj9/commit/14dcac2b8fc71cdbcd588c2945a7fd099b5403be
https://github.com/M-Davies/openj9/commit/41c1ab496201641ffc610b56ea599aaa9341c7c3

Undergoing testing for the above commits that should fix the problem

**Comment by M-Davies** [comment]
A potential fix could be to add `extended` as above and rejig `printStackTraceElement` to output the expected result, since the underlying `get()` functions work as intended

**Comment by pdbain-ibm** [comment]
I'll take a look. FYI @pdbain.

**Comment by pdbain-ibm** [comment]
Found a couple of things:
- HotSpot now adds the module version information in all cases.  
- toString() is not adding the classloader name.  

Fixed and tested.

**Comment by M-Davies** [comment]
> Fixed and tested.
Tests pass on my end too

**Comment by pshipton** [comment]
Doesn't appear the fix is merged. Is there a PR being opened with the fix?

**Comment by pdbain** [comment]
It failed the JCL regression tests.  I'm working on it.

**Comment by pdbain-ibm** [comment]
Fixed the JCL test, re-running a personal build.
