### ISSUE TITLE
JTReg Test Failure: java/lang/String/CaseInsensitiveComparator.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6665]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/String/CaseInsensitiveComparator.java

Optional info
-------------
Test fails on jdk11 with openj9, passes with hotspot. Problem seems to be with `String.CaseInsensitiveComparator` class.

Failure output
--------------
```
java.lang.Exception: Value restored from serial form does not equal original!
        at CaseInsensitiveComparator.main(CaseInsensitiveComparator.java:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by adam-thorpe** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk11-openj9.txt#L54
