### ISSUE TITLE
JTReg Test Failure: java/lang/String/CaseConvertSameInstance.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6672]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/String/CaseConvertSameInstance.java
Test Category: openjdk
Test Suite Name: jdk_lang
OS/Architecture: x86-64-windows, x86-64-linux, x86-64-osx, ...
OpenJDK Version: 11.0.4+11
Public Build SHAs:
OpenJ9 - `b09716014`
OMR - `6e99760b`
JCL - `965d0c0df3`

Optional info
-------------
Not an intermittent failure. Fails with openj9 but not hotspot.
Interesting to note that the test passed on an ubuntu system with the same parameters but failed on jenkins.

Failure output
--------------
```
java.lang.Exception: toLowerCase returned different object
  	at CaseConvertSameInstance.main(CaseConvertSameInstance.java:35)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by smlambert** [comment]
I do not see this test failing in Jenkins in the nightly runs at AdoptOpenJDK on any of the platforms you mentioned:

osx:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/14/testReport/

xlinux:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/20/testReport/

windows:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/19/testReport/

Where have you seen this test fail in Jenkins?  Either this test is not running as part of the jdk_lang target or its passing in the nightlies

**Comment by smlambert** [comment]
I have created a Grinder to reproduce the failure:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1842/testReport/

since its not failing in nightlies, it must not be running as part of the jdk_lang target
we will have to look at why

**Comment by adam-thorpe** [comment]
These tests were excluded from the JTReg suite, so am I right in saying they would not appear when you run a test suite? Which is why they do not appear unless specified?
Issue tracking this: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585

**Comment by smlambert** [comment]
That would explain it, and also explain what your mission appears to be (rerunning all the excluded tests in the list that were excluded under that generic issue 585, [exclusion for this test](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk11-openj9.txt#L53)), thanks @adam-thorpe
