### ISSUE TITLE
JTReg Failure: java/lang/System/Logger/custom/CustomLoggerTest.java and java/lang/System/Logger/default/DefaultLoggerTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6674]
Failure link
------------
CustomLoggerTest: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1846/
DefaultLoggerTest: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1848/
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/System/Logger/custom/CustomLoggerTest.java
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/System/Logger/default/DefaultLoggerTest.java
Test Category: openjdk
Test Suite: java_lang
OS/Architecture: x86-64-windows, x86-64-linux, x86-64-osx, ...
OpenJDK Version: 11.0.4+11
Public Build SHAs:
OpenJ9 - `85b0693e8`
OMR - `6e99760b`
JCL - `965d0c0df3`

Optional info
-------------
intermittent failure : no
regression or new test:  regression
These tests are both excluded jtreg tests, failing on openj9 builds of jdk11 across at least these 3 OS's. Both pass on hotspot builds. They seem to relate to the same problem which is why I have linked them in the same issue. Console outputs below.

Failure output
--------------
CustomLoggerTest:
*** With Security Manager, without permissions
`System.getLogger("foo"): jdk.internal.logger.LazyLoggers$JdkLazyLogger@22e01eb3`
CustomLoggerTest.java:314 - `Logger appLogger2 = System.getLogger("foo", loggerBundle);`
```
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "loggerFinder")
        at java.base/java.security.AccessController.throwACE(AccessController.java:176)
        at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.lang.System$LoggerFinder.verifyPermissions(System.java:1183)
        at java.base/java.lang.System$LoggerFinder.getLoggerFinder(System.java:1170)
        at java.base/java.lang.System.getLogger(System.java:1114)
        at CustomLoggerTest.test(CustomLoggerTest.java:382)
        at CustomLoggerTest.lambda$main$0(CustomLoggerTest.java:314)
        at CustomLoggerTest$$Lambda$6.00000000940AFE60.accept(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at CustomLoggerTest.main(CustomLoggerTest.java:304)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

DefaultLoggerTest:
*** With Security Manager, without permissions
`System.getLogger("foo"): jdk.internal.logger.LazyLoggers$JdkLazyLogger@5968a779`
DefaultLoggerTest.java:522 - `sink = java.util.logging.Logger.getLogger("foo");`
```
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "loggerFinder")
        at java.base/java.security.AccessController.throwACE(AccessController.java:176)
        at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.lang.System$LoggerFinder.verifyPermissions(System.java:1183)
        at java.base/java.lang.System$LoggerFinder.getLoggerFinder(System.java:1170)
        at java.base/java.lang.System.getLogger(System.java:1114)
        at DefaultLoggerTest.test(DefaultLoggerTest.java:522)
        at DefaultLoggerTest.test(DefaultLoggerTest.java:485)
        at DefaultLoggerTest.lambda$main$0(DefaultLoggerTest.java:438)
        at DefaultLoggerTest$$Lambda$15.0000000008015B60.accept(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at DefaultLoggerTest.main(DefaultLoggerTest.java:428)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by adam-thorpe** [comment]
The following tests also are affected by the same problem:
`java/lang/System/LoggerFinder/internal/BaseDefaultLoggerFinderTest/BaseDefaultLoggerFinderTest.java`
`java/lang/System/LoggerFinder/internal/BaseLoggerBridgeTest/BaseLoggerBridgeTest.java`
`java/lang/System/LoggerFinder/internal/LoggerBridgeTest/LoggerBridgeTest.java`
`java/lang/System/LoggerFinder/internal/LoggerFinderLoaderTest/LoggerFinderLoaderTest.java`
`java/lang/System/LoggerFinder/BaseLoggerFinderTest/BaseLoggerFinderTest.java`
`java/lang/System/LoggerFinder/DefaultLoggerFinderTest/DefaultLoggerFinderTest.java`
`java/lang/System/LoggerFinder/jdk/DefaultLoggerBridgeTest/DefaultLoggerBridgeTest.java`

**Comment by adam-thorpe** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk11-openj9.txt
Lines 61-64, 66-69, 71

**Comment by JasonFengJ9** [comment]
The AccessControlException was thrown by https://github.com/eclipse/openj9/blob/5dd23af8483d4671fe6ad2ff372bcf0e6fd74891/jcl/src/java.base/share/classes/java/lang/System.java#L1368.

**Comment by JasonFengJ9** [comment]
> regression or new test: regression

@adam-thorpe can you clarify if this is a regression (there is no recent change in this area)?

**Comment by JasonFengJ9** [comment]
`RI` does throw `AccessControlException` for `LoggerFinder.getLoggerFinder()`. As per [1], `System.getLogger​(name, bundle)` should not throw `AccessControlException`.
It appears an `AccessController.doPrivileged()` is missing here.

[1] https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/System.html#getLogger(java.lang.String,java.util.ResourceBundle)

**Comment by adam-thorpe** [comment]
As far as I am aware, these are all regression tests, which have been excluded from the test suites since at least September 2018, if not longer, which may be why there haven't been any recent changes.

**Comment by JasonFengJ9** [comment]
> As far as I am aware, these are all regression tests, which have been excluded from the test suites since at least September 2018, if not longer, which may be why there haven't been any recent changes.

I see the problem now, will submit a fix later.
