### ISSUE TITLE
JTReg Test Failure: java/lang/StackWalker/Basic.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6698]
Failure link
------------

- Test: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/StackWalker/Basic.java#L1
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1868/
- Test Catergory: openjdk
- Fails on x86-64-windows, x86-64-linux, x86-64-osx (passes on hotspot)
Build SHA's
- Version: 11.0.4+11
- OpenJ9: 85b0693e8
- OMR: 6e99760b
- JCL: 965d0c0df3 based on jdk-11.0.4+11

Optional info
-------------

- Part of the Excluded jdk11 openj9 JTReg tests: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Regression Test
- `testWalkFromConstructor()` expects 7 items in each list when only 3 are found. Potentially due to a `null` return from the `found` list.

Failure output (captured from console output)
---------------------------------------------
```
STDOUT:
15:26:27  [TestNG] Running:
15:26:27    java/lang/StackWalker/Basic.java
15:26:27  
15:26:27  depth=12 estimate=4 expected=12 walked=12
15:26:27  depth=12 estimate=8 expected=12 walked=12
15:26:27  depth=12 estimate=12 expected=12 walked=12
15:26:27  test Basic.test([I@1e159a4e, [I@7e38b9e5): success
15:26:27  depth=18 estimate=8 expected=16 walked=16
15:26:27  depth=18 estimate=16 expected=16 walked=16
15:26:27  depth=18 estimate=20 expected=16 walked=16
15:26:27  test Basic.test([I@835099ae, [I@5ddeecde): success
15:26:27  depth=32 estimate=16 expected=16 walked=16
15:26:27  depth=32 estimate=32 expected=16 walked=16
15:26:27  depth=32 estimate=64 expected=16 walked=16
15:26:27  test Basic.test([I@13e5d954, [I@9549e962): success
15:26:27  Basic$StackBuilder.m4 (Ljava/lang/Object;)V
15:26:27  Basic$StackBuilder.m3 ()I
15:26:27  Basic$StackBuilder.m2 ()Ljava/util/List;
15:26:27  Basic$StackBuilder.m1 ()V
15:26:27  Basic$StackBuilder.m4 (Ljava/lang/Object;)V
15:26:27  Basic$StackBuilder.m3 ()I
15:26:27  Basic$StackBuilder.m2 ()Ljava/util/List;
15:26:27  Basic$StackBuilder.m1 ()V
15:26:27  Basic$StackBuilder.m4 (Ljava/lang/Object;)V
15:26:27  Basic$StackBuilder.m3 ()I
15:26:27  Basic$StackBuilder.m2 ()Ljava/util/List;
15:26:27  Basic$StackBuilder.m1 ()V
15:26:27  test Basic.testMethodSignature(): success
15:26:27  testWalkFromConstructor:
15:26:27      java.lang.StackWalker$StackFrameImpl@7efe89a
15:26:27      java.lang.StackWalker$StackFrameImpl@528dd9e7
15:26:27      java.lang.StackWalker$StackFrameImpl@8c076580
15:26:27      java.lang.StackWalker$StackFrameImpl@6b2d5183
15:26:27      java.lang.StackWalker$StackFrameImpl@9d0256
15:26:27      java.lang.StackWalker$StackFrameImpl@ca23ee09
15:26:27      java.lang.StackWalker$StackFrameImpl@9392bc1a
15:26:27  test Basic.testWalkFromConstructor(): failure
15:26:27  java.lang.AssertionError: lists don't have the same size expected [7] but found [3]
15:26:27  	at org.testng.Assert.fail(Assert.java:94)
15:26:27  	at org.testng.Assert.failNotEquals(Assert.java:496)
15:26:27  	at org.testng.Assert.assertEquals(Assert.java:125)
15:26:27  	at org.testng.Assert.assertEquals(Assert.java:372)
15:26:27  	at org.testng.Assert.assertEquals(Assert.java:539)
15:26:27  	at org.testng.Assert.assertEquals(Assert.java:516)
15:26:27  	at Basic.testWalkFromConstructor(Basic.java:72)
15:26:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:26:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:26:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:26:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:26:27  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
15:26:27  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
15:26:27  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
15:26:27  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
15:26:27  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
15:26:27  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
15:26:27  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
15:26:27  	at org.testng.TestRunner.run(TestRunner.java:623)
15:26:27  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
15:26:27  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
15:26:27  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
15:26:27  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
15:26:27  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
15:26:27  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
15:26:27  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
15:26:27  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
15:26:27  	at org.testng.TestNG.run(TestNG.java:1018)
15:26:27  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
15:26:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:26:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:26:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:26:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:26:27  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
15:26:27  	at java.base/java.lang.Thread.run(Thread.java:831)
```
- Core dump files: https://na.artifactory.swg-devops.com/artifactory/sys-rt-generic-local/hyc-runtimes-jenkins.swg-devops.com/Grinder_Advanced/451/openjdk_test_output.tar.gz

**Comment by M-Davies** [comment]
Fails for the same reason as https://github.com/eclipse/openj9/issues/6724

**Comment by M-Davies** [comment]
Perm excluding due to linked issue comment https://github.com/eclipse/openj9/issues/7124#issuecomment-565446631
