### ISSUE TITLE
JTReg Test Failure: java/lang/annotation/AnnotationsInheritanceOrderRedefinitionTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6700]
Failure link
------------
- Test: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/annotation/AnnotationsInheritanceOrderRedefinitionTest.java
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1869
- Test Category: openjdk
- Test Suite Name: jdk_lang
- OS/Architecture: x86-64-windows, x86-64-linux, x86-64-osx, ...
- OpenJDK Version: 11.0.4+11
- Public Build SHAs:
- OpenJ9 - `4baf3d7e4`
- OMR - `6e99760b`
- JCL - `965d0c0df3`

Optional info
-------------
- Intermittent failure: No
- Regression or new test: Regression
- Part of the excluded jdk11 openj9 JTReg Tests: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Error is thrown because the field `classRedefinedCount` cannot be found in `Class`

Failure output (captured from console output)
---------------------------------------------
```
java.lang.Error: java.lang.NoSuchFieldException: classRedefinedCount
        at AnnotationsInheritanceOrderRedefinitionTest.<clinit>(AnnotationsInheritanceOrderRedefinitionTest.java:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NoSuchFieldException: classRedefinedCount
        at java.base/java.lang.Class.getDeclaredField(Class.java:896)
        at AnnotationsInheritanceOrderRedefinitionTest.<clinit>(AnnotationsInheritanceOrderRedefinitionTest.java:197)
        ... 6 more
```

**Comment by M-Davies** [comment]
Added to permanent exclusions list. This can be safely closed for now
