### ISSUE TITLE
JTReg Test Failure: java/lang/annotation/loaderLeak/Main.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6701]
Failure link
------------
- Test: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/annotation/loaderLeak/Main.java
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1870
- Test Category: openjdk
- Test Suite Name: jdk_lang
- OS/Architecture: x86-64-windows, x86-64-linux, x86-64-osx, ...
- OpenJDK Version: 11.0.4+11
- Public Build SHAs:
- OpenJ9 - `4baf3d7e4`
- OMR - `6e99760b`
- JCL - `965d0c0df3`

Optional info
-------------
- Intermittent failure: No
- Regression or new test: Regression 
- Part of the excluded jdk11 openj9 JTReg Tests: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585

Failure output (captured from console output)
---------------------------------------------
```
Note: Main.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Main.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Exception in thread "main" java.lang.AssertionError
        at Main.doTest(Main.java:56)
        at Main.main(Main.java:41)
```

**Comment by pdbain-ibm** [comment]
Reproduced locally.  Investigating...

**Comment by pdbain-ibm** [comment]
This test is invalid.  
```
        ClassLoader loader = new SimpleClassLoader();
        WeakReference<Class<?>> c = new WeakReference(loader.loadClass("C"));   <<< line 49
        if (c.get() == null) throw new AssertionError();
        if (c.get().getClassLoader() != loader) throw new AssertionError();
        if (readAnn) System.out.println(c.get().getAnnotations()[0]);
        if (c.get() == null) throw new AssertionError();
        System.gc();
        System.gc();
        if (c.get() == null) throw new AssertionError(); <<< Failing line 56
```

Line 49 creates a weak reference to the `Class` object for `C`.  It then runs two GCs, which clear the weak reference to the `Class` object because there are no strong references to the object, as designed.
