### ISSUE TITLE
JTReg Failure: java/lang/StackWalker/LocalsAndOperands.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6704]
Failure link
------------

- Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/965d0c0df359f3da224b865701bbcc044b7104c2/test/jdk/java/lang/StackWalker/LocalsAndOperands.java#L1 is consistantly failing on openj9 (hotspot is fine)
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/83/
- Category: openjdk
- Target: jdk_custom
- OS/architecture: openjdk_x86-64_linux, openjdk_x86-64_windows
- Version: build 11.0.4+11-201908041810
- OpenJ9: 4baf3d7e4
- OMR: 6e99760b
- JCL: 965d0c0df3 based on jdk-11.0.4+11)

Optional info
-------------
- Part of the excluded jdk11 openj9 JTReg Tests: [AdoptOpenJDK/openjdk-tests#585](https://github.com/AdoptOpenJDK/openjdk-tests/issues/585)
- Error is thrown by a `ClassNotFoundException` at #77. Investigation revealed that the underlying class https://github.com/eclipse/openj9/blob/5dd23af8483d4671fe6ad2ff372bcf0e6fd74891/jcl/src/java.base/share/classes/java/lang/LiveStackFrame.java#L1 is empty, which could be the cause of `LocalsAndOperands: null`. 

Failure output (captured from console output)
---------------------------------------------
```
STDOUT:
13:57:46  STDERR:
13:57:46  org.testng.TestNGException: 
13:57:46  An error occurred while instantiating class LocalsAndOperands: null
13:57:46  	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:394)
13:57:46  	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
13:57:46  	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
13:57:46  	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
13:57:46  	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
13:57:46  	at org.testng.TestRunner.initMethods(TestRunner.java:415)
13:57:46  	at org.testng.TestRunner.init(TestRunner.java:241)
13:57:46  	at org.testng.TestRunner.init(TestRunner.java:211)
13:57:46  	at org.testng.TestRunner.<init>(TestRunner.java:158)
13:57:46  	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:546)
13:57:46  	at org.testng.SuiteRunner.init(SuiteRunner.java:159)
13:57:46  	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
13:57:46  	at org.testng.TestNG.createSuiteRunner(TestNG.java:1260)
13:57:46  	at org.testng.TestNG.createSuiteRunners(TestNG.java:1247)
13:57:46  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
13:57:46  	at org.testng.TestNG.run(TestNG.java:1018)
13:57:46  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:57:46  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:57:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:57:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:57:46  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:57:46  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:57:46  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:57:46  	at java.base/java.lang.Thread.run(Thread.java:831)
13:57:46  Caused by: java.lang.ExceptionInInitializerError
13:57:46  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
13:57:46  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
13:57:46  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
13:57:46  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
13:57:46  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
13:57:46  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
13:57:46  	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
13:57:46  	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
13:57:46  	... 23 more
13:57:46  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: java.lang.LiveStackFrame
13:57:46  	at LocalsAndOperands.<clinit>(LocalsAndOperands.java:116)
13:57:46  	... 29 more
13:57:46  Caused by: java.lang.ClassNotFoundException: java.lang.LiveStackFrame
13:57:46  	at java.base/java.lang.Class.forNameImpl(Native Method)
13:57:46  	at java.base/java.lang.Class.forName(Class.java:340)
13:57:46  	at LocalsAndOperands.<clinit>(LocalsAndOperands.java:77)
13:57:46  	... 29 more
13:57:46  
13:57:46  JavaTest Message: Test threw exception: org.testng.TestNGException: 
13:57:46  An error occurred while instantiating class LocalsAndOperands: null
13:57:46  JavaTest Message: shutting down test
13:57:46  
13:57:46  STATUS:Failed.`main' threw exception: org.testng.TestNGException: An error occurred while instantiating class LocalsAndOperands: null
```

**Comment by pdbain-ibm** [comment]
`java.lang.ClassNotFoundException: java.lang.LiveStackFrame`

Note that `LiveStackFrame` is a proprietary class for OpenJDK and is not part of the documented JCL. Please close this issue and raise an issue against the original test.

**Comment by M-Davies** [comment]
^^ Currently unsuitable for OpenJ9
