### ISSUE TITLE
Unhandled Exception: Segmentation Error

### ISSUE THREAD

**Issue by olendvcook** [eclipse/openj9#6741]
Java -version output
--------------------

```1CIJAVAVERSION JRE 12 Windows 10 amd64-64 (build 12+33)
1CIVMVERSION   20190320_32
1CIJ9VMTAG     openj9-0.13.0
1CIJ9VMVERSION caeb51f87
1CIJITVERSION  caeb51f87
1CIOMRVERSION  33a33ff2_CMPRSS
1CIJCLVERSION  419f571019 based on jdk-12+33
1CIJITMODES    JIT enabled, AOT enabled, FSD disabled, HCR enabled
1CIRUNNINGAS   Running as a standalone JVM
1CIVMIDLESTATE VM Idle State: ACTIVE
1CICONTINFO    Running in container : FALSE
1CICGRPINFO    JVM support for cgroups enabled : FALSE
1CISTARTTIME   JVM start time: 2019/08/11 at 20:51:51:081
1CISTARTNANO   JVM start nanotime: 15520594236300
1CIPROCESSID   Process ID: 6240 (0x1860)```

Summary of problem
------------------

Unhandled Exception: Segmentation error while running a Liberty FAT Test

Diagnostic files
----------------
Attaching

**Comment by olendvcook** [comment]
[javacore.20190811.205155.6240.0002.txt](https://github.com/eclipse/openj9/files/3503422/javacore.20190811.205155.6240.0002.txt)

[stderr.txt](https://github.com/eclipse/openj9/files/3503423/stderr.txt)

**Comment by olendvcook** [comment]
javacore and snap in IBM only box link: https://ibm.box.com/s/ojr623lpqmo188ff3smx2v05gxtsxi4n

**Comment by kgibm** [comment]
Proximate crash in `jdk/crypto/jniprovider/NativeCrypto.DigestUpdate(Native Method)` while closing a socket during finalization:

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "Finalizer thread" J9VMThread:0x000000000014B100, omrthread_t:0x000001AD70AC07A8, java/lang/Thread:0x00000000C00BE670, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xC, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x514, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x404000a1)
3XMCPUTIME               CPU usage total: 0.125000000 secs, user: 0.046875000 secs, system: 0.078125000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=8864 (0x22A0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/crypto/jniprovider/NativeCrypto.DigestUpdate(Native Method)
4XESTACKTRACE                at sun/security/provider/NativeDigest.engineUpdate(NativeDigest.java:107)
5XESTACKTRACE                   (entered lock: sun/security/provider/NativeSHA@0x00000000FFF082A8, entry count: 1)
4XESTACKTRACE                at java/security/MessageDigest$Delegate.engineUpdate(MessageDigest.java:613)
4XESTACKTRACE                at java/security/MessageDigest.update(MessageDigest.java:355)
4XESTACKTRACE                at com/sun/crypto/provider/HmacCore.engineUpdate(HmacCore.java:180)
4XESTACKTRACE                at javax/crypto/Mac.update(Mac.java:505)
4XESTACKTRACE                at sun/security/ssl/Authenticator$MacImpl.compute(Authenticator.java:510)
4XESTACKTRACE                at sun/security/ssl/Authenticator$TLS10Mac.compute(Authenticator.java:581)
4XESTACKTRACE                at sun/security/ssl/Authenticator$MAC.compute(Authenticator.java:444)
4XESTACKTRACE                at sun/security/ssl/SSLCipher.addMac(SSLCipher.java:2658)
4XESTACKTRACE                at sun/security/ssl/SSLCipher$T10BlockWriteCipherGenerator$BlockWriteCipher.encrypt(SSLCipher.java:1189)
4XESTACKTRACE                at sun/security/ssl/OutputRecord.t10Encrypt(OutputRecord.java:462)
4XESTACKTRACE                at sun/security/ssl/OutputRecord.encrypt(OutputRecord.java:394)
4XESTACKTRACE                at sun/security/ssl/SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:78)
5XESTACKTRACE                   (entered lock: sun/security/ssl/SSLSocketOutputRecord@0x00000000FFF08BB8, entry count: 2)
4XESTACKTRACE                at sun/security/ssl/TransportContext.warning(TransportContext.java:242)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:553)
5XESTACKTRACE                   (entered lock: sun/security/ssl/SSLSocketOutputRecord@0x00000000FFF08BB8, entry count: 1)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.close(SSLSocketImpl.java:479)
4XESTACKTRACE                at sun/security/ssl/BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:275)
4XESTACKTRACE                at java/lang/J9VMInternals.runFinalize(J9VMInternals.java:328)
```

**Comment by keithc-ca** [comment]
This may be the same issue as #4530; the workaround suggested there is to disable the openssl digest support by using `-Djdk.nativeDigest=false`.

**Comment by pshipton** [comment]
@ashbm5

**Comment by ashbm5** [comment]
looks like the same issue as #4530 and `-Djdk.nativeDigest=false` should disable the function.

The actual fix was delivered for Java11 and Java8 but not yet for Java12. If possible, you could try using latest nightly build of Java11 and see if that fixes the problem.

**Comment by ashbm5** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/69 created to enable Message Digest and fix issue.
