### ISSUE TITLE
ub16x64j97 : Connection refused to host: 192.168.10.182

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#6758]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly/111/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
STF 00:25:12.995 - +------ Step 3 - Wait for processes to complete
STF 00:25:12.996 - | Wait for processes to meet expectations
STF 00:25:12.996 - |   Processes: [LT1, CL1]
STF 00:25:12.996 - |
STF 00:25:12.996 - Monitoring processes: CL1 LT1
CL1 j> 2019/08/16 00:25:13.402 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi

CL1 stderr java.rmi.ConnectException: Connection refused to host: 192.168.10.182; nested exception is: 
CL1 stderr 	java.net.ConnectException: Connection refused (Connection refused)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2105)
CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getServerConnection(ServerConnector.java:115)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:62)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:62)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:92)
CL1 stderr Caused by: java.net.ConnectException: Connection refused (Connection refused)
CL1 stderr 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
CL1 stderr 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
CL1 stderr 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
CL1 stderr 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:591)
CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:540)
CL1 stderr 	at java.base/java.net.Socket.<init>(Socket.java:436)
CL1 stderr 	at java.base/java.net.Socket.<init>(Socket.java:213)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
CL1 stderr 	... 12 more
CL1 stderr Exception in thread "main" java.lang.NullPointerException
CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:651)
CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:611)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:117)
CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
STF 00:30:16.297 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
STF 00:30:16.297 - Monitoring Report Summary:
STF 00:30:16.298 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
STF 00:30:16.298 -   o Process LT1 is still running as expected
STF 00:30:16.298 - Killing processes: CL1 LT1
STF 00:30:16.298 -   o Process CL1 is not running
STF 00:30:27.301 -   o Process LT1 killed
**FAILED** at step 3 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15659259053282/TestJlmRemoteClassNoAuth_0/20190816-002508-TestJlmRemoteClassNoAuth/
```

**Comment by pshipton** [comment]
I assume 192.168.10.182 is ub16x64j97. May be related to #6742

@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
182 is ub16x64j91
ub16x64j97 is 195

**Comment by AdamBrousseau** [comment]
`/etc/hosts` on `#7` had ip from `#1`
Updated.
