### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/DefineClassTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6800]
Failure link
------------

- Test: https://github.com/M-Davies/openj9-openjdk-jdk11/blob/dcaed50202aba11658bb827c255ef3c393d4b1ea/test/jdk/java/lang/invoke/DefineClassTest.java#L1 is consistantly failing for JDK11-openj9 (Hotspot unaffected)
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows 
- openjdk version "11.0.4" 2019-07-16
- OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190806_306 (JIT enabled, AOT enabled)
- OpenJ9   - 0f66c6431
- OMR      - ec782f26
- JCL      - fa49279450 based on jdk-11.0.4+11)

Optional info
-------------
- intermittent failure (no): 
- New test
- Part of https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- `lookup.findClass(cn)` has no access to `java.lang`

Failure output (captured from console output)
---------------------------------------------
```
test test.DefineClassTest.testAccess(): success
test test.DefineClassTest.testBootLoader(): failure
java.lang.IllegalAccessException: Module 'java.base' no access to: package 'java.lang' because module 'java.base' can't read module 'unnamed module @a556596f'
	at java.base/java.lang.invoke.MethodHandles$Lookup.throwIllegalAccessException(MethodHandles.java:715)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassModuleVisibility(MethodHandles.java:698)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:477)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:359)
	at java.base/java.lang.invoke.MethodHandles$Lookup.accessClass(MethodHandles.java:1583)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:1566)
	at test.DefineClassTest.testDiscoverable(DefineClassTest.java:73)
	at test.DefineClassTest.testBootLoader(DefineClassTest.java:221)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)
test test.DefineClassTest.testDefineClass(): success
test test.DefineClassTest.testInitializerNotRun(): success
test test.DefineClassTest.testNoPackageAccess(): success
test test.DefineClassTest.testNull(): success
test test.DefineClassTest.testTruncatedClassFile(): success
test test.DefineClassTest.testTwoProtectionDomains(): success
test test.DefineClassTest.testWrongPackage(): success

===============================================
java/lang/invoke/DefineClassTest.java
Total tests run: 9, Failures: 1, Skips: 0
===============================================

----------System.err:(14/858)----------
java.lang.Exception: failures: 1
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)

JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
JavaTest Message: shutting down test
```
[Archive.zip](https://github.com/eclipse/openj9/files/3525779/Archive.zip)

**Comment by M-Davies** [comment]
Recently failing job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/224/

**Comment by M-Davies** [comment]
^^ Trimmed down unrelated test results in Archive.zip

**Comment by M-Davies** [comment]
Potentially an unsuitable test for openj9

**Comment by M-Davies** [comment]
Will close and update perm excludes based off of the previous hypothesis
