### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/DropLookupModeTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6802]
Failure link
------------
- Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/4d41e016d25f4fd55a044c9e6556dba844f164a3/test/jdk/java/lang/invoke/DropLookupModeTest.java#L1 is consistantly failing for JDK13-openj9 (Hotspot unaffected)
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190806_306 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

Optional info
-------------

- intermittent failure (no): 
- New test
- Part of https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- 2 failures out of 7 (both caused by the same instance `DropLookupModeTest@6eeec051`. `Modifier` is not used when setting the bit flag of `PACKAGE` access in the Lookup factory (`PACKAGE` is used in the failing test). See for details: https://github.com/eclipse/openj9/blob/4df4d440243b69e46db1109575f2bc20e7de9fd5/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L141
- OpenJ9 is potentially missing `PACKAGE` from `Modifier` class?

Failure output (captured from console output)
---------------------------------------------
```
[TestNG] Running:
  java/lang/invoke/DropLookupModeTest.java

test DropLookupModeTest.testBadInput(0, null): success
test DropLookupModeTest.testBadInput(10, null): failure
org.testng.TestException: 
Method DropLookupModeTest.testBadInput(java.lang.Integer, java.lang.Object)[pri:0, instance:DropLookupModeTest@6eeec051] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1384)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)
test DropLookupModeTest.testBadInput(2147483647, null): failure
org.testng.TestException: 
Method DropLookupModeTest.testBadInput(java.lang.Integer, java.lang.Object)[pri:0, instance:DropLookupModeTest@6eeec051] should have thrown an exception of type class java.lang.IllegalArgumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1384)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:831)
test DropLookupModeTest.testBadInput(-2147483648, null): success
test DropLookupModeTest.testBasic(): success
test DropLookupModeTest.testPublicLookup(): success
test DropLookupModeTest.testReducingAccess(): success

===============================================
java/lang/invoke/DropLookupModeTest.java
Total tests run: 7, Failures: 2, Skips: 0
===============================================
```
[Archive.zip](https://github.com/eclipse/openj9/files/3525848/Archive.zip)

**Comment by fengxue-IS** [comment]
I'l look into this

**Comment by M-Davies** [comment]
Test passes for JDK11, reincluded. Now failing for JDK13 (error message is the same). @fengxue-IS would it be possible to reopen this issue and rebrand it as JDK13 only now?

**Comment by M-Davies** [comment]
Link to recent job: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/779/

Rebuild with this link if the above has expired: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/invoke/DropLookupModeTest.java&TARGET=jdk_custom_0

**Comment by fengxue-IS** [comment]
I don't think the merged changes are included in the 0.17-m2 release.

@DanHeidinga @pshipton should I port this fix to 0.17?

**Comment by DanHeidinga** [comment]
0.17.0 is complete and it's too late to add new changes to it.  This is likely due to removing the exclude which applies globally, not just to the 0.17 release

**Comment by pshipton** [comment]
This is re-opened due to https://github.com/eclipse/openj9/issues/6802#issuecomment-541011568, not because it fails in the 0.17 release builds.

**Comment by pshipton** [comment]
If it might be a factor, we can re-test once the 13.0.1 openjdk changes are merged in, likely tomorrow.

**Comment by fengxue-IS** [comment]
The SDK used in the failed grinder is 
```
06:24:29  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0-m2, JRE 13 Linux amd64-64-Bit Compressed References 20191009_90 (JIT enabled, AOT enabled)
06:24:29  OpenJ9   - 23b8b11b4
06:24:29  OMR      - 20db4fbc
06:24:29  JCL      - 2cb22d51d9 based on jdk-13+33)
```
which doesn't include the merged PR changes.
@M-Davies can you re-test this with VM based off the current master branch

**Comment by M-Davies** [comment]
Current master branch passes for JDK13. @fengxue-IS @pshipton can you react with a 👍 if you're happy for me to unexclude the test?
