### ISSUE TITLE
TestJcmd_0 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6816]
All extended testing.
```
FAILED: testJcmdHelps
java.lang.AssertionError: Help text corrupt: [Usage : jcmd <vmid> <arguments>, ,    -J : supply arguments to the Java VM running jcmd,    -l : list JVM processes on the local machine,    -h : print this help message, ,    <vmid> : Attach API VM ID as shown in jps or other Attach API-based tools, ,    arguments:,       help : print the list of diagnostic commands,       help <command> : print help for the specific command,       <command> [command arguments] : command from the list returned by "help", , list JVM processes on the local machine. Default behavior when no options are specified., , NOTE: this utility may significantly affect the performance of the target JVM.,     The available diagnostic commands are determined by,     the target VM and may vary between VMs.] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.openj9.test.attachAPI.TestJcmd.testJcmdHelps(TestJcmd.java:87)
```

**Comment by pshipton** [comment]
Will be fixed by https://github.com/eclipse/openj9/pull/6790
