### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/InvokeWithArgumentsTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6964]
Failure link
------------

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/259a016054953a431bbcb198848372c7830116ad/test/jdk/java/lang/invoke/InvokeWithArgumentsTest.java#L1 consistantly fails for JDK11-openj9 (hotspot unaffected)
- test category, openjdk
- OS/architecture, all platforms 
```
16:41:40  openjdk version "11.0.5" 2019-10-15
16:41:40  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+4-201909021901)
16:41:40  Eclipse OpenJ9 VM AdoptOpenJDK (build master-e2e21457f, JRE 11 Linux amd64-64-Bit Compressed References 20190902_324 (JIT enabled, AOT enabled)
16:41:40  OpenJ9   - e2e21457f
16:41:40  OMR      - 5628a974
16:41:40  JCL      - 259a016054 based on jdk-11.0.5+4)
```
- NOTE: A lot of `java.lang.invoke` seems to be unsuitable for openj9

Failure output (captured from console output)
---------------------------------------------
```
STDOUT:
16:21:11  [TestNG] Running:
16:21:11    java/lang/invoke/InvokeWithArgumentsTest.java
16:21:11  
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testArity(): success
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testArrayNoPassThrough(): failure
16:21:11  java.lang.ArrayStoreException
16:21:11  	at java.base/java.lang.invoke.VarargsCollectorHandle.invokeWithArguments(VarargsCollectorHandle.java:122)
16:21:11  	at test.java.lang.invoke.InvokeWithArgumentsTest.testArrayNoPassThrough(InvokeWithArgumentsTest.java:75)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:21:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:21:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:21:11  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
16:21:11  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
16:21:11  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
16:21:11  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
16:21:11  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
16:21:11  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
16:21:11  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
16:21:11  	at org.testng.TestRunner.run(TestRunner.java:623)
16:21:11  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
16:21:11  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
16:21:11  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
16:21:11  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
16:21:11  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
16:21:11  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
16:21:11  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
16:21:11  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
16:21:11  	at org.testng.TestNG.run(TestNG.java:1018)
16:21:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:21:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:21:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:21:11  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:21:11  	at java.base/java.lang.Thread.run(Thread.java:831)
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testArrayPack(): success
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testPrimitiveArrayWithNull(): success
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testPrimitiveArrayWithRef(): success
16:21:11  test test.java.lang.invoke.InvokeWithArgumentsTest.testRefArrayWithCast(): success
16:21:11  
16:21:11  ===============================================
16:21:11  java/lang/invoke/InvokeWithArgumentsTest.java
16:21:11  Total tests run: 6, Failures: 1, Skips: 0
16:21:11  ===============================================
16:21:11  
16:21:11  STDERR:
16:21:11  java.lang.Exception: failures: 1
16:21:11  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:21:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:21:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:21:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:21:11  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:21:11  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by M-Davies** [comment]
Test appears to be passing now
