### ISSUE TITLE
cent6-x64-3 running really slow

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6983]
There is a compile running on  cent6-x64-3 since 9am this morning, proceeding very slowly. There must be other stuff left running on the machine and it needs to be cleaned up.

https://ci.eclipse.org/openj9/job/Build_JDK13_x86-64_linux_xl_Release/1

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
```
jenkins  13078     1  0 Sep04 ?        00:12:23 /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -XX:StartAsJITServer
```
I believe this _should_ have been killed in the test tear down. cc @llxia 
It would have also been killed by the sanity job but it's currently disabled.

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/230/console
```
14:22:13  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
14:22:13  ...
14:22:13  
15:32:47  Cannot contact cent6-x64-3: java.lang.InterruptedException
19:12:34  Sending interrupt signal to process
Click here to forcibly terminate running steps
19:12:54  After 20s process did not stop
[Pipeline] sh
19:13:31  ++ uname
19:13:31  + '[' Linux = AIX ']'
19:13:31  ++ uname
19:13:31  + '[' Linux = SunOS ']'
19:13:31  + MAKE=make
19:13:31  + make -f ./openjdk-tests/TestConfig/testEnv.mk testEnvTeardown
19:13:31  pkill -9 -xf "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-imagebinjava -XX:StartAsJITServer"; true
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Unknown Source)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:956)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1086)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.stop(FileMonitoringTask.java:345)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.stop(DurableTaskStep.java:512)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:308)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1151)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$6.onSuccess(CpsFlowExecution.java:1140)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:907)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: ABORTED
```

**Comment by AdamBrousseau** [comment]
Is it odd that there's a few `/` missing from that pkill command path
```
openjdkbinary/j2sdk-imagebinjava -XX:StartAsJITServer
```

**Comment by llxia** [comment]
It looks like `$(D)` does not work.
https://github.com/eclipse/openj9/blob/96702a0bb3fbd71b64dd3a45b38693f5db4978d1/test/TestConfig/testEnv.mk#L33

We will fix it.
