### ISSUE TITLE
extended.functional_x86-64_mac TestAttachErrorHandling_0 FAILED: test_startupShutdownRobustness

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7010]
Failure link
------------

Public link to the failing test

https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/34/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
FAILED: test_startupShutdownRobustness
java.lang.AssertionError: target 72803: wait loop not terminated
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.terminateAndCheckLogs(TestAttachErrorHandling.java:157)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    TestAttachErrorHandling
    Tests run: 14, Failures: 1, Skips: 0
===============================================
```

At `AIX` as well https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly/134/consoleFull.

Will have a look.

**Comment by smlambert** [comment]
Now that we add some extra info at the bottom of the console output to aide reproduction of the failed test, its good to add it to the issues (especially as the Jenkins job and console output only stay around for a short time):

Grinder reproduction link: 
<JenkinsServer>/job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=functional&Jenkinsfile=openjdk_x86-64_mac&TARGET=TestAttachErrorHandling_0

Artifacts (SDK & native tests): https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/34/

**Comment by JasonFengJ9** [comment]
Update: 

Not able to reproduce the error in a 100x internal jenkins build.

**Comment by smlambert** [comment]
Not all tests that are run produce additional information in the tap results (system tests do, because they do not produce junit format output).  I think it is more about triagers knowing what info to grab off of a Jenkins job to attach to the issue, and developers knowing where to look in the information attached to an issue.   

I will plan to do a "triage and issue handling" best practices session next week.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/87
TestAttachErrorHandling_0
```
FAILED: test_startupShutdownRobustness
java.lang.AssertionError: target 23057: wait loop not terminated
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.terminateAndCheckLogs(TestAttachErrorHandling.java:157)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:116)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/197
TestAttachErrorHandling_0
```
java.lang.AssertionError: target 40989: wait loop not terminated
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.terminateAndCheckLogs(TestAttachErrorHandling.java:157)
	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:116)
```

**Comment by JasonFengJ9** [comment]
Will pick up this.
