### ISSUE TITLE
AArch64 pipeline failure creating java.base.jmod

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7012]
AArch64 CI pipeline builds are failing with the following exceptions (sample build https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_xl_Personal/21/)
```
11:05:04  Creating images/jmods/java.base.jmod
11:05:32  Error: java.nio.file.NoSuchFileException: /home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/images/jmods/jdk.httpserver.jmod
11:05:32  java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/images/jmods/jdk.httpserver.jmod
11:05:32  	at java.base/jdk.internal.module.ModuleHashes.computeHash(ModuleHashes.java:124)
11:05:32  	at java.base/jdk.internal.module.ModuleHashes.generate(ModuleHashes.java:141)
11:05:32  	at java.base/jdk.internal.module.ModuleHashesBuilder.lambda$computeHashes$2(ModuleHashesBuilder.java:118)
11:05:32  	at java.base/jdk.internal.module.ModuleHashesBuilder$$Lambda$89.0000000000000000.accept(Unknown Source)
11:05:32  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
11:05:32  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
11:05:32  	at java.base/java.util.ArrayDeque$DeqSpliterator.forEachRemaining(ArrayDeque.java:849)
11:05:32  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
11:05:32  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
11:05:32  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
11:05:32  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
11:05:32  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
11:05:32  	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
11:05:32  	at java.base/jdk.internal.module.ModuleHashesBuilder.computeHashes(ModuleHashesBuilder.java:105)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask$Hasher.computeHashes(JmodTask.java:926)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.computeHashes(JmodTask.java:654)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.writeModuleInfo(JmodTask.java:585)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask$JmodFileWriter.write(JmodTask.java:481)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask.create(JmodTask.java:438)
11:05:32  	at jdk.jlink/jdk.tools.jmod.JmodTask.run(JmodTask.java:208)
11:05:32  	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)
11:05:32  	Suppressed: java.lang.NoClassDefFoundError: java.util.Vector$Itr
11:05:32  		at java.base/java.util.Vector.iterator(Vector.java:1257)
11:05:32  		at java.base/java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:365)
11:05:32  		at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
11:05:32  		at java.base/java.util.zip.ZipOutputStream.close(ZipOutputStream.java:378)
11:05:32  		at jdk.jlink/jdk.tools.jmod.JmodOutputStream.close(JmodOutputStream.java:114)
11:05:32  		at jdk.jlink/jdk.tools.jmod.JmodTask.create(JmodTask.java:437)
11:05:32  		... 2 more
11:05:32  	Caused by: java.lang.ClassNotFoundException: java.util.Vector$Itr
11:05:32  		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1071)
11:05:32  		... 8 more
11:05:32  Caused by: java.nio.file.NoSuchFileException: /home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/images/jmods/jdk.httpserver.jmod
11:05:32  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
11:05:32  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
11:05:32  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
11:05:32  	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:178)
11:05:32  	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
11:05:32  	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
11:05:32  	at java.base/jdk.internal.module.ModuleHashes.computeHash(ModuleHashes.java:110)
11:05:32  	... 20 more
11:05:32  /usr/bin/cp: cannot create regular file ‘/home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/make-support/failure-logs/support_jmods_java.base.jmod.log’: No such file or directory
11:05:32  CreateJmods.gmk:162: recipe for target '/home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/images/jmods/java.base.jmod' failed
11:05:32  gmake[3]: *** [/home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/images/jmods/java.base.jmod] Error 1
11:05:32  make/Main.gmk:296: recipe for target 'java.base-jmod' failed
11:05:32  gmake[2]: *** [java.base-jmod] Error 1
11:05:32  
11:05:32  ERROR: Build failed for target 'all' in configuration 'linux-aarch64-normal-server-release' (exit code 2) 
11:05:32  make/Init.gmk:221: /home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/spec.gmk: No such file or directory
11:05:32  make/Init.gmk:224: /make/InitSupport.gmk: No such file or directory
11:05:32  gmake[2]: *** No rule to make target '/make/InitSupport.gmk'.  Stop.
```

**Comment by 0xdaryl** [comment]
Issue seems to be intermittent as other CI builds pass.  Perhaps storage availability related?  @knn-k

**Comment by knn-k** [comment]
I think so, because `/usr/bin/cp` fails to copy a file as follows.  It looks more like a storage problem than a java runtime problem to me.

> 11:05:32  /usr/bin/cp: cannot create regular file ‘/home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal/build/linux-aarch64-normal-server-release/make-support/failure-logs/support_jmods_java.base.jmod.log’: No such file or directory

**Comment by knn-k** [comment]
I think this can be closed now.

**Comment by 0xdaryl** [comment]
Resolved.
