### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/LambdaFormTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7055]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3c31c8cb4eb3eaed4de1a1438fa4f83e550fa51e/test/jdk/java/lang/invoke/LambdaFormTest.java#L1 is consistantly failing for JDK11-openj9 (Hotspot unaffected).
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac
```
10:30:54  openjdk version "11.0.5" 2019-10-15
10:30:54  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+4-201909021901)
10:30:54  Eclipse OpenJ9 VM AdoptOpenJDK (build master-e2e21457f, JRE 11 Linux amd64-64-Bit Compressed References 20190902_324 (JIT enabled, AOT enabled)
10:30:54  OpenJ9   - e2e21457f
10:30:54  OMR      - 5628a974
10:30:54  JCL      - 259a016054 based on jdk-11.0.5+4)
```

Optional info
-------------

- intermittent failure (yes|no): 
- new test:  
- Problem exists on all platforms and due to the absence of the class the test is searching for, I suspect this is an openj9 issue. However, I would like someone to take a look just to cross the T's and dot the I's. 

Failure output (captured from console output)
---------------------------------------------
```
STDOUT:
10:33:41  STDERR:
10:33:41  JavaTest Message: JUnit Failure: testShortenSignature(test.java.lang.invoke.LambdaFormTest): java.lang.NoSuchMethodException: java.lang.invoke.LambdaForm.shortenSignature(java.lang.String)
10:33:41  java.lang.AssertionError: java.lang.NoSuchMethodException: java.lang.invoke.LambdaForm.shortenSignature(java.lang.String)
10:33:41  	at test.java.lang.invoke.LambdaFormTest.<clinit>(LambdaFormTest.java:44)
10:33:41  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:33:41  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:33:41  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:33:41  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
10:33:41  	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:187)
10:33:41  	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:236)
10:33:41  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
10:33:41  	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:233)
10:33:41  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
10:33:41  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
10:33:41  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
10:33:41  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
10:33:41  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
10:33:41  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
10:33:41  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
10:33:41  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
10:33:41  	at org.junit.runners.Suite.runChild(Suite.java:128)
10:33:41  	at org.junit.runners.Suite.runChild(Suite.java:24)
10:33:41  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
10:33:41  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
10:33:41  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
10:33:41  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
10:33:41  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
10:33:41  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
10:33:41  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
10:33:41  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
10:33:41  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
10:33:41  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
10:33:41  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
10:33:41  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
10:33:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:33:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:33:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:33:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:33:41  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:33:41  	at java.base/java.lang.Thread.run(Thread.java:831)
10:33:41  Caused by: java.lang.NoSuchMethodException: java.lang.invoke.LambdaForm.shortenSignature(java.lang.String)
10:33:41  	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:638)
10:33:41  	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1344)
10:33:41  	at java.base/java.lang.Class.getMethodHelper(Class.java:1408)
10:33:41  	at java.base/java.lang.Class.getDeclaredMethod(Class.java:1080)
10:33:41  	at test.java.lang.invoke.LambdaFormTest.<clinit>(LambdaFormTest.java:40)
10:33:41  	... 36 more
10:33:41  
10:33:41  java.lang.Exception: JUnit test failure
10:33:41  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:92)
10:33:41  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
10:33:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:33:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:33:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:33:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:33:41  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:33:41  	at java.base/java.lang.Thread.run(Thread.java:831)
10:33:41  
10:33:41  JavaTest Message: Test threw exception: java.lang.Exception: JUnit test failure
10:33:41  JavaTest Message: shutting down test
```

**Comment by M-Davies** [comment]
Added to perm excludes
