### ISSUE TITLE
JTReg Test Failure: java/lang/constant/CondyDescTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7056]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/26/
Platform: mac
Version: 13
OpenJ9   - `39f1a4a52`
OMR      - `7e9584ea`
JCL      - `7f80b6bf6b`

Optional info
-------------
- intermittent failure: no
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
```
07:26:01  XML output with verification to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work
07:30:15  [2019-09-11 23:30:03,938] Agent[11]: stderr: Unhandled exception
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: Type=Segmentation error vmState=0x00000000
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: Handler1=00000000082922D0 Handler2=000000000797C590 InaccessibleAddress=00007FA25C918C5C
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: RDI=00000000000000C8 RSI=0000000007FFFFFF RAX=00000000FFFFFFFE RBX=00007FA23C918C20
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: RCX=0000000000000000 RDX=00000000000000C3 R8=0000000000000000 R9=0000000000000002
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: R10=0000000000000000 R11=00007FA2335A7700 R12=0000000000000000 R13=00007FA23BF0AED0
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: R14=00007FA23BF0AE40 R15=00007FA23CC2B08F
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: RIP=00000000083DD604 GS=0000 FS=0000 RSP=0000700008BC9090
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: RFlags=0000000000010A07 CS=002B RBP=0000700008BC90D0 ERR=5C918C5C00000006
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: TRAPNO=000000060000000E CPU=8C5C000000060000 FAULTVADDR=00007FA25C918C5C
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM2 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM3 bf6099e174400000 (f: 1950351360.000000, d: -2.026501e-03)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM4 bec13f824057e10a (f: 1079501056.000000, d: -2.056132e-06)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM5 bfc365fc00000000 (f: 0.000000, d: -1.515498e-01)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM6 bf6099e174400000 (f: 1950351360.000000, d: -2.026501e-03)
07:30:15  [2019-09-11 23:30:03,939] Agent[11]: stderr: XMM7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM8 432f656b6f766e69 (f: 1870032512.000000, d: 4.418618e+15)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,940] Agent[11]: stderr: XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: Module=/Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.dylib
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: Module_base_address=0000000008200000 Symbol=pool_newElement
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: Symbol_address=00000000083DD410
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: Target=2_90_20190912_73 (Mac OS X 10.14.5)
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: CPU=amd64 (4 logical CPUs) (0x200000000 RAM)
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: ----------- Stack Backtrace -----------
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: ---------------------------------------
07:30:15  [2019-09-11 23:30:03,941] Agent[11]: stderr: JVMDUMP039I Processing dump event "gpf", detail "" at 2019/09/11 23:30:03 - please wait.
07:30:15  [2019-09-11 23:30:03,948] Agent[11]: stderr: JVMDUMP039I Processing dump event "abort", detail "" at 2019/09/11 23:30:03 - please wait.
07:47:11  Timeout refired 60 times
07:47:11  [2019-09-11 23:47:04,073] Agent[11]: Killing process
```
`07:47:11  TEST RESULT: Error. Agent communication error: java.net.SocketTimeoutException: Read timed out; check console log for any additional details`
```
07:48:24  [2019-09-11 23:48:15,196] Agent[6]: stderr: JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/09/11 23:48:15 - please wait.
07:48:24  [2019-09-11 23:48:15,204] Agent[6]: stderr: JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/core.20190911.234815.73519.0001.dmp' in response to an event
07:48:24  [2019-09-11 23:48:21,067] Agent[6]: stderr: JVMDUMP012E Error in System dump: The core file created by child process with pid = 76899 was not found. Expected to find core file with name "/cores/core.76899"
07:48:24  [2019-09-11 23:48:21,068] Agent[6]: stderr: JVMDUMP032I JVM requested Heap dump using '/Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/heapdump.20190911.234815.73519.0002.phd' in response to an event
07:48:24  [2019-09-11 23:48:21,171] Agent[6]: stderr: JVMDUMP010I Heap dump written to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/heapdump.20190911.234815.73519.0002.phd
07:48:24  [2019-09-11 23:48:21,172] Agent[6]: stderr: JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/javacore.20190911.234815.73519.0003.txt' in response to an event
07:48:24  [2019-09-11 23:48:21,193] Agent[6]: stderr: JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/javacore.20190911.234815.73519.0003.txt
07:48:24  [2019-09-11 23:48:21,193] Agent[6]: stderr: JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/Snap.20190911.234815.73519.0004.trc' in response to an event
07:48:24  [2019-09-11 23:48:21,194] Agent[6]: stderr: JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work/scratch/3/Snap.20190911.234815.73519.0004.trc
07:48:24  [2019-09-11 23:48:21,195] Agent[6]: stderr: JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
07:49:01  [2019-09-11 23:49:00,366] Agent[9]: stderr: Waking Thread[Finalizer thread,5,system]
07:51:13  Test results: passed: 693; error: 1
07:51:23  Report written to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/jvmtest/openjdk/report/html/report.html
07:51:23  Results written to /Users/jenkins/workspace/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TestConfig/test_output_15682693464537/jdk_lang_0/work
```

**Comment by andrew-m-leonard** [comment]
More debug for jdk-13+33_openj9-0.16.0 build:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1986/console
```
09:50:24  [2019-09-17 01:50:23,890] Agent[1]: stderr: Unhandled exception
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: Type=Segmentation error vmState=0x00040000
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: Handler1=000000000D30D1A0 Handler2=000000000D5395D0 InaccessibleAddress=00007FEE7A9EF878
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: RDI=000000001B2CEA00 RSI=00007FEE7A9EF87A RAX=FFFFFFFFE019F238 RBX=0000000000000000
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: RCX=000000001B2D5DB8 RDX=000000001B2D5DB0 R8=0000000000000001 R9=00007FEE99015F30
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: R10=0000000000000001 R11=000000000F230430 R12=0000000000000000 R13=000000001B2CEA00
09:50:24  [2019-09-17 01:50:23,891] Agent[1]: stderr: R14=00007FEE9A8505E0 R15=0000000000000000
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: RIP=000000000F230652 GS=0000 FS=0000 RSP=000070000A9F8460
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: RFlags=0000000000010282 CS=002B RBP=000070000A9F84E0 ERR=7A9EF87800000004
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: TRAPNO=000000040000000E CPU=F878000000040000 FAULTVADDR=00007FEE7A9EF878
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM2 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM3 bf296b6878000000 (f: 2013265920.000000, d: -1.939359e-04)
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM4 be5431e6ddb91ac9 (f: 3719895808.000000, d: -1.880799e-08)
09:50:24  [2019-09-17 01:50:23,892] Agent[1]: stderr: XMM5 bfa252ec00000000 (f: 0.000000, d: -3.578889e-02)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM6 bf296b6878000000 (f: 2013265920.000000, d: -1.939359e-04)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM8 01000a0000001300 (f: 4864.000000, d: 7.308923e-304)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM9 08cbc4f66690748c (f: 1720743040.000000, d: 2.691288e-266)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM11 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,893] Agent[1]: stderr: XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,894] Agent[1]: stderr: XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:50:24  [2019-09-17 01:50:23,894] Agent[1]: stderr: Module=/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libjclse29.dylib
09:50:24  [2019-09-17 01:50:23,894] Agent[1]: stderr: Module_base_address=000000000F228000 Symbol=Java_java_lang_Class_getDeclaredClassesImpl
09:50:24  [2019-09-17 01:50:23,894] Agent[1]: stderr: Symbol_address=000000000F230430
09:50:24  [2019-09-17 01:50:23,894] Agent[1]: stderr: Target=2_90_20190916_77 (Mac OS X 10.14.5)
09:50:24  [2019-09-17 01:50:23,895] Agent[1]: stderr: CPU=amd64 (4 logical CPUs) (0x200000000 RAM)
09:50:24  [2019-09-17 01:50:23,895] Agent[1]: stderr: ----------- Stack Backtrace -----------
09:50:24  [2019-09-17 01:50:23,895] Agent[1]: stderr: ---------------------------------------
```
```
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Mac OS X 10.14.5
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : amd64
3XHNUMCPUS       How Many       : 4
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL           
1XHEXCPCODE    J9Generic_Signal_Number: 00000018
1XHEXCPCODE    Signal_Number: 0000000B
1XHEXCPCODE    Error_Value: 00000000
1XHEXCPCODE    Signal_Code: 00000001
1XHEXCPCODE    Handler1: 000000000D30D1A0
1XHEXCPCODE    Handler2: 000000000D5395D0
1XHEXCPCODE    InaccessibleAddress: 00007FEE7A9EF878
NULL           
1XHEXCPMODULE  Module: /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libjclse29.dylib
1XHEXCPMODULE  Module_base_address: 000000000F228000
1XHEXCPMODULE  Symbol: Java_java_lang_Class_getDeclaredClassesImpl
1XHEXCPMODULE  Symbol_address: 000000000F230430
```
```
1STSEGTOTAL    Total memory:                     6291456 (0x0000000000600000)
1STSEGINUSE    Total memory in use:              6291456 (0x0000000000600000)
1STSEGFREE     Total memory free:                      0 (0x0000000000000000)
1STSEGLIMIT    Allocation limit:               402653184 (0x0000000018000000)
```
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "AgentVMThread" J9VMThread:0x000000001B2CEA00, omrthread_t:0x00007FEE99894DD8, java/lang/Thread:0x00000000FFD93200, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x12, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x280A82B, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x000070000A9FB000, to:0x000070000AA3B000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.165111000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=1255920 (0x1329F0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Class.getDeclaredClassesImpl(Native Method)
4XESTACKTRACE                at java/lang/Class.getClasses(Class.java:548)
4XESTACKTRACE                at org/testng/internal/ClassInfoMap.registerClass(ClassInfoMap.java:40)
4XESTACKTRACE                at org/testng/internal/ClassInfoMap.<init>(ClassInfoMap.java:26)
4XESTACKTRACE                at org/testng/internal/ClassInfoMap.<init>(ClassInfoMap.java:18)
4XESTACKTRACE                at org/testng/TestRunner.initMethods(TestRunner.java:414)
4XESTACKTRACE                at org/testng/TestRunner.init(TestRunner.java:241)
4XESTACKTRACE                at org/testng/TestRunner.init(TestRunner.java:211)
4XESTACKTRACE                at org/testng/TestRunner.<init>(TestRunner.java:158)
4XESTACKTRACE                at org/testng/SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:546)
4XESTACKTRACE                at org/testng/SuiteRunner.init(SuiteRunner.java:159)
4XESTACKTRACE                at org/testng/SuiteRunner.<init>(SuiteRunner.java:114)
4XESTACKTRACE                at org/testng/TestNG.createSuiteRunner(TestNG.java:1260)
4XESTACKTRACE                at org/testng/TestNG.createSuiteRunners(TestNG.java:1247)
4XESTACKTRACE                at org/testng/TestNG.runSuitesLocally(TestNG.java:1101)
4XESTACKTRACE                at org/testng/TestNG.run(TestNG.java:1018)
4XESTACKTRACE                at com/sun/javatest/regtest/agent/TestNGRunner.main(TestNGRunner.java:94)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at jdk/internal/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
4XESTACKTRACE                at jdk/internal/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:567)
4XESTACKTRACE                at com/sun/javatest/regtest/agent/MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:831)
3XMTHREADINFO3           No native callstack available for this thread
```

**Comment by smlambert** [comment]
[Artifacts.zip](https://github.com/eclipse/openj9/files/3621498/Artifacts.zip)

**Comment by pshipton** [comment]
This should now be fixed, if the test is excluded it can be unexcluded.
