### ISSUE TITLE
Failing JTReg Test: java/lang/invoke/CustomizedLambdaFormTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7080]
JDK11's https://github.com/M-Davies/openj9-openjdk-jdk11/blob/dcaed50202aba11658bb827c255ef3c393d4b1ea/test/jdk/java/lang/invoke/CustomizedLambdaFormTest.java#L1 and JDK8's https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/c85b84056711e44d349a1d967eca1e7ace723566/jdk/test/java/lang/invoke/CustomizedLambdaFormTest.java#L1 are consistantly failing for x86-64_linux, windows and osx.

- Part of the excluded jdk11 openj9 JTReg Tests: https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Hotspot builds appear to be unaffected

JDK8
-----
```
/home/jenkins/workspace/Grinder_Advanced/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/invoke/CustomizedLambdaFormTest.java:38: error: cannot find symbol
14:09:31          mh.customize();
14:09:31            ^
14:09:31    symbol:   method customize()
14:09:31    location: variable mh of type MethodHandle
14:09:31  1 error
14:09:31  
14:09:31  TEST RESULT: Failed. Compilation failed: Compilation failed
```
JDK11
------
```
STDERR:
14:10:27  java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
14:10:27  	at java.base/java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
14:10:27  	at java.base/java.lang.invoke.MethodHandle.customize(MethodHandle.java:1366)
14:10:27  	at java.base/java.lang.invoke.MethodHandleHelper.customize(MethodHandleHelper.java:40)
14:10:27  	at CustomizedLambdaFormTest.testExtendCustomizedBMH(CustomizedLambdaFormTest.java:42)
14:10:27  	at CustomizedLambdaFormTest.main(CustomizedLambdaFormTest.java:47)
14:10:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:10:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:10:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:10:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:10:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
14:10:27  	at java.base/java.lang.Thread.run(Thread.java:831)
14:10:27  
14:10:27  JavaTest Message: Test threw exception: java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
14:10:27  JavaTest Message: shutting down test
14:10:27  
14:10:27  STATUS:Failed.`main' threw exception: java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
```

**Comment by M-Davies** [comment]
Problem list updated https://github.com/AdoptOpenJDK/openjdk-tests/pull/1343
