### ISSUE TITLE
ConcurrentModificationException launching build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7112]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/1613
```
09:12:50  Existing items:
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_ppc64_aix'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_ppc64le_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_s390x_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux_cm'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux_xl'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_windows'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_ppc64_aix'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_ppc64le_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_s390x_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-32_windows'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux_cm'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux_xl'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_mac'}
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_windows'}
09:12:50  Unreferenced items:
09:12:50      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_mac'}
[Pipeline] End of Pipeline
[Pipeline] // node
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:73)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize javaposse.jobdsl.plugin.actions.GeneratedObjectsRunAction#modifiedObjects for class javaposse.jobdsl.plugin.actions.GeneratedJobsBuildAction
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.util.XStream2.toXMLUTF8(XStream2.java:313)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:34)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1137)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1475)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:458)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
Could wrap https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/variables-functions.groovy#L1048
Can likely remove `create =` as well since we don't need whatever it is that is returned.

**Comment by AdamBrousseau** [comment]
cc @JennyChenyj

**Comment by JennyChenyj** [comment]
> Could wrap https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/variables-functions.groovy#L1048
> Can likely remove `create =` as well since we don't need whatever it is that is returned.

Hi @AdamBrousseau! Do you mean I would wrap them in a retry clause? Thanks!

**Comment by JennyChenyj** [comment]
https://github.com/eclipse/openj9/pull/7145

**Comment by pshipton** [comment]
Another one
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1643
```
18:08:27  Scheduling project: Pipeline_Build_Test_JDK8_x86-64_windows
[Pipeline] unstash
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
18:08:28  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
18:08:28  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
[Pipeline] }
[Pipeline] // retry
[Pipeline] }
[Pipeline] // node
18:08:28  Starting building: Pipeline_Build_Test_JDK11_ppc64_aix #724
[Pipeline] stage
[Pipeline] { (Pipeline_Build_Test_JDK11_x86-64_windows)
18:08:28  Existing items:
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_ppc64_aix'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_ppc64le_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_s390x_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux_cm'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux_xl'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_windows'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_ppc64_aix'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_ppc64le_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_s390x_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-32_windows'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux_cm'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_windows'}
18:08:28  Unreferenced items:
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_linux'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK11_x86-64_mac'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_linux_xl'}
18:08:28      GeneratedJob{name='Pipeline_Build_Test_JDK8_x86-64_mac'}
[Pipeline] End of Pipeline
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:73)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize javaposse.jobdsl.plugin.actions.GeneratedObjectsRunAction#modifiedObjects for class javaposse.jobdsl.plugin.actions.GeneratedJobsBuildAction
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.util.XStream2.toXMLUTF8(XStream2.java:313)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:34)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1137)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1475)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:458)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```

**Comment by AdamBrousseau** [comment]
Odd. I see the retry loop happening once in 2 different threads.
```
18:08:10  Stashed 1 file(s)
[Pipeline] cleanWs
18:08:10  [WS-CLEANUP] Deleting project workspace...
18:08:10  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
18:08:11  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] parallel
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_ppc64_aix)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_ppc64_aix)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-64_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_x86-64_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-64_linux_xl)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_x86-64_linux_xl)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-64_linux_cm)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_x86-64_linux_cm)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_ppc64le_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_ppc64le_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_s390x_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_s390x_linux)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-64_windows)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_x86-64_windows)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-32_windows)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK8_x86-64_mac)
[Pipeline] { (Branch: Pipeline_Build_Test_JDK11_x86-64_mac)
[Pipeline] node
[Pipeline] node
[Pipeline] node
18:08:11  Running on worker-1 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@7
18:08:11  Running on worker-1 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@8
[Pipeline] node
18:08:11  Running on worker-2 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@6
[Pipeline] node
[Pipeline] node
18:08:11  Running on worker-1 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@9
18:08:11  Running on worker-2 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@7
18:08:11  Running on worker-2 in /home/jenkins/jenkins-agent/workspace/Pipeline-OMR-Acceptance@8
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] node
[Pipeline] {
[Pipeline] {
[Pipeline] {
[Pipeline] {
[Pipeline] {
[Pipeline] {
[Pipeline] unstash
[Pipeline] unstash
[Pipeline] unstash
[Pipeline] unstash
[Pipeline] unstash
[Pipeline] unstash
[Pipeline] retry
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
[Pipeline] sleep
18:08:11  Sleeping for 2 min 0 sec
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
[Pipeline] retry
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] jobDsl
[Pipeline] sleep
18:08:11  Sleeping for 2 min 0 sec
18:08:12  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
18:08:12  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
18:08:12  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
18:08:12  Processing DSL script buildenv/jenkins/jobs/pipelines/Pipeline_Template.groovy
```
After that it appears to be working, up until it fails.
I wonder if it would be smarter to go back to doing DSL serially.
ref b990de20d7f63f2a7d2f015459d75bbaeb0fb860 #6274

**Comment by pshipton** [comment]
Another one, which blocked the nightly build and everything else from running since it blocked the workers.
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/661

**Comment by pshipton** [comment]
Another one, from a PR build, blocked workers.
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/1752
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:73)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize javaposse.jobdsl.plugin.actions.GeneratedObjectsRunAction#modifiedObjects for class javaposse.jobdsl.plugin.actions.GeneratedJobsBuildAction
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.util.XStream2.toXMLUTF8(XStream2.java:313)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:34)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1143)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1475)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:458)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by AdamBrousseau** [comment]
Has this happened since the last comment?

**Comment by pshipton** [comment]
I haven't seen it.
