### ISSUE TITLE
JTReg Test Failure: java/lang/ClassLoader/forNameLeak/ClassForNameLeak.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7122]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/50/
- test category: openjdk
- test target name: jdk_lang
- OS/architecture: all
- version: jdk8
- JVM: openj9
- public build SHAs:
```
05:13:59  OpenJ9   - 57ec9be1c
05:13:59  OMR      - ea20a3b7
05:13:59  JCL      - 467bd9a90a based on jdk8u232-b05
```

Optional info
-------------
- intermittent failure: no
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
```
05:18:23  STDOUT:
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@8216f6a9 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@8b4f50a6 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@51fb443d to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@9f8283b4 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@cf971d0b to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@72146db to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@cd3ae80 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@cfb3d405 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@845390d9 to LeakedClassLoader
05:18:23  returning phantom ref: java.lang.ref.PhantomReference@833a1201 to LeakedClassLoader
05:18:23  STDERR:
05:18:23  java.lang.RuntimeException: ClassLoader was never enqueued!
05:18:23  	at ClassForNameLeak.main(ClassForNameLeak.java:116)
05:18:23  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:18:23  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:18:23  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:18:23  	at java.lang.reflect.Method.invoke(Method.java:498)
05:18:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:18:23  	at java.lang.Thread.run(Thread.java:819)
```

**Comment by JasonFengJ9** [comment]
The test code in question is at [1]:
```
        // Give the GC a chance to enqueue the PhantomReferences
        for (int i = 0; i < 10; i++) {
            System.gc();
        }
        // Make sure all PhantomReferences to the leaked classloader are enqueued
        for (int j = 0; j < THREADS; j++) {
            Reference rmRef = rq.remove(TIMEOUT);
            if (rmRef == null) {
                throw new RuntimeException("ClassLoader was never enqueued!");
            } else {
                System.out.println("Enqueued " + rmRef);
            }
}
```

This appears a test of `RI GC` specific behaviour, `OpenJ9` might have different `GC` policies.

@dmitripivkine please comment.  

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/467bd9a90a42b9cd6db1c7b8b9faf818769c64b0/jdk/test/java/lang/ClassLoader/forNameLeak/ClassForNameLeak.java#L108-L116

**Comment by dmitripivkine** [comment]
If I am reading test correctly it expects Classloader to be unloaded by System GC. Class unloading decision in OpenJ9 based on heuristics (not mandatory) but it can be forced by using `-Xalwaysclassgc` command line option. Also we can add `-verbose:gc` to get gc verbose log output to be sure that actual Global GC has been executed

**Comment by JasonFengJ9** [comment]
@adam-thorpe does `RI Java 8` fail this test as well?

**Comment by adam-thorpe** [comment]
@JasonFengJ9 No, it passes: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/60/testReport/

**Comment by JasonFengJ9** [comment]
@adam-thorpe could you try `-Xalwaysclassgc` and `-verbose:gc` as per https://github.com/eclipse/openj9/issues/7122#issuecomment-532750848?

**Comment by adam-thorpe** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/775/console not sure what I'm looking for here

**Comment by JasonFengJ9** [comment]
The grinder with `Xalwaysclassgc` above still failed.
@dmitripivkine is there anything helpful in the console output or the result file?

**Comment by dmitripivkine** [comment]
We need to investigate why this test does not work as expected. Either test is bogus and expected behaviour rely on particular implementation or our code is misbehaving somehow. Let me check code.

**Comment by dmitripivkine** [comment]
GC does check for `((J2SE_VERSION(javaVM) & J2SE_VERSION_MASK) <= J2SE_18)` and keep Phantom Reference Referent alive if it is TRUE. Otherwise Phantom behaves as Weak. So Java 8 is last version where this test is valid. @JasonFengJ9 Is Java version equal J2SE_18 for this test? Is it rely on Java 8 or 2.9?

**Comment by JasonFengJ9** [comment]
> Is Java version equal J2SE_18 for this test? Is it rely on Java 8 or 2.9?

The JVM in question is OpenJ9 `Java 8`, `2.9` was IBM Java internal level. `J2SE_18` determines if it is a `Java 8`.

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by JasonFengJ9** [comment]
`OpenJ9 JDK 11` passes this test at a `10x` grinder https://ci.adoptopenjdk.net/job/Grinder/808/
Also `OpenJ9 JDK 8` failed as reported by this issue at a `3x` grinder https://ci.adoptopenjdk.net/job/Grinder/807

This test uses multiple (`10`) threads to stress the call to the test method however each test method performs following:
```
        ClassLoader classLoader = new URLClassLoader(
                new URL[]{jarFilePath.toUri().toURL()}) {
            @Override public String toString() { return "LeakedClassLoader"; }
        };

        Class<?> loadClass = Class.forName("ClassForName", true, classLoader);
        ((Runnable) loadClass.newInstance()).run();

        PhantomReference<ClassLoader> ref = new PhantomReference<>(classLoader, rq);
        System.out.println("returning phantom ref: " + ref + " to " + classLoader);
        return ref;
``` 
In addition, there is ` private static final ReferenceQueue<ClassLoader> rq = new ReferenceQueue<>();` which is expected to hold the `PhantomReference` of the `ClassLoader`.
It appears `OpenJ9 JDK 11` enqueued those `ClassLoader` `PhantomReferences` but `JDK 8` doesn't.

Note: `RI JDK 8` passes this test.

**Comment by JasonFengJ9** [comment]
`JDK 11` with `-Xnoclassgc -verbose:gc` 10x grinder is at https://ci.adoptopenjdk.net/job/Grinder/809/
fyi @dmitripivkine

**Comment by dmitripivkine** [comment]
Thank you. All jobs failed as we expected.

**Comment by DanHeidinga** [comment]
Has anyone used MAT (or similar tools) to validate what is holding onto the ClassLoader?  It would be good to know what strong root is keeping it alive.

**Comment by JasonFengJ9** [comment]
Tried `Eclipse MAT` to load a core generated when `RuntimeException("ClassLoader was never enqueued!")` was thrown. There was no `URLClassLoader` instance.
It appears those instances are GCed immediately and not available in the `ReferenceQueue<ClassLoader>`.
The core files are at `/team/triage/gitissue7122`.

@dmitripivkine could you have a look?

**Comment by dmitripivkine** [comment]
All ten classloaders have been unloaded in first (of 10) System GC

**Comment by DanHeidinga** [comment]
I feel like I'm missing something - if the referent was collected while the reference object was still alive, shouldn't the reference object have been enqueued?

**Comment by dmitripivkine** [comment]
Also I noticed there are no O-slots in the function frame, so function itself does not keep any object alive:
```
<13d8f00> Bytecode frame: bp = 0x0000000001437C20, sp = 0x0000000001437C10, pc = 0x00007F356440CE16, cp = 0x00000000014125A0, arg0EA = 0x0000000001437C68, flags = 0x0000000000000000
<13d8f00> 	Method: ClassForNameLeak.main([Ljava/lang/String;)V !j9method 0x0000000001412DE8
<13d8f00> 	Bytecode index = 170
<13d8f00> 	Using local mapper
<13d8f00> 	Locals starting at 0x0000000001437C68 for 0x0000000000000009 slots
<13d8f00> 		I-Slot: a0[0x0000000001437C68] = 0x00000000FFE0C5A8
<13d8f00> 		I-Slot: t1[0x0000000001437C60] = 0x00000000FFF0B6E0
<13d8f00> 		I-Slot: t2[0x0000000001437C58] = 0x00000000FFE99058
<13d8f00> 		I-Slot: t3[0x0000000001437C50] = 0x00000000FFF0B638
<13d8f00> 		I-Slot: t4[0x0000000001437C48] = 0x00000000FFFBAF90
<13d8f00> 		I-Slot: t5[0x0000000001437C40] = 0x00000000FFFD0768
<13d8f00> 		I-Slot: t6[0x0000000001437C38] = 0x00000000FFF09D78
<13d8f00> 		I-Slot: t7[0x0000000001437C30] = 0x0000000000000000
<13d8f00> 		I-Slot: t8[0x0000000001437C28] = 0x0000000000000000
```

**Comment by dmitripivkine** [comment]
> I feel like I'm missing something - if the referent was collected while the reference object was still alive, shouldn't the reference object have been enqueued?

I am confused too. Can somebody explain step by step how this test suppose to work?

**Comment by dmitripivkine** [comment]
@JasonFengJ9 Would you please generate GC verbose log as well?

**Comment by JasonFengJ9** [comment]
The test [1] looks like following:
`loadAndRun()` creates & returns `PhantomReference ref` which is registered to `ReferenceQueue rq`. The `referent` is a local `URLClassLoader classLoader` instance.
```
    private static final ReferenceQueue<ClassLoader> rq = new ReferenceQueue<>();
    public static PhantomReference<ClassLoader> loadAndRun(Path jarFilePath) {
        ........
        PhantomReference<ClassLoader> ref = new PhantomReference<>(classLoader, rq);
        return ref;
    }
```

`loadAndRun()` is invoked and returning `PhantomReference<ClassLoader>` is in a local `List<Future<PhantomReference<ClassLoader>>> refs`. There are 10 threads for such invocations. 
```
        List<Callable<PhantomReference<ClassLoader>>> callables =
                Stream.generate(() -> {
                    Callable<PhantomReference<ClassLoader>> cprcl = () -> {
                        return loadAndRun(jarFilePath);
                    };
                    return cprcl;
                }).limit(THREADS).collect(Collectors.toList());
        List<Future<PhantomReference<ClassLoader>>> refs = es.invokeAll(callables);
```
The test expects each `PhantomReference` was enqueued.
```
        for (int j = 0; j < THREADS; j++) {
            Reference rmRef = rq.remove(TIMEOUT);
            if (rmRef == null) {
                throw new RuntimeException("ClassLoader was never enqueued!");
            } else {
                System.out.println("Enqueued " + rmRef);
            }
        }
```

As per java doc [2]:
"Phantom reference objects, which are enqueued after the collector determines that their referents may otherwise be reclaimed."

> Would you please generate GC verbose log as well?

`verbosegc.20200124.171027.61017.txt` is in same triage foler.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/test/java/lang/ClassLoader/forNameLeak/ClassForNameLeak.java
[2] https://docs.oracle.com/javase/8/docs/api/java/lang/ref/PhantomReference.html

**Comment by JasonFengJ9** [comment]
> if the referent was collected while the reference object was still alive, shouldn't the reference object have been enqueued?

I think this is what the test expects.

**Comment by dmitripivkine** [comment]
> > Would you please generate GC verbose log as well?
> 
> `verbosegc.20200124.171027.61017.txt` is in same triage foler.

Somehow this verbose log does not match: I can not see class unloading events here as well as ten system GC back to back.

**Comment by dmitripivkine** [comment]
Also would be interesting to look to gc verbose log for Java 11 where this test works

**Comment by JasonFengJ9** [comment]
> Also would be interesting to look to gc verbose log for Java 11 where this test works

`verbosegc.20200124.212510.2710.txt` is at triage `jdk11` folder. 

In addition, re-created system/java core files along with `verbosegc` at `jdk8` folder.

**Comment by dmitripivkine** [comment]
There is a short summary what we got so far:
 - Test still fail in Java 8 even GC code has been switched to Java 11 mode. So the difference in handling of Phantom References in GC between Java 8 and Java 11 is irrelevant.
- GC verbose log shows number of discovered/cleared/enqueued Phantom References for each GC.
For Java 11 there are 62 alive Phantom References and 20 of them were cleared and enqueued by first System GC (and looks like 10 of these 20 were created by test as expected). 
- In Java 8 however there are 19 alive Phantom References only and none of them were cleared and enqueued. I examined system core provided and search for all Phantom References listed by GC. There are 19 of them exactly and none of them related to test. Looks like GC never discover Phantom References created by test alive so there is no way to enqueue them.

There is unlikely that problem relates to Phantom Reference handling in GC. Looks like there is different behaviour in VM between Java 8 and Java 11. We are going to continue this investigation.

**Comment by JasonFengJ9** [comment]
This `JDK8` test `ClassForNameLeak` uses `Lambda` expression to invoke `loadAndRun()` which holds (and _returns_) the `PhantomReference<ClassLoader>`.  However the returning reference is not hold by any variables outside of `loadAndRun()` and GC doesn't have root to discover these references. (There was an issue discussed about this GC limitation, @dmitripivkine do you happen to have a link to it?)
```
public static void main(java.lang.String[]) 

49: invokedynamic #32,  0             // InvokeDynamic #0:get:(Ljava/nio/file/Path;)Ljava/util/function/Supplier;

  0: #135 invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #136 ()Ljava/lang/Object;
      #137 invokestatic ClassForNameLeak.lambda$main$1:(Ljava/nio/file/Path;)Ljava/util/concurrent/Callable;
      #138 ()Ljava/util/concurrent/Callable;

  1: #135 invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #136 ()Ljava/lang/Object;
      #156 invokestatic ClassForNameLeak.lambda$null$0:(Ljava/nio/file/Path;)Ljava/lang/ref/PhantomReference;
      #157 ()Ljava/lang/ref/PhantomReference;

  private static java.util.concurrent.Callable lambda$main$1(java.nio.file.Path);
    descriptor: (Ljava/nio/file/Path;)Ljava/util/concurrent/Callable;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=1, locals=2, args_size=1
         0: aload_0
         1: invokedynamic #50,  0             // InvokeDynamic #1:call:(Ljava/nio/file/Path;)Ljava/util/concurrent/Callable;
         6: astore_1
         7: aload_1
         8: areturn

  private static java.lang.ref.PhantomReference lambda$null$0(java.nio.file.Path) throws java.lang.Exception;
    descriptor: (Ljava/nio/file/Path;)Ljava/lang/ref/PhantomReference;
    flags: ACC_PRIVATE, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokestatic  #51                 // Method loadAndRun:(Ljava/nio/file/Path;)Ljava/lang/ref/PhantomReference;
         4: areturn
```  

The reason that `OpenJ9 JDK11` passed the test is because `ClassForNameLeak.java` [1]  is different from its JDK8 friend though they have same file name.
The returning `PhantomReference<ClassLoader>` from method `loadAndRun()` was stored in `TestLoader.ref` hence it was discovered by GC and cleared/enqueued successfully.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/9f54681ac309d025bdbf45f4ba0cb7bc6247596a/test/jdk/java/lang/ClassLoader/forNameLeak/ClassForNameLeak.java#L62-L89

**Comment by dmitripivkine** [comment]
The reachability problem discussed here: http://thevirtualmachinist.blogspot.com/2011/07/subtle-issue-of-reachability.html

**Comment by JasonFengJ9** [comment]
The link and the insights about this kind of issue I was looking for is https://github.com/eclipse/openj9/issues/5325#issuecomment-479107547.
