### ISSUE TITLE
sanity.system_x86-64_mac TestIBMJlmRemoteMemoryAuth_SE80_0 MemoryProfiler.getStatsViaProxy assert

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7169]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/148
TestIBMJlmRemoteMemoryAuth_SE80_0
```
CL1 .............................j> 2019/09/20 00:09:14.275 Exiting as JVM we are connected to has finished
CL1 stderr Exception in thread "main" java.lang.AssertionError
CL1 stderr 	at org.junit.Assert.fail(Assert.java:86)
CL1 stderr 	at org.junit.Assert.fail(Assert.java:95)
CL1 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.getStatsViaProxy(MemoryProfiler.java:217)
CL1 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:119)
```

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&JenkinsFile=openjdk_x86-64_mac&TARGET=TestIBMJlmRemoteMemoryAuth_SE80_0

**Comment by pshipton** [comment]
@Mesbah-Alam this assert doesn't give any information about what went wrong. Nothing in the artifacts that I spotted either.

**Comment by pshipton** [comment]
I'll close this as a dup of #7397
