### ISSUE TITLE
JTReg Test Failure: java/util/Arrays/TimSortStackSize2.java (2)

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7223]
Failure link
------------
Rebuild: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux_xl&CUSTOM_TARGET=java/util/Arrays/TimSortStackSize2.java&TARGET=jdk_custom_0 (current bug with openjdk-tests so use `https://github.com/adam-thorpe/openjdk-tests.git` and branch `debuggrinder`)
- test category: openjdk
- OS/architecture: all (large heap only)
- Version: 8 (maybe 11 and 13 as well, they fail due to another issue at the moment)

Optional info
-------------
- intermittent failure: no
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
run main/othervm -Xms385m TimSortStackSize2 67108864:
```
10:10:47  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/09/25 09:10:42 - please wait.
10:10:47  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/core.20190925.091042.15721.0001.dmp' in response to an event
10:10:47  JVMDUMP010I System dump written to /home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/core.20190925.091042.15721.0001.dmp
10:10:47  JVMDUMP032I JVM requested Heap dump using '/home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/heapdump.20190925.091042.15721.0002.phd' in response to an event
10:10:47  JVMDUMP010I Heap dump written to /home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/heapdump.20190925.091042.15721.0002.phd
10:10:47  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/javacore.20190925.091042.15721.0003.txt' in response to an event
10:10:47  JVMDUMP010I Java dump written to /home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/javacore.20190925.091042.15721.0003.txt
10:10:47  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/Snap.20190925.091042.15721.0004.trc' in response to an event
10:10:47  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15694026323897/jdk_custom_0/work/scratch/0/Snap.20190925.091042.15721.0004.trc
10:10:47  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
10:10:47  java.lang.OutOfMemoryError: Java heap space
10:10:47  	at TimSortStackSize2.createArray(TimSortStackSize2.java:164)
10:10:47  	at TimSortStackSize2.doTest(TimSortStackSize2.java:59)
10:10:47  	at TimSortStackSize2.main(TimSortStackSize2.java:43)
10:10:47  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:10:47  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:10:47  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:10:47  	at java.lang.reflect.Method.invoke(Method.java:498)
10:10:47  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:10:47  	at java.lang.Thread.run(Thread.java:819)
```

Just to clarify, this is a different issue to https://github.com/eclipse/openj9/issues/7086

**Comment by pshipton** [comment]
For historical reasons OpenJ9 JDK8 uses a -Xmx512m by default, which is different and smaller than Hotspot. I expect if the test is run with a bigger -Xmx then it would pass.
