### ISSUE TITLE
JTReg Failure: java/lang/ref/FinalizerHistogramTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7226]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/502ab02dbda2e8b021cffedc3f52e25246cdeec1/test/jdk/java/lang/ref/FinalizerHistogramTest.java#L1 fails for JDK11/13-openj9
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac
```
13:18:38  openjdk version "11.0.5" 2019-10-15
13:18:38  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+7-201909200946)
13:18:38  Eclipse OpenJ9 VM AdoptOpenJDK (build master-ad592a06b, JRE 11 Linux amd64-64-Bit Compressed References 20190920_335 (JIT enabled, AOT enabled)
13:18:38  OpenJ9   - ad592a06b
13:18:38  OMR      - 640f1dfa
13:18:38  JCL      - 8bf2a81661 based on jdk-11.0.5+7)
```

Optional info
-------------

- intermittent failure (no): 
- Part of the excluded AdoptOpenJDK/openjdk-tests#585

Failure output (captured from console output)
---------------------------------------------
```
13:22:06  STDERR:
13:22:06  Test failed with java.lang.RuntimeException: MyObject is not found in test output
13:22:06  java.lang.RuntimeException: MyObject is not found in test output
13:22:06  	at FinalizerHistogramTest.main(FinalizerHistogramTest.java:93)
13:22:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:22:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:22:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:22:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:22:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:22:06  	at java.base/java.lang.Thread.run(Thread.java:831)
13:22:06  java.lang.RuntimeException: Test failed
13:22:06  	at FinalizerHistogramTest.main(FinalizerHistogramTest.java:100)
13:22:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:22:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:22:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:22:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:22:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:22:06  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by M-Davies** [comment]
Thanks @JasonFengJ9 ! :)
