### ISSUE TITLE
jdk11+ extended.functional jsr292Test testAsSpreader testIllegalArgument NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7246]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly/153
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/149
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/148
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/49
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly/152
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/152
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly/148
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/50
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_s390x_linux_Nightly/50
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_Nightly/49
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/147
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_Nightly/51
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_windows_Nightly/50
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.functional_s390x_linux_OpenJDK/35
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.functional_ppc64le_linux_OpenJDK/38

 jsr292Test_0
jsr292Test_1
```
FAILED: testAsSpreader
java.lang.NullPointerException
	at com.ibm.j9.jsr292.AdaptorTests.testAsSpreader(AdaptorTests.java:289)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testIllegalArgument
java.lang.NullPointerException
	at com.ibm.j9.jsr292.Crash.testIllegalArgument(Crash.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

failing
OpenJ9: 6125530
OMR: c30a477
OpenJDK: 502ab02

previous
OpenJ9: 7ee4708
OMR: c654661
OpenJDK: 502ab02

https://github.com/eclipse/openj9/compare/7ee4708...6125530
https://github.com/eclipse/openj9-omr/compare/c654661...c30a477

**Comment by pshipton** [comment]
@fengxue-IS @DanHeidinga

**Comment by fengxue-IS** [comment]
@pshipton 
The Java 11 api doc have updated on how null parameters should be handle (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/MethodHandle.html#asSpreader(int,java.lang.Class,int))

This makes these test invalid for testing in Java 11+ (either change expected result to NPE or just exclude them for 11+)

**Comment by pshipton** [comment]
@fengxue-IS ok, but the tests need to be fixed asap please, we can't have all these failures in every nightly build, and they are blocking acceptance of new JDKNext (Java 14) levels.
