### ISSUE TITLE
JTReg Test Failure: sun/nio/ch/TestMaxCachedBufferSize.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7277]
Failure link
------------
Rebuild link: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/sun/nio/ch/TestMaxCachedBufferSize.java&TARGET=jdk_custom_0
- test category: sanity openjdk
- OS/architecture: all
- version: 11, 13
- JVM: openj9

Optional info
-------------
- intermittent failure: no
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
run main/othervm TestMaxCachedBufferSize
```
13:29:19  STDOUT:
13:29:19  Threads 4 | Iterations 10000 | MaxBufferSize 9223372036854775807
13:29:19  
13:29:19   Worker   2 |     5000 Iters | Small     4961 Large       39 | Direct   10 /   16097K
13:29:19   Worker   1 |     5000 Iters | Small     4944 Large       56 | Direct   10 /   16097K
13:29:19   Worker   3 |     5000 Iters | Small     4946 Large       54 | Direct   10 /   16129K
13:29:19   Worker   0 |     5000 Iters | Small     4934 Large       66 | Direct   10 /   16129K
13:29:19   Worker   1 |    10000 Iters | Small     9911 Large       89 | Direct   10 /   16129K
13:29:19   Worker   2 |    10000 Iters | Small     9918 Large       82 | Direct   10 /   16129K
13:29:19   Worker   3 |    10000 Iters | Small     9904 Large       96 | Direct   10 /   16129K
13:29:19   Worker   0 |    10000 Iters | Small     9883 Large      117 | Direct   10 /   16129K
13:29:19  
13:29:19  Direct 10 / 16129K
13:29:19  STDERR:
13:29:19  java.lang.Error: inconsistent direct buffer total count, expected = 4, found = 10
13:29:19  	at TestMaxCachedBufferSize.checkDirectBuffers(TestMaxCachedBufferSize.java:186)
13:29:19  	at TestMaxCachedBufferSize.main(TestMaxCachedBufferSize.java:257)
13:29:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:29:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:29:19  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:29:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:29:19  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:29:19  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by adam-thorpe** [comment]
https://github.com/eclipse/openj9/issues/5328
