### ISSUE TITLE
JTReg Test Failure: java/lang/reflect/AccessibleObject/CanAccessTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7294]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/b44d19c4cbca42541aef5132f21870c1b924a68c/test/jdk/java/lang/reflect/AccessibleObject/CanAccessTest.java#L1 is consistantly failing for JDK11/JDK13-openj9
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac
```
10:12:47  openjdk version "11.0.5" 2019-10-15
10:12:47  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201909262135)
10:12:47  Eclipse OpenJ9 VM AdoptOpenJDK (build master-ceecaaa00, JRE 11 Linux amd64-64-Bit Compressed References 20190926_342 (JIT enabled, AOT enabled)
10:12:47  OpenJ9   - ceecaaa00
10:12:47  OMR      - 597e2a15
10:12:47  JCL      - 37664914e7 based on jdk-11.0.5+9)
```

Optional info
-------------

- intermittent failure (no)
- Part of the excluded AdoptOpenJDK/openjdk-tests#585
- AssertionError is caused when the test checks if it can't access the constructor of `Unsafe.java` and throws the error when it can.

Failure output (captured from console output)
---------------------------------------------
```
10:16:05  STDOUT:
10:16:05  [TestNG] Running:
10:16:05    java/lang/reflect/AccessibleObject/CanAccessTest.java
10:16:05  
10:16:05  test CanAccessTest.testConstructor(): failure
10:16:05  java.lang.AssertionError: expected [false] but found [true]
10:16:05  	at org.testng.Assert.fail(Assert.java:94)
10:16:05  	at org.testng.Assert.failNotEquals(Assert.java:496)
10:16:05  	at org.testng.Assert.assertFalse(Assert.java:63)
10:16:05  	at org.testng.Assert.assertFalse(Assert.java:73)
10:16:05  	at CanAccessTest.testConstructor(CanAccessTest.java:49)
10:16:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:16:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:16:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:16:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:16:05  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
10:16:05  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
10:16:05  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
10:16:05  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
10:16:05  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
10:16:05  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
10:16:05  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
10:16:05  	at org.testng.TestRunner.run(TestRunner.java:623)
10:16:05  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
10:16:05  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
10:16:05  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
10:16:05  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
10:16:05  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
10:16:05  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
10:16:05  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
10:16:05  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
10:16:05  	at org.testng.TestNG.run(TestNG.java:1018)
10:16:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
10:16:05  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
10:16:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:16:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:16:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:16:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
10:16:05  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:16:05  	at java.base/java.lang.Thread.run(Thread.java:831)
10:16:05  test CanAccessTest.testInstanceMethod(): success
10:16:05  test CanAccessTest.testInvalidInstanceObject(): success
10:16:05  test CanAccessTest.testProtectedConstructor(): success
10:16:05  test CanAccessTest.testProtectedStatic(): success
10:16:05  test CanAccessTest.testStaticMember(): success
```

Rerun job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/AccessibleObject/CanAccessTest.java&TARGET=jdk_custom_0

[openjdk_test_output (2).tar.gz](https://github.com/eclipse/openj9/files/3675248/openjdk_test_output.2.tar.gz)

**Comment by DanHeidinga** [comment]
Possibly related to https://bugs.openjdk.java.net/browse/JDK-8210522 ?

**Comment by DanHeidinga** [comment]
In either case, it sounds like we need to look at our Reflection method/field filtering.  @JasonFengJ9 can you take a look at this?

**Comment by M-Davies** [comment]
> Possibly related to https://bugs.openjdk.java.net/browse/JDK-8210522 ?

That does indeed seem related. The test does use the `Constructor` and `Method` reflect libraries and the next line of code after the error is `trySetAccessible()`.

**Comment by JasonFengJ9** [comment]
Looking into it. Reproduced the failure.
