### ISSUE TITLE
Java 8 extended functional test failure TestManagementAgent_SE80_0

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#730]
```
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 37 more
FAILED: test_startLocalManagementAgent
```

```
FAILED: test_startManagementAgent
java.lang.AssertionError: unexpected exception Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 10.20.12.127; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)] in 23745
	at org.testng.Assert.fail(Assert.java:94)
	at org.openj9.test.attachAPI.TestManagementAgent.test_startManagementAgent(TestManagementAgent.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
```

**Comment by DanHeidinga** [comment]
Adding the `comp:test` label as this looks like a test configuration issue based on the `Connection refused to host: 10.20.12.127; ` exception message.

@llxia Can someone on your team take a look at this?

**Comment by DanHeidinga** [comment]
@pshipton Are these tests part of the nightly test run?  If so, please add the priority:high label.

**Comment by smlambert** [comment]
same exception as seen in #301 (closed by #488) and #480

**Comment by DanHeidinga** [comment]
The fix for #301 went in ~20 days ago.  This is likely a different issue.

**Comment by smlambert** [comment]
Wasn't suggesting it was the same fix.  Am making notes on this issue to narrow down what to look at.  Noting it was an accesscontrolexception in 301, that caused the connection refused error.  

Both tests, test_startLocalManagementAgent, test_startManagementAgent:
attach() then
startLocalManagementAgent() methods
from com.sun.tools.attach.VirtualMachine 

I will confirm, but these tests run and pass in Java9, so do not think framework is the immediate suspect.  Should understand the differences between 8 & 9 attach api test and product code.

**Comment by pshipton** [comment]
This test is part of the "OpenJ9 [<platform>] 80 Extended Test" nightly run. Adding prio:high label as requested.

**Comment by smlambert** [comment]
Example of this test running and passing in SE90:
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/68/testngreports/org.openj9.test.attachAPI/TestManagementAgent/

**Comment by smlambert** [comment]
I believe SE80 / SE90 are both using the same test code (https://github.com/eclipse/openj9/blob/master/test/Java8andUp/src/org/openj9/test/attachAPI/TestManagementAgent.java), though I know there was some re-organization of the Utilities used by attach api tests, that @pdbain-ibm will be able to speak to. 

But based on the fact this test was running and passing in SE90 and SE80 & SE90 use the same test code, that implies the investigation needs to shift to the underlying product code that is being tested.  

What are the differences between 8 & 9 for the attach management agent code and/or javax.management.remote.JMXServiceURL ?

**Comment by pshipton** [comment]
Based on some testing @pdbain-ibm did for another issue, I'd say AttachAPI isn't working.
```
/team/pdbain/vm/openj9/xa6480_openj9/j2sdk-image/bin/java   \
-cp "/team/pdbain/lib:/team/pdbain/lib/testjars/testng.jar:/team/pdbain/lib/testjars/jcommander.jar:/team/pdbain/lib/tools.jar:/team/pdbain/bin/Java8andUp:/team/pdbain/bin/TestUtilities" \
-Dcom.ibm.tools.attach.enable=yes \
-Dcom.ibm.tools.attach.timeout=15000 \
org.testng.TestNG -d "results" "Java8AndUp/testng.xml" -testnames TestManagementAgent \
-groups level.extended \
-excludegroups d.*.linux_x86-64,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all
```
The stack trace is iffy:
```
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:118)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:75)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:220)
	at org.openj9.test.attachAPI.TestManagementAgent.test_startLocalManagementAgent(TestManagementAgent.java:112)
```
	It's calling the wrong attach API classes.

**Comment by pdbain-ibm** [comment]
AttachAPI is mostly working.  Start*ManagementAgent() seem to have problems.  I am investigating.

**Comment by DanHeidinga** [comment]
Based on @pshipton comment, are there missing patches from the JDK8 Extensions repo?

**Comment by pdbain-ibm** [comment]
Simple testcase:
`	private static void startAgent(String vmid) {
		try {
			VirtualMachine vm = VirtualMachine.attach(vmid);
			System.out.println("startLocalManagementAgent");
			String response = vm.startLocalManagementAgent();
			System.out.println("response="+response);
			vm.detach();
		} catch (AttachNotSupportedException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
`
gives:
$ java startlocalagent 19594
startLocalManagementAgent
com.sun.tools.attach.AttachOperationFailedException: AttachOperationFailedException from target: ATTACH_ERR AttachOperationFailedException in startLocalManagementAgent:  startLocalManagementAgent error starting agent:class com.ibm.tools.attach.target.IbmAttachOperationFailedException startLocalManagementAgent cannot access startLocalManagementAgent

Looking at the log files (19594 is the target, 19612 the attacher):
1512658494606 19612: 1 [main]: attachTarget 19594 on port 36406
1512658494610 19594: 16 [Attachment 36406]: Attachment run 
1512658495109 19612: 1 [main]: attachTarget SocketTimeoutException on 36406 to 19594
1512658495131 19612: 1 [main]: eraseReply deleted replyInfo
1512658495132 19594: 16 [Attachment 36406]: connectToAttacher exception Connection refused (Connection refused) java.net.ConnectException: Connection refused (Connection refused)
1512658495135 19612: 1 [main]: unlockAllAttachNotificationSyncFiles unlocking targetLocks[0]
1512658495137 19612: 1 [main]: unlockAllAttachNotificationSyncFiles unlocking targetLocks[1]
1512658495138 19612: 1 [main]: unlocking file /tmp/.com_ibm_tools_attach/19594/attachNotificationSync

**Comment by pdbain-ibm** [comment]
Attaching and doing getSystemProperties() works fine.
Running the target under OpenJ9 Java9 and running startLocalManagementAgent() using OpenJ9 Java 8 works fine, as expected.

**Comment by pdbain-ibm** [comment]
Instrumented Attachment:
PDB_DEBUG: getDeclaredMethod(START_LOCAL_MANAGEMENT_AGENT)
java.lang.NoSuchMethodException: sun.management.Agent.startRemoteManagementAgent(java.util.Properties)
	at java.lang.Class.newNoSuchMethodException(Class.java:515)
	at java.lang.Class.throwExceptionOrReturnNull(Class.java:1127)
	at java.lang.Class.getMethodHelper(Class.java:1189)
	at java.lang.Class.getDeclaredMethod(Class.java:884)
	at com.ibm.tools.attach.target.Attachment$MethodRefsHolder.lambda$0(Attachment.java:73)
	at com.ibm.tools.attach.target.Attachment$MethodRefsHolder$$Lambda$1.0000000000055240.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:638)
	at com.ibm.tools.attach.target.Attachment$MethodRefsHolder.<clinit>(Attachment.java:63)
	at com.ibm.tools.attach.target.Attachment.startLocalAgent(Attachment.java:392)

**Comment by pdbain-ibm** [comment]
First issue: startRemoteManagementAgent() in IBM Java8 takes a Properties object, but Java 9 and OpenJ9 Java 8 take a String argument.

**Comment by pdbain-ibm** [comment]
OpenJ9 Java 8 is using the same API as Java 9.  Updating the JPP flags seems to fix the problem.
