### ISSUE TITLE
Java 8 extended functional test failure VmArgumentTests_0

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#731]
```
FAILED: testXintAndOtherVmArguments
java.lang.AssertionError: argument missing: -showversion
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertNotNull(AssertJUnit.java:267)
	at org.openj9.test.vmArguments.VmArgumentTests.checkArgumentSequence(VmArgumentTests.java:1493)
	at org.openj9.test.vmArguments.VmArgumentTests.testXintAndOtherVmArguments(VmArgumentTests.java:979)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
```

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by DanHeidinga** [comment]
@pshipton Are these tests part of the nightly test run? If so, please add the priority:high label so we can get that build green.

**Comment by pdbain-ibm** [comment]
Is there  a link to the log files of the failing jobs for reference?  Thanks.

**Comment by pdbain-ibm** [comment]
It seems there is a difference between the IBM Java 8 launcher and OpenJ9's launcher: the former passes the "-showversion" argument on to the VM and the latter does not.

**Comment by smlambert** [comment]
Is that difference between IBM Java8 and OpenJ9 meant to exist?

**Comment by pshipton** [comment]
I'm not sure of the history. My guess is the launcher didn't handle -showversion in some earlier version of Java and support in the VM was added. Then the patch to the launcher was carried forward to Java 8 even though it is no longer required.

There is no reason the VM needs to implement -showversion. Its just calling sun.misc.Version.print(), which the launcher can also do.

**Comment by smlambert** [comment]
So the test is not valid and should be removed?

**Comment by pshipton** [comment]
The test is still valid for IBM Java 8 unless the launcher behavior is changed there. I did find some history, apparently somebody wanted -showversion to work from the VM option -Xoptionsfile (which btw is deprecated from Java 9 as its implemented by the launcher). This means the VM processing of -showversion should not be removed, at least while -Xoptionsfile is still supported (i.e. for Java 8).

I suggest we should replace the test with another test which puts -showversion in an -Xoptionsfile.

**Comment by pdbain-ibm** [comment]
> -Xoptionsfile (which btw is deprecated from Java 9 as its implemented by the launcher)
Please clarify: -Xoptionsfile is implemented in the VM.

For the record, the Java 9 launcher discards -showversion.  It looks like the VM's showversion code is never used in Java 9.

**Comment by pshipton** [comment]
Java 9 introduces a new option file operation which is implemented by the launcher (see the help output from running "java"). This obsoletes -Xoptionsfile so it is deprecated for Java 9 and may be disabled in a future version of (IBM) Java.

>  It looks like the VM's showversion code is never used in Java 9.

Unless you put -showversion in an -Xoptionsfile
