### ISSUE TITLE
Java 8 extended functional test failure testvmcheck

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#732]
```
Exception in thread "Thread-258" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : java.lang.invoke.MethodHandleImpl$ArrayAccessor
	at org.testng.Assert.fail(Assert.java:94)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:225)
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:177)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:108)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
```

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?

**Comment by theresa-m** [comment]
It looks like this is failing because two classes (`java.lang.invoke.ILGenMacros` and `java.util.PropertyPermission`) that are being loaded call `java.lang.invoke.MethodHandle.intrinsicName` which throw an error with `java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError`.

**Comment by DanHeidinga** [comment]
Thanks @theresa-m.  This looks like we're either missing some patches to the extensions repo or need to provide minimal stub implementations for the OJDK methods / class.

ILGenMacros is an OpenJ9 class that provides template helpers for the way JSR 292 MethodHandles get compiled so it shouldn't be directly calling `MethodHandle.instriniscName`.  It may appear to make a call to `instrinsicName` if there is a MH that has been created for that method.

Do you have a stacktrace that shows the `java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError` call?  That may help decide between patch vs stub.

**Comment by theresa-m** [comment]
This is the standard error output from `java.lang.invoke.ILGenMacros`:

```
Unexpected exception
java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
        at java.lang.invoke.MethodHandle.intrinsicName(MethodHandle.java:1110)
        at java.lang.invoke.MethodHandleImpl.makeIntrinsic(MethodHandleImpl.java:1371)
        at java.lang.invoke.MethodHandleImpl$ArrayAccessor.<clinit>(MethodHandleImpl.java:115)
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:297)
        at org.openj9.test.vmcheck.ClassloadingTester.main(ClassloadingTester.java:39)
Exception in thread "main" java.lang.AssertionError: Unexpected exceptionjava.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at org.testng.Assert.fail(Assert.java:94)
        at org.openj9.test.vmcheck.ClassloadingTester.main(ClassloadingTester.java:53)
<vm check: started (VM shutdown)>
  <vm check: Checking threads>
  <vm check: Checking 13 threads done>
  <vm check: Checking classes>
  <vm check: Checking 864 classes (0 obsolete) done>
  <vm check: Checking ROM classes>
  <vm check: Checking 864 ROM classes done>
  <vm check: Checking methods>
  <vm check: Checking 10177 methods done>
  <vm check: Checking ROM intern string nodes>
  <vm check: Checking 2345 ROM intern string nodes done>
  <vm check: Checking classloading constraints>
  <vm check: Checking classloading constraints, 1 nodes done>
<vm check: done>
```

and from `java.util.PropertyPermission`:

```
Unexpected exception
java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
        at java.lang.invoke.MethodHandle.intrinsicName(MethodHandle.java:1110)
        at java.lang.invoke.MethodHandleImpl.makeIntrinsic(MethodHandleImpl.java:1371)
        at java.lang.invoke.MethodHandleImpl.makeArrays(MethodHandleImpl.java:1429)
        at java.lang.invoke.MethodHandleImpl.access$000(MethodHandleImpl.java:49)
        at java.lang.invoke.MethodHandleImpl$Lazy.<clinit>(MethodHandleImpl.java:610)
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:297)
        at org.openj9.test.vmcheck.ClassloadingTester.main(ClassloadingTester.java:39)
Exception in thread "main" java.lang.AssertionError: Unexpected exceptionjava.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at org.testng.Assert.fail(Assert.java:94)
        at org.openj9.test.vmcheck.ClassloadingTester.main(ClassloadingTester.java:53)
<vm check: started (VM shutdown)>
  <vm check: Checking threads>
  <vm check: Checking 14 threads done>
  <vm check: Checking classes>
  <vm check: Checking 849 classes (0 obsolete) done>
  <vm check: Checking ROM classes>
  <vm check: Checking 849 ROM classes done>
  <vm check: Checking methods>
  <vm check: Checking 10130 methods done>
  <vm check: Checking ROM intern string nodes>
  <vm check: Checking 2345 ROM intern string nodes done>
  <vm check: Checking classloading constraints>
  <vm check: Checking classloading constraints, 1 nodes done>
<vm check: done
```

**Comment by DanHeidinga** [comment]
@theresa-m What is the test trying to do?  Our MethodHandle implementation will never attempt to load & initialize `MethodHandleImpl$Lazy.<clinit>` or `MethodHandleImpl$ArrayAccessor.<clinit>` on its own.  Is the test trying to load every class in rt.jar?

**Comment by theresa-m** [comment]
Yes.

**Comment by DanHeidinga** [comment]
We'll need to update the test to skip classes that are only there to be compile stubs.
