### ISSUE TITLE
DDR command shrc broken

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#7324]
DDR needs to be backward compatible so that the most recent version of DDR can be used to review old system core files.

The system core file was generated from pmz6480sr5fp27-20190104_01(SR5 FP27).  The DDR I am using was a recent one (build 428505, built on September 30,2019).  This is the error I got:

> shrc incache 0x000002005FB89028
!j9sharedclassconfig 0x00000050086D6B60

Error executing DDR command !shrc incache 0x000002005FB89028 : null
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:265)
        at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:175)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:830)
        at com.ibm.jvm.dtfjview.Session.execute(Session.java:785)
        at com.ibm.jvm.dtfjview.DTFJView.process(DTFJView.java:68)
        at com.ibm.jtc.service.tools.jdmpview.JdmpviewTool.process(JdmpviewTool.java:81)
        at com.ibm.jtc.service.store.Store.process(Store.java:131)
        at com.ibm.jtc.service.store.Store.processSimpleCommand(Store.java:86)
        at com.ibm.jtc.service.store.input.Tree.processObject(Tree.java:278)
        at com.ibm.jtc.service.store.input.Tree.process(Tree.java:217)
        at com.ibm.jtc.service.store.Store.runInteractive(Store.java:409)
        at com.ibm.jtc.service.store.Store.open(Store.java:308)
        at com.ibm.jtc.service.store.Store.main(Store.java:56)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9SharedClassCacheDescriptor._previousOffset_
        at com.ibm.j9ddr.vm29.pointer.generated.J9SharedClassCacheDescriptorPointer.previous(J9SharedClassCacheDescriptorPointer.java:243)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.dbgShrcReadConfig(ShrCCommand.java:1160)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.getSharedCacheMetadataStart(ShrCCommand.java:1282)
        at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.ShrCCommand.run(ShrCCommand.java:103)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
        at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
        at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
        at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
        ... 16 more

**Comment by hangshao0** [comment]
Will fix this
