### ISSUE TITLE
JTReg Test Failure: vm/verifier/VerifyProtectedConstructor.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7336]
Failure link
------------
Rebuild link: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/vm/verifier/VerifyProtectedConstructor.java&TARGET=jdk_custom_0
- test category: sanity openjdk
- OS/architecture: all
- version: 11, 13
- JVM: openj9 only

Optional info
-------------
- intermittent failure: no
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
```
15:50:40  java.lang.Exception: FAIL: should be a VerifyError for CF version 49
15:50:40  	at VerifyProtectedConstructor.main(VerifyProtectedConstructor.java:41)
15:50:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:50:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:50:40  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:50:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:50:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
15:50:40  	at java.base/java.lang.Thread.run(Thread.java:831)
```

This test is testing whether a protected constructor of a superclass can be accessed while not in the same package. On hotspot, doing this throws a VerifyError, but on J9 it does not.

**Comment by adam-thorpe** [comment]
Actually, just noticed test/jdk/vm tests don't exist for JDK13 is this intentional?

**Comment by pshipton** [comment]
Perhaps just moved. Looking for test/jdk/vm/verifier/VerifyProtectedConstructor in jdk13 I find it in 
test/hotspot/jtreg/runtime/verifier

**Comment by adam-thorpe** [comment]
Does this mean this test does not need to be ran against openj9 since its in a hotspot package? This test doesn't seem to be running in either hotspot or openj9 nightly sanity openjdk tests however.

**Comment by pshipton** [comment]
I expect some of the tests in Hotspot will apply to OpenJ9, and some will be Hotspot specific.
I think @sophia-guo was doing some investigation.
@smlambert @llxia

**Comment by sophia-guo** [comment]
This test was moved from jdk to hotpot ' 8219139: move hotspot tests from test/jdk/vm ' since 13.  I have a grinder to run all tests under 'test/hotspot/jtreg/runtime/'  against openj9. 

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/565/testReport/

Curious that it looks like this test didn't run at all. Try to look deeply to see if anything wrong.

**Comment by sophia-guo** [comment]
Running test under 'test/hotspot/jtreg/runtime/verifieri'  VerifyProtectedConstructor.java failed and got same failure report as posted in above comment:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/733/testReport/

```
Standard Error

java.lang.Exception: FAIL: should be a VerifyError for CF version 49
	at VerifyProtectedConstructor.main(VerifyProtectedConstructor.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:831)

JavaTest Message: Test threw exception: java.lang.Exception
JavaTest Message: shutting down test

    ```
No crash nor special options are used.
