### ISSUE TITLE
testvmcheck failing jdk11+ on TestClassRelationshipVerifier

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7362]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly/161
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_s390x_linux_Nightly/160
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/157
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/58
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/155
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/57
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/160
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_windows_Nightly/156
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/156
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_s390x_linux_Nightly/58
etc
testvmcheck_0
CR
testvmcheck_4
testvmcheck_6
XL
testvmcheck_1
testvmcheck_2
testvmcheck_5
```
Exception in thread "Thread-27" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : org.openj9.test.classRelationshipVerifier.TestClassRelationshipVerifier
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:251)
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:203)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
```

00:51:20  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_ppc64le_linux&TARGET=testvmcheck_0
00:51:20  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_ppc64le_linux&TARGET=testvmcheck_4
00:51:20  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_ppc64le_linux&TARGET=testvmcheck_6

**Comment by pshipton** [comment]
Dup of #7360
