### ISSUE TITLE
cmdLineTester_lockWordAlignment failures on jdk13 Unsupported class file major version 57

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7409]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/61
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/62
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_s390x_linux_Nightly/62
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_Nightly/63
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_windows_Nightly/62
cmdLineTester_lockWordAlignment_Object_i_0
cmdLineTester_lockWordAlignment_Object_ii_0
cmdLineTester_lockWordAlignment_Object_iii_0
cmdLineTester_lockWordAlignment_Object_d_0
```
Running test cmdLineTester_lockWordAlignment_Object_i_0 ...
===============================================
cmdLineTester_lockWordAlignment_Object_i_0 Start Time: Wed Oct  9 01:08:55 2019 Epoch Time (ms): 1570597735516
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 57
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at CreateTestObjectJar.main(CreateTestObjectJar.java:59)
*** Starting test suite: J9 Field Alignment Command-Line Option Tests ***
 
#######################################################
Running the tests with the following settings:
OBJECTTESTSBOOTCLASSPATH = --patch-module java.base=/home/jenkins/workspace/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/lockWordAlignment/object_i.jar
PRIV_FIELD1 = \W*private int i;
PRIV_FIELD2 = .*
PRIV_FIELD3 = .*
#######################################################
 
Testing: Check whether Object contains necessary private fields if any
Test start time: 2019/10/09 01:08:56 Eastern Standard Time
Running command: /home/jenkins/workspace/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/javap -p -bootclasspath /home/jenkins/workspace/Test_openjdk13_j9_extended.functional_ppc64le_linux_Nightly/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/lockWordAlignment/object_i.jar java/lang/Object
Time spent starting: 54 milliseconds
Time spent executing: 440 milliseconds
Test result: FAILED
Output from test:
 [ERR] Error: class not found: java/lang/Object
>> Success condition was not found: [Return code: 0]
>> Required condition was not found: [Output match: \W*private int i;]
>> Required condition was found: [Output match: .*]
>> Required condition was found: [Output match: .*]
```

**Comment by llxia** [comment]
It looks like a similar issue to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/261
asm needs to be upgraded to 7.1
