### ISSUE TITLE
worker-2 Cannot allocate memory

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7480]
Not sure if this is a real failure to allocate memory or not. If so, worker-2 may need a reboot.

https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_x86-64_mac/798
```
12:34:11  Starting building: Test_openjdk11_j9_sanity.functional_x86-64_mac_Nightly #168
12:34:11  Starting building: Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly #167
12:34:11  Starting building: Test_openjdk11_j9_extended.system_x86-64_mac_Nightly #166
12:34:11  Starting building: Test_openjdk11_j9_sanity.system_x86-64_mac_Nightly #166
[Pipeline] slackSend
12:36:00  Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: openj9, channel: #jenkins, color: danger, botUser: false, tokenCredentialId: 515a102c-4eee-4e66-9b05-fee104ea6fc2, notifyCommitters: false, iconEmoji: <empty>, username: <empty>
[Pipeline] node
12:36:04  Running on worker-2 in /home/jenkins/jenkins-agent/workspace/Pipeline_Build_Test_JDK11_x86-64_mac
[Pipeline] {
[Pipeline] step
12:36:24  [Set GitHub commit status (universal)] FAILURE on repos [GHRepository@7102b2df[description=Eclipse OpenJ9: A Java Virtual Machine for OpenJDK that's optimized for small footprint, fast start-up, and high throughput.   Builds on Eclipse OMR (https://github.com/eclipse/omr) and combines with the Extensions for OpenJDK for OpenJ9 repo.,homepage=,name=openj9,fork=false,archived=false,size=62500,milestones={},language=Java,commits={},source=<null>,parent=<null>,responseHeaderFields={null=[HTTP/1.1 200 OK], Access-Control-Allow-Origin=[*], Access-Control-Expose-Headers=[ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type], Cache-Control=[private, max-age=60, s-maxage=60], Content-Encoding=[gzip], Content-Security-Policy=[default-src 'none'], Content-Type=[application/json; charset=utf-8], Date=[Wed, 16 Oct 2019 16:36:20 GMT], ETag=[W/"19125c3941519155e2cbf12d5036e10c"], Last-Modified=[Wed, 16 Oct 2019 15:13:10 GMT], OkHttp-Received-Millis=[1571243780362], OkHttp-Response-Source=[CONDITIONAL_CACHE 200], OkHttp-Selected-Protocol=[http/1.1], OkHttp-Sent-Millis=[1571243780250], Referrer-Policy=[origin-when-cross-origin, strict-origin-when-cross-origin], Server=[GitHub.com], Status=[200 OK], Strict-Transport-Security=[max-age=31536000; includeSubdomains; preload], Transfer-Encoding=[chunked], Vary=[Accept, Authorization, Cookie, X-GitHub-OTP], X-Accepted-OAuth-Scopes=[repo], X-Content-Type-Options=[nosniff], X-Frame-Options=[deny], X-GitHub-Media-Type=[github.v3; format=json], X-GitHub-Request-Id=[9138:4862:1051DD4:215DB8A:5DA74704], X-OAuth-Scopes=[admin:repo_hook, repo, repo:status], X-RateLimit-Limit=[5000], X-RateLimit-Remaining=[4938], X-RateLimit-Reset=[1571247046], X-XSS-Protection=[1; mode=block]},url=https://api.github.com/repos/eclipse/openj9,id=101408117]] (sha:94c6cde) with context:Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly
12:36:24  Setting commit status on GitHub for https://github.com/eclipse/openj9/commit/94c6cde79bfa25d8c306acc4bc7bef080fc717ee
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: Cannot allocate memory
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.FileChannelImpl.write(Unknown Source)
	at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
	at java.nio.channels.Channels.writeFully(Unknown Source)
	at java.nio.channels.Channels.access$000(Unknown Source)
	at java.nio.channels.Channels$1.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
	at sun.nio.cs.StreamEncoder.flush(Unknown Source)
	at java.io.OutputStreamWriter.flush(Unknown Source)
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:75)
Caused: com.thoughtworks.xstream.io.StreamException:  : Cannot allocate memory
	at com.thoughtworks.xstream.core.util.QuickWriter.flush(QuickWriter.java:77)
	at com.thoughtworks.xstream.core.util.QuickWriter.write(QuickWriter.java:37)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.endNode(PrettyPrintWriter.java:317)
	at com.thoughtworks.xstream.io.WriterWrapper.endNode(WriterWrapper.java:37)
	at com.thoughtworks.xstream.io.path.PathTrackingWriter.endNode(PathTrackingWriter.java:48)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:65)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.util.XStream2.toXMLUTF8(XStream2.java:313)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:34)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1143)
	at hudson.BulkChange.commit(BulkChange.java:98)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1475)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:458)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
I suspect this was caused by a jenkins restart.

**Comment by fjeremic** [comment]
Another two instances of this issue are seen in #8110:
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Personal/417/console
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64le_linux_xl_Personal/36/console

@pshipton should we reopen this?

**Comment by pshipton** [comment]
Sure we can reopen it. I think things like this can occur when too many jenkins jobs are trying to start at the same time. They all start on master and afaik there is no queuing mechanism on master, only once the job has been assigned to a worker and a Node. We've created a new repo https://github.com/eclipse/openj9-jenkins and I want to move the jenkins code that needs to load on master to this repo. This should greatly reduce the work required for the git fetch as the repo will be quite a bit smaller. Perhaps only three files, but we need to decide exactly how much code needs to move to the jenkins repo.

**Comment by pshipton** [comment]
I don't expect any work on this to occur until the new year.
