### ISSUE TITLE
Windows IA32 80 SVT_Apps_1.SVT_Octane : NPE at java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286) 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7514]
Failure link
------------

```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pwi3280sr6-20191014_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 x86-32-Bit 20191018_430373 (JIT enabled, AOT enabled)
OpenJ9   - 43f607d
OMR      - 305c6c4
IBM      - ae1a7e3)
JCL - 20191009_01 based on Oracle jdk8u231-b10
```

Optional info
-------------

- intermittent failure (yes): 

Failure output (captured from console output)
---------------------------------------------

```
Exception in thread "main" java.lang.NullPointerException
	at java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286)
	at java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2215)
	at java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2253)
	at jdk.internal.dynalink.ChainedCallSite.makePruneAndInvokeMethod(ChainedCallSite.java:240)
	at jdk.internal.dynalink.ChainedCallSite.relinkInternal(ChainedCallSite.java:196)
	at jdk.internal.dynalink.ChainedCallSite.relink(ChainedCallSite.java:161)
	at jdk.nashorn.internal.runtime.linker.LinkerCallSite.relink(LinkerCallSite.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:297)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
	at java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:123)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:371)
	at jdk.nashorn.internal.scripts.Script$Recompilation$9$5859$base.:scopeCall(file:/W:/javatest/lib/octane/base.js)
	at jdk.nashorn.internal.scripts.Script$Recompilation$9$5859$base.RunSuites#RunStep(file:/W:/javatest/lib/octane/base.js:150)
	at jdk.nashorn.internal.scripts.Script$Recompilation$8$5614AA$base.RunSuites(file:/W:/javatest/lib/octane/base.js:173)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:73)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:506)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:405)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$200(NashornScriptEngine.java:85)
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:522)
	at javax.script.CompiledScript.eval(CompiledScript.java:117)
	at com.ibm.octane.test.Octane.runTest(Octane.java:166)
	at com.ibm.octane.test.Octane.runAllTests(Octane.java:114)
	at com.ibm.octane.test.Octane.main(Octane.java:59)
```

Not reproduced in a 10x grinder.

**Comment by JasonFengJ9** [comment]
```
+-------------+--------------------------------------------------------------------------------+
| 01:16:33 AM | richards                                                                       |
+-------------+--------------------------------------------------------------------------------+
| 01:16:33 AM | Running test: richards.js                                                      |
| 01:16:33 AM | Run path defined                                                               |
| 01:16:33 AM | Run path js bytes defined                                                      |
| 01:16:33 AM | as null? false                                                                 |
| 01:16:34 AM | Nashorn CompiledScript object string:                                          |
| 01:16:34 AM | jdk.nashorn.api.scripting.NashornScriptEngine$3@93a895f2                       |
| 01:16:34 AM | Loading dependencies for richards                                              |
| 01:16:34 AM | Loading dependency: load('W:\\javatest\\lib/octane//base.js');                 |
| 01:16:34 AM | Loading dependency: load('W:\\javatest\\lib/octane//richards.js');             |
| 01:16:35 AM | Loaded dependencies for: richards                                              |
| 01:16:45 AM | Richards:                                                                      |
| 01:16:45 AM |     Score: 15.5                                                                |
| 01:16:45 AM |     Duration: 11484ms                                    Exception in thread "main" java.lang.NullPointerException
	at java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286)
	at java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2215)
	at java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2253)
	at jdk.internal.dynalink.ChainedCallSite.makePruneAndInvokeMethod(ChainedCallSite.java:240)
	at jdk.internal.dynalink.ChainedCallSite.relinkInternal(ChainedCallSite.java:196)
	at jdk.internal.dynalink.ChainedCallSite.relink(ChainedCallSite.java:161)
	at jdk.nashorn.internal.runtime.linker.LinkerCallSite.relink(LinkerCallSite.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:297)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:300)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
	at java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:123)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:371)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:80)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.InvokeExactHandle.invokeExact_thunkArchetype_X(InvokeExactHandle.java:87)
	at java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
	at java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
	at jdk.nashorn.internal.scripts.Script$Recompilation$78$12471$base.RunStep#RunNextBenchmark(file:/W:/javatest/lib/octane/base.js:375)
	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
	at java.lang.invoke.InvokeExactHandle.invokeExact_thunkArche                      |
| 01:16:45 AM | Run path: W:\\javatest\\lib/octane//run.js                                     |
+-------------+--------------------------------------------------------------------------------+
| 01:16:45 AM | deltablue                                                                      |
+-------------+--------------------------------------------------------------------------------+
| 01:16:45 AM | Running test: deltablue.js                                                     |
| 01:16:45 AM | Run path defined                                                               |
| 01:16:45 AM | Run path js bytes defined                                                      |
| 01:16:45 AM | as null? false                                                                 |
| 01:16:45 AM | Nashorn CompiledScript object string:                                          |
| 01:16:45 AM | jdk.nashorn.api.scripting.NashornScriptEngine$3@35767831                       |
| 01:16:45 AM | Loading dependencies for deltablue                                             |
| 01:16:45 AM | Loading dependency: load('W:\\javatest\\lib/octane//base.js');                 |
| 01:16:45 AM | Loading dependency: load('W:\\javatest\\lib/octane//deltablue.js');            |
| 01:16:46 AM | Loaded dependencies for: deltablue                                             |

>> 2019 Tue Nov 5 01:17:07 check for undetected javacore files. Looking in the logdir
>> 2019 Tue Nov 5 01:17:07 check for undetected javacore files. Looking in the coredir
>> 2019 Tue Nov 5 01:17:07 check for undetected dr watson files
>> 2019 Tue Nov 5 01:17:07 check for undetected core files
>> 2019 Tue Nov 5 01:17:07 check for undetected heap files
>> 2019 Tue Nov 5 01:17:07 Archiving Trace
>> 2019 Tue Nov 5 01:17:07 archiveTraceFiles: logdir is C:\temp\bld_431970\octane.sanity\620274496\20191105-011629
>> 2019 Tue Nov 5 01:17:07 archiveTraceFiles: tracedir is C:\temp\bld_431970\octane.sanity\620274496\20191105-011629\trace-191105-011629
```

**Comment by DanHeidinga** [comment]
fyi @andrewcraik @liqunl

**Comment by andrewcraik** [comment]
@liqunl - will this be fixed by any of your recent changes?

**Comment by andrewcraik** [comment]
@JasonFengJ9 any chance you could try with the latest OpenJ9 as there have been a few fixes recently and I'd hate to investigate a duplicate. Would be nice to know if the latest OpenJ9 is functionally correct or not.

**Comment by liqunl** [comment]
It can be related to #7604, we need to try the latest build.

**Comment by JasonFengJ9** [comment]
> Would be nice to know if the latest OpenJ9 is functionally correct or not.

It is in latest `OpenJ9` acceptance build.
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pwa6480sr6-20191024_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit 20191105_431970 (JIT enabled, AOT enabled)
OpenJ9   - 0a53be1
OMR      - 30b107a
IBM      - ae1a7e3)
JCL - 20191016_01 based on Oracle jdk8u231-b10
```

100x grinder didn't reproduce.

**Comment by andrewcraik** [comment]
@JasonFengJ9 - looks like works on later build - I will close this - please re-open if there are additional concerns.

**Comment by pshipton** [comment]
@andrewcraik I think it's highly intermittent. It's tracked by internal defect 142512.

**Comment by andrewcraik** [comment]
hmm ok - well if we get more examples from adopt/openj9 reopen this one and I'll keep an eye on the other that you mentioned too - see if we can get any data to help find the solution...

**Comment by pshipton** [comment]
I don't think it's ever been seen in an OpenJ9 build. All the failures reported here appear to be from IBM Java builds.
