### ISSUE TITLE
MacOS J9 11.0.5 Segmentation fault

### ISSUE THREAD

**Issue by planetf1** [eclipse/openj9#7539]
Java -version output
--------------------

penjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

Summary of problem
------------------

One of our components in the open source 'egeria' project https://github.com/odpi/egeria hits a segmentation fault when using 11.0.5 on macOS catalina (10.15.1 beta 19B77a) but works correctly under 11.04 openj9 (from adoptopenjdk.net) and also 11.0.5 hotspot (also from adoptopenjdk.net)

Diagnostic files
----------------

The log here is of course egeria specific but in case it helps:
```
  java egeria.sh start
Starting multiple egeria platforms in bg
➜  java  ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.1.6.RELEASE) ::

 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.1.6.RELEASE) ::

 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.1.6.RELEASE) ::

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-distribution/open-metadata-assemblies/target/egeria-1.1-SNAPSHOT-omag-server/servers/omag-server-1.1-SNAPSHOT/server-chassis-spring-1.1-SNAPSHOT.jar!/BOOT-INF/lib/groovy-2.4.15-indy.jar!/) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-distribution/open-metadata-assemblies/target/egeria-1.1-SNAPSHOT-omag-server/servers/omag-server-1.1-SNAPSHOT/server-chassis-spring-1.1-SNAPSHOT.jar!/BOOT-INF/lib/groovy-2.4.15-indy.jar!/) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-distribution/open-metadata-assemblies/target/egeria-1.1-SNAPSHOT-omag-server/servers/omag-server-1.1-SNAPSHOT/server-chassis-spring-1.1-SNAPSHOT.jar!/BOOT-INF/lib/groovy-2.4.15-indy.jar!/) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00000000034A20A0 Handler2=0000000002356C20 InaccessibleAddress=0000000000000000
RDI=0000000000000000 RSI=0000000700072548 RAX=0000000701D6E380 RBX=00000007FF60BAD0
RCX=00000007FFA059A8 RDX=0000000700046100 R8=00000007FFA05FC8 R9=00000007FF60B898
R10=00000007FFA059A8 R11=0000000700046100 R12=0000000700046100 R13=0000000014BCE046
R14=00000007000002C0 R15=00000007FF60B8B0
RIP=0000000000000000 GS=0000 FS=0000 RSP=00000000055765D8
RFlags=0000000000010297 CS=002B RBP=0000000005489A00 ERR=0000000000000014
TRAPNO=000000140000000E CPU=0000000000140000 FAULTVADDR=0000000000000000
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM1 00000000df000000 (f: 3741319168.000000, d: 1.848457e-314)
XMM2 000000005f000000 (f: 1593835520.000000, d: 7.874594e-315)
XMM3 3f53bf5ee6000000 (f: 3858759680.000000, d: 1.205294e-03)
XMM4 bea85a6ffceea275 (f: 4243497472.000000, d: -7.257840e-07)
XMM5 bfbda72000000000 (f: 0.000000, d: -1.158314e-01)
XMM6 000fffffffffffff (f: 4294967296.000000, d: 2.225074e-308)
XMM7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
XMM8 0000000041040000 (f: 1090781184.000000, d: 5.389175e-315)
XMM9 0000000041040000 (f: 1090781184.000000, d: 5.389175e-315)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20191016_371 (Mac OS X 10.15.1)
CPU=amd64 (8 logical CPUs) (0x400000000 RAM)
----------- Stack Backtrace -----------
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2019/10/21 18:51:15 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jonesn/IdeaProjects/egeria/core.20191021.185115.14288.0001.dmp' in response to an event
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:577)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'groovyMarkupConfigurer' defined in class path resource [org/springframework/boot/autoconfigure/groovy/template/GroovyTemplateAutoConfiguration$GroovyMarkupConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$198.0000000000000000.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.main(OMAGServerPlatform.java:60)
	... 8 more
Caused by: java.lang.NullPointerException
	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
	at org.codehaus.groovy.control.customizers.ASTTransformationCustomizer$_setAnnotationParameters_closure1.doCall(ASTTransformationCustomizer.groovy:281)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5361)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2202)
	at org.codehaus.groovy.runtime.dgm$164.doMethodInvoke(Unknown Source)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:521)
	at java.base/java.lang.invoke.MethodHandles$CatchHelper.helper(MethodHandles.java:4487)
	at java.base/java.lang.invoke.ReceiverBoundHandle.invokeExact_thunkArchetype_L(ReceiverBoundHandle.java:168)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.codehaus.groovy.control.customizers.ASTTransformationCustomizer.setAnnotationParameters(ASTTransformationCustomizer.groovy:262)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:521)
	at java.base/java.lang.invoke.MethodHandles$CatchHelper.helper(MethodHandles.java:4487)
	at java.base/java.lang.invoke.ReceiverBoundHandle.invokeExact_thunkArchetype_L(ReceiverBoundHandle.java:168)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.codehaus.groovy.control.customizers.ASTTransformationCustomizer.<init>(ASTTransformationCustomizer.groovy:184)
	at org.codehaus.groovy.control.customizers.ASTTransformationCustomizer.<init>(ASTTransformationCustomizer.groovy:188)
	at groovy.text.markup.MarkupTemplateEngine.<init>(MarkupTemplateEngine.java:95)
	at org.springframework.web.servlet.view.groovy.GroovyMarkupConfigurer.createTemplateEngine(GroovyMarkupConfigurer.java:159)
	at org.springframework.web.servlet.view.groovy.GroovyMarkupConfigurer.afterPropertiesSet(GroovyMarkupConfigurer.java:152)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 25 more

No OMAG server in startup configuration
Mon Oct 21 18:51:20 BST 2019 OMAG server platform ready for more configurations
JVMDUMP012E Error in System dump: The core file created by child process with pid = 14377 was not found. Expected to find core file with name "/cores/core.14377"
JVMDUMP032I JVM requested Java dump using '/Users/jonesn/IdeaProjects/egeria/javacore.20191021.185115.14288.0002.txt' in response to an event
JVMDUMP010I Java dump written to /Users/jonesn/IdeaProjects/egeria/javacore.20191021.185115.14288.0002.txt
JVMDUMP032I JVM requested Snap dump using '/Users/jonesn/IdeaProjects/egeria/Snap.20191021.185115.14288.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/jonesn/IdeaProjects/egeria/Snap.20191021.185115.14288.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/Users/jonesn/IdeaProjects/egeria/jitdump.20191021.185115.14288.0004.dmp'
JVMDUMP010I JIT dump written to /Users/jonesn/IdeaProjects/egeria/jitdump.20191021.185115.14288.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
```

[macegeria.zip](https://github.com/eclipse/openj9/files/3752240/macegeria.zip)

**Comment by planetf1** [comment]
Unfortunately I don't have any specific test code, it's from a larger application with a typical complexity of moving parts (especially spring - which is slightly back level).

**Comment by planetf1** [comment]
Note the reflection warning is known ( https://github.com/odpi/egeria/issues/1156 )

**Comment by JamesKingdon** [comment]
I haven't looked at a Java11 crash before, nor a Mac one. It seems 'odd', the javacore suggests we dereferenced null, but also that we jumped to 0. Looks like it was the main thread, and the RAS is unable to provide the stack:

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x0000000005489A00, omrthread_t:0x00007F9B2F803A50, java/lang/Thread:0x00000007000485B0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0xA46CC, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x0000700007AB6000, to:0x0000700007B36000, size:0x80000)
3XMCPUTIME               CPU usage total: 9.899552000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=26026368 (0x18D2180)
3XMTHREADINFO3           Java callstack:
1INTERNAL                    Unable to walk in-flight data on call stack
3XMTHREADINFO3           No native callstack available for this thread
```

**Comment by DanHeidinga** [comment]
This part of the stacktrace makes me suspect a jit issue:
```
Caused by: java.lang.NullPointerException: null
at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404) ~[na:na]
```

Likely the same as https://github.com/eclipse/openj9/issues/7604

fyi @liqunl @andrewcraik

**Comment by liqunl** [comment]
This is a dup of #7604, @DanHeidinga @andrewcraik Can we close it?

**Comment by planetf1** [comment]
I'd be happy to test again too - where would I find a build? (normally I use the adoptopenjdk distributed releases)

**Comment by andrewcraik** [comment]
@planetf1 so the fix was merged yesterday so if you want to pick up an adoptopenjdk nightly we'll need to wait for the next build which _should_ include it. I checked the October 30 build which is the latest nightly on the adopt website and it does not yet have the fix. The adopt nightly would be the best source of a binary with the fix.

**Comment by planetf1** [comment]
Thanks... I'll keep an eye out for the 'nightly (presumably there was many days gap as nothing merged?)

**Comment by andrewcraik** [comment]
The gap would have likely been due to a release or some other activity at adoptopenjdk needing the machines. OpenJ9 merges PRs pretty much every day.

**Comment by planetf1** [comment]
There's an Oct 31 nightly now... https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

**Comment by liqunl** [comment]
@planetf1 The linux x64 build has the fix, but the Mac OS one doesn't. Please wait for the next Mac OS build.

**Comment by andrewcraik** [comment]
@planetf1 have you had a chance to see if the newer build containing the change from @liqunl has fixed the problem? It would be nice to close this issue if the problem has indeed been fixed... Thanks again for the report and help with the investigation.

**Comment by planetf1** [comment]
I don't have a new build yet... I had been awaiting the adoptopenjdk update? (11.0.6?). At the time there were no nightly builds available, though I see these have restarted. If 11.0.6 is soon it would be more efficient for me to wait, but if it's going to be > week or two I'll try and find a slot to test with the nightly?

**Comment by pshipton** [comment]
@planetf1 11.0.6 is not until about Jan 20.

**Comment by pshipton** [comment]
We'll also have a milestone build for 11.0.6 around Dec 18, although it won't contain any of the security fixes which will be include in the final build.

**Comment by planetf1** [comment]
Ok - in that case, do the nightlies at https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9 contain the fix?

**Comment by pshipton** [comment]
> do the nightlies at https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9 contain the fix?

They do.

**Comment by planetf1** [comment]
Thanks. I've gone with 27 Nov (macOS) and 26 Nov (linux x64) . An initial build was successful. I'll run with this through today.

**Comment by planetf1** [comment]
I have not seen this error now on either macOS, WIndows or Linux - using the 11.0.6 nightlies. But I am also not seeing on 11.0.5 now. I think all we can do at this point is close.
