### ISSUE TITLE
win2012r2-x86-2 is offline from jenkins

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7545]
Restarting the jenkins agent doesn't work.
```
ssh: connect to host 169.55.150.148 port 22: Operation timed out
ERROR: Unable to launch the agent for win2012r2-x86-2
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin pls try a reboot

**Comment by AdamBrousseau** [comment]
Done

**Comment by pshipton** [comment]
online now.
