### ISSUE TITLE
NPE at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:238)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7562]
Failure link
------------

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pwa6480sr6-20191014_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows Server 2016 amd64-64-Bit 20191022_430761 (JIT enabled, AOT enabled)
OpenJ9   - dcf5cce
OMR      - 20b4827
IBM      - ae1a7e3)
JCL - 20191009_01 based on Oracle jdk8u231-b10

Optional info
-------------

- intermittent failure (yes): 

Failure output (captured from console output)
---------------------------------------------

```
j> 18:57:58 20191022 18:57:57 Pooled Work Thread Factory INFO: Thread Pool Exhaustion Behaviour: Grow Pool
j> 18:57:58 20191022 18:57:57 ConfigurationReporter INFO: Change detected
j> 18:58:00 20191022 18:57:59 Execution Timer INFO: Execution Timer started
j> 18:58:00 20191022 18:57:59 Thread Control Engine INFO: Starting JobSet Primary
j> 18:58:28 20191022 18:58:27 <Primary|SimpleDriver|com.ibm.jtc.svt.lambda.TestLambdaDefaultsAndStatics.testAbstractedDefaultMethod|8|Default Invocant> ERROR: Test testAbstractedDefaultMethod(com.ibm.jtc.svt.lambda.TestLambdaDefaultsAndStatics) reported an error
j> 18:58:28 Throwable trace:
j> 18:58:28 java.lang.BootstrapMethodError: java.lang.NullPointerException
j> 18:58:28 	at com.ibm.jtc.svt.lambda.TestLambdaDefaultsAndStatics$LocalShareTrade.<init>(TestLambdaDefaultsAndStatics.java:133)
j> 18:58:28 	at com.ibm.jtc.svt.lambda.TestLambdaDefaultsAndStatics.testAbstractedDefaultMethod(TestLambdaDefaultsAndStatics.java:245)
j> 18:58:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
j> 18:58:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
j> 18:58:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 18:58:28 	at java.lang.reflect.Method.invoke(Method.java:508)
j> 18:58:28 	at junit.framework.TestCase.runTest(TestCase.java:168)
j> 18:58:28 	at junit.framework.TestCase.runBare(TestCase.java:134)
j> 18:58:28 	at junit.framework.TestResult$1.protect(TestResult.java:110)
j> 18:58:28 	at junit.framework.TestResult.runProtected(TestResult.java:128)
j> 18:58:28 	at junit.framework.TestResult.run(TestResult.java:113)
j> 18:58:28 	at junit.framework.TestCase.run(TestCase.java:124)
j> 18:58:28 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
j> 18:58:28 	at junit.framework.TestSuite.run(TestSuite.java:238)
j> 18:58:28 	at com.ibm.jtc.test.jltf.workunitadapters.JUnitWorkUnit.runWork(JUnitWorkUnit.java:370)
j> 18:58:28 	at com.ibm.jtc.test.jltf.threads.WorkUnitRunner.run(WorkUnitRunner.java:113)
j> 18:58:28 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.runWork(PooledRunnable.java:170)
j> 18:58:28 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:136)
j> 18:58:28 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 18:58:28 	at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 18:58:28 Caused by: java.lang.NullPointerException
j> 18:58:28 	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:238)
j> 18:58:28 	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:315)
j> 18:58:28 	at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
j> 18:58:28 	at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
j> 18:58:28 	at java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:898)
j> 18:58:28 	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:949)
j> 18:58:28 	... 20 more
```

10x grinder all passed.

**Comment by JasonFengJ9** [comment]
```
STF 01:56:51.316 - Running: /home/jenkins/workspace/Test_openjdk13_j9_extended.system_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -version
openjdk version "13.0.1-internal" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1-internal+0-adhoc.jenkins.BuildJDK13ppc64aixNightly)
Eclipse OpenJ9 VM (build ibm_sdk-55706fd6a1, JRE 13 AIX ppc64-64-Bit Compressed References 20191211_172 (JIT enabled, AOT enabled)
OpenJ9   - 55706fd6a1
OMR      - 209aa965c
JCL      - cca5f2e86a based on jdk-13.0.1+9)

MTM4 stderr Exception in thread "main" java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
MTM4 stderr 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
MTM4 stderr 	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:855)
MTM4 stderr 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1077)
MTM4 stderr 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
MTM4 stderr 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
MTM4 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:89)
MTM4 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:86)
MTM4 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:734)
MTM4 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:86)
MTM4 stderr 	at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
MTM4 stderr 	at java.base/java.lang.Class.newInstance(Class.java:2089)
MTM4 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)
MTM4 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)
MTM4 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
MTM4 stderr 	at java.base/java.text.NumberFormat.getInstance(NumberFormat.java:951)
MTM4 stderr 	at java.base/java.text.NumberFormat.getIntegerInstance(NumberFormat.java:540)
MTM4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.logMessage(LoaderSlaveMultiThreadMultiCL.java:118)
MTM4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.run(LoaderSlaveMultiThreadMultiCL.java:102)
MTM4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.main(LoaderSlaveMultiThreadMultiCL.java:59)
MTM4 stderr Caused by: java.lang.BootstrapMethodError: java.lang.NullPointerException
MTM4 stderr 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:887)
MTM4 stderr 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:768)
MTM4 stderr 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1186)
MTM4 stderr 	at java.base/java.lang.Class.forName(Class.java:489)
MTM4 stderr 	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:853)
MTM4 stderr 	... 17 more
MTM4 stderr Caused by: java.lang.NullPointerException
MTM4 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:221)
MTM4 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MTM4 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:1076)
MTM4 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1200)
MTM4 stderr 	... 22 more
```

**Comment by JasonFengJ9** [comment]
From an internal build `openjdk11_j9_extended.system_ppc64_aix SharedClasses.SCM01.MultiThread_0`
```
22:30:13  openjdk version "11.0.7-internal" 2020-04-14
22:30:13  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
22:30:13  Eclipse OpenJ9 VM (build ibm_sdk-df22f7ee4f, JRE 11 AIX ppc64-64-Bit Compressed References 20200220_325 (JIT enabled, AOT enabled)
22:30:13  OpenJ9   - df22f7ee4f
22:30:13  OMR      - 83ba4e770
22:30:13  JCL      - 75dba088c45 based on jdk-11.0.7+3)

MT3 stderr Exception in thread "main" java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
MT3 stderr 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
MT3 stderr 	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:853)
MT3 stderr 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1076)
MT3 stderr 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
MT3 stderr 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
MT3 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:89)
MT3 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:86)
MT3 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:734)
MT3 stderr 	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:86)
MT3 stderr 	at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
MT3 stderr 	at java.base/java.lang.Class.newInstance(Class.java:2084)
MT3 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)
MT3 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)
MT3 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
MT3 stderr 	at java.base/java.text.NumberFormat.getInstance(NumberFormat.java:905)
MT3 stderr 	at java.base/java.text.NumberFormat.getIntegerInstance(NumberFormat.java:537)
MT3 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.logMessage(LoaderSlaveMultiThread.java:119)
MT3 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.run(LoaderSlaveMultiThread.java:103)
MT3 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.main(LoaderSlaveMultiThread.java:57)
MT3 stderr Caused by: java.lang.BootstrapMethodError: java.lang.NullPointerException
MT3 stderr 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:865)
MT3 stderr 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:746)
MT3 stderr 	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1183)
MT3 stderr 	at java.base/java.lang.Class.forName(Class.java:484)
MT3 stderr 	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:851)
MT3 stderr 	... 17 more
MT3 stderr Caused by: java.lang.NullPointerException
MT3 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
MT3 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MT3 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:969)
MT3 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
MT3 stderr 	... 22 more
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
03:00:53  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=ppc64_aix&TARGET=SharedClasses.SCM01.MultiThread_0

**Comment by JasonFengJ9** [comment]
Another occurrence at an internal build `openjdk11_j9_extended.system_ppc64_aix` 
```
SharedClasses.SCM01.MultiThreadMultiCL_0_FAILED
MTM1 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
MTM1 stderr 	at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.newResourceBundle(ResourceBundle.java:3572)
MTM1 stderr 	at java.base/java.util.ResourceBundle$1.newResourceBundle(ResourceBundle.java:416)
MTM1 stderr 	at java.base/sun.util.resources.Bundles.findBundleOf(Bundles.java:209)
MTM1 stderr 	at java.base/sun.util.resources.Bundles.findBundleOf(Bundles.java:160)
MTM1 stderr 	at java.base/sun.util.resources.Bundles.findBundleOf(Bundles.java:160)
MTM1 stderr 	at java.base/sun.util.resources.Bundles.loadBundleOf(Bundles.java:145)
MTM1 stderr 	at java.base/sun.util.resources.Bundles.of(Bundles.java:106)
MTM1 stderr 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:185)
MTM1 stderr 	at java.base/sun.util.resources.LocaleData$1.run(LocaleData.java:182)
MTM1 stderr 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
MTM1 stderr 	at java.base/sun.util.resources.LocaleData.getBundle(LocaleData.java:182)
MTM1 stderr 	at java.base/sun.util.resources.LocaleData.getNumberFormatData(LocaleData.java:178)
MTM1 stderr 	at java.base/sun.util.locale.provider.LocaleResources.getNumberPatterns(LocaleResources.java:472)
MTM1 stderr 	at java.base/sun.util.locale.provider.NumberFormatProviderImpl.getInstance(NumberFormatProviderImpl.java:182)
MTM1 stderr 	at java.base/sun.util.locale.provider.NumberFormatProviderImpl.getIntegerInstance(NumberFormatProviderImpl.java:131)
MTM1 stderr 	at java.base/java.text.NumberFormat.getInstance(NumberFormat.java:930)
MTM1 stderr 	at java.base/java.text.NumberFormat.getInstance(NumberFormat.java:907)
MTM1 stderr 	at java.base/java.text.NumberFormat.getIntegerInstance(NumberFormat.java:537)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.logMessage(LoaderSlaveMultiThreadMultiCL.java:118)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.run(LoaderSlaveMultiThreadMultiCL.java:102)
MTM1 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThreadMultiCL.main(LoaderSlaveMultiThreadMultiCL.java:59)
MTM1 stderr Caused by: java.lang.NullPointerException
MTM1 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
MTM1 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:969)
MTM1 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
MTM1 stderr 	... 21 more
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
03:29:46  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=ppc64_aix&TARGET=HCRLateAttachWorkload_previewEnabled_0
03:29:46  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=ppc64_aix&TARGET=SharedClasses.SCM01.MultiThreadMultiCL_0

**Comment by pshipton** [comment]
@DanHeidinga should someone be looking at this?

**Comment by DanHeidinga** [comment]
Moving this forward as we haven't seen it for almost a month.  Hopefully we can reproduce it next milestone and get it sorted out.  My gut says this is likely to be a jit issue but we'd need cores to confirm

**Comment by pshipton** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/6748

19:54:56  openjdk version "11.0.7" 2020-04-14
19:54:56  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+8-202003202340)
19:54:56  Eclipse OpenJ9 VM AdoptOpenJDK (build master-b138dda, JRE 11 AIX ppc64-64-Bit Compressed References 20200320_531 (JIT enabled, AOT enabled)
19:54:56  OpenJ9   - b138dda
19:54:56  OMR      - 884db4d
19:54:56  JCL      - d1ca0eb based on jdk-11.0.7+8)

SharedClasses.SCM01.MultiThread_0
20:07:56  STF 20:07:55.614 - +------ Step 7 - Start java processes using LoaderSlaveMultiThread
```
20:07:56  STF 20:07:55.730 - Monitoring processes: MT1 MT2 MT3 MT4 MT5
20:08:13  MT3 20:08:10 >> --> Threads 0 to 300 <--
20:08:21  MT1 20:08:17 >> --> Threads 0 to 300 <--
20:08:21  MT5 20:08:16 >> --> Threads 0 to 300 <--
20:08:24  MT2 20:08:09 >> --> Threads 0 to 300 <--
20:08:36  MT4 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
20:08:36  MT4 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getCalendarProvider(JRELocaleProviderAdapter.java:349)
20:08:36  MT4 stderr 	at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getLocaleServiceProvider(JRELocaleProviderAdapter.java:115)
20:08:36  MT4 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:281)
20:08:36  MT4 stderr 	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
20:08:36  MT4 stderr 	at java.base/java.util.Calendar.createCalendar(Calendar.java:1692)
20:08:36  MT4 stderr 	at java.base/java.util.Calendar.getInstance(Calendar.java:1629)
20:08:36  MT4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.logMessage(LoaderSlaveMultiThread.java:121)
20:08:36  MT4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.run(LoaderSlaveMultiThread.java:103)
20:08:36  MT4 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.main(LoaderSlaveMultiThread.java:57)
20:08:36  MT4 stderr Caused by: java.lang.NullPointerException
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:231)
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:969)
20:08:36  MT4 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
20:08:36  MT4 stderr 	... 9 more
```

**Comment by DanHeidinga** [comment]
Has this occurred recently?  @JasonFengJ9 

If it doesn't occur anymore, we can close it for now

**Comment by JasonFengJ9** [comment]
@DanHeidinga I haven't seen this for a while, closing.

**Comment by roded** [comment]
We've encountered the same issue on z/OS:

`M9RODED:/u/m9roded: >/usr/lpp/java/current_64/bin/java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pmz6480sr6-20191107_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20191106_432135 (JIT enabled, AOT enabled)
OpenJ9   - f0b6be7
OMR      - 18d8f94
IBM      - 233dfb5)
JCL - 20191016_01 based on Oracle jdk8u231-b10`

`2020-11-01 12:37:47.631 SEVERE  [io.model9.backup.agent.ShutdownAwareHttpRequestManager-95] /discovery crashed unexpectedly, java.lang.BootstrapMethodError: java.lang.NullPointerException
 at io.model9.backup.discovery.DiscoveryRequestRunner.run(DiscoveryRequestRunner.java:80)
 at io.model9.backup.discovery.DiscoveryServiceImpl.discover(DiscoveryServiceImpl.java:27)
 at io.model9.backup.agent.BackupAgent.postDiscovery(BackupAgent.java:1269)
 at io.model9.backup.agent.BackupAgent.lambda$initializeSpark$15(BackupAgent.java:752)
 at io.model9.backup.agent.BackupAgent$$Lambda$206.000000008AC3FB90.handle(Unknown Source)
 at io.model9.backup.agent.ShutdownAwareHttpRequestManager$ShutdownAwareHttpRequestHandler.handle(ShutdownAwareHttpRequestManager.java:109)
 at spark.RouteImpl$1.handle(RouteImpl.java:72)
 at spark.http.matching.Routes.execute(Routes.java:61)
 at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
 at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.Server.handle(Server.java:564)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
 at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
 at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
 at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
 at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
 at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException
 at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:238)
 at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:315)
 at java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
 at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
 at java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:898)
 at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:949)
 ... 29 more
`

**Comment by JasonFengJ9** [comment]
@roded the error is tracked by https://github.com/eclipse/openj9/issues/10929 now.
