### ISSUE TITLE
groovy-2.4.17 jit error crash launching console

### ISSUE THREAD

**Issue by patric42** [eclipse/openj9#7604]
Java -version output
--------------------

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

Summary of problem
------------------

on 8u232:
groovy-2.4.17 won't launch groovyConsole, JVM exits with '
Unhandled exception
Type=Segmentation error vmState=0x00000000
'
on 11.0.5:
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(Unknown Source)
	at groovy.ui.Console.<init>(Console.groovy:168)
	at groovy.ui.Console.<init>(Console.groovy:218)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at java.base/java.lang.invoke.MethodHandles$CatchHelper.helper(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at groovy.ui.Console.main(Console.groovy:203)

Steps to reproduce:
- wget https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.17.zip
- unzip apache-groovy-binary-2.4.17.zip
- cd groovy-2.4.17
- LANG=C java -cp 'indy/\*:lib/\*' groovy.ui.Console

Happens with 8u232 and 11.0.5. Does not with <=8u222.

Diagnostic files
----------------
[javacore.20191028.123057.24262.0002.txt](https://github.com/eclipse/openj9/files/3778471/javacore.20191028.123057.24262.0002.txt)

**Comment by DanHeidinga** [comment]
FYI @andrewcraik @liqunl

**Comment by andrewcraik** [comment]
I'll let @liqunl have an initial look at this one.

**Comment by liqunl** [comment]
The problem is in ilgen, the stack is wrong after expanding `permuteArgs`. As a result, we generate trees to load thunks field from the wrong object and calling MethodHandle.invokeExact with the wrong receiver. The bug is in `calculateArrayElementAddress`, it dups the array object on the stack even though check is not needed.
