### ISSUE TITLE
Failing JTReg Test: java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7623]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/03cb3a3cb42f9b8992a9e4f5821a557f3ca9eaa4/jdk/test/java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/cc4272e86c12e635710cca2a4c5833c37e398c7b/test/jdk/java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java#L1 are failing for JDK8/11/13-openj9
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac

Optional info
-------------
- intermittent failure (no): 
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- JDK8 has a lot more failures and can be found in this file [openjdk_test_output (3).tar.gz](https://github.com/eclipse/openj9/files/3783985/openjdk_test_output.3.tar.gz). The error output below is the only common failure between 8, 11 and 13 (11 and 13 both fail with only this error)
- I suspect it is HS specific due to the slightly different method name

Failure output (captured from a linux JDK11-openj9 console output)
---------------------------------------------
```
test FilterNotMostSpecific.testGetMethod(java.lang.Class@60dcc7ed): failure
java.lang.AssertionError: 
On interface: interface FilterNotMostSpecific$B3AB
expected: HashMap B2B.m()
found: public abstract java.util.Map FilterNotMostSpecific$B2A.m()
	at org.testng.Assert.fail(Assert.java:94)
	at FilterNotMostSpecific.testGetMethod(FilterNotMostSpecific.java:59)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
Rerun JDK11 job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java&TARGET=jdk_custom_0

**Comment by pshipton** [comment]
@M-Davies I'm not finding the jdk8 failures in the tar

**Comment by M-Davies** [comment]
@pshipton They should be at openjdk-tests/TestConfig/test_output_15723589095981/jdk_custom_0/work/java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.jtr in the tar

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?

**Comment by theresa-m** [comment]
Yes I'll take a look.

**Comment by theresa-m** [comment]
There's a couple of issues here:

- [ ] Java 8 testGetMethod/testGetMethods failures
These test actually pass if I remove this check for Java 8 as well. Checking to see what other testing implications that may have. https://github.com/eclipse/openj9/pull/311

- [ ] Java 11+ testGetMethod failure:
If the calling interface does not implement the specified method, OpenJ9 checks only the first implemented interface, for the failing test the method with the most specific return type is in the second implemented interface.

From the failing test: only B2A is searched but B2B has the method "m" with the most specific return type.
```
interface B3AB extends B2A, B2B {}
interface B1 { Object m(); }
interface B2A extends B1 { Map m(); }
interface B2B extends B1 { HashMap m(); }
```

**Comment by DanHeidinga** [comment]
Moving this out of 0.18 as the change is too large to contain at this point
