### ISSUE TITLE
JTReg Test Failure: java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7624]
Failure link
------------
Rebuild: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_s390x_linux&CUSTOM_TARGET=test/jdk/java/nio/channels/spi/SelectorProvider/inheritedChannel/InheritedChannelTest.java&TARGET=jdk_custom_0&ITERATIONS=10 (NOTE: This test needs a native image so SDK_RESOURCE=customized and CUSTOMIZED_SDK_URL must contain JDK and image)

JDK Version: 11+
JVM: Openj9 only
Platform: z linux

Optional info
-------------
- intermittent failure: yes
- regression or new test: regression

Failure output (captured from console output)
---------------------------------------------
Just to clarify, this test runs 6 sub tests. All 6 of these tests fail intermittently, seemingly due to timeout issues. Increasing the timeout of all these tests cause them to pass, but obviously this isn't a fix as RI passes this fine without an increased timeout.

StateTest.java 1
```
10:18:44  Exception in thread "main" java.io.IOException: Timed out waiting for service to report test result
10:18:44  	at StateTest.waitForTestResult(StateTest.java:81)
10:18:44  	at StateTest.main(StateTest.java:166)
```

EchoTest.java (TCP)
```
11:00:14  Bad response or premature EOF, bytes read:              #Caused at EchoTest.java:122
11:00:14  java.lang.RuntimeException: Bad response or premature EOF from service
11:00:14  Exception in thread "main" java.lang.RuntimeException: Test failed - see log for details
11:00:14  	at EchoTest.main(EchoTest.java:179)
```

EchoTest.java (UDP)
```
10:18:44  java.net.SocketTimeoutException
10:18:44  	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:196)
10:18:44  	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:210)
10:18:44  	at EchoTest.UDPEchoTest(EchoTest.java:148)
10:18:44  	at EchoTest.main(EchoTest.java:170)
10:18:44  java.net.SocketTimeoutException
```

CloseTest.java
```
10:55:11  Exception in thread "main" java.lang.RuntimeException: Timed out waiting for connection to close
10:55:11  	at CloseTest.main(CloseTest.java:83)
```

StateTest.java 2
```
10:18:44  Exception in thread "main" java.io.IOException: Timed out waiting for service to report test result
10:18:44  	at StateTest.waitForTestResult(StateTest.java:81)
10:18:44  	at StateTest.main(StateTest.java:166)
```

StateTest.java 3
```
10:18:44  Exception in thread "main" java.io.IOException: Timed out waiting for service to report test result
10:18:44  	at StateTest.waitForTestResult(StateTest.java:81)
10:18:44  	at StateTest.main(StateTest.java:166)
```

**Comment by adam-thorpe** [comment]
Test is now showing 100% pass rate on 100x grinder, build from 29th Oct still showing ~70% pass rate so something along the way must have fixed this test case, closing and un-excluding.
