### ISSUE TITLE
Failing JTReg: java/lang/reflect/Nestmates/TestSecurityManagerChecks.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7715]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/e7da16be04c9cf4e6734e3621a5f40e34001de8a/test/jdk/java/lang/reflect/Nestmates/TestSecurityManagerChecks.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/12bdd062982e8ce6d81826de961c2b4c306990e4/test/jdk/java/lang/reflect/Nestmates/TestSecurityManagerChecks.java#L1 fail for JDK11/13-openj9
- test category, openjdk
- OS/architecture, all

Optional info
-------------
- intermittent failure (no): 
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Rerun job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/Nestmates/TestSecurityManagerChecks.java&TARGET=jdk_custom_0

Failure output (captured from console output)
---------------------------------------------
```
16:06:45  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10-201910301851)
16:06:45  Eclipse OpenJ9 VM AdoptOpenJDK (build master-99e396a57, JRE 11 Linux amd64-64-Bit Compressed References 20191030_359 (JIT enabled, AOT enabled)
16:06:45  OpenJ9   - 99e396a57
16:06:45  OMR      - cf9d75a4
16:06:45  JCL      - cc4272e86c based on jdk-11.0.5+10)

16:08:59  STDOUT:
16:08:59  OK - getNestHost succeeded for int
16:08:59  OK - getNestHost succeeded for [I
16:08:59  OK - getNestHost succeeded for testPkg.Host
16:08:59  OK - getNestHost succeeded for [LtestPkg.Host$Member;
16:08:59  OK - getNestHost succeeded for testPkg.Singleton
16:08:59  OK - getNestMembers succeeded for int
16:08:59  OK - getNestMembers succeeded for [I
16:08:59  STDERR:
16:08:59  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.testPkg")
16:08:59  	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
16:08:59  	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
16:08:59  	at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
16:08:59  	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
16:08:59  	at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1290)
16:08:59  	at java.base/java.lang.Class.getNestMembers(Class.java:4354)
16:08:59  	at TestSecurityManagerChecks.getNestMembers(TestSecurityManagerChecks.java:96)
16:08:59  	at TestSecurityManagerChecks.main(TestSecurityManagerChecks.java:70)
16:08:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:08:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:08:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:08:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:08:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
16:08:59  	at java.base/java.lang.Thread.run(Thread.java:832)
```

```
16:06:44  openjdk version "13.0.1" 2019-10-15
16:06:44  OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9-201910301711)
16:06:44  Eclipse OpenJ9 VM AdoptOpenJDK (build master-1f05af175, JRE 13 Linux amd64-64-Bit Compressed References 20191030_97 (JIT enabled, AOT enabled)
16:06:44  OpenJ9   - 1f05af175
16:06:44  OMR      - cf9d75a4
16:06:44  JCL      - 12bdd06298 based on jdk-13.0.1+9)

16:08:45  STDOUT:
16:08:45  OK - getNestHost succeeded for int
16:08:45  OK - getNestHost succeeded for [I
16:08:45  OK - getNestHost succeeded for testPkg.Host
16:08:45  OK - getNestHost succeeded for [LtestPkg.Host$Member;
16:08:45  OK - getNestHost succeeded for testPkg.Singleton
16:08:45  OK - getNestMembers succeeded for int
16:08:45  OK - getNestMembers succeeded for [I
16:08:45  STDERR:
16:08:45  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.testPkg")
16:08:45  	at java.base/java.security.AccessController.throwACE(AccessController.java:176)
16:08:45  	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
16:08:45  	at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
16:08:45  	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
16:08:45  	at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1376)
16:08:45  	at java.base/java.lang.Class.getNestMembers(Class.java:4369)
16:08:45  	at TestSecurityManagerChecks.getNestMembers(TestSecurityManagerChecks.java:96)
16:08:45  	at TestSecurityManagerChecks.main(TestSecurityManagerChecks.java:70)
16:08:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:08:45  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:08:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:08:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
16:08:45  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
16:08:45  	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by M-Davies** [comment]
The test passes for the NestHost but fails for the`NestedT[ ]` array when attempting `getNestMembers()`

**Comment by JasonFengJ9** [comment]
Will look into this.

**Comment by JasonFengJ9** [comment]
It appears `RI` failed this test as well.
@M-Davies could you check?

**Comment by M-Davies** [comment]
@JasonFengJ9 Tests appears to pass for me on HS. Both on jenkins and locally

**Comment by JasonFengJ9** [comment]
@M-Davies can you share `RI -version` output?

**Comment by M-Davies** [comment]
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

**Comment by adam-thorpe** [comment]
This test is still failing after the merge, on the next subtest:
`getNestMembers(singleton);   // Singleton nest`
It would appear that the issue is identical to the one above, so I would assume the problem was only partially fixed. Can we re-open this please

**Comment by JasonFengJ9** [comment]
Looking into it.

**Comment by M-Davies** [comment]
> Can we re-open this please
>

@adam-thorpe I don't have the authority to do so apparently. @pshipton could you reopen this please?

**Comment by pshipton** [comment]
Reopened.
