### ISSUE TITLE
Failing JTReg: java/lang/reflect/Proxy/ProxyLayerTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7775]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3cc03bc6fbbab6bbd54eecb860e007f44e14656e/test/jdk/java/lang/reflect/Proxy/ProxyLayerTest.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/5555cfa6ef8926f0c30ea9fe14aa41c9e7b3cd96/test/jdk/java/lang/reflect/Proxy/ProxyLayerTest.java#L1 fail for JDK11/13-openj9. 

- test category, openjdk
- OS/architecture, generic-all

Optional info
-------------
- intermittent failure (no): 
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Possibly related to #7741 
- Probably unsuitable for openj9 since the test is returning modules that openj9 uses but are likely not present in hotspot 

Failure output (captured from console output)
---------------------------------------------
```
13:48:44  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+2-201911141928)
13:48:44  Eclipse OpenJ9 VM AdoptOpenJDK (build master-ef7646f1a, JRE 11 Linux amd64-64-Bit Compressed References 20191114_364 (JIT enabled, AOT enabled)
13:48:44  OpenJ9   - ef7646f1a
13:48:44  OMR      - b372b24c8
13:48:44  JCL      - 3cc03bc6fb based on jdk-11.0.6+2)

13:48:32  openjdk version "13.0.1" 2019-10-15
13:48:32  OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9-201911081205)
13:48:32  Eclipse OpenJ9 VM AdoptOpenJDK (build master-59fcbec6f, JRE 13 Linux amd64-64-Bit Compressed References 20191108_98 (JIT enabled, AOT enabled)
13:48:32  OpenJ9   - 59fcbec6f
13:48:32  OMR      - d8a74ca74
13:48:32  JCL      - 12bdd06298 based on jdk-13.0.1+9)

13:52:41  STDOUT:
13:52:41  [TestNG] Running:
13:52:41    java/lang/reflect/Proxy/ProxyLayerTest.java
13:52:41  
13:52:41  config ProxyLayerTest.compileAll(): success
13:52:41  test ProxyLayerTest.testNoReadAccess(): success
13:52:41  test ProxyLayerTest.testProxyInDynamicModule(): failure
13:52:41  java.lang.AssertionError: expected [null] but found [openj9.traceformat, java.sql, jdk.internal.ed, java.naming, jdk.jdeps, java.instrument, jdk.security.jgss, jdk.httpserver, jdk.jdwp.agent, jdk.xml.dom, jdk.dynalink, jdk.attach, java.base, jdk.editpad, java.compiler, openj9.dtfj, java.security.jgss, jdk.jconsole, jdk.jsobject, jdk.jstatd, jdk.scripting.nashorn, jdk.unsupported, openj9.cuda, jdk.compiler, jdk.security.auth, jdk.internal.jvmstat, jdk.crypto.ec, jdk.javadoc, java.desktop, jdk.localedata, java.net.http, jdk.management.jfr, jdk.internal.opt, jdk.management, jdk.jartool, jdk.charsets, jdk.accessibility, jdk.naming.rmi, openj9.jvm, java.management, jdk.jdi, jdk.net, java.logging, openj9.gpu, java.transaction.xa, jdk.internal.le, jdk.crypto.cryptoki, jdk.jshell, jdk.unsupported.desktop, java.security.sasl, java.rmi, java.xml, openj9.zosconditionhandling, jdk.sctp, openj9.dataaccess, java.management.rmi, jdk.jlink, java.prefs, java.scripting, java.smartcardio, jdk.zipfs, java.datatransfer, java.sql.rowset, jdk.naming.dns, jdk.jfr, java.xml.crypto, openj9.sharedclasses, jdk.management.agent]
13:52:41  	at org.testng.Assert.fail(Assert.java:94)
13:52:41  	at org.testng.Assert.failNotEquals(Assert.java:496)
13:52:41  	at org.testng.Assert.assertEquals(Assert.java:116)
13:52:41  	at org.testng.Assert.assertEquals(Assert.java:167)
13:52:41  	at ProxyLayerTest.testProxyInDynamicModule(ProxyLayerTest.java:135)
13:52:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:52:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:52:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:52:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:52:41  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:52:41  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:52:41  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:52:41  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:52:41  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:52:41  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:52:41  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:52:41  	at org.testng.TestRunner.run(TestRunner.java:623)
13:52:41  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:52:41  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:52:41  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:52:41  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:52:41  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:52:41  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:52:41  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:52:41  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:52:41  	at org.testng.TestNG.run(TestNG.java:1018)
13:52:41  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:52:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:52:41  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:52:41  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:52:41  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:52:41  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:52:41  	at java.base/java.lang.Thread.run(Thread.java:832)
13:52:41  test ProxyLayerTest.testProxyInUnnamed(): success
```
Rerun JDK11 job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/Proxy/ProxyLayerTest.java&TARGET=jdk_custom_0

**Comment by smlambert** [comment]
Excluded by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1444 (previously by 585)

**Comment by M-Davies** [comment]
Added to perm excludes for the above comment
