### ISSUE TITLE
ssh: Could not resolve hostname ub16x64j91: Name or service not known

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7799]
ub16x64j91 didn't come online after https://github.com/eclipse-cbi/jiro/pull/68
```
$ ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 "ssh -i ~/.ssh/id_rsa.aix jenkins@ub16x64j91 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar'"
ssh: Could not resolve hostname ub16x64j91: Name or service not known
ERROR: Unable to launch the agent for ub16x64j91
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
This vm has suffered some sort of networking malfunction.  @rajdeepsingh1 is resolving.

**Comment by rajdeepsingh1** [comment]
working on cloning `ub16x64j95` in order to rebuild `ub16x64j91`

**Comment by rajdeepsingh1** [comment]
@pshipton this should now be resolved. 

`ub16x64j91` has been rebuilt successfully
