### ISSUE TITLE
Jenkins build "Failed in branch"

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7826]
The latest OMR acceptance didn't launch build/test on all platforms. Not sure what is going on, there are no details.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/1729

Update. Failure details can be seen via the chicklets now.

```
11:18:15  Scheduling project: Pipeline_Build_Test_JDK11_x86-64_mac
11:18:20  Starting building: Pipeline_Build_Test_JDK11_s390x_linux #1020
11:18:20  Starting building: Pipeline_Build_Test_JDK11_ppc64le_linux #1243
11:18:20  Starting building: Pipeline_Build_Test_JDK8_s390x_linux #1039
11:18:23  Starting building: Pipeline_Build_Test_JDK8_x86-32_windows #992
11:18:23  Starting building: Pipeline_Build_Test_JDK8_x86-64_mac #946
11:18:23  Starting building: Pipeline_Build_Test_JDK11_x86-64_mac #973
11:18:23  Starting building: Pipeline_Build_Test_JDK8_x86-64_windows #1139
11:18:23  Starting building: Pipeline_Build_Test_JDK11_x86-64_windows #1094
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK8_x86-64_linux_xl
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK8_ppc64_aix
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK11_ppc64_aix
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK8_x86-64_linux
[Pipeline] // stage
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK11_ppc64le_linux
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK11_x86-64_linux
[Pipeline] // stage
[Pipeline] }
11:45:30  Failed in branch Pipeline_Build_Test_JDK11_x86-64_linux_xl
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
13:41:55  Failed in branch Pipeline_Build_Test_JDK8_x86-32_windows
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
Actually, looking at AIX, it's probably this unlabelled job.
Seems there may have been network problems and we should just restart. There is no restart option for the running build.

https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline_Build_Test_JDK8_ppc64_aix/1004
```
Fetching upstream changes from https://github.com/eclipse/openj9.git
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/eclipse/openj9.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
Fetching upstream changes from https://github.com/eclipse/openj9.git
 > git fetch --tags --force --progress -- https://github.com/eclipse/openj9.git 
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/heads/master^{commit} # timeout=10
Checking out Revision 52d8b53ebd00e3724cf663137ab0391dcaadb264 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 52d8b53ebd00e3724cf663137ab0391dcaadb264
ERROR: Timeout after 10 minutes
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f 52d8b53ebd00e3724cf663137ab0391dcaadb264" returned status code 143:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2172)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1000(CliGitAPIImpl.java:78)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2471)
Caused: hudson.plugins.git.GitException: Could not checkout 52d8b53ebd00e3724cf663137ab0391dcaadb264
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2495)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1242)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:149)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Retrying after 10 seconds
No credentials specified
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/eclipse/openj9.git
 > git init /var/jenkins_home/workspace/Pipeline_Build_Test_JDK8_ppc64_aix@script # timeout=10
Using reference repository: /var/jenkins_home/openjdk_cache
Fetching upstream changes from https://github.com/eclipse/openj9.git
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/eclipse/openj9.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
Fetching upstream changes from https://github.com/eclipse/openj9.git
 > git fetch --tags --force --progress -- https://github.com/eclipse/openj9.git 
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/heads/master^{commit} # timeout=10
Checking out Revision 52d8b53ebd00e3724cf663137ab0391dcaadb264 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 52d8b53ebd00e3724cf663137ab0391dcaadb264
ERROR: Timeout after 10 minutes
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f 52d8b53ebd00e3724cf663137ab0391dcaadb264" returned status code 143:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2172)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1000(CliGitAPIImpl.java:78)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2471)
Caused: hudson.plugins.git.GitException: Could not checkout 52d8b53ebd00e3724cf663137ab0391dcaadb264
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2495)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1242)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:149)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```

**Comment by pshipton** [comment]
This seems like something that should be restartable, rather than having to restart the entire build.

**Comment by pshipton** [comment]
This is happening again in the new OMR acceptance build I launched.
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1730

**Comment by AdamBrousseau** [comment]
Opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=553326

Our builds usually don't fail at the "pipeline-build-test-version/spec" level which is why the restart functionality isn't being used here. Note there is a built-in retry for the scm clone which is being exercised. We have the ability to increase the count on this retry. If we were to wrap it with the restart function we'd be restarting an entire spec/version branch build instead of a single test or compile. I would prefer we pause on that and see if this is a one-off.

**Comment by AdamBrousseau** [comment]
Can this be closed?
