### ISSUE TITLE
jdk11_j9_extended.functional_ppc64_aix TestAttachErrorHandling_0 failed java.lang.AssertionError: target 8257778: wait loop not terminated

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#7915]
Internal nightly AIX JDK11
Machine: aix71p7rt5
```
[2019-11-28T09:50:30.889Z] ===============================================
[2019-11-28T09:50:30.889Z] Running test TestAttachErrorHandling_0 ...
[2019-11-28T09:50:30.889Z] ===============================================
[2019-11-28T09:50:31.718Z] TestAttachErrorHandling_0 Start Time: Thu Nov 28 04:50:30 2019 Epoch Time (ms): 1574934630782
[2019-11-28T09:50:31.718Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2019-11-28T09:50:31.718Z] JVMSHRC005I No shared class caches available
[2019-11-28T09:50:31.718Z] JVMSHRC005I No shared class caches available
[2019-11-28T09:50:31.718Z] cache cleanup done
[2019-11-28T09:50:31.718Z] variation: NoOptions
[2019-11-28T09:50:31.718Z] JVM_OPTIONS: -Xcompressedrefs 
[2019-11-28T09:50:31.718Z] { itercnt=1; \
[2019-11-28T09:50:31.718Z] mkdir -p "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15749311008458/TestAttachErrorHandling_0"; \
[2019-11-28T09:50:31.718Z] cd "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15749311008458/TestAttachErrorHandling_0"; \
[2019-11-28T09:50:31.718Z] "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs  \
[2019-11-28T09:50:31.718Z] -cp "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/lib/testng.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
[2019-11-28T09:50:31.718Z] -Dcom.ibm.tools.attach.enable=yes \
[2019-11-28T09:50:31.718Z] -Dcom.ibm.tools.attach.timeout=15000 \
[2019-11-28T09:50:31.718Z] org.testng.TestNG -d "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15749311008458/TestAttachErrorHandling_0" "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestAttachErrorHandling \
[2019-11-28T09:50:31.718Z] -groups level.extended \
[2019-11-28T09:50:31.718Z] -excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all; \
[2019-11-28T09:50:31.718Z] if [ $? -eq 0 ] ; then echo ""; echo "TestAttachErrorHandling_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/..;  else echo ""; echo "TestAttachErrorHandling_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15749311008458/TestTargetResult";
[2019-11-28T09:50:35.467Z] [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TestConfig/../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
[2019-11-28T09:50:35.467Z] ...
[2019-11-28T09:50:35.467Z] ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
[2019-11-28T09:50:35.467Z] ...
[2019-11-28T09:50:35.467Z] 
[2019-11-28T09:52:12.605Z] PASSED: testAttachWithCorruptAdvertisementFile
[2019-11-28T09:52:12.605Z] PASSED: testInitializationDeletesManyStaleDirectories
[2019-11-28T09:52:12.605Z] PASSED: testInitializationDeletesStaleDirectoryWithNumericId
[2019-11-28T09:52:12.605Z] PASSED: testInitializationDeletesStaleDirectoryWithPseudoNumericId
[2019-11-28T09:52:12.605Z] PASSED: testInitializationDeletesStaleDirectoryWithTextId
[2019-11-28T09:52:12.605Z] PASSED: testListVirtualMachinesWithCorruptAdvertisementFile
[2019-11-28T09:52:12.605Z] PASSED: testListVmsDeletesStaleDirectoriesWithNumericId
[2019-11-28T09:52:12.605Z] PASSED: testListVmsDeletesStaleDirectoryWithPseudoNumericId
[2019-11-28T09:52:12.605Z] PASSED: testListVmsDeletesStaleDirectoryWithTextId
[2019-11-28T09:52:12.605Z] PASSED: testMemoryExhaustion
[2019-11-28T09:52:12.605Z] PASSED: testPrematureSocketClose
[2019-11-28T09:52:12.605Z] PASSED: testTracepoint
[2019-11-28T09:52:12.605Z] PASSED: testVmShutdownWhileAttached
[2019-11-28T09:52:12.605Z] FAILED: test_startupShutdownRobustness
[2019-11-28T09:52:12.605Z] java.lang.AssertionError: target 8257778: wait loop not terminated
[2019-11-28T09:52:12.605Z] 	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
[2019-11-28T09:52:12.605Z] 	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
[2019-11-28T09:52:12.605Z] 	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
[2019-11-28T09:52:12.606Z] 	at org.openj9.test.attachAPI.TestAttachErrorHandling.terminateAndCheckLogs(TestAttachErrorHandling.java:157)
[2019-11-28T09:52:12.606Z] 	at org.openj9.test.attachAPI.TestAttachErrorHandling.test_startupShutdownRobustness(TestAttachErrorHandling.java:119)
[2019-11-28T09:52:12.606Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-11-28T09:52:12.606Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-11-28T09:52:12.606Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-11-28T09:52:12.606Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2019-11-28T09:52:12.606Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestRunner.run(TestRunner.java:505)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2019-11-28T09:52:12.606Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2019-11-28T09:52:12.606Z] 	at org.testng.TestNG.main(TestNG.java:1323)
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] ===============================================
[2019-11-28T09:52:12.606Z]     TestAttachErrorHandling
[2019-11-28T09:52:12.606Z]     Tests run: 14, Failures: 1, Skips: 0
[2019-11-28T09:52:12.606Z] ===============================================
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] ===============================================
[2019-11-28T09:52:12.606Z] GeneralTest suite
[2019-11-28T09:52:12.606Z] Total tests run: 14, Failures: 1, Skips: 0
[2019-11-28T09:52:12.606Z] ===============================================
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] 
[2019-11-28T09:52:12.606Z] TestAttachErrorHandling_0_FAILED
```
```
[2019-11-28T08:18:55.605Z] Run /home/jenkins/workspace/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -version
[2019-11-28T08:18:56.419Z] openjdk version "11.0.6-internal" 2020-01-14
[2019-11-28T08:18:56.419Z] OpenJDK Runtime Environment (build 11.0.6-internal+0-adhoc.jenkins.BuildJDK11ppc64aixNightly)
[2019-11-28T08:18:56.419Z] Eclipse OpenJ9 VM (build ibm_sdk-212974ddc5, JRE 11 AIX ppc64-64-Bit Compressed References 20191127_238 (JIT enabled, AOT enabled)
[2019-11-28T08:18:56.419Z] OpenJ9   - 212974ddc5
[2019-11-28T08:18:56.419Z] OMR      - 30afb774d
[2019-11-28T08:18:56.419Z] JCL      - e34da885d4 based on jdk-11.0.6+4)
```

**Comment by JasonFengJ9** [comment]
This is dup of #7010
