### ISSUE TITLE
jenkins - Cannot invoke method _getRuns() on null object

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8051]
Got the following exception in PR testing.

https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_linux_cm/712

```
java.lang.NullPointerException: Cannot invoke method _getRuns() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at Script3.cancel_running_builds(Script3.groovy:172)
	at Script3.workflow(Script3.groovy:451)
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
`jenkins test compile xlinuxcm jdk8` incorrect syntax. Maybe we should catch this?
It was trying to run testing and the test job name it was looking for doesn't exist.
It generated `Test_openjdk8_j9_compile.null_x86-64_linux_Personal` but it was looking for 
`Looking to stop running jobs:'Test_openjdk8_j9_compile_x86-64_linux_Personal' from build:'eclipse/openj9#8042'`

**Comment by AdamBrousseau** [comment]
If you search for jobs will `null` in the name, these can all be deleted.

**Comment by pshipton** [comment]
> If you search for jobs will `null` in the name, these can all be deleted.

Did that. Although if we don't fix the problem they may just be recreated?

**Comment by AdamBrousseau** [comment]
It's a user (committer) problem. We can build in protections against it? Eg. `jenkins test compile` could be caught and translated to `jenkins compile`. Things start to get messy and maybe hardcoded if we start down that path.

**Comment by pshipton** [comment]
It's fine with me if "test compile" just gives an error. It there had been an understandable error I would have realized what I did wrong.

**Comment by AdamBrousseau** [comment]
The problem is we allow any test target so it's more/less just passed along as-is to the test jobs. We could build in a catch for this one since it's a common occurrence.
