### ISSUE TITLE
AIX dropped jenkons connections

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8072]
I've been seeing a number for dropped jenkins connections on AIX which I've been ignoring, but I'll start reporting them now.

https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_OMR/425/
```
16:19:50  aix71-p8-3 was marked offline: Connection was broken: java.io.EOFException
16:19:50  	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
16:19:50  	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
16:19:50  	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
16:19:50  	at java.io.ObjectInputStream.<init>(Unknown Source)
16:19:50  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
16:19:50  	at hudson.remoting.Command.readFrom(Command.java:140)
16:19:50  	at hudson.remoting.Command.readFrom(Command.java:126)
16:19:50  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
16:19:50  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
16:19:50  Caused: java.io.IOException: Unexpected termination of the channel
16:19:50  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
16:19:50  
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Being that the machine is back online now and the uptime is 217 days and working fine now, this would appear to be either a network blip or something wrong with jenkins master.

**Comment by pshipton** [comment]
I haven't seen more of these, closing.
