### ISSUE TITLE
Java 14 : ASM IllegalArgumentException: Unsupported class file major version 58

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8085]
Failure link
------------

```
STF 01:29:52.251 - Running: /home/jenkins/workspace/Test_openjdkNext_j9_extended.system_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -version
openjdk version "14-internal" 2020-03-17
OpenJDK Runtime Environment (build 14-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
Eclipse OpenJ9 VM (build ibm_sdk-55706fd6a1, JRE 14 AIX ppc64-64-Bit Compressed References 20191211_66 (JIT enabled, AOT enabled)
OpenJ9   - 55706fd6a1
OMR      - 209aa965c
JCL      - e1dc1a35ab8 based on jdk-14+26)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  Exception seen while transforming String.
LT  stderr Exception in thread "Attachment 49285" java.lang.reflect.InvocationTargetException
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 58
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 58
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
LT  stderr Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:70)
LT  stderr 	... 6 more
LT  stderr Agent failed to start!
LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
```

**Comment by pshipton** [comment]
@Mesbah-Alam can you please take a look, we'll need to fix this in order to pass extended.system testing on Java 14.

**Comment by Mesbah-Alam** [comment]
This seems to be an ASM issuer. The system tests use ASM 7.1. I've updated it to using 7.3 (the latest). 

Now, running the same test yields a different error, as follows: 

```
11:01:53  LT  stderr Exception in thread "Attachment 35459" java.lang.reflect.InvocationTargetException
11:01:53  LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:01:53  LT  stderr 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:01:53  LT  stderr 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:01:53  LT  stderr 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
11:01:53  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
11:01:53  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
11:01:53  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
11:01:53  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
11:01:53  LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
11:01:53  LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.IllegalStateException: Invalid caller net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor
11:01:53  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
11:01:53  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
11:01:53  LT  stderr 	... 11 more
11:01:53  LT  stderr Caused by: java.lang.Error: java.lang.IllegalStateException: Invalid caller net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor
11:01:53  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
11:01:53  LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
11:01:53  LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
11:01:53  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
11:01:53  LT  stderr Caused by: java.lang.IllegalStateException: Invalid caller net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor
11:01:53  LT  stderr 	at org.objectweb.asm.Constants.checkAsm8Experimental(Constants.java:192)
11:01:53  LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:428)
11:01:53  LT  stderr 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
11:01:53  LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:76)
11:01:53  LT  stderr 	... 6 more
11:01:53  LT  stderr Caused by: java.lang.IllegalStateException: ASM8_EXPERIMENTAL can only be used by classes compiled with --enable-preview
11:01:53  LT  stderr 	at org.objectweb.asm.Constants.checkIsPreview(Constants.java:224)
11:01:53  LT  stderr 	at org.objectweb.asm.Constants.checkAsm8Experimental(Constants.java:190)
11:01:53  LT  stderr 	... 9 more
11:01:53  LT  stderr Agent failed to start!
11:01:53  LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
11:01:54  AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
11:01:54  AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
11:01:54  AG  stderr 	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
11:01:54  AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
```

**Comment by JasonFengJ9** [comment]
`Caused by: java.lang.IllegalStateException: ASM8_EXPERIMENTAL can only be used by classes compiled with --enable-preview`

**Comment by Mesbah-Alam** [comment]
I added `--release 14 --enable-preview` to the `javac` command of the test : https://github.com/AdoptOpenJDK/openjdk-systemtest/compare/master...Mesbah-Alam:update-asm-to-7.3?expand=1

Also added `--enable-preview` in the test command itself :  https://github.com/AdoptOpenJDK/openjdk-tests/compare/master...Mesbah-Alam:update-asm-to-7.3?expand=1

This results in a different failure: 

```
13:21:23  GEN stderr Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload, offset=6
```

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/5385/console

Any idea? @JasonFengJ9

**Comment by JasonFengJ9** [comment]
The error suggests `preview is not enabled`. It seems `--enable-preview` didn't appear in the script generated.

**Comment by JasonFengJ9** [comment]
Additional note: `--enable-preview` can't be recognized by `JDK8`.

To avoid the gap between the static ASM jar files and the new Java class version, JDK build-in `jdk.internal.org.objectweb.asm` can be used instead.

**Comment by Mesbah-Alam** [comment]
I am just trying to get it to work on Jdk 14 - once that's figured out, the plan is to make sure to use all the `--enable-preview` related changes only for jdk 14.

**Comment by Mesbah-Alam** [comment]
Got the test to work on jdk14 :  /Test_grinder/job/Grinder/5390

Solution : 
~~~~~~
1) We need ASM 7.3 for JDK14 (changes needed: Update systemtest getDependency script to fetch ASM 7.3; Update system test top.xml to use ASM 7.3). 
3) Update debugger test project so that we use `--enable-preview` + `-source` options with `javac`.
3) Update playlist.xml for HCRLateAttachWorkload test and pass in `--enable-preview` option to be used in the "generation" phase of the test.

I'll create the required PRs and submit for review.

**Comment by Mesbah-Alam** [comment]
@JasonFengJ9 - could you please verify and close this issue?

**Comment by pshipton** [comment]
I've started the jdk14 system testing https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK14/1/ so we can see where we stand.

**Comment by pshipton** [comment]
Seems we broke jdk14 yesterday. It will be fixed shortly and then I'll try again.

**Comment by pshipton** [comment]
Another attempt https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK14/2/

**Comment by pshipton** [comment]
The extended.system tests are passing now so I'll close this one. The mauve tests are still failing as per #8086
