### ISSUE TITLE
Java 14 : test AbsentStreamValuesTest.testGenericType(): local class incompatible:

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8087]
Failure link
------------

```
21:44:05  Run /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/java -version
21:44:05  openjdk version "14-internal" 2020-03-17
21:44:05  OpenJDK Runtime Environment (build 14-internal+0-adhoc.jenkins.BuildJDKnextppc64lelinuxNightly)
21:44:05  Eclipse OpenJ9 VM (build ibm_sdk-55706fd6a1, JRE 14 Linux ppc64le-64-Bit Compressed References 20191211_67 (JIT enabled, AOT enabled)
21:44:05  OpenJ9   - 55706fd6a1
21:44:05  OMR      - 209aa965c
21:44:05  JCL      - e1dc1a35ab8 based on jdk-14+26)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
21:52:32  ---
21:52:32  test AbsentStreamValuesTest.testGenericType(): failure
21:52:32  java.io.InvalidClassException: AbsentStreamValuesTest$R16; local class incompatible: stream classdesc serialVersionUID = 0, local class serialVersionUID = -5738666046459921263
21:52:32  	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:715)
21:52:32  	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2059)
21:52:32  	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1928)
21:52:32  	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2221)
21:52:32  	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1750)
21:52:32  	at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:557)
21:52:32  	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:494)
21:52:32  	at AbsentStreamValuesTest.deserialize(AbsentStreamValuesTest.java:169)
21:52:32  	at AbsentStreamValuesTest.testGenericType(AbsentStreamValuesTest.java:134)
21:52:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:52:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:52:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:52:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
21:52:32  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
21:52:32  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
21:52:32  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
21:52:32  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
21:52:32  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
21:52:32  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
21:52:32  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
21:52:32  	at org.testng.TestRunner.run(TestRunner.java:623)
21:52:32  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
21:52:32  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
21:52:32  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
21:52:32  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
21:52:32  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
21:52:32  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
21:52:32  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
21:52:32  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
21:52:32  	at org.testng.TestNG.run(TestNG.java:1018)
21:52:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
21:52:32  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
21:52:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:52:32  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:52:32  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:52:32  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
21:52:32  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:52:32  	at java.base/java.lang.Thread.run(Thread.java:835)
21:52:32  
```

**Comment by pshipton** [comment]
@JasonFengJ9 does this problem still occur? Is this the sanity.openjdk tests?

**Comment by JasonFengJ9** [comment]
> does this problem still occur? Is this the sanity.openjdk tests?

It was excluded as per https://github.com/eclipse/openj9/issues/7945#issuecomment-585124633

@adam-thorpe can you re-enable the tests?

fyi @theresa-m

**Comment by adam-thorpe** [comment]
Whats the full name of this test?

**Comment by JasonFengJ9** [comment]
> Whats the full name of this test? Or are you talking about the java/io/Serializable/records as a whole?

This individual test was excluded as `java/io/Serializable/records/AbsentStreamValuesTest.java    https://github.com/eclipse/openj9/issues/7945 generic-all`
I think `java/io/Serializable/records` need to be enabled as a whole as well.

**Comment by adam-thorpe** [comment]
Done

**Comment by JasonFengJ9** [comment]
Passed in latest internal build.
```
Passed
java/io/Serializable/records/AbsentStreamValuesTest.java.AbsentStreamValuesTest (from java_io_Serializable_records_AbsentStreamValuesTest.java)
```
