### ISSUE TITLE
jdk8 jdk_net_0 address 0:0:0:0:0:0:0:0 can not be reachable

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8089]
Failure link
------------

```
02:56:48  Run /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image/bin/java -version
02:56:48  openjdk version "1.8.0_242-internal"
02:56:48  OpenJDK Runtime Environment (build 1.8.0_242-internal-jenkins_2019_12_11_18_14-b00)
02:56:48  Eclipse OpenJ9 VM (build ibm_sdk-55706fd6a1, JRE 1.8.0 Linux amd64-64-Bit 20191211_254 (JIT enabled, AOT enabled)
02:56:48  OpenJ9   - 55706fd6a1
02:56:48  OMR      - 209aa965c
02:56:48  JCL      - fd9f45b10c8 based on jdk8u242-b04)
````

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
03:08:13          PingThis
03:08:13  STDOUT:
03:08:13  The target ip is 0.0.0.0
03:08:13  the target is reachable: true
03:08:13  Test passed 
03:08:13  The target ip is 0:0:0:0:0:0:0:0
03:08:13  the target is reachable: false
03:08:13  Test failed 
03:08:13  STDERR:
03:08:13  java.lang.Exception: address 0:0:0:0:0:0:0:0 can not be reachable!
03:08:13  	at PingThis.main(PingThis.java:86)
03:08:13  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:08:13  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:08:13  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:08:13  	at java.lang.reflect.Method.invoke(Method.java:498)
03:08:13  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
03:08:13  	at java.lang.Thread.run(Thread.java:821)
03:08:13  
03:08:13  JavaTest Message: Test threw exception: java.lang.Exception
03:08:13  JavaTest Message: shutting down test
03:08:13  
03:08:13  
03:08:13  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: address 0:0:0:0:0:0:0:0 can not be reachable!
03:08:13  --------------------------------------------------
03:08:19  TEST: java/net/ipv6tests/TcpTest.java
```

**Comment by pshipton** [comment]
Is this IBM internal testing? It looks like a machine problem.

**Comment by smlambert** [comment]
Is IPv6 enabled on the machine where it ran?

**Comment by JasonFengJ9** [comment]
Yeah, it is an internal test, will check IPv6 settings.
