### ISSUE TITLE
OpenJ9 crashes for the next test case

### ISSUE THREAD

**Issue by myspringchen** [eclipse/openj9#811]
OpenJ9 crashes for the next file. Please let me know if you cannot reproduce this crash.

How to reproduce:
(1) download the file https://jbox.sjtu.edu.cn/l/eHE9O0 and unzip it.
(2) run: java Harness fop
(3) Result:
IBM's jvm (build 2.9; J9VM - 20071122_371101; OpenJ9 - 8e3c85d) crashes; HotSpot (build 9+181) throws a verify error: Bad local variable type

**Comment by ChengJin01** [comment]
@myspringchen,

I already tried with the latest build on linux at https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9 and it ended up with pretty much the same result as Oracle. Please try with the latest build to double-check your app (please check whether you uploaded the correct app you want to reproduce the issue)

-----------------------
e.g. https://github.com/AdoptOpenJDK/openjdk9-openj9-nightly/releases/download/jdk-9%2B181-20170112/OpenJDK9-OPENJ9_x64_Linux_20170112.tar.gz

OpenJDK9-OPENJ9_x64_Linux_20171312/bin/java  -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171213_66 (JIT enabled, AOT enabled)
OpenJ9   - 723e4a5
OMR      - e7aff9e
OpenJDK  - f1a22d1 based on )

OpenJDK9-OPENJ9_x64_Linux_20171312/bin/java  Harness fop
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-internal/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-internal/NativeConstructorAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-internal/DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(java.base@9-internal/Constructor.java:488)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:211)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:171)
        at Harness.main(Harness.java:17)
Caused by: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=org/apache/fop/cli/Main, method=startFOP([Ljava/lang/String;)V, pc=243
Exception Details:
  Location:
    org/apache/fop/cli/Main.startFOP([Ljava/lang/String;)V @243: JBaload1
  Reason:
    Type top (current frame, locals[1]) is not assignable to 'reference' type
  Current Frame:
    bci: @243
    flags: { }
    locals: { '[Ljava/lang/String;', top, top, top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { 'java/lang/Object' }
  Exception Handler Table:
    bci [243, 310] => handler: 348
    bci [348, 349] => handler: 348
    bci [220, 355] => handler: 415
  Stackmap Table:
        at java.lang.Class.forNameImpl(java.base@9-internal/Native Method)
        at java.lang.Class.forName(java.base@9-internal/Class.java:370)
        at org.dacapo.harness.Fop.<init>(Fop.java:26)
        ... 7 more

---------------
OpenJDK/Oracle:

openjdk175/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.arnold.jdk9175)
OpenJDK 64-Bit Server VM (build 9-internal+0-adhoc.arnold.jdk9175, mixed mode)

 /team/cjin/OracleJDK/openjdk175/bin/java  Harness fop
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:211)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:171)
        at Harness.main(Harness.java:17)
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    org/apache/fop/cli/Main.startFOP([Ljava/lang/String;)V @243: aload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @243
    flags: { }
    locals: { '[Ljava/lang/String;', top, top, top, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer, integer }
    stack: { }
  Bytecode:
    0000000: 10c8 3604 1021 3605 107c 3606 10ca 3607
......

**Comment by myspringchen** [comment]
Thank you. I will run my test cases using the latest release.
