### ISSUE TITLE
Can't launch jenkins builds, MissingMethodException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8123]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/115
```
groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.keySet() is applicable for argument types: () values: []
Possible solutions: toSet(), toSet(), set(int, java.lang.Object), set(int, java.lang.Object), get(int), get(int)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:153)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at Script1.get_default_test_targets(Script1.groovy:672)
```

**Comment by pshipton** [comment]
I assume this was "caused" by https://github.com/eclipse/openj9/pull/8116

#8118 was also merged, but this is to another branch.

@dnakamura @AdamBrousseau

**Comment by pshipton** [comment]
Not sure what is going on. I reverted both changes seperately, but the build failure still occurred.

**Comment by pshipton** [comment]
Probably was I left the TESTS_TARGETS blank.

**Comment by pshipton** [comment]
Adam: I think it's this line
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/variables-functions.groovy#L672
