### ISSUE TITLE
No space left on device on cent6-x64-1

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#8151]
As seen in #8110 [1]:

```
13:51:31  Creating resources.jar
13:51:32  zip I/O error: No space left on devicejava.io.IOException: No space left on device
13:51:32  	at java.io.FileOutputStream.writeBytes(Native Method)
13:51:32  	at java.io.FileOutputStream.write(FileOutputStream.java:345)
13:51:32  	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
13:51:32  	at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:322)
13:51:32  	at sun.tools.jar.Main.copy(Main.java:823)
13:51:32  	at sun.tools.jar.Main.copy(Main.java:837)
13:51:32  	at sun.tools.jar.Main.addFile(Main.java:784)
13:51:32  	at sun.tools.jar.Main.create(Main.java:495)
13:51:32  	at sun.tools.jar.Main.run(Main.java:202)
13:51:32  	at sun.tools.jar.Main.main(Main.java:1231)
```

[1] https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_linux_xl_Personal/299/

**Comment by fjeremic** [comment]
Seems related to #8146.

**Comment by pshipton** [comment]
Closing as dup of #8146. The machine is currently disabled until it is fixed, but sometimes when jenkins restarts we have to re-disable machines.
