### ISSUE TITLE
aix71-p8-8 out of memory

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8164]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_ppc64_aix_Nightly/52/
```
02:41:22  STF 01:11:29.935 - +------ Step 6 - Waiting for jvm1 and jvm2 to finish
02:41:22  STF 01:11:29.935 - | Wait for processes to meet expectations
02:41:22  STF 01:11:29.935 - |   Processes: [jvm1, jvm2]
02:41:22  STF 01:11:29.935 - |
02:41:22  STF 01:11:29.935 - Monitoring processes: jvm1 jvm2
02:46:27  STF 01:16:29.303 - Heartbeat: Process jvm2 is still running
02:46:42  gmake: *** Waiting for unfinished jobs....
02:46:42  gmake[2]: *** Waiting for unfinished jobs....
02:46:42  gmake[1]: *** Waiting for unfinished jobs....
02:47:09  Cannot contact aix71-p8-8: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on aix71-p8-8 failed. The channel is closing down or has closed down
02:47:34  STF 01:17:15.495 - **FAILED** execute script failed. Expected return value=0 Actual=1
02:47:34  gmake[1]./openjdk-tests/maketest.sh: line 34: 5308566 Killed: *** [/                  $MAKE -C $testDir -f autoGen.mk $@home/u0020236/workspace/Test_openjdk13_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../TKG/settings.mk:251: extended.system-sharedClasses] Killed
02:47:34  STF 01:17:15.503 - 

...

java.io.IOException: error=12, There is not enough memory available now.
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:291)
	at java.lang.ProcessImpl.start(ProcessImpl.java:167)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1040)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to aix71-p8-8
```

No diagnostic files were captured.

**Comment by pshipton** [comment]
@jdekonin pls check the machine
