### ISSUE TITLE
openjdk8_j9_sanity.functional_ppc64le jasm_generator UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/openjdk/asmtools/Main, offset=6

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8172]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_xl_Nightly/24/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
00:12:37  jasm_generator:
00:12:37      [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64le_linux_xl_Nightly/openjdk-tests/functional/Java8andUp/bin/j9vm/test/invoker
00:12:37       [exec] Error: A JNI error has occurred, please check your installation and try again
00:12:37       [exec] Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/openjdk/asmtools/Main, offset=6
00:12:37       [exec] 	at java.lang.ClassLoader.defineClassImpl(Native Method)
00:12:37       [exec] 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
00:12:37       [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
00:12:37       [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
00:12:37       [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
00:12:37       [exec] 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
00:12:37       [exec] 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
00:12:37       [exec] 	at java.security.AccessController.doPrivileged(AccessController.java:770)
00:12:37       [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
00:12:37       [exec] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
00:12:37       [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
00:12:37       [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
00:12:37       [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
00:12:37       [exec] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
00:12:37       [exec] Result: 1
00:12:37       [exec] Error: A JNI error has occurred, please check your installation and try again
```

**Comment by pshipton** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1453
