### ISSUE TITLE
openjdkNext_j9_extended.system Unsupported class file major version 59

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8178]
Failure link
------------

From internal jenkins nightly jobs.

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  Exception seen while transforming String.
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:356)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:334)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:200)
LT  stderr 	at java.base/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 59
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.IllegalArgumentException: Unsupported class file major version 59
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
LT  stderr 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
LT  stderr 	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.TransformerMakerThread.run(TransformerMakerThread.java:68)
LT  stderr Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
LT  stderr 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:70)
LT  stderr 	... 6 more
LT  stderr Agent failed to start!
```

**Comment by pshipton** [comment]
Related to https://github.com/eclipse/openj9/issues/8085
@Mesbah-Alam can you pls take a look.

**Comment by Mesbah-Alam** [comment]
Support for JDK15 was added in ASM 7.3.1 : 
https://gitlab.ow2.org/asm/asm/-/merge_requests/281
https://asm.ow2.io/versions.html

I'll update our internal copy of ASM from 7.3->7.3.1.

@pshipton

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/333 should fix the issue. We need to verify it in the next openjdkNext_i9_extended.system build

**Comment by JasonFengJ9** [comment]
Thanks @Mesbah-Alam , the `IllegalArgumentException` is not seen in latest `openjdkNext_j9_extended.system` build,
Closing.
