### ISSUE TITLE
UnknownHostException: ub16x64j910

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8272]
Maybe just a temporary DNS hiccup, as it only occurred in one test, and no IP address is mentioned.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/249
ub16x64j910
MauveSingleThreadLoadTest_OpenJ9_0
```
LT  Test failed:
LT  java.net.UnknownHostException: ub16x64j910: ub16x64j910: Name or service not known
LT  	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
LT  	at gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2.<init>(DatagramPacketTest2.java:70)
LT  	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
LT  	at java.lang.Class.newInstance(Class.java:1852)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:52)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:821)
LT  Caused by: java.net.UnknownHostException: ub16x64j910: Name or service not known
LT  	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
LT  	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
LT  	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
LT  	... 8 more
```

**Comment by pshipton** [comment]
@jdekonin sti

**Comment by pshipton** [comment]
Rajdeep-Singh said:

There was an issue on the machine hosting the VMs for oj9.

ub16x64j910 has been operating accordingly, the only machine that seemed to be impacted by the hosting machine issue was ub16x64j98.

The issue mentioned above seems to have to no correlation with any issues on the host.

**Comment by pshipton** [comment]
I'll re-enable ub16x64j910 and we'll see if the problem occurs again.

**Comment by pshipton** [comment]
I'm not sure if I disabled ub16x64j910, it is enabled now.

**Comment by pshipton** [comment]
Rajdeep-Singh said:

Forgot to mention - I did reboot ub16x64j910 about 30-40 mins ago as well.
