### ISSUE TITLE
jenkins - NullPointerException: Cannot invoke method containsKey() on null object

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8280]
Failure link
------------

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_Personal/622/console
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/541/console
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_Personal/632/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
java.lang.NullPointerException: Cannot invoke method containsKey() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$1.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$1.callStatic(Unknown Source)
	at Buildspec.<init>(Script1.groovy:163)
```

fyi @jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
@pshipton 's `specialsystem` branch needs [this change](https://github.com/eclipse/openj9/commit/dd4fae228ce62d87f1e48ed062b4e3dce1f8964d#diff-a3fca431c8c372cebd1caff040ca6eab) applied to the defaults.yml variable file.

**Comment by pshipton** [comment]
Updated branch with the latest changes.
