### ISSUE TITLE
JTReg Failure: java/io/Serializable/serialFilter/GlobalFilterTest.java on jdk8u242-b08

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8352]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/121/
- test category: sanity.openjdk
- OS/architecture: all
- version: jdk8u242-b08
- jvm: openj9 only

Optional info
-------------
- intermittent failure (yes|no): no
- regression or new test: regression
- if regression, what are the last passing:
```
05:54:06  System.getProperty('java.fullversion')=1.8.0_242-202001130456-b06
05:54:06  JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200113_429 (JIT enabled, AOT enabled)
05:54:06  OpenJ9   - 6b1f6d9b5
05:54:06  OMR      - 9661da2d4
05:54:06  JCL      - a9857e68ed based on jdk8u242-b06
```
Failure output (captured from console output)
---------------------------------------------
```
13:33:44  test GlobalFilterTest.globalFilter(): failure
13:33:44  java.lang.AssertionError: System.setProperty("jdk.serialfilter", ...) should not change filter: java.lang.StringBuffer;!*
13:33:44  	at org.testng.Assert.fail(Assert.java:94)
13:33:44  	at org.testng.Assert.assertNotEquals(Assert.java:856)
13:33:44  	at GlobalFilterTest.globalFilter(GlobalFilterTest.java:114)
13:33:44  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:33:44  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:33:44  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:33:44  	at java.lang.reflect.Method.invoke(Method.java:498)
13:33:44  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:33:44  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:33:44  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:33:44  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:33:44  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:33:44  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:33:44  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:33:44  	at org.testng.TestRunner.run(TestRunner.java:623)
13:33:44  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:33:44  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:33:44  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:33:44  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:33:44  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:33:44  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:33:44  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:33:44  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:33:44  	at org.testng.TestNG.run(TestNG.java:1018)
13:33:44  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:33:44  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
13:33:44  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:33:44  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:33:44  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:33:44  	at java.lang.reflect.Method.invoke(Method.java:498)
13:33:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:33:44  	at java.lang.Thread.run(Thread.java:821)
```

**Comment by pshipton** [comment]
@JasonFengJ9

**Comment by JasonFengJ9** [comment]
@adam-thorpe can you re-run the test with `JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200113_429` and confirm if it passes?

**Comment by adam-thorpe** [comment]
By that you mean the build at jdk8u242-b06 ?

**Comment by adam-thorpe** [comment]
Grinder failed using the build from `20200113_429`
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1827/

Original run definitely passed, same build:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/120/testReport/
@JasonFengJ9 @pshipton

**Comment by JasonFengJ9** [comment]
> Grinder failed using the build from 20200113_429

Got same failure in local run.
