### ISSUE TITLE
HCRLateAttachWorkload UnsupportedClassVersionError 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8356]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/253
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_s390x_linux_Nightly/263
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_Nightly/249
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly/265
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Nightly/51
HCRLateAttachWorkload_0
```
GEN   /home/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/jvmtest/system/systemtest_prereqs/asm-7.3/asm-7.3.jar
GEN stderr Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload, offset=6
GEN stderr 	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
GEN stderr 	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:476)
GEN stderr 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:437)
GEN stderr 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:389)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.findClass(StfClassLoader.java:246)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfClassLoader.loadClass(StfClassLoader.java:143)
GEN stderr 	at java.base/java.lang.Class.forNameImpl(Native Method)
GEN stderr 	at java.base/java.lang.Class.forName(Class.java:342)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.createTestObject(StfRunner.java:621)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:200)
GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
Generation failed
```

**Comment by pshipton** [comment]
@Mesbah-Alam seems this is caused by fixes for jdk14.

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1568 should fix this.
