### ISSUE TITLE
sanity.openjdk Windows IOException: Access is denied

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8374]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows_Personal/1
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Personal/1
All tests fail with `IOException: Access is denied`
```
[2020-01-22T17:16:27.562Z] java.io.IOException: Access is denied.
[2020-01-22T17:16:27.562Z] 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[2020-01-22T17:16:27.562Z] 	at java.io.File.createNewFile(File.java:1012)
[2020-01-22T17:16:27.562Z] 	at SpecialTempFile.main(SpecialTempFile.java:86)
[2020-01-22T17:16:27.562Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-01-22T17:16:27.562Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-01-22T17:16:27.562Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-01-22T17:16:27.562Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-01-22T17:16:27.562Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2020-01-22T17:16:27.562Z] 	at java.lang.Thread.run(Thread.java:821)
```
```
[2020-01-22T17:16:28.219Z] java.io.IOException: Access is denied.
[2020-01-22T17:16:28.219Z] 	at java.io.File.createTempFile(File.java:2024)
[2020-01-22T17:16:28.219Z] 	at java.io.File.createTempFile(File.java:2070)
[2020-01-22T17:16:28.219Z] 	at CheckPermission.main(CheckPermission.java:364)
[2020-01-22T17:16:28.219Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-01-22T17:16:28.219Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-01-22T17:16:28.219Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-01-22T17:16:28.219Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-01-22T17:16:28.219Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2020-01-22T17:16:28.219Z] 	at java.lang.Thread.run(Thread.java:821)
```

**Comment by pshipton** [comment]
@smlambert @llxia seems like a setup issue, any ideas?

**Comment by llxia** [comment]
Sorry, I do not recall any special settings for openjdk tests on windows. @sophia-guo do you have any ideas?

**Comment by sophia-guo** [comment]
Yes, looks like the setup issue. No same issue happened in AdoptOpenJDK windows test build. 

The most errors are either calling `createTempFile` or `createTempDirectory`. Suspect the default Temporary Files Location value %TEMP%. 

```
12:16:28  java.io.IOException: Access is denied.
12:16:28  	at java.io.File.createTempFile(File.java:2024)
12:16:28  	at java.io.File.createTempFile(File.java:2070)
```
In adopt the jenkins windows TEMP is set as:

`02:34:11  TEMP=/cygdrive/c/Users/JENKIN~1.TES/AppData/Local/Temp`

What the %TEMP% in those Eclipse openj9 windows? ( looks like it's %systemdrive%\Windows\Temp )

**Comment by pshipton** [comment]
@jdekonin can you please address the previous comment.

**Comment by jdekonin** [comment]
The machines are all the same.  There is no restriction on jobs writing to /tmp.  Where is the job trying to write too?  Why is the job trying to create content outside of the workspace directory?  This leads to content clutter on the machines.

```
jenkins@oj9-win2012r2-1 ~
$ echo $TEMP
/tmp
```

**Comment by sophia-guo** [comment]
> The machines are all the same. There is no restriction on jobs writing to /tmp. Where is the job trying to write too?

Test job with createTempFile creates an empty file in _the default temporary-file directory_ ( note it is jenkins user on cygwin).

There are some other access denied

```
12:16:31  STDERR:
12:16:31  java.nio.file.AccessDeniedException: C:\Windows\6073852034634688818.tmp
```

>  Why is the job trying to create content outside of the workspace directory? This leads to content clutter on the machines.

Test could cleans up itself when exit(  f.deleteOnExit(); ), which is independent of jenkins job. Should no leftover issue.

**Comment by smlambert** [comment]
We run `printenv` at the beginning of every test run.

Looking at a [passing run on a windows machines at AdoptOpenJDK](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows/121/console), there is both a TMP and TEMP environment variable set.  
<img width="565" alt="Screen Shot 2020-01-28 at 9 27 22 PM" src="https://user-images.githubusercontent.com/2836948/73324366-aef28880-4218-11ea-8131-33a7f23f9c35.png">
<img width="574" alt="Screen Shot 2020-01-28 at 9 41 51 PM" src="https://user-images.githubusercontent.com/2836948/73324367-af8b1f00-4218-11ea-83e0-6807dd1b14a3.png">

Looking at the [console output of the failing test on the OpenJ9 machine](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows_Personal/1/consoleFull), there is no TMP or TEMP environment variables.  

That seems to be the fundamental difference between machine configurations that is causing the test failure.  If you compare all printenv output, you also see other differences between environment variables, including between PATH settings.   If you correct this difference in machine configuration, the test failures will be resolved.

**Comment by pshipton** [comment]
@jdekonin fyi Shelley's comment https://github.com/eclipse/openj9/issues/8374#issuecomment-579569564

**Comment by jdekonin** [comment]
Machines are connecting to jenkins differently, otherwise I don't see anything playbook specific that would address the setting of the env.  TEMP is now defined in the machine configuration.  Pete launched a grinder to see what else fails.
https://ci.eclipse.org/openj9/job/Grinder/620/console

Just jdk_security1_0, any suggestions as to what is needed if this is a system configuration issue?
```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.ProviderException: java.security.KeyException: Access is denied
```

**Comment by jdekonin** [comment]
Make env vars stick in jenkins config
https://github.com/eclipse-cbi/jiro/pull/80

**Comment by pshipton** [comment]
Updated the jdk_security1_0 failure comment with more information, although still not helpful. It's using the MSCAPI Provider, which is Windows specific. Googling found https://docs.genesys.com/Documentation/PSDK/latest/Developer/TLSSecurityProviders which mentions certmgr.msc, not sure if that helps.

**Comment by jdekonin** [comment]
@vsebe is this something that you have seen with any of our internal windows test wrt machine configuration requirements?

**Comment by vsebe** [comment]
Nothing related to certificates in WMI.

**Comment by pshipton** [comment]
This no longer seems to occur.
