### ISSUE TITLE
jenkins : ]: special characters are not allowed

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8377]
Failure link
------------

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/269
00:26:44  ]: special characters are not allowed
00:26:44  	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:469)
00:26:44  	at org.tap4j.parser.Tap13Parser.parseLine(Tap13Parser.java:288)
00:26:44  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:252)
00:26:44  	... 13 more
00:26:44  Caused by: unacceptable character '?' (0xD852) special characters are not allowed
00:26:44  in "'string'", position 881
00:26:44  	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67)
00:26:44  	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
00:26:44  	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
00:26:44  	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:459)
00:26:44  	... 15 more
00:26:44  TAP parse errors found in the build. Marking build as UNSTABLE
```

**Comment by JasonFengJ9** [comment]
A similar error at https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/110/console
```
05:26:41  TAP Reports Processing: START
05:26:41  Looking for TAP results report in workspace using pattern: **/*.tap
05:26:42  Saving reports...
05:26:42  Processing '/var/jenkins/jobs/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/builds/110/tap-master-files/openjdk-tests/TKG/test_output_16004166991381/TestTargetResult.tap'
05:26:42  Parsing TAP test result [/var/jenkins/jobs/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_1/builds/110/tap-master-files/openjdk-tests/TKG/test_output_16004166991381/TestTargetResult.tap].
05:26:42  org.tap4j.parser.ParserException: Error parsing TAP Stream: Error parsing YAML [    duration_ms: 1885
05:26:42    ..
05:26:42  ]: expected '<document start>', but found '<scalar>'
05:26:42   in 'string', line 2, column 3:
05:26:42        ..
05:26:42        ^
05:26:42  
05:26:42  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:257)
05:26:42  	at org.tap4j.parser.Tap13Parser.parseFile(Tap13Parser.java:231)
05:26:42  	at org.tap4j.plugin.TapParser.parse(TapParser.java:173)
05:26:42  	at org.tap4j.plugin.TapPublisher.loadResults(TapPublisher.java:572)
05:26:42  	at org.tap4j.plugin.TapPublisher.performImpl(TapPublisher.java:444)
05:26:42  	at org.tap4j.plugin.TapPublisher.perform(TapPublisher.java:403)
05:26:42  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:94)
05:26:42  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
05:26:42  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
05:26:42  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$344/00000000A0070420.run(Unknown Source)
05:26:42  	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
05:26:42  	at java.util.concurrent.FutureTask.run(Unknown Source)
05:26:42  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
05:26:42  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
05:26:42  	at java.lang.Thread.run(Unknown Source)
05:26:42  Caused by: org.tap4j.parser.ParserException: Error parsing YAML [    duration_ms: 1885
05:26:42    ..
05:26:42  ]: expected '<document start>', but found '<scalar>'
05:26:42   in 'string', line 2, column 3:
05:26:42        ..
05:26:42        ^
05:26:42  
05:26:42  	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:469)
05:26:42  	at org.tap4j.parser.Tap13Parser.onFinish(Tap13Parser.java:431)
05:26:42  	at org.tap4j.parser.Tap13Parser.parseTapStream(Tap13Parser.java:255)
05:26:42  	... 14 more
05:26:42  Caused by: expected '<document start>', but found '<scalar>'
05:26:42   in 'string', line 2, column 3:
05:26:42        ..
05:26:42        ^
05:26:42  
05:26:42  	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:225)
05:26:42  	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
05:26:42  	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
05:26:42  	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:122)
05:26:42  	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
05:26:42  	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
05:26:42  	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
05:26:42  	at org.tap4j.parser.Tap13Parser.parseDiagnostics(Tap13Parser.java:459)
05:26:42  	... 16 more
05:26:42  TAP parse errors found in the build. Marking build as UNSTABLE
05:26:42  TAP Reports Processing: FINISH
```

**Comment by smlambert** [comment]
This can handled by several options:
- raised/fixed as a feature request to support special characters against the Jenkins [TAP plugin](https://github.com/jenkinsci/tap-plugin) used by the Jenkins server
- turn off the feature that prints the console output into the (optional) TAP field in order to attempt to display it in the TAP view for functional tests (as we have already done for openjdk tests (and other tests that produce output containing special characters).
- fix the functional test that is creating output with characters that this convenience plugin can parse
