### ISSUE TITLE
TestAttachErrorHandling java.lang.IllegalArgumentException: Null charset name

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#839]
Observed only on LinuxPPC.

Symptoms:
[TargetManager] [ERROR] Error: A JNI error has occurred, please check your installation and try again

[TargetManager] [ERROR] Exception in thread "main" java.lang.IllegalArgumentException: Null charset name

[TargetManager] [ERROR] 	at java.nio.charset.Charset.lookup(Charset.java:487)

[TargetManager] [ERROR] 	at java.nio.charset.Charset.isSupported(Charset.java:553)

[TargetManager] [ERROR] 	at java.util.zip.ZipFile.open(Native Method)

[TargetManager] [ERROR] 	at java.util.zip.ZipFile.<init>(ZipFile.java:241)

[TargetManager] [ERROR] 	at java.util.zip.ZipFile.<init>(ZipFile.java:171)

[TargetManager] [ERROR] 	at java.util.jar.JarFile.<init>(JarFile.java:179)

[TargetManager] [ERROR] 	at java.util.jar.JarFile.<init>(JarFile.java:116)

[TargetManager] [ERROR] 	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:1060)

[TargetManager] [ERROR] 	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:906)

[TargetManager] [ERROR] 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:996)

[TargetManager] [ERROR] 	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:986)

**Comment by pdbain-ibm** [comment]
Seen on LinuxPPC and LinuxPPCLE, Java 8 only.  Cannot reproduce on Java 9.

**Comment by pdbain-ibm** [comment]
Tested with latest OpenJ9 Java 8 and associated test material:
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_12_25_21_45-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64 Compressed References 20171225_374449 (JIT enabled, AOT enabled)
OpenJ9   - 4f77dce
OMR      - 9beb3de
OpenJDK  - 00e69f9 based on Java8_SR5_FP7_20171215_1234_B373586)
java -Xcompressedrefs  \
-cp "/tmp/bld_374449/test/TestConfig/../../jvmtest/TestConfig/resources:/tmp/bld_374449/j2sdk-image/jre/bin/../../lib/tools.jar:/tmp/bld_374449/test/TestConfig/../../jvmtest/TestConfig/lib/testng.jar:/tmp/bld_374449/test/TestConfig/../../jvmtest/TestConfig/lib/jcommander.jar:/tmp/bld_374449/test/TestConfig/../../jvmtest/Java8andUp/GeneralTest.jar" \
-Dcom.ibm.tools.attach.enable=yes \
-Dcom.ibm.tools.attach.timeout=15000 \
org.testng.TestNG -d "/tmp/bld_374449/test/TestConfig/test_output_1514469772/TestAttachErrorHandling_SE80_0" "/tmp/bld_374449/test/TestConfig/../../jvmtest/Java8andUp/testng.xml" -testnames TestAttachErrorHandling \
-groups level.extended \
-excludegroups d.*.linux_ppc-64_cmprssptrs_le,d.*.arch.ppc,d.*.os.linux,d.*.bits.64,d.*.generic-all

Ran 25 times without failure.

**Comment by pdbain-ibm** [comment]
Seems to fail on rhel6p7gcvm1.ottawa.ibm.com.

**Comment by pdbain-ibm** [comment]
Different issue.
