### ISSUE TITLE
MathLoadTest bigdecimal ArrayIndexOutOfBoundsException or NPE

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8397]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_mac_Nightly/778
MathLoadTest_bigdecimal_special_14
variation: Mode551
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced 
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/265
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/260
MathLoadTest_all_0
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64_aix_Nightly/494
MathLoadTest_all_special_19
variation: Mode610
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon 
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/517
MathLoadTest_all_special_21
variation: Mode687
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:gencon -Xaggressive 
```
MLT testFailure: testItem_0216(net.adoptopenjdk.test.bigdecimal.TestSuite047): null
MLT java.lang.ArrayIndexOutOfBoundsException
MLT 	at java.math.BigInteger.add(BigInteger.java:1340)
MLT 	at java.math.BigInteger.add(BigInteger.java:1238)
MLT 	at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1728)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1530)
MLT 	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1789)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1589)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1493)
MLT 	at java.math.BigInteger.pow(BigInteger.java:2403)
MLT 	at java.math.BigDecimal.bigTenToThe(BigDecimal.java:3574)
MLT 	at java.math.BigDecimal.bigDigitLength(BigDecimal.java:3851)
MLT 	at java.math.BigDecimal.precision(BigDecimal.java:2243)
MLT 	at java.math.BigDecimal.doRound(BigDecimal.java:4019)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:4754)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:1755)
MLT 	at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1795)
MLT 	at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1833)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite047.testItem_0216(TestSuite047.java:1605)
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/1036
MathLoadTest_bigdecimal_special_14 
MathLoadTest_all_special_14
```
MLT testFailure: testItem_0895(net.adoptopenjdk.test.bigdecimal.TestSuite043): null
MLT java.lang.NullPointerException
MLT 	at java.math.BigInteger.add(BigInteger.java:1340)
MLT 	at java.math.BigInteger.add(BigInteger.java:1238)
MLT 	at java.math.BigInteger.squareKaratsuba(BigInteger.java:2119)
MLT 	at java.math.BigInteger.square(BigInteger.java:1985)
MLT 	at java.math.BigInteger.square(BigInteger.java:1964)
MLT 	at java.math.BigInteger.pow(BigInteger.java:2407)
MLT 	at java.math.BigDecimal.bigTenToThe(BigDecimal.java:3574)
MLT 	at java.math.BigDecimal.bigMultiplyPowerTen(BigDecimal.java:4539)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:4745)
MLT 	at java.math.BigDecimal.divide(BigDecimal.java:1755)
MLT 	at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1795)
MLT 	at java.math.BigDecimal.divideAndRemainder(BigDecimal.java:1951)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite043.testItem_0895(TestSuite043.java:6202)
```
```
MLT testFailure: testItem_0216(net.adoptopenjdk.test.bigdecimal.TestSuite047): null
MLT java.lang.NullPointerException
MLT 	at java.math.BigInteger.add(BigInteger.java:1352)
MLT 	at java.math.BigInteger.add(BigInteger.java:1238)
MLT 	at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1725)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1530)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1493)
MLT 	at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1722)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1530)
MLT 	at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1589)
MLT 	at java.math.BigInteger.multiply(BigInteger.java:1493)
MLT 	at java.math.BigInteger.pow(BigInteger.java:2403)
MLT 	at java.math.BigDecimal.bigTenToThe(BigDecimal.java:3574)
MLT 	at java.math.BigDecimal.setScale(BigDecimal.java:2473)
MLT 	at java.math.BigDecimal.setScale(BigDecimal.java:2389)
MLT 	at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1798)
MLT 	at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1833)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite047.testItem_0216(TestSuite047.java:1605)
```

Changes 229e6e2...a055a16

**Comment by pshipton** [comment]
@andrewcraik can you pls take a look, and either quickly fix or the problematic change reverted until it can be.

**Comment by andrewcraik** [comment]
A few things landed yesterday so we'll have a look and see what's up

**Comment by hzongaro** [comment]
Grinder runs are not complete, but when I re-ran the https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/260 MathLoadTest_all_0 in Grinder, there were 15/100 failures.

Rerunning with `-Xjit:{java/math/Big*}(disableCFGSimplification)` thus far there are 0/47 failures.
Rerunning with `TR_disableTernaryOpForEA=yes` thus far there are 1/45 failures with
```15:58:54  MLT java.lang.ArrayIndexOutOfBoundsException
15:58:54  MLT 	at java.math.BigInteger.add(BigInteger.java:1340)
15:58:54  MLT 	at java.math.BigInteger.add(BigInteger.java:1238)```

So I think that suggests that the EA+aternary change hasn't caused the problem, but I'm not certain that it's caused by the CFG simplification change yet. . . .

**Comment by pshipton** [comment]
Probably related https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_windows_OMR/4
DaaLoadTest_daa2_0
```
DLT testFailure: testAddPackedDecimal(net.openj9.test.arithmetics.TestArithmeticOperations): null
DLT java.lang.ArrayIndexOutOfBoundsException
DLT 	at java.math.BigInteger.add(BigInteger.java:1335)
DLT 	at java.math.BigInteger.add(BigInteger.java:1238)
DLT 	at net.openj9.test.arithmetics.TestArithmeticOperations.testAddPackedDecimal(TestArithmeticOperations.java:10437)
```

**Comment by hzongaro** [comment]
There was a failure in the Grinder run with `-Xjit:{java/math/Big*}(disableCFGSimplification)`, so I reran with `-Xjit:disableCFGSimplification`.  That saw 10/100 failures.
The Grinder run with environment variable `TR_disableTernaryOpForEA=yes` saw 1/100 failing.
So either the problem was caused by something else or both of those changes are capable of triggering the same problem.
I will rerun with both of those changes disabled next.

**Comment by hzongaro** [comment]
In a rerun with both CFG Simplification and generation of `aternary` in Escape Analysis disabled, I've seen 4/24 tests fail so far, so I think this failure is unrelated to either of those changes.  I will continue to investigate.

**Comment by pshipton** [comment]
I didn't see this occur in the builds last night (although we didn't get any AIX testing, and some linux testing didn't run either).

**Comment by hzongaro** [comment]
There's something peculiar happening here.  If I do a grinder run of MathLoadTest_all_0 on x86-64_linux for a build that contains commit https://github.com/eclipse/openj9/commit/ed96ff0e14d4f810b80e1e37213dc14d2d07f3ed I still see the odd intermittent failure with an `ArrayIndexOutOfBoundsException` from `java.math.BigInteger.add` both with and without `-Xjit:disableCFGSimplification`, as I mentioned above.  However, with a build that rolls back to merge commit 08d732f4348e5e7b3cf136caaf75b245417c5305, which came just before the merge for ed96ff0e14d4f810b80e1e37213dc14d2d07f3ed, I see no failures with or without `-Xjit:disableCFGSimplification`.

So this might still be the same problem as issue 8397, but I haven't yet been able to rule out that it's a distinct problem.  Are there circumstances in which CFG simplifier can be enabled even if `disableCFGSimplification` has been specified?

Charlene @Charlmzz, FYI.

**Comment by rpshukla** [comment]
Based on the openjdk system test source code here: https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.math/src/test.math/net/adoptopenjdk/test/bigdecimal/TestSuite043.java#L6202, I have created the following small test case which fails every time for me:
```java
import java.math.BigDecimal;

public class Main {
   static BigDecimal[] resultArray;
   public static void main(String[] args) {
      for (int i = 0; i < 1000; i++) {
         resultArray = jitme();
      }
   }

   private static BigDecimal[] jitme() {
      return (new BigDecimal("-2E+9")).divideAndRemainder(new BigDecimal("1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
   }
}
```

I am running a local build of openjdk8 with the latest openj9 master, openj9-omr and the following options:
```
-Xjit:disableAsyncCompilation,{*BigInteger.add*}(optlevel=hot)
```

Output:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        at java.math.BigInteger.add(BigInteger.java:1340)
        at java.math.BigInteger.add(BigInteger.java:1238)
        at java.math.BigInteger.multiplyKaratsuba(BigInteger.java:1728)
        at java.math.BigInteger.multiply(BigInteger.java:1530)
        at java.math.BigInteger.multiplyToomCook3(BigInteger.java:1795)
        at java.math.BigInteger.multiply(BigInteger.java:1589)
        at java.math.BigInteger.multiply(BigInteger.java:1493)
        at java.math.BigInteger.pow(BigInteger.java:2403)
        at java.math.BigDecimal.bigTenToThe(BigDecimal.java:3574)
        at java.math.BigDecimal.bigMultiplyPowerTen(BigDecimal.java:4539)
        at java.math.BigDecimal.divide(BigDecimal.java:4745)
        at java.math.BigDecimal.divide(BigDecimal.java:1755)
        at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1795)
        at java.math.BigDecimal.divideAndRemainder(BigDecimal.java:1951)
        at Main.jitme(Main.java:18)
        at Main.main(Main.java:10)
```

**Comment by rpshukla** [comment]
The cause of this issue seems to be that the result register for `aselect` nodes is not always being flagged as a collected reference during codegen. I have opened this PR to fix this: https://github.com/eclipse/omr/pull/5474
