### ISSUE TITLE
cent6-x64-5 - 7 are offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8455]
https://ci.eclipse.org/openj9/computer/cent6-x64-5/log
```
[01/30/20 07:40:19] Launching agent
$ ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@140.211.168.230 "ssh -i ~/.ssh/id_rsa.aix jenkins@cent6-x64-5 'wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar'"
bash: line 0: exec: java: not found
ERROR: Unable to launch the agent for cent6-x64-5
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
@rajdeep-singh, it appears looking at #5 that alternatives is not working for java although I can see that java8 is clearly there.  Looks like there was some "damage" when moving the instance to the other frame.

```
[jenkins@cent6-x64-5 ~]$ /usr/lib/jvm/java-1.8.0-openjdk.x86_64/jre/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b07)
OpenJDK 64-Bit Server VM (build 25.242-b07, mixed mode)
```

**Comment by rajdeepsingh1** [comment]
@pshipton This was corrected last week, should be good to go for cent6-x64-5 - 7
