### ISSUE TITLE
JTReg Test Failure: java/util/logging/LogManagerAppContextDeadlock.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8483]
Failure link
------------
- test category: sanity.openjdk
- OS/architecture: aix
- Version: JDK 11+

Optional info
-------------
- intermittent failure (yes|no): no
- regression or new test: old regression
- if regression, what are the last passing:
```
14:48:35  JRE 11 AIX ppc64-64-Bit Compressed References 20190717_292 (JIT enabled, AOT enabled)
14:48:35  OpenJ9   - 0f66c64
14:48:35  OMR      - ec782f2
14:48:35  JCL      - fa49279 based on jdk-11.0.4+11
```
^ Release jdk-11.0.4+11 build. jdk-11.0.5 throws the error

Failure output (captured from console output)
---------------------------------------------
```
12:01:20  ACTION: main -- Passed. Execution successful
12:01:20  REASON: User specified action: run main/othervm LogManagerAppContextDeadlock UNSECURE 
12:01:20  TIME:   0.633 seconds
12:01:20  messages:
12:01:20  command: main LogManagerAppContextDeadlock UNSECURE
12:01:20  reason: User specified action: run main/othervm LogManagerAppContextDeadlock UNSECURE 
12:01:20  Mode: othervm [/othervm specified]
12:01:20  Additional options from @modules: --add-modules java.base,java.logging,java.management --add-exports java.base/jdk.internal.misc=ALL-UNNAMED

-> [PASSED]

12:01:20  ACTION: main -- Failed. Execution failed: `main' threw exception: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "shutdownHooks")
12:01:20  REASON: User specified action: run main/othervm LogManagerAppContextDeadlock SECURE 
12:01:20  TIME:   0.606 seconds
12:01:20  messages:
12:01:20  command: main LogManagerAppContextDeadlock SECURE
12:01:20  reason: User specified action: run main/othervm LogManagerAppContextDeadlock SECURE 
12:01:20  Mode: othervm [/othervm specified]
12:01:20  Additional options from @modules: --add-modules java.base,java.logging,java.management --add-exports java.base/jdk.internal.misc=ALL-UNNAMED

->
12:01:20  STDOUT:
12:01:20  Running test case: SECURE
12:01:20  FakeAppContext.getAppContext()
12:01:20  Should exit now...
12:01:20  Sem2 acquired: Thread #1 will be waiting to acquire Sem
12:01:20  Logger.getLogger(name).info(name)
12:01:20  Releasing Sem
12:01:20  Sem acquired: Thread #2 has called JavaAWTAccess
12:01:20  Releasing Sem
12:01:20  Releasing Sem
12:01:20  Done: FakeAppContext.getAppContext()
12:01:20  Releasing Sem
12:01:20  Done: Logger.getLogger(name).info(name)
12:01:20  Test SECURE Passed
12:01:20  Releasing Sem

12:01:20  STATUS:Passed.
12:01:20  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "shutdownHooks")
12:01:20  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "shutdownHooks")
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:650)
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:676)
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:663)
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:663)
12:01:20  	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:232)
12:01:20  	at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:650)	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
12:01:20  
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:676)	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:213)
12:01:20  
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:663)	at jdk.management/com.ibm.lang.management.internal.OperatingSystemNotificationThread.run(OperatingSystemNotificationThread.java:54)
12:01:20  
12:01:20  	at java.base/java.security.AccessControlContext.checkPermissionWithCache(AccessControlContext.java:663)
12:01:20  	at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:232)
12:01:20  	at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
12:01:20  	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
12:01:20  	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:213)
12:01:20  	at jdk.management/com.ibm.lang.management.internal.OperatingSystemNotificationThread.run(OperatingSystemNotificationThread.java:54)
12:01:20  STATUS:Failed.`main' threw exception: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "shutdownHooks")
12:01:20  STATUS:Failed.`main' threw exception: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "shutdownHooks")

```

**Comment by JasonFengJ9** [comment]
It appears `OperatingSystemNotificationThread.java` missed an `AccessController.doPrivileged()`.

**Comment by pshipton** [comment]
@JasonFengJ9 were you planning to fix it?

**Comment by JasonFengJ9** [comment]
sure, it seems a straightforward one.

**Comment by JasonFengJ9** [comment]
@adam-thorpe is the failure reproducible in latest nightly builds? is it platform specific?
