### ISSUE TITLE
java/lang/ProcessBuilder/Basic.java fails on openj9 aix

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#8504]
See also https://github.com/AdoptOpenJDK/openjdk-tests/issues/1397

java/lang/ProcessBuilder/Basic.java fails in two ways on AIX:
1. The text output from operating system messages in java exceptions is not anticipated, so the checks fail.  This affects both openj9 and hotspot jdks and requires a fix to the openjdk test.
2. The test checks that the LIBPATH of a started process is the same as the process which started it. This test fails on openj9 AIX only.

jvm.c adds /usr/lib to LIBPATH on AIX.  So the starting process already has /usr/lib on its LIBPATH; the started process then has it added a second time, and the LIBPATH test fails with:
```
LIBPATH=/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/j9vm:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/jli:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/../lib/ppc64:/usr/lib:/usr/lib, not equal to LIBPATH=/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/j9vm:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/lib/ppc64/jli:/ramdisk0/build/workspace/Grinder/openjdkbinary/j2sdk-image/jre/../lib/ppc64:/usr/lib,
```
The test would succeed if /usr/lib were added to LIBPATH only if it were not already present.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/36
```
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2744)
	at Basic.fail(Basic.java:2745)
	at Basic.equal(Basic.java:2751)
	at Basic.realMain(Basic.java:1853)
	at Basic.main(Basic.java:2754)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:836)
Incorrect handling of envstrings containing NULs
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2744)
	at Basic.fail(Basic.java:2745)
	at Basic.check(Basic.java:2748)
	at Basic.realMain(Basic.java:1907)
	at Basic.main(Basic.java:2754)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:836)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:2756)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/39
like https://github.com/eclipse/openj9/issues/8504#issuecomment-629283640
