### ISSUE TITLE
testSCCacheManagement_0_FAILED Error: should never hit this code.

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8511]
Failure link
------------

From an internal build:
```
23:15:22  openjdk version "11.0.7-internal" 2020-04-14
23:15:22  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11x86-64macNightly)
23:15:22  Eclipse OpenJ9 VM (build ibm_sdk-479247ea9a, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200204_307 (JIT enabled, AOT enabled)
23:15:22  OpenJ9   - 479247ea9a
23:15:22  OMR      - b6a8e9309
23:15:22  JCL      - 54c0ee734c2 based on jdk-11.0.7+1)
```

Optional info
-------------

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
00:37:39  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_mac&TARGET=testSCCacheManagement_0

Failure output (captured from console output)
---------------------------------------------

```
23:24:42  There was 1 error:
23:24:42  1) testCacheCreationListingDestroying02(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: Error: should never hit this code.
23:24:42  	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
23:24:42  	at tests.sharedclasses.TestUtils.getCacheFileName(TestUtils.java:705)
23:24:42  	at tests.sharedclasses.TestUtils.getCacheFileLocationForPersistentCache(TestUtils.java:570)
23:24:42  	at tests.sharedclasses.TestUtils.checkNoFileForPersistentCache(TestUtils.java:851)
23:24:42  	at tests.sharedclasses.options.TestCacheCreationListingDestroying02.main(TestCacheCreationListingDestroying02.java:95)
23:24:42  	at tests.sharedclasses.options.junit.TestOptionsBase.testCacheCreationListingDestroying02(TestOptionsBase.java:34)
23:24:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:24:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:24:42  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:24:42  
23:24:42  FAILURES!!!
23:24:42  Tests run: 168,  Failures: 0,  Errors: 1
23:24:42  
23:24:42  
23:24:42  testSCCacheManagement_0_FAILED
23:24:42  
```

**Comment by pshipton** [comment]
@hangshao0 pls take a look.

**Comment by hangshao0** [comment]
Here are more output from the failure:

```
Command executed: '/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java -Xcompressedrefs  -Xshareclasses:printCacheFilename,name=Foo,persistent '
vvv STDOUT vvv

^^^ STDOUT ^^^
vvv STDERR vvv
Error: Port Library failed to initialize: -1
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

^^^ STDERR ^^^
vvv STACK TRACE vvv
java.lang.Throwable
	at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
	at tests.sharedclasses.TestUtils.getCacheFileName(TestUtils.java:705)
	at tests.sharedclasses.TestUtils.getCacheFileLocationForPersistentCache(TestUtils.java:570)
	at tests.sharedclasses.TestUtils.checkNoFileForPersistentCache(TestUtils.java:851)
	at tests.sharedclasses.options.TestCacheCreationListingDestroying02.main(TestCacheCreationListingDestroying02.java:95)
	at tests.sharedclasses.options.junit.TestOptionsBase.testCacheCreationListingDestroying02(TestOptionsBase.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at junit.textui.TestRunner.start(TestRunner.java:180)
	at junit.textui.TestRunner.main(TestRunner.java:138)
^^^ STACK TRACE ^^^
2nd last command executed: '/Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java -Xcompressedrefs  -Xshareclasses:printCacheFilename,name=Foo,persistent '
vvv 2ND LAST STDOUT vvv

^^^ 2ND LAST STDOUT ^^^
vvv 2ND LAST STDERR vvv
/Users/jenkins/javasharedresources/C290M11F1A64P_Foo_G41L00

^^^ 2ND LAST STDERR ^^^
Error: should never hit this code.
	Last command: /Users/jenkins/workspace/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java -Xcompressedrefs  -Xshareclasses:printCacheFilename,name=Foo,persistent 
```

The test code is parsing the cache file name from -Xshareclasses:printCacheFilename in the stderr. 
The cache file name is in the 2nd last stderr:
`/Users/jenkins/javasharedresources/C290M11F1A64P_Foo_G41L00`

The current stderr is:
```
Error: Port Library failed to initialize: -1
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
which might have caused the test to fail.

**Comment by hangshao0** [comment]
I have printed out more debug info. The error:
```
Error: Port Library failed to initialize: -1
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
causes the test to fail. The failure is intermittent.

**Comment by JasonFengJ9** [comment]
Another manifestation of `testSCCacheManagement_0_FAILED` from an internal build `Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly/323`
```
There were 2 errors:
1) testDestroyCache(tests.sharedclasses.options.junit.TestOptionsDefault)java.lang.RuntimeException: Not all expected messages were found
	at tests.sharedclasses.RunCommand.execute(RunCommand.java:216)
	at tests.sharedclasses.options.TestDestroyCache.testCase2(TestDestroyCache.java:96)
	at tests.sharedclasses.options.TestDestroyCache.main(TestDestroyCache.java:43)
	at tests.sharedclasses.options.junit.TestOptionsBase.testDestroyCache(TestOptionsBase.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2) testExpireDestroyOnCorruptCache(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/home/jenkins/javasharedresources/C290M11F1A64P_Foo_G41L00'
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 168,  Failures: 0,  Errors: 2


testSCCacheManagement_0_FAILED
```

**Comment by hangshao0** [comment]
Seems that the cache file is accidentally deleted by another process.

`No file found at '/home/jenkins/javasharedresources/C290M15F1A64P_Foo_G41L00'`

**Comment by hangshao0** [comment]
testSCCacheManagement_0 passed in the next Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly and Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly builds.

**Comment by pshipton** [comment]
Let's close this since it is a rare occurrence, and revisit if it starts to occur often.

**Comment by JasonFengJ9** [comment]
One more occurrence at `Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly/337`
```
There was 1 error:
1) testExpireDestroyOnCorruptCache(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/home/jenkins/javasharedresources/C290M11F1A64P_Foo_G41L00'
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 168,  Failures: 0,  Errors: 1


testSCCacheManagement_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/38
testSCCacheManagement_0
```
.Running  :testExpireDestroyOnCorruptCache  (Test suite : TestOptionsDefault)
Command executed: '/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=Foo,persistent '
vvv STDOUT vvv

^^^ STDOUT ^^^
vvv STDERR vvv
/home/jenkins/javasharedresources/C290M4F1A64P_Foo_G41L00

^^^ STDERR ^^^
vvv STACK TRACE vvv
java.lang.Throwable
	at tests.sharedclasses.TestUtils.showOutput(TestUtils.java:786)
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:595)
	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at junit.textui.TestRunner.start(TestRunner.java:180)
	at junit.textui.TestRunner.main(TestRunner.java:138)
^^^ STACK TRACE ^^^
2nd last command executed: '/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=Foo,persistent '
vvv 2ND LAST STDOUT vvv

^^^ 2ND LAST STDOUT ^^^
vvv 2ND LAST STDERR vvv
/home/jenkins/javasharedresources/C290M4F1A64P_Foo_G41L00

^^^ 2ND LAST STDERR ^^^
No file found at '/home/jenkins/javasharedresources/C290M4F1A64P_Foo_G41L00'
	Last command: /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java   -Xshareclasses:printCacheFilename,name=Foo,persistent 
E

Time: 775.238
There was 1 error:
1) testExpireDestroyOnCorruptCache(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/home/jenkins/javasharedresources/C290M4F1A64P_Foo_G41L00'
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
```

**Comment by JasonFengJ9** [comment]
[JDK17 aarch64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.functional_aarch64_linux_testList_0/427/)(`sles15-aarch64-4`)
```
[2023-10-18T23:25:05.281Z] variation: NoOptions
[2023-10-18T23:25:05.281Z] JVM_OPTIONS:  

[2023-10-18T23:42:57.162Z] There were 5 errors:
[2023-10-18T23:42:57.162Z] 1) testCorruptedCaches02(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: Cannot ftpascii file java.io.FileNotFoundException: /home/jenkins/.cache/javasharedresources/C290M17F1A64P_Foo_G43L00 (No such file or directory)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.corruptCache(TestUtils.java:1273)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestCorruptedCaches02.main(TestCorruptedCaches02.java:39)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testCorruptedCaches02(TestOptionsBase.java:65)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-18T23:42:57.162Z] 2) testPersistentCacheMoving03(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: Cannot copy file '/home/jenkins/.cache/javasharedresources/C290M17F1A64P_Foo_G43L00' java.io.FileNotFoundException: /home/jenkins/.cache/javasharedresources/C290M17F1A64P_Foo_G43L00 (No such file or directory)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.copyFile(TestUtils.java:1398)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestPersistentCacheMoving03.main(TestPersistentCacheMoving03.java:120)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testPersistentCacheMoving03(TestOptionsBase.java:95)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-18T23:42:57.162Z] 3) testSharedCacheJavaAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: SharedClassUtilities.getSharedCacheInfo failed: Invalid number of cache found	expected: 7	found: 8
[2023-10-18T23:42:57.162Z]  oldCacheCount is 0
[2023-10-18T23:42:57.162Z]  persistentGroupAccessCount is 1
[2023-10-18T23:42:57.162Z]  nonpersistentGroupAccessCount is 1
[2023-10-18T23:42:57.162Z]  persistentCount is 3
[2023-10-18T23:42:57.162Z]  nonpersistentCount is 1
[2023-10-18T23:42:57.162Z]  snapshotCount is 1
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestSharedCacheJavaAPI.main(TestSharedCacheJavaAPI.java:208)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJavaAPI(TestOptionsBase.java:120)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-18T23:42:57.162Z] 4) testDestroyCache(tests.sharedclasses.options.junit.TestOptionsDefault)java.lang.RuntimeException: Not all expected messages were found
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.RunCommand.execute(RunCommand.java:216)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestDestroyCache.testCase6(TestDestroyCache.java:395)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestDestroyCache.main(TestDestroyCache.java:47)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testDestroyCache(TestOptionsBase.java:121)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-18T23:42:57.162Z] 5) testExpireDestroyOnCorruptCache(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/home/jenkins/.cache/javasharedresources/C290M17F1A64P_Foo_G43L00'
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.TestExpireDestroyOnCorruptCache.main(TestExpireDestroyOnCorruptCache.java:60)
[2023-10-18T23:42:57.162Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testExpireDestroyOnCorruptCache(TestOptionsBase.java:122)
[2023-10-18T23:42:57.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-10-18T23:42:57.163Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2023-10-18T23:42:57.163Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-10-18T23:42:57.163Z] 
[2023-10-18T23:42:57.163Z] FAILURES!!!
[2023-10-18T23:42:57.163Z] Tests run: 168,  Failures: 0,  Errors: 5
[2023-10-18T23:42:57.163Z] 
[2023-10-18T23:42:57.163Z] -----------------------------------
[2023-10-18T23:42:57.163Z] testSCCacheManagement_0_FAILED
```

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_extended.functional_aarch64_mac](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_extended.functional_aarch64_mac_testList_0/27/)
```
[2025-09-19T22:25:16.728Z] Running test testSCCacheManagement_0 ...
[2025-09-19T22:25:16.728Z] ===============================================
[2025-09-19T22:25:16.728Z] testSCCacheManagement_0 Start Time: Fri Sep 19 15:25:15 2025 Epoch Time (ms): 1758320715202
[2025-09-19T22:25:16.728Z] variation: NoOptions
[2025-09-19T22:25:16.728Z] JVM_OPTIONS:  

[2025-09-19T22:47:51.114Z] There was 1 error:
[2025-09-19T22:47:51.114Z] 1) testSharedCacheJavaAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: No file found at '/Users/jenkins/.cache/javasharedresources/C290M25F2A64P_cache3_multilayercache_G45L00'
[2025-09-19T22:47:51.114Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2025-09-19T22:47:51.114Z] 	at tests.sharedclasses.TestUtils.checkFileExists(TestUtils.java:584)
[2025-09-19T22:47:51.114Z] 	at tests.sharedclasses.TestUtils.checkFileExistsForPersistentCache(TestUtils.java:880)
[2025-09-19T22:47:51.114Z] 	at tests.sharedclasses.options.TestSharedCacheJavaAPI.main(TestSharedCacheJavaAPI.java:150)
[2025-09-19T22:47:51.114Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJavaAPI(TestOptionsBase.java:120)
```
