### ISSUE TITLE
JDK14 IllegalArgumentException at org.objectweb.asm.ClassReader.<init>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8549]
Failure link
------------

From internal builds.
```
23:21:28  openjdk version "14-internal" 2020-03-17
23:21:28  OpenJDK Runtime Environment (build 14-internal+0-adhoc.jenkins.BuildJDK14ppc64aixNightly)
23:21:28  Eclipse OpenJ9 VM (build ibm_sdk-9f4164c186, JRE 14 AIX ppc64-64-Bit Compressed References 20200209_23 (JIT enabled, AOT enabled)
23:21:28  OpenJ9   - 9f4164c186
23:21:28  OMR      - 2065a9182
23:21:28  JCL      - 92ee44af358 based on jdk-14+34)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
[OUT] *** Testing [12/13]:	testBCIUsingASM_inject_stackValueUsage_After_Branch_Using_IfCompare
 [OUT] pre : 2
 [OUT] Expected pre-transform result received
 [ERR] Exception in thread "Thread-4" Exception in thread "Thread-5" Exception in thread "Thread-3" java.lang.IllegalArgumentException
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)java.lang.IllegalArgumentExceptionjava.lang.IllegalArgumentException
 [ERR] 
 [ERR] 
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at com.ibm.jvmti.tests.BCIWithASM.ASMTransformer.inject_call_to_timerMethod(ASMTransformer.java:1114)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
 [ERR] 	at com.ibm.jvmti.tests.BCIWithASM.ta001$1ProfilerThread.run(ta001.java:357)	at com.ibm.jvmti.tests.BCIWithASM.ASMTransformer.inject_call_to_timerMethod(ASMTransformer.java:1114)
 [ERR] 	at com.ibm.jvmti.tests.BCIWithASM.ta001$1ProfilerThread.run(ta001.java:357)
 [ERR] 	at com.ibm.jvmti.tests.BCIWithASM.ASMTransformer.inject_call_to_timerMethod(ASMTransformer.java:1114)
 [ERR] 	at com.ibm.jvmti.tests.BCIWithASM.ta001$1ProfilerThread.run(ta001.java:357)
 [ERR] 
Time spent executing: 266632 milliseconds
Test result: FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
10:19:24  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_jvmtitests_hcr_OSRG_nongold_2

**Comment by pshipton** [comment]
@JasonFengJ9 have there been more occurrences of this failure?
BTW, it would be nice to know which test suite the failures come from.

**Comment by JasonFengJ9** [comment]
> have there been more occurrences of this failure?
BTW, it would be nice to know which test suite the failures come from (i.e. sanity or extended).

It passed in latest builds.
```
03:11:32  Testing: ta001
03:11:32  Test start time: 2020/02/24 03:11:29 Eastern Standard Time
03:11:32  Running command: "/home/jenkins/workspace/Test_openjdk14_j9_extended.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation  -Xdump    -agentlib:jvmtitest=test:ta001 -cp "/home/jenkins/workspace/Test_openjdk14_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk14_j9_extended.functional_ppc64_aix_Nightly/openjdk-tests/TKG/../TKG/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
03:11:32  Time spent starting: 10 milliseconds
03:12:52  Time spent executing: 77330 milliseconds
03:12:52  Test result: PASSED

03:12:52  ---TEST RESULTS---
03:12:52  Number of PASSED tests: 24 out of 24
03:12:52  Number of FAILED tests: 0 out of 24
03:12:52  
03:12:52  cmdLineTester_jvmtitests_hcr_OSRG_nongold_2_PASSED
```

The rebuild link only shows it is `functional` and the TARGET is `cmdLineTester_jvmtitests_hcr_OSRG_nongold_2`.
It is an `extended` level test.1
