### ISSUE TITLE
JTReg Test Failure: java/lang/String/TranslateEscapes.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8563]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk14_j9_sanity.openjdk_x86-64_linux/1/
- test category: sanity.openjdk
- OS/architecture: jdk14 all

Optional info
-------------
- intermittent failure (yes|no): no
- regression or new test: regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
Failing since first jdk14 openj9 builds. Passes jdk 13.0.2

Failure output (captured from console output)
---------------------------------------------
```
java.lang.IllegalArgumentException: Invalid escape sequence detected: \s
	at java.base/java.lang.String.translateEscapes(String.java:4189)
	at TranslateEscapes.verifyEscape(TranslateEscapes.java:91)
	at TranslateEscapes.test1(TranslateEscapes.java:48)
	at TranslateEscapes.main(TranslateEscapes.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by sharon-wang** [comment]
`\s` is a new escape sequence for "space" introduced in JDK 14, however we don't have support for this. http://cr.openjdk.java.net/~iris/se/14/build/latest/api/java.base/java/lang/String.html#translateEscapes()

I'll work on adding support for this
