### ISSUE TITLE
JDKnext : Mauve[gnu.testlet.java.text.DecimalFormat.setGroupingSize] IllegalArgumentException: newValue is out of valid range. value: -1

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8620]
Failure link
------------

From internal builds:
```
00:35:31  openjdk version "15-internal" 2020-09-15
00:35:31  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
00:35:31  Eclipse OpenJ9 VM (build ibm_sdk-3d3bf4e3ef, JRE 15 AIX ppc64-64-Bit Compressed References 20200219_135 (JIT enabled, AOT enabled)
00:35:31  OpenJ9   - 3d3bf4e3ef
00:35:31  OMR      - dae5f37f5
00:35:31  JCL      - ed3a3ffbf5c based on jdk-15+10)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  02:30:55.872 -   4614 Mauve[gnu.testlet.javax.swing.ViewportLayout.minimumLayoutSize]  Weighting=1 
LT  02:30:55.872 -   4615 Mauve[gnu.testlet.javax.xml.xpath.XPath]  Weighting=1 
LT  02:30:56.130 - Starting thread. Suite=0 thread=0
LT  02:31:06.933 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
LT  02:31:06.935 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3676
LT    Test details  = 'Mauve[gnu.testlet.java.text.DecimalFormat.setGroupingSize]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.text.DecimalFormat.setGroupingSize (number 0)
LT  PASS: gnu.testlet.java.text.DecimalFormat.setGroupingSize (number 1)
LT  Test failed:
LT  java.lang.IllegalArgumentException: newValue is out of valid range. value: -1
LT  	at java.base/java.text.DecimalFormat.setGroupingSize(DecimalFormat.java:2801)
LT  	at gnu.testlet.java.text.DecimalFormat.setGroupingSize.test(setGroupingSize.java:48)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
LT  	at java.base/java.lang.Thread.run(Thread.java:835)
LT  <<<
LT  
LT  02:31:14.551 - Test failed. Details recorded in execution log.
LT  02:31:16.053 - Completed 0.4%. Number of tests started=8012 (with 2 failure(s))
```

This is a similar failure as https://github.com/eclipse/openj9/issues/8086.

fyi @Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/327 excludes the sub-test on jdk14+. Please verify and close the issue.

**Comment by JasonFengJ9** [comment]
The failure is not seen in latest build, thanks for quick action.
Closing.
