### ISSUE TITLE
NullPointerException's running testJITServer_0 on x86-64_linux_xl

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8674]
testJITServer_0

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OpenJDK11/38
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/sun.net.www.protocol.jar.Handler.checkNestedProtocol(Handler.java:125)
	at java.base/java.net.URL.<init>(URL.java:465)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:831)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:604)
	at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:587)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:586)
	at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:550)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:413)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:469)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:895)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:806)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:764)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078)
	at org.testng.TestNG.setOutputDirectory(TestNG.java:222)
	at org.testng.TestNG.configure(TestNG.java:1376)
	at org.testng.TestNG.privateMain(TestNG.java:1344)
	at org.testng.TestNG.main(TestNG.java:1323)
```

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR/434
```
Exception in thread "main" java.lang.NullPointerException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:942)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at org.testng.TestNG.setOutputDirectory(TestNG.java:222)
	at org.testng.TestNG.configure(TestNG.java:1376)
	at org.testng.TestNG.privateMain(TestNG.java:1344)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@mpirvu

**Comment by pshipton** [comment]
@mpirvu

**Comment by harryyu1994** [comment]
Should be fixed now, verifying: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/6594/

**Comment by harryyu1994** [comment]
Grinder 10/10 passed with latest build. @mpirvu This one can be closed.
