### ISSUE TITLE
JDK8 cmake : UnsatisfiedLinkError: com/ibm/jvmti/tests/redefineClasses/rc020.redefineClass(Ljava/lang/Class;I[B)Z

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8682]
Failure link
------------

From an internal cmake build:
```
21:52:59  openjdk version "1.8.0_252-internal"
21:52:59  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_02_27_18_16-b00)
21:52:59  Eclipse OpenJ9 VM (build ibm_sdk-c5d14933a4, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200227_3 (JIT enabled, AOT enabled)
21:52:59  OpenJ9   - unknown
21:52:59  OMR      - 6d123a4d8
21:52:59  JCL      - 4d1d1433e96 based on jdk8u252-b04)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Testing: rc020
Test start time: 2020/02/28 00:12:11 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_cm_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation  -Xdump    -agentlib:jvmtitest=test:rc020 -cp "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_cm_Nightly/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_cm_Nightly/openjdk-tests/TKG/../TKG/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 1 milliseconds
Time spent executing: 37740 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/1]:	testIndyRedefinition
 [ERR] exception thrown: null
 [ERR] java.lang.reflect.InvocationTargetException
 [ERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [ERR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 [ERR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 [ERR] 	at java.lang.reflect.Method.invoke(Method.java:498)
 [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
 [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
 [ERR] Caused by: java.lang.UnsatisfiedLinkError: com/ibm/jvmti/tests/redefineClasses/rc020.redefineClass(Ljava/lang/Class;I[B)Z
 [ERR] 	at com.ibm.jvmti.tests.redefineClasses.rc020.runTest(rc020.java:121)
 [ERR] 	at com.ibm.jvmti.tests.redefineClasses.rc020.runTest(rc020.java:116)
 [ERR] 	at com.ibm.jvmti.tests.redefineClasses.rc020.testIndyRedefinition(rc020.java:44)
 [ERR] 	... 8 more
>> Success condition was not found: [Return code: 0]
```

**Comment by DanHeidinga** [comment]
fyi @dnakamura

**Comment by gacholio** [comment]
Looks like someone (perhaps me) forgot to add this native to the cmake exports.
