### ISSUE TITLE
jvmnativestest_0 passes despite errors

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#8716]
Failure link
------------
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/297

Optional info
-------------
- intermittent failure (yes|no): 

Failure output (captured from console output)
---------------------------------------------
```
[2020-03-02T05:48:38.401Z] ===============================================
[2020-03-02T05:48:38.401Z] Running test jvmnativestest_0 ...
[2020-03-02T05:48:38.401Z] ===============================================
[2020-03-02T05:48:38.401Z] jvmnativestest_0 Start Time: Mon Mar  2 00:48:37 2020 Epoch Time (ms): 1583128117713
[2020-03-02T05:48:38.401Z] "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2020-03-02T05:48:38.401Z] JVMSHRC005I No shared class caches available
[2020-03-02T05:48:38.401Z] JVMSHRC005I No shared class caches available
[2020-03-02T05:48:38.401Z] cache cleanup done
[2020-03-02T05:48:38.401Z] variation: NoOptions
[2020-03-02T05:48:38.401Z] JVM_OPTIONS: -Xcompressedrefs 
[2020-03-02T05:48:38.401Z] { itercnt=1; \
[2020-03-02T05:48:38.401Z] 	mkdir -p "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../TKG/test_output_15831257047474/jvmnativestest_0"; \
[2020-03-02T05:48:38.401Z] 	cd "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../TKG/test_output_15831257047474/jvmnativestest_0"; \
[2020-03-02T05:48:38.401Z] 	export DYLD_LIBRARY_PATH="/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/openjdk-test-image/openj9:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/jre/bin/../lib//compressedrefs:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/jre/bin/../lib//j9vm:"; \
[2020-03-02T05:48:38.401Z] 	"/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs  \
[2020-03-02T05:48:38.401Z] 	-cp "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../TKG/lib/junit4.jar" \
[2020-03-02T05:48:38.401Z] 	com.ibm.oti.jvmtests.AutoRun; \
[2020-03-02T05:48:38.401Z] 	if [ $? -eq 0 ] ; then echo ""; echo "jvmnativestest_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/..; rm -f -r "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../TKG/test_output_15831257047474/jvmnativestest_0"; else echo ""; echo "jvmnativestest_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/openjdk-tests/TKG/../TKG/test_output_15831257047474/TestTargetResult";
[2020-03-02T05:48:38.401Z] .E.E.E.E.E.E.E.E.E
[2020-03-02T05:48:38.401Z] Time: 0.003
[2020-03-02T05:48:38.401Z] There were 9 errors:
[2020-03-02T05:48:38.401Z] 1) test_CallGetNanoTimeAdjustment(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_CallGetNanoTimeAdjustment(GetNanoTimeAdjustment.java:39)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.401Z] 2) test_EnsureWallClockTime(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_EnsureWallClockTime(GetNanoTimeAdjustment.java:47)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.401Z] 3) test_EnsureResultIsNanoSecondGranularity(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_EnsureResultIsNanoSecondGranularity(GetNanoTimeAdjustment.java:61)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.401Z] 4) test_PositiveOffset(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_PositiveOffset(GetNanoTimeAdjustment.java:70)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.401Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.401Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 5) test_PositiveOffset2(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_PositiveOffset2(GetNanoTimeAdjustment.java:80)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 6) test_NegativeOffset(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_NegativeOffset(GetNanoTimeAdjustment.java:100)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 7) test_NegativeOffset2(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_NegativeOffset2(GetNanoTimeAdjustment.java:110)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 8) test_UpperBound(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_UpperBound(GetNanoTimeAdjustment.java:129)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 9) test_LowerBound(com.ibm.oti.jvmtests.GetNanoTimeAdjustment)java.lang.UnsatisfiedLinkError: com/ibm/oti/jvmtests/SupportJVM.GetNanoTimeAdjustment(J)J
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.GetNanoTimeAdjustment.test_LowerBound(GetNanoTimeAdjustment.java:139)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-02T05:48:38.402Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-02T05:48:38.402Z] 	at com.ibm.oti.jvmtests.AutoRun.main(AutoRun.java:34)
[2020-03-02T05:48:38.402Z] 
[2020-03-02T05:48:38.402Z] FAILURES!!!
[2020-03-02T05:48:38.402Z] Tests run: 9,  Failures: 0,  Errors: 9
```

**Comment by pshipton** [comment]
@llxia A problem with junit?
We'll need to fix the test before fixing the junit problem, otherwise sanity.functional will fail across all platforms.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/pull/8720 should fix the test, it shouldn't be running on jdk8.

**Comment by llxia** [comment]
It looks like the test exits normally when there is a failure:
https://github.com/eclipse/openj9/blob/ebec356635a35ff2acbd4e3958752c309b9bcdc4/test/functional/VM_Test/src/com/ibm/oti/jvmtests/AutoRun.java#L33-L39

@LongyuZhang Could you add `System.exit(-2)` when there is failure? Thanks

**Comment by llxia** [comment]
Both #8720 and #8727 are merged.
Close this issue. Please reopen if the problem still occurs.
