### ISSUE TITLE
testJITServer NullPointerException StringBuilder.ensureCapacityImpl 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8726]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/296
testJITServer_1
```
JITServer is currently a technology preview. Its use is not yet supported
JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServerUnreachableForAWhile.client.jitverboselog.out
Exception in thread "main" java.lang.NullPointerException
java/lang/NullPointerException
	at java/lang/StringBuilder.ensureCapacityImpl (StringBuilder.java:4294967295)
	at java/lang/StringBuilder.append (StringBuilder.java:564)
	at java/lang/J9VMInternals.initializationAlreadyFailed (J9VMInternals.java:98)
	at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:872)
	at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:866)
	at java/lang/Thread.uncaughtException (Thread.java:1335)
Exception in thread "Attach API teardown" java.lang.NullPointerException
java/lang/NullPointerException
	at java/lang/StringBuilder.ensureCapacityImpl (StringBuilder.java:4294967295)
	at java/lang/StringBuilder.append (StringBuilder.java:564)
	at java/lang/J9VMInternals.initializationAlreadyFailed (J9VMInternals.java:98)
	at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:872)
	at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:866)
	at java/lang/Thread.uncaughtException (Thread.java:1335)

PASSED: testServer
PASSED: testServerComesUpAfterClient
PASSED: testServerComesUpAfterClientAndGoesDownAgain
PASSED: testServerGoesDown
PASSED: testServerGoesDownAnotherComesUp
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.fail(AssertJUnit.java:66)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:122)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:289)
```

**Comment by pshipton** [comment]
@mpirvu

**Comment by harryyu1994** [comment]
@mpirvu 25/25 grinder passed with latest. (Original failure rate is around 3/5). We can close this one.

**Comment by mpirvu** [comment]
Supposedly fixed by https://github.com/eclipse/openj9/pull/8811
