### ISSUE TITLE
Reboot Windows machines

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8740]
Might be time to reboot all the Windows machines.

win2012r2-x86-4 disabled.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/298
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.system_x86-64_windows_Nightly/25
```
Command Close created at
	at hudson.remoting.Command.<init>(Command.java:68)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1267)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1265)
	at hudson.remoting.Channel.close(Channel.java:1438)
	at hudson.remoting.Channel.close(Channel.java:1405)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1272)
Caused: hudson.remoting.Channel$OrderlyShutdown
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to win2012r2-x86-4
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.Request.call(Request.java:202)
		at hudson.remoting.Channel.call(Channel.java:956)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:144)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:822)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:813)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$279.000000005406D620.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
Caused: hudson.remoting.RequestAbortedException
	at hudson.remoting.Request.abort(Request.java:340)
	at hudson.remoting.Channel.terminate(Channel.java:1040)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1273)
	at hudson.remoting.Channel$1.handle(Channel.java:565)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:85)
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/view/Infrastructure/job/Sanitize-Nodes/291/
The sanitize job runs at 9pm and reboots the windows machines. Looks like it failed last night. I can take a look later this morning if Joe hasn't beat me to it by then.

**Comment by jdekonin** [comment]
win2012r2-x86-4 rebooted and back online.
