### ISSUE TITLE
OpenJ9 exception stack trace handling different than OpenJDK

### ISSUE THREAD

**Issue by sdwr98** [eclipse/openj9#8760]
Hi all,

I have discovered a difference in behavior between OpenJ9 and OpenJDK when dealing with serializing/deserializing exceptions using the google `gson` library.  

### Scenario
I am trying to serialize/deserialize an exception class using the Google `gson` library, and I've discovered a problem when trying to set the stack trace when running OpenJ9.  

 My Exception class does not have a default constructor, and so when `gson` creates the class, it appears to set the value of `Throwable.enableWritableStackTrace` to false.   This means that when we try to set the stack trace later on using `setStackTrace()`, the setter performs a no-op.  

### Expected Output: 
```
Exception before serialization: 
com.motus.TestException
	at com.motus.Main.main(Main.java:8)

Exception after serialization: 
com.motus.TestException
	at com.motus.Main.main(Main.java:8)
```

### Actual Output: 
```
Exception before serialization: 
com.motus.TestException
	at com.motus.Main.main(Main.java:8)

Exception after serialization: 
com.motus.TestException
```

### Environment: 
Open J9: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200122_439 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)
```

OpenJDK: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

To reproduce, run `mvn exec:java` on the attached Maven project with OpenJ9 and OpenJDK

[openj9-gson-exception.zip](https://github.com/eclipse/openj9/files/4294641/openj9-gson-exception.zip)

**Comment by sdwr98** [comment]
Thanks for the quick fix y'all!
