### ISSUE TITLE
JDK8 testDDRExt_SharedClasses_openj9_0_FAILED AssertionFailedError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8767]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/301/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
 [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcJITHStatsExt(TestSharedClassesExt.java:492)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
     [java] [AutoRun] [INFO] Finished testShrcJITHStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testShrcFindJITHext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  findjith <init>'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  findjith <init>'
     [java] [AutoRun] [INFO] Finished testShrcFindJITHext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testShrcFindJITHPext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  findjithp <init>'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  findjithp <init>'
     [java] [AutoRun] [INFO] Finished testShrcFindJITHPext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testShrcJITHForExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  jithfor 0x00007F15E9407180'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  jithfor 0x00007F15E9407180'
     [java] [AutoRun] [INFO] Finished testShrcJITHForExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testShrcWriteExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  write .'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  write .'
     [java] [AutoRun] [INFO] Finished testShrcWriteExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] 
     [java] [AutoRun] [INFO] ================Test Result for /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdk-tests/TKG/../TKG/test_output_15834759342049/testDDRExt_SharedClasses_openj9_0/DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   0 out of 30 test cases.
     [java] [AutoRun] [INFO] Failures: 9 out of 30 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 9
     [java] [AutoRun] [ERROR] testShrcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcAllStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcRcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcCpStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcJITPStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcFindJITPext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcFindJITPPext(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcJITPForExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [AutoRun] [ERROR] testShrcJITHStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)

BUILD FAILED
/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/jvmtest/functional/DDR_Test/tck_ddrext.xml:102: Java returned: 254

Total time: 22 seconds

testDDRExt_SharedClasses_openj9_0_FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
04:46:14  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=testDDRExt_SharedClasses_openj9_0

**Comment by hangshao0** [comment]
The test expects to see some JIT profile data, however it is 0:

`JITPROFILE data length 0`.

Probably we can wait and see if this happen again.

**Comment by JasonFengJ9** [comment]
Another `AssertionFailedError` at an internal build `Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/324`
```
[java] [AutoRun] [INFO] Starting testShrcUByteStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
     [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  ubytestats'
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 240
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 925248  STARTUPHINTS 96
     [java] 	JITHINT 0  AOTCLASSCHAIN 64 AOTTHUNK 0
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 147398
     [java] 	LocalVariableTable bytes : 718
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcAOTStatsExt(TestSharedClassesExt.java:79)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
     [java] 	at junit.framework.TestResult.run(TestResult.java:113)
     [java] 	at junit.framework.TestCase.run(TestCase.java:124)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
     [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
     [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
     [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)

     [java] [AutoRun] [INFO] ================Test Result for /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/openjdk-tests/TKG/../TKG/test_output_15838221193465/testDDRExt_SharedClasses_openj9_0/DDREXT.J9CORE.DMP==================
     [java] [AutoRun] [INFO] Errors:   0 out of 30 test cases.
     [java] [AutoRun] [INFO] Failures: 1 out of 30 test cases.
     [java] [AutoRun] [INFO] Total Error/Failures: 1
     [java] [AutoRun] [ERROR] testShrcAOTStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)

BUILD FAILED
/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/jvmtest/functional/DDR_Test/tck_ddrext.xml:102: Java returned: 254

Total time: 10 seconds

testDDRExt_SharedClasses_openj9_0_FAILED
```

**Comment by pshipton** [comment]
These are different problems from the original JITPROFILE related problem, they should be separate Issues.

**Comment by hangshao0** [comment]
The failures in https://github.com/eclipse/openj9/issues/8767#issuecomment-597328932 are caused by no AOT being generated:

`AOT data length 0 code length 0 metadata 0 total 0`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/367
testDDRExt_SharedClasses_openj9_0
`JITPROFILE data length 0 metadata 0`
```
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcStatsExt(TestSharedClassesExt.java:41)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.functional_x86-64_linux_Nightly_testList_1/4
testDDRExt_SharedClasses_openj9_0
```
     [java] 1: 0x00007FB4F67F90B8 JITPROFILE data !j9x 0x00007FB4F67F90D4,0x0000000000000068  type 1 updates 0 corrupt -1
     [java] 	getCharFromArrayByIndex(Ljava/lang/Object;I)C !j9rommethod 0x00007FB4E5426D40
     [java] 	com/ibm/jit/JITHelpers !j9romclass 0x00007FB4E5425848
     [java] 
     [java] Cache contains 723 classes, 11 orphans, 3 classpaths, 0 URLs, 0 tokens
     [java] 18 AOT, 36 SCOPES, 28 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
     [java] stale bytes 0
     [java] 1 JITPROFILE, 698 JITHINT
     [java] AOT data length 22600 code length 16800 metadata 504 total 39400
     [java] JITPROFILE data length 104 metadata 32 
     [java] JITHINT data length 2792 metadata 22336 
     [java] ROMClass data 2446680 metadata 32032
     [java] SCOPE data 4524 metadata 432 total 4956
     [java] BYTE data 1392 metadata 1008 rwarea 0
     [java] UNINDEXEDBYTE data 0 metadata 0
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 248
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 0  STARTUPHINTS 96
     [java] 	JITHINT 0  AOTCLASSCHAIN 920 AOTTHUNK 128
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 205204
     [java] 	LocalVariableTable bytes : 339624
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcJITPStatsExt(TestSharedClassesExt.java:375)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/20
testDDRExt_SharedClasses_openj9_0
```
     [java] Cache contains 545 classes, 9 orphans, 3 classpaths, 0 URLs, 0 tokens
     [java] 4 AOT, 75 SCOPES, 51 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
     [java] stale bytes 0
     [java] 0 JITPROFILE, 508 JITHINT
     [java] AOT data length 25232 code length 28480 metadata 112 total 53712
     [java] JITPROFILE data length 0 metadata 0 
     [java] JITHINT data length 2032 metadata 16256 
     [java] ROMClass data 1575032 metadata 24160
     [java] SCOPE data 7489 metadata 900 total 8389
     [java] BYTE data 927599 metadata 1836 rwarea 0
     [java] UNINDEXEDBYTE data 0 metadata 0
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 248
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 925560  STARTUPHINTS 96
     [java] 	JITHINT 0  AOTCLASSCHAIN 1520 AOTTHUNK 175
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 147520
     [java] 	LocalVariableTable bytes : 718
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcStatsExt(TestSharedClassesExt.java:41)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/24
```
     [java] Cache contains 554 classes, 9 orphans, 3 classpaths, 0 URLs, 0 tokens
     [java] 3 AOT, 80 SCOPES, 56 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
     [java] stale bytes 0
     [java] 0 JITPROFILE, 516 JITHINT
     [java] AOT data length 24288 code length 27008 metadata 84 total 51296
     [java] JITPROFILE data length 0 metadata 0 
     [java] JITHINT data length 2064 metadata 16512 
     [java] ROMClass data 1598352 metadata 24556
     [java] SCOPE data 7549 metadata 960 total 8509
     [java] BYTE data 927775 metadata 2016 rwarea 0
     [java] UNINDEXEDBYTE data 0 metadata 0
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 256
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 925560  STARTUPHINTS 96
     [java] 	JITHINT 0  AOTCLASSCHAIN 1688 AOTTHUNK 175
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 150288
     [java] 	LocalVariableTable bytes : 718
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcStatsExt(TestSharedClassesExt.java:41)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/31
```
     [java] Cache contains 554 classes, 9 orphans, 3 classpaths, 0 URLs, 0 tokens
     [java] 2 AOT, 52 SCOPES, 28 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
     [java] stale bytes 0
     [java] 0 JITPROFILE, 515 JITHINT
     [java] AOT data length 12360 code length 13824 metadata 56 total 26184
     [java] JITPROFILE data length 0 metadata 0 
     [java] JITHINT data length 2060 metadata 16480 
     [java] ROMClass data 1598704 metadata 24556
     [java] SCOPE data 7215 metadata 624 total 7839
     [java] BYTE data 926636 metadata 1008 rwarea 0
     [java] UNINDEXEDBYTE data 0 metadata 0
     [java] CHARARRAY data 0 metadata 0
     [java] BYTEDATA Summary
     [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 256
     [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 925560  STARTUPHINTS 96
     [java] 	JITHINT 0  AOTCLASSCHAIN 544 AOTTHUNK 180
     [java] DEBUG Area Summary
     [java] 	LineNumberTable bytes    : 150290
     [java] 	LocalVariableTable bytes : 718
     [java] 
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcStatsExt(TestSharedClassesExt.java:41)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.functional_x86-64_linux_Nightly_testList_0/44
testDDRExt_SharedClasses_openj9_0
```
     [java] 1: 0x00007F6CE67EE428 JITPROFILE data !j9x 0x00007F6CE67EE444,0x0000000000000068  type 1 updates 0 corrupt -1
     [java] 	getCharFromArrayByIndex(Ljava/lang/Object;I)C !j9rommethod 0x00007F6CD5426D40
     [java] 	com/ibm/jit/JITHelpers !j9romclass 0x00007F6CD5425848
     [java] 1: 0x00007F6CE67EE3B8 JITPROFILE data !j9x 0x00007F6CE67EE3D4,0x0000000000000024  type 1 updates 0 corrupt -1
     [java] 	putCharInArrayByIndex(Ljava/lang/Object;IC)V !j9rommethod 0x00007F6CD5426C60
     [java] 	com/ibm/jit/JITHelpers !j9romclass 0x00007F6CD5425848
```
```
     [java] junit.framework.AssertionFailedError
     [java] 	at junit.framework.Assert.fail(Assert.java:48)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:20)
     [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
     [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcJITPStatsExt(TestSharedClassesExt.java:375)
```

**Comment by andrew-m-leonard** [comment]
@pshipton  Looks like a possible re-occurence of this?
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_ppc64_aix/120/consoleFull
```
21:57:08  TCK.run.tests.ddrext:
21:57:08       [echo] Running the DDR Extension Test
21:57:08       [java] openjdk version "1.8.0_292-internal"
21:57:08       [java] OpenJDK Runtime Environment (build 1.8.0_292-internal-202104141809-b09)
21:57:08       [java] Eclipse OpenJ9 VM (build master-19fa4dcef, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20210414_1015 (JIT enabled, AOT enabled)
21:57:08       [java] OpenJ9   - 19fa4dcef
21:57:08       [java] OMR      - 2ccbf5e8c
21:57:08       [java] JCL      - bf7a0585 based on jdk8u292-b09)
21:57:08       [java] 
21:57:11       [java] [SetupConfig] [INFO] Created new DDR Interactive instance using core file : /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16184329252835/testDDRExt_SharedClasses_0/DDREXT.J9CORE.DMP
21:57:11       [java] [AutoRun] [INFO] Running 30 tests for /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16184329252835/testDDRExt_SharedClasses_0/DDREXT.J9CORE.DMP
21:57:11       [java] [AutoRun] [INFO] Starting testShrcExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:11       [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc '
21:57:11       [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!shrc '
21:57:11       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9sharedclassconfig 0x0000010020D9BFB0
21:57:11       [java] 1004294967295-1-1-1-1[DDRExtTesterBase] [INFO] Structure validation passed
21:57:11       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc '
21:57:11       [java] [AutoRun] [INFO] Finished testShrcExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:11       [java] 
21:57:11       [java] [AutoRun] [INFO] Starting testShrcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:11       [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  stats'
21:57:11       [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!shrc  stats'
21:57:11       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9sharedcacheheader 0x0A000100000000F0
21:57:11       [java] 3145725602843228840216036816357521180118000000004220301-1-1000100934536410040963040726976100004425161728289561616314571578-1-124272006553900067108864000[DDRExtTesterBase] [INFO] Structure validation passed
21:57:11       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  stats'
21:57:11       [java] [AutoRun] [INFO] Finished testShrcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:11       [java] 
21:57:11       [java] [AutoRun] [INFO] Starting testShrcAllStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation started for : '!coreinfo '
21:57:58       [java] [DDRExtTesterBase] [INFO] Starting exhaustive DDR structure test for parent command : '!coreinfo '
21:57:58       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9utf8 0x0A00010011400FEC
21:57:58       [java] 11[DDRExtTesterBase] [INFO] Structure validation passed
21:57:58       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9x 0x0A00010011400EE0
21:57:58       [java] [DDRExtTesterBase] [INFO] Can not validate: '!j9x  0x0A00010011400EE0' output is not a structure
21:57:58       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9romclass 0x0A00010000007000
21:57:58       [java] 163203314470348801300017170163214174351360052013182000015527700[DDRExtTesterBase] [WARN] '!j9romclass  0x0A00010000007000' output contains <FAULT> references
21:57:58       [java] [DDRExtTesterBase] [INFO] Structure validation passed
21:57:58       [java] [DDRExtTesterBase] [INFO] Runing structure test with : !j9rommethod 0x0A00010000038DB4
21:57:58       [java] 3211919695104035[DDRExtTesterBase] [INFO] Structure validation passed
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!coreinfo '
21:57:58       [java] [AutoRun] [INFO] Finished testShrcAllStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [AutoRun] [INFO] Starting testShrcRcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  rcstats'
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  rcstats'
21:57:58       [java] [AutoRun] [INFO] Finished testShrcRcStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [AutoRun] [INFO] Starting testShrcCpStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation started for : '!coreinfo '
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!coreinfo '
21:57:58       [java] [AutoRun] [INFO] Finished testShrcCpStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [AutoRun] [INFO] Starting testShrcAOTStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] [DDRExtTesterBase] [ERROR] '!shrc  aotstats' output does not contain success key : Ljava/lang/Object
21:57:58       [java] [DDRExtTesterBase] [ERROR] '!shrc  aotstats' output :!j9sharedclassconfig 0x0000010020D9BFB0
21:57:58       [java] 
21:57:58       [java] Meta data region to be used: 0x0A0001001130ABE0..0x0A00010011400FFC
21:57:58       [java] No entry found in the cache
21:57:58       [java] 
21:57:58       [java] Cache contains 555 classes, 9 orphans, 3 classpaths, 0 URLs, 0 tokens
21:57:58       [java] 0 AOT, 41 SCOPES, 17 BYTE data, 0 UNINDEXED DATA, 0 CHARARRAY, 0 stale
21:57:58       [java] stale bytes 0
21:57:58       [java] 24 JITPROFILE, 531 JITHINT
21:57:58       [java] AOT data length 0 code length 0 metadata 0 total 0
21:57:58       [java] JITPROFILE data length 2096 metadata 768 
21:57:58       [java] JITHINT data length 2124 metadata 16992 
21:57:58       [java] ROMClass data 1607320 metadata 24600
21:57:58       [java] SCOPE data 6658 metadata 492 total 7150
21:57:58       [java] BYTE data 949192 metadata 612 rwarea 0
21:57:58       [java] UNINDEXEDBYTE data 0 metadata 0
21:57:58       [java] CHARARRAY data 0 metadata 0
21:57:58       [java] BYTEDATA Summary
21:57:58       [java] 	UNKNOWN 0  HELPER 0  POOL 0  AOTHEADER 256
21:57:58       [java] 	JCL 0  VM 0  ROMSTRING 0  ZIPCACHE 948448  STARTUPHINTS 96
21:57:58       [java] 	JITHINT 0  AOTCLASSCHAIN 392 AOTTHUNK 0
21:57:58       [java] DEBUG Area Summary
21:57:58       [java] 	LineNumberTable bytes    : 151040
21:57:58       [java] 	LocalVariableTable bytes : 718
21:57:58       [java] 
21:57:58       [java] junit.framework.AssertionFailedError
21:57:58       [java] 	at junit.framework.Assert.fail(Assert.java:48)
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  aotstats'
21:57:58       [java] [AutoRun] [INFO] Finished testShrcAOTStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
21:57:58       [java] [AutoRun] [INFO] Starting testShrcOrphanStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation started for : '!shrc  orphanstats'
21:57:58       [java] [DDRExtTesterBase] [INFO] Validation passed for : '!shrc  orphanstats'	at junit.framework.Assert.assertTrue(Assert.java:20)
21:57:58       [java] 	at junit.framework.Assert.assertTrue(Assert.java:27)
21:57:58       [java] 	at j9vm.test.ddrext.junit.TestSharedClassesExt.testShrcAOTStatsExt(TestSharedClassesExt.java:79)
21:57:58       [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:57:58       [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:57:58       [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:57:58       [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
21:57:58       [java] 	at junit.framework.TestCase.runTest(TestCase.java:168)
21:57:58       [java] 	at junit.framework.TestCase.runBare(TestCase.java:134)
21:57:58       [java] 	at junit.framework.TestResult$1.protect(TestResult.java:110)
21:57:58       [java] 	at junit.framework.TestResult.runProtected(TestResult.java:128)
21:57:58       [java] 	at junit.framework.TestResult.run(TestResult.java:113)
21:57:58       [java] 	at junit.framework.TestCase.run(TestCase.java:124)
21:57:58       [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
21:57:58       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:74)
21:57:58       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:69)
21:57:58       [java] 	at j9vm.test.ddrext.junit.DDRTestSuite.run(DDRTestSuite.java:55)
21:57:58       [java] 	at j9vm.test.ddrext.AutoRun.runTest(AutoRun.java:275)
21:57:58       [java] 	at j9vm.test.ddrext.AutoRun.main(AutoRun.java:110)
21:57:58       [java] 
21:57:58       [java] [AutoRun] [INFO] Finished testShrcOrphanStatsExt(j9vm.test.ddrext.junit.TestSharedClassesExt)
21:57:58       [java] 
```
