### ISSUE TITLE
testJITServer_0 NullPointerException java.nio.DirectIntBufferU.get

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8769]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_Nightly/302
testJITServer_0
```
JITServer is currently a technology preview. Its use is not yet supported
JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServerUnreachableForAWhile.client.jitverboselog.out
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:872)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
	at java.base/java.lang.Thread.uncaughtException(Thread.java:1344)
Caused by: java.lang.NullPointerException
	at java.base/java.nio.DirectIntBufferU.get(DirectIntBufferU.java)
	at java.base/jdk.internal.jimage.BasicImageReader.findLocation(BasicImageReader.java:258)
	at java.base/jdk.internal.jimage.ImageReader.findLocation(ImageReader.java:148)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.findImageLocation(SystemModuleFinders.java:428)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.read(SystemModuleFinders.java:464)
	at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.open(SystemModuleFinders.java:448)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:434)
	at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
	at java.base/java.lang.Module.getResourceAsStream(Module.java:1569)
	at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:185)
	at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
	... 3 more

PASSED: testServer
PASSED: testServerComesUpAfterClient
PASSED: testServerComesUpAfterClientAndGoesDownAgain
PASSED: testServerGoesDown
PASSED: testServerGoesDownAnotherComesUp
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.fail(AssertJUnit.java:66)
	at jit.test.jitserver.JITServerTest.startProcess(JITServerTest.java:134)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:266)
```

**Comment by pshipton** [comment]
@mpirvu

**Comment by harryyu1994** [comment]
@mpirvu 25/25 grinder passed with latest. (Original failure rate is around 3/5). We can close this one.

**Comment by mpirvu** [comment]
Supposedly fixed by https://github.com/eclipse/openj9/pull/8811
