### ISSUE TITLE
Crash in VM_ObjectMonitor::getInitialLockword() at the JITServer

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#8800]
Observed a crash in `VM_ObjectMonitor::getInitialLockword()` at the server while doing sanity test `StringPeepholeTest_0`. Tried the debug build, not able to reproduce it yet. 

`TR_J9VMBase::getInitialLockword()` is introduced in #8047. Likely we need the server side implementation for those new methods. 

https://github.com/eclipse/openj9/blob/14d688fb3f49e75e73a3155aa71cafea906ce076/runtime/compiler/env/VMJ9.h#L679-L682

```
#12 <signal handler called>
#13 0x00007f43b17a7dfa in VM_ObjectMonitor::getInitialLockword(J9JavaVM*, J9Class*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#14 0x00007f43b178f00b in TR_J9VMBase::getInitialLockword(TR_OpaqueClassBlock*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#15 0x00007f43b1795513 in TR_J9VMBase::initializeClazzFlagsMonitorFields(TR::Compilation*, TR::TreeTop*, TR::Node*, TR::Node*, TR_OpaqueClassBlock*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
--Type <RET> for more, q to quit, c to continue without paging-- 
#16 0x00007f43b1794fea in TR_J9VMBase::initializeLocalObjectHeader(TR::Compilation*, TR::Node*, TR::TreeTop*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#17 0x00007f43b1ac273d in TR_EscapeAnalysis::makeLocalObject(Candidate*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#18 0x00007f43b1ac3279 in TR_EscapeAnalysis::makeContiguousLocalAllocation(Candidate*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#19 0x00007f43b1aae6f8 in TR_EscapeAnalysis::performAnalysisOnce() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#20 0x00007f43b1aaa3b6 in TR_EscapeAnalysis::perform() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#21 0x00007f43b1eaa6f9 in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#22 0x00007f43b1ea8d3f in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#23 0x00007f43b1ea8d3f in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#24 0x00007f43b1ea8d3f in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#25 0x00007f43b1ea8d3f in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#26 0x00007f43b1ea8d3f in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#27 0x00007f43b1ea74ae in OMR::Optimizer::optimize() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#28 0x00007f43b1c4a1d1 in OMR::Compilation::performOptimizations() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#29 0x00007f43b1c491f4 in OMR::Compilation::compile() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#30 0x00007f43b172b0a6 in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR::Compilation*, TR_ResolvedMethod*, TR_J9VMBase&, TR_OptimizationPlan*, TR::SegmentAllocator const&) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedref--Type <RET> for more, q to quit, c to continue without paging--
s/libj9jit29.so
#31 0x00007f43b172928a in TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#32 0x00007f43b3be7ff3 in omrsig_protect ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so
#33 0x00007f43b17267c1 in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR_MethodToBeCompiled*, J9::J9SegmentProvider&) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#34 0x00007f43b198165e in TR::CompilationInfoPerThreadRemote::processEntry(TR_MethodToBeCompiled&, J9::J9SegmentProvider&) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#35 0x00007f43b171ce58 in TR::CompilationInfoPerThread::processEntries() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#36 0x00007f43b171c794 in TR::CompilationInfoPerThread::run() ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#37 0x00007f43b171c569 in protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#38 0x00007f43b3be7ff3 in omrsig_protect ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so
#39 0x00007f43b171c33f in compilationThreadProc(void*) ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
#40 0x00007f43b4551212 in thread_wrapper ()
   from /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9thr29.so
#41 0x00007f43b4cfb6ba in start_thread (arg=0x7f43b0471700) at pthread_create.c:333
#42 0x00007f43b525541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by a7ehuo** [comment]
Close. This issue is fixed by #8811.
