### ISSUE TITLE
Cannot build on aix71-p8-5, Symbol resolution failed for libmawt.so

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8840]
ci.role.build label removed.

https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_Nightly/331/
```
23:33:52  Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/java7/jre/lib/ppc64/xawt/libmawt.so: /opt/java7/jre/lib/ppc64/xawt/libmawt.so, LIBPATH=/opt/java7/jre/lib/ppc64/server:/opt/java7/jre/lib/ppc64:/opt/java7/jre/lib/ppc64/jli:/opt/java7/jre/../lib/ppc64:/opt/java8_64/jre/lib/ppc64/j9vm:/opt/java8_64/jre/lib/ppc64:/opt/java8_64/jre/../lib/ppc64:/opt/java8_64/jre/lib/icc:/opt/freeware/lib:/usr/lib/:.:/usr/lib, LD_LIBRARY_PATH=/opt/freeware/lib:/usr/lib/:. : 	0509-130 Symbol resolution failed for /opt/java7/jre/lib/ppc64/xawt/libmawt.so because:
23:33:52  	0509-136   Symbol XRenderCreateRadialGradient (number 329) is not exported from
23:33:52  		   dependent module /opt/freeware/lib/libXrender.a[libXrender.so.0].
23:33:52  	0509-136   Symbol XRenderCreateLinearGradient (number 330) is not exported from
23:33:52  		   dependent module /opt/freeware/lib/libXrender.a[libXrender.so.0].
23:33:52  	0509-022 Cannot load module /opt/java7/jre/lib/ppc64/xawt/libmawt.so.
23:33:52  	0509-026 System error: Cannot run a file that does not have a valid format.
23:33:52  	0509-192 Examine .loader section symbols with the
23:33:52  		 'dump -Tv' comma
23:33:52  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
23:33:52  	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
23:33:52  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
23:33:52  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
23:33:52  	at java.lang.Runtime.load0(Runtime.java:795)
23:33:52  	at java.lang.System.load(System.java:1062)
23:33:52  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
23:33:52  	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
23:33:52  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
23:33:52  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
23:33:52  	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
23:33:52  	at java.lang.System.loadLibrary(System.java:1088)
23:33:52  	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
23:33:52  	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
23:33:52  	at java.security.AccessController.doPrivileged(Native Method)
23:33:52  	at sun.java2d.Disposer.<clinit>(Disposer.java:63)
23:33:52  	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.readBlob(ClassGenerator.java:57)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:143)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:53)
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
JDK8 manual compile is the basic test performed when this machine was initially setup a few weeks ago???

Anyways, (1)`yum reinstall libXrender`.  didn't resolve the issue with a retested jdk8 compile.  (2) replaced the jdk7 sdk didn't work either.

**Comment by pshipton** [comment]
@jdekonin if you can't fix it, please open a PR to remove the build label so that jenkins restarts don't re-enable it.

**Comment by pshipton** [comment]
For the record, the build label was removed from the aix71-p8-5 machine in code. Seems we should keep this open since the machine is broken and should ideally be fixed or recreated.

**Comment by jdekonin** [comment]
Th existing machines OpenJ9 are supplied through the IBM PDP team.  These are going to be replaced in the next few weeks as the donation period is coming to an end.  I have been in contact with the team that is to supply the "replacements".  I opened #8979 to track that work so folks other than @rajdeepsingh1 and I know about it.

I think this can be closed as the machine will be replaced soon and it won't be doing compiles ever again.
