### ISSUE TITLE
com.ibm.j9ddr.tools.ClassGenerator should not depend on FileImageInputStream

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8841]
See https://github.com/eclipse/openj9/issues/8840
```
23:33:52  	at sun.java2d.Disposer.<clinit>(Disposer.java:63)
23:33:52  	at javax.imageio.stream.FileImageInputStream.<init>(FileImageInputStream.java:98)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.readBlob(ClassGenerator.java:57)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:143)
23:33:52  	at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:53)
```

**Comment by keithc-ca** [comment]
This may require large-scale backward-incompatible changes to DTFJ.
