### ISSUE TITLE
openjdkNext_j9_extended.functional_ppc64le_linux testSCCacheManagement_0_FAILED testSharedCacheJvmtiAPI

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8883]
Failure link
------------

From an internal build `Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly/142`:
```
23:03:04  openjdk version "15-internal" 2020-09-15
23:03:04  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDKnextppc64lelinuxNightly)
23:03:04  Eclipse OpenJ9 VM (build ibm_sdk-1403211629, JRE 15 Linux ppc64le-64-Bit Compressed References 20200315_161 (JIT enabled, AOT enabled)
23:03:04  OpenJ9   - 1403211629
23:03:04  OMR      - aa8f7559b
23:03:04  JCL      - 563f19ad32b based on jdk-15+13)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
There was 1 error:
1) testSharedCacheJvmtiAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: iterateSharedCacheFunction ffailed, Invalid number of cache found	expected: 5	found: 6
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
	at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:111)
	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 168,  Failures: 0,  Errors: 1

testSCCacheManagement_0_FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=ppc64le_linux&TARGET=testSCCacheManagement_0

**Comment by hangshao0** [comment]
It passed in the next build: `Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly/143/`

**Comment by hangshao0** [comment]
There might be another Java process running on that machine which created a SCC at the time of failure.

**Comment by JasonFengJ9** [comment]
[openjdk25_j9_extended.functional_x86-64_linux](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_extended.functional_x86-64_linux_testList_1/16/)
```
[2025-09-12T01:39:29.380Z] Running test testSCCacheManagement_0 ...
[2025-09-12T01:39:29.380Z] ===============================================
[2025-09-12T01:39:29.380Z] testSCCacheManagement_0 Start Time: Thu Sep 11 18:39:28 2025 Epoch Time (ms): 1757641168170
[2025-09-12T01:39:29.380Z] variation: NoOptions
[2025-09-12T01:39:29.380Z] JVM_OPTIONS:  

[2025-09-12T02:02:42.501Z] There were 2 errors:
[2025-09-12T02:02:42.501Z] 1) testSharedCacheJvmtiAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: iterateSharedCacheFunction ffailed, Invalid number of cache found	expected: 5	found: 6
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.options.TestSharedCacheJvmtiAPI.main(TestSharedCacheJvmtiAPI.java:111)
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJvmtiAPI(TestOptionsBase.java:119)
[2025-09-12T02:02:42.501Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2025-09-12T02:02:42.501Z] 2) testSharedCacheJavaAPI(tests.sharedclasses.options.junit.TestOptionsDefault)tests.sharedclasses.TestFailedException: SharedClassUtilities.getSharedCacheInfo failed: Invalid number of cache found	expected: 7	found: 8
[2025-09-12T02:02:42.501Z]  oldCacheCount is 0
[2025-09-12T02:02:42.501Z]  persistentGroupAccessCount is 1
[2025-09-12T02:02:42.501Z]  nonpersistentGroupAccessCount is 1
[2025-09-12T02:02:42.501Z]  persistentCount is 3
[2025-09-12T02:02:42.501Z]  nonpersistentCount is 1
[2025-09-12T02:02:42.501Z]  snapshotCount is 1
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.options.TestSharedCacheJavaAPI.main(TestSharedCacheJavaAPI.java:208)
[2025-09-12T02:02:42.501Z] 	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheJavaAPI(TestOptionsBase.java:120)
[2025-09-12T02:02:42.501Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

```
