### ISSUE TITLE
java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.java.ParentLoggerWithHandlerGC fails if ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V is compiled with optLevel=cold

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse/openj9#8897]
## Java -version output

aarch64:
```
00:35:09  openjdk version "11.0.7" 2020-04-14
00:35:09  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+7-202003161455)
00:35:09  Eclipse OpenJ9 VM AdoptOpenJDK (build master-b7b7aaccd, JRE 11 Linux aarch64-64-Bit Compressed References 20200316_238 (JIT enabled, AOT enabled)
00:35:09  OpenJ9   - b7b7aaccd
00:35:09  OMR      - 5384dadb6
00:35:09  JCL      - 2c50aba301 based on jdk-11.0.7+7)
```

x86:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+7-202003142355)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-7bc7c3e40, JRE 11 Linux amd64-64-Bit Compressed References 20200314_517 (JIT enabled, AOT enabled)
OpenJ9   - 7bc7c3e40
OMR      - 5384dadb6
JCL      - 2c50aba301 based on jdk-11.0.7+7)
```

## Summary of Problem

`java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.java.ParentLoggerWithHandlerGC` intermittently fails (timeout) for aarch64 when `ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V` is compiled. It is also reproducible on x86 Linux if `optLevel=cold` is set.

Failure link for aarch64:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/88/testReport/junit/java_util_logging_LogManager_Configuration_ParentLoggerWithHandlerGC/java/ParentLoggerWithHandlerGC/

Test output for the failure:
```
03:31:08  ACTION: main -- Error. Program `/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 962237ms).
03:31:08  REASON: User specified action: run main/othervm ParentLoggerWithHandlerGC SECURE 
03:31:08  TIME:   962.249 seconds
03:31:08  messages:
03:31:08  command: main ParentLoggerWithHandlerGC SECURE
03:31:08  reason: User specified action: run main/othervm ParentLoggerWithHandlerGC SECURE 
03:31:08  Mode: othervm [/othervm specified]
03:31:08  Additional options from @modules: --add-modules java.logging
03:31:08  Timeout information:
03:31:08  Running jstack on process 87975
03:31:08  2020-03-16T18:31:04.530262355
03:31:08  Virtual machine: 87975 JVM information:
03:31:08  JRE 11 Linux aarch64-64-Bit Compressed References 20200316_238 (JIT enabled, AOT enabled)
03:31:08  OpenJ9   - b7b7aaccd
03:31:08  OMR      - 5384dadb6
03:31:08  JCL      - 2c50aba301 based on jdk-11.0.7+7
03:31:08  
03:31:08  "main" prio=5 Id=1 WAITING
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Native Method)
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Object.java:221)
03:31:08  	at java.base@11.0.7/java.lang.Thread.join(Thread.java:714)
03:31:08  	- locked java.lang.Thread@cfc76422
03:31:08  	at app//com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)
03:31:08  
03:31:08  "JIT Compilation Thread-000" prio=10 Id=3 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-001 Suspended" prio=10 Id=4 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-002 Suspended" prio=10 Id=5 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-003 Suspended" prio=10 Id=6 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-004 Suspended" prio=10 Id=7 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-005 Suspended" prio=10 Id=8 RUNNABLE
03:31:08  
03:31:08  "JIT Compilation Thread-006 Suspended" prio=10 Id=9 RUNNABLE
03:31:08  
03:31:08  "JIT Diagnostic Compilation Thread-007 Suspended" prio=10 Id=10 RUNNABLE
03:31:08  
03:31:08  "JIT-SamplerThread" prio=10 Id=11 TIMED_WAITING
03:31:08  
03:31:08  "IProfiler" prio=5 Id=12 RUNNABLE
03:31:08  
03:31:08  "Common-Cleaner" prio=8 Id=2 TIMED_WAITING
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Native Method)
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Object.java:221)
03:31:08  	at java.base@11.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
03:31:08  	- locked java.lang.ref.ReferenceQueue@e7b55dad
03:31:08  	at java.base@11.0.7/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
03:31:08  	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
03:31:08  	at java.base@11.0.7/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
03:31:08  
03:31:08  "Concurrent Mark Helper" prio=1 Id=13 RUNNABLE
03:31:08  
03:31:08  "Finalizer thread" prio=5 Id=14 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=15 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=16 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=17 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=18 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=19 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=20 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=21 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=22 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=23 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=24 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=25 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=26 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=27 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=28 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=29 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=30 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=31 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=32 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=33 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=34 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=35 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=36 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=37 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=38 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=39 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=40 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=41 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=42 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=43 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=44 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=45 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=46 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=47 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=48 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=49 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=50 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=51 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=52 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=53 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=54 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=55 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=56 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=57 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=58 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=59 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=60 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=61 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=62 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=63 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=64 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=65 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=66 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=67 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=68 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=69 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=70 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=71 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=72 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=73 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=74 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=75 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=76 RUNNABLE
03:31:08  
03:31:08  "GC Slave" prio=5 Id=77 RUNNABLE
03:31:08  
03:31:08  "Attach API wait loop" prio=10 Id=80 RUNNABLE
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.IPC.waitSemaphore(Native Method)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:259)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
03:31:08  
03:31:08  "MainThread" prio=5 Id=82 TIMED_WAITING
03:31:08  	at java.base@11.0.7/java.lang.Thread.sleep(Native Method)
03:31:08  	at java.base@11.0.7/java.lang.Thread.sleep(Thread.java:964)
03:31:08  	at app//ParentLoggerWithHandlerGC.testCloseOnResetTrue(ParentLoggerWithHandlerGC.java:291)
03:31:08  	at app//ParentLoggerWithHandlerGC.test(ParentLoggerWithHandlerGC.java:257)
03:31:08  	at app//ParentLoggerWithHandlerGC$TestCase.run(ParentLoggerWithHandlerGC.java:78)
03:31:08  	at app//ParentLoggerWithHandlerGC.main(ParentLoggerWithHandlerGC.java:142)
03:31:08  	at java.base@11.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:31:08  	at java.base@11.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:31:08  	at java.base@11.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:31:08  	at java.base@11.0.7/java.lang.reflect.Method.invoke(Method.java:566)
03:31:08  	at app//com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:31:08  	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
03:31:08  
03:31:08  "file lock watchdog" prio=10 Id=84 TIMED_WAITING
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Native Method)
03:31:08  	at java.base@11.0.7/java.lang.Object.wait(Object.java:221)
03:31:08  	at java.base@11.0.7/java.util.TimerThread.mainLoop(Timer.java:553)
03:31:08  	- locked java.util.TaskQueue@9134eefe
03:31:08  	at java.base@11.0.7/java.util.TimerThread.run(Timer.java:506)
03:31:08  
03:31:08  "Attachment 43225" prio=10 Id=85 RUNNABLE
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.DiagnosticUtils.dumpAllThreadsImpl(Native Method)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.DiagnosticUtils.getThreadInfo(DiagnosticUtils.java:233)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.DiagnosticUtils$$Lambda$17/0000000000000000.apply(Unknown Source)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.DiagnosticUtils.executeDiagnosticCommand(DiagnosticUtils.java:169)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:249)
03:31:08  	at java.base@11.0.7/openj9.internal.tools.attach.target.Attachment.run(Attachment.java:160)
03:31:08  
03:31:08  
03:31:08  --- Timeout information end.
03:31:08  elapsed time (seconds): 962.249
03:31:08  configuration:
03:31:08  Boot Layer
03:31:08    add modules: java.logging
03:31:08  
03:31:08  STDOUT:
03:31:08  Running test case: SECURE
03:31:08  
03:31:08  Testing: SECURE parent logger with handler mode=DEFAULT
03:31:08  Got barRef
03:31:08  Parent logger GCed
03:31:08  Got fooRef after reset()
03:31:08  Running test case: SECURE
03:31:08  
03:31:08  Testing: SECURE parent logger with handler mode=ENSURE_CLOSE_ON_RESET_TRUE
03:31:08  Timeout refired 960 times
03:31:08  STDERR:
03:31:08  rerun:
03:31:08  cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/scratch/1 && \
03:31:08  HOME=/home/jenkins \
03:31:08  LANG=en_US.UTF-8 \
03:31:08  PATH=/bin:/usr/bin:/usr/sbin \
03:31:08  CLASSPATH=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/classes/7/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LogManager/Configuration:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar \
03:31:08      /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java \
03:31:08          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/classes/7/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.d:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LogManager/Configuration \
03:31:08          -Dtest.file=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.java \
03:31:08          -Dtest.src=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LogManager/Configuration \
03:31:08          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/logging/LogManager/Configuration \
03:31:08          -Dtest.classes=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/classes/7/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.d \
03:31:08          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/classes/7/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.d \
03:31:08          -Dtest.vm.opts='-ea -esa -Xmx512m -Xcompressedrefs' \
03:31:08          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xcompressedrefs' \
03:31:08          -Dtest.compiler.opts= \
03:31:08          -Dtest.java.opts= \
03:31:08          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
03:31:08          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image \
03:31:08          -Dtest.timeout.factor=8.0 \
03:31:08          -Dtest.root=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
03:31:08          -Dtest.modules=java.logging \
03:31:08          --add-modules java.logging \
03:31:08          -ea \
03:31:08          -esa \
03:31:08          -Xmx512m \
03:31:08          -Xcompressedrefs \
03:31:08          com.sun.javatest.regtest.agent.MainWrapper /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdk-tests/TKG/test_output_15843729068704/jdk_util_0/work/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.d/main.1.jta SECURE
03:31:08  
03:31:08  TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 962237ms).
```

## Diagnostic files

[ParentLoggerWithHandlerGC_trace.zip](https://github.com/eclipse/openj9/files/4347591/ParentLoggerWithHandlerGC_trace.zip)

Attached zip file contains javacore and compilation trace log of `ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V` taken on x86 Linux.

The javacore says that the "MainThread" is executing this loop:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/178ac70bb74a722bf571dbd3954ca23b61097aee/test/jdk/java/util/logging/LogManager/Configuration/ParentLoggerWithHandlerGC.java#L289-L292
It is waiting for `queue.poll()` to return non-null weak reference. There's 2 reference object registered to that `ReferenceQueue`.

I suspect that at least one of those reference objects is not cleared because it is stored at `<temp slot 13>[#599  Auto +80] ` and `<temp slot 14>[#600  Auto +72] `.
```
 67019	 \\ ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V
 67020	 \\  105 JBinvokevirtual 62 java/util/logging/Logger.getParent()Ljava/util/logging/Logger;
 67021	 \\       1 JBgetfield 66 java/util/logging/Logger.parent Ljava/util/logging/Logger;
 67022	
 67023	0x7f9d0041e236 00000202 [0x7f9cfb421580] 8b 40 24                           mov	eax, dword ptr [rax+0x24]		# L4RegMem, SymRef  java/util/logging/Logger.parent Ljava/util/logging/Logger;[#598  volatile Shadow +36] [flags 0x82607 0x0 ]
 67024	0x7f9d0041e239 00000205 [0x7f9cfb4219a0] 48 89 44 24 50                     mov	qword ptr [rsp+0x50], rax		# S8MemReg, SymRef  <temp slot 13>[#599  Auto +80] [flags 0x20000007 0x0 ]
 67025	0x7f9d0041e23e 0000020a [0x7f9cfb421c20]                                    Fence Relative [ 00007F9CFB130924 ]	# FENCE BBEnd </block_56>
 67026	0x7f9d0041e23e 0000020a [0x7f9cfb421e60]                                    assocRegs                       # ASSOCREGS
 67027	0x7f9d0041e23e 0000020a [0x7f9cfb421f40]                                    Label L0256:			# LABEL
 67028	0x7f9d0041e23e 0000020a [0x7f9cfb422120]                                    Label L0052:			# LABEL
 67029	========================================
 67030	0x7f9d0041e23e 0000020a [0x7f9cfb4221c0]                                    Fence Relative [ 00007F9CFB130A90 ]	# FENCE BBStart <block_57> (frequency 2004)
 67031	
 67032	 \\ ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V
 67033	 \\  101 JBinvokevirtual 61 java/lang/ref/WeakReference.get()Ljava/lang/Object;
 67034	
 67035	0x7f9d0041e23e 0000020a [0x7f9cfb4225a0] 48 8b 44 24 48                     mov	rax, qword ptr [rsp+0x48]		# L8RegMem, SymRef  <temp slot 14>[#600  Auto +72] [flags 0x7 0x0 ]
```

The call to `System.gc()` in the loop is at offset 0x282.
```
 67110	 \\ ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V
 67111	 \\  151 JBinvokestatic 64 java/lang/System.gc()V
 67112	 \\       0 JBgetstatic 121 java/lang/System.RUNTIME Ljava/lang/Runtime;
 67113	
 67114	0x7f9d0041e2a2 0000026e [0x7f9cfb429310] 48 8b 14 25 18 c7 96 01            mov	rdx, qword ptr [$0x000000000196c718]		# L8RegMem, SymRef  java/lang/System.RUNTIME Ljava/lang/Runtime;[#610  final Static] [flags 0xa0307 0x0 ]
 67115	0x7f9d0041e2aa 00000276 [0x7f9cfb429420] 48 8b c2                           mov	rax, rdx		# MOV8RegReg
 67116	
 67117	 \\ ParentLoggerWithHandlerGC.testCloseOnResetTrue(Ljava/lang/String;Ljava/util/Properties;)V
 67118	 \\  151 JBinvokestatic 64 java/lang/System.gc()V
 67119	 \\       3 JBinvokevirtual 123 java/lang/Runtime.gc()V
 67120	
 67121	0x7f9d0041e2ad 00000279 [0x7f9cfb429640] 8b 0a                              mov	ecx, dword ptr [rdx]		# L4RegMem, SymRef  <vft-symbol>[#294  Shadow] [flags 0x18607 0x0 ]
 67122	0x7f9d0041e2af 0000027b [0x7f9cfb4296d0] 48 81 e1 00 ff ff ff               and	rcx, 0xffffffffffffff00	# AND8RegImm4
 67123	0x7f9d0041e2b6 00000282 [0x7f9cfb429fa0]                                    Label L0320:			# LABEL	# (Start of internal control flow)
 67124	0x7f9d0041e2b6 00000282 [0x7f9cfb429910] ff 91 50 ff ff ff                  call	dword ptr [rcx-0xb0]		# CALLMem, SymRef [#612 -176]
```

The GC map at offset 0x282 is as follows.  The stackmap contains `72` and `80`, so I guess that the reference object stored at `<temp slot 13>[#599  Auto +80] ` and `<temp slot 14>[#600  Auto +72] ` is not cleared by gc.
```
 65277	    map range: starting at [00007F9D0041E2B6]
 65278	      lowOffset: 00000282
 65279	      byteCodeInfo: <_callerIndex=2, byteCodeIndex=3>, _isSameReceiver=0, _doNotProfile=0
 65280	      registerSaveDescription: starting at [F909C3E6] { 00000000 }
 65281	      registers: 00000000	{ }
 65282	      stack map: 11111111111111	{ 56 64 72 80 88 96 104 112 120 128 136 144 152 160 }
```

**Comment by Akira1Saitoh** [comment]
@knn-k @0xdaryl

**Comment by knn-k** [comment]
It is possible #9044 is also related to this.  The ArrayBlockingQueue/WhiteBox test pass when you run it with `-Xjit:optlevel=warm`.

**Comment by 0xdaryl** [comment]
I can reproduce this on x86, but only at cold and only on an 80-core native machine.  It hangs maybe 1/25 runs.  The problem only seems to require trivial inlining to reproduce.  Investigation continues...

**Comment by 0xdaryl** [comment]
This test has been carefully engineered to expect certain behaviour from the garbage collector at certain points in the test.  It deals with `ReferenceQueue`s and `WeakReference`s and manipulates the apparent liveness of objects in order to have the `WeakReference`s enqueued at predictable points for testability.

When one of the test methods is compiled at optlevel cold, we perform a trivial inlining of some getter methods.  The inliner introduces temporaries that store some of the referents of the WeakReferences.  At optlevel cold, these temporaries are considered live throughout the method and hence are live from the garbage collector's perspective.  This defeats the assumptions in the test where it is expecting objects to die at points of its choosing.

GlobalLiveVariablesForGC is the optimization that tightens the live ranges of autos (including inliner temps), but it doesn't run at cold for compile-time performance reasons (it runs at optlevel warm and above).  It can be enabled with `-Xjit:enableAggressiveLiveness` and doing so has the expected effect of limiting the live range of inliner temps to only the blocks where they are live and the test succeeds.  I have not seen the test fail with hundreds of runs with `-Xjit:enableAggressiveLiveness` enabled.

I do not believe that relying on the behaviour and operation of the garbage collector at predictable moments is Java spec'ed behaviour, and indeed the OpenJ9 JIT takes advantage of the fact that this behaviour is un-spec'ed to give it more freedom in optimizing code.

I recommend this test be excluded for AArch64 because at the moment its optimization level defaults to cold (because recompilation is not enabled yet).  This problem has not been seen at higher optimization levels because GlobalLiveVariablesForGC runs and the liveness of temporaries is more precise.  Once recompilation is enabled I expect this test will pass successfully on AArch64.

The larger question of whether this is in fact a valid test that can be relied upon in the presence of an optimizing JIT is perhaps a bigger question to be answered.  From what I've seen, at higher optlevels the optimizations performed conform to behaviour that the test is expecting so there is value in continuing to run it.

**Comment by vijaysun-omr** [comment]
fyi @klangman since this is testing an area that we have had some customer issue in in the past as well  and you may have been the one that added the -Xjit option that @0xdaryl mentioned.

**Comment by knn-k** [comment]
#9043 and #9044 are known to have the same issue.
When we exclude the ParentLoggerWithHandlerGC test, WeakHashMap/GCDuringIteration and ArrayBlockingQueue/WhiteBox tests also need to be excluded.

**Comment by smlambert** [comment]
Re-included tests via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1780

**Comment by knn-k** [comment]
This test is no longer failing in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/140/ .

**Comment by knn-k** [comment]
https://github.com/eclipse/omr/pull/5159 enabled use of optlevel=warm or higher with AArch64 JIT.
