### ISSUE TITLE
jdk15 ASSERTION FAILED ** at VMAccess.cpp:427: ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8921]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK/146
cmdLineTester_jvmtitests_8
```
Testing: evmoa001
Test start time: 2020/03/19 13:20:37 Eastern Standard Time
Running command: "/Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump    -agentlib:jvmtitest=test:evmoa001 -cp "/Users/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_mac_OpenJDK/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 6 milliseconds
Time spent executing: 12558 milliseconds
Test result: FAILED
Output from test:
 [ERR] 17:20:37.658 0x10760c00    j9vm.227    *   ** ASSERTION FAILED ** at VMAccess.cpp:427: ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS)
```

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by pshipton** [comment]
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.load(Native Method)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:289)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.loadLibrary(NativeLibraries.java:176)
5XESTACKTRACE                   (entered lock: java/util/HashSet@0x0000000700027E18, entry count: 1)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.loadLibrary(NativeLibraries.java:118)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.findFromPaths(NativeLibraries.java:224)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.loadLibrary(NativeLibraries.java:214)
4XESTACKTRACE                at jdk/internal/loader/NativeLibraries.loadLibrary(NativeLibraries.java:199)
4XESTACKTRACE                at jdk/internal/loader/BootLoader.loadLibrary(BootLoader.java:147)
4XESTACKTRACE                at java/util/zip/ZipUtils.loadLibrary(ZipUtils.java:279)
4XESTACKTRACE                at java/util/zip/Inflater.<clinit>(Inflater.java:115)
```

**Comment by pshipton** [comment]
If it's useful, note there is a debug-image artifact on the JVM that contains the native debug symbols.
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_mac_OpenJDK/180/
