### ISSUE TITLE
xlinux santy.openjdk Cannot run program "null/Xvfb"

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8942]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7
cent6-x64-1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/8
ub16x64j97
```
23:27:54  Running tests...
[Pipeline] echo
23:27:54  ITERATION: 1/1
[Pipeline] wrap
23:27:21  $ null/Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-7-..fbdir5641863979065607233
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
23:27:55  TAP Reports Processing: START
23:27:55  Looking for TAP results report in workspace using pattern: **/*.tap
23:28:06  Did not find any matching files. Setting build result to FAILURE.
[Pipeline] junit
23:28:06  Recording test results
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
23:27:47  [consumer_1] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7/SHA.txt
[Pipeline] publishBuildInfo
23:28:21  Deploying build info to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
23:28:21  Deploying build descriptor to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
23:28:22  Build successfully deployed. Browse it in Artifactory under https://140-211-168-230-openstack.osuosl.org/artifactory/webapp/builds/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7
23:28:22  Sending request for build retention, deleting build artifacts, max number of builds to store: 20.
[Pipeline] echo
23:28:22  Test output artifactory URL:'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7/'
[Pipeline] sh
23:28:24  + tar -cf - ./openjdk-tests/TKG/test_output_15847609944938
23:28:24  + pigz -9
23:28:24  + gzip -9
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
23:27:51  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7/openjdk_test_output.tar.gz
[Pipeline] publishBuildInfo
23:28:28  Deploying build info to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
23:28:29  Deploying build descriptor to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
23:28:29  Build successfully deployed. Browse it in Artifactory under https://140-211-168-230-openstack.osuosl.org/artifactory/webapp/builds/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7
23:28:29  Sending request for build retention, deleting build artifacts, max number of builds to store: 20.
[Pipeline] echo
23:28:29  Test output artifactory URL:'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/7/'
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[WS-CLEANUP] done
[Pipeline] sh
+ find /tmp -name '*core*' -print -exec rm -f '{}' ';'
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to cent6-x64-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1060)
		at hudson.Launcher$ProcStarter.start(Launcher.java:455)
		at org.jenkinsci.plugins.xvfb.Xvfb.launchXvfb(Xvfb.java:587)
		at org.jenkinsci.plugins.xvfb.Xvfb.setUp(Xvfb.java:697)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$$Lambda$354.00000000CC0192A0.run(Unknown Source)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$$Lambda$287.00000000C40FEE00.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
Caused: java.io.IOException: Cannot run program "null/Xvfb": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:250)
	at hudson.Proc$LocalProc.<init>(Proc.java:219)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:937)
	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1319)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1272)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pshipton** [comment]
@llxia @smlambert any ideas what is causing this? It was working up to last night.

**Comment by pshipton** [comment]
We did have the jenkins restart, probably lost some setting?

**Comment by pshipton** [comment]
@jdekonin as well

**Comment by smlambert** [comment]
Looks like the plugin can not find and therefore can not launch the xvfb process on that particular machine (at null/Xvfb)

**Comment by pshipton** [comment]
I don't think it's a machine problem. It used to work on a machine that's failing now.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/4 - ub16x64j97

The last working builds were Thursday night, jdk8 link:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/6 - ub16x64j910

Latest failures:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/8
cent6-x64-4
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/9
ub16x64j97

**Comment by pshipton** [comment]
The tests continue to fail nightly, I'm not going to keep reporting them here every day.

**Comment by smlambert** [comment]
We can not see whether the something was lost in the Jenkins config on the restart, but imagine we can raise an issue to ask if anything was lost.  I have not seen that happen at the other Jenkins server (where the xvfb plugin in configuration gets wiped out on a restart, but its a possibility).

**Comment by smlambert** [comment]
added note to https://github.com/eclipse-cbi/jiro/issues/92#issuecomment-603246883

**Comment by pshipton** [comment]
I can't explain the timing, but the problem was in the jenkins config and is fixed as per https://github.com/eclipse-cbi/jiro/issues/92#issuecomment-603340529
