### ISSUE TITLE
net.openj9.test.PDMoveShifts.TestShiftsAndConvert: IllegalArgumentException: Invalid Precisions or shift amount

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8947]
Failure link
------------

From an internal build `Test_openjdk8_j9_special.system_x86-64_linux_Nightly/1298`:
```
00:08:33  openjdk version "1.8.0_252-internal"
00:08:33  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_03_21_21_42-b00)
00:08:33  Eclipse OpenJ9 VM (build ibm_sdk-14ba310fcc, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200321_357 (JIT enabled, AOT enabled)
00:08:33  OpenJ9   - 14ba310fcc
00:08:33  OMR      - 6e04bdd8e
00:08:33  JCL      - 61ecedabf89 based on jdk8u252-b06)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
DLT testFailure: testShiftRightNoRounding(net.openj9.test.PDMoveShifts.TestShiftsAndConvert): Invalid Precisions or shift amount
DLT java.lang.IllegalArgumentException: Invalid Precisions or shift amount
DLT 	at com.ibm.dataaccess.PackedDecimal.shiftRightPackedDecimal_(PackedDecimal.java:1560)
DLT 	at com.ibm.dataaccess.PackedDecimal.shiftRightPackedDecimal(PackedDecimal.java:1530)
DLT 	at net.openj9.test.PDMoveShifts.TestShiftsAndConvert.testShiftRight(TestShiftsAndConvert.java:3300)
DLT 	at net.openj9.test.PDMoveShifts.TestShiftsAndConvert.testShiftRightNoRounding(TestShiftsAndConvert.java:3411)
DLT 	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
DLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DLT 	at java.lang.reflect.Method.invoke(Method.java:498)
DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
DLT 	at java.lang.Thread.run(Thread.java:821)

DLT JUnit Test Results for: net.openj9.test.PDMoveShifts.TestShiftsAndConvert
DLT   Ran    : 64
DLT   Passed : 63
DLT   Failed : 1
DLT   Ignored: 0
DLT   Result : FAILED
DLT <<<

DaaLoadTest_daa1_special_20_FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/daaLoadTest&PLATFORM=x86-64_linux&TARGET=DaaLoadTest_daa1_special_20

**Comment by pshipton** [comment]
@JasonFengJ9 Looks like a dup of https://github.com/eclipse/openj9/issues/6552
