### ISSUE TITLE
testSoftMxLocal_3_FAILED : OutOfMemoryError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8948]
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/27`:
```
22:05:03  openjdk version "1.8.0_252-internal"
22:05:03  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_03_21_21_43-b00)
22:05:03  Eclipse OpenJ9 VM (build ibm_sdk-14ba310fcc, JRE 1.8.0 Mac OS X amd64-64-Bit 20200321_27 (JIT enabled, AOT enabled)
22:05:03  OpenJ9   - 14ba310fcc
22:05:03  OMR      - 6e04bdd8e
22:05:03  JCL      - 61ecedabf89 based on jdk8u252-b06)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test testSoftMxLocal_3 ...
===============================================
testSoftMxLocal_3 Start Time: Sat Mar 21 23:18:54 2020 Epoch Time (ms): 1584847134282
variation: Mode501
JVM_OPTIONS: -Xnocompressedrefs -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/03/21 23:18:57 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15848429297725/testSoftMxLocal_3/core.20200321.231857.19167.0001.dmp' in response to an event
JVMDUMP010I System dump written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15848429297725/testSoftMxLocal_3/core.20200321.231857.19167.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15848429297725/testSoftMxLocal_3/heapdump.20200321.231857.19167.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15848429297725/testSoftMxLocal_3/heapdump.20200321.231857.19167.0002.phd
JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15848429297725/testSoftMxLocal_3/javacore.20200321.231857.19167.0003.txt' in response to an event
/bin/sh: line 1: 19167 Abort trap: 6           (core dumped) "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xnocompressedrefs -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xmx1024m -Xsoftmx512m -Xmn1m -verbose:gc -Xverbosegclog:"/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15848429297725/testSoftMxLocal_3"/vgc.log -cp "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/lib/testng.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar" org.testng.TestNG -d "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15848429297725/testSoftMxLocal_3" "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/testng.xml" -testnames testSoftMxLocal -groups level.extended -excludegroups d.*.osx_x86-64,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all

testSoftMxLocal_3_FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_mac_xl&TARGET=testSoftMxLocal_3

**Comment by dmitripivkine** [comment]
This OOM has been created intentionally: 
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at j9vm/test/softmx/MemoryExhauster.usePercentageOfHeap(MemoryExhauster.java:64)
4XESTACKTRACE                at j9vm/test/softmx/SoftmxLocalTest.testSoftmxHasEffects(SoftmxLocalTest.java:244)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
```
https://github.com/eclipse/openj9/blob/398fa673037e0a655fb2b3b6735d914cac76e5fb/test/functional/JLM_Tests/src/j9vm/test/softmx/SoftmxLocalTest.java#L244
```
		try {
			OOMNotReached = memoryExhauster.usePercentageOfHeap(1.2);
		} catch ( OutOfMemoryError e ) {
			logger.debug("SoftmxLocalTest : OOM Reached");
			e.printStackTrace();
			OOMNotReached = false;
		}
```
However this OOM should be caught but it was not.

I have result files downloaded, ask me if you need them.

**Comment by dmitripivkine** [comment]
There are two things I noticed not related to failure but `x86-64_mac_xl` spec:
- Start address of object heap is `0xdc80000` obviously below 4GB. This means for Large Heap we overwrite linker default for OSX to use low 4GB for system purpose the same way it done for Compressed Refs. It is not wrong but I was under impression that we don't want (and don't need obviously) to do it for Large Heap version of JVM for Mac.
- Size of system core is 2434404352 bytes. With 1GB object heap provisioned it is ok (probably) but looks a little bit large. This is native memory section from javacore. I noticed size of Shared Class Cache is 314,572,896 bytes. Is it expected?
```
NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 1,870,215,652 bytes / 3639 allocations
1MEMUSER       |
2MEMUSER       +--VM: 1,482,911,372 bytes / 2959 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 330,647,528 bytes / 292 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Shared Class Cache: 314,572,896 bytes / 2 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 16,074,632 bytes / 290 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Modules: 1,151,252,260 bytes / 2354 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 1,138,504,840 bytes / 1478 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 1,074,262,016 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 64,242,824 bytes / 1477 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 12,442,948 bytes / 375 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 276,000 bytes / 21 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 11,927,552 bytes / 22 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 239,396 bytes / 332 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 216,208 bytes / 277 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 53,232 bytes / 101 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 17,256 bytes / 110 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 1,011,584 bytes / 313 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 387,226,808 bytes / 650 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 14,680,512 bytes / 7 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 104,110,840 bytes / 642 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 77,472 bytes / 30 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 77,472 bytes / 30 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 528 bytes / 6 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 528 bytes / 6 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 76,944 bytes / 24 allocations
```

**Comment by pshipton** [comment]
> I noticed size of Shared Class Cache is 314,572,896 bytes. Is it expected?

Yes, 300MB is the default size when there is room. This is the maximum size, there is a soft limit of 80MB unless the users changes it.

**Comment by pshipton** [comment]
> It is not wrong but I was under impression that we don't want (and don't need obviously) to do it for Large Heap version of JVM for Mac.

Seems it was done intentionally. Soon there will only be one JVM anyway.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/217

**Comment by pshipton** [comment]
> However this OOM should be caught but it was not.

**Comment by pshipton** [comment]
> However this OOM should be caught but it was not.

I'm not sure this is the problem. Before Java code runs the dumps are created by default (unless -Xdump:none), and in this case an abort occurred. Why did the abort occur?

**Comment by dmitripivkine** [comment]
> > However this OOM should be caught but it was not.
> 
> I'm not sure this is the problem. Before Java code runs the dumps are created by default (unless -Xdump:none), and in this case an abort occurred. Why did the abort occur?

This is good point. The `Abort trap: 6` usually associates with memory violation. However should we have `JVMDUMP039I Processing dump event "systhrow"` message if exception should be caught? I guess it crashed somewhere in OOM handling

**Comment by dmitripivkine** [comment]
I found some registers:
```
native threads for address space
 process id: 19167

  thread id: 0
   registers:
    cpu    = 0x0000000000000000   cs     = 0x0000000000000286   err    = 0x0000000000000004   faultvaddr = 0x0200014800000085
    fs     = 0x0000000000000007   gs     = 0x0000000000000000   r10    = 0x0000000000000000   r11    = 0x0000000000000000
    r12    = 0x0000000000000287   r13    = 0x00000000b00929f0   r14    = 0x00007fa932604170   r15    = 0x00000000b0094000
    r8     = 0x00000000b0092518   r9     = 0x00000000b00924d0   rax    = 0x0000002a00000004   rbp    = 0x000000000000000b
    rbx    = 0x0000000000000000   rcx    = 0x000000000000000b   rdi    = 0x0000000000000000   rdx    = 0x00000000b0092518
    rflags = 0x00007fff8ab15286   rip    = 0x00000000b0092a82   rsi    = 0x0000000000000203   rsp    = 0x00000000b0092540
    trapno = 0x0000000000000006
   native stack sections:
Problem running command:
null
```

**Comment by pshipton** [comment]
> hould we have `JVMDUMP039I Processing dump event "systhrow"` message if exception should be caught? 

yes, that is what happens. Usually these type of tests run with `-Xdump:none`

**Comment by dmitripivkine** [comment]
>Is it because dump file name is too long (183 bytes) and goes out-of-bound?

I looked through code and can not find place where size for buffer reserved for system dump name is not a `J9_MAX_DUMP_PATH` defined as `EsMaxPath` defined as `1024`

**Comment by JasonFengJ9** [comment]
A similar failure at another internal build `Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/57`:
```
===============================================
Running test testSoftMxLocal_LP4k_3 ...
===============================================
testSoftMxLocal_LP4k_3 Start Time: Tue Apr 21 01:42:31 2020 Epoch Time (ms): 1587447751954
variation: Mode501
JVM_OPTIONS: -Xnocompressedrefs -Xjit -Xgcpolicy:balanced -Xnocompressedrefs 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/04/21 01:42:34 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3/core.20200421.014234.1840.0001.dmp' in response to an event
JVMDUMP010I System dump written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3/core.20200421.014234.1840.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3/heapdump.20200421.014234.1840.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3/heapdump.20200421.014234.1840.0002.phd
JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3/javacore.20200421.014234.1840.0003.txt' in response to an event
/bin/sh: line 1:  1840 Abort trap: 6           (core dumped) "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xnocompressedrefs -Xjit -Xgcpolicy:balanced -Xnocompressedrefs -Xmx1024m -Xsoftmx512m -Xmn1m -Xlp:objectheap:pagesize=4k -verbose:gc -Xverbosegclog:"/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3"/vgc.log -cp "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/lib/testng.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar" org.testng.TestNG -d "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15874423224062/testSoftMxLocal_LP4k_3" "/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_mac_xl_Nightly/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/testng.xml" -testnames testSoftMxLocal -groups level.extended -excludegroups d.*.osx_x86-64,d.*.arch.x86,d.*.os.osx,d.*.bits.64,d.*.generic-all

testSoftMxLocal_LP4k_3_FAILED
```

**Comment by pshipton** [comment]
This hasn't been seen in some time so closing. We can reopen if it's seen again.
