### ISSUE TITLE
testSCCacheManagement_0 Mismatch in number of ROMClasses

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8949]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/319
 testSCCacheManagement_0
```
1) testSharedCacheEnableBCI(tests.sharedclasses.options.junit.TestOptionsCacheDir)tests.sharedclasses.TestFailedException: Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 523With enableBCI, # ROMClasses: 490.
Maximum allowed difference is 10
	at tests.sharedclasses.TestUtils.fail(TestUtils.java:598)
	at tests.sharedclasses.options.TestSharedCacheEnableBCI.runTest1(TestSharedCacheEnableBCI.java:255)
	at tests.sharedclasses.options.TestSharedCacheEnableBCI.main(TestSharedCacheEnableBCI.java:61)
	at tests.sharedclasses.options.junit.TestOptionsBase.testSharedCacheEnableBCI(TestOptionsBase.java:132)
```

**Comment by pshipton** [comment]
Likely some timing problem, opened for tracking in case it starts to occur more often.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/106
`Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 500With enableBCI, # ROMClasses: 533.`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/269
`Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 763With enableBCI, # ROMClasses: 750.`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly_testList_0/444
testSCCacheManagement_0
```
Mismatch in number of ROMClasses. Without enableBCI, # ROMClasses: 548With enableBCI, # ROMClasses: 513.
Maximum allowed difference is 15
```
