### ISSUE TITLE
AArch64: Failure in java/lang/ProcessBuilder/Basic.java#id0.Basic_id0

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse/openj9#9032]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/103/testReport/junit/java_lang_ProcessBuilder_Basic/java_id0/Basic_id0/

Failure output (captured from console output)
---------------------------------------------

```
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2730)
	at Basic.check(Basic.java:2733)
	at Basic.realMain(Basic.java:1777)
	at Basic.main(Basic.java:2740)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2730)
	at Basic.check(Basic.java:2733)
	at Basic.realMain(Basic.java:1778)
	at Basic.main(Basic.java:2740)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2730)
	at Basic.check(Basic.java:2733)
	at Basic.realMain(Basic.java:1779)
	at Basic.main(Basic.java:2740)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'0'< not equal to '1'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2730)
	at Basic.fail(Basic.java:2731)
	at Basic.equal(Basic.java:2737)
	at Basic.realMain(Basic.java:1780)
	at Basic.main(Basic.java:2740)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:2742)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
```

This test launches a child process and expects it to throw OOM, but the child process does not always throw OOM on the aarch64 test machine simply because the machine has large memory (128GB)

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/34c3dd7d55b36a29d76f5708f6bc299844455e20/test/jdk/java/lang/ProcessBuilder/Basic.java#L354-L361

The child process creates an array with `Integer.MAX_VALUE` elements, but this is not large enough to always trigger OOM on the machine with 128GB memory.

**Comment by Akira1Saitoh** [comment]
@knn-k @0xdaryl

**Comment by Akira1Saitoh** [comment]
@smlambert Can you give us some advice on this, please?
I wonder if I can set `-Xmx` option only to this test (actually, a child process this test spawns) so that OOM is always thrown as expected. Is it possible?

**Comment by knn-k** [comment]
@smlambert 
Can you give us a comment on this, please?  It looks like a testcase failure.  Thanks.

**Comment by smlambert** [comment]
Since this testcase comes from the openjdk project we do not directly change the settings of the individual testcase but try to raise the issue upstream for a fix (though for local runs, it can be done as part of the test [here](https://github.com/openjdk/jdk11u/blob/master/test/jdk/java/lang/ProcessBuilder/Basic.java#L34-L35) by passing -mx value, see Examples at https://openjdk.java.net/jtreg/tag-spec.html).  

To request an upstream fix, we could try to raise an issue in JBS (Java Bug Database) at the OpenJDK project to correct it as you suggest.  

We have a jbs slack channel at AdoptOpenJDK where we ask for help from people with rights to raise upstream issues against openjdk (otherwise you have to send an email to a mailing list, which may or may not get attention).

**Comment by knn-k** [comment]
This test is already excluded in https://github.com/AdoptOpenJDK/openjdk-tests/blob/f5d240cfa768d00475ae5e3e2f06daf7a168550c/openjdk/ProblemList_openjdk11-openj9.txt#L41 for `aix-all` for a different reason.

Shall I open a pull request for excluding the test for `linux-aarch64`?

**Comment by knn-k** [comment]
I opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/1716 for excluding ProcessBuilder tests on AArch64.

**Comment by JasonFengJ9** [comment]
Similar errors occurred JDK11 Windows at https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/127/consoleFull
```
01:34:50  Passed = 9217, failed = 3
01:34:50  
01:34:50  STDERR:
01:34:50  >'1'< not equal to '0'
01:34:50  java.lang.Throwable
01:34:50  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
01:34:50  	at Basic.fail(Basic.java:2747)
01:34:50  	at Basic.fail(Basic.java:2748)
01:34:50  	at Basic.equal(Basic.java:2754)
01:34:50  	at Basic.commandOutput(Basic.java:111)
01:34:50  	at Basic.commandOutput(Basic.java:122)
01:34:50  	at Basic.javaChildOutput(Basic.java:567)
01:34:50  	at Basic.pwdInChild(Basic.java:583)
01:34:50  	at Basic.realMain(Basic.java:1745)
01:34:50  	at Basic.main(Basic.java:2757)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:34:50  	at java.base/java.lang.Thread.run(Thread.java:836)
01:34:50  >'1'< not equal to '0'
01:34:50  java.lang.Throwable
01:34:50  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
01:34:50  	at Basic.fail(Basic.java:2747)
01:34:50  	at Basic.fail(Basic.java:2748)
01:34:50  	at Basic.equal(Basic.java:2754)
01:34:50  	at Basic.commandOutput(Basic.java:112)
01:34:50  	at Basic.commandOutput(Basic.java:122)
01:34:50  	at Basic.javaChildOutput(Basic.java:567)
01:34:50  	at Basic.pwdInChild(Basic.java:583)
01:34:50  	at Basic.realMain(Basic.java:1745)
01:34:50  	at Basic.main(Basic.java:2757)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:34:50  	at java.base/java.lang.Thread.run(Thread.java:836)
01:34:50  >''< not equal to 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_15979877257959\jdk_lang_j9_0\work\scratch\3'
01:34:50  java.lang.Throwable
01:34:50  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
01:34:50  	at Basic.fail(Basic.java:2747)
01:34:50  	at Basic.fail(Basic.java:2748)
01:34:50  	at Basic.equal(Basic.java:2754)
01:34:50  	at Basic.realMain(Basic.java:1745)
01:34:50  	at Basic.main(Basic.java:2757)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:34:50  	at java.base/java.lang.Thread.run(Thread.java:836)
01:34:50  java.lang.AssertionError: Some tests failed
01:34:50  	at Basic.main(Basic.java:2759)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:34:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:34:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:34:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:34:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:34:50  	at java.base/java.lang.Thread.run(Thread.java:836)
01:34:50  
01:34:50  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
```

**Comment by JasonFengJ9** [comment]
Another occurrence is at https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/169/consoleFull.

Since these failures are across platforms, the `arch` label and issue title should be updated.

**Comment by pshipton** [comment]
@JasonFengJ9 the list of failures isn't the same, and the aarch64 test is excluded, pls open another issue for the Windows failures.

**Comment by JasonFengJ9** [comment]
@pshipton Sure, just created https://github.com/eclipse/openj9/issues/10793 for `JDK11 Windows`, and we can determine later if they are dups.
