### ISSUE TITLE
JTReg jdk11-m2 Failure: java/util/WeakHashMap/GCDuringIteration.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#9043]
Failure link
------------
- test category, sanity.openjdk
- OS/architecture, aarch_64
```
17:48:19  openjdk version "11.0.7" 2020-04-14
17:48:19  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9)
17:48:19  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0-m2, JRE 11 Linux aarch64-64-Bit Compressed References 20200330_255 (JIT enabled, AOT enabled)
17:48:19  OpenJ9   - c93e4dabc
17:48:19  OMR      - 1b6abd044
17:48:19  JCL      - 644e9abfc0 based on jdk-11.0.7+9)
```

Optional info
-------------

- intermittent failure (no): 
- Part of the jdk11-m2 triage https://github.com/AdoptOpenJDK/openjdk-tests/issues/1705

Failure output (captured from console output)
---------------------------------------------
```
Standard Output
Seed from RandomFactory = -3230224931385960640L
[18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[17, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Passed = 309, failed = 1

    
Standard Error
java.lang.AssertionError: failed to do a "full" gc
	at GCDuringIteration.forceFullGc(GCDuringIteration.java:74)
	at GCDuringIteration.test(GCDuringIteration.java:190)
	at GCDuringIteration.instanceMain(GCDuringIteration.java:263)
	at GCDuringIteration.main(GCDuringIteration.java:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.AssertionError: Some tests failed
	at GCDuringIteration.instanceMain(GCDuringIteration.java:265)
	at GCDuringIteration.main(GCDuringIteration.java:261)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
This failure is known to be the same as #8897.

**Comment by knn-k** [comment]
This test is excluded by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1715 .

**Comment by smlambert** [comment]
Re-included tests via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1780

**Comment by knn-k** [comment]
This test is no longer failing in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/140/ .

**Comment by M-Davies** [comment]
> This test is no longer failing in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/140/ .

Running https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3016/ to confirm

**Comment by M-Davies** [comment]
Grinder passed. Thanks for the heads up @knn-k
