### ISSUE TITLE
JTReg jdk11-m2 Failure: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#9044]
Failure link
------------
- test category, sanity.openjdk 
- OS/architecture, aarch_64
```
17:48:19  openjdk version "11.0.7" 2020-04-14
17:48:19  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9)
17:48:19  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0-m2, JRE 11 Linux aarch64-64-Bit Compressed References 20200330_255 (JIT enabled, AOT enabled)
17:48:19  OpenJ9   - c93e4dabc
17:48:19  OMR      - 1b6abd044
17:48:19  JCL      - 644e9abfc0 based on jdk-11.0.7+9)
```

Optional info
-------------
- intermittent failure (no):  
- Part of the jdk11-m2 triage https://github.com/AdoptOpenJDK/openjdk-tests/issues/1705

Failure output (captured from console output)
---------------------------------------------
```
18:56:40  STDOUT:
18:56:40  [TestNG] Running:
18:56:40    java/util/concurrent/ArrayBlockingQueue/WhiteBox.java
18:56:40  
18:56:40  test WhiteBox.Iterator_remove_safetyWhileInDetachedMode(): success
18:56:40  test WhiteBox.advancing2CyclesWillRemoveIterators(): success
18:56:40  test WhiteBox.clear_willClearItrs(): success
18:56:40  test WhiteBox.collectiveSanity(): success
18:56:40  test WhiteBox.dequeuesBypassingIteratorCurrentPositions(): success
18:56:40  test WhiteBox.garbageCollectionOfUnreachableIterators(): success
18:56:40  test WhiteBox.garbageCollectionOfUnreachableIteratorsWithRandomlyRetainedSubset(): success
18:56:40  test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
18:56:40  java.lang.AssertionError: failed to do a "full" gc
18:56:40  	at WhiteBox.forceFullGc(WhiteBox.java:226)
18:56:40  	at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
18:56:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:56:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:56:40  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:56:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:56:40  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
18:56:40  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
18:56:40  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
18:56:40  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
18:56:40  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
18:56:40  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
18:56:40  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
18:56:40  	at org.testng.TestRunner.run(TestRunner.java:623)
18:56:40  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
18:56:40  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
18:56:40  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
18:56:40  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
18:56:40  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
18:56:40  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
18:56:40  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
18:56:40  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
18:56:40  	at org.testng.TestNG.run(TestNG.java:1018)
18:56:40  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
18:56:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:56:40  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:56:40  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:56:40  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:56:40  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
18:56:40  	at java.base/java.lang.Thread.run(Thread.java:834)
18:56:40  test WhiteBox.interiorRemovalOfAlternatingElements(): success
18:56:40  test WhiteBox.interiorRemovalOfElementsUsedByIterator(): success
18:56:40  test WhiteBox.interiorRemovalOfIteratorsLastElement(): success
18:56:40  test WhiteBox.iteratorsDetachedWhenExhaustedAndLastRetRemoved(): success
18:56:40  test WhiteBox.iteratorsOnEmptyQueue(): success
18:56:40  test WhiteBox.queueEmptyingWillClearItrs(): success
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
Never seen this before.

**Comment by knn-k** [comment]
I recreated the failure only once in 20+ runs.
```
test WhiteBox.incrementalSweepingOfUnreachableIterators(): failure
java.lang.AssertionError: failed to do a "full" gc
        at WhiteBox.forceFullGc(WhiteBox.java:226)
        at WhiteBox.incrementalSweepingOfUnreachableIterators(WhiteBox.java:555)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by knn-k** [comment]
Possibly the same cause as #8897.

**Comment by 0xdaryl** [comment]
@knn-k : can you try reproducing this with `-Xjit:enableAggressiveLiveness`?  If it still fails then it likely isn't the same problem as 8897.  I believe I know what the problem is for 8897, though I'm not sure yet if it is a test case issue or an optimizer issue.  More details coming in 8897.

**Comment by knn-k** [comment]
I tried `-Xjit:enableAggressiveLiveness` on cent7-aarch64-1 50 times, and they all pass.

**Comment by 0xdaryl** [comment]
OK.  Given this is an intermittent GC failure, is it possible to run it perhaps 100 times with that option?

**Comment by knn-k** [comment]
I ran 100 times with the compression refs build + 100 times with the large heap build.
I see no failures with `-Xjit:enableAggressiveLiveness`.

**Comment by M-Davies** [comment]
Ran this under the failing test's conditions. Seen 13/100 failures (test output/dump files are here in case the grinder is deleted https://ibm.box.com/shared/static/4db1l3tshf9xon6tauueb6wl3to5rygc.gz)

Running a 2nd 100 iteration grinder with `-Xjit:enableAggressiveLiveness` option enabled https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2720/console

**Comment by M-Davies** [comment]
2nd Grinder passed.

@0xdaryl Adding `-Xjit:enableAggressiveLiveness` seems to have resolved this. Is there a system setting that could be causing @knn-k testing to pass and not ours at Adopt?

**Comment by knn-k** [comment]
This test is excluded by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1715 .

**Comment by smlambert** [comment]
Re-included tests via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1780

**Comment by knn-k** [comment]
This test is no longer failing in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/140/ .

**Comment by M-Davies** [comment]
> This test is no longer failing in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/140/ .

Running https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3017/ to confirm

**Comment by M-Davies** [comment]
Grinder passed. Thanks @knn-k
