### ISSUE TITLE
zlinux failing to resolve github.com

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9066]
Still happening on builds this morning. All  of the zlinux builds failed last night.
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/346
`stderr: fatal: unable to access 'https://github.com/ibmruntimes/openj9-openjdk-jdk8.git/': Could not resolve host: github.com; Unknown error`

https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_xl_Nightly/126/
https://ci.eclipse.org/openj9/job/Build_JDK14_s390x_linux_Nightly/56/
https://ci.eclipse.org/openj9/job/Build_JDKnext_s390x_linux_OpenJDK/193/

The other machines had problems uploading to OSU last night.
`Caused by: java.net.UnknownHostException: 140-211-168-230-openstack.osuosl.org`
but in a test this morning, failing to resolve github.com now.(https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/347).

https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/345/
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_xl_Nightly/125/
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_Nightly/345/

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
I disconnected rh7-390-4, trying to bring it back online results in
```
$ ssh -C -i /run/secrets/jenkins/ssh/id_rsa.openj9 jenkins@148.100.245.61 "wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar"
Error: Invalid or corrupt jarfile slave.jar
ERROR: Unable to launch the agent for rh7-390-4
java.io.EOFException: unexpected stream termination
	at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:415)
	at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:360)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:434)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:154)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by jdekonin** [comment]
Our rhel7 390 machines cannot ping github.com.  ub16 390 machines do but these do not.  I will raise the issue with the provider.

**Comment by pshipton** [comment]
Seems to have been resolved.

**Comment by jdekonin** [comment]
Appears this resolved itself at some point between 4-5pm yesterday, and then stopped working around 8-9PM.  It was working when I checked at 5am and then again 9am this morning.  All times EST.  I've asked for a reason for what happened but I have yet to receive a concrete answer.

**Comment by pshipton** [comment]
All the nightly builds last night were fine.
