### ISSUE TITLE
extended.system SharedClasses NullPointerException BruteArgumentMoverHandle.permuteArguments

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9127]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/331
SharedClasses.SCM01.MultiThread_0
```
[2020-04-04T04:20:29.818Z] MT4 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
[2020-04-04T04:20:29.818Z] MT4 stderr   at net.openj9.test.sc.LoaderSlaveMultiThread.logMessage(LoaderSlaveMultiThread.java:153)
[2020-04-04T04:20:29.818Z] MT4 stderr   at net.openj9.test.sc.LoaderSlaveMultiThread.run(LoaderSlaveMultiThread.java:134)
[2020-04-04T04:20:29.818Z] MT4 stderr   at net.openj9.test.sc.LoaderSlaveMultiThread.main(LoaderSlaveMultiThread.java:59)
[2020-04-04T04:20:29.818Z] MT4 stderr Caused by: java.lang.invoke.StringConcatException: Generator failed
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:302)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.CollectHandle.invokeExact_thunkArchetype_X(CollectHandle.java:130)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
[2020-04-04T04:20:29.818Z] MT4 stderr   ... 3 more
[2020-04-04T04:20:29.818Z] MT4 stderr Caused by: java.lang.NullPointerException
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.BruteArgumentMoverHandle.permuteArguments(BruteArgumentMoverHandle.java:286)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2911)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2928)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1536)
[2020-04-04T04:20:29.818Z] MT4 stderr   at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
[2020-04-04T04:20:29.818Z] MT4 stderr   ... 10 more
```

**Comment by pshipton** [comment]
Dup of #8972
