### ISSUE TITLE
JDK8 JIT Server : cmdLineTester_jvmtitests_8 emeng001 NPE

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9129]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Nightly/39`:
```
22:13:11  openjdk version "1.8.0_252-internal"
22:13:11  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_04_04_18_44-b00)
22:13:11  Eclipse OpenJ9 VM (build ibm_sdk-128193cebc, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200404_40 (JIT enabled, AOT enabled)
22:13:11  OpenJ9   - 128193cebc
22:13:11  OMR      - b7eb64f76
22:13:11  JCL      - 4f7bf238294 based on jdk8u252-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Testing: emeng001
Test start time: 2020/04/04 19:31:17 Pacific Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump    -agentlib:jvmtitest=test:emeng001 -cp "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_jit_Nightly/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 4 milliseconds
Time spent executing: 45 milliseconds
Test result: FAILED
Output from test:
 [ERR] JITServer is currently a technology preview. Its use is not yet supported
 [ERR] Exception in thread "(unnamed thread)" java/lang/ExceptionInInitializerError
 [ERR] 	at java/lang/J9VMInternals.ensureError (J9VMInternals.java:148)
 [ERR] 	at java/lang/J9VMInternals.recordInitializationFailure (J9VMInternals.java:137)
 [ERR] 	at java/lang/ref/Reference.<clinit> (Reference.java:57)
 [ERR] 	at java/lang/Class.forNameImpl (NativeMethod:4294967295)
 [ERR] 	at java/lang/Class.forName (Class.java:337)
 [ERR] 	at java/lang/ref/ReferenceQueue.<clinit> (ReferenceQueue.java:53)
 [ERR] 	at java/util/WeakHashMap.<init> (WeakHashMap.java:180)
 [ERR] 	at java/util/WeakHashMap.<init> (WeakHashMap.java:241)
 [ERR] 	at java/lang/invoke/MethodType.<clinit> (MethodType.java:82)
 [ERR] java/lang/NullPointerException
 [ERR] 	at sun/reflect/Reflection.getCallerClass (NativeMethod:4294967295)
 [ERR] 	at sun/misc/Unsafe.getUnsafe (Unsafe.java:94)
 [ERR] 	at sun/misc/SharedSecrets.<clinit> (SharedSecrets.java:48)
 [ERR] 	at java/lang/ref/Reference.<clinit> (Reference.java:57)
 [ERR] 	at java/lang/Class.forNameImpl (NativeMethod:4294967295)
 [ERR] 	at java/lang/Class.forName (Class.java:337)
 [ERR] 	at java/lang/ref/ReferenceQueue.<clinit> (ReferenceQueue.java:53)
 [ERR] 	at java/util/WeakHashMap.<init> (WeakHashMap.java:180)
 [ERR] 	at java/util/WeakHashMap.<init> (WeakHashMap.java:241)
 [ERR] 	at java/lang/invoke/MethodType.<clinit> (MethodType.java:82)
>> Success condition was not found: [Return code: 0]

cmdLineTester_jvmtitests_8_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=cmdLineTester_jvmtitests_8

**Comment by pshipton** [comment]
@mpirvu

**Comment by harryyu1994** [comment]
Grinder 10x launched: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7143/

**Comment by EmanElsaban** [comment]
Ran 200 tests on Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11935/.  96 failed out of 200
This failure is similar to the failure in issue #9846 

Console Output:
```
19:57:10  Testing: gaste001
19:57:10  Test start time: 2020/11/06 19:57:09 Eastern Standard Time
19:57:10  Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump    -Xjit:count=0 -agentlib:jvmtitest=test:gaste001 -cp "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
19:57:10  Time spent starting: 2 milliseconds
19:57:29  Time spent executing: 18912 milliseconds
19:57:29  Test result: PASSED
19:57:29  
19:57:29  Testing: gaste001_multiple
19:57:29  Test start time: 2020/11/06 19:57:28 Eastern Standard Time
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] Error during test case: gaste001_multiple***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] java.lang.NullPointerException***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at java.lang.String.charAtInternal(String.java)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at java.lang.String.split(String.java:3682)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at java.lang.String.split(String.java:3609)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at TestSuite.printStackTrace(TestSuite.java:479)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at Test.run(Test.java:238)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at TestSuite.runTest(TestSuite.java:84)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at TestIterator.addTest(TestIterator.java:84)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at TestConfigParser$TestConfigDocumentHandler.xmlEndElement(TestConfigParser.java:309)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at com.oti.j9.exclude.XMLParser._scan_element_close(XMLParser.java:370)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at com.oti.j9.exclude.XMLParser._scan_element_or_instruction(XMLParser.java:391)***
19:57:29  ***[TEST INFO 2020/11/06 19:57:28] 	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:442)***
19:57:29  java.lang.NullPointerException
19:57:29  	at java.lang.String.length(String.java)
19:57:29  	at java.util.Locale.isUnicodeExtensionKey(Locale.java:2118)
19:57:29  	at java.util.Locale.getUnicodeLocaleType(Locale.java:1207)
19:57:29  	at java.util.Calendar$Builder.build(Calendar.java:1470)
19:57:29  	at sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:88)
19:57:29  	at java.util.Calendar.createCalendar(Calendar.java:1666)
19:57:29  	at java.util.Calendar.getInstance(Calendar.java:1655)
19:57:29  	at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:657)
19:57:29  	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:601)
19:57:29  	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
19:57:29  	at TestSuite.printErrorMessage(TestSuite.java:470)
19:57:29  	at TestSuite.printStackTrace(TestSuite.java:482)
19:57:29  	at TestSuite.runTest(TestSuite.java:104)
19:57:29  	at TestIterator.addTest(TestIterator.java:84)
19:57:29  	at TestConfigParser$TestConfigDocumentHandler.xmlEndElement(TestConfigParser.java:309)
19:57:29  	at com.oti.j9.exclude.XMLParser._scan_element_close(XMLParser.java:370)
19:57:29  	at com.oti.j9.exclude.XMLParser._scan_element_or_instruction(XMLParser.java:391)
19:57:29  	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:442)
19:57:29  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:470)
19:57:29  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
19:57:29  	at TestConfigParser.runTests(TestConfigParser.java:78)
19:57:29  	at MainTester.main(MainTester.java:106)
19:57:29  
19:57:29  ---TEST RESULTS---Exception in thread "main" java.lang.ExceptionInInitializerError
19:57:29  	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
19:57:29  	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
19:57:29  	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:872)
19:57:29  	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
19:57:29  	at java.lang.Thread.uncaughtException(Thread.java:1336)
19:57:29  Caused by: java.lang.NullPointerException
19:57:29  	at java.lang.StringBuilder.lengthInternal(StringBuilder.java)
19:57:29  	at java.lang.StringBuilder.append(StringBuilder.java:363)
19:57:29  	at java.lang.StringBuilder.appendCodePoint(StringBuilder.java:2865)
19:57:29  	at java.lang.String.toUpperCaseCore(String.java:3257)
19:57:29  	at java.lang.String.toUpperCase(String.java:3211)
19:57:29  	at java.util.jar.JarFile.maybeInstantiateVerifier(JarFile.java:336)
19:57:29  	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
19:57:29  	at com.ibm.oti.vm.AbstractClassLoader.getResourceAsStream(AbstractClassLoader.java:328)
19:57:29  	at com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:199)
19:57:29  	at com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
19:57:29  	at java.security.AccessController.doPrivileged(AccessController.java:678)
19:57:29  	at com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
19:57:29  	... 3 more
19:57:29  
19:57:29  cmdLineTester_jvmtitests_8_FAILED
```
FYI: @dmitry-ten  @mpirvu

**Comment by dmitry-ten** [comment]
Hopefully got fixed by  eclipse/omr#5658.
Running tests to verify

**Comment by dmitry-ten** [comment]
@mpirvu 200 [tests](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/12371/) passed, this can be closed.

**Comment by mpirvu** [comment]
Fixed by https://github.com/eclipse/omr/pull/5658
Closing based on the previous message.
