### ISSUE TITLE
java.lang.invoke.MethodHandlers.lookup() behaves different with openjdk.

### ISSUE THREAD

**Issue by fanthos** [eclipse/openj9#9147]
Java -version output
--------------------
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

Another OpenJDK:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+8-b520.43)
OpenJDK 64-Bit Server VM (build 11.0.6+8-b520.43, mixed mode, sharing)

Summary of problem
------------------
I have a jar works on OpenJdk11, 
I got exception when replace OpenJdk with OpenJ9:
```
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:412)
	...
Caused by: java.lang.IllegalArgumentException: Illegal Lookup object - originated from java.lang.invoke: java.lang.invoke.SecurityFrame
	at java.base/java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:151)
	at java.base/java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:164)
	at java.base/java.lang.invoke.MethodHandles.lookup(MethodHandles.java:1715)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:521)
	at java.lang.invoke.SecurityFrame.invoke(SecurityFrame.java:44)
	at java.base/java.lang.invoke.ReceiverBoundHandle.invokeExact_thunkArchetype_L(ReceiverBoundHandle.java:168)
	at ***.<clinit>(***.java)
	...
```
After some search, I found that `java.lang.invoke.MethodHandlers.lookup()` behaves different with openjdk.
In javadoc from OpenJdk:
```
    /* Returns a {@link Lookup lookup object} with
     * full capabilities to emulate all supported bytecode behaviors of the caller.
     * These capabilities include {@linkplain Lookup#hasFullPrivilegeAccess() full privilege access} to the caller.
     * Factory methods on the lookup object can create
     * <a href="MethodHandleInfo.html#directmh">direct method handles</a>
     * for any member that the caller has access to via bytecodes,
     * including protected and private fields and methods.
```
but OpenJ9 shows:
`Return a MethodHandles.Lookup object for the caller.`

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by DanHeidinga** [comment]
@fanthos Can you supply the command line options used?  Is there a test case we can use that can reproduce the issue?

**Comment by fanthos** [comment]
Sorry, its third party code. I will close this issue for now.
