### ISSUE TITLE
z/OS sanity.functional jsr335tests Invalid lambda deserialization

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9168]
job/Test_openjdk11_j9_sanity.functional_s390x_zos_Nightly
jsr335tests_1
jsr335tests_3
jsr335tests_5
jsr335tests_openj9_none_SCC_1
jsr335tests_openj9_none_SCC_3
jsr335tests_openj9_none_SCC_5
```
[2020-03-27T03:26:28.762Z] FAILED: testBasicSerializable
[2020-03-27T03:26:28.762Z] java.io.IOException: unexpected exception type
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1626)
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1256)
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2278)
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1771)
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:551)
[2020-03-27T03:26:28.762Z]      at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
[2020-03-27T03:26:28.762Z]      at org.openj9.test.jsr335.TestSerializable.reserialize(TestSerializable.java:286)
[2020-03-27T03:26:28.762Z]      at org.openj9.test.jsr335.TestSerializable.testBasicSerializable(TestSerializable.java:57)
[2020-03-27T03:26:28.762Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-27T03:26:28.762Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-27T03:26:28.762Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-27T03:26:28.762Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2020-03-27T03:26:28.762Z]      at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[2020-03-27T03:26:28.762Z]      at org.testng.TestRunner.privateRun(TestRunner.java:648)
[2020-03-27T03:26:28.762Z]      at org.testng.TestRunner.run(TestRunner.java:505)
[2020-03-27T03:26:28.762Z]      at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2020-03-27T03:26:28.762Z]      at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2020-03-27T03:26:28.762Z]      at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2020-03-27T03:26:28.763Z]      at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2020-03-27T03:26:28.763Z]      at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2020-03-27T03:26:28.763Z]      at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.runSuites(TestNG.java:1049)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.run(TestNG.java:1017)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.privateMain(TestNG.java:1354)
[2020-03-27T03:26:28.763Z]      at org.testng.TestNG.main(TestNG.java:1323)
[2020-03-27T03:26:28.763Z] Caused by: java.lang.reflect.InvocationTargetException
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-27T03:26:28.763Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-03-27T03:26:28.763Z]      at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:237)
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-27T03:26:28.763Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-27T03:26:28.763Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-03-27T03:26:28.763Z]      at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1250)
[2020-03-27T03:26:28.763Z]      ... 30 more
[2020-03-27T03:26:28.763Z] Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
[2020-03-27T03:26:28.763Z]      at org.openj9.test.jsr335.TestSerializable.$deserializeLambda$(TestSerializable.java:38)
[2020-03-27T03:26:28.763Z]      ... 40 more
```

Similarly
testGeneratedStringLambda
testLocalBooleanLambda
etc.

**Comment by DanHeidinga** [comment]
I'd start by using `javap` or `cfdump` to dump the `org.openj9.test.jsr335.TestSerializable` class and look at the `$deserializeLambda$` method to see what data it's looking at when deserializing.

My first guess here would be that there's an issue in the encoding for the data used to deserialize and this would be a way to check that

**Comment by mikezhang1234567890** [comment]
Taking a look.

**Comment by mikezhang1234567890** [comment]
It seems this issue is caused by malformed strings in the constant pool used by the `deserializeLambda` method. 

for example, a snippet of a z/OS classfile:
```
        70: invokevirtual #16                 // Method java/lang/invoke/SerializedLambda.getFunctionalInterfaceClass:()Ljava/lang/String;
        73: ldc           #17                 // String ¦/Î/\u0007ÍÈÑ%\u0007Ä?>ÄÍÊÊÁ>È\u0007ä/%%/Â%Á
        75: invokevirtual #18                 // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
```

vs OSX classfile:
```
        70: invokevirtual #16                 // Method java/lang/invoke/SerializedLambda.getFunctionalInterfaceClass:()Ljava/lang/String;
        73: ldc           #17                 // String java/util/concurrent/Callable
        75: invokevirtual #18                 // Method java/lang/Object.equals:(Ljava/lang/Object;)Z
```

Using a class file generated on a working platform on z/OS works. Still investigating why javac is outputting gibberish strings on z/OS.

**Comment by DanHeidinga** [comment]
> Still investigating why javac is outputting gibberish strings on z/OS.

Are they gibberish or are they encoded in EBCDIC rather than ascii?  There may be a path in the file IO that's accidentally doing the ASCII->EBCDIC conversion

**Comment by mikezhang1234567890** [comment]
The bytes aren't in ebcdic, however the malformed strings are similar in a way that suggests encoding gone wrong.

**Comment by mikezhang1234567890** [comment]
Turns out this isn't unique to z/OS, see https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/318
