### ISSUE TITLE
java_util_logging_CheckZombieLockTest Unexpected lock files found

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9186]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/3
java/util/logging/CheckZombieLockTest.java.CheckZombieLockTest (from java_util_logging_CheckZombieLockTest.java)
```
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir\\log.log
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir\\log.log.lck
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir\\log.log
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir\\log.log.lck
WARNING: unable to delete/cleanup writable test directory: C:\\temp\\writable-lockfile-dir
java.lang.RuntimeException: Unexpected lock files found: []
	C:\\temp\\writable-lockfile-dir\\log.log.lck should not have been reused
	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected lock files found: []
	C:\\temp\\writable-lockfile-dir\\log.log.lck should not have been reused
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Unexpected lock files found: [] C:\\temp\\writable-lockfile-dir\\log.log.lck should not have been reused
```

**Comment by pshipton** [comment]
3x grinder https://ci.eclipse.org/openj9/job/Grinder/761/

**Comment by lumpfish** [comment]
Occurred on jdk-11.0.7+10 GA build: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/188/consoleFull

**Comment by M-Davies** [comment]
Occurred on a nightly build https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/191/

Exclude PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1740

**Comment by JasonFengJ9** [comment]
Occurred in a JDK16 internal build `Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/232`:
```
22:28:13  openjdk version "16-internal" 2021-03-16
22:28:13  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
22:28:13  Eclipse OpenJ9 VM (build master-c2d4f396055, JRE 16 AIX ppc64-64-Bit Compressed References 20200922_334 (JIT enabled, AOT enabled)
22:28:13  OpenJ9   - c2d4f396055
22:28:13  OMR      - 4c2d9a1f1c2
22:28:13  JCL      - ed102a5ef9d based on jdk-16+16)

23:21:18  --------------------------------------------------
23:21:18  TEST: java/util/logging/CheckZombieLockTest.java
23:21:18  TEST JDK: /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/openjdkbinary/j2sdk-image
23:21:18  

23:21:18  STDERR:
23:21:18  WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
23:21:18  java.lang.RuntimeException: Unexpected lock files found: []
23:21:18  	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
23:21:18  	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
23:21:18  	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
23:21:18  	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
23:21:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:21:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
23:21:18  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:21:18  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:21:18  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:21:18  	at java.base/java.lang.Thread.run(Thread.java:845)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/11

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/186/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Nightly/157

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_xl_Nightly/46

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/3/

**Comment by JasonFengJ9** [comment]
Also seen in an internal JDK11 AIX mixed build `Test_openjdk11_j9_sanity.openjdk_ppc64_aix_mixed/1`.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/29

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/8

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/9

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/6/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/15/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_mixed_Nightly/17/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_mixed_Nightly/14

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/299/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/300/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/285/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/307/

**Comment by pshipton** [comment]
@tajila `-XX:-GlobalLockReservation` is still the default until https://github.com/eclipse/openj9/issues/11424 is merged, so yes it has.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/308

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/32/

**Comment by tajila** [comment]
After taking a closer look at the issue, I believe it has nothing to do with globalLockReservation. Given the intermittent nature of the failure, it may be a file system issue.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/293/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/35/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/318/

**Comment by lumpfish** [comment]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/373/consoleFull

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix_Nightly/29/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix_Nightly/44/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/48

**Comment by JasonFengJ9** [comment]
JDK11 (0.27 release) `jdk_util_1_FAILED` at https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Release/5/consoleFull
```
17:52:23  --------------------------------------------------
17:52:23  TEST: java/util/logging/CheckZombieLockTest.java
17:52:23  STDERR:
17:52:23  WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
17:52:23  java.lang.RuntimeException: Unexpected lock files found: []
17:52:23  	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
17:52:23  	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
17:52:23  	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
17:52:23  	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
17:52:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:52:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:52:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:52:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:52:23  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
17:52:23  	at java.base/java.lang.Thread.run(Thread.java:866)
17:52:23  
17:52:23  JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected lock files found: []
17:52:23  	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
17:52:23  JavaTest Message: shutting down test
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/90/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/109

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/68
jdk_util_0
java/util/logging/CheckZombieLockTest.java
```
22:28:45  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Unexpected lock files found: [] C:\temp\writable-lockfile-dir\log.log.lck should not have been reused
22:28:45  REASON: User specified action: run main/othervm CheckZombieLockTest REUSE 
22:28:45  TIME:   0.61 seconds
22:28:45  messages:
22:28:45  command: main CheckZombieLockTest REUSE
22:28:45  reason: User specified action: run main/othervm CheckZombieLockTest REUSE 
22:28:45  Mode: othervm [/othervm specified]
22:28:45  Additional options from @modules: --add-modules java.logging
22:28:45  elapsed time (seconds): 0.61
22:28:45  configuration:
22:28:45  Boot Layer
22:28:45    add modules: java.logging
22:28:45  
22:28:45  STDOUT:
22:28:45  Writable dir is: C:\temp\writable-lockfile-dir
22:28:45  before: 0 locks found
22:28:45  handler created: java.util.logging.FileHandler@cb28c645
22:28:45  Found file: log.log
22:28:45  Found file: log.log.lck
22:28:45  after creating handler: 1 locks found
22:28:45  Found file: log.log
22:28:45  after closing handler: 0 locks found
22:28:45  Found file: log.log
22:28:45  Found file: log.log.lck
22:28:45  before: 1 locks found
22:28:45  handler created: java.util.logging.FileHandler@c0252d4a
22:28:45  Found file: log.log
22:28:45  Found file: log.log.lck
22:28:45  after creating handler: 1 locks found
22:28:45  handler closed: java.util.logging.FileHandler@c0252d4a
22:28:45  Found file: log.log
22:28:45  after closing handler: 0 locks found
22:28:45  locked: C:\temp\writable-lockfile-dir\log.log.lck
22:28:45  handler created: java.util.logging.FileHandler@f2c74daa
22:28:45  Found file: log.log
22:28:45  Found file: log.log.lck
22:28:45  after creating handler: 1 locks found
22:28:45  end: 1 locks found
22:28:45  STDERR:
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir\log.log
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir\log.log.lck
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir\log.log
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir\log.log.lck
22:28:45  WARNING: unable to delete/cleanup writable test directory: C:\temp\writable-lockfile-dir
22:28:45  java.lang.RuntimeException: Unexpected lock files found: []
22:28:45  	C:\temp\writable-lockfile-dir\log.log.lck should not have been reused
22:28:45  	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
22:28:45  	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
22:28:45  	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
```

**Comment by tajila** [comment]
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into it.

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/82

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/147

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/94

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/99/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/102/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/169/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/153/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/164

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/217/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/173/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/175/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_Nightly/33

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/223/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/223/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Release/31

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/265/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/277

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/267/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/312/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/316/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/362/

**Comment by JasonFengJ9** [comment]
[Internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/185/)(`paix825`)
```
java version "17.0.5" 2022-10-18
IBM Semeru Runtime Certified Edition 17.0.5+6 (build 17.0.5+6)
Eclipse OpenJ9 VM 17.0.5+6 (build master-784820387, JRE 17 AIX ppc64-64-Bit Compressed References 20221018_228 (JIT enabled, AOT enabled)
OpenJ9   - 784820387
OMR      - 24b511df5
JCL      - 4c6463ea1 based on jdk-17.0.5+6)

[2022-09-25T03:08:19.959Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-09-25T03:08:19.959Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-09-25T03:26:38.733Z] TEST: java/util/logging/CheckZombieLockTest.java

[2022-09-25T03:26:38.741Z] STDERR:
[2022-09-25T03:26:38.741Z] WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
[2022-09-25T03:26:38.741Z] java.lang.RuntimeException: Unexpected lock files found: []
[2022-09-25T03:26:38.741Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
[2022-09-25T03:26:38.741Z] 	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
[2022-09-25T03:26:38.741Z] 	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
[2022-09-25T03:26:38.741Z] 	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
[2022-09-25T03:26:38.741Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-09-25T03:26:38.741Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-09-25T03:26:38.741Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-09-25T03:26:38.741Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-09-25T03:26:38.741Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-09-25T03:26:38.741Z] 	at java.base/java.lang.Thread.run(Thread.java:857)

[2022-09-25T03:56:05.368Z] Test results: passed: 897; failed: 1
[2022-09-25T03:56:34.193Z] Report written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16640711942664/jdk_util_0/report/html/report.html
[2022-09-25T03:56:34.193Z] Results written to /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/aqa-tests/TKG/output_16640711942664/jdk_util_0/work
[2022-09-25T03:56:34.193Z] Error: Some tests failed or other problems occurred.
[2022-09-25T03:56:34.193Z] 
[2022-09-25T03:56:34.193Z] jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/348

**Comment by JasonFengJ9** [comment]
[JDK17 0.36.0 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_testList_0/227/)
```
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0-m1 (build 17.0.6+4)
Eclipse OpenJ9 VM 17.0.6.0-m1 (build v0.36.0-release-f98e55973, JRE 17 AIX ppc64-64-Bit Compressed References 20230117_324 (JIT enabled, AOT enabled)
OpenJ9   - f98e55973
OMR      - acdbafc4a
JCL      - 792b340c15c based on jdk-17.0.6+4)
```

```
[2022-12-01T09:30:25.092Z] TEST: java/util/logging/CheckZombieLockTest.java

[2022-12-01T09:30:25.095Z] STDERR:
[2022-12-01T09:30:25.095Z] WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
[2022-12-01T09:30:25.095Z] java.lang.RuntimeException: Unexpected lock files found: []
[2022-12-01T09:30:25.095Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
[2022-12-01T09:30:25.095Z] 	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
[2022-12-01T09:30:25.095Z] 	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
[2022-12-01T09:30:25.095Z] 	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
[2022-12-01T09:30:25.095Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-12-01T09:30:25.095Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2022-12-01T09:30:25.095Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-12-01T09:30:25.095Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2022-12-01T09:30:25.095Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2022-12-01T09:30:25.095Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-12-01T09:30:25.095Z] 
[2022-12-01T09:30:25.095Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected lock files found: []
[2022-12-01T09:30:25.095Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
[2022-12-01T09:30:25.095Z] JavaTest Message: shutting down test
[2022-12-01T09:30:25.095Z] 
[2022-12-01T09:30:25.095Z] STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Unexpected lock files found: [] /tmp/writable-lockfile-dir/log.log.lck should not have been reused
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/379

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_x86-64_windows_Nightly/415/

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64_aix_Nightly/408

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR/2/

**Comment by JasonFengJ9** [comment]
[JDK8 ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_testList_0/488/)(`paix910`)
```
[2023-11-17T09:44:28.221Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2023-11-17T09:44:28.221Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2023-11-17T09:55:25.464Z] TEST: java/util/logging/CheckZombieLockTest.java

[2023-11-17T09:55:25.468Z] STDERR:
[2023-11-17T09:55:25.468Z] WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
[2023-11-17T09:55:25.468Z] java.lang.RuntimeException: Unexpected lock files found: []
[2023-11-17T09:55:25.468Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
[2023-11-17T09:55:25.468Z] 	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
[2023-11-17T09:55:25.469Z] 	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
[2023-11-17T09:55:25.469Z] 	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
[2023-11-17T09:55:25.469Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-11-17T09:55:25.469Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-11-17T09:55:25.469Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-11-17T09:55:25.469Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2023-11-17T09:55:25.469Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2023-11-17T09:55:25.469Z] 	at java.lang.Thread.run(Thread.java:826)
[2023-11-17T09:55:25.469Z] 
[2023-11-17T09:55:25.469Z] JavaTest Message: Test threw exception: java.lang.RuntimeException: Unexpected lock files found: []
[2023-11-17T09:55:25.469Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused

[2023-11-17T10:08:28.486Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OMR_testList_2/93

**Comment by JasonFengJ9** [comment]
[openjdk8_j9_sanity.openjdk_ppc64_aix](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/1275/)
```
[2026-05-23T00:14:21.074Z] Running test jdk_util_other_0 ...
[2026-05-23T00:14:21.074Z] ===============================================
[2026-05-23T00:14:21.074Z] jdk_util_other_0 Start Time: Fri May 22 20:14:20 2026 Epoch Time (ms): 1779495260577
[2026-05-23T00:14:21.074Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2026-05-23T00:14:21.074Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Xverbosegclog 

[2026-05-23T00:16:55.674Z] TEST: java/util/logging/CheckZombieLockTest.java

[2026-05-23T00:16:55.680Z] STDERR:
[2026-05-23T00:16:55.680Z] WARNING: unable to delete/cleanup writable test directory: /tmp/writable-lockfile-dir
[2026-05-23T00:16:55.680Z] java.lang.RuntimeException: Unexpected lock files found: []
[2026-05-23T00:16:55.680Z] 	/tmp/writable-lockfile-dir/log.log.lck should not have been reused
[2026-05-23T00:16:55.680Z] 	at CheckZombieLockTest.testFileHandlerReuse(CheckZombieLockTest.java:257)
[2026-05-23T00:16:55.680Z] 	at CheckZombieLockTest.runTests(CheckZombieLockTest.java:105)
[2026-05-23T00:16:55.680Z] 	at CheckZombieLockTest.main(CheckZombieLockTest.java:78)
```
