### ISSUE TITLE
JDK8 JIT Server : MauveMultiThreadLoadTest_special_19 NPE at gnu.testlet.java.lang.Thread.contextClassLoader.test(contextClassLoader.java:41)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9190]
Failure link
------------

From an internal build `Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly/251`:
```
00:26:37  openjdk version "1.8.0_252-internal"
00:26:37  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_04_07_21_42-b00)
00:26:37  Eclipse OpenJ9 VM (build ibm_sdk-8e755544e4, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200407_43 (JIT enabled, AOT enabled)
00:26:37  OpenJ9   - 8e755544e4
00:26:37  OMR      - 40bc70e5a
00:26:37  JCL      - 61d22079a86 based on jdk8u252-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  01:42:39.694 - Completed 38.8%. Number of tests started=1095458 (+156844)
LT  01:42:54.608 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
LT  01:42:54.609 - Test failed
LT    Failure num.  = 1
LT    Test number   = 2691
LT    Test details  = 'Mauve[gnu.testlet.java.lang.Thread.contextClassLoader]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.lang.NullPointerException
LT  	at gnu.testlet.java.lang.Thread.contextClassLoader.test(contextClassLoader.java:41)
LT  	at sun.reflect.GeneratedMethodAccessor1088.invoke(Unknown Source)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:821)
LT  <<<

MauveMultiThreadLoadTest_special_19_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/mauveLoadTest&PLATFORM=x86-64_linux&TARGET=MauveMultiThreadLoadTest_special_19

**Comment by pshipton** [comment]
@mpirvu

**Comment by a7ehuo** [comment]
Tried to run `MauveMultiThreadLoadTest_special_19` `30` times in [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7814/), all passed.

```
19:05:24  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
19:05:24  openjdk version "1.8.0_262-internal"
19:05:24  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_08_16_46-b00)
19:05:24  Eclipse OpenJ9 VM (build master-f9e5eed21, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200508_1448 (JIT enabled, AOT enabled)
19:05:24  OpenJ9   - f9e5eed21
19:05:24  OMR      - 1404a2722
19:05:24  JCL      - d0099f2c689 based on jdk8u262-b01)
```

**Comment by mpirvu** [comment]
It may be that this issue is very intermittent.
Let's do another batch of 30 and if that passes too, we'll close the issue.

**Comment by a7ehuo** [comment]
Ran `MauveMultiThreadLoadTest_special_19` `50` times in [Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7838/tapResults/) all passed.

```
openjdk version "1.8.0_262-internal"
OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_11_10_14-b00)
Eclipse OpenJ9 VM (build master-7339cb622, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200511_1451 (JIT enabled, AOT enabled)
OpenJ9   - 7339cb622
OMR      - cd259de5a
JCL      - d0099f2c689 based on jdk8u262-b01)
```

**Comment by mpirvu** [comment]
Based on the results above I think we can close this one and re-open if needed.
