### ISSUE TITLE
gcPolicyNogcTest_0 AfterTest AssertionError: expected [true] but found [false]

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9198]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/336
gcPolicyNogcTest_0
```
===============================================
Running test gcPolicyNogcTest_0 ...
===============================================
gcPolicyNogcTest_0 Start Time: Wed Apr  8 23:55:42 2020 Epoch Time (ms): 1586404542561
variation: -Xgcpolicy:nogc -Xms128m -Xmx1G -verbose:gc
JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:nogc -Xms128m -Xmx1G -verbose:gc 

<?xml version="1.0" ?>

<verbosegc xmlns="http://www.ibm.com/j9/verbosegc" version="e0efeed4d_CMPRSS">

<initialized id="1" timestamp="2020-04-08T23:55:42.705">
  <attribute name="gcPolicy" value="-Xgcpolicy:nogc" />
  <attribute name="maxHeapSize" value="0x40000000" />
  <attribute name="initialHeapSize" value="0x8000000" />
  <attribute name="compressedRefs" value="true" />
  <attribute name="compressedRefsDisplacement" value="0x0" />
  <attribute name="compressedRefsShift" value="0x0" />
  <attribute name="pageSize" value="0x1000" />
  <attribute name="pageType" value="not used" />
  <attribute name="requestedPageSize" value="0x1000" />
  <attribute name="requestedPageType" value="not used" />
  <attribute name="gcthreads" value="1" />
  <attribute name="packetListSplit" value="1" />
  <attribute name="cacheListSplit" value="1" />
  <attribute name="splitFreeListSplitAmount" value="1" />
  <attribute name="numaNodes" value="0" />
  <system>
    <attribute name="physicalMemory" value="8389656576" />
    <attribute name="numCPUs" value="4" />
    <attribute name="architecture" value="amd64" />
    <attribute name="os" value="Linux" />
    <attribute name="osVersion" value="2.6.32-754.27.1.el6.x86_64" />
  </system>
  <vmargs>
    <vmarg name="-Xoptionsfile=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre/l..." />
    <vmarg name="-Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword..." />
    <vmarg name="-Xjcl:jclse29" />
    <vmarg name="-Dcom.ibm.oti.vm.bootstrap.library.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openj..." />
    <vmarg name="-Dsun.boot.library.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-i..." />
    <vmarg name="-Djava.library.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image..." />
    <vmarg name="-Djava.home=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre" />
    <vmarg name="-Djava.ext.dirs=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre..." />
    <vmarg name="-Duser.dir=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_1586..." />
    <vmarg name="-Djava.class.path=." />
    <vmarg name="-Xcompressedrefs" />
    <vmarg name="-Xgcpolicy:nogc" />
    <vmarg name="-Xms128m" />
    <vmarg name="-Xmx1G" />
    <vmarg name="-verbose:gc" />
    <vmarg name="-Djava.class.path=/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdk-tests/TKG/../../jvm..." />
    <vmarg name="-Dsun.java.command=org.testng.TestNG -d /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openj..." />
    <vmarg name="-Dsun.java.launcher=SUN_STANDARD" />
    <vmarg name="-Dsun.java.launcher.pid=32036" />
  </vmargs>
</initialized>

[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

FAILED CONFIGURATION: @AfterTest afterTest
                      remove gc and memory notifications
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.nogc.TestGCPolicyNogc.afterTest(TestGCPolicyNogc.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:725)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by pshipton** [comment]
3x grinder https://ci.eclipse.org/openj9/job/Grinder/763/

**Comment by dmitripivkine** [comment]
@LinHu2016 FYI

**Comment by LinHu2016** [comment]
@dmitripivkine the assert is for verifying the allocation passed the threshold, gc has been triggered and heap is nothing change after "gc", might be the "last gc" has been triggered(I mean gc after allocation passed  the threshold). I will debug it later

**Comment by dmitripivkine** [comment]
If we compare failed job with runs in grinder the it has never reached heap expansion event.

**Comment by dmitripivkine** [comment]
I believe this was some kind of infrastructural issue. As a result there was no GC verbose log output detected except very first `<initialized>` pragma. And test has failed because can not find any success condition. Any way, if there was a problem with JVM we can not investigate it any way as far as no results stored. And this problem was unrelated with test functionality. Because it never happen again I am closing this item. Please free reopen if you think different
