### ISSUE TITLE
TestIBMJlmRemoteClassAuth jdk11 AArch64 failure: javax.crypto.AEADBadTagException: Tag mismatch!

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#9261]
Seen on AArch64 jdk11.0.7-ea+10 build:
23:27:27 Run /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java -version
23:27:27 openjdk version "11.0.7-ea" 2020-04-14
23:27:27 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7-ea+10)
23:27:27 Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux aarch64-64-Bit Compressed References 20200415_284 (JIT enabled, AOT enabled)
23:27:27 OpenJ9 - 05fa2d3
23:27:27 OMR - d4365f371
23:27:27 JCL - 534ae1c6d8 based on jdk-11.0.7+10)

Failure link: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/83
TestIBMJlmRemoteClassAuth_0

Output around failing test:
```
00:18:36  STF 23:18:36.372 - 
00:18:36  STF 23:18:36.372 - +------ Step 5 - Wait for the processes to complete
00:18:36  STF 23:18:36.372 - | Wait for processes to meet expectations
00:18:36  STF 23:18:36.372 - |   Processes: [LT1, CL1]
00:18:36  STF 23:18:36.372 - |
00:18:36  STF 23:18:36.372 - Monitoring processes: CL1 LT1
00:18:37  CL1 j> 2020/04/15 23:18:37.080 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
00:18:44  CL1 j> 2020/04/15 23:18:42.950 Monitored VM not ready at Apr 15, 2020, 11:18:42 PM (attempt 0).
00:18:44  CL1 j> 2020/04/15 23:18:42.952 Wait 5 secs and trying again...
00:18:45  CL1 j> 2020/04/15 23:18:45.508 Connection established!
00:18:46  CL1 j> 2020/04/15 23:18:45.731 Problem setting IBM extensions flag
00:18:46  CL1 stderr java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is: 
00:18:46  CL1 stderr 	javax.net.ssl.SSLException: Tag mismatch!
00:18:46  CL1 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:254)
00:18:46  CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
00:18:46  CL1 stderr 	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
00:18:46  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.isInstanceOf(Unknown Source)
00:18:46  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.isInstanceOf(RMIConnector.java:1101)
00:18:46  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:651)
00:18:46  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:611)
00:18:46  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.setIfIBM(ServerConnector.java:235)
00:18:46  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getSecureServerConnection(ServerConnector.java:208)
00:18:46  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:81)
00:18:46  CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:68)
00:18:46  CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:84)
00:18:46  CL1 stderr Caused by: javax.net.ssl.SSLException: Tag mismatch!
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1147)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1117)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
00:18:46  CL1 stderr 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
00:18:46  CL1 stderr 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
00:18:46  CL1 stderr 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
00:18:46  CL1 stderr 	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:240)
00:18:46  CL1 stderr 	... 11 more
00:18:46  CL1 stderr Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
00:18:46  CL1 stderr 	at java.base/com.sun.crypto.provider.NativeGaloisCounterMode.decryptFinal(NativeGaloisCounterMode.java:454)
00:18:46  CL1 stderr 	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1177)
00:18:46  CL1 stderr 	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1114)
00:18:46  CL1 stderr 	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:1002)
00:18:46  CL1 stderr 	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
00:18:46  CL1 stderr 	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
00:18:46  CL1 stderr 	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
00:18:46  CL1 stderr 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1903)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
00:18:46  CL1 stderr 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
00:18:46  CL1 stderr 	... 18 more
00:18:46  CL1 j> 2020/04/15 23:18:45.965 Starting to write data
00:18:46  CL1 j> 2020/04/15 23:18:46.255 Exiting as JVM we are connected to has finished
00:18:46  CL1 stderr Exception in thread "main" java.lang.AssertionError: Exiting as JVM we are connected to has finished
00:18:46  CL1 stderr 	at org.junit.Assert.fail(Assert.java:88)
00:18:46  CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:138)
00:18:46  CL1 stderr 	at net.openj9.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:97)
00:18:46  STF 23:18:46.355 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
00:18:46  STF 23:18:46.356 - Monitoring Report Summary:
00:18:46  STF 23:18:46.356 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
00:18:46  STF 23:18:46.356 -   o Process LT1 is still running as expected
00:18:46  STF 23:18:46.357 - Killing processes: CL1 LT1
00:18:57  STF 23:18:57.363 -   o Process LT1 killed
00:18:57  STF 23:18:57.363 -   o Process CL1 is not running
00:18:57  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/openjdk-tests/TKG/../TKG/test_output_15869906742995/TestIBMJlmRemoteClassAuth_0/20200415-231830-TestIBMJlmRemoteClassAuth/execute.pl line 173.
00:18:57  STF 23:18:57.560 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
One way to rerun test:
```
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=aarch64_linux_xl&TARGET=TestIBMJlmRemoteClassAuth_0
```

**Comment by knn-k** [comment]
It is very likely this is the same as #9046 and #9047.

**Comment by pshipton** [comment]
Closing as a dup.
