### ISSUE TITLE
Problem with aix71-p8-6 setup?

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9312]
I've seen this a couple of times. I'll disable aix71-p8-6 for now.
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64_aix_OMR/575
```
java.lang.ClassNotFoundException: hudson.EnvVars$GetEnvVars
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:367)
	at java.io.ClassCache$FutureValue.get(ClassCache.java:187)
	at java.io.ClassCache.get(ClassCache.java:158)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:788)
	at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:138)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1969)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2143)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1674)
	at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:515)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:291)
	at hudson.remoting.UserRequest.perform(UserRequest.java:190)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to aix71-p8-6
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.EnvVars.getRemote(EnvVars.java:428)
		at hudson.model.Computer.getEnvironment(Computer.java:1189)
		at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:807)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: java.lang.ClassNotFoundException: Failed to deserialize the Callable object. Perhaps you needed to implement DelegatingCallable?
	at hudson.remoting.UserRequest.perform(UserRequest.java:192)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:811)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Wed Apr 08 11:35:28 EDT 2020 by Thread[Ping thread for channel hudson.remoting.Channel@6a438b39:aix71-p8-6,5,main] [id=813]
		at hudson.model.Computer.recordTermination(Computer.java:224)
		at hudson.model.Computer.disconnect(Computer.java:486)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:750)
		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:198)
		at hudson.remoting.PingThread.ping(PingThread.java:134)
		at hudson.remoting.PingThread.run(PingThread.java:90)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Sun Apr 12 12:35:52 EDT 2020 by Thread[Ping thread for channel hudson.remoting.Channel@328a755e:aix71-p8-6,5,main] [id=10179]
		at hudson.model.Computer.recordTermination(Computer.java:224)
		at hudson.model.Computer.disconnect(Computer.java:486)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:750)
		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:198)
		at hudson.remoting.PingThread.ping(PingThread.java:134)
		at <unknown class>.<unknown method>(Unknown Source)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Sat Apr 18 00:21:58 EDT 2020 by Thread[Ping thread for channel hudson.remoting.Channel@9b61e74e:aix71-p8-6,5,main] [id=167374]
		at hudson.model.Computer.recordTermination(Computer.java:224)
		at hudson.model.Computer.disconnect(Computer.java:486)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:750)
		at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:198)
		at hudson.remoting.PingThread.ping(PingThread.java:134)
		at hudson.remoting.PingThread.run(PingThread.java:90)
Caused: java.io.IOException: Remote call on aix71-p8-6 failed
	at hudson.remoting.Channel.call(Channel.java:961)
	at hudson.EnvVars.getRemote(EnvVars.java:428)
	at hudson.model.Computer.getEnvironment(Computer.java:1189)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:807)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
That one was disabled last night when I was bringing them back online but I had assumed it was the old `#6`. That being said, I don't really know why it's giving that error but I don't think it's related to our setup. At least not known. I would guess the slave java is the same version as the other aix machines?

**Comment by jdekonin** [comment]
Yes, they were all built with an identical set of packages.

I rebooted the machine.  It could be related to me resetting the date/time a few days ago.  I believe I disconnected them all from jenkins at the time but maybe some didn't disconnect/reconnect cleanly??

**Comment by pshipton** [comment]
A ginder on the machine seems to be working fine.
