### ISSUE TITLE
UNB xlinux cent6 machines problems uploading to OSU

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9393]
We saw this starting last night trying to upload test results, then early this morning uploading OMR builds, and again just now uploading OMR builds. Seems to occur on cent6 machines. Maybe we should reboot them all. Last night and this morning we saw it on 1, 3, 5, 6.

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_cm_OMR/574 - cent6-x64-3
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_OMR/571/ - cent6-x64-6
```
16:45:53  Uploading to 'osu'...
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] retry
[Pipeline] {
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
16:45:59  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_OMR/571/OpenJ9-JDK11-x86-64_linux-20200428-200210.tar.gz
16:45:59  Error occurred for request GET /artifactory/api/system/version HTTP/1.1: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
16:45:59  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_OMR/571/OpenJ9-JDK11-x86-64_linux-20200428-200210.tar.gz;build.parentNumber=1870;build.parentName=Pipeline_Build_Test_JDK11_x86-64_linux;build.buildIdentifier=OMR-Acceptance;build.timestamp=1588104120224;build.name=Build_JDK11_x86-64_linux_OMR;build.number=571 HTTP/1.1: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty.
16:45:59  [consumer_0] An exception occurred during execution:
16:45:59  java.lang.RuntimeException: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
16:45:59  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
16:45:59  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
16:45:59  	at java.lang.Thread.run(Thread.java:748)
16:45:59  Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
16:45:59  	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
16:45:59  	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
16:45:59  	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1903)
16:45:59  	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1886)
16:45:59  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1402)
16:45:59  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
16:45:59  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
16:45:59  	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
16:45:59  	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
16:45:59  	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
16:45:59  	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
16:45:59  	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
16:45:59  	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
16:45:59  	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
16:45:59  	at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:85)
16:45:59  	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
16:45:59  	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
16:45:59  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
16:45:59  	at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:122)
16:45:59  	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:221)
16:45:59  	at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:217)
16:45:59  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:689)
16:45:59  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:376)
16:45:59  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:364)
16:45:59  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
16:45:59  	... 2 more
16:45:59  Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
16:45:59  	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:104)
16:45:59  	at sun.security.validator.Validator.getInstance(Validator.java:181)
16:45:59  	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:318)
16:45:59  	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:179)
16:45:59  	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:193)
16:45:59  	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
16:45:59  	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
16:45:59  	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
16:45:59  	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
16:45:59  	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
16:45:59  	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
16:45:59  	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
16:45:59  	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
16:45:59  	... 22 more
16:45:59  Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
16:45:59  	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
16:45:59  	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
16:45:59  	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
16:45:59  	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
16:45:59  	... 34 more
```

**Comment by pshipton** [comment]
Joe rebooted 1-3, 5, 7. 4 and 6 are busy but will be rebooted later. They've been taken offline.
The failed jobs are restarted, we'll see if they can upload now.

**Comment by pshipton** [comment]
Seems all the restarted jobs passed. 4 & 6 are pending restart, but I'll go ahead and close this.

**Comment by pshipton** [comment]
This is still occurring.
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_cm_Nightly/358 - cent6-x64-2
https://ci.eclipse.org/openj9/job/Build_JDK14_x86-64_linux_Nightly/82 - cent6-x64-4

**Comment by pshipton** [comment]
Failures to upload test results:
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/342 - cent6-x64-2

**Comment by pshipton** [comment]
I've disabled cent6-x64-2 and cent6-x64-4 temporarily and restarted the failed OMR jobs.

**Comment by AdamBrousseau** [comment]
Both 2,4 seem ok right now
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_cm_Personal/87
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_linux_cm_Personal/2

**Comment by pshipton** [comment]
Didn't see any problem in the builds last night, not sure if the machines were enabled or not. I'll reopen if any further problems are seen.

**Comment by AdamBrousseau** [comment]
Not enabled but I can add back the labels before tonight's builds.

**Comment by pshipton** [comment]
I've added the labels back, I'll keep an eye out for problems.
