### ISSUE TITLE
win2012r2-x86-5 no space left on device to create build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9397]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Nightly/373
```
00:27:24  c:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\jdk\src\share\classes\java\util\HashMap.java:1521: error: error while writing KeySpliterator: There is not enough space on the disk
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
```
jenkins@oj9-win2012r2-5 /cygdrive/c/Users/jenkins/workspace
$ du -sch *
0	Build_JDK11_x86-64_windows_Personal
0	Build_JDK11_x86-64_windows_Personal@tmp
7.0G	Build_JDK14_x86-64_windows_Nightly
4.4M	Build_JDK14_x86-64_windows_Nightly@tmp
21M	Build_JDK8_x86-32_windows_Nightly
0	Build_JDK8_x86-32_windows_Nightly@tmp
21M	Build_JDK8_x86-64_windows_Nightly
0	Build_JDK8_x86-64_windows_Nightly@tmp
0	Cleanup-Nodes
0	Cleanup-Nodes@tmp
0	Sanitize-Nodes
0	Sanitize-Nodes@tmp
885M	Test_openjdk8_j9_extended.system_x86-32_windows_Nightly
769K	Test_openjdk8_j9_extended.system_x86-32_windows_Nightly@tmp
4.0K	Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR
0	Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR@tmp
7.9G	total

jenkins@oj9-win2012r2-5 /cygdrive/c/Users/jenkins/workspace
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
C:/cygwin64     100G   97G  3.3G  97% /
D:              2.0G   32M  2.0G   2% /cygdrive/d
```
https://ci.eclipse.org/openj9/job/Build_JDK14_x86-64_windows_Nightly/80/console
```
22:38:28  /cygdrive/c/Users/jenkins/workspace/Build_JDK14_x86-64_windows_Nightly/build/windows-x86_64-server-release/configure-support/bin/fixpath.exe -c   /cygdrive/c/progra~2/mib055~1/2017/commun~1/vc/tools/msvc/1416~1.270/bin/hostx86/x64/cl -DOPENJ9_BUILD /Ox -DWIN32 -D_WIN32 -DOMR_OS_WINDOWS -D_AMD64_=1 -DWIN64 -D_WIN64 -DJ9HAMMER -FdRealtimeMarkTask.pdb -D_CRT_SECURE_NO_WARNINGS -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -D_WIN32_WINDOWS=0x0601 -D_MT -D_WINSOCKAPI_ -Zm400 -W3 -Zi -MD -D_DLL -WX  -I. -I../include -I../oti -I../gc_base -I../omr/gc/base -I../omr/gc/base/segregated -I../omr/gc/base/standard -I../gc_structs -I../omr/gc/structs -I../gc_stats -I../omr/gc/stats -I../gc_include -I../omr/gc/include -I../gc_glue_java -I../nls -I../omr/include_core  /w34189  -DTR_HOST_X86 -c RealtimeMarkTask.cpp
22:38:28  RealtimeAccessBarrier.cpp
22:38:28  RealtimeGC.cpp
22:38:28  RealtimeMarkTask.cpp
Creating placeholder flownodes because failed loading originals.
java.io.IOException: Tried to load head FlowNodes for execution Owner[Build_JDK14_x86-64_windows_Nightly/80:Build_JDK14_x86-64_windows_Nightly #80] but FlowNode was not found in storage for head id:FlowNodeId 1:72
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:679)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:716)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:665)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:529)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
	at hudson.model.RunMap.getById(RunMap.java:205)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:902)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:913)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
	at jenkins.model.Jenkins.<init>(Jenkins.java:1022)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Finished: FAILURE
```
Not sure why the cleanup build didn't catch this.
9:00pm cleanup didn't hit that machine. May have been offline from the sanitize job? Also Jenkins restarted during the cleanup build so that doesn't help.
2:00pm cleanup, win-5 was marked offline for VS2017 upgrade
11:00am seems like it ran on the machine. Obviously it didn't work.

Rm'd the directories.

**Comment by pshipton** [comment]
Similarly win2012r2-x86-3
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_OMR/579/

**Comment by pshipton** [comment]
I assume the cleanup efforts succeeded, there haven't been any more space related problems in the builds.
