### ISSUE TITLE
Windows ProcessBuilder/Basic.java '1'< not equal to '0'

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9398]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/20
java/lang/ProcessBuilder/Basic.java#id0.Basic_id0 
win2012r2-x86-3
```
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:107)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1742)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:108)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1742)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>''< not equal to 'C:\Windows'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.realMain(Basic.java:1742)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:107)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1746)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:108)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1746)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>''< not equal to 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_15881410284136\jdk_lang_j9_0\work\scratch\2'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.realMain(Basic.java:1746)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:107)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1738)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>'1'< not equal to '0'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.commandOutput(Basic.java:108)
	at Basic.commandOutput(Basic.java:118)
	at Basic.javaChildOutput(Basic.java:563)
	at Basic.pwdInChild(Basic.java:579)
	at Basic.realMain(Basic.java:1738)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
>''< not equal to 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_15881410284136\jdk_lang_j9_0\work\scratch\2'
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.fail(Basic.java:2741)
	at Basic.equal(Basic.java:2747)
	at Basic.realMain(Basic.java:1738)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.Throwable
	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
	at Basic.fail(Basic.java:2740)
	at Basic.check(Basic.java:2743)
	at Basic.realMain(Basic.java:1789)
	at Basic.main(Basic.java:2750)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:2752)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
```

**Comment by pshipton** [comment]
See also #9399 and #9400. Suspect a disk space issue on win2012r2-x86-3.

**Comment by pshipton** [comment]
This hasn't re-occurred since we made more space available on the machines.
