### ISSUE TITLE
Windows ProcessHandle/TreeTest.java not all children have been started

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9399]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/20
java/lang/ProcessHandle/TreeTest.java
win2012r2-x86-3
```
02:30:53  WARNING: not all children have been started. Can't complete test.
02:30:53           You can try to increase the timeout or
02:30:53           you can try to use a faster VM (i.e. not a debug version).
02:30:53   descendants:  [7072]
02:30:53  test TreeTest.test2(): failure
02:30:53  java.lang.AssertionError: Child should be alive: 6536 expected [true] but found [false]
02:30:53  	at org.testng.Assert.fail(Assert.java:94)
02:30:53  	at org.testng.Assert.failNotEquals(Assert.java:496)
02:30:53  	at org.testng.Assert.assertEquals(Assert.java:125)
02:30:53  	at org.testng.Assert.assertEquals(Assert.java:288)
02:30:53  	at TreeTest.lambda$test2$12(TreeTest.java:219)
02:30:53  	at TreeTest$$Lambda$79/00000000AC8931F0.accept(Unknown Source)
02:30:53  	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
02:30:53  	at TreeTest.test2(TreeTest.java:218)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:30:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:30:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:30:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
02:30:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
02:30:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
02:30:53  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
02:30:53  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:30:53  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
02:30:53  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
02:30:53  	at org.testng.TestRunner.run(TestRunner.java:623)
02:30:53  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
02:30:53  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
02:30:53  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
02:30:53  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
02:30:53  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:30:53  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
02:30:53  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
02:30:53  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
02:30:53  	at org.testng.TestNG.run(TestNG.java:1018)
02:30:53  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
02:30:53  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:30:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:30:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:30:53  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:30:53  	at java.base/java.lang.Thread.run(Thread.java:834)
02:30:53   p1: 6236
02:30:53  test TreeTest.test3(): success
02:30:53      Parent     Child  Info
02:30:53          null,       0, []
02:30:53          null,       4, []
02:30:53          null,     472, []
02:30:53          null,     484, []
02:30:53          null,     500, []
02:30:53          null,     756, []
02:30:53          null,     792, []
02:30:53          null,     804, []
02:30:53          null,     860, []
02:30:53          null,     868, []
02:30:53          null,     876, []
02:30:53          null,     904, []
02:30:53          null,     964, []
02:30:53          null,     972, []
02:30:53          null,    1004, []
02:30:53          null,    1036, []
02:30:53          null,    1060, []
02:30:53          null,    1152, []
02:30:53          null,    1364, []
02:30:53          null,    1412, []
02:30:53          null,    1500, []
02:30:53          null,    1532, []
02:30:53          null,    1564, []
02:30:53          null,    1708, []
02:30:53          null,    1784, []
02:30:53          null,    1816, []
02:30:53          null,    1868, []
02:30:53          null,    1908, []
02:30:53          null,    1924, []
02:30:53          null,    1932, []
02:30:53          null,    1948, []
02:30:53          null,    2028, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\make.exe, startTime: Optional[2020-04-29T06:17:00.489Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    2076, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:00.349Z], totalTime: Optional[PT0.234375S]]
02:30:53          null,    2180, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\make.exe, startTime: Optional[2020-04-29T06:17:08.817Z], totalTime: Optional[PT0.03125S]]
02:30:53          null,    2184, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:08.942Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    2192, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:08.802Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    2256, []
02:30:53          null,    2300, []
02:30:53          null,    2388, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\tee.exe, startTime: Optional[2020-04-29T06:17:11.427Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    2648, []
02:30:53          null,    2888, []
02:30:53          null,    3044, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:00.396Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    3108, []
02:30:53          null,    3668, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\sleep.exe, startTime: Optional[2020-04-29T06:30:45.427Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    3816, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:00.411Z], totalTime: Optional[PT0.03125S]]
02:30:53          null,    4684, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\make.exe, startTime: Optional[2020-04-29T06:17:08.958Z], totalTime: Optional[PT0.03125S]]
02:30:53          null,    4812, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:11.411Z], totalTime: Optional[PT0S]]
02:30:53          null,    5016, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:00.442Z], totalTime: Optional[PT0.03125S]]
02:30:53          null,    5904, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\make.exe, startTime: Optional[2020-04-29T06:17:07.942Z], totalTime: Optional[PT0.0625S]]
02:30:53          null,    6020, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T02:40:15.030Z], totalTime: Optional[PT0.015625S]]
02:30:53          null,    6920, []
02:30:53           180,    5216, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:22:18.896Z], totalTime: Optional[PT0.015625S]]
02:30:53          2056,    6952, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:22:45.880Z], totalTime: Optional[PT0S]]
02:30:53          2056,    7072, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:22:46.786Z], totalTime: Optional[PT1S]]
02:30:53          2172,    5348, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:18:47.536Z], totalTime: Optional[PT0.015625S]]
02:30:53          3044,     508, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:00.396Z], totalTime: Optional[PT0.09375S]]
02:30:53          3600,    4652, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:28.708Z], totalTime: Optional[PT0.015625S]]
02:30:53          3932,    2280, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:25.005Z], totalTime: Optional[PT0S]]
02:30:53          3936,    5112, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:20.927Z], totalTime: Optional[PT0S]]
02:30:53          4100,    4000, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:22:22.708Z], totalTime: Optional[PT0S]]
02:30:53          4344,    4204, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:22.583Z], totalTime: Optional[PT0.015625S]]
02:30:53          4460,    1936, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:33.567Z], totalTime: Optional[PT0.015625S]]
02:30:53          4524,     180, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:22:18.896Z], totalTime: Optional[PT6.0625S]]
02:30:53          4524,    2172, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:18:47.536Z], totalTime: Optional[PT1.90625S]]
02:30:53          4524,    3600, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:28.708Z], totalTime: Optional[PT28.796875S]]
02:30:53          4524,    3932, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:25.005Z], totalTime: Optional[PT2M8.171875S]]
02:30:53          4524,    3936, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:20.927Z], totalTime: Optional[PT1M21.5625S]]
02:30:53          4524,    4100, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:22:22.708Z], totalTime: Optional[PT2.1875S]]
02:30:53          4524,    4344, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:22.583Z], totalTime: Optional[PT1M1.40625S]]
02:30:53          4524,    4460, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:33.567Z], totalTime: Optional[PT15.640625S]]
02:30:53          4524,    4580, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:25.833Z], totalTime: Optional[PT1M21.484375S]]
02:30:53          4524,    5148, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:18:50.130Z], totalTime: Optional[PT2.359375S]]
02:30:53          4524,    5332, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:27.661Z], totalTime: Optional[PT42.921875S]]
02:30:53          4524,    5408, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:28:11.865Z], totalTime: Optional[PT5.3125S]]
02:30:53          4524,    5504, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:24.208Z], totalTime: Optional[PT18.25S]]
02:30:53          4524,    5612, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:28:15.552Z], totalTime: Optional[PT2.234375S]]
02:30:53          4524,    5920, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:23:24.833Z], totalTime: Optional[PT2S]]
02:30:53          4524,    6672, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:22:44.036Z], totalTime: Optional[PT6.609375S]]
02:30:53          4524,    6888, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:28:07.521Z], totalTime: Optional[PT10.109375S]]
02:30:53          4580,    3916, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:25.833Z], totalTime: Optional[PT0.03125S]]
02:30:53          4704,    4524, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:17:11.458Z], totalTime: Optional[PT1M7.703125S]]
02:30:53          4812,    5900, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:11.411Z], totalTime: Optional[PT0.015625S]]
02:30:53          5148,    2216, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:18:50.130Z], totalTime: Optional[PT0S]]
02:30:53          5332,    5704, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:27.661Z], totalTime: Optional[PT0.0625S]]
02:30:53          5408,    3268, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:28:11.865Z], totalTime: Optional[PT0S]]
02:30:53          5504,    4144, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:17:24.208Z], totalTime: Optional[PT0.015625S]]
02:30:53          5612,    1760, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:28:15.568Z], totalTime: Optional[PT0S]]
02:30:53          5900,    4704, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\cygwin64\bin\bash.exe, startTime: Optional[2020-04-29T06:17:11.442Z], totalTime: Optional[PT0.015625S]]
02:30:53          5920,    7056, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:23:24.833Z], totalTime: Optional[PT0S]]
02:30:53          6020,    3340, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Program Files\Java\jdk8u202-b08\bin\java.exe, startTime: Optional[2020-04-29T02:40:16.951Z], totalTime: Optional[PT2M44.28125S]]
02:30:53          6672,    2056, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:22:45.864Z], totalTime: Optional[PT0.9375S]]
02:30:53          6672,    6668, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:22:44.036Z], totalTime: Optional[PT0.015625S]]
02:30:53          6888,    6340, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:28:07.521Z], totalTime: Optional[PT0S]]
02:30:53          7072,    6184, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Windows\System32\conhost.exe, startTime: Optional[2020-04-29T06:22:46.802Z], totalTime: Optional[PT0S]]
02:30:53  test TreeTest.test4(): success
02:30:53  Spawning 2 x 2 x 2 processes, pid: 6748
02:30:53  Duration: PT2.1250037S
02:30:53  Process Cleanup: pid 6304, alive: true; parent: Optional[744], [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.974Z], totalTime: Optional[PT1.125S]]
02:30:53  Process Cleanup: pid 2884, alive: true; parent: Optional[4244], [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.990Z], totalTime: Optional[PT1.203125S]]
02:30:53  Process Cleanup: pid 6532, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.787Z], totalTime: Optional[PT0.140625S]]
02:30:53  Process Cleanup: pid 6312, alive: true; parent: Optional[4244], [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.974Z], totalTime: Optional[PT1.109375S]]
02:30:53  Process Cleanup: pid 744, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.412Z], totalTime: Optional[PT0.75S]]
02:30:53  Process Cleanup: pid 6120, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.974Z], totalTime: Optional[PT0.03125S]]
02:30:53  Process Cleanup: pid 6796, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.865Z], totalTime: Optional[PT0.046875S]]
02:30:53  Process Cleanup: pid 3948, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.927Z], totalTime: Optional[PT0.0625S]]
02:30:53  Process Cleanup: pid 3312, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.990Z], totalTime: Optional[PT1.15625S]]
02:30:53  Process Cleanup: pid 6576, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.849Z], totalTime: Optional[PT0.125S]]
02:30:53  Process Cleanup: pid 1328, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.896Z], totalTime: Optional[PT0.078125S]]
02:30:53  Process Cleanup: pid 4244, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:48.396Z], totalTime: Optional[PT0.734375S]]
02:30:53  Process Cleanup: pid 5368, alive: true; parent: Optional.empty, [user: Optional[OJ9-WIN2012R2-3\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-04-29T06:30:49.927Z], totalTime: Optional[PT0.0625S]]
02:30:53  test TreeTest.test5(): failure
02:30:53  java.lang.AssertionError: expected at least 14, actual: 13 expected [true] but found [false]
02:30:53  	at org.testng.Assert.fail(Assert.java:94)
02:30:53  	at org.testng.Assert.failNotEquals(Assert.java:496)
02:30:53  	at org.testng.Assert.assertTrue(Assert.java:42)
02:30:53  	at TreeTest.test5(TreeTest.java:451)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:30:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:30:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:30:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
02:30:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
02:30:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
02:30:53  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
02:30:53  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:30:53  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
02:30:53  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
02:30:53  	at org.testng.TestRunner.run(TestRunner.java:623)
02:30:53  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
02:30:53  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
02:30:53  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
02:30:53  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
02:30:53  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:30:53  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
02:30:53  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
02:30:53  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
02:30:53  	at org.testng.TestNG.run(TestNG.java:1018)
02:30:53  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
02:30:53  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:30:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:30:53  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:30:53  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:30:53  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
02:30:53  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pshipton** [comment]
See also #9398 and #9400. Suspect a disk space issue on win2012r2-x86-3.

**Comment by pshipton** [comment]
This hasn't re-occurred since we made more space available on the machines.
