### ISSUE TITLE
SharedCPEntryInvokerTests_0_FAILED : testInvokespecialInvokeinterface - Failed to redefine interface

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9434]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.functional_s390x_linux_xl_Nightly/63`:
```
22:55:54  openjdk version "11.0.8-internal" 2020-07-14
22:55:54  OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc.jenkins.BuildJDK11s390xlinuxxlNightly)
22:55:54  Eclipse OpenJ9 VM (build ibm_sdk-1a1ee6bf19, JRE 11 Linux s390x-64-Bit 20200502_71 (JIT enabled, AOT enabled)
22:55:54  OpenJ9   - 1a1ee6bf19
22:55:54  OMR      - 4e9428844
22:55:54  JCL      - 82fd27fc4c5 based on jdk-11.0.8+1)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
FAILED: testInvokespecialInvokeinterface
java.lang.AssertionError: Failed to redefine interface
	at org.testng.Assert.fail(Assert.java:96)
	at org.openj9.test.invoker.InvalidateSplitTableRetransformationTest.testInvokespecialInvokeinterface(InvalidateSplitTableRetransformationTest.java:272)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)

FAILED: testStaticSplitMutateOnStack
java.lang.AssertionError: Did not get expected value:  expected:<Dummy_V2.invokeStatic> but was:<Dummy_V1.invokeStatic>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.openj9.test.invoker.MutateOnStackSplitTableRetransformationTest.testStaticSplitMutateOnStack(MutateOnStackSplitTableRetransformationTest.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux_xl&TARGET=SharedCPEntryInvokerTests_0

**Comment by pshipton** [comment]
As with all the other failures reported today, this is possibly related to the addition of -Xfuture to the tests, although it can't be seen in the output shown here.

**Comment by pshipton** [comment]
Closing as some temporary hiccup adding `-Xfurture` https://github.com/eclipse/openj9/issues/9435#issuecomment-623649679, pls reopen if it still occurs.
