### ISSUE TITLE
JDK8 cmdLineTester_jvmtitests_2_FAILED : JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9439]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly/342`:
```
03:47:31  openjdk version "1.8.0_262-internal"
03:47:31  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_02_18_44-b00)
03:47:31  Eclipse OpenJ9 VM (build ibm_sdk-1a1ee6bf19, JRE 1.8.0 Windows Server 2016 x86-32-Bit 20200502_403 (JIT enabled, AOT enabled)
03:47:31  OpenJ9   - 1a1ee6bf19
03:47:31  OMR      - 4e9428844
03:47:31  JCL      - ed7c83cea53 based on jdk8u262-b01)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Testing: rnwr001
Test start time: 2020/05/03 01:16:58 Pacific Standard Time
Running command: "C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly/openjdkbinary/j2sdk-image\\bin\\java"  -Xjit -Xgcpolicy:gencon -Xshareclasses:cacheRetransformed,name=retransformenabled -Xnocompressedrefs -Xfuture -Xdump    -agentlib:jvmtitest=test:rnwr001 -cp "C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly/openjdk-tests///..//jvmtest\functional\cmdLineTests\jvmtitests\jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 31 milliseconds
Time spent executing: 1908 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/4]:	testRegisterNativesWithClassRetransformation
 [OUT] Pre retransformation: registered native method returned: 100	 PASS
 [OUT] Pre retransformation: instance method returned: 1	 PASS
 [OUT] Post retransformation: registered native method returned: 100	 PASS
 [OUT] Post retransformation: instance method returned: 2	 PASS
 [OUT] *** Test took 31 milliseconds
 [OUT] OK
 [OUT] 
 [OUT] *** Testing [2/4]:	testRegisterNativesWithInterfaceRetransformation1
 [OUT] Pre retransformation: registered native method returned: 100	 PASS
 [OUT] Pre retransformation: instance method returned: 1	 PASS
 [OUT] Post retransformation: registered native method returned: 100	 PASS
 [OUT] Post retransformation: instance method returned: 1	 PASS
 [OUT] *** Test took 16 milliseconds
 [OUT] OK
 [OUT] 
 [OUT] *** Testing [3/4]:	testRegisterNativesWithInterfaceRetransformation2
 [OUT] Pre retransformation: com.ibm.jvmti.tests.registerNativesWithRetransformation.rnwr001_Runner_V1.runTest2 returned: true	 PASS
 [OUT] Pre retransformation: com.ibm.jvmti.tests.registerNativesWithRetransformation.rnwr001_Runner_V1.runTest1 returned: true	 PASS
 [OUT] Post retransformation: com.ibm.jvmti.tests.registerNativesWithRetransformation.rnwr001_Runner_V1.runTest2 returned: true	 PASS
 [OUT] Post retransformation: com.ibm.jvmti.tests.registerNativesWithRetransformation.rnwr001_Runner_V1.runTest1 returned: true	 PASS
 [OUT] *** Test took 31 milliseconds
 [OUT] FAILED
 [OUT] 
 [OUT] *** Testing [4/4]:	testRegisterNativesWithSuperClassRetransformation
 [OUT] Pre retransformation: registered native method returned: 100	 PASS
 [OUT] Pre retransformation: instance method in super class returned: 1	 PASS
 [OUT] Pre retransformation: instance method in sub class returned: 1	 PASS
 [OUT] Post retransformation: registered native method returned: 100	 PASS
 [OUT] Post retransformation: instance method in super class returned: 1	 FAIL
 [OUT] Post retransformation: instance method in sub class returned: 1	 FAIL
 [OUT] *** Test took 16 milliseconds
 [OUT] FAILED
 [OUT] 
 [ERR] ERROR: Unexpected number of test methods in class com.ibm.jvmti.tests.registerNativesWithRetransformation.rnwr001_Runner_V1. Expected 3, found 2
 [ERR] ERROR: Expected "newMethod" to be present in the super class
 [ERR] exception thrown: 
 [ERR] type: 2type: 2type: 2type: 2type: 2	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 
 [ERR] com.ibm.jvmti.tests.util.AgentHardException: 
 [ERR] type: 2type: 2type: 2type: 2type: 2	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 	Error: 63  JVMTI_ERROR_UNSUPPORTED_REDEFINITION_METHOD_ADDED
 [ERR] 		RetransformClasses failed
 [ERR] 		Location:  -> [():0]
 [ERR] 
 [ERR] 	at com.ibm.jvmti.tests.util.ErrorControl.checkErrors(ErrorControl.java:71)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:87)
 [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
>> Success condition was not found: [Return code: 0]

cmdLineTester_jvmtitests_2_FAILED
```
For example, to rebuild the failed tests in =https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-32_windows&TARGET=cmdLineTester_jvmtitests_2

**Comment by pshipton** [comment]
Suspect this is related to `-Xfuture` being added to the tests. https://github.com/eclipse/openj9/issues/9435#issuecomment-623601635

**Comment by pshipton** [comment]
Closing as some temporary hiccup adding `-Xfurture` https://github.com/eclipse/openj9/issues/9435#issuecomment-623649679, pls reopen if it still occurs.
