### ISSUE TITLE
JDK8 testJITServer_1 : NPE at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9440]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/371`:
```
23:38:16  openjdk version "1.8.0_262-internal"
23:38:16  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_02_21_34-b00)
23:38:16  Eclipse OpenJ9 VM (build ibm_sdk-1a1ee6bf19, JRE 1.8.0 Linux amd64-64-Bit 20200502_397 (JIT enabled, AOT enabled)
23:38:16  OpenJ9   - 1a1ee6bf19
23:38:16  OMR      - 4e9428844
23:38:16  JCL      - ed7c83cea53 based on jdk8u262-b01)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Failed to properly start client, it terminated prematurely with exit value: 1
Dumping the contents of log file: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15884774801425/testJITServer_1/testServer.client.out
////////////////////////////////////////////////////////////////////////
//// JITServer is currently a technology preview. Its use is not yet supported
//// JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServer.client.jitverboselog.out
//// [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
//// Exception in thread "main" java.lang.NullPointerException
//// 	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
//// 	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1159)
//// 	at sun.misc.URLClassPath.getResource(URLClassPath.java:345)
//// 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1084)
//// 	at java.security.AccessController.doPrivileged(AccessController.java:770)
//// 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
//// 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
//// 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
//// 	at java.lang.ClassLoader.defineClassImpl(Native Method)
//// 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
//// 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
//// 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
//// 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
//// 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
//// 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
//// 	at java.security.AccessController.doPrivileged(AccessController.java:770)
//// 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
//// 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
//// 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
//// 	at java.lang.ClassLoader.defineClassImpl(Native Method)
//// 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
//// 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
//// 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
//// 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
//// 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
//// 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
//// 	at java.security.AccessController.doPrivileged(AccessController.java:770)
//// 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
//// 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
//// 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
//// 	at java.lang.ClassLoader.defineClassImpl(Native Method)
//// 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
//// 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
//// 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
//// 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
//// 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
//// 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
//// 	at java.security.AccessController.doPrivileged(AccessController.java:770)
//// 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
//// 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
//// 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
//// 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
//// 	at org.testng.TestNG.initializeDefaultListeners(TestNG.java:886)
//// 	at org.testng.TestNG.initializeEverything(TestNG.java:997)
//// 	at org.testng.TestNG.run(TestNG.java:1009)
//// 	at org.testng.TestNG.privateMain(TestNG.java:1354)
//// 	at org.testng.TestNG.main(TestNG.java:1323)
////////////////////////////////////////////////////////////////////////

testJITServer_1_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux_xl&TARGET=testJITServer_1

**Comment by pshipton** [comment]
@mpirvu

**Comment by dmitry-ten** [comment]
Probably the same underlying bug as #9197?

**Comment by EmanElsaban** [comment]
According to PR: #9828, the test testJITServer has been disabled for XL builds.
FYI: @mpirvu

**Comment by mpirvu** [comment]
Closing because we don't support XL builds with JITServer (JITServer is valuable in constrained environments)
