### ISSUE TITLE
GC Crash in ValueTypeTests 

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#9441]
Stack trace 1:

```
#14 0x00007fcafad86c98 in fixObjectIfClassDying (omrVMThread=0x1bb8380, region=0x7fcafc06f380, object=0x70556f450,
    userData=0x7fcb0211ebb8) at ../../gc_glue_java/GlobalCollectorDelegate.cpp:73
#15 0x00007fcafae27513 in MM_ParallelHeapWalker::allObjectsDoParallel (this=0x7fcafc036f30, env=<optimized out>,
    function=0x7fcafad86c90 <fixObjectIfClassDying(OMR_VMThread*, MM_HeapRegionDescriptor*, omrobjectptr_t, void*)>,
    userData=0x7fcb0211ebb8, walkFlags=<optimized out>) at ParallelHeapWalker.cpp:131
#16 0x00007fcafad60963 in MM_Dispatcher::run (this=0x7fcafc0354b0, env=0x7fcafc0370d8, task=0x7fcb0211ead0,
    newThreadCount=<optimized out>) at Dispatcher.cpp:96
#17 0x00007fcafae27230 in MM_ParallelHeapWalker::allObjectsDo (this=0x7fcafc036f30, env=0x7fcafc0370d8,
    function=0x7fcafad86c90 <fixObjectIfClassDying(OMR_VMThread*, MM_HeapRegionDescriptor*, omrobjectptr_t, void*)>,
    userData=0x7fcb0211ebb8, walkFlags=8, parallel=<optimized out>, prepareHeapForWalk=false) at ParallelHeapWalker.cpp:155
#18 0x00007fcafad90b7f in MM_ParallelGlobalGC::fixHeapForWalk (this=0x7fcafc035740, env=env@entry=0x7fcafc0370d8,
    walkFlags=walkFlags@entry=8, walkReason=walkReason@entry=1,
    walkFunction=walkFunction@entry=0x7fcafad86c90 <fixObjectIfClassDying(OMR_VMThread*, MM_HeapRegionDescriptor*, omrobjectptr_t, void*)>) at ParallelGlobalGC.cpp:1277
#19 0x00007fcafad87cf6 in MM_GlobalCollectorDelegate::masterThreadGarbageCollectFinished (this=this@entry=0x7fcafc035780,
    env=env@entry=0x7fcafc0370d8, compactedThisCycle=compactedThisCycle@entry=false)
    at ../../gc_glue_java/GlobalCollectorDelegate.cpp:218
#20 0x00007fcafad92b04 in MM_ParallelGlobalGC::masterThreadGarbageCollect (this=0x7fcafc035740, env=0x7fcafc0370d8,
    allocDescription=0x0, initMarkMap=<optimized out>, rebuildMarkBits=<optimized out>) at ParallelGlobalGC.cpp:526
#21 0x00007fcafad8f4f3 in MM_ParallelGlobalGC::internalGarbageCollect (this=<optimized out>, env=0x7fcafc0370d8,
    subSpace=<optimized out>, allocDescription=0x0) at ParallelGlobalGC.cpp:1231
#22 0x00007fcafad363f7 in MM_Collector::garbageCollect (this=0x7fcafc035740, env=0x7fcafc0370d8,
    callingSubSpace=0x7fcafc06ef60, allocateDescription=0x0, gcCode=<optimized out>, objectAllocationInterface=0x0,
    baseSubSpace=0x0, context=0x0) at Collector.cpp:499
#23 0x00007fcafad46b64 in MM_MemorySubSpace::systemGarbageCollect (this=0x7fcafc06ef60, env=0x7fcafc0370d8, gcCode=3)
    at MemorySubSpace.cpp:934
#24 0x00007fcafad46a6d in MM_MemorySubSpace::systemGarbageCollect (this=0x7fcafc06ebd0, env=0x7fcafc0370d8, gcCode=3)
    at MemorySubSpace.cpp:921
```

Stack trace 2:

```
#0  MM_MarkingDelegate::getObjectScanner (sizeToDo=0x7fffcef27ac0, reason=SCAN_REASON_PACKET, scannerSpace=0x7fffcef27ad0,
    objectPtr=0x705baec20, env=<optimized out>, this=<optimized out>) at ../../../gc_glue_java/MarkingDelegate.hpp:119
#1  MM_MarkingScheme::scanObject (objectPtr=0x705baec20, env=<optimized out>, this=<optimized out>) at MarkingScheme.cpp:298
#2  MM_MarkingScheme::completeScan (this=this@entry=0x7ffff0035830, env=env@entry=0x7fffb8001a68) at MarkingScheme.cpp:327
#3  0x00007fffefc1e581 in MM_MarkingScheme::completeMarking (this=0x7ffff0035830, env=env@entry=0x7fffb8001a68)
    at MarkingScheme.cpp:375
#4  0x00007fffefc1e5a5 in MM_MarkingScheme::markLiveObjectsScan (this=<optimized out>, env=env@entry=0x7fffb8001a68)
    at MarkingScheme.cpp:369
#5  0x00007fffefd1cab9 in MM_ParallelMarkTask::run (this=0x7ffff6fa4bc0, env=0x7fffb8001a68) at ParallelMarkTask.cpp:50
#6  0x00007fffefc3cf6b in MM_ParallelDispatcher::slaveEntryPoint (this=0x7ffff0035380, env=0x7fffb8001a68)
    at ParallelDispatcher.cpp:170
#7  0x00007fffefc3cdb2 in dispatcher_thread_proc2 (portLib=portLib@entry=0x7ffff67a4d40 <j9portLibrary>,
    info=info@entry=0x7ffff6fa5790) at ParallelDispatcher.cpp:92
#8  0x00007ffff5371473 in omrsig_protect (portLibrary=0x7ffff67a4d40 <j9portLibrary>,
    fn=0x7fffefc3cca0 <dispatcher_thread_proc2(OMRPortLibrary*, void*)>, fn_arg=0x7ffff6fa5790,
    handler=0x7ffff5fe4e18 <structuredSignalHandlerVM>, handler_arg=0x7ffff000fb20, flags=506, result=0x7fffcef27e28)
    at ../../omr/port/unix/omrsignal.c:425
#9  0x00007fffefc3c57c in dispatcher_thread_proc (info=<optimized out>) at ParallelDispatcher.cpp:130
#10 0x00007ffff5cdc202 in thread_wrapper (arg=0x7ffff01687e0) at ../omr/thread/common/omrthread.c:1705
```

The crash can reproduced by enabling `testValueWithLongAlignmentGCScanning` in ValueTypeTests, https://github.com/eclipse/openj9/blob/master/test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java#L2043.

The issue I see is that a headless object is push into the `env->_workStack`, it is later pop'ed for scaning or marking, then trys to read the J9Class but crashes because there isn't one.

I added a J9Class check to `MM_MarkingScheme::assertSaneObjectPtr` and get the following crash:

```
#0  MM_MarkingScheme::assertSaneObjectPtr (objectPtr=<optimized out>, env=<optimized out>, this=<optimized out>)
    at ./MarkingScheme.hpp:73
#1  MM_MarkingScheme::inlineMarkObjectNoCheck (leafType=false, objectPtr=<optimized out>, env=<optimized out>,
    this=<optimized out>) at ./MarkingScheme.hpp:147
#2  MM_MarkingScheme::scanObject (objectPtr=<optimized out>, env=<optimized out>, this=<optimized out>)
    at MarkingScheme.cpp:309
#3  MM_MarkingScheme::completeScan (this=this@entry=0x7ffff0035830, env=env@entry=0x7ffff0036fd8) at MarkingScheme.cpp:327
#4  0x00007fffefc1e6b1 in MM_MarkingScheme::completeMarking (this=0x7ffff0035830, env=env@entry=0x7ffff0036fd8)
    at MarkingScheme.cpp:375
#5  0x00007fffefc1e6d5 in MM_MarkingScheme::markLiveObjectsScan (this=<optimized out>, env=env@entry=0x7ffff0036fd8)
    at MarkingScheme.cpp:369
#6  0x00007fffefd1cf99 in MM_ParallelMarkTask::run (this=0x7ffff6fa4bc0, env=0x7ffff0036fd8) at ParallelMarkTask.cpp:50
#7  0x00007fffefc45963 in MM_Dispatcher::run (this=0x7ffff0035380, env=0x7ffff0036fd8, task=0x7ffff6fa4bc0,
    newThreadCount=<optimized out>) at Dispatcher.cpp:96
#8  0x00007fffefc770b2 in MM_ParallelGlobalGC::markAll (this=this@entry=0x7ffff0035610, env=env@entry=0x7ffff0036fd8,
    initMarkMap=initMarkMap@entry=true) at ParallelGlobalGC.cpp:952
#9  0x00007fffefc779ec in MM_ParallelGlobalGC::masterThreadGarbageCollect (this=0x7ffff0035610, env=0x7ffff0036fd8,
    allocDescription=0x0, initMarkMap=<optimized out>, rebuildMarkBits=<optimized out>) at ParallelGlobalGC.cpp:461
#10 0x00007fffefc744f3 in MM_ParallelGlobalGC::internalGarbageCollect (this=<optimized out>, env=0x7ffff0036fd8,
    subSpace=<optimized out>, allocDescription=0x0) at ParallelGlobalGC.cpp:1231
#11 0x00007fffefc1b3f7 in MM_Collector::garbageCollect (this=0x7ffff0035610, env=0x7ffff0036fd8,
    callingSubSpace=0x7ffff006ee60, allocateDescription=0x0, gcCode=<optimized out>, objectAllocationInterface=0x0,
    baseSubSpace=0x0, context=0x0) at Collector.cpp:499
#12 0x00007fffefc2bb64 in MM_MemorySubSpace::systemGarbageCollect (this=0x7ffff006ee60, env=0x7ffff0036fd8, gcCode=3)
    at MemorySubSpace.cpp:934
#13 0x00007fffefc2ba6d in MM_MemorySubSpace::systemGarbageCollect (this=0x7ffff006ead0, env=0x7ffff0036fd8, gcCode=3)
    at MemorySubSpace.cpp:921
#14 0x00007fffefa45097 in j9gc_modron_global_collect_with_overrides (vmThread=0x62da00, gcCode=3) at modronapi.cpp:89
#15 0x00007fffefa4501c in j9gc_modron_global_collect (vmThread=0x62da00) at modronapi.cpp:57
#16 0x00007fffeefa5ceb in JVM_GC_Impl () at sunvmi.c:606
```

**Comment by tajila** [comment]
@youngar

**Comment by youngar** [comment]
Thanks Tobi! Any idea why an object would be missing it's class, or is it just a bad object?

**Comment by tajila** [comment]
The object seems valid, by that I mean the values appear to be that of flattened array element. It seems to be like its just in the wrong place, but I can't find how it was added to the workstack.

**Comment by dmitripivkine** [comment]
@tajila Now, when Macros are fixed, Scavenger and Compact support added to Standard Collectors I think we can close this item. However "scan classes from FCC" is required to be added to complete handling of FA in Standard collectors
