### ISSUE TITLE
OpenJDK11-Acceptance TestZoneInfo310 availableIds don't match

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9642]
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK11-Acceptance/72/
All platforms are failing
sun/util/calendar/zi/TestZoneInfo310.java
```
STDOUT:
Compiling tz files!
testing!
OLD.getZoneInfoOld()[1]=275
OLD.getZoneInfoOld()[2]=200
OLD.getZoneInfoOld()[3]=141
OLD.getAvailableIDs()=699, total=628
OLD.getAliasTable()=361, total=228
OLD.TotalTZ()=38 (ms)
NEW.getTimeZone()[1]=21
NEW.getTimeZone()[2]=1
NEW.getTimeZone()[3]=1
NEW.getAvailableIDs()=13, total=629
NEW.getAliasTable()=43, total=229
NEW.TotalTZ()=0 (ms)

STDERR:
javazic: warning: found last rules for Morocco inconsistent.
javazic: warning: found last rules for Morocco inconsistent.
javazic: warning: found last rules for Eire inconsistent.
java.lang.RuntimeException:   FAILED:  availableIds don't match
	at TestZoneInfo310.main(TestZoneInfo310.java:163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by pshipton** [comment]
This fails on Hotspot 11.0.8+4 as well.
```
OLD.getZoneInfoOld()[1]=225
OLD.getZoneInfoOld()[2]=96
OLD.getZoneInfoOld()[3]=89
OLD.getAvailableIDs()=724, total=628
OLD.getAliasTable()=403, total=228
OLD.TotalTZ()=15 (ms)
NEW.getTimeZone()[1]=19
NEW.getTimeZone()[2]=603
NEW.getTimeZone()[3]=421
NEW.getAvailableIDs()=22, total=629
NEW.getAliasTable()=68, total=229
NEW.TotalTZ()=31 (ms)
STDERR:
javazic: warning: found last rules for Morocco inconsistent.
javazic: warning: found last rules for Morocco inconsistent.
javazic: warning: found last rules for Eire inconsistent.
java.lang.RuntimeException:   FAILED:  availableIds don't match
```

Excluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1793

**Comment by pshipton** [comment]
This issue stays open in order to validate the test is passing on a later build, and then remove the exclude.

**Comment by pshipton** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-tests/pull/1871 to remove the exclude.  I believe it was failing earlier because the tests don't necessarily fetch the test material which matches the JDK being tested.
