### ISSUE TITLE
Implementation required for MethodHandle.rebind()

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#9766]
OpenJDK acceptance failure (e.g. https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_linux_OpenJDK/218):
```
23:51:35  make/Main.gmk:363: recipe for target 'java.compiler-jmod' failed
23:51:35  java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
23:51:35  	at java.base/java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
23:51:35  	at java.base/java.lang.invoke.MethodHandle.rebind(MethodHandle.java:1479)
23:51:35  	at java.base/java.lang.invoke.StringConcatFactory.simpleConcat(StringConcatFactory.java:657)
23:51:35  	at java.base/java.lang.invoke.StringConcatFactory.generateMHInlineCopy(StringConcatFactory.java:458)
23:51:35  	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:354)
23:51:35  	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:1070)
23:51:35  	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1200)
23:51:35  	at jdk.jlink/jdk.tools.jlink.internal.Utils.getPathMatcher(Utils.java:97)
23:51:35  	at jdk.jlink/jdk.tools.jmod.JmodTask$PathMatcherConverter.convert(JmodTask.java:1173)
23:51:35  	at jdk.jlink/jdk.tools.jmod.JmodTask$PathMatcherConverter.convert(JmodTask.java:1169)
23:51:35  	at jdk.internal.opt/jdk.internal.joptsimple.internal.Reflection.convertWith(Reflection.java:154)
23:51:35  	at jdk.internal.opt/jdk.internal.joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:120)
23:51:35  	at jdk.internal.opt/jdk.internal.joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:308)
23:51:35  	at jdk.internal.opt/jdk.internal.joptsimple.OptionSet.valuesOf(OptionSet.java:253)
23:51:35  	at jdk.jlink/jdk.tools.jmod.JmodTask.handleOptions(JmodTask.java:1397)
23:51:35  	at jdk.jlink/jdk.tools.jmod.JmodTask.run(JmodTask.java:168)
23:51:35  	at jdk.jlink/jdk.tools.jmod.Main.main(Main.java:34)
```

**Comment by pshipton** [comment]
I'll close this as a dup of https://github.com/eclipse/openj9/issues/9771 even though this was created first.
