### ISSUE TITLE
Issue in image with openssl

### ISSUE THREAD

**Issue by JosafatZero** [eclipse/openj9#9769]
Hi everyone, our team started to use the image: `adoptopenjdk/openjdk8-openj9:jdk8u252-b09_openj9-0.20.0-alpine-slim` we already was using some in the past but in this case, in one of our components for some reason fail a rest call to https, not 100% but like 10% depending on some parameters that are sent to the api, this is the trace error:
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Tag mismatch!
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar!/:4.1.36.Final]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_252]
Caused by: javax.net.ssl.SSLException: Tag mismatch!
at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.SSLEngineImpl.readRecord(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[na:1.8.0_252]
at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[na:1.8.0_252]
at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1332) ~[netty-handler-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227) ~[netty-handler-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
... 14 common frames omitted
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at com.sun.crypto.provider.NativeGaloisCounterMode.decryptFinal(Unknown Source) ~[sunjce_provider.jar:1.8.0_252]
at com.sun.crypto.provider.CipherCore.finalNoPadding(Unknown Source) ~[sunjce_provider.jar:1.8.0_252]
at com.sun.crypto.provider.CipherCore.fillOutputBuffer(Unknown Source) ~[sunjce_provider.jar:1.8.0_252]
at com.sun.crypto.provider.CipherCore.doFinal(Unknown Source) ~[sunjce_provider.jar:1.8.0_252]
at com.sun.crypto.provider.AESCipher.engineDoFinal(Unknown Source) ~[sunjce_provider.jar:1.8.0_252]
at javax.crypto.CipherSpi.bufferCrypt(Unknown Source) ~[na:1.8.0_252]
at javax.crypto.CipherSpi.engineDoFinal(Unknown Source) ~[na:1.8.0_252]
at javax.crypto.Cipher.doFinal(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.CipherBox.decrypt(Unknown Source) ~[na:1.8.0_252]
at sun.security.ssl.EngineInputRecord.decrypt(Unknown Source) ~[na:1.8.0_252]
```

our team investigates about this and we found that:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8130341
so I start a thread in the java-at-ibm channel to ask about that where the people that help us ask us to change this flag:
`-Djdk.nativeCrypto=false`
as with the image by default is true , this works for us but maybe should be good fix it in the image to not do the change to patch it, I don't know which other information is needed to found the problem, I will add the onfo of the version:
```
image: adoptopenjdk/openjdk8-openj9:jdk8u252-b09_openj9-0.20.0-alpine-slim
java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200416_608 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)
```

also using different image this problem was not found:
```
image: openjdk:8-jdk-alpine
java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
thanks in advance, right now with the workaround we can live, so tell me if you need more information

**Comment by keithc-ca** [comment]
Can you provide more details about how one might reproduce this problem?

**Comment by pshipton** [comment]
@ashbm5 fyi

**Comment by ashbm5** [comment]
@samasri please take a look

**Comment by JosafatZero** [comment]
@keithc-ca for some reason I cannot reproduce now the problem, while I tried to create a project with fewer things to pass you I made the test and now is working without the flag, I tried directly with the original project and now is not happening :S as I mentioned this not happened with all calls, I don't know if some info from bluepages was weird or something and now was changed, but right now is not happen so don't know if we should close this..., I will let the project with the minimal things to reproduce, if you want to try to found, we use redis and webclient, I suppose the problem was in the response from webclient.

to make works I just use:
```
docker run --name test-redis -d  redis:3.2.6-alpine

./gradlew assemble
docker build -t test-bluepages .
docker run --name bluepages-test \
  --network es_network \
   -e REDIS_URI=test-redis
  -d test-bluepages:latest
```

[BluepagesTest.zip](https://github.com/eclipse/openj9/files/4719888/BluepagesTest.zip)
 thanks for your help

**Comment by keithc-ca** [comment]
If you encounter the problem again in the future, we can re-open this.
