### ISSUE TITLE
openjdk CheckedSetBash descendingSet() Element not present after addition

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9794]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl_Nightly/56
ub18-390-2
java/util/Collections/CheckedSetBash.java
```
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$22/0000000000000000@a6953aff): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet)", CheckedSetBash$$Lambda$25/0000000000000000@1b8e3e52): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$26/0000000000000000@e90fcbc1): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$22/0000000000000000@a6953aff): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$22/0000000000000000@a6953aff): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$26/0000000000000000@e90fcbc1): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet)", CheckedSetBash$$Lambda$25/0000000000000000@1b8e3e52): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$23/0000000000000000@87ff4475): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet().descendingSet()", CheckedSetBash$$Lambda$27/0000000000000000@6073759b): failure
22:26:53  java.lang.AssertionError: Element not present after addition.
22:26:53  	at org.testng.Assert.fail(Assert.java:94)
22:26:53  	at CheckedSetBash.AddRandoms(CheckedSetBash.java:132)
22:26:53  	at CheckedSetBash.testCheckedSet(CheckedSetBash.java:51)
22:26:53  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:26:53  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:26:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:26:53  	at java.lang.reflect.Method.invoke(Method.java:498)
22:26:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:26:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:26:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22:26:53  	at java.lang.Thread.run(Thread.java:823)
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$22/0000000000000000@a6953aff): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet().descendingSet()", CheckedSetBash$$Lambda$27/0000000000000000@6073759b): failure
22:26:53  java.lang.AssertionError: Element not present after addition.
22:26:53  	at org.testng.Assert.fail(Assert.java:94)
22:26:53  	at CheckedSetBash.AddRandoms(CheckedSetBash.java:132)
22:26:53  	at CheckedSetBash.testCheckedSet(CheckedSetBash.java:51)
22:26:53  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:26:53  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:26:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:26:53  	at java.lang.reflect.Method.invoke(Method.java:498)
22:26:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:26:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:26:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22:26:53  	at java.lang.Thread.run(Thread.java:823)
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(TreeSet).descendingSet()", CheckedSetBash$$Lambda$24/0000000000000000@52760107): failure
22:26:53  java.lang.AssertionError: Element not present after addition.
22:26:53  	at org.testng.Assert.fail(Assert.java:94)
22:26:53  	at CheckedSetBash.AddRandoms(CheckedSetBash.java:132)
22:26:53  	at CheckedSetBash.testCheckedSet(CheckedSetBash.java:51)
22:26:53  	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
22:26:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:26:53  	at java.lang.reflect.Method.invoke(Method.java:498)
22:26:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:26:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:26:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22:26:53  	at java.lang.Thread.run(Thread.java:823)
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$26/0000000000000000@e90fcbc1): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet)", CheckedSetBash$$Lambda$25/0000000000000000@1b8e3e52): success
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet().descendingSet()", CheckedSetBash$$Lambda$27/0000000000000000@6073759b): failure
22:26:53  java.lang.AssertionError: Element not present after addition.
22:26:53  	at org.testng.Assert.fail(Assert.java:94)
22:26:53  	at CheckedSetBash.AddRandoms(CheckedSetBash.java:132)
22:26:53  	at CheckedSetBash.testCheckedSet(CheckedSetBash.java:51)
22:26:53  	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
22:26:53  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:26:53  	at java.lang.reflect.Method.invoke(Method.java:498)
22:26:53  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
22:26:53  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
22:26:53  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
22:26:53  	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22:26:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
22:26:53  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
22:26:53  	at java.lang.Thread.run(Thread.java:823)
22:26:53  test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$22/0000000000000000@a6953aff): success
etc.
```

**Comment by pshipton** [comment]
@fjeremic fyi

**Comment by pshipton** [comment]
5x grinder on the same machine https://ci.eclipse.org/openj9/job/Grinder/901

**Comment by fjeremic** [comment]
Let's monitor this one to see if it reproduces. so far 0/55. If we start seeing this again I'll ask someone to take a look.

**Comment by JasonFengJ9** [comment]
Observed at an internal build `job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_testList_0/14/` (`cent7x64-1-7`)
```
openjdk version "1.8.0_322-beta"
IBM Semeru Runtime Open Edition (build 1.8.0_322-beta-202111170333-b02)
Eclipse OpenJ9 VM (build master-902c34f8c, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211117_252 (JIT enabled, AOT enabled)
OpenJ9   - 902c34f8c
OMR      - b95fd53e2
JCL      - 93eebb66 based on jdk8u322-b02)

[2021-11-17T04:33:15.597Z] Running test jdk_util_0 ...
[2021-11-17T04:33:15.597Z] ===============================================
[2021-11-17T04:33:15.597Z] jdk_util_0 Start Time: Tue Nov 16 20:33:14 2021 Epoch Time (ms): 1637123594701
[2021-11-17T04:33:15.597Z] "/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-11-17T04:33:15.597Z] JVMSHRC005I No shared class caches available
[2021-11-17T04:33:15.597Z] JVMSHRC005I No shared class caches available
[2021-11-17T04:33:15.597Z] cache cleanup done
[2021-11-17T04:33:15.597Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2021-11-17T04:33:15.597Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2021-11-17T04:33:51.776Z] --------------------------------------------------
[2021-11-17T04:33:51.776Z] TEST: java/util/Collections/CheckedSetBash.java

[2021-11-17T04:33:51.806Z] test CheckedSetBash.testCheckedSet("Collections.checkedSet(TreeSet).descendingSet()", CheckedSetBash$$Lambda$21/0x0000000000000000@e50ab699): failure
[2021-11-17T04:33:51.806Z] java.lang.AssertionError: Element not present after addition.
[2021-11-17T04:33:51.806Z] 	at org.testng.Assert.fail(Assert.java:94)
[2021-11-17T04:33:51.806Z] 	at CheckedSetBash.AddRandoms(CheckedSetBash.java:133)
[2021-11-17T04:33:51.806Z] 	at CheckedSetBash.testCheckedSet(CheckedSetBash.java:52)
[2021-11-17T04:33:51.806Z] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[2021-11-17T04:33:51.806Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-17T04:33:51.806Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-11-17T04:33:51.806Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2021-11-17T04:33:51.806Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2021-11-17T04:33:51.806Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2021-11-17T04:33:51.806Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
[2021-11-17T04:33:51.807Z] 	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
[2021-11-17T04:33:51.807Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-11-17T04:33:51.807Z] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2021-11-17T04:33:51.807Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-11-17T04:33:51.807Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-11-17T04:33:51.807Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-11-17T04:33:51.807Z] 	at java.lang.Thread.run(Thread.java:826)
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$20/0x0000000000000000@85cc8b50): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet)", CheckedSetBash$$Lambda$22/0x0000000000000000@ef713496): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$23/0x0000000000000000@ef48f577): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedSet(HashSet)", CheckedSetBash$$Lambda$19/0x0000000000000000@bf0a2203): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$23/0x0000000000000000@ef48f577): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedNavigableSet(TreeSet)", CheckedSetBash$$Lambda$22/0x0000000000000000@ef713496): success
[2021-11-17T04:33:51.807Z] test CheckedSetBash.testCheckedSet("Collections.checkedSet(TreeSet(reverseOrder)", CheckedSetBash$$Lambda$20/0x0000000000000000@85cc8b50): success
[2021-11-17T04:33:51.807Z] 
[2021-11-17T04:33:51.807Z] ===============================================
[2021-11-17T04:33:51.807Z] java/util/Collections/CheckedSetBash.java
[2021-11-17T04:33:51.807Z] Total tests run: 600, Failures: 200, Skips: 0
[2021-11-17T04:33:51.807Z] ===============================================
[2021-11-17T04:33:51.807Z] 
[2021-11-17T04:33:51.807Z] STDERR:
[2021-11-17T04:33:51.807Z] java.lang.Exception: failures: 200
[2021-11-17T04:33:51.807Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
[2021-11-17T04:33:51.807Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-11-17T04:33:51.807Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-11-17T04:33:51.807Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-11-17T04:33:51.807Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2021-11-17T04:33:51.807Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2021-11-17T04:33:51.807Z] 	at java.lang.Thread.run(Thread.java:826)
[2021-11-17T04:33:51.807Z] 
[2021-11-17T04:33:51.807Z] JavaTest Message: Test threw exception: java.lang.Exception
[2021-11-17T04:33:51.807Z] JavaTest Message: shutting down test
[2021-11-17T04:33:51.807Z] 
[2021-11-17T04:33:51.807Z] 
[2021-11-17T04:33:51.807Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 200
[2021-11-17T04:33:51.807Z] --------------------------------------------------
[2021-11-17T04:40:08.517Z] Test results: passed: 652; failed: 1
[2021-11-17T04:40:12.442Z] Report written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_testList_0/jvmtest/openjdk/report/html/report.html
[2021-11-17T04:40:12.442Z] Results written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_testList_0/aqa-tests/TKG/output_16371234002678/jdk_util_0/work
[2021-11-17T04:40:12.442Z] Error: Some tests failed or other problems occurred.
[2021-11-17T04:40:12.442Z] 
[2021-11-17T04:40:12.442Z] jdk_util_0_FAILED
```
