### ISSUE TITLE
ConcurrentLoadTest_0: testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest): 5 : getActiveThreadCount() expected:<0> but was:<1>

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#9797]
Test_openjdk8_j9_extended.system_x86-64_mac_xl:
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_mac_xl/216/tapResults/
```
testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest): 5 : getActiveThreadCount() expected:<0> but was:<1>
```

```
LT  testStarted : testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest)
LT  testFailure: testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest): 5 : getActiveThreadCount() expected:<0> but was:<1>
LT  junit.framework.AssertionFailedError: 5 : getActiveThreadCount() expected:<0> but was:<1>
LT  	at junit.framework.Assert.fail(Assert.java:57)
LT  	at junit.framework.Assert.failNotEquals(Assert.java:329)
LT  	at junit.framework.Assert.assertEquals(Assert.java:78)
LT  	at junit.framework.Assert.assertEquals(Assert.java:234)
LT  	at junit.framework.TestCase.assertEquals(TestCase.java:401)
LT  	at net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest.testAPI(ForkJoinPoolTest.java:122)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
LT  	at junit.framework.TestResult.run(TestResult.java:125)
LT  	at junit.framework.TestCase.run(TestCase.java:129)
LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:823)
LT  testFinished: testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinPoolTest)
```

**Comment by pshipton** [comment]
Closing as won't fix, see also https://github.com/eclipse/openj9/issues/4277.
If it happens more often, pls comment.

**Comment by adamfarley** [comment]
Will keep track of instances here, so we can re-open later if we discover "more often" is happening.

https://trss.adoptopenjdk.net/output/test?id=5efe55752e55416417bf7802

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/1881

**Comment by andrew-m-leonard** [comment]
Happened again: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_windows/317/consoleFull

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-32_windows_Nightly/628
