### ISSUE TITLE
gccheck fails on older core file

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#9810]
Java -version output
--------------------
```
$ ./jdk/bin/java -version
openjdk version "11.0.8-internal" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc.keithc.jdk11)
Eclipse OpenJ9 VM (build master-58ebe8c7216, JRE 11 Linux amd64-64-Bit Compressed References 20200605_000000 (JIT enabled, AOT enabled)
OpenJ9   - 58ebe8c7216
OMR      - b68a7d3001d
JCL      - d5a3efe3931 based on jdk-11.0.8+5)
```

Summary of problem
------------------
A core file created by an older JVM cannot be read by current builds.
To demonstrate, create a core file from a 0.20 build:
```
$ ./jdk-11.0.7+10-openj9/bin/java -Xdump:system:events=vmstart -version
JVMDUMP039I Processing dump event "vmstart", detail "" at 2020/06/05 11:09:18 - please wait.
JVMDUMP032I JVM requested System dump using '/home/keithc/space/openj9/jdk11/build/linux-x86_64-normal-server-release/images/core.20200605.110918.5975.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.5994.

JVMDUMP010I System dump written to /home/keithc/space/openj9/jdk11/build/linux-x86_64-normal-server-release/images/core.20200605.110918.5975.0001.dmp
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux amd64-64-Bit Compressed References 20200416_574 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
```
Then try to examine that core file with a current build (notice the exception in `gccheck`):
```
$ ./jdk/bin/jdmpview -core core.20200605.110918.5975.0001.dmp 
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) : 

Source : file:///home/keithc/space/openj9/jdk11/build/linux-x86_64-normal-server-release/images/core.20200605.110918.5975.0001.dmp
	*0 : PID: 5994 : JRE 11 Linux amd64-64 (build 11.0.7+10)

> !vmcheck
<vm check: Checking threads>
<vm check: Checking 16 threads done>
<vm check: Checking classes>
<vm check: Checking 508 classes (0 obsolete) done>
<vm check: Checking ROM classes>
<vm check: Checking 508 ROM classes done>
<vm check: Checking methods>
<vm check: Checking 8172 methods done>
<vm check: Checking ROM intern string nodes>
<vm check: Checking 0 ROM intern string nodes done>

> !gccheck
Starting GC Check
Checking HEAP...Error executing DDR command !gccheck : null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:663)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9ModronThreadLocalHeap._realHeapTopOffset_
	at com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapTop(J9ModronThreadLocalHeapPointer.java:217)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.<init>(GCObjectHeapIteratorAddressOrderedList_V1.java:78)
	at com.ibm.j9ddr.vm29.j9.gc.GCHeapRegionDescriptor_V1.objectIterator(GCHeapRegionDescriptor_V1.java:195)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckObjectHeap.check(CheckObjectHeap.java:53)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:469)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:60)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:47)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
	at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
	... 16 more
```
I expect this is due to the change in #9745.

**Comment by pshipton** [comment]
@dmitripivkine @LinHu2016

**Comment by LinHu2016** [comment]
@keithc-ca Could you please pass your old core file to me for testing? not every old core file can reproduce the problem. Thanks

**Comment by keithc-ca** [comment]
It's not special: in the description, see the command I used to create it (from the 0.20 adopt build for xlinux).

**Comment by pshipton** [comment]
Since this breaks DDR compatibility, setting as a blocker.
