### ISSUE TITLE
java/util/EnumSet/EnumSetBash.java 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9851]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/81
java/util/EnumSet/EnumSetBash.java
```
java.lang.RuntimeException: Incorrect hashCode computation.
	at EnumSetBash.fail(EnumSetBash.java:190)
	at EnumSetBash.bash(EnumSetBash.java:88)
	at EnumSetBash.main(EnumSetBash.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
30x grinder https://ci.eclipse.org/openj9/job/Grinder/910

**Comment by fjeremic** [comment]
Let's keep an eye on a reproduction. Gut feeling says its JIT given it is unreproducible, but we'll need a reasonable reproduction rate to be able to investigate.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/95

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/116
```
java.lang.RuntimeException: Set not equal to copy. 5
	at EnumSetBash.fail(EnumSetBash.java:190)
	at EnumSetBash.clone(EnumSetBash.java:145)
	at EnumSetBash.bash(EnumSetBash.java:66)
	at EnumSetBash.main(EnumSetBash.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_mac_Nightly/100
```
java.lang.RuntimeException: Set not equal to copy. 5
	at EnumSetBash.fail(EnumSetBash.java:191)
	at EnumSetBash.clone(EnumSetBash.java:146)
	at EnumSetBash.bash(EnumSetBash.java:67)
	at EnumSetBash.main(EnumSetBash.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_cm_Nightly/1
```
18:50:21  java.lang.RuntimeException: Set not equal to copy. 5
18:50:21  	at EnumSetBash.fail(EnumSetBash.java:191)
18:50:21  	at EnumSetBash.clone(EnumSetBash.java:146)
18:50:21  	at EnumSetBash.bash(EnumSetBash.java:61)
18:50:21  	at EnumSetBash.main(EnumSetBash.java:48)
18:50:21  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:50:21  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:50:21  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:50:21  	at java.lang.reflect.Method.invoke(Method.java:498)
18:50:21  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
18:50:21  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_sanity.openjdk_ppc64le_linux_Nightly/15
```
01:16:51  java.lang.RuntimeException: Incorrect hashCode computation.
01:16:51  	at EnumSetBash.fail(EnumSetBash.java:191)
01:16:51  	at EnumSetBash.bash(EnumSetBash.java:89)
01:16:51  	at EnumSetBash.main(EnumSetBash.java:50)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/94/
```
00:22:16  java.lang.RuntimeException: Incorrect hashCode computation.
00:22:16  	at EnumSetBash.fail(EnumSetBash.java:191)
00:22:16  	at EnumSetBash.bash(EnumSetBash.java:89)
00:22:16  	at EnumSetBash.main(EnumSetBash.java:48)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux_Release/1
```
11:38:43  java.lang.RuntimeException: Incorrect hashCode computation.
11:38:43  	at EnumSetBash.fail(EnumSetBash.java:191)
11:38:43  	at EnumSetBash.bash(EnumSetBash.java:89)
11:38:43  	at EnumSetBash.main(EnumSetBash.java:49)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/67
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/EnumSet/EnumSetBash.java
```
00:01:13  rerun:
00:01:13  cd /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16358197007711/jdk_util_0/work/scratch/2 && \
00:01:13  DISPLAY=:0 \
00:01:13  HOME=/home/jenkins \
00:01:13  LANG=en_US.UTF-8 \
00:01:13  PATH=/bin:/usr/bin:/usr/sbin \
00:01:13      /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/java \
00:01:13          -Dtest.vm.opts='-ea -esa -Xmx1540m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops -Djava.awt.headless=true' \
00:01:13          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx1540m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:+UseCompressedOops -J-Djava.awt.headless=true' \
00:01:13          -Dtest.compiler.opts= \
00:01:13          -Dtest.java.opts= \
00:01:13          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
00:01:13          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
00:01:13          -Dtest.timeout.factor=8.0 \
00:01:13          -Dtest.nativepath=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/openjdk-test-image/jdk/jtreg/native \
00:01:13          -Dtest.root=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk \
00:01:13          -Dtest.name=java/util/EnumSet/EnumSetBash.java \
00:01:13          -Dtest.file=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/EnumSet/EnumSetBash.java \
00:01:13          -Dtest.src=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/EnumSet \
00:01:13          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/EnumSet \
00:01:13          -Dtest.classes=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16358197007711/jdk_util_0/work/classes/0/java/util/EnumSet/EnumSetBash.d \
00:01:13          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16358197007711/jdk_util_0/work/classes/0/java/util/EnumSet/EnumSetBash.d \
00:01:13          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16358197007711/jdk_util_0/work/classes/0/java/util/EnumSet/EnumSetBash.d:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/EnumSet \
00:01:13          -classpath /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/TKG/output_16358197007711/jdk_util_0/work/classes/0/java/util/EnumSet/EnumSetBash.d:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/util/EnumSet:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
00:01:13          EnumSetBash
00:01:13  STDERR:
00:01:13  java.lang.RuntimeException: Incorrect hashCode computation.
00:01:13  	at EnumSetBash.fail(EnumSetBash.java:191)
00:01:13  	at EnumSetBash.bash(EnumSetBash.java:89)
00:01:13  	at EnumSetBash.main(EnumSetBash.java:49)
00:01:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:01:13  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
00:01:13  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:01:13  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
00:01:13  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
00:01:13  	at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/141/ - ub16p8j92
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/EnumSet/EnumSetBash.java
```
22:54:03  java.lang.RuntimeException: Incorrect hashCode computation.
22:54:03  	at EnumSetBash.fail(EnumSetBash.java:191)
22:54:03  	at EnumSetBash.bash(EnumSetBash.java:89)
22:54:03  	at EnumSetBash.main(EnumSetBash.java:49)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Nightly/142
jdk_util_1 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650`
java/util/EnumSet/EnumSetBash.java
```
01:29:12  STDERR:
01:29:12  java.lang.RuntimeException: Set not equal to copy. 5
01:29:12  	at EnumSetBash.fail(EnumSetBash.java:191)
01:29:12  	at EnumSetBash.clone(EnumSetBash.java:146)
01:29:12  	at EnumSetBash.bash(EnumSetBash.java:61)
01:29:12  	at EnumSetBash.main(EnumSetBash.java:48)
```

**Comment by JasonFengJ9** [comment]
Observed at an internal build `job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_0/15/testReport/java_util_EnumSet_EnumSetBash/java/EnumSetBash/`
```
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Certified Edition 17.0.1+12 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1+12 (build master-0f828acf4, JRE 17 Linux aarch64-64-Bit Compressed References 20211120_39 (JIT enabled, AOT enabled)
OpenJ9   - 0f828acf4
OMR      - 83214375c
JCL      - df273956de9 based on jdk-17.0.1+12)

[2021-11-20T17:01:28.622Z] Running test jdk_util_0 ...
[2021-11-20T17:01:28.622Z] ===============================================
[2021-11-20T17:01:28.622Z] jdk_util_0 Start Time: Sat Nov 20 12:01:28 2021 Epoch Time (ms): 1637427688078
[2021-11-20T17:01:28.622Z] "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_testList_0/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2021-11-20T17:01:28.622Z] JVMSHRC005I No shared class caches available
[2021-11-20T17:01:28.622Z] JVMSHRC005I No shared class caches available
[2021-11-20T17:01:28.622Z] cache cleanup done
[2021-11-20T17:01:28.622Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2021-11-20T17:01:28.622Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2021-11-20T17:04:10.720Z] --------------------------------------------------
[2021-11-20T17:04:10.720Z] TEST: java/util/EnumSet/EnumSetBash.java

java.lang.RuntimeException: Incorrect hashCode computation.
	at EnumSetBash.fail(EnumSetBash.java:191)
	at EnumSetBash.bash(EnumSetBash.java:89)
	at EnumSetBash.main(EnumSetBash.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_ppc64le_linux_Nightly/98
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/EnumSet/EnumSetBash.java
```
00:04:16  STDERR:
00:04:16  java.lang.RuntimeException: Set not equal to copy. 1
00:04:16  	at EnumSetBash.fail(EnumSetBash.java:191)
00:04:16  	at EnumSetBash.clone(EnumSetBash.java:146)
00:04:16  	at EnumSetBash.bash(EnumSetBash.java:68)
00:04:16  	at EnumSetBash.main(EnumSetBash.java:49)
00:04:16  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:04:16  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
00:04:16  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:04:16  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
00:04:16  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
00:04:16  	at java.base/java.lang.Thread.run(Thread.java:884)
```

**Comment by JasonFengJ9** [comment]
Appeared at JDK11 `0.30.0` release build `job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_1/13/`
```
[2022-01-31T20:26:44.471Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode150
[2022-01-31T20:26:44.471Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops 

[2022-01-31T20:29:29.483Z] TEST: java/util/EnumSet/EnumSetBash.java

[2022-01-31T20:29:29.484Z] STDERR:
[2022-01-31T20:29:29.484Z] java.lang.RuntimeException: Incorrect hashCode computation.
[2022-01-31T20:29:29.484Z] 	at EnumSetBash.fail(EnumSetBash.java:191)
[2022-01-31T20:29:29.484Z] 	at EnumSetBash.bash(EnumSetBash.java:89)
[2022-01-31T20:29:29.484Z] 	at EnumSetBash.main(EnumSetBash.java:49)
[2022-01-31T20:29:29.484Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-31T20:29:29.484Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-31T20:29:29.484Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-31T20:29:29.484Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-31T20:29:29.484Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
[2022-01-31T20:29:29.484Z] 	at java.base/java.lang.Thread.run(Thread.java:866)
[2022-01-31T20:29:29.484Z] 
[2022-01-31T20:29:29.484Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-01-31T20:29:29.484Z] JavaTest Message: shutting down test
[2022-01-31T20:29:29.484Z] 
[2022-01-31T20:29:29.484Z] 
[2022-01-31T20:29:29.484Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Incorrect hashCode computation.
[2022-01-31T20:29:29.484Z] --------------------------------------------------
[2022-01-31T20:56:14.359Z] Test results: passed: 839; failed: 1
[2022-01-31T20:56:28.343Z] 
[2022-01-31T20:56:28.343Z] jdk_util_0_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/222 - [osx1013-x86-4](https://openj9-jenkins.osuosl.org/computer/osx1013-x86-4)
jdk_util_0
java/util/EnumSet/EnumSetBash.java

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/245
jdk_util_1
java/util/EnumSet/EnumSetBash.java

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_s390x_linux_OpenJDK17/17/ - [rh7-390-3](https://openj9-jenkins.osuosl.org/computer/rh7-390-3)
jdk_util_1 
java/util/EnumSet/EnumSetBash.java
```
08:28:08  java.lang.RuntimeException: Set not equal to copy. 5
08:28:08  	at EnumSetBash.fail(EnumSetBash.java:191)
08:28:08  	at EnumSetBash.clone(EnumSetBash.java:146)
08:28:08  	at EnumSetBash.bash(EnumSetBash.java:65)
08:28:08  	at EnumSetBash.main(EnumSetBash.java:48)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/272/
jdk_util_0 `-Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:+UseCompressedOops`
java/util/EnumSet/EnumSetBash.java
```
21:44:50  STDERR:
21:44:50  java.lang.RuntimeException: Incorrect hashCode computation.
21:44:50  	at EnumSetBash.fail(EnumSetBash.java:191)
21:44:50  	at EnumSetBash.bash(EnumSetBash.java:89)
21:44:50  	at EnumSetBash.main(EnumSetBash.java:49)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/278
jdk_util_0 
java/util/EnumSet/EnumSetBash.java
```
22:50:31  STDERR:
22:50:31  java.lang.RuntimeException: Incorrect hashCode computation.
22:50:31  	at EnumSetBash.fail(EnumSetBash.java:191)
22:50:31  	at EnumSetBash.bash(EnumSetBash.java:89)
22:50:31  	at EnumSetBash.main(EnumSetBash.java:49)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/302
jdk_util_1 
java/util/EnumSet/EnumSetBash.java
```
00:01:28  java.lang.RuntimeException: Set not equal to copy. 5
00:01:28  	at EnumSetBash.fail(EnumSetBash.java:191)
00:01:28  	at EnumSetBash.clone(EnumSetBash.java:146)
00:01:28  	at EnumSetBash.bash(EnumSetBash.java:69)
00:01:28  	at EnumSetBash.main(EnumSetBash.java:48)
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/315
jdk_util_1 
java/util/EnumSet/EnumSetBash.java
```
21:28:09  java.lang.RuntimeException: Incorrect hashCode computation.
21:28:09  	at EnumSetBash.fail(EnumSetBash.java:191)
21:28:09  	at EnumSetBash.bash(EnumSetBash.java:89)
21:28:09  	at EnumSetBash.main(EnumSetBash.java:49)
```

**Comment by JasonFengJ9** [comment]
[An internal build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_0/69/)(`win16x64rt3-6`)
```
[2022-07-23T20:37:48.492Z] variation: -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache Mode650
[2022-07-23T20:37:48.871Z] JVM_OPTIONS:  -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-UseCompressedOops 

[2022-07-23T20:47:43.246Z] TEST: java/util/EnumSet/EnumSetBash.java

[2022-07-23T20:47:43.247Z] STDERR:
[2022-07-23T20:47:43.247Z] java.lang.RuntimeException: Incorrect hashCode computation.
[2022-07-23T20:47:43.247Z] 	at EnumSetBash.fail(EnumSetBash.java:191)
[2022-07-23T20:47:43.247Z] 	at EnumSetBash.bash(EnumSetBash.java:89)
[2022-07-23T20:47:43.247Z] 	at EnumSetBash.main(EnumSetBash.java:49)
[2022-07-23T20:47:43.247Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[2022-07-23T20:47:43.247Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[2022-07-23T20:47:43.247Z] 	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
[2022-07-23T20:47:43.247Z] 	at java.base/java.lang.Thread.run(Thread.java:857)
[2022-07-23T20:47:43.247Z] 
[2022-07-23T20:47:43.247Z] JavaTest Message: Test threw exception: java.lang.RuntimeException
[2022-07-23T20:47:43.247Z] JavaTest Message: shutting down test
[2022-07-23T20:47:43.247Z] 
[2022-07-23T20:47:43.247Z] 
[2022-07-23T20:47:43.247Z] TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Incorrect hashCode computation.
[2022-07-23T20:47:43.247Z] --------------------------------------------------
[2022-07-23T21:14:22.454Z] Test results: passed: 901; failed: 1
[2022-07-23T21:14:57.012Z] Report written to C:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_0\jvmtest\openjdk\report\html\report.html
[2022-07-23T21:14:57.012Z] Results written to C:\Users\jenkins\workspace\Test_openjdk18_j9_sanity.openjdk_x86-64_windows_testList_0\aqa-tests\TKG\output_16586060594469\jdk_util_1\work
[2022-07-23T21:14:57.012Z] Error: Some tests failed or other problems occurred.
[2022-07-23T21:14:57.012Z] 
[2022-07-23T21:14:57.012Z] jdk_util_1_FAILED
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/370/
jdk_util_1
java/util/EnumSet/EnumSetBash.java
```
23:05:56  java.lang.RuntimeException: Set not equal to copy. 5
23:05:56  	at EnumSetBash.fail(EnumSetBash.java:191)
23:05:56  	at EnumSetBash.clone(EnumSetBash.java:146)
23:05:56  	at EnumSetBash.bash(EnumSetBash.java:67)
23:05:56  	at EnumSetBash.main(EnumSetBash.java:48)
```
