### ISSUE TITLE
ub16x64j95 No display name received from Xvfb

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9875]
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.openjdk_x86-64_linux_Nightly/14
ub16x64j95
`Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-14-..fbdir7408207601216309862`
```
java.lang.IllegalStateException: No display name received from Xvfb within 10 seconds
	at org.jenkinsci.plugins.xvfb.AutoDisplayNameFilterStream.getDisplayNumber(AutoDisplayNameFilterStream.java:77)
	at org.jenkinsci.plugins.xvfb.Xvfb.launchXvfb(Xvfb.java:605)
	at org.jenkinsci.plugins.xvfb.Xvfb.setUp(Xvfb.java:697)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2.doStart(CoreWrapperStep.java:97)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$$Lambda$416/00000000200694B0.run(Unknown Source)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$$Lambda$386/0000000060010ED0.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau any ideas? I've only seen the one occurrence so far, will monitor for more.

**Comment by jdekonin** [comment]
Wasn't a problem on this machine on June 2nd or 4th for the same test, not to say it cannot be something new.

There have been no planned or unplanned changes to this machine in the past 2-4 weeks.

**Comment by pshipton** [comment]
Probably just a weird network thing.
