### ISSUE TITLE
ASSERTION FAILED ** at ObjectMonitor.cpp:331: (!(8 == (lock & (8 | 1))))

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9894]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/400
SC_Softmx_JitAot_0
```
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
03:59:32.630 0x20b8100    j9vm.225    *   ** ASSERTION FAILED ** at ObjectMonitor.cpp:331: (!(8 == (lock & (8 | 1))))
03:59:32.630 0x20ce900    j9vm.225    *   ** ASSERTION FAILED ** at ObjectMonitor.cpp:331: (!(8 == (lock & (8 | 1))))
03:59:32.630 0x20bf900    j9vm.225    *   ** ASSERTION FAILED ** at ObjectMonitor.cpp:331: (!(8 == (lock & (8 | 1))))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/06/15 22:59:32 - please wait.
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/06/15 22:59:32 - please wait.
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/06/15 22:59:32 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c00000fd J9Generic_Signal=00000004 ExceptionAddress=00007FFF7FAEF087 ContextFlags=0010005f
Handler1=00007FFF7FB8FC40 Handler2=00007FFF7FAD8900
RDI=00007FFF7FA998D0 RSI=00007FFF7FCC8BB0 RAX=0000000000000010 RBX=0000000000EA3B50
RCX=43309EF62D330000 RDX=0000000000000001 R8=0000000000000005 R9=0000000000000000
R10=00000000020B7000 R11=0000000015133000 R12=0000000000F7EB10 R13=00000000020B73C0
R14=00000000020B7470 R15=00000000020B7948
RIP=00007FFF7FAEF087 RSP=00000000020B7308 RBP=00000000020B7350 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9prt29.dll
Module_base_address=00007FFF7FAB0000 Offset_in_DLL=000000000003f087
Target=2_90_20200615_424 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
---------------------------------------
```

I don't find any diagnostic files.

**Comment by pshipton** [comment]
@hangshao0

**Comment by hangshao0** [comment]
> I don't find any diagnostic files.

Any reason why there are no diagnostic files ? @Mesbah-Alam

**Comment by pshipton** [comment]
Unless there is a hidden `-Xdump:none` command, I'm not sure what happened. Could be the VM gp'ed instead of creating dumps for the assert(s), and then wasn't in a good state to create dumps.
The output shows `JVMDUMP039I Processing dump event "gpf", detail "" at 2020/06/15 22:59:32 - please wait.` and then nothing.

**Comment by pshipton** [comment]
There may also have been a space problem, as I see
```
JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested 
 	Adjusted to maximum shared memory permitted (67108864 bytes) 
```

**Comment by hangshao0** [comment]
Something else is already wrong before the assertion. Test failed at 22:59:21. 

```
22:59:21.271 - Test failed
  Failure num.  = 1
  Test number   = 0
  Test details  = 'ArbitraryJava[net.adoptopenjdk.test.lang.invoke.BasicTest doTest]'
  Suite number  = 0
  Thread number = 1
>>> Captured test output >>>
Starting doTest
.
Step 1Test failed:
java.lang.Error: ERROR: Expected 20456; found 0
	at net.adoptopenjdk.test.lang.invoke.BasicTest.check(BasicTest.java:66)
	at net.adoptopenjdk.test.lang.invoke.BasicTest.doTest(BasicTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
<<<
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/547
SC_Softmx_JitAot_0
win2012-x86-6
```
STF 23:00:53.013 - **FAILED** Process jvm4 has timed out
```
16.jvm4.stderr
```
JVMSHRC237I Opened shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
04:31:19.573 0x57bc00    j9vm.225    *   ** ASSERTION FAILED ** at ObjectMonitor.cpp:331: (!(8 == (lock & (8 | 1))))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/11/14 22:31:19 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c00000fd J9Generic_Signal=00000004 ExceptionAddress=00007FFFDA9D0BD7 ContextFlags=0010005f
Handler1=00007FFFDAAA27D0 Handler2=00007FFFDA9BEE60
RDI=00007FFFDA959940 RSI=00007FFFDABEA8C0 RAX=0000000000000010 RBX=000000AB0B8DFC70
RCX=CEFDFED4DDC00000 RDX=0000000000000000 R8=0000000000000005 R9=0000000000000003
R10=000000000057A000 R11=000000AB138D3000 R12=000000000057AF70 R13=000000000057B4D0
R14=000000AB0C20F750 R15=000000000057AEC0
RIP=00007FFFDA9D0BD7 RSP=000000000057AE08 RBP=000000000057AE50 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9prt29.dll
Module_base_address=00007FFFDA990000 Offset_in_DLL=0000000000040bd7
Target=2_90_20201114_573 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/11/14 22:31:19 - please wait.
000000000055DD00: Invalid class pointer in thread Thread-15
000000000055DD00:	O-Slot=000000000055DB90
000000000055DD00:	O-Slot value=00000000FFC62758
000000000055DD00:	PC=00007FFFC60B1CFF
000000000055DD00:	framesWalked=3
000000000055DD00:	arg0EA=000000000055DBA0
000000000055DD00:	walkSP=000000000055DA68
000000000055DD00:	literals=0000000000000010
000000000055DD00:	jitInfo=000000AB12340F68
000000000055DD00:	method=0000000000504A90 (net/adoptopenjdk/test/nio/NioBuffersTest$Buffers$BufferThread.run()V) (JIT)
000000000055DD00:	stack=000000000055AC48-000000000055DC30
000000000055DD00: Invalid class pointer in thread Thread-15
000000000055DD00:	O-Slot=000000AB131CF750
000000000055DD00:	O-Slot value=00000000FFC62758
000000000055DD00:	PC=00007FFFC60B1CFF
000000000055DD00:	framesWalked=3
000000000055DD00:	arg0EA=000000000055DBA0
000000000055DD00:	walkSP=000000000055DA68
000000000055DD00:	literals=0000000000000010
000000000055DD00:	jitInfo=000000AB12340F68
000000000055DD00:	method=0000000000504A90 (net/adoptopenjdk/test/nio/NioBuffersTest$Buffers$BufferThread.run()V) (JIT)
000000000055DD00:	stack=000000000055AC48-000000000055DC30
JVMDUMP039I Processing dump event "abort", detail "" at 2020/11/14 22:31:19 - please wait.
```

In artifacts I see 3 java.exe_201114_<value>.dump files.
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly/547/system_test_output.tar.gz

**Comment by pshipton** [comment]
@tajila @gacholio fyi
Given the `Invalid class pointer`, I'm guessing this is a JIT issue?

**Comment by gacholio** [comment]
The jitInfo is not NULL, indicating that the error occurred in a JIT frame, which is not a guarantee that it's a JIT issue, but it's strong evidence.

**Comment by gacholio** [comment]
Possibly related to https://github.com/eclipse/openj9/issues/10984 and https://github.com/eclipse/openj9/issues/10196

**Comment by pshipton** [comment]
Another one https://github.com/eclipse/openj9/issues/10984#issuecomment-749593181

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_1/43/
SC_Softmx_JitAot_1
JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_1/43/system_test_output.tar.gz
```
JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested 
 	Adjusted to maximum shared memory permitted (67108864 bytes) 
 	(To increase available shared memory, modify system SHMMAX value) 
 	 If -Xscdmx is used, the debug attribute area is adjusted in proportion 
 	 according to its original ratio to the -Xscmx value.
JVMSHRC237I Opened shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
05:45:59.445 0x58df00    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
05:45:59.445 0x559300    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
05:45:59.445 0x551a00    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
05:45:59.445 0x56fd00    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/279
SC_Softmx_JitAot_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/279/system_test_output.tar.gz

16.jvm4.stderr
```
JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested 
 	Adjusted to maximum shared memory permitted (67108864 bytes) 
 	(To increase available shared memory, modify system SHMMAX value) 
 	 If -Xscdmx is used, the debug attribute area is adjusted in proportion 
 	 according to its original ratio to the -Xscmx value.
JVMSHRC237I Opened shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
02:03:57.815 0x55c100    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
02:03:57.815 0x572b00    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
Unhandled exception
Type=Segmentation error vmState=0x00000000
02:03:57.815 0x563a00    j9vm.225    *   Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFB00AC2185 ContextFlags=0010005f
Handler1=00007FFAF54CB3F0 Handler2=00007FFAF75393D0 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
RDI=0000000000554900 RSI=0000000080000020 RAX=000000AF0B4889A0 RBX=FFF28F18FFF27F10
RCX=0000000000000006 RDX=00000000FFF27F00 R8=0000000000554EA8 R9=0000000000000000
R10=0000000000554900 R11=0000000000016B40 R12=0000000000000000 R13=0000000000000074
R14=00007FFAF55919A8 R15=00007FFAF5591A10
02:03:57.815 0x589500    j9vm.225    *   RIP=00007FFB00AC2185 RSP=000000AF103EF3C0 RBP=00007FFAF5591A70 EFLAGS=0000000000010246
FS=0053 ES=002B DS=002B
** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
02:03:57.815 0x56b300    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9thr29.dll
Module_base_address=00007FFB00AC0000 Offset_in_DLL=0000000000002185
Target=2_90_20220526_282 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
02:03:57.815 0x57a400    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
02:03:57.815 0x598700    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
```

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/281
SC_Softmx_JitAot_1 `-Xcompressedrefs -Xjit -Xgcpolicy:gencon`

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/281/system_test_output.tar.gz

16.jvm4.stderr
```
JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested 
 	Adjusted to maximum shared memory permitted (67108864 bytes) 
 	(To increase available shared memory, modify system SHMMAX value) 
 	 If -Xscdmx is used, the debug attribute area is adjusted in proportion 
 	 according to its original ratio to the -Xscmx value.
JVMSHRC237I Opened shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMJITM018W Async Compilation feature mismatch. Ignoring AOT code in shared class cache.
05:14:26.531 0x59fd00    j9vm.225    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:347: (!(8 == (lock & (8 | 1))))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2022/05/31 00:14:26 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c00000fd J9Generic_Signal=00000004 ExceptionAddress=00007FFE8F690D77 ContextFlags=0010005f
Handler1=00007FFE8F78B3F0 Handler2=00007FFE8F6693D0
RDI=00007FFE9187B4D8 RSI=00007FFE9B30EC60 RAX=0000000000000010 RBX=00000007EA3CAB70
RCX=EEC9DEBEEE790000 RDX=0000000000000000 R8=0000000000000005 R9=0000000000000003
R10=000000000059E000 R11=00000007F21A3000 R12=000000000059EFA0 R13=000000000059F4F0
R14=00000007EAC2C170 R15=000000000059EEF0
RIP=00007FFE8F690D77 RSP=000000000059EE38 RBP=000000000059EE80 EFLAGS=0000000000010287
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9prt29.dll
Module_base_address=00007FFE8F650000 Offset_in_DLL=0000000000040d77
Target=2_90_20220530_284 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
---------------------------------------
`

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/466
SC_Softmx_JitAot_1

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2/466/system_test_output.tar.gz
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFD3C8E2225 ContextFlags=0010005f
Handler1=00007FFD31F7D140 Handler2=00007FFD31E5AA50 InaccessibleReadAddress=0000000000000008
04:31:43.323 0x597800    j9vm.225    *   RDI=0000000000588600 RSI=00000000FFEF2600 RAX=000000E6EB43F8C0 RBX=0000000000000000
RCX=0000000000000006 RDX=00000000FFEF2600 R8=00000000FFEF264C R9=0000000000000000
R10=0000000000588600 R11=00007FFD3DD615D1 R12=00007FFD3205B338 R13=00007FFD3205B380
R14=0000000080000020 R15=00007FFD3205B3E0
** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Nightly\openj9\runtime\vm\ObjectMonitor.cpp:351: (!(8 == (lock & (8 | 1))))
RIP=00007FFD3C8E2225 RSP=000000E6EE17F390 RBP=00000000FFEF2600 EFLAGS=0000000000010246
FS=0053 ES=002B DS=002B
XMM0 000000e6eb484948 (f: 3947383040.000000, d: 4.900093e-312)
XMM1 000000e6eb484948 (f: 3947383040.000000, d: 4.900093e-312)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9thr29.dll
Module_base_address=00007FFD3C8E0000 Offset_in_DLL=0000000000002225
Target=2_90_20230223_495 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
JVMDUMP039I Processing dump event "traceassert", detail "" at 2023/02/23 22:31:43 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c00000fd J9Generic_Signal=00000004 ExceptionAddress=00007FFD31E880D7 ContextFlags=0010005f
Handler1=00007FFD31F7D140 Handler2=00007FFD31E5AA50
RDI=00007FFD31E312C8 RSI=00007FFD32100DC0 RAX=0000000000000010 RBX=000000E6E6B5DFB0
RCX=CADB6C9494820000 RDX=0000000000000000 R8=0000000000000005 R9=0000000000000000
R10=0000000000596000 R11=000000E6EE483000 R12=00000000005968B0 R13=00007FFD32100DC0
R14=000000E6E7421550 R15=0000000000596800
RIP=00007FFD31E880D7 RSP=0000000000596748 RBP=0000000000596790 EFLAGS=0000000000010287
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=F:\Users\jenkins\workspace\Test_openjdk8_j9_extended.system_x86-64_windows_Nightly_testList_2\openjdkbinary\j2sdk-image\jre\bin\default\j9prt29.dll
Module_base_address=00007FFD31E40000 Offset_in_DLL=00000000000480d7
Target=2_90_20230223_495 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
----------- Stack Backtrace -----------
---------------------------------------
```
