### ISSUE TITLE
DDR incompatibilities realHeapAlloc() and _realHeapTopOffset_

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9944]
Trying to read older cores with the latest, running `!monitors deadlock`.

`com.ibm.j9ddr.CorruptDataException: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()`
- no stack for this one
- occurred reading OpenJ9 0.20 core with a recent IBM Java, which technically isn't supported, not sure if this problem is expected or should have been resolved by #9813

```
NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9ModronThreadLocalHeap._realHeapTopOffset_
	at com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapTop(J9ModronThreadLocalHeapPointer.java:217)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.<init>(GCObjectHeapIteratorAddressOrderedList_V1.java:78)
	at com.ibm.j9ddr.vm29.j9.gc.GCHeapRegionDescriptor_V1.objectIterator(GCHeapRegionDescriptor_V1.java:195)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIterator.fromHeapRegionDescriptor(GCObjectHeapIterator.java:51)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.<init>(HeapWalker.java:83)
```
- occurred reading OpenJ9 0.20 core with recent OpenJ9 nightly build.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by keithc-ca** [comment]
I tried opening a core file generated by
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux amd64-64-Bit Compressed References 20200416_574 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
```
with a current build and received
```
Problem running command:
com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.CorruptDataException: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()
```
This *is* a supported use case.

If you enable logging, you get more information:
```
> log j9ddr.interactive.context FINE
> !monitors deadlock
Jun. 19, 2020 9:51:05 A.M. com.ibm.j9ddr.tools.ddrinteractive.Context tryCommand
FINE: Problem running command: 
com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.CorruptDataException: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.MonitorsCommand.run(MonitorsCommand.java:119)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:356)
	at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:331)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:811)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.execute(Session.java:765)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:739)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.Session.run(Session.java:663)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
	at openj9.dtfjview/com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: com.ibm.j9ddr.CorruptDataException: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.monitors.DeadlockDetector.findDeadlocks(DeadlockDetector.java:122)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.MonitorsCommand.deadlockCommand(MonitorsCommand.java:223)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.MonitorsCommand.run(MonitorsCommand.java:112)
	... 21 more
Caused by: com.ibm.j9ddr.CorruptDataException: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.getRealHeapAlloc(GCObjectHeapIteratorAddressOrderedList_V1.java:178)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.<init>(GCObjectHeapIteratorAddressOrderedList_V1.java:84)
	at com.ibm.j9ddr.vm29.j9.gc.GCHeapRegionDescriptor_V1.objectIterator(GCHeapRegionDescriptor_V1.java:195)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIterator.fromHeapRegionDescriptor(GCObjectHeapIterator.java:51)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.<init>(HeapWalker.java:83)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.runFlatLockMonitorRegionWalk(HeapWalker.java:267)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.initializeFlatLockedMonitors(HeapWalker.java:255)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.getFlatLockedMonitors(HeapWalker.java:237)
	at com.ibm.j9ddr.vm29.j9.walkers.MonitorIterator.<init>(MonitorIterator.java:75)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.monitors.DeadlockUtils.readObjectMonitors(DeadlockUtils.java:346)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.monitors.DeadlockDetector.findDeadlocks(DeadlockDetector.java:61)
	... 23 more
Caused by: java.lang.NoSuchMethodException: com.ibm.j9ddr.vm29.pointer.generated.J9ModronThreadLocalHeapPointer.realHeapAlloc()
	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:640)
	at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1346)
	at java.base/java.lang.Class.getMethodHelper(Class.java:1410)
	at java.base/java.lang.Class.getMethod(Class.java:1338)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.getRealHeapAlloc(GCObjectHeapIteratorAddressOrderedList_V1.java:160)
	... 33 more
```
The problem is trying to find a method that isn't included in a current build. If the pointer classes were being generated at runtime, this would not occur (if you examine a 32-bit core with a 64-bit SDK or vice-versa). The DDR code needs to be updated so it does not rely on the method `realHeapAlloc()` existing.

**Comment by keithc-ca** [comment]
We have at least two ways to fix this.
* The first is to generate pointer classes dynamically more often (by removing [these lines](https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/J9DDRClassLoader.java#L69-L73) in `J9DDRClassLoader`).
* The second is to change `GCObjectHeapIteratorAddressOrderedList_V1` so it looks for the offset field `J9ModronThreadLocalHeap.realHeapAlloc` rather than the method `J9ModronThreadLocalHeapPointer.realHeapAlloc`.

Opinions anyone?

**Comment by keithc-ca** [comment]
I have a fix using the second approach.
