### ISSUE TITLE
JDI visible classes don't include array classes

### ISSUE THREAD

**Issue by provegard** [eclipse/openj9#9965]
Java -version output
--------------------

- Java Debug Interface (Reference Implementation) version 1.8
- Java Debug Wire Protocol (Reference Implementation) version 11.0
- JVM Debug Interface version 11.0
- JVM version 11.0.7 (Eclipse OpenJ9 VM, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200422_551 (JIT enabled, AOT enabled)
- OpenJ9   - 05fa2d361
- OMR      - d4365f371
- JCL      - 838028fc9d based on jdk-11.0.7+10)

Summary of problem
------------------

I have an application that connects to a remove JVM using JDI. The remove JVM is running OpenJ9. As part of invoking a method with a varargs signature, JDI calls VisibleClasses on the class loader of the declaring type of the method. The result is:

```
com.sun.jdi.ClassNotLoadedException: Class java.lang.Object[] not loaded
        at com.sun.tools.jdi.ClassLoaderReferenceImpl.findType(ClassLoaderReferenceImpl.java:107)
        at com.sun.tools.jdi.ReferenceTypeImpl.findType(ReferenceTypeImpl.java:1153)
        at com.sun.tools.jdi.MethodImpl.argumentType(MethodImpl.java:162)
        at com.sun.tools.jdi.MethodImpl.argumentTypes(MethodImpl.java:169)
        at com.sun.tools.jdi.MethodImpl.handleVarArgs(MethodImpl.java:301)
        at com.sun.tools.jdi.MethodImpl.validateAndPrepareArgumentsForInvoke(MethodImpl.java:366)
        at com.sun.tools.jdi.ObjectReferenceImpl.invokeMethod(ObjectReferenceImpl.java:407)
```

I have tried printing visible classes just before invoking the the method, and the list contains a number of `java.lang` classes (and interfaces, see below) including `java.lang.Object` but not `java.lang.Object[]`. In fact, the list contains no array types at all:

```
class java.lang.annotation.RetentionPolicy (no class loader)
class java.lang.ArithmeticException (no class loader)
class java.lang.ArrayIndexOutOfBoundsException (no class loader)
class java.lang.AssertionError (no class loader)
class java.lang.Boolean (no class loader)
class java.lang.Byte (no class loader)
class java.lang.Character (no class loader)
class java.lang.Class (no class loader)
class java.lang.ClassCastException (no class loader)
class java.lang.ClassLoader (no class loader)
class java.lang.ClassNotFoundException (no class loader)
class java.lang.ClassValue (no class loader)
class java.lang.CloneNotSupportedException (no class loader)
class java.lang.Double (no class loader)
class java.lang.Enum (no class loader)
class java.lang.Error (no class loader)
class java.lang.Exception (no class loader)
class java.lang.Float (no class loader)
class java.lang.IllegalAccessError (no class loader)
class java.lang.IllegalAccessException (no class loader)
class java.lang.IllegalArgumentException (no class loader)
class java.lang.IllegalStateException (no class loader)
class java.lang.IndexOutOfBoundsException (no class loader)
class java.lang.Integer (no class loader)
class java.lang.InterruptedException (no class loader)
class java.lang.invoke.CallSite (no class loader)
class java.lang.invoke.ConstantCallSite (no class loader)
class java.lang.invoke.LambdaMetafactory (no class loader)
class java.lang.invoke.MethodHandle (no class loader)
class java.lang.invoke.MethodHandles (no class loader)
class java.lang.invoke.MethodHandles$Lookup (no class loader)
class java.lang.invoke.MethodType (no class loader)
class java.lang.invoke.MutableCallSite (no class loader)
class java.lang.invoke.StringConcatFactory (no class loader)
class java.lang.invoke.SwitchPoint (no class loader)
class java.lang.invoke.WrongMethodTypeException (no class loader)
class java.lang.Long (no class loader)
class java.lang.Math (no class loader)
class java.lang.Module (no class loader)
class java.lang.module.Configuration (no class loader)
class java.lang.module.ModuleDescriptor (no class loader)
class java.lang.module.ModuleDescriptor$Builder (no class loader)
class java.lang.module.ModuleDescriptor$Modifier (no class loader)
class java.lang.module.ModuleReference (no class loader)
class java.lang.ModuleLayer (no class loader)
class java.lang.NoClassDefFoundError (no class loader)
class java.lang.NoSuchFieldError (no class loader)
class java.lang.NoSuchFieldException (no class loader)
class java.lang.NoSuchMethodError (no class loader)
class java.lang.NoSuchMethodException (no class loader)
class java.lang.NullPointerException (no class loader)
class java.lang.Number (no class loader)
class java.lang.NumberFormatException (no class loader)
class java.lang.Object (no class loader)
class java.lang.OutOfMemoryError (no class loader)
class java.lang.ref.Reference (no class loader)
class java.lang.ref.ReferenceQueue (no class loader)
class java.lang.ref.SoftReference (no class loader)
class java.lang.ref.WeakReference (no class loader)
class java.lang.reflect.Array (no class loader)
class java.lang.reflect.Constructor (no class loader)
class java.lang.reflect.Field (no class loader)
class java.lang.reflect.InvocationTargetException (no class loader)
class java.lang.reflect.Method (no class loader)
class java.lang.reflect.Proxy (no class loader)
class java.lang.ReflectiveOperationException (no class loader)
class java.lang.Runtime (no class loader)
class java.lang.RuntimeException (no class loader)
class java.lang.RuntimePermission (no class loader)
class java.lang.SecurityException (no class loader)
class java.lang.Short (no class loader)
class java.lang.StackOverflowError (no class loader)
class java.lang.StackWalker (no class loader)
class java.lang.StackWalker$Option (no class loader)
class java.lang.String (no class loader)
class java.lang.StringBuilder (no class loader)
class java.lang.System (no class loader)
class java.lang.Thread (no class loader)
class java.lang.ThreadLocal (no class loader)
class java.lang.Throwable (no class loader)
class java.lang.UnsupportedOperationException (no class loader)
class java.lang.VerifyError (no class loader)
class java.lang.VirtualMachineError (no class loader)
class java.lang.Void (no class loader)
interface java.lang.annotation.Annotation (no class loader)
interface java.lang.annotation.Retention (no class loader)
interface java.lang.CharSequence (no class loader)
interface java.lang.Cloneable (no class loader)
interface java.lang.Comparable (no class loader)
interface java.lang.Iterable (no class loader)
interface java.lang.module.ModuleFinder (no class loader)
interface java.lang.reflect.InvocationHandler (no class loader)
interface java.lang.Runnable (no class loader)
```

The class loader is `jdk.internal.loader.ClassLoaders$PlatformClassLoader`.

This error does not happen with a "regular" OpenJDK JVM, so it appears it has to do with OpenJ9. Visible classes in a OpenJDK 11 (non-OpenJ9) include for example:

```
array class boolean[] (no class loader)
array class byte[] (no class loader)
array class byte[][] (no class loader)
array class char[] (no class loader)
array class double[] (no class loader)
array class double[] (no class loader)
array class float[] (no class loader)
array class int[] (no class loader)
array class int[][] (no class loader)
array class java.lang.Number[] (no class loader)
array class java.lang.Number[][] (no class loader)
array class java.lang.Object[] (no class loader)
array class java.lang.Object[][] (no class loader)
```

(There are more - ~100 array classes in total).

How come OpenJ9 doesn't include array classes among visible classes?

**Comment by gacholio** [comment]
@provegard Can you provide a simplified test that uses JDI?

I've taken a look at the JVMTI code and it appears to be doing the correct thing, so I'm not sure where the error lies.

**Comment by gacholio** [comment]
I've verified that GetLoadedClasses is returning array classes as expected.

**Comment by gacholio** [comment]
The problem is with `GetClassLoaderClasses` which returns the classes whose loading was initiated by the loader (as opposed to defined by).

**Comment by gacholio** [comment]
As it stands, the code walks the class loader hash table, which does not contain array classes defined by the loader. Note that array classes can only be defined by the loader which initiated the load.

**Comment by provegard** [comment]
I can try to create a small sample to demonstrate the problem. Is that still relevant, given the referenced commit?

**Comment by gacholio** [comment]
No, thanks, I'm pretty sure this is the problem.
