### ISSUE TITLE
ClassCastException: com.ibm.j9ddr.view.dtfj.image.J9DDRCorruptData incompatible with com.ibm.dtfj.java.JavaObject

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9971]
Failure link
------------

From an internal build `ibuild 449730`:
VM_Extended.testDTFJ.Mode351

```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20200528_02(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200621_449730 (JIT enabled, AOT enabled)
OpenJ9   - 4217b39
OMR      - e05af8e
IBM      - 12bab13)
JCL - 20200528_01 based on Oracle jdk8u261-b76
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
[Linux Hammer Compressed Pointers] 80 VM_Extended.testDTFJ.Mode351.1

/bluebird/javatest/HEAD_382595/test/tools/gmake/linux_x86-32/make_3.82/make -f /bluebird/builds/bld_449730/jvmtest/makefile SITE=ottawa PLATFORM=linux_x86-64_cr JAVA_LANG_LEVEL=80 JVM_VERSION=29 JAVA_VERSION=80 BUILD_ID=449730 JOB_ID=647597097 JAVATEST_ROOT='/bluebird/javatest/HEAD_382595/test' JVM_TEST_ROOT='/bluebird/builds/bld_449730/jvmtest' MODULARITY_TEST= VARIATION=Mode351 _testDTFJ

 [junitx] DTFJ TCK loading config from /tmp/bld_449730/testDTFJ/647597097/output/tck/output/tck.properties, specified by tck.config.file system property
   [junitx] java.lang.ClassCastException: com.ibm.j9ddr.view.dtfj.image.J9DDRCorruptData incompatible with com.ibm.dtfj.java.JavaObject
   [junitx] 	at com.ibm.dtfj.tests.junit.JavaFieldTest.setUp(JavaFieldTest.java:60)
   [junitx] 	at junit.framework.TestCase.runBare(TestCase.java:125)
   [junitx] 	at junit.framework.TestResult$1.protect(TestResult.java:106)
   [junitx] 	at junit.framework.TestResult.runProtected(TestResult.java:124)
   [junitx] 	at junit.framework.TestResult.run(TestResult.java:109)
   [junitx] 	at junit.framework.TestCase.run(TestCase.java:118)
   [junitx] 	at junit.framework.TestSuite.runTest(TestSuite.java:208)
   [junitx] 	at junit.framework.TestSuite.run(TestSuite.java:203)
   [junitx] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
   [junitx] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
   [junitx] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:743)
```

**Comment by pshipton** [comment]
@keithc-ca can you take a look pls.

**Comment by keithc-ca** [comment]
It could just be exactly what it says: 'corrupt data'. Is the core file available?

**Comment by keithc-ca** [comment]
I found a core file (hopefully it's the right one).

**Comment by keithc-ca** [comment]
More detail from jdmpview:
```
$ jdmpview -core core.tck.dmp 
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) : 

Source : file:///home/keithc/space/openj9/jdmpview/9971/core.tck.dmp
	*0 : PID: 12158 : JRE 1.8.0 Linux amd64-64 (build 8.0.7.0 - pxa6480sr7-20200528_02(SR7))

> !gccheck
Starting GC Check
Checking HEAP...Jun. 22, 2020 12:14:09 P.M. com.ibm.j9ddr.vm29.events.DefaultEventListener corruptData
WARNING: Error getting next item
com.ibm.j9ddr.CorruptDataException: Allocated object at 0x00000000E005D530 has an invalid size of 0x0000000000000020
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorSegregated_V1.hasNext(GCObjectHeapIteratorSegregated_V1.java:178)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckObjectHeap.check(CheckObjectHeap.java:54)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:469)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:60)
	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:47)
```
The test was not written anticipating corruption: it's not clear what can be done besides improving the test.

**Comment by pshipton** [comment]
The test was passing, but started failing consistently across multiple platforms, which implies that something in the change list broke it.

https://github.com/eclipse/openj9/compare/77c3af9...d2ab44a

**Comment by pshipton** [comment]
VM_Extended.testDTFJ.Mode301 is also failing, starting in the same build.
```
     [echo] Test failure : com.ibm.dtfj.tck.tests.javaruntime.TestJavaClass_getName
     [echo] Test case    : testJavaClass_getName
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError
     [echo]     at com.ibm.dtfj.tck.tests.javaruntime.TestJavaClass_getName.testJavaClass_getName(TestJavaClass_getName.java:88)
     [echo]     at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
     [echo] 
     [echo] Test failure : com.ibm.dtfj.tck.tests.javaruntime.TestJavaMethod_getName
     [echo] Test case    : testGetDeclaredMethods
     [echo] Test error   : java.lang.NullPointerException
     [echo] java.lang.NullPointerException
     [echo]     at com.ibm.dtfj.tck.tests.javaruntime.TestJavaMethod_getName.testGetDeclaredMethods(TestJavaMethod_getName.java:47)
     [echo]     at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
     [echo] 
     [echo] Test failure : com.ibm.dtfj.tck.tests.javaruntime.TestJavaMonitor_ObjectMonitors
     [echo] Test case    : testFindMonitor_0_1_1
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: Couldn't find 0-1-1
     [echo]     at com.ibm.dtfj.tck.tests.javaruntime.TestJavaMonitor_ObjectMonitors.testFindMonitor_0_1_1(TestJavaMonitor_ObjectMonitors.java:493)
     [echo]     at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
     [echo] 
     [echo] Test case    : testGetID_0_1_1
     [echo] Test error   : java.lang.NullPointerException
     [echo] java.lang.NullPointerException
     [echo]     at com.ibm.dtfj.tck.tests.javaruntime.TestJavaMonitor_ObjectMonitors.testGetID_0_1_1(TestJavaMonitor_ObjectMonitors.java:499)
     [echo]     at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)
etc.
```

@dmitripivkine @bragaigor is this related to https://github.com/eclipse/openj9/pull/9373 ? It seems the most likely change to have caused it.

**Comment by bragaigor** [comment]
This is probably due to #9373 and I think I found the issue. DDR code wasn't updated accordingly, I'll be creating a PR shortly.
