### ISSUE TITLE
Running jdmpview on jdk14, the info class command is not visible

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9985]
Java -version output
--------------------

Tested jdk14 0.20.0 release, and also the latest nightly 20200623.

Summary of problem
------------------

Run jdmpview from jdk14 on a core file, the `info class` command is not visible in the help output or when running it (`Unrecognised command: info class`). Open the core with jdmpview from jdk11 or jdk8 and `info class` is available. I don't think the core file matters, I tried cores from jdk11 and jdk14.

**Comment by pshipton** [comment]
@keithc-ca @dmitripivkine

**Comment by keithc-ca** [comment]
Enabling logging shows:
```
java.lang.UnsupportedOperationException: This feature requires ASM7
        at java.base/jdk.internal.org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:181)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:572)
        at java.base/jdk.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:422)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl.scanClassFile(PluginManagerImpl.java:318)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl.examineClassFile(PluginManagerImpl.java:297)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl.lambda$listClassFiles$1(PluginManagerImpl.java:176)
        at com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl$$Lambda$34/0000000000000000.accept(Unknown Source)
[...]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl.listClassFiles(PluginManagerImpl.java:170)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.plugins.impl.PluginManagerImpl.scanForClassFiles(PluginManagerImpl.java:164)
        at openj9.dtfj/com.ibm.java.diagnostics.utils.DTFJContext.refresh(DTFJContext.java:110)
        at openj9.dtfjview/com.ibm.jvm.dtfjview.JdmpviewContextManager.createContext(JdmpviewContextManager.java:63)
```
